### DISCUSSION TITLE
Three different sized thumbnails of the same photo are displayed separately in the gallery

### DISCUSSION THREAD

**Discussion by PolarisGitYHNL** [immich-app/immich#10108] [Q&A]
### The bug

The three different sizes of thumbnails for the same photo are displayed separately in the gallery, namely SYNOPHOTO-THUMB-XL.jpg, SYNOPHOTO-THUMB-L.jpg, and SYNOPHOTO-THUMB-SM.jpg. Its dimensions are 2 MP 1918 x 1280 214.2 KiB, 480 x 320 17.2 KiB, and 360 x 240 10.7 KiB, respectively.
These photos were imported by me from an external library.
Here are the pictures:
<img width="1217" alt="image" src="https://github.com/immich-app/immich/assets/165972224/9d557783-fe5a-44e0-8eb8-8e44238d0527">
The detail page for each image is as follows:
<img width="1911" alt="image" src="https://github.com/immich-app/immich/assets/165972224/df38429f-1a8d-4544-88a3-63b4d0055bf1">
<img width="1911" alt="image" src="https://github.com/immich-app/immich/assets/165972224/ec3a967d-9400-4d20-b417-97fa007eccf2">
<img width="1908" alt="image" src="https://github.com/immich-app/immich/assets/165972224/9b6d09ca-f07d-45a0-b3dd-7423364f60e4">
All photos in the gallery are displayed in these three resolutions.

### The OS that Immich Server is running on

Sinology DSM docker

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume1/docker/Immich/Cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/docker/Immich/Photo
# The location where your database files are stored
DB_DATA_LOCATION=/volume1/docker/Immich/Data

EXTERNAL_PATH=/volume1/homes/admin_polaris/Photos

HF_ENDPOINT="https://hf-mirror.com"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
Image Settings
Manage the quality and resolution of generated images


THUMBNAIL FORMAT
WebP produces smaller files than JPEG, but is slower to encode.
JPEG

THUMBNAIL RESOLUTION
Used when viewing groups of photos (main timeline, album view, etc.). Higher resolutions can preserve more detail but take longer to encode, have larger file sizes, and can reduce app responsiveness.
720P

PREVIEW FORMAT
WebP produces smaller files than JPEG, but is slower to encode.
JPEG

PREVIEW RESOLUTION
Used when viewing a single photo and for machine learning. Higher resolutions can preserve more detail but take longer to encode, have larger file sizes, and can reduce app responsiveness.
1440P

QUALITY
Image quality from 1-100. Higher is better for quality but produces larger files.
80

PREFER WIDE GAMUT
Use Display P3 for thumbnails. This better preserves the vibrance of images with wide colorspaces, but images may appear differently on old devices with an old browser version. sRGB images are kept as sRGB to avoid color shifts.
T

PREFER EMBEDDED PREVIEW
Use embedded previews in RAW photos as the input to image processing when available. This can produce more accurate colors for some images, but the quality of the preview is camera-dependent and the image may have more compression artifacts.
T
```
