### DISCUSSION TITLE
Faces Aren't Detected

### DISCUSSION THREAD

**Discussion by betterthanever2** [immich-app/immich#10269] [Q&A]
### The bug

My photos definitely contain faces. Yes, no faces are detected by Immich. When I go to "Administration>Jobs" and launch recognition job, it goes through it (seemingly), but not faces are detected. I'm not seeing any errors or anything like that. Just nothing turns up.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

--

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ./upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - media_storage:/media
    env_file:
      - .env
    ports:
      - 50846:3001
    depends_on:
      - redis
    restart: always

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ./upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - media_storage:/media
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #  file: hwaccel.ml.yml
    #  service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the -wsl version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - media_storage:/media
    env_file:
      - .env
    restart: always

  redis:
    container_name: redis-immich
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

volumes:
  model-cache:
  media_storage:
    driver_opts:
      type: "cifs"
      o: <credentials>
      device: <path>
```

### Your .env content

```Shell
# all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_PASSWORD=<superpass>
DB_URL=<db_string>
DB_HOSTNAME=<db_host>
DB_PORT=<db_port>
```

### Reproduction steps

```bash
1. Go to Administration
2. Go to Jobs
3. Scroll down to Face Detection, click on "All" or "Missing"
4. Observe the process
5. Go to "Explore" and observe absence of "people" section
```
