### DISCUSSION TITLE
immich_server keep restarting

### DISCUSSION THREAD

**Discussion by WeijieH** [immich-app/immich#10362] [Q&A] [answered]
### The bug

I upgraded from v1.105.1 to v1.106.4 today and the immich_server keeps restarting.
Here is the output from docker-compose ps:
![image](https://github.com/immich-app/immich/assets/16510655/bfe24d56-4151-40f8-bc5c-6faf300a4efd)

### The OS that Immich Server is running on

Unraid v6.12.10

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/user/NAS/Photos:/photos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    # healthcheck:
    #   test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    #   interval: 5m
    #   start_interval: 30s
    #   start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/NAS/immich/upload
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/NAS/immich/database

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgrespw

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. docker-compose up
2. immich_server keeps restarting without giving any logs

below is docker-compose logs output. No log from immich_server is captured!
```

### Relevant log output

```shell
immich_postgres  |
immich_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres  |
immich_postgres  | 2024-06-15 18:39:06.774 UTC [1] LOG:  redirecting log output to logging collector process
immich_postgres  | 2024-06-15 18:39:06.774 UTC [1] HINT:  Future log output will appear in directory "log".
immich_redis     | 1:C 15 Jun 2024 18:39:08.635 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis     | 1:C 15 Jun 2024 18:39:08.635 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis     | 1:C 15 Jun 2024 18:39:08.635 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis     | 1:M 15 Jun 2024 18:39:08.636 * monotonic clock: POSIX clock_gettime
immich_redis     | 1:M 15 Jun 2024 18:39:08.636 * Running mode=standalone, port=6379.
immich_redis     | 1:M 15 Jun 2024 18:39:08.636 # Server initialized
immich_redis     | 1:M 15 Jun 2024 18:39:08.636 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis     | 1:M 15 Jun 2024 18:39:08.637 * Ready to accept connections
immich_machine_learning  | [06/15/24 18:39:07] INFO     Starting gunicorn 22.0.0
immich_machine_learning  | [06/15/24 18:39:07] INFO     Listening at: http://[::]:3003 (9)
immich_machine_learning  | [06/15/24 18:39:07] INFO     Using worker: app.config.CustomUvicornWorker
immich_machine_learning  | [06/15/24 18:39:07] INFO     Booting worker with pid: 10
immich_machine_learning  | [06/15/24 18:39:12] INFO     Started server process [10]
immich_machine_learning  | [06/15/24 18:39:12] INFO     Waiting for application startup.
immich_machine_learning  | [06/15/24 18:39:12] INFO     Created in-memory cache with unloading after 300s
immich_machine_learning  |                              of inactivity.
immich_machine_learning  | [06/15/24 18:39:12] INFO     Initialized request thread pool with 8 threads.
immich_machine_learning  | [06/15/24 18:39:12] INFO     Application startup complete.
```

### Additional information

v1.105.1 works correctly on my unraid system
