### DISCUSSION TITLE
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc

### DISCUSSION THREAD

**Discussion by muammar** [immich-app/immich#10408] [Q&A]
### The bug

Thank you very much for this project that has helped me to get rid of Google Photos. Everything has been solid except for the error noted in the title. 

From time to time, I am required to **restart** the`[immich_machine_learning]` container to get the search option to run again. My NVIDIA GPU is working perfectly fine with other services on my server, but immich is the only one having issues with loading the ML model. 

Attached you will find the log files of the `immich_machine_learning` container. Let me know if this is helpful. 

Best, 

[_immich_machine_learning_logs.txt](https://github.com/user-attachments/files/15859136/_immich_machine_learning_logs.txt)


### The OS that Immich Server is running on

Debian Testing 

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # command: ['start.sh', 'immich'] Removed v1.106.1
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  # Removed from v1.106.1
  # immich-microservices:
  #   container_name: immich_microservices
  #   image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
  #   #   file: hwaccel.transcoding.yml
  #   #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
  #   command: ['start.sh', 'microservices']
  #   volumes:
  #     - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #     - /etc/localtime:/etc/localtime:ro
  #   env_file:
  #     - stack.env
  #   depends_on:
  #     - redis
  #     - database
  #   restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  # pgdata:
  model-cache:
```
```


### Your .env content

```Shell
UPLOAD_LOCATION=/path/to/Immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/path/to/immich/data
```


### Reproduction steps

```bash
1.Use search function. 
2.Expect results from search but the system returns an error.
```


### Relevant log output

```shell
RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:123 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:116 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             100: no CUDA-capable device is detected ;          
                             GPU=-451060998 ; hostname=5d07834094fa ;           
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;         
                             expr=cudaSetDevice(info_.device_id);               
                                                                                
                                                                                
                                                                                
                             The above exception was the direct cause of the    
                             following exception:                               
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:151 in predict             │
                             │                                                 │
                             │   148 │   │   inputs = text                     │
                             │   149 │   else:                                 │
                             │   150 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 151 │   response = await run_inference(inputs │
                             │   152 │   return ORJSONResponse(response)       │
                             │   153                                           │
                             │   154                                           │
                             │                                                 │
                             │ /usr/src/app/main.py:174 in run_inference       │
                             │                                                 │
                             │   171 │   │   response[entry["task"]] = output  │
                             │   172 │                                         │
                             │   173 │   without_deps, with_deps = entries     │
                             │ ❱ 174 │   await asyncio.gather(*[_run_inference │
                             │   175 │   if with_deps:                         │
                             │   176 │   │   await asyncio.gather(*[_run_infer │
                             │   177 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /usr/src/app/main.py:168 in _run_inference      │
                             │                                                 │
                             │   165 │   │   │   except KeyError:              │
                             │   166 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   167 │   │   │   │   raise HTTPException(400,  │
                             │ ❱ 168 │   │   model = await load(model)         │
                             │   169 │   │   output = await run(model.predict, │
                             │   170 │   │   outputs[model.identity] = output  │
                             │   171 │   │   response[entry["task"]] = output  │
                             │                                                 │
                             │ /usr/src/app/main.py:200 in load                │
                             │                                                 │
                             │   197 │   │   return model                      │
                             │   198 │                                         │
                             │   199 │   try:                                  │
                             │ ❱ 200 │   │   await run(_load, model)           │
                             │   201 │   │   return model                      │
                             │   202 │   except (OSError, InvalidProtobuf, Bad │
                             │   203 │   │   log.warning(                      │
                             │                                                 │
                             │ /usr/src/app/main.py:187 in run                 │
                             │                                                 │
                             │   184 │   if thread_pool is None:               │
                             │   185 │   │   return func(*args, **kwargs)      │
                             │   186 │   partial_func = partial(func, *args, * │
                             │ ❱ 187 │   return await asyncio.get_running_loop │
                             │   188                                           │
                             │   189                                           │
                             │   190 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:196 in _load               │
                             │                                                 │
                             │   193 │                                         │
                             │   194 │   def _load(model: InferenceModel) -> I │
                             │   195 │   │   with lock:                        │
                             │ ❱ 196 │   │   │   model.load()                  │
                             │   197 │   │   return model                      │
                             │   198 │                                         │
                             │   199 │   try:                                  │
                             │                                                 │
                             │ /usr/src/app/models/base.py:54 in load          │
                             │                                                 │
                             │    51 │   │                                     │
                             │    52 │   │   self.download()                   │
                             │    53 │   │   log.info(f"Loading {self.model_ty │
                             │       to memory")                               │
                             │ ❱  54 │   │   self.session = self._load()       │
                             │    55 │   │   self.loaded = True                │
                             │    56 │                                         │
                             │    57 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/app/models/clip/textual.py:29 in _load │
                             │                                                 │
                             │   26 │   │   self.tokenizer = self._load_tokeni │
                             │   27 │   │   log.debug(f"Loaded tokenizer for C │
                             │   28 │   │                                      │
                             │ ❱ 29 │   │   return super()._load()             │
                             │   30 │                                          │
                             │   31 │   @abstractmethod                        │
                             │   32 │   def _load_tokenizer(self) -> Tokenizer │
                             │                                                 │
                             │ /usr/src/app/models/base.py:80 in _load         │
                             │                                                 │
                             │    77 │   │   )                                 │
                             │    78 │                                         │
                             │    79 │   def _load(self) -> ModelSession:      │
                             │ ❱  80 │   │   return self._make_session(self.mo │
                             │    81 │                                         │
                             │    82 │   def clear_cache(self) -> None:        │
                             │    83 │   │   if not self.cache_dir.exists():   │
                             │                                                 │
                             │ /usr/src/app/models/base.py:119 in              │
                             │ _make_session                                   │
                             │                                                 │
                             │   116 │   │   │   case ".armnn":                │
                             │   117 │   │   │   │   session = AnnSession(mode │
                             │   118 │   │   │   case ".onnx":                 │
                             │ ❱ 119 │   │   │   │   session = ort.InferenceSe │
                             │   120 │   │   │   │   │   model_path.as_posix() │
                             │   121 │   │   │   │   │   sess_options=self.ses │
                             │   122 │   │   │   │   │   providers=self.provid │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:43 │
                             │ 2 in __init__                                   │
                             │                                                 │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │    431 │   │   │   │   except Exception as fall │
                             │ ❱  432 │   │   │   │   │   raise fallback_error │
                             │    433 │   │   │   # Fallback is disabled. Rais │
                             │    434 │   │   │   raise e                      │
                             │    435                                          │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:42 │
                             │ 7 in __init__                                   │
                             │                                                 │
                             │    424 │   │   │   │   │   print(f"EP Error {e} │
                             │    425 │   │   │   │   │   print(f"Falling back │
                             │    426 │   │   │   │   │   print("************* │
                             │ ❱  427 │   │   │   │   │   self._create_inferen │
                             │    428 │   │   │   │   │   # Fallback only once │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:48 │
                             │ 3 in _create_inference_session                  │
                             │                                                 │
                             │    480 │   │   │   disabled_optimizers = set(di │
                             │    481 │   │                                    │
                             │    482 │   │   # initialize the C++ InferenceSe │
                             │ ❱  483 │   │   sess.initialize_session(provider │
                             │    484 │   │                                    │
                             │    485 │   │   self._sess = sess                │
                             │    486 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:123 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:116 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             100: no CUDA-capable device is detected ;          
                             GPU=-451060998 ; hostname=5d07834094fa ;           
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;         
                             expr=cudaSetDevice(info_.device_id);
```


### Additional information

_No response_

**Comment by mertalev** [comment]
What GPU do you have? We require compute capability 5.2 or higher, so it won’t work if it’s below that.

**Reply by muammar** [reply]
I have an NVIDIA GeForce RTX 3060.

```
muammar@pneuma ~
  % nvidia-smi --query-gpu=compute_cap --format=csv                                                                                                                                                            !10247
compute_cap
8.6
```

**Reply by mertalev** [reply]
Hmm, I'm not sure what the issue is in that case. CUDA works for other users and I can confirm it works for me, so I still think this is external to immich. I would try updating the driver and installing the latest nvidia container toolkit.

**Reply by muammar** [reply]
It works for some time and then I start getting the error I posted above. For instance, as of the writing of my reply, it is working. 

CUDA is updated to the latest version, so I don't think it is external to immich. Other docker containers I use that also use my GPU works perfectly fine. 

```
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
```

**Reply by muammar** [reply]
I forgot to ask, how should I update the latest "nvidia container toolkit"? I don't see that: 

```
muammar@pneuma ~
  % docker ps |grep immich                                                                                                                                                                                     !10252
5d07834094fa   ghcr.io/immich-app/immich-machine-learning:release-cuda      "tini -- ./start.sh"     2 days ago     Up 3 hours (healthy)                                                                                                                                                                                                                       immich_machine_learning
38a019baa6c6   ghcr.io/immich-app/immich-server:release                     "tini -- /bin/bash s…"   2 days ago     Up 41 hours (healthy)   0.0.0.0:2283->3001/tcp, :::2283->3001/tcp                                                                                                                                                                          immich_server
562dd5c80f36   registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0   "docker-entrypoint.s…"   6 weeks ago    Up 41 hours             5432/tcp                                                                                                                                                                                                           immich_postgres
a6d5e0d0c3a7   registry.hub.docker.com/library/redis:6.2-alpine             "docker-entrypoint.s…"   6 weeks ago    Up 41 hours             6379/tcp                                                                                                                                                                                                           immich_redis
```

My `/immich-machine-learning:release-cuda` was updated two days ago. Is that what you are referring to?

**Reply by mertalev** [reply]
Can you confirm if it still happens when immich is the only container with access to the GPU?

**Reply by muammar** [reply]
> Can you confirm if it still happens when immich is the only container with access to the GPU?

That's a good one. I would have to test that hypothesis.

**Reply by mertalev** [reply]
I was referring to [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

**Reply by muammar** [reply]
> I was referring to [this](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html).

```
muammar@pneuma ~
  % aptitude show nvidia-container-toolkit                                                                                                                                                                     !10253
Package: nvidia-container-toolkit
Version: 1.13.5-1
New: yes
State: installed
Automatically installed: yes
Priority: optional
Section: utils
Maintainer: NVIDIA CORPORATION <cudatools@nvidia.com>
Architecture: amd64
Uncompressed Size: 2,429 k
Depends: nvidia-container-toolkit-base (= 1.13.5-1), libnvidia-container-tools (>= 1.13.5-1), libnvidia-container-tools (< 2.0.0), libseccomp2
Breaks: nvidia-container-runtime (<= 3.5.0-1), nvidia-container-runtime-hook
Replaces: nvidia-container-runtime (<= 3.5.0-1), nvidia-container-runtime-hook
Description: NVIDIA container runtime hook
 Provides a OCI hook to enable GPU support in containers.
Homepage: https://github.com/NVIDIA/nvidia-container-runtime/wiki
```

It was not updated. I went back to the NVIDIA's website to change my sources and now it looks updated: 

```
muammar@pneuma ~
  % aptitude show nvidia-container-toolkit                                                                                                                                                                     !10259
Package: nvidia-container-toolkit
Version: 1.15.0-1
New: yes
State: installed
Automatically installed: yes
Priority: optional
Section: utils
Maintainer: NVIDIA CORPORATION <cudatools@nvidia.com>
Architecture: amd64
Uncompressed Size: 2,956 k
Depends: nvidia-container-toolkit-base (= 1.15.0-1), libnvidia-container-tools (>= 1.15.0-1), libnvidia-container-tools (< 2.0.0)
Breaks: nvidia-container-runtime (<= 3.5.0-1), nvidia-container-runtime-hook
Replaces: nvidia-container-runtime (<= 3.5.0-1), nvidia-container-runtime-hook
Description: NVIDIA Container toolkit
 Provides tools and utilities to enable GPU support in containers.
Homepage: https://github.com/NVIDIA/nvidia-container-toolkit
```

I will reboot my server, and give this a try. Thanks for your replies, this hopefully solves the issue 🤞

**Reply by mertalev** [reply]
Fingers crossed!

**Reply by muammar** [reply]
It's been two days and the `immich_machine_learning` is still working. I will give it the week, and if it does not break I will mark your suggestion as the answer. Thanks.

**Comment by muammar** [comment]
Problem persists: 

```
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             100: no CUDA-capable device is detected ;          
                             GPU=1081075431 ; hostname=0d269897dbb8 ;           
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;         
                             expr=cudaSetDevice(info_.device_id);   
```

Only restarting the container fixes it for some time. It might be the process for loading/unloading the model.

**Reply by mertalev** [reply]
[This](https://github.com/immich-app/immich/discussions/10555) discussion might help.

**Comment by JMalland** [comment]
> ```
>                              RuntimeError:                                      
>                              /onnxruntime_src/onnxruntime/core/providers/cuda/cu
>                              da_call.cc:123 std::conditional_t<THRW, void,      
>                              onnxruntime::common::Status>                       
>                              onnxruntime::CudaCall(ERRTYPE, const char*, const  
>                              char*, ERRTYPE, const char*, const char*, int)     
>                              [with ERRTYPE = cudaError; bool THRW = true;       
>                              std::conditional_t<THRW, void,                     
>                              onnxruntime::common::Status> = void]               
>                              /onnxruntime_src/onnxruntime/core/providers/cuda/cu
>                              da_call.cc:116 std::conditional_t<THRW, void,      
>                              onnxruntime::common::Status>                       
>                              onnxruntime::CudaCall(ERRTYPE, const char*, const  
>                              char*, ERRTYPE, const char*, const char*, int)     
>                              [with ERRTYPE = cudaError; bool THRW = true;       
>                              std::conditional_t<THRW, void,                     
>                              onnxruntime::common::Status> = void] CUDA failure  
>                              100: no CUDA-capable device is detected ;          
>                              GPU=-451060998 ; hostname=5d07834094fa ;           
>                              file=/onnxruntime_src/onnxruntime/core/providers/cu
>                              da/cuda_execution_provider.cc ; line=280 ;         
>                              expr=cudaSetDevice(info_.device_id);
> ```

I have been having this exact error as well.

Today, I finally got my GPU working on my Ubuntu 24.04 server. And, now that I'm running (or trying to) Immich Machine Learning, I have no idea why I'm getting this.

This is my output of nvidia-smi:
```
 root@immich-machine-learning:/home/jacob# nvidia-smi
Sun Oct  6 18:54:26 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID P40-1B4                   Off | 00000000:01:00.0 Off |                  N/A |
| N/A   N/A    P8              N/A /  N/A |      0MiB /  1024MiB |      0%   Prohibited |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

As you can see, I meet the 535 minimum driver version, and CUDA 12.2. I've uninstalled everything NVIDIA and reinstalled twice now, and yet it persists. 

The only thing I can think of, is that, on another Windows server of mine running a vGPU, I had to install a NVIDIA license from the license server I'm running. Though I've tried some googling, and can't seem to find anything about that for Linux.

I'd appreciate any suggestions or input anyone has to offer.

**Reply by mertalev** [reply]
The "no CUDA-capable device is detected" error can be caused by [this](https://github.com/NVIDIA/nvidia-container-toolkit/issues/48) issue. The Docker workaround for that might help.

**Reply by mertalev** [reply]
Also, you mentioned that you installed everything NVIDIA, but make sure that [nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) in particular is up-to-date.

**Reply by JMalland** [reply]
I've managed to get `docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi` to work properly, by changing `no-cgroups` to `false` in `/etc/nvidia-container-runtime/config.toml`. 

Now, when I start the Immich Machine Learning server, I get:
```
RuntimeError:
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:123 std::conditional_t<THRW, void,
                             onnxruntime::common::Status>
                             onnxruntime::CudaCall(ERRTYPE, const char*, const
                             char*, ERRTYPE, const char*, const char*, int)
                             [with ERRTYPE = cudaError; bool THRW = true;
                             std::conditional_t<THRW, void, common::Status> =
                             void]
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:116 std::conditional_t<THRW, void,
                             onnxruntime::common::Status>
                             onnxruntime::CudaCall(ERRTYPE, const char*, const
                             char*, ERRTYPE, const char*, const char*, int)
                             [with ERRTYPE = cudaError; bool THRW = true;
                             std::conditional_t<THRW, void, common::Status> =
                             void] CUDA failure 100: no CUDA-capable device is
                             detected ; GPU=31331 ; hostname=68bf34c56e80 ;
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;
                             expr=cudaSetDevice(info_.device_id);
```

I'm honestly not sure whether this is better or not.

Is there any way I can directly specify the device to use when the server is started? I found [this](https://forums.developer.nvidia.com/t/nvida-container-toolkit-failed-to-initialize-nvml-unknown-error/286219/2) post, and the docker run command works successfully even with `no-cgroups=true`. 

**EDIT:**
For the sake of explaining my workflow here, I'll include this. 
I tried adding the devices referenced above to `hwaccel.ml.yml` when `no-cgroups` is `true`, and had no luck.

```
cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                #- compute
                #- video

    # The devices below only caused more "CUDA failure 801"
    #devices:
    #  - /dev/nvidia0:/dev/nvidia0
    #  - /dev/nvidiactl:/dev/nvidiactl
    #  - /dev/nvidia-uvm:/dev/nvidia-uvm
    #  - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
```
