### DISCUSSION TITLE
Error in log

### DISCUSSION THREAD

**Discussion by mxm199** [immich-app/immich#10459] [Q&A]
### The bug

The error occurs when processing the library
![image](https://github.com/immich-app/immich/assets/133875469/1f3c77ff-09ea-437a-8794-50666d0dae8f)
![image](https://github.com/immich-app/immich/assets/133875469/2d32c6c6-66c5-419c-b91c-b776c288a9eb)

### The OS that Immich Server is running on

Windows 10 / Docker Desktop 4.31.1 (153621)

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

1.106.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/mnt/media/dcim:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 172.16.0.37

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 172.16.0.38

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      my_network:
        ipv4_address: 172.16.0.39

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
    networks:
      my_network:
        ipv4_address: 172.16.0.40

volumes:
  model-cache:
  immich-database:
  redis:

networks:
  my_network:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=d:/immich-library
DB_DATA_LOCATION=immich-database
EXTERNAL_PATH=d:/dcim
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Presumably after completing the SMART SEARCH / FACE DETECTION / FACIAL RECOGNITION tasks

Otherwise, everything works normally. The library is scanned, detects faces, and SMART SEARCH works
```
