### DISCUSSION TITLE
duplicate key value after restoring icloud photos

### DISCUSSION THREAD

**Discussion by tezlm** [immich-app/immich#10509] [Q&A]
### The bug

Restoring photos from an icloud backup then trying to backup the photos with immich causes all the photos to fail to backup.

### The OS that Immich Server is running on

nixos

### Version of Immich Server

1.106.3 build.160

### Version of Immich Mobile App

1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  postgres:
    container_name: postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg16-v0.2.1
    user: "1000"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      start_period: 30s
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ./immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /media
        target: /data/media
        read_only: true
        bind:
          propagation: slave
    environment:
      - DB_URL=postgres://immich:passwordredacted@postgres/immich?sslmode=disable
    depends_on:
      - postgres
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always
```

### Your .env content

(env provided in compose.yaml)

### Reproduction steps

```bash
1. backup photos with icloud and immich
2. reset phone or get a new one
3. restore photos from icloud
4. open immich
```

### Relevant log output

```shell
[31m[Nest] 17  - [39m06/17/2024, 12:32:11 AM [31m  ERROR[39m [33m[Api:QueryFailedError: duplicate key value violates unique constraint "UQ_16294b83fa8c0149719a1f631ef"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async SubjectExecutor.executeInsertOperations (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
    at async SubjectExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
    at async EntityPersistExecutor.execute (/usr/src/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:140:21)
    at async AssetMediaService.create (/usr/src/app/dist/services/asset-media.service.js:290:23)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:131:27)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)~7y1i0rro][39m [31mFailed to upload asset[39m
```
