### DISCUSSION TITLE
"Error loading image" - loads okay when you click 'Refresh Thumbnails'

### DISCUSSION THREAD

**Discussion by sharmalakshay** [immich-app/immich#10570] [Q&A]
### The bug

A lot of images show as blur and when you click to open, you get the message "Error loading image".
![image](https://github.com/immich-app/immich/assets/33317879/4236df21-005c-4272-9807-fba7c4a1452e)
![image](https://github.com/immich-app/immich/assets/33317879/07501c60-f866-4914-ba76-267bb8790bca)
But if then you click 'Refresh Thumbnails', close the image and re-open, it opens fine!
![image](https://github.com/immich-app/immich/assets/33317879/a081cf75-2473-4eec-a271-03b3b01ff5c2)

Also can't load the thumnails for the People n Places!
![image](https://github.com/immich-app/immich/assets/33317879/c48fafe7-0b03-464f-989e-2c0e44687d77)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always



  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres

    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich_disk/all1
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
THUMB_LOCATION=/immich_thumbs
```

### Reproduction steps

```bash
1. Open Immich web
2. Scroll down a little to see old images (2-3 weeks)
3. Lots of images with blur
```

### Additional information

The disk I use for backups is an HDD and I have recently chosen to store the thumnails on the sd card with hopes of better load-times when searching for images of people or things.
I have deleted the old thumbnails and have re-created them on the sd card.
This issue existed BEFORE I did all that but it wasn't that bad. Now more than half of the images show up like that.
Also, I use both an iPhone and an Android to upload.
