### DISCUSSION TITLE
Server cannot connect to redis after backup&restore

### DISCUSSION THREAD

**Discussion by Qhilm** [immich-app/immich#10656] [Q&A]
I had the "unhealthy" issue, hence I did a backup&restore to enable checksum on postgres. The restore seemed to work fine, but since then, the server cannot connect to redis somehow, I don't exactly understand how that's possible and `immich_postgres` continues to complain it's unhealthy, even though I do see "Data page checksums are enabled" in the container logs.

This is the log of the restore, I don't see any big problem, except the error at the beginning but it seemed cosmetic:

<details>
  <summary>restore logs</summary>

  ```
  root@synology:~# gunzip < "//volume1/Photos/dump.sql.gz" \
  > | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
  > | docker exec -i immich_postgres psql --username=postgres
  SET
  SET
  SET
  DROP DATABASE
  ERROR:  current user cannot be dropped
  ERROR:  role "postgres" already exists
  ALTER ROLE
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  UPDATE 1
  DROP DATABASE
  CREATE DATABASE
  ALTER DATABASE
  You are now connected to database "template1" as user "postgres".
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  COMMENT
  ALTER DATABASE
  You are now connected to database "template1" as user "postgres".
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  REVOKE
  GRANT
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  CREATE DATABASE
  ALTER DATABASE
  You are now connected to database "immich" as user "postgres".
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  ALTER DATABASE
  You are now connected to database "immich" as user "postgres".
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  CREATE SCHEMA
  ALTER SCHEMA
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE EXTENSION
  COMMENT
  CREATE FUNCTION
  ALTER FUNCTION
  CREATE FUNCTION
  ALTER FUNCTION
  SET
  SET
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  COMMENT
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE SEQUENCE
  ALTER TABLE
  ALTER SEQUENCE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE SEQUENCE
  ALTER TABLE
  ALTER SEQUENCE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE SEQUENCE
  ALTER TABLE
  ALTER SEQUENCE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  COMMENT
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  CREATE TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  COPY 0
  COPY 667
  COPY 43629
  COPY 8
  COPY 1
  COPY 43757
  COPY 58585
  COPY 809
  COPY 58609
  COPY 218
  COPY 58608
  COPY 202330
  COPY 0
  COPY 0
  COPY 0
  COPY 152
  COPY 53
  COPY 2
  COPY 0
  COPY 47
  COPY 7
  COPY 3
  COPY 4184
  COPY 23651
  COPY 0
  COPY 4
  COPY 0
  COPY 0
  COPY 2
  COPY 0
  COPY 3
   setval 
  --------
      218
  (1 row)
  
   setval 
  --------
      152
  (1 row)
  
   setval 
  --------
       44
  (1 row)
  
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  CREATE INDEX
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  ALTER TABLE
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  DROP DATABASE
  CREATE DATABASE
  ALTER DATABASE
  You are now connected to database "postgres" as user "postgres".
  SET
  SET
  SET
  SET
  SET
       set_config     
  --------------------
   public, pg_catalog
  (1 row)
  
  SET
  SET
  SET
  SET
  COMMENT
  root@synology:~# 
  ```

</details>

this is my docker compose yaml (It's a stack in Portainer actually):

<details>
  <summary>Docker Compose</summary>

  ```yaml
  #
  # WARNING: Make sure to use the docker-compose.yml of the current release:
  #
  # https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
  #
  # The compose file on main may not be compatible with the latest release.
  #
  
  name: immich
  
  services:
    immich-server:
      user: '1037:100'
      container_name: immich_server
      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      # command: ['start.sh', 'immich']
      volumes:
        - ${UPLOAD_LOCATION}:/usr/src/app/upload
        - /etc/localtime:/etc/localtime:ro
      env_file:
        - stack.env
      ports:
        - 2283:3001
      depends_on:
        - redis
        - database
      restart: always
      security_opt:
        # Prevent escalation of privileges after the container is started
        - no-new-privileges:true
      cap_drop:
        # Prevent access to raw network traffic
        - NET_RAW
  
    immich-machine-learning:
      user: '1037:100'
      container_name: immich_machine_learning
      # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
      # Example tag: ${IMMICH_VERSION:-release}-cuda
      image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
      # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      #   file: hwaccel.ml.yml
      #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
      volumes:
      #  - model-cache:/cache
        - ${MACHINE_LEARNING_CACHE_LOCATION}:/cache
        - ${MACHINE_LEARNING_DOTCACHE_LOCATION}:/.cache
        - ${MACHINE_LEARNING_DOTCONFIG_LOCATION}:/.config
      env_file:
        - stack.env
      restart: always
      security_opt:
        # Prevent escalation of privileges after the container is started
        - no-new-privileges:true
      cap_drop:
        # Prevent access to raw network traffic
        - NET_RAW
  
    redis:
      user: '1037:100'
      container_name: immich_redis
      image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
  #   image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
      healthcheck:
        test: redis-cli ping || exit 1
      restart: always
      volumes:
        - ${REDIS_DATA_LOCATION}:/data
      security_opt:
        # Prevent escalation of privileges after the container is started
        - no-new-privileges:true
      cap_drop:
        # Prevent access to raw network traffic
        - NET_RAW
  
    database:
      user: '1037:100'
      container_name: immich_postgres
      image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    # image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
        POSTGRES_INITDB_ARGS: '--data-checksums'
      volumes:
      # - pgdata:/var/lib/postgresql/data
        - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      healthcheck:
        test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only   --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" =   '0' ] || exit 1
        interval: 5m
        start_interval: 30s
        start_period: 5m
      command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c",   "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
      restart: always
  
  ```
</details>

Any idea what I could have forgotten? It had just upgrade from 103 to v106 before, it appeared to work just fine, although I did not check every single feature.
