### DISCUSSION TITLE
`immich_postgres` unhealthy but zero checksum errors

### DISCUSSION THREAD

**Discussion by Qhilm** [immich-app/immich#10661] [Q&A] [answered]
As [documented](https://immich.app/docs/FAQ/#how-can-i-verify-the-integrity-of-my-database), I verified checksums are enabled:

```bash
root@synology:/volume1/Photos# docker exec -it immich_postgres psql --dbname=immich --username=postgres --command="show data_checksums"
 data_checksums 
----------------
 on
(1 row)
root@synology:/volume1/Photos# 
```

and that there is no checksum errors:

```bash
root@synology:/volume1/Photos# docker exec -it immich_postgres psql --dbname=immich --username=postgres --command="SELECT datname, checksum_failures, checksum_last_failure FROM pg_stat_database WHERE datname IS NOT NULL"
  datname  | checksum_failures | checksum_last_failure 
-----------+-------------------+-----------------------
 template0 |                 0 | 
 template1 |                 0 | 
 immich    |                 0 | 
 postgres  |                 0 | 
(4 rows)

root@synology:/volume1/Photos# 
```

Any idea what else I could check?

immich_postgres yaml:

```yaml
  database:
    user: '1037:100'
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```
