### DISCUSSION TITLE
Thumbnails only sometimes being generated

### DISCUSSION THREAD

**Discussion by apixandru** [immich-app/immich#10714] [Q&A]
### The bug

Some of my images are not getting uploaded properly, it's only displaying the placeholder.
I can fix it by clicking the image -> more -> generate thumbnails but even that doesn't always fix it, it's more like 1/5 chance that i get a new thumbail

There is no error in the logs and triggering the refresh thumnails job does not refresh everything

![missing_images](https://github.com/immich-app/immich/assets/4395571/0ad52095-e2d8-44ef-8789-c0026e66989e)

### The OS that Immich Server is running on

openmediavault

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.2"

services:

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
#    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME}
      DB_HOSTNAME: ${IMMICH_DB_HOSTNAME}
      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}
    ports:
      - 2283:3001
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    networks:
      - immich_network
      - nginx_link

#  immich-microservices:
#    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
#    command: [ "start.sh", "microservices" ]
#    volumes:
#      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
#      DB_USERNAME: ${IMMICH_DB_USERNAME}
#      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME}
#      DB_HOSTNAME: ${IMMICH_DB_HOSTNAME}
#      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}
#    depends_on:
#      - immich-redis
#      - immich-database
#    restart: always
#    networks:
#      - immich_network

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - ${IMMICH_MODELCACHE_LOCATION}:/cache
    restart: always
    networks:
      - immich_network

  immich-redis:
    image: redis:${IMMICH_REDIS_VERSION}
    restart: always
    networks:
      - immich_network

  immich-database:
    image: tensorchord/pgvecto-rs:${IMMICH_PGVECTO_VERSION}
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_PGDATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_network

networks:
  nginx_link:
    name: nginx_link
    external: true
  immich_network:
    name: immich_network
```

### Your .env content

```Shell
IMMICH_VERSION=v1.106.4
IMMICH_REDIS_VERSION=6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
IMMICH_PGVECTO_VERSION=pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

IMMICH_UPLOAD_LOCATION=[...]
IMMICH_PGDATA_LOCATION=[...]
IMMICH_MODELCACHE_LOCATION=[...]

IMMICH_DB_PASSWORD=[...]
IMMICH_DB_HOSTNAME=immich-database
IMMICH_DB_USERNAME=[...]
IMMICH_DB_DATABASE_NAME=immich
IMMICH_REDIS_HOSTNAME=immich-redis
```

### Reproduction steps

```bash
1. use app as normal
2. app reports successful sync but the webapp is missing the images
3. trigger regenerate thumbnails about 5 times and the metadata will appear
...
```
