### DISCUSSION TITLE
Force reupload asset

### DISCUSSION THREAD

**Discussion by apixandru** [immich-app/immich#10713] [Feature Request]
### The bug

I have an image that fails to display with the error "The source image cannot be decoded."
Neither the app nor the webapp has an option to reupload that image, the only thing close to this is "Replace with manual upload" which is less than optimal.

Can we get a "force reupload" option?

### The OS that Immich Server is running on

openmediavault

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.2"

services:

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
#    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME}
      DB_HOSTNAME: ${IMMICH_DB_HOSTNAME}
      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}
    ports:
      - 2283:3001
    depends_on:
      - immich-redis
      - immich-database
    restart: always
    networks:
      - immich_network
      - nginx_link

#  immich-microservices:
#    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
#    command: [ "start.sh", "microservices" ]
#    volumes:
#      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
#      - /etc/localtime:/etc/localtime:ro
#    environment:
#      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
#      DB_USERNAME: ${IMMICH_DB_USERNAME}
#      DB_DATABASE_NAME: ${IMMICH_DB_DATABASE_NAME}
#      DB_HOSTNAME: ${IMMICH_DB_HOSTNAME}
#      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}
#    depends_on:
#      - immich-redis
#      - immich-database
#    restart: always
#    networks:
#      - immich_network

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    volumes:
      - ${IMMICH_MODELCACHE_LOCATION}:/cache
    restart: always
    networks:
      - immich_network

  immich-redis:
    image: redis:${IMMICH_REDIS_VERSION}
    restart: always
    networks:
      - immich_network

  immich-database:
    image: tensorchord/pgvecto-rs:${IMMICH_PGVECTO_VERSION}
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_PGDATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_network

networks:
  nginx_link:
    name: nginx_link
    external: true
  immich_network:
    name: immich_network
```

### Your .env content

```Shell
IMMICH_VERSION=v1.106.4
IMMICH_REDIS_VERSION=6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
IMMICH_PGVECTO_VERSION=pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

IMMICH_UPLOAD_LOCATION=[...]
IMMICH_PGDATA_LOCATION=[...]
IMMICH_MODELCACHE_LOCATION=[...]

IMMICH_DB_PASSWORD=[...]
IMMICH_DB_HOSTNAME=immich-database
IMMICH_DB_USERNAME=[...]
IMMICH_DB_DATABASE_NAME=immich
IMMICH_REDIS_HOSTNAME=immich-redis
```

### Reproduction steps

```bash
1. get a corrupt image
2. try to fix it
3. ???
...
```

### Relevant log output

```shell
DOMException: The source image cannot be decoded.
(anonymous) @ checkbox.D91GCG_G.js:6
await in (anonymous) (async)
Q @ scheduler.J2j3c2Oj.js:1
(anonymous) @ index._RfW-mJx.js:4
ht @ scheduler.J2j3c2Oj.js:1
Promise.then (async)
_t @ scheduler.J2j3c2Oj.js:1
ht @ index._RfW-mJx.js:4
(anonymous) @ index._RfW-mJx.js:4
IntersectionObserver.rootMargin @ thumbnail.B1DQEw6N.js:3
```
