### DISCUSSION TITLE
Upgrade from 1.100.0 to 1.106.4 images are lost and cannot be synced again.

### DISCUSSION THREAD

**Discussion by dustsucker** [immich-app/immich#10749] [Q&A]
### The bug

So I upgraded my Kubernetes deployment from v 1.100.0 to 1.106.4 and now all images are no longer available, only the preview images. I tried resyncing, but my app shows that all images are synced, and I'm not aware of a way to force resync them. 
I tried reinstalling the Android app version : 1.106.3 build.143
Thereafter, I deleted all images from the server to try and resync with no images on the server.
But that did not work, it still displays all images are synced. 

### The OS that Immich Server is running on

Kuberntes K3S k3s version v1.29.4+k3s1

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

1.1006.3 build.143

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# Diese Einträge sind zwischen allen Immich-Komponenten geteilt
env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'

image:
  tag: v1.106.4

immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library-pvc
  configuration: {}

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: secret #changed
        database: secret #changed
        password: secret #changed
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-dns"
        traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
      hosts:
        - host: immich.*.de #changed 
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.*.de #changed 
          secretName: tls-immich-ingress-dns

microservices:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: emptyDir
      accessMode: ReadWriteMany
```

### Your .env content

```Shell
Contained in docker-compose(values.yaml)
```

### Reproduction steps

```bash
Upgrade from 1.100.0 to 1.106.4 I guess, but I don't really know why this happens.
```
