### DISCUSSION TITLE
Mobile app now shows all images in main Photos view

### DISCUSSION THREAD

**Discussion by eldridgea** [immich-app/immich#10761] [Feature Request]
### The bug

In the new v1.107.0, support was added for other directories without enabling auto-upload (which is a new feature I love by the way!). However It now shows all photos in the main photo view. This includes a lot of things like Whatsapp images, random downloads, etc. instead of just the camera reel. This may be working as intended, but expected behavior for me at least was being able to access those photos from the Library tab, but not see them by default in the main Photos view (as they're mostly not photos).

(Overall, love this project and have been amazed by the progress!)

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.107.0

### Version of Immich Mobile App

v1.107.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
I use a Helm chart but here's the values file:


image:
  tag: v1.107.0
immich:
  persistence:
    library:
      existingClaim: immich-data
machine-learning:
  enabled: true
  env:
    TRANSFORMERS_CACHE: /cache
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/immich-app/immich-machine-learning
  persistence:
    cache:
      accessMode: ReadWriteMany
      enabled: true
      size: 10Gi
      type: emptyDir
postgresql:
  image:
    tag: pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
  enabled: true
  global:
    postgresql:
      auth:
        database: immich
        password: immich
        username: immich
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;
redis:
  architecture: standalone
  auth:
    enabled: false
  enabled: true
server:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/immich-app/immich-server
typesense:
  enabled: true
  env:
    TYPESENSE_API_KEY: typesense
    TYPESENSE_DATA_DIR: /tsdata
  image:
    pullPolicy: IfNotPresent
    repository: docker.io/typesense/typesense
    tag: 0.24.0
  persistence:
    tsdata:
      accessMode: ReadWriteOnce
      enabled: true
      size: 1Gi
```
```


### Your .env content

```Shell
env:
  DB_DATABASE_NAME: '{{ .Values.postgresql.global.postgresql.auth.database }}'
  DB_HOSTNAME: '{{ .Release.Name }}-postgresql'
  DB_PASSWORD: '{{ .Values.postgresql.global.postgresql.auth.password }}'
  DB_USERNAME: '{{ .Values.postgresql.global.postgresql.auth.username }}'
  DISABLE_REVERSE_GEOCODING: false
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name
    }}'
  IMMICH_SERVER_URL: '{{ printf "http://%s-server:3001" .Release.Name }}'
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  TYPESENSE_API_KEY: '{{ .Values.typesense.env.TYPESENSE_API_KEY }}'
  TYPESENSE_ENABLED: '{{ .Values.typesense.enabled }}'
  TYPESENSE_HOST: '{{ printf "%s-typesense" .Release.Name }}'
```

### Reproduction steps

```bash
1.Open mobile app
2.Open Photos pane
3.
...
```
