### DISCUSSION TITLE
After upgrading from 1.98 -> 1.106.4 (via path), jobs will not start.

### DISCUSSION THREAD

**Discussion by ns-mglaske** [immich-app/immich#10766] [Q&A] [answered]
### The bug

None of the jobs will start, they all state 'waiting'. 

### The OS that Immich Server is running on

Ubuntu 20, docker

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /d1/pictures:/d1/pictures:ro
      - ./glaskeCA.crt:/usr/local/share/ca-certificates/glaskeCA.crt:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /srv/immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /srv/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/d1/immich/upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.106.4"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
- follow upgrade path
- try to start jobs from Adminstration tab
```

### Relevant log output

```shell
[Nest] 19  - 07/02/2024, 4:58:00 PM    WARN [Api:DuplicateService~4v4gxmjp] Unknown keys found: {
  "job": {
    "objectTagging": {
      "concurrency": 1
    },
    "recognizeFaces": {
      "concurrency": 1
    }
  },
  "machineLearning": {
    "classification": {
      "enabled": true
    }
  }
}
[Nest] 19  - 07/02/2024, 4:58:02 PM    WARN [Api:DuplicateService~ldxr8fvi] Unknown keys found: {
  "job": {
    "objectTagging": {
      "concurrency": 1
    },
    "recognizeFaces": {
      "concurrency": 1
    }
  },
  "machineLearning": {
    "classification": {
      "enabled": true
    }
  }
}
```

### Additional information

I've tried doing docker down, then back up again, no difference.  I've also tried hard-reload my web browser cache, then resetting and saving the job concurrency settings (which seems to have resolve the log errors above), but still not working.
