### DISCUSSION TITLE
[BUG] Job Status counter decrease even when "machine learning server" Offline

### DISCUSSION THREAD

**Discussion by nicolasfruit** [immich-app/immich#10787] [Q&A]
### The bug

First, I would like to congrat all contributor to this amazing tools !!!!!

**Context**
My Immich server works correctly, but it's on a small ARM Board with limited resources (2GB RAM - 16 GB eMMC), running 24/7. So I deported the Machine Learning Jobs to a more powerfull server, but this server is NOT running 24/7 (only several hours daily). I configure Immich to use this other server available in my local Network

**It's OK when**
When the "Machine Learning Server" is UP, everything works correctly.

**Problem**
BUT when the "Machine Learning Server" is DOWN, Immich Server continue to send Jobs to it, and seems to NOT SEE that the server if Offline. No Error displayed. user won't see that the Jobs are failing

**Workaround**
For Now , I let the Machine Learning running 24/7, but not optimal ! And re-run Jobs with the "Missing" button to re-catch (I hope !) all failing jobs ... but difficult to be sure that all Jobs are correctly done... I have lot's of images/Video.

### The OS that Immich Server is running on

aarch64

### Version of Immich Server

v1.91.2

### Version of Immich Mobile App

v1.91.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/dietpi_userdata/Partage:/mnt/media/Partage:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/dietpi_userdata/Partage:/mnt/media/Partage:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 512M
        reservations:
          cpus: '3'
          memory: 400M
          
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 512M
        reservations:
          cpus: '3'
          memory: 400M

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/dietpi_userdata/Sync/immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=my-type-sense-api-key
DB_PASSWORD=nfr0825
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TYPESENSE_THREAD_POOL_SIZE=8
```

### Reproduction steps

```bash
1.Configure the main Immich server (in my case it's a small arm SBC aarch64, very limited power), so I configure to use an external machine learning server in my network . In /admin/system-settings, section "Machine Learning Settings", URL: http://192.168.1.7:3003 (in my case this is more power full server on my network than Immich serve itself)
2.On the server with IP 192.168.1.7, I have Docker running a container with only the compose part for Immich Machine Learning
3.I upload lot of image (or add an external Library)
4.Then I see Machine Learning Jobs ("Tag Objects", "Smart Search", "Recognize Faces") start correctly, every thing is ok... more than 10K Waiting on each Jobs
5. BUT, if my external server goes Offline (or in my case in sleep mode) ... then Immich server continue to send Machine Learingn Jobs, and don't manage correctly that the Machine Learning server is NOT reachable, and should return ERROR/NOT AVAILABLE....

Should be fun to have a feedback that there is an error:
Perhaps an "ERROR bar" like the "PAUSED" bar indicator when you click "Pause" on a job ???
```

### Additional information

Also, when I try to go to /admin/repair page, my Immich server freeze ... become unresponsive, so difficult to see errors ....
