### DISCUSSION TITLE
v1.107.2 - pgvecto.rs: IPC connection is closed unexpected.

### DISCUSSION THREAD

**Discussion by nothing2obvi** [immich-app/immich#10803] [Q&A]
### The bug

v1.106.4 - Everything was working fine.

Upgraded to v1.107.2 - Immich won't start. I get the following in my logs repeatedly (see below), even upon restarting the postgres instance, as instructed.

### The OS that Immich Server is running on

MacOS Sonoma 14.5

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.2 (I think; N/A)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /Users/username/Docker/immich/.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /Volumes/ExtHDD/PHOTOS/docker/model-cache:/cache
    env_file:
      - /Users/username/Docker/immich/.env
    restart: always
    #deploy:
      #resources:
        #limits:
          #cpus: "0.50"
          #memory: 1000M

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    #deploy:
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 1000M

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    volumes:
      #- /Volumes/ExtHDD/PHOTOS/docker/pgdata:/var/lib/postgresql/data
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    #deploy:
      #resources:
        #limits:
          #cpus: "0.25"
          #memory: 1000M
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/Volumes/ExtHDD/PHOTOS
# The ones below are not in the original example.env file.
#IMMICH_MEDIA_LOCATION=/Volumes/ExtHDD/IMMICH-TEST
EXTERNAL_PATH="/Volumes/ExtHDD/PHOTOS/External Libraries"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD="password-here"

# Where the database will be
DB_DATA_LOCATION=/Volumes/ExtHDD/PHOTOS/docker/pgdata

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upgrade to v1.107.2
2. Can't start Immich
3. See error
```

### Relevant log output

```shell
Container started
Detected CPU Cores: 8
Starting api worker
Starting microservices worker
[Nest] 7  - 07/02/2024, 11:30:11 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 07/02/2024, 11:30:11 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 7  - 07/02/2024, 11:30:31 PM    WARN [Microservices:DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
QueryFailedError: pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
	at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
	at async DatabaseRepository.shouldReindex (/usr/src/app/dist/repositories/database.repository.js:119:25)
	at async /usr/src/app/dist/services/database.service.js:122:21
	at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
  query: '\n' +
	'          SELECT idx_status\n' +
	'          FROM pg_vector_index_stat\n' +
	'          WHERE indexname = $1',
  parameters: [ 'clip_index' ],
  driverError: error: pgvecto.rs: IPC connection is closed unexpected.
  ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
	  at /usr/src/app/node_modules/pg/lib/client.js:526:17
	  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	  at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
	  at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
	  at async DatabaseRepository.shouldReindex (/usr/src/app/dist/repositories/database.repository.js:119:25)
	  at async /usr/src/app/dist/services/database.service.js:122:21
	  at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
	length: 272,
	severity: 'ERROR',
	code: 'XX000',
	detail: undefined,
	hint: undefined,
	position: undefined,
	internalPosition: undefined,
	internalQuery: undefined,
	where: undefined,
	schema: undefined,
	table: undefined,
	column: undefined,
	dataType: undefined,
	constraint: undefined,
	file: 'error.rs',
	line: '7',
	routine: undefined
  },
  length: 272,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'error.rs',
  line: '7',
  routine: undefined
}
microservices worker exited with code 1
07/02/2024
04:30:32 PM
Container stopped
```
