### DISCUSSION TITLE
Repair Page takes long to load and crashes 100% of the time with Gateway Timeout Error 504

### DISCUSSION THREAD

**Discussion by gerryflux** [immich-app/immich#10834] [Q&A]
### The bug

The Repair page under Administration doesn't work. It times out with the error 504.

### The OS that Immich Server is running on

Debian 12 (docker)

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - ${EXTERNAL_PATH}:/usr/src/app/external
      - ${IMMICH_USER_ONE}:/mnt/external/one:ro
      - ${IMMICH_USER_TWO}:/mnt/external/two:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      homenet:
        ipv4_address: 172.16.10.200
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${IMMICH_MODEL_CACHE}:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      homenet:
        ipv4_address: 172.16.10.202

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      homenet:
        ipv4_address: 172.16.10.203

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    networks:
      homenet:
        ipv4_address: 172.16.10.204
networks:
  homenet:
    external: true
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/myfiles
EXTERNAL_PATH=/myfilesext

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
IMMICH_MODEL_CACHE=./model-cache

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=somerandompassword

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=mygoogle
DB_USERNAME=userme
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./pg_db

# Redis HOSTNAME
REDIS_HOSTNAME=mygoogle_redis

# External Paths
IMMICH_USER_ONE=/myfiles/one
IMMICH_USER_TWO=/myfiles/two
```

### Reproduction steps

```bash
1. Open and Log in to Immich
2. Navigate to Administration
3. Select "Repair" from the left navigation pane
4. The page will remain stuck at loading for about a minute or two before timing out and producing the error shown below.
```

### Relevant log output

```shell
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
 - 504
Error: Error: 504
    at Object.fe [as ok] (https://[**url**].com/_app/immutable/chunks/fetch-client.vy9D4DHV.js:1:2872)
    at async Yt (https://[**url**].com/_app/immutable/nodes/28.1srml0Xi.js:1:1195)
    at async Re (https://[**url**].com/_app/immutable/chunks/entry.BiGLZ5Ak.js:1:13734)
```

### Additional information

I have so far with limited testing also noticed the page has no issue on a fresh installation with no media added. The issue happens immediately after adding media (uploads or external paths).
