### DISCUSSION TITLE
Broken Immich "service unavailable"; postgres database lost?

### DISCUSSION THREAD

**Discussion by przemhb** [immich-app/immich#10988] [Q&A]
My Immich worked fine for a long time. I have not updated it recently. Yet one day I noticed it does not work and instead of it I get  error "service unavailable". Simple Immich docker restarts didn't help. Docker service restart neither.
I spotted, that not all Immich containers work. Logs told me that:

```
failed to start daemon: Error initializing network controller: error creating default "bridge" network: cannot create network ead197ce8fd4cec3098dff26f3e9982703453bea18647d2357d11d079df987db (docker0>
```

I removed the bridge docker0, deleted and prune networks, recreated them and connected back again to the appropriate containers. More or less like this:

```
sudo rm -rf /var/lib/docker/network

sudo ip link set docker0 down
sudo brctl delbr docker0

sudo ip link set br-9916ee7fd5f8 down
sudo brctl delbr br-9916ee7fd5f8

sudo ip link set br-f11a390fdef9 down
sudo brctl delbr br-f11a390fdef9

sudo rm -rf /var/lib/docker/network

docker network prune

docker network create br-9916ee7fd5f8
docker network create br-f11a390fdef9

docker network disconnect br-9916ee7fd5f8 <container_id>
docker network connect br-9916ee7fd5f8 <container_id>

sudo systemctl restart docker

```

Updated Immich as usual and started it. Unfortunately it displayed just "Get started screen".

So I've checked _.env_ and _docker-compose.yml_
Noticed a few changes since 1.106.4. 

Merged them with my configuration. Importantly postgres database volume is as of 1.107.x referenced by a variable. Previously I had:

```

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
     - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:

```

And now:

```

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
     - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database

volumes:
  model-cache:

```

Set DB_DATA_LOCATION in _.env_ file to:

```
# The location where your database files are stored
DB_DATA_LOCATION=/var/lib/docker/volumes/pgdata/_data
```

No better. Still just the Get started screen.

I do not understand what caused docker and Immich to fail and why it cannot read its database? What I am missing here?

One more puzzle: when I noticed the 503 error I checked /root partition space. It was just 4GB, so I pruned unused containers to regain about 30GB.
