### DISCUSSION TITLE
Upload folder

### DISCUSSION THREAD

**Discussion by DeltaTango69** [immich-app/immich#10982] [Q&A]
Hello,

When I delete the

`- UPLOAD_LOCATION=./library` 

 in the .Env file then I have also to delete the variable in the docker_compose.yml. 

`${UPLOAD_LOCATION}:/usr/src/app/upload`

Maybe I didn't understand this manual?

https://immich.app/docs/guides/custom-locations/

**Comment by bo0tzz** [comment]
What are you trying to do exactly?

**Reply by DeltaTango69** [reply]
I want to have only the uploaded images on my NAS. All the other stuff (thumbs) should be local on a fast SSD. I don't use encoding of videos.

**Reply by bo0tzz** [reply]
Then you can leave UPLOAD_LOCATION as is and you only need to create an extra mount for the thumbs folder.

**Reply by DeltaTango69** [reply]
I have this in the .env

```
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
```

and this in docker-compose.yml

```
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "bilder2:/mnt/media/bilder_all:ro"
      - "mobil:/mnt/media/mobil:ro"
      - "insta:/mnt/media/insta:ro"
    env_file:
      - .env
volumes:
  model-cache:
  bilder2:
    driver_opts:
      type: cifs
      o: "xxxxx
      device: "//192.168.178.4/Bilder_ok"
  insta:
    driver_opts:
      type: cifs
      o: "xxxxx"
      device: "//192.168.178.4/insta"
  mobil:
    driver_opts:
      type: cifs
      o: "xxxxx"
      device: "//192.168.178.4/mobil_bilder"
  mobil_dirk:
    driver_opts:
      type: cifs
      o: "xxxxx"
      device: "//192.168.178.4/mobil_bilder/Upload_Immich_Dirk/"    
```

this is the folder /library

![image](https://github.com/immich-app/immich/assets/82575543/60132637-e969-4476-89d3-00ca715977e3)



The upload directory should now be the

`      device: "//192.168.178.4/mobil_bilder/Upload_Immich_Dirk/"   ` 

I don't really understand why I can leave the UPLOAD_LOCATION=./library now?
Should not be

`UPLOAD_LOCATION=mobil_dirk `

What is stored in the folder library?
