### DISCUSSION TITLE
[Bug] Smart Search Failing -> 500: Internal Server Error

### DISCUSSION THREAD

**Discussion by flloschy** [immich-app/immich#11018] [Q&A]
### The bug

When I search something with context like "three" or "water" or "building", anything really, no results appear, not only that but also an error toast gets shown saying the smart search failed.

As seen in the Error I use this model `ViT-H-14__laion2b-s32b-b79k`, but as you also can see, there is a leading whitespace, which I assume is the culprit here, though i don't have enough knowledge about this projects internal workings to be certain. 

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm) [raspberryPi-OS]

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

1.107.1 build.162

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 5010:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /mnt/immich/cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/upload
# The location where your databas files are stored
DB_DATA_LOCATION=/mnt/immich/database

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.108.0"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Server Settings > Machine Learning Settings > Smart Search > CLIP model
2. Select model `ViT-H-14__laion2b-s32b-b79k`
3. Save Changes
4. Server > Jobs
5. Start Smart Search by clicking the `all` button
(I would guess its not the problem of the model)
```

### Relevant log output

```shell
immich_server            |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~ehro2our] Error: Machine learning request '{"clip":{"textual":{"modelName":" ViT-H-14__laion2b-s32b-b79k"}}}' failed with status 500: Internal Server Error
immich_machine_learning  | [07/10/24 20:19:58] ERROR    Exception in ASGI application
immich_machine_learning  |
immich_server            | [Nest] 17  - 07/10/2024, 8:19:59 PM   ERROR [Api:Error: Machine learning request '{"clip":{"textual":{"modelName":" ViT-H-14__laion2b-s32b-b79k"}}}' failed with status 500: Internal Server Error
immich_server            |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:22:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
immich_server            |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~vlhom9et] Failed to search smart
immich_server            | [Nest] 17  - 07/10/2024, 8:19:59 PM   ERROR [Api:Error: Machine learning request '{"clip":{"textual":{"modelName":" ViT-H-14__laion2b-s32b-b79k"}}}' failed with status 500: Internal Server Error
immich_server            |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:22:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
immich_server            |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~vlhom9et] Error: Machine learning request '{"clip":{"textual":{"modelName":" ViT-H-14__laion2b-s32b-b79k"}}}' failed with status 500: Internal Server Error
immich_machine_learning  |                              ╭─────── Traceback (most recent call last) ───────╮
immich_machine_learning  |                              │ /opt/venv/lib/python3.11/site-packages/anyio/to │
immich_machine_learning  |                              │ _thread.py:56 in run_sync                       │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   53 │   │   │   stacklevel=2,                  │
immich_machine_learning  |                              │   54 │   │   )                                  │
immich_machine_learning  |                              │   55 │                                          │
immich_machine_learning  |                              │ ❱ 56 │   return await get_async_backend().run_s │
immich_machine_learning  |                              │   57 │   │   func, args, abandon_on_cancel=aban │
immich_machine_learning  |                              │   58 │   )                                      │
immich_machine_learning  |                              │   59                                            │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /opt/venv/lib/python3.11/site-packages/anyio/_b │
immich_machine_learning  |                              │ ackends/_asyncio.py:2134 in                     │
immich_machine_learning  |                              │ run_sync_in_worker_thread                       │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   2131 │   │   │   │   │   worker_scope = scope │
immich_machine_learning  |                              │   2132 │   │   │   │                            │
immich_machine_learning  |                              │   2133 │   │   │   │   worker.queue.put_nowait( │
immich_machine_learning  |                              │ ❱ 2134 │   │   │   │   return await future      │
immich_machine_learning  |                              │   2135 │                                        │
immich_machine_learning  |                              │   2136 │   @classmethod                         │
immich_machine_learning  |                              │   2137 │   def check_cancelled(cls) -> None:    │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /opt/venv/lib/python3.11/site-packages/anyio/_b │
immich_machine_learning  |                              │ ackends/_asyncio.py:851 in run                  │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │    848 │   │   │   │   │   exception: BaseExcep │
immich_machine_learning  |                              │    849 │   │   │   │   │   threadlocals.current │
immich_machine_learning  |                              │    850 │   │   │   │   │   try:                 │
immich_machine_learning  |                              │ ❱  851 │   │   │   │   │   │   result = context │
immich_machine_learning  |                              │    852 │   │   │   │   │   except BaseException │
immich_machine_learning  |                              │    853 │   │   │   │   │   │   exception = exc  │
immich_machine_learning  |                              │    854 │   │   │   │   │   finally:             │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/app/main.py:119 in get_entries         │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   116 │   │   │   │   │   "type": type,         │
immich_machine_learning  |                              │   117 │   │   │   │   │   "options": entry.get( │
immich_machine_learning  |                              │   118 │   │   │   │   }                         │
immich_machine_learning  |                              │ ❱ 119 │   │   │   │   dep = get_model_deps(pars │
immich_machine_learning  |                              │   120 │   │   │   │   (with_deps if dep else wi │
immich_machine_learning  |                              │   121 │   │   return without_deps, with_deps    │
immich_machine_learning  |                              │   122 │   except (orjson.JSONDecodeError, Valid │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/app/models/__init__.py:40 in           │
immich_machine_learning  |                              │ get_model_deps                                  │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   37                                            │
immich_machine_learning  |                              │   38                                            │
immich_machine_learning  |                              │   39 def get_model_deps(model_name: str, model_ │
immich_machine_learning  |                              │      list[tuple[ModelType, ModelTask]]:         │
immich_machine_learning  |                              │ ❱ 40 │   return get_model_class(model_name, mod │
immich_machine_learning  |                              │   41                                            │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │ /usr/src/app/models/__init__.py:32 in           │
immich_machine_learning  |                              │ get_model_class                                 │
immich_machine_learning  |                              │                                                 │
immich_machine_learning  |                              │   29 │   │   │   return FaceRecognizer          │
immich_machine_learning  |                              │   30 │   │                                      │
immich_machine_learning  |                              │   31 │   │   case _:                            │
immich_machine_learning  |                              │ ❱ 32 │   │   │   raise ValueError(f"Unknown mod │
immich_machine_learning  |                              │      {model_task}")                             │
immich_machine_learning  |                              │   33                                            │
immich_machine_learning  |                              │   34                                            │
immich_machine_learning  |                              │   35 def from_model_type(model_name: str, model │
immich_machine_learning  |                              │      **kwargs: Any) -> InferenceModel:          │
immich_machine_learning  |                              ╰─────────────────────────────────────────────────╯
immich_machine_learning  |                              ValueError: Unknown model combination: None,
immich_machine_learning  |                              textual, clip
```
