### DISCUSSION TITLE
machine-learning yml wrong

### DISCUSSION THREAD

**Discussion by DeltaTango69** [immich-app/immich#11041] [Q&A] [answered]
Hi,

I would like to try out the hardware acceleration and have changed the corresponding passages under machine leaning. But something is wrong with the code, but I don't know what: 

```
immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: "ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino"
      extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        file: hwaccel.ml.yml
        service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
```
docker compose up -d gives following failure:

```
E:\Immich>docker compose up -d
yaml: line 36: did not find expected key
```

line 36 is : immich-machine-learning:

Image I first had without "" then this error message appeared:

```
E:\Immich>docker compose up -d
yaml: line 41: mapping values are not allowed in this context
```

line 41 is :       extends: # uncomment this section for hardware acceleration - see ....

with this code it works:

```
 immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
     # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      #  file: hwaccel.ml.yml
      #  service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
```

**Comment by bo0tzz** [comment]
Do you have the hwaccel.ml.yml file in the folder as well?

**Reply by DeltaTango69** [reply]
yes it is in the same folder as docker-compose.yml

**Comment by bo0tzz** [comment, marked as answer]
Ah, I see the issue
```yaml
    image: "ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino"
      extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        file: hwaccel.ml.yml
        service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
```
Your extends block is indented. That should be:
```yaml
    image: "ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino"
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
```
