### DISCUSSION TITLE
How to get acceleration on mali-G610 (orange pi 5)

### DISCUSSION THREAD

**Discussion by plord12** [immich-app/immich#11056] [Q&A]
Hi All,

Now that https://github.com/immich-app/immich/issues/11019 is resolved, anyone got acceleration working with maili GPU ?

Firstly I found it hard to find a definitive source for libmali ... eventually I used the deb packages at https://github.com/tsukumijima/libmali-rockchip/releases ( I chose libmali-valhall-g610-g6p0-gbm_1.9-1_arm64.deb ).

I updated hwaccel.ml.yml :

```
services:
  armnn:
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
      - /usr/lib/aarch64-linux-gnu/libmali.so.1.9.0:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)
 ```
 
 and docker-compose.yml :
 
 ```
   immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: armnn # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
 ```
 
 Now when I click on the smart search job I see :
 
 ```
 $ docker logs -f immich_machine_learning
 ...
 [07/12/24 14:32:52] DEBUG    Setting model format to armnn                      
[07/12/24 14:32:52] INFO     Loading visual model 'ViT-B-32__openai' to memory  
[07/12/24 14:32:52] DEBUG    Loading visual preprocessing config for CLIP model 
                             'ViT-B-32__openai'                                 
[07/12/24 14:32:52] DEBUG    Loaded visual preprocessing config for CLIP model  
                             'ViT-B-32__openai'                                 
arm_release_ver of this libmali is 'g6p0-01eac0', rk_so_ver is '5'.
[07/12/24 14:32:53] INFO     Loading ANN model                                  
                             /cache/clip/ViT-B-32__openai/visual/model.armnn ...
[07/12/24 14:32:54] INFO     Loaded ANN model with ID 0                         
[07/12/24 14:33:00] DEBUG    Checking for inactivity...                         
[07/12/24 14:33:10] DEBUG    Checking for inactivity...                         
[07/12/24 14:33:20] DEBUG    Checking for inactivity...                         
[07/12/24 14:33:30] DEBUG    Checking for inactivity...                         
[07/12/24 14:33:40] DEBUG    Checking for inactivity...                         
[07/12/24 14:33:50] DEBUG    Checking for inactivity...                         
[07/12/24 14:34:00] DEBUG    Checking for inactivity...                         
[07/12/24 14:34:10] DEBUG    Checking for inactivity...                         
[07/12/24 14:34:20] DEBUG    Checking for inactivity...                         
[07/12/24 14:34:30] DEBUG    Checking for inactivity...                         
[07/12/24 14:34:39] ERROR    Worker (pid:10) was sent code 139!        
...
 ```
 
So it seems libmali is being picked up.  But not much info on the failure.

On the host I see :

```
# dmesg -w
....
[ 1120.001326] mali fb000000.gpu: Power transition timed out unexpectedly
[ 1120.001360] mali fb000000.gpu: 	MCU desired = 1
[ 1120.001378] mali fb000000.gpu: 	MCU sw state = 2
[ 1120.001394] mali fb000000.gpu: Current state :
[ 1120.001415] mali fb000000.gpu: 	Shader=0000000000000000
[ 1120.001433] mali fb000000.gpu: 	Tiler =0000000000000000
[ 1120.001450] mali fb000000.gpu: 	L2    =0000000000000001
[ 1120.001467] mali fb000000.gpu: 	MCU status = 2
[ 1120.001484] mali fb000000.gpu: Cores transitioning :
[ 1120.001502] mali fb000000.gpu: 	Shader=0000000000000000
[ 1120.001520] mali fb000000.gpu: 	Tiler =0000000000000000
[ 1120.001538] mali fb000000.gpu: 	L2    =0000000000000000
[ 1120.001555] mali fb000000.gpu: Sending reset to GPU - all running jobs will be lost
[ 1120.001581] mali fb000000.gpu: Preparing to soft-reset GPU
[ 1120.001610] mali fb000000.gpu: Wait for MCU power on failed on scheduling tick/tock
[ 1120.002221] mali fb000000.gpu: Resetting GPU (allowing up to 500 ms)
[ 1120.002243] mali fb000000.gpu: Register state:
[ 1120.002269] mali fb000000.gpu:   GPU_IRQ_RAWSTAT=0x00000000   GPU_STATUS=0x00000000  MCU_STATUS=0x00000002
[ 1120.002294] mali fb000000.gpu:   JOB_IRQ_RAWSTAT=0x00000000   MMU_IRQ_RAWSTAT=0x00000000   GPU_FAULTSTATUS=0x00000000
[ 1120.002318] mali fb000000.gpu:   GPU_IRQ_MASK=0x00000000   JOB_IRQ_MASK=0x00000000   MMU_IRQ_MASK=0x00000000
[ 1120.002339] mali fb000000.gpu:   PWR_OVERRIDE0=0x00000000   PWR_OVERRIDE1=0x00000000
[ 1120.002360] mali fb000000.gpu:   SHADER_CONFIG=0x00000000   L2_MMU_CONFIG=0x00000000   TILER_CONFIG=0x00000000
[ 1120.002390] mali fb000000.gpu: Firmware trace buffer dump:
[ 1120.002962] mali fb000000.gpu: reloading firmware
[ 1120.003605] mali fb000000.gpu: Reset complete
[ 1122.564515] mali fb000000.gpu: Power transition timed out unexpectedly
[ 1122.564540] mali fb000000.gpu: 	MCU desired = 1
[ 1122.564551] mali fb000000.gpu: 	MCU sw state = 2
[ 1122.564563] mali fb000000.gpu: Current state :
[ 1122.564578] mali fb000000.gpu: 	Shader=0000000000000000
[ 1122.564591] mali fb000000.gpu: 	Tiler =0000000000000000
[ 1122.564602] mali fb000000.gpu: 	L2    =0000000000000001
[ 1122.564614] mali fb000000.gpu: 	MCU status = 2
[ 1122.564624] mali fb000000.gpu: Cores transitioning :
[ 1122.564636] mali fb000000.gpu: 	Shader=0000000000000000
[ 1122.564647] mali fb000000.gpu: 	Tiler =0000000000000000
[ 1122.564661] mali fb000000.gpu: 	L2    =0000000000000000
[ 1122.564671] mali fb000000.gpu: Sending reset to GPU - all running jobs will be lost
[ 1122.564686] mali fb000000.gpu: Preparing to soft-reset GPU
[ 1122.564722] mali fb000000.gpu: Wait for MCU power on failed on scheduling tick/tock
[ 1122.564995] mali fb000000.gpu: Resetting GPU (allowing up to 500 ms)
[ 1122.565008] mali fb000000.gpu: Register state:
[ 1122.565024] mali fb000000.gpu:   GPU_IRQ_RAWSTAT=0x00000000   GPU_STATUS=0x00000000  MCU_STATUS=0x00000002
[ 1122.565039] mali fb000000.gpu:   JOB_IRQ_RAWSTAT=0x00000000   MMU_IRQ_RAWSTAT=0x00000000   GPU_FAULTSTATUS=0x00000000
[ 1122.565054] mali fb000000.gpu:   GPU_IRQ_MASK=0x00000000   JOB_IRQ_MASK=0x00000000   MMU_IRQ_MASK=0x00000000
[ 1122.565068] mali fb000000.gpu:   PWR_OVERRIDE0=0x00000000   PWR_OVERRIDE1=0x00000000
[ 1122.565082] mali fb000000.gpu:   SHADER_CONFIG=0x00000000   L2_MMU_CONFIG=0x00000000   TILER_CONFIG=0x00000000
[ 1122.565100] mali fb000000.gpu: Firmware trace buffer dump:
[ 1122.565320] mali fb000000.gpu: reloading firmware
[ 1122.565932] mali fb000000.gpu: Reset complete
```

I've no clue what this means.

Thanks!

**Comment by smiggiddy** [comment]
did you figure this out?

**Reply by plord12** [reply]
When searching photos I see -

```
                             FileNotFoundError: Model file not found:           
                             /cache/clip/ViT-B-32__openai/textual/model.armnn   
[08/26/24 07:14:55] WARNING  ARMNN is available, but model 'ViT-B-32__openai'   
                             does not support it.       
```

I guess this is still pending.

**Comment by jacopomaroli** [comment]
it seems to work for me:
```
[09/11/24 17:19:17] INFO     Starting gunicorn 23.0.0                           
[09/11/24 17:19:17] INFO     Listening at: http://[::]:3003 (9)                 
[09/11/24 17:19:17] INFO     Using worker: app.config.CustomUvicornWorker       
[09/11/24 17:19:17] INFO     Booting worker with pid: 10                        
[09/11/24 17:19:23] INFO     Started server process [10]                        
[09/11/24 17:19:24] INFO     Waiting for application startup.                   
[09/11/24 17:19:24] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[09/11/24 17:19:24] INFO     Initialized request thread pool with 8 threads.    
[09/11/24 17:19:24] DEBUG    Checking for inactivity...                         
[09/11/24 17:19:24] INFO     Application startup complete.                      
[09/11/24 17:19:31] DEBUG    Setting model format to armnn                      
[09/11/24 17:19:31] INFO     Loading visual model 'ViT-B-32__openai' to memory  
[09/11/24 17:19:31] DEBUG    Loading visual preprocessing config for CLIP model 
                             'ViT-B-32__openai'                                 
[09/11/24 17:19:31] DEBUG    Loaded visual preprocessing config for CLIP model  
                             'ViT-B-32__openai'                                 
arm_release_ver: g13p0-01eac0, rk_so_ver: 10
[09/11/24 17:19:31] INFO     Loading ANN model                                  
                             /cache/clip/ViT-B-32__openai/visual/model.armnn ...
[09/11/24 17:19:32] INFO     Loaded ANN model with ID 0    
```

problem is I get load on my CPU and running
```
sudo watch -n 1 cat /sys/kernel/debug/rknpu/load
```
or even
```
sudo watch -n 1 cat /sys/kernel/debug/rkrga/load
```
shows no activty. how do I confirm it's actually using HW accel?

my setup: orangepi 5 Joshua-Riek ubuntu
```
orangepi@opi5:~$ uname -r
5.10.0-1012-rockchip
orangepi@opi5:~$ uname -a
Linux opi5 5.10.0-1012-rockchip #12-Ubuntu SMP Wed Aug 14 22:22:22 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
orangepi@opi5:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

I downloaded and installed `libmali-valhall-g610-g13p0-gbm_1.9-1_arm64.deb` from the repo in the first comment.
the only change I had to do was mounting both libmali.so and libmali.so.1 into my container.
this distro also includes a `libmali-valhall-g610-g13p0-x11-wayland-gbm.so` but mounting that as `libmali.so` will trigger an infinite amount of other requirements for other *.so files mostly related to X, so I pulled the lean non-wayland library I mentioner earlier

**Comment by Mahoo12138** [comment]
Look forward to any progress from you.

**Reply by LeoRX** [reply]
it took some time for me to get things going, but I'm also seeing the "Power transition timed out unexpectedly" issue.  :(

forgot to mention I'm running rock pi 5a

**Reply by mertalev** [reply]
Rockchip boards tend to be sensitive to the power block and cable you use. I had to try like 4 different things before I found something that worked reliably. Check what others have used with success for your model. A "dumb", non-PD charger with the right voltage and amperage is more likely to work well.

**Reply by LeoRX** [reply]
@mertalev Thank you for your suggestion.  Unfortunately I can't find the power supply and cable that suits.   tried a few high power rated cable and various power supply, including the Radxa 30w power adapter.

**Comment by LeoRX** [comment]
Finally!  after another few hours of fiddle around and got this working. 
I can't comment why "Power transition timed out unexpectedly" happens, but it is most likely due to missing... something.  I had cli version of the Radxa OS and ended up install the KDE version, everything started to work afterwards.

**Reply by RikudouGoku** [reply]
Do you mind giving a step by step guide on how you did this? I just installed Immich on my Orange Pi 5 Plus so looking to try it out with hardware acceleration.

**Reply by LeoRX** [reply]
@RikudouGoku  have you follow the steps in the doc?  [https://immich.app/docs/features/ml-hardware-acceleration](url)
are you seeing errors?

btw.. there was an update of driver a few hours ago at [https://github.com/tsukumijima/libmali-rockchip/releases](url)

**Reply by LeoRX** [reply]
Also want to note, I have not able to get any clip model working except for the default "ViT-B-32__openai"...

**Reply by RikudouGoku** [reply]
I did check the docs. "/dev/mali0", "/usr/lib/libmali.so" and "/lib/firmware/mali_csffw.bin" exists.

Here is how my docker-compose.yml looks under the ml area:

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: armnn # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

**Comment by plord12** [comment]
I have upgraded to `libmali-valhall-g610-g24p0-gbm_1.9-1_arm64.deb` and have refresh the model cache.

When running text searches I see -

```
[12/02/24 08:38:12] INFO     Downloading textual model 'ViT-B-32__openai'. This 
                             may take a while.                                  
Fetching 14 files: 100%|██████████| 14/14 [00:00<00:00, 1542.96it/s]
[12/02/24 08:38:12] INFO     Loading textual model 'ViT-B-32__openai' to memory 
[12/02/24 08:38:12] ERROR    Model file not found:                              
                             /cache/clip/ViT-B-32__openai/textual/model.armnn   
```

When forcing a facial recognition, I see -

```
[12/02/24 08:42:55] INFO     Loading detection model 'buffalo_l' to memory      
arm_release_ver: g24p0-00eac0, rk_so_ver: 4
[12/02/24 08:42:55] INFO     Loading ANN model                                  
                             /cache/facial-recognition/buffalo_l/detection/model
                             .armnn ...                                         
Binary version (37) differs from expected (44)
terminate called after throwing an instance of 'cl::Error'
  what():  clCreateProgramWithBinary
```

I guess I'll try with the 'g13p0' version

**Reply by plord12** [reply]
> I have upgraded to `libmali-valhall-g610-g24p0-gbm_1.9-1_arm64.deb` and have refresh the model cache.

Ah.  I need the g6p0 version (presumably some binary compatibility).  

Specifically, I'm currently trying `https://github.com/tsukumijima/libmali-rockchip/releases/download/v1.9-1-3238416/libmali-valhall-g610-g6p0-gbm_1.9-1_arm64.deb`

I'm not seeing errors with smart search admin job - clip model appears to be loaded and used.   Accelerated text searches not supported.

dmesg is still very noisy ... GPU reset many times.  I've no idea if this stops acceleration being used.

**Reply by LeoRX** [reply]
I haven't seen similar errors.  However, straight after the server start, you can run `dmesg | grep gpu` to find the version of the user space driver you should be using.

mine looks like this

`[   11.819838] mali fb000000.gpu-mali: Kernel DDK version g21p0-01eac0`

**Comment by jasonkolodziej** [comment]
Hi @plord12 I was curious if you got this working?

For me I am facing a slightly different issue with mounting the *.so and .bin files with docker-compose. (yes, it's `snapcrafted`).

Device Stats:
```sh
Ubuntu 24.04.1 LTS (GNU/Linux 6.1.0-1025-rockchip aarch64)
$: cat /etc/orangepi-release 
BOARD=orangepi5plus
$: uname -a
Linux ubuntu-gpu0 6.1.0-1025-rockchip #25-Ubuntu SMP Mon Aug 26 23:01:14 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

Helper script to simplify the `libmali.so` reinstall:
```bash
#!/bin/bash

echo "Display session type: ${XDG_SESSION_TYPE}"
# Install Mali GPU driver
#? https://github.com/immich-app/immich/discussions/11056
install() {
    local version=$(gh release -R tsukumijima/libmali-rockchip list | awk 'NR==1{print $1}')
    echo "$FUNCNAME(): Installing Mali GPU driver..."
    echo "Current location: ${PWD}"
    mkdir -p ~/tmp/libmali
    pushd ~/tmp/libmali
    # sudo apt-get install -y libmali-sunxi-utgard0-r6p0
    gh release -R tsukumijima/libmali-rockchip download $version -p '*-g610-g13p0*'
    sudo dpkg -i libmali-valhall-g610-g13p0-gbm_${version}_arm64.deb
    # sudo dpkg --info --simulate libmali-valhall-g610-g13p0-gbm_1.9-1_arm64.deb
    popd
    echo "Mali GPU driver installed."
}

purge() {
    echo "$FUNCNAME(): Purging Mali GPU driver..."
    sudo dpkg -P libmali-valhall-g610-g13p0-gbm
    echo "Mali GPU driver purged."
}

list_kernel_modules() {
    local modules=${1:-''}
    echo "$FUNCNAME(): Listing kernel (active/loaded) modules..."
    ls -R /lib/modules/$(uname -r)/kernel/$modules
    # lsmod | grep mali
}

list_kernel_drivers() {
    local drivers=${1:-''}
    echo "$FUNCNAME(): Listing kernel drivers..."
    list_kernel_modules drivers/gpu
}

install_glmark2() {
    echo "$FUNCNAME(): Installing glmark2..."
    sudo apt install glmark2-es2-x11
}

install_clinfo() {
    echo "$FUNCNAME(): Installing glmark2..."
    sudo apt install clinfo
}

find_firmware_csf() {
    echo "$FUNCNAME(): Finding Mali GPU CSF firmware..."
    # find /lib/modules/$(uname -r)/kernel/drivers/gpu/drm/ -name '*csf*'
    #? expect -- /usr/lib/firmware/mali_csffw.bin
    sudo find / -name mali_csffw.bin
}

find_shared_obj() {
    echo "$FUNCNAME(): Finding Mali GPU libmalidrm..."
    # find /lib/modules/$(uname -r)/kernel/drivers/gpu/drm/ -name '*libmalidrm*'
    #? expect -- /usr/lib/aarch64-linux-gnu/libmalidrm.so
    sudo find / -name libmali*.so*
}

$@

```

`docker-compose.yaml`

```yaml
x-armnn-og: &armnn-og
  #? For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
  #* Example tag: ${IMMICH_VERSION:-release}-cuda
  image: &armnn-image ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
  environment: &armnn-env
    MACHINE_LEARNING_ANN: "true" #? Enable ARM-NN hardware acceleration if supported
    # MACHINE_LEARNING_ANN_FP16_TURBO: "false" #? Enable ARM-NN FP16 Turbo mode if supported
    # MACHINE_LEARNING_ANN_TUNING_LEVEL: "2" #? ARM-NN GPU tuning level (1: rapid, 2: normal, 3: exhaustive)
  devices: &armnn-devices
    - /dev/mali0:/dev/mali0
  restart: &armnn-restart always
  expose: &armnn-expose
    - 3003
  #? Reference: https://docs.docker.com/engine/storage/bind-mounts/
  volumes: &armnn-og-volumes
    # - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
    # - /usr/lib/aarch64-linux-gnu/libmali.so:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)
    - type: volume
      source: model-cache
      target: /cache
    - type: volume #? Mali firmware for your chipset (not always required depending on the driver)
      source: firmware
      target: /lib/firmware
    - type: volume #? Mali driver for your chipset (always required)
      source: usr-lib
      target: /usr/lib

services:
  immich-machine-learning:
    # env_file: .env
    container_name: immich_machine_learning
    hostname: immich_machine_learning.docker
    image: *armnn-image
    # extends: #? uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #*   file: hwaccel.ml.yml
    #*   service: cpu #? set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    environment:
      <<: *armnn-env
    devices: *armnn-devices
    restart: *armnn-restart
    expose: *armnn-expose
    volumes:
      *armnn-og-volumes

    networks:
      immich_frontend:
        aliases:
          - immich_machine_learning.docker
          - immich_ml

    healthcheck:
      disable: false

volumes:
  model-cache:
  usr-lib:
    external: true
    name: usr-lib
    #* driver: local
    #* driver_opts:
    #*   type: bind
    #*   device: /usr/lib/aarch64-linux-gnu
    #*   o: bind,ro
  firmware:
    external: true
    name: lib-firmware
    #* driver: local
    #* driver_opts:
    #*   type: bind
    #*   device: /lib/firmware
    #*   o: bind,ro

networks:
  immich_frontend:
    external: true
    name: cloudflare-tunnel
```

I was able to execute **Smart Search** and use `btop` (`snap install btop`) to see the performance of the system. Was definitely faster than intel cpu I originally had this container running on. 

## For you

Despite us having different boards are you sure that `libmali-valhall-g610-g6p0-gbm_1.9-1_arm64.deb` is the board for you? or would it be the same as mine ` libmali-valhall-g610-g13p0-gbm_1.9-1_arm64.deb`?

I originally was trying with Ubuntu 24.10 using [ubuntu-rockchip](https://github.com/Joshua-Riek/ubuntu-rockchip/wiki). I wasn't sure about the `/dev/mali0`, it seems like the newest os-release migrated to a more open source approach, so to stay safe and not gain a headache --- I went with Ubuntu 24.04. did my checks during install to know which `libmali-valhall-g610-g*p0-x11-wayland-gbm.so` was installed in `/usr/lib/aarch64-linux-gnu/libmali-x11`.

## For me
I keep getting silly errors about setting volumes being `read-only`...

```sh
docker: Error response from daemon: error while creating mount source path '/usr/lib/aarch64-linux-gnu/libmali.so': mkdir /usr/lib/aarch64-linux-gnu/libmali.so: read-only file system.
```

and have tried not `:ro` and then..
```sh
docker run -v $(readlink -f /usr/lib/aarch64-linux-gnu/libmali.so):/usr/lib/libmali.so -v /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro -it --rm alpine /bin/ash
docker: Error response from daemon: error while creating mount source path '/usr/lib/aarch64-linux-gnu/libmali.so.1.9.0': mkdir /usr/lib/aarch64-linux-gnu/libmali.so.1.9.0: read-only file system.
```

Anyway if you have a chance try out my suggestion to at least get it working.. in the meantime I presume that the docker snap can't see `/usr/lib/*` but not entirely sure.. Would appreciate if you have any thought.


Happy New Year :-)
