### DISCUSSION TITLE
Port 2283 not listening

### DISCUSSION THREAD

**Discussion by mvineetmenon** [immich-app/immich#11085] [Q&A]
### The bug

Web GUI doesn't connect to immich web on forwarded port 2283.

On debian (no GUI, minimalist, netinstall ISO installation) docker host sends a reset for every syn packet from browser.
On further investigation of the docker container, there's no application listening on port 3001. Immich-api and Immich are only listening on 8001 and 8002 respectively.

Tried the same setup with an RHEL9 based docker host, and it worked fine.

### The OS that Immich Server is running on

Debian 12.5

### Version of Immich Server

1.108.0

### Version of Immich Mobile App

1.108.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2
 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_N
AME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database
')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_c
ollector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_
of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Create a machine with iso images available [here](https://www.debian.org/CD/netinst/).
2. Install docker-ce and docker-compose as advised in the official docker manual.
3. Install immich as per immich documention via docker compose method.
```

**Comment by alextran1502** [comment]
Can you post the logs of the server?

**Reply by safehome-jdev** [reply]
I'm experiencing the same issue using helm charts. v1.116.2 works, but all versions afterwards fail.

I attached some screenshots

![image](https://github.com/user-attachments/assets/fcf37dba-8c13-4982-8615-f8d841942ddc)

![image](https://github.com/user-attachments/assets/fb1f3c67-72a1-4030-a263-7e3802785bd3)

![image](https://github.com/user-attachments/assets/fa7b4c74-ce6d-4735-8905-426f13b46461)

Essentially the readiness probe fails. The service clusterIP exists and is forwarding to the right pod, but the pod isn't able to advertise the data yet due to pod state.

My guess is the IP address is the issue and using localhost may solve it as the cluster IP will likely not get the traffic to the pod due to the pod state of "creating"

**Reply by safehome-jdev** [reply]
>
> Essentially the readiness probe fails. The service clusterIP exists and is forwarding to the right pod, but the pod isn't able to advertise the data yet due to pod state.
> 
> My guess is the IP address is the issue and using localhost may solve it as the cluster IP will likely not get the traffic to the pod due to the pod state of "creating"

[wrong] -> I can connect to the pod so it _**is**_ showing that it's able to come up. But probing the port at 2283 provides no result :(

```sh
root@immich-server-78867f6545-5zrvp:/usr/src/app# curl -X GET "http://immich-server.immich.svc:2283/api/server/ping" -v
*   Trying 10.43.82.80:2283...
* connect to 10.43.82.80 port 2283 failed: Connection refused
* Failed to connect to immich-server.immich.svc port 2283 after 2 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to immich-server.immich.svc port 2283 after 2 ms: Couldn't connect to server


root@immich-server-78867f6545-5zrvp:/usr/src/app# curl -X GET "http://10.42.5.89:2283/api/server/ping" -v
*   Trying 10.42.5.89:2283...
* connect to 10.42.5.89 port 2283 failed: Connection refused
* Failed to connect to 10.42.5.89 port 2283 after 0 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to 10.42.5.89 port 2283 after 0 ms: Couldn't connect to server

root@immich-server-78867f6545-5zrvp:/usr/src/app# curl -X GET "http://localhost:2283/api/server/ping" -v
*   Trying 127.0.0.1:2283...
*   Trying [::1]:2283...
* connect to ::1 port 2283 failed: Connection refused
* Failed to connect to localhost port 2283 after 0 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to localhost port 2283 after 0 ms: Couldn't connect to server
```

To take it even further, I noticed the deployment is doing the health/readiness/liveness check on port `:80` instead of `:2283`, which is odd/inconsistent with the events that is reported at the namespace.

```yaml
kind: Deployment
[...]
spec:
    containers:
[...]
       -  name: immich-server
           livenessProbe:
             failureThreshold: 3
             httpGet:
               path: /api/server/ping
               port: http
               scheme: HTTP
             periodSeconds: 10
             successThreshold: 1
             timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```

```yaml
id: immich/immich-server-78867f6545-5zrvp.1800efe6be196691
type: event
links:
    remove: …/v1/events/immich/immich-server-78867f6545-5zrvp.1800efe6be196691
    self: …/v1/events/immich/immich-server-78867f6545-5zrvp.1800efe6be196691
    update: …/v1/events/immich/immich-server-78867f6545-5zrvp.1800efe6be196691
    view: >-
        …/api/v1/namespaces/immich/events/immich-server-78867f6545-5zrvp.1800efe6be196691
_type: Warning
apiVersion: v1
count: 22
firstTimestamp: "2024-10-23T01:13:51Z"
involvedObject:
    apiVersion: v1
    fieldPath: "spec.containers{immich-server}"
    kind: Pod
    name: immich-server-78867f6545-5zrvp
    namespace: immich
    resourceVersion: "558052249"
    uid: 4163b945-149f-4a65-a640-ce04984b750f
kind: Event
lastTimestamp: "2024-10-23T01:17:21Z"
message: >-
    Startup probe failed: Get "http://10.42.5.89:2283/api/server/ping": dial tcp
    10.42.5.89:2283: connect: connection refused
metadata:
    creationTimestamp: "2024-10-23T01:13:51Z"
    fields:
        - 30m
        - Warning
        - Unhealthy
        - pod/immich-server-78867f6545-5zrvp
        - "spec.containers{immich-server}"
        - "kubelet, k3s-06"
        - >-
            Startup probe failed: Get "http://10.42.5.89:2283/api/server/ping": dial
            tcp 10.42.5.89:2283: connect: connection refused
        - 34m
        - 22
        - immich-server-78867f6545-5zrvp.1800efe6be196691
```
