### DISCUSSION TITLE
"Unexpected EOF" when I click upload on the "website"

### DISCUSSION THREAD

**Discussion by jadenquinn** [immich-app/immich#11125] [Q&A]
### The bug

I was able to install immich, and got to the web server, but I clicked upload, and it instantly broke. No idea why. I have no experience in dev stuff for the most part.

### The OS that Immich Server is running on

MacoS 14.5

### Version of Immich Server

The Newest (as of 10 minutes ago)

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres1595610030

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
I have no idea how to reproduce this, all I know is I am having this issue and I have no idea how to fix it.
```

### Relevant log output

```shell
jaden@UltraPuckExtreme immich-app % docker compose up                                                                  
[+] Running 4/0
 ✔ Container immich_postgres          Running                                                                              0.0s 
 ✔ Container immich_redis             Running                                                                              0.0s 
 ✔ Container immich_machine_learning  Running                                                                              0.0s 
 ✔ Container immich_server            Running                                                                              0.0s 
Attaching to immich_machine_learning, immich_postgres, immich_redis, immich_server
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:MapRepository] Geodata import completed
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:ServerService] Feature Flags: {
immich_server            |   "smartSearch": true,
immich_server            |   "facialRecognition": true,
immich_server            |   "duplicateDetection": true,
immich_server            |   "map": true,
immich_server            |   "reverseGeocoding": true,
immich_server            |   "sidecar": true,
immich_server            |   "search": true,
immich_server            |   "trash": true,
immich_server            |   "oauth": false,
immich_server            |   "oauthAutoLaunch": false,
immich_server            |   "passwordLogin": true,
immich_server            |   "configFile": false,
immich_server            |   "email": false
immich_server            | }
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:NestFactory] Starting Nest application...
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] OpenTelemetryModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] OpenTelemetryCoreModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] ConfigHostModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] DiscoveryModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] ClsModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] ConfigModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] EventEmitterModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] TypeOrmCoreModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:InstanceLoader] MicroservicesModule dependencies initialized
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:NestApplication] Nest application successfully started
immich_server            | [Nest] 7  - 07/15/2024, 8:21:09 PM     LOG [Microservices:Bootstrap] Immich Microservices is running [v1.108.0] [PRODUCTION] 
immich_server            | [Nest] 17  - 07/15/2024, 8:22:23 PM     LOG [Api:EventRepository] Websocket Connect:    pyWXzqrOCPW3jpCuAAAB
immich_server            | [Nest] 17  - 07/15/2024, 8:22:41 PM     LOG [Api:SystemConfigService~41mulf8n] LogLevel=log (set via system config)
immich_server            | [Nest] 17  - 07/15/2024, 8:22:41 PM     LOG [Api:SystemConfigService~41mulf8n] LogLevel=log (set via system config)
immich_server            | [Nest] 17  - 07/15/2024, 8:22:41 PM     LOG [Api:MapRepository~41mulf8n] Initializing metadata repository
immich_server            | [Nest] 17  - 07/15/2024, 8:22:41 PM     LOG [Api:MetadataService~41mulf8n] Initialized local reverse geocoder
immich_server            | [Nest] 17  - 07/15/2024, 8:22:41 PM     LOG [Api:SystemConfigService~41mulf8n] LogLevel=log (set via system config)
immich_server            | [Nest] 7  - 07/15/2024, 8:22:41 PM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
Gracefully stopping... (press Ctrl+C again to force)
unexpected EOF
jaden@UltraPuckExtreme immich-app %
```

### Additional information

I have no idea how to find my version, it doesn't say in the log, probably because it "attached" to an already existing one... I have no idea.
