### DISCUSSION TITLE
Unable to update from 1.107.0

### DISCUSSION THREAD

**Discussion by Vendo233** [immich-app/immich#11207] [Q&A]
### The bug

All works OK. I`m on 1.107.0 where trying to upgrade as usual via Portainer/Stacks etc.. it will start but update won`t happen. still immihc shows 1.107.0

### The OS that Immich Server is running on

Debian / Docker / Portainer

### Version of Immich Server

1.107.0

### Version of Immich Mobile App

1.108.0 build 148

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/media/pictures:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/pictures:/usr/src/app/external
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always



  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
see picture below
```

### Reproduction steps

```bash
1. Enter Portainer
2. Enter Stacks
3. Update the Stack / Immich with re-pull all images ON
...
```

### Relevant log output

```shell
ctions
 
 
 
      
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/sessions, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/sessions/:id, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] SharedLinkController {/api/shared-links}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/me, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, PATCH} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] SyncController {/api/sync}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] TagController {/api/tags}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PATCH} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 17  - 07/18/2024, 11:35:35 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.109.2] [PRODUCTION] 
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:MapRepository] Geodata import completed
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:ServerService] Feature Flags: {
  "smartSearch": true,
  "facialRecognition": true,
  "duplicateDetection": true,
  "map": true,
  "reverseGeocoding": true,
  "sidecar": true,
  "search": true,
  "trash": true,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false,
  "email": false
}
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:NestFactory] Starting Nest application...
[Nest] 7  - 07/18/2024, 11:36:33 PM   ERROR [Microservices:TypeOrmModule] Unable to connect to the database. Retrying (1)...
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] OpenTelemetryModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] OpenTelemetryCoreModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] ConfigHostModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] DiscoveryModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] ClsModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] ConfigModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] EventEmitterModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:InstanceLoader] MicroservicesModule dependencies initialized
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:NestApplication] Nest application successfully started
[Nest] 7  - 07/18/2024, 11:36:33 PM     LOG [Microservices:Bootstrap] Immich Microservices is running [v1.109.2] [PRODUCTION] 
Error: connect ECONNREFUSED 172.21.0.2:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
```

### Additional information

![image](https://github.com/user-attachments/assets/37695700-37e1-4b1c-a6cb-dfa34c8a7d4a)
