### DISCUSSION TITLE
immich_postgres outputs fatal error of lack of root role and can't view images in website ui

### DISCUSSION THREAD

**Discussion by SaiukoTorrent** [immich-app/immich#11212] [Q&A]
**The bug**
When I'm trying to see full-size photo/video in web interface, it displays such an error: 
![image](https://github.com/user-attachments/assets/06129d87-b161-4c88-8ba1-b84bd7523662)

> Failed to get asset info (500)

> Stacktrace
> Error: Error: 500
>    at Object.de [as ok] (http://192.168.0.106:2283/_app/immutable/chunks/fetch-client.BoMhsoLS.js:1:2872)
>    at async vt (http://192.168.0.106:2283/_app/immutable/nodes/16.Df5ECu9K.js:1:2233)
>    at async Re (http://192.168.0.106:2283/_app/immutable/chunks/entry.HrKP_vNb.js:1:13734)

There is no problem in mobile app with opening the full-sized content.

### The OS that Immich Server is running on
docker in openmediavault

### Version of Immich Server
v1.109.2

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```
### Your .env content

```Shell
IMMICH_VERSION=release
DB_PASSWORD=xxx
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-af93ffd6-1bd4-4e38-a04a-71f2d720b82b/Srv-Immich/Immich_Library
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-af93ffd6-1bd4-4e38-a04a-71f2d720b82b/Srv-Immich/Immich_DB
```

### Reproduction steps
Display full-size content on website

### Relevant log output

When looking to logs of immich-server container: 

```shell
[Nest] 17  - 07/19/2024, 5:55:48 AM   ERROR [Api:QueryFailedError: could not open file "base/16384/16711": No such file or directory
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1979:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async AssetService.get (/usr/src/app/dist/services/asset.service.js:100:23)~2b3wpvan] Failed to get asset info
[Nest] 17  - 07/19/2024, 5:55:48 AM   ERROR [Api:QueryFailedError: could not open file "base/16384/16711": No such file or directory
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1979:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async AssetService.get (/usr/src/app/dist/services/asset.service.js:100:23)~2b3wpvan] QueryFailedError: could not open file "base/16384/16711": No such file or directory
[Nest] 17  - 07/19/2024, 5:55:48 AM   ERROR [Api:QueryFailedError: could not open file "base/16384/16711": No such file or directory
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1979:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async AssetService.get (/usr/src/app/dist/services/asset.service.js:100:23)~31odby0n] Failed to get asset info
[Nest] 17  - 07/19/2024, 5:55:48 AM   ERROR [Api:QueryFailedError: could not open file "base/16384/16711": No such file or directory
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1979:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async AssetService.get (/usr/src/app/dist/services/asset.service.js:100:23)~31odby0n] QueryFailedError: could not open file "base/16384/16711": No such file or directory
```

However the log of postgresql outputs:
```shell
2024-07-19 05:12:08.120 UTC [1113] FATAL:  role "root" does not exist
2024-07-19 05:17:08.414 UTC [1128] FATAL:  role "root" does not exist
2024-07-19 05:22:08.706 UTC [1143] FATAL:  role "root" does not exist
2024-07-19 05:26:23.717 UTC [1157] ERROR:  could not open file "base/16384/16711": No such file or directory
2024-07-19 05:26:23.727 UTC [1159] ERROR:  could not open file "base/16384/16711": No such file or directory
2024-07-19 05:47:10.419 UTC [1234] FATAL:  role "root" does not exist
2024-07-19 05:52:10.714 UTC [1249] FATAL:  role "root" does not exist
2024-07-19 05:54:11.398 UTC [1259] ERROR:  could not open file "base/16384/16711": No such file or directory
2024-07-19 05:54:11.581 UTC [1261] ERROR:  could not open file "base/16384/16711": No such file or directory
2024-07-19 05:57:11.010 UTC [1282] FATAL:  role "root" does not exist
```

### Additional information

At the beginning after set up immich there weren't any problems for several days. The OMV is running on RP4 that reboots scheduled 1 time everyday. I was trying to look for a similar problem in other posts, also these associated particulary with postgresql; however none of suggested solutions worked for me. I wanted to also add I'm totally newbie in immich and postgresql.
