### DISCUSSION TITLE
HTTP 500 ApiError: Internal Server Error When Uploading Any Media

### DISCUSSION THREAD

**Discussion by bootsareme** [immich-app/immich#11331] [Q&A] [answered]
### The bug

No matter uploading images or videos, the Immich server container crashes with HTTP 500 and the stack needs to be redeployed. This is the case agnostic to uploading methods and on both the web browser, mobile app, and `immich-go`, no files can be uploaded. Furthermore, phantom icons of the content get generated upon the next launch but the thumbnails and content of the image or video which did not get uploaded cannot be viewed. 

### The OS that Immich Server is running on

Debian 12 Bookworm

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.109.2

### Platform with the issue

- [X] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content
*Machine learning is disabled due to lack of hardware.*

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich-stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database

  redis:
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    volumes:
      - /mnt/replicated-650gb/immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/replicated-650gb/immich/storage
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/replicated-650gb/immich/db

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=**********

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Go to any client (web browser, mobile app, `immich-go`).
2. Upload one image or video.
3. Upload fails with HTTP 500 Internal Server Error.
4. Redeploy containers since server crashes.
5. Ghost icons appear of the supposedly uploaded files but thumbnails and file content are missing.

### Relevant log output

```shell
[Nest] 7  - 07/24/2024, 11:36:17 AM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/9c/96/9c961091-bb23-42f7-9ac9-a329c998f226.JPG'
[Nest] 7  - 07/24/2024, 11:36:17 AM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/9c/96/9c961091-bb23-42f7-9ac9-a329c998f226.JPG'
    at async Object.stat (node:internal/fs/promises:1032:18)
    at async MetadataService.exifData (/usr/src/app/dist/services/metadata.service.js:394:23)
    at async MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:184:36)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 07/24/2024, 11:36:17 AM   ERROR [Microservices:JobService] Object:
{
  "id": "109e9976-b935-4e47-b393-5977e5c29c7d",
  "source": "upload"
}
[Nest] 17  - 07/24/2024, 11:36:55 AM   ERROR [Api:AssetMediaService~y5tpxaja] Error uploading file QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)
[Nest] 17  - 07/24/2024, 11:36:55 AM   ERROR [Api:QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)~y5tpxaja] Failed to upload asset
[Nest] 17  - 07/24/2024, 11:36:55 AM   ERROR [Api:QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)~y5tpxaja] QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
[Nest] 7  - 07/24/2024, 11:36:56 AM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/1c/ec/1cecc864-4f31-4e42-8abd-90d7ccfcd6fc.JPG'
[Nest] 7  - 07/24/2024, 11:36:56 AM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/1c/ec/1cecc864-4f31-4e42-8abd-90d7ccfcd6fc.JPG'
    at async Object.stat (node:internal/fs/promises:1032:18)
    at async MetadataService.exifData (/usr/src/app/dist/services/metadata.service.js:394:23)
    at async MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:184:36)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 07/24/2024, 11:36:56 AM   ERROR [Microservices:JobService] Object:
{
  "id": "8e25d136-67b8-4559-88fb-5a3e1983c655",
  "source": "upload"
}
[Nest] 17  - 07/24/2024, 11:38:50 AM    WARN [Api:AuthGuard~v9k3sgja] Denied access to admin only route: /api/jobs
[Nest] 17  - 07/24/2024, 11:39:37 AM     LOG [Api:EventRepository] Websocket Connect:    Rx4sE0pF_oSEEK9oAAAH
[Nest] 17  - 07/24/2024, 11:39:56 AM     LOG [Api:EventRepository] Websocket Disconnect: 2mCEn_jwJ-ONFT0WAAAF
[Nest] 17  - 07/24/2024, 11:41:13 AM     LOG [Api:EventRepository] Websocket Disconnect: Rx4sE0pF_oSEEK9oAAAH
[Nest] 17  - 07/24/2024, 11:45:13 AM     LOG [Api:EventRepository] Websocket Connect:    0SSEO5kOK1GzqLCwAAAJ
[Nest] 17  - 07/24/2024, 11:46:54 AM     LOG [Api:EventRepository] Websocket Connect:    ZY0M4n96Su_mFzG9AAAL
[Nest] 17  - 07/24/2024, 11:47:13 AM     LOG [Api:EventRepository] Websocket Disconnect: 0SSEO5kOK1GzqLCwAAAJ
[Nest] 17  - 07/24/2024, 11:47:15 AM    WARN [Api:AuthGuard~o1ip34ye] Denied access to admin only route: /api/jobs
[Nest] 17  - 07/24/2024, 11:47:26 AM    WARN [Api:AuthGuard~w998pbca] Denied access to admin only route: /api/jobs
[Nest] 17  - 07/24/2024, 11:47:44 AM   ERROR [Api:AssetMediaService~k6llugto] Error uploading file QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)
[Nest] 17  - 07/24/2024, 11:47:44 AM   ERROR [Api:QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)~k6llugto] Failed to upload asset
[Nest] 17  - 07/24/2024, 11:47:44 AM   ERROR [Api:QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async UserRepository.updateUsage (/usr/src/app/dist/repositories/user.repository.js:114:9)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:133:13)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:39:29)~k6llugto] QueryFailedError: duplicate key value violates unique constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
[Nest] 7  - 07/24/2024, 11:47:44 AM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/d2/9b/d29bc6c1-e265-4100-a6e3-9fa6156baf5f.JPG'
[Nest] 7  - 07/24/2024, 11:47:44 AM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, stat 'upload/upload/a4d2d2fb-900c-4613-a61b-262131a4ac23/d2/9b/d29bc6c1-e265-4100-a6e3-9fa6156baf5f.JPG'
    at async Object.stat (node:internal/fs/promises:1032:18)
    at async MetadataService.exifData (/usr/src/app/dist/services/metadata.service.js:394:23)
    at async MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:184:36)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 07/24/2024, 11:47:44 AM   ERROR [Microservices:JobService] Object:
{
  "id": "b429e3b6-0dc9-40a6-9a5a-cf6086ccdbef",
  "source": "upload"
}
[Nest] 17  - 07/24/2024, 11:47:45 AM     LOG [Api:EventRepository] Websocket Connect:    u6ZxFQLnoRhfT6ChAAAN
[Nest] 17  - 07/24/2024, 11:48:04 AM     LOG [Api:EventRepository] Websocket Disconnect: ZY0M4n96Su_mFzG9AAAL
```

### Additional information

I have managed to upload 1000 files already without any problem. The issue started suddenly a week ago and I tried my best to find a solution but nothing so far found works.
