### DISCUSSION TITLE
immich-postgres constantly restarting after update

### DISCUSSION THREAD

**Discussion by script-js** [immich-app/immich#11469] [Q&A] [answered]
### The bug

I recently updated to v1.111.0. When I tried to access my server, I got a "The connection was reset" error. I usually get this error while the server is starting up, but this time it lasted longer. I checked docker, and the immich-postgres container was boot looping. I have tried restarting the server and the container
![Screenshot_20240730_204608_Chrome](https://github.com/user-attachments/assets/ad5623e8-65cf-4c9b-a370-3b2c43612ee0)

### The OS that Immich Server is running on

MacOS Monterey

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env

    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
unknown
```

### Reproduction steps

```bash
I don't know, it just happened
```

### Relevant log output

```shell
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | /usr/src/app/node_modules/redis-parser/lib/parser.js:179
immich_microservices     | Detected CPU Cores: 4
immich_server            |     return new ReplyError(string)
immich_server            |            ^
immich_server            | 
immich_server            | ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
immich_server            |     at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
immich_server            |     at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
immich_server            |   command: {
immich_server            |     name: 'hset',
immich_server            |     args: [
immich_server            |       'immich_bull:metadataExtraction:meta',
immich_server            |       'opts.maxLenEvents',
immich_server            |       '10000'
immich_server            |     ]
immich_server            |   }
immich_server            | }
immich_server            | 
immich_server            | Node.js v20.16.0
immich_server            | api worker exited with code 1
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_microservices     | Starting microservices worker
immich_microservices     | 
immich_microservices     | node:internal/event_target:1094
immich_microservices     |   process.nextTick(() => { throw err; });
immich_microservices     |                            ^
immich_microservices     | Error [ReplyError]: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
immich_microservices     |     at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
immich_microservices     |     at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
immich_microservices     | Emitted 'error' event on Worker instance at:
immich_microservices     |     at [kOnErrorMessage] (node:internal/worker:326:10)
immich_microservices     |     at [kOnMessage] (node:internal/worker:337:37)
immich_microservices     |     at MessagePort.<anonymous> (node:internal/worker:232:57)
immich_microservices     |     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
immich_microservices     |     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
immich_microservices     |   command: {
immich_microservices     |     name: 'hset',
immich_microservices     |     args: [
immich_microservices     |       'immich_bull:thumbnailGeneration:meta',
immich_microservices     |       'opts.maxLenEvents',
immich_microservices     |       '10000'
immich_microservices     |     ]
immich_microservices     |   }
immich_microservices     | }
immich_microservices     | 
immich_microservices     | Node.js v20.16.0
immich_microservices     | Detected CPU Cores: 4
immich_microservices     | Starting microservices worker
error from daemon in stream: Error grabbing logs: invalid character '\x00' looking for beginning of value
```
