### DISCUSSION TITLE
Error response from daemon: Bind mount failed: '/data/compose/x/postgres' does not exists

### DISCUSSION THREAD

**Discussion by Aspyryan** [immich-app/immich#11522] [Q&A] [answered]
### The bug

When trying to create my stack using portainer, the creation crashes with the following message:
```failed to deploy a stack: Network immich_default Creating Network immich_default Created Container immich_redis Creating Container immich_postgres Creating Container immich_machine_learning Creating Container immich_redis Created Container immich_machine_learning Created Container immich_postgres Created Container immich_server Creating Container immich_server Created Container immich_postgres Starting Container immich_redis Starting Container immich_machine_learning Starting Container immich_redis Started Container immich_machine_learning Started Error response from daemon: Bind mount failed: '/data/compose/x/postgres' does not exists```

Everything else seems to have been downloaded fine:
![image](https://github.com/user-attachments/assets/52debdde-46dd-4601-9274-a3a4ab145649)

### The OS that Immich Server is running on

Synology DSM 7.2.1-69057 Update 5

### Version of Immich Server

Release

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the stack.env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Set up docker and portainer on synology
2. Go to the stacks
3. Add the docker compose and env
4. Try to build
```

### Relevant log output

```shell
First run:
failed to deploy a stack: 
pulling... downloading... extracting... (cut for readability)
Pull complete immich-server Pulled Network immich_default Creating Network immich_default Created Volume "immich_model-cache" Creating Volume "immich_model-cache" Created Container immich_postgres Creating Container immich_machine_learning Creating Container immich_redis Creating Container immich_machine_learning Created Container immich_redis Created Container immich_postgres Created Container immich_server Creating Container immich_server Created Container immich_postgres Starting Container immich_machine_learning Starting Container immich_redis Starting Container immich_redis Started Container immich_machine_learning Started Error response from daemon: Bind mount failed: '/data/compose/1/postgres' does not exists
```
