### DISCUSSION TITLE
Large number of untracked files after moving folder

### DISCUSSION THREAD

**Discussion by jeevadotnet** [immich-app/immich#11540] [Q&A]
### The bug

`OS` - ubuntu 22 LTS VM
`immich version` - v1.108.0

**Issue**
Large number of untracked files (200k+) and all my thumbnails & images are missing

**Recreation of error**
1) I moved the immich folder from one NAS to another NAS and then. I changed my  `UPLOAD_LOCATION=/mnt/immich` to  `UPLOAD_LOCATION=/mnt/media/immich`. I moved it with rsync. Both folders (old NAS and new NAS) looks exactly the same with the same folder permissions and ownership.

2) I moved the `immich-app` folder containing, `.env` , `./postgre` and the docker compose file from `/opt/immich-app` to `/root/immich-app`

I ran a script to check the PSQL database if there are any mention of the old NAS mount "/mnt/immich" (which obviously change with       - ${UPLOAD_LOCATION}:/usr/src/app/upload) just to double check if something haven't gone haywire. 

Not sure what went wrong? Postgresql files maybe not like being moved? Docker inspect looks fine. 

### The OS that Immich Server is running on

Ubuntu 22 LTS

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
default

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgre

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=ZA

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1) I moved the immich folder from one NAS to another NAS and then. I changed my  `UPLOAD_LOCATION=/mnt/immich` to  `UPLOAD_LOCATION=/mnt/media/immich`. I moved it with rsync. Both folders (old NAS and new NAS) looks exactly the same with the same folder permissions and ownership.

2) I moved the `immich-app` folder containing, `.env` , `./postgre` and the docker compose file from `/opt/immich-app` to `/root/immich-app`

I ran a script to check the PSQL database if there are any mention of the old NAS mount "/mnt/immich" (which obviously change with       - ${UPLOAD_LOCATION}:/usr/src/app/upload) just to double check if something haven't gone haywire. 

Not sure what went wrong? Postgresql files maybe not like being moved? Docker inspect looks fine.
```
