### DISCUSSION TITLE
Thumbnail generation is not consistent after gap in updating

### DISCUSSION THREAD

**Discussion by guitarmanusa** [immich-app/immich#11557] [Q&A] [answered]
### The bug

After uploading ~700 images/videos (about 2 months worth from my iPhone) no thumbnails were generated.  I had updated from 1.103.1 prior to moving and updated to 1.111.0 before the upload of photos.  The one breaking change that I saw was the deprecation of the immich_microservices container which I accounted for in my docker_compose.yml.

Sometimes I can trigger a thumbnail for the new photos to be generated by selecting the photos in the web app and then choosing "Refresh Thumbnail", other times I can only trigger the thumbnail generation after selecting the preview of the photo and then from the options selecting "Refresh Thumbnail".  From the administration page then jobs selecting Generate Thumbnails for missing or all will trigger only one or two images to generate a thumbnail.

The thumbnails for all new photos that were uploaded from the iPhone show in the mobile app, but from the web app no thumbnails show and video encodes are not happening.

### The OS that Immich Server is running on

Ubuntu 22.04.4

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:

  tailscale:
    container_name: tailscale
    hostname: immich
    image: tailscale/tailscale
    volumes:
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    restart: unless-stopped

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./immich-app/immich.env
    depends_on:
      - redis
      - database
      - tailscale
    restart: always
    network_mode: service:tailscale

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: ./immich-app/hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - ./immich-app/immich.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      #- ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    
  immich_backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./immich_db_dumps:/db_dumps
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/$USER/tank/Pictures/immich_library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.111.0

# LOG LEVEL
IMMICH_LOG_LEVEL=debug

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload photos to internal library
2. No thumbnails are generated, videos are not transcoded
3. Selecting "Refresh Thumbnails" does not always trigger a thumbnail to be generated
...
```

### Relevant log output

```shell
[Nest] 17  - 08/04/2024, 12:35:28 AM   DEBUG [Api:JobService~sffzhtd5] Handling command: queue=thumbnailGeneration,force=false
[Nest] 17  - 08/04/2024, 12:35:28 AM   DEBUG [Api:LoggingInterceptor~sffzhtd5] PUT /api/jobs/thumbnailGeneration 200 3.23ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:29 AM   DEBUG [Api:LoggingInterceptor~9p6lif4k] GET /api/server-info/statistics 200 14.55ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:30 AM   DEBUG [Api:LoggingInterceptor~gqr5e6dh] GET /api/server-info/storage 200 0.31ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:30 AM   DEBUG [Api:LoggingInterceptor~obon5ama] GET /api/admin/users?withDeleted=false 200 1.30ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:30 AM   DEBUG [Api:LoggingInterceptor~h588mrre] GET /api/jobs 200 4.09ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:33 AM   DEBUG [Api:LoggingInterceptor~63o2g2ze] GET /api/jobs 200 2.01ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:35 AM   DEBUG [Api:LoggingInterceptor~1pwpyy8a] GET /api/jobs 200 3.45ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:38 AM   DEBUG [Api:LoggingInterceptor~t31pcsp5] GET /api/jobs 200 3.43ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:40 AM   DEBUG [Api:LoggingInterceptor~73ak4tk1] GET /api/jobs 200 2.88ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:43 AM   DEBUG [Api:LoggingInterceptor~x4dno17h] GET /api/jobs 200 4.15ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:45 AM   DEBUG [Api:LoggingInterceptor~g93v4edd] GET /api/jobs 200 4.88ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:48 AM   DEBUG [Api:LoggingInterceptor~sswghm11] GET /api/jobs 200 3.55ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:50 AM   DEBUG [Api:LoggingInterceptor~6jkfsvwo] GET /api/jobs 200 9.12ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:53 AM   DEBUG [Api:LoggingInterceptor~s8g4d0nc] GET /api/jobs 200 3.91ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:55 AM   DEBUG [Api:LoggingInterceptor~8h44t5di] GET /api/jobs 200 4.91ms ::ffff:100.102.51.9
[Nest] 17  - 08/04/2024, 12:35:58 AM     LOG [Api:EventRepository] Websocket Disconnect: iEcpn8huTNnH35u0AAAU
```

### Additional information

I can see in the debug log that the thumbnail generation job is being posted but the tasks don't execute.
