### DISCUSSION TITLE
Broken images after CLI upload

### DISCUSSION THREAD

**Discussion by RenanGreca** [immich-app/immich#11585] [Q&A] [answered]
### The bug

I just uploaded a folder via the CLI (as I've done in the past):
```sh
> immich upload --album 2023-01\ 3.\ Paris
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 103/103 assets
Found 103 new files and 0 duplicates
Uploading assets | ████████████████████████████████████████ | 100% | ETA: 0s | 806.9 MB/806.9 MB
Successfully uploaded 103 new assets (806.9 MB)
Creating albums | ████████████████████████████████████████ | 100% | ETA: 0s | 1/1 albums
Successfully created 1 new album
Successfully updated 103 assets
Adding assets to albums | ████████████████████████████████████████ | 100% | ETA: 0s | 103/103 assets
```

However, after finishing, 9 out of the 103 images appear broken on Immich:
<img width="1191" alt="Screenshot 2024-08-05 at 09 41 44" src="https://github.com/user-attachments/assets/6815daa6-6471-4bae-8d57-d9a303d2eea9">

I correctly see all these files, uncorrupted, where they should be (`library/.../2023/2023-01/xxxxx.jpg`).
<img width="329" alt="Screenshot 2024-08-05 at 09 46 55" src="https://github.com/user-attachments/assets/6df53e93-79f1-4fe9-8a6e-d97d3c4eb0bd">
(nevermind my typo of Paris 🙃)

I tried permanently deleting them — but after doing so the files are still in the trash. I also tried re-uploading them via CLI, GUI or using "Replace with Upload", but in all cases Immich detects a duplicate and refuses to substitute.

I tried uploading another folder with 72 images, and again I have 4 images that appear broken on Immich, despite being present in the server path. I investigated the logs and there was an issue with the URL to the remote ML service, although those errors were appearing independently of the broken images. I was only able to find two logs related to the unseen images (see attach log below).

Trying again a third time, after fixing the remote ML URL, no issues occurred. Yet I'm unable to fix the images that already appear broken.

### The OS that Immich Server is running on

Raspberry Pi OS

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_CLUTER=TRUE
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - SCHEDULE=@weekly
      - BACKUP_DIR=/db_dumps
      - BACKUP_KEEP_WEEKS=4
      - POSTGRES_EXTRA_OPTS=-Z6 --clean --if-exists
    volumes:
      - ${BACKUP_LOCATION}/backup:/db_dumps
    depends_on:
      - database

  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      TZ: "America/Sao_Paulo"
    volumes:
      - ./immich-kiosk.yaml:/config.yaml
    restart: on-failure
    ports:
      - 3003:3000

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/pictures/Immich/
BACKUP_LOCATION=/media/backups/Immich/

IMMICH_VERSION=release
DB_PASSWORD=xxxx

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_USERNAME=immich
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload a directory of images with the CLI (`immich upload --album`)
2. About 5-10% of images appear corrupt on the application, despite being available in the correct path.
```

### Relevant log output

```shell
[Nest] 7  - 08/05/2024, 7:08:23 AM   ERROR [Microservices:StorageTemplateService] Problem applying storage template
[Nest] 7  - 08/05/2024, 7:08:23 AM   ERROR [Microservices:StorageTemplateService] Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:633:28)
    at Connection.emit (node:events:519:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 7  - 08/05/2024, 7:08:23 AM   ERROR [Microservices:StorageTemplateService] Object:
{
  "id": "0f93b788-10e1-45c7-b8c2-2c339ac369fa",
  "oldPath": "upload/upload/4ee4629e-68c4-40fc-bede-523c5f343c3d/9f/0f/9f0f0f34-7a42-4c7a-a894-cbf7f358bb8c.jpg",
  "newPath": "upload/library/admin/2023/2023-01/pairs-032-2023-01-10.jpg"
}

[Nest] 7  - 08/05/2024, 7:09:28 AM   ERROR [Microservices:StorageTemplateService] Problem applying storage template
[Nest] 7  - 08/05/2024, 7:09:28 AM   ERROR [Microservices:StorageTemplateService] Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
    at Object.onceWrapper (node:events:633:28)
    at Connection.emit (node:events:519:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)
    at Socket.emit (node:events:519:28)
    at TCP.<anonymous> (node:net:339:12)
[Nest] 7  - 08/05/2024, 7:09:28 AM   ERROR [Microservices:StorageTemplateService] Object:
{
  "id": "42a6d4bc-ee4c-452e-b3a6-9d3762892895",
  "oldPath": "upload/upload/4ee4629e-68c4-40fc-bede-523c5f343c3d/bc/b8/bcb81b38-4ccb-4112-ac6c-316c25a354b1.jpg",
  "newPath": "upload/library/admin/2023/2023-01/pairs-085-2023-01-12.jpg"
}
```
