### DISCUSSION TITLE
no login after changing api key

### DISCUSSION THREAD

**Discussion by pindaroli** [immich-app/immich#11583] [Q&A]
### The bug

1) I created a key for account  admin.
2) I logged (immich login) with key
3) I delected and created a new key
4) immich login http://docker.pind/api xxxxxxxxxxxxxxxxxxx
Logging in to http://docker.pind/api
Failed to load user info - TypeError: fetch failed

repeted 3) and 4) but always some result 

### The OS that Immich Server is running on

docker on alpine 

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

no mobile

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: vaapi
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime
      - ${PHOTODIR}:/nfs
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
PHOTODIR=/mnt/nfs-arrdata/media/foto
```

### Reproduction steps

```bash
1) I created a key for account  admin.
2) I logged (immich login) with key
3) I delected and created a new key
4) immich login http://docker.pind/api xxxxxxxxxxxxxxxxxxx
Logging in to http://docker.pind/api
Failed to load user info - TypeError: fetch failed
```

### Relevant log output

```shell
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SearchController {/api/search}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/metadata, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/smart, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/explore, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/person, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/places, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/cities, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/search/suggestions, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] ServerController {/api/server}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/about, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/storage, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/ping, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/version, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/features, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/theme, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/config, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/statistics, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/media-types, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] ServerInfoController {/api/server-info}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/about, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/storage, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/ping, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/version, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/features, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/theme, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/config, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/statistics, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/media-types, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SessionController {/api/sessions}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions/:id, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SharedLinkController {/api/shared-links}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/me, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, PATCH} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SyncController {/api/sync}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] TagController {/api/tags}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PATCH} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 17  - 08/05/2024, 5:46:53 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.111.0] [PRODUCTION] 
[Nest] 17  - 08/05/2024, 5:46:54 AM     LOG [Api:EventRepository] Websocket Connect:    WmF_9SX5VXPJ269CAAAB
[Nest] 17  - 08/05/2024, 5:46:57 AM     LOG [Api:EventRepository] Websocket Connect:    gAxQhdEqkrXP8GXsAAAD
[Nest] 17  - 08/05/2024, 5:52:48 AM     LOG [Api:EventRepository] Websocket Disconnect: gAxQhdEqkrXP8GXsAAAD
[Nest] 17  - 08/05/2024, 5:53:05 AM     LOG [Api:EventRepository] Websocket Connect:    rYac5qZimCAMzPSBAAAF
```
