### DISCUSSION TITLE
Oauth2 issues when connection to MS365 Azure Directory

### DISCUSSION THREAD

**Discussion by TVES-Tech** [immich-app/immich#11584] [Q&A] [answered]
### The bug

I am attempting to enable SSO in combination with Oauth integrated in the Microsoft Azure cloud.

I had some issues setting it up, now that the connection is there I face a final issue. the error message "Failed to finish oath"

### The OS that Immich Server is running on

Ubuntu 24.xx

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=my_little_secret

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
Open the webpage of IMMICH https://{{mydomain}}
Click the SSO button I called it "Sign-in with 365"

The laptop is forwarding through the sign-in windows as it is Azure Joined.

Immich returns and shows the error: "Failed to finish oauth"
```

### Relevant log output

```shell
[Nest] 17  - 08/05/2024, 7:20:17 AM   ERROR [Api:RPError: expected application/jwt response from the userinfo_endpoint
    at Client.userinfo (/usr/src/app/node_modules/openid-client/lib/client.js:1268:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthService.callback (/usr/src/app/dist/services/auth.service.js:151:25)
    at async OAuthController.finishOAuth (/usr/src/app/dist/controllers/oauth.controller.js:39:22)~yf08dc86] Failed to finish oauth
[Nest] 17  - 08/05/2024, 7:20:17 AM   ERROR [Api:RPError: expected application/jwt response from the userinfo_endpoint
    at Client.userinfo (/usr/src/app/node_modules/openid-client/lib/client.js:1268:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthService.callback (/usr/src/app/dist/services/auth.service.js:151:25)
    at async OAuthController.finishOAuth (/usr/src/app/dist/controllers/oauth.controller.js:39:22)~yf08dc86] RPError: expected application/jwt response from the userinfo_endpoint
[Nest] 17  - 08/05/2024, 7:20:17 AM   DEBUG [Api:HttpExceptionFilter~yf08dc86] HttpException(500) {"message":"Failed to finish oauth","error":"Internal Server Error","statusCode":500}
```

### Additional information

In the portal.azure.com register an application.
Generate the client ID and secret, Retreive the Issuer URL:

IMMICH SETTINGS:

ISSUER URL: https://login.microsoftonline.com/{{mytenantID}}/v2.0
CLIENT ID: {{Application (client) ID}}
CLIENT SECRECT: {{Generated by the Certificates & Secret section}}
SCOPE: openid profile email
SIGNING ALGORITHM: RS256
PROFILE SIGNING ALGORITHM: RS256
MOBILE REDIRECT URL: https://{{mydomain}}/api/oauth/mobile-redirect

REDIRECT URL's:
https://{{mydomain}}/user-settings
https://{{mydomain}}/auth/login
https://{{mydomain}}/api/oauth/mobile-redirect
