### DISCUSSION TITLE
External Library finds 0 assets

### DISCUSSION THREAD

**Discussion by guitarmanusa** [immich-app/immich#11595] [Q&A] [answered]
I'm having an issue where my external library will never find any assets in any of my directories/import paths.  Even if I drill down to a specific folder that does not have any special characters scans of my external library will always result in "0 assets found while crawling".

docker-compose.yml
```
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # external library mount
      - /media/name/tank/Pictures/2010:/usr/src/app/external/photos
    env_file:
      - ./immich-app/immich.env
    depends_on:
      - redis
      - database
      - tailscale
    restart: always
    network_mode: service:tailscale

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: ./immich-app/hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - ./immich-app/immich.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
```

immich.env
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/name/tank/Pictures/immich_library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.111.0

# LOG LEVEL
IMMICH_LOG_LEVEL=debug

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

immich_server [DEBUG_LOG]
```
[Nest] 17  - 08/05/2024, 4:40:40 PM   DEBUG [Api:LoggingInterceptor~qt5jsp8n] POST /api/libraries/e8167a6a-91b7-476a-9547-9bc157570764/validate 200 0.82ms ::ffff:100.102.51.9
[Nest] 17  - 08/05/2024, 4:40:51 PM   DEBUG [Api:LoggingInterceptor~6rly76th] POST /api/libraries/e8167a6a-91b7-476a-9547-9bc157570764/validate 200 1.30ms ::ffff:100.102.51.9
[Nest] 17  - 08/05/2024, 4:40:53 PM   DEBUG [Api:LoggingInterceptor~yreudmhd] POST /api/libraries/e8167a6a-91b7-476a-9547-9bc157570764/scan 204 8.50ms ::ffff:100.102.51.9
[Nest] 7  - 08/05/2024, 4:40:53 PM     LOG [Microservices:LibraryService] Refreshing library: e8167a6a-91b7-476a-9547-9bc157570764
[Nest] 7  - 08/05/2024, 4:40:53 PM   DEBUG [Microservices:LibraryService] Found 0 asset(s) when crawling import paths 
[Nest] 17  - 08/05/2024, 4:40:56 PM   DEBUG [Api:LoggingInterceptor~uifdy3sg] GET /api/jobs 200 7.34ms ::ffff:100.102.51.9
[Nest] 17  - 08/05/2024, 4:40:56 PM   DEBUG [Api:LoggingInterceptor~mu4dy2ar] GET /api/system-config 200 4.94ms ::ffff:100.102.51.9
```

I have confirmed I can see the files from inside the docker container:
`docker exec -it immich_server bash` gives me:
```
root@immich:/usr/src/app# cd external/
root@immich:/usr/src/app/external# ls
photos
root@immich:/usr/src/app/external# cd photos/
root@immich:/usr/src/app/external/photos# ls
10  11
root@immich:/usr/src/app/external/photos# cd 10
root@immich:/usr/src/app/external/photos/10# ls
23  24	30  31
root@immich:/usr/src/app/external/photos/10# cd 31/
root@immich:/usr/src/app/external/photos/10/31# ls
IMAG0018.jpg  IMAG0019.jpg  IMAG0020.jpg
root@immich:/usr/src/app/external/photos/10/31# ls -la
total 2949
drwx------ 2 node node       5 May  9  2016 .
drwx------ 6 node node       6 May  9  2016 ..
-rw------- 1 node node 1136962 Nov  1  2010 IMAG0018.jpg
-rw------- 1 node node  888885 Nov  1  2010 IMAG0019.jpg
-rw------- 1 node node  942121 Nov  1  2010 IMAG0020.jpg
```

I have tried mounting the volume in my docker-compose as both read only and without the ro flag, no change.  I've changed the location of where the volume is mapped inside the container, no change.  I have tried both `docker compose up -d` and `docker compose up -d --force-recreate`, no change still 0 assets found when crawling.

I don't see any option to set external paths for a user in the administration settings as some discussion threads have previously mentioned, so I'm assuming that was a feature that was removed.

This has to be a permissions issue, right?  I'm just not seeing where it permissions could be messed up since I can see the files from a docker exec.  Please help!
