### DISCUSSION TITLE
Immich_Postgre Container unhealthy after update from 1.109.0 to 1.111.0

### DISCUSSION THREAD

**Discussion by ETS-FTW** [immich-app/immich#11676] [Q&A] [answered]
### The bug

Remove containers and non-persistent volumes to upgrade to 1.111.0.

4 containers come up healthy via Portainer.  After a few minutes, Immich_Postgres moves to a "running" state.  (unhealthy).  Receive following error trying to access page:2283

Failed to get server config - 500
Error: Error: 500
    at Object.he [as ok] (https://"redacted"/_app/immutable/chunks/fetch-client.1_Y0LTYI.js:1:2872)
    at async Q (https://"redacted"/_app/immutable/nodes/4.CZdv-cb5.js:1:638)
    at async Re (https://"redacted"/_app/immutable/chunks/entry.aDZJwCCj.js:1:13734)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
TZ=America/Los_Angeles
IMMICH_VERSION=release
DB_PASSWORD="redacted"
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Stop all containers.
2. Remove containers and non-persistent volumes and images
3. Copy new Compose file to Portainer editor, adding "stack" in front of all .env references
4. Verify .env file is the same
5. Redeploy and repull images
6. Log into Immich to verify version
7. 2-3 minutes later, page freeze, receive error listed above, Postgre container moves to "running" (unhealthy) status.  Other containers remain healthy.
8. Restart of containers leave machine_learning and redis healthy and postgre and server "running"
...
```

### Additional information

I am new at troubleshooting Docker and its intricacies, but can get around.   Please be gentle :-)
