### DISCUSSION TITLE
Upload folder on external NAS

### DISCUSSION THREAD

**Discussion by DeltaTango69** [immich-app/immich#11686] [Q&A] [answered]
Hi,

I am new to the upload things, before I have only used external library's. I want to have only the uploaded images on my NAS. All the other stuff (thumbs) should be local on a fast SSD. I don't use encoding of videos. 

This setup is not working - with this setup I am not able to go to the admin tab. Upload is working normal! But I don't know what is wrong! Maybe something is wrong with the mount of the samba share. I have reading about uid and gid but I dont know which numbers are correct. Any help would be appreciated. 

extract from .env
```
# The location where your uploaded files are stored

 UPLOAD_LOCATION=Immich
 THUMB_LOCATION=./library/thumbs
 ENCODED_VIDEO_LOCATION=./library/encoded-video
 PROFILE_LOCATION=./library/profile

```

extract from docker_compose.yml

```
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
      - "bilder2:/mnt/media/bilder_all:ro"
      - "mobil:/mnt/media/mobil:ro"
      - "insta:/mnt/media/insta:ro"

volumes:
  model-cache:
  bilder2:
    driver_opts:
      type: cifs
      o: "username=xxxxx,password=xxxxxxx,rw"
      device: "//192.168.178.4/Bilder_ok"
  insta:
    driver_opts:
      type: cifs
      o: "username=xxxxx,password=xxxxxxx,rw"
      device: "//192.168.178.4/insta"
  mobil:
    driver_opts:
      type: cifs
      o: "username=xxxxx,password=xxxxxxx,rw"
      device: "//192.168.178.4/mobil_bilder"
  Immich:
    driver_opts:
      type: cifs
      o: "username=xxxxx,password=xxxxxxx,rw"
      device: "//192.168.178.4/Immich/"   
```
      
```
  Immich:
    driver_opts:
      type: cifs
      o: "username=xxxx,password=xxxxx,uid=1000,gid=1000,rw"
      device: "//192.168.178.4/Immich" 
```
also not working!

**Comment by DeltaTango69** [comment, marked as answer]
I have found a solution by myself. This only for anybody with the same problems :-)
The problem is the SMB share!
I have tried it with NFS with my mycloud system, this should be the address:

`# Bereitstellungspunkt: nfs://192.168.178.4/nfs/Immich`

```
  Immich:
    driver_opts:
      type: nfs
      o: "addr=192.168.178.4,rw"
      device: ":/nfs/Immich"
```
  
works for me now!
