### DISCUSSION TITLE
Permission Denied when viewing paticular files that were uploaded

### DISCUSSION THREAD

**Discussion by Youwenqwq** [immich-app/immich#11711] [Q&A]
Hi there,

I've been using immich as my personal gallery for a few weeks, everything works fine except the auto-backup files from my Android phone. When I'm trying to view photos that were uploaded from mobile phone on Chrome, it just shows "An error occured while loading the photo", with a error message in log:

```
[Nest] 16  - 08/12/2024, 7:06:16 AM    WARN [Api:ExpressAdapter~je2v4cmg] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 16  - 08/12/2024, 7:06:16 AM   ERROR [Api:ExceptionsHandler~je2v4cmg] EACCES: permission denied, access 'upload/library/admin/2024/2024-08-09/IMG_20240809_030026.jpg'
Error: EACCES: permission denied, access 'upload/library/admin/2024/2024-08-09/IMG_20240809_030026.jpg'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.downloadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:46:9)
```

The strange thing is, after opening the upload folder in WinSCP (takes the folder in the log as example: `upload/library/admin/2024/2024-08-09/`), every photo under this folder can be viewed in immich fluently. Also, open the specific photo (such as the IMG_20240809_030026.jpg below) can make this photo able to view in immich, but this doesn't have the same effect as in WinSCP that can make the whole folder works.

Since the photos uploaded (in the same folder as my phone uploaded) in Chrome can easily be viewed and downloaded, I don't know what caused this error.

These are informations of the immich-app's running environment:

**System**
1. Immich version: v1.111.0
2. Immich Android App version: 1.111.0 build.2152
3. Running in Docker Container in a LXC container (Ubuntu23.04) under Proxmox Virtual Environment 8.2.2
4. `/mnt/nas2` is a nfs mount point linked to a Synology NAS, I can confirm the LXC container has permission to read or write files.

**Docker Compose**
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: 1000:1000 # Tested that deleting this line and use root user doesn't help
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/nas2/netdisk/photos:/mnt/nas2/photos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri:/dev/dri
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    environment:
      - http_proxy=http://192.168.9.3:7890
      - https_proxy=http://192.168.9.3:7890
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always




  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

**.env**

```
UPLOAD_LOCATION=/mnt/nas2/netdisk/photos-immich
DB_DATA_LOCATION=/root/appdata/immich-app/database
IMMICH_VERSION=v1.111.0
DB_PASSWORD=**********
DB_USERNAME=**********
DB_DATABASE_NAME=immich
```
