### DISCUSSION TITLE
Connect Timeout when using smart search

### DISCUSSION THREAD

**Discussion by Ex0danify** [immich-app/immich#11752] [Q&A]
### The bug

When doing a simple search for example for "Garden", the Ffront end shows the following error:
![image](https://github.com/user-attachments/assets/b3a92b18-adf1-444b-9b86-8bb7680220f5)

I can see that the IP from the server logs for the search it's trying to connect to is different than the IP that the immich_machine_learning container is running on.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm) x86_64

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.107.1 build.146

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external 
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    ports:
      - 3003:3003
  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/data/photos/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

#External Library
EXTERNAL_PATH=<Redacted>
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<Redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Startup server via docker compose
2. Do a search on the web gui
3. Error
...
```

### Relevant log output

```shell
immich_server            | [Nest] 17  - 08/12/2024, 9:56:53 PM   ERROR [Api:Error: Machine learning request to "http://172.24.0.3:3003" failed with ConnectTimeoutError: Connect Timeout Error
immich_server            |     at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
immich_server            |     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
immich_server            |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~181a44nc] Failed to search smart
immich_server            | [Nest] 17  - 08/12/2024, 9:56:53 PM   ERROR [Api:Error: Machine learning request to "http://172.24.0.3:3003" failed with ConnectTimeoutError: Connect Timeout Error
immich_server            |     at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
immich_server            |     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
immich_server            |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~181a44nc] Error: Machine learning request to "http://172.24.0.3:3003" failed with ConnectTimeoutError: Connect Timeout Error
```

### Additional information

Docker inspect shows a different ip address than the immich server is trying to connect to. From the server log it seems the server tries a connection to **172.24.0.3:3003**, but the docker inspect output shows that immich_machine_learning is running with IP **172.30.0.4**

Network settings from immich_machine_learning, docker inspect output:

```json
{
            "Bridge": "",
            "SandboxID": "2b25d0f51a1678036b009f6be1940e0ac934125ef5161604c5a165dab74776ad",
            "SandboxKey": "/var/run/docker/netns/2b25d0f51a16",
            "Ports": {
                "3003/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3003"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "3003"
                    }
                ]
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "immich_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "immich_machine_learning",
                        "immich-machine-learning"
                    ],
                    "MacAddress": "02:42:ac:1e:00:04",
                    "NetworkID": "66c74015f640da114c841bc5d51ce3097094b65bcbcb632c82fe2cf9a1209632",
                    "EndpointID": "e2c481cc87209bc16dc357b9a0471beb201f88bb0a6170c9ea7cddee4b899edb",
                    "Gateway": "172.30.0.1",
                    "IPAddress": "172.30.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DriverOpts": null,
                    "DNSNames": [
                        "immich_machine_learning",
                        "immich-machine-learning",
                        "afe153bd0f81"
                    ]
                }
            }
        }
```
