### DISCUSSION TITLE
Assets not moved to library

### DISCUSSION THREAD

**Discussion by wardwygaerts** [immich-app/immich#11788] [Q&A] [answered]
Since a couple of days I noticed assets are not moved from upload to library anymore.
I took lots of pictures today, and they're all uploading fine in the upload directory, but not moved to the library. Can I check something else?
Pictures added via web ui, have the same issue.
```
16:46:56
[Nest] 7  - 08/14/2024, 4:46:56 PM     LOG [Microservices:MediaService] Successfully generated JPEG image preview for asset e447cddb-090b-42bd-a2fb-478f40ca89ae
16:46:57
[Nest] 7  - 08/14/2024, 4:46:57 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset e447cddb-090b-42bd-a2fb-478f40ca89ae
16:46:59
[Nest] 7  - 08/14/2024, 4:46:59 PM    WARN [Microservices:MediaService] Unable to complete move. File size mismatch: 0 !== 8710680
16:46:59
[Nest] 7  - 08/14/2024, 4:46:59 PM    WARN [Microservices:MediaService] Skipping move due to file size mismatch
```

**Comment by alextran1502** [comment]
Does this applied to all the assets?

**Reply by wardwygaerts** [reply]
All new assets indeed.

**Reply by alextran1502** [reply]
If you do `docker compose down` then `docker compose pull` and finally `docker compose up` then try uploading a new photo and see if it gets moved

**Reply by wardwygaerts** [reply]
Same behavior. 
Which data uses immich to compare the file sizes?
I did one change some days ago: because the location where my upload directory was located was  getting full, I moved it to another location (same NAS as where the encoded videos, thumbs and my actual library is located). My volumes are all cifs shares. The ones pointing to `/usr/src/app/upload/*` are subfolders in the sale directory but mounted seperately.
```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - pictures_immich:/usr/src/app/upload/library
      - immich_upload:/usr/src/app/upload/upload
      - immich_thumbs:/usr/src/app/upload/thumbs
      - $CONFIGDIR/immich/profile:/usr/src/app/upload/profile
      - immich_video:/usr/src/app/upload/encoded-video
      - pictures:/mnt/media/pictures:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    networks:
      - proxy
      - local
    depends_on:
      - redis
      - database
    restart: always
```
