### DISCUSSION TITLE
Search broken

### DISCUSSION THREAD

**Discussion by Qhilm** [immich-app/immich#11869] [Q&A]
#### Disclaimer

I had a smart search job running for a really long time (I picked too big a CLIP model I think) hence I don't exactly know when the search broke.

#### Issue

I get "Failed to Search Smart - Immich Server Error" when I search for anything (examples: "snow", "house"...)

#### Environment

* Synology DSM 7 (Docker 20.10)
* Portainer
* immich latest (1.112.1)

#### docker-compose.yml

```yaml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    user: '1037:100'
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    



  immich-machine-learning:
    user: '1037:100'
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
    #  - model-cache:/cache
      - ${MACHINE_LEARNING_CACHE_LOCATION}:/cache
      - ${MACHINE_LEARNING_DOTCACHE_LOCATION}:/.cache
      - ${MACHINE_LEARNING_DOTCONFIG_LOCATION}:/.config
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW

  redis:
    user: '1037:100'
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${REDIS_DATA_LOCATION}:/data
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW

  database:
    user: '1037:100'
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - stack.env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - /volume1/Photos/db_dumps:/db_dumps
    depends_on:
      - database

# volumes:
#   model-cache:
```

#### stack.env

```
UPLOAD_LOCATION=/volume1/Photos/
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/volume1/Photos/postgres/
MACHINE_LEARNING_CACHE_LOCATION=/volume1/Photos/machine-learning/cache/
MACHINE_LEARNING_DOTCACHE_LOCATION=/volume1/Photos/machine-learning/.cache/
MACHINE_LEARNING_DOTCONFIG_LOCATION=/volume1/Photos/machine-learning/.config/
REDIS_DATA_LOCATION=/volume1/Photos/redis/
```

#### Troubleshooting done so far

* `docker logs` on the immich-server container shows this, happening regularly:

```
[Nest] 17  - 08/17/2024, 11:58:40 AM   ERROR [Api:QueryFailedError: pgvecto.rs: Operands of the operator differs in dimensions or scalar type.
INFORMATION: left_dimensions = 512, right_dimensions = 1152
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async paginatedBuilder (/usr/src/app/dist/utils/pagination.js:44:19)
    at async /usr/src/app/dist/repositories/search.repository.js:98:23
    at async EntityManager.transaction (/usr/src/app/node_modules/typeorm/entity-manager/EntityManager.js:73:28)
    at async SearchRepository.searchSmart (/usr/src/app/dist/repositories/search.repository.js:82:9)~wjmenm0h] Failed to search smart
```

as well as:

```
[Nest] 7  - 08/17/2024, 9:48:42 AM   ERROR [Microservices:JobService] Unable to run job handler (duplicateDetection/duplicate-detection): QueryFailedError: pgvecto.rs: Operands of the operator differs in dimensions or scalar type.
INFORMATION: left_dimensions = 512, right_dimensions = 1152
[Nest] 7  - 08/17/2024, 9:48:42 AM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: Operands of the operator differs in dimensions or scalar type.
INFORMATION: left_dimensions = 512, right_dimensions = 1152
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
    at async DuplicateService.handleSearchDuplicates (/usr/src/app/dist/services/duplicate.service.js:86:33)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 08/17/2024, 9:48:42 AM   ERROR [Microservices:JobService] Object:
{
  "id": "db8a8cc4-a179-4700-a634-1731fd8c7ac5",
  "source": "upload"
}
```

**Comment by Qhilm** [comment]
One more thing I just noticed, my CLIP model ("nllb-clip-large-siglip__v1") is not listed anymore here:

https://huggingface.co/collections/immich-app/multilingual-clip-654eb08c2382f591eeb8c2a7

Is that normal?

**Comment by Qhilm** [comment]
So I decided to rerun the ML from scratch and see if it helps. I get different errors now, but it still does not work.

I set up remote machine learning because my laptop is like 10 times faster than my NAS for this:

```yaml
name: immich_remote_ml

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.ml.yml
    #   service: # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW

volumes:
  model-cache:
```

I'm using colima for the docker runtime, it's lighter, I don't need Docker Desktop:

`colima start --cpu 6 --memory 4 --disk 10`

`docker compose up` (I didn't detach to see the logs live for now)

I let it run a bit, it did 6000 images and then I did a search, and it fails in the GUI and I see this in the immich-server container logs (notice the "Failed to search smart" at the end):

```
[Nest] 7  - 08/18/2024, 3:41:45 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://192.168.1.10:3003" failed with SocketError: other side closed
[Nest] 7  - 08/18/2024, 3:41:45 AM   ERROR [Microservices:JobService] Error: Machine learning request to "http://192.168.1.10:3003" failed with SocketError: other side closed
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:129:27)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 08/18/2024, 3:41:45 AM   ERROR [Microservices:JobService] Object:
{
  "id": "ceed216c-4690-4f79-838d-9976c76a6360"
}

[Nest] 17  - 08/18/2024, 3:41:45 AM   ERROR [Api:Error: Machine learning request to "http://192.168.1.10:3003" failed with SocketError: other side closed
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
    at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:97:27)~ds8wp2ei] Failed to search smart
```
