### DISCUSSION TITLE
Thunmbnails and photos are not shown in web ui

### DISCUSSION THREAD

**Discussion by andonovski** [immich-app/immich#11940] [Q&A] [answered]
### The bug

Somewhere since June in web ui the thumbnails and photos are not shown. Photos older than June this year are shown properly in web ui. In Android app all photos are shown.

What is seen is web ui:
![image](https://github.com/user-attachments/assets/3eb0cdba-e5d6-427c-91bb-eb0934fcb921)

In server administration for jobs I see this:
![image](https://github.com/user-attachments/assets/28fe43e5-af3b-4638-801b-54b03631bd74)

In Android app I see these errors on log:
Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = https://photo.andonovski.net/api/assets/aac7a91e-0673-4b8f-8c04-e22bc5917889/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription'

Android phone is Samsung S23, Android app and Immich server are on latest version. The issue started few versions back it seems, I just haven't noticed before.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

1.112.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

#  immich-microservices:
#    container_name: immich_microservices
#    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
#    command: [ "start.sh", "microservices" ]
#    volumes:
#      - library:/usr/src/app/upload
#      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - .env
#    depends_on:
#      - redis
#      - database
#    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
#    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  library:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
#IMMICH_VERSION="1.92.1"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=SOMERANDOMPWD

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take a picture with phone Camera
2. Picture is uploaded to Immich
3. Picture is visible in Android Immich app
4. Login to web, the thumbnail or picture is not visible, just a image placeholder is present
...
```

### Relevant log output

```shell
Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 404, uri = https://photo.andonovski.net/api/assets/aac7a91e-0673-4b8f-8c04-e22bc5917889/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription'
```
