### DISCUSSION TITLE
When changing thumbnail folder, it defaults back to the previous folder a few hours after changing

### DISCUSSION THREAD

**Discussion by aaronjrodrigues** [immich-app/immich#11944] [Q&A]
### The bug

I followed this guide (https://immich.app/docs/guides/custom-locations/) to make thumbnails get stored on my ssd while my uploads and everything else get stored on my storage box. However I've noticed that it works fine for a few hours and then it reverts to storing the thumbnails on the storage box again.

I'm sure this is happening because I delete the thumbnail folder on the storage box multiple times but it comes back and it starts generating images in the old location again.

### The OS that Immich Server is running on

Ubuntu 22.04, ARM64

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
​
name: immich
​
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
​
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
​
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
​
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/ubuntu/gringotts/immich
THUMB_LOCATION=/home/ubuntu/immich/thumbs
# The location where your database files are stored
DB_DATA_LOCATION=/home/ubuntu/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Setup immich server using this guide (https://immich.app/docs/install/docker-compose). In this setup, assume by default the upload location is /library and as a result thumbs, uploads, etc will have the path have the path /libary/thumbs, /library/uploads.

2. Follow this guide https://immich.app/docs/guides/custom-locations/ and create a custom location for thumbnails ONLY. So now, assume we've set the custom location for thumbs to be /ssd/thumbs.

3. Delete the old thumbs folder at /library/thumbs and regenerate all thumbnails, so all new thumbnails will be created at /ssd/thumbs.

4. Wait for a few days and notice how Immich will revert to storing thumbs in the default location (/libary/thumbs) and all previously generated thumbnails for images wont be able to be viewed on immich web as it changed the thumbnail path back to the default one.

If you restart immich, it'll go back to using the new thumbnail folder however after a few hours it'll go back to the old thumbnail folder.

I've attached logs under 'Relevant log output' that shows the errors that Immich outputs when trying to view thumbnails after immich changed the thumbnail location back to the old one.
```

### Relevant log output

```shell
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:LoggerRepository~rzicjm2h] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/53/50/5350e04c-0b79-419d-ad82-ccf69e9ecdba-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM    WARN [Api:ExpressAdapter~rzicjm2h] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:ExceptionsHandler~rzicjm2h] ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/53/50/5350e04c-0b79-419d-ad82-ccf69e9ecdba-thumbnail.webp'
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/53/50/5350e04c-0b79-419d-ad82-ccf69e9ecdba-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:LoggerRepository~6sc8jmxy] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/c5/68/c568c02f-d58d-4f8a-ac38-dd98f20b7a58-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM    WARN [Api:ExpressAdapter~6sc8jmxy] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:ExceptionsHandler~6sc8jmxy] ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/c5/68/c568c02f-d58d-4f8a-ac38-dd98f20b7a58-thumbnail.webp'
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/c5/68/c568c02f-d58d-4f8a-ac38-dd98f20b7a58-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:LoggerRepository~37faqe7q] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/26/61/2661e9df-7aec-42c5-ac2e-04fcfe9836bc-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM    WARN [Api:ExpressAdapter~37faqe7q] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:ExceptionsHandler~37faqe7q] ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/26/61/2661e9df-7aec-42c5-ac2e-04fcfe9836bc-thumbnail.webp'
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/26/61/2661e9df-7aec-42c5-ac2e-04fcfe9836bc-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:LoggerRepository~nzebxe8f] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/13/cc/13cc06fa-9dc5-45e3-95b6-705b5fa835b8-thumbnail.webp'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 18  - 08/20/2024, 12:42:42 PM    WARN [Api:ExpressAdapter~nzebxe8f] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 18  - 08/20/2024, 12:42:42 PM   ERROR [Api:ExceptionsHandler~nzebxe8f] ENOENT: no such file or directory, access 'upload/thumbs/496d4685-9669-437e-a2e4-25324663b100/13/cc/13cc06fa-9dc5-45e3-95b6-705b5fa835b8-thumbnail.webp'
```
