### DISCUSSION TITLE
no space left on device

### DISCUSSION THREAD

**Discussion by msubodh** [immich-app/immich#11955] [Q&A]
I keep on getting the following error:

![image](https://github.com/user-attachments/assets/68997e0b-6a87-4f37-90f2-992626e96a66)

even though I seem to have enough space:

![image](https://github.com/user-attachments/assets/f2076c7a-fe1b-4c08-98f9-ff937590370b)

I am running in docker on ubuntu and the images should be uploaded to a USB drive. 

Here is my docker-compose.yml

```yml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${EXTERNAL_LIBRARY}:/usr/src/app/external_library
      - /etc/localtime:/etc/localtime:ro
      # - /mnt/amberx/ext/Munjal/Backup/Pictures/immich/upload:/usr/src/app/upload
      # - /mnt/amberx/ext/Munjal/Backup/Pictures:/usr/src/app/external_library
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/munjal/docker/immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    volumes:
      - ${REDIS_DATA}:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    restart: always
```

and here are the env (not showing some of the passwords)

```dotenv
# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/amberx/Munjal/Backup/Pictures/immich/upload
THUMB_LOCATION=/media/amberx/Munjal/Backup/Pictures/immich/upload/thumbs
ENCODED_VIDEO_LOCATION=/media/amberx/Munjal/Backup/Pictures/immich/upload/encoded-video
PROFILE_LOCATION=/media/amberx/Munjal/Backup/Pictures/immich/upload/profile
EXTERNAL_LIBRARY=/media/amberx/Munjal/Backup/Pictures/external_immich_library

# The location where your database files are stored
DB_DATA_LOCATION=/home/munjal/docker/immich/postgres

# Redis Data location
REDIS_DATA=/home/munjal/docker/immich/redis/data

# Config file
# IMMICH_CONFIG_FILE=/home/munjal/docker/immich/immich-config.json

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Lisbon

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=*****
DB_DATABASE_NAME=****
```
