### DISCUSSION TITLE
Running as Non Root Needs Documentation Update

### DISCUSSION THREAD

**Discussion by easymod0** [immich-app/immich#12017] [Q&A]
### The bug

Machine Learning will not run with the steps shown in : https://immich.app/docs/FAQ/#how-can-i-run-immich-as-a-non-root-user

There is a permission error thrown regarding the /cache folder, we need to add an extra volume to the docker compose file

In addition to:
immich-machine-learning:/.cache

I also needed to add:
immich-machine-learning:/cache

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    user: 1000:100
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    user: 1000:100
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
      - /appdata/immich/ml/config:/.config
      - /appdata/immich/ml/cache-hidden:/.cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    user: 1000:100
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    volumes:
      - /appdata/immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    user: 1000:100
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/appdata/immich/upload/
LIBRARY_LOCATION=/srv/mergerfs/pool1/backup/XXX/
THUMBS_LOCATION=/appdata/immich/thumbs/
PROFILE_LOCATION=/appdata/immich/profile/
VIDEO_LOCATION=/appdata/immich/encoded-video

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=XXX
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/appdata/immich/db

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Start docker containers with recommended volumes per wiki
2. Run facial recognition jobs and we see error attached
3. Need to add an additional volume: - /appdata/immich/ml/cache:/cache

  immich-machine-learning:
    container_name: immich_machine_learning
    user: 1000:100
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
      - /appdata/immich/ml/config:/.config
      - /appdata/immich/ml/cache-hidden:/.cache
      - /appdata/immich/ml/cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
```

### Relevant log output

```shell
[08/24/24 16:30:45] INFO     Starting gunicorn 22.0.0
[08/24/24 16:30:45] INFO     Listening at: http://[::]:3003 (9)
[08/24/24 16:30:45] INFO     Using worker: app.config.CustomUvicornWorker
[08/24/24 16:30:45] INFO     Booting worker with pid: 10
[08/24/24 16:30:49] INFO     Started server process [10]
[08/24/24 16:30:49] INFO     Waiting for application startup.
[08/24/24 16:30:49] INFO     Created in-memory cache with unloading after 300s
                             of inactivity.
[08/24/24 16:30:49] INFO     Initialized request thread pool with 24 threads.
[08/24/24 16:30:49] INFO     Application startup complete.
[08/24/24 16:31:20] INFO     Downloading detection model 'buffalo_l'. This may
                             take a while.
[08/24/24 16:31:20] WARNING  Failed to load detection model 'buffalo_l'.
                             Clearing cache.
[08/24/24 16:31:20] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist
[08/24/24 16:31:20] INFO     Downloading detection model 'buffalo_l'. This may
                             take a while.
[08/24/24 16:31:20] ERROR    Exception in ASGI application

                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:213 in load                │
                             │                                                 │
                             │   210 │   │   return model                      │
                             │   211 │                                         │
                             │   212 │   try:                                  │
                             │ ❱ 213 │   │   return await run(_load, model)    │
                             │   214 │   except (OSError, InvalidProtobuf, Bad │
                             │   215 │   │   log.warning(f"Failed to load {mod │
                             │       '{model.model_name}'. Clearing cache.")   │
                             │   216 │   │   model.clear_cache()               │
                             │                                                 │
                             │ /usr/src/app/main.py:188 in run                 │
                             │                                                 │
                             │   185 │   if thread_pool is None:               │
                             │   186 │   │   return func(*args, **kwargs)      │
                             │   187 │   partial_func = partial(func, *args, * │
                             │ ❱ 188 │   return await asyncio.get_running_loop │
                             │   189                                           │
                             │   190                                           │
                             │   191 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:200 in _load               │
                             │                                                 │
                             │   197 │   │   │   raise HTTPException(500, f"Fa │
                             │   198 │   │   with lock:                        │
                             │   199 │   │   │   try:                          │
                             │ ❱ 200 │   │   │   │   model.load()              │
                             │   201 │   │   │   except FileNotFoundError as e │
                             │   202 │   │   │   │   if model.model_format ==  │
                             │   203 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/app/models/base.py:50 in load          │
                             │                                                 │
                             │    47 │   │   │   return                        │
                             │    48 │   │   self.load_attempts += 1           │
                             │    49 │   │                                     │
                             │ ❱  50 │   │   self.download()                   │
                             │    51 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    52 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │    53 │   │   self.session = self._load()       │
                             │                                                 │
                             │ /usr/src/app/models/base.py:43 in download      │
                             │                                                 │
                             │    40 │   │   │   log.info(                     │
                             │    41 │   │   │   │   f"Downloading {self.model │
                             │       '{self.model_name}'. This may take a whil │
                             │    42 │   │   │   )                             │
                             │ ❱  43 │   │   │   self._download()              │
                             │    44 │                                         │
                             │    45 │   def load(self) -> None:               │
                             │    46 │   │   if self.loaded:                   │
                             │                                                 │
                             │ /usr/src/app/models/base.py:70 in _download     │
                             │                                                 │
                             │    67 │                                         │
                             │    68 │   def _download(self) -> None:          │
                             │    69 │   │   ignore_patterns = [] if self.mode │
                             │ ❱  70 │   │   snapshot_download(                │
                             │    71 │   │   │   f"immich-app/{clean_name(self │
                             │    72 │   │   │   cache_dir=self.cache_dir,     │
                             │    73 │   │   │   local_dir=self.cache_dir,     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/huggingf │
                             │ ace_hub/utils/_validators.py:114 in _inner_fn   │
                             │                                                 │
                             │   111 │   │   if check_use_auth_token:          │
                             │   112 │   │   │   kwargs = smoothly_deprecate_u │
                             │       has_token=has_token, kwargs=kwargs)       │
                             │   113 │   │                                     │
                             │ ❱ 114 │   │   return fn(*args, **kwargs)        │
                             │   115 │                                         │
                             │   116 │   return _inner_fn  # type: ignore      │
                             │   117                                           │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/huggingf │
                             │ ace_hub/_snapshot_download.py:265 in            │
                             │ snapshot_download                               │
                             │                                                 │
                             │   262 │   # In that case store a ref.           │
                             │   263 │   if revision != commit_hash:           │
                             │   264 │   │   ref_path = os.path.join(storage_f │
                             │ ❱ 265 │   │   os.makedirs(os.path.dirname(ref_p │
                             │   266 │   │   with open(ref_path, "w") as f:    │
                             │   267 │   │   │   f.write(commit_hash)          │
                             │   268                                           │
                             │ in makedirs:215                                 │
                             │ in makedirs:215                                 │
                             │ in makedirs:215                                 │
                             │ in makedirs:225                                 │
                             ╰─────────────────────────────────────────────────╯
                             PermissionError: [Errno 13] Permission denied:
                             '/cache/facial-recognition'

                             During handling of the above exception, another
                             exception occurred:

                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:152 in predict             │
                             │                                                 │
                             │   149 │   │   inputs = text                     │
                             │   150 │   else:                                 │
                             │   151 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 152 │   response = await run_inference(inputs │
                             │   153 │   return ORJSONResponse(response)       │
                             │   154                                           │
                             │   155                                           │
                             │                                                 │
                             │ /usr/src/app/main.py:175 in run_inference       │
                             │                                                 │
                             │   172 │   │   response[entry["task"]] = output  │
                             │   173 │                                         │
                             │   174 │   without_deps, with_deps = entries     │
                             │ ❱ 175 │   await asyncio.gather(*[_run_inference │
                             │   176 │   if with_deps:                         │
                             │   177 │   │   await asyncio.gather(*[_run_infer │
                             │   178 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /usr/src/app/main.py:169 in _run_inference      │
                             │                                                 │
                             │   166 │   │   │   except KeyError:              │
                             │   167 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   168 │   │   │   │   raise HTTPException(400,  │
                             │ ❱ 169 │   │   model = await load(model)         │
                             │   170 │   │   output = await run(model.predict, │
                             │   171 │   │   outputs[model.identity] = output  │
                             │   172 │   │   response[entry["task"]] = output  │
                             │                                                 │
                             │ /usr/src/app/main.py:217 in load                │
                             │                                                 │
                             │   214 │   except (OSError, InvalidProtobuf, Bad │
                             │   215 │   │   log.warning(f"Failed to load {mod │
                             │       '{model.model_name}'. Clearing cache.")   │
                             │   216 │   │   model.clear_cache()               │
                             │ ❱ 217 │   │   return await run(_load, model)    │
                             │   218                                           │
                             │   219                                           │
                             │   220 async def idle_shutdown_task() -> None:   │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:200 in _load               │
                             │                                                 │
                             │   197 │   │   │   raise HTTPException(500, f"Fa │
                             │   198 │   │   with lock:                        │
                             │   199 │   │   │   try:                          │
                             │ ❱ 200 │   │   │   │   model.load()              │
                             │   201 │   │   │   except FileNotFoundError as e │
                             │   202 │   │   │   │   if model.model_format ==  │
                             │   203 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/app/models/base.py:50 in load          │
                             │                                                 │
                             │    47 │   │   │   return                        │
                             │    48 │   │   self.load_attempts += 1           │
                             │    49 │   │                                     │
                             │ ❱  50 │   │   self.download()                   │
                             │    51 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    52 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │    53 │   │   self.session = self._load()       │
                             │                                                 │
                             │ /usr/src/app/models/base.py:43 in download      │
                             │                                                 │
                             │    40 │   │   │   log.info(                     │
                             │    41 │   │   │   │   f"Downloading {self.model │
                             │       '{self.model_name}'. This may take a whil │
                             │    42 │   │   │   )                             │
                             │ ❱  43 │   │   │   self._download()              │
                             │    44 │                                         │
                             │    45 │   def load(self) -> None:               │
                             │    46 │   │   if self.loaded:                   │
                             │                                                 │
                             │ /usr/src/app/models/base.py:70 in _download     │
                             │                                                 │
                             │    67 │                                         │
                             │    68 │   def _download(self) -> None:          │
                             │    69 │   │   ignore_patterns = [] if self.mode │
                             │ ❱  70 │   │   snapshot_download(                │
                             │    71 │   │   │   f"immich-app/{clean_name(self │
                             │    72 │   │   │   cache_dir=self.cache_dir,     │
                             │    73 │   │   │   local_dir=self.cache_dir,     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/huggingf │
                             │ ace_hub/utils/_validators.py:114 in _inner_fn   │
                             │                                                 │
                             │   111 │   │   if check_use_auth_token:          │
                             │   112 │   │   │   kwargs = smoothly_deprecate_u │
                             │       has_token=has_token, kwargs=kwargs)       │
                             │   113 │   │                                     │
                             │ ❱ 114 │   │   return fn(*args, **kwargs)        │
                             │   115 │                                         │
                             │   116 │   return _inner_fn  # type: ignore      │
                             │   117                                           │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/huggingf │
                             │ ace_hub/_snapshot_download.py:265 in            │
                             │ snapshot_download                               │
                             │                                                 │
                             │   262 │   # In that case store a ref.           │
                             │   263 │   if revision != commit_hash:           │
                             │   264 │   │   ref_path = os.path.join(storage_f │
                             │ ❱ 265 │   │   os.makedirs(os.path.dirname(ref_p │
                             │   266 │   │   with open(ref_path, "w") as f:    │
                             │   267 │   │   │   f.write(commit_hash)          │
                             │   268                                           │
                             │ in makedirs:215                                 │
                             │ in makedirs:215                                 │
                             │ in makedirs:215                                 │
                             │ in makedirs:225                                 │
                             ╰─────────────────────────────────────────────────╯
                             PermissionError: [Errno 13] Permission denied:
                             '/cache/facial-recognition'
```
