### DISCUSSION TITLE
Metrics no working in immich-server

### DISCUSSION THREAD

**Discussion by agutf** [immich-app/immich#12014] [Q&A]
### The bug

I've tried to setup Prometheus + Grafana for visualizing Immich metrics as described in [documentation](https://immich.app/docs/features/monitoring/), but the dashboard in Grafana did not show any data at all (I imported [this](https://github.com/friendlyFriend4000/prometheus-immich-exporter) one).

Then I added 8081:8081 to the server container's ports as stated in documentation to check what's happening and when I visit the `/metrics` endpoint the following message appears:

```
# failed to export metrics: Error: MetricReader is not bound to a MetricProducer
```

### The OS that Immich Server is running on

Docker on Debian 10

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
      - 8081:8081
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-prometheus:
    container_name: immich_prometheus
    ports:
      # this exposes the default port for Prometheus so you can interact with it
      - 9090:9090
    image: prom/prometheus
    volumes:
      # the Prometheus configuration file - a barebones one is provided to get started
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # a named volume defined in the bottom of the Compose file; it can also be a mounted folder
      - prometheus-data:/prometheus

  immich-grafana:
    container_name: immich_grafana
    command: ['./run.sh', '-disable-reporting'] # this is to disable Grafana's telemetry
    ports:
      - 3000:3000
    image: grafana/grafana
    volumes:
      # stores your pretty dashboards and panels
      - grafana-data:/var/lib/grafana

volumes:
  pgdata:
  model-cache:
  prometheus-data:
  grafana-data:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/docker/data/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=-

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

IMMICH_METRICS=true
```

### Reproduction steps

```bash
1. Follow documentation for showing metrics
2. Add 8081:8081 to the server container's ports
3. Visit /metrics endpoint
```
