### DISCUSSION TITLE
Cannot log into Immich server on mobile apps

### DISCUSSION THREAD

**Discussion by coryrearick9900** [immich-app/immich#12044] [General]
I can no longer log into my server on my mobile apps.  I type in my server address. email, and password correctly and I get an error reading "Error logging you in, check server URL, email and password".  I have attached some log entries below.  I hope someone can help shine some light on my issue.

![image](https://github.com/user-attachments/assets/9a7bc728-821b-419f-84fa-5257d1ecae84)
![image](https://github.com/user-attachments/assets/bbf17e95-a08d-4367-be34-a8d017180c03)
![image](https://github.com/user-attachments/assets/c1d06747-1b07-48dc-aa8b-7be03b949950)

**Comment by coryrearick9900** [comment]
I also tried to upgrade my server and that did not fix the issue.  Here is the output from running the upgrade command:
![image](https://github.com/user-attachments/assets/ec50d2c8-569f-4160-baf5-a9bc78c21df5)

**Reply by alextran1502** [reply]
What is your server version and your mobile app version? You still have immich-microservice, which means that you have a quite outdated docker-compose file

**Comment by coryrearick9900** [comment]
My server version is:
![image](https://github.com/user-attachments/assets/cf0ab13b-91fe-4d89-a033-0877eef064c5)

MY ios moibile app versions were updated fully recently from the app store, my phone's version is v1.112.1

I suppose that I could update my dockercompose file from the Immich site?

**Reply by alextran1502** [reply]
Please read this release note to update your docker-compose file https://github.com/immich-app/immich/releases/tag/v1.106.1

**Reply by coryrearick9900** [reply]
I am reading the documentation to attempt to fix this.  I removed the microservices section from my docker compose file and I moved the hardware acceleration extends section to the immich-server section however I am getting a couple error messages.

Either it cannot read hwaccel.transdoding.yml... 
```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      _extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding_
        _file: hwaccel.transcoding.yml_
        _service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding_
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
```

...or "mapping values are not allowed in this context".
_docker-compose.yml_:
```
services:
  immich-server:
    _extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding_
      _file: hwaccel.transcoding.yml_
      _service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding_
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
```

I have to be putting the extends section in the wrong place or I have the wrong number of indentations.  Do you have any imput as to which?
