### DISCUSSION TITLE
Unable to connect to the database

### DISCUSSION THREAD

**Discussion by zaqai** [immich-app/immich#12119] [Q&A]
### The bug

I have previously used Immich with docker and saved some data.
I followed your tips on docs and changed 'UPLOAD_LOCATION', 'DB_PASSWORD', 'DB_DATA_LOCATION'.
I got an error `[TypeOrmModule] Unable to connect to the database. Retrying (1),  error: could not open file "base/16384/2659": No such file or directory`
I'm sure `DB_PASSWORD` is correct because if I cahnged it, I will get an error about authentation.
btw, `DB_PASSWORD` contains special characters `.`, which I set before.

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/xb/backup/immich

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD="abc123."

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
immich_server            | [Nest] 17  - 08/29/2024, 4:28:22 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | error: could not open file "base/16384/2659": No such file or directory
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at addChunk (node:internal/streams/readable:559:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
immich_server            |     at Readable.push (node:internal/streams/readable:390:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
immich_server            | [Nest] 17  - 08/29/2024, 4:28:22 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich_server            | error: could not open file "base/16384/2659": No such file or directory
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at addChunk (node:internal/streams/readable:559:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
immich_server            |     at Readable.push (node:internal/streams/readable:390:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
immich_server            | [Nest] 17  - 08/29/2024, 4:28:22 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
```
