### DISCUSSION TITLE
Hardware Transcoding not work on J4205

### DISCUSSION THREAD

**Discussion by death4444** [immich-app/immich#12337] [Q&A] [answered]
### The bug

unraid v6.12.11 
docker version 24.0.9
![8355dc2857a37f8cdc5dc406e8afb34](https://github.com/user-attachments/assets/8c21ad26-f26f-4c33-847c-c652639081ca)
![image](https://github.com/user-attachments/assets/fab405d0-09f5-49c5-8398-fe76523854a6)
![image](https://github.com/user-attachments/assets/c19bfb5e-8dc7-4458-ba07-5dc0fc09f82c)

### The OS that Immich Server is running on

Linux 6.1.99-Unraid x86_64

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external #外部库路径
      - ${EXTERNAL_PATH_aries}:/usr/src/app/external_aries #外部库路径
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      # - model-cache:/cache
      - /mnt/user/immich/cache:/cache #自定义cache位置
    environment:
      - HTTP_PROXY=http://10.4.4.99:7890
      - HTTPS_PROXY=http://10.4.4.99:7890
    ports:
      - 3003:3003
    restart: always
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
networks: {}
```

### Your .env content

```Shell
#自定义的照片上传路径
UPLOAD_LOCATION=/mnt/user/immich/photo

#自定义的外部库路径，就是你本来在群晖备份的照片
EXTERNAL_PATH=/mnt/user/photo

EXTERNAL_PATH_aries=/mnt/user/homes/aries/Privacy

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
#自定义数据库路径
DB_DATA_LOCATION=/mnt/user/immich/data

REDIS_HOSTNAME=immich_redis

# 更改文件名为.env
```

### Reproduction steps

1.use compose.yaml to Deployment projects
2.Start scanning the gallery
3.Found that the GPU is not working
