### DISCUSSION TITLE
Some videos are unable to play both in Android app and web browser

### DISCUSSION THREAD

**Discussion by Hotwill** [immich-app/immich#12344] [Q&A]
### The bug

Some videos of my immich are unable to play both in Android and web browser. 
The videos are in external library. When a video is added to the external library, immich can discover the video, but sometimes can't play.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

v1.113.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/backups/immich_library
# The location where your database files are stored
DB_DATA_LOCATION=/volume1/backups/server/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=4t5t4trtrtr7aH6

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

HF_ENDPOINT=https://hf-mirror.com
```

### Reproduction steps

1. Add a video to external library
2. Play the video that was just added.
3. Sometimes the videos can play normally, and sometimes they cannot.

### Relevant log output

log of immich server when add a video to external library:

```
[Nest] 7  - 09/04/2024, 9:17:13 PM     LOG [Microservices:MediaService] Successfully generated JPEG image preview for asset /synology_homes/Photos/MobileBackup/Xiaomi 12/DCIM/Screenshots/2024/09/Screenshot_2024-09-04-14-59-18-779_com.tencent.mm.jpg
|stdout|2024-09-04T13:17:13.507352283Z
[Nest] 7  - 09/04/2024, 9:17:15 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset /synology_homes/Photos/MobileBackup/Xiaomi 12/DCIM/Screenshots/2024/09/Screenshot_2024-09-04-14-59-18-779_com.tencent.mm.jpg
|stdout|2024-09-04T13:17:15.142957660Z
[Nest] 7  - 09/04/2024, 9:17:26 PM     LOG [Microservices:MediaService] Started encoding video 3cf87d3f-7783-48c4-b8cb-dead8d34c71a {"inputOptions":[],"outputOptions":["-c:v h264","-c:a copy","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-v verbose","-vf scale=720:-2,format=yuv420p","-preset ultrafast","-crf 23","-maxrate 4500000","-bufsize 9000000"],"twoPass":false}
|stdout|2024-09-04T13:17:26.159126206Z
[Nest] 7  - 09/04/2024, 9:17:31 PM     LOG [Microservices:MediaService] Successfully generated JPEG video preview for asset /synology_homes/Photos/MobileBackup/Xiaomi 12/DCIM/Camera/2024/09/VID_20240904_201011.mp4
|stdout|2024-09-04T13:17:31.605999412Z
[Nest] 7  - 09/04/2024, 9:17:32 PM     LOG [Microservices:MediaService] Started encoding video 3cf87d3f-7783-48c4-b8cb-dead8d34c71a {"inputOptions":[],"outputOptions":["-c:v h264","-c:a copy","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-v verbose","-vf scale=720:-2,format=yuv420p","-preset ultrafast","-crf 23","-maxrate 4500000","-bufsize 9000000"],"twoPass":false}
|stdout|2024-09-04T13:17:32.178436540Z
[Nest] 7  - 09/04/2024, 9:17:36 PM     LOG [Microservices:MediaService] Successfully generated WEBP video thumbnail for asset /synology_homes/Photos/MobileBackup/Xiaomi 12/DCIM/Camera/2024/09/VID_20240904_201011.mp4
|stdout|2024-09-04T13:17:36.505687290Z
[Nest] 7  - 09/04/2024, 9:17:40 PM     LOG [Microservices:MediaService] Successfully encoded 3cf87d3f-7783-48c4-b8cb-dead8d34c71a
|stdout|2024-09-04T13:17:40.825533375Z
[Nest] 7  - 09/04/2024, 9:17:43 PM     LOG [Microservices:MediaService] Successfully encoded 3cf87d3f-7783-48c4-b8cb-dead8d34c71a
```
