### DISCUSSION TITLE
Upload is acting strange/unstable (from always) on Android and iOS

### DISCUSSION THREAD

**Discussion by lukanowa** [immich-app/immich#12357] [Q&A]
### The bug

I use Immich on Samsung TabActive 5 (Android 14) and iPhone 15 Pro. It works very well, but uploading is acting strange. It is worse on iOS than on Android.

iPhone first scenario:
1. I take photos and open Immich. Photos will appear on the timeline (need a couple of seconds), but upload is not starting. The upload icon is active, but when I open the upload detail, I see that the upload is still at 0%,
2. When I close Immich and reopen it upload is 100%. Photos have been marked as uploaded ((on the web these photos are visible), but the upload icon is still spinning,
3. I close Immich and open it again; everything is OK.

iPhone second scenario:
1. I take photos but open Immich sometime later (1 or 2 minutes later). Photos will appear on the timeline very quickly, upload is fast, and photos are marked as uploaded (on the web these photos are visible), but an icon of the upload is still spinning.
2. I closed Immich and reopened it again; everything is OK.

When I take photos and wait for background upload, it seems OK. After a time photos appear on web.

Android works much better. Photos are always uploaded right away, but the upload icon still spins like on an iPhone. 

Besides uploading, everything works very well, like deleting, creating albums, and viewing photos. Fast and no errors.

I use Immich only on proxy by external address (Ngnix Proxy Manager) but I tested in LAN on local address and it change nothing.

I having this problem as far as I remember, but some older version of Immich (mobile) worked better.

Uploading from the web (external proxy address) works very fast and has no problems.

Now I use Unraid and Ngnix Proxy Manager but before I used Synology DSM and Synology internal proxy server. On both setup it works the same.

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.113.1

### Version of Immich Mobile App

1.113.1 build 172

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: Immich-SRV
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: Immich-MLR
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/user/appdata/immich-model:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: Immich-RDS
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: Immich-DB
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.3.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
volumes:
  immich-model:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/user/appdata/immich-photos

IMMICH_VERSION=release

DB_PASSWORD=redacted

DB_HOSTNAME=redacted
DB_USERNAME=redacted
DB_DATABASE_NAME=redacted
DB_DATA_LOCATION=/mnt/user/appdata/immich-pgdata


REDIS_HOSTNAME=immich-rds

MACHINE_LEARNING_PRELOAD__CLIP=XLM-Roberta-Large-ViT-H-14__frozen_laion5b_s13b_b90k
```

### Reproduction steps

Detailed decriptions on top.
