### DISCUSSION TITLE
[BUG] Image appears in wrong date on timeline but has correct date and time when inspecting metadata

### DISCUSSION THREAD

**Discussion by spmdgit** [immich-app/immich#12368] [Q&A]
### The bug

Thank you for developing this wonderful app! In anticipation of doing a CLI upload of a large library of 10k pictures downloaded from iCloud, I uploaded a few test images using the browser and came across a date / time issue that I don't see reported yet. An image with a timestamp from the evening posts in the timeline as having been taken on the following day even though the metadata listed in the image view is correct. I believe this is related to a timezone / UTC issue, and I tried to replicated this on the demo server, but when I uploaded the image there, it posts on the correct date but the metadata lists the incorrect time for the image.

You can see this demonstrated in the images below. Here are three images, the first one was actually taken the day before and the following two were taken on the dates listed. 
![1](https://github.com/immich-app/immich/assets/51379768/1e3a30b8-c57d-4f9c-b452-cef9bfd9ae4d)

You can see the correct time and date for each image on the metadata listed in the image view on the next three screenshots.
![2](https://github.com/immich-app/immich/assets/51379768/f522f99b-b309-4061-bb40-28bf8251d9fc)
![3](https://github.com/immich-app/immich/assets/51379768/fb79a1ec-eaf3-4fb6-898d-7f8adf1f6514)
![4](https://github.com/immich-app/immich/assets/51379768/ce653480-320a-4267-9da3-66ed129ca83a)

I believe that if the last image had been taken after 7pm, it would have been placed on the following date in the timeline similar to the way the first image was handled.

As mentioned above, the demo server doesn't replicate this exactly, but the metadata represented there isn't correct either (maybe because I have the TZ environment variable set to US/Central in my .env file and the demo server is using UTC?). Anyway, here's how it looks on the demo server:

![5](https://github.com/immich-app/immich/assets/51379768/74d6cc01-c442-4186-97ee-f0b92c77b8b3)
![6](https://github.com/immich-app/immich/assets/51379768/5df16433-942e-477e-9589-a469943c49b4)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.88.2

### Version of Immich Mobile App

v1.88.0

### Platform with the issue

- [X] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/second/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=
DB_PASSWORD=

#TIMEZONE
TZ="US/Central"

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=simple

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Set TZ in .env file to proper timezone
2.Upload image that would be categorized as having a date on the next day if it was interpreted in UTC
3.Image should have the proper time and date in the metadata on the image view but will be placed in the incorrect date on the timeline
...
```

### Additional information

I should say also that I refreshed the metadata for the miscategorized image, and it didn't change anything.
