### DISCUSSION TITLE
Video Larger than 22GB fails to upload

### DISCUSSION THREAD

**Discussion by pug306d** [immich-app/immich#12410] [Q&A]
### The bug

I have a video recorded on my iPhone 13, 4K 60FPS that is 27GB in size and when I try to upload it using the iOS app it fails to upload.  I have tried with the web interface and it gets to 75-80% and also fails.  I also tried the CLI and although it reports it uploaded successfully it did not.

All of these attempts to upload leaves files in the /usr/src/app/upload/upload/<random folder name> folder, the largest being 22GB so I assume there is a limit somewhere of 22GB on the upload?

I am not using a proxy and directly connecting to the immch_server container port for the uploads.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4 build 132

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    environment:
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD: MYPASSWORD
      UPLOAD_LOCATION: ./library
      IMMICH_VERSION: release
    volumes:
      - /mnt/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    environment:
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      DB_PASSWORD: MYPASSWORD
      UPLOAD_LOCATION: ./library
      IMMICH_VERSION: release
    volumes:
      - /mnt/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    environment:
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
Included above in compose file above.
```

### Reproduction steps

```bash
1. Upload 27gb video file using mobile app
2. Upload 27gb video file using web interface
3. Upload 27gb video file using CLI
4. Confirm the file was not uploaded and that the uploaded file is partially uploaded to the upload folder.
```
