### DISCUSSION TITLE
Files above ~210MB get stuck

### DISCUSSION THREAD

**Discussion by KuramaSyu** [immich-app/immich#12564] [Q&A]
### The bug

Hi,

the bug occures, when immich tries to sync a video file which has a size of 230MB. It gets stuck at 93% with 210MB. I tried it multiple times. Photos work like expected. 
Since I searched for similar issues, I often found, that the reverse proxy should be the issue.
This is my setup:
DNS: Cloudflare (Cloudflare Proxy is disabled, hence it should not fail there)
Reverse Proxy: Traefk (Has no max body size per default)

This is the log from immich:
```
immich_server            | 2024-09-11T08:17:57.319844000Z [Nest] 17  - 09/11/2024, 10:17:57 AM     LOG [Api:EventRepository] Websocket Connect:    Ik1zspE11XYMIEZCAABR
immich_server            | 2024-09-11T08:20:35.616816000Z [Nest] 17  - 09/11/2024, 10:20:35 AM   ERROR [Api:LoggerRepository~vlw93mg6] Unable to send file: Error
immich_server            | 2024-09-11T08:20:35.617443000Z Error: ENOENT: no such file or directory, access 'upload/thumbs/ced8824d-7d61-4d21-9ac0-39d463e8a47d/90/19/9019b13b-b0f4-4cb5-8b50-9aa4f850f077-thumbnail.webp'
immich_server            | 2024-09-11T08:20:35.617547000Z     at async access (node:internal/fs/promises:606:10)
immich_server            | 2024-09-11T08:20:35.617614000Z     at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
immich_server            | 2024-09-11T08:20:35.617677000Z     at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
immich_server            | 2024-09-11T08:20:35.617770000Z [Nest] 17  - 09/11/2024, 10:20:35 AM   ERROR [Api:GlobalExceptionFilter~vlw93mg6] Unknown error: Error: ENOENT: no such file or directory, access 'upload/thumbs/ced8824d-7d61-4d21-9ac0-39d463e8a47d/90/19/9019b13b-b0f4-4cb5-8b50-9aa4f850f077-thumbnail.webp'
```

App Error:
```
Flutter Error - Catch All

Instance of 'FlutterErrorDetails'
Exception: HttpException: Invalid statusCode: 500, uri = https://pictures.domain.com/api/assets/9019b13b-b0f4-4cb5-8b50-9aa4f850f077/thumbnail?size=thumbnail
Library: image resource service
Context: Instance of 'ErrorDescription'
```

### The OS that Immich Server is running on

fedora 40

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0 build.158

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    networks:
      - proxy
      - default
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      com.centurylinklabs.watchtower.enable: false
      traefik.enable: true
      traefik.http.routers.immitch.entrypoints: websecure
      traefik.http.routers.immitch.rule: Host(`pictures.domain.com`)
      traefik.http.services.immitch.loadbalancer.server.port: 3001
      traefik.http.routers.immitch.middlewares: error-pages-middleware

  immich-machine-learning:
    container_name: immich_machine_learning
    networks:
      - default
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    networks:
      - default
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/nas/immich
# The location where your database files are stored
DB_DATA_LOCATION=./data/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Install immich with docker on fedora server
2. use traefik as reverse proxy and cloudflare as DNS provider
3. Try to send a file from Mobile (in my case Pixel 6) which exceeds 210MB
...

### Relevant log output

```shell
immich_server            | 2024-09-11T08:17:57.319844000Z [Nest] 17  - 09/11/2024, 10:17:57 AM     LOG [Api:EventRepository] Websocket Connect:    Ik1zspE11XYMIEZCAABR
immich_server            | 2024-09-11T08:20:35.616816000Z [Nest] 17  - 09/11/2024, 10:20:35 AM   ERROR [Api:LoggerRepository~vlw93mg6] Unable to send file: Error
immich_server            | 2024-09-11T08:20:35.617443000Z Error: ENOENT: no such file or directory, access 'upload/thumbs/ced8824d-7d61-4d21-9ac0-39d463e8a47d/90/19/9019b13b-b0f4-4cb5-8b50-9aa4f850f077-thumbnail.webp'
immich_server            | 2024-09-11T08:20:35.617547000Z     at async access (node:internal/fs/promises:606:10)
immich_server            | 2024-09-11T08:20:35.617614000Z     at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
immich_server            | 2024-09-11T08:20:35.617677000Z     at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
immich_server            | 2024-09-11T08:20:35.617770000Z [Nest] 17  - 09/11/2024, 10:20:35 AM   ERROR [Api:GlobalExceptionFilter~vlw93mg6] Unknown error: Error: ENOENT: no such file or directory, access 'upload/thumbs/ced8824d-7d61-4d21-9ac0-39d463e8a47d/90/19/9019b13b-b0f4-4cb5-8b50-9aa4f850f077-thumbnail.webp'
```

**Comment by bo0tzz** [comment]
The errors you've posted are about trying to view a thumbnail, and have nothing to do with uploading.

**Comment by mmomjian** [comment]
Traefik may not have a max body size but it does have a timeout by default, which serves functionally the same purpose. You should increase it.

**Comment by KuramaSyu** [comment]
Ok, thanks for the info that there is a default timeout. I found out, that it's at 60s. Now is the question, if there is any "nice" way to increase the timeout. The only solution I found after trying quite a lot is this:
increasing the transport times for the :443 port under `transport` in the `traefik.yaml`:
```yaml
entryPoints:
  websecure:
    address: :443
    AsDefault: true
    http:
      # middlewares:
      #  - error-pages-service
      tls:
        certresolver: cloudflare-resolver
        domains:
          - main: "*.domain.com"
            sans: 
              - "domain.com"
    transport:
      respondingTimeouts:
        readTimeout: 500s 
        writeTimeout: 500s
        idleTimeout: 300s 
```
With this it works at least. But I would prefer to just define it for the immich service. Is there a way to do so?

Also: I would add a small entry for how to configure traefik in the documentation or somewhere else, since it's a common setup, especially when using docker-compose, imo
