### DISCUSSION TITLE
immich-cli docker exiting with error

### DISCUSSION THREAD

**Discussion by Sithuk** [immich-app/immich#12639] [Q&A] [answered]
### The bug

The immich-cli docker container creates ok, but it exits with error. 

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

1.114.0 build.173

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich_cli

services:

  immich-cli:

    container_name: immich-cli

    image: 'ghcr.io/immich-app/immich-cli:latest'

    restart: on-failure:1

    environment:

      IMMICH_INSTANCE_URL: http://[REDACTED]:2283/api

      IMMICH_API_KEY: [REDACTED]

    volumes:

      - ./import:/import:ro
```

### Your .env content

```Shell
Do not use .env with the immich-cli docker.
```

### Reproduction steps

1. Create the docker compose file.
2. sudo docker compose up -d

...
