### DISCUSSION TITLE
Can not start immich server after upgrade.

### DISCUSSION THREAD

**Discussion by mrtatg** [immich-app/immich#12647] [Q&A] [answered]
### The bug

Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:48:28 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 09/13/2024, 6:48:29 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:48:29 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:48:44 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:48:44 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:49:01 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:49:01 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:48:44 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:49:00 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:49:16 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:49:32 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:49:48 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:50:05 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
[Nest] 7  - 09/13/2024, 6:49:17 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:49:17 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:49:33 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:49:33 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:49:49 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:49:49 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:50:05 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:50:05 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
Starting microservices worker
[Nest] 6  - 09/13/2024, 6:50:21 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:50:37 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 6  - 09/13/2024, 6:50:21 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:50:38 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:50:38 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:50:54 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:50:54 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
[Nest] 7  - 09/13/2024, 6:51:10 PM   ERROR [Microservices:StorageService] Failed to read upload/profile/.immich: Error: ENOENT: no such file or directory, open 'upload/profile/.immich'
[Nest] 7  - 09/13/2024, 6:50:54 PM     LOG [Microservices:EventRepository] Initialized websocket server
Detected CPU Cores: 4
Starting microservices worker
[Nest] 7  - 09/13/2024, 6:51:10 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 09/13/2024, 6:51:10 PM   ERROR [Microservices:StorageService] The "profile" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/profile")
microservices worker exited with code 1
Detected CPU Cores: 4
Starting microservices worker

### The OS that Immich Server is running on

Docker Desktop v.4.43.2 on Mac OS 12.7.6 (21H1320)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

app on iOS v.1.114.0 build 173

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
# Default libraryy location
#UPLOAD_LOCATION=./library

#Change to external HDD 
#UPLOAD_LOCATION=/Volumes/500G_WTLT/photo_app/immich-app/library

# Change Ligrary Location to USB 4TB Seagate 07 June 2024
# UPLOAD_LOCATION=/Volumes/1T22SG4T/photo_app/immich-app/library

# Change Ligrary Location  15 Jul 2024 
###################################################################################
# Upload File Location Library , encoded-video, profile, thumbs and upload
#
# This is the location where uploaded files are stored.
###################################################################################

# 28 Jul 2024 Change thumbs, profile,encoded-video to U5XY_WD2T
#THUMBS_LOCATION=/Volumes/U5XY_WD2T/photo_app/immich-app/library/thumbs/
#PROFILE_LOCATION=/Volumes/U5XY_WD2T/photo_app/immich-app/library/profile/
#VIDEO_LOCATION=/Volumes/U5XY_WD2T/photo_app/immich-app/library/encoded-video/


# 6 Aug 2024  Move Data to 12TB  naem 8DN0SG12T


#LIBRARY_LOCATION=/Volumes/1T22SG4T/photo_app/immich-app/library/library/
#UPLOAD_LOCATION=/Volumes/1T22SG4T/photo_app/immich-app/library/upload/


# 12 Sep 2024 Add 1T22SG4T for encoded-video, profile and thumbs and point them from 8DN0SG12T to 1T22SG4T

#THUMBS_LOCATION=/Volumes/8DN0SG12T/photo_app/immich-app/library/thumbs/
#PROFILE_LOCATION=/Volumes/8DN0SG12T/photo_app/immich-app/library/profile/
#VIDEO_LOCATION=/Volumes/8DN0SG12T/photo_app/immich-app/library/encoded-video2/
PROFILE_LOCATION=/Users/tatg/Documents/photo_app/immich-app/library/profile

VIDEO_LOCATION=/Volumes/1T22SG4T/photo_app/immich-app/library/encoded-video/
#PROFILE_LOCATION=/Volumes/1T22SG4/photo_app/immich-app/library/profile/
THUMBS_LOCATION=/Volumes/1T22SG4T/photo_app/immich-app/library/thumbs/


LIBRARY_LOCATION=/Volumes/8DN0SG12T/photo_app/immich-app/library/library/
UPLOAD_LOCATION=/Volumes/8DN0SG12T/photo_app/immich-app/library/upload/



#LIBRARY_LOCATION=/mnt/user/Immich/
#THUMBS_LOCATION=/mnt/apps/Immich-Cache/thumbs/
#UPLOAD_LOCATION=//mnt/apps/Immich-Cache/upload/
#PROFILE_LOCATION=/mnt/apps/Immich-Cache/profile/
#VIDEO_LOCATION=/mnt/apps/Immich-Cache/encoded-video/


# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# 31 May 2024 Time zone BKK 
#TIMEZONE
#TZ="US/Central"
TZ="Asia/Bangkok"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres180723472

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upgrade Docker Desktop to latest v.4.43.2 - Server is running after start
2. Upgrade immich server to  v1.115.0 - Server is not running after start - there error shown in immich_microservices log on Decker Desktop about Failed to read upload/profile/.immich 
3. Try to restore database from backup before update Docker and immich server , the issue still.
