### DISCUSSION TITLE
After selecting Custom Upload Location, immich_server container fails to start

### DISCUSSION THREAD

**Discussion by kwykwyk** [immich-app/immich#12743] [Q&A]
``I installed immich via docker compose

When using the default upload location in the .env file (i.e. #UPLOAD_LOCATION=./library), I am able to launch immich without any issues

I am trying to point my upload location to an external drive mounted to my RPi4

I've made the following adjustments to the **docker-compose.yml** file

```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app//upload/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:


```

changes to the **.env** file

```
# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
UPLOAD_LOCATION=/mnt/hdd/immich/library
THUMB_LOCATION=/mnt/hdd/immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/hdd/immich/encoded-video
PROFILE_LOCATION=/mnt/hdd/immich/profile
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich


```

This is the **error log** from my immich_server container

```

Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 09/16/2024, 3:13:13 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 09/16/2024, 3:13:14 AM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
[Nest] 7  - 09/16/2024, 3:13:14 AM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 7  - 09/16/2024, 3:13:14 AM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
[Nest] 7  - 09/16/2024, 3:13:14 AM     LOG [Microservices:ServerService] Feature Flags: {
  "smartSearch": true,
  "facialRecognition": true,
  "duplicateDetection": true,
  "map": true,
  "reverseGeocoding": true,
  "importFaces": false,
  "sidecar": true,
  "search": true,
  "trash": true,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false,
  "email": false
}
[Nest] 7  - 09/16/2024, 3:13:15 AM     LOG [Microservices:StorageService] Verifying system mount folder checks
[Nest] 7  - 09/16/2024, 3:13:15 AM   ERROR [Microservices:StorageService] Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'
microservices worker error: Error: Failed to validate folder mount (read from "<MEDIA_LOCATION>/encoded-video")
microservices worker exited with code 1

```

I've mounted the drive with the path /mnt/hdd

```

pi@raspberrypi:~/immich $ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.6G     0  1.6G   0% /dev
tmpfs           380M  1.6M  378M   1% /run
/dev/sda2       235G  9.8G  213G   5% /
tmpfs           1.9G  2.2M  1.9G   1% /dev/shm
tmpfs           5.0M   16K  5.0M   1% /run/lock
/dev/sdb1       1.9T  352K  1.9T   1% /mnt/hdd
/dev/sda1       510M   76M  435M  15% /boot/firmware
tmpfs           380M   40K  380M   1% /run/user/1000

```

I've mostly followed this [guide](https://immich.app/docs/guides/custom-locations), is there a step I'm missing or something I did incorrectly??
