### DISCUSSION TITLE
Generation of thumbnails and previews seems infinite.

### DISCUSSION THREAD

**Discussion by BAMingMayo** [immich-app/immich#12777] [Q&A]
### The bug

After scanning an external library, the system generated thumbnails, it then scans the thumbnails, and generates thumbnails, and keeps doing this.  My library has 254,000 assets and the system reported 1,243,344 assets after two days.  I have since turned off the system until I can figure out why it is doing this.  I can turn it back on and provide any logging information that you may need if you can point me to them.

### The OS that Immich Server is running on

Docker on Ubuntu Server 22.04

### Version of Immich Server

1.115

### Version of Immich Mobile App

1.115

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/MegaBox/homes/feeds/Drive/Moments/immich/library
DB_DATA_LOCATION=/home/immich-app/postgres
IMMICH_VERSION=release
DB_PASSWORD=********
DB_USERNAME=********
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Added external library (/mnt/MegaBox/homes/feeds/Drive/Moments
2.  Scanned it with exclusion of all @eaDir (Synology Moments files)
3.  Finished scanning after several hours.
4.  A day later it started scanning again after I uploaded some photos from my phone.
5.  Two days later I noticed the server was red lining on memory and CPU, found asset count had ballooned to 1.2 million.
6.  Explored the library and found thumbnails now being treated as new images and it was generating more thumbnails for existing thumbnails.  It was like it was stuck in a loop.
...

### Relevant log output

```shell
[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 17c453be-ded0-4889-84f9-b1f785b90919 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 17c453be-ded0-4889-84f9-b1f785b90919 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 2b4cef37-057c-4c71-967b-8c9ac60eb668 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 2b4cef37-057c-4c71-967b-8c9ac60eb668 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 6cfcd9ee-03b5-4104-b015-878e92313090 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:17 PM    WARN [Microservices:MetadataService] Asset 6cfcd9ee-03b5-4104-b015-878e92313090 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 194dfaae-d416-4d4b-8e41-c7d61fe7a05a has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 194dfaae-d416-4d4b-8e41-c7d61fe7a05a has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 0ad69636-6be6-4966-9999-4343ac329959 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 0ad69636-6be6-4966-9999-4343ac329959 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 69fef48d-5518-4356-a05d-e322402fb9b0 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 69fef48d-5518-4356-a05d-e322402fb9b0 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 01b78ab1-da58-4876-ba3d-e6635c3926a8 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 01b78ab1-da58-4876-ba3d-e6635c3926a8 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 0b488d3d-7501-423a-85c9-e4a693b1e33c has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 0b488d3d-7501-423a-85c9-e4a693b1e33c has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 2d097e51-481a-4cad-a5bf-aa600bfc9343 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset 2d097e51-481a-4cad-a5bf-aa600bfc9343 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset a260667a-cc2c-4ed4-80c1-e6fe5ceb5e65 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:18 PM    WARN [Microservices:MetadataService] Asset a260667a-cc2c-4ed4-80c1-e6fe5ceb5e65 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 4a78c4b3-7830-4300-92af-c0cd511aa31a has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 4a78c4b3-7830-4300-92af-c0cd511aa31a has no time zone information

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 486b3d37-9274-412e-ba68-3e8ffad5b638 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 486b3d37-9274-412e-ba68-3e8ffad5b638 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 30444838-86b8-42e8-9a37-bf7b3af71bc0 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 30444838-86b8-42e8-9a37-bf7b3af71bc0 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset ad50e3f9-4b65-43f5-9f43-c26b5a6f6881 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset ad50e3f9-4b65-43f5-9f43-c26b5a6f6881 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 41014c25-38f0-4fb0-96b1-96b9fb93d40b has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:19 PM    WARN [Microservices:MetadataService] Asset 41014c25-38f0-4fb0-96b1-96b9fb93d40b has no time zone information

[Nest] 7  - 09/18/2024, 4:25:21 PM    WARN [Microservices:MetadataService] Asset 4a09525d-2427-4ec1-a908-77232c34cbd3 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:21 PM    WARN [Microservices:MetadataService] Asset 4a09525d-2427-4ec1-a908-77232c34cbd3 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:21 PM    WARN [Microservices:MetadataService] Asset 6f66a31f-1b50-4ea4-9e5f-5425cb83b660 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:21 PM    WARN [Microservices:MetadataService] Asset 6f66a31f-1b50-4ea4-9e5f-5425cb83b660 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:22 PM    WARN [Microservices:MetadataService] Asset 552b00a9-dea4-4321-af87-82662901d5a8 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:22 PM    WARN [Microservices:MetadataService] Asset 552b00a9-dea4-4321-af87-82662901d5a8 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:23 PM    WARN [Microservices:MetadataService] Asset 3a2b569a-0769-49a3-abdd-22d3bcd15f58 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:23 PM    WARN [Microservices:MetadataService] Asset 3a2b569a-0769-49a3-abdd-22d3bcd15f58 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:24 PM    WARN [Microservices:MetadataService] Asset 17bf26c9-0af3-4b5f-a0b8-5e7da39304ce has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:24 PM    WARN [Microservices:MetadataService] Asset 17bf26c9-0af3-4b5f-a0b8-5e7da39304ce has no time zone information

[Nest] 7  - 09/18/2024, 4:25:24 PM    WARN [Microservices:MetadataService] Asset 24bc6426-4c39-44f1-9864-3ffa98431046 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:24 PM    WARN [Microservices:MetadataService] Asset 24bc6426-4c39-44f1-9864-3ffa98431046 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:25 PM    WARN [Microservices:MetadataService] Asset 183cd3b1-409a-4ee2-9fcd-eabbd49b3151 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:25 PM    WARN [Microservices:MetadataService] Asset 183cd3b1-409a-4ee2-9fcd-eabbd49b3151 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset 51fa7787-8428-458e-89e8-26fbf8906bfe has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset 51fa7787-8428-458e-89e8-26fbf8906bfe has no time zone information

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset dc42cd89-d7b7-4e8a-8063-2bffcf087832 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset dc42cd89-d7b7-4e8a-8063-2bffcf087832 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset a09ba41b-eed7-445c-99b7-608120909826 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset a09ba41b-eed7-445c-99b7-608120909826 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset ea3ee6e4-769b-485a-91b5-0a34b1101920 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset ea3ee6e4-769b-485a-91b5-0a34b1101920 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset b857b8aa-8cdc-4abb-8806-eb95445be3c5 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:26 PM    WARN [Microservices:MetadataService] Asset b857b8aa-8cdc-4abb-8806-eb95445be3c5 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 97e204b0-b8db-4c89-a5e1-2d0e755407a5 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 97e204b0-b8db-4c89-a5e1-2d0e755407a5 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 9d6aedb5-7a31-451a-abab-db38885179db has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 9d6aedb5-7a31-451a-abab-db38885179db has no time zone information

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 161ecf3d-2fbe-4806-bd8d-7cba1e7bcf0d has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 161ecf3d-2fbe-4806-bd8d-7cba1e7bcf0d has no time zone information

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 1197f653-be6b-4197-93ed-d1f4b828efeb has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 1197f653-be6b-4197-93ed-d1f4b828efeb has no time zone information

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 9e1d8eb8-9ee9-45d0-9cfe-6cab38e68e9b has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:28 PM    WARN [Microservices:MetadataService] Asset 9e1d8eb8-9ee9-45d0-9cfe-6cab38e68e9b has no time zone information

[Nest] 7  - 09/18/2024, 4:25:30 PM    WARN [Microservices:MetadataService] Asset 80545957-9ddb-4932-b6c2-01efd6843b1e has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:30 PM    WARN [Microservices:MetadataService] Asset 80545957-9ddb-4932-b6c2-01efd6843b1e has no time zone information

[Nest] 7  - 09/18/2024, 4:25:31 PM    WARN [Microservices:MetadataService] Asset ba56fd8b-01ad-4f65-b917-41cfac82965a has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:31 PM    WARN [Microservices:MetadataService] Asset ba56fd8b-01ad-4f65-b917-41cfac82965a has no time zone information

[Nest] 7  - 09/18/2024, 4:25:31 PM    WARN [Microservices:MetadataService] Asset 46f585c6-255b-444b-bfca-b3a16ab1ead9 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:31 PM    WARN [Microservices:MetadataService] Asset 46f585c6-255b-444b-bfca-b3a16ab1ead9 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 28f6340d-92a3-4ff3-9474-a84b186a1ada has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 28f6340d-92a3-4ff3-9474-a84b186a1ada has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 801875f3-a680-4861-b7e1-17aa5416273f has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 801875f3-a680-4861-b7e1-17aa5416273f has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset b9651918-319a-40cc-9a00-62f5c7200229 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset b9651918-319a-40cc-9a00-62f5c7200229 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset ba3294b6-4c16-4910-8d94-83d94c0f7e45 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset ba3294b6-4c16-4910-8d94-83d94c0f7e45 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset afabcb73-99ea-4bf5-9467-9e590ca5a1c1 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset afabcb73-99ea-4bf5-9467-9e590ca5a1c1 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 0eabfd05-2d3d-41d9-a106-f0d5dfa1633c has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:33 PM    WARN [Microservices:MetadataService] Asset 0eabfd05-2d3d-41d9-a106-f0d5dfa1633c has no time zone information

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 3812917e-caf0-498d-ba09-9813fefbfb72 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 3812917e-caf0-498d-ba09-9813fefbfb72 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 105f2a4e-b752-418c-a1e6-c84149b4be1b has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 105f2a4e-b752-418c-a1e6-c84149b4be1b has no time zone information

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 81c80b07-eb68-40ed-a569-7630d1879a0f has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:35 PM    WARN [Microservices:MetadataService] Asset 81c80b07-eb68-40ed-a569-7630d1879a0f has no time zone information

[Nest] 7  - 09/18/2024, 4:25:36 PM    WARN [Microservices:MetadataService] Asset 22124838-7948-4618-83b4-6c948dcc9f02 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:36 PM    WARN [Microservices:MetadataService] Asset 22124838-7948-4618-83b4-6c948dcc9f02 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:37 PM    WARN [Microservices:MetadataService] Asset 424a2dcd-c9ff-4353-a973-4c0adc8a0eb7 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:37 PM    WARN [Microservices:MetadataService] Asset 424a2dcd-c9ff-4353-a973-4c0adc8a0eb7 has no time zone information

[Nest] 7  - 09/18/2024, 4:25:38 PM    WARN [Microservices:MetadataService] Asset d902121d-4f66-4723-b269-486db57fe370 has no valid date (undefined), falling back to asset.fileCreatedAt

[Nest] 7  - 09/18/2024, 4:25:38 PM    WARN [Microservices:MetadataService] Asset d902121d-4f66-4723-b269-486db57fe370 has no time zone information
```

### Additional information

I love this project.  You have done an amazing job.  Thank you for all your work on this.  It is very much appreciated.
