### DISCUSSION TITLE
Refreshing encoded video appear to do nothing

### DISCUSSION THREAD

**Discussion by ryanwinter** [immich-app/immich#12795] [Q&A]
### The bug

I'm sure in the past this would trigger a reencoding of the selected video using the current encoding settings, however now it appears to do nothing.

When I select some videos and press the "Refresh encoding video" I see the following POST to ` https://photos.winterbug.com/api/assets/jobs` which appear to have an empty assetIds list even though I have selected items.

```
{
  "assetIds":[],
  "name":"transcode-video"
}
```

### The OS that Immich Server is running on

Ubuntu 22.04 with Docker

### Version of Immich Server

v1.115

### Version of Immich Mobile App

v1.115

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    restart: unless-stopped
    volumes:
      - /mnt/truenas_immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"       
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: unless-stopped
    volumes:
      - /volumes_tmp/immich/model-cache:/cache
    labels:
      - "com.centurylinklabs.watchtower.enable=false"       
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    restart: unless-stopped
    volumes:
      - /volumes_tmp/immich/redis:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"       
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"   
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  postgres:
```

### Your .env content

```Shell
DB_USERNAME=xxx
DB_DATABASE_NAME=xxx
DB_PASSWORD=xxx
```

### Reproduction steps

1. Select some files from the photo stream.
2. Choose "Refresh encoded videos" from the triple dot menu
3. Observe that nothing appears to happen, and the assets ids arent posted to the job.
