### DISCUSSION TITLE
Not uploading all videos

### DISCUSSION THREAD

**Discussion by green-limon** [immich-app/immich#12807] [Q&A] [answered]
### The bug

Hello Immich Team,

After updating to v1.115.0, videos stopped loading to the server thrue mobile app and web.
The application displays the loading process and progress reaches the end, but there is no video on the server.
The web brouser shows this error.
![image](https://github.com/user-attachments/assets/51df52fa-743c-4dcd-be29-7241adb1ac18)

Immich server in a docker container.
Before v1.114.0, the video was loaded.
After updating to v1.114.0 and then to v1.115.0, it stopped loading.

Here is a logs:

[Immich_log_2024-09-19T21:32:10.325826.log](https://github.com/user-attachments/files/17065734/Immich_log_2024-09-19T21.32.10.325826.log)
[_immich_server_logs.txt](https://github.com/user-attachments/files/17065735/_immich_server_logs.txt)

Please help solve/fix the problem.
Thank you.

### The OS that Immich Server is running on

Ubuntu-22.04.3

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

1.115.0 build 175

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    networks:
      - immich_default
      - proxy
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/12345/immich/model-cache:/cache
    env_file:
      - stack.env
    networks:
      - immich_default
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    volumes:
      - /home/12345/immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich_default
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

    networks:
      - immich_default
    restart: always

volumes:
  model-cache:

networks:
  immich_default:
    external: false
  proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/12345/immich
# The location where your database files are stored
DB_DATA_LOCATION=/home/12345/immich/database/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=some-generated-password

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=12345
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the app on IOS and start uploading videos
2.Open browser start uploading video

### Relevant log output

```shell
Logs have been added
```
