### DISCUSSION TITLE
Postgresql database password using secrets

### DISCUSSION THREAD

**Discussion by ezpc98** [immich-app/immich#12833] [Q&A]
I have setup app using recommended docker compose and env files, works ok. To add security, I want to move away from DB_PASSWORD in .env file to rather use DB_PASSWORD_FILE attribute to read password from a file located on storage. Can anyone guide me with example on how to configure .env and docker compose yml file that uses secrets and set postgresql database password?

Current .env file:
```
# Immich variables
# Documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
IMMICH_VERSION=release
UPLOAD_LOCATION=/mnt/media/immich-library
DB_DATA_LOCATION=/mnt/dietpi_userdata/docker-data/appdata/immich-postgres
DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD=postgres
```
Current docker compose file:
```
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

**Comment by bjoernwuest** [comment]
Have you tried the following in ```database:``` service section?
```
    environment:
      - POSTGRES_PASSWORD_FILE=/postgres_password.secret
    volumes:
      - /mylocalfileystem/postgres.secret:/postgres_password.secret:ro
```

**Reply by timwis** [reply]
But the other containers need the password too, to connect to the database :/

**Comment by Ovski4** [comment]
I had the same question and figured it out, so sharing here.

docker-compose.yml file (relevant changes only)
```
name: immich

services:
  immich-server:
    ...
    env_file:
      - .env
    ...
    secrets:
      - postgres_password

  immich-machine-learning:
    ...
    env_file:
      - .env
    ...
    secrets:
      - postgres_password

  # nothing to change for redis

  database:
    ...
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ...
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: ./secret_postgres_password.txt
```

full docker-compose.yml file
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    secrets:
      - postgres_password

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    secrets:
      - postgres_password

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    secrets:
      - postgres_password

volumes:
  model-cache:


secrets:
  postgres_password:
    file: ./secret_postgres_password.txt
```

.env file
```
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_PASSWORD_FILE=/run/secrets/postgres_password
```

And we have to create the secret file of course. (`secret_postgres_password.txt` here in the above example). We could use the same trick for the DB_USERNAME value, by specifying a DB_USERNAME_FILE env variable with another secret file path as a value
