### DISCUSSION TITLE
How to disable Upload functionality

### DISCUSSION THREAD

**Discussion by vs30217** [immich-app/immich#12981] [General]
I am mounting data to immich using external library and using it's facial recognition feature, however i do not want to allow upload from immich. can anyone help in disabling the upload functionality in immich web UI ?

**Comment by bo0tzz** [comment]
You can block the upload endpoint in your reverse proxy.

**Reply by scottcopus** [reply]
Any idea of the upload URL? I'm not an expert with Chrome's dev tools to figure it out.

**Reply by ojsef39** [reply]
@scottcopus @vs30217  maybe this?
[api.immich.app/endpoints/assets/uploadAsset](https://api.immich.app/endpoints/assets/uploadAsset)

ill try later and hopefully won't forget to give an update

**Reply by ojsef39** [reply]
Okay, so what i did was create a small nginx deployment that  returns my custom status code:
<details><summary>Nginx</summary>
<p>

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-upload-blocker-nginx
  namespace: shares
data:
  default.conf: |
    server {
      listen 80 default_server;
      return 403 '{"message":"Upload disabled. Please upload via Nextcloud.","statusCode":403}';
      default_type application/json;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-upload-blocker
  namespace: shares
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-upload-blocker
  template:
    metadata:
      labels:
        app: immich-upload-blocker
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: config
          configMap:
            name: immich-upload-blocker-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: immich-upload-blocker
  namespace: shares
spec:
  selector:
    app: immich-upload-blocker
  ports:
    - port: 80
      targetPort: 80

```

</p>
</details> 

and then turned off the ingress in the helm chart and created a custom ingressroute like this:

<details><summary>IngressRoute</summary>
<p>

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich-block-uploads
  namespace: shares
spec:
  entryPoints:
    - websecure
  routes:
    # Block POST to upload endpoint
    - match: Host(`DOMAIN`) && PathPrefix(`/api/asset/upload`) && Method(`POST`)
      kind: Rule
      priority: 100
      services:
        - name: immich-upload-blocker
          port: 80
    # Block POST to assets endpoint (bulk upload)
    - match: Host(`DOMAIN`) && PathPrefix(`/api/assets`) && Method(`POST`)
      kind: Rule
      priority: 100
      services:
        - name: immich-upload-blocker
          port: 80
    # Block PUT to assets endpoint (replace)
    - match: Host(`DOMAIN`) && PathPrefix(`/api/assets`) && Method(`PUT`)
      kind: Rule
      priority: 100
      services:
        - name: immich-upload-blocker
          port: 80
    # Allow all other traffic to Immich
    - match: Host(`DOMAIN`)
      kind: Rule
      priority: 10
      services:
        - name: immich-server
          port: 2283
  tls:
    certResolver: labca

```

</p>
</details>
