### DISCUSSION TITLE
Error after upgrade from v1.115.0 to v1.116.0 & v1.116.1 & v1.116.2

### DISCUSSION THREAD

**Discussion by underhax** [immich-app/immich#12997] [Q&A]
### The bug

Hello.

The following is used for the immich server in docker compose:
```
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      # - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - "/mnt/imlib:/usr/src/app/upload/library"
      - "/mnt/imext:/mnt/media:ro"
    env_file:
      - .env
    ports:
      - 127.0.0.1:12283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '4G'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    user: '1038:33'
```
The permissions in the system are set as follows:
```
ls -na /mnt
...
drwxr-x---  1 1038 33    0 Sep 17 21:44 imext
drwxr-x---  1 1038 33    0 Sep 27 21:08 imlib
```
The permissions in the container (v1.115.0):
```
I have no name!@2706689c7ad1:/usr/src/app$ ls -na /usr/src/app/upload
total 24
drwxr-xr-x 7 1038 33 4096 Aug 31 21:32 .
drwxr-xr-x 1    0  0 4096 Sep 27 21:22 ..
drwxr-xr-x 3 1038 33 4096 Sep 26 19:49 encoded-video
drwxr-x--- 1 1038 33    0 Sep 27 21:08 library
drwxr-xr-x 5 1038 33 4096 Sep 26 20:09 profile
drwxr-xr-x 5 1038 33 4096 Sep 26 19:49 thumbs
drwxr-xr-x 4 1038 33 4096 Sep 26 19:50 upload
```

Up to v1.115.0 everything works fine.

<img width="1347" alt="Снимок экрана 2024-09-27 в 21 23 48" src="https://github.com/user-attachments/assets/ba8acff2-d5eb-4be2-bb88-30d751dfb2fc">

After upgrading to v1.116.0 and v1.116.1, errors occur:

```
ERROR [Api:StorageService] Failed to write upload/library/.immich: AggregateError: EPERM: operation not permitted, write
ERROR [Api:StorageService] The "library" folder cannot be written to, please make sure the volume is mounted with the correct permissions
```

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.116.1

### Version of Immich Mobile App

v1.116.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    # image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    image: ghcr.io/immich-app/immich-server:v1.115.0 
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    # devices:
      # - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      # - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - "/mnt/imlib:/usr/src/app/upload/library"
      - "/mnt/imext:/mnt/media:ro"
    env_file:
      - .env
    ports:
      - 127.0.0.1:12283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          # Number of CPU threads
          cpus: '2.00'
          # Gigabytes of memory
          memory: '4G'
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    user: '1038:33'

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
  #   # Example tag: ${IMMICH_VERSION:-release}-cuda
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   #   file: hwaccel.ml.yml
  #   #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #   volumes:
  #     - ./model-cache:/cache
  #   env_file:
  #     - .env
  #   restart: always
  #   healthcheck:
  #     disable: false
  #   deploy:
  #     resources:
  #       limits:
  #         # Number of CPU threads
  #         cpus: '2.00'
  #         # Gigabytes of memory
  #         memory: '4G'
  #   security_opt:
  #     # Prevent escalation of privileges after the container is started
  #     - no-new-privileges:true
  #   cap_drop:
  #     # Prevent access to raw network traffic
  #     - NET_RAW
  #   user: '1038:33'

  redis:
    container_name: immich_redis
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - ./redis-data:/data
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    user: '1038:1038'

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    user: '999:1038'
```

### Your .env content

```Shell
UPLOAD_LOCATION=./storage
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=redacted
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=Europe/Kyiv
```

### Reproduction steps

1. Separate mounting for /usr/src/app/upload/library
2. Individual user:group
3. Upgrade to v1.116.1
More details in the first post above

### Relevant log output

```shell
ERROR [Api:StorageService] Failed to write upload/library/.immich: AggregateError: EPERM: operation not permitted, write
ERROR [Api:StorageService] The "library" folder cannot be written to, please make sure the volume is mounted with the correct permissions
```

**Comment by alextran1502** [comment]
Hello, just to confirm that your previous version was 1.115?

**Comment by underhax** [comment]
Hello. That's correct. The previous version on which it works now is v1.115.0. I checked after the release of v1.116.2 - it doesn't work on it either. In order to be able to use the server further, I replaced the release version in docker compose with v1.115.0.
```
# image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
 image: ghcr.io/immich-app/immich-server:v1.115.0 
```

**Comment by underhax** [comment]
Clarification: the disk is mounted using the rclone
```
cat /etc/systemd/system/mnt-imlib.mount
```

```
[Unit]
Description=Mount for immich library

[Mount]
What=immich-library-enc:
Where=/mnt/imlib
Type=rclone
Options=rw,allow-other,default-permissions,config=/root/.config/rclone/rclone.conf,uid=1038,gid=33,umask=027,dir-perms=750,file-perms=640

[Install]
WantedBy=multi-user.target
```
```
cat /etc/systemd/system/mnt-imlib.automount
```
```
[Unit]
Before=remote-fs.target

[Automount]
Where=/mnt/imlib

[Install]
WantedBy=multi-user.target
```

**Comment by bo0tzz** [comment]
Your container mountpoints are very strange, and I think there's a bunch of separate mounts pointing to the same path. Why do you have it set that way?

**Comment by underhax** [comment]
The mount points are correct and as I need them. Sensitive information is stored in encrypted folders (if someone accesses the disk outside the system, they can't view the photos). Mounting allows immich to work with such folders in decrypted form.

What, in your opinion, is incorrect?

Everything works from early versions of immich up to 1.115.0
Only with version 1.116.0+ an error appeared.

**Comment by alextran1502** [comment]
Hello, can you help us confirm that by attaching to the container, you can create file in each Immich's folders (thumb, upload...etc) from the container's context

**Comment by underhax** [comment]
Of course. immich v1.115.0 
```
I have no name!@2e979c62e818:/usr/src/app$ cd /usr/src/app/upload
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la
total 24
drwxr-xr-x 7 1038 www-data 4096 Aug 31 21:32 .
drwxr-xr-x 1 root root     4096 Sep 27 22:15 ..
drwxr-xr-x 3 1038 www-data 4096 Sep 26 19:49 encoded-video
drwxr-x--- 1 1038 www-data    0 Sep 27 22:05 library
drwxr-xr-x 5 1038 www-data 4096 Sep 26 20:09 profile
drwxr-xr-x 5 1038 www-data 4096 Sep 26 19:49 thumbs
drwxr-xr-x 4 1038 www-data 4096 Sep 26 19:50 upload
I have no name!@2e979c62e818:/usr/src/app/upload$ touch test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la
total 24
drwxr-xr-x 7 1038 www-data 4096 Sep 28 14:17 .
drwxr-xr-x 1 root root     4096 Sep 27 22:15 ..
drwxr-xr-x 3 1038 www-data 4096 Sep 26 19:49 encoded-video
drwxr-x--- 1 1038 www-data    0 Sep 27 22:05 library
drwxr-xr-x 5 1038 www-data 4096 Sep 26 20:09 profile
-rw-r--r-- 1 1038 www-data    0 Sep 28 14:17 test.txt
drwxr-xr-x 5 1038 www-data 4096 Sep 26 19:49 thumbs
drwxr-xr-x 4 1038 www-data 4096 Sep 26 19:50 upload
I have no name!@2e979c62e818:/usr/src/app/upload$ touch library/test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ touch profile/test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ touch thumbs/test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ touch upload/test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la profile/
total 24
drwxr-xr-x 5 1038 www-data 4096 Sep 28 14:18 .
drwxr-xr-x 7 1038 www-data 4096 Sep 28 14:17 ..
-rw-r--r-- 1 1038 www-data   13 Sep 27 22:15 .immich
drwxr-xr-x 2 1038 www-data 4096 Aug 31 15:58 499fbfd1-df47-4124-ab5c-bd0f80b167f8
drwxr-xr-x 2 1038 www-data 4096 Aug 31 15:58 4f70a06c-0ba6-4886-8a59-934c97927862
drwxr-xr-x 2 1038 www-data 4096 Sep  5 01:41 96df33de-35ef-4cea-9145-44b5dbe32367
-rw-r--r-- 1 1038 www-data    0 Sep 28 14:18 test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la library/
total 5
drwxr-x--- 1 1038 www-data    0 Sep 28 14:18 .
drwxr-xr-x 7 1038 www-data 4096 Sep 28 14:17 ..
-rw-r----- 1 1038 www-data   13 Sep 27 22:15 .immich
drwxr-x--- 1 1038 www-data    0 Sep  8 12:19 .stfolder
-rw-r----- 1 1038 www-data   20 Sep  8 12:25 .stignore
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 alisa
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 dima
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 sergei
-rw-r----- 1 1038 www-data    0 Sep 28 14:18 test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la thumbs/
total 24
drwxr-xr-x   5 1038 www-data 4096 Sep 28 14:18 .
drwxr-xr-x   7 1038 www-data 4096 Sep 28 14:17 ..
-rw-r--r--   1 1038 www-data   13 Sep 27 22:15 .immich
drwxr-xr-x 176 1038 www-data 4096 Aug 28 12:35 499fbfd1-df47-4124-ab5c-bd0f80b167f8
drwxr-xr-x 258 1038 www-data 4096 May  4 15:58 4f70a06c-0ba6-4886-8a59-934c97927862
drwxr-xr-x   3 1038 www-data 4096 May  8 20:15 96df33de-35ef-4cea-9145-44b5dbe32367
-rw-r--r--   1 1038 www-data    0 Sep 28 14:18 test.txt
I have no name!@2e979c62e818:/usr/src/app/upload$ ls -la upload/
total 20
drwxr-xr-x   4 1038 www-data 4096 Sep 28 14:18 .
drwxr-xr-x   7 1038 www-data 4096 Sep 28 14:17 ..
-rw-r--r--   1 1038 www-data   13 Sep 27 22:15 .immich
drwxr-xr-x 181 1038 www-data 4096 Aug 28 12:35 499fbfd1-df47-4124-ab5c-bd0f80b167f8
drwxr-xr-x   3 1038 www-data 4096 May  8 20:15 96df33de-35ef-4cea-9145-44b5dbe32367
-rw-r--r--   1 1038 www-data    0 Sep 28 14:18 test.txt
```

**Reply by alextran1502** [reply]
Hello, can you try removing the `.immich` file in all of the folder and restart the stack?

**Reply by underhax** [reply]
> Hello, can you try removing the `.immich` file in all of the folder and restart the stack?

Hello. I did this right after updating to v1.116.0

**Reply by alextran1502** [reply]
What error message are you seeing now on the latest `1.116.2` with the `.immich` file are in the correct folders?

**Reply by underhax** [reply]
```
Detected CPU Cores: 2
Starting api worker
Starting microservices worker
[Nest] 7  - 09/29/2024, 6:41:40 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 16  - 09/29/2024, 6:41:40 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 16  - 09/29/2024, 6:41:40 PM   ERROR [Api:StorageService] Failed to write upload/library/.immich: AggregateError: EPERM: operation not permitted, write
[Nest] 16  - 09/29/2024, 6:41:40 PM   ERROR [Api:StorageService] The "library" folder cannot be written to, please make sure the volume is mounted with the correct permissions
api worker exited with code 1
```

**Reply by underhax** [reply]
Before the service went down, I checked the permissions - they are the same as they should be, as they were in 1.115.0 and earlier
```
total 5
drwxr-x--- 1 1038 www-data    0 Sep 28 14:26 .
drwxr-xr-x 7 1038 www-data 4096 Sep 28 14:26 ..
-rw-r----- 1 1038 www-data   13 Sep 27 22:15 .immich
drwxr-x--- 1 1038 www-data    0 Sep  8 12:19 .stfolder
-rw-r----- 1 1038 www-data   20 Sep  8 12:25 .stignore
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 alisa
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 dima
drwxr-x--- 1 1038 www-data    0 Sep  3 00:11 sergei
```

**Comment by yzjJosh** [comment]
I'm facing the same issue after upgrading from v1.115.0 to v1.116.2

**Reply by yzjJosh** [reply]
Note that I'm also using rclone.

**Comment by mufeedali** [comment]
Facing the same issue with an rclone crypt mount

**Comment by yzjJosh** [comment]
I've found a workaround which is to explicitly bind the `/usr/src/app/upload/library/.immich` file from the local directory instead of a rclone backed remote drive:
```
     - ${UPLOAD_LOCATION}/library/.immich:/usr/src/app/upload/library/.immich
```
After adding the above line to the docker compose file under the `immich-server` section, my server can successfully start now.

**Reply by underhax** [reply]
I confirm. Thank you. This may be a solution, but it is certainly better that the developers find the root cause and fix it.

For those who have encountered the error, I will explain in more detail.

Beforehand, you need to create a .immich file in the local directory and set the correct permissions
```
touch ./storage/library/.immich && chown -R user:group ./storage
```
and make changes to the docker compose
```
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      - "/mnt/imlib:/usr/src/app/upload/library"
      - ${UPLOAD_LOCATION}/library/.immich:/usr/src/app/upload/library/.immich
      - "/mnt/imext:/mnt/media:ro"
    ...
```
