### DISCUSSION TITLE
BUG: machine learning remote server, "Cannot Identify Image File"

### DISCUSSION THREAD

**Discussion by jordanlambrecht** [immich-app/immich#13085] [Q&A]
### The bug

When sending an image for Smart Search to my remote machine for ML (nvidia GTX 4800ti), immich-ml throws the error below for each attempted image.

### The OS that Immich Server is running on

Server: Docker Desktop for Mac, ML: Docker Desktop w/ WSL2 & Ubuntu VM

### Version of Immich Server

v1.116.2@8bbcd5c31

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

**Remote Machine Learning container:**
```YAML
services:
  immich-machine-learning:
    container_name: immich_machine_learning
    restart: always
    tty: true
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"
        max-size: "10m"
        max-file: "36"
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    environment:
      IMMICH_LOG_LEVEL: verbose
      TZ: America/Chicago
      MACHINE_LEARNING_WORKER_TIMEOUT: 1600
      MACHINE_LEARNING_PRELOAD__CLIP: ViT-H-14-378-quickgelu__dfn5b
      MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION: buffalo_l
      MACHINE_LEARNING_MODEL_TTL: 0
      MACHINE_LEARNING_HTTP_KEEPALIVE_TIMEOUT_S: 15
    volumes:
      - model-cache:/cache:rw
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 3003:3003
      - 3001:3001
    networks:
      network_universal:
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: true
      diun.enable: true
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/3003"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  model-cache:
```

**Immich Server:**

```YAML
---
name: immich

# ╔══════════════════════════════════════════════════════════╗
# ║                                                          ║
# ║                      Immich  Server                      ║
# ║                                                          ║
# ╚══════════════════════════════════════════════════════════╝

# ════════════════════════════════════
#          ANCHORS/FRAGMENTS
# ════════════════════════════════════
x-common-config: &common-config
  restart: always
  tty: true
  stdin_open: true
  logging:
    driver: json-file
    options:
      tag: "{{.Name}}"
      max-size: "10m"
      max-file: "36"
  env_file:
    - .env

x-common-labels: &common-labels
  com.centurylinklabs.watchtower.enable: true
  autoheal: false
  diun.enable: false

x-kuma-labels: &kuma-labels
  kuma.{{ container_name }}-docker.docker.parent_name: "immich"
  kuma.{{ container_name }}-docker.docker.name: "{{ container_name }}"
  kuma.{{ container_name }}-docker.docker.active: true

x-common-env: &common-env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

x-common-networks: &common-networks
  network_universal:
  network_autokuma:
  default:

# ════════════════════════════════════
#                Services
# ════════════════════════════════════
services:
  # ┌──────────────────────────────────────┐
  # |            Immich Server             |
  # └──────────────────────────────────────┘
  immich:
    <<: *common-config
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./tmp:/tmp:rw
      - ./immich/config:/config:rw
      - ${STORAGE_LOCATION}/photos:/usr/src/app/upload:rw
      - ${STORAGE_LOCATION}/thumbs:/usr/src/app/upload/thumbs:rw
      - ${STORAGE_LOCATION}/encoded-videos:/usr/src/app/upload/encoded-video:rw
      - ${STORAGE_LOCATION}/profiles:/usr/src/app/upload/profile:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro # TODO: needed?
      - /etc/localtime:/etc/localtime:to # TODO: redundant?
    environment:
      <<: *common-env
      IMMICH_METRICS: true
      IMMICH_HOST_METRICS: true
      IMMICH_IO_METRICS: true
      IMMICH_JOB_METRICS: true
      IMMICH_LOG_LEVEL: verbose
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      REDIS_PORT: 6379
    ports:
      - <redacted>:3001
      - <redacted>:8081
      - <redacted>:8082
    depends_on:
      - redis
      - database
    labels:
      <<: [*common-labels, *kuma-labels]
    networks:
      <<: *common-networks
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail http://immich_server:3001/api/server-info/ping | grep -q ''{"res":"pong"}'' || exit 1',
        ]
      interval: 1m
      timeout: 10s
      retries: 3
      disable: false

  # ┌──────────────────────────────────────┐
  # |                Redis                 |
  # └──────────────────────────────────────┘
  redis:
    <<: *common-config
    image: redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    container_name: immich_redis
    environment:
      <<: *common-env
    ports:
      - 6379:6379 # TODO: remove and test, rely on stack network only
    volumes:
      - ./redis_data:/data
      - ./tmp:/tmp
    networks:
      <<: *common-networks
    labels:
      <<: *common-labels
    healthcheck:
      test: redis-cli ping || exit 1

  # ┌──────────────────────────────────────┐
  # |               Postgres               |
  # └──────────────────────────────────────┘
  database:
    <<: *common-config
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    environment:
      <<: *common-env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:rw
      - /etc/localtime:/etc/localtime:to # TODO: redundant?
    ports:
      - ${DB_PORT}:5432
    labels:
      <<: *common-labels
    networks:
      <<: *common-networks
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m

# ------------------------end of services------------------------ #


# ════════════════════════════════════
#               NETWORKS
# ════════════════════════════════════
networks:
  default:
    name: network_default_immich
  network_universal:
    external: true
  network_autokuma:
    external: true
```

### Your .env content

```dotenv
#  Immich Server .env

STORAGE_LOCATION=/Volumes/<REDACTED>
IMMICH_VERSION=release

DB_DATA_LOCATION=./pgdata
PROFILE_LOCATION=/Volumes/<REDACTED>
DB_PASSWORD=<REDACTED>

DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_PORT=5432

REDIS_HOSTNAME=immich_redis

TZ=America/Chicago
PUID=10000
PGID=10000
UMASK=002
```

### Reproduction steps

1. Immich Server is running on my primary docker machine via Docker Desktop for Mac
2. Immich ML is running on my PC via WSL2, Ubuntu VM, and Docker Desktop
3. Connection is stable
4. Using `ViT-H-14-378-quickgelu__dfn5b` for the clip
5. Error happens when the server attempts to send a file for smart search recognition. The connection is stable and communication happens. Error repeats for every attempted image sent.

### Relevant log output

```shell
[09/30/24 09:51:29] ERROR    Exception in ASGI application

                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:147 in predict             │
                             │                                                 │
                             │   144 │   text: str | None = Form(default=None) │
                             │   145 ) -> Any:                                 │
                             │   146 │   if image is not None:                 │
                             │ ❱ 147 │   │   inputs: Image | str = await run(l │
                             │   148 │   elif text is not None:                │
                             │   149 │   │   inputs = text                     │
                             │   150 │   else:                                 │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │ entries = (                                 │ │
                             │ │           │   [                             │ │
                             │ │           │   │   {                         │ │
                             │ │           │   │   │   'name':               │ │
                             │ │           'ViT-H-14-378-quickgelu__dfn5b',  │ │
                             │ │           │   │   │   'task': 'clip',       │ │
                             │ │           │   │   │   'type': 'visual',     │ │
                             │ │           │   │   │   'options': {}         │ │
                             │ │           │   │   }                         │ │
                             │ │           │   ],                            │ │
                             │ │           │   []                            │ │
                             │ │           )                                 │ │
                             │ │   image = b''                               │ │
                             │ │    text = None                              │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             │                                                 │
                             │ /usr/src/app/main.py:188 in run                 │
                             │                                                 │
                             │   185 │   if thread_pool is None:               │
                             │   186 │   │   return func(*args, **kwargs)      │
                             │   187 │   partial_func = partial(func, *args, * │
                             │ ❱ 188 │   return await asyncio.get_running_loop │
                             │   189                                           │
                             │   190                                           │
                             │   191 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │         args = ()                           │ │
                             │ │         func = <function                    │ │
                             │ │                predict.<locals>.<lambda> at │ │
                             │ │                0x7f3c572be980>              │ │
                             │ │       kwargs = {}                           │ │
                             │ │ partial_func = functools.partial(<function  │ │
                             │ │                predict.<locals>.<lambda> at │ │
                             │ │                0x7f3c572be980>)             │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:147 in <lambda>            │
                             │                                                 │
                             │   144 │   text: str | None = Form(default=None) │
                             │   145 ) -> Any:                                 │
                             │   146 │   if image is not None:                 │
                             │ ❱ 147 │   │   inputs: Image | str = await run(l │
                             │   148 │   elif text is not None:                │
                             │   149 │   │   inputs = text                     │
                             │   150 │   else:                                 │
                             │                                                 │
                             │ ╭── locals ───╮                                 │
                             │ │ image = b'' │                                 │
                             │ ╰─────────────╯                                 │
                             │                                                 │
                             │ /usr/src/app/models/transforms.py:52 in         │
                             │ decode_pil                                      │
                             │                                                 │
                             │   49 def decode_pil(image_bytes: bytes | IO[byt │
                             │   50 │   if isinstance(image_bytes, Image.Image │
                             │   51 │   │   return image_bytes                 │
                             │ ❱ 52 │   image: Image.Image = Image.open(BytesI │
                             │      bytes) else image_bytes)                   │
                             │   53 │   image.load()                           │
                             │   54 │   if not image.mode == "RGB":            │
                             │   55 │   │   image = image.convert("RGB")       │
                             │                                                 │
                             │ ╭───── locals ──────╮                           │
                             │ │ image_bytes = b'' │                           │
                             │ ╰───────────────────╯                           │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/PIL/Imag │
                             │ e.py:3498 in open                               │
                             │                                                 │
                             │   3495 │   for message in warning_messages:     │
                             │   3496 │   │   warnings.warn(message)           │
                             │   3497 │   msg = "cannot identify image file %r │
                             │ ❱ 3498 │   raise UnidentifiedImageError(msg)    │
                             │   3499                                          │
                             │   3500                                          │
                             │   3501 #                                        │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │       _open_core = <function                │ │
                             │ │                    open.<locals>._open_core │ │
                             │ │                    at 0x7f3bf2936160>       │ │
                             │ │  checked_formats = [                        │ │
                             │ │                    │   'PNG',               │ │
                             │ │                    │   'BMP',               │ │
                             │ │                    │   'DIB',               │ │
                             │ │                    │   'GIF',               │ │
                             │ │                    │   'JPEG',              │ │
                             │ │                    │   'PPM',               │ │
                             │ │                    │   'BLP',               │ │
                             │ │                    │   'BUFR',              │ │
                             │ │                    │   'CUR',               │ │
                             │ │                    │   'PCX',               │ │
                             │ │                    │   ... +32              │ │
                             │ │                    ]                        │ │
                             │ │     exclusive_fp = False                    │ │
                             │ │         filename = ''                       │ │
                             │ │          formats = [                        │ │
                             │ │                    │   'PNG',               │ │
                             │ │                    │   'BMP',               │ │
                             │ │                    │   'DIB',               │ │
                             │ │                    │   'GIF',               │ │
                             │ │                    │   'JPEG',              │ │
                             │ │                    │   'PPM',               │ │
                             │ │                    │   'BLP',               │ │
                             │ │                    │   'BUFR',              │ │
                             │ │                    │   'CUR',               │ │
                             │ │                    │   'PCX',               │ │
                             │ │                    │   ... +32              │ │
                             │ │                    ]                        │ │
                             │ │               fp = <_io.BytesIO object at   │ │
                             │ │                    0x7f3c572073d0>          │ │
                             │ │               im = None                     │ │
                             │ │             mode = 'r'                      │ │
                             │ │              msg = 'cannot identify image   │ │
                             │ │                    file <_io.BytesIO object │ │
                             │ │                    at 0x7f3c572073d0>'      │ │
                             │ │           prefix = b''                      │ │
                             │ │ warning_messages = []                       │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             ╰─────────────────────────────────────────────────╯
                             UnidentifiedImageError: cannot identify image file
                             <_io.BytesIO object at 0x7f3c572073d0>
[09/30/24 09:51:29] ERROR    Exception in ASGI application

                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:147 in predict             │
                             │                                                 │
                             │   144 │   text: str | None = Form(default=None) │
                             │   145 ) -> Any:                                 │
                             │   146 │   if image is not None:                 │
                             │ ❱ 147 │   │   inputs: Image | str = await run(l │
                             │   148 │   elif text is not None:                │
                             │   149 │   │   inputs = text                     │
                             │   150 │   else:                                 │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │ entries = (                                 │ │
                             │ │           │   [                             │ │
                             │ │           │   │   {                         │ │
                             │ │           │   │   │   'name':               │ │
                             │ │           'ViT-H-14-378-quickgelu__dfn5b',  │ │
                             │ │           │   │   │   'task': 'clip',       │ │
                             │ │           │   │   │   'type': 'visual',     │ │
                             │ │           │   │   │   'options': {}         │ │
                             │ │           │   │   }                         │ │
                             │ │           │   ],                            │ │
                             │ │           │   []                            │ │
                             │ │           )                                 │ │
                             │ │   image = b''                               │ │
                             │ │    text = None                              │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             │                                                 │
                             │ /usr/src/app/main.py:188 in run                 │
                             │                                                 │
                             │   185 │   if thread_pool is None:               │
                             │   186 │   │   return func(*args, **kwargs)      │
                             │   187 │   partial_func = partial(func, *args, * │
                             │ ❱ 188 │   return await asyncio.get_running_loop │
                             │   189                                           │
                             │   190                                           │
                             │   191 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │         args = ()                           │ │
                             │ │         func = <function                    │ │
                             │ │                predict.<locals>.<lambda> at │ │
                             │ │                0x7f3ca8679da0>              │ │
                             │ │       kwargs = {}                           │ │
                             │ │ partial_func = functools.partial(<function  │ │
                             │ │                predict.<locals>.<lambda> at │ │
                             │ │                0x7f3ca8679da0>)             │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:147 in <lambda>            │
                             │                                                 │
                             │   144 │   text: str | None = Form(default=None) │
                             │   145 ) -> Any:                                 │
                             │   146 │   if image is not None:                 │
                             │ ❱ 147 │   │   inputs: Image | str = await run(l │
                             │   148 │   elif text is not None:                │
                             │   149 │   │   inputs = text                     │
                             │   150 │   else:                                 │
                             │                                                 │
                             │ ╭── locals ───╮                                 │
                             │ │ image = b'' │                                 │
                             │ ╰─────────────╯                                 │
                             │                                                 │
                             │ /usr/src/app/models/transforms.py:52 in         │
                             │ decode_pil                                      │
                             │                                                 │
                             │   49 def decode_pil(image_bytes: bytes | IO[byt │
                             │   50 │   if isinstance(image_bytes, Image.Image │
                             │   51 │   │   return image_bytes                 │
                             │ ❱ 52 │   image: Image.Image = Image.open(BytesI │
                             │      bytes) else image_bytes)                   │
                             │   53 │   image.load()                           │
                             │   54 │   if not image.mode == "RGB":            │
                             │   55 │   │   image = image.convert("RGB")       │
                             │                                                 │
                             │ ╭───── locals ──────╮                           │
                             │ │ image_bytes = b'' │                           │
                             │ ╰───────────────────╯                           │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/PIL/Imag │
                             │ e.py:3498 in open                               │
                             │                                                 │
                             │   3495 │   for message in warning_messages:     │
                             │   3496 │   │   warnings.warn(message)           │
                             │   3497 │   msg = "cannot identify image file %r │
                             │ ❱ 3498 │   raise UnidentifiedImageError(msg)    │
                             │   3499                                          │
                             │   3500                                          │
                             │   3501 #                                        │
                             │                                                 │
                             │ ╭────────────────── locals ───────────────────╮ │
                             │ │       _open_core = <function                │ │
                             │ │                    open.<locals>._open_core │ │
                             │ │                    at 0x7f3c5731fba0>       │ │
                             │ │  checked_formats = [                        │ │
                             │ │                    │   'PNG',               │ │
                             │ │                    │   'BMP',               │ │
                             │ │                    │   'DIB',               │ │
                             │ │                    │   'GIF',               │ │
                             │ │                    │   'JPEG',              │ │
                             │ │                    │   'PPM',               │ │
                             │ │                    │   'BLP',               │ │
                             │ │                    │   'BUFR',              │ │
                             │ │                    │   'CUR',               │ │
                             │ │                    │   'PCX',               │ │
                             │ │                    │   ... +32              │ │
                             │ │                    ]                        │ │
                             │ │     exclusive_fp = False                    │ │
                             │ │         filename = ''                       │ │
                             │ │          formats = [                        │ │
                             │ │                    │   'PNG',               │ │
                             │ │                    │   'BMP',               │ │
                             │ │                    │   'DIB',               │ │
                             │ │                    │   'GIF',               │ │
                             │ │                    │   'JPEG',              │ │
                             │ │                    │   'PPM',               │ │
                             │ │                    │   'BLP',               │ │
                             │ │                    │   'BUFR',              │ │
                             │ │                    │   'CUR',               │ │
                             │ │                    │   'PCX',               │ │
                             │ │                    │   ... +32              │ │
                             │ │                    ]                        │ │
                             │ │               fp = <_io.BytesIO object at   │ │
                             │ │                    0x7f3c572078d0>          │ │
                             │ │               im = None                     │ │
                             │ │             mode = 'r'                      │ │
                             │ │              msg = 'cannot identify image   │ │
                             │ │                    file <_io.BytesIO object │ │
                             │ │                    at 0x7f3c572078d0>'      │ │
                             │ │           prefix = b''                      │ │
                             │ │ warning_messages = []                       │ │
                             │ ╰─────────────────────────────────────────────╯ │
                             ╰─────────────────────────────────────────────────╯
                             UnidentifiedImageError: cannot identify image file
                             <_io.BytesIO object at 0x7f3c572078d0>
```
