### DISCUSSION TITLE
Non-root configuration

### DISCUSSION THREAD

**Discussion by CiNcH83** [immich-app/immich#13124] [Q&A]
Hi everybody

I want to run Immich as a non-root user. I have learned that this is possible but I can't do anything with the respective [FAQ](https://immich.app/docs/FAQ#how-can-i-run-immich-as-a-non-root-user). Guess I am lacking some Docker knowledge...

Adding user and group to the yml was the easy part. But what about the volume part? Are those 3 additional volumes needed or not? Do I have to remove the top-level volume and point all volumes to host directories to which the respective user has read/write permissions? The FAQ is also a bit misleading IMHO in that those 3 additional volumes look to be named volumes which I suppose do not work in a non-root environment!?

Can somebody post a proper non-root sample yml?

Thanks.

**Comment by CiNcH83** [comment]
Hi everbody

So let me make a proposal for a non-root yml from the things I have learned…

I have created a user Immich (`1003`/`1003`) which obviously has read/write permissions to `/home/Immich`.
```
name: immich

services:
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: 1003:1003
    volumes:
      - /home/Immich/upload:/usr/src/app/upload
      - /home/Dan/assets:/assets/Dan
      - /home/Sab/assets:/assets/Sab
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    user: 1003:1003
    volumes:
      - /home/Immich/var/cache:/cache
      - /home/Immich/var/.cache:/.cache
      - /home/Immich/var/.config:/.config
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    user: 1003:1003
    volumes:
      - /home/Immich/var/data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    user: 1003:1003
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /home/Immich/var/database:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped

```

Here are the things I have changed:
- Added user `1003:1003`
- Removed top-level volume `model-cache`
- Added 3 additional volumes, see [FAQ](https://immich.app/docs/FAQ#how-can-i-run-immich-as-a-non-root-user) (`/.config`, `/.cache`, `/data`)
- Turned named volumes (`/cache`) into host volumes

I haven’t tried it yet. Will this work? Any suggestions for improvement? Do we really need `cache` and `.cache` in immich-machine-learning? How about those 3 additional volumes mentioned in the FAQ? Are they really needed? Since FAQ says that they "may be needed".

Thanks.
