### DISCUSSION TITLE
https://mydomain/api 404

### DISCUSSION THREAD

**Discussion by bugge** [immich-app/immich#13147] [Q&A]
### The bug

Try to reach the api i get this:
https://mydomain/api

{
  "message": "Cannot GET /api",
  "error": "Not Found",
  "statusCode": 404,
  "correlationId": "vn1gga8r"
}

or try to use album creator:

time=2024-10-03T07:17:41.439+02:00 level=INFO msg=Detected Immich server version 1.116.0
time=2024-10-03T07:17:41.440+02:00 level=INFO msg=Requesting all assets
Traceback (most recent call last):
.
.
.
.

  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mydomain/api/search/metadata

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.116

### Version of Immich Mobile App

v.1.116

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3"
services:
  immich:
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_BIND_SERVICE
      - NET_RAW
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT
    cap_drop:
      - AUDIT_CONTROL
      - BLOCK_SUSPEND
      - DAC_READ_SEARCH
      - IPC_LOCK
      - IPC_OWNER
      - LEASE
      - LINUX_IMMUTABLE
      - MAC_ADMIN
      - MAC_OVERRIDE
      - NET_ADMIN
      - NET_BROADCAST
      - SYSLOG
      - SYS_ADMIN
      - SYS_BOOT
      - SYS_MODULE
      - SYS_NICE
      - SYS_PACCT
      - SYS_PTRACE
      - SYS_RAWIO
      - SYS_RESOURCE
      - SYS_TIME
      - SYS_TTY_CONFIG
      - WAKE_ALARM
    container_name: immich
    entrypoint:
      - /init
    environment:
   
    hostname: immich
    image: ghcr.io/imagegenius/immich:1.116.0
    ipc: private
    labels:
      build_version: 'ImageGenius Version:- v1.116.1-ig329 Build-date:- 2024-09-28T02:56:02+10:00'
      maintainer: 'hydazz, martabal'
      org.opencontainers.image.authors: imagegenius.io
      org.opencontainers.image.created: 2024-09-28T02:56:02+10:00
      org.opencontainers.image.description: 'Immich is a high performance self-hosted
        photo and video backup solution.'
      org.opencontainers.image.documentation: https://docs.linuxserver.io/images/docker-baseimage-ubuntu
      org.opencontainers.image.licenses: GPL-3.0-only
      org.opencontainers.image.ref.name: 1165f8aafae55235ed0208df869965831db0e6c7
      org.opencontainers.image.revision: 1165f8aafae55235ed0208df869965831db0e6c7
      org.opencontainers.image.source: https://github.com/imagegenius/docker-immich
      org.opencontainers.image.title: Immich
      org.opencontainers.image.url: https://github.com/imagegenius/docker-immich/packages
      org.opencontainers.image.vendor: imagegenius.io
      org.opencontainers.image.version: v1.116.1-ig329
    logging:
      driver: json-file
      options: {}
    networks:
      - bugge-vlan
    ports:
      - 3001:3001/tcp
      - 3001:3001/udp
      - 8080:8080/tcp
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid-03bdf31e-a0dd-4839-b13d-70ba4115e431/Appdata/immich/config:/config
      - /srv/dev-disk-by-uuid-03bdf31e-a0dd-4839-b13d-70ba4115e431/Appdata/immich/libraries:/libraries
      - /srv/dev-disk-by-uuid-03bdf31e-a0dd-4839-b13d-70ba4115e431/Backup/-=Kepek=-:/photos
      - /srv/dev-disk-by-uuid-03bdf31e-a0dd-4839-b13d-70ba4115e431/Backup/-=Kepek=-:/usr/src/app/external
    working_dir: /
networks:
  bugge-vlan:
    external: true
```

### Your .env content

```Shell
- TZ=Europe/Budapest
      - PUID=1000
      - PGID=1000
      - DB_HOSTNAME=192.168.1.77
      - DB_USERNAME=*********
      - "DB_PASSWORD=**********"
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.78
      - PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - LANGUAGE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - TERM=xterm
      - S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
      - S6_VERBOSITY=1
      - S6_STAGE2_HOOK=/docker-mods
      - VIRTUAL_ENV=/lsiopy
      - IMMICH_BUILD_DATA=/app/immich/server
      - IMMICH_ENV=production
      - IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003
      - IMMICH_MEDIA_LOCATION=/photos
      - IMMICH_PORT=8080
      - MACHINE_LEARNING_CACHE_FOLDER=/config/machine-learning/models
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - TRANSFORMERS_CACHE=/config/machine-learning/models
      - NODE_ENV=production
```

### Reproduction steps

Try to reach the api i get this:
https://mydomain/api

{
  "message": "Cannot GET /api",
  "error": "Not Found",
  "statusCode": 404,
  "correlationId": "vn1gga8r"
}

or try to use album creator:

time=2024-10-03T07:17:41.439+02:00 level=INFO msg=Detected Immich server version 1.116.0
time=2024-10-03T07:17:41.440+02:00 level=INFO msg=Requesting all assets
Traceback (most recent call last):
.
.
.
.

  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mydomain/api/search/metadata
