### DISCUSSION TITLE
Upload folder on NAS Share in Docker works - external not??

### DISCUSSION THREAD

**Discussion by DeltaTango69** [immich-app/immich#13155] [Q&A] [answered]
Hello,

I have a strange behaviour. When I mount the NAS/Share in the docker container then I have access.

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - Immich:/usr/src/app/upload
...

volumes:
  model-cache:
  Immich:
    driver_opts:
      type: cifs
      o: "username=xxxx,password=xxxxxx"
      device: "//192.168.178.4/Immich"  
```

When I mount in ubuntu then not:

```
fstab:
//192.168.178.4/Immich /mnt/immich cifs uid=1000,gid=1000,username=xxxx,password=xxxxx,rw
```
or only
```
fstab:
//192.168.178.4/Immich /mnt/immich cifs username=xxxx,password=xxxxx
```

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /mnt/immich:/usr/src/app/upload

```
log

```
immich_server            | [Nest] 17  - 10/03/2024, 6:07:42 PM     LOG [Api:StorageService] Verifying system mount folder checks (enabled=true)
immich_server            | [Nest] 17  - 10/03/2024, 6:07:42 PM   ERROR [Api:StorageService] Failed to write upload/library/.immich: Error: EACCES: permission denied, open 'upload/library/.immich'
```
It seems to be a rights problem. But I don't see a difference to the both methods?
