### DISCUSSION TITLE
Microservices container restarting after upgrade from 1.114 to 1.117

### DISCUSSION THREAD

**Discussion by rimalino** [immich-app/immich#13184] [General]
docker-compose:
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      #command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
      #env_file:
      #- .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  pgdata:
  model-cache:
```

Error log for microservices container, this just keeps repeating:
```
[Nest] 8  - 10/04/2024, 1:45:08 PM     LOG [ImmichMicroservices] [EventRepository] Initialized websocket server
QueryFailedError: relation "system_config" does not exist
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async SystemConfigCore.buildConfig (/usr/src/app/dist/cores/system-config.core.js:124:15)
    at async /usr/src/app/dist/cores/system-config.core.js:79:35 {
  query: 'SELECT "SystemConfigEntity"."key" AS "SystemConfigEntity_key", "SystemConfigEntity"."value" AS "SystemConfigEntity_value" FROM "system_config" "SystemConfigEntity"',
  parameters: [],
  driverError: error: relation "system_config" does not exist
      at /usr/src/app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
      at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
      at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
      at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
      at async SystemConfigCore.buildConfig (/usr/src/app/dist/cores/system-config.core.js:124:15)
      at async /usr/src/app/dist/cores/system-config.core.js:79:35 {
    length: 113,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '128',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1381',
    routine: 'parserOpenTable'
  },
  length: 113,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '128',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1381',
  routine: 'parserOpenTable'
}
Microservices worker exited with code 1
```

Running containers:
```
CONTAINER ID   IMAGE                                                COMMAND                  CREATED          STATUS                          PORTS                                         NAMES
5059605a4ea3   ghcr.io/immich-app/immich-server:release             "tini -- /bin/bash s…"   14 minutes ago   Up 12 minutes (healthy)         0.0.0.0:2283->3001/tcp, [::]:2283->3001/tcp   immich_server
2892608a27de   tensorchord/pgvecto-rs:pg14-v0.2.0                   "docker-entrypoint.s…"   14 minutes ago   Up 12 minutes (healthy)         5432/tcp                                      immich_postgres
ea9a81b80398   redis:6.2-alpine                                     "docker-entrypoint.s…"   14 minutes ago   Up 12 minutes (healthy)         6379/tcp                                      immich_redis
85ec0fea8409   ghcr.io/immich-app/immich-machine-learning:release   "tini -- ./start.sh"     14 minutes ago   Up 12 minutes (healthy)                                                       immich_machine_learning
769943d69e65   1b05b09d5e10                                         "tini -- /bin/bash s…"   4 months ago     Restarting (1) 55 seconds ago                                                 immich_microservices
```

The app appears to be up and the web server is functioning, but I don't remember the microservices container restarting all the time like that.
