### DISCUSSION TITLE
Web: Download takes space of the media 2 times

### DISCUSSION THREAD

**Discussion by hofq** [immich-app/immich#13215] [Feature Request]
### The bug

If i download a file, the space is taken up 2 times.
So if i download a 50gig media file, i have to have 100 gigs available on my client.

I believe that happens because of the split download design which was selected to use. After a download hitting 100% in the Webui, it will be downloaded via the browsers download manager. In that Time frame the disk space is taken up 2 times until the Webpage is reloaded.

### The OS that Immich Server is running on

K3S/ Kubernetes. Chartversion 0.* (latest)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

not used

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
there is none.

My values file:

        image:
          tag: v1.115.0
        immich:
          persistence: 
            library: 
              existingClaim: immich-data
        postgresql:
          image:
            registry: ghcr.io
            repository: hofq/immich-charts/pg-bitnami-vecto-rs
            tag: 14.5.0-debian-11-r6
            pullPolicy: Always
          enabled: true
          global:
            postgresql:
              auth:
                existingSecret: postgres-immich
                database: immich
                username: immich
                secretKeys:
                  adminPasswordKey: postgres-admin-password
                  userPasswordKey: postgres-password
                  replicationPasswordKey: postgres-replication-password
        redis:
          enabled: true
          auth:
            enabled: false
        env:
          DB_USERNAME: immich
          POSTGRES_USER: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: postgres-immich
                key: postgres-password
```

### Your .env content

```Shell
see above. 2in1
```

### Reproduction steps

1. Go to a media file
2. Press Download
3. Wait for the In-Browser Download
4. See the Media File taking 2x the Space of its size on your Disk

### Additional information

This is especially a problem with large Media files. As i work a lot with 100M 4k 25p Records from my A7III, i hit large file sizes quite fast
