### DISCUSSION TITLE
Web: Download cannot be ran again

### DISCUSSION THREAD

**Discussion by hofq** [immich-app/immich#13216] [Q&A]
### The bug

If i try to run a download of a mediafile again, it just failes and must be retriggered in the web ui while loosing the whole downloads progress.

This issue came up as my drive hit its full capacity.

### The OS that Immich Server is running on

K3S/ Kubernetes. Chartversion 0.* (latest)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

not used

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
there is none.

My values file:

        image:
          tag: v1.115.0
        immich:
          persistence: 
            library: 
              existingClaim: immich-data
        postgresql:
          image:
            registry: ghcr.io
            repository: hofq/immich-charts/pg-bitnami-vecto-rs
            tag: 14.5.0-debian-11-r6
            pullPolicy: Always
          enabled: true
          global:
            postgresql:
              auth:
                existingSecret: postgres-immich
                database: immich
                username: immich
                secretKeys:
                  adminPasswordKey: postgres-admin-password
                  userPasswordKey: postgres-password
                  replicationPasswordKey: postgres-replication-password
        redis:
          enabled: true
          auth:
            enabled: false
        env:
          DB_USERNAME: immich
          POSTGRES_USER: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: postgres-immich
                key: postgres-password
```

### Your .env content

```Shell
see above. 2in1
```

### Reproduction steps

1. go to a media file that is larger than disk space is available on your device
2. click download
3. after the download in the web ui finishes wait for the download/transfer in your browser to fail
...
