### DISCUSSION TITLE
Immich group files with same filename but different extension/timestamp/exif as a live photo.

### DISCUSSION THREAD

**Discussion by raidolo** [immich-app/immich#13278] [Q&A]
### The bug

Little background: I've always backed up my wife's photos using "DS Files" on my Synology NAS. The photos were archived in her home folder and the duplicated filenames were renamed to <filenamenew>_1.extension, so nothing has been overwritten by DS Files. But, it can happen that you have a photo and a video with the same filename, of course one has a photo extension (JPG, HEIC, PNG) and the other is a video (MOV), you probably have taken the video in a different moment, because the file naming on the phones and cameras can be cyclical you ended up with the same filename. For instance I have two files, IMG_3223.PNG and IMG_3223.MOV. Different metadata, different timestamps/exifs. 

```
username@hostname:/volume2/homes/username/photos$ ls -al IMG_3223*
-rwxrwxrwx+ 1 username users 34695688 Aug  1  2021 IMG_3223.MOV
-rwxrwxrwx+ 1 username users  2583316 Sep  3 19:08 IMG_3223.PNG

```

I've uploaded the files using immich-go and immich server just grouped the two files in a "live photo", even if a PNG would never be a live photo in any phone in the market. 

Is there any way to fix this? 
Why immich grouped two files with so much different timestamps/exif data?

Thanks in advance.

### The OS that Immich Server is running on

Docker - Synology x86 (xpenology)

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: Europe/Rome
      BACKUP_ON_START: 'FALSE'
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database  
    

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume2/Dati/Media
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. upload two files one image and one MOV file with the same filename "suffix" like IMG_0002.PNG and IMG_0002.MOV with immich-go
2. check the web ui, they will be grouped into a live photo.

### Relevant log output

```shell
These two are two lines in the immich-go log with are one near each other (you can see the timestamp they are 1 second apart)

 INFO | uploaded | file=IMG_3223.PNG "capture date"="2024-09-03 19:08:08 +0200 CEST" time="2024-10-07T11:39.58 CEST"
 INFO | uploaded | file=IMG_3224.MOV "capture date"="2021-08-01 18:03:00 +0200 CEST" time="2024-10-07T11:39.59 CEST"
```
