### DISCUSSION TITLE
Just installed immich using docker-compose, logged in, added 1 photo and ... no thumbnail, extract metadata job stuck

### DISCUSSION THREAD

**Discussion by antrv** [immich-app/immich#13309] [Q&A]
Here is my docker-compose file 

```YAML‎
name: immich

services:
    immich-server:
        image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
        container_name: immich_server
        restart: unless-stopped
        healthcheck:
            disable: false
        networks:
            - proxy
        # extends:
        #   file: hwaccel.transcoding.yml
        #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
#        ports:
#            - 2283:3001
        volumes:
            # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
            - ${UPLOAD_LOCATION}:/usr/src/app/upload
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - stack.env
        depends_on:
            - redis
            - database
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.immich.entrypoints=https"
            - "traefik.http.routers.immich.rule=Host(`photos.mylocaldomain`)"
            - "traefik.http.routers.immich.tls=true"
            - "traefik.http.services.immich.loadbalancer.server.port=3001"

    immich-machine-learning:
        container_name: immich_machine_learning
        # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
        image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #   file: hwaccel.ml.yml
        #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
        restart: unless-stopped
        healthcheck:
            disable: false
        networks:
            - proxy
        volumes:
            - ${CONTAINER_DATA}/model-cache:/cache
        env_file:
            - stack.env

    redis:
        image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
        container_name: immich_redis
        restart: unless-stopped
        networks:
            - proxy
        healthcheck:
            test: redis-cli ping || exit 1

    database:
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
        container_name: immich_postgres
        restart: unless-stopped
        networks:
            - proxy
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE_NAME}
            - POSTGRES_INITDB_ARGS=--data-checksums
#            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
            - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
            interval: 5m
            start_interval: 30s
            start_period: 5m
        command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

networks:
    proxy:
        external: true
```

stack.env file:
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user-data/PhotoLibrary
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/container-data/immich/postgres
CONTAINER_DATA=/mnt/container-data/immich

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Helsinki

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

and I see some errors in the logs:

```
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] TagController {/api/tags}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/assets, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RoutesResolver] ViewController {/api/view}:
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 17  - 10/09/2024, 3:22:52 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.117.0] [PRODUCTION] 
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:NestFactory] Starting Nest application...
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] OpenTelemetryModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] OpenTelemetryCoreModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] ConfigHostModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] DiscoveryModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] ClsModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] ConfigModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:InstanceLoader] MicroservicesModule dependencies initialized
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:NestApplication] Nest application successfully started
[Nest] 7  - 10/09/2024, 3:22:52 PM     LOG [Microservices:Bootstrap] Immich Microservices is running [v1.117.0] [PRODUCTION] 
[Nest] 17  - 10/09/2024, 3:22:56 PM     LOG [Api:EventRepository] Websocket Connect:    6_hFWR9suxWbE7HrAAAB
[Nest] 17  - 10/09/2024, 3:22:56 PM   ERROR [Api:EventRepository] Websocket connection error: UnauthorizedException: Invalid user token
UnauthorizedException: Invalid user token
    at AuthService.validateSession (/usr/src/app/dist/services/auth.service.js:307:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AuthService.authenticate (/usr/src/app/dist/services/auth.service.js:91:25)
    at async EventRepository.handleConnection (/usr/src/app/dist/repositories/event.repository.js:48:26)
[Nest] 17  - 10/09/2024, 3:22:56 PM     LOG [Api:EventRepository] Websocket Disconnect: 6_hFWR9suxWbE7HrAAAB
[Nest] 7  - 10/09/2024, 3:23:27 PM    WARN [Microservices:MediaService] Thumbnail generation failed for asset 050128bd-0ea0-49f1-a20a-ca94c210da01: not found
[Nest] 17  - 10/09/2024, 3:23:28 PM     LOG [Api:EventRepository] Websocket Connect:    5XmE7uFYlCWbp33VAAAD
[Nest] 7  - 10/09/2024, 3:24:23 PM    WARN [Microservices:JobService] Skipping unknown job: "undefined"
Error: Missing lock for job 3. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:266:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 17  - 10/09/2024, 3:27:47 PM     LOG [Api:EventRepository] Websocket Disconnect: 5XmE7uFYlCWbp33VAAAD
[Nest] 17  - 10/09/2024, 3:27:47 PM     LOG [Api:EventRepository] Websocket Connect:    xC6rWj8q-3hgulL3AAAF
[Nest] 17  - 10/09/2024, 3:27:53 PM     LOG [Api:EventRepository] Websocket Disconnect: xC6rWj8q-3hgulL3AAAF
[Nest] 17  - 10/09/2024, 3:27:53 PM     LOG [Api:EventRepository] Websocket Connect:    MaLYiUEtH8zMIg_WAAAH
[Nest] 17  - 10/09/2024, 3:30:57 PM     LOG [Api:EventRepository] Websocket Disconnect: MaLYiUEtH8zMIg_WAAAH
[Nest] 17  - 10/09/2024, 3:30:58 PM     LOG [Api:EventRepository] Websocket Connect:    Rzi7wWWC6cwIs6rpAAAJ
[Nest] 17  - 10/09/2024, 3:33:33 PM     LOG [Api:EventRepository] Websocket Disconnect: Rzi7wWWC6cwIs6rpAAAJ
[Nest] 17  - 10/09/2024, 3:33:34 PM     LOG [Api:EventRepository] Websocket Connect:    FZKzx9FpOv0sDmO8AAAL
[Nest] 17  - 10/09/2024, 3:35:20 PM     LOG [Api:EventRepository] Websocket Disconnect: FZKzx9FpOv0sDmO8AAAL
[Nest] 17  - 10/09/2024, 3:35:20 PM     LOG [Api:EventRepository] Websocket Connect:    WtndkTflUevliB8NAAAN
[Nest] 17  - 10/09/2024, 3:36:06 PM     LOG [Api:EventRepository] Websocket Disconnect: WtndkTflUevliB8NAAAN
[Nest] 17  - 10/09/2024, 3:36:06 PM     LOG [Api:EventRepository] Websocket Connect:    sSj2pzMnC_1K7FjUAAAP
```

Whats wrong with my installation?
