### DISCUSSION TITLE
Cannot resolve redis

### DISCUSSION THREAD

**Discussion by bjoernwuest** [immich-app/immich#13325] [Q&A]
### The bug

When starting up immich, I get below error message in logs:

My docker compose.yaml file (excerpt with just immich) is below.

### The OS that Immich Server is running on

Docker compose @ Ubuntu 24.04

### Version of Immich Server

release

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
##################################
### Immich Services
##################################
  immich_server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    profiles: [run, immich]
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /Docker/safe_dedup/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_USERNAME=immich
      - DB_PASSWORD=immich
      - DB_DATABASE_NAME=immich
    ports:
      - 3001:3001
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    healthcheck:
      disable: false

  immich_machine_learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    profiles: [run, immich]
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /Docker/safe_dedup/immich/model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  immich_redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    profiles: [run, immich]
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich_postgres:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    profiles: [run, immich]
    environment:
      POSTGRES_PASSWORD_FILE: /postgres_password.secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /Docker/postgresql/immich/14:/var/lib/postgresql/data
      - /Docker/safe_dedup/immich/postgres.secret:/postgres_password.secret:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -t 5 -U postgres"]
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c">    restart: always
```

### Your .env content

```Shell
n/a, do not use .env file!
```

### Reproduction steps

1. docker compose --profile immich up -d
2. docker compose logs immich_server

### Relevant log output

```shell
immich_server  | Error: getaddrinfo ENOTFOUND redis
immich_server  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
immich_server  |   errno: -3008,
immich_server  |   code: 'ENOTFOUND',
immich_server  |   syscall: 'getaddrinfo',
immich_server  |   hostname: 'redis'
immich_server  | }
```
