### DISCUSSION TITLE
Listen port 2283:2283 on v1.118.0

### DISCUSSION THREAD

**Discussion by reraxe** [immich-app/immich#13464] [Q&A]
### The bug

"Reverse proxies using port 3001 also need to be updated to use port 2283."

Still listens to 3001.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.118.0

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
...
image: ghcr.io/immich-app/immich-server:v1.118.0
...
      labels:
        - "traefik.http.services.immich.loadbalancer.server.port=3001"
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Launch server with 2283 listen port.
2. Does not launch. Check log and shows listening to 3001
3. changed it back to 3001 to launch server.
...

### Relevant log output

```shell
[Nest] 17  - 10/15/2024, 10:05:46 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.118.0] [production]
```
