### DISCUSSION TITLE
Rockchip RK3588 encoding error

### DISCUSSION THREAD

**Discussion by norton-chris** [immich-app/immich#13626] [Q&A]
### The bug

I'm trying to run hardware encoding on the rkmpp (Rockchip RK3588) on the RockPi5 and I'm seeing the error below (in the log output section)

### The OS that Immich Server is running on

Armbian 23.8.1 bullseye

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v.1.118.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: rkmpp # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-7936f8bd-919b-463a-8e0f-ea540e30d588/RAID_Drive/Family_Photos:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: armnn # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-7936f8bd-919b-463a-8e0f-ea540e30d588/RAID_Drive/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-7936f8bd-919b-463a-8e0f-ea540e30d588/RAID_Drive/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Chicago

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD={password}

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Enable rkmpp in docker compose
2. Enable rkmpp in immich setting
3. Start transcoding and view logs

### Relevant log output

```shell
[Nest] 7  - 10/20/2024, 12:07:12 PM     LOG [Microservices:MediaService] Encoding video 1f39a14d-2578-45a4-9007-17c2b0672a4f with RKMPP acceleration
[Nest] 7  - 10/20/2024, 12:07:12 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel rkmpp -hwaccel_output_format drm_prime -afbc rga -noautorotate -i /usr/src/app/external/Erica/Erica's phone/Erica’s iPhone (2)/Recents/IMG_2445.MOV -y -c:v h264_rkmpp -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -strict unofficial -map 0:1 -g 256 -v verbose -vf scale_rkrga=-2:1080:format=p010:afbc=1,hwmap=derive_device=opencl:mode=read,tonemap_opencl=format=nv12:r=pc:p=bt709:t=bt709:m=bt709:tonemap=hable:desat=0,hwmap=derive_device=rkmpp:mode=write:reverse=1,format=drm_prime -level 51 -threads 1 -rc_mode CQP -qp_init 23 upload/encoded-video/e82c154f-2013-4b59-95f9-a54c6d050595/1f/39/1f39a14d-2578-45a4-9007-17c2b0672a4f.mp4
[Nest] 7  - 10/20/2024, 12:07:12 PM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Routing option strict to both codec and muxer layer
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f861a0180] stream 0, timescale not set
Selecting decoder 'hevc_rkmpp' because of requested hwaccel method rkmpp
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/usr/src/app/external/Erica/Erica's phone/Erica’s iPhone (2)/Recents/IMG_2445.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2023-10-04T04:56:21.000000Z
    com.apple.quicktime.is-montage: iMovie
  Duration: 00:12:49.53, start: 0.000000, bitrate: 15368 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10), 1 reference frame (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67, left), 1920x1080, 15112 kb/s, 29.99 fps, 30 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2023-10-04T04:56:21.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 4, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4
        Ambient Viewing Environment, ambient_illuminance=314.000000, ambient_light_x=0.312700, ambient_light_y=0.329000
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 250 kb/s (default)
      Metadata:
        creation_time   : 2023-10-04T04:56:21.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x0]: Video: mjpeg (Baseline), 1 reference frame, yuvj420p(pc, bt470bg/unknown/unknown, center), 480x270 [SAR 72:72 DAR 16:9], 90k tbr, 90k tbn (attached pic)
[out#0/mp4 @ 0x7f861e0840] Adding streams from explicit maps...
[vost#0:0/h264_rkmpp @ 0x7f86216480] Created video stream from input stream 0:0
[hevc_rkmpp @ 0x7f862e4780] Picked up an existing RKMPP hardware device
[aost#0:1/aac @ 0x7f86211c80] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_rkmpp) -> h264 (h264_rkmpp))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
[vost#0:0/h264_rkmpp @ 0x7f86216480] Starting thread...
[aost#0:1/aac @ 0x7f86211c80] Starting thread...
[vf#0:0 @ 0x7f86057c00] Starting thread...
[af#0:1 @ 0x7f860578e0] Starting thread...
[vist#0:0/hevc @ 0x7f86150f00] [dec:hevc_rkmpp @ 0x7f861b0400] Starting thread...
[aist#0:1/aac @ 0x7f86150a80] [dec:aac @ 0x7f861b2700] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f86080480] Starting thread...
Press [q] to stop, [?] for help
[graph_1_in_0:1 @ 0x7f7e090240] tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:stereo
[hevc_rkmpp @ 0x7f862e4780] Noticed an info change
[hevc_rkmpp @ 0x7f862e4780] Configured with size: 1920x1080 | pix_fmt: drm_prime | sw_pix_fmt: nv15
[graph 0 input from stream 0:0 @ 0x7f7a0c0600] w:1920 h:1080 pixfmt:drm_prime tb:1/600 fr:30/1 sar:0/1 csp:bt2020nc range:tv
[Parsed_scale_rkrga_0 @ 0x7f7a0c0240] w:1920 h:1080 fmt:nv15 -> w:1920 h:1080 fmt:p010le
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
[AVHWDeviceContext @ 0x7f7a0c0840] 0.0: ARM Platform / Unknown Device

[Nest] 7  - 10/20/2024, 12:07:12 PM   ERROR [Microservices:MediaService] Error occurred during transcoding: ffmpeg was killed with signal SIGSEGV
```

### Additional information
cat hwaccel.transcoding.yml 
version: "3.8"

services:
  cpu: {}

  rkmpp:
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    volumes:
      - /etc/OpenCL:/etc/OpenCL:ro # Ensure /etc/OpenCL exists and has the correct configuration files
      - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro # Required for Mali GPU acceleration
    environment:
      - LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu  # Set this environment variable for Mali libraries

I thought I had this working recently, but now I can't seem to get the acceleration to work. It doesn't even revert to CPU after, it just gets stuck.
