### DISCUSSION TITLE
Machine Learning Worker get a SIGKILL and failed when photo is uploaded.

### DISCUSSION THREAD

**Discussion by Reivax47** [immich-app/immich#13681] [Q&A]
### The bug

When I upload a picture from my phone, the worker crash. Facial detection failed to do his job. But, if I use the task manager to run face detection and recognition, then it's work fine. 

### The OS that Immich Server is running on

Debian

### Version of Immich Server

V1.118.2

### Version of Immich Mobile App

v1.118.0 build.163

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-ad367a2e-4c8a-4c56-90ba-27ca2aae78bb/ImmichLibrary
# The location where your database files are stored
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-ad367a2e-4c8a-4c56-90ba-27ca2aae78bb/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=#######

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xavier
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.Take a picture
2.Open Immich app on smartphone.
3.Crash
...

### Relevant log output

```shell
Log from machine_leraning

[10/22/24 15:20:49] INFO     Booting worker with pid: 107045                    
[10/22/24 15:26:17] INFO     Starting gunicorn 23.0.0                           
[10/22/24 15:26:17] INFO     Listening at: http://[::]:3003 (9)                 
[10/22/24 15:26:17] INFO     Using worker: app.config.CustomUvicornWorker       
[10/22/24 15:26:17] INFO     Booting worker with pid: 17                        
[10/22/24 15:26:35] INFO     Started server process [17]                        
[10/22/24 15:26:35] INFO     Waiting for application startup.                   
[10/22/24 15:26:35] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[10/22/24 15:26:35] INFO     Initialized request thread pool with 4 threads.    
[10/22/24 15:26:35] INFO     Application startup complete.                      
[10/22/24 15:28:43] INFO     Loading visual model                               
                             'ViT-H-14-378-quickgelu__dfn5b' to memory          
[10/22/24 15:28:43] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         
[10/22/24 15:30:36] CRITICAL WORKER TIMEOUT (pid:17)                            
[10/22/24 15:31:33] ERROR    Worker (pid:17) was sent SIGKILL! Perhaps out of   
                             memory?                                            
[10/22/24 15:31:33] INFO     Booting worker with pid: 99                        
[10/22/24 15:31:39] INFO     Started server process [99]                        
[10/22/24 15:31:39] INFO     Waiting for application startup.                   
[10/22/24 15:31:39] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[10/22/24 15:31:39] INFO     Initialized request thread pool with 4 threads.    
[10/22/24 15:31:39] INFO     Application startup complete.                      
[10/22/24 15:31:39] INFO     Loading visual model                               
                             'ViT-H-14-378-quickgelu__dfn5b' to memory          
[10/22/24 15:31:39] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         
[10/22/24 15:33:40] CRITICAL WORKER TIMEOUT (pid:99)                            
[10/22/24 15:34:38] ERROR    Worker (pid:99) was sent SIGKILL! Perhaps out of   
                             memory?                                            
[10/22/24 15:34:38] INFO     Booting worker with pid: 150                       
[10/22/24 15:34:44] INFO     Started server process [150]                       
[10/22/24 15:34:44] INFO     Waiting for application startup.                   
[10/22/24 15:34:44] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[10/22/24 15:34:44] INFO     Initialized request thread pool with 4 threads.    
[10/22/24 15:34:44] INFO     Application startup complete.   

Log from server

[Nest] 7  - 10/22/2024, 3:33:41 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
[Nest] 7  - 10/22/2024, 3:33:41 PM   ERROR [Microservices:JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:108:27)
    at async /usr/src/app/dist/services/job.service.js:163:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 10/22/2024, 3:33:41 PM   ERROR [Microservices:JobService] Object:
{
  "id": "ea95eb31-48c5-4ab6-b26e-ad573c6d5b85",
  "source": "upload"
}
```

### Additional information

Works of PI5 with 8Gb of memory. I checked memory use with htop, and it's seemed that there is no huge use of memory.
