### DISCUSSION TITLE
Authentication Error?

### DISCUSSION THREAD

**Discussion by bhamtech23data** [immich-app/immich#13865] [Q&A]
Hi all,

I'm running Immich in docker on a VPS with external block storage. 
It has four containers - server, postgress, redis and machine learning. 

A week or so ago, I noticed that the server was not accepting uploads or in turn login, and further to that the Web portal does not resolve. 

Investigation found all containers are 'healthy' but the server container has this error in the logs. 

ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}

I can see its an authentication error with redis, but not sure how to fix.

Any ideas would be greatly appreciated. 

Thanks 
S

**Comment by bo0tzz** [comment]
Can you post the relevant info? Your compose file, redis logs, etc.

**Comment by bhamtech23data** [comment]
Thanks for your reply, here is the info you requested.
Just to clarify,  the instance was working fine and uploaded 70Gb of photos and following that the app continued to backup my photos as the occurred without fail.   Then is stopped...



**Docker Compose**
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - NPM-NET-MAIN

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - NPM-NET-MAIN
      
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - NPM-NET-MAIN

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB>
      interval: 5m
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "m>
    restart: always
    networks:
      - NPM-NET-MAIN

volumes:
  model-cache:

networks:
  NPM-NET-MAIN:
    external: true
```

**.env file**
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/VolumeBlock001/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/VolumeBlock001/immich/db

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Australia/Sydney

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<password for db>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```
**Following logs taken from Portainer**

**Redis Logs**

```
1:M 01 Nov 2024 12:10:33.183 * Background saving terminated with success
1:M 01 Nov 2024 12:15:34.022 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:15:34.023 * Background saving started by pid 38916
38916:C 01 Nov 2024 12:15:34.094 * DB saved on disk
38916:C 01 Nov 2024 12:15:34.094 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:15:34.124 * Background saving terminated with success
1:M 01 Nov 2024 12:20:35.057 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:20:35.058 * Background saving started by pid 38987
38987:C 01 Nov 2024 12:20:35.127 * DB saved on disk
38987:C 01 Nov 2024 12:20:35.128 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:20:35.158 * Background saving terminated with success
1:M 01 Nov 2024 12:25:36.013 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:25:36.014 * Background saving started by pid 39057
39057:C 01 Nov 2024 12:25:36.086 * DB saved on disk
39057:C 01 Nov 2024 12:25:36.087 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:25:36.114 * Background saving terminated with success
1:M 01 Nov 2024 12:30:37.056 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:30:37.057 * Background saving started by pid 39129
39129:C 01 Nov 2024 12:30:37.137 * DB saved on disk
39129:C 01 Nov 2024 12:30:37.138 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:30:37.158 * Background saving terminated with success
1:M 01 Nov 2024 12:35:38.011 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:35:38.012 * Background saving started by pid 39199
39199:C 01 Nov 2024 12:35:38.087 * DB saved on disk
39199:C 01 Nov 2024 12:35:38.088 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:35:38.112 * Background saving terminated with success
1:M 01 Nov 2024 12:40:39.071 * 100 changes in 300 seconds. Saving...
1:M 01 Nov 2024 12:40:39.072 * Background saving started by pid 39269
39269:C 01 Nov 2024 12:40:39.145 * DB saved on disk
39269:C 01 Nov 2024 12:40:39.145 * RDB: 0 MB of memory used by copy-on-write
1:M 01 Nov 2024 12:40:39.173 * Background saving terminated with success
```


**Immich server logs**
```

ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
ReplyError: NOAUTH Authentication required.
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'info', args: [] }
}
```

**Postgress Logs**

```
2024-08-14 12:41:16.473 UTC [1] LOG:  redirecting log output to logging collector process
2024-08-14 12:41:16.473 UTC [1] HINT:  Future log output will appear in directory "log".
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-08-14 12:45:51.160 UTC [1] LOG:  redirecting log output to logging collector process
2024-08-14 12:45:51.160 UTC [1] HINT:  Future log output will appear in directory "log".
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-10-18 11:30:02.684 UTC [1] LOG:  redirecting log output to logging collector process
2024-10-18 11:30:02.684 UTC [1] HINT:  Future log output will appear in directory "log".
```


**Following logs taken from output of "docker compose logs -f"**

```
immich_redis             | 39129:C 01 Nov 2024 12:30:37.137 * DB saved on disk
immich_redis             | 39129:C 01 Nov 2024 12:30:37.138 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 01 Nov 2024 12:30:37.158 * Background saving terminated with success
immich_redis             | 1:M 01 Nov 2024 12:35:38.011 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 01 Nov 2024 12:35:38.012 * Background saving started by pid 39199
immich_redis             | 39199:C 01 Nov 2024 12:35:38.087 * DB saved on disk
immich_redis             | 39199:C 01 Nov 2024 12:35:38.088 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 01 Nov 2024 12:35:38.112 * Background saving terminated with success
immich_redis             | 1:M 01 Nov 2024 12:40:39.071 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 01 Nov 2024 12:40:39.072 * Background saving started by pid 39269
immich_redis             | 39269:C 01 Nov 2024 12:40:39.145 * DB saved on disk
immich_redis             | 39269:C 01 Nov 2024 12:40:39.145 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 01 Nov 2024 12:40:39.173 * Background saving terminated with success
immich_redis             | 1:M 01 Nov 2024 12:45:40.018 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 01 Nov 2024 12:45:40.019 * Background saving started by pid 39340
immich_redis             | 39340:C 01 Nov 2024 12:45:40.098 * DB saved on disk
immich_redis             | 39340:C 01 Nov 2024 12:45:40.100 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 01 Nov 2024 12:45:40.120 * Background saving terminated with success

```







Thanks
