### DISCUSSION TITLE
Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'

### DISCUSSION THREAD

**Discussion by RonaldPM** [immich-app/immich#13862] [Q&A] [answered]
### The bug

I restarted my server and I was presented with the following errors in Immich Server log

```
Initializing Immich v1.119.1

Detected CPU Cores: 4

Starting api worker

Starting microservices worker

[Nest] 7  - 10/31/2024, 10:11:07 PM     LOG [Microservices:EventRepository] Initialized websocket server

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:MapRepository] Initializing metadata repository

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:MapRepository] Initializing metadata repository

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:ServerService] Feature Flags: {

  "smartSearch": true,

  "facialRecognition": true,

  "duplicateDetection": true,

  "map": true,

  "reverseGeocoding": true,

  "importFaces": false,

  "sidecar": true,

  "search": true,

  "trash": true,

  "oauth": false,

  "oauthAutoLaunch": false,

  "passwordLogin": true,

  "configFile": false,

  "email": false

}

[Nest] 17  - 10/31/2024, 10:11:08 PM     LOG [Api:EventRepository] Initialized websocket server

[Nest] 7  - 10/31/2024, 10:11:08 PM     LOG [Microservices:StorageService] Verifying system mount folder checks (enabled=true)

[Nest] 7  - 10/31/2024, 10:11:08 PM   ERROR [Microservices:StorageService] Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'

microservices worker error: Error: Failed to read "<UPLOAD_LOCATION>/encoded-video/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information."

microservices worker exited with code 1
```

I have tried restarting, tried removing and recreating .immich files in folders as recommended [here](https://github.com/immich-app/immich/discussions/12798#discussioncomment-10918056) but with no luck. 

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.119.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Shut down Immich
2. Start again using `docker compose up -d`
3. Look at the Immich server logs
...

### Relevant log output

```shell
Given above
```
