### DISCUSSION TITLE
immich keeps creating new files in upload directory even when no new files are uploaded

### DISCUSSION THREAD

**Discussion by adityajpatil** [immich-app/immich#13994] [Q&A]
### The bug

I noticed that the storage use shown in immich keeps increasing steadily. As it has only been few weeks that I am using immich, I don't know if this has been since start or something that started in a recent version.

See the two photos below, where the disk usage has increased even though only 2 photos have been added. The underlying disk is a zfs raidz1 system, which I use exclusively for immich.

![Screenshot 2024-11-06 1245142](https://github.com/user-attachments/assets/cae7e8bb-db1d-412f-a7a8-dc60e0bbb005)
<img width="1396" alt="Screenshot 2024-11-07 203027" src="https://github.com/user-attachments/assets/77dbc3a7-a567-4c30-b4a3-0bbd4e77b5ad">

I used the following command to check for recently added files in the immich upload directory.

```
$ ls -alh $(find . -name '*.*'  -mtime -0.1)
find: ‘./postgres’: Permission denied
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/backups/.immich
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/encoded-video/.immich
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/library/.immich
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/profile/.immich
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/thumbs/.immich
-rw-r--r-- 1 root root 369M Nov  7 20:25 ./library/upload/d453a362-e73f-4c19-99a8-fca45ad93ce7/0b/f6/0bf6fe4e-61aa-4d93-bb63-b4190bd35570.mp4
-rw-r--r-- 1 root root 5.0M Nov  7 20:48 ./library/upload/d453a362-e73f-4c19-99a8-fca45ad93ce7/3b/46/3b46937d-f339-47fe-83d0-d33c687524c4.mp4
-rw-r--r-- 1 root root 207M Nov  7 20:48 ./library/upload/d453a362-e73f-4c19-99a8-fca45ad93ce7/ae/24/ae249d64-6519-46be-8baf-85d0cd883614.mp4
-rw-r--r-- 1 root root   13 Nov  7 20:32 ./library/upload/.immich
```

Notice the three mp4 files. I haven't added any video in the last 0.1 day. I copied over one of this video to my local disk but vlc can't play it.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.120.0

### Version of Immich Mobile App

1.119.0 build.164

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/storage/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/storage/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Calcutta

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Watch immich storage space usage tick up continuously
...
