### DISCUSSION TITLE
Immich Server not using Nvidia Transcode on Unraid

### DISCUSSION THREAD

**Discussion by adamzvolanek** [immich-app/immich#14053] [Q&A]
I have machine learning hardware acceleration setup however I cannot get the NVENC transcode working on the Immich Server itself. Here is my docker-compose file:

I can verify the immich-machine-learning component has the nvidia gpu 'useable?' by running `nvidia-smi` however I have no such command on the immich-server. Likewise, I set the transcode policy to "all videos" and did not see a process appear on my nvidia gpu.

```yaml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:2283:2283"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      #- /path/to/config/immich-config.json:/immich-config.json
    environment:
      TZ: ${TZ}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      #IMMICH_CONFIG_FILE: /immich-config.json
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_GPUID}
      NVIDIA_DRIVER_CAPABILITIES: 'all'
    depends_on:
      - redis
      - database
    restart: always
#    healthcheck:
#      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    networks:
      - devrack
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - /mnt/user/Scratch/immich:/cache
    restart: always
#    healthcheck:
#      disable: false
```
