### DISCUSSION TITLE
Automatically database backup not happen

### DISCUSSION THREAD

**Discussion by mcjak97** [immich-app/immich#14077] [Q&A] [answered]
### The bug

I have automatically backup setting activated but it's not working.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

v1.120.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    logging:
      driver: "journald"
      options:
        tag: "immich-server"
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /mnt/nas:/mnt/pictures
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /mnt/nas:/mnt/pictures
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no->
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
LIBRARY_LOCATION=/mnt/photos
THUMBS_LOCATION=/mnt/immich-cache/thumbs
UPLOAD_LOCATION=/mnt/immich-cache/upload
PROFILE_LOCATION=/mnt/immich-cache/profile
VIDEO_LOCATION=/mnt/immich-cache/encoded-video

# The location where your database files are stored
# DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Bucharest

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Activate backup in settings at 02.00 AM every night
2. Checking server logs and upload location, but no backup found

![384587916-af520055-41d1-40b0-9255-2ed84d8e809f](https://github.com/user-attachments/assets/13b26bac-8f8c-4dde-8a63-2a2473bec385)

### Relevant log output

```shell
`[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Refreshing library 1d9a97c7-9568-414f-af1e-fa7893e102f1 for new assets
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Refreshing library 6136d46d-7234-4f2f-8467-7a951a9ed8f3 for new assets
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Refreshing library 01aa388e-7456-426b-9c53-d0caaea388bd for new assets
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Scanning library 6136d46d-7234-4f2f-8467-7a951a9ed8f3 for removed assets
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Scanning library 1d9a97c7-9568-414f-af1e-fa7893e102f1 for removed assets
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Finished queueing check of 1196 assets for library 1d9a97c7-9568-414f-af1e-fa7893e102f1
[Nest] 7 - 11/09/2024, 12:00:00 AM LOG [Microservices:LibraryService] Scanning library 01aa388e-7456-426b-9c53-d0caaea388bd for removed assets
[Nest] 7 - 11/09/2024, 12:00:01 AM LOG [Microservices:LibraryService] Finished queueing check of 6273 assets for library 01aa388e-7456-426b-9c53-d0caaea388bd
[Nest] 7 - 11/09/2024, 12:00:05 AM LOG [Microservices:LibraryService] Finished queueing check of 29696 assets for library 6136d46d-7234-4f2f-8467-7a951a9ed8f3
[Nest] 17 - 11/09/2024, 1:47:32 AM LOG [Api:EventRepository] Websocket Disconnect: 6S1tZrEHoT-5XSKgAAAd
[Nest] 17 - 11/09/2024, 1:47:34 AM LOG [Api:EventRepository] Websocket Connect: 1jDu7HmUTeagzySfAAAj
[Nest] 17 - 11/09/2024, 9:00:17 AM LOG [Api:EventRepository] Websocket Connect: cy4NdYuF2sixV_cvAAAl
[Nest] 17 - 11/09/2024, 9:00:44 AM LOG [Api:EventRepository] Websocket Disconnect: cy4NdYuF2sixV_cvAAAl`
```
