### DISCUSSION TITLE
CLI upload failes with Error 400

### DISCUSSION THREAD

**Discussion by F-Node-Karlsruhe** [immich-app/immich#14072] [Q&A] [answered]
### The bug

When uploading with the CLI tool 2.2.30 i always get an Error 400, no matter if recursive, album or other options

```
immich upload /images/dir/image.JPG 
Crawling for assets...
Checking files | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0% | ETA: 0s | 0/1 assets
Found 0 new files and 0 duplicates
Failed to verify 1 file:
- /images/dir/image.JPG - Error: Error: 400
All assets were already uploaded, nothing to do.
```

The error appears to happen on bulkUploadCheck as i could see in the nginx logs

```
- - [09/Nov/2024:23:13:00 +0100] "POST /api/assets/bulk-upload-check HTTP/1.1" 301 178 "-" "node"
- - [09/Nov/2024:23:13:00 +0100] "GET /api/assets/bulk-upload-check HTTP/1.1" 400 99 "-" "node"
```

Is this a known problem or am i doing something wrong (as 400 suggests) or is the latest cli not compatible with the latest server API?

### The OS that Immich Server is running on

Ubuntu 22.04.1 LTS

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=yyy
DB_PASSWORD=xxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. docker run --rm -it -v /home/user/images:/images node:20-slim bash
2. npm i -g @immich/cli
3. immich login
4. immich upload /your/image.jpg
...

### Relevant log output

```shell
# immich cli
Crawling for assets...
Checking files | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0% | ETA: 0s | 0/1 assets
Found 0 new files and 0 duplicates
Failed to verify 1 file:
- /images/dir/image.JPG - Error: Error: 400
All assets were already uploaded, nothing to do.


# nginx
- - [09/Nov/2024:23:13:00 +0100] "POST /api/assets/bulk-upload-check HTTP/1.1" 301 178 "-" "node"
- - [09/Nov/2024:23:13:00 +0100] "GET /api/assets/bulk-upload-check HTTP/1.1" 400 99 "-" "node"
```

### Additional information

I cannot tell since when the problem exists as the last time i used the CLI tool successfully is over half a year ago.
Upload via App or Web works fine.
