### DISCUSSION TITLE
crontab time for automatic backup is incorrect

### DISCUSSION THREAD

**Discussion by wistoch** [immich-app/immich#14139] [Q&A]
### The bug

the default time for backup db is 02 am. But actually it happened on 10 am. 

maybe the time zone issue. 

When setting 02 am to backup, it should be 02 am local time. 

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

v1.120.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. upgrade immich to 1.120.2 to enable the automatic backup feature
2. after one day, check the backup
3. the backup created at 10am.
