### DISCUSSION TITLE
iOS upload image - not working

### DISCUSSION THREAD

**Discussion by davew723** [immich-app/immich#14141] [Q&A]
### The bug

I have upable to get images to either upload from the background job or manually for a single photo.  In the background case the UI suggests its uploading but they never work.  In the single / manual case they also never upload.  (This works via the web.)

### The OS that Immich Server is running on

ubuntu 24.04

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

v1.120.2 build 184

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/data/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxx
DB_DATABASE_NAME=xxx
```

### Reproduction steps

1.  In mobile app select an image that has a cloud suggesting its only local.  Upload image.
  - Nothing happens.

### Relevant log output

```shell
I have observed to error cases in the mobile log.  (Nothing is appearing in the server log of interest from the time period.). The below errors were from build v1.120.1 build.183.  Using v1.120.2 build 184 I don't seem to get any errors in the logs.  upload just does nothing select I select the upload icon...best I can tell.

Case 1:
  #0 MediaQuery._of (package:flutter/src/widgets/media_query.dart:1191) #1 MediaQuery.of (package:flutter/src/widgets/media_query.dart:1186)
  #2 FToast.showToast (package:fluttertoast/fluttertoast.dart:253)
  #3 ImmichToast.show (package:immich_mobile/widgets/common/immich_toast.dart:49)
  #4 ManualUploadNotifier.uploadAssets (package:immich_mobile/providers/backup/manual_upload.provider.dart:371) <asynchronous suspension>

Case 2:
  ApiException 400: HTTP connection failed: GET /albums/12dc5e7d-f1af-426c-90fc-d4c71d33b18d (Inner exception: ClientException: Bad file descriptor, uri=https://immich.<name removed>.com/api/albums/12dc5e7d-f1af-426c-90fc-d4c71d33b18d)

  #0 IOClient.send (package:http/src/io_client.dart:156) <asynchronous suspension>
  #1 BaseClient._sendUnstreamed (package:http/src/base_client.dart:93) <asynchronous suspension> 
  #2 ApiClient.invokeAPI (package:openapi/api_client.dart:101) <asynchronous suspension>
  #3 AlbumsApi.getAlbumInfo (package:openapi/api/albums_api.dart:270) <asynchronous suspension> 
  #4 ApiRepository.checkNull (package:immich_mobile/repositories/api.repository.dart:5) <asynchronous suspension> #5 AlbumApiRepository.get (package:immich_mobile/repositories/album_api.repository.dart:21) <asynchronous suspension>
  #6 SyncService._syncRemoteAlbum (package:immich_mobile/services/sync.service.dart:360) <asynchronous suspension>
  #7 diffSortedLists (package:immich_mobile/utils/diff.dart:23) <asynchronous suspension>
  #8 SyncService._syncRemoteAlbumsToDb (package:immich_mobile/services/sync.service.dart:323) <asynchronous suspension> #9 AlbumService.refreshRemoteAlbums (package:immich_mobile/services/album.service.dart:180) <asynchronous suspension>
  #10 AlbumNotifier.refreshRemoteAlbums (package:immich_mobile/providers/album/album.provider.dart:34) <asynchronous suspension>
```

### Additional information

I do have nginx infront of immich converting immich (HTTP) <-> internet (HTTPS).  This seems to suggest its working properly since the web works for this case.
