### DISCUSSION TITLE
External Library , Unable to read pictures in the path（Hard drives accessed through the hard drive box）

### DISCUSSION THREAD

**Discussion by zhz-we** [immich-app/immich#14202] [Q&A]
### The bug

External Library is configured, and when immich configured the path, it can also be verified, but after clicking Scan, the following content is printed

`immich_server            | [Nest] 7  - 11/18/2024, 4:31:55 PM     LOG [Microservices:LibraryService] Refreshing library bcb9d011-0a8e-4182-835c-279e83a3902e for new assets
immich_server            | [Nest] 7  - 11/18/2024, 4:31:55 PM     LOG [Microservices:LibraryService] Scanning library bcb9d011-0a8e-4182-835c-279e83a3902e for removed assets
immich_server            | [Nest] 7  - 11/18/2024, 4:31:55 PM     LOG [Microservices:LibraryService] Finished queueing check of 1 assets for library bcb9d011-0a8e-4182-835c-279e83a3902e`

Then there is no result, and there is a 100G picture in the corresponding path, There is also no sign of execution during the 'mission'
![image](https://github.com/user-attachments/assets/d1103469-91fd-49cc-b5a9-51377e3f64e3)
There is also nothing in the photo column
![image](https://github.com/user-attachments/assets/9e8b438d-9e99-46f5-ad90-cd035143cea9)

![image](https://github.com/user-attachments/assets/65248f69-cd02-41d7-b418-e77a01e112c7)

The hard disk calculation seems to be wrong
![image](https://github.com/user-attachments/assets/5cb37e19-10c8-4afe-bf8e-f77379f7a6f3)
![image](https://github.com/user-attachments/assets/7dfce32f-79ca-471f-a196-dc99f05769d1)
![image](https://github.com/user-attachments/assets/611c6982-559d-4055-912f-4ded50d1cf41)
![image](https://github.com/user-attachments/assets/d86b5583-ad61-4346-9060-613309d68f0c)

**The hard drive connected through sata seems to work**
![image](https://github.com/user-attachments/assets/2d96de3d-d9ff-48ef-ba74-ffa831277fc7)

### The OS that Immich Server is running on

docker desktop for windows11 24h2

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

v1.120.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # 不要编辑下一行。如果您想更改系统上的媒体存储位置，请编辑. dev文件中UPLOAD_LOCATION的值
      # 上传路径
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # 外部库
      - "H:/immich/album/HZH:/mnt/media/hzh:ro"
      - "H:/immich/album/LXP:/mnt/media/lxp:ro"
      - "H:/immich/album/iPad:/mnt/media/ipad:ro"
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${CACHE_LOCATION}:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: [ 'postgres', '-c', 'shared_preload_libraries=vectors.so', '-c', 'search_path="$$user", public, vectors', '-c', 'logging_collector=on', '-c', 'max_wal_size=2GB', '-c', 'shared_buffers=512MB', '-c', 'wal_compression=on' ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=H:/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
# Ai
CACHE_LOCATION=./cache
# 外部库
HZH=H:/immich/album/HZH
LXP=H:/immich/album/LXP

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. I configured the basic configuration first, and the External Library was added after configuring the basic content
2. The initially configured External Library path is ` “${HZH}:/usr/src/app/external”` ，However, the image cannot be read, and then the configuration is modified to `"H:/immich/album/HZH:/mnt/media/hzh:ro"`
3.
...
