### DISCUSSION TITLE
Backup location

### DISCUSSION THREAD

**Discussion by 1mfaasj** [immich-app/immich#14249] [Q&A]
### The bug

Hi, I have set the automatic backup but nothing is written to the location I defined. am I doing it right?

in the documentation (https://immich.app/docs/guides/custom-locations/)
it says to use BACKUP_LOCATION, but on another page (https://immich.app/docs/administration/backup-and-restore/) it says something else 'UPLOAD_LOCATION/backups'

which one should work?

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
`services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.120.2
    volumes:
      - /share/images:/afbeeldingen:ro
      - /share/images/upload:/usr/src/app/upload
      - /share/backup:/usr/src/app/backup
      - /etc/localtime:/etc/localtime:ro
    environment:
      - UPLOAD_LOCATION=/usr/src/app/upload
      - BACKUP_LOCATION=/usr/src/app/backup
      - DB_PASSWORD=immich
      - DB_USERNAME=immich
      - DB_DATABASE_NAME=immich
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.120.2
    volumes:
      - /home/media/immich/cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      - POSTGRES_PASSWORD=immich
      - POSTGRES_USER=immich
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS = '--data-checksums'
      - DB_DATA_LOCATION=./postgres
      - DB_PASSWORD=immich
      - DB_USERNAME=immich
      - DB_DATABASE_NAME=immich
    volumes:
      - /home/media/immich/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='immich' || exit 1; Chksum="$$(psql --dbname='immich' --username='immich' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
`
```

### Your .env content

```Shell
none, I have defined the environment variables in the docker-compose file (mentioned above)
```

### Reproduction steps

I enabled the backup like this:
![image](https://github.com/user-attachments/assets/16b06d15-fba9-441e-b43d-6da294cda0df)

### Relevant log output

```shell
none
```
