### DISCUSSION TITLE
V1.121.0 | Immich_server unhealthy | npm error Missing script: "healthcheck"

### DISCUSSION THREAD

**Discussion by account-banned** [immich-app/immich#14275] [Q&A]
Hello All, 

I've just updated to latest v1.121.0, and the immich_server container is unhealthy with the following error:
`npm error Missing script: "healthcheck"

Typically I just stop the container, pull the latest image and start again but tonight, no such luck. 

What might I have overlooked? I was previously on v1.120.1

My Compose/Portainer Stack
```
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/ingest/photos:/ingest:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    volumes:
      - /volume1/docker/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
    volumes:
      - /volume1/docker/immich/redis:/data
    
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```
npm debug log
```
root@9c125c547074:/usr/src/app# cat /root/.npm/_logs/2024-11-21T06_03_41_907Z-debug-0.log 
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/usr/local/lib/node_modules/npm/npmrc
4 silly config load:file:/usr/src/app/.npmrc
5 silly config load:file:/root/.npmrc
6 silly config load:file:/usr/local/etc/npmrc
7 verbose title npm run healthcheck
8 verbose argv "run" "healthcheck"
9 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-11-21T06_03_41_907Z-
10 verbose logfile /root/.npm/_logs/2024-11-21T06_03_41_907Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 verbose stack Error: Missing script: "healthcheck"
13 verbose stack
13 verbose stack To see a list of scripts, run:
13 verbose stack   npm run
13 verbose stack     at #run (/usr/local/lib/node_modules/npm/lib/commands/run-script.js:111:13)
13 verbose stack     at async RunScript.exec (/usr/local/lib/node_modules/npm/lib/commands/run-script.js:40:7)
13 verbose stack     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 error Missing script: "healthcheck"
14 error
14 error To see a list of scripts, run:
14 error   npm run
15 verbose cwd /usr/src/app
16 verbose os Linux 3.10.108
17 verbose node v22.11.0
18 verbose npm  v10.9.0
19 verbose exit 1
20 verbose code 1
21 error A complete log of this run can be found in: /root/.npm/_logs/2024-11-21T06_03_41_907Z-debug-0.log
```
[_immich_postgres_logs.txt](https://github.com/user-attachments/files/17840794/_immich_postgres_logs.txt)
[_immich_server_logs.txt](https://github.com/user-attachments/files/17840795/_immich_server_logs.txt)
