### DISCUSSION TITLE
Can't start after 1.222.0 update

### DISCUSSION THREAD

**Discussion by kimberlyeet** [immich-app/immich#14499] [Q&A]
### The bug

immich-server container keeps restarting with the attached error log after updating to 1.222.0.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.222.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.122.0
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    healthcheck:
      disable: false
    depends_on:
      - immich_redis
      - database
    networks:
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.122.0
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false
    networks:
      - proxy

  immich_redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - proxy

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - proxy

volumes:
  pgdata:
  model-cache:
  immich-files:
    external: true
networks:
  proxy:
    external: true
```

### Your .env content

```Shell
IMMICH_LOG_LEVEL=log
UPLOAD_LOCATION=immich-files
IMMICH_VERSION=release
DB_PASSWORD=censored
DB_HOSTNAME=immich_postgres
DB_USERNAME=censored
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Update to 1.222.0
2. Start stack
3. See Error log
...

### Relevant log output

```shell
[Nest] 16  - 12/05/2024, 7:13:29 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.122.0] [production] 
[Nest] 7  - 12/05/2024, 7:13:33 PM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: QueryFailedError: Connection terminated unexpectedly
QueryFailedError: Connection terminated unexpectedly
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/dist/repositories/database.repository.js:201:21
error: the database system is in recovery mode
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  length: 109,
  severity: 'FATAL',
  code: '57P03',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postmaster.c',
  line: '2357',
  routine: 'ProcessStartupPacket'
}
microservices worker error: error: the database system is in recovery mode
microservices worker exited with code 1
Killing api process
Initializing Immich v1.122.0
Detected CPU Cores: 10
Starting api worker
Starting microservices worker
```

**Comment by mmomjian** [comment]
Your database is damaged/broken. Please post the logs , compose and env

**Reply by kimberlyeet** [reply]
Already posted. Log from postgres docker container:

```
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-12-05 19:20:40.221 UTC [1] LOG:  redirecting log output to logging collector process
2024-12-05 19:20:40.221 UTC [1] HINT:  Future log output will appear in directory "log".
```

Nothing else. Shouldn't break just by updating huh?

**Comment by alextran1502** [comment]
Quite odd. However, you can restore the database from the database dump at `UPLOAD_LOCATION/backups`  by following the steps here.

https://immich.app/docs/administration/backup-and-restore#manual-backup-and-restore

**Reply by alextran1502** [reply]
It is also a good opportunity to move your database volume off docker volume and use bind mount instead

**Reply by kimberlyeet** [reply]
Thanks, I tried this but seems like it didn't do much, same logs as before.

**Reply by alextran1502** [reply]
Have you tried with only one database dump or a few?

**Reply by kimberlyeet** [reply]
Tried with two database dumps from different days. Both didn't work. I've let it sit there for a day with the old dump and now it is up and running again.

The only Error now is:

```
[Nest] 7  - 12/07/2024, 3:11:23 AM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
```

**Comment by lephuochung18** [comment]
got the same error too after update can't start

**Reply by alextran1502** [reply]
Hello, for some data point, is your database on SSD or HDD?

**Reply by lephuochung18** [reply]
hdd

**Comment by Eernie** [comment]
Got the same issue. Reverting back fixed the problem. For it took down the pg server everytime immich started to connect to it.

**Reply by alextran1502** [reply]
Hello, for some data point, is your database on SSD or HDD?

**Reply by Eernie** [reply]
On HDD's, via a iscsi pvc

**Comment by alextran1502** [comment]
Thanks, we will take a look into this

**Comment by ndragon798** [comment]
Hey Yall,

Had the same issue running on kubernetes I had to massively increase the amount of memory the pod postgres was allowed to use and then the application started fine. It seems to be something weird with geocode migrations? My postgres pod is assigned to an hdd server so that could also contribute.

**Reply by mmomjian** [reply]
Define massively? Postgres recommends 2GB

**Reply by raackley** [reply]
I was hitting this error as well with my kubernetes helm deployment.  After setting requests and limits to 2Gi for memory, the issue was resolved.  I don't remember the default that it was using, but it was something like 128Mi or so.

**Reply by Eernie** [reply]
I'll give this a try today aswell

**Reply by Eernie** [reply]
Yes this indeed fixes it. 
The helm charts have a default resourcePreset of nano
> "nano" (dict 
      "requests" (dict "cpu" "100m" "memory" "128Mi" "ephemeral-storage" "50Mi")
      "limits" (dict "cpu" "150m" "memory" "192Mi" "ephemeral-storage" "2Gi")
   )
   
Maybe the Charts should have a better set default? Since the DB needs more then a small 128Mi, shouldn't the charts have a default of at least a 1 Gi? or maybe even 2 Gi?

**Reply by twaldecker** [reply]
@Eernie how did you overwrite the limits in the helm chart?

**Reply by Eernie** [reply]
Yes, I did the following:
```yaml
postgres:
    primary:
        resources:
            requests:
                cpu: 500m
                memory: 2048Mi
            limits:
                cpu: 750m
                memory: 2048Mi
```

This seems enough for my database and the amount of media immich holds
