### DISCUSSION TITLE
Keyword search for images is very slow

### DISCUSSION THREAD

**Discussion by colaKot** [immich-app/immich#14547] [Q&A]
### The bug

cpu：AMD 7840hs
Total number of photos and videos : 9,272 (11 GiB) | 568 (12 GiB)

After an interval of 1 hour, the first keyword search takes about 1 minute, and I see that the memory usage keeps increasing. Continuing the search later will make the speed faster. Is this process loading some data I hope this experience can be improved

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

1.122.1

### Version of Immich Mobile App

web

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "D:/winnas/photos:/mnt/photos:rm"
      - "D:/winnas/gexuan/Photos:/mnt/gxphotos:rm"
      - "D:/winnas/bibi/Photos:/mnt/bibiphotos:rm"
      - "D:/winnas/share:/mnt/share:rm"
    env_file:
      - .env
    ports:
      - '88:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - "D:/docker/imm/model:/cache"
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=D:/winnas/photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.After an interval of 1 hour, the first search will appear
2.
3.
...

**Comment by mmomjian** [comment]
The delay is to load in the machine learning model. You can preload it if you want.  

https://immich.app/docs/install/environment-variables/#machine-learning

**Reply by noliveleger** [reply]
Thank you @mmomjian , it did the trick for me. Now search is instantaneous

**Reply by kanjieater** [reply]
if the defaults make things unusuable, they should probably be changed or alert the user.

**Reply by bo0tzz** [reply]
The defaults are usually fine, only on slower systems does the loading cause a noticeable latency. And deciding to always keep it loaded isn't straightforward, as that would use a lot of RAM people might not have available.

**Reply by kanjieater** [reply]
I've set up immich on an i5 12500, and search is just broken, failing to return anything. Maybe it's a different issue, but the default compose certainly isn't working.

**Reply by DrSpaldo** [reply]
I know a link to the docs are great, but when there are so many options in the docs it can make it confusing. I am also getting super slow search speeds.... 

Do I need to add both of these variables like this?


>   immich-machine-learning:
>     container_name: immich_machine_learning
>     image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
>     volumes:
>       - model-cache:/cache
>     env_file:
>       - .env
>     restart: always
> 	**environment:
> 	  - MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=ViT-SO400M-16-SigLIP2-384__webli
> 	  - MACHINE_LEARNING_PRELOAD__CLIP__VISUAL=ViT-SO400M-16-SigLIP2-384__webli
> 	  - MACHINE_LEARNING_MODEL_TTL=0**
>     deploy:
>       resources:
>         reservations:
>           devices:
>             - driver: nvidia
>               count: all
>               capabilities: [gpu]

_Ignore the indentation, I couldn't do bold and code at the same time for the environment section..._ 

Is there anything else?

**Reply by noliveleger** [reply]
Exactly what I did in my `.env` files. Does make a huge difference on my old i7 (with plenty of RAM though).

```
MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=XLM-Roberta-Large-Vit-B-16Plus
MACHINE_LEARNING_PRELOAD__CLIP__VISUAL=XLM-Roberta-Large-Vit-B-16Plus
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__DETECTION=buffalo_l
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__RECOGNITION=buffalo_l
``` 

I guess the last two do not improve the search but the facial recognition :-P

**Reply by DrSpaldo** [reply]
> Exactly what I did in my `.env` files. Does make a huge difference on my old i7 (with plenty of RAM though).
>

Thanks @noliveleger. Mine has worked the way I did it above, but being in the .env is probably a better method... 

For anyone finding this topic with search, as I use CLIP/ML/Search with GPU, it has loaded that model into the GPU RAM, which runs 4-5gig depending when you look. My card has 8 gigs so, no issues with Immich & Frigate using the card. It is just something to consider when you select which model you end up using... In the [docs](https://docs.immich.app/features/searching/) it says that model I am using (ViT-SO400M-16-SigLIP2-384__webli) uses 3854MB, when it actually takes up 4000-5200MB when preloaded.

**Comment by aeozyalcin** [comment]
I am running the even smaller ViT-SO400M-16-SigLIP2-256__webli model with OpenVino on i5-12500T system with 32GB RAM. I have the models preloaded with timeout set to 0.

My issue is, most searches take forever! And I can't tell where the bottleneck is. I am looking at htop and intel_gpu_top, and while I see a blip initially on the GPU from the immich python process, it only lasts a couple of seconds, and then seemingly there is no following GPU or CPU activity regarding this context search after that. I am not convinced the issue is HW inference speed limited. Does anyone have any pointers on how I can tell why context searches are taking so long?

**Comment by timglong** [comment]
I have the same problem: the first search is slow or fails, depending on the interface (web vs iOS), but all additional searches are very fast. I'm running remote ML with CUDA on an 8GB 5050. Server and remote ML are both version 2.7.5. I have about 10,000 assets on this instance.

Via the web interface using Firefox:
- Searching loads the model as expected, per `nvidia-smi`.
- The first search is slow, but eventually loads the expected results.
  - Time to results:
    - `ViT-SO400M-16-SigLIP2-256__webli`: 71 seconds
    - `ViT-B-16-SigLIP2__webli`: 72 seconds
- All additional searches are very fast.

Via the iOS app (2.7.5 build.256):
- Searching loads the model as expected, per `nvidia-smi`.
- The first search fails with "no results found".
  - Leaving the Search page, then searching for the search term again results in a successful search.
  - Searching for a different search term results in a successful search.
    - Time to "no results found":
      - `ViT-SO400M-16-SigLIP2-256__webli`: 60 seconds
      - `ViT-B-16-SigLIP2__webli`: 60 seconds
    - Time to first successful search after "no results found":
      - `ViT-SO400M-16-SigLIP2-256__webli`: Instant
      - `ViT-B-16-SigLIP2__webli`: Instant
- All additional searches are very fast.

Pre-loading the model using `MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL` and `MACHINE_LEARNING_PRELOAD__CLIP__VISUAL` did not impact this behavior, but did result in higher memory usage. I confirmed I used the same model (`ViT-SO400M-16-SigLIP2-256__webli`). ~~It's not clear to me how these environment variables work, specifically how they map to the `CLIP model` selected in Machine Learning Settings (or not), and whether I should be using one or both of them.~~ (Edit: based on my reading about CLIP models and the discussion in https://github.com/immich-app/immich/discussions/12475 I assume only `TEXTUAL` pre-loading is necessary for fast searching.)

I also tried changing the Smart Search model to `ViT-B-16-SigLIP2__webli`, which according to the chart [in the searching docs](https://docs.immich.app/features/searching) has a much lower Execution Time. This change had no noticeable impact on the observed behavior.

Edit to add some testing data above as well as testing observations:
- When using the web interface:
  - After the initial search, `nvidia-smi` shows the model being loaded into memory and the GPU starts loading up: Perf goes from P8 -> P1, Power Usage goes up, GPU-Util goes up, etc.
  - After about 30 seconds, the GPU goes back to its default state: P8, 0% util, 7W power, 0% fan.
  - After another 30 seconds, the GPU goes active again: P1, util up, power usage up, fan on.
  - The search results load shortly after this.
- When using the iOS app:
  - After the initial search, `nvidia-smi` shows the model being loaded into memory and the GPU starts loading up: Perf goes from P8 -> P1, Power Usage goes up, GPU-Util goes up, etc.
  - The next GPU actions seen when using the web interface do not happen.
  - The search fails with "no results found".
- After the first successful search:
  - If the model has recently unloaded, searches are still fast, though not as fast as if the model was still loaded when starting the search.

**Reply by DrSpaldo** [reply]
This is what mine looks like:

```
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    volumes:
      - /mnt/user/appdata/immich/model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    environment:
      - MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=ViT-B-16-SigLIP2__webli
      - MACHINE_LEARNING_PRELOAD__CLIP__VISUAL=ViT-B-16-SigLIP2__webli
      - MACHINE_LEARNING_MODEL_TTL=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: 
                - gpu
                - compute
                - video   
```

Looks like you have the two preload's, except maybe try adding the 

> MACHINE_LEARNING_MODEL_TTL=0

**Reply by timglong** [reply]
I used that variable as well and there was no impact on the first search behavior. Based on the discussion in https://github.com/immich-app/immich/pull/7540 it doesn't seem like `TTL` should be needed if `PRELOAD` is used.

Since searches after the first search are fast, I'm testing whether `MACHINE_LEARNING_MODEL_TTL=0` works to preserve after-first-search performance.
- No impact on first search.
- Additional searches after waiting for some time are much faster.

I'm also going to test pre-loading `TEXTUAL` only as this appears to be the intended use of splitting the environment variables (see https://github.com/immich-app/immich/discussions/12475).
- No impact on first search.
- Additional searches after waiting for some time are much faster.

Note the observed behavior is unchanged in v3.0.0.

**Reply by timglong** [reply]
I don't know what to make of this. Regardless of what I try, the first search after ML container startup takes 60-70 seconds. Preload seems to keep things snappy _after_ the first search, so I guess I'll just leave textual preload enabled and see how that works moving forward.

Something weird: I had textual preload enabled on my test instance, but not my production instance, and my iOS search (production, not preloaded) was instantaneous. I can see both processes on `nvidia-smi` and watched the process related to the iOS search spin up. Edit: I haven't been able to duplicate this.

**Reply by timglong** [reply]
For posterity, or if anyone has the same question later, here are the results of my testing and what I implemented:
- Nothing I did improved the speed of the _**first**_ search after the machine learning container is started, or after the `TEXTUAL` model unloads and there hasn't been a search in a while.
- Using `MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL` makes every search after the initial search very fast.

So, I added the `MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL` environment variable and made a note to myself to run a search immediately after restarting the remote machine learning container that both of my instances use. No problems so far and day-to-day searching is snappy.

**Reply by DrSpaldo** [reply]
Hi @timglong thanks for the update. It still isn't right though, it clearly isn't preloading. I wonder why it isn't doing as intended. Let's hope that the staff actually read this and can provide some ideas or a way to fix it. You shouldn't need to run the search each time...

**Reply by DrSpaldo** [reply]
What does your ML container log say? does it look like this? 

```
[07/03/26 02:42:41] INFO     Starting gunicorn 25.3.0                           
[07/03/26 02:42:41] INFO     Listening at: http://[::]:3003 (84)                
[07/03/26 02:42:41] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[07/03/26 02:42:41] INFO     Booting worker with pid: 116                       
[07/03/26 02:42:44] INFO     Started server process [116]                       
[07/03/26 02:42:44] INFO     Waiting for application startup.                   
[07/03/26 02:42:44] INFO     Created in-memory cache with unloading disabled.   
[07/03/26 02:42:44] INFO     Initialized request thread pool with 32 threads.   
[07/03/26 02:42:44] INFO     Preloading models:                                 
                             clip:textual='ViT-B-16-SigLIP2__webli'             
                             visual='ViT-B-16-SigLIP2__webli'                   
                             facial_recognition:recognition=None detection=None 
[07/03/26 02:42:44] INFO     Loading textual model 'ViT-B-16-SigLIP2__webli' to memory                                             
[07/03/26 02:42:44] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[07/03/26 02:42:51] INFO     Loading visual model 'ViT-B-16-SigLIP2__webli' to memory                                             
[07/03/26 02:42:51] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[07/03/26 02:42:52] INFO     Application startup complete.    
```

**Reply by timglong** [reply]
Yes, my logs are basically identical to what you posted. On container startup I can watch the model load into memory via `nvidia-smi`, so pre-load seems to be working as intended.

There is also a delay after container start-up when triggering the Smart Search job (i.e., re-processing all assets or something similar), which I assume is the same thing happening. I don't recall noticing this delay in the past, so maybe something was introduced at some point to cause this behavior, but I could also have just not been paying enough attention.

Either way, running a single search every time I restart my remote ml machine isn't a huge deal.

**Reply by DrSpaldo** [reply]
Very strange. Feels like it isn't being loaded into memory but says it is (and configured like it is). Hopefully someone on the dev time can take the time to have a look and see what is going wrong. I know running the search isn't too bad for you, but still shouldn't need to happen.

**Reply by timglong** [reply]
> Very strange. Feels like it isn't being loaded into memory but says it is (and configured like it is).

There is an open issue https://github.com/immich-app/immich/issues/28583 regarding Blackwell GPUs, which should include my RTX 5050. In the interest of being thorough I disabled CUDA this morning and ran ML on the CPU to see what would happen. I re-triggered the Smart Search job for all assets and watched the results. As expected, the ML container logs showed `'CPUExecutionProvider'` only, `top` showed much higher CPU utilization, 200% for the python process vs 80-90% when using CUDA, and `nvidia-smi` showed no utilization. The Smart Search job ran at a painfully slow pace. I didn't wait around for it to finish, but I estimate it would have taken about 3 hours.

After re-enabling CUDA, the Smart Search job (all assets) finished in about 20 minutes. It's difficult to determine how long it should take, given hardware differences and the lack of available benchmarks, but [this post](https://dansgarden.eu/technology/self-hosting/immich-machine-learning) from late 2025 reports a 10-minute completion time for slightly more assets (13,000 vs 10,000) using a different model (`ViT-L-16-SigLIP-384__webli` vs `ViT-SO400M-16-SigLIP2-256__webli`) and (much?) more powerful hardware (RTX 3080 vs RTX 5050). I feel like 20 minutes for my setup is solidly in the ballpark of reasonable.

So, no changes on the first-search front, but I feel very confident that my GPU is crunching away as intended.

**Reply by timglong** [reply]
In the interest of even more completeness, here are my logs from container startup through to the end of processing all assets. At 14:08:42 you can see the visual model load after I trigger the Smart Search job. There's no indication when the job finishes, but the shutdown message at 14:37:06 makes sense given my rough timing of 24 minutes for job completion + 300 seconds of inactivity.

Edit: this corresponds to 1,704 seconds, so subtracting 300 for default TTL gives a job completion time of 23:24. Oddly enough, the delta between that calculated time and my timer time of 24:00 is almost exactly the delay that I notice (~30 seconds) between model loading and things working (i.e., the 70 seconds to first search referenced above roughly break down to 30 seconds to load the model, 30 seconds of inactivity, and 10 seconds of completing the search).

```
docker logs testing-immich-machine-learning-1
[07/04/26 14:08:03] INFO     Starting gunicorn 25.3.0                           
[07/04/26 14:08:03] INFO     Listening at: http://[::]:3003 (49)                
[07/04/26 14:08:03] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[07/04/26 14:08:03] INFO     Booting worker with pid: 53                        
[07/04/26 14:08:06] INFO     Started server process [53]                        
[07/04/26 14:08:06] INFO     Waiting for application startup.                   
[07/04/26 14:08:06] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[07/04/26 14:08:06] INFO     Initialized request thread pool with 4 threads.    
[07/04/26 14:08:06] INFO     Application startup complete.                      
[07/04/26 14:08:42] INFO     Loading visual model                               
                             'ViT-SO400M-16-SigLIP2-256__webli' to memory       
[07/04/26 14:08:42] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[07/04/26 14:37:06] INFO     Shutting down due to inactivity.                   
[07/04/26 14:37:06] INFO     Shutting down                                      
[07/04/26 14:37:06] INFO     Waiting for application shutdown.                  
[07/04/26 14:37:06] INFO     Application shutdown complete.                     
[07/04/26 14:37:06] INFO     Finished server process [53]                       
[07/04/26 14:37:06] WARNING  Worker (pid:53) was sent SIGINT!                   
[07/04/26 14:37:06] INFO     Booting worker with pid: 470                       
[07/04/26 14:37:08] INFO     Started server process [470]                       
[07/04/26 14:37:08] INFO     Waiting for application startup.                   
[07/04/26 14:37:08] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[07/04/26 14:37:08] INFO     Initialized request thread pool with 4 threads.    
[07/04/26 14:37:08] INFO     Application startup complete.  
```

**Reply by DrSpaldo** [reply]
@mmomjian @bo0tzz are either of you able to check for tim?

**Reply by mertalev** [reply]
The expectation is that the first search is very fast if the model is preloaded. If you restart the whole Immich stack, wait for the model to preload and do a search, how long does that search take? If you then restart the ML container alone without touching any other containers and wait for it to preload, then do a search, how long does that search take?

**Reply by timglong** [reply]
> The expectation is that the first search is very fast if the model is preloaded. If you restart the whole Immich stack, wait for the model to preload and do a search, how long does that search take? If you then restart the ML container alone without touching any other containers and wait for it to preload, then do a search, how long does that search take?

I don't know exactly how long preloading `ViT-SO400M-16-SigLIP2-256__webli` takes, but via `nvidia-smi`, `Memory-Usage` rests at `2981MiB /   8151MiB` and `GPU Memory Usage` for the `python` process rests at `2966MiB` with textual preloading enabled. For these tests I waited for those values to stabilize, then waited for everything else to go quiet/to resting baseline: 0% fan, P8 perf, 7W pwr usage, 0% util. Then I waited a bit longer.

I was able to repeatedly replicate these results. Here's the `nvidia-smi` data for my last replication: [testing.csv](https://github.com/user-attachments/files/29674652/testing.csv)

Things that jump out at me:
- The ~35 second rest period where the GPU is idle during the first search
- The change in memory usage after the idle period
  - `Memory-Usage` from `3063MiB` to `3065MiB`, then to `3075MiB` (only in the ML container restart scenario)
  - `GPU Memory Usage` for the `python` process from `3048MiB` to `3050MiB`
- Searches after restarting only the ML container being instant
- Different memory behavior after restarting only the ML container

#### Cold start:
- Total time to first search results: **~71 seconds**
- GPU behavior via `nvidia-smi` after searching:
  - `Memory-Usage` immediately goes to `3063MiB /   8151MiB`
  - `GPU Memory Usage` for the `python` process immediately goes to `3048MiB`
  - The GPU immediately goes active: P8 -> P1, pwr usage up, util up
  - At ~32 seconds, the GPU goes back to its resting state: P1 -> P8, 7W pwr, 0% util
  - At ~69 seconds, the GPU goes active again
  - `Memory-Usage` goes to `3065MiB /   8151MiB`
  - `GPU Memory Usage` for the `python` process goes to `3050MiB`
  - Search results load

#### ML container restart via `docker restart testing-immich-machine-learning-1`:
- Total time to first search results: **Instant**
- GPU behavior via `nvidia-smi` after restart:
  -  The GPU goes active to preload the model
  - `Memory-Usage` immediately goes to `2981MiB /   8151MiB`
  - `GPU Memory Usage` for the `python` process immediately goes to `2966MiB`
- GPU behavior via `nvidia-smi` after searching:
  - The GPU immediately became active: P8 -> P1, pwr usage up, util up
  - `Memory-Usage` immediately goes to `3065MiB /   8151MiB`, then to `3075MiB /   8151MiB`
  - `GPU Memory Usage` for the `python` process immediately goes to `3050MiB`
  - Search results load immediately

I hope this is useful, thanks for the help!

**Reply by mmomjian** [reply]
For the users who DO preload and still see slow searches, what storage medium is your Postgres database on? And are you using our default docker image Postgres container?

**Reply by aeozyalcin** [reply]
> For the users who DO preload and still see slow searches, what storage medium is your Postgres database on? And are you using our default docker image Postgres container?

This 1000%! I had the same issue on my setup, and the culprit was that postgres db lived on my RAID HDD. Despite having the models preloaded, first search was painfully slow. Fix for me was to keep the postgres db on my boot SSD, and of course keeping the assets on the raid HDD.

**Reply by timglong** [reply]
> For the users who DO preload and still see slow searches, what storage medium is your Postgres database on? And are you using our default docker image Postgres container?

For the testing above, the database is on a SATA SSD RAID 10 array. For my other two instances, one is on a SATA SSD RAID 1 array, the other is on an NVME SSD RAID 1 array. Both of those instances use remote ML and exhibit the same first-search behavior.

I use the default docker image for Postgres (and everything else) and whenever I update I check the hash. The only modifications to the default compose file are a) the addition of a network to connect to Caddy, and b) setting environment variables to keep Postgres/thumbnails on SSDs and data on HDDs.

One thing just popped into my head--I set `THUMB_LOCATION` and keep thumbnails on those same SSD arrays, would that have any impact? Edit: I re-ran the tests with thumbs in the default location; no change.

**Reply by mertalev** [reply]
The results seem to imply that the model preloading is working and the ML server responds quickly on the first search. Something else is making it very slow despite that.

Do you see any notable IO activity in the server or DB containers that continues throughout the wait?

**Reply by mmomjian** [reply]
May need to setup pg_stat_statements to log long queries next

**Reply by timglong** [reply]
> The results seem to imply that the model preloading is working and the ML server responds quickly on the first search. Something else is making it very slow despite that.
> 
> Do you see any notable IO activity in the server or DB containers that continues throughout the wait?

I used `docker stats` to watch the server and database containers during the first search and didn't see much of anything. When the first search results loaded after the initial 70-second wait there was a brief blip in utilization on the database container. Edit: On subsequent searches there is an immediate blip on the database container corresponding to the search results loading immediately.

Here are the exact compose and environment files I used today as well.

<details>
<summary>compose.yaml</summary>

```
name: testing-immich

services:
  server:
    container_name: testing-immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - ${THUMB_LOCATION}:/data/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - proxy-network
      - immich-network
    expose:
      - 2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich-network
    environment:
      - MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=ViT-SO400M-16-SigLIP2-256__webli
    restart: always
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:9@sha256:4963247afc4cd33c7d3b2d2816b9f7f8eeebab148d29056c2ca4d7cbc966f2d9
    networks:
      - immich-network
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich-network
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always
    healthcheck:
      disable: false

volumes:
  model-cache:

networks:
  proxy-network:
    name: caddy-immich-net
    external: true
  immich-network:
    name: immich-internal-net
```

</details>

<details>
<summary>.env</summary>

```
UPLOAD_LOCATION=/mnt/raid1/testing-immich/immich_files
THUMB_LOCATION=./thumbnails

DB_DATA_LOCATION=./postgres

TZ=Etc/UTC

IMMICH_VERSION=v3

DB_PASSWORD=*redacted*

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

</details>
