### DISCUSSION TITLE
N305 not loading ML

### DISCUSSION THREAD

**Discussion by tye-mustafa** [immich-app/immich#14806] [Q&A] [answered]
### The bug

I was running before the docker setup on windows now i totally shifted to Ubuntu 24 LTS

now problem i'm facing is all things going fine hardware encoding to everything 

but ML is not working no errors in logs tried to give models names and waited for 2 days to let it start but still in Jobs its showing one by one reducing number of items slowly but immich_machine_learnign not showing any logs of loading models

nothing on intel_cpu_top
no cpu usage on htop too

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-51-generic x86_64)

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/tye/SSD:/home/tye/SSD
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
#    deploy:
#      resources:
#        limits:
#          cpus: '7.0' # Maximum 7 CPU core
#          memory: 24G  # Maximum 24 GB of RAM
    restart: always
    healthcheck:
      disable: false
      interval: 15m
      start_interval: 5m
      start_period: 5m

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
#      file: hwaccel.ml.yml
#      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    ports:
      - '3003:3003'
    volumes:
      - /home/tye/SSD/immich/cache:/cache
#      - model-cache:/cache
    env_file:
      - .env
#    deploy:
#      resources:
#        limits:
#          cpus: '7.0' # Maximum 7 CPU core
#          memory: 16G  # Maximum 16 GB of RAM
    restart: always
    healthcheck:
      disable: false
      interval: 15m
      start_interval: 5m
      start_period: 5m

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

#volumes:
#  model-cache:
```

### Your .env content

```Shell
#You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/tye/SSD/immich/library

# The location where your database files are stored
DB_DATA_LOCATION=/home/tye/SSD/immich/postgresDB

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.as described to install
2. all went ok
3. no ML errors just empty
...

### Relevant log output

```shell
[12/19/24 08:10:34] INFO     Starting gunicorn 23.0.0
[12/19/24 08:10:34] INFO     Listening at: http://[::]:3003 (9)
[12/19/24 08:10:34] INFO     Using worker: app.config.CustomUvicornWorker
[12/19/24 08:10:34] INFO     Booting worker with pid: 10
[12/19/24 08:10:39] INFO     Started server process [10]
[12/19/24 08:10:39] INFO     Waiting for application startup.
[12/19/24 08:10:39] INFO     Created in-memory cache with unloading after 300s
                             of inactivity.
[12/19/24 08:10:39] INFO     Initialized request thread pool with 8 threads.
[12/19/24 08:10:39] INFO     Application startup complete.
[12/19/24 09:50:39] INFO     Starting gunicorn 23.0.0
[12/19/24 09:50:39] INFO     Listening at: http://[::]:3003 (9)
[12/19/24 09:50:39] INFO     Using worker: app.config.CustomUvicornWorker
[12/19/24 09:50:39] INFO     Booting worker with pid: 10
[12/19/24 09:50:45] INFO     Started server process [10]
[12/19/24 09:50:45] INFO     Waiting for application startup.
[12/19/24 09:50:45] INFO     Created in-memory cache with unloading after 300s
                             of inactivity.
[12/19/24 09:50:45] INFO     Initialized request thread pool with 8 threads.
[12/19/24 09:50:45] INFO     Application startup complete
```

### Additional information

i tried permission to my cache folder and ownership 

now my permissions are these
drwxrwxr-x 4 root docker 4096 Oct 22 07:47 /home/tye/SSD/immich/cache
