### DISCUSSION TITLE
ERR_SSL_PROTOCOL_ERROR downloading a bug album

### DISCUSSION THREAD

**Discussion by SchSeba** [immich-app/immich#14805] [Q&A]
### The bug

I am using immich-helm with ingress-nginx and when I try to deploy a big album I can see in the browser that it starts but after around 200M it stop and I get `POST https://photos.X.com/api/download/archive net::ERR_SSL_PROTOCOL_ERROR 200 (OK)`

When I use nodePort to access directly the immich server I am able to download the full album with no issue

### The OS that Immich Server is running on

centos

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

none

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
server:
  enabled: true
  controller:
    replicas: 1
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  persistence:
    external-library:
      enabled: true
      type: pvc
      existingClaim: immich-external-library
      mountPath: /mnt
  ingress:
    main:
      enabled: true
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
        # nginx.ingress.kubernetes.io/proxy-buffer-size: 256k
        # nginx.ingress.kubernetes.io/proxy-buffers-number: '100'
        nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
        nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          # allow large file uploads
          #client_max_body_size 50000M;

          # Set headers
          # proxy_set_header Host              $http_host;
          # proxy_set_header X-Real-IP         $remote_addr;
          # proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
          # proxy_set_header X-Forwarded-Proto $scheme;

          # enable websockets: http://nginx.org/en/docs/http/websocket.html
          proxy_cache_bypass $http_upgrade;

          # set timeout
          send_timeout       600s;
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: nginx
      ingressClassName: nginx
      hosts:
        - host: photos.X.com
          paths:
            - path: "/"
      tls:
        - hosts:
          - photos.X.com
          secretName: immich-tls
```

### Your .env content

```Shell
None
```

### Reproduction steps

1.try to download a big album 3Gi
