### DISCUSSION TITLE
Brand new install of Immich not running

### DISCUSSION THREAD

**Discussion by weav797** [immich-app/immich#14812] [Q&A] [answered]
### The bug

I recently installed Immich from scratch after trying it on a different Windows machine. After going through the normal documentation on installing Immich again, I am now faced with weird errors that prevents usage. I have researched as much as I could on my own, and I cannot figure this out on my own it seems.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

Latest

### Version of Immich Mobile App

Latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Denver

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[redacted]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Follow standard documentation on Immich website [here](https://immich.app/docs/install/docker-compose).
2. Run docker compose up -d
3. immich_server container starts throwing errors immediately after that saying unable to connect to database.
...

### Relevant log output

```shell
From immich_server container: 

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...

Error: connect EHOSTUNREACH 172.19.0.4:5432

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:24 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 7  - 12/19/2024, 6:31:24 PM     LOG [NestFactory] Starting Nest application...

[Nest] 7  - 12/19/2024, 6:31:24 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...

api worker exited with code 1

Initializing Immich v1.123.0

Detected CPU Cores: 12

Starting api worker

Starting microservices worker

(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

(Use `node --trace-deprecation ...` to show where the warning was created)

(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

(Use `node --trace-deprecation ...` to show where the warning was created)

(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

(Use `node --trace-deprecation ...` to show where the warning was created)

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [NestFactory] Starting Nest application...

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms

[Nest] 17  - 12/19/2024, 6:31:52 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms

[Nest] 7  - 12/19/2024, 6:31:52 PM     LOG [NestFactory] Starting Nest application...

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 17  - 12/19/2024, 6:31:52 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database

Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

[Nest] 7  - 12/19/2024, 6:31:52 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...

microservices worker exited with code 1

Killing api process

Initializing Immich v1.123.0

Detected CPU Cores: 12

Starting api worker

Starting microservices worker

(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

(Use `node --trace-deprecation ...` to show where the warning was created)




From immch_postgres container: 

The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting dynamic shared memory implementation ... posix

selecting default max_connections ... 20

selecting default shared_buffers ... 400kB

selecting default time zone ... Etc/UTC

creating configuration files ... ok

2024-12-20 01:31:03.524 UTC [82] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

2024-12-20 01:31:03.524 UTC [82] HINT:  The server must be started by the user that owns the data directory.

child process exited with exit code 1

initdb: removing contents of data directory "/var/lib/postgresql/data"

running bootstrap script ... NThe files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting dynamic shared memory implementation ... posix

selecting default max_connections ... 20

selecting default shared_buffers ... 400kB

selecting default time zone ... Etc/UTC

creating configuration files ... ok

2024-12-20 01:31:10.657 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

2024-12-20 01:31:10.657 UTC [83] HINT:  The server must be started by the user that owns the data directory.

child process exited with exit code 1

initdb: removing contents of data directory "/var/lib/postgresql/data"

running bootstrap script ... NThe files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting dynamic shared memory implementation ... posix

selecting default max_connections ... 20

selecting default shared_buffers ... 400kB

selecting default time zone ... Etc/UTC

creating configuration files ... ok

2024-12-20 01:31:23.982 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

2024-12-20 01:31:23.982 UTC [83] HINT:  The server must be started by the user that owns the data directory.

child process exited with exit code 1

initdb: removing contents of data directory "/var/lib/postgresql/data"

running bootstrap script ... NThe files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting dynamic shared memory implementation ... posix

selecting default max_connections ... 20

selecting default shared_buffers ... 400kB

selecting default time zone ... Etc/UTC

creating configuration files ... ok

2024-12-20 01:31:50.282 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

2024-12-20 01:31:50.282 UTC [83] HINT:  The server must be started by the user that owns the data directory.

child process exited with exit code 1

initdb: removing contents of data directory "/var/lib/postgresql/data"

running bootstrap script ... NThe files belonging to this database system will be owned by user "postgres".

This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".

The default database encoding has accordingly been set to "UTF8".

The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok

creating subdirectories ... ok

selecting dynamic shared memory implementation ... posix

selecting default max_connections ... 20

selecting default shared_buffers ... 400kB

selecting default time zone ... Etc/UTC

creating configuration files ... ok

2024-12-20 01:32:42.195 UTC [82] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

2024-12-20 01:32:42.195 UTC [82] HINT:  The server must be started by the user that owns the data directory.

child process exited with exit code 1

initdb: removing contents of data directory "/var/lib/postgresql/data"

running bootstrap script ...
```

### Additional information

I also read somewhere in another github issue to check port 2283 because of this error I saw in my portainer (although the error disappeared after I reinstalled with same documentation steps): 

curl: (7) Failed to connect to localhost port 2283 after 0 ms: Couldn't connect to server Fail: exit code is 7

Could this mean something maybe?

```
plex@PlexHomelabServer:/media/plex/PlexMedia/immich-app$ curl localhost:2283
curl: (56) Recv failure: Connection reset by peer
```
