### DISCUSSION TITLE
Failed to get all albums (500)

### DISCUSSION THREAD

**Discussion by macminoz** [immich-app/immich#14859] [Q&A]
### The bug

I have the latest version (1.123.0) of Immich, after the latest batch I started receiving this message:

```
Failed to get all albums (500)

Stacktrace
Error: Error: 500
    at Object.it [as ok] (http://fotografie:2283/_app/immutable/chunks/fetch-client.DUPjmxtR.js:1:7428)
    at async ct (http://fotografie:2283/_app/immutable/nodes/5.BoFv1jq3.js:1:1438)
    at async Ue (http://fotografie:2283/_app/immutable/chunks/entry.DTR95pgu.js:1:15801)

```
I tried to put 128GB of RAM and 16 CPU core  but nothing changed. I have 503,552 of Photos (412 GiB)
and 8,979 (327 GiB) of videos but I always get this error. In order to make all my check I suspended all the DB engines activities (no facial rec and detection)

### The OS that Immich Server is running on

Debian 12.8

### Version of Immich Server

1.123.0

### Version of Immich Mobile App

not using

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=16GB
      -c shared_buffers=8GB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Rome

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Import photos with immich CLI: immich upload --recursive --concurrency 8 --ignore '**/*thumb*'  /mnt/NAS/home/Photo\ Backup/
2. Check the Albums tab
3. Expect the message

### Relevant log output

```shell
[Nest] 7  - 12/19/2024, 2:00:00 AM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 14
[Nest] 7  - 12/19/2024, 2:06:34 AM     LOG [Microservices:BackupService] Database Backup Success
[Nest] 17  - 12/19/2024, 11:09:13 AM     LOG [Api:EventRepository] Websocket Disconnect: AURFKkDt4-rsjTZaAAAH
[Nest] 17  - 12/19/2024, 11:09:14 AM     LOG [Api:EventRepository] Websocket Connect:    4nsx3wqSs6s-lQoIAAAJ
[Nest] 17  - 12/19/2024, 11:09:28 AM   ERROR [Api:ErrorInterceptor~pvvru6ey] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[Nest] 17  - 12/19/2024, 11:09:45 AM   ERROR [Api:ErrorInterceptor~9slnn3x2] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[Nest] 17  - 12/19/2024, 11:19:40 AM   ERROR [Api:ErrorInterceptor~2avpt926] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[Nest] 17  - 12/19/2024, 11:19:57 AM   ERROR [Api:ErrorInterceptor~8490gwag] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[Nest] 17  - 12/19/2024, 11:21:29 AM     LOG [Api:EventRepository] Websocket Disconnect: 4nsx3wqSs6s-lQoIAAAJ
[Nest] 17  - 12/19/2024, 11:21:29 AM     LOG [Api:EventRepository] Websocket Connect:    TSeitMwcxcR1JNyfAAAL
[Nest] 17  - 12/19/2024, 11:21:44 AM   ERROR [Api:ErrorInterceptor~6edvcdrq] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
[Nest] 17  - 12/19/2024, 11:23:11 AM   ERROR [Api:ErrorInterceptor~i1c8up01] Unknown error: Error: timeout exceeded when trying to connect
Error: timeout exceeded when trying to connect
    at Timeout._onTimeout (/usr/src/app/node_modules/pg-pool/index.js:205:27)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7)
```
