### DISCUSSION TITLE
Unable to install immich on unraid

### DISCUSSION THREAD

**Discussion by xiongster** [immich-app/immich#14861] [Q&A]
### The bug

Immich server wont start. New to server installation via docker. Please see log output.

### The OS that Immich Server is running on

UNRAID

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      #start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/immich
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/appdata

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Install following install guide in immich website
2. Visit the IP:PORT. Eg- 192.168.1.123:2283
3.

### Relevant log output

```shell
text  error  warn  system  array  login  

    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 18  - 12/22/2024, 11:36:39 AM   ERROR [ExceptionHandler] connect ECONNREFUSED 172.20.0.5:5432
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
api worker exited with code 1
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 7  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
[Nest] 17  - 12/22/2024, 11:37:21 AM   ERROR [ExceptionHandler] connect ECONNREFUSED 172.20.0.5:5432
Error: connect ECONNREFUSED 172.20.0.5:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
microservices worker exited with code 1
Killing api process
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Initializing Immich v1.123.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 12/22/2024, 11:37:21 AM     LOG [NestFactory] Starting Nest application...
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [NestFactory] Starting Nest application...
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 17  - 12/22/2024, 11:37:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
Initializing Immich v1.123.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
Initializing Immich v1.123.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
