### DISCUSSION TITLE
Large Video File not uploading

### DISCUSSION THREAD

**Discussion by Bhawesh-Agrawal** [immich-app/immich#15059] [Q&A] [answered]
### The bug

I have been trying to backup my all photos in the immich. During upload I found out that it's not able to upload large video files. My files where around 300-400mb . I am not sure why it isn't uploading or it's just a bug. 
![image](https://github.com/user-attachments/assets/0f5d3b0c-b89d-4408-a457-e84577323ebb)

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3" # Use version 3 of the docker-compose file format

# Service definitions for the big-bear-immich application
services:
  # Main Immich Server service configuration
  immich-server:
    container_name: immich-server # Name of the running container
    image: ghcr.io/immich-app/immich-server:v1.123.0 # Image to be used
    ports: # Mapping ports from the host OS to the container
      - 2283:2283
    volumes: # Mounting directories for persistent data storage
      - immich_upload:/usr/src/app/upload
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: portainer
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on: # Dependencies to ensure the order of service startup
      - redis
      - database
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Immich Machine Learning service
  immich-machine-learning:
    container_name: immich-machine-learning # Name of the running container
    image: ghcr.io/immich-app/immich-machine-learning:v1.123.0 # Image to be used
    volumes: # Mounting directories for persistent data storage
      - immich_cache:/cache
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: portainer
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Redis service
  redis:
    container_name: immich-redis # Name of the running container
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3 # Image to be used
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Database service
  database:
    container_name: immich-postgres # Name of the running container
    image: tensorchord/pgvecto-rs:pg14-v0.2.0 # Image to be used
    environment: # Setting environment variables
      POSTGRES_PASSWORD: portainer
      POSTGRES_USER: portainer
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes: # Mounting directories for persistent data storage
      - immich_postgres:/var/lib/postgresql/data
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

# Network definitions
networks:
  # Define the network
  immich-network:
    # Use the bridge driver
    driver: bridge

# Define named volumes for data persistence.
volumes:
  # Define a named volume for Immich data.
  immich_cache:
    # Use the local storage driver.
    driver: local
  immich_upload:
    # Use the local storage driver.
    driver: local
  immich_postgres:
    # Use the local storage driver.
    driver: local
```

### Your .env content

```Shell
DB_DATABASE_NAME	immich
DB_HOSTNAME	        immich-postgres
DB_PASSWORD	        portainer
DB_PORT	                5432
DB_USERNAME	        portainer
IMMICH_BUILD	        12377454804
IMMICH_BUILD_IMAGE	v1.123.0
IMMICH_BUILD_IMAGE_URL	https://github.com/immich-app/immich/pkgs/container/immich-server
IMMICH_BUILD_URL	https://github.com/immich-app/immich/actions/runs/12377454804
IMMICH_MACHINE_LEARNING_URL	http://immich-machine-learning:3003
IMMICH_REPOSITORY	immich-app/immich
IMMICH_REPOSITORY_URL	https://github.com/immich-app/immich
IMMICH_SOURCE_COMMIT	fd34a914a6b2e6dcfbbe53afcf0112cabccc232b
IMMICH_SOURCE_REF	v1.123.0
IMMICH_SOURCE_URL	https://github.com/immich-app/immich/commit/fd34a914a6b2e6dcfbbe53afcf0112cabccc232b
LD_LIBRARY_PATH	/usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib:
NODE_ENV	production
NODE_VERSION	22.12.0
NVIDIA_DRIVER_CAPABILITIES	all
NVIDIA_VISIBLE_DEVICES	all
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/bin
REDIS_HOSTNAME	immich-redis
YARN_VERSION	1.22.22
```

### Reproduction steps

1. I was backing up my data.
2. I found some of the assets are not being uploaded it just going through a loop again and again and not showing any error in the mobile app
3. I tried uploading it through web application. It didn't uploaded and just gave an error could not upload
4. I found that does file were videos and were larger than 150 mb
