### DISCUSSION TITLE
[Feature] Remote Thumbnail Generation

### DISCUSSION THREAD

**Discussion by jadster** [immich-app/immich#15085] [Feature Request]
### I have searched the existing feature requests to make sure this is not a duplicate request.

- [X] Yes

### The feature

I'm new to Immich and mostly elated by how clean it is set up and how clean and satisfying the UX is. A rare experience.

One of the aspects that truly blew me away was how easy it was to use my little M2 Macbook Air as a remote Machine Learning worker for my feeble Synology NAS, where my Photo collection and Immich installation reside. My Mac processes the machine-learning stuff much much faster than my NAS despite no GPU acceleration.

Naturally, I would now like to further offload tasks from my NAS that are taxing it. Most notably the thumbnail generation task. It is extremely slow and CPU-intensive on my NAS and I would love to let my Macbook Air or other machines in the home network help out.

On a system like my NAS where both disk IO and CPU are vastly inferior to my macbook air and but my home network is decently quick - it seems to me it would be a large benefit with no significant overhead on my NAS if I could outsource most of the thumbnail generation away from my NAS. Especially when initializing a large dataset or making lots of changes to an external library that needs to be rescanned and processed...

I searched the issues and docs to see if this has been mentioned or described.

I did find mentions of microservices [in the docs](https://immich.app/docs/guides/scaling-immich) but it's much too vague for me.

And I found issue https://github.com/immich-app/immich/discussions/14142 with a few examples of custom setups getting certain other services outsourced, and maybe I'll figure out eventually. But clearly it's not as easy as outsourcing the machine-learning tasks.

Assuming that remote thumbnail generation *is already possible*, my feature request would be this: 

Make outsourcing thumbnail generation as easy and as similar as possible for the user as it works with machine-learning.
 i.e. 
* run an(other) instance of a thumbnail-generation container with a ready-to-use api. expose the container port on the remote computer.
* implement a UX in Admin Settings for thumbnail generation that is identical to "Machine Learning Settings", where I can just add and order URLs to remote thumbnail generation apis.

And then describe the process in the docs for Dummies like me :)

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by bo0tzz** [comment]
Like you found, this is already possible, it's just an advanced setup. Making it easier isn't really feasible - the only way that could be done is by creating a separate container for only thumbnail handling (just like there is for ML), but that wouldn't really make sense architecture wise.

**Reply by yann117** [reply]
It is funny to see how many people think the opposite ...

I guess many people are self-hosting on small capacity machines, **which is perfectly fine for the storage and delivery part**, but not for the computing power.

Immich is running perfectly on small NAS/Pi/MiniPC once the database is built and that is great. But everytime I have to add new pictures it is a nightmare: 10+ hours to do ML/Smart search on it, compared to 30 minutes on my main desktop, as this part can be delegated there.

Now, the only single activity we can't offload (easily) is for the thumbnail generation. For the original setup I had it running for 2 full nights. If I have to do that again from scratch (in case of some bug corrupting the DB, or just me messing it up), I'll probably give up with Immitch, as in the meantime I added even more pictures.

Having a dedicated container just for thumbnails handling, **does make great sense** with regard to a modular architecture and providing therefore a way to easily switch on remote/offload processing.
 
Currently it is not clear how to do it. @bo0tzz you mention/confirm multiple times that it is possible, but IIUC we have to figure it out ourselves, there is no documentation, and it seems you are not willing to either provide details in the _discussions_?

Is that a feature which should remain secret? Do we all need to struggle experimenting things by ourselves, or rely on bad suggestion like I've seen in other topic and are dangerous?

Even if making it ootb configurable (like what is suggested here) is not a priority, I don't get why you pushback and deny the need of better details to set it up as we can currently?

**Reply by mmomjian** [reply]
We explain everything needed here:

https://immich.app/docs/administration/jobs-workers/

Basically, you can add a second immich container on the remote machine with `IMMICH_WORKERS_EXCLUDE: 'api'`, connect it to the same postgres database and UPLOAD_LOCATION mount.

**Reply by yann117** [reply]
Thanks, I'm currently reading the doc and also the [architecture page](https://immich.app/docs/developer/architecture) helps.
I have (the beginning of) an idea how to do it now.

I need to figure out what are the ports of each containers used for communication, that I need to expose on the homelab instance, to have the offloaded instance connect to Redis/Postgres.
Also I need to determine if access to the homelab instance's Filesystem is required for the remote or not (data flow could be all through the API/communication channel otherwise).
Probably more reading will help ;-)

Edit:
> connect it to the [..] UPLOAD_LOCATION mount
That answer the question of accessing the "local" homelab FS

**Reply by yann117** [reply]
[Checking the code](https://github.com/immich-app/immich/blob/4c4c67f0d283abb9d69a2c4c3480c55fa1d64bca/docker/docker-compose.prod.yml#L77), the postgres database container is on port 5432. I guess that is the one we need to export explicitly on the local instance.

Google tell me that is the _default_ port for postgres :-)

Therefore I checked what is the port for redis and found it is 6379, and I find that one in the code too, so I assume this is the one to export for redis?

**Reply by yann117** [reply]
Ok, finally it was not so hard :+1:  I got it working by doing few changes.
Below are my files/changes, let's call "local" the main instance, your NAS/Pi/Mini-PC/homelab, and "remote" your powerful other machine.

On the **local**:
1. open the ports **5432 and 6379** in your firewall
2. save and then edit your _compose.yml_, applying the changes below **## ADDITION**:

```yaml
services:
  immich-server:
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /data/pictures/john:/john:ro
      - /data/pictures/jane:/jane:ro
    env_file:
      - .env
    ## ADDITION: Only keep the api workers (UI) running on the 'local'
    environment:
      IMMICH_WORKERS_INCLUDE: 'api'
    ...

  immich-machine-learning:
    ... # no changes

  redis:
    ## ADDITION: Publishing Redis port to expose it for the remote
    ports:
      - '6379:6379'

  database:
    ## ADDITION: Publishing Postgres port to expose it for the remote
    ports:
      - '5432:5432'

```

On the **remote**:
1. don't forget to enable hardware acceleration (for ML+transcoding) if possible
2. if you changed the default Postgres database password (_DB_PASSWORD_ variable) in your **local** Immich _.env_ file, then set the same password in your remote _.env_ file
3. mount (SMB/NFS) the **local** filesystem, which contain your Immich _UPLOAD_LOCATION_ and your external libraries if any. In my case and example, I have two external libraries under _/data/pictures_. I mount that the whole parent _/data_ which contains my Immich docker as well

4. in the _.env_ file modify the _UPLOAD_LOCATION_ with your mounted folder and so it is resolving/pointing to the **local** <immich>/library folder. In my case:

```UPLOAD_LOCATION=/mnt/homelab/data/docker/immich-app/library```

5. edit your _compose.yml_ with the below changes:

```yaml
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      ## CHANGES: update your external libraries path to resolve to the **local** mounted location
      - /mnt/homelab/data/pictures/john:/john:ro
      - /mnt/homelab/data/pictures/jane:/jane:ro
    env_file:
      - .env
    ## ADDITION: Only run the microservices workers (excluding 'api'). Then define the DB and REDIS variables with your homelab IP
    environment:
      IMMICH_WORKERS_EXCLUDE: 'api'
      DB_HOSTNAME: '192.168.1.xx'
      REDIS_HOSTNAME: '192.168.1.xx'
```

Finally, restart both Immich instances with:
```
docker compose up -d --force-recreate
```

Now I can re-process my whole library in a few minutes as compared to days! Thank you !
