### DISCUSSION TITLE
Unable to save email notification settings

### DISCUSSION THREAD

**Discussion by haioken** [immich-app/immich#15159] [Q&A]
I'm running immich containerized using the documentation from https://immich.app/docs/install/docker-compose/

When attempting to configure email notifications from Immich, clicking "Send test email and save" yields a message `Failed to send test email (Immich Server Error)`

Checking the container logs, the error given on each attempt is the same:
```
[Nest] 17  - 01/08/2025, 1:18:39 PM   ERROR [Api:ErrorInterceptor~jlad87y2] Unknown error: TypeError: Cannot read properties of undefined (reading 'languages')
TypeError: Cannot read properties of undefined (reading 'languages')
    at /usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:24:694
    at Array.flatMap (<anonymous>)
    at it (/usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:24:681)
    at Ai (/usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:27:12039)
    at rr (/usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:33:273)
    at /usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:35:802
    at gu (/usr/src/app/node_modules/@react-email/render/node_modules/prettier/standalone.js:35:871)
    at pretty (/usr/src/app/node_modules/@react-email/render/dist/node/index.js:87:39)
    at /usr/src/app/node_modules/@react-email/render/dist/node/index.js:163:12
    at Generator.next (<anonymous>)
```

My docker compose for immich_server is as follows:
```
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```

The `.env` file:
```
UPLOAD_LOCATION=/mnt/bigDiskEnergy/container-data/cfgImmich/upload
DB_DATA_LOCATION=/mnt/bigDiskEnergy/container-data/cfgImmich/postgres
TZ=Australia/Melbourne
IMMICH_VERSION=release
DB_PASSWORD=[redacted obviously]
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

The configuration I'm trying to add is a private mail server, so I won't add the details, but it's configured for auth plain over TLS, StartTLS is enabled and functional.
I can auth against the mail server from the terminal with `openssl s_client -connect sub.domain.tld:587 -starttls smtp`

From a limited google, it looks like something might be missing from the Immich container? The only other reference I can find to `Cannot read properties of undefined (reading 'languages')` comes from a ticket for `prettier` which appears to be a HTML code formatter that can be used as a python module.

I've tried updating the container from v1.123.0 to v1.124.0, this has not resolved the issue, changing from hostname to IP address (in case of resolution issue), using an account with a simpler password as a test for special character problems, updating each template with a single word for the same reason.
