### DISCUSSION TITLE
An error occurred while running the job task

### DISCUSSION THREAD

**Discussion by GXY1122** [immich-app/immich#15173] [Q&A]
### The bug

[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Object:
{
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Object:
{
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
[Nest] 7  - 01/08/2025, 2:46:57 PM   ERROR [Microservices:JobService] Object:
{
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Object:
{

[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Object:
{
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
[Nest] 7  - 01/08/2025, 2:46:58 PM   ERROR [Microservices:JobService] Object:
{
[Nest] 7  - 01/08/2025, 2:47:00 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 01/08/2025, 2:47:00 PM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
-----
<img width="442" alt="image" src="https://github.com/user-attachments/assets/98fbb068-0449-4ef1-a5c3-926fa12e5567" />

### The OS that Immich Server is running on

DSM 7.2.1-69057 Update 3

### Version of Immich Server

v1.124.0

### Version of Immich Mobile App

v1.124.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:

  immich-server:

    container_name: immich_server

    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    command: [ "start.sh", "immich" ]

    volumes:

      - ${UPLOAD_LOCATION}:/usr/src/app/upload

      - ${EXTERNAL_PATH}:/usr/src/app/external

      - /etc/localtime:/etc/localtime:ro

    env_file:

      - .env

    ports:

      - 2283:2283    #可修改为自定义webui端口

    depends_on:

      - redis

      - database

    restart: always

  immich-microservices:

    container_name: immich_microservices

    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    # extends:

    #   file: hwaccel.yml

    #   service: hwaccel

    command: [ "start.sh", "microservices" ]

    volumes:

      - ${UPLOAD_LOCATION}:/usr/src/app/upload

      - ${EXTERNAL_PATH}:/usr/src/app/external

      - /etc/localtime:/etc/localtime:ro

    env_file:

      - .env

    depends_on:

      - redis

      - database

    restart: always

  immich-machine-learning:

    container_name: immich_machine_learning

    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}

    volumes:

      - /volume3/hot-ssd-home/docker/immich/cache:/cache	   #自定义cache位置

    env_file:

      - .env

    restart: always

  redis:

    container_name: immich_redis

    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc

    restart: always

  database:

    container_name: immich_postgres

    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

    env_file:

      - .env

    environment:

      POSTGRES_PASSWORD: ${DB_PASSWORD}

      POSTGRES_USER: ${DB_USERNAME}

      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:

      - /volume3/hot-ssd-home/docker/immich/data:/var/lib/postgresql/data	   #自定义data位置

    restart: always

volumes:

  pgdata:

  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume3/hot-ssd-home/docker/immich/photo

EXTERNAL_PATH=/volume3/hot-ssd-home/cloudsync

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1.login
2.start Generate a thumbnail task
...
