### DISCUSSION TITLE
Can't find uploaded images on the server

### DISCUSSION THREAD

**Discussion by tajanthind** [immich-app/immich#15275] [Q&A]
### The bug

I have immich set up on my fedora server with portainer. I have a external hard drive connected that is mounted on /mnt/storage.

As you can see I set up immich_upload to indicate the external drive but to no avail. I uploaded some images to see where it was uploading them but couldn't find them. It is also showing me incorrect storage information.

![immich issue](https://github.com/user-attachments/assets/34af4d62-d361-4f10-8533-635fbacb774d)

Even though I have empty 2TB hard drive.

### The OS that Immich Server is running on

Linux server latest

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3" # Use version 3 of the docker-compose file format

# Service definitions for the big-bear-immich application
services:
  # Main Immich Server service configuration
  immich-server:
    container_name: immich-server # Name of the running container
    image: ghcr.io/immich-app/immich-server:v1.124.2 # Image to be used
    ports: # Mapping ports from the host OS to the container
      - 2283:2283
    volumes: # Mounting directories for persistent data storage
      - immich_upload:/mnt/storage/immich/upload
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: portainer
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on: # Dependencies to ensure the order of service startup
      - redis
      - database
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Immich Machine Learning service
  immich-machine-learning:
    container_name: immich-machine-learning # Name of the running container
    image: ghcr.io/immich-app/immich-machine-learning:v1.124.2 # Image to be used
    volumes: # Mounting directories for persistent data storage
      - immich_cache:/mnt/storage/immich/cache
    environment: # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: portainer
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Redis service
  redis:
    container_name: immich-redis # Name of the running container
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3 # Image to be used
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Database service
  database:
    container_name: immich-postgres # Name of the running container
    image: tensorchord/pgvecto-rs:pg14-v0.2.0 # Image to be used
    environment: # Setting environment variables
      POSTGRES_PASSWORD: portainer
      POSTGRES_USER: portainer
      POSTGRES_DB: immich
      PG_DATA: /mnt/storage/immich/postgresql
    volumes: # Mounting directories for persistent data storage
      - immich_postgres:/mnt/storage/immich/postgresql
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

# Network definitions
networks:
  # Define the network
  immich-network:
    # Use the bridge driver
    driver: bridge

# Define named volumes for data persistence.
volumes:
  # Define a named volume for Immich data.
  immich_cache:
    # Use the local storage driver.
    driver: local
  immich_upload:
    # Use the local storage driver.
    driver: local
  immich_postgres:
    # Use the local storage driver.
    driver: local
```

### Your .env content

```Shell
no env
```

### Reproduction steps

1.Deploy the server
2. upload images
3. Cant find data
...

### Relevant log output

```shell
[Nest] 7  - 01/12/2025, 1:55:44 AM     LOG [Microservices:MediaService] Successfully encoded 26799553-cabe-47c4-9314-e96a83886e95
[Nest] 7  - 01/12/2025, 1:55:44 AM     LOG [Microservices:MediaService] Transcoding video 385e53f5-a72e-447b-ae4e-9acecf01713f without hardware acceleration
[Nest] 7  - 01/12/2025, 1:55:45 AM     LOG [Microservices:MediaService] Successfully encoded 385e53f5-a72e-447b-ae4e-9acecf01713f
[Nest] 7  - 01/12/2025, 1:55:45 AM     LOG [Microservices:MediaService] Transcoding video 33dd0660-4cff-42d6-8b0b-e3af55124a53 without hardware acceleration
[Nest] 7  - 01/12/2025, 1:55:45 AM     LOG [Microservices:MediaService] Successfully encoded 33dd0660-4cff-42d6-8b0b-e3af55124a53
[Nest] 7  - 01/12/2025, 1:55:45 AM     LOG [Microservices:MediaService] Transcoding video 33dd0660-4cff-42d6-8b0b-e3af55124a53 without hardware acceleration
[Nest] 7  - 01/12/2025, 1:55:45 AM     LOG [Microservices:MediaService] Successfully encoded 33dd0660-4cff-42d6-8b0b-e3af55124a53
```
