### DISCUSSION TITLE
Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory

### DISCUSSION THREAD

**Discussion by Martin-int01** [immich-app/immich#15310] [Q&A] [answered]
### The bug

Hi,

I have created a new Immich container. In Immich I added 4 external libraries and scanned them successfully. 
Now I have removed the container and created a new one. 
Immich-server no longer starts.  I get the following error:

Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory

I have tried to create the folder encoded-video and the file .immich manually.
Unfortunately, immich-server still does not start

thank you in advanced

best

Martin

### The OS that Immich Server is running on

Ubuntu 24.04 with docker compose

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/upload
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: /mnt/shares/Martin
        target: /app/photos/Martin
      - type: bind
        source: /mnt/shares/Marialuisa
        target: /app/photos/Marialuisa
      - type: bind
        source: /mnt/shares/Claudia
        target: /app/photos/Claudia
      - type: bind
        source: /mnt/shares/Common
        target: /app/photos/Common
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`gallery.mydomain.eu`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/immich-app/library
# The location where your database files are stored
DB_DATA_LOCATION=/opt/immich-app/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create an Immich Container with default settings
2. Finish Immich first start wizard
3. Add external library
4. scan external library
5. recreate the Immich Container
...

### Relevant log output

```shell
Initializing Immich v1.124.2

Detected CPU Cores: 4

Starting api worker

Starting microservices worker

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:EventRepository] Initialized websocket server

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:MetadataService] Bootstrapping metadata service

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:MetadataService] Initializing metadata service

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:MapRepository] Initializing metadata repository

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:ServerService] Feature Flags: {

  "smartSearch": true,

  "facialRecognition": true,

  "duplicateDetection": true,

  "map": true,

  "reverseGeocoding": true,

  "importFaces": false,

  "sidecar": true,

  "search": true,

  "trash": true,

  "oauth": false,

  "oauthAutoLaunch": false,

  "passwordLogin": true,

  "configFile": false,

  "email": false

}

[Nest] 7  - 01/13/2025, 2:25:57 PM     LOG [Microservices:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}

[Nest] 7  - 01/13/2025, 2:25:57 PM   ERROR [Microservices:StorageService] Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'

microservices worker error: Error: Failed to read "<UPLOAD_LOCATION>/encoded-video/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information."

microservices worker exited with code 1

Killing api process
```
