### DISCUSSION TITLE
immich_postgres keeps restart looping with permission errors

### DISCUSSION THREAD

**Discussion by fiverglem** [immich-app/immich#15472] [Q&A] [answered]
### The bug

I simply run the `docker compose up -d` command and only the immich_postgres container starts to constantly restart looping with. Been at this for over 3 weeks uninstalling docker desktop and WSL and flushing all folders associated with docker and reinstalling. I am really sorry if this is something really simple and ive been over looking it this whole time, and thank you in advanced. (kind of new to docker so sorry if i entered any of the information incorrectly)

### The OS that Immich Server is running on

Ubuntu docker desktop 4.37.1

### Version of Immich Server

release

### Version of Immich Mobile App

none

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=D:\immich\library
# The location where your database files are stored
DB_DATA_LOCATION=D:\immich\postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=US

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=mypasswordhere

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. I simply run the `docker compose up -d` command with PS in admin mode (first time it errors because it asks for permission for files so i restart docker desktop and run command again) and the immich_postgres container starts to constantly restart, the three other containers in the compose stack run without restarting.

### Relevant log output

```shell
2025-01-20 09:50:28 running bootstrap script ... 2025-01-20T15:51:30.135012900Z The files belonging to this database system will be owned by user "postgres".
2025-01-20 09:51:30 This user must also own the server process.
2025-01-20 09:51:30 
2025-01-20 09:51:30 The database cluster will be initialized with locale "en_US.utf8".
2025-01-20 09:51:30 The default database encoding has accordingly been set to "UTF8".
2025-01-20 09:51:30 The default text search configuration will be set to "english".
2025-01-20 09:51:30 
2025-01-20 09:51:30 Data page checksums are enabled.
2025-01-20 09:51:30 
2025-01-20 09:51:30 fixing permissions on existing directory /var/lib/postgresql/data ... ok
2025-01-20 09:51:30 creating subdirectories ... ok
2025-01-20 09:51:30 selecting dynamic shared memory implementation ... posix
2025-01-20 09:51:30 selecting default max_connections ... 20
2025-01-20 09:51:30 selecting default shared_buffers ... 400kB
2025-01-20 09:51:31 selecting default time zone ... Etc/UTC
2025-01-20 09:51:31 creating configuration files ... ok
2025-01-20 09:51:31 2025-01-20 15:51:31.128 UTC [83] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
2025-01-20 09:51:31 2025-01-20 15:51:31.128 UTC [83] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
2025-01-20 09:51:31 child process exited with exit code 1
2025-01-20 09:51:31 initdb: removing contents of data directory "/var/lib/postgresql/data"
2025-01-20 09:51:31 running bootstrap script ...
```

### Additional information

errors from immich_server that could be relevant, was not sure since its not restart looking

2025-01-20 10:11:10 Initializing Immich v1.124.2
2025-01-20 10:11:10 Detected CPU Cores: 8
2025-01-20 10:11:14 Starting api worker
2025-01-20 10:11:14 Starting microservices worker
2025-01-20 10:12:10 [Nest] 7  - 01/20/2025, 4:12:10 PM     LOG [NestFactory] Starting Nest application...
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [NestFactory] Starting Nest application...
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
2025-01-20 10:12:10 [Nest] 17  - 01/20/2025, 4:12:10 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
2025-01-20 10:12:12 Initializing Immich v1.124.2
2025-01-20 10:12:12 Detected CPU Cores: 8
2025-01-20 10:05:58     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:05:58 microservices worker exited with code 1
2025-01-20 10:05:58 Killing api process
2025-01-20 10:07:07 [Nest] 7  - 01/20/2025, 4:07:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2025-01-20 10:07:07 microservices worker exited with code 1
2025-01-20 10:07:07 Killing api process
2025-01-20 10:08:08 [Nest] 7  - 01/20/2025, 4:08:08 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2025-01-20 10:08:08 microservices worker exited with code 1
2025-01-20 10:08:08 Killing api process
2025-01-20 10:09:09 [Nest] 7  - 01/20/2025, 4:09:09 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2025-01-20 10:09:09 microservices worker exited with code 1
2025-01-20 10:09:09 Killing api process
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
2025-01-20 10:10:07 Error: connect ECONNREFUSED 172.18.0.5:5432
2025-01-20 10:10:07     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
2025-01-20 10:10:07 [Nest] 17  - 01/20/2025, 4:10:07 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database
2025-01-20 10:10:07 Error: getaddrinfo ENOTFOUND database
2025-01-20 10:10:07     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
