### DISCUSSION TITLE
External Library shows up empty

### DISCUSSION THREAD

**Discussion by Qhilm** [immich-app/immich#15485] [Q&A] [answered]
Here is the yaml code for the `immich-server` section of the `docker-compose.yml`:

```yaml
services:
  immich-server:
    user: '1037:100'
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${FTP_UPLOAD}:/mnt/media/ftp-upload/:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
```

* `FTP_UPLOAD` is set to a local path on the NAS.
* Import path is set to `/mnt/media/ftp-upload/` and **validation is successful** when I hit "save" (green checkmark next to the import path in the GUI)
* One exclusion pattern, set to `**/*.arw`.
* 20 `.ARW` files in FTP_UPLOAD folder and one `.JPG` file.
* I connected via FTP to the NAS using the same user that the docker container is running as (UID 1037) and checked I can see the files in the correct folder.

But the library stubbornly says "0 assets".

Any idea what I could try next?
