### DISCUSSION TITLE
Breaking when try to access Review Duplicates in Utilities

### DISCUSSION THREAD

**Discussion by luishang** [immich-app/immich#15504] [Q&A] [answered]
I've already run all jobs related to duplicated pictures and at some point I could see them. However now the container restarts whenever I try to access this on UI. 
Any ideas?

The OS that Immich Server is running on
Linux raspberrypi 6.6.62+rpt-rpi-v8 https://github.com/immich-app/immich/issues/1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux

Version of Immich Server
v.1.24.2

Version of Immich Mobile App
1.124

.env:
```
 The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/seagatetati/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
#DB_DATA_LOCATION=/mnt/seagatetati/immich

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=BR

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

docker compose:
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/seagatetati/TATI/Fotos:/mnt/seagatetati/fotos:ro
      - /mnt/seagateluis:/mnt/seagateluis:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

logs:
immich_machine_learning  | [01/21/25 21:26:04] INFO     Shutting down due to inactivity.                   
immich_machine_learning  | [01/21/25 21:26:33] CRITICAL WORKER TIMEOUT (pid:22554)                         
immich_machine_learning  | [01/21/25 21:30:15] ERROR    Worker (pid:22554) was sent SIGKILL! Perhaps out of
immich_machine_learning  |                              memory?                                            
immich_machine_learning  | [01/21/25 21:30:17] INFO     Booting worker with pid: 25441                     
immich_server            | api worker exited with code null
immich_server exited with code 0
immich_server            | Detected CPU Cores: 4
immich_machine_learning  | [01/21/25 21:31:15] INFO     Started server process [25441]                     
immich_machine_learning  | [01/21/25 21:31:15] INFO     Waiting for application startup.                   
immich_machine_learning  | [01/21/25 21:31:15] INFO     Created in-memory cache with unloading after 300s  
immich_machine_learning  |                              of inactivity.                                     
immich_machine_learning  | [01/21/25 21:31:15] INFO     Initialized request thread pool with 4 threads.    
immich_machine_learning  | [01/21/25 21:31:15] INFO     Application startup complete.                      
immich_server            | Starting api worker
immich_server            | Starting microservices worker
