### DISCUSSION TITLE
Some problem about postgres

### DISCUSSION THREAD

**Discussion by FLAWING2016** [immich-app/immich#15512] [Q&A]
### The bug

I start immich-server in my nas with an error,is that model(XLM-Roberta-Large-Vit-B-16Plus) not be supported?
[Nest] 9  - 01/22/2025, 6:39:58 AM     LOG [Microservices:SmartInfoService] Dimension size of model XLM-Roberta-Large-Vit-B-16Plus is 640, but database expects 512.
[Nest] 9  - 01/22/2025, 6:39:58 AM     LOG [Microservices:SmartInfoService] Updating database CLIP dimension size to 640.
Query failed : {
  durationMs: 3.2393900000024587,
PostgresError: syntax error at or near "'vector(640)'"
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42601',
  position: '58',
  file: 'scan.l',
  line: '1176',
  routine: 'scanner_yyerror'
}
microservices worker error: PostgresError: syntax error at or near "'vector(640)'"
microservices worker exited with code 1
Killing api process 

### The OS that Immich Server is running on

01/22/2025, 6:39:58 AM

### Version of Immich Server

v14982

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#



services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:pr-14892
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume2/photo/:/mnt/media/photo
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${MODEL_CACHE}:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.m.daocloud.io/redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.m.daocloud.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    ports:
      - '5431:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      #start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=1024MB
      -c wal_compression=on
    restart: always

volumes:
    model-cache:
```

### Your .env content

```Shell
#自定义的照片上传路径

UPLOAD_LOCATION=/volume2/docker/immich/photo

#自定义的外部库路径，就是你本来在群晖备份的照片

EXTERNAL_PATH=/volume2/photo

IMMICH_VERSION=release

#时区设置
TZ=Asia/shanghai

# 以下为自定义的数据库内容，分别是数据库名、账号、密码
DB_DATA_LOCATION=/volume2/docker/immich/data

DB_DATABASE_NAME=immich

DB_USERNAME=postgres

DB_PASSWORD=postgres

#以下是镜像名字，不建议修改

DB_HOSTNAME=immich_postgres

REDIS_HOSTNAME=immich_redis

#模型目录
MODEL_CACHE=/volume2/docker/immich/model-cache

#忽略报错
IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
