### DISCUSSION TITLE
Very High CPU Usage in Immich Server

### DISCUSSION THREAD

**Discussion by The-Inamati** [immich-app/immich#15793] [Q&A]
Hello,
I am experiencing an issue with Immich that has never happened before (at least to me) and I require your help.

When I have Immich running after a while I get HUGE CPU spikes that basically make the VM unusable.

The VM has 6GB of RAM and 8 Cores so it should be more than enough to run it (and indeed it was up until now).

These are the two processes that seem to cause the issue.

![Screenshot from 2025-01-30 16-25-32](https://github.com/user-attachments/assets/ddbd8769-efae-4d03-8920-49c43e41a4a6)

![Screenshot from 2025-01-30 16-25-41](https://github.com/user-attachments/assets/2e13b776-92d5-4656-b528-dc214b36f415)

To give you an idea here is the graph collected during the event.

![Screenshot from 2025-01-30 16-26-29](https://github.com/user-attachments/assets/66e793f3-d5de-4081-8c4b-67ff9a379004)

As you can see I even stop getting the metrics from the VM.

Any help is appreciated as I have no idea what is going on. I am running version 1.125.2 and this is my compose file.

```yaml
secrets:
  immichdb_pass:
    file: $SECRETS_DIR/immichdb_pass

volumes:
  immich:
  immichml:
  immichdb:

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.125.2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    secrets:
      - immichdb_pass
    networks:
      - traefik
      - database
    volumes:
      - immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_HOSTNAME: immichred
      DB_HOSTNAME: immichdb
      DB_USERNAME: immich
      DB_DATABASE_NAME: immichdb
      DB_PASSWORD_FILE: /run/secrets/immichdb_pass
    depends_on:
      - immichred
      - immichdb
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.http.routers.immich.rule=Host(`photos.$DOMAINNAME1`)"
      - "traefik.http.routers.immich.tls=true"
      ## HTTP Services
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.routers.immich.middlewares=no-auth@file"


  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.125.2
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    secrets:
      - immichdb_pass
    networks:
      - database
    environment:
      REDIS_HOSTNAME: immichred
      DB_HOSTNAME: immichdb
      DB_USERNAME: immich
      DB_DATABASE_NAME: immichdb
      DB_PASSWORD_FILE: /run/secrets/immichdb_pass
    volumes:
      - immichml:/cache

  immichred:
    container_name: immichred
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - database

  immichdb:
    container_name: immichdb
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    security_opt:
      - no-new-privileges:true
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped
    secrets:
      - immichdb_pass
    networks:
      - database
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/immichdb_pass
      POSTGRES_USER: immich
      POSTGRES_DB: immichdb
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immichdb:/var/lib/postgresql/data
```
