### DISCUSSION TITLE
Third party tool for rule-based smart albums

### DISCUSSION THREAD

**Discussion by kvalev** [immich-app/immich#15814] [Show and tell]
I created a tool for automatically creating and updating rule-based smart albums, one of the most requested Immich feature https://github.com/immich-app/immich/discussions/1673.

You can find all the code and documentation in this repository https://github.com/kvalev/immich-dynamic-albums

The TL;DR is to create a config file containing one or more albums and their respective rules:

```
[
    {
        "name": "Best of Egypt 2021",
        "query": {
            "country": "Egypt",
            "favorite": true,
            "timespan": {
                "start": "2021-05-01",
                "end": "2021-05-10"
            }
        }
    }
]
```

And then mount it in the provided docker container and it will periodically query Immich for matching assets and keep those albums up-to-date:

```

    immich-dynamic-albums:
        image: ghcr.io/kvalev/immich-dynamic-albums:latest
        restart: unless-stopped
        volumes:
            - PATH_TO_CONFIG_JSON_FILE:/config/dynamic-albums.json:ro
        environment:
            IMMICH_URL: http://immich_server:2283/
            IMMICH_API_KEY: API_KEY
            CONFIG_FILE: /config/dynamic-albums.json
            SCHEDULE_INTERVAL: 1440 # 1440 minutes, meaning once per day
            PYTHONUNBUFFERED: True # ensure stdout is flushed on every print
        depends_on:
            immich-server:
                condition: service_healthy
```

If you have any suggestions or discover any issue let me know here or raise an issue in the other repository.
If someone from the Immich team finds this helpful you can link it in the locked feature request.
