### DISCUSSION TITLE
Unable to access Immich Server

### DISCUSSION THREAD

**Discussion by souravlayek** [immich-app/immich#15849] [Q&A] [answered]
### What is the problem or bug?

I was unable to open the immich app in browser.

### Screenshots/Logs

```bash
sourav@immich:~$ curl http://localhost:2283
curl: (56) Recv failure: Connection reset by peer
sourav@immich:~$ docker ps
CONTAINER ID   IMAGE                                                COMMAND                  CREATED        STATUS                    PORTS                                                 NAMES
b6440e5d65b3   ghcr.io/immich-app/immich-machine-learning:release   "tini -- ./start.sh"     24 hours ago   Up 25 minutes (healthy)                                                         immich_machine_learning
bd78b8fb5651   ghcr.io/immich-app/immich-server:release             "tini -- /bin/bash s…"   24 hours ago   Up 25 minutes (healthy)   2283/tcp, 0.0.0.0:2283->3001/tcp, :::2283->3001/tcp   immich_server
0a89ba837b74   containrrr/watchtower                                "/watchtower"            2 days ago     Up 25 minutes (healthy)   8080/tcp                                              watchtower
b6fb7b546652   redis:6.2-alpine                                     "docker-entrypoint.s…"   5 months ago   Up 25 minutes (healthy)   6379/tcp                                              immich_redis
5e58dadfefb6   tensorchord/pgvecto-rs:pg14-v0.2.0                   "docker-entrypoint.s…"   5 months ago   Up 25 minutes (healthy)   5432/tcp                                              immich_postgres
sourav@immich:~$
```
Docker container logs

[logs.txt](https://github.com/user-attachments/files/18631407/logs.txt)

Do let me know if anything else need to share.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.5

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./Library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<MY PASSWORD>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Start the container

### Relevant log output

```shell
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[h264 @ 0x5d02c1e0580] Reinit context to 1280x720, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/upload/6c1506c2-8f72-4f59-b282-931c53ef071a/9b/e2/9be2d80f-b3c2-443c-b69e-a8605eb95ead.MP4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-09-11T11:47:40.000000Z
  Duration: 00:00:06.52, start: 0.000000, bitrate: 2445 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, smpte170m, progressive, left), 1280x720 [SAR 1:1 DAR 16:9], 2337 kb/s, 17.65 fps, 17.67 tbr, 90k tbn (default)
      Metadata:
        creation_time   : 2018-09-11T11:47:40.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 09/11/2018.
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
      Metadata:
        creation_time   : 2018-09-11T11:47:40.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 09/11/2018.
        vendor_id       : [0][0][0][0]
[out#0/webp @ 0x5d02c161140] No explicit maps, mapping streams automatically...
[vost#0:0/libwebp_anim @ 0x5d02c173480] Created video stream from input stream 0:0
[Parsed_thumbnail_1 @ 0x5d02c160d80] batch size: 12 frames
[Parsed_scale_5 @ 0x5d02c1609c0] w:-2 h:250 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[Parsed_fps_0 @ 0x5d02c160c00] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> webp (libwebp_anim))
[vost#0:0/libwebp_anim @ 0x5d02c173480] Starting thread...
[vf#0:0 @ 0x5d02c150500] Starting thread...
[vist#0:0/h264 @ 0x5d02c220780] [dec:h264 @ 0x5d02c220a80] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280] Starting thread...
Press [q] to stop, [?] for help
[h264 @ 0x5d02c1e0d80] Reinit context to 1280x720, pix_fmt: yuv420p
[Parsed_thumbnail_1 @ 0x5d0300506c0] batch size: 12 frames
[Parsed_scale_5 @ 0x5d0300509c0] w:-2 h:250 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[graph 0 input from stream 0:0 @ 0x5d030050a80] w:1280 h:720 pixfmt:yuv420p tb:1/90000 fr:53/3 sar:1/1 csp:smpte170m range:tv
[Parsed_fps_0 @ 0x5d030050540] fps=12/1
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280] Terminating thread with return code 0 (success)
[vist#0:0/h264 @ 0x5d02c220780] [dec:h264 @ 0x5d02c220a80] Decoder thread received EOF packet
[vist#0:0/h264 @ 0x5d02c220780] [dec:h264 @ 0x5d02c220a80] Decoder returned EOF, finishing
[Parsed_scale_5 @ 0x5d0300509c0] w:1280 h:720 fmt:yuv420p csp:smpte170m range:tv sar:1/1 -> w:444 h:250 fmt:yuv420p csp:smpte170m range:pc sar:1000/999 flags:0x00042200
[graph 0 input from stream 0:0 @ 0x5d030050a80] video frame properties congruent with link at pts_time: 4.193111
[Parsed_fps_0 @ 0x5d030050540] Set first pts to 50
[vist#0:0/h264 @ 0x5d02c220780] [dec:h264 @ 0x5d02c220a80] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x5d02c150500] Filtergraph returned EOF, finishing
[vf#0:0 @ 0x5d02c150500] All consumers returned EOF
[vost#0:0/libwebp_anim @ 0x5d02c173480] No filtered frames for output stream, trying to initialize anyway.
Output #0, webp, to 'upload/thumbs/6c1506c2-8f72-4f59-b282-931c53ef071a/36/37/3637cbd6-7097-4ff9-adf6-b9f33e5d5e83-thumbnail.webp':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf61.1.100
  Stream #0:0(und): Video: webp, 1 reference frame, yuv420p(progressive), 444x250 [SAR 1000:999 DAR 16:9], q=2-31, 200 kb/s, 12 fps, 1k tbn (default)
      Metadata:
        creation_time   : 2018-09-11T11:47:40.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 09/11/2018.
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.3.100 libwebp_anim
[out#0/webp @ 0x5d02c161140] Starting thread...
[Parsed_fps_0 @ 0x5d030050540] 2 frames in, 0 frames out; 2 frames dropped, 0 frames duplicated.
[vost#0:0/libwebp_anim @ 0x5d02c173480] Encoder thread received EOF
[libwebp encoder @ 0x5d02c060e00] WebPAnimEncoderAssemble() failed with error: 1
[vost#0:0/libwebp_anim @ 0x5d02c173480] Error submitting video frame to the encoder
[vost#0:0/libwebp_anim @ 0x5d02c173480] Error flushing encoder: Cannot allocate memory
[vost#0:0/libwebp_anim @ 0x5d02c173480] Task finished with error code: -12 (Cannot allocate memory)
[vost#0:0/libwebp_anim @ 0x5d02c173480] Terminating thread with return code -12 (Cannot allocate memory)
[out#0/webp @ 0x5d02c161140] All streams finished
[out#0/webp @ 0x5d02c161140] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x5d02c150500] Terminating thread with return code 0 (success)
[AVIOContext @ 0x5d02c060b80] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[out#0/webp @ 0x5d02c161140] Output file #0 (upload/thumbs/6c1506c2-8f72-4f59-b282-931c53ef071a/36/37/3637cbd6-7097-4ff9-adf6-b9f33e5d5e83-thumbnail.webp):
[out#0/webp @ 0x5d02c161140]   Output stream #0:0 (video): 0 frames encoded; 0 packets muxed (0 bytes);
[out#0/webp @ 0x5d02c161140]   Total: 0 packets (0 bytes) muxed
[out#0/webp @ 0x5d02c161140] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
[out#0/webp @ 0x5d02c161140] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280] Input file #0 (upload/upload/6c1506c2-8f72-4f59-b282-931c53ef071a/9b/e2/9be2d80f-b3c2-443c-b69e-a8605eb95ead.MP4):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280]   Input stream #0:0 (video): 114 packets read (1887831 bytes); 2 frames decoded; 0 decode errors;
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x5d02c120280]   Total: 114 packets (1887831 bytes) demuxed
[AVIOContext @ 0x5d02c060680] Statistics: 1994661 bytes read, 0 seeks
Conversion failed!

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: ffmpeg exited with code 244: Conversion failed!

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: ffmpeg exited with code 244: Conversion failed!

    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "3637cbd6-7097-4ff9-adf6-b9f33e5d5e83"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "3e97422a-dd90-40fc-be79-9334a8bb4fd6"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "67a5d641-42a5-4830-930a-cbc739defb62"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "45a57ebd-5f91-48c3-9251-6d1ba165e15f"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "cb826661-d116-44ab-9d3b-73a80b77a509"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "4eeef2c4-1727-43ca-b9e5-e4a5c38bf5ad"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "a39cfb3e-b4b5-48a9-8a05-0f233be8c313"
}

[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/02/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "326b4a3a-882d-4d23-a1f9-72bdf53bdbf3"
}

```
