### DISCUSSION TITLE
Photos missing in timeline but exists when searching through filename.

### DISCUSSION THREAD

**Discussion by abishek235** [immich-app/immich#15889] [Q&A]
### The bug

I have uploaded all my photos from google takeout to immich, but they are missing in timeline. But, if I search using filename or go to explore tab and select the person the photos showing in the right place.  Its not available in both web and ios app.

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.7

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: big-bear-immich
services:
  database:
    cpu_shares: 90
    command: []
    container_name: immich-postgres
    deploy:
      resources:
        limits:
          memory: 15877M
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=immich
      - POSTGRES_PASSWORD=######
      - POSTGRES_USER=casaos
    hostname: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-immich/pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    networks:
      - big_bear_immich_network
    privileged: false
  immich-machine-learning:
    cpu_shares: 90
    command: []
    container_name: immich-machine-learning
    deploy:
      resources:
        limits:
          memory: 15877M
    environment:
      - DB_DATABASE_NAME=########
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=########
      - DB_PORT=5432
      - DB_USERNAME=############
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.125.5
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-immich/model-cache
        target: /cache
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    networks:
      - big_bear_immich_network
    privileged: false
  immich-server:
    cpu_shares: 90
    command: []
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 15877M
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=#########
      - DB_PORT=5432
      - DB_USERNAME=#########
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - REDIS_HOSTNAME=immich-redis
      - THUMB_LOCATION=/usr/src/app/upload/thumbs
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:release
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    ports:
      - mode: ingress
        target: 2283
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/#######/Storage1/Immich/upload
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /media/#########/SSD/Immich/immich/thumbs
        target: /usr/src/app/upload/thumbs
    devices: []
    cap_add: []
    networks:
      - big_bear_immich_network
    privileged: false
  redis:
    cpu_shares: 90
    command: []
    container_name: immich-redis
    deploy:
      resources:
        limits:
          memory: 15877M
    hostname: immich-redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: always
    ports: []
    volumes: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - big_bear_immich_network
    privileged: false
networks:
  big_bear_immich_network:
    name: big-bear-immich_big_bear_immich_network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBear
  description:
    en_us: Self-hosted photo and video storage.
  developer: ""
  hostname: #############
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  index: /
  is_uncontrolled: true
  main: immich-server
  port_map: ""
  scheme: http
  store_app_id: big-bear-immich
  tagline:
    en_us: Immich
  thumbnail: ""
  title:
    custom: ""
    en_us: Immich
```

### Your .env content

```Shell
environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=#########
      - DB_PORT=5432
      - DB_USERNAME=#########
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - REDIS_HOSTNAME=immich-redis
      - THUMB_LOCATION=/usr/src/app/upload/thumbs
   
    volumes:
      - type: bind
        source: /media/#######/Storage1/Immich/upload
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /media/#########/SSD/Immich/immich/thumbs
        target: /usr/src/app/upload/thumbs
```

### Reproduction steps

1. Uploaded all photos from google takeout
2. observed that photo was missing in timeline
3. Photo was visible when seraching using filename IMG_0000
4. Photo was also available when going to explore and selecting the person and scrolled through that timeline

### Relevant log output

```shell

```
