### DISCUSSION TITLE
Unable to upload files that are larger than 2 GB on web

### DISCUSSION THREAD

**Discussion by vishwa5854** [immich-app/immich#15906] [Q&A]
### The bug

If an upload of a file that is larger than 2GB is initiated on webapp, it would fail. I have looked at the console logs or errors in developer console and seems like it is an issue from the `SubtleCrypto` library function.

Here's the exact error I see
```
Error calculating sha1 file=20250204_142925.mp4) TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
[HQvrpDmE.js:1:3984](https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js)
[handleError]: Unable to upload file TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
 J@https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js:1:3688
[CeBM9qXI.js:1:643](https://photos.cruger.in/_app/immutable/chunks/CeBM9qXI.js)
Error calculating sha1 file=20250204_142925.mp4) TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
[HQvrpDmE.js:1:3984](https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js)
[handleError]: Unable to upload file TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
 J@https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js:1:3688
```

![Image](https://github.com/user-attachments/assets/bd63da4f-8889-4a3d-8d52-e545e0a73f75)

![Image](https://github.com/user-attachments/assets/cac0c536-2088-490b-aee0-768e52d5708d)

However it gets uploaded with no issues on the mobile app (I'm guessing it is using a different crypto library that doesn't have this issue)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.125.6

### Version of Immich Mobile App

1.125.5.build.181

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '127.0.0.1:2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=***************

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create a video that is very large specifically greater than 2GB
2. Try to upload it to immich using the web app on phone or desktop
3. You will see an error message saying upload failed
...

### Relevant log output

```shell
Error calculating sha1 file=20250204_142925.mp4) TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
[HQvrpDmE.js:1:3984](https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js)
[handleError]: Unable to upload file TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
 J@https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js:1:3688
[CeBM9qXI.js:1:643](https://photos.cruger.in/_app/immutable/chunks/CeBM9qXI.js)
Error calculating sha1 file=20250204_142925.mp4) TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
[HQvrpDmE.js:1:3984](https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js)
[handleError]: Unable to upload file TypeError: SubtleCrypto.digest: ArrayBuffer branch of (ArrayBufferView or ArrayBuffer) can't be an ArrayBuffer or an ArrayBufferView larger than 2 GB
    J Immutable
 J@https://photos.cruger.in/_app/immutable/chunks/HQvrpDmE.js:1:3688
```
