### DISCUSSION TITLE
Immich Server Wont Start (Redis/DB Timeout)

### DISCUSSION THREAD

**Discussion by kirantnath** [immich-app/immich#15991] [Q&A] [answered]
### The bug

Hello,

I am running v1.125.7 on Synology DS224+ and things were good for the last year.
Since 9th Feb (there were no changes to Immich since the update to 1.125.7, I am unable to get the server to start up. 

Kindly help.

### The OS that Immich Server is running on

Synology DS224+

### Version of Immich Server

1.125.7

### Version of Immich Mobile App

1.125.7

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${MY_PHOTOS}:/mnt/media/photos:rw   
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always


  database:
    container_name: Immich-DB
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/homes/immichadmin/Photos/immich/
MY_PHOTOS=/volume1/photo
IMMICH_VERSION=release
TZ=...(HIDDEN)
NODE_ENV=production
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=immichpw
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/volume1/docker/immich/db
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET= ..... .(HIDDEN)
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Restart Server
2. The server does not start and exits with the following log
3.
...

### Relevant log output

```shell
Initializing Immich v1.125.7
Detected CPU Cores: 4
Starting api worker
Starting microservices worker


Error: getaddrinfo EAI_AGAIN immich-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis'
}
Error: getaddrinfo EAI_AGAIN immich-redis
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'immich-redis'
}


Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:638:28)
    at Socket.emit (node:events:524:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [NestFactory] Starting Nest application...
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] KyselyModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] KyselyCoreModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +1ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 17  - 02/10/2025, 7:27:25 AM   ERROR [ExceptionHandler] Connection terminated due to connection timeout
Error: Connection terminated due to connection timeout
    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
    at Object.onceWrapper (node:events:638:28)
    at Connection.emit (node:events:524:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
    at Socket.emit (node:events:524:28)
    at TCP.<anonymous> (node:net:351:12)
[Nest] 7  - 02/10/2025, 7:27:25 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 02/10/2025, 7:27:25 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
microservices worker exited with code 1
Killing api process
```

### Additional information

Please find the other logs below:

--------------------------------------------------------------------------------------------------------------------------------------------

(Immich REDIS)

1:C 09 Feb 2025 22:13:40.944 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

1:C 09 Feb 2025 22:13:40.944 # Redis version=6.2.17, bits=64, commit=00000000, modified=0, pid=1, just started

1:C 09 Feb 2025 22:13:40.944 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf

1:M 09 Feb 2025 22:13:40.945 * monotonic clock: POSIX clock_gettime

1:M 09 Feb 2025 22:13:40.946 * Running mode=standalone, port=6379.

1:M 09 Feb 2025 22:13:40.946 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

1:M 09 Feb 2025 22:13:40.946 # Server initialized

1:M 09 Feb 2025 22:13:40.946 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

1:M 09 Feb 2025 22:13:40.946 * Loading RDB produced by version 6.2.17

1:M 09 Feb 2025 22:13:40.946 * RDB age 27803 seconds

1:M 09 Feb 2025 22:13:40.946 * RDB memory usage when created 0.77 Mb

1:M 09 Feb 2025 22:13:40.946 # Done loading RDB, keys loaded: 0, keys expired: 0.

1:M 09 Feb 2025 22:13:40.946 * DB loaded from disk: 0.000 seconds

1:M 09 Feb 2025 22:13:40.946 * Ready to accept connections

--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------

(Immich DB LOG FILE)

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-02-10 07:14:11.035  [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

2025-02-10 07:14:11.151  [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

2025-02-10 07:14:11.151  [1] LOG:  listening on IPv6 address "::", port 5432

2025-02-10 07:14:11.642  [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

[2025-02-09T22:14:12Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17351".

[2025-02-09T22:14:12Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17595".

[2025-02-09T22:14:12Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17351/segments/e6526e9b-8295-4338-83b8-cf5cbcc11842".

2025-02-10 07:14:12.348  [35] LOG:  database system was shut down at 2025-02-09 23:30:14 

2025-02-10 07:14:13.803  [1] LOG:  database system is ready to accept connections

2025-02-10 07:14:28.424  [46] LOG:  could not send data to client: Broken pipe

2025-02-10 07:14:28.424  [46] FATAL:  connection to client lost

[2025-02-09T22:14:31Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17595/segments/a0c09592-1ff3-4dbd-aeee-a30ce999a582".

2025-02-10 07:19:12.434  [33] LOG:  checkpoint starting: time

2025-02-10 07:19:12.752  [33] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.060 s, total=0.318 s; sync files=3, longest=0.060 s, average=0.020 s; distance=0 kB, estimate=0 kB; lsn=14/808ABFE8, redo lsn=14/808ABFB0
