### DISCUSSION TITLE
chdir to cwd (\"/usr/src/app\") set in config.json failed: no such file or directory: unknown"

### DISCUSSION THREAD

**Discussion by vadzxd** [immich-app/immich#15993] [Q&A] [answered]
### The bug

I started Immich containers using the same immich docker-compose.yml file on two machines，There is a little difference in the images of docker-compose.yml file. On the first machine (an x86 machine), after entering the container, the directory listing is as follows:

total 100
drwxr-xr-x   1 root root  4096 Feb 10 17:10 .
drwxr-xr-x   1 root root  4096 Feb 10 17:10 ..
-rwxr-xr-x   1 root root     0 Feb 10 17:10 .dockerenv
-rw-r--r--   1 root root 32388 Jan 30 01:43 LICENSE
lrwxrwxrwx   1 root root     7 Jan 13 08:00 bin -> usr/bin
drwxr-xr-x   2 root root  4096 Dec 31 18:25 boot
drwxr-xr-x   1 root root  4096 Jan 30 01:47 build
drwxr-xr-x   5 root root   340 Feb 10 17:10 dev
drwxr-xr-x   1 root root  4096 Feb 10 17:10 etc
drwxr-xr-x   1 root root  4096 Jan 22 23:25 home
lrwxrwxrwx   1 root root     7 Jan 13 08:00 lib -> usr/lib
lrwxrwxrwx   1 root root     9 Jan 13 08:00 lib64 -> usr/lib64
drwxr-xr-x   2 root root  4096 Jan 30 01:47 licenses
drwxr-xr-x   2 root root  4096 Jan 13 08:00 media
drwxr-xr-x   2 root root  4096 Jan 13 08:00 mnt
drwxr-xr-x   1 root root  4096 Jan 22 23:25 opt
dr-xr-xr-x 664 root root     0 Feb 10 17:10 proc
drwx------   1 root root  4096 Jan 30 01:47 root
drwxr-xr-x   3 root root  4096 Jan 13 08:00 run
lrwxrwxrwx   1 root root     8 Jan 13 08:00 sbin -> usr/sbin
drwxr-xr-x   2 root root  4096 Jan 13 08:00 srv
dr-xr-xr-x  13 root root     0 Feb 10 17:10 sys
drwxrwxrwt   1 root root  4096 Jan 30 01:47 tmp
drwxr-xr-x   1 root root  4096 Jan 13 08:00 usr
drwxr-xr-x   1 root root  4096 Jan 13 08:00 var
In this container, the directory /usr/src/app is directly accessible.

However, on the other machine (an ARM machine), the Immich container’s directory listing looks like this:

total 8
drwxr-xr-x   17 1000     1000             0 Jan 21 14:56 .
drwxr-xr-x   17 1000     1000             0 Jan 21 14:56 ..
lrwxrwxrwx    1 1000     1000             7 Dec  3 07:04 bin -> usr/bin
drwxr-xr-x    1 0        0                6 Feb 10 11:58 chroot
drwxr-xr-x    3 1000     1000             0 Dec  3 07:11 conf
drwxr-xr-x    2 0        0                0 Jan 21 13:15 config
drwxr-xr-x    3 0        0                0 Jan 21 14:56 custom_components
drwxr-xr-x   19 0        0             4060 Jan 21 08:18 dev
drwxr-xr-x    7 1000     1000             0 Jan 21 15:20 etc
-rwxr-xr-x    1 1000     1000          1196 Dec  7 06:04 init
lrwxrwxrwx    1 1000     1000             7 Dec  3 07:04 lib -> usr/lib
dr-xr-xr-x  508 0        0                0 Jan 21 08:17 proc
drwxr-xr-x   19 0        0              285 Dec  5 02:26 rom
drwx------    2 0        0                0 Nov 28 01:08 root
drwxr-xr-x    6 0        0              120 Jan 21 08:18 run
lrwxrwxrwx    1 1000     1000             8 Dec  3 07:04 sbin -> usr/sbin
drwxr-xr-x    7 1000     1000             0 Dec  3 07:11 scripts
dr-xr-xr-x   14 0        0                0 Jan 21 08:17 sys
drwxr-xr-x    2 0        0                0 Jan 21 08:17 userdata
drwxr-xr-x    5 1000     1000             0 Dec  3 07:11 usr
drwxr-xr-x    5 0        0             4096 Dec 24 13:04 zettlab
To access the original /usr/src/app directory, I need to go through /chroot/usr/src/app. However, the /usr/src/app directory does not contain this directory; attempting to change into it results in the error:

cd: can't cd to /usr/src/app: No such file or directory
Could you help me analyze what might be causing the directory differences? On the ARM machine, the different directory structure causes the immich_server health check to fail with the following error:

Feb 10 12:04:43 ZettLab dockerd[2219310]: time="2025-02-10T12:04:43.559306397Z" level=warning msg="Health check for container dfbf0e8210c4190d873f07ae0576d9f0bf4146b88ce10500b9e6daac3d21c107 error: OCI runtime exec failed: exec failed: unable to start container process: chdir to cwd (\"/usr/src/app\") set in config.json failed: no such file or directory: unknown"

### The OS that Immich Server is running on

debians

### Version of Immich Server

release

### Version of Immich Mobile App

no

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
#    working_dir: /chroot/usr/src/app
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ["/bin/sh", "-c", "ln -sf /chroot/usr/src/app /usr/src/app && ./start-server.sh"]
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
cat .env
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. just exec   docker compose up -d

### Relevant log output

```shell

```
