### DISCUSSION TITLE
Orange Pi 5 Hardware acceleration for ML not working

### DISCUSSION THREAD

**Discussion by tekofx** [immich-app/immich#16080] [Q&A]
### The bug

I have configured the docker-compose.yml and hwaccel.ml.yml like in the wiki, and check if exists /dev/mali0, /usr/lib/libmali.so and /lib/firmware/mali_csffw.bin. I have also installed https://github.com/tsukumijima/libmali-rockchip/releases/download/v1.9-1-3238416/libmali-valhall-g610-g13p0-gbm_1.9-1_arm64.deb and check with  clinfo if it works. But the HW acceleration does not work.

### The OS that Immich Server is running on

Armbian 24.11.1 jammy aarch64

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: rkmpp # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: armnn
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
volumes:
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces


# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Trigger a Face Recognition or Smart Search Job
2. Check docker logs immich_machine_learning -f
3. The output contains  ['CPUExecutionProvider'], in descending order of preference

### Relevant log output

```shell

```

**Comment by mhl221135** [comment]
I'm trying to run Immich Machine Learning in Portainer with ARM NN acceleration on my Orange Pi 5, but every time I start the container, it defaults to CPUExecutionProvider instead of ARM NN, even though all drivers and dependencies are present.
```yaml
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/OpenCL:/etc/OpenCL:ro
      - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    security_opt:
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/mali0:/dev/mali0
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      #- /dev/video-dec0:/dev/video-dec0  # Decoder
      #- /dev/video-enc0:/dev/video-enc0  # Encoder
    environment:
      - HWACCEL_RKMPP=true

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    deploy:

    devices:
      # Enable ARM NN (AI Inference Acceleration)
      - /dev/mali0:/dev/mali0
    volumes:
      - model-cache:/cache
      - /usr/lib/aarch64-linux-gnu/libmali.so:/usr/lib/libmali.so:ro
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro
    env_file:
      - stack.env
    environment:
      - HWACCEL_ARMNN=true
      - MACHINE_LEARNING_ANN=true
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```
Log of container 

`
Initializing Immich ML v1.128.0
[03/04/25 12:59:02] INFO     Starting gunicorn 23.0.0                           
[03/04/25 12:59:02] INFO     Listening at: http://[::]:3003 (9)                 
[03/04/25 12:59:02] INFO     Using worker: app.config.CustomUvicornWorker       
[03/04/25 12:59:02] INFO     Booting worker with pid: 10                        
[03/04/25 12:59:10] INFO     Started server process [10]                        
[03/04/25 12:59:10] INFO     Waiting for application startup.                   
[03/04/25 12:59:10] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[03/04/25 12:59:10] INFO     Initialized request thread pool with 8 threads.    
[03/04/25 12:59:10] INFO     Application startup complete.                      
[03/04/25 13:01:18] INFO     Loading visual model                               
                             'XLM-Roberta-Large-Vit-B-16Plus' to memory         
[03/04/25 13:01:18] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         

`

**Reply by haspre** [reply]
Same on my opi5+

**Comment by mhl221135** [comment]
looks like image missing dependencies which required for machine learning use armnn and its pick cpu since of that

i fixed it with adding commands which install dependencies in entrypoint

```yml
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/OpenCL:/etc/OpenCL:ro
      - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always

    security_opt:
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/mali0:/dev/mali0
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      #- /dev/video-dec0:/dev/video-dec0  # Decoder
      #- /dev/video-enc0:/dev/video-enc0  # Encoder
    environment:
      - HWACCEL_RKMPP=true

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
        # Override the entrypoint so we can run apt-get, then start Immich ML
    entrypoint: >
      sh -c "apt-get update && \
      apt-get install -y libx11-6 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1 libxext6 libxcb1 && \
      apt-get clean && rm -rf /var/lib/apt/lists/* && \
      exec /usr/src/app/start.sh"
    deploy:
    
    devices:
    # Enable ARM NN (AI Inference Acceleration)
    - /dev/mali0:/dev/mali0
    volumes:
      - model-cache:/cache
      - /usr/lib/aarch64-linux-gnu/libmali.so:/usr/lib/libmali.so:ro
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro
    env_file:
      - stack.env
    environment:
      - HWACCEL_ARMNN=true
      - MACHINE_LEARNING_ANN=true
      - MACHINE_LEARNING_ANN_FP16_TURBO=true
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```


so now i get in logs model load
```
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]

Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]

Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]

Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8693 kB]

Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [13.3 kB]

Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [242 kB]

Fetched 9202 kB in 20s (461 kB/s)

Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

libx11-6 is already the newest version (2:1.8.4-2+deb12u2).

libx11-xcb1 is already the newest version (2:1.8.4-2+deb12u2).

libxcb-dri2-0 is already the newest version (1.15-1).

libxcb-dri3-0 is already the newest version (1.15-1).

libxcb-glx0 is already the newest version (1.15-1).

libxcb-present0 is already the newest version (1.15-1).

libxcb-sync1 is already the newest version (1.15-1).

libxext6 is already the newest version (2:1.3.4-1+b1).

libxcb1 is already the newest version (1.15-1).

0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

Initializing Immich ML v1.128.0

[03/04/25 20:39:06] INFO     Starting gunicorn 23.0.0                           

[03/04/25 20:39:06] INFO     Listening at: http://[::]:3003 (105)               

[03/04/25 20:39:06] INFO     Using worker: app.config.CustomUvicornWorker       

[03/04/25 20:39:06] INFO     Booting worker with pid: 106                       

[03/04/25 20:39:13] INFO     Started server process [106]                       

[03/04/25 20:39:13] INFO     Waiting for application startup.                   

[03/04/25 20:39:13] INFO     Created in-memory cache with unloading after 300s  

                             of inactivity.                                     

[03/04/25 20:39:13] INFO     Initialized request thread pool with 8 threads.    

[03/04/25 20:39:13] INFO     Application startup complete.                      

[03/04/25 20:39:57] INFO     Loading visual model 'ViT-B-32__openai' to memory  

arm_release_ver: g13p0-01eac0, rk_so_ver: 9

[03/04/25 20:39:57] INFO     Loading ANN model                                  

                             /cache/clip/ViT-B-32__openai/visual/model.armnn ...

[03/04/25 20:40:01] INFO     Loaded ANN model with ID 0                         


```

but looks like its working fine only for visual models and only for ViT-B-32__openai - looks like no compatible model for textual searches, if i try run text search i getting next errors- not sure how to fix it- looks like we need model for arm 

```
[03/04/25 20:44:08] INFO     Loading textual model 'ViT-B-32__openai' to memory 

[03/04/25 20:44:08] INFO     Loading ANN model                                  

                             /cache/clip/ViT-B-32__openai/textual/model.armnn   

                             ...                                                

Warning: WARNING: Layer of type Constant is not supported on requested backend GpuAcc for input data type Float32 and output data type Signed64 (reason: Unsupported DataType), falling back to the next backend.

Warning: WARNING: Layer of type Constant is not supported on requested backend GpuAcc for input data type Float32 and output data type Signed64 (reason: Unsupported DataType), falling back to the next backend.

Warning: WARNING: Layer of type Cast is not supported on requested backend GpuAcc for input data type Boolean and output data type Signed64 (reason: in validate_arguments src/gpu/cl/kernels/ClCastKernel.cpp:59: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type Cast is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type ElementwiseBinary is not supported on requested backend GpuAcc for input data type Signed64 and output data type Signed64 (reason: in validate_arguments src/gpu/cl/kernels/ClMulKernel.cpp:63: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type ElementwiseBinary is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type ElementwiseBinary is not supported on requested backend GpuAcc for input data type Signed64 and output data type Signed64 (reason: in validate_arguments_with_arithmetic_rules src/gpu/cl/kernels/ClElementwiseKernel.cpp:160: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type ElementwiseBinary is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type Gather is not supported on requested backend GpuAcc for input data type Float16 and output data type Float16 (reason: in validate_arguments src/core/CL/kernels/CLGatherKernel.cpp:58: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type Gather is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type Constant is not supported on requested backend GpuAcc for input data type Float32 and output data type Signed64 (reason: Unsupported DataType), falling back to the next backend.

Warning: WARNING: Layer of type Constant is not supported on requested backend GpuAcc for input data type Float32 and output data type Signed64 (reason: Unsupported DataType), falling back to the next backend.

Warning: WARNING: Layer of type Cast is not supported on requested backend GpuAcc for input data type Boolean and output data type Signed64 (reason: in validate_arguments src/gpu/cl/kernels/ClCastKernel.cpp:59: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type Cast is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type ElementwiseBinary is not supported on requested backend GpuAcc for input data type Signed64 and output data type Signed64 (reason: in validate_arguments src/gpu/cl/kernels/ClMulKernel.cpp:63: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type ElementwiseBinary is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type ElementwiseBinary is not supported on requested backend GpuAcc for input data type Signed64 and output data type Signed64 (reason: in validate_arguments_with_arithmetic_rules src/gpu/cl/kernels/ClElementwiseKernel.cpp:160: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type ElementwiseBinary is not supported on any preferred backend [GpuAcc ]

Warning: WARNING: Layer of type Gather is not supported on requested backend GpuAcc for input data type Float32 and output data type Float32 (reason: in validate_arguments src/core/CL/kernels/CLGatherKernel.cpp:58: ITensor data type S64 not supported by this kernel), falling back to the next backend.

Warning: ERROR: Layer of type Gather is not supported on any preferred backend [GpuAcc ]

[03/04/25 20:44:10] ERROR    Exception in ASGI application                      

                                                                                

                             ╭─────── Traceback (most recent call last) ───────╮

                             │ /usr/src/app/main.py:177 in predict             │

                             │                                                 │

                             │   174 │   │   inputs = text                     │

                             │   175 │   else:                                 │

                             │   176 │   │   raise HTTPException(400, "Either  │

                             │ ❱ 177 │   response = await run_inference(inputs │

                             │   178 │   return ORJSONResponse(response)       │

                             │   179                                           │

                             │   180                                           │

                             │                                                 │

                             │ /usr/src/app/main.py:200 in run_inference       │

                             │                                                 │

                             │   197 │   │   response[entry["task"]] = output  │

                             │   198 │                                         │

                             │   199 │   without_deps, with_deps = entries     │

                             │ ❱ 200 │   await asyncio.gather(*[_run_inference │

                             │   201 │   if with_deps:                         │

                             │   202 │   │   await asyncio.gather(*[_run_infer │

                             │   203 │   if isinstance(payload, Image):        │

                             │                                                 │

                             │ /usr/src/app/main.py:194 in _run_inference      │

                             │                                                 │

                             │   191 │   │   │   except KeyError:              │

                             │   192 │   │   │   │   message = f"Task {entry[' │

                             │       output of {dep}"                          │

                             │   193 │   │   │   │   raise HTTPException(400,  │

                             │ ❱ 194 │   │   model = await load(model)         │

                             │   195 │   │   output = await run(model.predict, │

                             │   196 │   │   outputs[model.identity] = output  │

                             │   197 │   │   response[entry["task"]] = output  │

                             │                                                 │

                             │ /usr/src/app/main.py:238 in load                │

                             │                                                 │

                             │   235 │   │   return model                      │

                             │   236 │                                         │

                             │   237 │   try:                                  │

                             │ ❱ 238 │   │   return await run(_load, model)    │

                             │   239 │   except (OSError, InvalidProtobuf, Bad │

                             │   240 │   │   log.warning(f"Failed to load {mod │

                             │       '{model.model_name}'. Clearing cache.")   │

                             │   241 │   │   model.clear_cache()               │

                             │                                                 │

                             │ /usr/src/app/main.py:213 in run                 │

                             │                                                 │

                             │   210 │   if thread_pool is None:               │

                             │   211 │   │   return func(*args, **kwargs)      │

                             │   212 │   partial_func = partial(func, *args, * │

                             │ ❱ 213 │   return await asyncio.get_running_loop │

                             │   214                                           │

                             │   215                                           │

                             │   216 async def load(model: InferenceModel) ->  │

                             │                                                 │

                             │ /usr/local/lib/python3.11/concurrent/futures/th │

                             │ read.py:58 in run                               │

                             │                                                 │

                             │ /usr/src/app/main.py:225 in _load               │

                             │                                                 │

                             │   222 │   │   │   raise HTTPException(500, f"Fa │

                             │   223 │   │   with lock:                        │

                             │   224 │   │   │   try:                          │

                             │ ❱ 225 │   │   │   │   model.load()              │

                             │   226 │   │   │   except FileNotFoundError as e │

                             │   227 │   │   │   │   if model.model_format ==  │

                             │   228 │   │   │   │   │   raise e               │

                             │                                                 │

                             │ /usr/src/app/models/base.py:53 in load          │

                             │                                                 │

                             │    50 │   │   self.download()                   │

                             │    51 │   │   attempt = f"Attempt #{self.load_a │

                             │       else "Loading"                            │

                             │    52 │   │   log.info(f"{attempt} {self.model_ │

                             │       '{self.model_name}' to memory")           │

                             │ ❱  53 │   │   self.session = self._load()       │

                             │    54 │   │   self.loaded = True                │

                             │    55 │                                         │

                             │    56 │   def predict(self, *inputs: Any, **mod │

                             │                                                 │

                             │ /usr/src/app/models/clip/textual.py:26 in _load │

                             │                                                 │

                             │    23 │   │   return serialize_np_array(res)    │

                             │    24 │                                         │

                             │    25 │   def _load(self) -> ModelSession:      │

                             │ ❱  26 │   │   session = super()._load()         │

                             │    27 │   │   log.debug(f"Loading tokenizer for │

                             │    28 │   │   self.tokenizer = self._load_token │

                             │    29 │   │   tokenizer_kwargs: dict[str, Any]  │

                             │                                                 │

                             │ /usr/src/app/models/base.py:78 in _load         │

                             │                                                 │

                             │    75 │   │   )                                 │

                             │    76 │                                         │

                             │    77 │   def _load(self) -> ModelSession:      │

                             │ ❱  78 │   │   return self._make_session(self.mo │

                             │    79 │                                         │

                             │    80 │   def clear_cache(self) -> None:        │

                             │    81 │   │   if not self.cache_dir.exists():   │

                             │                                                 │

                             │ /usr/src/app/models/base.py:108 in              │

                             │ _make_session                                   │

                             │                                                 │

                             │   105 │   │                                     │

                             │   106 │   │   match model_path.suffix:          │

                             │   107 │   │   │   case ".armnn":                │

                             │ ❱ 108 │   │   │   │   session: ModelSession = A │

                             │   109 │   │   │   case ".onnx":                 │

                             │   110 │   │   │   │   session = OrtSession(mode │

                             │   111 │   │   │   case _:                       │

                             │                                                 │

                             │ /usr/src/app/sessions/ann.py:26 in __init__     │

                             │                                                 │

                             │   23 │   │   self.ann = Ann(tuning_level=settin │

                             │      "gpu-tuning.ann").as_posix())              │

                             │   24 │   │                                      │

                             │   25 │   │   log.info("Loading ANN model %s ... │

                             │ ❱ 26 │   │   self.model = self.ann.load(        │

                             │   27 │   │   │   model_path.as_posix(),         │

                             │   28 │   │   │   cached_network_path=model_path │

                             │   29 │   │   │   fp16=settings.ann_fp16_turbo,  │

                             │                                                 │

                             │ /usr/src/ann/ann.py:124 in load                 │

                             │                                                 │

                             │   121 │   │   │   cached_network_path.encode()  │

                             │   122 │   │   )                                 │

                             │   123 │   │   if net_id < 0:                    │

                             │ ❱ 124 │   │   │   raise ValueError("Cannot load │

                             │   125 │   │                                     │

                             │   126 │   │   self.input_shapes[net_id] = tuple │

                             │   127 │   │   │   self.shape(net_id, input=True │

                             │       input=True))                              │

                             ╰─────────────────────────────────────────────────╯

                             ValueError: Cannot load model!      
```
