### DISCUSSION TITLE
Jobs indefinitely "Waiting" while there are are no "active" jobs

### DISCUSSION THREAD

**Discussion by ollie-galbraith** [immich-app/immich#16137] [Q&A] [answered]
### The Bug 
All jobs are either never starting, or never fully completing (not entirely sure), even though there are no active jobs. 

![image](https://github.com/user-attachments/assets/bb7f853d-3cc7-4712-944e-d17df342f9f6)

### Immich version 
v1.126.1 

### OS
Ubuntu 24.04.1

###

### docker-compose.yml 
```yaml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - type: volume
        source: data_vol
        target: /usr/src/app/upload
        volume: 
          nocopy: true
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - MACHINE_LEARNING_PRELOAD__CLIP=${MACHINE_LEARNING_PRELOAD__CLIP}
      - MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION=${MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION}
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    environment:
      TZ: ${TZ}

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    user: '1004:1001'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
        volume: 
          nocopy: true
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  pg_data:
    driver_opts:
      type: "nfs"
      o: "addr=${SSD_NFS_ROOT_SHARE},nolock,rw"
      device: ":${SSD_NFS_MNT_SHARE}/${CONTAINER_NAME}/pg_data"
  model_cache:
    driver_opts:
      type: "nfs"
      o: "addr=${SSD_NFS_ROOT_SHARE},nolock,rw"
      device: ":${SSD_NFS_MNT_SHARE}/${CONTAINER_NAME}/model_cache"
  ts_data:
    driver_opts:
      type: "nfs"
      o: "addr=${SSD_NFS_ROOT_SHARE},nolock,rw"
      device: ":${SSD_NFS_MNT_SHARE}/${CONTAINER_NAME}/ts_data"
  data_vol:
    driver_opts:
      type: "nfs"
      o: "addr=${HDD_NFS_ROOT_SHARE},nolock,rw"
      device: ":${HDD_NFS_MNT_SHARE}"
  geocache_vol:
    driver_opts:
      type: "nfs"
      o: "addr=${SSD_NFS_ROOT_SHARE},nolock,rw"
      device: ":${SSD_NFS_MNT_SHARE}/${CONTAINER_NAME}/geocache_data"
```

### .env content
```ini
###################################################################################
# General
###################################################################################

CONTAINER_NAME=immich
SSD_NFS_ROOT_SHARE=<ssd_server>
SSD_NFS_MNT_SHARE=<path/to/share>
HDD_NFS_ROOT_SHARE=<hdd_server>
HDD_NFS_MNT_SHARE=<path/to/share>
TZ=Australia/Melbourne

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich

PUBLIC_LOGIN_PAGE_MESSAGE=Homelab Immich

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

IMMICH_TELEMETRY_INCLUDE=all

MACHINE_LEARNING_PRELOAD__CLIP=XLM-Roberta-Large-ViT-H-14__frozen_laion5b_s13b_b90k
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION=buffalo_l
IMMICH_WORKERS_INCLUDE=api
```
### Logs
Nothing seems to be out of the ordinary in the [logs](https://github.com/user-attachments/files/18814039/immich_logs.zip) from the initial look I took
