### DISCUSSION TITLE
408 Request Timeout when pulling from repositories

### DISCUSSION THREAD

**Discussion by gLiTcHyN0ObZ** [immich-app/immich#16281] [Q&A]
### The bug

This error is returned every time I attempt to run `docker compose up -d`

> Error response from daemon: unknown: <html><body><h1>408 Request Time-out</h1>
> Your browser didn't send a complete request in time.
> </body></html>
> exit status 1

It consistently stops at ~40 seconds and I have tried [decreasing the MTU](https://forums.docker.com/t/http-408-request-time-out-but-not-a-ratelimit-or-dns-issue/113755) as suggested by this article, however it doesn't seem to actually change when I enter `ip a`?

### The OS that Immich Server is running on

Ubuntu Server 24.04.2 LTS

### Version of Immich Server

n/a

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
GNU nano 7.2                                       docker-compose.yml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of U>
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
```

### Your .env content

```Shell
GNU nano 7.2                                              .env
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variabl>

# The location where your uploaded files are stored
UPLOAD_LOCATION=./media/sf_Immich
# The location where your database files are stored
DB_DATA_LOCATION=./home/immichuser/immich-app

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia>
# TZ=AU

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Install docker [following these steps](https://docs.docker.com/engine/install/ubuntu/)
2. Pulling the `docker-compose.yml` and `.env` files [from Immich](https://immich.app/docs/install/docker-compose)
3. Running `docker compose up -d`

### Relevant log output

```shell

```
