### DISCUSSION TITLE
[Feature]: Branding

### DISCUSSION THREAD

**Discussion by athornfam2** [immich-app/immich#1634] [Feature Request]
### Feature detail

Having the ability to rebrand the app background, logos, and images would be nice to make it unique for home use.

### Platform

Web

**Comment by nep2ner** [comment]
Maybe this would help to get businesses interested in Immich as well, which has potential to bring along donations and dev support?

**Comment by pl4nty** [comment]
I've implemented custom logos by mounting files under `/usr/src/app/build/client/_app/immutable/assets/`, but they contain a build hash eg `immich-logo.18dcdcef.svg`. It'd be nice to use a static filename like `immich-logo.svg`, but I suspect that'd cause issues on caching proxies eg Cloudflare

**Reply by MikNolhan** [reply]
The real trick to this would be to sed their SVG pre build. I actually just forked this, and will be setting up something locally to do a merge of fork with my logos and SVG, and the updated code.

**Comment by MexHigh** [comment]
I've managed to change the logo in the Webapp via Theme Settings > Custom CSS (see below for code) but this does not affect the app sadly. It would be nice, if this would be added, if it would affect the apps logo as well.

Custom CSS:

```css
img[alt="Immich Logo"] {
  content: url("https://exmaple.com/logo.svg");
}

h1[class*="font-immich-title"] {
  text-indent: -9999px;
}

h1[class*="font-immich-title"]:before {
  text-indent: 0;
  float: left;
  content: "CUSTOM TITLE HERE";
  /* you could also change the font here */
}
```
