### DISCUSSION TITLE
I can't update

### DISCUSSION THREAD

**Discussion by mrSaT13** [immich-app/immich#16385] [Q&A]
### The bug

Good afternoon dear developers
I use version 126
yesterday and to this day I wanted to update to the 127 version of the server as soon as possible-as you said in the message
but my docker container does not allow me to do this from the releases branch
writes an error in access with version 126 this was not
the case now in the docker compous file it is written as follows:
image: ghcr.io/immich-app/immich-server:release
maybe I should put it differently on 127 instead of release?
and won't the server data fly off when you change the branch?

### The OS that Immich Server is running on

debian

### Version of Immich Server

126.1

### Version of Immich Mobile App

126

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
```

### Your .env content

```Shell
there is no possibility
```

### Reproduction steps

1. went to the list of containers
2. clicked the pool
3. got an error with access
...

### Relevant log output

```shell

```
