### DISCUSSION TITLE
Uploaded and partner shared assets are broken after updating to v1.127.0

### DISCUSSION THREAD

**Discussion by FrankelJb** [immich-app/immich#16387] [Q&A]
### The bug

Since updating to [v1.127.0](https://github.com/immich-app/immich/releases/tag/v1.127.0), all assets are showing as broken in the web UI. They are viewable in the mobile app but Web isn't rendering them. They're also showing as broken in partner timeline while being viewable on the device they were uploaded from.

### The OS that Immich Server is running on

Kubernetes v1.31.2+k3s1

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

1.127.0 build.195

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.1
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.127.0@sha256:d38705cdebe2389b46e11d46b7874ffb81d7e7bbf68eaa02df6f26b97d550901
            resources:
              limits:
                memory: 5000Mi
              requests:
                cpu: 100m
                memory: 800Mi
      server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.127.0@sha256:6606ce7740f7a06f7a53b49083100c6c05f75c84c85a87e9e4e7309ac0c5d454
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          external-dns.alpha.kubernetes.io/target: external.${ROOT_DOMAIN}
        className: external
        enabled: true
        hosts:
          - host: immich.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: server
                  port: http
        tls:
          - hosts:
              - immich.${ROOT_DOMAIN}
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
      model-cache:
        type: emptyDir
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
    service:
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      server:
        controller: server
        ports:
          http:
            port: 2283
```

### Your .env content

```Shell
apiVersion: v1
data:
  DISABLE_REVERSE_GEOCODING: "true"
  NODE_ENV: "production"
  REDIS_HOSTNAME: valkey.default.svc.cluster.local
  IMMICH_SERVER_URL: http://immich-server.cloud.svc.cluster.local:2283
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.cloud.svc.cluster.local:3003
  IMMICH_LOG_LEVEL: "debug"
  TYPESENSE_HOST: immich-typesense.cloud.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: immich-configmap
  namespace: cloud
```

### Reproduction steps

1. Update to v1.127.0
2. Upload assets from mobile
3. View broken assets in partner timeline
4. View broken assets on web of same user
...

### Relevant log output

```shell
User 1 Web

[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~h9strrli] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~h9strrli] GET /api/assets/6c6638bd-71de-43b3-958d-35accdcc427b/thumbnail?size=thumbnail 404 10.20ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~62pjmaym] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~62pjmaym] GET /api/assets/9470dc06-fdf1-4898-9962-20281d7e4244/thumbnail?size=thumbnail 404 33.23ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~b2mocm6n] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~b2mocm6n] GET /api/assets/2ebe7c1c-2a99-4c53-aacd-752202aabb11/thumbnail?size=thumbnail 404 16.23ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~dce76u7a] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~dce76u7a] GET /api/assets/f3f07482-293d-4999-8f70-ee473b5b0826/thumbnail?size=thumbnail 404 13.84ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~h5epmgco] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~h5epmgco] GET /api/assets/de2f334e-ccd8-4f9e-908a-2d4bc57c3109/thumbnail?size=thumbnail 404 18.18ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~fqmqy19e] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~fqmqy19e] GET /api/assets/a82a7023-98c0-43d3-8f55-acf4accf9220/thumbnail?size=thumbnail 404 19.85ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~7cryaepn] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~7cryaepn] GET /api/assets/1ed302aa-11c7-4127-90ac-32cf667c1728/thumbnail?size=thumbnail 404 21.25ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:GlobalExceptionFilter~ygrze5kc] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~ygrze5kc] GET /api/assets/a32d464e-b505-40d2-8b03-a27297f9e935/thumbnail?size=thumbnail 404 15.35ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~95ez1ddd] GET /api/server/storage 200 1.07ms 192.168.1.201
[Nest] 17  - 02/27/2025, 9:46:58 AM   DEBUG [Api:LoggingInterceptor~96vgf9zp] GET /api/assets/device/f2b8f665ca55eabb1d7e524e52cec3b95b46c87993ef18315929b06fddeb2f16 200 7.50ms 192.168.1.201


User 2 Web

[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~no8k9c8h] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~no8k9c8h] GET /api/assets/9470dc06-fdf1-4898-9962-20281d7e4244/thumbnail?size=thumbnail 404 9.43ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~l5qqbrvv] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~l5qqbrvv] GET /api/assets/2ebe7c1c-2a99-4c53-aacd-752202aabb11/thumbnail?size=thumbnail 404 8.02ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~1l7le1tk] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~1l7le1tk] GET /api/assets/1ed302aa-11c7-4127-90ac-32cf667c1728/thumbnail?size=thumbnail 404 6.59ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~hub2nzui] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~hub2nzui] GET /api/assets/a82a7023-98c0-43d3-8f55-acf4accf9220/thumbnail?size=thumbnail 404 6.53ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~8iowmbja] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~8iowmbja] GET /api/assets/de2f334e-ccd8-4f9e-908a-2d4bc57c3109/thumbnail?size=thumbnail 404 6.37ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~uksw6syd] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~uksw6syd] GET /api/assets/f3f07482-293d-4999-8f70-ee473b5b0826/thumbnail?size=thumbnail 404 4.87ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:GlobalExceptionFilter~qfwdy06j] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~qfwdy06j] GET /api/assets/a32d464e-b505-40d2-8b03-a27297f9e935/thumbnail?size=thumbnail 404 4.41ms 192.168.1.8
[Nest] 17  - 02/27/2025, 9:47:30 AM   DEBUG [Api:LoggingInterceptor~g6vyekbp] GET /api/server/about 200 87.87ms 192.168.1.8


User 2 Mobile

2025-02-27 17:50:16.756326 | INFO     | BackupNotifier       | _getBackupAlbumsInfo: Found 24 available albums |
2025-02-27 17:50:16.716624 | INFO     | AssetNotifier        | Load assets: 1612ms |
2025-02-27 17:50:16.716541 | INFO     | AlbumService         | Syncing completed. Changes: false |
2025-02-27 17:50:16.175304 | INFO     | AlbumService         | Found 24 device albums |
2025-02-27 17:50:16.160240 | INFO     | BackupNotifier       | Found 24 local albums |
2025-02-27 17:50:15.107645 | INFO     | BackupNotifier       | [_resumeBackup] Start back up |
2025-02-27 17:50:15.106423 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Bad state: No element |
#0      ListBase.firstWhere (dart:collection/list.dart:132)
#1      IsarStoreRepository._toUpdateEvent (package:immich_mobile/infrastructure/repositories/store.repository.dart:68)
#2      IsarStoreRepository.watchAll.<anonymous closure>.<anonymous closure> (package:immich_mobile/infrastructure/repositories/store.repository.dart:26)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      new Stream.fromFutures (dart:async/stream.dart:317)
#6      IsarStoreRepository.watchAll.<anonymous closure> (package:immich_mobile/infrastructure/repositories/store.repository.dart:26)
#7      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:858)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#12     _StreamController._add (dart:async/stream_controller.dart:658)
#13     _StreamController.add (dart:async/stream_controller.dart:606)
#14     Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart:797)
<asynchronous suspension>
#15     _BufferingStreamSubscription.resume (dart:async/stream_impl.dart:200)
<asynchronous suspension>

2025-02-27 17:50:14.888583 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | Bad state: No element |
#0      ListBase.firstWhere (dart:collection/list.dart:132)
#1      IsarStoreRepository._toUpdateEvent (package:immich_mobile/infrastructure/repositories/store.repository.dart:68)
#2      IsarStoreRepository.watchAll.<anonymous closure>.<anonymous closure> (package:immich_mobile/infrastructure/repositories/store.repository.dart:26)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      new Stream.fromFutures (dart:async/stream.dart:317)
#6      IsarStoreRepository.watchAll.<anonymous closure> (package:immich_mobile/infrastructure/repositories/store.repository.dart:26)
#7      Stream.asyncExpand.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:858)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:365)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:297)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784)
#12     _StreamController._add (dart:async/stream_controller.dart:658)
#13     _StreamController.add (dart:async/stream_controller.dart:606)
#14     Stream.asyncMap.<anonymous closure>.add (dart:async/stream.dart:797)
<asynchronous suspension>
#15     _BufferingStreamSubscription.resume (dart:async/stream_impl.dart:200)
<asynchronous suspension>
```
