### DISCUSSION TITLE
[immich-server] Error: connect ETIMEDOUT

### DISCUSSION THREAD

**Discussion by r10r** [immich-app/immich#16607] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi, 

I'm trying to install immich with `podman-compose`. 
Currently only the **container_name** is resolved  so I  tried to set redis and database hostname
in the environment file *.env*

```
# only the container name is resolved when using `podman-compose`, not the hostname
REDIS_HOSTNAME=immich_redis
DB_HOSTNAME=immich_postgres
```

I've added an additional container to the pod to test the redis connection with `redis-cli` and the database connection with `pgsql`

```
  immich_test:
    container_name: immich_test
    image: docker.io/library/alpine:latest
    command: sleep 3600
    restart: always
    env_file:
      - .env
``` 

Connection tests are working fine from this container

```
# podman exec -it immich_test /bin/sh
/ # apk add postgresql-client redis
/ # psql -h $DB_HOSTNAME immich postgres
Password for user postgres: 
psql (16.8, server 14.10 (Debian 14.10-1.pgdg120+1))
Type "help" for help.

immich=# 
immich=# \q
/ # redis-cli -h $REDIS_HOSTNAME
immich_redis:6379> 
```

But the immich-server container fails to connect.

```
[immich-server]           | [Nest] 18  - 03/05/2025, 11:51:33 AM     LOG [Api:EventRepository] Initialized websocket server
[immich-server]           | Error: connect ETIMEDOUT
[immich-server]           |     at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
[immich-server]           |     at Object.onceWrapper (node:events:638:28)
[immich-server]           |     at Socket.emit (node:events:524:28)
[immich-server]           |     at Socket._onTimeout (node:net:609:8)
[immich-server]           |     at listOnTimeout (node:internal/timers:594:17)
[immich-server]           |     at process.processTimers (node:internal/timers:529:7) {
[immich-server]           |   errorno: 'ETIMEDOUT',
[immich-server]           |   code: 'ETIMEDOUT',
[immich-server]           |   syscall: 'connect'
[immich-server]           | }
[immich-server]           | Error: Connection terminated due to connection timeout
[immich-server]           |     at Client._connectionCallback (/usr/src/app/node_modules/pg-pool/index.js:247:17)
[immich-server]           |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:144:18)
[immich-server]           |     at Object.onceWrapper (node:events:638:28)
[immich-server]           |     ... 3 lines matching cause stack trace ...
[immich-server]           |     at TCP.<anonymous> (node:net:351:12) {
[immich-server]           |   [cause]: Error: Connection terminated unexpectedly
[immich-server]           |       at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
[immich-server]           |       at Object.onceWrapper (node:events:638:28)
[immich-server]           |       at Connection.emit (node:events:524:28)
[immich-server]           |       at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
[immich-server]           |       at Socket.emit (node:events:524:28)
[immich-server]           |       at TCP.<anonymous> (node:net:351:12)
[immich-server]           | }
[immich-server]           | microservices worker error: Error: Connection terminated due to connection timeout, stack: Error: Connection terminated due to connection timeout
[immich-server]           |     at Client._connectionCallback (/usr/src/app/node_modules/pg-pool/index.js:247:17)
[immich-server]           |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:144:18)
[immich-server]           |     at Object.onceWrapper (node:events:638:28)
[immich-server]           |     at Connection.emit (node:events:524:28)
[immich-server]           |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
[immich-server]           |     at Socket.emit (node:events:524:28)
[immich-server]           |     at TCP.<anonymous> (node:net:351:12)
[immich-server]           | microservices worker exited with code 1
[immich-server]           | Killing api process
```

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
        # networks:
        #- default
        #- srv

  immich_test:
    container_name: immich_test
    image: docker.io/library/alpine:latest
    command: sleep 3600
    restart: always
    env_file:
      - .env

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
        #networks:
        # - default

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
      #networks:
      #- default

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
      #networks:
      #- default
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.128.0
#IMMICH_VERSION=v1.127.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

LOG_LEVEL=debug

# only the container name is resolved when using `podman-compose`, not the hostname
REDIS_HOSTNAME=immich_redis
DB_HOSTNAME=immich_postgres
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
