### DISCUSSION TITLE
Immich Causing Whole Docker Stack to Crash

### DISCUSSION THREAD

**Discussion by Altycoder** [immich-app/immich#16648] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On the last 2 occasions of updating Immich, it has caused my whole docker stack to crash.

I have just tried updating from 128.0 to 129.0 and I got the same issue as when trying to upgrade from 127.0 to 128.0.

I change the version number in my .env file, stop my Immich stack, remove all the containers, then bring them back up and I get the following:

```
[neil@nas ~]$ cd /mnt/btrfs_raid2/docker/compose/immich/
[neil@nas immich]$ docker compose stop
[+] Stopping 5/5
 ✔ Container immich_machine_learning  Stopped                                                                                                           0.4s
 ✔ Container immich_server            Stopped                                                                                                           0.5s
 ✔ Container immich_db_dumper         Stopped                                                                                                           0.3s
 ✔ Container immich_redis             Stopped                                                                                                           0.3s
 ✔ Container immich_postgres          Stopped                                                                                                           1.8s
[neil@nas immich]$ docker compose rm -f
Going to remove immich_server, immich_db_dumper, immich_postgres, immich_machine_learning, immich_redis
[+] Removing 5/5
 ✔ Container immich_redis             Removed                                                                                                           0.0s
 ✔ Container immich_db_dumper         Removed                                                                                                           0.0s
 ✔ Container immich_machine_learning  Removed                                                                                                           0.0s
 ✔ Container immich_postgres          Removed                                                                                                           0.0s
 ✔ Container immich_server            Removed                                                                                                           0.0s
[neil@nas immich]$ docker compose up -d
[+] Running 33/37
 ⠦ immich-machine-learning [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 262.8MB / 262.8MB Pulling                                                                                     12.7s
   ✔ 7cf63256a31a Pull complete                                                                                                                         1.8s
   ✔ 183f0922284a Pull complete                                                                                                                         2.1s
   ✔ 5dbb3b698b72 Pull complete                                                                                                                         2.6s
   ✔ 0c5ce2cb4ecc Pull complete                                                                                                                         2.6s
   ✔ 5efa444321ca Pull complete                                                                                                                         2.7s
   ✔ acdd21a85373 Pull complete                                                                                                                         2.7s
   ✔ 46f1101cdf59 Pull complete                                                                                                                         2.7s
   ✔ b0edd876f623 Pull complete                                                                                                                        10.6s
   ✔ 81ded11e5262 Pull complete                                                                                                                        10.7s
   ⠙ cca3d0bf6fa2 Extracting      [==================================================>]  1.002kB/1.002kB                                               11.8s
   ✔ c47c43dcbd21 Download complete                                                                                                                     1.3s
 ⠦ immich-server [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 164.9MB / 170.3MB Pulling                                                                                  12.7s
   ✔ c29f5b76f736 Already exists                                                                                                                        0.0s
   ✔ 5bd7a8bc8b2a Already exists                                                                                                                        0.0s
   ✔ 3db87391745f Already exists                                                                                                                        0.0s
   ✔ f83bd266acdb Already exists                                                                                                                        0.0s
   ✔ 506c1d361a32 Already exists                                                                                                                        0.0s
   ✔ 3c7f29e705a2 Already exists                                                                                                                        0.0s
   ✔ 980d317ec8db Already exists                                                                                                                        0.0s
   ✔ 15988c723d00 Already exists                                                                                                                        0.0s
   ✔ 3509f73b1292 Already exists                                                                                                                        0.0s
   ✔ 8669eddf062e Already exists                                                                                                                        0.0s
   ✔ 7558eb359add Already exists                                                                                                                        0.0s
   ✔ e1464afc9c63 Already exists                                                                                                                        0.0s
   ✔ 4f4fb700ef54 Already exists                                                                                                                        0.0s
   ⠴ c95d4baaa354 Extracting      [==============================================>    ]  143.2MB/154.9MB                                               11.7s
   ✔ 7aa1a96aeb94 Download complete                                                                                                                     1.5s
   ✔ 40e428d6837f Download complete                                                                                                                     1.8s
   ✔ 1fcddc9900ac Download complete                                                                                                                     2.3s
   ✔ aa817f90fce7 Download complete                                                                                                                     2.5s
   ✔ 54e75e48cc65 Download complete                                                                                                                     2.8s
   ✔ cd69bdbc35a9 Download complete                                                                                                                     3.0s
   ✔ 7459d750e37d Download complete                                                                                                                     3.2s
   ✔ 3b847f991115 Download complete                                                                                                                     3.5s
   ✔ 183f2c810b77 Download complete                                                                                                                     3.7s
   ✔ ce94705b5bf4 Download complete                                                                                                                     3.9s
unexpected EOF
exit status 1
```

### The OS that Immich Server is running on

Arch LTS Kernel 6.12.x

### Version of Immich Server

v128.0 (trying to upgrade to 129)

### Version of Immich Mobile App

v128.0 but not relevant to this bug

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    networks:
      - immich
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    networks:
      - immich
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    networks:
      - immich
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

#https://immich.app/docs/administration/backup-and-restore/
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily" #once a day at midnight
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    networks:
      - immich
    volumes:
      - /mnt/btrfs_raid2/Backup/Backups/immich_db:/db_dumps
    depends_on:
      - database

networks: #should be created automatically
  immich:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  model-cache:
```

### Your .env content

```Shell
DOCKER_DIR=/mnt/btrfs_raid2/docker

PUID=1000
PGID=1000
UMASK=002

TZ=Europe/London

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/btrfs_raid2/docker/immich/upload #/mnt/btrfs_raid/Backup/Photos/immich

#postgres db location
DB_DATA_LOCATION=/mnt/btrfs_raid2/docker/immich/db

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.129.0 #v1.128.0 #release

# Connection secrets for postgres and typesense. You should change these to random passwords
#TYPESENSE_API_KEY=<redacted>
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
#DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
#REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. cd to immich compose folder
2. update version in .env file to v1.129.0 from v1.128.0 (or from 127 to 128)
3. docker compose stop
4. docker compose rm -f
5. docker compose up -d
6. docker crashes bringing down not just my immich stack but 2 other stacks as well.  This never happened before v1.127

### Relevant log output

```shell
No log output as immich isn't running but shell output:


[neil@nas ~]$ cd /mnt/btrfs_raid2/docker/compose/immich/
[neil@nas immich]$ docker compose stop
[+] Stopping 5/5
 ✔ Container immich_machine_learning  Stopped                                                                                                           0.4s
 ✔ Container immich_server            Stopped                                                                                                           0.5s
 ✔ Container immich_db_dumper         Stopped                                                                                                           0.3s
 ✔ Container immich_redis             Stopped                                                                                                           0.3s
 ✔ Container immich_postgres          Stopped                                                                                                           1.8s
[neil@nas immich]$ docker compose rm -f
Going to remove immich_server, immich_db_dumper, immich_postgres, immich_machine_learning, immich_redis
[+] Removing 5/5
 ✔ Container immich_redis             Removed                                                                                                           0.0s
 ✔ Container immich_db_dumper         Removed                                                                                                           0.0s
 ✔ Container immich_machine_learning  Removed                                                                                                           0.0s
 ✔ Container immich_postgres          Removed                                                                                                           0.0s
 ✔ Container immich_server            Removed                                                                                                           0.0s
[neil@nas immich]$ docker compose up -d
[+] Running 33/37
 ⠦ immich-machine-learning [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 262.8MB / 262.8MB Pulling                                                                                     12.7s
   ✔ 7cf63256a31a Pull complete                                                                                                                         1.8s
   ✔ 183f0922284a Pull complete                                                                                                                         2.1s
   ✔ 5dbb3b698b72 Pull complete                                                                                                                         2.6s
   ✔ 0c5ce2cb4ecc Pull complete                                                                                                                         2.6s
   ✔ 5efa444321ca Pull complete                                                                                                                         2.7s
   ✔ acdd21a85373 Pull complete                                                                                                                         2.7s
   ✔ 46f1101cdf59 Pull complete                                                                                                                         2.7s
   ✔ b0edd876f623 Pull complete                                                                                                                        10.6s
   ✔ 81ded11e5262 Pull complete                                                                                                                        10.7s
   ⠙ cca3d0bf6fa2 Extracting      [==================================================>]  1.002kB/1.002kB                                               11.8s
   ✔ c47c43dcbd21 Download complete                                                                                                                     1.3s
 ⠦ immich-server [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿] 164.9MB / 170.3MB Pulling                                                                                  12.7s
   ✔ c29f5b76f736 Already exists                                                                                                                        0.0s
   ✔ 5bd7a8bc8b2a Already exists                                                                                                                        0.0s
   ✔ 3db87391745f Already exists                                                                                                                        0.0s
   ✔ f83bd266acdb Already exists                                                                                                                        0.0s
   ✔ 506c1d361a32 Already exists                                                                                                                        0.0s
   ✔ 3c7f29e705a2 Already exists                                                                                                                        0.0s
   ✔ 980d317ec8db Already exists                                                                                                                        0.0s
   ✔ 15988c723d00 Already exists                                                                                                                        0.0s
   ✔ 3509f73b1292 Already exists                                                                                                                        0.0s
   ✔ 8669eddf062e Already exists                                                                                                                        0.0s
   ✔ 7558eb359add Already exists                                                                                                                        0.0s
   ✔ e1464afc9c63 Already exists                                                                                                                        0.0s
   ✔ 4f4fb700ef54 Already exists                                                                                                                        0.0s
   ⠴ c95d4baaa354 Extracting      [==============================================>    ]  143.2MB/154.9MB                                               11.7s
   ✔ 7aa1a96aeb94 Download complete                                                                                                                     1.5s
   ✔ 40e428d6837f Download complete                                                                                                                     1.8s
   ✔ 1fcddc9900ac Download complete                                                                                                                     2.3s
   ✔ aa817f90fce7 Download complete                                                                                                                     2.5s
   ✔ 54e75e48cc65 Download complete                                                                                                                     2.8s
   ✔ cd69bdbc35a9 Download complete                                                                                                                     3.0s
   ✔ 7459d750e37d Download complete                                                                                                                     3.2s
   ✔ 3b847f991115 Download complete                                                                                                                     3.5s
   ✔ 183f2c810b77 Download complete                                                                                                                     3.7s
   ✔ ce94705b5bf4 Download complete                                                                                                                     3.9s
unexpected EOF
exit status 1
```

**Comment by Altycoder** [comment]
If I remove all the 128 images and run 'docker compose pull' I get the same EOF error when it's trying to pull the immich-server image.

If I then run 'docker compose pull' a second time it pulls the server image successfully.

However when I bring up the Immich stack via 'docker compose up -d' all my other containers crash again.

**Comment by Altycoder** [comment]
I have now updated my docker compose to the following after comparing to the documentation on here in case I missed any breaking changes in the release notes.  

I then took down my Immich stack, deleted the containers and images, the Immich network and any volumes, then restarted the docker daemon.

This hasn't made a difference and when pulling the immich-server container I still get the following error which causes my whole docker setup to crash.

```
⠇ immich-server [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]   658MB / 658MB   Pulling                                                                                  45.9s
   ✔ c29f5b76f736 Already exists                                                                                                                        0.0s
   ✔ 5bd7a8bc8b2a Pull complete                                                                                                                         0.3s
   ✔ 3db87391745f Pull complete                                                                                                                         3.7s
   ✔ f83bd266acdb Pull complete                                                                                                                         3.8s
   ✔ 506c1d361a32 Pull complete                                                                                                                         3.8s
   ✔ 3c7f29e705a2 Pull complete                                                                                                                         3.9s
   ✔ 980d317ec8db Pull complete                                                                                                                         3.9s
   ✔ 15988c723d00 Pull complete                                                                                                                        26.0s
   ✔ 3509f73b1292 Pull complete                                                                                                                        27.7s
   ✔ 8669eddf062e Pull complete                                                                                                                        28.5s
   ✔ 7558eb359add Pull complete                                                                                                                        28.5s
   ✔ e1464afc9c63 Pull complete                                                                                                                        28.6s
   ✔ 4f4fb700ef54 Pull complete                                                                                                                        28.6s
   ✔ c95d4baaa354 Pull complete                                                                                                                        42.9s
   ✔ 7aa1a96aeb94 Pull complete                                                                                                                        43.1s
   ✔ 40e428d6837f Pull complete                                                                                                                        43.2s
   ✔ 1fcddc9900ac Pull complete                                                                                                                        43.9s
   ✔ aa817f90fce7 Pull complete                                                                                                                        43.9s
   ✔ 54e75e48cc65 Pull complete                                                                                                                        44.0s
   ✔ cd69bdbc35a9 Pull complete                                                                                                                        44.0s
   ✔ 7459d750e37d Pull complete                                                                                                                        44.0s
   ✔ 3b847f991115 Pull complete                                                                                                                        44.3s
   ⠸ 183f2c810b77 Extracting  [==================================================>]  11.15kB/11.15kB                                                   45.4s
   ✔ ce94705b5bf4 Download complete                                                                                                                     5.3s
 ✔ redis Pulled                                                                                                                                        16.3s
   ✔ f18232174bc9 Already exists                                                                                                                        0.0s
   ✔ f46bfab96088 Pull complete                                                                                                                        14.3s
   ✔ 985b7b1332d5 Pull complete                                                                                                                        14.6s
   ✔ eb572f6e61e7 Pull complete                                                                                                                        14.6s
   ✔ ea791409802b Pull complete                                                                                                                        14.9s
   ✔ 7e2382db4737 Pull complete                                                                                                                        14.9s
   ✔ 74f6c688f24f Pull complete                                                                                                                        15.0s
unexpected EOF
exit status 1
```

My updated docker compose:

```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    networks:
      - immich
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - immich
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1    
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: always
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

#https://immich.app/docs/administration/backup-and-restore/
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    user: postgres:postgres
    
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_CLUSTER='TRUE'
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - SCHEDULE="@daily" #once a day at midnight
      #- POSTGRES_EXTRA_OPTS='--clean --if-exists'
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - BACKUP_DIR=/db_dumps
    networks:
      - immich
    volumes:
      - /mnt/btrfs_raid2/Backup/Backups/immich_db:/db_dumps
    depends_on:
      - database
    links:
      - database

networks:
  immich:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1

volumes:
  model-cache:
```
