### DISCUSSION TITLE
Can't upgrade  Immich Server beyond v1.127.0

### DISCUSSION THREAD

**Discussion by jarneson33** [immich-app/immich#16717] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello,

I have been running immich in portainer almost since the beginning of immich, and applying updates as they have been released.  I'm currently running 1.127.0, and its solid.  I have tried to update to 1.128.0 and 1.129.0, and every time the immich_server service keeps failing.  It starts and stops.  I can rollback to 1.127.0 and 1.126.1 with no issues, but 1.128.0 and 1.129.0 produce the same error.

### The OS that Immich Server is running on

Fedora 40

### Version of Immich Server

1.128.0 || 1.129.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - REDIS_HOSTNAME=immich_redis
    networks: 
      - overlay_default
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - immich_redis
      - immich_postgres

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /dev/shm:/cache
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_default

  immich_redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_default

  immich_postgres:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - overlay_default
    
networks:
  overlay_default:
    external: true
```

### Your .env content

```Shell
Likely not relevant
```

### Reproduction steps

1.Log into portainer, re-pull image to update
2.Once the update completes all services start, except the the immich_server service.  It starts and stops.
...

### Relevant log output

```shell
Initializing Immich v1.128.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 03/07/2025, 11:45:06 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 03/07/2025, 11:45:06 PM     LOG [Api:EventRepository] Initialized websocket server
Migration "AddUpdateIdColumns1740586617223" failed, error: could not read block 1602 in file "base/16384/429394": read only 0 of 8192 bytes
QueryFailedError: could not read block 1602 in file "base/16384/429394": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
    at async /usr/src/app/dist/services/database.service.js:96:17
    at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
  query: 'UPDATE "asset_files" SET "updateId" = immich_uuid_v7("updatedAt")',
  parameters: undefined,
  driverError: error: could not read block 1602 in file "base/16384/429394": read only 0 of 8192 bytes
      at /usr/src/app/node_modules/pg/lib/client.js:535:17
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
      at async /usr/src/app/dist/services/database.service.js:96:17
      at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
    length: 127,
    severity: 'ERROR',
    code: 'XX001',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'md.c',
    line: '685',
    routine: 'mdread'
  },
  length: 127,
  severity: 'ERROR',
  code: 'XX001',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'md.c',
  line: '685',
  routine: 'mdread'
}
microservices worker error: QueryFailedError: could not read block 1602 in file "base/16384/429394": read only 0 of 8192 bytes, stack: QueryFailedError: could not read block 1602 in file "base/16384/429394": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
    at async /usr/src/app/dist/services/database.service.js:96:17
    at async /usr/src/app/dist/repositories/database.repository.js:211:23
microservices worker exited with code 1
Killing api process
```

### Additional information

I saw this issue was created and closed with the exact same issue.
https://github.com/immich-app/immich/issues/16506
 @bo0tzz closed it and said it was a DB corruption issue, but I find it odd the server continues to work as expected during rollback and everything operates as expected. Also just could be a strange coincidence both our DB's corrupted with v1.128.0, but I just want to be sure this is a DB corruption issue for sure before I go through the work of rolling back.

Thank you.
