### DISCUSSION TITLE
Crash on "missing thumbnails" job

### DISCUSSION THREAD

**Discussion by radqnico** [immich-app/immich#16936] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Mi immich instance crashes violently and without much verbosity when it tries to generate thumbnails or i do it manually. No weird video or picture was uploaded. This is preventing me from using it at all!

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.129.0

### Version of Immich Mobile App

1.129.0 build 187

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
secrets:
  JWT_SECRET:
    file: './authelia/secrets/JWT_SECRET'
  SESSION_SECRET:
    file: './authelia/secrets/SESSION_SECRET'
  STORAGE_PASSWORD:
    file: './authelia/secrets/STORAGE_PASSWORD'
  STORAGE_ENCRYPTION_KEY:
    file: './authelia/secrets/STORAGE_ENCRYPTION_KEY'


services:
  autoheal:
    restart: "unless-stopped"
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: alta
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - /mnt/nas/files:/files:ro  # Mount local paths to backup
      - /root/domotica/immich:/immich_db:ro  # Mount local paths to backup
      - /mnt/nas/immich:/immich_data:ro  # Mount local paths to backup
      - /mnt/nas/users:/users:ro  # Mount local paths to backup
      - /mnt/nas/backups:/backups
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Rome
    restart: unless-stopped

  traefik:
    image: traefik # The official v3 Traefik docker image
    container_name: "traefik"
    restart: "unless-stopped"
    depends_on:
      authelia:
        condition: service_healthy
    environment:
      - TZ=Europe/Rome
    ports:
      - 80:80 # HTTP entryPoints
      - 443:443 # HTTPS entryPoints
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket to watch for Traefik
      - ./traefik/traefik.yml:/traefik.yml:ro # Traefik config file
      - ./traefik/providers:/providers:ro # Traefik config file
      - ./traefik/certs:/certs # Docker volume to store the acme file for the Certifactes

  authelia:
    container_name: "authelia"
    image: "docker.io/authelia/authelia:latest"
    restart: "unless-stopped"
    secrets: ['JWT_SECRET', 'SESSION_SECRET', 'STORAGE_PASSWORD', 'STORAGE_ENCRYPTION_KEY']
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/SESSION_SECRET'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/STORAGE_ENCRYPTION_KEY'
    volumes:
      - './authelia/config:/config:ro'
      - './authelia/db:/db:rw'
    labels:
      ## Expose Authelia through Traefik
      traefik.enable: 'true'
      traefik.docker.network: 'authelia'

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: "unless-stopped"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: "unless-stopped"
    depends_on:
      - mosquitto
    volumes:
        - ./zigbee2mqtt:/app/data
        - /run/udev:/run/udev:ro
    environment:
        - TZ=Europe/Rome
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_40205fe63bb6ed1195e6d80ea8669f5d-if00-port0

  homeassistant:
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/Rome
    restart: "unless-stopped"
    depends_on:
      - traefik
      - zigbee2mqtt

  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - ./homer:/www/assets # Make sure your local config directory exists
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default, requires the config directory to be writable for the container user (see user option)
    restart: "unless-stopped"


  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/nas/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-database
      DB_USERNAME: immich
      DB_PASSWORD: immich
      TZ: Europe/Rome
      IMMICH_PROCESS_INVALID_IMAGES: true
      IMMICH_LOG_LEVEL: verbose
    depends_on:
      - immich-redis
      - immich-database
      - immich-machine-learning
    restart: "unless-stopped"
    ports:
      - 2283:2283
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          memory: 2048M

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: "unless-stopped"
    devices:
      - /dev/dri:/dev/dri

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: "unless-stopped"

  immich-database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: immich
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ./immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: "unless-stopped"

  immich-samba:
    container_name: immich-samba
    image: dockurr/samba
    environment:
      NAME: "NAS"
      USER: "scialpi"
      PASS: "ScendeLaNotte1!"
    volumes:
      - /mnt/nas/immich/library:/storage:ro
    ports:
      - 445:445
    restart: "unless-stopped"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - ./portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "unless-stopped"

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: "unless-stopped"
    volumes:
      - /mnt/nas:/srv
      - ./filebrowser/filebrowser.db:/database.db
      - ./filebrowser/filebrowser.json:/.filebrowser.json

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 3000:3000/tcp # initial setup web interface
    volumes:
      - ./adguard/conf:/opt/adguardhome/conf # app configuration
      - ./adguard/work:/opt/adguardhome/work # app working directory

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com   # Replace with your email
  #     PGADMIN_DEFAULT_PASSWORD: admin            # Replace with a secure password
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   restart: "unless-stopped"



volumes:
  model-cache:
  pgadmin-data:
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Upload 7k+ photos and it will happen eventually.
2.
3.
...

### Relevant log output

```shell
immich-server  | [Nest] 17  - 03/17/2025, 10:46:22 PM   DEBUG [Api:LoggingInterceptor~js3zvvku] GET /api/jobs 200 77.95ms 192.168.1.1
immich-server  | [Nest] 17  - 03/17/2025, 10:46:22 PM   DEBUG [Api:LoggingInterceptor~mythr53m] GET /api/jobs 200 39.87ms 192.168.1.1
immich-server  | [Nest] 17  - 03/17/2025, 10:46:23 PM   DEBUG [Api:JobService~2ektts06] Handling command: queue=thumbnailGeneration,command=start,force=false
immich-server  | [Nest] 17  - 03/17/2025, 10:46:23 PM   DEBUG [Api:LoggingInterceptor~2ektts06] PUT /api/jobs/thumbnailGeneration 200 25.20ms 192.168.1.1
immich-server  | [Nest] 17  - 03/17/2025, 10:46:23 PM VERBOSE [Api:LoggingInterceptor~2ektts06] {"command":"start","force":false}
immich-server  | [Nest] 7  - 03/17/2025, 10:46:23 PM   ERROR [Microservices:{"id":"af1e46df-5ae0-429b-a357-68405a781107"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
immich-server  | Error: Input file contains unsupported image format
immich-server  |     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
immich-server  |     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
immich-server  |     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
immich-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich-server  |     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
immich-server  |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich-server  |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich-server  |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich-server  |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich-server  | [Nest] 17  - 03/17/2025, 10:46:26 PM   DEBUG [Api:LoggingInterceptor~t5p6papp] GET /api/server/ping 200 1.34ms ::ffff:127.0.0.1
immich-server  | [Nest] 17  - 03/17/2025, 10:46:27 PM   DEBUG [Api:LoggingInterceptor~c4tetjc9] GET /api/jobs 200 38.92ms 192.168.1.1
immich-server  | [Nest] 17  - 03/17/2025, 10:46:35 PM   DEBUG [Api:LoggingInterceptor~g2ak8nuh] GET /api/jobs 200 2458.45ms 192.168.1.1
immich-server exited with code 0
```
