### DISCUSSION TITLE
Jobs not running - TypeError: Cannot read properties of undefined (reading 'replaceAll')

### DISCUSSION THREAD

**Discussion by RestartB** [immich-app/immich#16937] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello! I recently created a new instance of Immich using Docker Compose. I've uploaded some media from my phone. however I can see that if I go to jobs, it's gotten stuck. I can also see in the logs a lot of errors that are either the same or look very similar. I've added an example in the logs section.

Here's a screenshot showing the stuck jobs:

![Image](https://github.com/user-attachments/assets/d5f3197b-e198-4923-84b7-5a74c0237972)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-https.tls=true
      - traefik.http.routers.immich-https.tls.certresolver=cloudflare
      - traefik.http.routers.immich-https.entrypoints=websecure
      - traefik.http.routers.immich-https.rule=Host(`censored`)
      - traefik.http.services.immich-https.loadbalancer.server.port=2283
    networks:
      - traefik
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - traefik
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - traefik
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      - traefik

volumes:
  model-cache:

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich/library
DB_DATA_LOCATION=/mnt/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=censored
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload some media
2. Go to the jobs page and the Docker logs
3. See the jobs get stuck and errors appear in the Docker logs

### Relevant log output

```shell
[Nest] 7  - 03/17/2025, 9:02:27 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 03/17/2025, 9:02:27 PM   ERROR [Microservices:{}] Unable to run job handler (metadataExtraction/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:154:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 207. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

**Comment by alextran1502** [comment]
Hello, did you change the job concurrency by chance?

**Reply by RestartB** [reply]
Hello! No, the only settings I changed were enabling the storage template, enabling OAuth and disabling password login.

**Reply by Bo0sted** [reply]
Hello! Have you had any success fixing this issue?

**Reply by RestartB** [reply]
@Bo0sted Unfortunately not, I went back to using my old instance that works and upgraded it to the latest version. Works fine, so not really sure what was wrong with the broken instance.

**Comment by Bo0sted** [comment]
Hi, I'm also having this issue.  No changes. Started happening randomly in my view. 

```
[Nest] 7  - 03/27/2025, 7:03:07 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -skip_frame nointra -sws_flags accurate_rnd+full_chroma_int -i upload/upload/87641885-a342-4d0d-9734-a7195bcae9b6/2f/72/2f72dae1-8e5c-4b4b-9ad8-ccba30a63407.mp4 -y -fps_mode vfr -frames:v 1 -update 1 -v verbose -vf fps=12:eof_action=pass:round=down,thumbnail=12,select=gt(scene\,0.1)-eq(prev_selected_n\,n)+isnan(prev_selected_n)+gt(n\,20),trim=end_frame=2,reverse,scale=-2:250:flags=lanczos+accurate_rnd+full_chroma_int:out_range=pc upload/thumbs/87641885-a342-4d0d-9734-a7195bcae9b6/8c/f4/8cf4a1d7-bacf-4c0e-af5c-63cffcf6ba39-thumbnail.webp

[Nest] 7  - 03/27/2025, 7:03:10 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"

[Nest] 7  - 03/27/2025, 7:03:10 PM   ERROR [Microservices:{}] Unable to run job handler (videoConversion/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')

TypeError: Cannot read properties of undefined (reading 'replaceAll')

    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)

    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)

    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

Error: Missing lock for job 2. failed

    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)

    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)

    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

My config file:
```
name: immich
services:
  immich-server:
    user: 1000:100
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.130.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`x`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=cloudflare"
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: rkmpp # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:${DOCKER_IMMICH_LOCATION}
      #According to docs, all other subfolders will be based on this folder so no need to specify any others
      - /srv/dev-disk-by-uuid-b04015b7-f18d-4e7a-bd87-92d39b6e772f/photoprism/originals:/external_library
      - /srv/dev-disk-by-uuid-b04015b7-f18d-4e7a-bd87-92d39b6e772f/google_photos:/external_library2
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - frontend
    environment:
      IMMICH_LOG_LEVEL: verbose
    # environment:
    #   - IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicabl
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - frontend

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - frontend

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - frontend

volumes:
  model-cache:

networks:
  frontend:
    external: true

```
**Observed behavior**
- Immich fails to auto-generate thumbnails for newly uploaded media
- Thumbnails jobs are queued up as indicated by the "Waiting" column but never progress to generation
- Manually refreshing thumbnail via context menu seems to fix the thumbanil

**Steps to reproduce**
- Upload something
- Notice that thumbnail shows error
