### DISCUSSION TITLE
Microservices keep crashing

### DISCUSSION THREAD

**Discussion by klejejs** [immich-app/immich#16943] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have noticed that microservices are restarting when large libraries are being scanned, or some jobs are running. As there is nothing definitive in logs, I have no clue how to debug this or figure out where the issue is originating from.
I thought it might be an issue running out of memory on server or ML, but CPU and memory usage is not high during the crash.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
networks:
  docker_local_server:
    external: true

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${LOCATION_UPLOAD}:/usr/src/app/upload/upload
      - ${LOCATION_THUMBS}:/usr/src/app/upload/thumbs
      - ${LOCATION_ENCODED_VIDEO}:/usr/src/app/upload/encoded-video
      - ${LOCATION_PROFILE}:/usr/src/app/upload/profile
      # External libraries
      ...
      # Timezone
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    ports:
      - 2283:2283
      - 8081:8081
      - 8082:8082
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3000M
    networks:
      docker_local_server:
        ipv4_address: ...
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./data/machine-learning/cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3000M
    networks:
      docker_local_server:
        ipv4_address: ...
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    restart: unless-stopped
    networks:
      docker_local_server:
        ipv4_address: ...
    healthcheck:
      test: redis-cli ping || exit 1
    ports:
      - ....:6379

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - ....:5432
    restart: unless-stopped
    networks:
      docker_local_server:
        ipv4_address: ...
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
```

### Your .env content

```Shell
IMMICH_VERSION=v1.129.0

Other data seems irrelevant
```

### Reproduction steps

1. Start a job or library scan
2. Observe microservices crashing

### Relevant log output

```shell
microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')

    at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)

    at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)

    at connectTimedOut (/usr/src/app/node_modules/postgres/cjs/src/connection.js:257:5)

    at Timeout.done [as _onTimeout] (/usr/src/app/node_modules/postgres/cjs/src/connection.js:1033:8)

    at listOnTimeout (node:internal/timers:596:11)

    at process.processTimers (node:internal/timers:529:7)
```
