### DISCUSSION TITLE
Immich microservices container causes high cpu usage

### DISCUSSION THREAD

**Discussion by Bistekka6** [immich-app/immich#17001] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Up until since version 1.117.0 but i'm not sure, I've noticed higher then usual CPU usage by the vm which is running Immich, about double or triple in some case.
The immich microservices container seems to be the culprit.
The logs are filled with the output attached below

### The OS that Immich Server is running on

Debian 10

### Version of Immich Server

1.129.0

### Version of Immich Mobile App

1.129

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    #entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.entrypoints: "xxxxxxx"
      traefik.http.routers.immich.rule: "Host(`xxxxxxxxxx`)"
      traefik.http.routers.immich.tls: "true"
      traefik.http.routers.immich.tls.certresolver: "xxxxxxxx"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always


volumes:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=xxxxxxxx
DB_PASSWORD=xxxxxxxx
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/photos
TYPESENSE_API_KEY=xxxxxxxxxxxxx
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
DB_DATA_LOCATION=/docker/immich/pgdata
```

### Reproduction steps

1. start the containers

### Relevant log output

```shell
[Nest] 7  - 03/20/2025, 11:55:19 AM     LOG [ImmichMicroservices] [EventRepository] Initialized websocket server

QueryFailedError: relation "system_config" does not exist

    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)

    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)

    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)

    at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)

    at async SystemConfigCore.buildConfig (/usr/src/app/dist/cores/system-config.core.js:124:15)

    at async /usr/src/app/dist/cores/system-config.core.js:79:35 {

  query: 'SELECT "SystemConfigEntity"."key" AS "SystemConfigEntity_key", "SystemConfigEntity"."value" AS "SystemConfigEntity_value" FROM "system_config" "SystemConfigEntity"',

  parameters: [],

  driverError: error: relation "system_config" does not exist

      at /usr/src/app/node_modules/pg/lib/client.js:526:17

      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)

      at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)

      at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)

      at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)

      at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)

      at async SystemConfigCore.buildConfig (/usr/src/app/dist/cores/system-config.core.js:124:15)

      at async /usr/src/app/dist/cores/system-config.core.js:79:35 {

    length: 113,

    severity: 'ERROR',

    code: '42P01',

    detail: undefined,

    hint: undefined,

    position: '128',

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'parse_relation.c',

    line: '1381',

    routine: 'parserOpenTable'

  },

  length: 113,

  severity: 'ERROR',

  code: '42P01',

  detail: undefined,

  hint: undefined,

  position: '128',

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: undefined,

  table: undefined,

  column: undefined,

  dataType: undefined,

  constraint: undefined,

  file: 'parse_relation.c',

  line: '1381',

  routine: 'parserOpenTable'

}

Microservices worker exited with code 1
```
