### DISCUSSION TITLE
[Feature] Ability to disable certain tasks in machine learning containers

### DISCUSSION THREAD

**Discussion by sithmein** [immich-app/immich#17045] [Feature Request]
### I have searched the existing feature requests, both open and closed, to make sure this is not a duplicate request.

- [X] Yes

### The feature

Follow up on https://github.com/immich-app/immich/discussions/17029. It would be nice if the different machine learnings tasks - face recognition, image processing, smart search - had dedicated URLs. Then you can configure different container/hosts, e.g. face recognition and image processing on powerful on/off machines and smart search on always-on low performance systems.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by sithmein** [comment]
First attempt in splitting URLs into three different ones: https://github.com/sithmein/immich/tree/feat/machine-learning-dedicated-paths
![grafik](https://github.com/user-attachments/assets/4d89cd1d-989f-4ec2-8f45-609dc7a5c59b)

**Comment by mertalev** [comment]
Before you spend more time on this, I don't think this is a direction we should go in. Imagine that we add OCR, image quality assessment, pet recognition, etc. Juggling URLs for all of this is messy and adds complexity for what I imagine is a quite niche feature.

**Reply by sithmein** [reply]
But then you essentially rule out using immich on devices such as Raspberry Pis. Which would be a real pity.
Alternatively you can stick to a default URL and then you can optionally override the URLs for certain tasks. If you don't think it should be exposed in the UI then at least make it configurable via environment variables.

**Reply by mertalev** [reply]
> But then you essentially rule out using immich on devices such as Raspberry Pis.

I don't think this is a fair comment. There are many people using immich on a Raspberry Pi, either through offloading ML to another server, ensuring enough swap space, having an 8GB model or disabling machine learning.

There are also plenty of other approaches that would solve your issue without complicating configuration, like model quantization to reduce RAM usage.

**Reply by sithmein** [reply]
So you don't consider adding the possibility to route different ML tasks to different target at all? For example video transcoding has an "advanced" section where it is explicitly mentioned that most user won't have to touch it - and yet it exists. Therefore I don't think "niche feature" is a good argument to rule it out completely.

Even if this not interesting for the majority of users I still see potential, especially since the changes are minimal (it took me an hour to implement this, and I am not a JS developer). Are there any other variants of making this possible that you would accept?

**Reply by bo0tzz** [reply]
A loadbalancer/reverse proxy worth its salt can totally route on request body content, fwiw.

**Reply by sithmein** [reply]
Neither traefik nor ngix can do that (or I missed that part in their documentation).
But yes, if the URLs for the different requests would be different then using a reverse proxy would also be a way to make this work.

**Reply by mertalev** [reply]
> Are there any other variants of making this possible that you would accept?

If the ML service can reject certain tasks, then the server can move to the next URL until success using the existing fallback mechanism. I think this is a simpler way to get the same result.

**Reply by sithmein** [reply]
You mean a configuration (via environment variables) of the machine learning container which kind of requests (face, image, textual, ...) they are willing to accept? Sounds good to me. I can give it a try in the next few days.
Is there any specific HTTP status code that the service should return in order to reject a task or does anything != 200 work?

**Reply by mertalev** [reply]
Any non-200 code will achieve the same effect, but 422 would probably be the most appropriate.

**Reply by skatsubo** [reply]
> route on request body content

I did PoC with 3 reverse proxies (HAProxy, Nginx, OpenResty) to route requests based on the request body - https://github.com/skatsubo/request-body-reverse-proxy. It's just PoC and not extensively tested, but I can polish it if it might be of interest.

> if the URLs for the different requests would be different then using a reverse proxy would also be a way to make this work

Definitely different URLs would make reverse proxying easier and with better performance. I see it was done in https://github.com/sithmein/immich/commit/328004e0486e4145b498c6593a06ddd0ab67b836 (branch linked from the comment below https://github.com/immich-app/immich/discussions/17045#discussioncomment-12646102). Does it make sense to create a PR?

(Sorry, a bit late to the party. Hoping to revive the topic.)

**Reply by sithmein** [reply]
I am happy to create PRs (and a proper feature request) once there is agreement that this functionality will be included.

**Reply by mertalev** [reply]
If having separate endpoints for image and text is enough, then that alone would be the simplest solution. The current endpoint already only expects one or the other, so it's cleaner to separate them. There should be a single endpoint for images and a single endpoint for text, though, not separate endpoints for facial recognition, clip, etc.

**Reply by sithmein** [reply]
I deliberately created more endpoints because
- facial recognition needs the least resources, both in terms of memory and CPU
- clip needs both much memory and CPU resource
- text search need much memory but not many CPU resources

Being able to route these three types of requests to different targets is worthwile in my opinion (this is how I do it).

**Reply by mertalev** [reply]
A single endpoint is more powerful because it means several ML tasks can use the same image sent in the same request, which is faster, reduces IO and lowers memory usage. It's also more composable since a single model output can be shared between multiple ML models that rely on it instead of reprocessing the shared output. I'm not interested in changing that at the moment.

**Reply by sithmein** [reply]
Sorry, but I don't understand your argument. Since clip, textual, and facial recognition are three separate tasks that are triggered independently it doesn't make a difference whether its individual or combined endpoints. There are no combined requests as far as I can tell from the source code.

**Reply by mertalev** [reply]
There are none right now, but that can change in the future with later tasks. For example, pet recognition could share the same request as face recognition, along with image quality assessment run on each detected face. Using the same API, each of these tasks could be requested together or independently with options for each task's model and parameters. It's ultimately a more flexible design.

**Comment by sithmein** [comment]
https://github.com/sithmein/immich/tree/feat/machine-learning-disable-tasks contains an implementation of this feature. The machine learning container accepts a new environment variable `MACHINE_LEARNING_ENABLED_TASKS` which by default is `face,image,text`. By changing the value you can exclude certain tasks from getting accepted.
I decided to return 501 instead of 422 because it's not a client error if the server-side does not support some functionality.
In addition I added path suffixes for the different tasks which makes it easier for the new backoff functionality (which is buggy by the way, see https://github.com/immich-app/immich/issues/17185; the above branch contains fixes for the bug).
Let me know what you think and if there are suggestions for further improvements.

**Reply by aviv926** [reply]
I tried your code but there seems to be a bug?

immich-machine-learning_remote | [04/23/25 17:42:48] INFO **Enabled tasks: {"image", "text"}.**
immich-machine-learning_remote | [04/23/25 17:42:48] INFO Initialized request thread pool with 16 threads.
immich-machine-learning_remote | [04/23/25 17:42:48] DEBUG Checking for inactivity...
immich-machine-learning_remote | [04/23/25 17:42:48] INFO Application startup complete.
immich-machine-learning_remote | [04/23/25 17:42:56] DEBUG **Rejected text classification/smart search tasks**
immich-machine-learning_remote | **since it has been turned off by configuration.**

```
immich_server    | [Nest] 7  - 04/23/2025, 5:49:50 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://192.168.1.230:3003/predict/image" failed with status 404 (Not Found)
immich_server    | [Nest] 7  - 04/23/2025, 5:49:50 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://192.168.1.230:3003/predict/face" failed with status 404 (Not Found)
immich_server    | [Nest] 7  - 04/23/2025, 5:49:50 PM   ERROR [Microservices:{"id":"499ece43-25fa-49ba-9ca6-010c623b8ef1","source":"upload"}] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-SO400M-16-SigLIP2-384__webli"}}}' failed for all URLs
immich_server    | Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-SO400M-16-SigLIP2-384__webli"}}}' failed for all URLs
immich_server    |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:114:15)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:132:26)
immich_server    |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:103:27)
immich_server    |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
immich_server    |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server    |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server    |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server    | [Nest] 7  - 04/23/2025, 5:49:50 PM   ERROR [Microservices:{"id":"499ece43-25fa-49ba-9ca6-010c623b8ef1","source":"upload"}] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.6}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
```

![image](https://github.com/user-attachments/assets/afb9de16-0231-4c91-a1ef-22634f786cee)

**Reply by sithmein** [reply]
It seems you set the environment variable `MACHINE_LEARNING_ENABLED_TASKS` wrong. It should contain a comma-separated list of tasks names, e.g. `MACHINE_LEARNING_ENABLED_TASKS=image,text`. Judging from the output you passed something else (a JSON object?):

```
immich-machine-learning_remote | [04/23/25 17:42:48] INFO Enabled tasks: {"image", "text"}.
```
vs
```
[04/22/25 09:22:09] INFO     Enabled tasks: image, text.
```

**Reply by aviv926** [reply]
> It seems you set the environment variable `MACHINE_LEARNING_ENABLED_TASKS` wrong. It should contain a comma-separated list of tasks names, e.g. `MACHINE_LEARNING_ENABLED_TASKS=image,text`. Judging from the output you passed something else (a JSON object?):
> 
> ```
> immich-machine-learning_remote | [04/23/25 17:42:48] INFO Enabled tasks: {"image", "text"}.
> ```
> vs
> ```
> [04/22/25 09:22:09] INFO     Enabled tasks: image, text.
> ```

I also tried the way you wrote: 

`MACHINE_LEARNING_ENABLED_TASKS=image,text`

but without success. The error still appeared. Did it work for you? 
When I tried to run the code it indicated that there were some errors that were automatically corrected by the formatter

**Reply by sithmein** [reply]
I've been using my feature branch for several weeks by now without any problems. Are you sure you are using the latest version of https://github.com/sithmein/immich/tree/feat/machine-learning-disable-tasks?

**Reply by aviv926** [reply]
> I've been using my feature branch for several weeks by now without any problems. Are you sure you are using the latest version of https://github.com/sithmein/immich/tree/feat/machine-learning-disable-tasks?

Yes, and I just tried rebuilding the image again and pulling it, but it still doesn't work.

**immich-server:**
ghcr.io/aviv926/immich-server:pr-machine-learning-disable-tasks

**immich-machine-learning**
docker pull ghcr.io/aviv926/immich-machine-learning:pr-machine-learning-disable-tasks-cuda
docker pull ghcr.io/aviv926/immich-machine-learning:pr-machine-learning-disable-tasks

**Reply by sithmein** [reply]
Your images work perfectly fine for me:
```
CONTAINER ID   IMAGE                                                                            COMMAND                  CREATED         STATUS                   PORTS                                         NAMES
e6f9b79f5368   ghcr.io/aviv926/immich-machine-learning:pr-machine-learning-disable-tasks-cuda   "tini -- python -m i…"   3 minutes ago   Up 3 minutes (healthy)   0.0.0.0:3003->3003/tcp, [::]:3003->3003/tcp   immich-immich-machine-learning-cuda-1
```
```
[04/25/25 18:25:57] INFO     Starting gunicorn 23.0.0                           
[04/25/25 18:25:57] INFO     Listening at: http://[::]:3003 (8)                 
[04/25/25 18:25:57] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[04/25/25 18:25:57] INFO     Booting worker with pid: 9                         
[04/25/25 18:25:59] INFO     Started server process [9]                         
[04/25/25 18:25:59] INFO     Waiting for application startup.                   
[04/25/25 18:25:59] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/25/25 18:25:59] INFO     Enabled tasks: image, face.                        
[04/25/25 18:25:59] INFO     Initialized request thread pool with 2 threads.    
[04/25/25 18:25:59] INFO     Application startup complete.                      
[04/25/25 18:27:43] INFO     Loading detection model 'antelopev2' to memory     
[04/25/25 18:27:43] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[04/25/25 18:27:45] INFO     Loading visual model 'ViT-L-16-SigLIP2-512__webli' 
                             to memory                                          
[04/25/25 18:27:45] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[04/25/25 18:27:50] INFO     Loading recognition model 'antelopev2' to memory   
[04/25/25 18:27:50] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
```

Can you post the contents of your Docker compose file?

**Reply by aviv926** [reply]
The problem still exists for me, here is more information:

## docker compose file:
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/aviv926/immich-server:pr-machine-learning-disable-tasks

    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${MYLIB}:/usr/src/mnt/mylib

    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    ports:
      - "5432:5432"
volumes:
  model-cache:
```

## docker compose file immich remote ML:
```
name: immich_remote_ml

services:
  immich-machine-learning_remote:
    container_name: immich-machine-learning_remote
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/aviv926/immich-machine-learning:pr-machine-learning-disable-tasks-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    env_file:
      - .env
    ports:
      - 3099:3003

volumes:
  model-cache:
```

## ENV used for immich remote ML
```
IMMICH_LOG_LEVEL=verbose
MACHINE_LEARNING_ENABLED_TASKS=image, text
```

## Logs immich remote ML:
```
immich-machine-learning_remote  | [04/26/25 21:12:29] INFO     Starting gunicorn 23.0.0
immich-machine-learning_remote  | [04/26/25 21:12:29] INFO     Listening at: http://[::]:3003 (8)
immich-machine-learning_remote  | [04/26/25 21:12:29] INFO     Using worker: immich_ml.config.CustomUvicornWorker
immich-machine-learning_remote  | [04/26/25 21:12:29] INFO     Booting worker with pid: 9
immich-machine-learning_remote  | [04/26/25 21:12:30] DEBUG    Could not load ANN shared libraries, using ONNX:
immich-machine-learning_remote  |                              libmali.so: cannot open shared object file: No such
immich-machine-learning_remote  |                              file or directory
immich-machine-learning_remote  | [04/26/25 21:12:30] DEBUG    RKNN is not available
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Started server process [9]
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Waiting for application startup.
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Created in-memory cache with unloading after 300s
immich-machine-learning_remote  |                              of inactivity.
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Enabled tasks: image,  face.
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Initialized request thread pool with 16 threads.
immich-machine-learning_remote  | [04/26/25 21:12:31] DEBUG    Checking for inactivity...
immich-machine-learning_remote  | [04/26/25 21:12:31] INFO     Application startup complete.
immich-machine-learning_remote  | [04/26/25 21:12:41] DEBUG    Checking for inactivity...
immich-machine-learning_remote  | [04/26/25 21:12:51] DEBUG    Checking for inactivity...
immich-machine-learning_remote  | [04/26/25 21:13:01] DEBUG    Checking for inactivity...
immich-machine-learning_remote  | [04/26/25 21:13:11] DEBUG    Checking for inactivity...
immich-machine-learning_remote  | [04/26/25 21:13:21] DEBUG    Checking for inactivity...
```

## Logs immich server:
```
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RoutesResolver] ViewController {/api/view}:
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:NestApplication] Nest application successfully started
immich_server    | [Nest] 19  - 04/26/2025, 9:10:49 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.131.3] [production] 
immich_server    | [Nest] 19  - 04/26/2025, 9:11:23 PM     LOG [Api:EventRepository] Websocket Connect:    YfoiN9lDuuyPcNUbAAAB
immich_server    | [Nest] 7  - 04/26/2025, 9:11:29 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://localhost:3099" failed: fetch failed
immich_server    | [Nest] 7  - 04/26/2025, 9:11:29 PM   ERROR [Microservices:{"id":"b87c77c9-fc9c-41da-ab87-65f2a9c7434d"}] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.6}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
immich_server    | Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.6}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
immich_server    |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:114:15)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:123:26)
immich_server    |     at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:239:52)
immich_server    |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
immich_server    |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server    |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server    |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server    | [Nest] 19  - 04/26/2025, 9:11:42 PM     LOG [Api:EventRepository] Websocket Disconnect: YfoiN9lDuuyPcNUbAAAB
immich_server    | [Nest] 19  - 04/26/2025, 9:11:44 PM     LOG [Api:EventRepository] Websocket Connect:    Ua7pnFgow3Qcmpo8AAAD
immich_server    | [Nest] 7  - 04/26/2025, 9:12:42 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://localhost:3099" failed: fetch failed
immich_server    | [Nest] 7  - 04/26/2025, 9:12:42 PM   ERROR [Microservices:{"id":"499ece43-25fa-49ba-9ca6-010c623b8ef1"}] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.6}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
immich_server    | Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.6}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
immich_server    |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:114:15)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:123:26)
immich_server    |     at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:239:52)
immich_server    |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
immich_server    |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server    |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server    |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_redis     | 1:M 26 Apr 2025 21:14:59.092 * 100 changes in 300 seconds. Saving...
immich_redis     | 1:M 26 Apr 2025 21:14:59.093 * Background saving started by pid 84
immich_redis     | 84:C 26 Apr 2025 21:14:59.102 * DB saved on disk
immich_redis     | 84:C 26 Apr 2025 21:14:59.102 * RDB: 0 MB of memory used by copy-on-write
immich_redis     | 1:M 26 Apr 2025 21:14:59.193 * Background saving terminated with success
immich_redis     | 1:M 26 Apr 2025 21:20:45.195 * 100 changes in 300 seconds. Saving...
immich_redis     | 1:M 26 Apr 2025 21:20:45.195 * Background saving started by pid 169
immich_redis     | 169:C 26 Apr 2025 21:20:45.206 * DB saved on disk
immich_redis     | 169:C 26 Apr 2025 21:20:45.206 * RDB: 0 MB of memory used by copy-on-write
immich_redis     | 1:M 26 Apr 2025 21:20:45.296 * Background saving terminated with success
immich_redis     | 1:M 26 Apr 2025 21:26:45.172 * 100 changes in 300 seconds. Saving...
immich_redis     | 1:M 26 Apr 2025 21:26:45.172 * Background saving started by pid 254
immich_redis     | 254:C 26 Apr 2025 21:26:45.179 * DB saved on disk
immich_redis     | 254:C 26 Apr 2025 21:26:45.180 * RDB: 0 MB of memory used by copy-on-write
immich_redis     | 1:M 26 Apr 2025 21:26:45.273 * Background saving terminated with success
immich_server    | [Nest] 19  - 04/26/2025, 9:30:56 PM    WARN [Api:MachineLearningRepository~0y0hej0f] Machine learning request to "http://localhost:3099" failed: fetch failed
immich_server    | [Nest] 19  - 04/26/2025, 9:30:56 PM   ERROR [Api:ErrorInterceptor~0y0hej0f] Unknown error: Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-SO400M-16-SigLIP2-384__webli","options":{"language":"en-US"}}}}' failed for all URLs
immich_server    | Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-SO400M-16-SigLIP2-384__webli","options":{"language":"en-US"}}}}' failed for all URLs
immich_server    |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:114:15)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:137:26)
immich_server    |     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:62:27)
```


## docker ps:
```
docker ps
CONTAINER ID   IMAGE                                                                            COMMAND                  CREATED          STATUS                             PORTS                    NAMES
cda23267da2c   ghcr.io/aviv926/immich-machine-learning:pr-machine-learning-disable-tasks-cuda   "tini -- python -m i…"   22 seconds ago   Up 22 seconds (health: starting)   0.0.0.0:3099->3003/tcp   immich-machine-learning_remote
17204c85710f   ghcr.io/aviv926/immich-server:pr-machine-learning-disable-tasks                  "tini -- /bin/bash s…"   26 seconds ago   Up 3 seconds (health: starting)    0.0.0.0:2283->2283/tcp   immich_server
8946dfb3461f   tensorchord/pgvecto-rs:pg14-v0.2.0                                               "docker-entrypoint.s…"   27 seconds ago   Up 26 seconds (health: starting)   0.0.0.0:5432->5432/tcp   immich_postgres
ca5de86e1cc6   redis:6.2-alpine                                                                 "docker-entrypoint.s…"   27 seconds ago   Up 26 seconds (health: starting)   6379/tcp                 immich_redis
```

**Reply by sithmein** [reply]
Remove the leading space in front of `face` in your definition `MACHINE_LEARNING_ENABLED_TASKS`.

**Reply by aviv926** [reply]
> Remove the leading space in front of `face` in your definition `MACHINE_LEARNING_ENABLED_TASKS`.

The problem still exists.
Even when I use all the options:
`MACHINE_LEARNING_ENABLED_TASKS=image,face,text
`
Can you share your .env& docker compose file?

**Reply by sithmein** [reply]
Sure:
```
name: immich

services:
  immich-machine-learning:
    image: dreg.meinl.ddnss.ch/immich/immich-machine-learning:${IMMICH_VERSION}
    environment:
      - MACHINE_LEARNING_REQUEST_THREADS=2
      - MACHINE_LEARNING_ENABLED_TASKS=face,image
      - IMMICH_LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 3003:3003
    deploy:
      resources:
        limits:
          cpus: "4"
    healthcheck:
      disable: false
    profiles:
      - cpu

  immich-machine-learning-cuda:
    image: dreg.meinl.ddnss.ch/immich/immich-machine-learning:${IMMICH_VERSION}-cuda
    environment:
      - MACHINE_LEARNING_REQUEST_THREADS=2
      - MACHINE_LEARNING_ENABLED_TASKS=face,image
      - TZ=${TZ}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 3003:3003
    deploy:
      resources:
        limits:
          cpus: "2"
    healthcheck:
      disable: false
    profiles:
      - cuda


volumes:
  model-cache:
```

```
TZ=Europe/Zurich
IMMICH_VERSION=v1.132.1-1
```
