### DISCUSSION TITLE
[BUG]error on docker

### DISCUSSION THREAD

**Discussion by VwEl** [immich-app/immich#17083] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Node.js v22.13.1

Initializing Immich v1.128.0

Detected CPU Cores: 4

node:internal/modules/cjs/loader:1247

  throw err;

  ^

Error: Cannot find module './langs/br.json'

Require stack:

- /usr/src/app/node_modules/i18n-iso-countries/entry-node.js

- /usr/src/app/dist/repositories/map.repository.js

- /usr/src/app/dist/services/base.service.js

- /usr/src/app/dist/services/cli.service.js

- /usr/src/app/dist/commands/list-users.command.js

- /usr/src/app/dist/commands/index.js

- /usr/src/app/dist/app.module.js

- /usr/src/app/dist/main.js

### The OS that Immich Server is running on

QNAP QTS5.2.3

### Version of Immich Server

v1.128.0 and v1.129

### Version of Immich Mobile App

null

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=//share/HC550/immich
# The location where your database files are stored
DB_DATA_LOCATION=/share/HC550/docker/immich

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.ip:2283
2.
3.
...

### Relevant log output

```shell

```
