### DISCUSSION TITLE
Admin ->Job Status not loading

### DISCUSSION THREAD

**Discussion by crumbach** [immich-app/immich#17091] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

http://{my immich ip}:2283/admin/jobs-status does not respond (connection time out) whereas all other immich links work fine, e.g. /admin/user-management. 

There is a similar old issue: https://github.com/immich-app/immich/issues/12145
Restarting the server, incognito mode or clearing browser cache does not help. 

### The OS that Immich Server is running on

Docker on a UGREEN NAS

### Version of Immich Server

V1.129.0

### Version of Immich Mobile App

V1.129.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ./library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      # The location where your uploaded files are stored
      - UPLOAD_LOCATION=./library
      # The location where your database files are stored
      - DB_DATA_LOCATION=./postgres
      # To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      # TZ=Etc/UTC
      # The Immich version to use. You can pin this to a specific version like "v1.71.0"
      - IMMICH_VERSION=release
      # Connection secret for postgres. You should change it to a random password
      # Please use only the characters `A-Za-z0-9`, without special characters or spaces
      - DB_PASSWORD=notarandompw
      # The values below this line do not need to be changed
      ###################################################################################
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: notarandompw
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='postgres' || exit 1; Chksum="$$(psql --dbname='immich' --username='postgres' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

timeout for url: http://{my immich ip}:2283/admin/jobs-status

### Relevant log output

```shell
jquery-ui.js:14 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.js:14:12
    at jquery-ui.js:16:2
(anonymous) @ jquery-ui.js:14
(anonymous) @ jquery-ui.js:16
f67Ns1jr.js:1 
            
            
           GET http://{my immich ip}/api/jobs net::ERR_CONNECTION_TIMED_OUT
window.fetch @ f67Ns1jr.js:1
It @ f67Ns1jr.js:1
fetch @ f67Ns1jr.js:1
r @ CpqwS_fC.js:1
n @ CpqwS_fC.js:1
a @ CpqwS_fC.js:1
ln @ CpqwS_fC.js:1
Rt @ 30.Cuo-tj2M.js:1
await in Rt
Oe @ f67Ns1jr.js:1
await in Oe
(anonymous) @ f67Ns1jr.js:1
$e @ f67Ns1jr.js:1
q @ f67Ns1jr.js:1
await in q
de @ f67Ns1jr.js:1
hn @ f67Ns1jr.js:1
Sn @ f67Ns1jr.js:1
await in Sn
(anonymous) @ jobs-status:191
Promise.then
(anonymous) @ jobs-status:190
f67Ns1jr.js:1 
            
            
           GET http://{my immich ip}:2283/_app/version.json net::ERR_CONNECTION_REFUSED
window.fetch @ f67Ns1jr.js:1
r @ f67Ns1jr.js:1
$e @ f67Ns1jr.js:1
await in $e
q @ f67Ns1jr.js:1
await in q
de @ f67Ns1jr.js:1
hn @ f67Ns1jr.js:1
Sn @ f67Ns1jr.js:1
await in Sn
(anonymous) @ jobs-status:191
Promise.then
(anonymous) @ jobs-status:190
app.6B4UViqF.js:2 [hooks.client.ts]:handleError Failed to fetch TypeError: Failed to fetch
    at window.fetch (f67Ns1jr.js:1:1519)
    at It (f67Ns1jr.js:1:1849)
    at fetch (f67Ns1jr.js:1:15782)
    at r (CpqwS_fC.js:1:6695)
    at n (CpqwS_fC.js:1:6061)
    at Object.a [as fetchJson] (CpqwS_fC.js:1:6271)
    at ln (CpqwS_fC.js:1:12997)
    at Rt (30.Cuo-tj2M.js:1:1629)
    at async Oe (f67Ns1jr.js:1:15906)
vt @ app.6B4UViqF.js:2
V @ f67Ns1jr.js:1
$e @ f67Ns1jr.js:1
await in $e
q @ f67Ns1jr.js:1
await in q
de @ f67Ns1jr.js:1
hn @ f67Ns1jr.js:1
Sn @ f67Ns1jr.js:1
await in Sn
(anonymous) @ jobs-status:191
Promise.then
(anonymous) @ jobs-status:190
```
