### DISCUSSION TITLE
No photos displayed in Photos page v1.30.x

### DISCUSSION THREAD

**Discussion by danukefl** [immich-app/immich#17181] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

This issue is similar to #17121 but I only use the internal library in the web versions. 

I did not test v1.30.0 but for v1.30.1-1.30.3, no photos from any time appear in the "Photos" view in the web client. The android mobile app is fully functional from what I have tested. Images and videos in albums, favorites, and explore, including those uploaded since updates, show and function as expects.

Troubleshooting:
- Signed out and back in
- Browsers Brave, Firefox, Chrome, and Edge
- Recreated and repulled images for docker stack (both to upgrade and within the same version)
- No relevant logs found within any container
- No errors or warnings from Brave browser inspect window

Photos Page
![Image](https://github.com/user-attachments/assets/0fe7e236-51d9-4308-a1d9-d2e8fbd9ea0c)

Explore page for a location of photos taken yesterday
![Image](https://github.com/user-attachments/assets/8368f8f9-2717-4d3a-b4ec-fe21c63fb701)

### The OS that Immich Server is running on

Docker on Debian 9 host

### Version of Immich Server

v1.30.3

### Version of Immich Mobile App

v1.30.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    env_file:
      - stack.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  photolibrary:
    driver_opts:
      type: nfs
      o: addr=192.168.1.1,nolock,soft,rw
      device: :/Docker-HDD/ImmichLibrary
  pgdata:
    driver_opts:
      type: nfs
      o: addr=192.168.1.1,nolock,soft,rw
      device: :/Docker-SSD/ImmichPostgres
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich_user
DB_DATABASE_NAME=immich
TYPESENSE_API_KEY=xxxxxxxx
DB_PASSWORD=xxxxxxx
REDIS_HOSTNAME=immich_redis
IMMICH_VERSION=release
UPLOAD_LOCATION=photolibrary
```

### Reproduction steps

1. Log in to Immich
2. Photos not shown on Photos page

### Relevant log output

```shell

```
