### DISCUSSION TITLE
description field does not save

### DISCUSSION THREAD

**Discussion by hctrr** [immich-app/immich#17377] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

It was happening in 1.129.x and currently still occurring on 1.131.3

for both videos and pictures, it appears that anything that i populate within the description field does not actually get saved, even though it prompts me that it has.

![Image1](https://github.com/user-attachments/assets/d3b86aa2-8915-4984-bf26-855335645dee)

![Image2](https://github.com/user-attachments/assets/e71c2ba4-2b99-4dfb-9fef-1032a03bbe61)

after closing the info bar and reopen to review the description, all the info is gone.

This also happens when attempting to perform the same steps via the iOS mobile app.

### The OS that Immich Server is running on

Ubuntu 22.04.5

### Version of Immich Server

1.131.3

### Version of Immich Mobile App

1.131.3

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
## NOTE: I use portainer and leverage their env_file: - stack.env implementation.


name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "/home/zzzz/immich/immich/pictures:/home/user/originals:ro"
    env_file:
      - stack.env
    ports:
      - 'xxxx:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/zzzz/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
.
```

### Reproduction steps

1. open a picture or video and add a description
2. let it save and show that it saved
3. close the info bar, and relaunch the info bar to review the description... its at this point that the info is missing.
...

### Relevant log output

```shell

```
