### DISCUSSION TITLE
Gateway Timeout with Traefik even with respondingTimeouts

### DISCUSSION THREAD

**Discussion by ajfriesen** [immich-app/immich#17618] [Q&A]
I have recently set up immich with docker-compose and use my traefik reverse proxy.
The domain I am using points to a tailscale ip, if that is of relevance, but I do not think so.

I have successfully imported 70k photos and 1500 videos via `IP:PORT`.
Immich itself seemed to run fine and performant enough. It is running on NVME ssds, i5-12400.
However, when using proxy it sometimes works for a couple of minutes/hours but then at some point it stops for good.

I always get a `Gateway Timeout`.

Here the logs in traefik:

```
traefik  | 2025-04-15T11:25:04Z DBG github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:84 > Accepting IP 100.82.206.54 middlewareName=local-only@file middlewareType=IPAllowLister
traefik  | 2025-04-15T11:25:04Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.21.0.4:2283
traefik  | 2025-04-15T11:25:34Z DBG github.com/traefik/traefik/v3/pkg/proxy/httputil/proxy.go:121 > 504 Gateway Timeout error="dial tcp 172.21.0.4:2283: i/o timeout"
traefik  | 2025-04-15T11:25:34Z DBG github.com/traefik/traefik/v3/pkg/middlewares/ipallowlist/ip_allowlist.go:84 > Accepting IP 100.82.206.54 middlewareName=local-only@file middlewareType=IPAllowLister
traefik  | 2025-04-15T11:25:34Z DBG github.com/traefik/traefik/v3/pkg/server/service/loadbalancer/wrr/wrr.go:213 > Service selected by WRR: http://172.21.0.4:2283
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:38962: read tcp 172.31.0.6:443->170.39.218.2:38962: read: connection reset by peer
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:38978: read tcp 172.31.0.6:443->170.39.218.2:38978: read: connection reset by peer
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:38992: tls: no cipher suite supported by both client and server
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:39004: tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:39008: tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9])
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:39024: tls: client offered only unsupported versions: [302 301]
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:45Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:39040: read tcp 172.31.0.6:443->170.39.218.2:39040: read: connection reset by peer
traefik  | 2025-04-15T11:25:45Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:46Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:39056: read tcp 172.31.0.6:443->170.39.218.2:39056: read: connection reset by peer
traefik  | 2025-04-15T11:25:46Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:46Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:35310: read tcp 172.31.0.6:443->170.39.218.2:35310: read: connection reset by peer
traefik  | 2025-04-15T11:25:46Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: "PUBLIC-IP"
traefik  | 2025-04-15T11:25:46Z DBG log/log.go:245 > http: TLS handshake error from 170.39.218.2:35316: read tcp 172.31.0.6:443->170.39.218.2:35316: read: connection reset by peer
traefik  | 2025-04-15T11:25:46Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
traefik  | 2025-04-15T11:25:46Z DBG github.com/traefik/traefik/v3/pkg/tls/tlsmanager.go:228 > Serving default certificate for request: ""
traefik  | 2025-04-15T11:26:04Z DBG github.com/traefik/traefik/v3/pkg/proxy/httputil/proxy.go:121 > 504 Gateway Timeout error="dial tcp 172.21.0.4:2283: i/o timeout"
```

Here is the file for whitelisting internal IPs only.
This is needed, otherwise, people can get my public IP and curl all my services like so:
`curl -k https://$PUBLIC_IP/web/#/home.html -H 'Host: immich.domain.com'`

```
cat file/ip-whitelist.yaml
http:
  middlewares:
    local-only:
      ipAllowList:
        sourceRange:
          - "192.168.178.0/24"
          - "100.64.0.0/10"
```

I have seen the example for [adding timeouts to traefik in the docs](https://immich.app/docs/administration/reverse-proxy#traefik-proxy-example-config) and have added the  `respondingTimeouts` accordingly. At least, I think so.

Here is my traefik config.
I am using my own `proxy-network`.

```yaml
services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      # file provider
      - "--providers.file.directory=/config/traefik_configs"
      # docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # timeouts for immich
      # https://immich.app/docs/administration/reverse-proxy/#traefik-proxy-example-config
      - "--entryPoints.websecure.transport.respondingTimeouts.readTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.idleTimeout=300s"
      - "--entryPoints.websecure.transport.respondingTimeouts.writeTimeout=300s"
      # Endoints
      - "--entryPoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # http resolver
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
        #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=XXX@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # DNS resolver
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.dnsresolver.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.dnsresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.dnsresolver.acme.email=XXX@gmail.com"
        # - "--certificatesresolvers.dnsresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./file/:/config/traefik_configs/"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
```

Here is my immich compose. Only changes I made:
- use bind mounts instead of volumes
- use the proxy-network for exposing

```yaml
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.my.domain.com`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=dnsresolver"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.middlewares=local-only@file"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    networks:
      - proxy-network
      - immich-internal

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-internal

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - immich-internal

volumes:
  model-cache:
networks:
  proxy-network:
    external: true
    name: proxy-network
  immich-internal:
```

Maybe someone has an idea how to debug this further.

**Comment by MatrixTechno** [comment]
https://github.com/immich-app/immich/discussions/8872

fixed it for me

### TLDR, here's the fix:

Add the following to your Traefik config and **restart** the Traefik instance. For more examples, see the docs: https://doc.traefik.io/traefik/routing/entrypoints/#respondingtimeouts

```yaml
entryPoints:
  ...
  name:
    ...
    # This is the fix:
    transport:
      respondingTimeouts:
        readTimeout: "0s"
```
