### DISCUSSION TITLE
have trouble with N5105‘s Hardware Transcoding on QNAP TS564

### DISCUSSION THREAD

**Discussion by FlankerZzzz** [immich-app/immich#17694] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Have trouble with N5105‘s Hardware Transcoding on QNAP TS564
It just not work, both vappi and qsv mode
have already checked this issue [](https://github.com/immich-app/immich/discussions/11422)
So, how to  set GUC=2 on QNAP system startup?

### The OS that Immich Server is running on

Linux QFlanker 5.10.60-qnap #1 SMP Fri Mar 21 01:07:02 CST 2025 x86_64 GNU/Linux [admin@QFlanker i915]# cat /etc/*release NAME="QTS" VERSION="5.2.4 (20250321)" ID=qts PRETTY_NAME="QTS 5.2.4 (20250321)" VERSION_ID="5.2.4"

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    privileged: true
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /share/CACHEDEV2_DATA/Important:/share/CACHEDEV2_DATA/Important:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    environment:
      - UID=0
      - GID=0
      - PUID=0
      - PGID=0
      - UMASK=0022
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - /share/CACHEDEV1_DATA/Public/Docker/immich-app/model:/cache
    env_file:
      - .env
    restart: always
    environment:
      - HTTP_PROXY=http://192.168.31.152:7890
      - HTTPS_PROXY=http://192.168.31.152:7890
      - NO_PROXY=localhost,127.0.0.1
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
[admin@QFlanker immich-app]# cat .env 
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/share/CACHEDEV2_DATA/Important/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
