### DISCUSSION TITLE
Oauth Issue -> OPError: expected 200 OK, got: 403 Forbidden

### DISCUSSION THREAD

**Discussion by Daniel-dev22** [immich-app/immich#17706] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm seeing this error. After changing nothing in authelia my IDP provider. In fact immich isn't even reaching out to authelia.

`OPError: expected 200 OK, got: 403 Forbidden`

```
[Nest] 17  - 04/18/2025, 5:10:57 PM     LOG [Api:EventRepository] Websocket Connect:    FEd2WhPqOdhSfC6LAAAB
[Nest] 17  - 04/18/2025, 5:10:59 PM   ERROR [Api:OAuthRepository~98s1vem8] Error in OAuth discovery: OPError: expected 200 OK, got: 403 Forbidden
[Nest] 17  - 04/18/2025, 5:10:59 PM   ERROR [Api:OAuthRepository~98s1vem8] OPError: expected 200 OK, got: 403 Forbidden
    at processResponse (/usr/src/app/node_modules/openid-client/lib/helpers/process_response.js:41:11)
    at Issuer.discover (/usr/src/app/node_modules/openid-client/lib/issuer.js:152:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async OAuthRepository.getClient (/usr/src/app/dist/repositories/oauth.repository.js:61:28)
    at async OAuthRepository.authorize (/usr/src/app/dist/repositories/oauth.repository.js:27:24)
    at async AuthService.authorize (/usr/src/app/dist/services/auth.service.js:128:21)
```

This is very odd.

### The OS that Immich Server is running on

Treunas scale

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ${CURRENT_IMMICH_SERVER_IMAGE}
    devices:
    - /dev/dri/renderD128:/dev/dri
    volumes:
    - /mnt/raid_array/docker_container_volumes/immich_storage:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
    networks:
      traefik-network:
        ipv4_address: 10.0.1.20
      immich-stack-network:
        ipv4_address: 10.0.2.2
    environment:
      UPLOAD_LOCATION: /mnt/raid_array/docker_container_volumes/immich_storage/upload
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
    - redis
    - database
    restart: always
    healthcheck:
      disable: false
    labels:
    - traefik.enable=true
    - traefik.http.routers.immich.rule=Host(`photos.domain.com`)
    - traefik.http.routers.immich.entrypoints=websecure
    - traefik.http.routers.immich.tls=true
    - traefik.http.routers.immich.tls.certresolver=le
    - traefik.http.routers.immich.service=immich
    - traefik.http.services.immich.loadbalancer.server.port=2283
    - traefik.http.routers.immich.middlewares=secured-headers@file
    - traefik.docker.network=traefik-network
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ${CURRENT_IMMICH_MACHINE_LEARNING_IMAGE}
    device_cgroup_rules:
    - c 189:* rmw
    devices:
    - /dev/dri/renderD128:/dev/dri
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.3
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /mnt/fast_storage/docker_container_volumes/immich/model_cache:/cache
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: ${CURRENT_IMMICH_REDIS_IMAGE}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.4
  database:
    container_name: immich_postgres
    image: ${CURRENT_IMMICH_POSTGRES_IMAGE}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_DATA_LOCATION: /mnt/fast_storage/docker_container_volumes/immich/postgres
    volumes:
    - /mnt/fast_storage/docker_container_volumes/immich/postgres:/var/lib/postgresql/data
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.5
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}"
        --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures),
        0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user",
      public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
networks:
  traefik-network:
    external: true
  immich-stack-network:
    external: true
```

### Your .env content

```Shell
.
```

### Reproduction steps

1.add oauth client
2.remove authorized devices except current session
3.logout and try to login with oauth
...

### Relevant log output

```shell

```

### Additional information

[immich_server_logs.txt](https://github.com/user-attachments/files/19817173/immich_server_logs.txt)
