### DISCUSSION TITLE
immich-machine-learning cuda version container restarts constantly

### DISCUSSION THREAD

**Discussion by davidshen84** [immich-app/immich#17707] [Q&A] [answered]
Hi,

I want to deploy the cuda version of the immich machine learning container image to my k8s cluster. However, the pod is not functioning correctly and restarts constantly.

Below are my immich configuration, logs and gpu profile.

# values.yaml

```yaml
immich:
  env:
    DB_HOSTNAME: db-pg-rw
    DB_USERNAME: postgres
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: db-pg-superuser
          key: password
    IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
    IMMICH_LOG_LEVEL: debug

  image:
    tag: v1.131.3

  immich:
    persistence:
      library:
        existingClaim: immich-library

  server:
    resources:
      limits:
        cpu: 3000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi
    service:
      main:
        type: LoadBalancer
    persistence:
      external:
        existingClaim: immich-external

  redis:
    enabled: true
    architecture: standalone
    auth:
      enabled: false
    master:
      resources:
        limits:
          cpu: 1000m
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 256Mi

  machine-learning:
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.131.3-cuda
    env:
      TRANSFORMERS_CACHE: /cache
    persistence:
      cache:
        size: 32Gi
        type: emptyDir
        accessMode: ReadWriteOnce
    resources:
      limits:
        cpu: 3000m
        memory: 16Gi
        nvidia.com/gpu: 1
      requests:
        cpu: 50m
        memory: 128Mi
```

# immich machine learning pod debug log
```
[04/19/25 04:24:38] INFO     Starting gunicorn 23.0.0                           
[04/19/25 04:24:38] INFO     Listening at: http://[::]:3003 (8)                 
[04/19/25 04:24:38] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[04/19/25 04:24:38] INFO     Booting worker with pid: 9                         
[04/19/25 04:24:39] DEBUG    Could not load ANN shared libraries, using ONNX:   
                             libmali.so: cannot open shared object file: No such
                             file or directory                                  
[04/19/25 04:24:39] DEBUG    RKNN is not available                              
[04/19/25 04:24:41] INFO     Started server process [9]                         
[04/19/25 04:24:41] INFO     Waiting for application startup.                   
[04/19/25 04:24:41] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/19/25 04:24:41] INFO     Initialized request thread pool with 8 threads.    
[04/19/25 04:24:41] DEBUG    Checking for inactivity...                         
[04/19/25 04:24:41] INFO     Application startup complete.                      
[04/19/25 04:24:47] DEBUG    Setting model format to onnx                       
[04/19/25 04:24:47] INFO     Downloading detection model 'buffalo_s'. This may  
                             take a while.                                      
[04/19/25 04:24:51] DEBUG    Checking for inactivity...                         
[04/19/25 04:25:01] DEBUG    Checking for inactivity...                         
Fetching 4 files: 100%|██████████| 4/4 [00:11<00:00,  2.93s/it]
[04/19/25 04:25:07] INFO     Loading detection model 'buffalo_s' to memory      
[04/19/25 04:25:07] DEBUG    Available ORT providers:                           
                             {'TensorrtExecutionProvider',                      
                             'CUDAExecutionProvider', 'CPUExecutionProvider'}   
[04/19/25 04:25:07] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[04/19/25 04:25:07] DEBUG    Setting execution provider options to              
                             [{'arena_extend_strategy': 'kSameAsRequested',     
                             'device_id': '0'}, {'arena_extend_strategy':       
                             'kSameAsRequested'}]                               
[04/19/25 04:25:07] DEBUG    Setting execution_mode to ORT_SEQUENTIAL           
[04/19/25 04:25:07] DEBUG    Setting inter_op_num_threads to 0                  
[04/19/25 04:25:07] DEBUG    Setting intra_op_num_threads to 0                  
[04/19/25 04:25:13] ERROR    Worker (pid:9) was sent code 139!                  
[04/19/25 04:25:13] INFO     Booting worker with pid: 40                        
[04/19/25 04:25:14] DEBUG    Could not load ANN shared libraries, using ONNX:   
                             libmali.so: cannot open shared object file: No such
                             file or directory                                  
[04/19/25 04:25:14] DEBUG    RKNN is not available                              
[04/19/25 04:25:15] INFO     Started server process [40]                        
[04/19/25 04:25:15] INFO     Waiting for application startup.                   
[04/19/25 04:25:15] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/19/25 04:25:15] INFO     Initialized request thread pool with 8 threads.    
[04/19/25 04:25:15] DEBUG    Checking for inactivity...                         
[04/19/25 04:25:15] INFO     Application startup complete.                      
[04/19/25 04:25:15] DEBUG    Setting model format to onnx                       
[04/19/25 04:25:15] INFO     Loading detection model 'buffalo_s' to memory      
[04/19/25 04:25:15] DEBUG    Available ORT providers:                           
                             {'TensorrtExecutionProvider',                      
                             'CUDAExecutionProvider', 'CPUExecutionProvider'}   
[04/19/25 04:25:15] INFO     Setting execution providers to                     
                             ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
                             in descending order of preference                  
[04/19/25 04:25:15] DEBUG    Setting execution provider options to              
                             [{'arena_extend_strategy': 'kSameAsRequested',     
                             'device_id': '0'}, {'arena_extend_strategy':       
                             'kSameAsRequested'}]                               
[04/19/25 04:25:15] DEBUG    Setting execution_mode to ORT_SEQUENTIAL           
[04/19/25 04:25:15] DEBUG    Setting inter_op_num_threads to 0                  
[04/19/25 04:25:15] DEBUG    Setting intra_op_num_threads to 0                  
[04/19/25 04:25:24] ERROR    Worker (pid:40) was sent code 139!                 
[04/19/25 04:25:24] INFO     Booting worker with pid: 64                        
```

# nvidia-smi
```
Sat Apr 19 14:26:28 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.07             Driver Version: 570.133.07     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050        Off |   00000000:01:00.0 Off |                  N/A |
| N/A   55C    P8            N/A  / 5001W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by bo0tzz** [comment, marked as answer]
I believe you also have to set the `runtimeClass` for it to actually be assigned a GPU.

**Reply by davidshen84** [reply]
```yaml
  machine-learning:
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.131.3-cuda
    runtimeClassName: nvidia
```
