### DISCUSSION TITLE
Feature Request: Ignore ._* AppleDouble (dot-underscore) files during Web UI uploads

### DISCUSSION THREAD

**Discussion by mastaxx** [immich-app/immich#17744] [Feature Request]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**Description:**

When drag-and-dropping folders into the Immich Web UI, Immich currently processes all files inside those folders, including macOS-generated ._* (AppleDouble) files. These files are not valid media — they’re metadata sidecars generated by macOS and are completely useless in the context of a photo/video library.

Unfortunately, Immich treats them as real files and attempts to process them, which causes unnecessary clutter in the upload queue and often leads to stalling or blocking the progress monitor. This makes it difficult to verify when a large upload has truly finished.

**Expected Behaviour:**

Immich should automatically ignore any file that starts with ._ when processing drag/drop folder uploads via the Web UI. This behaviour should:

- Apply only to files named like ._filename.jpg, ._video.mov, etc.

- Not affect hidden files that don’t follow the AppleDouble convention (like .env).

- Never delete or modify these files — just ignore them on the client side during upload.

**Bonus (Nice-to-have): If feasible, a toggle in settings like:**

[x] Ignore AppleDouble dot-underscore files during upload
would be helpful for users who might want this behavior optional.

**Why this matters:**

- These files are automatically generated on macOS when copying files to non-native file systems (like SMB or USB drives).

- Users are often unaware they exist.

- They're not valid media and waste processing cycles, disk space, and UI visibility.

- They can stall large uploads and confuse users into thinking the queue is still processing when it may have already completed.

**Environment Info:**

OS: macOS (source of ._ files)

Upload method: Web UI via drag-and-drop folders

Immich version: v1.131.3

Browser: Chrome / Firefox

### The OS that Immich Server is running on

Ubuntu 22.04 (Live Server)

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release-nvenc}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release-cuda}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.Open Immich Web UI in a browser.
2.Drag and drop a parent folder into the UI that contains many nested subfolders with image and video files (e.g., exporting a photo library).
3.Observe that `.DS_Store`, `._filename.ext`, and other hidden macOS-generated "ghost" files are added to the import queue alongside valid assets
4. When importing a large batch (e.g., 1000-10,000+ assets), the queue in the Web UI eventually hangs — it stops updating, and there is no clear indication whether the import has completed or stalled.

### Relevant log output

```shell

```
