### DISCUSSION TITLE
Thumbnail generation throws errors from jpegli library but does not give the filename

### DISCUSSION THREAD

**Discussion by f18m** [immich-app/immich#17777] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I run the process to generate thumbnails on my photo library, I get the following error log:

```
[Nest] 7  - 04/22/2025, 11:51:54 AM   ERROR [Microservices:{"id":"d1eadd62-4154-4d07-af2e-ca16949081c1"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd0
Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd0
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:51:54 AM   ERROR [Microservices:{"id":"214c1950-253b-48d0-82bf-aa293d656472"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:51:54 AM   ERROR [Microservices:{"id":"0b1b62e3-ddff-48ff-8913-afe9536674d7"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:51:54 AM   ERROR [Microservices:{"id":"030bf292-969a-42fa-9c65-ba318f86e482"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd0
Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd0
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:51:54 AM   ERROR [Microservices:{"id":"83cd3e91-02cb-43b2-9097-c921498fe75a"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:51:55 AM   ERROR [Microservices:{"id":"6db5b5f4-fc86-4592-8c01-dedf83367fab"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd7
Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:535: Incomplete scan detected.
VipsJpeg: ./lib/jpegli/decode_marker.cc:554: Unexpected marker 0xd7
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:97:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:192:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[...]
```

These errors might be legitimate... it's however impossible for me to check if the are JPEG files that are truly corrupted because the log does not contain any filename... 

So this bug report is to ask the devs to add to the logs of any jpegli exception (maybe at the 'MediaRepository.decodeImage' layer ?) the logging of the filename.

Thanks!

### The OS that Immich Server is running on

Fedora Linux 41

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

NONE

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.131.3
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - photos_nas:/data/import/photos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.3
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine3.21
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Rome

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Point your browser to http://localhost:2283/admin/jobs-status
2. Click the Run button for missing files on Thumbnail generation
3. Check all errors reported via 'docker logs immich_server'
...

### Relevant log output

```shell

```
