### DISCUSSION TITLE
Error generating thumbnails and syncing images

### DISCUSSION THREAD

**Discussion by ErikFunke** [immich-app/immich#17774] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**Description:**

After updating immich-server to v1.131.3 using the official Docker images and `docker-compose` setup on Ubuntu Server, I’ve encountered issues with thumbnail generation. My Immich-App version was still an older version (older than v1.126.0)(I don't know the exact version, because I already updated before deciding to open this issue).

**Symptoms:**

- Thumbnails stopped generating after the update
- Images were not saved inside my library folder structure
- Images show up without previews, and clicking on the images also shows that the image cannot be loaded
![Image](https://github.com/user-attachments/assets/cdd4878a-be44-4433-9b7c-75f6c2427e3b)

**What I Tried:**

I restarted and removed the immich-server conatiner. When I first triggered a manual thumbnail generation inside the "Jobs" menu for missing elements, I got Error 1

(Immich Server v1.131.3 and Android Immich App version older than v1.126.0)

When I restarted the immich-server container, the thumbnails where generated. Somehow the images with the missing thumbnails are not present inside my library folder on my fileserver. Immich still shows them inside my web-browser and app after manually triggering thumbnail generatiion and restarting the container.

**Testing New Upload**  
   I took a new photo with my smartphone and the updated Immich Android App (v1.131.3) and tried syncing a new image it to test if thumbnails now generate correctly. Upon doing so, I encountered an error: (See Error Log 2)
The image is still shown with broken thumbnails. I have to manually trigger the thumbnail creation for the selected images. New images show up inside the libraray folder after the android app update.

### The OS that Immich Server is running on

Ubuntu 24.04 Server

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-server.rule=Host(`immich.------------`)"
      - "traefik.http.routers.immich-server.entrypoints=websecure"
      - "traefik.http.routers.immich-server.tls=true"
      - "traefik.http.routers.immich-server.tls.certresolver=myresolver"
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - web
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    networks:
      - web
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - web
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - web
    restart: always

volumes:
  model-cache:

networks:
  web:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/zfs-share/immich/storage
DB_DATA_LOCATION=/mnt/zfs-share/immich/database
IMMICH_VERSION=release
DB_PASSWORD=-----
DB_USERNAME=-----
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Updated immich to newest version (v1.131.3)
2. Noticed some days later that the synced photos from the smartphone were not able to be shown inside the web-browser version
3. Web request for thumbnails from assets returend 404 in brwoser console
4. Manually triggered thumbnail creation inside the "Jobs" settings for missing thumbnails
5. Error log 1 shows up
6. Restarting the container created the thumbnails, sometimes marking the images and creating the thumbnails explicitly also worked
7. Updating Android App and uploading/syncing new image with matching app version v1.131.3
8. Error log 2 shows up

### Relevant log output

```shell
Error Log 1:

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 32. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 33. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 34. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
Error: Missing lock for job 35. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 36. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
Error: Missing lock for job 37. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/22/2025, 11:28:35 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 38. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)



Error Log 2:
[Nest] 17  - 04/22/2025, 10:45:37 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.131.3] [production] 
[Nest] 17  - 04/22/2025, 10:46:07 AM     LOG [Api:EventRepository] Websocket Connect:    -cbunLGfedNqD2pZAAAB
[Nest] 17  - 04/22/2025, 10:46:13 AM     LOG [Api:EventRepository] Websocket Connect:    eiZZYfm9sZIggrmuAAAD
[Nest] 17  - 04/22/2025, 10:47:20 AM     LOG [Api:EventRepository] Websocket Disconnect: eiZZYfm9sZIggrmuAAAD
[Nest] 17  - 04/22/2025, 10:48:29 AM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 17  - 04/22/2025, 10:48:29 AM    WARN [Api:FileUploadInterceptor] Error: aborted
    at abortIncoming (node:_http_server:809:17)
    at socketOnClose (node:_http_server:803:3)
    at Socket.emit (node:events:530:35)
    at TCP.<anonymous> (node:net:351:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
[Nest] 7  - 04/22/2025, 10:48:29 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 04/22/2025, 10:48:29 AM   ERROR [Microservices:{}] Unable to run job handler (thumbnailGeneration/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:157:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 17  - 04/22/2025, 10:48:30 AM     LOG [Api:EventRepository] Websocket Connect:    4jagoy0eXDGEf8P-AAAF
[Nest] 17  - 04/22/2025, 10:48:56 AM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 17  - 04/22/2025, 10:48:56 AM    WARN [Api:FileUploadInterceptor] Error: aborted
    at abortIncoming (node:_http_server:809:17)
    at socketOnClose (node:_http_server:803:3)
    at Socket.emit (node:events:530:35)
    at TCP.<anonymous> (node:net:351:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
Query failed : {
  durationMs: 2.52295199999935,
  error: PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(f815f71d-cc55-4105-b08b-3b336627798d, \\x31d197086380b30ac22c0296f33cba8ec6a0130c) already exists.',
    schema_name: 'public',
    table_name: 'assets',
    constraint_name: 'UQ_assets_owner_checksum',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    'f815f71d-cc55-4105-b08b-3b336627798d',
    ----
    'IMG_20250422_124717_984.jpg'
  ]
}
```
