### DISCUSSION TITLE
Immich fails to start after last update

### DISCUSSION THREAD

**Discussion by fajulleiro** [immich-app/immich#17844] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating my immich instance to 1.132.1, it fails to start properly.

I've attached the relevant error below. Seems to be related to some record in PG DB and it restarts that worker and fails over and over again

### The OS that Immich Server is running on

Docker on Debian 12

### Version of Immich Server

v1.132.1

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=***/immich/library
DB_DATA_LOCATION=***/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=*****
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. updated from 1.131.3 using Update the Stack in Portainer with Re-pull image and redeploy
2.
3.
...

### Relevant log output

```shell
Initializing Immich v1.132.1

Detected CPU Cores: 4

Starting api worker

Starting microservices worker

[Nest] 7  - 04/24/2025, 10:23:20 AM     LOG [Microservices:EventRepository] Initialized websocket server

[Nest] 7  - 04/24/2025, 10:23:20 AM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while

Migration "MakeFileMetadataNonNullable1744662638410" failed, error: attempted to delete invisible tuple

QueryFailedError: attempted to delete invisible tuple

    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async MakeFileMetadataNonNullable1744662638410.up (/usr/src/app/dist/migrations/1744662638410-MakeFileMetadataNonNullable.js:6:9)

    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)

    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:195:13)

    at async /usr/src/app/dist/services/database.service.js:93:17

    at async /usr/src/app/dist/repositories/database.repository.js:231:27

    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20

    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20) {

  query: 'DELETE FROM assets WHERE "fileCreatedAt" IS NULL OR "fileModifiedAt" IS NULL OR "localDateTime" IS NULL',

  parameters: undefined,

  driverError: error: attempted to delete invisible tuple

      at /usr/src/app/node_modules/pg/lib/client.js:545:17

      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:181:25)

      at async MakeFileMetadataNonNullable1744662638410.up (/usr/src/app/dist/migrations/1744662638410-MakeFileMetadataNonNullable.js:6:9)

      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)

      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:195:13)

      at async /usr/src/app/dist/services/database.service.js:93:17

      at async /usr/src/app/dist/repositories/database.repository.js:231:27

      at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20 {

    length: 92,

    severity: 'ERROR',

    code: '55000',

    detail: undefined,

    hint: undefined,

    position: undefined,

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'heapam.c',

    line: '2814',

    routine: 'heap_delete'

  },

  length: 92,

  severity: 'ERROR',

  code: '55000',

  detail: undefined,

  hint: undefined,

  position: undefined,

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: undefined,

  table: undefined,

  column: undefined,

  dataType: undefined,

  constraint: undefined,

  file: 'heapam.c',

  line: '2814',

  routine: 'heap_delete'

}

microservices worker error: QueryFailedError: attempted to delete invisible tuple, stack: QueryFailedError: attempted to delete invisible tuple

    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:216:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async MakeFileMetadataNonNullable1744662638410.up (/usr/src/app/dist/migrations/1744662638410-MakeFileMetadataNonNullable.js:6:9)

    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)

    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:195:13)

    at async /usr/src/app/dist/services/database.service.js:93:17

    at async /usr/src/app/dist/repositories/database.repository.js:231:27

    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20

    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)

microservices worker exited with code 1

Killing api process
```
