### DISCUSSION TITLE
Immich does not support the audio codec uncompressed PCM for video's in Firefox

### DISCUSSION THREAD

**Discussion by ferrybig** [immich-app/immich#17847] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have an 8 year old video in my photo album. When looking at the video in Immich, Immich only shows video, the audio is lost. (the browser shows the muted audio icon without being able to change it, indicating the converted file for browser viewing lost the audio track) Downloading the original and opening it in VLC does play the audio.

The file in question: 

    MVI_1773.AVI: RIFF (little-endian) data, AVI, 320 x 240, 30.00 fps, video: Motion JPEG, audio: uncompressed PCM (stereo, 44100 Hz)

The table at https://immich.app/docs/features/supported-formats shows `.avi` is supported (but does that really mean anything, as avi's can contain so many formats??)

### The OS that Immich Server is running on

Debian 6.1.124-1 (2025-01-12) via 28.0.1, build 068a01e

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
    #  - 127.0.0.1:2283:2283
    depends_on:
      - redis
      - database
    restart: on-failure
    healthcheck:
      disable: false
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      proxy:
      immich-net:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      immich-net:
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich-net:
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      immich-net:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      LANG: en_NL
      TZ: Europe/Amsterdam
      KIOSK_IMMICH_API_KEY: ${KIOSK_API_KEY}
      KIOSK_SHOW_IMAGE_EXIF: true
      KIOSK_SHOW_IMAGE_LOCATION: true
      KIOSK_SHOW_IMAGE_DATE: true
      KIOSK_IMMICH_URL: http://immich-server:2283/
      KIOSK_IMMICH_EXTERNAL_URL: https://fotos.ferrybig.me/
      KIOSK_EXCLUDED_ALBUMS: c50c39bf-233e-490a-bafe-4dc21935d65b
    volumes:
      # Mount the directory with config.yaml inside
      - ./kiosk-config:/config
    restart: always
    #ports:
    #  - 127.0.0.1:2284:3000
    networks:
      proxy:
volumes:
  model-cache: null
include:
    - '../networks.docker-compose.yml'
networks:
  immich-net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0DB8:3::/64
```

### Your .env content

```Shell
HOST=::
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
# TZ=Etc/UTC
IMMICH_VERSION=release
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
KIOSK_API_KEY=<redacted
```

### Reproduction steps

1. Open Firefox 137.0.1
2. Upload the following video file to immich: https://www.dropbox.com/scl/fi/i8a2eq4zgxxm8798r6bdv/MVI_1773.AVI?rlkey=zxnkjse5ak04hoep99nrcja0j&st=b9qi9n1p&dl=0
3. Wait until immich has done its internal things (give it 1 minute, though I probably do not need to tell this to the makers of Immich)
4. Click on the video file to open it in Immich
Expected: The video file plays and the audio works

Actual: The video file only shows audio 

(Quick link to the uploaded file on my Immich server: https://fotos.ferrybig.me/share/1eFc-f0sBnFpcJUJQv4IriJzYIz4RQ2EsYO73s-bApRaW7mTwNcnBDGo2Gi9VfiR6no)

### Relevant log output

```shell

```

### Additional information

Note that Chromium 135.0.7049.52 plays the audio of the above file, Firefox 137.0.1 does not.

EDIT: The Android app also fails to play the sound
