### DISCUSSION TITLE
[BUG] Backing up photos from Android no longer works

### DISCUSSION THREAD

**Discussion by Levente96** [immich-app/immich#17857] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Letting the Android app upload the image brakes the image within Immich (aka. the local file on the phone is not modified ofc.)
Uploading the same image from the web interface marks it as duplicate; mirroring the image and uploading that (through the webpage), uploads the image correctly.

### The OS that Immich Server is running on

Linux ubuntu 5.15.0-1074-raspi #77-Ubuntu SMP PREEMPT Thu Feb 20 07:17:11 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

### Version of Immich Server

v1.132.1

### Version of Immich Mobile App

v1.132.1  build.2195

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
default
```

### Your .env content

```Shell
default
```

### Reproduction steps

1. Take a photo with Open Camera, ported Gcam or the built in camera app
2. Wait for the backup to happen
3. Check the website of Immich for the uploaded image: image is "Error uploading image"
4. The Android app does not complain, and marks the image as successfully backed up

The attached image shows how it look on the website, while also the image itself that fails to upload from the app.

![Image](https://github.com/user-attachments/assets/41e4b667-8111-4697-90f3-08d9f18278f8)

### Relevant log output

```shell
After uploading the image from the Android app:
immich_server            | [Nest] 16  - 04/24/2025, 4:33:37 PM     LOG [Api:EventRepository] Websocket Connect:    jrzYLUC7l3KV-eqtAAAn
immich_server            | [Nest] 16  - 04/24/2025, 4:33:37 PM   DEBUG [Api:LoggingInterceptor~pkczg8g9] GET /api/server/ping 200 0.64ms ::ffff:127.0.0.1
immich_server            | [Nest] 16  - 04/24/2025, 4:33:38 PM   DEBUG [Api:LoggingInterceptor~b9x7nqse] POST /api/assets/exist 200 13.77ms 80.108.203.112
immich_server            | [Nest] 16  - 04/24/2025, 4:33:38 PM VERBOSE [Api:LoggingInterceptor~b9x7nqse] {"deviceAssetIds":["1000000875"],"deviceId":"I_modified_this_when_copying_the_log"}
immich_server            | [Nest] 16  - 04/24/2025, 4:33:40 PM   DEBUG [Api:LoggingInterceptor~orguzybd] POST /api/assets 201 1151.61ms 80.108.203.112
immich_server            | [Nest] 16  - 04/24/2025, 4:33:40 PM VERBOSE [Api:LoggingInterceptor~orguzybd] {"deviceAssetId":"1000000875","deviceId":"I_modified_this_when_copying_the_log","fileCreatedAt":"2025-04-24T16:33:03.000Z","fileModifiedAt":"2025-04-24T16:33:03.000Z","isFavorite":"false","duration":"0:00:00.000000"}
immich_server            | [Nest] 16  - 04/24/2025, 4:33:50 PM     LOG [Api:EventRepository] Websocket Disconnect: jrzYLUC7l3KV-eqtAAAn

And in the android log it writes "Syncing completed."
```

### Additional information

This has been the case every now and then since I updated from v1.101 to v1.13x.

**Comment by danieldietzler** [comment]
Check the jobs page (https://my.immich.app/admin/jobs-status). Immich will be processing the thumbnails async after uploading.

**Comment by Levente96** [comment]
@danieldietzler Triggered the jobs manually, and after waiting for them to finish the issue still remain, it seems that this issue has been going on in my instance for several days at this point. (Also fails to load the preview with the following log as an example: )
```
immich_server            | [Nest] 16  - 04/24/2025, 4:59:56 PM   DEBUG [Api:LoggingInterceptor~soxnnnee] GET /api/assets/99872439-1009-4c41-9eb1-afba0ab9cef3/thumbnail?size=preview 200 51.07ms 80.108.203.112
immich_server            | [Nest] 16  - 04/24/2025, 4:59:56 PM   DEBUG [Api:GlobalExceptionFilter~soxnnnee] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
```

**Reply by bo0tzz** [reply]
What do the logs say when you trigger the jobs?

**Reply by danieldietzler** [reply]
Converted to a discussion because I'm fairly confident this is an issue with your install and not with Immich. Could you provide your compose and env file (instead of just saying default) and also share more logs, not just some log snippets?

**Reply by Levente96** [reply]
@bo0tzz 
```
immich_server            | [Nest] 16  - 04/24/2025, 5:03:23 PM   DEBUG [Api:LoggingInterceptor~8cuyn3kq] GET /api/jobs 200 27.46ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:27 PM   DEBUG [Api:JobService~po0u8kzv] Handling command: queue=thumbnailGeneration,command=start,force=false
immich_server            | [Nest] 16  - 04/24/2025, 5:03:27 PM   DEBUG [Api:LoggingInterceptor~po0u8kzv] PUT /api/jobs/thumbnailGeneration 200 10.53ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:27 PM VERBOSE [Api:LoggingInterceptor~po0u8kzv] {"command":"start","force":false}
immich_server            | [Nest] 16  - 04/24/2025, 5:03:28 PM   DEBUG [Api:LoggingInterceptor~sb5xu2gs] GET /api/server/ping 200 0.60ms ::ffff:127.0.0.1
immich_server            | [Nest] 16  - 04/24/2025, 5:03:29 PM   DEBUG [Api:LoggingInterceptor~jvjlqiqe] GET /api/jobs 200 24.77ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:34 PM   DEBUG [Api:LoggingInterceptor~m72wd6m4] GET /api/jobs 200 30.38ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:39 PM   DEBUG [Api:LoggingInterceptor~920difxi] GET /api/jobs 200 20.88ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:44 PM   DEBUG [Api:LoggingInterceptor~rzhq8h2d] GET /api/jobs 200 19.23ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:49 PM   DEBUG [Api:LoggingInterceptor~wmuvpepi] GET /api/jobs 200 21.23ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:54 PM   DEBUG [Api:LoggingInterceptor~mrne7z4m] GET /api/jobs 200 22.55ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:03:58 PM   DEBUG [Api:LoggingInterceptor~o2l204rf] GET /api/server/ping 200 0.47ms ::ffff:127.0.0.1
immich_server            | [Nest] 16  - 04/24/2025, 5:03:59 PM   DEBUG [Api:LoggingInterceptor~yn21cbbs] GET /api/jobs 200 21.55ms ::ffff:192.168.0.151
immich_server            | [Nest] 16  - 04/24/2025, 5:04:04 PM   DEBUG [Api:LoggingInterceptor~o068g16n] GET /api/server/statistics 200 98.08ms ::ffff:192.168.0.151
```

**Reply by danieldietzler** [reply]
There are no microservices logs at all. Are there any logs on start up indicating it failed starting?

**Reply by Levente96** [reply]
@danieldietzler 
For some reason 3 pictures got successfully uploaded among the ones that failed, I am also searching for some reasonable answer on my end. Hope I can help. In the meantime here are the requested files:
Compose:
```
version: '3'
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    expose:
      - 2283
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - proxiable
      - immich_local
    logging:
      driver: "journald"
      options:
        tag: "immich-server"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich_local

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich_local

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      - immich_local

volumes:
  model-cache:

networks:
  proxiable:
    name: proxiable
    external: true
  immich_local:
    name: immich_local
    driver: bridge

```
and the env:
```
 You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/md0/immich-library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=i_use_this_elsewhere_so_modified_it_:D

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

```
