### DISCUSSION TITLE
Error: ENOENT: no such file or directory for immich-server when importing (can't read metadata)

### DISCUSSION THREAD

**Discussion by Hammit** [immich-app/immich#17871] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Errors reading file metadata on initial import.

### The OS that Immich Server is running on

Ubuntu 24.04 Host Running Recommended Docker Compose Setup

### Version of Immich Server

v1.132.1

### Version of Immich Mobile App

v1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_MACHINE_LEARNING_VERSION:-release-openvino}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=Australia/Perth

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
#IMMICH_VERSION=v1.130.3
#IMMICH_MACHINE_LEARNING_VERSION=v1.130.3-openvino
#IMMICH_MACHINE_LEARNING_VERSION=v1.130.3
IMMICH_VERSION=release
IMMICH_MACHINE_LEARNING_VERSION=release-openvino

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. docker compose up
2. Login to Immich and enable Storage Template during setup (probably irrelevant)
3. Change user Storage Label (probably irrelevant)
4. On another computer, run immich-go (version doesn't seem to matter but I tried to use 0.25.0 and 0.25.3) and upload a google-photos takeout
5. Monitor the Immich logs. You will see a lot Error: ENOENT during the upload. immich-go will say no errors

### Relevant log output

```shell
8694a5f8-444a-426a-b080-52d8a7609c9c25, 12:23:59 PM   ERROR [Microservices:{"id":"5fbb9c69-1445-4be7-a7a5-9ca03b1ff15b","source":"sidecar-write"}] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/9f276f9e-c6fe-4c53-8264-85431576082c/a7/6a/a76a9a6d-c03e-4d28-ba55-9d43e3572ea0.jp
eg'ich_server  |     at async Promise.all (index 1)
immich_server  |     at async MetadataService.handleMetadataExtraction > (/usr/src/app/dist/services/metadata.service.js:141:35)_server  |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
immich_server  |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server  |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server  |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server  | [Nest] 7  - 04/25/2025, 12:23:59 PM    WARN [Microservices:Error: File not found - /usr/src/app/upload/upload/9f276f9e-c6fe-4c53-8264-85431576082c/a7/6a/a76a9a6d-c03e-4d28-ba559d43e3572ea0.jpegendored/dist/ExifToolTask.js:76:71)_server  |     at ReadTask.parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:47:167)
immich_server  |     at ReadTask._Task_resolve (/usr/src/app/node_modules/batch-cluster/dist/Task.js:146:40)] Error reading exif data (upload/upload/9f276f9e-c6fe-4c53-8264-85431576082c/a7/6a/a76a9a6d-c03e-4d28ba55-9d43e3572ea0.jpeg): Error: File not found - /usr/src/app/upload/upload/9f276f9e-c6fe-4c53-8264-85431576082c/a7/6a/a76a9a6d-c03e-4d28-ba55-9d43e3572ea0.jpegctory, stat 'upload/upload/9f276f9e-c6fe4c53-8264-85431576082c/d9/90/d990ea3d-d5b7-4b0f-9757-fb2b24e2f551.jp
eg'ich_server  |     at async Promise.all (index 1)
immich_server  |     at async MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:1
41:35)_server  |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
immich_server  |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server  |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server  |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

### Additional information

When I change the tag of the immich-machine-learning image to "release", I don't appear to get these errors. Only with "release-openvino".
