### DISCUSSION TITLE
Immich server hangs on start

### DISCUSSION THREAD

**Discussion by wuast94** [immich-app/immich#17978] [Q&A]
Dont know why but my immich server dont start anymore. the db server had an issue which i fixed, dont know if its related. 

```
immich_immich-server.1.majnnxpjaqd8@swarm04    | Initializing Immich v1.132.3
immich_immich-server.1.majnnxpjaqd8@swarm04    | DEBUG: cgroup v2 detected.
immich_immich-server.1.majnnxpjaqd8@swarm04    | DEBUG: No CPU limits set.
immich_immich-server.1.majnnxpjaqd8@swarm04    | Detected CPU Cores: 40
immich_immich-server.1.majnnxpjaqd8@swarm04    | Starting api worker
immich_immich-server.1.majnnxpjaqd8@swarm04    | Starting microservices worker
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 30  - 04/29/2025, 11:33:05 PM     LOG [Api:EventRepository] Initialized websocket server
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:MetadataService] Bootstrapping metadata service
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:MetadataService] Initializing metadata service
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:MapRepository] Initializing metadata repository
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 14
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 30  - 04/29/2025, 11:33:05 PM     LOG [Api:DatabaseRepository] Running migrations, this may take a while
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:05 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:06 PM     LOG [Microservices:ServerService] Feature Flags: {
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "smartSearch": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "facialRecognition": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "duplicateDetection": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "map": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "reverseGeocoding": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "importFaces": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "sidecar": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "search": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "trash": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "oauth": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "oauthAutoLaunch": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "passwordLogin": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "configFile": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "email": false
immich_immich-server.1.majnnxpjaqd8@swarm04    | }
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:06 PM     LOG [Microservices:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 20  - 04/29/2025, 11:33:06 PM     LOG [Microservices:StorageService] Successfully verified system mount folder checks
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 30  - 04/29/2025, 11:33:06 PM     LOG [Api:ServerService] Feature Flags: {
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "smartSearch": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "facialRecognition": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "duplicateDetection": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "map": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "reverseGeocoding": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "importFaces": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "sidecar": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "search": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "trash": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "oauth": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "oauthAutoLaunch": true,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "passwordLogin": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "configFile": false,
immich_immich-server.1.majnnxpjaqd8@swarm04    |   "email": false
immich_immich-server.1.majnnxpjaqd8@swarm04    | }
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 30  - 04/29/2025, 11:33:06 PM     LOG [Api:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
immich_immich-server.1.majnnxpjaqd8@swarm04    | [Nest] 30  - 04/29/2025, 11:33:06 PM     LOG [Api:StorageService] Successfully verified system mount folder checks
```

after this nothing happens anymore. 

```
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.132.3@sha256:6680d88486251b0264a78a1934fe82eef875555aa6d84d703a0980328a5d5c31
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/cephfs/docker/appdata/sftpgo/data/wuast94:/wuast94:rw
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}
      TZ: ${TZ}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_URL: ${DB_URL}
      IMMICH_API_METRICS_PORT: 8081
      IMMICH_MICROSERVICES_METRICS_PORT: 8082
      IMMICH_TELEMETRY_INCLUDED: all
      IMMICH_TRUSTED_PROXIES: 
      IMMICH_LOG_LEVEL: verbose
    healthcheck:
      test: [CMD-SHELL, /bin/true]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy_t2_proxy
      - immich
    depends_on:
      - redis
      - database
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.db == sqlite
      labels:
        - traefik.enable=true
        - traefik.http.routers.immich.entrypoints=https
        - traefik.http.routers.immich.rule=Host(``)
        - traefik.http.routers.immich.tls=true
        - traefik.http.routers.immich.middlewares=chain-auth@file
        - traefik.http.routers.immich.service=immich
        - traefik.http.services.immich.loadbalancer.server.port=2283

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.2-cuda@sha256:289d33718b92dcff0658e31fa1bbff0738130df326501cffb0382a93d0f0d40d
    volumes:
      - /sqliteshit/immich/mlmodels:/cache
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
      UPLOAD_LOCATION: ${UPLOAD_LOCATION}
      TZ: ${TZ}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    networks:
      - immich
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.db == sqlite

  redis:
    image: docker.io/redis:7.4-alpine@sha256:f773b35a95e170d92dd4214a3ec4859b1b7960bf56896ae687646d695f311187
    networks:
      - immich
    ulimits:
      memlock: -1
    volumes:
      - /mnt/cephfs/docker/appdata/immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

  db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    volumes:
      - /mnt/cephfs/docker/appdata/immich/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      TZ: ${TZ}
    networks:
      - immich
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.platform.arch == x86_64

networks:
  proxy_t2_proxy:
    external: true
  immich:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1450

```
db logs: 
```
2025-04-29 23:58:09.554 CEST [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-04-29 23:58:09.556 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-04-29 23:58:09.556 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2025-04-29 23:58:09.619 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-04-29 23:58:09.756 CEST [27] LOG:  database system was interrupted; last known up at 2025-04-29 22:49:13 CEST
[2025-04-29T21:58:09Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/269886".
[2025-04-29T21:58:09Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17591".
[2025-04-29T21:58:09Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17591/segments/5be69324-d223-43e7-ad77-e4f610c59edd".
[2025-04-29T21:58:10Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/269886/segments/d330014b-0766-462a-b61a-dd2fb10ad258".
2025-04-29 23:58:11.424 CEST [27] LOG:  database system was not properly shut down; automatic recovery in progress
2025-04-29 23:58:11.505 CEST [27] LOG:  redo starts at 3/4A000110
2025-04-29 23:58:11.505 CEST [27] LOG:  invalid record length at 3/4A0001F8: wanted 24, got 0
2025-04-29 23:58:11.505 CEST [27] LOG:  redo done at 3/4A0001C0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2025-04-29 23:58:11.727 CEST [1] LOG:  database system is ready to accept connections
```
redis logs
```
1:C 29 Apr 2025 22:07:25.209 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Apr 2025 22:07:25.209 * Redis version=7.4.3, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Apr 2025 22:07:25.209 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 29 Apr 2025 22:07:25.209 * monotonic clock: POSIX clock_gettime
1:M 29 Apr 2025 22:07:25.210 * Running mode=standalone, port=6379.
1:M 29 Apr 2025 22:07:25.211 * Server initialized
1:M 29 Apr 2025 22:07:25.253 * Loading RDB produced by version 7.4.3
1:M 29 Apr 2025 22:07:25.253 * RDB age 3 seconds
1:M 29 Apr 2025 22:07:25.253 * RDB memory usage when created 6.67 Mb
1:M 29 Apr 2025 22:07:25.272 * Done loading RDB, keys loaded: 183, keys expired: 15.
1:M 29 Apr 2025 22:07:25.272 * DB loaded from disk: 0.060 seconds
1:M 29 Apr 2025 22:07:25.272 * Ready to accept connections tcp
```
machine learning logs: 
```
[04/29/25 20:51:41] INFO     Starting gunicorn 23.0.0                           
[04/29/25 20:51:41] INFO     Listening at: http://[::]:3003 (21)                
[04/29/25 20:51:41] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[04/29/25 20:51:41] INFO     Booting worker with pid: 22                        
[04/29/25 20:51:43] INFO     Started server process [22]                        
[04/29/25 20:51:43] INFO     Waiting for application startup.                   
[04/29/25 20:51:43] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/29/25 20:51:43] INFO     Initialized request thread pool with 40 threads.   
[04/29/25 20:51:43] INFO     Application startup complete.       
```

i added the always true healtcheck because swarm constantly restarts the container if its unhealthy just to see if the container just needs more time to start. 

dont know if i should open an issue, tried also to increase the log level but i dont get any information that would help me find the issue :/
