### DISCUSSION TITLE
Machine learning request to "http://immich-machine-learning:3003" failed with status 500

### DISCUSSION THREAD

**Discussion by H4rl3k1n** [immich-app/immich#18011] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

since latest version 1.132.3 searchfunction doesnt work anymore. i tryed different clip models:
immich-app/XLM-Roberta-Large-Vit-B-16Plus
ViT-B-16-SigLIP-i18n-256__webli

### The OS that Immich Server is running on

Ubuntu Server 24.04 lts

### Version of Immich Server

1..132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /dockervolumes/immich/immich_cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /dockervolumes/immich/immich_redis:/data
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/dockervolumes/immich/immich_upload
DB_DATA_LOCATION=/dockervolumes/immich/immich_postgres
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_VERSION=v1.132.3
```

### Reproduction steps

1. upgrade to version 1.132.3
2. use search function

### Relevant log output

```shell
[Nest] 17  - 05/01/2025, 6:45:55 AM    WARN [Api:MachineLearningRepository~m3pj7itl] Machine learning request to "http://immich-machine-learning:3003" failed with status 500: Internal Server Error

[Nest] 17  - 05/01/2025, 6:45:55 AM   ERROR [Api:ErrorInterceptor~m3pj7itl] Unknown error: Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-16-SigLIP-i18n-256__webli","options":{"language":"de"}}}}' failed for all URLs

Error: Machine learning request '{"clip":{"textual":{"modelName":"ViT-B-16-SigLIP-i18n-256__webli","options":{"language":"de"}}}}' failed for all URLs

    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:121:26)

    at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:62:27)
```

### Additional information

i tryed the usual stuff:
new machine learning intelligent search, reboot, restart, reinstall but always get this error.

i tryed a fallback to 1.131.3, here the searchfunction works fine.
