### DISCUSSION TITLE
iOS Mobile app - does not show the image is synced but it is

### DISCUSSION THREAD

**Discussion by holas1337** [immich-app/immich#18095] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

In the iOS APP when I sync photo/video using backup (I am calling it manually from time to time) it is uploaded to the server, processed and visible through the web and backup shows all is backed up but on my phone it looks like the something is wrong with photos.

The cloud has no checkmark and the loading animation is never ending.

![Image](https://github.com/user-attachments/assets/648f9809-cbcc-4902-8b38-3197a309329c)

![Image](https://github.com/user-attachments/assets/a2fbba33-fd6e-47f4-be29-eb63a8f813c2)

Also the list reloads with the fotos from the server after killing the app and opening it again only.

It started after the upgrading from v1.131.3. I did no changed the app configuration since then (only updated the docker compose with new redis image when updating) and it worked before.
You can see the photo

![Image](https://github.com/user-attachments/assets/263982d9-ddbe-4ade-892a-13a4f16efb86)

the cloud has checkmark and this is the last photo uploaded using old version.

### The OS that Immich Server is running on

Raspberry Pi 5 - Linux rpi 6.12.20+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.20-1+rpt1~bpo12+1 (2025-03-19) aarch64 GNU/Linux

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
My docker-compose.yaml is original taken from the release I am using.
I am using docker-compose.override.yml to adjust it with the content below

services:
  immich-server:
    restart: ${RESTART}
    networks:
      - web
      - default
    user: "${UID}:${GID}"
    labels:
      - traefik.enable=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.http.routers.immich.rule=Host(`${URL}`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=${CERTRESOLVER}
      - traefik.http.routers.immich.tls=true
      - traefik.docker.network=web
      - traefik.http.routers.immich.middlewares=gzip

  immich-machine-learning:
    volumes:
      - ${APP_MODEL_CACHE_LOCATION}:/cache
    restart: ${RESTART}
    networks:
      - default

  redis:
    restart: ${RESTART}
    networks:
      - default

  database:
    restart: ${RESTART}
    networks:
      - default

networks:
    default:
    web:
        external: true
```

### Your .env content

```Shell
# Nothing special here
# APP_VERSION=release
APP_VERSION=v1.132.3
APP_UPLOAD_LOCATION=./web/library
APP_DB_DATA_LOCATION=./data/postgres
APP_MODEL_CACHE_LOCATION=./data/model_cache

URL=CENSORED
CERTRESOLVER=le
UID=1000
GID=1000
RESTART=always

### >>> Immich ENV
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
UPLOAD_LOCATION=${APP_UPLOAD_LOCATION}
DB_DATA_LOCATION=${APP_DB_DATA_LOCATION}
IMMICH_VERSION=${APP_VERSION}
DB_PASSWORD=CENSORED
DB_USERNAME=CENSORED
DB_DATABASE_NAME=CENSORED
### <<< Immich ENV
```

### Reproduction steps

Probably just sync images using iOS app.

### Relevant log output

```shell
there is no logs in the mobile or web app related to this
```
