### DISCUSSION TITLE
Upgraded to v1.113.0 Meet:[Api:QueryFailedError: relation "smart_info" does not exist

### DISCUSSION THREAD

**Discussion by hanshanglin** [immich-app/immich#18217] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I just try to update my immich server version from **v1.112.0 to v1.113.0**, then the thing went wrong.
On web, once click a photo or goto explore page, meet a 500 error.

Error info on the website:
Error: Error: 500
    at Object.fe [as ok] (http://xxx.xxx.com:52283/_app/immutable/chunks/fetch-client.nroxF77n.js:1:2872)
    at async Promise.all (index 0)
    at async ge (http://xxx.xxx.com:52283/_app/immutable/nodes/9.S5xvL1kx.js:1:975)
    at async Re (http://xxx.xxx.com:52283/_app/immutable/chunks/entry.BaWV2bvl.js:1:13734)

### The OS that Immich Server is running on

docker 

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.113.0
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /share/Container/immich/immich_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    environment:
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      HF_ENDPOINT: https://hf-mirror.com
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      HF_ENDPOINT: https://hf-mirror.com
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /share/Container/immich/immich_db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' || exit 1; Chksum="$$(psql --dbname='immich' --username='postgres' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
no .env file
```

### Reproduction steps

1. update from v1.112.0 to v1.113.0
2. go to website 
3. click any photo, or go to xxx/explore
4. 500!!

### Relevant log output

```shell
[Nest] 32  - 05/11/2025, 3:03:10 PM   ERROR [Api:QueryFailedError: relation "smart_info" does not exist
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
immich_server            |     at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
immich_server            |     at async AssetRepository.getAssetIdByTag (/usr/src/app/dist/repositories/asset.repository.js:525:23)
immich_server            |     at async Promise.all (index 1)
immich_server            |     at async SearchService.getExploreData (/usr/src/app/dist/services/search.service.js:61:25)~94df6ymo] Failed to get explore data
immich_server            | [Nest] 32  - 05/11/2025, 3:03:10 PM   ERROR [Api:QueryFailedError: relation "smart_info" does not exist
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
immich_server            |     at async SelectQueryBuilder.getRawMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:646:29)
immich_server            |     at async AssetRepository.getAssetIdByTag (/usr/src/app/dist/repositories/asset.repository.js:525:23)
immich_server            |     at async Promise.all (index 1)
immich_server            |     at async SearchService.getExploreData (/usr/src/app/dist/services/search.service.js:61:25)~94df6ymo] QueryFailedError: relation "smart_info" does not exist
```
