### DISCUSSION TITLE
Uloading a Single Photo under 1MB is Slow or takes too long to Upload.

### DISCUSSION THREAD

**Discussion by kenrmayfield** [immich-app/immich#18366] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

In the Immich WEB Interface, Uploading a Single Photo that is under 1MB is Extremely Slow.

Machine Learning is Turned Off.

### The OS that Immich Server is running on

Alpine

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

NONE

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.y
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl]
    volumes:
      # Do not edit the next line. If you want to change the media storage locat
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
- /immich-app/docker-compose.yml 1/79 1%
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immi

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supp
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifi
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spac
DB_PASSWORD=ZWRiMTQ4OD

# The values below this line do not need to be changed
################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
~
- /immich-app/.env 1/22 4%
```

### Reproduction steps

1. Uploading a Single Photo that is under 1MB.
2.
3.
...

### Relevant log output

```shell

```
