### DISCUSSION TITLE
Immich_server does not start

### DISCUSSION THREAD

**Discussion by John710** [immich-app/immich#18513] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi. I updated v1.133.0 according to the instructions, but I can't start the server.

### The OS that Immich Server is running on

Linux raspberry 6.12.25+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.25-1+rpt1 (2025-04-30) aarch64 GNU/Linux

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    #command: [ "start.sh", "immich" ]
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      t3_proxy:
        ipv4_address: 192.168.90.23
     # home-network:
     #   ipv4_address: 192.168.92.33
      db-network:
        ipv4_address: 192.168.93.33
    #ports:
    #  - 2283:2283
    environment:
      REDIS_HOSTNAME: $REDIS_HOSTNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_HOSTNAME: $DB_HOSTNAME
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich_postgres
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.immich-rtr.entrypoints=websecure"
      - "traefik.http.routers.immich-rtr.rule=Host(`photo.$DOMAINNAME_1`)"
      # Middlewares
      #- "traefik.http.routers.homepage-rtr.middlewares=chain-basic-auth@file"
      - "traefik.http.routers.immich-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      db-network:
        ipv4_address: 192.168.93.16
    environment:
      REDIS_HOSTNAME: $REDIS_HOSTNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_HOSTNAME: $DB_HOSTNAME
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    volumes:
      - $APPDATA/immich/machine:/cache

  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0  #docker.io/tensorchord/pgvecto-rs:pg15-v0.3.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      db-network:
        ipv4_address: 192.168.93.32
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - $APPDATA/immich/pgvecto:/var/lib/postgresql/data
    #command:
    #  [
    #    'postgres',
    #    '-c',
    #    'shared_preload_libraries=vectors.so',
    #    '-c',
    #    'search_path="$$user", public, vectors',
    #    '-c',
    #    'logging_collector=on',
    #    '-c',
    #    'max_wal_size=2GB',
    #    '-c',
    #    'shared_buffers=512MB',
    #    '-c',
    #    'wal_compression=on',
    #  ]
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich
IMMICH_VERSION=release
REDIS_HOSTNAME=redis
DB_PASSWORD=********************
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_DATABASE_NAME=immich
```

### Reproduction steps

Stopped the containers
Checked if there is a backup
Edited the yml
Pull and start compose.
All containers except the server start. The server error is attached below.

### Relevant log output

```shell
Initializing Immich v1.133.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 05/23/2025, 2:18:52 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 05/23/2025, 2:18:52 AM     LOG [Api:EventRepository] Initialized websocket server
/usr/src/app/node_modules/postgres/cjs/src/connection.js:388
    if (!query || typeof query !== 'object' || !query.reject) throw err
                                                              ^
Error: getaddrinfo EAI_AGAIN immich_postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'immich_postgres'
}
Node.js v22.14.0
microservices worker error: Error: getaddrinfo EAI_AGAIN immich_postgres, stack: Error: getaddrinfo EAI_AGAIN immich_postgres
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
microservices worker exited with code 1
Killing api process
```
