### DISCUSSION TITLE
Authentik OAuth Login fails

### DISCUSSION THREAD

**Discussion by noahtrr** [immich-app/immich#18556] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

![Image](https://github.com/user-attachments/assets/cfdfdb97-64fa-4648-90f5-2ae435b623b9)
![image](https://github.com/user-attachments/assets/bff271f3-9ef3-4254-ba2b-6cba25c809de)
![Image](https://github.com/user-attachments/assets/68f9b8ae-b022-4a55-86ac-00bbda7196d6)

### The OS that Immich Server is running on

Ubuntu 24.10 LXC

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.Set up compose with compose file provided by the docs
2. Set up OAuth Provider in authentik
3. Add OAuth Provider via WebUi
4. Won't work
...

### Relevant log output

```shell
[Nest] 17  - 05/23/2025, 10:13:03 PM   ERROR [Api:OAuthRepository~078gja7n] OAuth login failed: server responded with an error in the response body
[Nest] 17  - 05/23/2025, 10:13:03 PM   ERROR [Api:OAuthRepository~078gja7n] ResponseBodyError: server responded with an error in the response body
    at checkOAuthBodyError (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:865:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async processGenericAccessTokenResponse (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1141:5)
    at async processAuthorizationCodeOAuth2Response (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1373:20)
    at async authorizationCodeGrant (file:///usr/src/app/node_modules/openid-client/build/index.js:942:18)
    at async OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:53:28)
    at async AuthService.callback (/usr/src/app/dist/services/auth.service.js:178:25)
    at async OAuthController.finishOAuth (/usr/src/app/dist/controllers/oauth.controller.js:46:22) {
  cause: {
    error: 'invalid_client',
    error_description: 'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)'
  },
  code: 'OAUTH_RESPONSE_BODY_ERROR',
  error: 'invalid_client',
  status: 400,
  error_description: 'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)'
}
[Nest] 17  - 05/23/2025, 10:13:03 PM   ERROR [Api:ErrorInterceptor~078gja7n] Unknown error: Error: OAuth login failed
Error: OAuth login failed
    at OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:69:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AuthService.callback (/usr/src/app/dist/services/auth.service.js:178:25)
    at async OAuthController.finishOAuth (/usr/src/app/dist/controllers/oauth.controller.js:46:22
```

### Additional information

Running behind caddy:

@immich host immich.example.com
        handle @immich {
                reverse_proxy http://192.168.0.11:2283
        }
