### DISCUSSION TITLE
role "root" does not exist on v1.133.0

### DISCUSSION THREAD

**Discussion by wesleykirkland** [immich-app/immich#18565] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

`FATAL:  role "root" does not exist` is consistently produced in the DB with the new `ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0` image. I saw an existing issue stating to start with a fresh DB and restore the DB. I've done this and the error is still being produced.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.133.0

### Version of Immich Mobile App

1.133.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
# Backups - https://immich.app/docs/administration/backup-and-restore/
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich
networks:
  proxy:
    external: true
  default:
  br0:
    external: true
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices: # Copied fom hwaccel.yml
      - /dev/dri:/dev/dri
    volumes:
      - immich_storage:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    networks:
      br0:
        ipv4_address: 10.x.x.x
      default:
      proxy:
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 3G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`${DNS}.REDACTED.TLD`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=cloudflare"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.docker.network=proxy"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=5000000000" # optional, only necessary for file uploads; allow 5000MB
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=5000000000" # optional, only necessary for file uploads; allow 5000MB
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=5000000000" # optional, only necessary for file uploads; allow 5000MB
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=5000000000" # optional, only necessary for file uploads; allow 5000MB
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
    networks:
      - default
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 4G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    restart: always
    networks:
      - default
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    networks:
      - default
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    env_file:
      - .env
    ports:
      - 3010:3000
    environment:
      IMMICH_URL: "https://${DNS}.REDACTED.TLD"
      EXTERNAL_IMMICH_URL: "https://${DNS}.REDACTED.TLD"
    networks:
      - default
      - proxy
      # - br0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

  # https://www.reddit.com/r/docker/comments/d0ipuu/glances_and_traefik/
  immich-power-tools-proxy:
    image: alpine/socat:latest
    container_name: immich_power_tools_proxy
    entrypoint: /bin/sh
    command: >
      -c "ip -4 route list match 0/0 | awk '{print $$3\" host.docker.internal\"}' >> /etc/hosts
      && socat tcp-listen:3010,fork,reuseaddr tcp-connect:host.docker.internal:3010"
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immichpowertools.rule=Host(`${DNS}-powertools.REDACTED.TLD`)"
      - "traefik.http.routers.immichpowertools.entrypoints=websecure"
      - "traefik.http.routers.immichpowertools.tls.certresolver=cloudflare"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.immichpowertools.loadbalancer.server.port=3010"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://syslog.REDACTED.TLD:12201"
        tag: "{{.Name}}" # Optional: Tag your logs with container name

volumes:
  pgdata:
    name: pgdata
    driver_opts:
      type: nfs
      o: addr=10.x.x.x,nolock,soft
      device: :/volume1/docker/immich/pgdata
  model-cache:
    name: model-cache
    driver_opts:
      type: nfs
      o: addr=10.x.x.x,nolock,soft
      device: :/volume1/docker/immich/model_cache
  immich_storage:
    name: immich_storage
    driver_opts:
      type: nfs
      o: addr=10.x.x.x,nolock,soft
      device: :/volume2/fsp04/Photo_Library
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/disk1/plex/photos
TZ=America/New_York
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DNS=immich
GOOGLE_MAPS_API_KEY=REDACTED
#######PowerTools######
DB_HOST=immich_postgres
DB_PORT=5432
GEMINI_API_KEY=REDACTED
```

### Reproduction steps

1. Existing Immich, I believe I started around v0.80.0 and I've upgraded from there.
2. Upgrade to v1.133.0
3. DB produces `FATAL:  role "root" does not exist` every minute or so. I've traced this back in my SIEM and it started first on.

```
image_id
sha256:c0bbffd020b13d92f472b1487547c4aae244ce317544b28de75644562e5280f2
image_name
ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
```
...

### Relevant log output

```shell
2025-05-23 21:07:11.911 EDT [190] FATAL:  role "root" does not exist
2025-05-23 21:07:42.044 EDT [199] FATAL:  role "root" does not exist
2025-05-23 21:07:42.538 EDT [201] FATAL:  role "root" does not exist
2025-05-23 21:08:13.094 EDT [219] FATAL:  role "root" does not exist
2025-05-23 21:08:13.354 EDT [221] FATAL:  role "root" does not exist
2025-05-23 21:08:43.525 EDT [234] FATAL:  role "root" does not exist
2025-05-23 21:08:43.605 EDT [236] FATAL:  role "root" does not exist
2025-05-23 21:13:43.876 EDT [278] FATAL:  role "root" does not exist
2025-05-23 21:13:43.927 EDT [280] FATAL:  role "root" does not exist
2025-05-23 21:18:44.077 EDT [303] FATAL:  role "root" does not exist
2025-05-23 21:18:44.115 EDT [305] FATAL:  role "root" does not exist
```
