### DISCUSSION TITLE
Immich v1.133.1 DB migration failed, null value in "naturalearth_countries"

### DISCUSSION THREAD

**Discussion by fralalonde** [immich-app/immich#18617] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

# Context
Docker running in dedicated debian VM instance running on proxmox. /image folder is an NFS share to a local proxmox hosted ZFS partition. 

# Problem
Upgrading immich from a version not older than a month (1.132?). 

Updated container immich server fails to come up after some time. Logs show that DB migration failed on non-null constraint.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

1.133.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=postgres
```

### Reproduction steps

```
docker compose pull
docker compose down
docker compose up -d
```

### Relevant log output

```shell
[...]
6095,-5.879815), (124.037446,-5.914321), (124.046397,-5.925714), (124.057628,-5.951104), (124.065196,-5.962498))',
    ... 16996 more items
  ]
}
[Nest] 7  - 05/25/2025, 6:10:23 PM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: PostgresError: null value in column "id" of relation "naturalearth_countries" violates not-null constraint
PostgresError: null value in column "id" of relation "naturalearth_countries" violates not-null constraint
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
Error: Metadata service init failed
    at MetadataService.init (/usr/src/app/dist/services/metadata.service.js:93:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MetadataService.onBootstrap (/usr/src/app/dist/services/metadata.service.js:72:9)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async MicroservicesModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
    at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)
    at async bootstrap (/usr/src/app/dist/workers/microservices.js:25:5)
microservices worker error: Error: Metadata service init failed, stack: Error: Metadata service init failed
    at MetadataService.init (/usr/src/app/dist/services/metadata.service.js:93:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MetadataService.onBootstrap (/usr/src/app/dist/services/metadata.service.js:72:9)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async MicroservicesModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
    at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)
    at async bootstrap (/usr/src/app/dist/workers/microservices.js:25:5)
microservices worker exited with code 1
Killing api process
Initializing Immich v1.133.1
Detected CPU Cores: 4


docker-compose .yaml is untouched from first install:

QEMU Vm specs are 


agent: enabled=1
balloon: 2048
boot: c
bootdisk: scsi0
cores: 4
cpu: x86-64-v2-AES
ide2: zfs:vm-104-cloudinit,media=cdrom
ipconfig0: ip=dhcp,ip6=auto
memory: 4096
meta: creation-qemu=9.0.2,ctime=1738452710
name: immich
net0: virtio=BC:24:11:88:AF:29,bridge=vmbr0,firewall=1
numa: 0
onboot: 1
ostype: l26
scsi0: zfs:vm-104-disk-0,discard=on,size=24G
scsihw: virtio-scsi-pci
searchdomain: lan
serial0: socket
sockets: 1
[...]
```
