### DISCUSSION TITLE
Learning Container error - "No Module named 'gunicorn'

### DISCUSSION THREAD

**Discussion by dcastle85** [immich-app/immich#18635] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I updated recently to [v1.133.1] and found that my smart search is failing.  Failed to Smart search - Immich Server Error

### The OS that Immich Server is running on

Portainer - UGreen NAS

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1000:10
    environment:
      - TZ=Europe/London
    volumes:
      - /volume2/immich/redis:/data:rw
    restart: always

  immich-db:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.0
    container_name: Immich-db
    hostname: immich-db
    environment:
      - TZ=Europe/London
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=********
    volumes:
      - /volume2/immich/db:/var/lib/postgresql/data:rw
    restart: always

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    device_cgroup_rules:
     - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    container_name: Immich-SERVER
    hostname: immich-server
    privileged: true
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume2/immich/library/thumbs:/usr/src/app/upload/thumbs
      - /volume1/FamilyVault/Photos:/volume1/FamilyVault/Photos
      - /home/dcastle85/Photos:/home/dcastle85/Photos
      - /home/Lisa/Photos:/home/Lisa/Photos
    restart: always
    healthcheck:
      disable: true
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    container_name: Immich-LEARNING
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    hostname: immich-machine-learning
    privileged: true
    user: "0"
    group_add:
      - "1000"
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
      - /usr/lib/wsl:/usr/lib/wsl
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /volume2/immich/cache:/cache:rw
      - /volume2/immich/matplotlib:/matplotlib:rw
    environment:
      - NEOReadDebugKeys=1
      - OverrideGpuAddressSpace=48
      - HUGGINGFACE_MIRROR=https://mirror-site-url   # Optional, replace with actual mirror if needed
      - OPENVINO_DEVICE=GPU
      - LIBVA_DRIVER_NAME=iHD
      - OPENVINO_CL_DEVICE=GPU
      - INTEL_OPENCL_DEVICE=GPU
      
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    ports:
      - 3003:3003
    depends_on:
      immich-db:
        condition: service_started

volumes:
   model-cache:
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Europe/London
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=*******
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=,********
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
EXTERNAL_IMMICH_URL=https://external-address
THUMB_LOCATION=/volume2/immich/library/thumbs
UPLOAD_LOCATION=/volume1/FamilyVault/upload
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
2025-05-25T20:11:12.648157379Z Traceback (most recent call last):
2025-05-25T20:11:12.648189108Z   File "<frozen runpy>", line 198, in _run_module_as_main
2025-05-25T20:11:12.648195538Z   File "<frozen runpy>", line 88, in _run_code
2025-05-25T20:11:12.648199939Z   File "/usr/src/immich_ml/__main__.py", line 6, in <module>
2025-05-25T20:11:12.648205476Z     from .config import log, non_prefixed_settings, settings
2025-05-25T20:11:12.648208978Z   File "/usr/src/immich_ml/config.py", line 8, in <module>
2025-05-25T20:11:12.648300806Z     from gunicorn.arbiter import Arbiter
2025-05-25T20:11:12.648314160Z ModuleNotFoundError: No module named 'gunicorn'
```
