### DISCUSSION TITLE
env_file, environment and .env only work on the current working directory

### DISCUSSION THREAD

**Discussion by jolly-jump** [immich-app/immich#1867] [General]
Ok this is hard to explain: I wanted to integrate the docker-compose into my greater docker-compose containing an nginx-reverse-proxy and more...

Normally this works out of the box, this time I stumbled across the usage of env_file and the `.env`-file:
My conclusion is: I **have to** put the .env file  where the docker-compose file is, and I cannot do the following:

```
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:release
    restart: always
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    env_file:
      - ./immich/.env
    volumes:
      - "${UPLOAD_LOCATION}:/usr/src/app/upload"
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-redis
      - immich-db
```
The problem is not that I cannot rename the `.env`-file or put it in a sub-directory which I usually do. The containers still get the env-variables set.
The problem is, that the replacement in the docker-compose file then does not take place anymore.

Although [this here](https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-with-an-env-file) suggest, that you could do what I wanted, 
> The .env file should be placed at the root of the project directory next to your docker-compose.yml file. You can use an alternative path with one of the following methods:
> 
>     The --file option in the CLI
>     The --env-file option in the CLI
>     Using the env_file attribute in the Compose file

The last bit just does not work: If i put the env_file to point to some other file, the TAGS get not replaced in the docker-compose.yml.

The [SA-Answer here](https://stackoverflow.com/a/72368718) explains what I experience, while the other answers there seem to miss the point.

My point for the installation is:
- Maybe one should not use `env_file` **and** use the values in `.env` to replace variables in the docker-compose since they serve different purposes.
- On the other hand, I have no better idea than to hardcode the UPLOAD_LOCATION in the docker-compose.yml once it is set up and rename the variables DB_USERNAME to POSTGRES_USER etc. in the .env file. Then the `.env`-file serves only the purpose for the containers, not for the docker-compose file and can be moved and renamed however one wants.

Just in case, someone tries the same like me :)
