### DISCUSSION TITLE
Immich exclusively uses IPv4 for hosting both the git repository and container images

### DISCUSSION THREAD

**Discussion by dmpmem** [immich-app/immich#18907] [Feature Request]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Due to immich's use of IPv4-exclusive hosting - github - for both it's container registry (ghcr.io), and it's git (github.com), an IPv6-only server (such as the one I run; it's on an infrastructure provider that cannot provide IPv4 links due to the AS having none allocated) cannot fetch images, nor automatically build them.

This issue exists for the sake of kindly requesting that immich maintainers maintain publicly listed "official" images on some other repository - in addition to ghcr - that accepts IPv6 requests. This could be, for example, [quay.io](https://quay.io), [hub.docker.com](https://hub.docker.com), or a self-hosted quay or [zot](https://zotregistry.dev/) registry, or something completely different.

Additionally, it would be nice if source blobs also existed outside of github - be it a cgit that always follows HEAD and copies over tags, a [codeberg](https://codeberg.org) repository (which can also [host images](https://forgejo.org/docs/latest/user/packages/container/) if the desire to use the same platform for both arises) that could just mirror HEAD and tags (or the entire repo)/another forgejo instance that's hosted elsewhere doing the same, or something completely different - however this is harder to implement and less crucial for IPv6-enabled adoption

### The OS that Immich Server is running on

Alpine Linux, but this isn't relevant

### Version of Immich Server

N/A

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=temporarytestinstance

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Get IPv6-only host - or remove your IPv4 link/blacklist your kernel's IPv4 stack/compile it without one
2. `podman compose pull` (or `podman compose up -d` if images were previously not locally available)
3. See errors contacting the container registry

### Relevant log output

```shell

```

### Additional information

Would appreciate this to be solved at some point soonish; I really want to self-host immich to try it out, but all of my server infrastructure that I trust enough with my data or with hosting & regularly rebuilding images that in turn process my data are IPv6-only.
