### DISCUSSION TITLE
microservices worker error: Error: write CONNECT_TIMEOUT immich-db:5432, stack: Error: write CONNECT_TIMEOUT immich-db:5432

### DISCUSSION THREAD

**Discussion by dwantstocode** [immich-app/immich#19362] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

[_Immich-SERVER_logs.txt](https://github.com/user-attachments/files/20831659/_Immich-SERVER_logs.txt)

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.135.0

### Version of Immich Mobile App

v1.135.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: $PUID:$PGID
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/immich_backup/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich_backup/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_DB=immich
      - POSTGRES_USER=<user>
      - POSTGRES_PASSWORD=<password>
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: Immich-SERVER
    hostname: immich-server
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 2283:2283
    volumes:
      - /volume1/docker/immich_backup/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: $PUID:$PGID
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich_backup/upload:/usr/src/app/upload:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=America/Los_Angeles
DB_HOSTNAME=immich-db
DB_USERNAME=<user>
DB_PASSWORD=<password>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=<secret>
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
PUID=<PUID>
PGID=<PGID>
IMMICH_VERSION=v1.135.0
```

### Reproduction steps

1. Watchtower updated to v1.135.1 but read it had issues, so tried to downgrade back to 1.135.0
2. Immich sever cannot start with the following error
3.
...

### Relevant log output

```shell
}
Error: connect ETIMEDOUT
    at Socket.<anonymous> (/usr/src/app/node_modules/ioredis/built/Redis.js:170:41)
    at Object.onceWrapper (node:events:632:28)
    at Socket.emit (node:events:518:28)
    at Socket._onTimeout (node:net:609:8)
    at listOnTimeout (node:internal/timers:594:17)
    at process.processTimers (node:internal/timers:529:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect'
}
microservices worker error: Error: write CONNECT_TIMEOUT immich-db:5432, stack: Error: write CONNECT_TIMEOUT immich-db:5432
    at connectTimedOut (/usr/src/app/node_modules/postgres/cjs/src/connection.js:257:20)
    at Timeout.done [as _onTimeout] (/usr/src/app/node_modules/postgres/cjs/src/connection.js:1035:8)
    at listOnTimeout (node:internal/timers:596:11)
    at process.processTimers (node:internal/timers:529:7)
microservices worker exited with code 1
Killing api process
```
