### DISCUSSION TITLE
Remove useless "folders" bar on top

### DISCUSSION THREAD

**Discussion by WhyNotHugo** [immich-app/immich#19372] [Feature Request]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When viewing photos via the "folders" view, there's a large bar on top which merely says the name of this feature, "folders":

![Screenshot showing the bar](https://github.com/user-attachments/assets/84fe14da-d5fc-48fa-966d-768531f7caa2)

This bar has not useful content and no controls, but takes up vertical space (of which only ~60% serves the main content).

The other bars here all have some useful content or controls (regardless of whether one might think they are essential or not).

Removing this bar is an easy way to increase the amount of content that fits on screen.

### The OS that Immich Server is running on

docker-compose

### Version of Immich Server

release

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    # TODO: pin to an exact version?
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ./.immich_upload:/usr/src/app/upload
      - ./Photos:/library:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ./.immich_postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

  proxy:
    image: alpine/socat
    command: >
      TCP-LISTEN:2283,fork,reuseaddr TCP:immich-server:2283
    ports:
      - "2283:2283"
    networks:
      - internal
      - dmz

volumes:
  model-cache:

networks:
  internal:
    driver: bridge
    internal: true
  dmz:
    driver: bridge   # Has host access
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. In Account Settings > Features, enable both toggles for "folders" feature.
2. Navigate to the folders view on the sidebar.

### Relevant log output

```shell
n/a
```
