### DISCUSSION TITLE
"Latest Version" outdated on mobile app

### DISCUSSION THREAD

**Discussion by aaronjamt** [immich-app/immich#19495] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I just updated my Immich server from v1.132.3 to v1.135.3 and both before and after the update, my Android phone says "Latest Version: v1.132.3", and the Immich server has the following error on startup:
```
[Nest] 17  - 06/24/2025, 1:32:56 PM    WARN [Api:Error: Failed to fetch GitHub release: TypeError: fetch failed
    at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/repositories/server-info.repository.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async VersionService.handleVersionCheck (/usr/src/app/dist/services/version.service.js:111:77)
    at async VersionService.onBootstrap (/usr/src/app/dist/services/version.service.js:64:9)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async ApiModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
    at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
```

### The OS that Immich Server is running on

Unraid OS v7.0.1

### Version of Immich Server

v1.135.3 (updated from v1.132.3 to v1.133.0 to v1.135.0 to v1.135.3)

### Version of Immich Mobile App

v1.135.1 build.202

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal
      - publish

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

  tailscale:
    image: ghcr.io/tailscale/tailscale:stable
    restart: always
    depends_on:
      - immich-server
    links:
      - immich-server
    environment:
      - TS_HOSTNAME=immich
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/var/lib/tailscale/ts-serve.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${TS_CONFIG_LOCATION}:/var/lib/tailscale
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    networks:
      - internal
      - public

networks:
  internal:
    internal: true
  publish:
    external: true
  public:

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/appdata/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/appdata/immich/postgres
# The location where the Tailscale configuration files are stored
TS_CONFIG_LOCATION=/mnt/user/appdata/immich/tailscale

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.135.3

# Preload all machine learning models and never unload them
MACHINE_LEARNING_MODEL_TTL=0
MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=ViT-B-16-SigLIP2__webli
MACHINE_LEARNING_PRELOAD__CLIP__VISUAL=ViT-B-16-SigLIP2__webli
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__RECOGNITION=antelopev2
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION__DETECTION=antelopev2

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[REDACTED]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=[REDACTED]
DB_DATABASE_NAME=[REDACTED]
```

### Reproduction steps

1. Start Immich
2. Check the `immich_server` container logs

### Relevant log output

```shell
[Nest] 17  - 06/24/2025, 1:32:56 PM    WARN [Api:Error: Failed to fetch GitHub release: TypeError: fetch failed
    at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/repositories/server-info.repository.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async VersionService.handleVersionCheck (/usr/src/app/dist/services/version.service.js:111:77)
    at async VersionService.onBootstrap (/usr/src/app/dist/services/version.service.js:64:9)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async ApiModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
    at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
```
