### DISCUSSION TITLE
ENOTFOUND database - Unable to start Immich Server

### DISCUSSION THREAD

**Discussion by Anon666333** [immich-app/immich#19533] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

This randomly started happening today, after having no issues at all.

I'm having this repeat in the logs, and the Immich Server will not start.

```
[Nest] 7  - 06/25/2025, 12:14:25 PM     LOG [Microservices:EventRepository] Initialized websocket server

microservices worker error: Error: getaddrinfo ENOTFOUND database, stack: Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

microservices worker exited with code 1

Killing api process

Initializing Immich v1.135.3

Detected CPU Cores: 48

Starting api worker

Starting microservices worker

[Nest] 7  - 06/25/2025, 12:15:31 PM     LOG [Microservices:EventRepository] Initialized websocket server

microservices worker error: Error: getaddrinfo ENOTFOUND database, stack: Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

microservices worker exited with code 1

Killing api process
```

### The OS that Immich Server is running on

Docker on Ubuntu 24.10

### Version of Immich Server

1.135.3

### Version of Immich Mobile App

v1.135.1 build.202

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
     # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
     # DB_STORAGE_TYPE: 'HDD'      
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/matt/immich_data
DB_DATA_LOCATION=/home/matt/docker/immich_db
IMMICH_VERSION=release
DB_PASSWORD=supersecretpassword
DB_USERNAME=supersecretusername
DB_DATABASE_NAME=immich
TZ=America/Toronto
```

### Reproduction steps

1. Start immich? 
2. I'm sorry I have no idea what caused this.
3.
...

### Relevant log output

```shell
[Nest] 7  - 06/25/2025, 12:14:25 PM     LOG [Microservices:EventRepository] Initialized websocket server

microservices worker error: Error: getaddrinfo ENOTFOUND database, stack: Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

microservices worker exited with code 1

Killing api process

Initializing Immich v1.135.3

Detected CPU Cores: 48

Starting api worker

Starting microservices worker

[Nest] 7  - 06/25/2025, 12:15:31 PM     LOG [Microservices:EventRepository] Initialized websocket server

microservices worker error: Error: getaddrinfo ENOTFOUND database, stack: Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

microservices worker exited with code 1

Killing api process
```

### Additional information

I recently had a power outage, though after the power outage everything started back up fine so I don't believe this had any effect, but I thought it might be relevant to know.
