### DISCUSSION TITLE
[BUG] Unable to login with Immich Android app despite matching versions (v1.135.3)

### DISCUSSION THREAD

**Discussion by madkoin** [immich-app/immich#19555] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello,

I am experiencing a login issue with the Immich Android app:

- Server version: v1.135.3 (Docker)
- Android app version: v1.135.3 (official GitHub APK / F-Droid)
- SSL certificate: Let’s Encrypt, valid (tested with SSL Labs)
- Immich API is accessible, returns JSON 401 on /api/users/me

**Problem:**
- The app displays “different version” or “incompatible version” when trying to log in.
- App logs show:
  - `Missing authentication, server, or endpoint info from the local store`
  - `Unable to login using offline or online methods - Logging out completely`
  - `Error logging out`
  - `PlatformDispatcher - Catch all`

**Already tried:**
- Uninstalling/reinstalling the app
- Clearing app cache and data
- Testing on multiple Android devices
- Restarting all Immich containers
- Testing with both F-Droid and GitHub APKs

**Additional info:**
- The API responds correctly in the browser (JSON 401 when not authenticated)
- SSL is valid and recognized by Android
- No reverse proxy authentication on the API endpoints

**Screenshot of the app logs attached.**

Thank you for your help!

![Image](https://github.com/user-attachments/assets/70813afe-2a1b-4d9c-8e6d-2bd41fe2ffca)

### The OS that Immich Server is running on

Debian/Docker

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - /srv/remotemount/Photos_immich:/usr/src/app/upload
      - /srv/remotemount/Photos:/srv/remotemount/Photos:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      TZ: Europe/Paris
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - swag_network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    networks:
      - swag_network

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - swag_network

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /appdata/immich/db:/var/lib/postgresql/data
    restart: always
    networks:
      - swag_network

volumes:
  model-cache:


networks:
  swag_network:
    external: true
```

### Your .env content

```Shell
I use environment variables managed by OMV Compose, but all relevant variables (DB, REDIS, UPLOAD_LOCATION, etc.) are set and working.

IMMICH_VERSION=release
DB_PASSWORD=xxxxxxxxx
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
