### DISCUSSION TITLE
Issues with deploying in Portainer

### DISCUSSION THREAD

**Discussion by Nwhouse** [immich-app/immich#19638] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I am trying to perform a fresh deployment using Portainer.
I have followed the instructions regarding the installation process via Portainer. I used the stock docker-compose.yml provided in GitHub as well as the env file.
Everything deploys, but the immich_server container keeps cycling through the following error.

`Initializing Immich v1.134.0

Detected CPU Cores: 12

Starting api worker

Starting microservices worker

[Nest] 7  - 06/30/2025, 4:20:44 PM     LOG [Microservices:EventRepository] Initialized websocket server

Error: The VectorChord extension version is 0.4.3, but Immich only supports >=0.3 <0.4.

    Please change VectorChord to a compatible version in the Postgres instance.

    at /usr/src/app/dist/services/database.service.js:76:23

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async /usr/src/app/dist/repositories/database.repository.js:377:27

    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20

    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)

    at async /usr/src/app/dist/repositories/database.repository.js:374:13

microservices worker error: Error: The VectorChord extension version is 0.4.3, but Immich only supports >=0.3 <0.4.

    Please change VectorChord to a compatible version in the Postgres instance., stack: Error: The VectorChord extension version is 0.4.3, but Immich only supports >=0.3 <0.4.

    Please change VectorChord to a compatible version in the Postgres instance.

    at /usr/src/app/dist/services/database.service.js:76:23

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

    at async /usr/src/app/dist/repositories/database.repository.js:377:27

    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20

    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)

    at async /usr/src/app/dist/repositories/database.repository.js:374:13

microservices worker exited with code 1

Killing api process`

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS LXC on Proxmox

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich_lib/Library
DB_DATA_LOCATION=./postgres
TZ=America/New_York
IMMICH_VERSION=release
DB_PASSWORD=38bvQ3ZyCM86AIbiFyyi41um
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create the stack in Portainer
2. Copy and paste the contents of the docker-compose.yml from GetHub
3. Copy and paste the contents of the example.env from GetHub
4. Make edits to env settings as described in the install documentation
5. Deploy the stack
...

### Relevant log output

```shell

```
