### DISCUSSION TITLE
v1.52.0

### DISCUSSION THREAD

**Discussion by alextran1502** [immich-app/immich#2110] [Announcements]
# v1.52.0

## Highlights

This release includes many bug fixes and hardening of the recent new features in Immich. We are making Immich more robust as we try to move into the stable territory of the application. I hope you enjoy this release.

### Splitting generated content into a separate folder

This is a feature to build toward a custom location setting for generated files so that the user can leverage SSD for quick serving of thumbnails and encoded video and put the original files to HDD. Users can now store thumbnails and encoded videos at a different location. The separation between generated content and originals makes it easier to know what to backup. It's more clear what folder media is uploaded. Accomplished by swapping `type/uuid` to `uuid/type`.

The resulting folder structure is as follows:
  - `library/<uuid>/<template>`
  - `profile/<uuid>`
  - `thumbs/<uuid>`
  - `encoded-videos/<uuid>` 

Migration Notes:
- All the files are left untouched. 
- New files will start using the new location
- To migrate existing files that are in the old structure:
  - Run storage migration job - moves originals to new `library/`
  - Run generate thumbnail job (then delete `<uuid>/thumbs`) - regenerates thumbs in `thumbs/`
  - Run transcode job (then delete `<uuid>/encoded-videos`) - regenerates encoded videos in `encoded-videos/`
  - Re-upload profile picture - (then delete `<uuid>/profile`) - moves profile image to `profile/`

### Hardening mobile synchronization mechanism

We've solved issues with concurrency that caused the mismatch in the sync status of the local vs. remote assets on the mobile app and further optimized the `Asset` model to guard against bad upload cases from the CLI. The sync and display on the mobile app should now correctly display all local and remote assets.

### Update search UI

Searching is now CLIP-enabled by default. You can search for asset metadata such as location info, camera model.etc by prepending `m:` to your search term, for example, `m:Long Beach`. 

![image](https://user-images.githubusercontent.com/27055614/228380159-eef51ee6-0100-4a5a-a5d2-f78cb3c780ed.png)

On the web, we also added the search history (maximum of 5) to the search bar for a better search experience.

We revamped the Search page on the mobile app to include the new search mechanism and the metadata/CLIP search similar to the web.

<p align="left">
<img src="https://user-images.githubusercontent.com/27055614/228135530-92e1e785-1e4b-4006-8120-72aec268f159.png" width="250"> 

<img src="https://user-images.githubusercontent.com/27055614/228135873-ea55c049-e9e6-44cb-8a22-94253ee74335.png" width="250"> 

<img src="https://user-images.githubusercontent.com/27055614/228136444-468e4dfd-e52a-49a8-8cbc-1da4c9e7d027.png" width="250"> 
</p>

----

As always, please consider supporting the project.

🎉 Cheer! 🎉

## Support

<p align="center">
<img src="https://media.giphy.com/media/LStqgGESXW8XnuCv5y/giphy.gif" width="250" title="Loading ~4000 images/videos"> 
</p>

If you find the project helpful and it helps you in some ways, you can support the project [one time](https://github.com/sponsors/alextran1502?frequency=one-time&sponsor=alextran1502) or [monthly](https://github.com/sponsors/alextran1502) from GitHub Sponsors

It is a great way to let me know that you want me to continue developing and working on this project for years to come.

### Server
* feat(server): Allow .mkv, .wmv, .flv, .mpg videos to be uploaded by @samip5 in https://github.com/immich-app/immich/pull/2045
* fix(server): Do not change file ext case on upload by @bo0tzz in https://github.com/immich-app/immich/pull/2056
* fix(server): invalid video duration format by @michelheusschen in https://github.com/immich-app/immich/pull/2058
* refactor(server): asset serve files by @jrasm91 in https://github.com/immich-app/immich/pull/2052
* refactor(server): media service by @jrasm91 in https://github.com/immich-app/immich/pull/2051
* chore(server): cleanup controllers by @jrasm91 in https://github.com/immich-app/immich/pull/2065
* refactor(server): common by @jrasm91 in https://github.com/immich-app/immich/pull/2066
* refactor(server): cron jobs by @jrasm91 in https://github.com/immich-app/immich/pull/2067
* feat(server): split generated content into a separate folder by @jrasm91 in https://github.com/immich-app/immich/pull/2047
* feat(server): improve and refactor get all albums by @michelheusschen in https://github.com/immich-app/immich/pull/2048
* fix(server): get all query does not respect asset type by @alextran1502 in https://github.com/immich-app/immich/pull/2089
* feat(server): require auth for more endpoints by @michelheusschen in https://github.com/immich-app/immich/pull/2092
* fix(server): increase Typesense start-up settings by @jrasm91 in https://github.com/immich-app/immich/pull/2095
* feat(server): change clip embedding entity type by @michelheusschen in https://github.com/immich-app/immich/pull/2091
* feat(server): resume queues by @jrasm91 in https://github.com/immich-app/immich/pull/2104
* feat(server): add transcode presets by @brighteyed in https://github.com/immich-app/immich/pull/2084
* chore(server): cleanup template variables by @jrasm91 in https://github.com/immich-app/immich/pull/2107
* feat(server): apply storage migration after exif completes by @jrasm91 in https://github.com/immich-app/immich/pull/2093

### Mobile
* refactor(mobile): migrate all Hive boxes to Isar database by @fyfrey in https://github.com/immich-app/immich/pull/2036
* feat(mobile): Use new search API and GridView for Places / Locations by @martyfuhry in https://github.com/immich-app/immich/pull/2043
* refactor(mobile): store backup settings on device by @fyfrey in https://github.com/immich-app/immich/pull/2054
* feat(mobile): Explore favorites, recently added, videos, and motion photos by @martyfuhry in https://github.com/immich-app/immich/pull/2076
* fix(mobile): Fixed mobile app not reporting webm MIME type by @zeyadtamimi in https://github.com/immich-app/immich/pull/2090
* feature(mobile): Hardening synchronization mechanism + Pull to refresh by @fyfrey in https://github.com/immich-app/immich/pull/2085
* feat(mobile): improve explore page and allow metadata search by @alextran1502 in https://github.com/immich-app/immich/pull/2097
* feat(mobile): uploading files in chunk by @perryizgr8 in https://github.com/immich-app/immich/pull/2101

### Web
* feat(web): better search bar by @alextran1502 in https://github.com/immich-app/immich/pull/2062
* fix(web): remove protocol header by @michelheusschen in https://github.com/immich-app/immich/pull/2068
* feat(web): improve and refactor thumbnails by @michelheusschen in https://github.com/immich-app/immich/pull/2087

### Others
* chore: bump openapi version to v1.51.2 by @michelheusschen in https://github.com/immich-app/immich/pull/2059
* Documentation: Add FAQ items for reverse proxy and rpi performance by @etnoy in https://github.com/immich-app/immich/pull/2070
* chore: openapi generation  by @alextran1502 in https://github.com/immich-app/immich/pull/2079
* fix(cli): missing dep in immich cli by @jrasm91 in https://github.com/immich-app/immich/pull/2094
* fix(cli): clean up set interval on application shutdown by @jrasm91 in https://github.com/immich-app/immich/pull/2103
* chore(ci): update prepare release action to bypass branch check by @alextran1502 in https://github.com/immich-app/immich/pull/2106

## New Contributors
* @zeyadtamimi made their first contribution in https://github.com/immich-app/immich/pull/2090
* @perryizgr8 made their first contribution in https://github.com/immich-app/immich/pull/2101

**Full Changelog**: https://github.com/immich-app/immich/compare/v1.51.2...

<hr /><em>This discussion was created from the release <a href='https://github.com/immich-app/immich/releases/tag/v1.52.0'>v1.52.0</a>.</em>

**Comment by SuberSeb** [comment]
Can you please provide an example how to separate thumbnails, encoded videos and profile picture? I mean the docker-compose example. Currently there is only one volume for photos location.

**Comment by jrasm91** [comment]
Something like this should work:

![image](https://user-images.githubusercontent.com/4334196/228848298-20751bf5-e840-4dd5-a61b-677f4b796650.png)

You should add the new volumes to the `immich-server`, `immich-microservices`, and `immich-machine-learning` containers.

You do not have to use an env variable on the left either, so you could do something like this as well:

![image](https://user-images.githubusercontent.com/4334196/228848809-f7010d24-819a-4d80-9a62-c75943c5d435.png)

The left side is the location of thumbs, encoded-video, etc. The right side should point to these internal paths in the container:
- `/usr/src/app/upload` - root directory for all immich content
 - `/usr/src/app/upload/thumbs` - thumbnails are written here
 - `/usr/src/app/upload/encoded-video` - transcoded videos are written here
 - `/usr/src/app/upload/profile` - profile picture is saved here
 - `/usr/src/app/upload/upload` - on upload, files are written here
 - `/usr/src/app/upload/library` - after storage template is applied they get moved here

You can configure all or just some of the volumes, as needed. Volumes should only be needed (in addition to `UPLOAD_LOCATION`) if you are trying to move specific sub-folders to another drive location, otherwise they'll show up inside of `UPLOAD_LOCATION`.

**Reply by patrontheo** [reply]
Thanks! Is it necessary to add those volumes to immich-machine-learning as well ? I get the sense that immich-microservices and immich-server is enough, no ?

**Reply by jrasm91** [reply]
ML doesn't need them, no.

**Reply by bo0tzz** [reply]
⚠️ At this point the information here is pretty outdated. For anybody passing by in the future, please reference https://immich.app/docs/guides/custom-locations instead.

**Reply by panyachai2018-crypto** [reply]
Ioio

**Reply by panyachai2018-crypto** [reply]
Ioio

**Comment by chengcheng300** [comment]
It seems that my Docker doesn't support nested subdirectory mount. So I mounted them seperatedly rather than just override the thumbs folder.

.env

```
UPLOAD_LOCATION=/HDD/immich-data
THUMBS_LOCATION=/SSD/thumbs
```

docker-compose.yml, in `immich-server` and `immich-microservices`

```
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - /etc/localtime:/etc/localtime:ro
```

**Reply by carmolim** [reply]
This will work only for images I upload or for external libraries too?

**Reply by jrasm91** [reply]
External libraries use everything as well, except for UPLOAD_LOCATION/upload

**Reply by carmolim** [reply]
My configuration looks like this:

My .env file
```bash
...
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
EXTERNAL_PATH=/mnt/Memories
THUMBS_LOCATION=/mnt/big/immich/thumbs
VIDEO_LOCATION=/mnt/big/immich/encoded-video
...
```

docker-compose.yml
```yml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463>
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

But all my thumbs and encoded videos are in `./library/thumbs and` and `./library/encoded-video` not in `/mnt/big/immich/`
But when I upload media from my phone the generated thumbs and encoded-videos are being saved on /mnt/big/immich/....

What I'm doing wrong?
