### DISCUSSION TITLE
Image randomly corrupted when generating webp thumbnails with ARW,JPEG files.

### DISCUSSION THREAD

**Discussion by dudgns0507** [immich-app/immich#21352] [Q&A]
### The bug

<img width="167" alt="스크린샷 2024-11-18 오전 12 04 34" src="https://github.com/user-attachments/assets/0635eada-212b-4a66-85ec-f67699cdcff1">
<img width="355" alt="스크린샷 2024-11-18 오전 12 04 39" src="https://github.com/user-attachments/assets/9a538fc1-7cdc-4abb-8272-c80a634a6213">

This is original image files.
![thumbnail (1)](https://github.com/user-attachments/assets/d0d332c4-d6d6-4f4c-980c-4506d10e4613)
![thumbnail](https://github.com/user-attachments/assets/9bd819e3-9063-4431-8246-65b7afc8642c)

This bug happen almost 1~2 out of 10. When I recreate thumbnail image it can be solved. However, I think it would be better if it was possible to fix this bug or retry automatically when an error occurs in thumbnail image creation.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

v1.120.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/volume3/photo
    env_file:
      - .env
    ports:
      - '3006:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tup>
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/Disk/HDD2/library
DB_DATA_LOCATION=./postgres
EXTERNAL_PATH=/Disk/HDD2/Pictures

TZ=Asia/Seoul

IMMICH_VERSION=release

DB_PASSWORD=postgres

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload image to folder
2. Thumbnail created
3. Thumbnail randomly corrupted
...
