### DISCUSSION TITLE
Empty Trash Not Deleting the Assets in Trash

### DISCUSSION THREAD

**Discussion by bagleytravis68** [immich-app/immich#21824] [Q&A] [answered]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Recently updated v1.135.3

Testing uploading Snapchat videos with immich-go I noticed I can no longer re-upload anything as even after sending assets to the trash and emptying the trash immich-go reports they are duplicates. 

Sure enough if I manually upload via web UI it says it is a duplicate and I can go to it. 

If I try to then permanently delete 1 by 1 the first click just says it is deleted, but I can still see/play the video. The second click also says deleted and boots me off that asset back to the trash. However I can STILL get back to it by copy pasting the asset URL.

### The OS that Immich Server is running on

Debian GNU/Linux 13 (trixie)

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

V1.135.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
     
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - caddy_proxy
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    networks: 
      - caddy_proxy
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    networks: 
      - caddy_proxy
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    networks: 
      - caddy_proxy
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs -- currently this is routed to SD but assets are on HD
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:

networks:
  caddy_proxy:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich/library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=xyz
DB_USERNAME=xyz
DB_DATABASE_NAME=xyz
```

### Reproduction steps

1. Add photos to an album
2. Select all photos and delete them
3. Go to trash
4. Empty trash
5. Try to upload photo again

### Relevant log output

```shell
There isn't much here. You can see I empty trash. Then navigate to the video. Delete it. Nav back to it again. Delete it. Its still there.

[Nest] 17  - 06/27/2025, 5:13:44 PM   DEBUG [Api:LoggingInterceptor~hhtgz97g] POST /api/trash/empty 200 18.57ms 172.19.0.2

[Nest] 17  - 06/27/2025, 5:14:19 PM   DEBUG [Api:LoggingInterceptor~27e017m7] GET /api/albums?assetId=3992d18d-fa1d-414b-b96c-bd6902009d13 200 40.41ms 172.19.0.2

[Nest] 17  - 06/27/2025, 5:14:43 PM   DEBUG [Api:LoggingInterceptor~6gq408mf] DELETE /api/assets 204 44.98ms 172.19.0.2

[Nest] 17  - 06/27/2025, 5:15:14 PM   DEBUG [Api:LoggingInterceptor~57jdiur9] GET /api/albums?assetId=3992d18d-fa1d-414b-b96c-bd6902009d13 200 23.92ms 172.19.0.2
```

### Additional information

![Image](https://github.com/user-attachments/assets/14e0df6e-e075-4b43-813e-0a1113a9e04a)

![Image](https://github.com/user-attachments/assets/85ef2100-6ca2-4158-af5b-3fb7975ae673)
