### DISCUSSION TITLE
The built-in backup in Immich does not always work after the update to v1.129.0

### DISCUSSION THREAD

**Discussion by Doomnometron** [immich-app/immich#22190] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On March 6, I updated Immich from v1.126.1 to v1.129.0. Since then, the backup no longer works as smoothly as before. No more backups have been made since the update, only after I adjusted the cronjob and restarted all Docker containers is it partially working again. After the restart, two backup jobs ran one after the other, one successfully and the other not.

### The OS that Immich Server is running on

Debian 12 bookworm

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0 build.187

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - import:/import:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: no
    networks:
      - mynetwork

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: no
    networks:
      - mynetwork

  redis:
    container_name: immich-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: no
    volumes:
      - redisdata:/data
    networks:
      - mynetwork

  database:
    container_name: immich-postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: no
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    networks:
      - mynetwork

  immich-folder-album-creator:
    container_name: immich-folder-album-creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: no
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY_FILE: /mnt/api.key
      ALBUM_LEVELS: 1
      ROOT_PATH: /import
      CRON_EXPRESSION: "10 * * * *"
      TZ: Europe/Berlin
    volumes:
      - apikey:/mnt:ro
    depends_on:
      - immich-server
    networks:
      - mynetwork

networks:
   mynetwork:
    name: mynetwork
    external: true

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,rw,nfsvers=4"
      device: ":/volume1/docker/immich/model-cache"

  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /etc/docker/immich/db

  upload:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,rw,nfsvers=4"
      device: ":/volume1/docker/immich/upload"

  import:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,ro,nfsvers=4"
      device: ":/volume1/photos"

  redisdata:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,rw,nfsvers=4"
      device: ":/volume1/docker/immich/redisdata"

  apikey:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=10.0.0.10,ro,nfsvers=4"
      device: ":/volume1/docker/immich/folder-album-creator"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
# The location where your database files are stored
#DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=securepassword

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Use of the integrated backup job that starts via cronjob.

### Relevant log output

```shell
[Nest] 7  - 03/08/2025, 2:00:00 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 03/08/2025, 2:00:00 AM   ERROR [Microservices:{}] Unable to run job handler (backupDatabase/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:154:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 2. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 8  - 03/08/2025, 8:03:00 AM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 14
[Nest] 8  - 03/08/2025, 8:04:18 AM     LOG [Microservices:BackupService] Database Backup Success
[Nest] 8  - 03/08/2025, 8:04:18 AM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 14
[Nest] 8  - 03/08/2025, 8:05:36 AM     LOG [Microservices:BackupService] Database Backup Success
[Nest] 8  - 03/08/2025, 8:05:36 AM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 8  - 03/08/2025, 8:05:36 AM   ERROR [Microservices:{}] Unable to run job handler (backupDatabase/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:154:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 121. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

### Additional information

No backup since March 6, only after I intervened manually.
```shell
me@server:~$ ls -l /mnt/immichbackup
total 4759616
-rwxr-xr-x 1 root root 347826945 Feb 23 03:01 immich-db-backup-1740276000011.sql.gz
-rwxr-xr-x 1 root root 347827065 Feb 24 03:01 immich-db-backup-1740362400008.sql.gz
-rwxr-xr-x 1 root root 347826927 Feb 25 03:01 immich-db-backup-1740448800009.sql.gz
-rwxr-xr-x 1 root root 347827409 Feb 26 03:01 immich-db-backup-1740535200004.sql.gz
-rwxr-xr-x 1 root root 347827267 Feb 27 03:01 immich-db-backup-1740621600005.sql.gz
-rwxr-xr-x 1 root root 347826941 Feb 28 03:01 immich-db-backup-1740708000008.sql.gz
-rwxr-xr-x 1 root root 347511481 Mar  1 03:01 immich-db-backup-1740794400013.sql.gz
-rwxr-xr-x 1 root root 347509418 Mar  2 03:01 immich-db-backup-1740880800006.sql.gz
-rwxr-xr-x 1 root root 347509567 Mar  3 03:01 immich-db-backup-1740967200008.sql.gz
-rwxr-xr-x 1 root root 347509556 Mar  4 03:01 immich-db-backup-1741053600008.sql.gz
-rwxr-xr-x 1 root root 347509948 Mar  5 03:01 immich-db-backup-1741140000009.sql.gz
-rwxr-xr-x 1 root root 347478063 Mar  6 03:01 immich-db-backup-1741226400006.sql.gz
-rwxr-xr-x 1 root root 350858266 Mar  8 09:04 immich-db-backup-1741420980128.sql.gz
-rwxr-xr-x 1 root root 350858266 Mar  8 09:05 immich-db-backup-1741421058265.sql.gz
```
