### DISCUSSION TITLE
NFS issues with XMP

### DISCUSSION THREAD

**Discussion by jmigual** [immich-app/immich#22192] [Q&A]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have the `${UPLOAD_LOCATION}` in an NFS share. I've started uploading my big library and I'm finding lots of issues like these:

```
immich_server  | [Nest] 7  - 03/15/2025, 11:15:03 PM    WARN [Microservices:APIKeyService] Unable to complete move. Error renaming file with code ENOENT and message: ENOENT: no such file or directory, rename 'upload/upload/9c002a5c-7668-4e86-b85e-e833939658ef/29/09/290956a8-4ea5-4f80-849d-b45aa8cc2a9c.JPG.xmp' -> 'upload/library/admin/2010/06/100_1086_9257825d0319.JPG.xmp'
immich_server  | [Nest] 7  - 03/15/2025, 11:15:34 PM    WARN [Microservices:Error: File not found - /usr/src/app/upload/upload/9c002a5c-7668-4e86-b85e-e833939658ef/df/38/df3899b1-f7b4-4e91-a1db-77ce3940f91e.JPG.xmp
immich_server  |     at ReadTask._ExifToolTask_parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:76:71)
immich_server  |     at ReadTask.parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:47:167)
immich_server  |     at ReadTask._Task_resolve (/usr/src/app/node_modules/batch-cluster/dist/Task.js:146:40)] Error reading exif data (upload/upload/9c002a5c-7668-4e86-b85e-e833939658ef/df/38/df3899b1-f7b4-4e91-a1db-77ce3940f91e.JPG.xmp): Error: File not found - /usr/src/app/upload/upload/9c002a5c-7668-4e86-b85e-e833939658ef/df/38/df3899b1-f7b4-4e91-a1db-77ce3940f91e.JPG.xmp
```

Reading a bit it seems that rename operations are not atomic in NFS and this can cause issues as file locking should be used when renaming.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    restart: unless-stopped
    user: "${WWW_DATA_UID}:${WWW_DATA_GID}"
    networks:
      - internal
      - outside
      - proxy-net
    volumes:
      - /media/hdd/containers/immich/data:/usr/src/app/upload
      - /media/hdd/containers/nextcloud/data:/external/nextcloud:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"

      # HTTPS routers
      - "traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)||Host(`photos.${DOMAIN}`)||Host(`fotos.${DOMAIN}`)"
      - "traefik.http.routers.immich.entrypoints=https"

      # HTTPS Services
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    restart: unless-stopped
    networks:
      - internal
      - outside
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    networks:
      - internal
      - proxy-net
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /usr/local/share/docker-data/immich-db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

volumes:
  model-cache:

networks:
  outside:
    internal: false
  internal:
    internal: true
  proxy-net:
    external: true
    name: "proxy-net"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.129.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=mypassword

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

COMPOSE_PROJECT_NAME=bordils-server-immich
DOMAIN=mydomain.com

WWW_DATA_GID=33
WWW_DATA_UID=33
```

### Reproduction steps

1. Have the upload folder in an NFS share
2. Upload many files at once using immich-go
3. Watch the log
...

### Relevant log output

```shell

```

**Comment by mmomjian** [comment]
I haven't seen this before.. how is your NFS Mounted? how far away, wired vs wireless, what is the latency etc?

**Comment by jmigual** [comment]
This is my fstab mount:

```
192.168.1.15:/mnt/tank /media/hdd nfs4 defaults,noatime,nodiratime,noac 0 0
```

Previously I didn't have the `noac` option. I tried adding it to see whether it would do anything but still got the same issue. The NFS host is in the hypervisor of the same machine while the mount is in a VM inside the hypervisor.

**Comment by bo0tzz** [comment]
> it seems that rename operations are not atomic in NFS

I've never heard of this, can you share your source?

Have you had any issues with mount reliability, disconnections or such?

**Comment by jmigual** [comment]
>>it seems that rename operations are not atomic in NFS
>
>I've never heard of this, can you share your source?

I've found these two sources regarding this topic:
- https://serverfault.com/q/817887/493136
- https://stackoverflow.com/q/41362016/4005637

I haven't had any issues with mount reliability so far. This is the first issue I encounter. Specially since the NFS client is on a VM of the NFS host. 

Reducing the concurrency regarding XMP files seemed to lessen the issue significantly.

**Comment by bo0tzz** [comment]
Neither of those seem to me like they say rename operations are not atomic.

**Comment by LitecoinTim** [comment]
I am running Immich (v1.131.2) with Docker compose and I have mounted a volume from my local filesystem into my Immich instance. I have added  the path as external library and I am getting the same errors when trying to add a location to images/videos that originate from the external library.

```immich_server            | [Nest] 7  - 04/01/2025, 4:39:39 PM    WARN [Microservices:MetadataService] Missing file creation or modification date for asset 525e4342-30d0-4983-9e54-20a3867c59b3: /data/photoprism/Events/2024/REDACTED/_DSC0730.jpg
immich_server            | [Nest] 7  - 04/01/2025, 4:39:39 PM    WARN [Microservices:Error: File not found - /data/photoprism/Events/2024/REDACTED/_DSC0729.jpg.xmp
immich_server            |     at ReadTask._ExifToolTask_parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:76:71)
immich_server            |     at ReadTask.parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:47:167)
immich_server            |     at ReadTask._Task_resolve (/usr/src/app/node_modules/batch-cluster/dist/Task.js:146:40)] Error reading exif data (/data/photoprism/Events/2024/REDACTED/_DSC0729.jpg.xmp): Error: File not found - /data/photoprism/Events/2024/REDACTED/_DSC0729.jpg.xmp
```

**Comment by feld** [comment]
I also had a lot of issues with a low-latency NFS to a share exported by the hypervisor until I added the `noac` mount flag. I tried both with the OS mounting NFS and Docker doing it directly, though I prefer when Docker handles it to ensure it mounts before the container.

snippets from my compose file:

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - immich_storage:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```

```
volumes:
  model-cache:
  immich_storage:
    driver_opts:
      type: "nfs"
      o: "addr=nfs.internal,noac,soft,rw,vers=4.2"
      device: ":/local/photos/immich"
```
