### DISCUSSION TITLE
[Feature] Automatically Archive Assets When Added to a Certain Album

### DISCUSSION THREAD

**Discussion by Chipwingg** [immich-app/immich#2365] [Feature Request]
### The feature

I would love a feature where an entire album could be archived, and any photos added to the album in the past or the future would be archived and not shown in the timeline. The only way to see those photos would be directly in the album. 

Currently if an asset is in an album, you can archive it and it remains in the album. The only difference this would be is that it would archive any new images that are added to the album, automatically. 

Google Photos has this feature, and back when I used Gphotos I used it for photo timelapses or large amounts of photos that were of similar things (e.g., family photos or coin collections).

Another use case is for keeping screenshots, saved QR codes, memes, event tickets, etc that are saved to a phones camera roll from showing up in the main timeline. 

I enjoy using Immich, and it is by far the best photo backup app for me. Thanks Alex and the Team for all the updates and fast development! 

### Platform

- [X] Server
- [X] Web
- [X] Mobile

**Comment by jrasm91** [comment]
Maybe it should be possible to archive an album, and that would hide it from the albums page. Then, when something is added to it, it would make sense for it to become archived as well.

That wouldn't require any changes to the existing archive functionally, just a little bit of logic around archiving albums and related assets.

**Reply by bo0tzz** [reply]
Related to #1645 as well.

**Reply by titro** [reply]
Hi! Any progress or new status for this idea? Would also really appreciate to have that feature :-)

**Reply by r748** [reply]
Would also really appreciate to have the option to hide/archive entire albums and not have them show up on the albums page! Any progress on this feature?

**Comment by aisbergde** [comment]
and after possible implementing of
- #2168
- #3518

it would be great if albums could be created automatically by using external custom tags.

My desired workflow:
- use digiKam to manage tags
- assign specific custom tags (screenshot, archive, document, ...)
- import (and update) custom tags into immich
- optionally create album based on a user specific set of custom tags
- automatically archive assets based on a user specific set of custom tags or based on this specific album

**Comment by aemaeth2501** [comment]
> ### The feature
> I would love a feature where an entire album could be archived, and any photos added to the album in the past or the future would be archived and not shown in the timeline. The only way to see those photos would be directly in the album.
> 
> Currently if an asset is in an album, you can archive it and it remains in the album. The only difference this would be is that it would archive any new images that are added to the album, automatically.
> 
> Google Photos has this feature, and back when I used Gphotos I used it for photo timelapses or large amounts of photos that were of similar things (e.g., family photos or coin collections).
> 
> Another use case is for keeping screenshots, saved QR codes, memes, event tickets, etc that are saved to a phones camera roll from showing up in the main timeline.
> 
> I enjoy using Immich, and it is by far the best photo backup app for me. Thanks Alex and the Team for all the updates and fast development!
> 
> ### Platform
> * [x]  Server
> * [x]  Web
> * [x]  Mobile

Such a setting on an album would be awesome: "if I hide a picture on this specific album with the -auto archive- option, image will be archived" :)

**Comment by nothing2obvi** [comment]
I would absolutely love this feature. I have photos I only want to see in albums and not in my timeline.

**Comment by Gecko-with-a-hat** [comment]
This would especially be awesome with the Phone Album Sync that got added today in release 1.113

**Comment by Gamrin** [comment]
I'm on board with this one, but for an altenate reason.

I like having my mobile Whatsapp, Reddit and Screenshots saved to my Immich Server for archiving purposes. It's nice to be able to scroll through my saved memes and spicy images on very dedicated image-software. It's great for tagging certain recurring memes, and finding 100 of the same image to use as a "reaction gif", or certain erotic tags. But I'd like for those images to not clog up the main page feed.

So if the "Reddit" album would automatically be archived, that'd save me a lot of embarassing moments when showing grandma the pictures of last Christmas.

**Reply by aemaeth2501** [reply]
Hello,

I have the exact same needs and workflow (especially "React memes" xD).
As for now, I made a small script that leverages the API, which is launched periodically to archive not-already-archived assets in specified albums. Having this feature implemented directly in immich would be huge :)

**Reply by thegranddesign** [reply]
@aemaeth2501 care to share the script?

**Reply by aemaeth2501** [reply]
Hello,

The script looks like this:
```
const { init, getMyUser, getAllAlbums, getAlbumInfo, updateAssets } = require('@immich/sdk');

(async () => {
  init({ baseUrl: process.env.BASE_URL, apiKey: process.env.API_KEY });

const user = await getMyUser();
const albums = await getAllAlbums({});

// console.log({ user });

let assetIdsToArchive: string[] = [];

// Filter albums by name and extract asset IDs
for (const album of albums) {
//   console.log(album.albumName);
  if (album.albumName !== "to sort") {
    const albumInfo = await getAlbumInfo({ id: album.id });
    albumInfo.assets
      .filter(asset => !asset.isArchived) // Filter assets where isArchived is false
      .forEach(asset => assetIdsToArchive.push(asset.id));
  }
}
// Print the size of the assetIdsToArchive array
console.log(`Total assets to archive: ${assetIdsToArchive.length}`);

await updateAssets({
    assetBulkUpdateDto: {
        ids: assetIdsToArchive,
        // isArchived: true --> seems to not exist anymore
        visibility: 'archive'
    } // Correct payload structure
});
})();
```

It basically archive all assets that are in all albums except the one named "to sort". Logic can be changed to only target specific albums.

I then turned the whole in a Docker:
```
# Compile the script
#npx tsc archiveAll.ts --outDir dist
# Build the docker image
#docker build -t archive-assets .
# Run it
#docker run --rm -e API_KEY="[API_KEY]" -e BASE_URL="https://immich.fqdn/api" archive-assets
# This is then placed into a crontab on the server

# Use Node.js 23 as the base image
FROM node:23

# Set working directory
WORKDIR /app

ENV BASE_URL="TO_CHANGE"
ENV API_KEY="TO_CHANGE"

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy compiled JavaScript files into the container
COPY dist/ ./dist/

# Run the script
CMD ["node", "./dist/archiveAll.js"]
```

I'm no expert in node dev, but this fits my needs.

**Reply by Gecko-with-a-hat** [reply]
Thanks for sharing. I converted it to an ansible playbook if anyone wanted to automate it with ansible. The API key is added by an external variable. Just set your Immich host address in base_url and add the names of the albums to the list of albums you'd like to archive. Oh and set the correct host obviously.

Now you can run this playbook on a cron schedule or as I have it, in SemaphoreUI on schedule.

The playbook.yaml:


```
---
- name: Archive selected Immich albums
  hosts: localhost
  gather_facts: false
  vars:
    immich_base_url: "https://immich.mydomain.com"
    immich_albums_to_archive:
      - "album1"
      - "album2"
      - "album3"

  tasks:
    - name: Get all albums
      ansible.builtin.uri:
        url: "{{ immich_base_url }}/api/albums"
        method: GET
        headers:
          x-api-key: "{{ lookup('env', 'IMMICH_API_KEY') }}"
        return_content: yes
      register: albums_response

    - name: Parse albums JSON
      ansible.builtin.set_fact:
        albums: "{{ albums_response.json }}"

    - name: Filter selected albums
      ansible.builtin.set_fact:
        selected_albums: "{{ albums | selectattr('albumName', 'in', immich_albums_to_archive) | list }}"

    - name: Get album details
      ansible.builtin.uri:
        url: "{{ immich_base_url }}/api/albums/{{ item.id }}"
        method: GET
        headers:
          x-api-key: "{{ lookup('env', 'IMMICH_API_KEY') }}"
        return_content: yes
      register: album_details
      loop: "{{ selected_albums }}"
      loop_control:
        label: "{{ item.albumName }}"

    - name: Collect unarchived asset IDs
      ansible.builtin.set_fact:
        asset_ids: >-
          {{
            album_details.results
            | map(attribute='json.assets')
            | flatten
            | selectattr('isArchived', 'equalto', false)
            | map(attribute='id')
            | list
          }}

    - name: Print number of assets to archive
      ansible.builtin.debug:
        msg: "Total assets to archive: {{ asset_ids | length }}"

    - name: Archive assets (bulk update)
      ansible.builtin.uri:
        url: "{{ immich_base_url }}/api/assets"
        method: PUT
        headers:
          x-api-key: "{{ lookup('env', 'IMMICH_API_KEY') }}"
          Content-Type: "application/json"
        body_format: json
        body:
          ids: "{{ asset_ids }}"
          visibility: "archive"
        status_code: [200, 204]
      when: asset_ids | length > 0
```
