### DISCUSSION TITLE
v1.15.0_21-dev

### DISCUSSION THREAD

**Discussion by alextran1502** [immich-app/immich#283] [Announcements]
## Breaking Changes

**First and foremost. No data will be lost**

There is no new version of the mobile app in this release.

**The `docker-compose` file will need to be updated with new content.** 

<details>
<summary>Click to show new docker-compose.yml content</summary>

```yml

version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
      - 2284:443
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

```
</details>

You no longer need the `nginx.conf` file for the setup. The `immich-proxy` container has been added to the stack to handle the proxy setup. Additional changes to the internal networking will not require an update on your side. 

The default tags of the containers in docker-compose file have been changed from `latest` to `release` to avoid pushing out changes that are not formally sorted between the client and the server app.

I and the team are working hard to provide more features, higher quality, and an easier way to set up the app for you.

## What's Changed
* Update server dependencies and fixed Typeorm API changes in the new version by @alextran1502 in https://github.com/alextran1502/immich/pull/276
* feat: create an immich-nginx container to remove default Nginx config setup by @zackpollard in https://github.com/alextran1502/immich/pull/280
* Add Podman Support by @alextran1502 in https://github.com/alextran1502/immich/pull/278

## F-Droid
You can get the app on F-droid by clicking the image below.

[<img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png"
    alt="Get it on F-Droid"
    height="80">](https://f-droid.org/packages/app.alextran.immich)

#### You can also download the app from Google Play Store [here](https://play.google.com/store/apps/details?id=app.alextran.immich) 

*The App version might be lagging behind the latest release due to the review process.*

<p align="left">
  <img src="https://user-images.githubusercontent.com/27055614/164953845-4749bccf-8f9d-45e1-ac41-61fe98d6e5b4.png" width="200" title="Google Play Store">
<p/>

#### You can download the app from Apple AppStore [here](https://apps.apple.com/us/app/immich/id1613945652):

<p align="left">
  <img src="https://user-images.githubusercontent.com/27055614/164953841-de6e3f0f-4fd4-4e25-8327-6c3ccc622fc2.png" width="200" title="Apple App Store">
<p/>

*The App version might be lagging behind the latest release due to the review process.*

## Support
You can support the project using [Github Sponsor](https://github.com/sponsors/alextran1502) or [!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/altran1502)

**Full Changelog**: https://github.com/alextran1502/immich/compare/v1.14.0_21-dev...v1.15.0_21-dev

<hr /><em>This discussion was created from the release <a href='https://github.com/alextran1502/immich/releases/tag/v1.15.0_21-dev'>v1.15.0_21-dev</a>.</em>
