### DISCUSSION TITLE
Using Immich mobile app when the entire domain is protected by Authelia

### DISCUSSION THREAD

**Discussion by markormesher** [immich-app/immich#3118] [Q&A]
(Recently started using Immich, absolutely loving it so far ❤️ Clearly paid-for-quality software and I'm glad there are options to support it!)

I have everything I host sitting behind [Authelia](https://www.authelia.com/) for authentication, and for apps that require an OIDC provider I use it for that too - including Immich. That means I'm effectively doing auth twice for these apps, but that way I don't need to trust N different apps to get auth right, just Authelia.

That works fine for Immich on the web, but means the mobile app doesn't work because it hasn't already logged in to Authelia, so all requests are getting blocked (I'm getting this on Android, but I imagine iOS would get the same problem). If I allow-list some paths like `/.well-known/immich`, `/api/oauth` and a few others I can get the login flow to work, but obviously the main app still can't talk to the server.

I appreciate this isn't an _Immich_ problem, this is a _my setup_ problem, but I imagine plenty of other people may encounter the same problem if they protect their domains with Authelia, Authentik, Keycloak, etc. Has anyone found a good way to deal with this, or would there be any way to add support in the apps for a "pre-login" phase?

**Comment by jrasm91** [comment]
I think one solution is to use delegated auth. 

The auth service runs in front of the desired application and takes care of authenticating the user. If the user is logged in (authenticated) the request is forwarded to the app  _with additional headers_. The idea being the app has _delegated_ authentication to an upstream server and can trust/infer auth from the headers or other parameters. Something like `X-Immich-User=admin`. Instead of looking up the user from a session token or similar, it gets the user id directly from the header.

Things to consider:
- Apps (immich) need to support it
- Apps need to have whitelisted IPs that they trust this header coming from
- Still relies on intercepting requests and redirecting to a login portal, so still doesn't work for mobile

This would effectively remove the "auth" layer from Immich and "delegate" it to "Authelia", but it would require a bit of work to implement and still doesn't solve the mobile app issue.

**Comment by markormesher** [comment]
Delegated/proxy auth would indeed be great - it's what I use for apps that support it, like [Gitea](https://docs.gitea.com/next/usage/authentication#reverse-proxy) and [Grafana](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/auth-proxy/), but I have a few other apps with the same double-login and it's not a huge pain. Depending on how your proxy is configured you can even avoid IP allow-listing issues, but it's good to have that option.

The only reason I'm looking harder for an answer here is that Immich is the first service I'm hosting with a mobile app I _really want to use_ 😅  I'm going to poke around the request logs and see if it would be possible to do something like allow-listing the paths I listed above, grabbing some of the session/cookie data during the login flow, then applying them to all requests. You'd need to detect when those credentials have expired and re-auth, but I'm a bit surprised the app doesn't do that anyway when it gets a flood of 401s on all requests.

**Reply by jrasm91** [reply]
Yes, the bigger issue seems to be making anything work with the mobile app itself. There was talk in discord about seeing if the app could be configured to follow redirects during login process and if persisted cookies could be included with future http requests that could be a potential solution.

**Reply by maxime1992** [reply]
Hi @jrasm91 do you have any links to that discussion by any chance, article or something I could follow? OIDC if really not enough IMO as I have described [here](https://github.com/immich-app/immich/discussions/3118#discussioncomment-10735041) and I'd really like to be able to use Immich android app. Thanks!

**Comment by kilgil27** [comment]
did you ever get anywhere with this?

**Reply by markormesher** [reply]
There's some discussion on Discord about this (look for "Exposing Immich to the internet") but the short answer is that this requires some dev work. I've worked as a mobile dev before so I am hoping to implement this as a contribution, but it will probably be a little while before I have time.

**Comment by MVrauwdeunt** [comment]
I use Immich behind Authelia. I just let Authelia handle the login step. And use [OAuth](https://immich.app/docs/administration/oauth/#mobile-redirect-uri) for the login in Immich.
This also works great with the app. And adds 2FA if enabled in Authelia.

**Reply by markormesher** [reply]
That's interesting - you're saying that the Android app works fine even though requests are going through Authelia on your server before hitting Immich? I've just tried that myself on the latest server / app versions and see the same problems described in the original post.

**Reply by sannidhyaroy** [reply]
> That's interesting - you're saying that the Android app works fine even though requests are going through Authelia on your server before hitting Immich?

No, what he's trying to say is he uses Authelia for an OAuth login to Immich. So, that's a single layer of authentication, instead of what's been discussed here, and not exactly relevant to the issue.

**Comment by MVrauwdeunt** [comment]
Just double checked it to confirm it But yes I can use Authelia to login in the android app of Immich. Latest version of the app and server..

**Reply by maxime1992** [reply]
Are you talking about using Authelia OIDC mechanism or having Authelia protecting the entire domain (or both)?

For me IODC isn't enough at all, see [here](https://github.com/immich-app/immich/discussions/3118#discussioncomment-10735041). But if you got the app working with Authelia protecting the entire domain, I'd be really interested. Could you share your config if that's the case? Thanks a lot

**Comment by dsm1212** [comment]
I bypassed authelia because I wanted to share albums. Is there any way for that to work without my having to give an authelia account to everyone?

**Reply by Irda13** [reply]
I'm a bit late here, but you can have authelia to bypass only the share path with something like that:
```
access_control:
  default_policy: 'deny'
  rules:
    # This allows to bypass authelia for immich.example.com/share
    - domain: 'immich.example.com'
      policy: 'bypass'
      resources:
        - '^/share'
    # But have it activated on everything else
    - domain: '*.example.com'
      policy: 'two_factor'
```

**Reply by tanmaychimurkar** [reply]
Hey @Irda13, thanks for your reply.

I tried the above with the latest authelia version, but it seems that I cannot get this to work. When I create a shared album link and access it via incongnito or on a different device, immich returns `Error - Something went wrong`.

Immich logs are all normal, nothing seems weird, not even `Websocket Connect` or anything. In authelia however, I see the following logs:

`time="2024-04-11T11:57:54+02:00" level=info msg="Access to https://immich.mydomain.url.org/custom.css (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2Fcustom.css&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x

time="2024-04-11T11:57:55+02:00" level=info msg="Access to https://immich.mydomain.url.org/_app/immutable/assets/slideshow.Ms20_H8Y.css (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2F_app%2Fimmutable%2Fassets%2Fslideshow.Ms20_H8Y.css&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x

time="2024-04-11T11:57:55+02:00" level=info msg="Access to https://immich.mydomain.url.org/_app/immutable/assets/asset-viewer.CeAujpVS.css (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2F_app%2Fimmutable%2Fassets%2Fasset-viewer.CeAujpVS.css&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x

time="2024-04-11T11:57:55+02:00" level=info msg="Access to https://immich.mydomain.url.org/_app/version.json (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2F_app%2Fversion.json&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x

time="2024-04-11T11:57:55+02:00" level=info msg="Access to https://immich.mydomain.url.org/_app/version.json (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2F_app%2Fversion.json&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x

time="2024-04-11T11:57:55+02:00" level=info msg="Access to https://immich.mydomain.url.org/manifest.json (method GET) is not authorized to user <anonymous>, responding with status code 401 with location redirect to https://authelia.mydomain.url.org/?rd=https%3A%2F%2Fimmich.mydomain.url.org%2Fmanifest.json&rm=GET" method=GET path=/api/authz/auth-request remote_ip=194.xxx.xxx.x`

I used the same access control rule as above, and this is what happens in authelia when I try to access shared folder. Any pointers on this?

Thanks

**Reply by mk12** [reply]
Just exposing `/share` (and `/s`) does not work. See https://github.com/alangrainger/immich-public-proxy?tab=readme-ov-file#why-not-simply-put-immich-behind-a-reverse-proxy-and-only-expose-the-share-path-to-the-public

**Reply by dsm1212** [reply]
@mk12 your statement is too brief. Are you saying the above authelia bypass suggestion from may didn’t work and we should use the new proposal at that link? Or are you saying what’s at that link didn’t work? Or both?

**Reply by mk12** [reply]
The link explains why exposing those routes is not sufficient. The /share page is not designed to only load from /share. It accesses /api like everything else in Immich.

**Comment by chain710** [comment]
I'm using authelia too. My suggestion is don't protect the whole domain with authelia, instead use oauth and disable Immich password login

**Reply by maxime1992** [reply]
This really isn't enough IMO. It does reduce the **login** surface attack, but it's not the most important one and it's not enough.

If you self host services, hopefully you have something like fail2ban to avoid brute force attack. So if one was to try to login into Immich x times without success, they should be banned. In that case, oauth doesn't matter that much it's just a convenience to avoid login in twice.

For me the point of Authelia is that it'll block access to the entire app (if not logged into Authelia ofc), making it a lot more secure to open to the web. Imagine for a second that Immich forgot to implement an auth check on an endpoint to list and download pictures for example. Anyone could scan the web searching for Immich app and list + download all pictures of users exposing Immich. OAuth login would not help you in any way at all here. Authelia blocking any external access for non Authelia users would.

I think it's essential to have a dedicated security layer ahead of all the apps like Immich.

**Reply by mk12** [reply]
Well said. I feel like we're entering a golden age of self-hosting with amazing projects like Immich. But it would be so much valuable if I could share it with family and friends. I don't want to make them install a VPN that drains their battery, and I'm unwilling to expose it directly to the Internet, even with crowdsec. Forward auth solves this use case perfectly, but only on web. Mobile apps can do it with an in-app browser popup (e.g. Gmail does this), but it's so poorly supported in client apps of self-hosted services that I can't find a single example. There isn't even a commonly understood term for describing it and searching of it, as evidenced by all the confusion on this discussion page.

Happily I saw the Immich app has support for client certificates, so I was going to allow mTLS to bypass the forward auth. Only to discover it's only half-implemented: it breaks photo upload and video playback on iOS 😢 Ditto with HTTP basic auth, you can provide a `user:pass@` in the URL but it isn't passed for photo upload and video playback so it's useless.

**Comment by gonsalvesc** [comment]
@chain710 @MVrauwdeunt I was able to get Authelia to work on the web but can't get the app to work. What server endpoint URL are you using on the app? And which credentials are you using? Authelia or Immich? Would you mind sharing the oidc section of your authelia configuration.yml file?

**Reply by chain710** [reply]
server endpoint: https://immich.example.com

authelia oidc config looks like:

```
identity_providers:
  oidc:
    hmac_secret: your_hmac_secret
    issuer_private_key: your_private_key
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://immich.example.com
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: immich
        description: Immich
        secret: your_secret
        sector_identifier: ''
        public: false
        authorization_policy: two_factor # or something else
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - app.immich:/
          - https://immich.example.com/auth/login
          - https://immich.example.com/user-settings
        grant_types:
          - refresh_token
          - authorization_code
        userinfo_signing_algorithm: none
```

**Reply by gonsalvesc** [reply]
Thank you!
I have a real strange situation. The app works if I use the local server IP address as the server end point. But if I use the FQDN, then it throws an error say "Error logging using OAuth, check server URL"

**Reply by gonsalvesc** [reply]
One more question - what reverse proxy are you using?

**Reply by chain710** [reply]
use nginx as reverse proxy

> But if I use the FQDN, then it throws an error say "Error logging using OAuth, check server URL"

Make sure that the domain you used exists in `allowed_origins` and restart authelia

**Reply by gonsalvesc** [reply]
Yup, did that. Now it takes me to the Immich authentication page and asks for my Immich email and password, even though I have Password Authentication turned off

**Reply by chain710** [reply]
immich side oauth config, hope it helps:

```
ISSUER URL: https://auth.example.com/.well-known/openid-configuration

CLIENT ID: immich

CLIENT SECRET: yoursecret

SCOPE: openid email profile

STORAGE LABEL CLAIM: preferred_username

AUTO REGISTER: yes

AUTO LAUNCH: yes
```

**Reply by Irda13** [reply]
I have the same issue, traefik + authelia + immich, web works fine, but in order to make the app to work I had to bypass authelia for `- '^/.well-known/immich'` and full `- '^/api'`
I don't really like having authelia bypassed for full /api path, but that was the only way I made the app work. With OAuth activated you can then login to the app using authelia login, but you have to rely on Immich handling security instead of Authelia.
I don't know if there's other ways, it would be nice if Immich could handle this better.

**Reply by epd5** [reply]
> I have the same issue, traefik + authelia + immich, web works fine, but in order to make the app to work I had to bypass authelia for `- '^/.well-known/immich'` and full `- '^/api'` I don't really like having authelia bypassed for full /api path, but that was the only way I made the app work. With OAuth activated you can then login to the app using authelia login, but you have to rely on Immich handling security instead of Authelia. I don't know if there's other ways, it would be nice if Immich could handle this better.

Thanks very much for this info. Managed to get the mobile app working with Traefik + Authentik
Here's the entries in docker compose for Immich if it's any use to anyone -


               - traefik.enable=true

               - traefik.http.routers.immichmobile.rule=Host(`immich.domain.com`) && (PathPrefix(`/.well-known/immich`) || PathPrefix(`/api`))
               - traefik.http.routers.immichmobile.service=immich-server
               - traefik.http.routers.immichmobile.entrypoints=websecure
               - traefik.http.routers.immichmobile.middlewares=mymiddleware

               - traefik.http.routers.immich.rule=Host(`immich.domain.com`)
               - traefik.http.routers.immich.service=immich-server
               - traefik.http.routers.immich.entrypoints=websecure
               - traefik.http.services.immich-server.loadbalancer.server.port=3001
               - traefik.http.routers.immich.middlewares=authentik,mymiddleware

**Reply by Cheekie25** [reply]
> I have the same issue, traefik + authelia + immich, web works fine, but in order to make the app to work I had to bypass authelia for `- '^/.well-known/immich'` and full `- '^/api'` I don't really like having authelia bypassed for full /api path, but that was the only way I made the app work. With OAuth activated you can then login to the app using authelia login, but you have to rely on Immich handling security instead of Authelia. I don't know if there's other ways, it would be nice if Immich could handle this better.

Is there any other way you think ?
I was wondering about the risks of this solution ?

How  did you find that you had to bypass those two ? I would like to bypass for another app as well and I'm wondering how you figured this out.
Also I noticed that sharing link doesn't work unauthentified. I tried to add `/share` and now the immich logo is loading forever instead of being redirected to the IDP. So it's a bit better but not yet functionnal.

**Comment by dsm1212** [comment]
Have you guys tried this? https://blog.lrvt.de/configuring-authelia-oidc-for-immich/

It appears the app does support it if you set up correctly.

I'm wondering if that blog plus the share bypass would get shares working at least on the web.

**Reply by l4rm4nd** [reply]
I've updated the blog post to reflect some latest configuration changes by Authelia.

Works again for Immich v1.111.0 and Authelia v4.38.9

**Comment by gonsalvesc** [comment]
Hello everyone:
I was able to get it to work. I'm using Caddy + Authelia + Crowdsec
Got it working for both mobile app and desktop. Happy to assist if anyone has any specific questions.

**Reply by Irda13** [reply]
I'm interested in your Authelia configuration then. Is the full subdomain protected ? What are your redirects URI ?
Thanks

**Reply by gonsalvesc** [reply]
Sure! Here's the entire config. Note that I'm still on 4.37

````yaml
## The theme to display: light, dark, grey, auto.
theme: 'dark'

## The secret used to generate JWT tokens when validating user identity by email confirmation. JWT Secret can also be
## set using a secret: https://www.authelia.com/c/secrets
jwt_secret: my_secret

## Log Configuration
log:
  level: 'debug'
  format: 'json'
  file_path: '/var/log/authelia/authelia.log'
  keep_stdout: true


## First Factor 
## https://www.authelia.com/configuration/first-factor/file/
authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id

## TOTP Configuration
## https://www.authelia.com/c/totp
totp:
  disable: false
  issuer: 'authelia.com'
  algorithm: 'SHA1'
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

duo_api:
  disable: true

webauthn:
  disable: true

## Access Control Configuration
## https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: deny
  rules:
    - domain: immich.mydomain.tdl
      policy: two_factor

## Session Provider Configuration
## https://www.authelia.com/configuration/session/introduction/
session:
  name: authelia_session
  domain: mydomain.tdl
  secret: mysecret
  expiration: 1h
  inactivity: 10m
  remember_me_duration: 15d

## Password Policy
## https://www.authelia.com/configuration/security/password-policy/
password_policy:
  standard:
    enabled: true
    min_length: 8
    max_length: 0
    require_uppercase: true
    require_lowercase: true
    require_number: true
    require_special: false
  zxcvbn:
    enabled: false
    min_score: 3

## Regulation configuration
## https://www.authelia.com/configuration/security/regulation/
regulation:
  max_retries: 4
  find_time: 2m
  ban_time: 5m

## 
## https://www.authelia.com/configuration/storage/sqlite/
storage:
  encryption_key: my_encryption_key
  local:
    path: /data/db.sqlite3

## Notification provider
## https://www.authelia.com/configuration/notifications/smtp/
notifier:
  disable_startup_check: false
  smtp:
    host: smtp.gmail.com
    port: 587
    username: username@gmail.com
    password: password
    sender: username@gmail.com
    timeout: 30s


identity_providers:
  oidc:
    hmac_secret: hmac_secret
    issuer_certificate_chain: |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
            -----END RSA PRIVATE KEY-----
    access_token_lifespan: 2h
    authorize_code_lifespan: 2m
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
        - userinfo
      allowed_origins:
        - https://immich.mydomain.tdl
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: immich
        description: Immich OIDC
        secret: secret
        sector_identifier: ''
        public: false
        authorization_policy: two_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - app.immich:/
          - https://immich.myDomain.tdl
          - https://immich.myDomain.tdl/auth/login
          - https://immich.myDomain.tdl/user-settings
          - https://immich.myDomain.tdl/api/oauth/mobile-redirect
        grant_types:
          - authorization_code
          - refresh_token
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
````

**Reply by gonsalvesc** [reply]
One more thing - I'm not sure how Traefik works, but you need to make sure that the reverse proxy request is NOT forwarding the request to Authelia. Immich directly integrates with Authelia via OIDC. So users will need to press the "login with Oauth" button when they get to your Immich login page - for both web and app.

**Reply by mrkaryo** [reply]
Hello @gonsalvesc ! 

Are you protecting the whole domain with Authelia for your setup above? 
I managed to get everything working if the immich domain is bypassed in Authelia, then I have disabled the password login in immich and I use only OIDC via Authelia.

If i try to protect the whole domain under Authelia, the OIDC button never appears in the app. Logging-in via password in the app in that instance also doesnt work.

**Reply by gonsalvesc** [reply]
Hi @mrkaryo 

So sorry for the late reply. No, I am not protecting the whole domain - just Immich. Immich is the only app I have that is exposed to the internet.

**Reply by pjosuah** [reply]
> Hello everyone (...) I'm using Caddy + Authelia + Crowdsec (...)

Hi @gonsalvesc 

Apologies for resurrecting and hijacking this thread, the part I've quoted is what made me stop.
**I'm trying to make Caddy + Authelia + Crowdsec work together.**
I've been scouring the Internet and going through trials and errors for more than 1 month now, to no avail.

I'd be immensely thankful if you could share with me your (redacted, of course) `compose` file and `Caddyfile`.
Thanks in advance

**Reply by gonsalvesc** [reply]
Sure thing!
I've uploaded the compose files into [this repo](https://github.com/gonsalvesc/Immich-Caddy-Authelia-Crowdsec/).

Good luck and let me know how it goes!

**Reply by maxime1992** [reply]
> No, I am not protecting the whole domain - just Immich. Immich is the only app I have that is exposed to the internet

I don't think you're protecting much by doing that. I've explained more here https://github.com/immich-app/immich/discussions/3118#discussioncomment-10735041

**Comment by maxime1992** [comment]
Hello everyone :wave: 

I have found a workaround for this which IMO lets us keep the entire API safe. Feel free to let me know what you think but I think it's quite robust and avoid excluding any part of the server from Authelia like the /api endpoint.

**This is not a proper implementation of Authelia within Immich. This is a workaround and having a way in app to be redirected to an Authelia login page properly is the go to solution. Do not close this issue because of this workaround.**

With that out of the way, let see how to achieve something while we patiently wait for a proper implementation.

# Context

I use SWAG with Authelia. Behind the scenes it's just NGINX anyway so if you don't use SWAG you should be able to adapt fairly easily to your own use case.

# Problem

- Exposing Immich safely to the web: Behind Authelia without leaving any endpoint open for everyone.
- Being able to use the mobile app

# Solution

We have a regular conf for NGINX for our Immich app, all protected by Authelia:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name immich.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    include /config/nginx/authelia-server.conf;

    location / {
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app immich-server;
        set $upstream_port 2283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location ~ (/immich)?/api {
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app immich-server;
        set $upstream_port 2283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
} 
```

We then create another conf for an extra sub domain. This time, we'll only cover the /api endpoint as the app will never try to use the UI and we do not have Authelia. BUT, we create a map with very long tokens, like 30 chars, one for each user we want to give access to the mobile app:

```
map $http_immich_skip_authelia $immich_skip_authelia {
    default 0;
    generate-a-long-string-here-for-user-1 1; # user 1
    generate-a-long-string-here-for-user-2 1; # user 2
    generate-a-long-string-here-for-user-3 1; # user 3
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name immich-mobile.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location ~ (/immich)?/api {
        # https://stackoverflow.com/a/54160148/2398593
        if ($immich_skip_authelia = 0) { 
            return 403;
        }

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app immich-server;
        set $upstream_port 2283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
} 
```

If someone tries on that sub domain to access the /api endpoint without passing an `Immich-Skip-Authelia` header with a correct value, we just return 403. Make sure to use something like Fail2Ban so that if someone tries to brute force the endpoint you ban them.

I'm using OAuth, unsure how that'd behave if you don't, hopefully you just don't have to do that step.
In Immich:
- Go to `/admin/system-settings?isOpen=authentication+oauth`
- Turn on the toggle "MOBILE REDIRECT URI OVERRIDE"
- Set the value "MOBILE REDIRECT URI" to "https://your-immich-url/api/oauth/mobile-redirect"
- Save

Open your mobile app:
- On the login screen, use the :gear: icon
- Advanced
- Custom proxy headers
- "Header name": "Immich-Skip-Authelia"
- "Header value": Pass on the generated string that you've put on the map. Do not create one that you share with several people, create one per person you'd like to give access to the app
- Use the URL of the seconf conf file we've made, in this case the subdomain "immich-mobile"

Now all the endpoints both the frontend and /api are protected by Authelia on the first sub domain, and on the second it's protected by a very long password provided as a header per user protected with Fail2Ban to avoid brute force.

Seems like a fairly good workaround while waiting for an official implementation where we can just log in with Authelia as every endpoint is protected instead of just excluding /api from Authelia.

**Reply by howardrcc** [reply]
It also works without OAuth. 
I'm just wondering why bother setting up another domain for mobile? Just put the header and password info in the original nginx config for the location /api (and remove `include /config/nginx/authelia-location.conf;`)

Link sharing doesn't work btw, @dsm1212.

**Reply by Faexa** [reply]
Hello, I managed to adapt your idea, but with only one subdomain : 
```
    location / {
        if ($immich_skip_authelia = 1) {
          rewrite ^ /__skipauth$uri last;
        }

        include snippets/authelia_proxy.conf;
        include snippets/authelia_authrequest.conf;
        include include/websockets_params;
        proxy_pass http://<ip>:<port>;
     }

    location /__skipauth/ {
       include snippets/authelia_proxy.conf;
       include include/websockets_params;
       proxy_pass http://<ip>:<port>;
       rewrite  ^/__skipauth/(.*) /$1 break;
    }
```

Anyway, thank you very much for your idea.

**Reply by 1randomguy** [reply]
Another possible workaround is bypassing the additional authentication for clients on the local network and either using the webpage to access immich or using a vpn to your home network when you need to use the app (like if you want to upload pictures while on vacation or something). It's not quite as seemless in use, but easier to set up initially and doesn't require setting up secrets.

**Reply by nosar77** [reply]
Anyone got this setup working in HAProxy? I'm going to attempt to do this on OPNsense's version of HAProxy.

**Reply by hmmenke** [reply]
Wow, I just have to jump in and let you know that this helped me a lot, and the solution also works without OAuth)
I'll share my subdomain config here, as I believe my setup is fairly common;
- Unraid
- SWAG (Nginx+fail2ban++)
- Authelia w/2FA (no OAuth) (defaults to 2FA for all subdomains unless bypassed)
- Cloudflare with proxied subdomains.

This setup allows me to keep **one subdomain** for immich (_photos.my-domain.com_ in my case), while bypassing Authelia when header with token is passed.

Full (anonymized) immich subdomain config as follows - PLEASE, if anyone sees major issues with this (I'm a newb), let me know:

```
map $http_immich_skip_authelia $immich_skip_authelia {
    default 0;
    <LONG-TOKEN-GOES-HERE> 1; # user 1 (ME)
#    add more tokens as new lines if needed
}

server {
    listen 443 ssl;
#    listen 443 quic;
    listen [::]:443 ssl;
#    listen [::]:443 quic;

    server_name photos.*;

    include /config/nginx/ssl.conf;
    client_max_body_size 0;

    # enable for Authelia (requires authelia-location.conf in the location block)
    include /config/nginx/authelia-server.conf;

    location / {
        if ($immich_skip_authelia = 1) {
          rewrite ^ /__skipauth$uri last;
        }

        # enable for Authelia (requires authelia-server.conf in the server block)
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app <IP-ADDRESS>;
        set $upstream_port 2283;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }

    location /__skipauth/ {
       proxy_pass http://<IP-ADDRESS>:2283;
       rewrite  ^/__skipauth/(.*) /$1 break;
    }
}
```

Result:

- Visiting subdomain (photos.my-domain.com) from web redirects to Authelia subdomain for auth -> regular login.
- Immich mobile app _without_ custom proxy header fails
- Immich mobile app _with wrong token in proxy header_ fails
- Immich mobile app _with correct token in proxy header_ **SUCCESS**

Check, check, check! Thank you!

I hope my post also helps someone with similar setups, and hopefully someone'll answer if I should change anything in this config. (PS: I use Cloudflare to block IPs from countries outside my own, as an extra security measure).

**Comment by dsm1212** [comment]
Interesting, for me I'd still like to be able to share links though. I'm ok with those being open with just a password. I think this would block them?

**Reply by maxime1992** [reply]
Not sure whether you're commenting about my previous message or not. If that's the case, correct. You'd need something like this https://github.com/alangrainger/immich-public-proxy

**Comment by wilfredwee** [comment]
@maxime1992 thanks for you idea in https://github.com/immich-app/immich/discussions/3118#discussioncomment-11025563

This led me to this video on how to do something similar with Cloudflare Access: https://www.youtube.com/watch?v=J4vVYFVWu5Q

However I use Authentik, so I came up with a slightly different method:

1. In Authentik, go to Directory -> Users -> Create Service Account
1. Configure the user however you like.
1. Copy the username and password.
1. Base64 encode the username and password, joined by a colon: `<username>:<password>`. On UNIX systems, you can do: `echo -n '<username>:<password>' | base64`
1. Go to your Immich Mobile app, click the gear Settings icon.
1. Go to Advanced -> Custom proxy headers
1. For Header name, input 'Authorization'
1. For Header value, input 'Basic <base64 encoded string you generated'
1. Now you can log into your Immich Mobile App! You will still need to complete the regular login process for Immich.

I've written more about my setup here: https://wilfredwee.github.io/entry/authentik-proxy-with-immich/

**Reply by chevaal** [reply]
Hi @wilfredwee,

I just tried your solution and it works!

Just for completeness: the header for basic authentication is 
 - Name: "Authorization"
 - Value: "Basic `base64 of <username>:<password>`" (not just "Basic")

And if anyone is using Authelia, you also need to enable basic authentication for forward auth
```
server:
  endpoints:
    authz:
      forward-auth:
        implementation: 'ForwardAuth'
        authn_strategies:
          - name: 'HeaderAuthorization'
            schemes:
              - 'Basic'
            scheme_basic_cache_lifespan: 0
          - name: 'CookieSession'
```

Now, I'm wondering what the security experts and enthusiasts think of this solution ? It doesn't bypass the authentication, but it requires to have the credentials saved as plaintext (base64) in the app's configuration.
