### DISCUSSION TITLE
[BUG] 500 after update to v1.73.0

### DISCUSSION THREAD

**Discussion by Darvyn** [immich-app/immich#3717] [General]
### The bug

After using the command docker-compose pull && docker-compose up -d     # Or `docker compose up -d` to upgrade to v1.73.0, the site show a 500 error:

> 500 connect ECONNREFUSED 172.19.0.8:3001

### The OS that Immich Server is running on

Mac OS

### Version of Immich Server

v.1.73.0

### Version of Immich Mobile App

v.1.73.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1.docker-compose pull && docker-compose up -d, got the 500 error.
2.Then I tried to docker-compose down, and to execute docker-compose up without -d, it works.
3.But after I turned down and execute docker-compose -up -d , the 500 error shows again.
```

**Comment by jrasm91** [comment]
Can you add the immich-server logs?

**Comment by alextran1502** [comment]
@Darvyn Convert to discussion, please continue the conversation here. Can you provide the logs?

**Reply by Darvyn** [reply]
Hi, @alextran1502 @jrasm91 , thanks for the quick reply, 
I just tried again, and niticed that maybe it's not a issue, I refreshed the browser and cleared the history data, and it works as usual.
So far it's good, maybe we can close this. And I'll observe and let you know if happens later.

> By the way, this app is awesome !

**Reply by alextran1502** [reply]
Ah Typesense might just take a while to start up and the server wait for Typesense to start up before getting everything in order

**Comment by trlsmax** [comment]
Same error with latest docker images
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^
<ref *1> Error: getaddrinfo ENOTFOUND typesense
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'typesense',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function (anonymous)] ],
    timeout: 10000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: Infinity,
    maxBodyLength: Infinity,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'X-TYPESENSE-API-KEY': 'some-random-text',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.26.1'
    },
    method: 'get',
    url: 'http://typesense:8108/collections',
    data: undefined
  },
  request: <ref *3> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [ [Function: handleRequestSocket], [Function: destroyOnTimeout] ]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/collections',
      method: 'GET',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'X-TYPESENSE-API-KEY': 'some-random-text',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.26.1'
      },
      agent: undefined,
      agents: { http: undefined, https: undefined },
      auth: undefined,
      hostname: 'typesense',
      port: '8108',
      nativeProtocols: {
        'http:': {
          _connectionListener: [Function: connectionListener],
          METHODS: [
            'ACL',         'BIND',       'CHECKOUT',
            'CONNECT',     'COPY',       'DELETE',
            'GET',         'HEAD',       'LINK',
            'LOCK',        'M-SEARCH',   'MERGE',
            'MKACTIVITY',  'MKCALENDAR', 'MKCOL',
            'MOVE',        'NOTIFY',     'OPTIONS',
            'PATCH',       'POST',       'PROPFIND',
            'PROPPATCH',   'PURGE',      'PUT',
            'REBIND',      'REPORT',     'SEARCH',
            'SOURCE',      'SUBSCRIBE',  'TRACE',
            'UNBIND',      'UNLINK',     'UNLOCK',
            'UNSUBSCRIBE'
          ],
          STATUS_CODES: {
            '100': 'Continue',
            '101': 'Switching Protocols',
            '102': 'Processing',
            '103': 'Early Hints',
            '200': 'OK',
            '201': 'Created',
            '202': 'Accepted',
            '203': 'Non-Authoritative Information',
            '204': 'No Content',
            '205': 'Reset Content',
            '206': 'Partial Content',
            '207': 'Multi-Status',
            '208': 'Already Reported',
            '226': 'IM Used',
            '300': 'Multiple Choices',
            '301': 'Moved Permanently',
            '302': 'Found',
            '303': 'See Other',
            '304': 'Not Modified',
            '305': 'Use Proxy',
            '307': 'Temporary Redirect',
            '308': 'Permanent Redirect',
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a Teapot",
            '421': 'Misdirected Request',
            '422': 'Unprocessable Entity',
            '423': 'Locked',
            '424': 'Failed Dependency',
            '425': 'Too Early',
            '426': 'Upgrade Required',
            '428': 'Precondition Required',
            '429': 'Too Many Requests',
            '431': 'Request Header Fields Too Large',
            '451': 'Unavailable For Legal Reasons',
            '500': 'Internal Server Error',
            '501': 'Not Implemented',
            '502': 'Bad Gateway',
            '503': 'Service Unavailable',
            '504': 'Gateway Timeout',
            '505': 'HTTP Version Not Supported',
            '506': 'Variant Also Negotiates',
            '507': 'Insufficient Storage',
            '508': 'Loop Detected',
            '509': 'Bandwidth Limit Exceeded',
            '510': 'Not Extended',
            '511': 'Network Authentication Required'
          },
          Agent: [Function: Agent] { defaultMaxSockets: Infinity },
          ClientRequest: [Function: ClientRequest],
          IncomingMessage: [Function: IncomingMessage],
          OutgoingMessage: [Function: OutgoingMessage],
          Server: [Function: Server],
          ServerResponse: [Function: ServerResponse],
          createServer: [Function: createServer],
          validateHeaderName: [Function: __node_internal_],
          validateHeaderValue: [Function: __node_internal_],
          get: [Function: get],
          request: [Function: request],
          setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
          maxHeaderSize: [Getter],
          globalAgent: [Getter/Setter]
        },
        'https:': {
          Agent: [Function: Agent],
          globalAgent: Agent {
            _events: [Object: null prototype],
            _eventsCount: 2,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object: null prototype],
            requests: [Object: null prototype] {},
            sockets: [Object: null prototype] {},
            freeSockets: [Object: null prototype] {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            scheduling: 'lifo',
            maxTotalSockets: Infinity,
            totalSocketCount: 0,
            maxCachedSessions: 100,
            _sessionCache: [Object],
            [Symbol(kCapture)]: false
          },
          Server: [Function: Server],
          createServer: [Function: createServer],
          get: [Function: get],
          request: [Function: request]
        }
      },
      pathname: '/collections'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: <ref *2> ClientRequest {
      _events: [Object: null prototype] {
        response: [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: Socket {
        connecting: false,
        _hadError: true,
        _parent: null,
        _host: 'typesense',
        _closeAfterHandlingError: false,
        _readableState: ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          destroyed: true,
          errored: [Circular *1],
          closed: true,
          closeEmitted: true,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: false,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
          end: [Function: onReadableStreamEnd],
          connect: [ [Function], [Function], [Function] ],
          free: [Function: onFree],
          close: [ [Function: onClose], [Function: socketCloseListener] ],
          timeout: [ [Function: onTimeout], [Function: destroy] ],
          agentRemove: [Function: onRemove],
          error: [Function: socketErrorListener],
          drain: [Function: ondrain]
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          errored: [Circular *1],
          closed: true,
          closeEmitted: true,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: 'GET /collections HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'X-TYPESENSE-API-KEY: some-random-text\r\n' +
          'Content-Type: application/json\r\n' +
          'User-Agent: axios/0.26.1\r\n' +
          'Host: typesense:8108\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _pendingEncoding: 'latin1',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular *2],
        timeout: 10000,
        [Symbol(async_id_symbol)]: 1192,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 64637,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: false,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 1199,
          [Symbol(triggerId)]: 1194
        },
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      _header: 'GET /collections HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'X-TYPESENSE-API-KEY: some-random-text\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Host: typesense:8108\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object: null prototype] { noDelay: true, path: null },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] {},
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 0,
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/collections',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'typesense',
      protocol: 'http:',
      _redirectable: [Circular *3],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        'x-typesense-api-key': [ 'X-TYPESENSE-API-KEY', 'some-random-text' ],
        'content-type': [ 'Content-Type', 'application/json' ],
        'user-agent': [ 'User-Agent', 'axios/0.26.1' ],
        host: [ 'Host', 'typesense:8108' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://typesense:8108/collections',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Node.js v18.17.0
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +101ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +10ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +390ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] InfraModule dependencies initialized +10ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] AppModule dependencies initialized +5ms
[Nest] 7  - 08/16/2023, 7:43:43 AM     LOG [InstanceLoader] DomainModule dependencies initialized +6ms
[Nest] 7  - 08/16/2023, 7:43:44 AM     LOG [SearchService] Running bootstrap
Request #1692171824214: Request to Node 0 failed due to "EHOSTUNREACH connect EHOSTUNREACH 172.22.0.9:8108"
Request #1692171824214: Sleeping for 4s and then retrying request...
Request #1692171824214: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1692171824214: Sleeping for 4s and then retrying request...
Request #1692171824214: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1692171824214: Sleeping for 4s and then retrying request...
Request #1692171824214: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1692171824214: Sleeping for 4s and then retrying request...
Request #1692171824214: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1692171824214: Sleeping for 4s and then retrying request...
```

**Reply by bo0tzz** [reply]
Your typesense container isn't running

**Reply by trlsmax** [reply]
Oh, you are right. typesense container just keep restarting.
And I just use a default config, how can I make it work ?

**Reply by alextran1502** [reply]
You can try `docker-compose down` then `docker-compose pull` and finally `docker-compose up`. If you have many assets, typesense might take a few minutes to index them.

**Comment by coutouly** [comment]
I have the same issue
`````
[arch@archlinux immich-app]$ docker compose logs -f immich-server
immich_server  | [Nest] 7  - 08/16/2023, 1:13:11 PM     LOG [NestFactory] Starting Nest application...
immich_server  | [Nest] 7  - 08/16/2023, 1:13:11 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +441ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:11 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:11 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +8ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:11 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +2ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:12 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +65ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:12 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +2ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:12 PM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:13 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +1864ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:13 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +4ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:13 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:13 PM     LOG [InstanceLoader] InfraModule dependencies initialized +47ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:13 PM     LOG [InstanceLoader] AppModule dependencies initialized +21ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:14 PM     LOG [InstanceLoader] DomainModule dependencies initialized +77ms
immich_server  | [Nest] 7  - 08/16/2023, 1:13:16 PM     LOG [SearchService] Running bootstrap
immich_server  | Request #1692191596579: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 172.24.0.8:8108"
immich_server  | Request #1692191596579: Sleeping for 4s and then retrying request...
immich_server  | Request #1692191596579: Request to Node 0 failed due to "EAI_AGAIN getaddrinfo EAI_AGAIN typesense"
immich_server  | Request #1692191596579: Sleeping for 4s and then retrying request...
immich_server  | Request #1692191596579: Request to Node 0 failed due to "EAI_AGAIN getaddrinfo EAI_AGAIN typesense"
immich_server  | Request #1692191596579: Sleeping for 4s and then retrying request...
immich_server  | Request #1692191596579: Request to Node 0 failed due to "ECONNREFUSED connect ECONNREFUSED 172.24.0.8:8108"
immich_server  | Request #1692191596579: Sleeping for 4s and then retrying request...
immich_server  | Request #1692191596579: Request to Node 0 failed due to "EAI_AGAIN getaddrinfo EAI_AGAIN typesense"
immich_server  | Request #1692191596579: Sleeping for 4s and then retrying request...

```

**Reply by alextran1502** [reply]
You can try `docker-compose down` then `docker-compose pull` and finally `docker-compose up`. If you have lots of assets, typesense might take a few minutes to index them.

**Reply by coutouly** [reply]
it s a new install and it is not running

**Comment by adambeck7** [comment]
I just upgraded to 1.73.0 and it is working fine for me. @coutouly and @trlsmax what does your docker-compose look like? Are you pulling the proper typesense version like:  
```
 typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
```

**Comment by coutouly** [comment]
I am in a New install not an update .
For an update it IS working fine
I am taking thé docker composé file as is it

**Reply by adambeck7** [reply]
Regardless of if it's a new install or update, you really need to post your docker-compose and env so we can see if everything looks correct.

**Comment by coutouly** [comment]
```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:

```
