### DISCUSSION TITLE
Run multiple instances of immich docker

### DISCUSSION THREAD

**Discussion by iceisraw** [immich-app/immich#375] [Q&A]
Hi. I tried the immich using the docker compose. Thank you very much for this app. We liked it so much that others in my household want to use the same app but with isolation from one another. Such that each of them have their docker app running. I want to run each instance of this app through docker on one Ubuntu host. Can each instance of the app run such that they use own separate backup folder and their own ip/port. Is it easily possible ? I tried simply running same thing twice with env file modified for each to account for port and folder path but it did not work. I am not sure if what I am asking even makes sense or considered appropriate from docker perspective.

**Comment by alextran1502** [comment]
What environment are you hosting, an RPi, or a dedicated server? If you have a dedicated server, you can spin up multiple VMs with different IP addresses so that each user will have access to their instance.

Suppose you want to spin up multiple instances on the same machine. In that case, it could hamper the machine's performance if multiple users choose to upload simultaneously, triggering image and video conversion (heavy CPU tasks). So to do that, follow the steps below:

1. Create a separate folder for each instance with a distinct name
2. Create a `docker-compose.yml` and put the `docker-compose` file content into it ([link](https://github.com/alextran1502/immich/blob/27ea3fc881/docker/docker-compose.yml))
3. In the docker-compose file, `immich-proxy`, use a different port for each instance.

For example, for Peter

```yaml
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2284:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```

for Alex

```yaml
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2285:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```
5. Populate the `.env` file in each folder with a different `UPLOAD_LOCATION`, which is dedicated to each person and the port you specified above for `VITE_SERVER_ENDPOINT`
6. From each folder, run `docker-compose up -d`

Anyway, I suggest using one instance with multiple accounts.
