### DISCUSSION TITLE
[BUG] Android app doesn't work with domain name and reverse prixy

### DISCUSSION THREAD

**Discussion by sosoelec** [immich-app/immich#3968] [Q&A]
### The bug

Hello, I have searched before and didn't see people having exactly the same issue as mine.

The immich android app doesn't want to connect to my immich server in https when it's going through my nginx reverse proxy (I tried with a self signed certificate but also with a publicly signed certificate through Let's encrypt)

I connect to to my reverse proxy through my home VPN, there is no issue on the browser to reach immich, the issue is only through the android mobile app.

When I disconnect my VPN i get the following error "Server unreachable" but when i turn ON my VPN on my android phone i have the error in french (my phone config language) : "Impossible de se connecter au serveur" (Impossible to connect to server)

I don't think that the issue comes from my reverse proxy because i have no issues through my browser, i have no logs shown in the app or on the reverse proxy.

When i type on the app : http**s**://immich.domain.com it doesn't work but http://immich.domain.com**:2283** works.
Both links work through the browser

Thank in advance for you help

Regards,

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.76.1

### Version of Immich Mobile App

v1.75.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/ssl/certs:/etc/ssl/certs
    env_file:
      - .env
    depends_on:
      - redis
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=redacted
DB_USERNAME=redacted
DB_PASSWORD=redacted
DB_DATABASE_NAME=redacted
NODE_TLS_REJECT_UNAUTHORIZED=0
# Optional Database settings:
DB_PORT=redacted
UPLOAD_LOCATION=<nfs folder>
PUBLIC_LOGIN_PAGE_MESSAGE="test msg"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Download the android app from f-droid
2. Launch the app
3. Enter the URL of reverse proxy that points to docker container on port 8223
Ex https://Galery.domain.com (that points to 127.0.0.1:2283 (config used : https://immich.app/docs/administration/reverse-proxy)

4. Error "Cann
```

**Comment by EnochPrime** [comment]
How do you have your nginx proxy configured?

**Comment by bo0tzz** [comment]
I've converted this to a discussion as it's unlikely to be a bug in Immich.

A self-signed certificate definitely won't work, so you should use an LE (or other CA) one. You say that accessing Immich directly on port 2283 works, so the issue must be with your reverse proxy somehow. Can you share your config?

I also see you've mounted some certs into the Immich containers - that won't do anything.

**Reply by sosoelec** [reply]
Hello, i'm currently using a left encrypt certificate and it still doesn't work. 

Here is my nginx configuration : 

````
server {
        listen 80 ;
        listen [::]:80 ;

        server_name photo.domain.eu;

        # location to redirect to https
        location / {
            return 301 https://$server_name$request_uri;
        }
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name photo.domain.eu;
	# let's encrypt certificate
        ssl_certificate /crt/photo.domain.eu.pem;
        ssl_certificate_key /crt/photo.domain.eu.key;

location / {
        proxy_pass http://localhost:2283;
        proxy_set_header Host              $http_host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        
        proxy_http_version 1.1;
        proxy_set_header   Upgrade    $http_upgrade;
        proxy_set_header   Connection "upgrade";
        proxy_redirect off;



        }
}
````
As i mentionned before, this configuration works  through the web browser, is there anything specific that should be added for the android app to work?
Thanks for your help

**Reply by jrasm91** [reply]
Probably http2 doesn't work with mobile.

**Comment by eygraber** [comment]
This is my config that is working on web and Android:

```
server {
    listen 80;
    server_name example.com;

    client_max_body_size 0;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name example.com;

    client_max_body_size 0;

    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    location / {
        proxy_pass http://192.168.86.2:2283;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

```
version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
```
