### DISCUSSION TITLE
[BUG] Unable to run job handler: TypeError: fetch failed

### DISCUSSION THREAD

**Discussion by Hadatko** [immich-app/immich#4085] [Q&A]
### The bug

Sorry to creating bug but discord login somehow not working for me.

When i upload foto, the processing in microservices fail.

```
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +30ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +4ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:19:59 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +156ms
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [InstanceLoader] InfraModule dependencies initialized +5ms
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [InstanceLoader] DomainModule dependencies initialized +10ms
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +0ms
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering thumbnailGeneration with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering metadataExtraction with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering videoConversion with a concurrency of 1
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering objectTagging with a concurrency of 2
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering recognizeFaces with a concurrency of 2
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering clipEncoding with a concurrency of 2
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering backgroundTask with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering storageTemplateMigration with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering search with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM   DEBUG [JobService] Registering sidecar with a concurrency of 5
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 7  - 09/10/2023, 9:20:00 AM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [MetadataExtractionProcessor] Reverse Geocoding Initialized
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [SearchService] Running bootstrap
[Nest] 7  - 09/10/2023, 9:20:09 AM   DEBUG [TypesenseRepository] assets-v8 collection has 7176 documents
[Nest] 7  - 09/10/2023, 9:20:09 AM   DEBUG [TypesenseRepository] faces-v1 collection has 0 documents
[Nest] 7  - 09/10/2023, 9:20:09 AM   DEBUG [TypesenseRepository] albums-v2 collection has 0 documents
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [TypesenseRepository] Schema up to date: assets/assets-v8
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [TypesenseRepository] Schema up to date: albums/albums-v2
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [TypesenseRepository] Schema up to date: faces/faces-v1
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [TypesenseRepository] Alias mapping: [{"collection_name":"faces-v1","name":"faces"},{"collection_name":"albums-v2","name":"albums"},{"collection_name":"assets-v8","name":"assets"}]
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [TypesenseRepository] Collections needing migration: {"assets":false,"albums":false,"faces":false}
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [NestApplication] Nest application successfully started +18ms
[Nest] 7  - 09/10/2023, 9:20:09 AM     LOG [ImmichMicroservice] Immich Microservices is listening on http://[::1]:3002 [v1.77.0] [PRODUCTION] 
[Nest] 7  - 09/10/2023, 9:24:43 AM   DEBUG [GeocodingRepository] Request: 49.4593658447222,18.1274585722222
[Nest] 7  - 09/10/2023, 9:24:43 AM   DEBUG [GeocodingRepository] Normalized: {"country":"Czech Republic","state":"Okres Vsetín, Zlín","city":"Rožnov pod Radhoštěm"}
[Nest] 7  - 09/10/2023, 9:24:44 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset baa9bc73-a1c0-41ac-8322-8fa4f6d48f8d
(node:7) ExperimentalWarning: buffer.File is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Nest] 7  - 09/10/2023, 9:24:45 AM   DEBUG [SearchService] Flushing 1 asset upserts
[Nest] 7  - 09/10/2023, 9:24:45 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset baa9bc73-a1c0-41ac-8322-8fa4f6d48f8d
[Nest] 7  - 09/10/2023, 9:24:47 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset 42fb37b3-2116-4e89-ab94-31b6f08bfcc9
[Nest] 7  - 09/10/2023, 9:24:48 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 42fb37b3-2116-4e89-ab94-31b6f08bfcc9
[Nest] 7  - 09/10/2023, 9:24:50 AM   DEBUG [SearchService] Flushing 1 asset upserts
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Unable to run job handler: TypeError: fetch failed
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async MachineLearningRepository.post (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:27:21)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/domain/smart-info/smart-info.service.js:120:31)
    at async /usr/src/app/dist/domain/job/job.service.js:105:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Object:
{
  "id": "baa9bc73-a1c0-41ac-8322-8fa4f6d48f8d",
  "source": "upload"
}
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Unable to run job handler: TypeError: fetch failed
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async MachineLearningRepository.post (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:27:21)
    at async FacialRecognitionService.handleRecognizeFaces (/usr/src/app/dist/domain/facial-recognition/facial-recognition.services.js:105:23)
    at async /usr/src/app/dist/domain/job/job.service.js:105:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Object:
{
  "id": "baa9bc73-a1c0-41ac-8322-8fa4f6d48f8d",
  "source": "upload"
}
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Unable to run job handler: TypeError: fetch failed
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async MachineLearningRepository.post (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:27:21)
    at async SmartInfoService.handleClassifyImage (/usr/src/app/dist/domain/smart-info/smart-info.service.js:77:22)
    at async /usr/src/app/dist/domain/job/job.service.js:105:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
[Nest] 7  - 09/10/2023, 9:25:09 AM   ERROR [JobService] Object:
{
  "id": "baa9bc73-a1c0-41ac-8322-8fa4f6d48f8d",
  "source": "upload"
}
```

### The OS that Immich Server is running on

ubuntu 22.04

### Version of Immich Server

latest release

### Version of Immich Mobile App

latest release

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    network_mode: local
    hostname: immich-server
    command: [ "start.sh", "immich" ]
    environment:
      - TZ=Europe/Prague
      - TYPESENSE_API_KEY=someRandomText
      - REDIS_SOCKET=/run/unixsocket/redis.sock
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_DATABASE=immich
      - DB_PASSWORD=password
    volumes:
      - /media/HDDDATA/immich:/usr/src/app/upload
      - redis_socket:/run/unixsocket
    depends_on:
      - redis
      - postgresql
      - typesense
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 8000M
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    network_mode: local
    environment:
      - TZ=Europe/Prague
      - TYPESENSE_API_KEY=someRandomText
      - REDIS_SOCKET=/run/unixsocket/redis.sock
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_DATABASE=immich
      - DB_PASSWORD=password
      - LOG_LEVEL=debug
    volumes:
      - /media/HDDDATA/immich:/usr/src/app/upload
      - redis_socket:/run/unixsocket
    depends_on:
      - redis
      - postgresql
      - typesense
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 8000M
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    hostname: immich-machine-learning
    network_mode: local
    environment:
      - TZ=Europe/Prague
      - TYPESENSE_API_KEY=someRandomText
      - REDIS_SOCKET=/run/unixsocket/redis.sock
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=password
    volumes:
      - immich_model_cache:/cache
    deploy:
      resources:
        limits:
          cpus: '5'
          memory: 8000M
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    hostname: immich-web
    network_mode: local
    environment:
      - TZ=Europe/Prague
      - TYPESENSE_API_KEY=someRandomText
      - REDIS_SOCKET=/run/unixsocket/redis.sock
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=password
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 1000M
    restart: always

  typesense:
    container_name: typesense
    image: typesense/typesense:0.26.0.rc17
    network_mode: local
    hostname: typesense
    environment:
      - TZ=Europe/Prague
      - TYPESENSE_API_KEY=someRandomText
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
      - REDIS_SOCKET=/run/unixsocket/redis.sock
      - DB_HOSTNAME=postgresql
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=password
    volumes:
      - typesense_data:/data
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 1000M
    restart: always
```

### Your .env content

```Shell
i don't have
```

### Reproduction steps

```bash
1.Upload file from mobile to server
```

**Comment by jrasm91** [comment]
It looks like your machine learning container isn't running.

**Comment by Hadatko** [comment]
It is running:
```bash
[09/13/23 14:47:11] INFO     Starting gunicorn 21.2.0                           
[09/13/23 14:47:11] INFO     Listening at: http://0.0.0.0:3003 (9)              
[09/13/23 14:47:11] INFO     Using worker: uvicorn.workers.UvicornWorker        
[09/13/23 14:47:11] INFO     Booting worker with pid: 10                        
[09/13/23 14:47:20] INFO     Created in-memory cache with unloading disabled.   
[09/13/23 14:47:20] INFO     Initialized request thread pool with 6 threads.    
[09/14/23 00:00:00] INFO     Loading image classification model                 
                             'microsoft/resnet-50'                              
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
[09/14/23 00:00:00] INFO     Loading clip model 'ViT-B-32::openai'              
[09/14/23 00:00:00] INFO     Downloading facial recognition model               
                             'buffalo_l'.This may take a while.                 
[09/14/23 00:00:01] WARNING  Failed to load facial-recognition model            
                             'buffalo_l'.Clearing cache and retrying.           
[09/14/23 00:00:01] INFO     Cleared cache directory for model 'buffalo_l'.     
[09/14/23 00:00:01] INFO     Downloading facial recognition model               
                             'buffalo_l'.This may take a while.                 
Downloading /cache/facial-recognition/buffalo_l/buffalo_l.zip from https://github.com/deepinsight/insightface/releases/download/v0.7/buffalo_l.zip...
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.11/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
  warnings.warn(

  0%|          | 0/281857 [00:00<?, ?KB/s]
  0%|          | 989/281857 [00:00<00:28, 9887.58KB/s]
  1%|          | 2024/281857 [00:00<00:29, 9573.99KB/s]
  1%|          | 2983/281857 [00:00<00:32, 85
...
...
s]
 99%|█████████▉| 280056/281857 [00:44<00:00, 6525.09KB/s]
100%|█████████▉| 280824/281857 [00:44<00:00, 6840.72KB/s]
100%|█████████▉| 281510/281857 [00:44<00:00, 6307.80KB/s]
100%|██████████| 281857/281857 [00:44<00:00, 6305.11KB/s]
[09/14/23 00:00:48] INFO     Loading facial recognition model 'buffalo_l'       

```

**Reply by jrasm91** [reply]
Is it reachable from the microservices container? There is something happening that is preventing them from communicating.

**Comment by Hadatko** [comment]
Sorry accidentally removed my second comment. It looks like my issue was fixed with recent immich update https://github.com/immich-app/immich/releases/tag/v1.78.0

**Comment by byjoker8625** [comment]
Im using version `1.88.2` and still get the same error:

```
[Nest] 7  - 11/28/2023, 6:56:38 PM   ERROR [JobService] Unable to run job handler (clipEncoding/clip-encode): TypeError: fetch failed
[Nest] 7  - 11/28/2023, 6:56:38 PM   ERROR [JobService] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.post (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:16:21)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/domain/smart-info/smart-info.service.js:85:31)
    at async /usr/src/app/dist/domain/job/job.service.js:108:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:385:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:572:24)
[Nest] 7  - 11/28/2023, 6:56:38 PM   ERROR [JobService] Object:
{
  "id": "b1b90718-56a3-4265-ad73-d0977138250e",
  "source": "upload"
}

[Nest] 7  - 11/28/2023, 6:56:39 PM     LOG [MediaService] Successfully generated WEBP video thumbnail for asset b1b90718-56a3-4265-ad73-d0977138250e
```

im using this compose file in portainer:

```yml
version: "3.8"

services:
  server:
    hostname: immich_serve
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  microservices:
    hostname: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  machine-learning:
    hostname: immich_marchine_lerning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  typesense:
    hostname: immich_typesense
    image: typesense/typesense:0.24.1
    volumes:
      - typesense:/data
    env_file:
      - stack.env
    restart: always

  redis:
    hostname: immich_redis
    image: redis:6.2-alpine
    env_file:
      - stack.env
    restart: always

  database:
    image: postgres:14-alpine
    hostname: immich_postgres

    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - stack.env
    restart: always

volumes:
  postgres:
  model-cache:
  typesense:
```
