### DISCUSSION TITLE
[BUG] I can't set the network for anything different than immich_default

### DISCUSSION THREAD

**Discussion by RebeliusGaming** [immich-app/immich#4173] [Q&A] [answered]
### The bug

I installed immich, but now I need it to be in the same custom docker network that some other containers.
As docker compose works, if there is no information, the containers deploy with a "[containername]_default" network. (in this case immich_default)
I want to configure it to use a previous existing custom network called "patacona"

What I tried, is the next cases:
1) To install all the services under the previous custom network:
      For this, I added 
      `networks:
        patacona:`
   to every service, and also a top level entry
   `networks:
      patacona:
        external: true`
        
In this sitouation, what I achieved is to have all the services installed with a really long string name corresponding to the NETWORK ID, where it should be the nework name.
HERE you can see in red the weird network name, that starts the same than the network id of the custom network as you can see in yellow.
In blue, there should be some port mapping, that there is no more.
<img width="654" alt="immich bad installation" src="https://github.com/immich-app/immich/assets/94674848/76eac17f-ad8a-4721-a499-eb00cc05e1e7">

### The OS that Immich Server is running on

Unraid 6.12.4

### Version of Immich Server

v1.78.1

### Version of Immich Mobile App

v1.78.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
     patacona:

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
     patacona:

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
     patacona:

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    networks:
     patacona:

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always
    networks:
     patacona:

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
     patacona:

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
     patacona:

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
     patacona:

volumes:
  pgdata:
  model-cache:
  tsdata:
  
networks:
 patacona:
  external: true
  name: patacona
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/photos/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Modify the docker compose to use the custom nework
2. Deploy as instructed.
```

### Additional information

I am still able to connect through the local ip:port of the normal installation with the immich_default network

**Comment by jrasm91** [comment]
It's possible those are orphan containers. Maybe try removing the stack and re-adding it.

**Reply by RebeliusGaming** [reply]
Do you mean "compose down"?

**Comment by Allram** [comment]
This is my compose file, i use the network name "immich" in this compose file, but that will only account for the dockers inside, they still get the ip-address from my external network from my UnRaid network called eth0.30 (on VLAN 30, if not it would have been only eth0. Your's might be something else or perhaps br0):

```version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /tmp/Postgresql/postgresql/:/var/run/postgresql
      - /tmp/Redis/Redis/:/var/run/redis
    env_file:
      - .env
    depends_on:
      - typesense
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.17
    labels:
    - TZ=Europe/Oslo
    - "traefik.enable=true"
    - "traefik.http.routers.immich-api.entryPoints=https"
    - "traefik.http.services.immich-api.loadbalancer.server.port=3001"
    - "traefik.http.routers.immich-api.rule=Host(`DOMAIN`) && Pathprefix(`/api`)"
    - "traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes=/api"
    - "traefik.http.routers.immich-api.middlewares=middlewares-secure-headers@file,service-immich-api-strip"
    environment:
      - TZ=Europe/Oslo
        

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: /mnt/apps/appdata/Immich/microservices/hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /tmp/Postgresql/postgresql/:/var/run/postgresql
      - /tmp/Redis/Redis/:/var/run/redis
    env_file:
      - .env
    depends_on:
      - typesense
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.18
    environment:
      - TZ=Europe/Oslo

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/apps/appdata/Immich/machine-learning:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.30
    environment:
      - TZ=Europe/Oslo

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.16
    labels:
    - "TZ=Europe/Oslo"
    - "traefik.enable=true"
    - "traefik.http.routers.immich-web.entryPoints=https"
    - "traefik.http.services.immich-web.loadbalancer.server.port=3000"
    - "traefik.http.routers.immich-web.rule=Host(`DOMAIN`)"
    - "traefik.http.routers.immich-web.middlewares=middlewares-secure-headers@file"
    environment:
      - TZ=Europe/Oslo

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      - TZ=Europe/Oslo
      - GLOG_minloglevel=1
    volumes:
      - /mnt/apps/appdata/Immich/typesense:/data
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.10
        
  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - TZ=Europe/Oslo
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:2283
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.23



networks:
  immich:
    name: eth0.30
    external: true`

**Reply by Allram** [reply]
If you don't want to give each docker a static ip-address, you could try this on each docker:


 networks:
    - immich

Instead of my solution:
    networks:
      immich:
        ipv4_address: 192.168.30.23

**Reply by RebeliusGaming** [reply]
is that hypehn before immich a typo?

Tried to remove the stack, delete all orphan containers, copy your code, without my unused features as traefik, hwaccel, specific ip, and it installs everything, but with the same problem.
The custom previous network name "patacona" is not usend and instead it gives me a long string starting with the network id of patacona:
<img width="841" alt="network id as network name" src="https://github.com/immich-app/immich/assets/94674848/7f529ab1-36c3-4ee4-a34f-fba110f12dcc">

As I had my previous Immich installation bookmarked, I can access with the same ip, evendough I cant see the port mapping info in the docker containers.

**Reply by Allram** [reply]
That is correct. You won't see the Immich/network IP's or ports in unRAID GUI.
But as long as you use the external part, it gets ip-addresses from your unRAID network.

**Reply by RebeliusGaming** [reply, marked as answer]
Thats right, and unconvenient.
Anyway, I managed to give it the name patacona, using the name tag in the global networks:  section. I don't know why it is working now, as I did everything as before. The only thing I did different was composing down prior to composing up.


Thank you for participating!

**Reply by serfriz** [reply]
Hey, I am having the same issue with Unraid, can you share your working docker-compose? Thanks!

**Reply by mompl** [reply]
Same here.
I don't quite understand the part with "using the name tag in the global networks: section."
How can I achieve to have the correct name displayed?

**Reply by RebeliusGaming** [reply]
Hi. In that moment it worked, but as I said, I don't know what I did to make it work.

I finally uninstalled, and installed through the appstore. Way easier

**Comment by DrJohnsn** [comment]
Does anyone already have a solution?

Is this a general problem ?

Will all compose containers have this error ?

**Comment by Lakers2O13** [comment]
For anyone stumbling upon this thread and trying to figure out how to change the network to a custom value and then view what that is, I'll walk you through what I did. It's essentially what everyone above described, but I've put it together in a clearer format. Hopefully, it helps.

1. **Adjusting Network Settings in Unraid**:
   - In the Docker tab on Unraid, click the cog wheel under "Compose" next to the Immich stack, then select "Compose File". You have a couple of options here:
     - Create a new network and assign all the containers to that network.
     - Add an existing network, possibly one used for a proxy, and assign all the containers to that external network.  I chose this option since I had already set up Nginx Proxy Manager for other containers and I wanted to use the same docker network.

2. **Modifying the Compose File**:
   - In the compose file, scroll to the bottom and add the following after the "volumes" section (it doesn't have to be placed there, but it's neatest and easy to find):
     ```yaml
     networks:
       your_network_name:
         external: true
     ```
     Here, we're telling the compose file about our custom networks. We define a network (replace `your_network_name` with whatever your network's name is) and indicate that it's an external network that already exists. If you choose not to use `external: true`, Docker Compose will create and manage the network itself, rather than expecting the network to already exist.

3. **Assigning Containers to the Network**:
   - Now that we've defined the network, we need to assign the containers to use it. For each of the five containers (`immich_server`, `immich-microservices`, `immich-machine-learning`, `redis`, `database`), add the following under their service definitions:
     ```yaml
     networks:
       - your_network_name
     ```
     Note: There are five containers if you're using the default configuration for Immich. This step forces each container to utilize the network we defined earlier.

4. **Applying Changes**:
   - After making these adjustments, save the compose file. Use `docker-compose down` followed by `docker-compose up` to restart the services. Once the containers have restarted, you might see a series of numbers and letters next to the containers in the Unraid GUI, representing the network ID.

5. **Verifying Port Mappings**:
   - First, run `docker container ls` from the Unraid CLI (accessible via the Terminal icon at the top right of the Unraid GUI) to confirm the containers are running. You should see all relevant containers listed. Next to "immich_server" under the "PORTS" column, you might see `0.0.0.0:2283->3001/tcp`, indicating the internal service port (`3001`) is mapped to an external port (`2283`) on your Unraid server. Keep note of the external port because we will be using that to access our web GUI at the end.

6. **Inspecting the Custom Network**:
   - Use `docker network ls` in the CLI to find your custom network (`your_network_name`). Take note of the "NETWORK ID". Fun fact, this ID is the beginning of the string you saw instead of IP addresses in the Unraid GUI. You can see how they are the same in the images below (first image shows containers with long string; second image shows CLI output with network ID).  

![Untitled-2](https://github.com/immich-app/immich/assets/112349889/090f8d99-a474-4d15-889e-aaf3e5b03705)
![image](https://github.com/immich-app/immich/assets/112349889/4ff35c1a-2873-48d7-8d9e-0a9c49568e25)

Next, use `docker network inspect NETWORK_ID` (replace `NETWORK_ID` with your actual network ID) to view detailed information about the custom Docker network. In the "Containers" section of the output, you should see all the containers assigned an IPv4 address, indicating successful network assignment.

7. **Accessing the Web GUI**:
   - To access the Immich server web GUI, use your Unraid server's IP address and the external port from step 5. For example: `http://192.168.1.100:2283`.

8. **Setting Up Nginx Proxy Manager**:
   - If you're looking to set up Nginx Proxy Manager, I recommend watching some tutorial videos, such as those by IBRACORP, which I found very helpful. Once set up, you can create a new proxy host with the IP address and port mentioned earlier, ensuring to activate all relevant switches and SSL settings with your certificate for a successful configuration.  Take your time to set everything up properly.  Generally people use NPM to access their internal services out on the web, and while its convenient, it could be a security risk.  If you don't understand it, ask around until you do.  Better to be safe then sorry.

Disclaimer: I'm not a professional, and this walkthrough is based on my experience and understanding. It worked for my system, and I hope it helps others who are navigating similar setups. Your setup and results may vary, so please adjust instructions as necessary for your environment.
