### DISCUSSION TITLE
Configuration to backup postgresql database (Immich data related to photos) Request and question/solution

### DISCUSSION THREAD

**Discussion by lordraiden** [immich-app/immich#4314] [Feature Request]
### The feature

A corrupted postgre database would mean that all the album and configuration would be lost.
As far as I know Immich doesn't have a native way to export or backup the configuration and I think there should be a way to do it.

In the mean time I am using this to do the database backup 
https://github.com/prodrigestivill/docker-postgres-backup-local
But I'm not sure what would be the correct parameters to run the backup for immich
POSTGRES_EXTRA_OPTS
Here is some documentation I would appreciate if someone can help
https://www.postgresql.org/docs/current/app-pgdump.html

I'm using this in the docker compose, it's working, but I'm not sure if the  "- POSTGRES_EXTRA_OPTS=-Z6" variable is fine/enough or not.

```
  pgbackups:
    container_name: Immich_pgbackups  
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    user: postgres:postgres # Optional: see below
    networks:
      - immich_network    
    volumes:
      - /mnt/user/Docker/Immich/pgbackups:/backups
    links:
      - database
    depends_on:
      - database
    environment:
      - TZ
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
     #- POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z6
      - SCHEDULE=30 1 */3 * * #At 01:30 AM, every 3 days
      - BACKUP_KEEP_DAYS=6
      - BACKUP_KEEP_WEEKS=1
      - BACKUP_KEEP_MONTHS=0
      - HEALTHCHECK_PORT=5432
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
```

### Platform

- [X] Server
- [X] Web
- [ ] Mobile
