### DISCUSSION TITLE
System requirements for low-end UX

### DISCUSSION THREAD

**Discussion by davidecavestro** [immich-app/immich#4364] [Show and tell]
While still far from having a fine-tuned config to share, I certainly have Immich running on a NAS equipped with just 4Gb of RAM and a dual-core Celeron N4505: both _face recognition_ and _typesense_ are enabled.

So I would like to share my experience and collect feedback, so that other low-end users give Immich a try, as **it really works like a charm** even on devices like mine.

The first time I considered running Immich on this hardware, I read the official docs and decided to give up: minimum requirements were not met. 

Then - after a lot of headaches with other software - I gave it a try and: KABOOM! I started with ML and search disabled, then enabled them.

Now my configuration is still not fine-tuned, but for sure docker is running Immich like this: 

![image](https://github.com/immich-app/immich/assets/447917/b9d869c6-0172-41a7-bd49-a88dcb7dc757)

This is an excerpt of my _compose.yml_:

```yaml title="compose.yml"
version: "3.8"

services:
  immich-server:
    ...
    deploy:
      resources:        
        limits:
          cpus: '1'
          memory: '1024M'

  immich-microservices:
    ...
    deploy:
      resources:        
        limits:
          cpus: '0.6'
          memory: '768M'

  immich-machine-learning:
    ...
    deploy:
      resources:
        limits:
          cpus: '1.2'
          memory: '1300M'

  typesense:
    ...
    deploy:
      resources:
        limits:  
          cpus: '0.4'
          memory: '512M'

  # no limits in place for remaining services
```

But please note that I also set some global cgroup limits to 3.2Gb of memory and 1.8 CPU cores for the whole docker stuff, so that - in case of spikes - single limits are further bounded by global ones:

```bash
#!/bin/bash

CG_NAME=docker

MEMORY=3200
CPU=180
# Create the cgroups in case they don't exist yet
mkdir -p /sys/fs/cgroup/memory/$CG_NAME
mkdir -p /sys/fs/cgroup/cpu/$CG_NAME

# Set the limits
echo $(($MEMORY * 1024 * 1024)) > /sys/fs/cgroup/memory/$CG_NAME/memory.limit_in_bytes

echo 100000 > /sys/fs/cgroup/cpu/$CG_NAME/cpu.cfs_period_us
echo $(($CPU * 1000)) > /sys/fs/cgroup/cpu/$CG_NAME/cpu.cfs_quota_us

```

At the moment this system is also running a _jellyfin_ instance and some scheduled _rclone_ copy tasks.

TBH I cannot assure containers are never killed this way: maybe it could happen if I launch a lot of concurrent batch jobs.
THat said I'm sure this way it just works properly for me, and I will refine it if needed.

Anyone tried something similar?
What was the oucome?
