### DISCUSSION TITLE
Traefik Documentation

### DISCUSSION THREAD

**Discussion by ilkersigirci** [immich-app/immich#437] [Q&A] [answered]
I have been using this app from the beginning with traefik docker-compose setup. But after changes in `/api` path in the URI, I couldn't manage to work it with traefik. Is there any documentation about it or does anyone able to work it with the latest version? If requested, I can share my traefik file which was working before `api` and `immich_nginx` changes

**Comment by alextran1502** [comment]
@zackpollard Is this something you can share for this?

**Comment by alextran1502** [comment]
From the architecture stand, if you opt-out of using `immich-proxy` then you need to expose port `3001` on `immich-server` container to the host and point any `/api` back to `http://your-local-ip:3001`

**Reply by ilkersigirci** [reply]
I was hoping to not use `immich-proxy` since `traefik` can handle reverse proxy setup nicely.

**Reply by alextran1502** [reply]
Yep, can you try the general direction above while waiting for Zack? I know he uses Traefik and also does not use `immich-proxy` container.

**Reply by ilkersigirci** [reply]
Ok, I will give it a try. Actually, if I don't use `traefik`, everything is working as expected. I will search how to do what you write above
Thank you for the fast reply, btw.

**Comment by NegativeFeedback** [comment, marked as answer]
I have just finished setting up a nomad job to run this behind traefik, without nginx.
` service {
      name = "service-immich-http"
      port = "3000"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name = "database-postgres"
              local_bind_port  = 5432
            }
          }
        }
      }


      tags = [
        "traefik.enable=true",
        "traefik.consulcatalog.connect=true",
        "traefik.http.routers.service-immich-http.entrypoints=https",
        "traefik.http.routers.service-immich-http.rule=Host(`immich.url.io`)",
        "traefik.http.routers.service-immich-http.tls=true",
        "traefik.http.routers.service-immich-http.tls.certresolver=lets-encrypt",
        "traefik.http.routers.service-immich-http.tls.domains[0].main=*.url.io"
      ]
    }

    service {
      name = "service-immich-api"
      port = "3001"

      connect {
        sidecar_service {
        }
      }

      tags = [
        "traefik.enable=true",
        "traefik.consulcatalog.connect=true",
        "traefik.http.routers.service-immich-api.entrypoints=https",
        "traefik.http.routers.service-immich-api.rule=Host(`immich.url.io`) && Pathprefix(`/api`)",
        "traefik.http.routers.service-immich-api.middlewares=service-immich-api-strip",
        "traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes=/api",
        "traefik.http.routers.service-immich-api.tls=true",
        "traefik.http.routers.service-immich-api.tls.certresolver=lets-encrypt",
        "traefik.http.routers.service-immich-api.tls.domains[0].main=*.url.io"
      ]
    }`

**Reply by ilkersigirci** [reply]
Wow, this helps a lot.

I was using
```
- "traefik.http.middlewares.add-api.addPrefix.prefix=/api"
```

but changing it to your version
```
- "traefik.http.middlewares.add-api.stripprefix.prefixes=/api"
```

fixes my problem. Thanks

**Reply by ilkersigirci** [reply]
If anyone wants, I can share my whole traefik docker-compose file

**Reply by fbinabri** [reply]
can you please share your traefik docker-compose file

**Reply by sbkg0002** [reply]
> If anyone wants, I can share my whole traefik docker-compose file

I'm also interested!

**Reply by cerealcable** [reply]
@sbkg0002 see my [comment below](https://github.com/immich-app/immich/discussions/437#discussioncomment-3609797), hopefully it gives you some understanding of how I did the very same.

**Comment by cerealcable** [comment]
Here is my full docker-compose for immich, it uses an external network for my traefik instance (named proxy). 

```yaml
version: "3.8"

networks:
  proxy:
    external:
      name: proxy
  immich:

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    networks:
      - proxy
      - immich
    labels:
      traefik.enable: "true"
      traefik.http.services.media-immich-api.loadbalancer.server.port: "3001"
      traefik.http.routers.media-immich-api.rule: "Host(`immich.domain.tld`) && Pathprefix(`/api`)"
      traefik.http.routers.media-immich-api.middlewares: service-immich-api-strip
      traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes: "/api"
      traefik.http.routers.media-immich-api.tls: true
      traefik.http.routers.media-immich-api.tls.certresolver: letsencrypt
      traefik.http.routers.media-immich-api.tls.domains[0].main: "*.domain.tld"
      traefik.http.routers.media-immich-api.entrypoints: websecure
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    networks:
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    networks:
      - proxy
      - immich
    labels:
      traefik.enable: "true"
      traefik.http.services.media-immich.loadbalancer.server.port: "3000"
      traefik.http.routers.media-immich.rule: "Host(`immich.domain.tld`)"
      traefik.http.routers.media-immich.tls: true
      traefik.http.routers.media-immich.tls.certresolver: letsencrypt
      traefik.http.routers.media-immich.tls.domains[0].main: "*.domain.tld"
      traefik.http.routers.media-immich.entrypoints: websecure
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    networks:
      - immich
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always

  #immich-proxy:
  #  container_name: immich_proxy
  #  image: altran1502/immich-proxy:release
  #  ports:
  #    - 2283:80
  #  logging:
  #    driver: none
  #  depends_on:
  #    - immich-server
  #  restart: always
```

My traefik docker-compose file looks like below. It's assuming a docker network named proxy has previously been created. I am using wildcard ssl certificates from lets-encrypt so I'm using the gandi provider for that, obviously this would need to be adjusted for your own scenario.

```yaml
version: "3.7"

networks:
  proxy:
    external:
      name: proxy

services:
  traefik:
    container_name: traefik
    image: traefik:2.3
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      traefik.http.routers.api.service: "api@internal"
      traefik.http.routers.api.entrypoints: "traefik"
    environment:
      - GANDIV5_API_KEY=SUPER_SECRET_KEY
    command:
      # See https://doc.traefik.io/traefik/contributing/data-collection/
      - --global.sendAnonymousUsage=false
      # See https://doc.traefik.io/traefik/observability/logs/
      - --log.filePath=/data/traefik.log
      - --log.level=INFO
      # See https://doc.traefik.io/traefik/observability/access-logs/
      - --accessLog
      # See https://doc.traefik.io/traefik/operations/api/
      - --api=true
      - --api.dashboard=true
      # See https://doc.traefik.io/traefik/routing/entrypoints/#redirection
      - --entryPoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.traefik.address=:8080
      # See https://doc.traefik.io/traefik/https/acme/
      - --certificatesresolvers.letsencrypt.acme.email=email@domain.tld
      - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=gandiv5
      # https://doc.traefik.io/traefik/providers/docker/
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --providers.docker.watch=true
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

The only issue I currently have is the ML portion isn't identifying anything, of course I'm also not sure exactly what to expect either so maybe it's working and I simply don't know it. I've only uploaded a few photos and haven't seen anything detected yet.

**Reply by zakul** [reply]
Hi @cerealcable,
thanks so much for sharing docker-compose files.
I adapted them for use with the current and everything works like a breeze.
Maybe a rather simple question, but how is the API exposed by Traefik? 
Is it `immich.domain.tld/api`? Or do I need to specify the port as well?

**Okay, never mind. It is `immich.domain.tld/api` :)**

**Reply by cerealcable** [reply]
I have updated my deployment a bit since I've posted this and now just use a `docker-compose.override.yml` file.

`docker-compose.override.yml`:
```yaml
networks:
  proxy:
    external: true
  immich:

services:
  immich-server:
    labels:
      traefik.enable: "true"
      traefik.http.services.immich-api.loadbalancer.server.port: "3001"
      traefik.http.routers.immich-api.rule: "Host(`immich.domain.tld`) && Pathprefix(`/api`)"
      traefik.http.routers.immich-api.middlewares: service-immich-api-strip
      traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes: "/api"
      traefik.http.routers.immich-api.tls: true
      traefik.http.routers.immich-api.tls.certresolver: letsencrypt
      traefik.http.routers.immich-api.tls.domains[0].main: "immich.domain.tld"
      traefik.http.routers.immich-api.entrypoints: websecure
    networks:
      - proxy
      - immich
    expose:
      - 3001

  immich-microservices:
    networks:
      - immich
    expose:
      - 3001

  immich-machine-learning:
    networks:
      - immich

  immich-web:
    labels:
      traefik.enable: "true"
      traefik.http.services.immich-web.loadbalancer.server.port: "3000"
      traefik.http.routers.immich-web.rule: "Host(`immich.domain.tld`)"
      traefik.http.routers.immich-web.tls: true
      traefik.http.routers.immich-web.tls.certresolver: letsencrypt
      traefik.http.routers.immich-web.tls.domains[0].main: "immich.domain.tld"
      traefik.http.routers.immich-web.entrypoints: websecure
    networks:
      - proxy
      - immich
    expose:
      - 3000

  typesense:
    networks:
      - immich
  
  redis:
    networks:
      - immich
    expose:
      - 6379

  database:
    networks:
      - immich
    expose:
      - 5432

  immich-proxy:
    entrypoint: ["echo", "Service disabled"]
    networks: []
    ports: []
    restart: "no"
```
This works better IMO than my previous example and still does the same design as before where the API is hosted at `immich.domain.tld/api`.

**Reply by fcogomez** [reply]
Any idea on how to do this with the latest version @cerealcable ?

**Reply by cerealcable** [reply]
I was able to follow the guides quite easily, which resulted in my efforts looking like the following. Hopefully it helps!

`docker-compose.yml`:
```yaml
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

And here's my updated `docker-compose.override.yml`:
```yaml
networks:
  proxy:
    external: true
  immich:

services:
  immich-server:
    labels:
      traefik.enable: "true"
      traefik.http.services.immich.loadbalancer.server.port: "3001"
      traefik.http.routers.immich.rule: "Host(`immich.domain.tld`)"
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.tls.certresolver: letsencrypt
      traefik.http.routers.immich.tls.domains[0].main: "immich.domain.tld"
      traefik.http.routers.immich.entrypoints: websecure
    networks:
      - proxy
      - immich
    expose:
      - 3001

  immich-microservices:
    networks:
      - immich
    expose:
      - 3001

  immich-machine-learning:
    networks:
      - immich

  redis:
    networks:
      - immich
    expose:
      - 6379

  database:
    networks:
      - immich
    expose:
      - 5432
```

**Reply by fcogomez** [reply]
Thanks for your config, it is a little different when the two servers are on different network, but the key issue for me was a DNS issue, after fixing that everything works now. Thanks @cerealcable

**Reply by hitesh-singh** [reply]
Thanks much @cerealcable works like a charm. I ended up adding few more traffic labels (as following) for my setup
```yaml
labels:
  - "traefik.enable=true"
  - "traefik.http.routers.immich.entrypoints=http"
  - "traefik.http.routers.immich.rule=Host(`immich.domain.com`)"
  - "traefik.http.middlewares.immich-https-redirect.redirectscheme.scheme=https"
  - "traefik.http.routers.immich.middlewares=immich-https-redirect"
  - "traefik.http.routers.immich-secure.entrypoints=https"
  - "traefik.http.routers.immich-secure.rule=Host(`immich.domain.com`)"
  - "traefik.http.routers.immich-secure.tls=true"
  - "traefik.http.routers.immich-secure.service=immich"
  - "traefik.http.services.immich.loadbalancer.server.port=3001"
  - "traefik.docker.network=traefik_network"
```

**Reply by dcwestra** [reply]
For the life of me I cannot get this to work. I keep getting a bad gateway error. Im sure im missing something obvious. I would greatly appreciate any help. Here is my docker compose:

```
networks:
  traefik:
    external: true
  immich:
    name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - LOG_LEVEL=verbose
    env_file:
      - .env
    expose:
      - 3001
    networks:
      - traefik
      - immich
    depends_on:
      - redis
      - database
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entryPoints: https
      traefik.http.routers.immich.rule: Host(`photos.mydomain.com`)
      traefik.http.routers.immich.tls: true
      traefik.http.services.immich.loadbalancer.server.port: 3001


  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: 
      file: hwaccel.transcoding.yml
      service: quicksync 
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - immich
    expose:
      - 3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    networks:
      - immich
    expose:
      - 6379

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich
    expose:
      - 5432
    restart: always

volumes:
  model-cache:
```

And, due to notes in the documentation about making sure proper headers are being passed, here is the headers section of my dynamic fileConfig for traefik:

```
securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "noindex,nofollow"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
          - "X-Forwarded-Server"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          Connection: Upgrade
          Upgrade: websocket
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
```

As a side note, ive noticed that when a run `sudo docker ps` the microservices container says port 3001 is listening, but when running `sudo docker logs immich_microservices` the log says it is listening on port 3002. Im sure thats not the problem here as I can access normally from ip:port when exposed without a proxy.
