### DISCUSSION TITLE
[BUG] face recognition is merging my kids' child pictures as if they were all the same people

### DISCUSSION THREAD

**Discussion by pdarcos** [immich-app/immich#4440] [Q&A] [answered]
### The bug

Hi guys,

First of all thank you for this great project. I'm loving it.

I noticed that the face recognition algo is pretty unreliable when it comes to baby/toddler faces (understandbly so since many babies look alike, specially from the same parents).

In my case the algo has merged together (without me doing anything besides assigning names to my kids' recent pictures) my kids as if they were only one person. I suspect the algo is being misled because they did look alike when they were toddlers.

Is there any way that I can retrain the algo to tell it that they are not the same person? In other words what can we do when the algo makes mistakes?

If there's no easy solution I don't mind digging into the weeds and changing database entries manually or whatever.

And thanks for this great project!

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.8.1

### Version of Immich Mobile App

v1.8.0 build 120

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /media/nas/media/homevideos:/mnt/media/nas/homevideos:ro
      - /media/nas/media/photos:/mnt/media/nas/photos:ro
      
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /media/nas/media/homevideos:/mnt/media/nas/homevideos:ro
      - /media/nas/media/photos:/mnt/media/nas/photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/smb_nas/immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=redacted
DB_PASSWORD=redacted
DB_HOSTNAME=immich_postgres
DB_USERNAME=redacted
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. As explained above on a fresh install I just tagged a few recent photos of my kids with their names
2. Subsequently searching for their pictures I noticed that immich assigned the wrong person to some of their baby/toddler pictures
3.
...
```
