### DISCUSSION TITLE
[BUG] Unable to send file: Error EPIPE

### DISCUSSION THREAD

**Discussion by bestrocker221** [immich-app/immich#4754] [General]
### The bug

While trying to play a video, it stutters and lags and in the logs I can see the errors
```
immich_server            | [Nest] 7  - 10/30/2023, 11:19:58 PM   ERROR [AssetService] Unable to send file: Error
immich_server            | Error: write EPIPE
immich_server            |     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
immich_server            |     at writeGeneric (node:internal/stream_base_commons:151:3)
immich_server            |     at Socket._writeGeneric (node:net:952:11)
immich_server            |     at Socket._write (node:net:964:8)
immich_server            |     at doWrite (node:internal/streams/writable:465:12)
immich_server            |     at clearBuffer (node:internal/streams/writable:625:7)
immich_server            |     at Writable.uncork (node:internal/streams/writable:407:7)
immich_server            |     at connectionCorkNT (node:_http_outgoing:955:8)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
```

This happens already when viewing a video from same network

### The OS that Immich Server is running on

debian 11

### Version of Immich Server

v1.83.0

### Version of Immich Mobile App

v1.83.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    #user: "1000:1000"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${MYLIB_LOCATION}:/usr/src/app/mylibrary:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    #user: "1000:1000"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${MYLIB_LOCATION}:/usr/src/app/mylibrary:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    #user: "1000:1000"
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    user: "1000:1000"

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    user: "1000:1000"
    volumes:
      - ./tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    #user: "1000:1000"

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    #user: "1000:1000"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
```

### Your .env content

```Shell
#You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=XXXX
MYLIB_LOCATION=YYYY

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# added by me
NODE_OPTIONS="--max-old-space-size=8192"
TYPESENSE_API_KEY=blah-bliggedy-blah

PUBLIC_LOGIN_PAGE_MESSAGE="Your own private photo library."
###

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Index videos folder from external library
2.Play them from browser
3.
...
```
