### DISCUSSION TITLE
[BUG] Android App duplicate with external library

### DISCUSSION THREAD

**Discussion by toxic0berliner** [immich-app/immich#4763] [Feature Request]
### The bug

Given the warning to not use immich as the sole backup app for your pictures, I am still using an external app that backups all my pictures from my android phone to my NAS.
I just moved from a custom importer script to the external library feature.

But now, immich is not able to recognize anymore that the same picture is on my phone and on the server. I get a duplicate for each picture, one with a cloud only icon for the one on the server, and one with a crossed cloud for the one on my phone.

In the past I used to get a proper deduplication with a single picture and a checkmark inside the little cloud icon.

Maybe something broke and external libs are not matched against the local android pictures ?

### The OS that Immich Server is running on

Docker image running on ubuntu 22.04

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

1.80.0 build.104

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - immich-upload:/usr/src/app/upload
      - orion-photo:/mnt/orion/photo
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      immichnet:
        aliases: 
          - immich-server

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - immich-upload:/usr/src/app/upload
      - orion-photo:/mnt/orion/photo
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      immichnet:
        aliases: 
          - immich-microservices

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
      immichnet:
        aliases: 
          - immich-machine-learning

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always
    networks:
      immichnet:
        aliases: 
          - immich-web

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always
    networks:
      immichnet:
        aliases: 
          - typesense

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      immichnet:
        aliases: 
          - redis

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      immichnet:
        aliases: 
          - database

  photo:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    labels:
      traefik.http.services.photo.loadbalancer.server.port: 8080
      traefik.docker.network: traefiknetwork
      subdomain: photo
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
      - IMMICH_WEB_URL=${IMMICH_WEB_URL}
    #ports:
    #  - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      traefiknetwork:
        aliases: 
          - photo
      immichnet:
        aliases: 
          - immich_proxy
  

  
  
volumes:
  pgdata:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/pgdata
  model-cache:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/model-cache
  tsdata:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/tsdata
  orion-photo:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_ORION}/photo
  immich-upload:
    driver: local-persist
    driver_opts:
      # mountpoint: ${BASE_ORION}/photo/immich
      mountpoint: ${BASE_ORION}/docker/volumes/immich
networks:
  traefiknetwork:
    name: traefiknetwork
    driver: bridge
    external: true
  immichnet:
    name: immichnet
    driver: bridge
    external: false
    attachable: true
```

### Your .env content

```Shell
STACKNAME=photo
BASE_VOLUMES=/var/lib/docker/local-persist
BASE_ORION=/mnt/orion
PUID=5678
PGID=100
TZ=Europe/Paris
UMASK=0
LOCAL_NETWORK=192.168.0.0/16
REALHOST=myhostname
DB_HOSTNAME=immich_postgres
DB_USERNAME=myuser
DB_PASSWORD=mypassword
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=${BASE_ORION}/photo/immich
TYPESENSE_API_KEY=myAPIKey
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
LOG_LEVEL=debug
```

### Reproduction steps

```bash
0.backup your android pictures to the future external library folder
1.spin up the stack, add a user and the external library, let it discover all pictures
2.start the android app, login, let it scan local pictures 
3.all pictures are show twice
```
