### DISCUSSION TITLE
[BUG] Upgraded to v1.84.0 Immich server and immich microservices containers restarting with QueryFailedError: there is no unique constraint matching given keys for referenced table "albums"

### DISCUSSION THREAD

**Discussion by vadimzharov** [immich-app/immich#4829] [Q&A] [answered]
### The bug

I have two identical immich environments, deployed in k8s cluster in two separate namespaces. Both are deployed using immich helm charts and use the same values file, example (some values are specific to ArgoCD which I'm using to deploy immich via helm):
```
            env:
              IMMICH_MACHINE_LEARNING_URL: "false"
            image:
              tag: '{{metadata.labels.immich-tag}}'
            immich:
              persistence:
                library:
                  existingClaim: immich-m-photos
            redis:
              enabled: true
              architecture: standalone
              master:
                persistence:
                  enabled: false
              auth:
                enabled: false
            machine-learning:
              enabled: false
            postgresql:
              enabled: false
              global:
                postgresql:
                  auth:
                    username: <pgsql_username>
                    password: <pgsql_password>
                    database: <pgsql_database>
            server:
              enabled: true
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent
            proxy:
              ingress:
                main:
                  enabled: false
```
Both instances is using PQSQL database (each instance is using it's own database) running in container `docker.io/bitnami/postgresql:15.4.0-debian-11-r0`.

The first immich instance was installed a while ago and seamlessly upgraded from v1.72.2 to v1.84.0 without any issues (this instance is serving around 4000 photos). Last upgrade was by changing tag from 1.82.1 to 1.84.0 and all containers are running and the instance is working (all containers are up, no errors).

But I cannot upgrade the second immich instance. It was initially installed as 1.74.0 and upgraded to 1.82.1 - again without any issues (this instance is service around 65000 photos). 
Recently I changed immich images tag from 1.82.1 to 1.84.0 - and both immich-microservices and immich-service containers are failing with the same error:
```
[Nest] 8  - 11/02/2023, 4:41:02 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: there is no unique constraint matching given keys for referenced table "albums"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddActivity1698693294632.up (/usr/src/app/dist/infra/migrations/1698693294632-AddActivity.js:13:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
```
I didn't touch the database at all (it is still running without any restarts) for both immich instances.c 

If I change tag to 1.83.0 - immich (all containers including immich-server and immich-microservices) started to work without any issues - means can connect to the database and I can access immich UI.

So the issue I have - immich-server and immich-microservices containers are failing with error:
```
[Nest] 8  - 11/02/2023, 4:46:40 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
QueryFailedError: there is no unique constraint matching given keys for referenced table "albums"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddActivity1698693294632.up (/usr/src/app/dist/infra/migrations/1698693294632-AddActivity.js:13:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
```
after I upgrade immich from 1.83.0 to 1.84.0, but can work without any issues/errors if I revert immich to use version 1.83.0

I guess it might be some issue with PSQL database - something changed in 1.84.0 and preventing immich to work with database properly.

### The OS that Immich Server is running on

K8S cluster with Ubuntu nodes.

### Version of Immich Server

v1.84.0

### Version of Immich Mobile App

1.84.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: immich-m
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8secrets/immich"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          immich-m: "installed"
          k8s-csi-nfs: "installed"
      values:
        revision: '{{metadata.annotations.branch-name}}'
        version: '{{metadata.labels.immich-tag}}'        
  - clusters:
      selector:
        matchLabels:
          immich-m: "passive"
      values:
        revision: '{{metadata.annotations.branch-name}}'
      template:
        metadata: 
          name: '{{name}}-immich-m-passive' 
        spec:
          sources:
            - repoURL: https://github.com/vadimzharov/k8s-rpi-cluster.git
              targetRevision: '{{values.revision}}'
              path: k8s-rpi-apps-ingress/immich-m-ingress
          destination:
            server: '{{server}}'
            namespace: immich-m
          project: k8s-rpi-apps              
  template:
    metadata:
      name: '{{name}}-immich-m'
    spec:
      project: k8s-rpi-apps
      sources:
      - helm:
          releaseName: immich
          values: |
            global:
              postgresql:
                auth:
                  username: <pgsql_username>
                  password: <pgsql_password>
                  database: <pgsql_database>
            primary:
              persistence:
                enabled: false
              extraVolumes:
                - name: pgsql-restored-mark
                  emptyDir: {}
              extraVolumeMounts:
                - name:  pgsql-restored-mark
                  mountPath: /tmp/pgsqlrestore/
              startupProbe:
                exec:
                  command:
                    - cat
                    - /tmp/pgsqlrestore/restored
                failureThreshold: 30
                periodSeconds: 20
                initialDelaySeconds: 10                  
              sidecars:
              - name: pgsql-backup-daemon
                image: quay.io/vadimzharov/podbackup:latest
                imagePullPolicy: Always
                command:
                  - podbackup
                args:
                  - backup-pgsql-daemon
                envFrom:
                - secretRef:
                    name: sync-s3-secret
                - configMapRef:
                    name: pgsql-b-r-settings
                - secretRef:
                    name: pgsql-creds
                volumeMounts:
                - name:  pgsql-restored-mark
                  mountPath: /tmp/pgsqlrestore/                
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - podbackup
                        - restore-pgsql
        repoURL: https://charts.bitnami.com/bitnami
        chart: postgresql
        targetRevision: 12.8.2
      - repoURL: https://github.com/vadimzharov/k8s-rpi-cluster.git
        targetRevision: '{{values.revision}}'
        path: k8s-apps-immich-m
      - repoURL: https://github.com/vadimzharov/k8s-rpi-cluster.git
        targetRevision: '{{values.revision}}'
        path: k8s-rpi-apps-ingress/immich-m-ingress
      - helm:
          releaseName: immich
          values: |
            env:
              IMMICH_MACHINE_LEARNING_URL: "false"
            image:
              tag: '{{metadata.labels.immich-tag}}'
            immich:
              persistence:
                library:
                  existingClaim: immich-m-photos
            redis:
              enabled: true
              architecture: standalone
              master:
                persistence:
                  enabled: false
              auth:
                enabled: false
            machine-learning:
              enabled: false
            postgresql:
              enabled: false
              global:
                postgresql:
                  auth:
                    username: <pgsql_username>
                    password: <pgsql_password>
                    database: <pgsql_database>
            server:
              enabled: true
              image:
                repository: ghcr.io/immich-app/immich-server
                pullPolicy: IfNotPresent
            proxy:
              ingress:
                main:
                  enabled: false
        repoURL: https://immich-app.github.io/immich-charts
        chart: immich
        targetRevision: 0.1.2
      destination:
        server: '{{server}}' 
        namespace: immich-m
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

### Your .env content

```Shell
DB_DATABASE_NAME : immich
DB_HOSTNAME : immich-postgresql
DB_PASSWORD : ######
DB_USERNAME : immich
IMMICH_MACHINE_LEARNING_URL : false
IMMICH_SERVER_URL : http://immich-server:3001
IMMICH_WEB_URL : http://immich-web:3000
REDIS_HOSTNAME : immich-redis-master
REVERSE_GEOCODING_DUMP_DIRECTORY : /geodata-cache
TYPESENSE_API_KEY : typesense
TYPESENSE_ENABLED : false
TYPESENSE_HOST : immich-typesense
```

### Reproduction steps

```bash
1. Have immich running using containers v1.83.0 - no issues
2. Change immich to use tag v1.84.0 - immich-server and immich-microservices are failing with error:
[Nest] 8  - 11/02/2023, 4:41:02 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
QueryFailedError: there is no unique constraint matching given keys for referenced table "albums"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddActivity1698693294632.up (/usr/src/app/dist/infra/migrations/1698693294632-AddActivity.js:13:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
3. Revert Immich containers to use v1.83.0 - containers are running without any error. No changes to database.
...
```
