### DISCUSSION TITLE
IOS application stops upload

### DISCUSSION THREAD

**Discussion by german-aksenov** [immich-app/immich#4838] [General]
### The bug

fresh installation of immich. I'm trying to upload images from mobile phone (iOS 16.6) to server. 
 
2269 images was transferred and progress is stoped (still 247 in queue)
in the mobile application log there is 

Ignoring duplicate assets on device:
{
  "id": "N/A",
  "remoteId": "N/A",
  "localId": "DA49F295-C7C7-4778-A546-9BCD06840EEF/L0/001",
  "checksum": "w1C5UxYBQV0FhqQ0Fzopbw5yp9A=",
  "ownerId": 7102608187667092359,
  "livePhotoVideoId": "N/A",
  "stackCount": "0",
  "stackParentId": "N/A",
  "fileCreatedAt": "2019-11-10 12:39:20.000",
  "fileModifiedAt": "2023-08-12 11:56:59.000",
  "updatedAt": "2023-08-12 11:56:59.000",
  "durationInSeconds": 0,
  "type": "AssetType.image",
  "fileName": "",
  "isFavorite": false,
  "isRemote: false,
  "storage": "AssetState.local",
  "width": 568,
  "height": 1152,
  "isArchived": false,
  "isTrashed": false,
}
{
  "id": "N/A",
  "remoteId": "N/A",
  "localId": "3549205F-9AE9-4F3B-92DF-F85A2F9866A4/L0/001",
  "checksum": "w1C5UxYBQV0FhqQ0Fzopbw5yp9A=",
  "ownerId": 7102608187667092359,
  "livePhotoVideoId": "N/A",
  "stackCount": "0",
  "stackParentId": "N/A",
  "fileCreatedAt": "2019-11-10 12:39:20.000",
  "fileModifiedAt": "2023-08-12 11:56:59.000",
  "updatedAt": "2023-08-12 11:56:59.000",
  "durationInSeconds": 0,
  "type": "AssetType.image",
  "fileName": "",
  "isFavorite": false,
  "isRemote: false,
  "storage": "AssetState.local",
  "width": 568,
  "height": 1152,
  "isArchived": false,
  "isTrashed": false,
}

looks like very old images unable to be uploaded. 

### The OS that Immich Server is running on

Docker compose + debian

### Version of Immich Server

1.84.0

### Version of Immich Mobile App

1.84.0 build.124

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.yml
       service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure:5

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/immich_lib

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=hidden
DB_PASSWORD=hidden

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

LOG_LEVEL=debug
PUBLIC_LOGIN_PAGE_MESSAGE="My Family Photos and Videos"
```

### Reproduction steps

```bash
1. fress install immich ios app and server
2 login via mobile app 
3 manually start syncing
```
