### DISCUSSION TITLE
redis volume left behind

### DISCUSSION THREAD

**Discussion by dsm1212** [immich-app/immich#5274] [Q&A]
Every time I restart immich I have a redis volume left behind. It's mapped to /data. I tried naming it and reusing it but it won't restart correctly when the prior contents are there. Is there any way to avoid these volumes I have to manually clean up?

thanks

**Comment by davidpan** [comment]
maybe change docker-compose.yml files:
```yml
redis:
  container_name: immich_redis
  image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
  volumes:
    - redis_data:/data	
  restart: always

volumes:
  redis_data:
```
