### DISCUSSION TITLE
[Question] How to add multiple hard drive/extend space

### DISCUSSION THREAD

**Discussion by mchiappinam** [immich-app/immich#5450] [General]
Hi all,

I'm trying to find a way to expand my storage, I have my first hard drive with over 90% and I have more space on another hd.
I didn't find any discussion about this, which surprised me, so I'm sorry if that already exists...

Is it possible to set multiple hd?

Thanks :D

**Comment by mchiappinam** [comment]
```
###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

LIBRARY_LOCATION=/mnt/user/Immich/
THUMBS_LOCATION=/mnt/apps/Immich-Cache/thumbs/
UPLOAD_LOCATION=/mnt/apps/Immich-Cache/upload/
PROFILE_LOCATION=/mnt/apps/Immich-Cache/profile/
VIDEO_LOCATION=/mnt/apps/Immich-Cache/encoded-video/
```


I have found this but I don't think this settings accept multiple locations...

**Comment by bo0tzz** [comment]
This isn't really something that goes in the application domain, it would usually be handled by your OS.

**Comment by zackpollard** [comment]
This is not something we should handle in the application as @bo0tzz mentioned. There are plenty of tools out there to combine drives into one bigger drive, and some of those can improve the resillience of your data. One example of this would be RAID. Im going to close this discussion

**Comment by metheoryt** [comment]
I resolved it for myself in Docker Compose setup under Windows 11 WSL, by sharding my library.
I have only one library, but that doesn't matter.
I have mutiple hard drives, that are connected through 2-in-1 hdd hub, and that's what I did:

```yaml
  immich-server:
    volumes:
      # Do not edit the next line...
      # 
      # I edited this line anyway, to support different physical disk mounts across library.
      # This default location is used to store everything until 2025
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      # separate mount for 2025 and 2026, TBC...
      - ${LOCATION_2025}:/usr/src/app/upload/library/admin/2025
      - ${LOCATION_2026}:/usr/src/app/upload/library/admin/2026
```

And specified partitions on different disks for each new LOCATION. 

```file .env
UPLOAD_LOCATION=D:\Immich
LOCATION_2025=E:\admin\2025
LOCATION_2026=F:\admin\2026
```

> This would require you to ensure your [storage template](https://docs.immich.app/administration/storage-template/) starts by splitting data by year (or whatever sharding schema works for you).

That scales up for me, quick and enough for now.
