### DISCUSSION TITLE
[ BUG ] Machine learning container issues

### DISCUSSION THREAD

**Discussion by modem7** [immich-app/immich#5454] [General]
Log:

```console
[Nest] 7  - 12/02/2023, 7:36:31 PM   ERROR [JobService] Unable to run job handler (recognizeFaces/recognize-faces): TypeError: fetch failed
[Nest] 7  - 12/02/2023, 7:36:31 PM   ERROR [JobService] TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at async MachineLearningRepository.post (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:16:21)
    at async PersonService.handleRecognizeFaces (/usr/src/app/dist/domain/person/person.service.js:183:23)
    at async /usr/src/app/dist/domain/job/job.service.js:108:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:387:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:574:24)
[Nest] 7  - 12/02/2023, 7:36:31 PM   ERROR [JobService] Object:
{
  "id": "813b831f-9b87-4df9-8b1a-ad2f290d3a8b",
  "source": "upload"
}           
```

```console
[12/02/23 19:33:41] INFO     Starting gunicorn 21.2.0                           
[12/02/23 19:33:41] INFO     Listening at: http://0.0.0.0:3003 (9)              
[12/02/23 19:33:41] INFO     Using worker: uvicorn.workers.UvicornWorker        
[12/02/23 19:33:41] INFO     Booting worker with pid: 29                        
[12/02/23 19:33:41] INFO     Booting worker with pid: 30                        
[12/02/23 19:33:41] INFO     Booting worker with pid: 31                        
[12/02/23 19:33:41] INFO     Booting worker with pid: 32                        
[12/02/23 19:33:53] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[12/02/23 19:33:53] INFO     Initialized request thread pool with 20 threads.   
[12/02/23 19:33:53] INFO     Downloading facial recognition model               
                             'buffalo_l'.This may take a while.                 
[12/02/23 19:33:53] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[12/02/23 19:33:53] INFO     Initialized request thread pool with 20 threads.   
[12/02/23 19:33:54] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[12/02/23 19:33:54] INFO     Initialized request thread pool with 20 threads.   
[12/02/23 19:33:54] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[12/02/23 19:33:54] INFO     Initialized request thread pool with 20 threads.   

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Downloading .gitattributes:   0%|          | 0.00/1.52k [00:00<?, ?B/s]
Downloading .gitattributes: 100%|██████████| 1.52k/1.52k [00:00<00:00, 5.26MB/s]


Downloading README.md:   0%|          | 0.00/582 [00:00<?, ?B/s]
Downloading README.md: 100%|██████████| 582/582 [00:00<00:00, 2.63MB/s]

Fetching 4 files:  25%|██▌       | 1/4 [00:00<00:01,  1.80it/s]

Downloading model.onnx:   0%|          | 0.00/16.9M [00:00<?, ?B/s]


Downloading model.onnx:   0%|          | 0.00/174M [00:00<?, ?B/s]

Downloading model.onnx:  62%|██████▏   | 10.5M/16.9M [00:00<00:00, 31.4MB/s]


Downloading model.onnx:   6%|▌         | 10.5M/174M [00:00<00:05, 31.9MB/s]

Downloading model.onnx: 100%|██████████| 16.9M/16.9M [00:00<00:00, 40.0MB/s]
Downloading model.onnx: 100%|██████████| 16.9M/16.9M [00:00<00:00, 37.5MB/s]



Downloading model.onnx:  12%|█▏        | 21.0M/174M [00:00<00:03, 47.9MB/s]
Fetching 4 files:  75%|███████▌  | 3/4 [00:01<00:00,  2.43it/s]


Downloading model.onnx:  18%|█▊        | 31.5M/174M [00:00<00:02, 58.2MB/s]


Downloading model.onnx:  24%|██▍       | 41.9M/174M [00:00<00:01, 67.2MB/s]


Downloading model.onnx:  30%|███       | 52.4M/174M [00:00<00:01, 75.5MB/s]


Downloading model.onnx:  36%|███▌      | 62.9M/174M [00:00<00:01, 81.6MB/s]


Downloading model.onnx:  48%|████▊     | 83.9M/174M [00:01<00:00, 93.3MB/s]


Downloading model.onnx:  60%|██████    | 105M/174M [00:01<00:00, 99.3MB/s] 


Downloading model.onnx:  72%|███████▏  | 126M/174M [00:01<00:00, 102MB/s] 


Downloading model.onnx:  84%|████████▍ | 147M/174M [00:01<00:00, 104MB/s]


Downloading model.onnx:  96%|█████████▌| 168M/174M [00:01<00:00, 104MB/s]
Downloading model.onnx: 100%|██████████| 174M/174M [00:01<00:00, 87.7MB/s]

Fetching 4 files: 100%|██████████| 4/4 [00:03<00:00,  1.13it/s]
Fetching 4 files: 100%|██████████| 4/4 [00:03<00:00,  1.31it/s]
[12/02/23 19:33:57] INFO     Loading facial recognition model 'buffalo_l'       
[12/02/23 19:33:58] INFO     Downloading clip model 'ViT-B-32__openai'.This may 
                             take a while.                                      

Fetching 11 files:   0%|          | 0/11 [00:00<?, ?it/s]

Downloading README.md:   0%|          | 0.00/422 [00:00<?, ?B/s]
Downloading README.md: 100%|██████████| 422/422 [00:00<00:00, 2.22MB/s]


Downloading .gitattributes:   0%|          | 0.00/1.52k [00:00<?, ?B/s]
Downloading .gitattributes: 100%|██████████| 1.52k/1.52k [00:00<00:00, 5.95MB/s]


Downloading config.json:   0%|          | 0.00/196 [00:00<?, ?B/s]
Downloading config.json: 100%|██████████| 196/196 [00:00<00:00, 942kB/s]


Downloading textual/merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]


Downloading (…)okenizer_config.json:   0%|          | 0.00/704 [00:00<?, ?B/s]
Downloading (…)okenizer_config.json: 100%|██████████| 704/704 [00:00<00:00, 2.81MB/s]



Downloading (…)cial_tokens_map.json:   0%|          | 0.00/472 [00:00<?, ?B/s]
Downloading (…)cial_tokens_map.json: 100%|██████████| 472/472 [00:00<00:00, 1.65MB/s]



Downloading textual/tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]
Downloading textual/merges.txt: 100%|██████████| 525k/525k [00:00<00:00, 6.33MB/s]

Fetching 11 files:   9%|▉         | 1/11 [00:00<00:07,  1.27it/s]

Downloading model.onnx:   0%|          | 0.00/254M [00:00<?, ?B/s]


Downloading textual/tokenizer.json: 100%|██████████| 2.22M/2.22M [00:00<00:00, 16.2MB/s]
Downloading textual/tokenizer.json: 100%|██████████| 2.22M/2.22M [00:00<00:00, 16.0MB/s]


Downloading model.onnx:   4%|▍         | 10.5M/254M [00:00<00:04, 49.4MB/s]

Downloading model.onnx:   8%|▊         | 21.0M/254M [00:00<00:03, 71.2MB/s]
Fetching 11 files:  36%|███▋      | 4/11 [00:01<00:01,  3.97it/s]


Downloading textual/vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

Downloading model.onnx:  17%|█▋        | 41.9M/254M [00:00<00:02, 92.1MB/s]


Downloading textual/vocab.json: 100%|██████████| 862k/862k [00:00<00:00, 5.89MB/s]
Downloading textual/vocab.json: 100%|██████████| 862k/862k [00:00<00:00, 5.86MB/s]



Downloading (…)/preprocess_cfg.json:   0%|          | 0.00/197 [00:00<?, ?B/s]
Downloading (…)/preprocess_cfg.json: 100%|██████████| 197/197 [00:00<00:00, 535kB/s]


Downloading model.onnx:  25%|██▍       | 62.9M/254M [00:00<00:01, 102MB/s] 


Downloading model.onnx:   0%|          | 0.00/351M [00:00<?, ?B/s]

Downloading model.onnx:  33%|███▎      | 83.9M/254M [00:00<00:01, 101MB/s]

Downloading model.onnx:  37%|███▋      | 94.4M/254M [00:01<00:01, 96.7MB/s]


Downloading model.onnx:   3%|▎         | 10.5M/351M [00:00<00:12, 26.7MB/s]

Downloading model.onnx:  41%|████▏     | 105M/254M [00:01<00:01, 89.1MB/s] 

Downloading model.onnx:  45%|████▌     | 115M/254M [00:01<00:01, 85.5MB/s]


Downloading model.onnx:   6%|▌         | 21.0M/351M [00:00<00:09, 34.6MB/s]

Downloading model.onnx:  50%|████▉     | 126M/254M [00:01<00:01, 79.5MB/s]


Downloading model.onnx:   9%|▉         | 31.5M/351M [00:00<00:07, 40.0MB/s]

Downloading model.onnx:  54%|█████▎    | 136M/254M [00:01<00:01, 77.7MB/s]

Downloading model.onnx:  58%|█████▊    | 147M/254M [00:01<00:01, 74.2MB/s]


Downloading model.onnx:  12%|█▏        | 41.9M/351M [00:01<00:07, 43.2MB/s]

Downloading model.onnx:  62%|██████▏   | 157M/254M [00:01<00:01, 71.5MB/s]


Downloading model.onnx:  15%|█▍        | 52.4M/351M [00:01<00:06, 46.0MB/s]

Downloading model.onnx:  66%|██████▌   | 168M/254M [00:02<00:01, 69.7MB/s]


Downloading model.onnx:  18%|█▊        | 62.9M/351M [00:01<00:06, 47.9MB/s]

Downloading model.onnx:  70%|███████   | 178M/254M [00:02<00:01, 67.1MB/s]


Downloading model.onnx:  21%|██        | 73.4M/351M [00:01<00:05, 50.6MB/s]

Downloading model.onnx:  74%|███████▍  | 189M/254M [00:02<00:01, 64.9MB/s]


Downloading model.onnx:  24%|██▍       | 83.9M/351M [00:01<00:05, 52.4MB/s]

Downloading model.onnx:  78%|███████▊  | 199M/254M [00:02<00:00, 63.8MB/s]


Downloading model.onnx:  27%|██▋       | 94.4M/351M [00:02<00:04, 54.0MB/s]

Downloading model.onnx:  83%|████████▎ | 210M/254M [00:02<00:00, 61.9MB/s]


Downloading model.onnx:  30%|██▉       | 105M/351M [00:02<00:04, 55.7MB/s] 

Downloading model.onnx:  87%|████████▋ | 220M/254M [00:02<00:00, 60.3MB/s]


Downloading model.onnx:  33%|███▎      | 115M/351M [00:02<00:04, 57.3MB/s]

Downloading model.onnx:  91%|█████████ | 231M/254M [00:03<00:00, 58.5MB/s]


Downloading model.onnx:  36%|███▌      | 126M/351M [00:02<00:03, 58.7MB/s]

Downloading model.onnx:  95%|█████████▌| 241M/254M [00:03<00:00, 57.2MB/s]


Downloading model.onnx:  39%|███▉      | 136M/351M [00:02<00:03, 60.3MB/s]

Downloading model.onnx:  99%|█████████▉| 252M/254M [00:03<00:00, 56.7MB/s]


Downloading model.onnx:  42%|████▏     | 147M/351M [00:02<00:03, 59.9MB/s]
Downloading model.onnx: 100%|██████████| 254M/254M [00:03<00:00, 71.1MB/s]



Downloading model.onnx:  45%|████▍     | 157M/351M [00:03<00:03, 62.9MB/s]


Downloading model.onnx:  48%|████▊     | 168M/351M [00:03<00:02, 67.2MB/s]
Fetching 11 files:  45%|████▌     | 5/11 [00:04<00:06,  1.16s/it]


Downloading model.onnx:  51%|█████     | 178M/351M [00:03<00:02, 73.4MB/s]


Downloading model.onnx:  57%|█████▋    | 199M/351M [00:03<00:01, 86.9MB/s]


Downloading model.onnx:  60%|█████▉    | 210M/351M [00:03<00:01, 90.2MB/s]


Downloading model.onnx:  66%|██████▌   | 231M/351M [00:03<00:01, 97.6MB/s]


Downloading model.onnx:  72%|███████▏  | 252M/351M [00:03<00:00, 102MB/s] 


Downloading model.onnx:  78%|███████▊  | 273M/351M [00:04<00:00, 104MB/s]


Downloading model.onnx:  84%|████████▎ | 294M/351M [00:04<00:00, 105MB/s]


Downloading model.onnx:  87%|████████▋ | 304M/351M [00:04<00:00, 105MB/s]


Downloading model.onnx:  92%|█████████▏| 325M/351M [00:04<00:00, 106MB/s]


Downloading model.onnx:  98%|█████████▊| 346M/351M [00:04<00:00, 108MB/s]
Downloading model.onnx: 100%|██████████| 351M/351M [00:04<00:00, 72.3MB/s]

Fetching 11 files:  91%|█████████ | 10/11 [00:06<00:00,  1.53it/s]
Fetching 11 files: 100%|██████████| 11/11 [00:06<00:00,  1.65it/s]
[12/02/23 19:34:05] INFO     Loading clip model 'ViT-B-32__openai'              
[12/02/23 19:34:06] INFO     Downloading image classification model             
                             'microsoft/resnet-50'.This may take a while.       

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

Downloading pytorch_model.bin:   0%|          | 0.00/103M [00:00<?, ?B/s]


Downloading config.json:   0%|          | 0.00/69.6k [00:00<?, ?B/s]



Downloading (…)rocessor_config.json:   0%|          | 0.00/266 [00:00<?, ?B/s]
Downloading (…)rocessor_config.json: 100%|██████████| 266/266 [00:00<00:00, 936kB/s]

Downloading config.json: 100%|██████████| 69.6k/69.6k [00:00<00:00, 950kB/s]

Fetching 3 files:  33%|███▎      | 1/3 [00:00<00:01,  1.38it/s]

Downloading pytorch_model.bin:  10%|█         | 10.5M/103M [00:00<00:02, 41.9MB/s]

Downloading pytorch_model.bin:  20%|██        | 21.0M/103M [00:00<00:01, 63.9MB/s]

Downloading pytorch_model.bin:  41%|████      | 41.9M/103M [00:00<00:00, 85.5MB/s]

Downloading pytorch_model.bin:  51%|█████     | 52.4M/103M [00:00<00:00, 88.7MB/s]

Downloading pytorch_model.bin:  61%|██████▏   | 62.9M/103M [00:00<00:00, 89.4MB/s]

Downloading pytorch_model.bin:  82%|████████▏ | 83.9M/103M [00:00<00:00, 93.2MB/s]

Downloading pytorch_model.bin:  92%|█████████▏| 94.4M/103M [00:01<00:00, 89.8MB/s]
Downloading pytorch_model.bin: 100%|██████████| 103M/103M [00:01<00:00, 84.8MB/s] 

Fetching 3 files: 100%|██████████| 3/3 [00:02<00:00,  1.14it/s]
Fetching 3 files: 100%|██████████| 3/3 [00:02<00:00,  1.16it/s]
[12/02/23 19:34:10] INFO     Loading image classification model                 
                             'microsoft/resnet-50'                              
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
[12/02/23 19:34:10] INFO     ONNX model not found in cache directory for        
                             'microsoft/resnet-50'.Exporting optimized model for
                             future use.                                        

Downloading config.json:   0%|          | 0.00/69.6k [00:00<?, ?B/s]
Downloading config.json: 100%|██████████| 69.6k/69.6k [00:00<00:00, 3.17MB/s]
[12/02/23 19:34:12] INFO     Loading clip model 'ViT-B-32__openai'              
Framework not specified. Using pt to export to ONNX.
[12/02/23 19:34:13] INFO     Loading facial recognition model 'buffalo_l'       

Downloading (…)rocessor_config.json:   0%|          | 0.00/266 [00:00<?, ?B/s]
Downloading (…)rocessor_config.json: 100%|██████████| 266/266 [00:00<00:00, 1.21MB/s]
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.11/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
  warnings.warn(
Using the export variant default. Available variants are:
	- default: The default ONNX variant.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Using framework PyTorch: 2.1.0+cpu
/opt/venv/lib/python3.11/site-packages/transformers/models/resnet/modeling_resnet.py:95: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_channels != self.num_channels:
[12/02/23 19:34:23] INFO     Loading image classification model                 
                             'microsoft/resnet-50'                              
[12/02/23 19:34:23] INFO     Loading clip model 'ViT-B-32__openai'              
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
[12/02/23 19:34:23] INFO     ONNX model not found in cache directory for        
                             'microsoft/resnet-50'.Exporting optimized model for
                             future use.                                        
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Framework not specified. Using pt to export to ONNX.
2023-12-02 19:34:24.471587943 [W:onnxruntime:, inference_session.cc:1732 Initialize] Serializing optimized model with Graph Optimization level greater than ORT_ENABLE_EXTENDED and the NchwcTransformer enabled. The generated model may contain hardware specific optimizations, and should only be used in the same environment the model was optimized in.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.11/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
  warnings.warn(
Using the export variant default. Available variants are:
	- default: The default ONNX variant.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Using framework PyTorch: 2.1.0+cpu
/opt/venv/lib/python3.11/site-packages/transformers/models/resnet/modeling_resnet.py:95: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if num_channels != self.num_channels:
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
2023-12-02 19:34:35.381435294 [W:onnxruntime:, inference_session.cc:1732 Initialize] Serializing optimized model with Graph Optimization level greater than ORT_ENABLE_EXTENDED and the NchwcTransformer enabled. The generated model may contain hardware specific optimizations, and should only be used in the same environment the model was optimized in.
[12/02/23 19:34:36] INFO     Loading facial recognition model 'buffalo_l'       
[12/02/23 19:34:38] INFO     Loading image classification model                 
                             'microsoft/resnet-50'                              
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.11/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
  warnings.warn(
[12/02/23 19:35:14] INFO     Loading facial recognition model 'buffalo_l'       
[12/02/23 19:35:17] INFO     Loading clip model 'ViT-B-32__openai'              
[12/02/23 19:35:21] INFO     Loading image classification model                 
                             'microsoft/resnet-50'                              
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/opt/venv/lib/python3.11/site-packages/transformers/models/convnext/feature_extraction_convnext.py:28: FutureWarning: The class ConvNextFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ConvNextImageProcessor instead.
  warnings.warn(
```

Compose file:
```yaml
  immich-server:
    container_name: Immich_Server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/docker_data/immich/uploads:/usr/src/app/upload
      - /mnt/oldhd/Pictures:/photos
    environment:
      - TZ=$TZ
      - LOG_LEVEL=log
      - IMMICH_MEDIA_LOCATION=./upload
      - DB_HOSTNAME=immichdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=$IMMICH_DB_PWD
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immichredis
      - TYPESENSE_HOST=immichtypesense
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
    networks:
      pihole:
        ipv4_address: '172.22.0.147'
      isolated:
      isonet:
    ports:
      - 2283:3001
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-rtr.entrypoints=https"
      - "traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)"
      - "traefik.http.routers.immich-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.immich-rtr.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.immich-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.immich-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=3001"
      ## Homepage
      - homepage.name=Immich
      - homepage.group=Other
      - homepage.icon=immich
      - homepage.href=https://immich.$DOMAINNAME
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      - immichredis
      - immichdb
      - immichtypesense
    restart: always

  immich-microservices:
    container_name: Immich_Microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - /mnt/docker_data/immich/uploads:/usr/src/app/upload
      - /mnt/oldhd/Pictures:/photos
    environment:
      - TZ=$TZ
      - LOG_LEVEL=log
      - IMMICH_MEDIA_LOCATION=./upload
      - REVERSE_GEOCODING_DUMP_DIRECTORY=./.reverse-geocoding-dump/
      - DB_HOSTNAME=immichdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=$IMMICH_DB_PWD
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immichredis
      - TYPESENSE_HOST=immichtypesense
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
      - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
    networks:
      pihole:
        ipv4_address: '172.22.0.148'
      isolated:
      isonet:
    depends_on:
      - immichredis
      - immichdb
      - immichtypesense
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immich-machine-learning:
    container_name: Immich_Machine_Learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    networks:
      isonet:
    environment:
      - MACHINE_LEARNING_WORKERS=4
      - MACHINE_LEARNING_CACHE_FOLDER=/cache
    volumes:
      - /mnt/docker_data/immich/cache:/cache
      # - $USERDIR/Immich/cache:/cache
      # - model-cache:/cache
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichtypesense:
    container_name: Immich_Typesense
    image: typesense/typesense:0.24.1
    environment:
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    networks:
      isonet:
    volumes:
      - /mnt/docker_data/immich/typesense:/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichredis:
    container_name: Immich_Redis
    image: redis:6.2-alpine
    networks:
      isolated:
    volumes:
      - $USERDIR/Immich/redis:/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichdb:
    container_name: ImmichDB
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$IMMICH_DB_PWD
      - POSTGRES_DB=immich
    volumes:
      - $USERDIR/Immich/DB:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      isolated:
    restart: always
```

Unsure where I'm going wrong in this case - cheers!
