### DISCUSSION TITLE
[Feature] Schedule time for jobs

### DISCUSSION THREAD

**Discussion by baflo** [immich-app/immich#5498] [Feature Request]
### The feature

Currently, I must disable video transcoding and people recognition, because it requires too much resources by day. My system becomes too laggy for normal usage, when immich

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by bo0tzz** [comment]
You can decrease the concurrency of the jobs in the admin panels, and you could set up the microservices container on a cron timer so it's only started during the night. Would that do the trick for you?

**Reply by baflo** [reply]
I already reduced the concurrency to 1, but my server still runs on 100% during transcoding. 

The idea with the cron job sounds feasible, however in my current setup it might be complicated. I'm hosting Immich on Home Assistant using an addon that's based on https://github.com/imagegenius/docker-immich which is a monolithic container for immich with all services inside.

What I'm trying to say is, that there may be many different ways to run immich and they may require different solutions for the cron job. On the other hand it seems to be easier to create a scheduler in Immich itself.

However, if this cannot be done, I must consider to ask for this feature in the imagegenius container or implement it myself.

**Reply by baflo** [reply]
I just saw there's an API endpoint for jobs. I'll try and see, if I can switch the relevant jobs externally.

**Reply by baflo** [reply]
The API works well for this:
![image](https://github.com/immich-app/immich/assets/834350/60faae3a-ac80-4c69-986a-b2d7d0ad9454)

**Reply by raihatneloy** [reply]
Hi @baflo can you please explain a bit what you actually did for this? I am on the same boat. Running immich on rpi4. So, I am okay with thumbnail and other jobs to run. But I would like to wait for the face detection and facial recognition to wait for night time when the usage is low. Sometimes happened, I shared some photos with friends through link and then they couldn't access because jobs are running on the background.

**Reply by baflo** [reply]
Hey @raihatneloy,
immich's API has two endpoints to get current job states and to set job config:
* https://immich.app/docs/api/get-all-jobs-status
* https://immich.app/docs/api/send-job-command

In Home Assistant, I created REST sensors and command, which you can review in the file below. The commands can then be used in HA scripts and automations.

<details>
<summary>immich.yaml</summary>

```yaml
rest:
  - resource: http://db21ed7f-immich:8080/api/jobs/
    scan_interval: 600
    headers:
      Accept: "application/json"
      X-API-KEY: !secret immich_admin_api_key
    sensor:
      - name: Immich Thumbnails Generation delayed
        unique_id: immich_thumbnail_generation_delayed
        value_template: "{{ value_json.thumbnailGeneration.jobCounts.delayed }}"
        state_class: total
      - name: Immich Thumbnails Generation waiting
        unique_id: immich_thumbnail_generation_waiting
        value_template: "{{ value_json.thumbnailGeneration.jobCounts.waiting }}"
        state_class: total
      - name: Immich Thumbnails Generation paused
        unique_id: immich_thumbnail_generation_paused
        value_template: "{{ value_json.thumbnailGeneration.jobCounts.paused }}"
        state_class: total

      - name: Immich Video Conversion delayed
        unique_id: immich_video_conversion_delayed
        value_template: "{{ value_json.videoConversion.jobCounts.delayed }}"
        state_class: total
      - name: Immich Video Conversion waiting
        unique_id: immich_video_conversion_waiting
        value_template: "{{ value_json.videoConversion.jobCounts.waiting }}"
        state_class: total
      - name: Immich Video Conversion paused
        unique_id: immich_video_conversion_paused
        value_template: "{{ value_json.videoConversion.jobCounts.paused }}"
        state_class: total

      - name: Immich Object Tagging delayed
        unique_id: immich_object_tagging_delayed
        value_template: "{{ value_json.objectTagging.jobCounts.delayed }}"
        state_class: total
      - name: Immich Object Tagging waiting
        unique_id: immich_object_tagging_waiting
        value_template: "{{ value_json.objectTagging.jobCounts.waiting }}"
        state_class: total
      - name: Immich Object Tagging paused
        unique_id: immich_object_tagging_paused
        value_template: "{{ value_json.objectTagging.jobCounts.paused }}"
        state_class: total

      - name: Immich Recognize Faces delayed
        unique_id: immich_recognize_faces_delayed
        value_template: "{{ value_json.recognizeFaces.jobCounts.delayed }}"
        state_class: total
      - name: Immich Recognize Faces waiting
        unique_id: immich_recognize_faces_waiting
        value_template: "{{ value_json.recognizeFaces.jobCounts.waiting }}"
        state_class: total
      - name: Immich Recognize Faces paused
        unique_id: immich_recognize_faces_paused
        value_template: "{{ value_json.recognizeFaces.jobCounts.paused }}"
        state_class: total

      - name: Immich Clip Encoding delayed
        unique_id: immich_clip_encoding_delayed
        value_template: "{{ value_json.clipEncoding.jobCounts.delayed }}"
        state_class: total
      - name: Immich Clip Encoding waiting
        unique_id: immich_clip_encoding_waiting
        value_template: "{{ value_json.clipEncoding.jobCounts.waiting }}"
        state_class: total
      - name: Immich Clip Encoding paused
        unique_id: immich_clip_encoding_paused
        value_template: "{{ value_json.clipEncoding.jobCounts.paused }}"
        state_class: total

rest_command:
  immich_turn_off_thumbnail_generation:
    url: http://db21ed7f-immich:8080/api/jobs/thumbnailGeneration
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{ "command": "pause" }'
  immich_turn_on_thumbnail_generation:
    url: http://db21ed7f-immich:8080/api/jobs/thumbnailGeneration
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{"command": "resume"}'

  immich_turn_off_video_conversion:
    url: http://db21ed7f-immich:8080/api/jobs/videoConversion
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{ "command": "pause" }'
  immich_turn_on_video_conversion:
    url: http://db21ed7f-immich:8080/api/jobs/videoConversion
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{"command": "resume"}'

  immich_turn_off_clip_encoding:
    url: http://db21ed7f-immich:8080/api/jobs/clipEncoding
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{ "command": "pause" }'
  immich_turn_on_clip_encoding:
    url: http://db21ed7f-immich:8080/api/jobs/clipEncoding
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{"command": "resume"}'

  immich_turn_off_object_tagging:
    url: http://db21ed7f-immich:8080/api/jobs/objectTagging
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{ "command": "pause" }'
  immich_turn_on_object_tagging:
    url: http://db21ed7f-immich:8080/api/jobs/objectTagging
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{"command": "resume"}'

  immich_turn_off_recognize_faces:
    url: http://db21ed7f-immich:8080/api/jobs/recognizeFaces
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{ "command": "pause" }'
  immich_turn_on_recognize_faces:
    url: http://db21ed7f-immich:8080/api/jobs/recognizeFaces
    method: PUT
    content_type: "application/json; charset=utf-8"
    headers:
      X-API-KEY: !secret immich_admin_api_key
    payload: '{"command": "resume"}'
```
</details>

**Reply by baflo** [reply]
After I read your comment again, I wonder if this is something you must have automated or just need once in a while. Immich also has its own UI for disabling the jobs, which you could use in the latter case:
![image](https://github.com/immich-app/immich/assets/834350/64e26963-309c-439b-bb51-12dfd1279b67)

**Reply by raihatneloy** [reply]
Thanks a million @baflo, this was something I was trying to get. As I already have homeassistant up and running, your config will help me a lot! Will surely gonna try it.

**Comment by aisbergde** [comment]
How can I check, in the container logs, if the cron job was really running?

I enabled it, the cron expression is
0 */1 * * *
but it looks like libraries are not scanned, new assets are not added.

**Comment by aisbergde** [comment]
I manually triggerd the scan new, and I got these entries in [immich_microservices] log

```
[Nest] 7  - 01/06/2024, 11:36:08 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset b3dce9f3-92a3-480e-a49e-d7c2b0ccfa2c
[Nest] 7  - 01/06/2024, 11:36:08 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset 8d60769a-b8bc-40cc-b7df-5f1a1854e7bd
[Nest] 7  - 01/06/2024, 11:36:08 PM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset b3dce9f3-92a3-480e-a49e-d7c2b0ccfa2c
[Nest] 7  - 01/06/2024, 11:36:09 PM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 8d60769a-b8bc-40cc-b7df-5f1a1854e7bd
```

that means, the cron job to rescan libraries doesn't run or it is running, but not doing, what it should do.
How can I see the  logs of the cron job? And how could I make it run?

**Comment by Shurov** [comment]
I'm backing this feature as well, but for another use-case:
For me centrally distributed electricity is 2x-3x cheaper at night than day/primetime hours, so I'd like to have some scheduler UI to be able to plan jobs for the night run (and not immediately). I appreciate that standard periodic routine tasks as library re-scan etc are done at night anyway, but e.g. I changed Storage Template and need to manually trigger a corresponding job for it to move historical files... So I'm waiting till night to manually trigger it, and cannot pre-schedule this.

Alternatively, people who have own solar panels might want to run energy-intensive tasks during the day (even the periodic ones). 

Also detailed scheduler (hours + different week days) can add flexibility e.g. do nothing on Friday/Saturday nights.
For instance, Tdarr has such scheduler - [link](https://home.tdarr.io) (the last screenshot on the very bottom)

**Reply by DmitrySandalov** [reply]
```
#!/usr/bin/env bash

key=<your-api-key>
immich_host=<your-immich-host>

sendJobCommand() {
  curl -L -X PUT "$immich_host/api/jobs/$1" \
    -H 'Content-Type: application/json' \
    -H 'Accept: application/json' \
    -H 'x-api-key: '$key \
    -d '{
      "command": "'$2'",
      "force": false
    }'
}

sendJobCommand faceDetection pause
sendJobCommand facialRecognition resume
```
You might want to put it to systemd, cron, or run it otherwise.

https://immich.app/docs/api/send-job-command

**Comment by Gitonthegrid** [comment]
I have a similar problem.

I'm running Immich on a Synology DS918+. I started an experiment with 200,000 pictures, but my system can't handle it well. I had to stop all the "jobs" and start them manually one at a time. First, I scanned the library, and when that finished, I generated the thumbnails, etc. This way, my system can manage it.

If I reduce the job concurrency, it performs better, but it still takes a long time. I've been working on it for four days now, and the thumbnails are almost done. After that, I still need to extract metadata, perform smart searches, do face recognition, and then face detection.

In my real scenario, I have more pictures, so I think it will take weeks to complete all the tasks. Are there ways to improve this? It's really slow.
Compared to Synology Photos, it was much faster at indexing, generating thumbnails, and doing face recognition.

I really do love the app, but it is so slow with indexing everything. I really hate it, if (for some reason) I have to do all indexing again, with this amount of pictures.

**Reply by titro** [reply]
You could also give the ML Container (which is the container with the hardest jobs) less CPU Time. If you are using Docker with compose you can use:

```
   deploy:
    resources:
      limits:
        cpus: '0.3'

```
