### DISCUSSION TITLE
what's the best way to start over, from scratch, factory reset my db and images.

### DISCUSSION THREAD

**Discussion by steve-builds** [immich-app/immich#5851] [General]
After playing around, my images are all messed up, i have 10x more broken files than usable files.   I want to nuke it and start over. I thought I could just delete the database, but i can't find it.  I'm running docker compose, i checked inside /var/lib but there is no folder for postgresql.   i'm new to docker,  i'm not sure how to find and delete the database.   I'll keep looking around. 

I'm thinking about setting up a dedicated db so i can have better visibility and control over the db directly, and to back it up easily by connecting directly with pgAdmin. 

here is my docker-compose file for the database: 

running ver: 1.91.3 

```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/immich-app/library-ext-mnt/:/import:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    environment:
      - TZ=America/New_York

 immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/administrator/immich-app/library-ext-mnt/:/import:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    #restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```
