### DISCUSSION TITLE
Immich and Docker Swarm

### DISCUSSION THREAD

**Discussion by valentin-voica** [immich-app/immich#5857] [Q&A]
Hello,

Can I deploy Immich using Docker Swarm? I have tried to adjust the configuration file to match my environment, but I get the error below straight after deploying it.

```
user@felix:~$ docker stack deploy immich --compose-file /mnt/hdd1/docker/config/immich-app/immich-app.yml 
1 error(s) decoding:

* error decoding 'Volumes[0]': invalid spec: :/usr/src/app/upload: empty section between colons
```

Here is the configuration file:

```
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/hdd1/docker/runtime/immich-app/model-cache:/cache
    env_file:
      - .env

  redis:
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/hdd1/docker/data/immich-app/pgdata:/var/lib/postgresql/data
```

and the `.env` file:

```

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/hdd1/datastore/pictures/uploads

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=Blurt-Dullness6-Depth

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

The directory structure:

```
user@felix:~$ ls -l /mnt/hdd1/datastore/pictures/
total 0
drwxr-xr-x 1 user user 0 Dec 19 06:59 photoalbum
drwxr-xr-x 1 user user 0 Dec 19 06:59 uploads
```

I would like to thank all the devs for the hard work with this app. I tested it for a short-while on a TrueNAS SCALE machine and I liked it a lot.
