### DISCUSSION TITLE
[BUG] <I cannot get my docker container running in development>

### DISCUSSION THREAD

**Discussion by hellodivya** [immich-app/immich#5922] [Q&A]
### The bug

I tried to deploy the app by pulling the latest image and that worked fine but I tried to do `make dev` and everything was up and running except immich_web container. It might be that I have less experience or sth but the deployment processes are mostly seamless but I am getting this issue:
![image](https://github.com/immich-app/immich/assets/144518951/939f7087-7e5e-4b1c-816c-6b4e72303181)

### The OS that Immich Server is running on

Docker on arch

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# See:
# - https://immich.app/docs/developer/setup
# - https://immich.app/docs/developer/troubleshooting

version: "3.8"

name: immich-dev

x-server-build: &server-common
  image: immich-server-dev:latest
  build:
    context: ../
    dockerfile: server/Dockerfile
    target: dev
  volumes:
    - ../server:/usr/src/app
    - ${UPLOAD_LOCATION}/photos:/usr/src/app/upload
    - /usr/src/app/node_modules
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - .env
  environment:
    - NODE_ENV=development
  ulimits:
    nofile:
      soft: 1048576
      hard: 1048576

services:
  immich-server:
    container_name: immich_server
    command: [ "/usr/src/app/bin/immich-dev", "immich" ]
    <<: *server-common
    ports:
      - 3001:3001
      - 9230:9230
    depends_on:
      - redis
      - database

  immich-microservices:
    container_name: immich_microservices
    command: [ "/usr/src/app/bin/immich-dev", "microservices" ]
    <<: *server-common
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    ports:
      - 9231:9230
    depends_on:
      - database
      - immich-server

  immich-web:
    container_name: immich_web
    image: immich-web-dev:1.9.0
    build:
      context: ../web
      dockerfile: Dockerfile
    command: "node ./node_modules/.bin/vite dev --host 0.0.0.0 --port 3000"
    env_file:
      - .env
    ports:
      - 2283:3000
      - 24678:24678
    volumes:
      - ../web:/usr/src/app
      - /usr/src/app/node_modules
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    restart: unless-stopped
    depends_on:
      - immich-server

  immich-machine-learning:
    container_name: immich_machine_learning
    image: immich-machine-learning-dev:latest
    build:
      context: ../machine-learning
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ../machine-learning:/usr/src/app
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - database
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${UPLOAD_LOCATION}/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Clone the repository
2. Run `make dev`
...
```
