### DISCUSSION TITLE
[Feature] Path per user

### DISCUSSION THREAD

**Discussion by MrSpoocy** [immich-app/immich#5984] [Feature Request]
### The feature

I am currently moving to Immich with my whole family and my sister has a small child. As a result, she already takes over 40,000 photos and videos. That quickly takes up more than 400GB. When importing, I ran into the problem that my server SSD doesn't have enough space. So I bought a second one. But now you can only put external libraries in another directory and even then, thumbnails and encoded videos are written to the main directory. I think it would be quite useful if we can specify a path per user so that the directory structure changes as follows:

current:
 - library
    - encoded-video
      - USER1
      - USER2
    - library
      - USER1
      - USER2
    - thumbs
      - USER1
      - USER2
    - upload
      - USER1
      - USER2

after:
 - library
   - USER1
     - encoded-video
     - library
     - thumbs
     - upload
   - USER2
     - encoded-video
     - library
     - thumbs
     - upload

This makes it easy to mount other paths or symlinks. A migration should then not be so difficult. I could also help with the code.  But first I wanted to know what you think of the idea.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by aisbergde** [comment]
I think this is a good idea. And this is the normal or common way to store data in file system.

External libraries already can be stored in different places and can be mounted to the current internal structure. Maybe the same would be possible for the internal libraries? Then the internal folder structure could stay as it is.

**Reply by Samco2005** [reply]
I think it's a nice thing to have...

**Comment by MrSpoocy** [comment]
I've already looked a bit in the code and it looks like this could all be possible with a few changes in `server/src/domain/storage/storage.core.ts` (for the backend). Of course, something is still needed in the frontend and a migration script.

**Comment by Cyanogenbot** [comment]
This could be interesting to make interoperability with nextcloud easier aswell!

**Comment by jaimetur** [comment]
Definitely this is a must. Most of us would like to separate the different user libraries on different folders or even volumes. 

One common case is place each user library into /homes/user path, in that way, we can give access to each user to its /homes/user directory and they can see and manage its assets, and what is more important, we can make sure that each user don't exceed the given hard drive quota limit defined in the system

**Reply by ashar38** [reply]
Another vote for this. It would be extremely useful to give user-specific network or mount paths. I thought External Libraries can do this, but realized they are read-only.

**Reply by serivas** [reply]
Absolute must. In fact, this is the only thing that's barring us from adopting Immich thus far since we're already backing up each user's photos to our own `/home` directory and wouldn't want to separate old photos from (new) photos backed up by Immich. This would break other workstreams

**Comment by BryanConradHart** [comment]
To build on this, it'd be nice if the path for each user was configurable per user, rather than needing to use symlinks.

My family keeps our photos on a NAS, and each family member has their own share, and each share is mounted separately. It'd be nice if I could simply select each user's mount, right from the administration page, rather than SSHing into the host and configuring all the symlinks.

**Reply by artu-st** [reply]
This feature is essential.
While storage paths are usually set globally on the server, it would be very useful to allow configuration directly from the mobile clients. This way, when setting up a backup on a device, the user can also choose the storage path.
It would even allow a single user to define different paths for different devices if needed.

 #22333

**Reply by BryanConradHart** [reply]
I've worked around this in my deployment by using docker compose volumes:

```yaml
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: public-share
        target: /external-library/public
        volume:
          subpath: home-media/archive
      - type: volume
        source: user1-share
        target: /data/library/user-1-immich-user-id-here
        volume:
          subpath: home-media/library
      - type: volume
        source: user1-share
        target: /external-library/user1
        volume:
          subpath: home-media/archive
      - type: volume
        source: user2-share
        target: /data/library/user-2-immich-user-id-here
        volume:
          subpath: home-media/library
      - type: volume
        source: user2-share
        target: /external-library/user2
        volume:
          subpath: home-media/archive
      - type: volume
        source: backups-share
        target: /data/backups
        volume:
          subpath: immich
          
          
volumes:
  model-cache:
  public-share:
    external: true
  user1-share:
    external: true
  user2-share:
    external: true
  backups-share:
    external: true
```

although it means that every time you make a user, you need to go in and create a new service volume for them before they start backing up photos.

In my case, I don't want to save the transient files like thumbnails and transcodings, so I've only mapped libraries and backups to my NFS NAS volume.

**Reply by autox86** [reply]
It seems docker has changed the logic.

As we can see you are mounting "data" as usual:
`- ${UPLOAD_LOCATION}:/data`

The next step you mount again to overwrite the standard:
```

      - type: volume
        source: backups-share
        target: /data/backups
        volume:
          subpath: immich

```

We could also use the short form of it, without subpath
so something realistic:
`/mnt/bilder/christian:/data/library/christian`

After a couple of hours, inerestingly:
1.) Earlier the UID of the user was used, this has changed to the user name
2.) The mount after the first mount (data) is ignored.

It remains on the immich default, it does not matter what I do in docker compose.

The workaround is simple, I use bind mounts in fstab with no-fail option (eventhough it does not make sense)
Advantage: We remain default with the immich volumes.

Example:

```
# <source>              <target>                                    <type> <options>                   <dump> <pass>
/mnt/bilder/christian   /mnt/bilder/immich_app_data/library/christian   none   bind,nofail,x-systemd.device-timeout=10 0 0
```
