### DISCUSSION TITLE
[Feature] run, store, share database queries via GUI

### DISCUSSION THREAD

**Discussion by aisbergde** [immich-app/immich#6093] [Feature Request]
### The feature

more a nice to have feature, but maybe not so complicated to implement:

I would like to run database queries directly via the WEB GUI, in the administrator section.
some queries are already listed here:
https://immich.app/docs/guides/database-queries/

And I have some own queries (for example, to update all screenshots as isArchived, or to mark found orphans as offline and deleted). 

It's fine to run the scripts externally. But why not implement a way to execute queries directly via GUI?
And not only to execute them, but also to store them in the database?
And why not sharing scripts with other users?

### Platform

- [X] Server
- [X] Web
- [ ] Mobile

**Comment by martabal** [comment]
I feel like this is out of Immich scope. Sure, it's nice to have, but it requires more code to maintain.
There are many tools that already do that.

**Comment by zackpollard** [comment]
Yea, this is something out of scope for Immich, plenty of database clients exist that make this simple enough to do, there are even ones with their own web UI's.

**Reply by jurekl** [reply]
"Adminer" in a container in the same docker-compose works beautifully. When using the tailscale at the same time, we have full comfort and safety.

**Reply by aisbergde** [reply]
@jurekl - could you share your docker-compose or the relevant part of it, to easy setup Adminer and to see, how it works on the immich database?

**Reply by aisbergde** [reply]
I added:

```
  adminer:
    container_name: immich_adminer
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: immich_postgres
    depends_on:
      - database

```

and this works great! No need for extra pgAdmin.

**Reply by jurekl** [reply]
Here you go, this is the docker-compose snippet for my immich server instance:
```
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    ports:
      - 5432:5432 # OPTIONAL, for pgAdmin direct (via tailscale) access
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    #ports:
      #- 8080:8080 # not needed with Caddy proxy
    environment:
      ADMINER_DESIGN: "dracula" #optional
  
  #Caddy reverse proxy - optional
  caddy:
    image: caddy:latest
    container_name: caddy
  ...
  ...
```
For secure access, I have tailscale installed (free tier, 100% sufficient for everything I want) on all my machines, including immich, dev, home, etc. This is of course optional, you can easily use the standard tunnel SSH. Port selection at your discretion. Of course, it is also optional to use Caddy's reverse proxy, where I do not have to provide the host with any port from the Adminer container, Caddy takes care of this.

variable ADMINER_DESIGN: "dracula" is my theme configuration because I like it very much :-)
