### DISCUSSION TITLE
Using External PostgreSQL Database

### DISCUSSION THREAD

**Discussion by fabioteixei** [immich-app/immich#6200] [Q&A] [answered]
Hello

I'm trying to deploy immich on kubernetes using the official helm chart but with some changes to use an external PostgreSQL Database.
I have dedicated PostgreSQL hosts for many reasons and i would like to use my external server and not the auto created one.

So here are my values.yaml

```
env:
  DB_DATABASE_NAME: 'immich'
  DB_HOSTNAME: 'psqlhost'
  DB_PASSWORD: 'pass@word1'
  DB_USERNAME: 'immich'
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
image:
  tag: v1.91.4
immich:
  persistence:
    library:
      existingClaim: pvc-photos
machine-learning:
  enabled: true
  env:
    TRANSFORMERS_CACHE: /cache
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/immich-app/immich-machine-learning
  persistence:
    cache:
      accessMode: ReadWriteMany
      enabled: true
      size: 10Gi
      type: emptyDir
microservices:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/immich-app/immich-server
postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        database: immich
        password: immich
        username: immich
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.1.11
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;
redis:
  architecture: standalone
  auth:
    enabled: false
  enabled: true
server:
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/immich-app/immich-server
  ingress:
    main:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
      enabled: false
      hosts:
        - host: immich.local
          paths:
            - path: /
      tls: []
global:
  cattle:
    systemProjectId: p-d22rj
typesense:
  enabled: true
  persistence:
    tsdata:
      enabled: true
```

I deploy the chart but i got the same error on immich-server and on immich-microservices:

> [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [NestFactory] Starting Nest application...
> 2024-01-05T14:50:25.226630814-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
> [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
> 2024-01-05T14:50:25.226863718-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
> [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
> 2024-01-05T14:50:25.227195923-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
> [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
> 2024-01-05T14:50:25.227339726-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
> [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
> 2024-01-05T14:50:25.227928736-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
> [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
> QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.228906753-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
>     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.228972655-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
> 2024-01-05T14:50:25.229137157-05:00 QueryFailedError: function uuid_generate_v4() does not exist
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> 2024-01-05T14:50:25.229157058-05:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229186558-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.229208459-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> 2024-01-05T14:50:25.229247359-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
> 2024-01-05T14:50:25.229258860-05:00 QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.229267560-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> 2024-01-05T14:50:25.229276760-05:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-01-05T14:50:25.229290260-05:00     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229305260-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
>     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
> QueryFailedError: function uuid_generate_v4() does not exist
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> 2024-01-05T14:50:25.229428863-05:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-01-05T14:50:25.229437263-05:00     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229445663-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.229462863-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
> 2024-01-05T14:50:25.229561165-05:00 QueryFailedError: function uuid_generate_v4() does not exist
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> 2024-01-05T14:50:25.229587465-05:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-01-05T14:50:25.229596565-05:00     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229605166-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.229632766-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> 2024-01-05T14:50:25.229669667-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
> 2024-01-05T14:50:25.229685367-05:00 QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.229694667-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-01-05T14:50:25.229711567-05:00     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229720568-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.229749768-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> 2024-01-05T14:50:25.229774469-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
> 2024-01-05T14:50:25.229785869-05:00 QueryFailedError: function uuid_generate_v4() does not exist
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 2024-01-05T14:50:25.229820469-05:00     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.229828970-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.229845670-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> 2024-01-05T14:50:25.230039073-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
> 2024-01-05T14:50:25.230057974-05:00 QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.230073274-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.230145675-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
>     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.230216676-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> 2024-01-05T14:50:25.230252377-05:00 [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
> QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.230278677-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
> 2024-01-05T14:50:25.230287278-05:00     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.230303878-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
> 2024-01-05T14:50:25.230312078-05:00     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.230320278-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
> [Nest] 8  - 01/05/2024, 7:50:25 PM   ERROR [ExceptionHandler] function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.230375879-05:00 QueryFailedError: function uuid_generate_v4() does not exist
> 2024-01-05T14:50:25.230384679-05:00     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
> 2024-01-05T14:50:25.230421580-05:00     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
> 2024-01-05T14:50:25.230437580-05:00     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
> 2024-01-05T14:50:25.230452180-05:00     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)

Does any one has any idea on how to fix that?
