### DISCUSSION TITLE
how to include Adminer into docker-compose for easy database access

### DISCUSSION THREAD

**Discussion by aisbergde** [immich-app/immich#6254] [Show and tell]
### The feature

https://immich.app/docs/guides/database-queries lists some queries.
it looks like, that it is very easy to add [Adminer](https://www.adminer.org/) to the docker-compose, and this way administrators get very easy GUI access to the database. See idea posted by @jurekl in https://github.com/immich-app/immich/discussions/6093#discussioncomment-8042863_

Could we include this into the documentation as a hint?
my configuration:

```
  adminer:
    container_name: immich_adminer
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: immich_postgres
    depends_on:
      - database
```

maybe the port mapping is not the best, if it is already used

Can users just contribute to the docs?

### Platform

- [ ] Server
- [ ] Web
- [ ] Mobile
