### DISCUSSION TITLE
[BUG] <title>

### DISCUSSION THREAD

**Discussion by cgeheim** [immich-app/immich#6299] [Q&A]
### The bug

There are no files found in external libary.

### The OS that Immich Server is running on

Docker Synology

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-redis:
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    container_name: Immich-REDIS
    hostname: immich-redis
    networks:
      default:
        ipv4_address: 192.168.0.44
    ports:
      - 6379:6379    
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 5
    user: 1026:100
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: always

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.1.11
    container_name: Immich-DB
    hostname: immich-db
    networks:
      default:
        ipv4_address: 192.168.0.45
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 5m
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=HuGvs2024iW!
    restart: always

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    networks:
      default:
        ipv4_address: 192.168.0.46
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:3001
    volumes:
      - /volume1/immich/upload:/usr/src/app/upload
      - /volume2/immich-libary:/volume2/immich-libary:ro
    restart: always
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    networks:
      default:
        ipv4_address: 192.168.0.47
    ports:
      - 8212:3002   
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/immich/upload:/usr/src/app/upload
      - /volume1/immich/micro:/usr/src/app/.reverse-geocoding-dump
      - /volume2/immich-libary:/volume2/immich-libary:ro
    restart: always
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    networks:
      default:
        ipv4_address: 192.168.0.48
    ports:
      - 3003:3003   
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/immich/upload:/usr/src/app/upload
      - /volume1/immich/cache:/cache
      - /volume2/immich-libary:/volume2/immich-libary:ro
    restart: always
    depends_on:
      immich-db:
        condition: service_started
        
networks:
  default:
    name: mvl
    external: true
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Europe/Berlin
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=HuGvs2024iW!
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=Pass
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
IMMICH_WEB_URL=http://192.168.0.46:3001
IMMICH_SERVER_URL=http://192.168.0.46:3001
IMMICH_MACHINE_LEARNING_URL=http://192.168.0.48:3003
```

### Reproduction steps

```bash
1. Created external libary like the description on ther immich website
2. Scan libary for new files
3. No files were found
4. worked with Version v1.91.4
...
```
