### DISCUSSION TITLE
healtchecks for containers

### DISCUSSION THREAD

**Discussion by github-cli** [immich-app/immich#6320] [Q&A]
Hi,

I frequently get logs that the immich-machine-learning access timed out, I would like to add some healtcheck to each container, curl does not seem to be installed.
what would be a good way to check the health status of the containers?

**Comment by schuhbacca** [comment]
Personally I use uptime Kuma to monitor all my home lab stuff.

**Comment by github-cli** [comment]
sorry, I meant a healtcheck for the container that the container does by itself
so when you "docker ps" you see the status of the node itself
e.g. immich is reachable just fine but the microservices container complains about not being able to reach the machine learning container:
`immich_microservices     | [Nest] 7  - 01/10/2024, 9:09:52 PM   ERROR [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with ConnectTimeoutError: Connect Timeout Error`
i would like to know if the container itself is also reachable (actually it is so i need to find out whats wrong but thats a different topic)

**Comment by stanthewizzard** [comment]
Hello

I'm using in compose for:
  redis:
```
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
```

immich-server
```
    healthcheck:
      test: "curl -f http://localhost:3001"
      interval: 15s
      timeout: 45s
      retries: 10
```

database:
```
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
```

immich-microservices
```
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/3002"]
      interval: 10s
      timeout: 5s
      retries: 5
```

immich-machine-learning
```
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/3003"]
      interval: 10s
      timeout: 5s
      retries: 5
```

**Reply by stanthewizzard** [reply]
Curl is no more in server

**Reply by github-cli** [reply]
Sucks, it saves so little space but is so good for healthcheck and troubleshooting

**Reply by mmomjian** [reply]
You can mount a [static curl binary](https://github.com/moparisthebest/static-curl) into the container.

**Reply by stanthewizzard** [reply]
I'll watch that and don't understand how it will work inside the container

**Reply by AdrienPoupa** [reply]
I can offer an alternative for the server; create the following healthcheck.js script that calls `/api/server-info/ping`:

```js
// Inspired by: https://anthonymineo.com/docker-healthcheck-for-your-node-js-app/
const http = require('http');
const options = {
    host: '127.0.0.1',
    port: 3001,
    timeout: 2000,
    path: '/api/server-info/ping',
    headers: {
        'Host': process.env.HOSTNAME,
    }
};

const healthCheck = http.request(options, (res) => {
    console.log(`HEALTHCHECK STATUS: ${res.statusCode}`);
    if (res.statusCode === 200) {
        process.exit(0);
    }
    else {
        process.exit(1);
    }
});

healthCheck.on('error', function (err) {
    console.error('ERROR:' + err);
    process.exit(1);
});

healthCheck.end();
```

configure your docker-compose like this:

```yml
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./healthcheck.js:/healthcheck/healthcheck.js
    healthcheck:
      test: [ "CMD", "node", "/healthcheck/healthcheck.js" ]
      interval: 30s
      retries: 10
```

change the paths as needed and voila! A Node.js healthcheck that relies on Immich's API to report health status to Docker :)

**Reply by stanthewizzard** [reply]
I'm using this:

```
healthcheck:
  test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/3001"]
  interval: 10s
  timeout: 30s
  retries: 10
labels:
  - "autoheal=true"
```

**Comment by alangrainger** [comment]
An update for @AdrienPoupa 's excellent healthcheck script, to take into account the new port and server API path from [release 1.118.0](https://github.com/immich-app/immich/releases/tag/v1.118.0):

```javascript
// From: https://github.com/immich-app/immich/discussions/6320#discussioncomment-9183383
// Inspired by: https://anthonymineo.com/docker-healthcheck-for-your-node-js-app/
const http = require('http');
const options = {
    host: '127.0.0.1',
    port: 2283,
    timeout: 2000,
    path: '/api/server/ping'
};

const healthCheck = http.request(options, (res) => {
    console.log(`HEALTHCHECK STATUS: ${res.statusCode}`);
    if (res.statusCode === 200) {
        process.exit(0);
    }
    else {
        process.exit(1);
    }
});

healthCheck.on('error', function (err) {
    console.error('ERROR:' + err);
    process.exit(1);
});

healthCheck.end();
```

Configure your `docker-compose.yml` like this:

```yaml
  immich-server:
    volumes:
      - ./healthcheck.js:/healthcheck/healthcheck.js
    healthcheck:
      test: [ "CMD", "node", "/healthcheck/healthcheck.js" ]
      interval: 30s
      retries: 10
```
