### DISCUSSION TITLE
redis not working properly always showing Background saving terminated with success

### DISCUSSION THREAD

**Discussion by balavenkateshs** [immich-app/immich#6359] [Q&A]
### The bug

i am using portiner stack file.
immich redis logs 
1:C 06 Jan 2024 01:31:02.657 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Jan 2024 01:31:02.657 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 06 Jan 2024 01:31:02.657 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 06 Jan 2024 01:31:02.659 * monotonic clock: POSIX clock_gettime
1:M 06 Jan 2024 01:31:02.729 * Running mode=standalone, port=6379.
1:M 06 Jan 2024 01:31:02.730 # Server initialized
1:M 06 Jan 2024 01:31:02.730 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 06 Jan 2024 01:31:02.734 * Loading RDB produced by version 6.2.14
1:M 06 Jan 2024 01:31:02.734 * RDB age 187 seconds
1:M 06 Jan 2024 01:31:02.734 * RDB memory usage when created 1.78 Mb
1:M 06 Jan 2024 01:31:02.734 # Done loading RDB, keys loaded: 13, keys expired: 11.
1:M 06 Jan 2024 01:31:02.734 * DB loaded from disk: 0.004 seconds
1:M 06 Jan 2024 01:31:02.734 * Ready to accept connections
1:M 06 Jan 2024 01:36:03.017 * 100 changes in 300 seconds. Saving...
1:M 06 Jan 2024 01:36:03.019 * Background saving started by pid 19
19:C 06 Jan 2024 01:36:03.027 * DB saved on disk
19:C 06 Jan 2024 01:36:03.029 * RDB: 0 MB of memory used by copy-on-write
1:M 06 Jan 2024 01:36:03.120 * Background saving terminated with success
![1](https://github.com/immich-app/immich/assets/35548750/917a3ee3-433d-469a-85bd-7c38e76a8e8c)
![2](https://github.com/immich-app/immich/assets/35548750/3df6e6b0-340a-4d04-86a7-cbdd5f0d7018)

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - i_model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always
    volumes:
      - i_redis:/data
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - i_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  i_pgdata:
    external: true
    name: i_pgdata
  i_redis:
    external: true
    name: i_redis
  i_model-cache:
    external: true
    name: i_model-cache
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-448690dd-6c4a-48a3-8f35-88c2f9635af9/immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.photos faces not identify, same faces also showing as separate.
2. every time i am adding face name and merging the photos, my library around 25K + photos 
3.
...
```
