### DISCUSSION TITLE
[BUG] Wrong date on videos due to re-encoding them

### DISCUSSION THREAD

**Discussion by GregTroar** [immich-app/immich#6370] [General]
### The bug

All my videos are having wrong dates and all appears in the timeline at the date of 4th January which is the date when they were encoded by Immich.
So videos of 1,2, 3 years old all appears on the same day on the timeline.

Would be great to retain the creation date of original videos rather then the encoded video itself.

Thanks

### The OS that Immich Server is running on

Docker, Debian Bookworm

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.92.0 build.117

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Multimedia/Photos:/mnt/media:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Multimedia/Photos:/mnt/media:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always
    volumes:
      - ./data:/data

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION="/mnt/Multimedia/Photos/Photos Telephones/"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=xxxxxx
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. First time installing Immich
2. Upload all pictures / videos from Camera from today to 2 years ago
3. After Immich has finished encoding the videos for the web GUI all videos are showing the date of the encoding not the original date.
4. All videos are improperly sorted in the timeline.
```
