### DISCUSSION TITLE
[BUG] Failed to finish oauth

### DISCUSSION THREAD

**Discussion by Alexsaphir** [immich-app/immich#6400] [Q&A]
### The bug

I set up authelia with immich and use OAuth to perform login. Everything worked fine, OAuth was working until recently when I tried to log in. I was prompted with the following message: `Failed to finish oauth`.

### The OS that Immich Server is running on

Container K3s

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Running Immich on kubernetes.
```

### Your .env content

```Shell
DB_URL : secretKeyRef(database-immich.POSTGRES_URL) 
DISABLE_REVERSE_GEOCODING : true
IMMICH_MACHINE_LEARNING_URL : http://immich-machine-learning.immich.svc.cluster.local:3003
IMMICH_SERVER_URL : http://immich-server.immich.svc.cluster.local:3001
IMMICH_WEB_URL : http://immich-web.immich.svc.cluster.local:3000
LOG_LEVEL : verbose
NODE_ENV : production
REDIS_HOSTNAME : immich-redis.immich.svc.cluster.local
REDIS_PORT : 6379
TRANSFORMERS_CACHE : /usr/src/app/.transformers_cache
JWT_SECRET : secretKeyRef(immich-secret.JWT_SECRET)
```

### Reproduction steps

```bash
I previously setup oauth and used it fine. Recently trying to login the oauth was not working anymore.
```

### Additional information

I've made sure that the client id is the same between both applications.
The secret is also the same.

The server returns the following logs:

```
[Nest] 8  - 01/15/2024, 3:18:10 PM   ERROR [OPError: invalid_client (Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).)
    at processResponse (/usr/src/app/node_modules/openid-client/lib/helpers/process_response.js:38:13)
    at Client.grant (/usr/src/app/node_modules/openid-client/lib/client.js:1354:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.callback (/usr/src/app/node_modules/openid-client/lib/client.js:493:24)
    at async AuthService.getOAuthProfile (/usr/src/app/dist/domain/auth/auth.service.js:225:24)
    at async AuthService.callback (/usr/src/app/dist/domain/auth/auth.service.js:167:25)
    at async OAuthController.finishOAuth (/usr/src/app/dist/immich/controllers/oauth.controller.js:39:38)] OPError: invalid_client (Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).)
```

Authelia is setup in the following manner:

```yaml
identity_providers:
  oidc:
    cors:
      endpoints: [ 'authorization', 'token', 'revocation', 'introspection' ]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - id: immich
        description: Immich
        secret: "${IMMICH_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: [ 'openid', 'profile', 'email' ]
        redirect_uris:
          - https://photos.${SECRET_DOMAIN_NAME}/auth/login
          - https://photos.${SECRET_DOMAIN_NAME}/user-settings
          - app.immich:/
        userinfo_signing_algorithm: none
```
