### DISCUSSION TITLE
[Feature] Add a `MACHINE_LEARNING_URL` environment variable

### DISCUSSION THREAD

**Discussion by PHLAK** [immich-app/immich#6630] [Feature Request]
### The feature

I have a customized [Docker compose environment](https://github.com/PHLAK/immich-compose) and use a different name for the micro-services container which requires me to set an alternate URL in the Micro Services Settings section of the administrator settings. However, after modifying some of my facial recognition detection values when I clicked the "Reset to default" button to reset these to default it _also_ reset the Micro Services URL to default without me realizing. This broke the connection to the machine learning container.

Of course I realized my mistake after inspecting the container logs but it would be convenient if we could set an environment variable (e.g. `MACHINE_LEARNING_URL` or similar) to control this setting's default value and avoid this situation altogether. This would allow us to preset the variable in our `docker-compose.yaml` file as well since, at least in my case, the value is predetermined by the machine learning container name.

### Platform

- [ ] Server
- [X] Web
- [ ] Mobile

**Comment by bo0tzz** [comment]
You can configure the ML URL via the config file.

**Reply by PHLAK** [reply]
Sure, but ~~that must be done _after_ the container is created and~~ I don't believe this affects the default value (i.e. clicking "Reset to default" would set it back to `http://immich-machine-learning:3003`).

I'd really like to be able to do something like this.

```yaml
version: '3'

services:

  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      MACHINE_LEARNING_URL: "http://machine-learning:3003"
    // ...

  machine-learning:
    image: image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    // ...
```

**EDIT:** Double checked the documentation and realized we can set the config file _before_ container creation. Need to confirm how this affects the default value still though.
