### DISCUSSION TITLE
Error: ENOENT: no such file or directory, open '/usr/src/app/dist/main'

### DISCUSSION THREAD

**Discussion by varosengineer** [immich-app/immich#6790] [Q&A]
### The bug

I'm trying to deploy Immich on my Asustor NAS, but I can't get it to work.

This is the error that appears in the logs of `immich_server` container:
```
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^
Error: ENOENT: no such file or directory, open '/usr/src/app/dist/main'
    at Object.readFileSync (node:fs:453:20)
    at Module._extensions..js (node:internal/modules/cjs/loader:1397:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/src/app/dist/main'
}
Node.js v20.11.0
```

### The OS that Immich Server is running on

Asustor ADM 4.2.6.RPI1

### Version of Immich Server

release

### Version of Immich Mobile App

release

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /share/Backup/Immich/cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /share/Backup/Immich/db/:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
TZ=Europe/Madrid
UPLOAD_LOCATION=/share/Backup/Immich/upload
IMMICH_VERSION=release
DB_PASSWORD=my_db_password
TYPESENSE_ENABLED=false
MACHINE_LEARNING_REQUEST_THREADS=0
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
REDIS_PORT=6379
```

### Reproduction steps

```bash
1. Go to Portainer and click on create new Stack
2. Paste the content of the docker-compose.yml in the editor
3. Set the Environment Variables
4. Click on Deploy Stack
5. Check the immich-server logs
```
