### DISCUSSION TITLE
Search fails with pgvector.rs

### DISCUSSION THREAD

**Discussion by monotok** [immich-app/immich#6828] [Q&A] [answered]
### The bug

I think this happened after migrating to pgvector.rs with 1.91.1 but currently running 1.94.1.

I used to be able to search things like "flowers" and it would show all the flowers however I now get a 500 error.

```
Failed to search - 500 - Internal Server Error
j@https://pics.example.com/_app/immutable/chunks/api.hDXpMC_1.js:1:5297
nn@https://pics.example.com/_app/immutable/chunks/api.hDXpMC_1.js:3:1042
b@https://pics.example.com/_app/immutable/chunks/api.hDXpMC_1.js:3:4229
```

The logs in the server container.

```
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2040:26)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getMany (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:750:25)
    at async /usr/src/app/dist/infra/repositories/smart-info.repository.js:71:23
    at async EntityManager.transaction (/usr/src/app/node_modules/typeorm/entity-manager/EntityManager.js:73:28)
    at async SmartInfoRepository.searchCLIP (/usr/src/app/dist/infra/repositories/smart-info.repository.js:51:9)
    at async SearchService.search (/usr/src/app/dist/domain/search/search.service.js:68:26)] QueryFailedError: pgvecto.rs: The index is not existing in the background worker.
ADVICE: Drop or rebuild the index.
```

Before pgvector.rs was required I was using a postgres cluster that was shared with other services. I setup a new cluster [cloudnative-pgvector.rs](https://github.com/tensorchord/cloudnative-pgvecto.rs/pkgs/container/cloudnative-pgvecto.rs) and migrated the data via pgdump.

### The OS that Immich Server is running on

Kubernetes RKE2 Cluster

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.93.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-server
    app: immich
    storage.type: iscsi
  name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-server
    spec:
      nodeName: "kubey01"
      containers:
        - args:
            - start-server.sh
          env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-server:v1.94.1
          name: immich-server
          resources: {}
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-server-claim0
            - mountPath: /usr/src/app/upload/thumbs
              name: immich-thumbs
            - mountPath: /mnt/photos
              subPath: Processed
              name: photos-vol
      restartPolicy: Always
      volumes:
        - name: immich-server-claim0
          persistentVolumeClaim:
            claimName: immich-claim0
        - name: immich-thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs-pvc
        - name: photos-vol
          nfs:
            path: /Photos
            server: 192.168.1.1
            readOnly: true
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-machine-learning
    app: immich
    storage.type: iscsi
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-machine-learning
    spec:
      containers:
        - env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-machine-learning:v1.94.1
          name: immich-machine-learning
          resources:
            limits:
              cpu: "4"
          volumeMounts:
            - mountPath: /cache
              name: immich-machine-learning-cache
      restartPolicy: Always
      volumes:
        - name: immich-machine-learning-cache
          persistentVolumeClaim:
            claimName: immich-ml-cache-pvc
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-microservices
    app: immich
    storage.type: iscsi
  name: immich-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-microservices
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-microservices
    spec:
      nodeName: "kubey01"
      containers:
        - args:
            - start-microservices.sh
          env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-server:v1.94.1
          name: immich-microservices
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-microservices-claim0
            - mountPath: /usr/src/app/upload/thumbs
              name: immich-thumbs
            - mountPath: /mnt/photos
              subPath: Processed
              name: photos-vol
      restartPolicy: Always
      volumes:
        - name: immich-microservices-claim0
          persistentVolumeClaim:
            claimName: immich-claim0
        - name: immich-thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs-pvc
        - name: photos-vol
          nfs:
            path: /Photos
            server: 192.168.1.1
            readOnly: true
status: {}
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
1. Search for any word within the web gui
```
