### DISCUSSION TITLE
/immich-app/immich-server - Error [Nest] 7

### DISCUSSION THREAD

**Discussion by cgeheim** [immich-app/immich#6851] [Q&A]
### The bug

[Nest] 7  - 02/01/2024, 7:11:39 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:11:39 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:13:37 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses

[Nest] 7  - 02/01/2024, 7:13:38 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at afterWriteDispatched (node:internal/stream_base_commons:160:15)

    at writeGeneric (node:internal/stream_base_commons:151:3)

    at Socket._writeGeneric (node:net:952:11)

    at Socket._write (node:net:964:8)

    at doWrite (node:internal/streams/writable:590:12)

    at clearBuffer (node:internal/streams/writable:773:7)

    at Writable.uncork (node:internal/streams/writable:523:7)

    at connectionCorkNT (node:_http_outgoing:955:8)

### The OS that Immich Server is running on

Sysnology DS1618

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.94.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
 
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    container_name: immich_server
    hostname: immich-server
    networks:
      default:
        ipv4_address: 192.168.0.46
    user: 1026:101
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
    restart: always
    depends_on:
     - immich-redis
     - immich-db

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    container_name: immich_microservices
    hostname: immich-microservices
    networks:
      default:
        ipv4_address: 192.168.0.47
    ports:
      - 8212:3002   
    user: 1026:101
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
     # - ${EXTERNAL_PATH}:/usr/src/app/external
     # - /volume2/immich/micro:/usr/src/app/.reverse-geocoding-dump
    restart: always
    depends_on:
     - immich-redis
     - immich-db

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-learning
    hostname: immich-machine-learning
    user: 1026:101
    networks:
      default:
        ipv4_address: 192.168.0.48
    ports:
      - 8212:3003   
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume2/immich/cache:/cache
    restart: always
        
  immich-redis:
    image: redis:6.2-alpine@sha256:e37f1652146657d95486471424a2ff36d375f9ac3ca66028818c2dbba40e6303
    container_name: immich_redis
    hostname: immich-redis
    networks:
      default:
        ipv4_address: 192.168.0.44
    ports:
      - 6379:6379    
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 5
    user: 1026:101
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: always

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.1.11
    container_name: immich_postgres
    hostname: immich-db
    networks:
      default:
        ipv4_address: 192.168.0.45
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 5m
      timeout: 5s
      retries: 5
    volumes:
      - /volume2/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=XXXX
    restart: always
     
networks:
  default:
    name: mvl
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume2/immich/upload
IMMICH_VERSION=release
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=HuGvs2024iW!
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=xia7jNMRT50PgcShC0BTuFxTLPamoYnQO8OKH8jUff4iD0AdtbC8HTZp/Rv4LSdpV7kXbYTvxNrw24NzJJiag2nisYbUmEV8XbJEEboag98z+6KR5djhPPC4/oztoSJHOB2rpPXjv4VNwCAT0PvTKUo3gSY8rDja85DGugYqJ0c=
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://192.168.0.46:3001
IMMICH_SERVER_URL=http://192.168.0.46:3001
IMMICH_MACHINE_LEARNING_URL=http://192.168.0.48:3003
NODE_ENV=production
TZ=Europe/Berlin
EXTERNAL_PATH=/volume2/immich_extern
```

### Reproduction steps

```bash
1. Running immich
2. Check logs
3. Find a lot of errors since update to 1.94.1 about [Nest] 7 
...
```

### Additional information

[Nest] 7  - 02/01/2024, 7:11:39 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:11:39 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:13:37 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses

[Nest] 7  - 02/01/2024, 7:13:38 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at afterWriteDispatched (node:internal/stream_base_commons:160:15)

    at writeGeneric (node:internal/stream_base_commons:151:3)

    at Socket._writeGeneric (node:net:952:11)

    at Socket._write (node:net:964:8)

    at doWrite (node:internal/streams/writable:590:12)

    at clearBuffer (node:internal/streams/writable:773:7)

    at Writable.uncork (node:internal/streams/writable:523:7)

    at connectionCorkNT (node:_http_outgoing:955:8)

    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] Failed to serve file

[Nest] 7  - 02/01/2024, 7:27:14 PM   ERROR [Error: write EPIPE

    at afterWriteDispatched (node:internal/stream_base_commons:160:15)

    at writeGeneric (node:internal/stream_base_commons:151:3)

    at Socket._writeGeneric (node:net:952:11)

    at Socket._write (node:net:964:8)

    at doWrite (node:internal/streams/writable:590:12)

    at clearBuffer (node:internal/streams/writable:773:7)

    at Writable.uncork (node:internal/streams/writable:523:7)

    at connectionCorkNT (node:_http_outgoing:955:8)

    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] Error: write EPIPE

[Nest] 7  - 02/01/2024, 7:27:18 PM     LOG [CommunicationRepository] Websocket Disconnect: ix5aqmj1QoR8F-gBAAAH

[Nest] 7  - 02/01/2024, 7:27:19 PM     LOG [CommunicationRepository] Websocket Connect:    7TB8GkwjJhyYIsGSAAAJ

[Nest] 7  - 02/01/2024, 7:27:21 PM     LOG [CommunicationRepository] Websocket Disconnect: 7TB8GkwjJhyYIsGSAAAJ

[Nest] 7  - 02/01/2024, 8:23:47 PM     LOG [CommunicationRepository] Websocket Connect:    rYq-tki26D26SXtcAAAL

[Nest] 7  - 02/01/2024, 8:24:11 PM     LOG [CommunicationRepository] Websocket Disconnect: rYq-tki26D26SXtcAAAL

[Nest] 7  - 02/01/2024, 8:38:09 PM     LOG [CommunicationRepository] Websocket Connect:    MQIx1QsyTTNX-ZVtAAAN

[Nest] 7  - 02/01/2024, 8:39:54 PM     LOG [CommunicationRepository] Websocket Disconnect: MQIx1QsyTTNX-ZVtAAAN

[Nest] 7  - 02/02/2024, 6:52:57 AM     LOG [CommunicationRepository] Websocket Connect:    JuC40-X0hSrvcCImAAAP

[Nest] 7  - 02/02/2024, 6:52:59 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/02/2024, 6:52:59 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/02/2024, 6:52:59 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/02/2024, 6:52:59 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/02/2024, 6:53:00 AM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses

[Nest] 7  - 02/02/2024, 6:53:00 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/02/2024, 6:53:00 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/02/2024, 6:53:00 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

[Nest] 7  - 02/02/2024, 6:53:00 AM   ERROR [Error: write EPIPE

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Error: write EPIPE

[Nest] 7  - 02/02/2024, 6:53:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:632:28)

    at Connection.emit (node:events:518:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:337:12)

[Nest] 7  - 02/02/2024, 6:53:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:632:28)

    at Connection.emit (node:events:518:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:337:12)

[Nest] 7  - 02/02/2024, 6:53:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:632:28)

    at Connection.emit (node:events:518:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:337:12)

[Nest] 7  - 02/02/2024, 6:53:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:632:28)

    at Connection.emit (node:events:518:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:337:12)

[Nest] 7  - 02/02/2024, 6:53:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:632:28)

    at Connection.emit (node:events:518:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:63:12)

    at Socket.emit (node:events:518:28)

    at TCP.<anonymous> (node:net:337:12)

[Nest] 7  - 02/02/2024, 7:04:46 AM     LOG [CommunicationRepository] Websocket Disconnect: JuC40-X0hSrvcCImAAAP
