### DISCUSSION TITLE
Broken thumbnails

### DISCUSSION THREAD

**Discussion by ippocratis** [immich-app/immich#6873] [Q&A]
### The bug

All containers looks like they run fine

I want to use immich with external library

Files on the dir owned by root

```
ls -l ../photos                                                   total 2925460                                           drwxrwxrwx  3 root root       4096 Jan 18  2022 2008    drwxrwxrwx 13 root root       4096 Jan 18  2022 2009    drwxrwxrwx 13 root root       4096 Jan 18  2022 2010    drwxrwxrwx 10 root root       4096 Jan 20  2022 2011    drwxrwxrwx 14 root root       4096 Jan 19  2022 2012    drwxrwxrwx 13 root root       4096 Jan 19  2022 2013    drwxrwxrwx 14 root root       4096 Jan 20  2022 2014    drwxrwxrwx 14 root root       4096 Jan 19  2022 2015    drwxrwxrwx 14 root root       4096 Jan 19  2022 2016    drwxrwxrwx 14 root root       4096 Jan 19  2022 2017    drwxrwxrwx 14 root root       4096 Jan 19  2022 2018    drwxrwxrwx 14 root root       4096 Jan 19  2022 2019    drwxrwxrwx 14 root root       4096 Jan 17  2022 2020    drwxrwxrwx 14 root root       4096 Jan 18  2022 2021    drwxrwxrwx 14 root root       4096 Dec  2  2022 2022    drwxrwxrwx 14 root root       4096 Dec  3 23:14 2023    drwxrwxrwx  3 root root       4096 Jan  1 16:45 2024
```

App logs filled with errors

```
FlutterError - Catch all error:  - HttpException: Invalid statusCode: 404, uri = http://192.168.1.24:2283/api/asset/thumbnail/aae922af-48e1-4252-93f7-357aef1ff088?format=WEBP - image resource service - resolving an image codec - 
```

### The OS that Immich Server is running on

Manjaro arm

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

Same

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"                                                                                                  #                                                       # WARNING: Make sure to use the docker-compose.yml of the current release:                                      #                                                       # https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml                              #                                                       # The compose file on main may not be compatible with the latest release.                                       #                                                                                                               name: immich                                                                                                    services:                                                 immich-server:                                            container_name: immich_server                           image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                              command: [ "start.sh", "immich" ]                       volumes:                                                  - ${UPLOAD_LOCATION}:/usr/src/app/upload                - /etc/localtime:/etc/localtime:ro                      - ${EXTERNAL_PATH}:/usr/src/app/external              env_file:                                                 - .env                                                ports:                                                    - 2283:3001                                           depends_on:                                               - redis                                                 - database                                            restart: always                                                                                               immich-microservices:                                     container_name: immich_microservices                    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                              # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding                                               #   file: hwaccel.transcoding.yml                       #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding        command: [ "start.sh", "microservices" ]                volumes:                                                  - ${UPLOAD_LOCATION}:/usr/src/app/upload                - /etc/localtime:/etc/localtime:ro                      - ${EXTERNAL_PATH}:/usr/src/app/external              env_file:                                                 - .env
    depends_on:                                               - redis                                                 - database                                            restart: always                                                                                               immich-machine-learning:                                  container_name: immich_machine_learning                 # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.                              # Example tag: ${IMMICH_VERSION:-release}-cuda          image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}                                    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration                                           #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable                     volumes:
      - model-cache:/cache                                  env_file:                                                 - .env                                                restart: always
                                                          redis:                                                    container_name: immich_redis                            image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82                 restart: always                                                                                               database:
    container_name: immich_postgres                         image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:                                                 - .env                                                environment:                                              POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}                           POSTGRES_DB: ${DB_DATABASE_NAME}                      volumes:                                                  - pgdata:/var/lib/postgresql/data
    restart: always                                                                                             volumes:                                                  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables                                                                                                       # The location where your uploaded files are stored     UPLOAD_LOCATION=./library                                                                                       #external library                                       EXTERNAL_PATH=/run/media/ippo/TOSHIBA/photos                                                                    # The Immich version to use. You can pin this to a specific version like "v1.71.0"                              IMMICH_VERSION=release                                                                                          # Connection secret for postgres. You should change it to a random password                                     DB_PASSWORD=somepassword                                                                                           # The values below this line do not need to be changed  ###################################################################################                             DB_HOSTNAME=immich_postgres                             DB_USERNAME=postgres                                    DB_DATABASE_NAME=immich                                                                                         REDIS_HOSTNAME=immich_redis



Additional content

App logs are filled with

```
FlutterError - Catch all error:  - HttpException: Invalid statusCode: 404, uri = http://192.168.1.24:2283/api/asset/thumbnail/bd7d75e7-b7cf-478b-8f04-732a127f17b9?format=WEBP - image resource service - resolving an image codec -
```


### Reproduction steps

```bash
1.
2.
3.
...
```
