### DISCUSSION TITLE
v1.29.0_42-dev

### DISCUSSION THREAD

**Discussion by alextran1502** [immich-app/immich#694] [Announcements]
## Breaking change
#651 *Breaking Change* 
`immich-proxy` switched from using port `80` which was used inside of the container to `8080` to drop dependency on a privileged user inside the container. This reduces a potential security risk of someone being able to impersonate that user on the host.

As a result you will need to change your `docker-compose.yaml` to reflect this change, by changing the port-binding from

```
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
```
to
```
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
```

re-running
```bash
curl -o- https://raw.githubusercontent.com/immich-app/immich/main/install.sh | bash
```
will also ensure you get the latest version of the docker-compose.yaml

a full example of the always-up-to-date docker-compose.yaml can be found [in our repo](https://raw.githubusercontent.com/immich-app/immich/main/docker/docker-compose.yml)

## What's Changed
* feat(readme) add app store links by @tennox in https://github.com/immich-app/immich/pull/689
* fix(mobile): Android BackgroundServiceStartNotAllowedException by @zoodyy in https://github.com/immich-app/immich/pull/687
* fix(server): mismatch createdAt value in `exif` table and `asset` table by @alextran1502 in https://github.com/immich-app/immich/pull/688
* feat(setup): use non-root image for immich-proxy by @PixelJonas in https://github.com/immich-app/immich/pull/651
* feat(readme) by @beune in https://github.com/immich-app/immich/pull/690
* fix(mobile) cache read write error on iOS 16 by @alextran1502 in https://github.com/immich-app/immich/pull/691
* fix(setup): revert nginx image to support arm/v7 by @PixelJonas in https://github.com/immich-app/immich/pull/692

## New Contributors
* @tennox made their first contribution in https://github.com/immich-app/immich/pull/689
* @PixelJonas made their first contribution in https://github.com/immich-app/immich/pull/651
* @beune made their first contribution in https://github.com/immich-app/immich/pull/690

**Full Changelog**: https://github.com/immich-app/immich/compare/v1.28.4_41-dev...v1.29.0_42-dev

<hr /><em>This discussion was created from the release <a href='https://github.com/immich-app/immich/releases/tag/v1.29.0_42-dev'>v1.29.0_42-dev</a>.</em>
