### DISCUSSION TITLE
AFter the upgrade, all albums are gone and not able to access albums tab on web interface

### DISCUSSION THREAD

**Discussion by grpursuing** [immich-app/immich#6983] [Q&A]
### The bug

AFter the upgrade, all albums are gone and not able to access albums tab on web interface

Below is the error

Failed to get all albums (500 - Internal Server Error)

Stacktrace
AxiosError: Request failed with status code 500
    at nn (https://XXXX/_app/immutable/chunks/api.hDXpMC_1.js:3:1042)
    at XMLHttpRequest.b (https://XXXX/_app/immutable/chunks/api.hDXpMC_1.js:3:4227)
    at ze.request (https://XXXX/_app/immutable/chunks/api.hDXpMC_1.js:5:3105)
    at async tl (https://XXXX/_app/immutable/nodes/4.vvr9h-Yw.js:1:1789)
    at async be (https://XXXX/_app/immutable/chunks/entry.XM6ES_OL.js:1:12873)

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

1.94.1 build 1.37

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/root/photos-drive/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=XXXXXXXX
DB_PASSWORD=XXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=XXXX
DB_USERNAME=XXXX
DB_DATABASE_NAME=XXXX
```

### Reproduction steps

```bash
Issue 1 (On web interface)
1.Logon on web interface
2.Click Albums
3. Fails with Internal server 500 error 
...

Issue 2 (on mobile app)
I can select album and it shows all random albums created with random names and 2-3 pics in all of those albums, doenst show any on my previous albums except couple
```

### Additional information

Is it because of i have 1.1 tb of pictures ?
