### DISCUSSION TITLE
[BUG] Opening Settings page throws "TypeError: Failed to fetch dynamically imported module"

### DISCUSSION THREAD

**Discussion by entr0p1** [immich-app/immich#6994] [Q&A] [answered]
### The bug

When navigating to the "Settings" sub-menu of the "Administration" page, an error is thrown with the below text displayed on the page:
```
Failed to fetch dynamically imported module: https://<My Instance URL>/_app/immutable/nodes/35.dd5db5ca.js (500)

Stacktrace
TypeError: Failed to fetch dynamically imported module: https://<My Instance URL>/_app/immutable/nodes/35.dd5db5ca.js
```
I've browsed to the URL manually and it loads fine.

### The OS that Immich Server is running on

Oracle Linux 8.9

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.91.4
    command: ["start.sh", "immich"]
    ports:
      - 40006:3001
    env_file:
      - stack.env
    volumes:
      - /data/container-data/immich/immichdata:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.91.4
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    env_file:
      - stack.env
    volumes:
      - /data/container-data/immich/immichdata:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.91.4
    env_file:
      - stack.env
    volumes:
      - /var/container-data/immich/mlcache:/cache
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /var/container-data/immich/pgsqldata:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_PASSWORD=<REDACTED>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Australia/Melbourne
```

### Reproduction steps

```bash
1. Go to "Administration" page
2. Click "Settings"
```

### Additional information

To rule out any obvious issues with my environment I have tried to:

1. Use both Firefox and Chrome
2. Use Private Browsing in both browsers
3. Bypass my reverse proxy and access the Docker container directly over HTTP

None of the above has resolved it. It appears all other areas of the application are working fine; I am able to browse my photo gallery both on the web and mobile apps and can upload content just fine.

**Comment by martabal** [comment]
Can you try without your reverse proxy ?

**Comment by entr0p1** [comment]
Yeah I have tried that (step 3 in my "additional information" section), but no luck there either unfortunately. 

After some further testing, the user settings (under the logged in user's menu in the top-right corner of the page) exhibits the same behaviour. 

I have also tried completely destroying the container and re-pulling it just in case something weird happened to the local image.

**Comment by aviv926** [comment]
I saw that several people reported a similar problem to yours on the Immich discord server
Although you have tried different browsers, you should try:
1. Try clearing your browser cache
2. Try peeking here https://github.com/immich-app/immich/issues/5291
3. Some claim it's related to a problem with NPM but I can't say for sure

**Comment by Aldwyr** [comment]
Same issues, but on main page like : immich.domaine/photos. 
When I first connect to my main page and reload, I have this error message.

**Comment by undaunt** [comment]
@Aldwyr I was seeing a ton of 429 errors which made me realize my Traefik was causing rate limiting issues. I disabled that specific middleware and everything is now resolved.

Here are my middlewares and chains below. There are probably similar rate limit configs for caddy and nginx?

**rateLimit middleware**
```
      rateLimit:
        average: 100
        burst: 50
```

**chained middlewares**
```
    chain-auth:
      chain:
        middlewares:
          - secure-headers
          - rate-limit
          - crowdsec
          - authelia
    chain-no-ratelimit:
      chain:
        middlewares:
          - secure-headers
          - crowdsec
          - authelia
```

I swapped from chain-auth to chain-no-ratelimit.
