### DISCUSSION TITLE
Missing faces & face recognition terminated early

### DISCUSSION THREAD

**Discussion by dominikheinz** [immich-app/immich#7011] [Q&A]
### The bug

Today, I created a fresh immich instance on my home server, all settings on default.
Then, I imported some pictures, and after the upload I waited for all the jobs to complete.
I noticed that a large amount of faces were not detected/not showing up in the person view (even tho the faces are clearly visible in the picture).

> [!NOTE]
> It is worth noting, that I had the **exact same pictures** on a previous older instance that I've created a couple of months ago, and there, all faces were detected/recognized perfectly fine. That being said, I don't remember what the version of the immich instance was on at the time of the upload on the old instance, because I updated it multiple times since then...

I also noticed something weird, that may or may not have to do with this issue:
During the upload the _face detection_ and then _face recognition_ task are started.
However, when the _face detection_ job is completed, the _face recognition_ job is automatically terminated (even tho there are still hundreds of pictures left in the queue!).
Also: Restarting the _face recognition_ job for all assets by clicking the button, has no effect.

A video of this problem is attached below:

[Screencast from 2024-02-09 20-41-34.webm](https://github.com/immich-app/immich/assets/32770080/93e25118-2b8b-477f-9bea-248c3cb7e097)

### The OS that Immich Server is running on

Arch Linux

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Setup new immich instance (1.94.1)
2. Upload a bunch of images
3. Observe the jobs that get started
4. Notice that the completion of the face detection task terminates the face recognition task, and manually restarting the face recognition task for all assets has no effect
5. Notice a bunch of faces are not recognized and therefore not showing up in the UI...
```
