### DISCUSSION TITLE
Immich not loading new mobile upload into /library on NAS

### DISCUSSION THREAD

**Discussion by nicoKoehler** [immich-app/immich#7013] [Q&A] [answered]
Hi all, hope you can help, I am at wit's end. 

I have my Immich setup all but ready to fully replace Google Photos. But mobile uploads are still a thorn in my thigh. 

**Expected behavior**
Per my understanding, Immich should move mobile uploads into the /library path after its done processing.

**Observed behavior**
Mobile uploads show up in Web client, but path remains obscure system path and is never moved outside of the container/volumes. I tunneled into the running container to confirm path in the filesystem and DB. E.g.:
`upload/upload/d119fe25-6334-40fa-9c15-b87126474df2/c2/e9/c2e9310a-7113-47af-9e06-b3b34d805716.jpg`

**Errors**
None. Docker logs show no errors or warnings

**Things I have tried**
- Tried to map NAS directly as volume to the container, both via cifs (did not work) and nfs (worked, but same result)
- Tried to map NAS in fstab as nfs. Same behavior
- Tunneled into container, placed new file in mapped volume path (/library) from the shell. File showed up on NAS. Makes me believe it's not a permissions issue either. 

**General setup:**
- Synology NAS DS214play
- Beelink S12 Pro N100 server
- Immich running in  docker on Ubuntu Server
- NAS drive is mapped as cifs via fstab on the server
`//192.168.1.xx/Files/Images  /mnt/nas  cifs    credentials=/home/server/xyz,uid=1000,gid=1000,vers=2.0    0       0`
- Mapped NAS is used as external path (scan successful

**docker-compose.yml** (volumes)
```yml
volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${EXT_FILES}:/usr/src/app/external
      - ${LIBRARY_LOC}:/usr/src/app/upload/library:rw
      - ${UPLOAD_LOC}:/usr/src/app/upload/upload
      - ${THUMBS_LOC}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOC}:/usr/src/app/upload/profile
      - ${EVID_LOC}:/usr/src/app/upload/encoded-video
    env_file:
      - .env
```
**And the .env**
``` 
  LIBRARY_LOC=/mnt/nas/immich_library
  UPLOAD_LOC=/home/server/immich/upload
  THUMBS_LOC=/home/server/immich/thumbs
  PROFILE_LOC=/home/server/immich/profile
  EVID_LOC=/home/server/immich/encoded-video

```
The separation of folders comes from [this guide](https://github.com/immich-app/immich/discussions/2328). The separation is intended to allow for new mobile uploads to be backed up on my NAS (which in turn is backed up itself), without backing up the meta files like thumbnails etc.
