### DISCUSSION TITLE
AMD ROCM/MigraphX machile learning

### DISCUSSION THREAD

**Discussion by dmnieto** [immich-app/immich#7169] [Feature Request]
### The feature

Not for the faint of heart, but following the addition of CUDA, openVINO and ARM based ML addition to immich I am looking into adding that functionality.

I will monitor the progress in this thread, as it is *significantly* more complex that I though... I got it working, but I am still debugging some of their multiple 'quirks'

As a summary:

- Getting an image with the proper rocm/migraphx binaries => Done, but requires tweaks as it does not build in the same environment as the python 3.11 based one we have in immich
- Getting onnxruntime compiled => Done, Alas, the only EP supported by onnxruntime without a simple pip installation is the ROCM one, and believe me, I can see why. There are binary *whl files availble for rocm, but, not for python 3.11
- Getting the models actually working=> In progress, because of course the ROCM EP in onnxruntime is broken. (related bug https://github.com/apache/tvm/pull/16178) and I'll likely need to open a bug in onnxruntime or create a branch with the fix on it. Currently I made it work by completely disabling the algo model cache, and I am trying to see if there is a way to be a bit nicer.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by dmnieto** [comment]
@mertalev I'd probably need your help to get this something akin to a functional state.

Attached the Dockerfile

[Dockerfile.txt](https://github.com/immich-app/immich/files/14319726/Dockerfile.txt)

**Comment by mertalev** [comment]
It looks like there is a prebuilt wheel for it [distributed by AMD](https://docs.amd.com/projects/radeon/en/latest/docs/install/install-onnx.html), but you're right that it supports 3.10 and not 3.11. This is fine - OpenVINO is in the same camp and that image uses 3.10 as a result. I would prefer this to avoid needing to build onnxruntime ourselves.

**Comment by dmnieto** [comment]
I’d need to see how to use the 3.10… in any case we’d need to wait until onnxruntime merges my pull request to fix the convolution bug https://github.com/microsoft/onnxruntime/pull/19550On Feb 17, 2024, at 13:29, Mert ***@***.***> wrote:﻿
It looks like there is a prebuilt wheel for it distributed by AMD, but you're right that it supports 3.10 and not 3.11. This is fine - OpenVINO is in the same camp and that image uses 3.10 as a result. I would prefer this to avoid needing to build onnxruntime ourselves.

**Reply by mertalev** [reply]
It would just mean using the `python:3.10-bookworm` image for ROCm

```dockerfile
FROM python:3.10-bookworm@sha256:b54e76c629a98430ac9c92e4f6bddeb672396a895b44a85022d12ee2f7239144 as builder-rocm
...
FROM builder-rocm as prod-rocm
```

**Reply by mertalev** [reply]
The other dependencies like `half` would also need to be installed in the prod image.

**Comment by dmnieto** [comment]
I am going to try to build a image with the python-3.10 and the publicly
available runtime (when the change submits we can get it from the
nightlies).

Do you have any suggestion on how to modify the poetry config to install a
local package? right now I do something dirty like loading the venv and
calling pip uninstall/pit install

**Reply by mertalev** [reply]
You can add it like this:
```toml
[tool.poetry.group.rocm]
optional = true

[tool.poetry.group.rocm.dependencies]
onnxruntime-rocm = {url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.0.2/onnxruntime_rocm-inference-1.17.0-cp310-cp310-linux_x86_64.whl"}
```
I actually tried to add it by adding the ROCm repo as a source, but this didn't work. It would have looked like this:
```toml
[tool.poetry.group.rocm]
optional = true

[tool.poetry.group.rocm.dependencies]
onnxruntime-rocm = {version = "^1.17.0", source = "rocm"}

[[tool.poetry.source]]
name = "rocm"
url = "https://repo.radeon.com/rocm/manylinux/rocm-rel-6.0.2"
priority = "explicit"
```
