### DISCUSSION TITLE
CUDA device is not detected

### DISCUSSION THREAD

**Discussion by owerrride** [immich-app/immich#7200] [Q&A]
### The bug

Immich cannot work with a video card. I completed all the requirements according to the instructions but still ran into a problem.

1. NVIDIA-SMI 535.154.05           
Driver Version: 535.154.05  
CUDA Version: 12.2 

2. **nvcc --version**
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

3. **nvidia-container-toolkit --version**
NVIDIA Container Runtime Hook version 1.14.5
commit: 9ea336070134e612145d342e495f2fc616aab063

[ML container logs.txt](https://github.com/immich-app/immich/files/14330662/ML.container.logs.txt)
[microservices logs.txt](https://github.com/immich-app/immich/files/14330678/microservices.logs.txt)
[server logs.txt](https://github.com/immich-app/immich/files/14330707/server.logs.txt)

### The OS that Immich Server is running on

 Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-94-generic x86_64)

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.94.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml 
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:

```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/toshiba/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=*****************
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
When I start transcoding, I see that everything happens on the processor, instead of the video card.
```

**Comment by tastelessjolt** [comment]
I'm also facing the same issue, it seems like docker with `capabilities` having only `gpu` passes the CUDA runtime + GPU into docker, but when other `capabilities` like `compute` and `video` are added, `capabilities: [compute, video, gpu]`, it doesn't pass.
But I don't see any errors in the docker daemon logs. 

It seems to be a docker issue. 

Simple Reproduction of not working `docker-compose.yml`: 

```yaml
services:
  test:
    image: nvidia/cuda:12.3.1-base-ubuntu20.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [compute, video, gpu]
```

```console
$ docker compose up
[+] Running 1/1
 ✔ Container gpu-test-test-1  Recreated                                                                                                                                                                     0.1s
Attaching to test-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "nvidia-smi": executable file not found in $PATH: unknown
```

And a working `docker-compose.yml`:

```yaml
services:
  test:
    image: nvidia/cuda:12.3.1-base-ubuntu20.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

```console
$ docker compose up
[+] Running 1/1
 ✔ Container gpu-test-test-1  Recreated                                                                                                                                                                     0.1s
Attaching to test-1
test-1  | Wed Feb 21 16:47:11 2024
test-1  | +---------------------------------------------------------------------------------------+
test-1  | | NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
test-1  | |-----------------------------------------+----------------------+----------------------+
test-1  | | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
test-1  | | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
test-1  | |                                         |                      |               MIG M. |
test-1  | |=========================================+======================+======================|
test-1  | |   0  NVIDIA GeForce GTX 950M        Off | 00000000:01:00.0 Off |                  N/A |
test-1  | | N/A   55C    P8              N/A / 200W |     76MiB /  4096MiB |      0%      Default |
test-1  | |                                         |                      |                  N/A |
test-1  | +-----------------------------------------+----------------------+----------------------+
test-1  |
test-1  | +---------------------------------------------------------------------------------------+
test-1  | | Processes:                                                                            |
test-1  | |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
test-1  | |        ID   ID                                                             Usage      |
test-1  | |=======================================================================================|
test-1  | +---------------------------------------------------------------------------------------+
test-1 exited with code 0
```

**Reply by tastelessjolt** [reply]
Sorry, on further inspection, it seems like regardless, `python -c "import onnxruntime as ort;print(ort.get_device())"` does show that the GPU is detected inside the `immich-machine-learning` container.  I'm not sure what the issue is. Might be related to the CUDA version or GPU compatibility. 
**Host CUDA version**: 12.3 
**NVIDIA driver version**: 545.29.06 
**GPU**: NVIDIA GeForce GTX 950M

**Reply by amatheo** [reply]
For me running `python -c "import onnxruntime as ort;print(ort.get_device())"` return `CPU` while the nvidia/cuda with nvidia-smi works fine. Spinnin up a hashcat docker with gpu benchmarked all fine.
Changing the capabilities of the devices didn't change anything

Host CUDA version: 12.4
NVIDIA driver version: 551.23
GPU: NVIDIA GeForce RTX 3080

**Reply by FoxxMD** [reply]
I'm experiencing the same issue, also on a docker setup. I pass my nvidia GPU to many other containers without an issue. Also have no issue with HW transcoding on the microservers container using the same `deploy` configuration. Running `nvidia-smi` in `immich-machine-learning` also shows my GPU but "Available Providers" only shows CPUExecution and the above python command also shows CPU only when all capabilities are enabled.

EDIT: **Fixed it (mostly)**

It wasn't clear from documentation but the machine learning image **needs** to use a vendor specific tag, unlike the other images, and this is what I was missing. 

Changing 
* from `ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}` 
* to `ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda` (using `-cuda` suffixed-tag)

resolved Available Providers missing my gpu as a provider. I haven't verified the `capabilities` bug but using the right tag with the "gpu only" capabilities is now working correctly for me.

**Reply by just5ky** [reply]
Can confirm @tastelessjolt statement.
Seeing the same issue here, passing all 3 `compute, video, gpu` doesn't work, but only passing `gpu` seems to be working.


```yml
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    networks:
      - immich
      - proxy
    ports:
      - 2283:3001
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - $PICTURES:/mnt/media/:ro
    env_file:
      - .env
    depends_on:
      - immich_redis
      - immich_postgres
    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: Host(`immich.$DOMAINNAME`)
      traefik.http.services.immich.loadbalancer.server.port: 3001
      traefik.http.routers.immich.entryPoints: https

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    networks:
      - immich
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - $PICTURES:/mnt/media/:ro
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                #- compute
                #- video
    depends_on:
      - immich_redis
      - immich_postgres


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    restart: unless-stopped
    networks:
      - immich
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                #- compute
                #- video

  immich_redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:alpine
    networks:
      - immich
    restart: unless-stopped

  immich_postgres:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
````

### Result of python command 
```bash
root@Galax:~# docker exec -it immich_machine_learning python -c "import onnxruntime as ort;print(ort.get_device())"
GPU
root@Galax:~#
```

### `nvtop` is reporting encoding + machine learning
![image](https://github.com/immich-app/immich/assets/71321862/cb34cb62-382d-4f13-86a1-ab5653bbc820)
 
### Something is still pinning my CPU to 100% while indexing, my guess is that it's jpeg/thumbnail extraction.
![image](https://github.com/immich-app/immich/assets/71321862/82b75937-9f8c-4197-b41f-f1baf591e378)

**Reply by romonwafa** [reply]
Can confirm here as well. My GTX 1080 was recognized in the container after removing ```compute``` and ```video```, only leaving ```gpu```.

The test with the ```nvidia/cuda:12.3.1-base-ubuntu20.04``` image also yielded the same results for me.

**Comment by maicss** [comment]
```
docker exec -it immich_machine_learning python -c "import onnxruntime as ort;print(ort.get_device())"
GPU
```
```
cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
nvidia-smi 
Mon Apr  1 19:53:47 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.67                 Driver Version: 550.67         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 960         Off |   00000000:01:00.0 Off |                  N/A |
| 20%   34C    P8             16W /  132W |       2MiB /   2048MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                   
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```
```
nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.15.0-rc.4
commit: 1ddc859700c0d698f7f155fdbf7ae6f77ea0c1f5
```
```
# nvtop
Device 0 [NVIDIA GeForce GTX 960] PCIe GEN 1@ 8x RX: 0.000 KiB/s TX: 0.000 KiB/s
 GPU 135MHz  MEM 405MHz  TEMP  39°C FAN  20% POW  16 / 132 W
 GPU[                                 0%] MEM[|                  0.061Gi/2.000Gi]
   ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
100│GPU0 %                                                                                                                        │
   │GPU0 mem%                                                                                                                     │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
 75│                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
 50│                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
 25│                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │                                                                                                                              │
   │──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
  0│──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────│
   └63s───────────────────────────47s─────────────────────────────31s────────────────────────────15s────────────────────────────0s┘
    PID USER DEV     TYPE  GPU        GPU MEM    CPU  HOST MEM Command                                                              









F2Setup   F6Sort    F9Kill    F10Quit    F12Save Config                                                                             
```

```yml
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_LOCATION}:/mnt/catImages:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_LOCATION}:/mnt/catImages:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    runtime: nvidia
    # devices:
    #   - /dev/dri:/dev/dri
    depends_on:
      - redis
      - database
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
      # service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - redis-data:/data

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  pgdata:
  model-cache:
  redis-data:
```

```
# micro service log
[Nest] 7  - 04/01/2024, 12:19:10 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset b5f9d2c1-e86b-4a78-ba10-7ff52788ff36
[Nest] 7  - 04/01/2024, 12:19:10 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset f3ef5429-ec69-4033-b683-d035b06aa947
[Nest] 7  - 04/01/2024, 12:19:10 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset c78da916-fe2f-4509-bf55-4ed6a6e8b068
[Nest] 7  - 04/01/2024, 12:19:10 PM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
[Nest] 7  - 04/01/2024, 12:19:10 PM   ERROR [JobService] Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:23:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:257:23)
    at async /usr/src/app/dist/services/job.service.js:147:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 04/01/2024, 12:19:10 PM   ERROR [JobService] Object:
{
  "id": "bb5f1cae-09e7-44d3-a9ab-1d75bdf29764",
  "source": "upload"
}
[Nest] 7  - 04/01/2024, 12:19:10 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset ea9d089b-384e-43ef-add5-7b13eeec5b47
[Nest] 7  - 04/01/2024, 12:19:10 PM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset 0d1423b1-d3a4-41a7-973b-952d7d15b853
```

```
# machine learning log
[04/01/24 12:20:56] INFO     Loading facial recognition model 'buffalo_l' to    
                             memory                                             
2024-04-01 12:20:56.647716693 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 30010, index: 6, mask: {11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 999: unknown error ; GPU=-263739048 ; hostname=1e45e2c70387 ; file=/onnxruntime_src/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=245 ; expr=cudaSetDevice(info_.device_id); 
 when using ['CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-04-01 12:20:56.653850525 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 30017, index: 6, mask: {11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
[04/01/24 12:20:56] ERROR    Exception in ASGI application                      
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:41 │
                             │ 9 in __init__                                   │
                             │                                                 │
                             │    416 │   │   disabled_optimizers = kwargs["di │
                             │        kwargs else None                         │
                             │    417 │   │                                    │
                             │    418 │   │   try:                             │
                             │ ❱  419 │   │   │   self._create_inference_sessi │
                             │        disabled_optimizers)                     │
                             │    420 │   │   except (ValueError, RuntimeError │
                             │    421 │   │   │   if self._enable_fallback:    │
                             │    422 │   │   │   │   try:                     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:48 │
                             │ 3 in _create_inference_session                  │
                             │                                                 │
                             │    480 │   │   │   disabled_optimizers = set(di │
                             │    481 │   │                                    │
                             │    482 │   │   # initialize the C++ InferenceSe │
                             │ ❱  483 │   │   sess.initialize_session(provider │
                             │    484 │   │                                    │
                             │    485 │   │   self._sess = sess                │
                             │    486 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:121 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:114 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             999: unknown error ; GPU=-263739048 ;              
                             hostname=1e45e2c70387 ;                            
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=245 ;         
                             expr=cudaSetDevice(info_.device_id);               
                                                                                
                                                                                
                                                                                
                             The above exception was the direct cause of the    
                             following exception:                               
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:116 in predict             │
                             │                                                 │
                             │   113 │   except orjson.JSONDecodeError:        │
                             │   114 │   │   raise HTTPException(400, f"Invali │
                             │   115 │                                         │
                             │ ❱ 116 │   model = await load(await model_cache. │
                             │       ttl=settings.model_ttl, **kwargs))        │
                             │   117 │   model.configure(**kwargs)             │
                             │   118 │   outputs = await run(model.predict, in │
                             │   119 │   return ORJSONResponse(outputs)        │
                             │                                                 │
                             │ /usr/src/app/main.py:137 in load                │
                             │                                                 │
                             │   134 │   │   │   model.load()                  │
                             │   135 │                                         │
                             │   136 │   try:                                  │
                             │ ❱ 137 │   │   await run(_load, model)           │
                             │   138 │   │   return model                      │
                             │   139 │   except (OSError, InvalidProtobuf, Bad │
                             │   140 │   │   log.warning(                      │
                             │                                                 │
                             │ /usr/src/app/main.py:125 in run                 │
                             │                                                 │
                             │   122 async def run(func: Callable[..., Any], i │
                             │   123 │   if thread_pool is None:               │
                             │   124 │   │   return func(inputs)               │
                             │ ❱ 125 │   return await asyncio.get_running_loop │
                             │   126                                           │
                             │   127                                           │
                             │   128 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:134 in _load               │
                             │                                                 │
                             │   131 │                                         │
                             │   132 │   def _load(model: InferenceModel) -> N │
                             │   133 │   │   with lock:                        │
                             │ ❱ 134 │   │   │   model.load()                  │
                             │   135 │                                         │
                             │   136 │   try:                                  │
                             │   137 │   │   await run(_load, model)           │
                             │                                                 │
                             │ /usr/src/app/models/base.py:52 in load          │
                             │                                                 │
                             │    49 │   │   │   return                        │
                             │    50 │   │   self.download()                   │
                             │    51 │   │   log.info(f"Loading {self.model_ty │
                             │       to memory")                               │
                             │ ❱  52 │   │   self._load()                      │
                             │    53 │   │   self.loaded = True                │
                             │    54 │                                         │
                             │    55 │   def predict(self, inputs: Any, **mode │
                             │                                                 │
                             │ /usr/src/app/models/facial_recognition.py:30 in │
                             │ _load                                           │
                             │                                                 │
                             │   27 │   │   super().__init__(clean_name(model_ │
                             │   28 │                                          │
                             │   29 │   def _load(self) -> None:               │
                             │ ❱ 30 │   │   self.det_model = RetinaFace(sessio │
                             │   31 │   │   self.rec_model = ArcFaceONNX(      │
                             │   32 │   │   │   self.rec_file.with_suffix(".on │
                             │   33 │   │   │   session=self._make_session(sel │
                             │                                                 │
                             │ /usr/src/app/models/base.py:117 in              │
                             │ _make_session                                   │
                             │                                                 │
                             │   114 │   │   │   case ".armnn":                │
                             │   115 │   │   │   │   session = AnnSession(mode │
                             │   116 │   │   │   case ".onnx":                 │
                             │ ❱ 117 │   │   │   │   session = ort.InferenceSe │
                             │   118 │   │   │   │   │   model_path.as_posix() │
                             │   119 │   │   │   │   │   sess_options=self.ses │
                             │   120 │   │   │   │   │   providers=self.provid │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:43 │
                             │ 2 in __init__                                   │
                             │                                                 │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │    431 │   │   │   │   except Exception as fall │
                             │ ❱  432 │   │   │   │   │   raise fallback_error │
                             │    433 │   │   │   # Fallback is disabled. Rais │
                             │    434 │   │   │   raise e                      │
                             │    435                                          │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:42 │
                             │ 7 in __init__                                   │
                             │                                                 │
                             │    424 │   │   │   │   │   print(f"EP Error {e} │
                             │    425 │   │   │   │   │   print(f"Falling back │
                             │    426 │   │   │   │   │   print("************* │
                             │ ❱  427 │   │   │   │   │   self._create_inferen │
                             │    428 │   │   │   │   │   # Fallback only once │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:48 │
                             │ 3 in _create_inference_session                  │
                             │                                                 │
                             │    480 │   │   │   disabled_optimizers = set(di │
                             │    481 │   │                                    │
                             │    482 │   │   # initialize the C++ InferenceSe │
                             │ ❱  483 │   │   sess.initialize_session(provider │
                             │    484 │   │                                    │
                             │    485 │   │   self._sess = sess                │
                             │    486 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:121 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:114 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             999: unknown error ; GPU=-263739048 ;              
                             hostname=1e45e2c70387 ;                            
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=245 ;         
                             expr=cudaSetDevice(info_.device_id); 
```

Any suggestion? Thanks!
