### DISCUSSION TITLE
Can not upload certain video file

### DISCUSSION THREAD

**Discussion by drmcachr** [immich-app/immich#7377] [Q&A]
### The bug

I have 3 of my videos can not upload to immich, when I upload manually, it failed, I don't know where to find log files, but postreg has lot of error like this:

2024-02-23 13:24:29.982 UTC [7492] LOG:  could not receive data from client: Connection reset by peer
2024-02-23 13:20:42.169 UTC [7438] STATEMENT:  INSERT INTO "assets"("id", "deviceAssetId", "ownerId", "libraryId", "deviceId", "type", "originalPath", "resizePath", "webpPath", "thumbhash", "encodedVideoPath", "createdAt", "updatedAt", "deletedAt", "fileCreatedAt", "localDateTime", "fileModifiedAt", "isFavorite", "isArchived", "isExternal", "isReadOnly", "isOffline", "checksum", "duration", "isVisible", "livePhotoVideoId", "originalFileName", "sidecarPath", "stackId") VALUES (DEFAULT, $1, $2, $3, $4, $5, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7, $8, $9, DEFAULT, DEFAULT, $10, $11, DEFAULT, $12, DEFAULT, DEFAULT, DEFAULT, $13, $14, DEFAULT) RETURNING "id", "webpPath", "encodedVideoPath", "createdAt", "updatedAt", "deletedAt", "isFavorite", "isArchived", "isExternal", "isReadOnly", "isOffline", "isVisible"
2024-02-23 13:20:42.169 UTC [7438] DETAIL:  Key ("ownerId", "libraryId", checksum)=(ff0225e3-6581-4634-a551-f3a32f6035b3, dfc019ff-3647-4bb7-a7b0-ca9f24e21942, \x7317121a78790cd5732584b164da319ff50868a4) already exists.
2024-02-23 13:20:42.169 UTC [7438] ERROR:  duplicate key value violates unique constraint "UQ_assets_owner_library_checksum"
2024-02-23 13:20:42.167 UTC [7460] STATEMENT:  INSERT INTO "assets"("id", "deviceAssetId", "ownerId", "libraryId", "deviceId", "type", "originalPath", "resizePath", "webpPath", "thumbhash", "encodedVideoPath", "createdAt", "updatedAt", "deletedAt", "fileCreatedAt", "localDateTime", "fileModifiedAt", "isFavorite", "isArchived", "isExternal", "isReadOnly", "isOffline", "checksum", "duration", "isVisible", "livePhotoVideoId", "originalFileName", "sidecarPath", "stackId") VALUES (DEFAULT, $1, $2, $3, $4, $5, $6, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $7, $8, $9, DEFAULT, DEFAULT, $10, $11, DEFAULT, $12, DEFAULT, DEFAULT, DEFAULT, $13, $14, DEFAULT) RETURNING "id", "webpPath", "encodedVideoPath", "createdAt", "updatedAt", "deletedAt", "isFavorite", "isArchived", "isExternal", "isReadOnly", "isOffline", "isVisible"

and I found there are 7 offline path in repair page, all of them are video files, I don't know how to delete them.

### The OS that Immich Server is running on

Asustor ADM 4.26

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.nju.edu.cn/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/Media/Photos:/share/Media/Photos:ro
      - /share/Media/Photos:/share/Media/Videos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.nju.edu.cn/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/Media/Photos:/share/Media/Photos:ro
      - /share/Media/Photos:/share/Media/Videos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning

    image: ghcr.nju.edu.cn/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache

    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.nju.edu.cn/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: docker.nju.edu.cn/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /share/Docker/Immich/pgdata
  model-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /share/Docker/Immich/model-cache
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/Docker/Immich/Backup
IMMICH_VERSION=release
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.upload file
2.failed
3.
...
```
