### DISCUSSION TITLE
pgvecto.rs only supports 0.2.0, ships with 0.1.11

### DISCUSSION THREAD

**Discussion by Torstein-Eide** [immich-app/immich#7508] [Q&A] [answered]
### The bug

From a clear docker installation, without any old databases.

The following docker service fail to start:

* immich_microservices exited with code 0                                                     
* immich_server exited with code 0                                                            
* immich_microservices exited with code 0



### The OS that Immich Server is running on

debain 12, docker 25

### Version of Immich Server

1.9.6

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
```


### Your .env content

```Shell
UPLOAD_LOCATION=/volum1/@docker/immich/upload_files

IMMICH_VERSION=release
DB_PASSWORD=${Redacted }
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```


### Reproduction steps

```bash
1. Standard docker install
2. Try and start ´docker compose up´
...
```


### Additional information

Log for all three service

````node
 /usr/src/app/dist/domain/database/database.service.js:137
            throw new Error(`                                                                                                                                 
                  ^                                                                                                                                           
                                                                                                                                                              
Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.
                                                                                                                                                              
        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.

        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/usr/src/app/dist/domain/database/database.service.js:137:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/domain/database/database.service.js:39:13                                                                                      
    at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 
````
