### DISCUSSION TITLE
Reverse geocaching returns null

### DISCUSSION THREAD

**Discussion by utrack** [immich-app/immich#7556] [Q&A]
### The bug

Hi team!

I'm using the latest release v1.97.0 via Docker Compose - except for the ML image, which is main-openvino.
My Compose (from v1.95.1) is slightly modified, I'm running containers as a non-root user (no issues with the mounts' permissions, I've fixed them).

I've realized that the map view is missing a lot of photos, so I've started the 'extract metadata' job.
My logs are full of these messages:

```
immich_microservices     | [Nest] 7  - 02/29/2024, 2:38:30 PM    WARN [MetadataRepository] Response from database for reverse geocoding latitude: 63.789032, longitude: -18.0456314 was null
```

It feels like a timeout is happening, since every such request takes a couple of minutes to complete if I look at the logs.
How can I debug that? :)

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.9.7

### Version of Immich Mobile App

<not needed>

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /opt/docked/immich/passwd:/etc/passwd
    env_file:
      - .env
    ports:
      - 2283:3001
    group_add:
      - 989
      - 985
    user: "1004:1004"
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /opt/docked/immich/passwd:/etc/passwd
    user: "1004:1004"
    group_add:
      - 989
      - 985
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    #image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    image: ghcr.io/immich-app/immich-machine-learning:main-openvino
      #user: "1004:1004"
      #group_add:
      #- 989
      #- 985
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /opt/docked/immich/passwd:/etc/passwd
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
      #user: "1004:1004"
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/hdd/immich/pgdb:/var/lib/postgresql/data
    restart: always
    user: "1004:1004"

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/hdd/immich
PUID=

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<secret :) >

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
PUID=1004
PGID=1001
LOG_LEVEL=debug
```

### Reproduction steps

```bash
1. Try to run the Extract Metadata job
2. Wait for the logs for a couple of minutes
```

### Additional information

---
