### DISCUSSION TITLE
What to exclude from Synology Photos (photo) folder | External library

### DISCUSSION THREAD

**Discussion by Gitonthegrid** [immich-app/immich#7573] [General]
Dear all, 

I have setup my Immich with my Synology NAS. 
I point towards the default /photo folder that Synology creates. The only problem is that Synology makes there own thumbnails and downsized videos etc. So that are all separated files

What do you guys exclude from the external library, so that those file wont get imported?
I have excluded the following, but still see the files. The normal "rescan" didnt work, and I still see the SYNO files.

- **/SYNOPHOTO_THUMB 
- **/@eaDir/**
- **/SYNOPHOTO_FILM_H264

**Comment by 94tiger** [comment]
`**/@eaDir/**`
In my case, adding the above to the exclusion pattern worked fine :smiley_cat:

**Reply by TheLinuxGuy** [reply]
is this the only exclusion rule you are using? or this setting in addition to OP?

**Reply by huydinh282** [reply]
Not OP, but I'm only using **/@eaDir/**
make sure to do a remove offline file afterwards

**Comment by CarlK10** [comment]
@Gitonthegrid I am trying to get Immich on my Synology to work with the photo folder and can't get Immich to scan that folder. I have set up the external library path successfully and have the upload path set to /volume1/photo as well and scanning does nothing.  Did you have any issues?  Could you share your YAML and ENV?  I followed what appears to be the only Syno youtube setup video available and there are a few differences in the YAML volumes listed in his video from a few months ago and the current download.  I have asked in the Reddit thread with all my info but have not received any replies.

Any help would be appreciated.

**Reply by ridv** [reply]
```yaml
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/homes/<user>/Photos:/opt/external-libraries/<user>:ro
...
```

Then I added an external library under administration `/opt/external-libraries/<user>`
I also made sure to add `**/@eaDir/**` as an exclusion pattern.
Finally, I hit scan. It took a bit for anything to show up but just be patient and let your synology do its thing.
