### DISCUSSION TITLE
Upgrade v1.96.0 to v1.97.0 will not start

### DISCUSSION THREAD

**Discussion by ThRPctmylSgltwH** [immich-app/immich#7579] [Q&A]
### The bug

v1.97.0 will not start. Using local IP:Port error is "refused to connect". Rollback to v1.96.0 is successful without errors. It is reproducible if I upgrade again and rollback works each time.

**Machine learning log** - Error: Unable to configure handler 'console'

**Microservices error**
    at Module._extensions..json (node:internal/modules/cjs/loader:1453:39)
SyntaxError: /usr/src/app/node_modules/mime-db/db.json: Unexpected end of JSON input
Node.js v20.11.1
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.<anonymous> (/usr/src/app/node_modules/mime-db/index.js:12:18)
    at require (node:internal/modules/helpers:176:18)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at parse (<anonymous>)
    ^
node:internal/modules/cjs/loader:1456
    throw err;

**Postgress** - ready to accept connections without error

**Redis log** these lines are repeated
1:M 02 Mar 2024 15:22:18.200 * Background saving terminated with success
203:C 02 Mar 2024 15:22:18.104 * RDB: 1 MB of memory used by copy-on-write
203:C 02 Mar 2024 15:22:18.103 * DB saved on disk
1:M 02 Mar 2024 15:22:18.100 * Background saving started by pid 203
1:M 02 Mar 2024 15:22:18.099 * 100 changes in 300 seconds. Saving...
1:M 02 Mar 2024 15:17:17.125 * Background saving terminated with success

**Server log**
Node.js v20.11.1
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.<anonymous> (/usr/src/app/node_modules/mime-db/index.js:12:18)
    at require (node:internal/modules/helpers:176:18)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module._extensions..json (node:internal/modules/cjs/loader:1453:39)
    at parse (<anonymous>)
SyntaxError: /usr/src/app/node_modules/mime-db/db.json: Unexpected end of JSON input
node:internal/modules/cjs/loader:1456
    throw err;
    ^

### The OS that Immich Server is running on

PI OS

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

v1.97.0 build.125

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PGDATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/pi/3TBData1/Files/AppData/Config/immich
EXTERNAL_PATH=/media/pi/3TBData1/media/Pictures
PGDATA_LOCATION=/media/pi/3TBData1/Files/AppData/Databases/immich
IMMICH_VERSION=v1.97.0
DB_PASSWORD=xxx
DB_HOSTNAME=xxx
DB_USERNAME=xxx
DB_DATABASE_NAME=xxx
REDIS_HOSTNAME=xxx
```

### Reproduction steps

```bash
1.upgrade to v1.97.0 from v1.97.0
2.can no longer connect
3.
...
```
