### DISCUSSION TITLE
Archive and download shortcuts don't work

### DISCUSSION THREAD

**Discussion by lyz-code** [immich-app/immich#7725] [Q&A] [answered]
### The bug

I've tried to use `a` and `<arrow up>` to archive a photo and `d` and `<arrow up>` (again??) to download it and none worked.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.98.0

### Version of Immich Mobile App

None

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
version: "3.3"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - upload-location:/usr/src/app/upload
      - external-photos:/usr/src/app/external/photos
      - external-videos:/usr/src/app/external/videos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    # ports:
    #   - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - upload-location:/usr/src/app/upload
      - external-photos:/usr/src/app/external/photos
      - external-videos:/usr/src/app/external/videos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  external-photos:
  external-videos:
  upload-location:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

#
# WARNING: Make sure to update the docker-compose.yml of the current release if you change the IMMICH_VERSION
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
# WARNING: Don't use watchtower until the program is stable enough
# https://immich.app/docs/install/docker-compose#step-4---upgrading
#
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# See all versions at https://github.com/immich-app/immich/pkgs/container/immich-server/versions?filters%5Bversion_type%5D=tagged
IMMICH_VERSION=v1.98.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=Redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=Redacted
DB_DATABASE_NAME=Redacted

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open a photo in an album in the web browser
2. Press a, d, arrow up 
3. Nothing happens
...
```
