### DISCUSSION TITLE
How change Immich to localhost

### DISCUSSION THREAD

**Discussion by BenjaminCz0101** [immich-app/immich#7761] [Q&A]
Hi
How can I change the Immich Docker or the IP address (Immich Server and Immich Learning machine and Redis) to localhost so that I can then set it up as a Nginx proxy?

This is my current Nginx config but it only works to a limited extent because I can always access it via http.

server {

    listen 80;

    server_name 192.168.178.16;
	
	
    client_max_body_size 50000M;

    root /usr/share/nginx;

    access_log off;

    location /.well-known/acme-challenge/ { allow all; }

    location / { return 301 https://$host$request_uri; }

}

server {

    listen 443 http2 ssl;
    listen [::]:443 http2 ssl;

    server_name 192.168.178.xxx;
	
	client_max_body_size 50000M;

    ssl_certificate /opt/cert/immich.home.crt;
    ssl_certificate_key /opt/cert/immich.home.key;
    #ssl_dhparam /etc/ssl/certs/dhparam.pem;

    ########################################################################
    # from https://cipherli.st/                                            #
    # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html #
    ########################################################################

   

    ##################################
    # END https://cipherli.st/ BLOCK #
    ##################################

    root /usr/share/nginx/html;

    location / {
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP $remote_addr;
      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header        X-Forwarded-Proto $scheme;

      # Fix the “It appears that your reverse proxy set up is broken" error.
      proxy_pass          http://192.168.178.xxx:2283;
      proxy_read_timeout  90;

      # WebSocket support
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

    }

    error_page 404 /404.html;
    location = /404.html {
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {

    }
}

**Comment by mmomjian** [comment]
What do you mean "change it to localhost"? Please describe the problem you are having.

**Reply by BenjaminCz0101** [reply]
Hi, sorry! My problem is I have uploaded all photos and videos to Immich via Immich APP Mobile. If I take new photos, the app only uploads the photos with the Backup Background Worker if I only use http. So standard configuration 
http://192.168.178.xxx:2283/api

But I wanted to use https with a self-signed certificate. Everything works except for the automatic upload. He always wants to upload all the photos and then it fails. Something is configured incorrectly. I tried it with 
https://192.168.178.xxx/api
and
https://immich.home/api

I have Debian 12 and Immich Installed on Docker and Nginx Installed an Configuration on root not Docker.

Connection works Manual Upload Works.

Fotos to Upload:
![Screenshot_20240309_003759](https://github.com/immich-app/immich/assets/122832214/8e18d882-f0a3-4be5-b87b-5b4086cd7b2d)

Works with Standart http Connection:
![Screenshot_20240309_005250_One UI Home](https://github.com/immich-app/immich/assets/122832214/d935e15d-f3f2-4c7c-a957-963f7a3295c2)

Works NOT with https (nginx see Configuration on Top)
![Screenshot_20240309_003319](https://github.com/immich-app/immich/assets/122832214/da415181-ea63-43d8-9463-8c110d18827a)

**Comment by mmomjian** [comment]
Seems to be a duplicate of #5562? Is that your same issue?

**Reply by BenjaminCz0101** [reply]
Yes, exactly is there a solution?

**Reply by mmomjian** [reply]
I don't think there is at this moment. My best recommendation would be to get a domain name and get a real cert through LetsEncrypt. Unfortunately self signed certs can be very cumbersome especially on mobile devices.

**Reply by BenjaminCz0101** [reply]
OK, unfortunately I only run it locally, including DNS rewriting, and not publicly, which is why I use the self-signed certificate. Is there a solution known? Thanks for the feedback!

**Reply by mmomjian** [reply]
You can still run it locally with a real domain name. You just don't expose the ports to the internet. You can set the DNS just like you do for your internal domain name. But no, there is not a known solution and I suspect it's some very deeply underlying issue with the way Android handles self-signed certs, even when imported into the root.

**Reply by BenjaminCz0101** [reply]
OK, is there a guide somewhere on how to do this? I've already had a hard time setting it up like that. I have AdGuard and I have the DNS rewrite in there. Thank you!

**Reply by mmomjian** [reply]
You can start with something like Nginx Proxy Manager (NPM), it will automatically refresh the cert using LetsEncrypt. Then it can proxy the HTTPS traffic to Immich and you can just add the new domain name that you bought to Adguard Home.

Or, if you're only using it at home anyway, you can use HTTP :)

**Reply by BenjaminCz0101** [reply]
OK thanks!

**Reply by BenjaminCz0101** [reply]
Just one more question. If I were to do this via the Nginx Proxy Manager, I would also have to secure and harden the server on which the Nginx Proxy Manager is running, e.g. with fail2ban or CorwdSec or ? since it always updates the certificates?

**Reply by mmomjian** [reply]
I'm not 100% sure if NPM supports it, but you can get a cert from LEC without exposing the server to the internet at all. If you use Cloudflare (free) as your DNS server, it's as simple as this (redacted from my own setup). This uses the Cloudflare API to confirm ownership by adding a record to the DNS entries, instead of connecting directly to your server.

```
services:
  letsencrypt-cloudflare:
    container_name: letsencrypt-cloudflare
    hostname: letsencrypt-cloudflare
    restart: no
    image: certbot/dns-cloudflare

certonly --cert-name='cert_name_here' --dns-cloudflare-propagation-seconds 30 --non-interactive --agree-tos
        --email user@example.com --dns-cloudflare --dns-cloudflare-credentials /opt/cloudflare/credentials
        -d (url1) -d (*.url1) -d (url2) etc...
        --server https://acme-v02.api.letsencrypt.org/directory
    volumes:
      - '${lec}/cloudflare-credentials:/opt/cloudflare/credentials:ro'
      - '${lec}/container-data:/etc/letsencrypt'
      - '${lec}/container-logs:/var/log/letsencrypt'
      - '${lec}/var-lib:/var/lib/letsencrypt'
```
