### DISCUSSION TITLE
How do you go about docker compose upgrades?

### DISCUSSION THREAD

**Discussion by lisachev** [immich-app/immich#7862] [Q&A]
I'm following a general 'get notified of new version -> read through the release notes -> upgrade docker" path.
What I struggle with is the `docker-compose.yml` changes. I have a bunch of custom lines in the compose file such as labels for `traefik`, `volumes` definitions, `network`. What is the best way to upgrade without messing up the custom lines? I'm currently going through the yml manually, line-by-line, it hurts.

**Comment by bjeanes** [comment]
I define a `docker-compose.override.yml`, which Docker Compose will merge out of the box. This is how I configure traefik labels, for instance. Then, I just use the stock `docker-compose.yml` and download that from the release I'm upgrading too (and double check whether anything has changes I need to accommodate in my override).

**Comment by Benny-Git** [comment]
Same here. As an example, my `docker-compose.override.yml` looks like this:

```yaml
services:
  immich-server:
    volumes:
      # additional external library
      - /tank/fotos:/tank/fotos:ro
    networks:
      - immich
      - proxy
    labels:
      # Explicitly tell Traefik to expose this container
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.myowndomain.com`)"
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.docker.network=proxy"

  immich-machine-learning:
    networks:
      - immich

  redis:
    networks:
      - immich

  database:
    networks:
      - immich

networks:
  immich:
  proxy:
    external: true
```
