### DISCUSSION TITLE
User authentication NAS

### DISCUSSION THREAD

**Discussion by DJF3** [immich-app/immich#7912] [Q&A] [answered]
Team,
After reading (interesting) documents like [this](https://github.com/immich-app/immich/discussions/6912) I'm missing an important piece of information. 
GOAL: **mount a NAS share in Docker so Immich can use it as an external library.**

In all of the examples only the following config is shown:
```  
immich-server:
    volumes:
      - ${EXTERNAL_PATH}:/usr/src/app/external
```

 Questions: 
1. Should **EXTERNAL_PATH** be something like `//192.169.1.22/PICTURES/` ?
2. What _user credentials_ will be used to connect to the NAS? 

Tested
In docker-compose.yml:
```  
immich-server:
    volumes:
      - network_pictures:/usr/src/app/external:ro

... plus ...

volumes:
  pgdata:
  model-cache:
  network_pictures:
    driver_opts:
      type: cifs
      o: "username=immichdockeruser,password=******,vers=3.0"
      device: "//192.168.1.22/PICTURES/"

```
And in the external library configuration "add path" : `/usr/src/app/external`

Same result: yellow triangle with the text "Path does not exist"

This also resulted in the same

**Comment by DJF3** [comment]
One way that I got working _**a bit**_ is using NFS, but with manual configuration needed every time the docker image restarts.
When Immich is running I execute: 
       `docker exec -it --privileged immich_microservices /bin/bash`
to access the microservices container.
Then I create a folder and map the share using NFS.
```
mkdir /usr/src/app/mypics
mount -t nfs -o nfsvers=4 192.168.1.22:/volume1/PICTURES/ /usr/src/app/mypics
```
_**+ repeat for the immich_server container.**_

Now the drive is mapped but after restarting Immich this config is gone. 

*Ideally I want to accomplish the same through the docker-compose file.*

But the following config doesn't do it:


```
services:
  immich-server:
    container_name: immich_server
    volumes:
      - my_pics:/usr/src/app/mypics:ro

volumes:
  pgdata:
  model-cache:
  my_pics:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.22,nolock,soft,ro,nfsvers=4"
      device: ":/volume1/PICTURES"
```

Any ideas?
👍

**Comment by alternativesurfer** [comment]
What is your docker running on?

**Reply by DJF3** [reply]
Macbook M2 with the Docker app.

**Comment by Meliox** [comment]
I am using the following smb share, which works. Not that there should be a big difference, but maybe an alternative to try. 

External library must point to /mnt/Photos/

docker v 25.0.3

```
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - localLibrary:/mnt/Photos/      

# Remember to delete volumes in portainer prior making changes below - mounts are immutable
volumes:
  localLibrary:
    driver_opts:
      type: cifs
      device: //192.168.3.4/Photos
      o: addr=192.168.3.4,username=usr,password=psss,file_mode=0555,dir_mode=0555,vers=3.0
```

**Reply by DJF3** [reply]
`"External library must point to /mnt/Photos/"`

Could you also point them to "/usr/src/app/Photos" ?
You use the word "localLibrary" but that's just a name you assigned to that configuration right? It could also be "externalLibrary"?

After trying this it still doesn't work. It's so difficult because I haven't found a way to get debug logs for that particular part of the configuration. On the NAS side I don't see any logging, even after configuring the wrong password. 
I was unable to find any kind of mounting debug info. (debug level immich set to DEBUG)

**Comment by DJF3** [comment]
Right now I have Immich running on 2 platforms:
1. Macbook with Docker
2. Proxmox with Ubuntu / Docker

The following command:
`mount -t cifs //192.168.1.22/PICTURES/2005 /mnt/mypics2005 -o username=immichdockeruser,password=SECRET`
works..
#1. Macos: Working fine, even though it doesn't mount these based on the docker-compose.yml config.
#2. Ubuntu: the ever lasting error
```
mount: /mnt/mypics2005: permission denied.
       dmesg(1) may have more information after failed mount system call.
```

Feeling that I'm _SO CLOSE_ but not there yet.  :-)

**Comment by DJF3** [comment]
UPDATE:
What _seems_ to work now is the following config. Note that this is one of these scenarios where I may have changed so much that it's hard to say what exactly caused this scenario to work now :-) 

```
  my_naspics:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.22,nolock,ro
      device: ":/volume1/PICTURES/"
```
plus for both the _server and _microservices containers "`- my_naspics:/mnt/naspics`" under volumes.

**Comment by DJF3** [comment, marked as answer]
Let me just share what worked at the end - only showing the additions to the standard docker-compose.yml :
```
services:
  immich-server:
    volumes:
      - mypics:/usr/src/app/mypics:ro
  immich-microservices:
    volumes:
      - mypics:/usr/src/app/mypics:ro
volumes:
  mypics:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.122,nolock,soft,ro,nfsvers=4"
      device: ":/volume1/PICTURES"
```
**On the NAS:**
- Enable NFS services
- Configure PICTURES share with NFS rights: 192.168.1.22, READ_ONLY, "map all users to admin"


Cheers!
DJ
