### DISCUSSION TITLE
Machine learning face detection time out

### DISCUSSION THREAD

**Discussion by superkeyor** [immich-app/immich#8014] [Q&A] [answered]
### The bug

I had a lot of the following timeout errors for `immich_microservices`.

```
[Nest] 7  - 03/14/2024, 2:56:06 AM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request to "http://immich-machine-learning:3003" failed with HeadersTimeoutError: Headers Timeout Error
[Nest] 7  - 03/14/2024, 2:56:06 AM   ERROR [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with HeadersTimeoutError: Headers Timeout Error
    at /usr/src/app/dist/infra/repositories/machine-learning.repository.js:18:19
    at async MachineLearningRepository.predict (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:17:21)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/domain/person/person.service.js:248:23)
    at async /usr/src/app/dist/domain/job/job.service.js:137:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 03/14/2024, 2:56:06 AM   ERROR [JobService] Object:
{
  "id": "9b72ec6f-c2df-462e-af0b-2e54b80d34fe"
}
```

But the log for `immich_machine_learning` seemed fine.

```
[03/14/24 02:42:46] INFO     Starting gunicorn 21.2.0
[03/14/24 02:42:46] INFO     Listening at: http://0.0.0.0:3003 (9)
[03/14/24 02:42:46] INFO     Using worker: app.config.CustomUvicornWorker
[03/14/24 02:42:47] INFO     Booting worker with pid: 10
[03/14/24 02:44:47] CRITICAL WORKER TIMEOUT (pid:10)
[03/14/24 02:44:48] ERROR    Worker (pid:10) was sent SIGKILL! Perhaps out of
                             memory?
[03/14/24 02:44:48] INFO     Booting worker with pid: 12
[03/14/24 02:45:32] INFO     Started server process [12]
[03/14/24 02:45:32] INFO     Waiting for application startup.
[03/14/24 02:45:32] INFO     Created in-memory cache with unloading after 300s
                             of inactivity.
[03/14/24 02:45:32] INFO     Initialized request thread pool with 1 threads.
[03/14/24 02:45:32] INFO     Application startup complete.
[03/14/24 02:48:14] INFO     Setting 'buffalo_l' execution providers to
                             ['CPUExecutionProvider'], in descending order of
                             preference
[03/14/24 02:48:14] INFO     Loading facial recognition model 'buffalo_l' to
                             memory
```

### The OS that Immich Server is running on

Ubuntu 20

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
        container_name: immich_server
        image: ghcr.io/immich-app/immich-server:v1.98.2
        command: [ "start.sh", "immich" ]
        volumes:
            - "/mnt/Media/Photo/Upload:/usr/src/app/upload"
            - "/mnt/Media/Photo/Album:/usr/src/app/external"   # https://immich.app/docs/guides/external-library/
            - /etc/localtime:/etc/localtime:ro
        environment:
            DB_DATABASE_NAME: immich
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_HOSTNAME: immich-postgres
            DB_PORT: 5432
            REDIS_HOSTNAME: immich-redis
            REDIS_PORT: 6379
        ports:
            - "2283:3001"
        depends_on:
            - immich-redis
            - immich-postgres
        restart: always

    immich-microservices:
        container_name: immich_microservices
        image: ghcr.io/immich-app/immich-server:v1.98.2
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
        #   file: hwaccel.transcoding.yml
        #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
        command: [ "start.sh", "microservices" ]
        volumes:
            - "/mnt/Media/Photo/Upload:/usr/src/app/upload"
            - "/mnt/Media/Photo/Album:/usr/src/app/external"
            - /etc/localtime:/etc/localtime:ro
        environment:
            DB_DATABASE_NAME: immich
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_HOSTNAME: immich-postgres
            DB_PORT: 5432
            REDIS_HOSTNAME: immich-redis
            REDIS_PORT: 6379
        depends_on:
            - immich-redis
            - immich-postgres
        restart: always

    immich-machine-learning:
        container_name: immich_machine_learning
        # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
        # Example tag: v1.98.2-cuda
        image: ghcr.io/immich-app/immich-machine-learning:v1.98.2
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #   file: hwaccel.ml.yml
        #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
        volumes:
            - "/mnt/Media/Photo/Upload/ml:/cache"
        environment:
            DB_DATABASE_NAME: immich
            DB_USERNAME: postgres
            DB_PASSWORD: password
            DB_HOSTNAME: immich-postgres
            DB_PORT: 5432
            REDIS_HOSTNAME: immich-redis
            REDIS_PORT: 6379
        restart: always

    immich-postgres:
        container_name: immich_postgres
        image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
        environment:
            POSTGRES_DB: immich
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - "/data/immich/pgdata:/var/lib/postgresql/data"
        restart: always

    immich-redis:
        container_name: immich_redis
        image: registry.hub.docker.com/library/redis:6.2-alpine
        restart: always
```

### Your .env content

```Shell
I did not use .env. Instead, I merge the info into docker-compose.yml
```

### Reproduction steps

```bash
1.Just run the docker compose
2.Start the face detection job
```

### Additional information

The thumbnail generation, video transcoding worked fine.
