### DISCUSSION TITLE
Always get `CPUExecutionProvider` in immich_machine_learning container

### DISCUSSION THREAD

**Discussion by Triple-Z** [immich-app/immich#8106] [Q&A] [answered]
First, thank you for your great photo management app!

Here is my PC:
- i7-4720HQ
- NVIDIA GeForce GTX 970M (Compute Capability 5.2)
- Windows 11
- Ubuntu 22.04 with WSL2
- Installed CUDA 11.8 in WSL2

And my docker-compose file:
```yaml
version: '3'

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

volumes:
  model-cache:
```

However, I always get `CPUExecutionProvider` in the container log like this following image.

![image](https://github.com/immich-app/immich/assets/16285716/f686b8ab-2c83-4f1c-b102-7b1fa7efdd07)

How can I get GPU acceleration for machine learning container? Which log or which test should I look in?
