### DISCUSSION TITLE
After some time, consistently get 5xx errors with blank page

### DISCUSSION THREAD

**Discussion by MichaelBui** [immich-app/immich#8181] [Q&A]
### The bug

After upgrading from 1.88.2 to 1.98.2, I noticed that it started getting 5xx errors consistently after some time.
<img width="533" alt="image" src="https://github.com/immich-app/immich/assets/1146708/0ee95871-c97e-43f2-a9f6-93f1961f7e13">

I'm not sure how it's related to [this issue](https://github.com/immich-app/immich/issues/5305) because the timeline section `virtual-timeline` is still empty. 

`server` logs:
![image](https://github.com/immich-app/immich/assets/1146708/d164779c-ff10-4fa2-bd79-f74e22ae6510)

I've checked the DB sessions and it seems that there was a query which started around the same time which is possibly the reason:
<img width="1418" alt="image" src="https://github.com/immich-app/immich/assets/1146708/7fc7427f-5598-4973-83eb-24ed4c125665">

Formated query:
```sql
SELECT
    COUNT("asset"."id")::int AS "count",
    (date_trunc('month', ("asset"."localDateTime" AT TIME ZONE 'UTC')) AT TIME ZONE 'UTC')::timestamptz AS "timeBucket"
FROM
    "assets" "asset"
    LEFT JOIN "exif" "exifInfo" ON "exifInfo"."assetId" = "asset"."id"
    LEFT JOIN "asset_stack" "stack" ON "stack"."id" = "asset"."stackId"
    LEFT JOIN "assets" "stackedAssets" ON "stackedAssets"."stackId" = "stack"."id"
        AND ("stackedAssets"."deletedAt" IS NULL)
WHERE
    ("asset"."isVisible" = true
     AND "asset"."ownerId" IN ($1)
     AND "asset"."isArchived" = $2
     AND ("stack"."primaryAssetId" = "asset"."id" OR "asset"."stackId" IS NULL))
    AND ("asset"."deletedAt" IS NULL)
GROUP BY
    (date_trunc('month', ("asset"."localDateTime" AT TIME ZONE 'UTC')) AT TIME ZONE 'UTC')::timestamptz
ORDER BY
    (date_trunc('month', ("asset"."localDateTime" AT TIME ZONE 'UTC')) AT TIME ZONE 'UTC')::timestamptz DESC;
```

### The OS that Immich Server is running on

Kubernetes in TrueNAS 

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I'm using Kubernetes and this is my YAML:


apiVersion: v1
kind: Namespace
metadata:
  name: immich

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: common-env
  namespace: immich
data:
  IMMICH_SERVER_URL: http://192.168.1.5:10400
  UPLOAD_LOCATION: "library"
  DB_HOSTNAME: "192.168.1.5"
  DB_PORT: "5432"
  DB_USERNAME: immich
  DB_PASSWORD: **********
  DB_DATABASE_NAME: immich
  PGCONNECT_TIMEOUT: "30000"
  REDIS_HOSTNAME: "192.168.1.5"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  DEVICE: cpu

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
        app.kubernetes.io/name: immich-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-server
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 568
      containers:
      - name: immich-server
        image: altran1502/immich-server:v1.98.0
        command: [ "./start.sh", "immich" ]
        envFrom:
        - configMapRef:
            name: common-env
        volumeMounts:
        - name: immich-upload
          mountPath: /usr/src/app/upload
      volumes:
        - name: immich-upload
          hostPath:
            path: /mnt/main/Home/Data/Apps/Immich/upload

---

apiVersion: v1
kind: Service
metadata:
  name: immich-server
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-server
spec:
  ports:
  - name: http
    targetPort: 3001
    port: 10400
  selector:
    app.kubernetes.io/name: immich-server
  type: LoadBalancer

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-microservices
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
        app.kubernetes.io/name: immich-microservices
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-microservices
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 568
      containers:
      - name: immich-microservices
        image: altran1502/immich-server:v1.98.0
        command: [ "./start.sh", "microservices" ]
        envFrom:
        - configMapRef:
            name: common-env
        volumeMounts:
        - name: immich-upload
          mountPath: /usr/src/app/upload
      volumes:
        - name: immich-upload
          hostPath:
            path: /mnt/main/Home/Data/Apps/Immich/upload

---

apiVersion: v1
kind: Service
metadata:
  name: immich-microservices
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-microservices
spec:
  ports:
  - name: http
    targetPort: 3002
    port: 3002
  selector:
    app.kubernetes.io/name: immich-microservices
  type: ClusterIP

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: immich-machine-learning
  namespace: immich
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
        app.kubernetes.io/name: immich-machine-learning
  template:
    metadata:
      labels:
        app.kubernetes.io/name: immich-machine-learning
    spec:
      containers:
      - name: immich-machine-learning
        image: altran1502/immich-machine-learning:v1.98.0
        envFrom:
        - configMapRef:
            name: common-env
        volumeMounts:
        - name: immich-model-cache
          mountPath: /cache
      volumes:
        - name: immich-model-cache
          hostPath:
            path: /mnt/main/Home/Data/Apps/Immich/model-cache

---

apiVersion: v1
kind: Service
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app.kubernetes.io/name: immich-machine-learning
spec:
  ports:
  - name: http
    targetPort: 3003
    port: 3003
  selector:
    app.kubernetes.io/name: immich-machine-learning
  type: ClusterIP
```

### Your .env content

```Shell
I store all ENV in the configMaps:


  IMMICH_SERVER_URL: http://192.168.1.5:10400
  UPLOAD_LOCATION: "library"
  DB_HOSTNAME: "192.168.1.5"
  DB_PORT: "5432"
  DB_USERNAME: immich
  DB_PASSWORD: **********
  DB_DATABASE_NAME: immich
  PGCONNECT_TIMEOUT: "30000"
  REDIS_HOSTNAME: "192.168.1.5"
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "0"
  DEVICE: CPU
```
```


### Reproduction steps

```bash
1. Open the website
2. Play around for sometime
3. Receive 5xx errors
...
```
