### DISCUSSION TITLE
[Feature] Start all Immich metrics with word "immich_".

### DISCUSSION THREAD

**Discussion by reefland** [immich-app/immich#8191] [Feature Request]
### The feature

Finding Immich metrics  is a chore as none of the metrics contain the word "immich" which makes finding and discovery of metrics annoying.  I don't want to have to curl both the endpoints to figure out metric names instead of going to Prometheus Web interface and type "immich" and they all start showing up as you type.

Looks like the initial round of metrics are developer focused.  Please consider adding metrics that can be used for a typical dashboards... number of: images, movies, albums, people, objects, faces not associated to person, etc.

### Platform

- [X] Server
- [ ] Web
- [ ] Mobile

**Comment by bo0tzz** [comment]
I think setting a global prefix is not supported by the library we use: https://github.com/pragmaticivan/nestjs-otel/issues/265

@mertalev thoughts?

**Reply by mertalev** [reply]
Only the io metrics can easily use a prefix since they're custom. We'd have to monkeypatch things to force the prefix in other cases.

All the metrics have immich as the service name, so that might also help with discovery.

**Comment by mertalev** [comment]
> Looks like the initial round of metrics are developer focused. Please consider adding metrics that can be used for a typical dashboards... number of: images, movies, albums, people, objects, faces not associated to person, etc.

Yep, this was initially aimed as more of a development / debugging tool. But I also want to add these kinds of metrics as well as job metrics.

**Comment by mertalev** [comment]
I've made an upstream PR to allow prefixing the API metrics [here](https://github.com/pragmaticivan/nestjs-otel/pull/472). I'm not sure if we should change the repo metrics now, or wait for that change so they're consistent.

**Comment by MMK21Hub** [comment]
As a workaround, here's part of my `prometheus.yml` that shows how to add a prefix to Immich's metrics on the scraping side:

```yaml
  - job_name: immich_microservices
    static_configs:
      - targets: ["immich-microservices:8081"]
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(.*)'
        action: replace
        replacement: immich_${1}
```

Note that I don't think you need to add the same relabeling config to the `immich_server` scraper, as its metrics are already prefixed with `immich_`

![A screenshot of the Grafana metrics explorer showing 1511 metrics that start with "immich_"](https://github.com/immich-app/immich/assets/50421330/df939b24-64f9-4596-8e46-8f516e5c58fe)

**Reply by mertalev** [reply]
That's a really good find! We should add that to the official config. A small tweak can be to change the regex to this: `^(?!immich).*$`. The job metrics do have the immich prefix and others in the future may as well, so this prevents the prefix from being added twice.

**Reply by reefland** [reply]
When I tried your regex suggestion above `regex: '^(?!immich).*$'` Prometheus failed config loading with:
```
error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

**Reply by mertalev** [reply]
Hmm, Go's regex engine apparently doesn't support lookarounds.

**Reply by bo0tzz** [reply]
I don't have a good setup to test it myself, but would it work to just do this?
```yaml
  - job_name: immich_microservices
    static_configs:
      - targets: ["immich-microservices:8081"]
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(immich_)?(.*)'
        action: replace
        replacement: immich_${2}
```
