### DISCUSSION TITLE
v1.99.0 immich_machine_learning ERROR Can't connect to ('::', 3003)

### DISCUSSION THREAD

**Discussion by datdamnzotz** [immich-app/immich#8220] [Q&A]
### The bug

immich_machine_learning  | [03/23/24 12:31:53] INFO     Starting gunicorn 21.2.0
immich_machine_learning  | [03/23/24 12:31:53] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:31:54] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:31:55] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:31:56] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:31:57] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:31:58] ERROR    Can't connect to ('::', 3003)
immich_machine_learning exited with code 1
immich_machine_learning  | [03/23/24 12:32:01] INFO     Starting gunicorn 21.2.0
immich_machine_learning  | [03/23/24 12:32:01] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:02] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:03] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:04] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:05] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:06] ERROR    Can't connect to ('::', 3003)
immich_machine_learning exited with code 1
immich_machine_learning  | [03/23/24 12:32:10] INFO     Starting gunicorn 21.2.0
immich_machine_learning  | [03/23/24 12:32:10] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:11] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:12] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:13] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:14] ERROR    Retrying in 1 second.
immich_machine_learning  | [03/23/24 12:32:15] ERROR    Can't connect to ('::', 3003)
immich_machine_learning exited with code 1

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    networks:
      - immich
      - proxy
#Runs on port 3001
#    ports:
#     - 2283:3001

    depends_on:
      - redis
      - database
#      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ['start.sh', 'microservices']
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    networks:
      - immich
    depends_on:
      - redis
      - database
 #     - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - model-cache:/cache
    networks:
      - immich
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - redis_data:/data
    networks:
      - immich
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgdata:/var/lib/postgresql/data
    networks:
      - immich
    restart: always

networks:
  immich:
  proxy:
    external: true

volumes:
  pgdata:
  model-cache:
#  tsdata:
  redis_data:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
TZ=America/Chicago
PUID=1000
PGI=1000
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media/immich/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<r>
TYPESENSE_DATA_DIR=/data
# remove this to get debug messages
GLOG_minloglevel=1

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_PASSWORD=<r>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis

#Webserver
# Make sure these values get passed through from the env file
#IMMICH_SERVER_URL
#IMMICH_WEB_URL

#MACHINE_LEARNING_WORKERS=1 #optional
#MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
```

### Reproduction steps

```bash
docker-compose down
docker-compose up
```

### Additional information

ipv6 is disabled on host and docker.
could this be the issue?

[v1.98.2](https://github.com/immich-app/immich/releases/tag/v1.98.2) loads just fine.
