### DISCUSSION TITLE
No way to download images from a shared album?

### DISCUSSION THREAD

**Discussion by TheImmortalOne** [immich-app/immich#8318] [Q&A]
Hello,

I imagined that checking the option to 'allow users to download photos' would mean, in a similar way to Synology Photos does it for example, that sharing an album with the particular check enabled would ALSO provided viewers the option to download each image. 
On desktop, one could 'save as' to a fully zoomed in image (otherwise they get a lower res photo), but on mobile that's not really the case on android devices. Am I missing something, is there a 'download image' button I'm somehow hiding unintentionally?

There IS the option to download the entire album and that provides a nice zip, but I don't have one for downloading an image.
![Screenshot_623](https://github.com/immich-app/immich/assets/15293387/fb238e39-7edd-4682-ad4e-bf05fd5c5a77)

LE: On desktop I found out, by searching, of the 'shift+d' option. But on mobile? The keyboard wont appear when just looking at an img.

The OS that Immich Server is running on
Synology

Version of Immich Server
v1.99.0

Version of Immich Mobile App
v1.99.0

Platform with the issue
 Server
 Web
 Mobile X

Your docker-compose.yml content
```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```
