### DISCUSSION TITLE
Redis replacement?

### DISCUSSION THREAD

**Discussion by bertmelis** [immich-app/immich#8328] [General]
Hi all,

As an open source fan, I obviously was quite disappointed with the [turmoil around Redis](https://github.com/redis/redis/pull/13157/files/17a6ddc2aec52a981474bcdce7a550dedcf3c572#r1533472447). So I wanted to look into the possibilities of replacing Redis with one of the alternatives.

Does anybody already tried such a thing? Which alternative?
If I'm the first to bring up this subject, which alternative would you suggest?

Note that I'm running on an old cpu without AVX extensions. I tried to use Dragonfly in the past but since their standard container needs AVX, I abandoned that one.

PS I'm not (yet) advocating to change the default immich stack. Just exploring...

**Comment by bo0tzz** [comment]
AFAIK:
1. The library we use (bullmq) doesn't use any particular/special features, and thus should work with any redis-compatible alternatives.
2. The redis license change doesn't really affect home users (beyond the enshittification it signals, that is).
3. You can probably continue running a redis version from before the license change essentially in perpetuity without downsides.

Finally, we've been intending for a while to drop redis entirely in favour of doing the queueing through postgres. These license changes don't change anything about that, but it will come at some point :)

**Reply by bertmelis** [reply]
True, the license doesn't hinder me as a self-hosting home user. It's the sentiment around it that bothers me.

I'll give it a try, just for fun and see how it goes.

Queueing through PG? Something to look forward to! Another container to shut down!

**Comment by R-Nabil** [comment]
Hello,

For sharing back with the community, I was able to use dragonfly with immich and so far (which has been only 2 days), has been working well. I share below my manifest in case it is needed :

```
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/created-by: dragonfly-operator
  name: immich-dragonfly
  namespace: immich
spec:
  args:
    - "--cluster_mode=emulated"
    - "--default_lua_flags=allow-undeclared-keys"
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: 600m
      memory: 750Mi
```
