### DISCUSSION TITLE
[Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Failed to get server info

### DISCUSSION THREAD

**Discussion by luyzfernando08** [immich-app/immich#8487] [Q&A]
### The bug

I'm using a NAS to store photos and for some reason the storage information is no longer shown.

![image](https://github.com/immich-app/immich/assets/134880920/475dea28-dcf0-4fcc-a38b-41cabc8b5985)

Additionally, when trying to access the administrator area I receive the error below.

![image](https://github.com/immich-app/immich/assets/134880920/c492a308-eee8-4032-a2de-07a6693cd52b)

`Failed to get server info (500)

Stacktrace
Error: Error: 500
    at Object.ie [as ok] (http://fotos.local/_app/immutable/chunks/fetch-client.DbGu7UYN.js:1:2832)
    at async v (http://fotos.local/_app/immutable/chunks/auth.BSeebS59.js:1:636)
    at async ml (http://fotos.local/_app/immutable/nodes/39.DZd7bJfn.js:1:1738)
    at async Ie (http://fotos.local/_app/immutable/chunks/entry.gs5-sG3j.js:1:13443)`

`2024-04-03 07:35:52 [Nest] 6  - 04/03/2024, 10:35:52 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Failed to get server info`
`2024-04-03 07:35:52 [Nest] 6  - 04/03/2024, 10:35:52 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'`

I'm not sure which version of Immich the problem started with

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0 build 130

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes: 
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - "D:/Immich/pgdata:/var/lib/postgresql/data"
    restart: always

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.199/Immich/cache
      o: addr=192.168.0.199,vers=2.0,username=XXXXXX,password=XXXXX,file_mode=0777,dir_mode=0777
  upload: 
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.199/Immich/upload
      o: addr=192.168.0.199,vers=2.0,username=XXXXX,password=XXXXX,file_mode=0777,dir_mode=0777
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=immich-upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.100.0

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=TYPESENSE_API_KEY
DB_PASSWORD=XXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. open the web or mobile app
2. access the area to view "Server Storage"
```

**Comment by bo0tzz** [comment]
That looks like your network mount broke, I don't think this is an issue in Immich.

**Reply by luyzfernando08** [reply]
It's not a network problem, everything else works.

Access to photos on the NAS is normal, as is the backup.

See the image below for recent photos.

![image](https://github.com/immich-app/immich/assets/134880920/72e0908c-4019-4aec-8e03-f137c6258374)


It's a specific problem that has appeared in recent versions, but unfortunately I can't confirm which one.

**Comment by luyzfernando08** [comment]
@bo0tzz  Could it be that problem [8202](https://github.com/immich-app/immich/issues/8202) and [8426 ](https://github.com/immich-app/immich/issues/8426) is unrelated to this?

**Reply by bo0tzz** [reply]
I think those are different issues. What you're seeing isn't inconsistency but just straight up errors. If you try to browse the files locally on your system, or from the shell inside of the immich containers, does that work as expected?

**Reply by luyzfernando08** [reply]
To test, I took a photo now.

In docker and windows explorer the file is there.

![image](https://github.com/immich-app/immich/assets/134880920/470084dd-8f51-4a5f-a39e-b5d0cbac0e04)

![image](https://github.com/immich-app/immich/assets/134880920/08ef7000-9bb4-4293-8e98-469848ea673c)

In Immich, the photo is loaded in the browser.

![image](https://github.com/immich-app/immich/assets/134880920/975463d4-60ee-42ab-838f-1e30cbaa76be)

**Reply by mmomjian** [reply]
Can you download that image?

**Reply by luyzfernando08** [reply]
Yes, however, a strange thing happens.

When requesting download, the image is downloaded twice.

There are two files left, one good and one corrupt.

But I think that could be another problem.

![image](https://github.com/immich-app/immich/assets/134880920/42d81fe9-6d47-4cb7-bf8c-4e1529d86747)

![image](https://github.com/immich-app/immich/assets/134880920/ba426091-79ed-4dab-babf-11c5307f3b19)

![image](https://github.com/immich-app/immich/assets/134880920/5c17e20d-84df-4956-b803-fe351982ac34)

**Reply by mmomjian** [reply]
I suspect this is due to a weird interplay of Windows / Docker Desktop / network storage creating a perfect storm. While it would ideally work, there is a limit to the systems we can test / support. We recommend Linux with plain Docker, as Docker Desktop + Windows can introduce a lot of issues due to the virtual machine structure and file/network permissions.

**Comment by odedia** [comment]
I seem to face the same/similar issue on macOS (ARM, M1 Max). The images are on a TrueNAS Scale SMB share. I've added a volume to `server` and `microservices` in docker-compose as follows:
```
      - /Volumes/Data-1/Pictures/PhotoPrism/Originals:/mnt/media/originals:ro
```
The docker logs output the following in `microservices`:
```
2024-04-09 18:19:31 [Nest] 7  - 04/09/2024, 3:19:31 PM   ERROR [JobService] Unable to run job handler (library/library-refresh): Error: EAGAIN: resource temporarily unavailable, scandir '/mnt/media/originals/2007/2007-09-02'
2024-04-09 18:19:31 [Nest] 7  - 04/09/2024, 3:19:31 PM   ERROR [JobService] Error: EAGAIN: resource temporarily unavailable, scandir '/mnt/media/originals/2007/2007-09-02'
2024-04-09 18:19:31 [Nest] 7  - 04/09/2024, 3:19:31 PM   ERROR [JobService] Object:
2024-04-09 18:19:31 {
2024-04-09 18:19:31   "id": "776bb755-95d6-4fb6-8623-61ee9cccb703",
2024-04-09 18:19:31   "refreshModifiedFiles": false,
2024-04-09 18:19:31   "refreshAllFiles": true
2024-04-09 18:19:31 }
2024-04-09 18:19:31 
```
This is a brand new install, library is empty, all I did was add the external library `/mnt/media/originals` and ran "Force Rescan". It's currenly at zero.

<img width="1032" alt="image" src="https://github.com/immich-app/immich/assets/2992180/bab745b3-feac-4135-bcf6-fb290918f01a">

**Comment by HardoA** [comment]
I appear to have the same issue.

Immich v1.101.0 run as a docker container in Ubuntu 22.04.4 LTS with the latest updates. Photos on SMB share from Truenas. I have been using Immich for over a year with continued updates as they come out but I did skip v1.100.0. 

Rebooted the containers, restarted the host and attempted administrator self fix page but that now times out.

[Some logs attached](https://github.com/immich-app/immich/files/14925441/_immich_server_logs.1.txt) from immich_server. I have not enabled DEBUG yet.

**Comment by tspirtle** [comment]
Same issue here, seeing log entries containing "Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'"

I've been running v1.101.0 since release day. Today, suddenly photos backed up via Android and iOS apps appear as grey broken thumbnails and images. Photos uploaded via the web are working correctly. No changes have been made to my environment to cause this. The timing of the issue seems to coincide with backing up ~300 images from my phone. Thumbnails stopped generating and images became broken midway through the upload.

Additionally, Storage Stats will not display (constantly spinning), and "Users" and "External Libraries" result in Error 500:

```
Failed to get server info (500)

Stacktrace
Error: Error: 500
    at Object.de [as ok] (https://photos.redacted.com/_app/immutable/chunks/fetch-client.CUHQ0TcQ.js:1:2835)
    at async v (https://photos.redacted.com/_app/immutable/chunks/auth.Ceg-WeSQ.js:1:636)
    at async ml (https://photos.redacted.com/_app/immutable/nodes/39.DLgPt8r1.js:1:1694)
    at async Ie (https://photos.redacted.com/_app/immutable/chunks/entry.Cvo-FpGt.js:1:13444)
```

**Reply by alextran1502** [reply]
@tspirtle please double check your mount point at UPLOAD_LOCATION

**Reply by tspirtle** [reply]
Confirmed the mount seems healthy. The files are uploading to upload location correctly, and I can view them manually via file browser. I also confirmed I can see the uploaded files from within the immich_server container at /usr/src/app/upload, and all permissions/etc look correct.

**Reply by alextran1502** [reply]
I just did some reading on this and it looks like an issue with Linux kernel issue, perhaps are you on Kernel 6.1?

Ref1: https://github.com/home-assistant/operating-system/issues/3041

Ref2: https://forum.manjaro.org/t/samba-share-ls-directory-resource-temporarily-unavailable/155083

**Reply by tspirtle** [reply]
Bingo! Good find! I was running kernel 5.15.0-102. I rolled back to 5.15.0-101, and uploads are working correctly. I had to refresh thumbnails on assets uploaded before I rolled back the kernel.

**Reply by Baker53054** [reply]
TI waws on 5.15, i updated to 6.5 and it is all good, sweet and thanks

**Reply by HardoA** [reply]
Confirmed, fixed it for me as well. I updated to 6.5.

**Reply by waliaabhishek** [reply]
Confirmed working. kernel 5.15.102 is broken if anyone else comes looking for a similar issue.  Kernal upgrade otr downgrade might help.

**Reply by DevGoran** [reply]
Solved it also for me, upgraded from 5.15.102 to 6.5

**Comment by kkoshelev** [comment]
I have the same issue. I beleive it is because of recent kernel update.

> Linux version 5.15.0-102-generic (buildd@lcy02-amd64-080) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #112-Ubuntu SMP Tue Mar 5 16:50:32 UTC 2024

Can anyone suggest a command to downgrade kernel to the previous 101 version?

**Reply by gruenheit** [reply]
I solved it by downgrading, following this [guide](https://askubuntu.com/questions/82140/how-can-i-boot-with-an-older-kernel-version/1393019#1393019). 
5.15.0-102-generic -> 5.15.0-101-generic x86_64

**Comment by engkad** [comment]
Worth noting that I have this issue on docker on Ubuntu and ended up trying an SMB docker volume instead of the one mounted on the host, and that seems to solve the problem as well. Maybe easier than rolling back kernel if you only have remote access like me.

Edit: Nope never mind, samba is definitely a problem here - I realized the volume that worked was a new local volume, not the smb volume.

**Comment by raikes** [comment]
Just been battling with this myself. Changed my storage over to an SMB mount (using autofs) and suddenly couldn't access the Administration tab via the web gui. Server logs were showing:

`immich_server            | 2024-04-14T08:58:36.826248020Z [Nest] 7  - 04/14/2024, 8:58:36 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Failed to get server info`

`immich_server            | 2024-04-14T08:58:36.826294662Z [Nest] 7  - 04/14/2024, 8:58:36 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'`

Server is running Ubuntu 22.04 LTS, the kernel was 5.15.0-102. Downgraded kernel to 5.15.0-101 and everything is working again

**Reply by engkad** [reply]
I just tried that but the 101 kernel broke some of my other containers - I'm hoping someone finds another workaround.

**Comment by TheCanadian42** [comment]
Any ideas for a windows docker desktop workaround?

**Comment by roks531** [comment]
Same problem here, ubuntu server, kernel 5.15.0-102. Kernel downgrade is not a real solution...

**Comment by mgaudieri** [comment]
Same issue here unfortunately.

**Comment by Edzioindra** [comment]
Tried several rolling back and forth. Issue is the same. Using Ubuntu Server VM in proxmix and upload library is in TrueNas.

**Comment by Master-of-Mouse** [comment]
I'm setting up an immich container in a docker environment.
Proxmox -> Debian VM -> docker ->immich

I have another Truenas VM with an SMB share that I would like to use for immich
Proxmox -> VM Truenas -> Share SMB immich

I would like to replace "UPLOAD_LOCATION=./library" in the .env with something that points to the share on Truenas.

I understand that many of you have already done this but I didn't understand how you configured the connection in the docker-compose.yml and .env files.
I would like to keep only the database on the Debian VM disk. Images, videos and previews in Truenas.

**Comment by kkoshelev** [comment]
Is it safe to upgrade kernel from 5.15.0-101 version? Do you know if the issue is still there?

Edited: new 5.15.0-112-generic kernel doesn't seem to have that issue

**Comment by DeltaTango69** [comment]
I have the same issue with smb share. I have tried it with NFS with my mycloud system, this should be the address:

`# Bereitstellungspunkt: nfs://192.168.178.4/nfs/Immich`

```
  Immich:
    driver_opts:
      type: nfs
      o: "addr=192.168.178.4,rw"
      device: ":/nfs/Immich"  
```
works for me
