### DISCUSSION TITLE
After updating, errors in containerConfig

### DISCUSSION THREAD

**Discussion by zolstarym** [immich-app/immich#8496] [Q&A] [answered]
### The bug

On v1.99, which was working normally, did a "docker-compose pull" command, then a "docker-compose up -d" command to upgrade server as usual. The container failed to launch giving errors in containerConfig

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"   
                             
#name: immich
                             
services:          
  immich-server:             
    container_name: immich_server                          
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                                 
    command: ["start.sh", "immich"]                                                                                    
    volumes:                                               
      - ${UPLOAD_LOCATION}:/usr/src/app/upload             
      - /etc/localtime:/etc/localtime:ro      
    env_file:                                              
      - .env 
    ports:  
      - 2283:3001
    depends_on:
      - redis   
      - database   
    restart: always          
                             
  immich-microservices:                                    
    container_name: immich_microservices                                                                               
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                                 
    command: ["start.sh", "microservices"]                 
    volumes: 
      - ${UPLOAD_LOCATION}:/usr/src/app/upload             
      - /etc/localtime:/etc/localtime:ro                   
    env_file:                
      - .env
    depends_on:                                            
      - redis                                                                                                          
      - database                                                                                                       
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}                                     
    volumes:    
      - model-cache:/cache                                 
    env_file:                                              
      - .env                                               
    restart: always
                             
  redis:    
    container_name: immich_redis                           
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5                    
#    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3                   
    restart: always

  database:               
    container_name: immich_postgres        
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}                    
      POSTGRES_USER: ${DB_USERNAME}                        
      POSTGRES_DB: ${DB_DATABASE_NAME}                     
    volumes:       
      - pgdata:/var/lib/postgresql/data                    
    restart: always
                                                           
volumes:                                                                                                               
  pgdata:                                                                                                              
  model-cache:
```

### Your .env content

```Shell
$ docker exec immich_postgres env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin
HOSTNAME=c4792f04e9bb
POSTGRES_PASSWORD=postgres16
POSTGRES_USER=postgres
POSTGRES_DB=immich
GOSU_VERSION=1.16
LANG=en_US.utf8
PG_MAJOR=14
PG_VERSION=14.10-1.pgdg120+1
PGDATA=/var/lib/postgresql/data
HOME=/root
$ docker exec immich_redis env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=f26c8e93f6d9
GOSU_VERSION=1.17
REDIS_VERSION=6.2.14
REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-6.2.14.tar.gz
REDIS_DOWNLOAD_SHA=34e74856cbd66fdb3a684fb349d93961d8c7aa668b06f81fd93ff267d09bc277
HOME=/root
```

### Reproduction steps

```bash
On v1.99, which was working normally, did a "docker-compose pull" command, then a "docker-compose up -d" command to upgrade server as usual. The container failed to launch giving errors in containerConfig
```

### Additional information

$ docker-compose up -d                                                                     
Recreating 59287dd285e9_immich_machine_learning ...                                                                    
Starting immich_postgres                        ...                                                                    
Starting immich_redis                           ...                                                                    
Starting immich_postgres                        ... done                                                               
Starting immich_redis                           ... done                                                               
Recreating 91dc8915cef2_immich_microservices    ...                                                                    
Recreating b1e2570f2c81_immich_server           ...                                                                    
                                                              

ERROR: for 91dc8915cef2_immich_microservices  'ContainerConfig'                                                 
                                                                                                                       
ERROR: for b1e2570f2c81_immich_server  'ContainerConfig'   
                                                                                                                       
ERROR: for immich-machine-learning  'ContainerConfig'
                                                                                                                       
ERROR: for immich-microservices  'ContainerConfig'         
                                                                                                                       
ERROR: for immich-server  'ContainerConfig'                
Traceback (most recent call last):                                                                                     
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())  
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main                                          
    command_func()                                                                                                     
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command                              
    handler(command, command_options)                                                                                  
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper                              
    result = fn(*args, **kwargs)                                                                                       
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up                                          
    to_attach = up(False)                                                                                              
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up                                          
    return self.project.up(                                                                                            
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up                                            
    results, errors = parallel.parallel_execute(                                                                       
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise                                                                                             
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)                                                                                                 
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do                                            
    return service.execute_convergence_plan(                                                                           
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan                      
    return self._execute_convergence_recreate(                                                                         
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(                 
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise                                 
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer                                     
    result = func(obj)                                     
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate                                      
    return self.recreate_container(     
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container                            
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container                              
    container_options = self._get_container_create_options(                                                            
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options                 
    container_options, override_options = self._build_container_volume_options(                                        
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options               
    binds, affinity = merge_volume_bindings(            
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings                        
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes                   
    container.image_config['ContainerConfig'].get('Volumes') or {}                                                     
KeyError: 'ContainerConfig'
