### DISCUSSION TITLE
Smart Search - malformed array literal

### DISCUSSION THREAD

**Discussion by Jurrer** [immich-app/immich#8554] [Q&A] [answered]
### The bug

My search broke, so I ran Smart Search for all.
Now all I'm getting is this error:
```
[Nest] 8  - 04/05/2024, 9:24:53 PM   ERROR [JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: malformed array literal: "[-0.026290784,-0.007018573,...[a very long vector]]
```

Full logs here:
[_immich-microservices_logs_query_err.txt](https://github.com/immich-app/immich/files/14889854/_immich-microservices_logs_query_err.txt)
I tried using verbose log level, with same results.

### The OS that Immich Server is running on

Ubuntu 22.04.04 LTS, Docker 25.0

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:v1.101.0
    user: ${PUID}:${PGID}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${DATAPATH}/pictures:/usr/src/app/upload
      - ${HOMEPATH}/immich_thumbnails:/usr/src/app/upload/thumbs
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      DB_HOSTNAME: ${IMMICH_DB_HOST}
      DB_DATABASE_NAME: ${IMMICH_DB}
      DB_USERNAME: ${IMMICH_DB_USERNAME}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD}
      REDIS_PASSWORD: ${IMMICH_REDIS_PASSWORD}
      REDIS_HOSTNAME: ${IMMICH_REDIS_HOST}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      NVIDIA_DRIVER_CAPABILITIES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu,video,compute]
    networks:
      immich:
    restart: unless-stopped
```

### Your .env content

```Shell
IMMICH_DB=immich_db
IMMICH_DB_HOST=postgresql
IMMICH_DB_USERNAME=immich
IMMICH_DB_PASSWORD=redacted

IMMICH_REDIS_HOST=redis-immich
IMMICH_REDIS_PASSWORD=redacted
```

### Reproduction steps

```bash
I cannot really say how to reproduce this step.
I can say it appeared after some problems I was having with pgvecto.rs version bump.
```

### Additional information

I am using Bitnami postgresql database with manually installed pgvecto.rs plugin.
I tried two CLIP models for ML: `ViT-B-32__openai` and `XLM-Roberta-Large-Vit-B-16Plus` without any success.
After change I reran the job for all.
Recreating the containers didn't help
