### DISCUSSION TITLE
"Display order" album sorting not carried over to shared albums

### DISCUSSION THREAD

**Discussion by hydrandt** [immich-app/immich#8565] [Feature Request]
### The bug

Selected album display order is not respected in albums shared with a link. 

It would be great if:

1. Shared albums respected the sorting order set in the album
2. (optional) let viewers set their preferred display order

### The OS that Immich Server is running on

Ubuntu 23.10

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich                                

services:                                   
  immich-server:                            
    container_name: immich_server                                                                                                                                                 
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                   
    command: ['start.sh', 'immich']
    volumes:                                
      - ${UPLOAD_LOCATION}:/usr/src/app/upload                                           
      - /etc/localtime:/etc/localtime:ro                                                                                                                                          
    env_file:                               
      - .env                                
    ports:                                  
      - 2283:3001                           
    depends_on:                             
      - redis                               
      - database                            
    restart: always 

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=_____

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create an album, and in its Options, select Display order: Oldest first
2. Share the album (Create link)
3. Open the link -> display order is from oldest -> newest
```

### Additional information

If a PR for this is welcome, let me know:) I didn't go through the frontend code yet, I suppose it should be easy to find the places to work on. If there is something that would be helpful to bring this feature to shared albums, please share.
