### DISCUSSION TITLE
Seeking Help: Integrating Over 200,000 Photos into Immich on My Ubuntu Server

### DISCUSSION THREAD

**Discussion by BoBBer446** [immich-app/immich#8853] [Q&A] [answered]
Hello everyone! I've recently upgraded my server and am now using Immich to manage my photo library. Although I've successfully set up everything initially, I'm encountering a few challenges where I could really use your expertise and experience. Here’s a brief overview of my setup and the specific issues I need help with.

I have the following server setup:
LarkBox X 2023 with Intel N100
12 GB RAM, recently upgraded with a new 2 TB NVME SSD.

It runs Ubuntu Server 22.04 with Ubuntu Pro. I've installed Portainer using Docker Compose:
```yaml
version: '3.3'
services:
  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "9000:9000" # Portainer UI
      - "8000:8000" # Portainer Agent (optional, für Edge Agents)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
```

Through Portainer, I've also installed Immich:

```yaml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

env File:
```yml
UPLOAD_LOCATION=/var/lib/docker/bindmounts/immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

Directory path:
```bash
/var/lib/docker/bindmounts/immich $ ll
total 0
drwxr-xr-x+ 6 root root 70 Apr 15 18:29 ./
drwxrwxr-x+ 4 root root 39 Apr 15 18:01 ../
...
```

I've successfully uploaded some photos through the web interface. On the server, there are over 200,000 photos in a different folder that I would like to integrate into Immich.

Should or can I just move them to the folder:

```bash
/var/lib/docker/bindmounts/immich/library $ ll
total 0
drwxrwxr-x+ 4 root root 62 Apr 15 18:20 ./
...
```
that matches my user ID.

How can I best manage this?

Second question:
Does Immich handle duplicates the same way? The web interface skips duplicates. What happens if I provide the data on a file basis to Immich?

I hope someone can help :)
