### DISCUSSION TITLE
High CPU Utilization on transcoding even with GPU.

### DISCUSSION THREAD

**Discussion by siganberg** [immich-app/immich#8888] [Q&A] [answered]
I'm getting around 60% CPU utilization when doing video transcoding even though I setup my GPU hardware acceleration. 

Here's a sample screenshot of my Unraid Server when transcoding is in progress. I paused other Jobs in Immich Server to make only transcoding. 

![image](https://github.com/immich-app/immich/assets/5061442/91e8c922-f723-4f0a-bd5f-0837a1c93328)

I know the GPU setup is working cause it has utilization too but very less, just around 2%

![image](https://github.com/immich-app/immich/assets/5061442/598776a6-abf4-495f-9fbc-8026fa770580)

Logs from Immich MicroServer

![image](https://github.com/immich-app/immich/assets/5061442/44b92947-bbd4-4010-a383-d57f3319b81f)

Immich Transcoding settings:

![image](https://github.com/immich-app/immich/assets/5061442/52d491f6-575b-479d-b37e-9c2b15463d50)

Also only transcoding 1 video at a time on the Job Settings. 

Pausing the transcoding will put my CPU to almost idle utilization and  0% on GPU. 

I'm using docker-compose to run my UnRaid Server. 

```yml
....
immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: 
      file: hwaccel.transcoding.yml
      service: nvenc    
    command: ['start.sh', 'microservices']   
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/user/videos:/videos
    env_file:
      - .env
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=GPU-xxxx-xxxx-xxxx-....
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
       file: hwaccel.ml.yml
       service: cuda
    volumes:
      - ${MODEL_LOCATION}:/cache
    env_file:
      - .env
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=GPU-xxxx-xxxx-xxxx-....
    restart: always
....

```

GPU Info:

![image](https://github.com/immich-app/immich/assets/5061442/dc4658c4-ebf2-4156-878f-861ba6f6c656)
