### DISCUSSION TITLE
How to merge a mobile album into an immich album

### DISCUSSION THREAD

**Discussion by ShiFangJuMie** [immich-app/immich#9006] [Q&A] [answered]
### The bug

I backed up the album from my iPhone to immich, but the album can only be viewed on my phone. I can see photos in immich's explore, but not in the album.

I hope to merge my phone backup album into my home album

The method I have found so far is to go to the backup album on my phone, select each photo, and then add it to the home album created in immich. This process can only be completed on mobile phones at present

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

iPhone latest

### Platform with the issue

- [ ] Server
- [X] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: /volume2/docker/immich-app/hwaccel.transcoding.yml
    #   service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: /volume2/docker/immich-app/hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume2/docker/immich-app/library
IMMICH_VERSION=release
LANG=C.UTF-8
LANGUAGE=zh_CN.UTF-8
TZ=Asia/Shanghai
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=************
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/volume2/docker/immich-app/postgres
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Deploy immich in Docker
2. Manually create 5 albums
3. Uploaded 2k+photos from the computer using Chrome
4. Use iPhone to download immich from the app store
5. Select 3 photo albums to backup to immich
6. Go to the backup album on iPhone, select All, and add to the album
```

### Additional information

![2ef56420f37788dc4ef372434c23855](https://github.com/immich-app/immich/assets/9131886/05e836d3-8b9d-4b81-940e-01f8bf9b8b5e)

![image](https://github.com/immich-app/immich/assets/9131886/745a61e4-6103-45ac-80b8-63493ad15a4e)
