### DISCUSSION TITLE
Can't restore database from backup - v1.102.3 [Stuck on Admin Registration page]

### DISCUSSION THREAD

**Discussion by conorlap** [immich-app/immich#9034] [Q&A] [answered]
I recently upgraded to [v1.102.3](https://github.com/immich-app/immich/releases/tag/v1.102.3) and undertook the steps to remove pgdata and add location etc:

```
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
#remove:  - pgdata:/var/lib/postgresql/data  
+      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
#remove: - pgdata:
  model-cache:
```
```
.env file
[...]
 DB_HOSTNAME=immich_postgres
 DB_USERNAME=postgres
 DB_DATABASE_NAME=immich
+DB_DATA_LOCATION=/srv/appdata/immich_db/
```

I had already setup immich_db_dumper and had plenty of backups. However when I go to restore the backup, when I start Immich it just brings me to the Admin Registration page "Since you are the first user on the system, you will be assigned as the Admin and are responsible for administrative tasks, and additional users will be created by you."

I have restored the backup by undertaking the following:

1. Stop all immich containers
2. Delete db files created in /srv/appdata/immich_db/
3. docker start immich_postgres
4.  gunzip < /srv/appdata/immich_db_backup/last/immich-20240412-000000.sql.gz \
| sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
| docker exec -i immich_postgres psql --username=postgres
5. start all immich containers

Can anyone suggest how to restore?

**Comment by drvenabili** [comment]
Hi @conorlap , did you fix it? I have the same issue. 

Thanks!

**Reply by conorlap** [reply]
Unfortunately not, I've given up to be honest! I may come back to Immich at some point and start from scratch but I'm quite disappointed that the backup solution that I implemented based on Immich guides didn't even work!

**Reply by drvenabili** [reply]
Ah too bad, thanks. Yes I feel the same way... I'll look more into it and ping you here if I find a fix.

**Reply by mmomjian** [reply]
Please share the exact docker compose content you used for the db_dumper. Also, what logs do you get when trying to restore the database?

**Reply by drvenabili** [reply]
This fixes it for me: https://github.com/immich-app/immich/discussions/9034#discussioncomment-9554783 

For reference the dumper part of the docker-compose is pasted below. It's pretty standard. Logs are fine (i.e. the command creates and fills the DB), no error thrown.

```
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 7
    volumes:
      - /mnt/user/CommunityApplicationsAppdataBackup/immich_db_backup/:/db_dumps
    depends_on:
      - database
```
