### DISCUSSION TITLE
DB Manifest for cloudnative-pg

### DISCUSSION THREAD

**Discussion by RogerSik** [immich-app/immich#9060] [General]
Someone successfully run db with cloudnative-pg Operator?

Trying it with custom image but always is something else missing / not working.

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
  namespace: immich
  labels:
    app: immich-db
spec:
  instances: 1

  # special image
  # https://docs.pgvecto.rs/admin/kubernetes.html
  # https://github.com/tensorchord/cloudnative-pgvecto.rs
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14-v0.2.0

  postgresql:
    parameters:
      shared_buffers: 500MB # use 25% of resources.limits
    shared_preload_libraries:
      - 'vectors.so'

  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true

      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
```

Currently immich-server stucks with:
```
[Nest] 7  - 04/24/2024, 3:41:31 PM     LOG [EventRepository] Initialized websocket server
Migration "AddCLIPEmbeddingIndex1700713994428" failed, error: operator class "vector_cos_ops" does not exist for access method "vectors"
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
                  ^

QueryFailedError: operator class "vector_cos_ops" does not exist for access method "vectors"
```

**Comment by bo0tzz** [comment]
You're missing the search path sql noted in the cloudnative-pgvecto.rs README.

**Reply by RogerSik** [reply]
You mean

```
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
```

same error with it :/ 

```
Migration "AddCLIPEmbeddingIndex1700713994428" failed, error: operator class "vector_cos_ops" does not exist for access method "vectors"
/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
            throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
```

I somewhere after some time removed it because in https://docs.pgvecto.rs/admin/kubernetes.html it wasn'tt mention.

**Reply by RS185734** [reply]
It seems no one can make immich work with cloud-native PostgreSQL.

**Comment by RS185734** [comment]
Same Error 

```
QueryFailedError: operator class "vector_cos_ops" does not exist for access method "vectors"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:179:9)
    at async /usr/src/app/dist/services/database.service.js:52:13
    at async /usr/src/app/dist/repositories/database.repository.js:187:23 {
  query: '\n' +
    '      CREATE INDEX IF NOT EXISTS clip_index ON smart_search\n' +
    '      USING hnsw (embedding vector_cosine_ops)\n' +
    '      WITH (ef_construction = 300, m = 16)',
  parameters: undefined,
  driverError: error: operator class "vector_cos_ops" does not exist for access method "vectors"
      at /usr/src/app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:179:9)
      at async /usr/src/app/dist/services/database.service.js:52:13
      at async /usr/src/app/dist/repositories/database.repository.js:187:23 {
```

Use below

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-immich-cluster
  namespace: cnpg-system
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.2
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
  instances: 1
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      storageClassName: manual-immich
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: postgresql-immich-pgsql
      owner: postgresql-immich-pgsql
      secret:
        name: post-init-immich-pgsql-secret
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
```

**Reply by dgsardina** [reply]
I got the same error, even tried adding the following to portInitApplicationSQL. And tried with many tags of the image without success, using either v0.2.0 and 0.2.1 of pgvecto...
@RS185734  Did you get it working?

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.2-v0.2.0

  superuserSecret:
    name: immich-pg-superuser
  enableSuperuserAccess: true

  startDelay: 30
  stopDelay: 100
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart ##@@ Cannot use switchover with 1 instance

  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    enableAlterSystem: true

  storage:
    size: 8Gi

  monitoring:
    enablePodMonitor: false

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-pg-user
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
```

**Comment by dgsardina** [comment]
@RS185734  I made it work... The trick was NOT to create extension 'vector' on postInitApplicationSQL as all the commands here are executed with superuser permissions. The extension is then created by the migrations on the regular app (or immich) user.

```yaml
apiVersion: postgresql.cnpg.io/v1                                                                                                                                                                                                                                                       
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  superuserSecret:
    name: immich-pg-superuser
  enableSuperuserAccess: true
  startDelay: 30
  stopDelay: 100
  primaryUpdateStrategy: unsupervised
  primaryUpdateMethod: restart ##@@ Cannot use switchover with 1 instance
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    enableAlterSystem: true
  storage:
    size: 8Gi
  monitoring:
    enablePodMonitor: false
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-pg-user
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
        # - CREATE EXTENSION IF NOT EXISTS "vector";
        # - ALTER ROLE "immich" WITH "superuser";
```

**Reply by RogerSik** [reply]
This works. Thanks for sharing!

**Comment by RS185734** [comment]
Thanks, @dgsardina For the manifests,

For someone who is importing PostgreSQL from the immich chart 

use below
```
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - ALTER SCHEMA vectors OWNER TO "postgresql_immich_pgsql";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "postgresql_immich_pgsql";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "postgresql_immich_pgsql";
        - CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA pg_catalog;
        - CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA pg_catalog;
  ```

**Reply by 88brmig** [reply]
Latest version (1.132.3) getting the error while doing migrations "public.earth" does not exist, fixed it changing the last two lines, removed schema referencing and now working all good!
``` postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - ALTER SCHEMA vectors OWNER TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich";
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance;
 ```

**Comment by bdsoha** [comment]
@RS185734 I was not able to **backup** the native `bitnami/postgresql` that comes with the chart and restore it on the new `cnpg` cluster instance.

Any suggestions?

**Comment by kriegalex** [comment]
On my side, I checked the Immich [documentation](https://immich.app/docs/administration/postgres-standalone#updating-pgvectors), and it says:

> Typically Immich expects superuser permission in the database, which you can grant by running ALTER USER <immichdbusername> WITH SUPERUSER; at the psql console. If you prefer not to grant superuser permissions, follow the instructions in the next section.

So, I added the line to grant superuser rights. To be safe, I left the two lines required by pgvecto.rs that I already had. My instance is now working. Previously, it complained about permissions issues while creating the vectors extension. 

From the solution above, I see that I was probably missing the `ALTER` and `GRANT` requests, but this setup is more in line with the official documentation. This database should not be reachable outside the cluster, at least it doesn't matter in a homelab environment, I guess.

My Cluster bootstrap section (CloudNativePG) :

```
# Database configuration
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret
      postInitSQL:
        - ALTER USER immich WITH SUPERUSER;
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
```

I leave my error message here, so others can find this discussion thread:

```
[Nest] 7 - 02/12/2025, 4:39:14 AM FATAL [Microservices:DatabaseService] Failed to activate pgvecto.rs extension.
Please ensure the Postgres instance has pgvecto.rs installed.

If the Postgres instance already has pgvecto.rs installed, Immich may not have the necessary permissions to activate it.
In this case, please run 'CREATE EXTENSION IF NOT EXISTS vectors' manually as a superuser.
See https://immich.app/docs/guides/database-queries for how to query the database.

Alternatively, if your Postgres instance has pgvector, you may use this instead by setting the environment variable 'DB_VECTOR_EXTENSION=pgvector'.
Note that switching between the two extensions after a successful startup is not supported.
The exception is if your version of Immich prior to upgrading was 1.90.2 or earlier.
In this case, you may set either extension now, but you will not be able to switch to the other extension following a successful startup.
microservices worker error: QueryFailedError: permission denied to create extension "vectors", stack: QueryFailedError: permission denied to create extension "vectors"
at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
at async DatabaseRepository.createExtension (/usr/src/app/dist/repositories/database.repository.js:85:9)
at async DatabaseService.createExtension (/usr/src/app/dist/services/database.service.js:121:13)
at async /usr/src/app/dist/services/database.service.js:82:17
at async /usr/src/app/dist/repositories/database.repository.js:211:23
microservices worker exited with code 1
Killing api process
```

**Comment by davralin** [comment]
Has someone made the switch to v1.133.0 or above, and still use cnpg?

**Reply by RogerSik** [reply]
Yeah i upgraded Immich to 1.133.0 (and 1.134.0) and it still works fine. pgvector.rs is still supported, but the default is now vectorchord.

I tried to switch to the new default. It is needed to recreate the instance from backup, because cloudnative-pg don't allow to change the image (only the tags).

The db was working fine but immich reported some error so I reverted tp pgvecto.rs. Didn't have the time to investigate more. 

```
-  # https://github.com/tensorchord/cloudnative-pgvecto.rs/pkgs/container/cloudnative-pgvecto.rs	
-  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1

+ # https://github.com/tensorchord/cloudnative-vectorchord/pkgs/container/cloudnative-vectorchord
+ imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0

```

**Reply by bo0tzz** [reply]
> cloudnative-pg don't allow to change the image (only the tags).

Is this documented somewhere? I've changed out the image every time there was a change to the vector extensions and it's been fine with it (except for a bug where it won't restart the primary but that's easily fixed manually).

**Reply by RogerSik** [reply]
Yeah i couldn't apply the manifest with the new image. I got the error that this change is not allowed.

**Reply by RogerSik** [reply]
Interesting I tried it now again (to post the error message here) and the error didn't appear again.

**Reply by christiaangoossens** [reply]
I made the switch today, seems to work but I had to build a custom image. Steps:

1. Update your db image for the cluster to `christiaangoossens/cloudnative-pgvectors-vectorchord:14-vectorchord0.3.0-pgvectors0.2.0`
2. For `shared_preload_libraries`, use both `vectors.so` and `vchord.so` (config example below)
3. Update Immich to 1.133 or later
4. You should see some log lines in the Immich server log that indicate that VectorChord is now used (see example below)
5. Change the image again to `ghcr.io/tensorchord/cloudnative-vectorchord:14-0.3.0` and remove `vectors.so` from `shared_preload_libraries`

Config example initial state:
```
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14-v0.2.0
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
``` 

Config example intermediate state:
```
  imageName: christiaangoossens/cloudnative-pgvectors-vectorchord:14-vectorchord0.3.0-pgvectors0.2.0
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
      - "vchord.so"
```

Config example final state:

```
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:14-0.3.0
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
```

Log line example:
```
[Nest] 6  - 05/31/2025, 10:00:43 AM     LOG [Microservices:DatabaseRepository] Creating VectorChord extension
[Nest] 6  - 05/31/2025, 10:00:43 AM     LOG [Microservices:DatabaseRepository] targetLists=1, current=1 for clip_index of 25126 rows
[Nest] 6  - 05/31/2025, 10:00:43 AM     LOG [Microservices:DatabaseRepository] Reindexing clip_index
[Nest] 6  - 05/31/2025, 10:00:43 AM     LOG [Microservices:DatabaseRepository] targetLists=1, current=1 for face_index of 15350 rows
[Nest] 6  - 05/31/2025, 10:00:43 AM     LOG [Microservices:DatabaseRepository] Reindexing face_index
[Nest] 6  - 05/31/2025, 10:00:45 AM     LOG [Microservices:DatabaseRepository] Reindexed face_index
[Nest] 6  - 05/31/2025, 10:00:48 AM     LOG [Microservices:DatabaseRepository] Reindexed clip_index
[Nest] 6  - 05/31/2025, 10:00:48 AM     LOG [Microservices:DatabaseRepository] Dropping pgvecto.rs extension
```

_Note that the Immich image for `ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0` does not work with cloudnative-pg_

**Reply by bo0tzz** [reply]
Alternatively, the steps at https://immich.app/docs/administration/postgres-standalone/#migrating-to-vectorchord let you migrate straight to the cloudnative-vectorchord image without having both extensions at the same time.

**Reply by christiaangoossens** [reply]
> Alternatively, the steps at https://immich.app/docs/administration/postgres-standalone/#migrating-to-vectorchord let you migrate straight to the cloudnative-vectorchord image without having both extensions at the same time.

True, although I found replacing the image twice to have it all automatically completed easier, especially as immich was already a superuser. It's good to mention both methods here!

**Comment by fbuchmeier** [comment]
If someone is interested, I've just deployed a new instance of immich with a postgresql database managed by the cloudnative-pg operator:

*database*

NOTE: Updated the image from `ghcr.io/immich-app/postgres:15-vectorchord0.3.0-pgvectors0.2.1` to the recommended `ghcr.io/tensorchord/cloudnative-vectorchord:15-0.3.0`. Also I still need to test if this works with the `immich` user not having superuser rights, so please test this on your own.

```yaml
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn-crypto
  monitoring:
    enablePodMonitor: true
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15-0.3.0
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER USER immich WITH SUPERUSER;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
  resources:
    limits:
      cpu: 2
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
```

My helm values then look like this:

```yaml
image:
  tag: v1.134.0
env:
  DB_VECTOR_EXTENSION: vectorchord
  DB_HOSTNAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-app
        key: host
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-app
        key: username
  DB_DATABASE_NAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-app
        key: dbname
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgresql-app
        key: password
```

**Reply by bo0tzz** [reply]
Not sure what you have going on there, but the `ghcr.io/immich-app/postgres:15-vectorchord0.3.0-pgvectors0.2.1` shouldn't (and doesn't) work with CNPG.

**Reply by fbuchmeier** [reply]
Which side effects do you anticipate when using the image with CNPG?
My single node "cluster" is healthy and usable by immich:
<details>
<summary>cluster</summary>

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  creationTimestamp: "2025-06-14T18:59:46Z"
  generation: 2
  labels:
    kustomize.toolkit.fluxcd.io/name: immich
    kustomize.toolkit.fluxcd.io/namespace: default
  name: immich-postgresql
  namespace: default
  resourceVersion: "44399181"
  uid: df56c509-2523-4806-9037-8f009bcc9efa
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      dataChecksums: true
      database: immich
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: immich
      postInitApplicationSQL:
      - ALTER USER immich WITH SUPERUSER;
  enablePDB: true
  enableSuperuserAccess: false
  failoverDelay: 0
  imageName: ghcr.io/immich-app/postgres:15-vectorchord0.3.0-pgvectors0.2.1
  instances: 1
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: true
  postgresGID: 999
  postgresUID: 999
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    shared_preload_libraries:
    - vchord.so
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  resources: {}
  smartShutdownTimeout: 180
  startDelay: 3600
  stopDelay: 1800
  storage:
    resizeInUseVolumes: true
    size: 5Gi
    storageClass: longhorn-crypto
  switchoverDelay: 3600
status:
  availableArchitectures:
  - goArch: amd64
    hash: 024c5162e1dee336b21121d781397b347d04939a857d9d8a47664d1796e8b7c9
  - goArch: arm64
    hash: 63f3a3fbe19b8fe1c26a0e516ecb965c3412e390729a02706825399f585d9298
  certificates:
    clientCASecret: immich-postgresql-ca
    expirations:
      immich-postgresql-ca: 2025-09-12 18:54:46 +0000 UTC
      immich-postgresql-replication: 2025-09-12 18:54:46 +0000 UTC
      immich-postgresql-server: 2025-09-12 18:54:46 +0000 UTC
    replicationTLSSecret: immich-postgresql-replication
    serverAltDNSNames:
    - immich-postgresql-rw
    - immich-postgresql-rw.default
    - immich-postgresql-rw.default.svc
    - immich-postgresql-rw.default.svc.cluster.local
    - immich-postgresql-r
    - immich-postgresql-r.default
    - immich-postgresql-r.default.svc
    - immich-postgresql-r.default.svc.cluster.local
    - immich-postgresql-ro
    - immich-postgresql-ro.default
    - immich-postgresql-ro.default.svc
    - immich-postgresql-ro.default.svc.cluster.local
    serverCASecret: immich-postgresql-ca
    serverTLSSecret: immich-postgresql-server
  cloudNativePGCommitHash: 1535f3c17
  cloudNativePGOperatorHash: 63f3a3fbe19b8fe1c26a0e516ecb965c3412e390729a02706825399f585d9298
  conditions:
  - lastTransitionTime: "2025-06-14T19:02:58Z"
    message: Cluster is Ready
    reason: ClusterIsReady
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-06-14T19:00:44Z"
    message: Continuous archiving is working
    reason: ContinuousArchivingSuccess
    status: "True"
    type: ContinuousArchiving
  configMapResourceVersion:
    metrics:
      cnpg-default-monitoring: "44396991"
  currentPrimary: immich-postgresql-1
  currentPrimaryTimestamp: "2025-06-14T19:00:44.529948Z"
  healthyPVC:
  - immich-postgresql-1
  image: ghcr.io/immich-app/postgres:15-vectorchord0.3.0-pgvectors0.2.1
  instanceNames:
  - immich-postgresql-1
  instances: 1
  instancesReportedState:
    immich-postgresql-1:
      ip: 10.42.11.41
      isPrimary: true
      timeLineID: 1
  instancesStatus:
    healthy:
    - immich-postgresql-1
  latestGeneratedNode: 1
  managedRolesStatus: {}
  pgDataImageInfo:
    image: ghcr.io/immich-app/postgres:15-vectorchord0.3.0-pgvectors0.2.1
    majorVersion: 15
  phase: Cluster in healthy state
  poolerIntegrations:
    pgBouncerIntegration: {}
  pvcCount: 1
  readService: immich-postgresql-r
  readyInstances: 1
  secretsResourceVersion:
    applicationSecretVersion: "44396966"
    clientCaSecretVersion: "44396961"
    replicationSecretVersion: "44396965"
    serverCaSecretVersion: "44396961"
    serverSecretVersion: "44396964"
  switchReplicaClusterStatus: {}
  targetPrimary: immich-postgresql-1
  targetPrimaryTimestamp: "2025-06-14T18:59:47.020502Z"
  timelineID: 1
  topology:
    instances:
      immich-postgresql-1: {}
    nodesUsed: 1
    successfullyExtracted: true
  writeService: immich-postgresql-rw
```
<details>

**Reply by bo0tzz** [reply]
It doesn't meet the requirements from https://cloudnative-pg.io/documentation/1.25/container_images/. Although I see you don't have backups set up, which probably sidesteps the barman part, but not having backups is an awful idea.

**Reply by fbuchmeier** [reply]
Well yes, I have volume snapshots enabled with offsite backups in  longhorn. This should be "good enough" for my lab setup.

Can you recommend a different image with vectorchord 0.3.0 and all the other extensions used by immich (cube?) that is fully compatible? If possible I want to avoid building and maintaining my own image.

Thanks!

**Reply by bo0tzz** [reply]
https://github.com/tensorchord/cloudnative-vectorchord, as was also mentioned upthread.

**Reply by fbuchmeier** [reply]
Thanks, that works for me 🎉 . I've updated my posts accordingly.

**Comment by madimadi** [comment]
Hi,
For those who want to have a fresh and clean new deployment using vchord only, here's what worked for me.
(It doesn't support migration from below immich v1.133.0)

```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgresql
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:15-0.3.0

  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 4Gi
```
Note, there's no "vectors.so" to eliminate failures, but creating extensions `vector` is required.

**Comment by ChristofferNissen** [comment]
Sharing is caring :cake: 

```yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: cnpg-system
spec:
  instances: 2
  imageName: ghcr.io/immich-app/postgres:18-vectorchord1.1.1-pgvector0.8.5
  postgresUID: 999
  postgresGID: 999
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  bootstrap:
    initdb:
      database: immich
      owner: immich
      dataChecksums: true
      postInitApplicationSQL:
        - "CREATE EXTENSION IF NOT EXISTS vector;"
        - "CREATE EXTENSION IF NOT EXISTS vchord CASCADE;"
        - 'CREATE EXTENSION IF NOT EXISTS "cube";'
        - 'CREATE EXTENSION IF NOT EXISTS "earthdistance";'
      secret:
        name: immich-postgresql-secret
  storage:
    size: 10Gi
```
