### DISCUSSION TITLE
api/assets take 10000 crashes server with out of memory (64gb system)

### DISCUSSION THREAD

**Discussion by Dankni95** [immich-app/immich#9241] [Q&A]
### The bug

``
api/asset?skip=10000&take=10000&updatedBefore=2024-05-03T07%3A53%3A04.610024Z&userId=xxxx
``

Crashes my server, 

if i run api call with take 5000 my server does not crash `api/asset?skip=10000&take=5000&updatedBefore=2024-05-03T07%3A53%3A04.610024Z&userId=xxxx`

It seems to me like JSON.stringify is running out of memory when stringifying too many objects. 

More info from other places i have posted this issue:

Im getting this error that crashes immich_server when building the timeline.

```
04/23/2024
11:06:53 PM
<--- Last few GCs --->
04/23/2024
11:06:53 PM
04/23/2024
11:06:53 PM
[6:0x5d52e330000]   917559 ms: Scavenge (reduce) 2044.8 (2081.5) -> 2044.1 (2081.8) MB, 7.28 / 0.00 ms  (average mu = 0.338, current mu = 0.325) allocation failure; 
04/23/2024
11:06:53 PM
[6:0x5d52e330000]   917618 ms: Scavenge (reduce) 2044.9 (2081.8) -> 2044.2 (2081.8) MB, 5.81 / 0.00 ms  (average mu = 0.338, current mu = 0.325) allocation failure; 
04/23/2024
11:06:53 PM
[6:0x5d52e330000]   917681 ms: Scavenge (reduce) 2045.0 (2081.8) -> 2044.4 (2082.0) MB, 4.54 / 0.00 ms  (average mu = 0.338, current mu = 0.325) allocation failure; 
04/23/2024
11:06:53 PM
04/23/2024
11:06:53 PM
04/23/2024
11:06:53 PM
<--- JS stacktrace --->
04/23/2024
11:06:53 PM
04/23/2024
11:06:53 PM
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
04/23/2024
11:06:53 PM
----- Native stack trace -----
04/23/2024
11:06:53 PM
04/23/2024
11:06:53 PM
 1: 0xb84bd6 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [immich_server]
04/23/2024
11:06:53 PM
 2: 0xefeb90 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [immich_server]
04/23/2024
11:06:53 PM
 3: 0xefee77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [immich_server]
04/23/2024
11:06:53 PM
 4: 0x1110885  [immich_server]
04/23/2024
11:06:53 PM
 5: 0x1110e14 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [immich_server]
04/23/2024
11:06:53 PM
 6: 0x1127d04 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*) [immich_server]
04/23/2024
11:06:53 PM
 7: 0x112851c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [immich_server]
04/23/2024
11:06:53 PM
 8: 0x112a67a v8::internal::Heap::HandleGCRequest() [immich_server]
04/23/2024
11:06:53 PM
 9: 0x1095ce7 v8::internal::StackGuard::HandleInterrupts() [immich_server]
04/23/2024
11:06:53 PM
10: 0x1537542 v8::internal::Runtime_StackGuardWithGap(int, unsigned long*, v8::internal::Isolate*) [immich_server]
04/23/2024
11:06:53 PM
11: 0x7fc429e99ef6 
```

Server crashes before reaching 4.3 gb of ram, when i added```- NODE_OPTIONS="--max-old-space-size=24000"``` it now reaches 8gb on my 64gb system. 

With the env variable i got this error:

```
Nest] 7  - 04/22/2024, 5:51:27 PM   ERROR [ExceptionsHandler] Invalid string length
04/22/2024
07:51:27 PM
RangeError: Invalid string length
04/22/2024
07:51:27 PM
    at JSON.stringify (<anonymous>)
04/22/2024
07:51:27 PM
    at stringify (/usr/src/app/node_modules/express/lib/response.js:1159:12)
04/22/2024
07:51:27 PM
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:272:14)
04/22/2024
07:51:27 PM
    at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
04/22/2024
07:51:27 PM
    at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
04/22/2024
07:51:27 PM
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
04/22/2024
07:51:27 PM
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
04/22/2024
07:51:27 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
04/22/2024
07:51:27 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

This is only for 18k photos for this user, total 30k, 64gb allocated.
Help much appreciated.

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Can post if really needed
```

### Your .env content

```Shell
no env
```

### Reproduction steps

```bash
1. upload 15k assets on web
2. try to build timeline on ios/android
3. or call api `api/asset?skip=10000&take=10000&updatedBefore=2024-05-03T07%3A53%3A04.610024Z&userId=xxxx`
...
```

### Relevant log output

```shell
Nest] 7  - 04/22/2024, 5:51:27 PM   ERROR [ExceptionsHandler] Invalid string length
04/22/2024
07:51:27 PM
RangeError: Invalid string length
04/22/2024
07:51:27 PM
    at JSON.stringify (<anonymous>)
04/22/2024
07:51:27 PM
    at stringify (/usr/src/app/node_modules/express/lib/response.js:1159:12)
04/22/2024
07:51:27 PM
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:272:14)
04/22/2024
07:51:27 PM
    at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
04/22/2024
07:51:27 PM
    at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
04/22/2024
07:51:27 PM
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
04/22/2024
07:51:27 PM
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
04/22/2024
07:51:27 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
04/22/2024
07:51:27 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

**Comment by bo0tzz** [comment]
I don't know if there's anything we can do to make `take=10000` possible, I'm inclined to just say "don't do that" :P Maybe we should limit that parameter to an amount that won't crash things though.

**Comment by jrasm91** [comment]
This seems a bit off, since 10k assets should not be using anywhere near the memory limit of your system. Can you provide some details about the hardware and operating system/setup you are using to run immich?

**Reply by Dankni95** [reply]
@jrasm91 Added more info, sorry for late answer.

**Comment by Dankni95** [comment]
```
danny@server:~$ inxi -Fazy
System:
  Kernel: 5.15.0-105-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-5.15.0-105-generic
    root=UUID=71b57f53-7df8-4678-90ff-2491bc881939 ro
  Console: pty pts/0 Distro: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop System: HP product: HP EliteDesk 800 G4 DM 65W v: N/A
    serial: <superuser required> Chassis: type: 6 serial: <superuser required>
  Mobo: HP model: 845A v: KBC Version 07.D4.00 serial: <superuser required>
    UEFI: HP v: Q21 Ver. 02.09.01 date: 10/15/2019
CPU:
  Info: model: Intel Core i5-8500 bits: 64 type: MCP arch: Coffee Lake
    family: 6 model-id: 0x9E (158) stepping: 0xA (10) microcode: 0xF4
  Topology: cpus: 1x cores: 6 smt: <unsupported> cache: L1: 384 KiB
    desc: d-6x32 KiB; i-6x32 KiB L2: 1.5 MiB desc: 6x256 KiB L3: 9 MiB
    desc: 1x9 MiB
  Speed (MHz): avg: 899 high: 900 min/max: 800/4100 scaling:
    driver: intel_pstate governor: powersave cores: 1: 900 2: 900 3: 899 4: 900
    5: 900 6: 900 bogomips: 36000
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
  Vulnerabilities:
  Type: gather_data_sampling mitigation: Microcode
  Type: itlb_multihit status: KVM: Split huge pages
  Type: l1tf
    mitigation: PTE Inversion; VMX: conditional cache flushes, SMT disabled
  Type: mds mitigation: Clear CPU buffers; SMT disabled
  Type: meltdown mitigation: PTI
  Type: mmio_stale_data mitigation: Clear CPU buffers; SMT disabled
  Type: retbleed mitigation: IBRS
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass
    mitigation: Speculative Store Bypass disabled via prctl and seccomp
  Type: spectre_v1
    mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: IBRS, IBPB: conditional, STIBP: disabled, RSB
    filling, PBRSB-eIBRS: Not affected
  Type: srbds mitigation: Microcode
  Type: tsx_async_abort mitigation: TSX disabled
Graphics:
  Device-1: Intel CoffeeLake-S GT2 [UHD Graphics 630]
    vendor: Hewlett-Packard CometLake-S driver: i915 v: kernel ports:
    active: none empty: DP-1, DP-2, DP-3, HDMI-A-1, HDMI-A-2, HDMI-A-3
    bus-ID: 00:02.0 chip-ID: 8086:3e92 class-ID: 0300
  Display: server: No display server data found. Headless machine?
    tty: 127x33
  Message: GL data unavailable in console. Try -G --display
Audio:
  Device-1: Intel Cannon Lake PCH cAVS vendor: Hewlett-Packard
    driver: snd_hda_intel v: kernel alternate: snd_sof_pci_intel_cnl
    bus-ID: 00:1f.3 chip-ID: 8086:a348 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-105-generic running: yes
Network:
  Device-1: Intel Ethernet I219-LM vendor: Hewlett-Packard driver: e1000e
    v: kernel port: N/A bus-ID: 00:1f.6 chip-ID: 8086:15bb class-ID: 0200
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel pcie: gen: 2
    speed: 5 GT/s lanes: 1 bus-ID: 02:00.0 chip-ID: 8086:2723 class-ID: 0280
  IF: wlp2s0 state: down mac: <filter>
  IF-ID-1: br-14dcf5d899bb state: down mac: <filter>
  IF-ID-2: br-6d5399d1faf0 state: down mac: <filter>
  IF-ID-3: br-6daf544d1011 state: down mac: <filter>
  IF-ID-4: br-82805a7e3b1c state: down mac: <filter>
  IF-ID-5: br-a9b575639ebf state: down mac: <filter>
  IF-ID-6: br-d6111d55c623 state: up speed: 10000 Mbps duplex: unknown
    mac: <filter>
  IF-ID-7: br-dbd83ad2ada4 state: down mac: <filter>
  IF-ID-8: br-dc7facddd3fd state: down mac: <filter>
  IF-ID-9: br-e95684473394 state: down mac: <filter>
  IF-ID-10: br-fd5c7c6087f7 state: down mac: <filter>
  IF-ID-11: br-fe90af4602a8 state: down mac: <filter>
  IF-ID-12: docker0 state: up speed: 10000 Mbps duplex: unknown
    mac: <filter>
  IF-ID-13: host-vlan state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-14: iot state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-15: media state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-16: misc state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-17: server state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-18: tun0 state: unknown speed: N/A duplex: N/A mac: N/A
  IF-ID-19: veth04696fc state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-20: veth0d50736 state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-21: veth3e8c251 state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-22: veth40549c7 state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-23: veth4908db7 state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-24: veth650425e state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-25: veth6e00544 state: up speed: 10000 Mbps duplex: full
    mac: <filter>
  IF-ID-26: veth9cb98fa state: up speed: 10000 Mbps duplex: full
    mac: <filter>
Bluetooth:
  Device-1: Intel AX200 Bluetooth type: USB driver: btusb v: 0.8
    bus-ID: 1-14:3 chip-ID: 8087:0029 class-ID: e001
  Report: rfkill ID: hci0 rfk-id: 0 state: down bt-service: not found
    rfk-block: hardware: no software: no address: see --recommends
Drives:
  Local Storage: total: 15.7 TiB used: 10.4 TiB (66.3%)
  SMART Message: Unable to run smartctl. Root privileges required.
  ID-1: /dev/nvme0n1 maj-min: 259:0 vendor: Western Digital
    model: PC SN720 SDAPNTW-256G-1006 size: 238.47 GiB block-size:
    physical: 512 B logical: 512 B speed: 31.6 Gb/s lanes: 4 type: SSD
    serial: <filter> rev: 10112006 temp: 44.9 C scheme: GPT
  ID-2: /dev/sda maj-min: 8:0 type: USB model: HAT5300-16T size: 14.55 TiB
    block-size: physical: 4096 B logical: 512 B type: N/A serial: N/A
    scheme: GPT
  ID-3: /dev/sdb maj-min: 8:16 type: USB vendor: Seagate
    model: ST1000LM024 HN-M101MBB size: 931.51 GiB block-size: physical: 512 B
    logical: 512 B type: HDD rpm: 5400 serial: <filter> rev: 0608 scheme: MBR
Partition:
  ID-1: / raw-size: 237.42 GiB size: 232.64 GiB (97.98%)
    used: 95.86 GiB (41.2%) fs: ext4 dev: /dev/nvme0n1p2 maj-min: 259:2
  ID-2: /boot/efi raw-size: 1.05 GiB size: 1.05 GiB (99.80%)
    used: 6.1 MiB (0.6%) fs: vfat dev: /dev/nvme0n1p1 maj-min: 259:1
Swap:
  Kernel: swappiness: 60 (default) cache-pressure: 100 (default)
  ID-1: swap-1 type: file size: 4 GiB used: 137.5 MiB (3.4%) priority: -2
    file: /swap.img
Sensors:
  System Temperatures: cpu: 30.0 C pch: 42.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Info:
  Processes: 369 Uptime: 2d 2h 14m wakeups: 1 Memory: 62.58 GiB
  used: 7.12 GiB (11.4%) Init: systemd v: 249 runlevel: 5 tool: systemctl
  Compilers: gcc: 11.4.0 alt: 11/12 Packages: 996 apt: 991 lib: 496 snap: 5
  Shell: Bash v: 5.1.16 running-in: pty pts/0 (SSH) inxi: 3.3.13
```

```
name: big-bear-immich
services:
  database:
    cpu_shares: 90
    command: []
    container_name: immich-postgres
    deploy:
      resources:
        limits:
          memory: 64077M
    environment:
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=immich
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_USER=casaos
    hostname: immich-postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/hdd/Gallery/pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database Password
        - container: POSTGRES_USER
          description:
            en_us: Database Username
        - container: POSTGRES_DB
          description:
            en_us: Database Name
        - container: PG_DATA
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
    ports: []
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
  immich-machine-learning:
    cpu_shares: 90
    command: []
    container_name: immich-machine-learning
    deploy:
      resources:
        limits:
          memory: 64077M
    environment:
      - DB_DATABASE_NAME=casaos
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=xxxx
      - DB_PORT=5432
      - DB_USERNAME=casaos
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.103.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/hdd/Gallery/model-cache
        target: /cache
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: Database Hostname
        - container: DB_USERNAME
          description:
            en_us: Database Username
        - container: DB_PASSWORD
          description:
            en_us: Database Password
        - container: DB_DATABASE_NAME
          description:
            en_us: Database Name
        - container: DB_PORT
          description:
            en_us: Database Port
        - container: REDIS_HOSTNAME
          description:
            en_us: Redis Hostname
      volumes:
        - container: /cache
          description:
            en_us: "Container Path: /cache"
    ports: []
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
  immich-microservices:
    cpu_shares: 90
    command:
      - start.sh
      - microservices
    container_name: immich-microservices
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 64077M
    devices:
      - /dev/dri:/dev/dri
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=xxxx
      - DB_PORT=5432
      - DB_USERNAME=casaos
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-microservices
    image: ghcr.io/immich-app/immich-server:v1.103.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/hdd/Gallery/upload
        target: /usr/src/app/upload
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: Database Hostname
        - container: DB_USERNAME
          description:
            en_us: Database Username
        - container: DB_PASSWORD
          description:
            en_us: Database Password
        - container: DB_DATABASE_NAME
          description:
            en_us: Database Name
        - container: DB_PORT
          description:
            en_us: Database Port
        - container: REDIS_HOSTNAME
          description:
            en_us: Redis Hostname
      volumes:
        - container: /usr/src/app/upload
          description:
            en_us: "Container Path: /usr/src/app/upload"
    ports: []
    cap_add: []
    networks:
      - default
    privileged: false
  immich-server:
    cpu_shares: 90
    command:
      - start.sh
      - immich
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 64077M
    environment:
      - DB_DATABASE_NAME=immich
      - DB_HOSTNAME=immich-postgres
      - DB_PASSWORD=xxxx
      - DB_PORT=5432
      - DB_USERNAME=casaos
      - IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
      - LOG_LEVEL=verbose
      - NODE_OPTIONS=--max-old-space-size=24000
      - REDIS_HOSTNAME=immich-redis
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:v1.103.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    ports:
      - mode: ingress
        target: 3001
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/hdd/Gallery/upload
        target: /usr/src/app/upload
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: DB_HOSTNAME
          description:
            en_us: Database Hostname
        - container: DB_USERNAME
          description:
            en_us: Database Username
        - container: DB_PASSWORD
          description:
            en_us: Database Password
        - container: DB_DATABASE_NAME
          description:
            en_us: Database Name
        - container: DB_PORT
          description:
            en_us: Database Port
        - container: REDIS_HOSTNAME
          description:
            en_us: Redis Hostname
        - container: IMMICH_MACHINE_LEARNING_URL
          description:
            en_us: Immich Machine Learning URL
      ports:
        - container: "3001"
          description:
            en_us: "Container Port: 3001"
      volumes:
        - container: /usr/src/app/upload
          description:
            en_us: "Container Path: /usr/src/app/upload"
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
  redis:
    cpu_shares: 90
    command: []
    container_name: immich-redis
    deploy:
      resources:
        limits:
          memory: 64077M
    hostname: immich-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: always
    ports: []
    volumes: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - default
    privileged: false
networks:
  default:
    name: big-bear-immich_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Self-hosted photo and video storage.
  developer: ""
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  index: /
  is_uncontrolled: false
  main: immich-server
  port_map: "2283"
  scheme: http
  store_app_id: big-bear-immich
  tagline:
    en_us: Immich
  thumbnail: ""
  title:
    custom: ""
    en_us: Immich
```


```
{
  "ffmpeg": {
    "crf": 23,
    "threads": 0,
    "preset": "veryfast",
    "targetVideoCodec": "h264",
    "acceptedVideoCodecs": [
      "h264"
    ],
    "targetAudioCodec": "aac",
    "acceptedAudioCodecs": [
      "aac",
      "mp3",
      "libopus"
    ],
    "targetResolution": "720",
    "maxBitrate": "0",
    "bframes": -1,
    "refs": 0,
    "gopSize": 0,
    "npl": 0,
    "temporalAQ": false,
    "cqMode": "auto",
    "twoPass": false,
    "preferredHwDevice": "auto",
    "transcode": "required",
    "tonemap": "hable",
    "accel": "qsv"
  },
  "job": {
    "backgroundTask": {
      "concurrency": 5
    },
    "smartSearch": {
      "concurrency": 2
    },
    "metadataExtraction": {
      "concurrency": 5
    },
    "faceDetection": {
      "concurrency": 2
    },
    "search": {
      "concurrency": 5
    },
    "sidecar": {
      "concurrency": 5
    },
    "library": {
      "concurrency": 5
    },
    "migration": {
      "concurrency": 5
    },
    "thumbnailGeneration": {
      "concurrency": 5
    },
    "videoConversion": {
      "concurrency": 1
    }
  },
  "logging": {
    "enabled": true,
    "level": "debug"
  },
  "machineLearning": {
    "enabled": true,
    "url": "http://immich-machine-learning:3003",
    "clip": {
      "enabled": true,
      "modelName": "ViT-B-32__openai"
    },
    "facialRecognition": {
      "enabled": true,
      "modelName": "buffalo_l",
      "minScore": 0.7,
      "maxDistance": 0.5,
      "minFaces": 3
    }
  },
  "map": {
    "enabled": true,
    "lightStyle": "",
    "darkStyle": ""
  },
  "reverseGeocoding": {
    "enabled": false
  },
  "oauth": {
    "autoLaunch": false,
    "autoRegister": false,
    "buttonText": "Login with OAuth",
    "clientId": "xxxx",
    "clientSecret": "xxxx",
    "defaultStorageQuota": 1,
    "enabled": true,
    "issuerUrl": "https://accounts.google.com",
    "mobileOverrideEnabled": true,
    "mobileRedirectUri": "xxxx/api/oauth/mobile-redirect",
    "scope": "openid email profile",
    "signingAlgorithm": "RS256",
    "storageLabelClaim": "preferred_username",
    "storageQuotaClaim": "immich_quota"
  },
  "passwordLogin": {
    "enabled": true
  },
  "storageTemplate": {
    "enabled": true,
    "hashVerificationEnabled": true,
    "template": "{{y}}/{{MM}}/{{filename}}"
  },
  "image": {
    "thumbnailFormat": "webp",
    "thumbnailSize": 250,
    "previewFormat": "jpeg",
    "previewSize": 1440,
    "quality": 80,
    "colorspace": "p3",
    "extractEmbedded": false
  },
  "newVersionCheck": {
    "enabled": true
  },
  "trash": {
    "enabled": true,
    "days": 30
  },
  "theme": {
    "customCss": ""
  },
  "library": {
    "scan": {
      "enabled": true,
      "cronExpression": "0 0 * * *"
    },
    "watch": {
      "enabled": false
    }
  },
  "server": {
    "externalDomain": "xxx",
    "loginPageMessage": "Hei alle sammen - hilsen danny"
  },
  "user": {
    "deleteDelay": 7
  }
}
```

![image](https://github.com/immich-app/immich/assets/71786017/6211f42a-b761-4881-8fb6-6d3cb7baa2c0)


I am happy to provide more information if needed
Thanks
