### DISCUSSION TITLE
Not able to upload files larger than 1gb from web portal same file gets stuck at 100% ios app

### DISCUSSION THREAD

**Discussion by PR4SAN** [immich-app/immich#9519] [Q&A]
### The bug

-Not able to upload files larger than 1gb from web portal or ios app.
-in ios ap after 100% it gets stuck there and won's say success.

https://github.com/immich-app/immich/assets/20751006/a481400e-1fbc-4e8a-9cf6-048f1487a26d

<img width="452" alt="Screenshot 2024-05-15 at 15 44 57" src="https://github.com/immich-app/immich/assets/20751006/346c554c-5b2c-4fe1-9afd-767af89035a2">

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.103.0 build.155

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=mypassword

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Take any file above 1gb
2. Upload via mobile app
3. Upload via web app
```

### Relevant log output

```shell
web portal logs

[Nest] 7  - 05/15/2024, 11:53:12 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    Eq6WHVyD8Ckv0ptVAABF
[Nest] 7  - 05/15/2024, 11:53:23 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: Eq6WHVyD8Ckv0ptVAABF
[Nest] 7  - 05/15/2024, 11:58:25 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    NP7EfywC6WpKFgC0AABH
[Nest] 7  - 05/15/2024, 12:00:20 PM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: NP7EfywC6WpKFgC0AABH
[Nest] 7  - 05/15/2024, 12:30:00 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    p7QFWq82czNZIJOOAABJ
[Nest] 7  - 05/15/2024, 12:30:42 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    rmoVATrmYmzcOzhMAABL
[Nest] 7  - 05/15/2024, 12:30:47 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:47 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:48 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:48 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:48 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:48 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:30:49 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:30:54 PM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: rmoVATrmYmzcOzhMAABL
[Nest] 7  - 05/15/2024, 12:32:46 PM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: p7QFWq82czNZIJOOAABJ
[Nest] 7  - 05/15/2024, 12:34:37 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    b8ocrSo9gsHzI-MlAABN
[Nest] 7  - 05/15/2024, 12:35:35 PM     LOG [ImmichServer] [EventRepository] Websocket Connect:    VfsWKK8YVFc1PoGSAABP
[Nest] 7  - 05/15/2024, 12:35:36 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:35:36 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:35:37 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:35:37 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:35:41 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:35:41 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:35:41 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:35:41 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:36:44 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:36:44 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:36:45 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:36:45 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:39:36 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:39:36 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:39:42 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:39:42 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE
[Nest] 7  - 05/15/2024, 12:39:43 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Failed to serve file
[Nest] 7  - 05/15/2024, 12:39:43 PM   ERROR [ImmichServer] [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:95:16)
    at WriteWrap.callbackTrampoline (node:internal/async_hooks:130:17)] Error: write EPIPE



For IOS app i cleared the log and then started backup. there is no logs when it gets stuck at 100%.
```
