### DISCUSSION TITLE
[BUG] Explore page empty when Machine Learning is disabled

### DISCUSSION THREAD

**Discussion by pig-cop** [immich-app/immich#9536] [Q&A]
### The bug

When Machine Learning is disabled the Explore page doesn't work properly.
Before it was possible to access Recently Added and other categories from there, now there's only an empty page.

![image](https://github.com/immich-app/immich/assets/1793444/155c714e-6d65-4a73-ae66-16ae847f0d3b)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1 build.139

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${TAG}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${TAG}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:

      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_MACHINE_LEARNING_ENABLED = false
```

### Reproduction steps

```bash
1. Disable Machine Learning by removing the container from docker-compose.yml
2. Add IMMICH_MACHINE_LEARNING_ENABLED environment variable, set it to false
3. Disable Machine Learning in Settings
3. Check Search and Explore from Web
```
