### DISCUSSION TITLE
RAW MAX (iPhone 15 Pro) previews are too dark

### DISCUSSION THREAD

**Discussion by twiesing** [immich-app/immich#9547] [Q&A] [answered]
### The bug

Photoprism (and iOS Photo Library):
![IMG_4061](https://github.com/immich-app/immich/assets/436986/e1089c53-56d8-48fd-bdd3-c07a4dfac97b)

Immich:
![IMG_4060](https://github.com/immich-app/immich/assets/436986/12da00b0-f564-4729-a4f6-9baf12e93086)

### The OS that Immich Server is running on

Docker

### Version of Immich Server

Latest

### Version of Immich Mobile App

Latest

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    networks:
      - default
      - proxy_apps
    image: ghcr.io/immich-app/immich-server:v1.105.1
    command: ['start.sh', 'immich']
    volumes:
      - upload_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - photoprism_app_originals:/mnt/photoprism:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    cpus: 1.0

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.105.1
    devices:
      - /dev/dri:/dev/dri
    command: ['start.sh', 'microservices']
    volumes:
      - upload_data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - photoprism_app_originals:/mnt/photoprism:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    cpus: 1.0

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.105.1
    volumes:
      - model_cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    cpus: 1.0

  redis:
    container_name: immich_redis
    image: redis:7-alpine
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.immichdbbackup.schedule: "0 0 1 * * *"
      ofelia.job-exec.immichdbbackup.command: "sh -c 'pg_dumpall -U immich -f /var/lib/postgresql/data/backup.sql'"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  offlineremover:
    image: ghcr.io/hueske-digital/immich:removeoffline
    labels:
      ofelia.restart: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.immichofflineremover.schedule: "0 40 * * * *"
      ofelia.job-exec.immichofflineremover.command: "sh -c 'bash /removeofflineimages.sh'"
    environment:
      - API_TOKEN
      - LIBRARY_IDS
      - BASE_URL
    restart: unless-stopped

networks:
  proxy_apps:
    name: proxy_apps
    external: true

volumes:
  model_cache:
  db_data:
  upload_data:
  photoprism_app_originals:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

DB_USERNAME=immich
DB_PASSWORD=immich
DB_HOSTNAME=immich_postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# Offline Remover
API_TOKEN=""
LIBRARY_IDS="1,2"
BASE_URL="https://test.example.com"
```

### Reproduction steps

```bash
Upload this https://we.tl/t-8zfFD9DhXi RAw image
```
