### DISCUSSION TITLE
External library - path to inore

### DISCUSSION THREAD

**Discussion by cgeheim** [immich-app/immich#9609] [Q&A] [answered]
### The bug

I used immich  on my synology nas.

I use an external library:

Synology external folder:      /volume2/immich_extern
Synology folder for trash:     /volume2/immich_extern/#recycle

When I delete an object it goes into the synology trash folder:  /volume2/immich_extern/#recycle
In Immich I do not find a way to exclude the trash folder in the scan settings
Immich Text: To ignore an absolute path, use "/path/to/ignore/**".    ( Tried /volume2/immich_extern/#recycle/**)
But what is the correct path for the folder: /volume2/immich_extern/#recycle

I tried my versions, but nothing works

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
 
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    container_name: immich_server
    hostname: immich-server
    networks:
      default:
        ipv4_address: 192.168.0.46
    user: 1026:101
    env_file:
      - stack.env
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
    restart: always
    depends_on:
     - immich-redis
     - immich-db


  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-learning
    hostname: immich-machine-learning
    user: 1026:101
    networks:
      default:
        ipv4_address: 192.168.0.48
    ports:
      - 2283:3003   
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume2/immich/cache:/cache
    restart: always
        
  immich-redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:c0634a08e74a4bb576d02d1ee993dc05dba10e8b7b9492dfa28a7af100d46c01
    hostname: immich-redis
    networks:
      default:
        ipv4_address: 192.168.0.44
    ports:
      - 6379:6379    
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 5m
      timeout: 5s
      retries: 5
    user: 1026:10
    environment:
     - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: always

  immich-db:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    hostname: immich-db
    networks:
      default:
        ipv4_address: 192.168.0.45
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 5m
      timeout: 5s
      retries: 5
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - /volume2/immich/backup:/backup
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=HuGvs2024iW!
      - POSTGRES_INITDB_ARGS= '--data-checksums'
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]


networks:
  default:
    name: mvl
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume2/immich
DB_HOSTNAME=XXX
DB_USERNAME=XXXX
DB_PASSWORD=XXXX
DB_DATABASE_XXXX
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=X
IMMICH_SERVER_X
IMMICH_MACHINE_LEARNING_URL=X
TZ=Europe/Berlin
EXTERNAL_PATH=/volume2/immich_extern
POSTGRES_HOST_AUTH_METHOD=trust
DB_DATA_LOCATION=/volume2/immich/db-14
```

### Reproduction steps

```bash
1. delete an object from the external library, it goes into the synology trash folder
2.scan otions To ignore an absolute path /volume2/immich_extern/#recycle/**
3.Rescan and remove offline file from the external library
4. object always in library
...
```
