### DISCUSSION TITLE
Oauth2 help

### DISCUSSION THREAD

**Discussion by ghost** [immich-app/immich#981] [Q&A] [answered]
Hello, I read the information in the documentation, but I was not successful in integrating immich with authentik, am I doing something wrong?

This is my env file:
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres_username
DB_PASSWORD=postgres_password
DB_DATABASE_NAME=immich_name
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/apps/selfhosted/immich/upload
LOG_LEVEL=simple
JWT_SECRET=secret
PUBLIC_LOGIN_PAGE_MESSAGE="Welcome to immich"

OAUTH_ENABLED=true
OAUTH_ISSUER_URL=https://my_authentik.tld/application/o/immich/.well-known/openid-configuration
OAUTH_CLIENT_ID=secret
OAUTH_CLIENT_SECRET=secret
OAUTH_REDIRECT_URI=https://my_immich.tdl/auth/login
OAUTH_TOKEN_RESPONSE_ALG=HS256
OAUTH_AUTO_REGISTER=true
OAUTH_BUTTON_TEXT=Login with Authentik
```

This is my configuration inside authentik:

![image](https://user-images.githubusercontent.com/41516742/202218866-d87cadc0-a69e-49cb-9ccc-ac810cdd50e9.png)

And this is my compose file:

```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich

  immich-machine-learning:
    container_name: immich_machine-learning
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always
    networks:
      - immich

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    restart: always
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    volumes:
      - /apps/selfhosted/immich/redis:/data
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /apps/selfhosted/immich/data:/var/lib/postgresql/data
    restart: always
    networks:
      - immich

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - immich

networks:
 immich:
  external: true
```
