### DISCUSSION TITLE
How to enable face recognition

### DISCUSSION THREAD

**Discussion by nsu700** [immich-app/immich#9960] [Q&A]
### The bug

I have deployed immich at the beginning without the machinelearning container, now all are running smoothly and I decided to try the face recognition, hence I have uncommented the machine-learning docker-compose yaml, however there is no people detected in the explore tab, I have tried disable and reenabled the machine-learning in the setting, but not work

### The OS that Immich Server is running on

QNAP NAS Standalone 20.10.22-qnap7

### Version of Immich Server

v1.105.0

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.105.0
    command: ['start.sh', 'immich']
    volumes:
      - /share/CACHEDEV1_DATA/Multimedia/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    environment:
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.105.0
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    environment:
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich   
    volumes:
      - /share/CACHEDEV1_DATA/Multimedia/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /share/CACHEDEV1_DATA/Multimedia/immich/postgres:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v1.105.0
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /share/CACHEDEV1_DATA/Multimedia/immich/model-cache:/cache
    environment:
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    restart: always
```

### Your .env content

```Shell
NA, I do not have the env file
```

### Reproduction steps

```bash
1. Commented out the machine-learning section of the above yaml
2. Uncommented the machine-learning section
```

### Relevant log output

```shell
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/shared-link/:id/assets, DELETE} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] SyncController {/api/sync}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-config/map/style.json, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] TagController {/api/tag}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id, PATCH} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id, DELETE} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id/assets, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id/assets, PUT} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/tag/:id/assets, DELETE} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] TimelineController {/api/timeline}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] TrashController {/api/trash}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RoutesResolver] UserController {/api/user}:
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/info/:id, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/me, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/profile-image, DELETE} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/:id, DELETE} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/:id/restore, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user, PUT} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/profile-image, POST} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [RouterExplorer] Mapped {/api/user/profile-image/:id, GET} route
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [NestApplication] Nest application successfully started
[Nest] 6  - 06/03/2024, 7:46:37 AM     LOG [ImmichServer] [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.105.0] [PRODUCTION] 
[Nest] 6  - 06/03/2024, 7:46:42 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    -JIJ9f5fvbE1775iAAAB
[Nest] 6  - 06/03/2024, 7:48:46 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: -JIJ9f5fvbE1775iAAAB
[Nest] 6  - 06/03/2024, 7:48:47 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    NCvGmudgT2Z-VUC2AAAD
[Nest] 6  - 06/03/2024, 7:48:50 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:48:50 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:48:50 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:50:06 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:50:08 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:50:08 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:51:15 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 7:56:24 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 8:00:15 AM   ERROR [ImmichServer] [Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at doWrite (node:internal/streams/writable:590:12)
    at clearBuffer (node:internal/streams/writable:774:7)
    at Writable.uncork (node:internal/streams/writable:523:7)
    at connectionCorkNT (node:_http_outgoing:981:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] Failed to serve file
[Nest] 6  - 06/03/2024, 8:00:15 AM   ERROR [ImmichServer] [Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:161:15)
    at writeGeneric (node:internal/stream_base_commons:152:3)
    at Socket._writeGeneric (node:net:953:11)
    at Socket._write (node:net:965:8)
    at doWrite (node:internal/streams/writable:590:12)
    at clearBuffer (node:internal/streams/writable:774:7)
    at Writable.uncork (node:internal/streams/writable:523:7)
    at connectionCorkNT (node:_http_outgoing:981:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)] Error: write EPIPE
[Nest] 6  - 06/03/2024, 8:00:15 AM     LOG [ImmichServer] [AuditService] Found 0 original files, 15652 thumbnails, 1330 encoded videos, 0 profile files
[Nest] 6  - 06/03/2024, 8:00:21 AM     LOG [ImmichServer] [AuditService] Found 8276 assets, 2 users, 0 people
[Nest] 6  - 06/03/2024, 8:01:45 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 8:05:06 AM     LOG [ImmichServer] [LibraryService] Creating EXTERNAL library for 06ddaa50-bfd4-48cd-b912-b8b089b4d732}
[Nest] 6  - 06/03/2024, 8:16:00 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: NCvGmudgT2Z-VUC2AAAD
[Nest] 6  - 06/03/2024, 8:16:00 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    u_dJbrEYCGZm9HBWAAAF
[Nest] 6  - 06/03/2024, 8:16:45 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: u_dJbrEYCGZm9HBWAAAF
[Nest] 6  - 06/03/2024, 8:25:44 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    YJYR1_svpFeMwy1uAAAH
[Nest] 6  - 06/03/2024, 8:28:18 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    rt7fGRKbPGLu2XlJAAAJ
[Nest] 6  - 06/03/2024, 8:28:24 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: YJYR1_svpFeMwy1uAAAH
[Nest] 6  - 06/03/2024, 8:39:04 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: rt7fGRKbPGLu2XlJAAAJ
[Nest] 6  - 06/03/2024, 8:46:47 AM    WARN [ImmichServer] [Error: Failed to fetch GitHub release: TypeError: fetch failed
    at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/repositories/server-info.repository.js:22:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ServerInfoService.handleVersionCheck (/usr/src/app/dist/services/server-info.service.js:143:35)
    at async ApiService.onVersionCheck (/usr/src/app/dist/services/api.service.js:69:9)
    at async Timeout._onTimeout (/usr/src/app/node_modules/@nestjs/schedule/dist/schedule.explorer.js:96:17)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
[Nest] 6  - 06/03/2024, 8:47:57 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    kKw_W4JgkY9qv7xeAAAL
[Nest] 6  - 06/03/2024, 8:58:59 AM     LOG [ImmichServer] [EventRepository] Websocket Connect:    2YuaxeOS9PtnjYfrAAAN
[Nest] 6  - 06/03/2024, 8:59:44 AM     LOG [ImmichServer] [EventRepository] Websocket Disconnect: 2YuaxeOS9PtnjYfrAAAN
[Nest] 6  - 06/03/2024, 9:03:50 AM     LOG [ImmichServer] [SystemConfigService] LogLevel=log (set via system config)
[Nest] 6  - 06/03/2024, 9:03:50 AM     LOG [ImmichServer] [SystemConfigService] LogLevel=log (set via system config)
[Nest] 6  - 06/03/2024, 9:05:21 AM     LOG [ImmichServer] [SystemConfigService] LogLevel=log (set via system config)
[Nest] 6  - 06/03/2024, 9:05:21 AM     LOG [ImmichServer] [SystemConfigService] LogLevel=log (set via system config)
[Nest] 6  - 06/03/2024, 9:06:42 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 6  - 06/03/2024, 9:06:45 AM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
```

### Additional information

I found the volumn mounted by the machine-learning container, it is empty, but the container is running 
```
[06/03/24 07:49:49] INFO     Starting gunicorn 22.0.0                           
[06/03/24 07:49:49] INFO     Listening at: http://[::]:3003 (9)                 
[06/03/24 07:49:49] INFO     Using worker: app.config.CustomUvicornWorker       
[06/03/24 07:49:49] INFO     Booting worker with pid: 13                        
[06/03/24 07:51:18] WARNING  Matplotlib is building the font cache; this may    
                             take a moment.                                     
[06/03/24 07:51:49] INFO     Started server process [13]                        
[06/03/24 07:51:49] INFO     Waiting for application startup.                   
[06/03/24 07:51:49] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[06/03/24 07:51:49] INFO     Initialized request thread pool with 4 threads.    
[06/03/24 07:51:49] INFO     Application startup complete.                      
[06/03/24 09:10:38] INFO     Starting gunicorn 22.0.0                           
[06/03/24 09:10:38] INFO     Listening at: http://[::]:3003 (9)                 
[06/03/24 09:10:38] INFO     Using worker: app.config.CustomUvicornWorker       
[06/03/24 09:10:38] INFO     Booting worker with pid: 13                        
[06/03/24 09:11:12] INFO     Started server process [13]                        
[06/03/24 09:11:12] INFO     Waiting for application startup.                   
[06/03/24 09:11:12] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[06/03/24 09:11:12] INFO     Initialized request thread pool with 4 threads.    
[06/03/24 09:11:12] INFO     Application startup complete.                      
```
