### DISCUSSION TITLE
External Library - Permissions Denied on NFS shares, and mkdir on existing folders

### DISCUSSION THREAD

**Discussion by huntervcx** [immich-app/immich#9977] [Q&A]
### The bug

Trying to setup an external library, reading on a mounted NFS share (hosted on TrueNAS Scale), with 777 permissions and www-data as owner

When i try to set a external library in docker compose to the NFS share : 
`Error response from daemon: error while creating mount source path '/mnt/my_nfs_mount/my_username/Pictures': mkdir /mnt/my_nfs_mount/my_username/: permission denied`

Tried to set a symbolic link to the nefs share in my home repo, different error : 
`Error response from daemon: error while creating mount source path '/mnt/my_nfs_mount/my_username/Pictures': mkdir /mnt/my_nfs_mount/my_username/Pictures: file exists`

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/my_nfs_mount/my_username/Pictures:/mnt/my_nfs_mount/my_username/Pictures:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/my_nfs_mount/my_username/Pictures:/mnt/my_nfs_mount/my_username/Pictures:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_>

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=**redacted**

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Mount an NFS share stored on a TrueNas Scale
2. Try to mount it as an external library
3.
...
```

**Comment by Biepa** [comment]
Having the same issue.

**Comment by huntervcx** [comment]
@bo0tzz any updates or clue to help on this ? still an issue for some of us

**Reply by bo0tzz** [reply]
This seems like it's not an Immich issue but an issue with your docker installation or mounts/filesystem permissions, which I don't really have insight into.

**Reply by Biepa** [reply]
My setup works fine for a lot of other containers. That's why I assume it has to do at least partially with the way Immich works or with the libraries/tools immich uses. I'm not sure how to troubleshoot it though and will be happy to provide every info needed.

**Reply by huntervcx** [reply]
Same here, this folder works perfectly with nextcloud and plex containers, only immich report permissions problems of try to create folders event with an external configured in :RO

**Reply by Biepa** [reply]
I'm not even using ":RO" in case it matters.

**Reply by huntervcx** [reply]
tried it too, no changes. even in RO, immich-server docker file seems to try to create a folder, and return a permission denied

**Reply by sabya14** [reply]
@huntervcx I had the same issue in a different setup, I was installing Immich in Proxmox LXC container. I mounted the smb share to the container, but somehow the docker container didnot have permission to write to it. I changed my container from unprivileged to privileged and it started working. Though I would want to solve it in a better way later.

**Reply by huntervcx** [reply]
Just tried to set all containers in privileged mode, still getting the same error

The thing that i don't understand is that my upload_location is an nfs share also, but with www-data as owner

**Reply by Acumane** [reply]
Have you tried running as a non-root user? You can set this in your docker compose:
```yaml
...
immich-server:
  user: "1000:1000"
  ...
```
