### ISSUE TITLE
 [BUG] Timeline endpoint returns the wrong video duration

### ISSUE THREAD

**Issue by RWDai** [immich-app/immich#10007]
### The bug

The `api/timeline/bucket` retruns here
<img width="510" alt="iShot_2024-06-06_13 14 56" src="https://github.com/immich-app/immich/assets/27391645/d2a3b239-2f22-43e2-baa1-2593f842465e">
But the actual video duration。
<img width="1394" alt="iShot_2024-06-06_13 15 48" src="https://github.com/immich-app/immich/assets/27391645/9b8c2ff0-a999-4284-8be9-1d8dc0f99536">
Test video shot by a7c2。

### The OS that Immich Server is running on

unraid

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'
services:
  postgres:
    container_name: postgres
    # image: postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - /mnt/user/appdata/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=xxxx
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - /mnt/user/appdata/redis/data:/data
      - /mnt/user/appdata/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    
  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    ports:
      - 18086:80
    volumes:
      - /mnt/user/appdata/nextcloud/html:/var/www/html
      - /mnt/user/appdata/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/user/appdata/nextcloud/config:/var/www/html/config
      - /mnt/user/appdata/nextcloud/data:/var/www/html/data
    environment:
      - POSTGRES_HOST=xxx
      - POSTGRES_DB=xxx
      - POSTGRES_USER=xx
      - POSTGRES_PASSWORD=xx
      - NEXTCLOUD_ADMIN_PASSWORD=xxx
      - NEXTCLOUD_ADMIN_USER=xx
    depends_on:
      - postgres

  code:
    container_name: nextcloud-code
    ports:
      - 18087:9980
    environment:
      - DONT_GEN_SSL_CERT=yes 
      - extra_params=--o:ssl.enable=false  
      - username=xxxx
      - password=xxxxx
    restart: always
    depends_on:
      - nextcloud
    image: collabora/code

  immich:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    restart: always
    ports:
      - 2283:3001
    volumes:
     - /mnt/user/appdata/immich/upload:/usr/src/app/upload
     - /mnt/user/Photo:/mnt/media/photo:ro
     - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=xxxx
      - DB_PASSWORD=xxxx
      - DB_DATABASE_NAME=immich
      - DB_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    command: ['start.sh', 'immich']

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    command: ['start.sh', 'microservices']
    volumes:
      - /mnt/user/appdata/immich/upload:/usr/src/app/upload
      - /mnt/user/Photo:/mnt/media/photo:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=xxxx
      - DB_PASSWORD=xxxx
      - DB_DATABASE_NAME=immich
      - DB_PORT=5432
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    restart: always
  
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    # image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - /mnt/user/appdata/immich/ml-cache:/cache
    restart: always
```

### Your .env content

```Shell
none
```

### Reproduction steps

```bash
1. This test vedio is at external library（/mnt/user/Photo:/mnt/media/photo）。
```
