### ISSUE TITLE
[Feature]: Oauth & Authelia & Self-signed cert

### ISSUE THREAD

**Issue by CKranebitter** [immich-app/immich#1005]
### Feature detail

Thanks for the Oidc-Feature.
I have Authelia configured.
My Issuer Url is: `https://auth.example.local/api/oidc/authorization`
Nest complains on `immich-server:3001`:

<img width="974" alt="Screenshot 2022-11-22 at 11 12 00" src="https://user-images.githubusercontent.com/63287042/203288371-cba44c9a-d23f-4e2a-9b2e-ea99c001754c.png">

Frontend gives me a 500.
I added my root-certificate to the trust store of the server-container.
But Axios seems to don't care.
Is there any way to circumvent this check?
Thanks for the help.

Best regards & I hope you have the energy to keep up the great work.

### Platform

Server

**Comment by d-sko** [comment]
I have a similar setup with authentik. You have to point node to your CA cert by adding an environment-variable: `NODE_EXTRA_CA_CERTS=<path to your CA cert file>`

**Comment by CKranebitter** [comment]
@d-sko 
Ah. Ok. Seems this would solve my issue. Could you offer a bit of guidance where to place this in the immich-server context? In which file did you place it exactly?

Would be great if immich would allow to set a CA-cert via the environment-variables of the app.

**Comment by d-sko** [comment]
In  `docker-compose.yml` I added a volume to the volume to the service definition of the `immich-server`-service to have my CA cert available in the container and then I added the environment variable to make node aware of it. This is the full service definition then:
```yaml
services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
# add cert via read only volume
      - /path/to/my-ca-cert:/ca-certs/my-ca-cert:ro
    env_file:
      - .env
    environment:
# add environment variable
      - NODE_EXTRA_CA_CERTS=/ca-certs/my-ca-cert
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
```
