### ISSUE TITLE
VAAPI AV1 encoding not supported

### ISSUE THREAD

**Issue by mkottman** [immich-app/immich#10056]
### The bug

I am using VAAPI hardware acceleration and want to use AV1 as the codec for transcoding.  I am using Arc 750 GPU that I made work with Immich with the `group_add` and `OverrideGpuAddressSpace=48` workarounds.

When selecting AV1 and VAAPI in the settings, the config is saved successfully with no errors. However when I try to run the transcoding, an error log shows that AV1 is not supported (see log below). The issue is that the ffmpeg available in the Docker container is fully capable of making use of `av1_vaapi` transcoding option (there's no way my CPU is encoding 1080p video at 4.5x realtime):

```
# docker compose exec immich-microservices bash
root@284deb7f0360:/usr/src/app# ffmpeg -init_hw_device vaapi=/dev/dri/card1 -i source.mp4 -vf format=nv12,hwupload -c:v av1_vaapi -y target.mp4
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
...
 Stream #0:0(eng): Video: av1 (Main) (av01 / 0x31307661), vaapi(tv, bt470bg/bt470bg/smpte170m, progressive), 1920x1080, q=2-31, 30 fps, 15360 tbn (default)
...
frame= 2872 fps=136 q=-0.0 Lsize=  273480kB time=00:01:35.74 bitrate=23398.2kbits/s dup=30 drop=4 speed=4.53x
video:271892kB audio:1506kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.030043%
```

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 91
      - 991
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    device_cgroup_rules:
      - "c 189:* rmw"
      - "c 226:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./models:/cache
    group_add:
      - 91
      - 991
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
```

### Your .env content

```Shell
LOG_LEVEL=debug
NEOReadDebugKeys=1
OverrideGpuAddressSpace=48

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Go to Settings > Video Transcoding Settings
2. Set Video Codec = AV1
3. Set Hardware Acceleration > Acceleration API = VAAPI
4. Go to Jobs
5. Click Transcode Videos > All
```

### Relevant log output

```shell
ERROR [ImmichMicroservices] [MediaService] An error occurred while configuring transcoding options: UnsupportedMediaTypeException: VAAPI acceleration does not support codec 'AV1'. Supported codecs: h264,hevc,vp9
```
