### ISSUE TITLE
RAW (NEF) Files from Raw + Jpeg shooting stored at a different time/date than the Jpeg

### ISSUE THREAD

**Issue by smorar** [immich-app/immich#10060]
### The bug

Raw files seem to be stored in the timeline at the time + timezone modifier, whereas the Jpeg file seems to being stored in the timeline at the image creation time. This tends to separate the photos, and makes stacking harder.

The exif data from my example case appear to be the same for creation date, time zone and other critical date/time fields.

[exifdata_DSC8135.NEF.txt](https://github.com/user-attachments/files/15752647/exifdata_DSC8135.NEF.txt)
[exifdata_DSC8135.JPG.txt](https://github.com/user-attachments/files/15752648/exifdata_DSC8135.JPG.txt)
![337872643-bbb5dd03-46d0-4472-8944-be8a9e83b68b](https://github.com/immich-app/immich/assets/126771/8b9c9f38-4a18-42cb-bfd5-c32503e5b890)
![337872636-fe5fce32-dee4-4d24-88be-06e8890e52a8](https://github.com/immich-app/immich/assets/126771/39079ece-a50c-43fe-99d8-05f1dd1a21bc)

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/smorar/Pictures:/usr/src/app/picture_library:ro
      - /home/smorar/Videos:/usr/src/app/video_library:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      #  file: hwaccel.transcoding.yml
      #  service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/smorar/Pictures:/usr/src/app/picture_library:ro
      - /home/smorar/Videos:/usr/src/app/video_library:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        file: hwaccel.ml.yml
        service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /home/smorar/Pictures:/usr/src/app/picture_library:ro
      - /home/smorar/Videos:/usr/src/app/video_library:ro
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/smorar/Immich_Upload
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<snipped>

#LOG_LEVEL=debug

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Upload a folder containing Raw+Jpeg files
2. View files in timeline, notice that the Jpeg and Raw files are present in separate batches, instead of being interleaved.
3. Check the creation time allocated to each file in Immich
```
