### ISSUE TITLE
Media controls on mobile are not working for videos

### ISSUE THREAD

**Issue by JordyEGNL** [immich-app/immich#10082]
### The bug

As shown in the video below, the media controls do not work for me. This is the case for every video on Immich.

https://github.com/immich-app/immich/assets/65036298/92fabd8a-010b-420a-80d7-f65bd90f0ff9

### The OS that Immich Server is running on

Ubuntu Server 22.04 LTS

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command:
      - start.sh
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3001
    env_file:
      - ./.env
    depends_on:
      - redis
      - database
    labels:
      traefik.enable: true
      traefik.http.routers.immich.entryPoints: https
      traefik.http.services.immich.loadbalancer.server.port: 3001
      traefik.http.routers.immich.rule: Host(`photos.<domain>.<tld>`)
      com.centurylinklabs.watchtower.monitor-only: true
    restart: always
    networks:
      - immich
      - proxy
  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      # https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command:
      - start.sh
      - microservices
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.env
    depends_on:
      - redis
      - database
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    restart: always
    networks:
      - immich
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - ./.env
    volumes:
      - model-cache:/cache
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    restart: always
    networks:
      - immich
  redis:
    container_name: immich-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    restart: always
    networks:
      - immich
  database:
    container_name: immich-postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    volumes:
      - /mnt/media/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql
        --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only
        --no-align --command='SELECT SUM(checksum_failures) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
    networks:
      - immich
networks:
  proxy:
    name: proxy
    external: true
  immich:
    name: immich
    external: true
volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
UPLOAD_LOCATION=/mnt/media/immich/uploads
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TYPESENSE_API_KEY=<redacted>
TZ=Europe/Amsterdam
IMMICH_METRICS=true
```

### Reproduction steps

```bash
1. Upload a video to Immich
2. View the video on mobile
3. Try to skip, play/pause
4. It does not work
```

### Additional information

Android OS: 14
Phone: OnePlus 9 Pro
