### ISSUE TITLE
[BUG] Error getting credentials - `Cannot autolaunch D-Bus without x11 $DISPLAY`

### ISSUE THREAD

**Issue by vincentmathis** [immich-app/immich#1012]
<!--
Note: Please search to see if an issue already exists for the bug you encountered.
-->


**Describe the bug**
Trying to set up Immich behind traefik reverse proxy but when I try to run docker compose it crashes because it cannot find display. My remote server does not have a display.

I was following this setup https://github.com/immich-app/immich/discussions/437#discussioncomment-3609797

**Task List**


- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.


 ```yaml
version: "3.3"
services:
  traefik:
    image: ${TRAEFIK_DOCKER_IMAGE}
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=${TRAEFIK_API_INSECURE_ENABLED}"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      # This is for testing to prevent rate limit:
      #- "--certificatesResolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.le.acme.tlsChallenge=true"
      - "--certificatesResolvers.le.acme.email=${TRAEFIK_LETSENCRYPT_EMAIL}"
      - "--certificatesResolvers.le.acme.httpChallenge=true"
      - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.le.acme.storage=acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${BASE_DATA_LOCATION}/traefik/acme.json:/acme.json
    networks:
      - traefik-network

  nextcloud:
    image: ${NEXTCLOUD_DOCKER_IMAGE}
    container_name: nextcloud
    restart: always
    volumes:
      - ${BASE_DATA_LOCATION}/nextcloud:/var/www/html
    expose:
        - "8080"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)
      - traefik.http.routers.nextcloud.tls=true
      - traefik.http.routers.nextcloud.tls.certresolver=le
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.middlewares.nextcloud-redirect-web-secure.redirectscheme.scheme=https
      - traefik.http.routers.nextcloud-web.middlewares=nextcloud-redirect-web-secure
      - traefik.http.routers.nextcloud-web.rule=Host(`${NEXTCLOUD_URL}`)
      - traefik.http.routers.nextcloud-web.entrypoints=web
    environment:
      - MYSQL_DATABASE=${MARIADB_NEXTCLOUD_DATABASE}
      - MYSQL_USER=${MARIADB_NEXTCLOUD_USER}
      - MYSQL_PASSWORD=${MARIADB_NEXTCLOUD_PASSWORD}
      - MYSQL_HOST=database
    networks:
      - traefik-network
      - database-network
  
  database:
    image: ${MARIADB_DOCKER_IMAGE}
    container_name: database
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${BASE_DATA_LOCATION}/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_NEXTCLOUD_DATABASE}
      - MYSQL_USER=${MARIADB_NEXTCLOUD_USER}
      - MYSQL_PASSWORD=${MARIADB_NEXTCLOUD_PASSWORD}
    networks:
      - database-network

  bitwarden:
    image: ${BITWARDEN_DOCKER_IMAGE}
    container_name: bitwarden
    restart: always
    volumes:
      - ${BASE_DATA_LOCATION}/bitwarden:/data
    expose:
      - "3012"
      - "80"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.bitwarden-ui-https.rule=Host(`${BITWARDEN_URL}`)
      - traefik.http.routers.bitwarden-ui-https.entrypoints=websecure
      - traefik.http.routers.bitwarden-ui-https.tls=true
      - traefik.http.routers.bitwarden-ui-https.tls.certresolver=le
      - traefik.http.routers.bitwarden-ui-https.service=bitwarden-ui
      - traefik.http.routers.bitwarden-ui-http.rule=Host(`${BITWARDEN_URL}`)
      - traefik.http.routers.bitwarden-ui-http.entrypoints=web
      - traefik.http.routers.bitwarden-ui-http.middlewares=redirect-https
      - traefik.http.routers.bitwarden-ui-http.service=bitwarden-ui
      - traefik.http.services.bitwarden-ui.loadbalancer.server.port=80
      - traefik.http.routers.bitwarden-websocket-https.rule=Host(`${BITWARDEN_URL}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket-https.entrypoints=websecure
      - traefik.http.routers.bitwarden-websocket-https.tls=true
      - traefik.http.routers.bitwarden-websocket-https.tls.certresolver=le
      - traefik.http.routers.bitwarden-websocket-https.service=bitwarden-websocket
      - traefik.http.routers.bitwarden-websocket-http.rule=Host(`${BITWARDEN_URL}`) && Path(`/notifications/hub`)
      - traefik.http.routers.bitwarden-websocket-http.entrypoints=web
      - traefik.http.routers.bitwarden-websocket-http.middlewares=redirect-https
      - traefik.http.routers.bitwarden-websocket-http.service=bitwarden-websocket
      - traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
    networks:
      - traefik-network

  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    networks:
      - traefik-network
      - immich-network
    labels:
      traefik.enable: "true"
      traefik.http.services.media-immich-api.loadbalancer.server.port: "3001"
      traefik.http.routers.media-immich-api.rule: "Host(`${IMMICH_URL}`) && Pathprefix(`/api`)"
      traefik.http.routers.media-immich-api.middlewares: service-immich-api-strip
      traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes: "/api"
      traefik.http.routers.media-immich-api.tls: true
      traefik.http.routers.media-immich-api.tls.certresolver: letsencrypt
      traefik.http.routers.media-immich-api.tls.domains[0].main: "Host(`${BASE_DOMAIN}`)"
      traefik.http.routers.media-immich-api.entrypoints: websecure
    volumes:
      - ${BASE_DATA_LOCATION}/immich:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - immich-database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    networks:
      - immich-network
    volumes:
      - ${BASE_DATA_LOCATION}/immich:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - immich-database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - immich-network
    volumes:
      - ${BASE_DATA_LOCATION}/immich:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    networks:
      - traefik-network
      - immich-network
    labels:
      traefik.enable: "true"
      traefik.http.services.media-immich.loadbalancer.server.port: "3000"
      traefik.http.routers.media-immich.rule: "Host(`${IMMICH_URL}`)"
      traefik.http.routers.media-immich.tls: true
      traefik.http.routers.media-immich.tls.certresolver: letsencrypt
      traefik.http.routers.media-immich.tls.domains[0].main: "Host(`${BASE_DOMAIN}`)"
      traefik.http.routers.media-immich.entrypoints: websecure
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    networks:
      - immich-network
    restart: always

  immich-database:
    container_name: immich_postgres
    image: postgres:14
    networks:
      - immich-network
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_IMMICH_PASSWORD}
      POSTGRES_USER: ${POSTGRES_IMMICH_USERNAME}
      POSTGRES_DB: ${POSTGRES_IMMICH_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${BASE_DATA_LOCATION}/postgres:/var/lib/postgresql/data
    restart: always


networks:
  traefik-network:
    external:
      name: traefik-network
  database-network:
    external:
      name: database-network
  immich-network:
```

```env
# Globals
BASE_DATA_LOCATION=/mnt/data

# Traefik & TLS Configuration
TRAEFIK_DOCKER_IMAGE=traefik:latest
TRAEFIK_API_INSECURE_ENABLED=false
TRAEFIK_LETSENCRYPT_EMAIL=

# Nextcloud Configuration
NEXTCLOUD_DOCKER_IMAGE=nextcloud:latest
NEXTCLOUD_URL=

# MariaDB Configuration
MARIADB_DOCKER_IMAGE=mariadb:latest
MARIADB_ROOT_PASSWORD=
MARIADB_NEXTCLOUD_DATABASE=
MARIADB_NEXTCLOUD_USER=
MARIADB_NEXTCLOUD_PASSWORD=

# Bitwarden Configuration
BITWARDEN_DOCKER_IMAGE=bitwardenrs/server:latest
BITWARDEN_URL=


# Immich config
IMMICH_URL=

# Postgres config
POSTGRES_IMMICH_PASSWORD=
POSTGRES_IMMICH_USERNAME=immich
POSTGRES_IMMICH_DATABASE_NAME=immich
```

**Screenshots**

```
[+] Running 0/0
 ⠋ immich-microservices Pulling                                                                                                                                                                                                            0.0s
 ⠋ immich-database Pulling                                                                                                                                                                                                                 0.0s
 ⠋ immich-server Pulling                                                                                                                                                                                                                   0.0s
 ⠋ redis Pulling                                                                                                                                                                                                                           0.0s
 ⠋ immich-machine-learning Pulling                                                                                                                                                                                                         0.0s
error getting credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY
```

**System**
- Phone OS [iOS, Android]: ---
- Server Version: release
- Mobile App Version: ---
