### ISSUE TITLE
Image duplication not working - v1.106.1

### ISSUE THREAD

**Issue by schnobbc** [immich-app/immich#10122]
### The bug

Hello,

I upgraded to v1.106.1, I ran the Duplication detection job as a admin user. I then logged into my normal user where the pictures exist and went to Utilities > Review duplicate's. 

When I go to trash one of the duplicates I get the following error in the GUI:
"Forbidden Resource (Immich Server Error)

In the Docker logs I get the following error:
WARN [Api:AuthGuard~4ng59idq] Denied access to admin only route: /api/system-config

### The OS that Immich Server is running on

Ubuntu 20.x

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

v1.106.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /opt/dockerdata/immich/data/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/dockerdata/immich/data/app

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.106.1"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<PASSWORD>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/opt/dockerdata/immich/data/pgdata
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Login as an Admin
2. Run the duplication detector job
3. Login as a normal user
4. Try to delete a duplicate from Utilities > Review Duplicates
```

### Relevant log output

```shell
[Nest] 17  - 06/11/2024, 11:49:26 AM    WARN [Api:AuthGuard~7idnlhts] Denied access to admin only route: /api/system-config
[Nest] 17  - 06/11/2024, 11:49:28 AM    WARN [Api:AuthGuard~97hldj5j] Denied access to admin only route: /api/system-config
[Nest] 17  - 06/11/2024, 11:49:37 AM    WARN [Api:AuthGuard~25ilcnuq] Denied access to admin only route: /api/system-config
```
