### ISSUE TITLE
Stacks don't show in albums and stack selector missing when image viewed from album

### ISSUE THREAD

**Issue by jasonhun** [immich-app/immich#10135]
### The bug

1. If you stack images from an album, the images disappear, but refreshing the page brings them all back.  The thumbnails do not show stacked in the album, although locating the image in the regular photos feed shows that a stack was applied.

2. When selecting a photo in the album to view the larger image, the stacked image selector doesn't show at the bottom.

3. In the mobile app, the stacks you created show multiple times (as many times as you attempted the stack when it didn't seem to work from the album) and do not display the image when pressed on.

### The OS that Immich Server is running on

Windows 11, Docker

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1 build 157

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: photos
        target: /photos
        volume:
          nocopy: true
      - type: volume
        source: private
        target: /private
        volume:
          nocopy: true
      - type: volume
        source: ai
        target: /ai
        volume:
          nocopy: true
      - type: volume
        source: videos
        target: /videos
        volume:
          nocopy: true
      - type: volume
        source: family
        target: /family
        volume:
          nocopy: true
      - type: volume
        source: uploads
        target: /usr/src/app/upload
        volume:
          nocopy: true
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
      - type: volume
        source: photos
        target: /photos
        volume:
          nocopy: true
      - type: volume
        source: private
        target: /private
        volume:
          nocopy: true
      - type: volume
        source: ai
        target: /ai
        volume:
          nocopy: true
      - type: volume
        source: videos
        target: /videos
        volume:
          nocopy: true
      - type: volume
        source: family
        target: /family
        volume:
          nocopy: true
      - type: volume
        source: uploads
        target: /usr/src/app/upload
        volume:
          nocopy: true
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - type: volume
        source: photos
        target: /photos
        volume:
          nocopy: true
      - type: volume
        source: private
        target: /private
        volume:
          nocopy: true
      - type: volume
        source: ai
        target: /ai
        volume:
          nocopy: true
      - type: volume
        source: videos
        target: /videos
        volume:
          nocopy: true
      - type: volume
        source: family
        target: /family
        volume:
          nocopy: true
    env_file:
      - .env
    restart: always
    ports:
      - 3003:3003

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
  photos:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft,rw"
      device: ":/volume1/photo"
  private:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft"
      device: ":/volume1/private"
  ai:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft"
      device: ":/volume1/ai"
  videos:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft"
      device: ":/volume1/video"
  family:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft"
      device: ":/volume1/homes"
  uploads:
    driver_opts:
      type: nfs
      o: "addr=192.168.1.10,nolock,soft"
      device: ":/volume1/uploads"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=uploads
THUMB_LOCATION=./library/thumbs
ENCODED_VIDEO_LOCATION=./library/encoded-video
PROFILE_LOCATION=./library/profile

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

NVIDIA_VISIBLE_DEVICES=all
MACHINE_LEARNING_WORKER_TIMEOUT=300
MACHINE_LEARNING_MODEL_TTL=600
MACHINE_LEARNING_WORKER_TIMEOUT=150
```

### Reproduction steps

```bash
1. Go into an album in the web browser.
2. Select multiple images and then press 's' or choose 'stack' from the menu.
3. Although some images disappear, the stack icon does not show.
4. Refresh the page, all images reappear
5. Locate the image(s) in the main photo feed by clicking 'photos' in the left-hand menu.
6. Image shows with stack icon.
7. In the mobile app, go to the album.
8. Images are duplicated, but have the stack icon.
9. Press on any of the images, no photo is displayed.
```
