### ISSUE TITLE
immich_postgres healthcheck not working

### ISSUE THREAD

**Issue by PotatoPTT** [immich-app/immich#10134]
### The bug

In the latest dockercompose was added a healthcheck but in immich_postgres
`SELECT SUM(checksum_failures) FROM pg_stat_database` returns NULL not 0, so the healthcheck fails every time
For a temporary solution i just changed to `SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database`

### The OS that Immich Server is running on

Docker/Non Relatable

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
database:
    container_name: immich_postgres
    image: ${IMMICH_POSTGRES}
    env_file:
      - .env
    networks:
      - non_exposed
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    labels:
      - 'wud.watch=false'
```

### Your .env content

```Shell
NON RELATABLE
```

### Reproduction steps

```bash
1. Run the container
2. Wait 5 minutes
3. Healthcheck fails
```
