### ISSUE TITLE
Duplicates Forbidden resource

### ISSUE THREAD

**Issue by nicoloma89** [immich-app/immich#10159]
### The bug

Hello,
i cant delete the file. 
![image](https://github.com/immich-app/immich/assets/98285054/29fa8660-68cb-4f72-b4d5-935b42581717)

### The OS that Immich Server is running on

ubuntu 22.04 portainer

### Version of Immich Server

1.106.1

### Version of Immich Mobile App

1.106.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3" # Use version 3 of the docker-compose file format

# Service definitions for the big-bear-immich application
services:
  # Main Immich Server service configuration
  immich-server:
    container_name: immich-server # Name of the running container
    image: ghcr.io/immich-app/immich-server:v1.106.1 # Image to be used
 #   command: ["start.sh", "immich"] # Command to be executed upon container start
    ports: # Mapping ports from the host OS to the container
      - 2283:3001
    volumes: # Mounting directories for persistent data storage
      - /media/immich/immich_upload:/usr/src/app/upload
      - /media/immich/immich_upload/input:/usr/src/app/import
    environment: # Setting environment variables
#      IMMICH_VERSION: release
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: ******
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
      IMMICH_METRICS: true
      IMMICH_HOST_METRICS: true
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003 ###http://localhost:5432
    depends_on: # Dependencies to ensure the order of service startup
      - redis
      - database
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for the Immich Microservices
#  immich-microservices:
#    container_name: immich-microservices # Name of the running container
#    image: ghcr.io/immich-app/immich-server:v1.105.1 # Image to be used
    # extends:  # Feature to use configuration from another service (currently commented out)
    #   file: hwaccel.yml
    #   service: hwaccel
#    command: ["start.sh", "microservices"] # Command to be executed upon container start
#    volumes: # Mounting directories for persistent data storage
#      - /media/immich/immich_upload:/usr/src/app/upload
#      - /media/immich/immich_upload/input:/usr/src/app/import
#    environment: # Setting environment variables
#      DB_HOSTNAME: immich-postgres
#      DB_USERNAME: portainer
#      DB_PASSWORD: *******
#      DB_DATABASE_NAME: immich
#      DB_PORT: 5432
#      REDIS_HOSTNAME: immich-redis
#      IMMICH_METRICS: true
#      IMMICH_HOST_METRICS: true
#    depends_on: # Dependencies to ensure the order of service startup
#      - redis
#      - database
#    restart: always # Policy to always restart the container if it stops
#    networks:
#      - immich-network

  # Configuration for Immich Machine Learning service
  immich-machine-learning:
    container_name: immich-machine-learning # Name of the running container
    image: ghcr.io/immich-app/immich-machine-learning:v1.106.1 # Image to be used
    volumes: # Mounting directories for persistent data storage
      - /media/immich/immich_cache:/cache
    environment: # Setting environment variables
#     IMMICH_VERSION: release
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: portainer
      DB_PASSWORD: ******
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Redis service
  redis:
    container_name: immich-redis # Name of the running container
    image: redis:6.2-alpine # Image to be used
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

  # Configuration for Database service
  database:
    container_name: immich-postgres # Name of the running container
    image: tensorchord/pgvecto-rs:pg14-v0.2.0 # Image to be used
    environment: # Setting environment variables
      POSTGRES_PASSWORD: ****
      POSTGRES_USER: portainer
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes: # Mounting directories for persistent data storage
      - immich_postgres:/var/lib/postgresql/data
    restart: always # Policy to always restart the container if it stops
    networks:
      - immich-network

# Network definitions
networks:
  # Define the network
  immich-network:
    # Use the bridge driver
    driver: bridge

# Define named volumes for data persistence.
volumes:
  # Define a named volume for Immich data.
  immich_cache:
    # Use the local storage driver.
    driver: local
  immich_upload:
    # Use the local storage driver.
    driver: local
  immich_postgres:
    # Use the local storage driver.
    driver: local
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1.i mark the picture
2. he dont let me delete
3.
...
```

### Relevant log output

```shell
[Nest] 17  - 06/11/2024, 6:16:12 PM    WARN [Api:AuthGuard~ch4ruonj] Denied access to admin only route: /api/system-config
[Nest] 7  - 06/11/2024, 6:16:17 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: ENOENT: no such file or directory, open 'upload/thumbs/7af8b72c-1177-413f-b1bc-9355169e48e3/dc/c4/dcc485ed-306a-4448-bf81-c562f48fd429-preview.jpeg'
[Nest] 7  - 06/11/2024, 6:16:17 PM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, open 'upload/thumbs/7af8b72c-1177-413f-b1bc-9355169e48e3/dc/c4/dcc485ed-306a-4448-bf81-c562f48fd429-preview.jpeg'
    at async open (node:internal/fs/promises:636:25)
    at async readFile (node:internal/fs/promises:1246:14)
    at async MachineLearningRepository.getFormData (/usr/src/app/dist/repositories/machine-learning.repository.js:54:48)
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:17:26)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:86:27)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 06/11/2024, 6:16:17 PM   ERROR [Microservices:JobService] Object:
{
  "id": "dcc485ed-306a-4448-bf81-c562f48fd429"
}
[Nest] 7  - 06/11/2024, 6:16:17 PM     LOG [Microservices:MediaService] Attempting to finish incomplete move: upload/library/Fran/2024/May/IMG_7275.mov => upload/library/Fran/2024/May/IMG_7275.MOV.mov
```
