### ISSUE TITLE
Web UI requires login every time I open a new browser window or tab

### ISSUE THREAD

**Issue by sumnerboy12** [immich-app/immich#10170]
### The bug

If I successfully login to the Immich web UI, then open another browser tab (in the same browser window), I am asked to login again in the new tab.

Basically every new web UI session requires me to login.

### The OS that Immich Server is running on

Docker on Ubuntu 20.10

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  app:
    image: ghcr.io/immich-app/immich-server:release
    env_file: /var/data/config/immich/immich.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/data/immich/upload:/usr/src/app/upload
      - /var/data/media/upload/library:/usr/src/app/upload/library
      - /var/data/media/photos:/usr/src/app/photos:ro
    networks:
      - traefik_proxy
      - internal
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.immich.rule=Host(`immich.domain.tld`)"
        - "traefik.http.routers.immich.entrypoints=https"
        - "traefik.http.routers.immich.service=immich"
        - "traefik.http.services.immich.loadbalancer.server.port=3001"

  machinelearning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    env_file: /var/data/config/immich/immich.env
    volumes:
      - /var/data/runtime/immich/cache:/cache
    networks:
      - internal

  redis:
    image: redis:6.2
    networks:
      - internal

  db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file: /var/data/config/immich/immich.env
    volumes:
      - /var/data/runtime/immich/database:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

  db-backup:
    image: tiredofit/db-backup:latest
    env_file: /var/data/config/immich/immich-backup.env
    volumes:
      - /var/data/immich/database-dump:/backup
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal

networks:
  traefik_proxy:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.25.0/24
```

### Your .env content

```Shell
TZ=Pacific/Auckland

DB_HOSTNAME=db
DB_PORT=5432
DB_DATABASE_NAME=immich
DB_USERNAME=immich
DB_PASSWORD=secret

POSTGRES_HOST=db
POSTGRES_PORT=5432
POSTGRES_DB=immich
POSTGRES_USER=immich
POSTGRES_PASSWORD=secret
POSTGRES_INITDB_ARGS=--data-checksums
```

### Reproduction steps

```bash
1. Open web browser and login to Immich
2. Close web browser
3. Repeat step 1.
```
