### ISSUE TITLE
checkExistingAssets returns null IDs, breaking background backup

### ISSUE THREAD

**Issue by K3das** [immich-app/immich#10175]
### The bug

The checkExistingAssets returns `{"existingIds":[null]}`, causing the mobile app to fail to unmarshal the response:
```
type 'Null' is not a subtype of type 'String' in type cast
```
and sends a "Failed to connect to the server. Retrying..." notification

### The OS that Immich Server is running on

Alma 9

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload:z
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
    #  - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    image: registry.hub.docker.com/library/redis:6.2-alpine
    restart: always

  database:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/photos
IMMICH_VERSION=release
DB_PASSWORD=
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=redis
```

### Reproduction steps

```bash
1. Start a background backup
```
