### ISSUE TITLE
Cannot stay logged in after updating

### ISSUE THREAD

**Issue by kangruixiang** [immich-app/immich#10185]
### The bug

After updating to latest version. I cannot stay logged in on web browser.

### The OS that Immich Server is running on

Synology NAS

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    environment:
      - TZ=America/New_York
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: on-failure:5

  database:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: immich_postgres
    hostname: database
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=America/New_York
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: on-failure:5

  immich-server:
    image: altran1502/immich-server:release
    # command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 2283:3001
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/homes/kang/Photos:/mnt/media:ro
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      database:
        condition: service_started


  # immich-microservices:
  #   image: altran1502/immich-server:release

  #   command: ["start-microservices.sh"]
  #   container_name: Immich-MICROSERVICES
  #   hostname: immich-microservices
  #   security_opt:
  #     - no-new-privileges:true
  #   env_file:
  #     - stack.env
  #   volumes:
  #     - /volume1/docker/immich/upload:/usr/src/app/upload
  #     - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
  #     - /volume1/homes/kang/Photos:/mnt/media:ro
  #   restart: on-failure:5
  #   depends_on:
  #     immich-redis:
  #       condition: service_healthy
  #     # immich-db:
  #     database:
  #       condition: service_started
  #     # typesense:
  #       # condition: service_started

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: on-failure:5
    depends_on:
      # immich-db:
      database:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=America/New_York
TYPESENSE_API_KEY= ###
DB_HOSTNAME=database
DB_USERNAME=immichuser
DB_PASSWORD=immichpw
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
JWT_SECRET=###
```

### Reproduction steps

```bash
1. Open Immich in web browser
2. Log in
3. Everything works as is when staying on the app. Refreshing is ok
4. Close tab
5. Reopen Immich => redirected to log in page again
```
