### ISSUE TITLE
White text and icons are not visible on photo & video previews with light background

### ISSUE THREAD

**Issue by Maxobus** [immich-app/immich#10213]
### The bug

If photo or video preview has image with light background then white text and icons are not visible.
When you hover over the preview, it is shaded and the text becomes visible.

![image](https://github.com/immich-app/immich/assets/60475350/7fce7859-2ecc-4877-9310-f98f8238d03e)
![image](https://github.com/immich-app/immich/assets/60475350/f4be05b0-808f-46ab-a73e-76c43096a6ce)

Suggestion is to add shading glow effect or similar to icons and text.

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.10.6.1 build.142

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - /NAS/POISON/! BACKUPS !/Camera Upload:/mnt/media/camera_upload:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: no


  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: no

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: no

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: no
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/NAS/CLOUD/immich/upload
THUMBS_LOCATION=/mnt/CACHEDISK/immich/upload/thumbs
DB_DATA_LOCATION=/NAS/CLOUD/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=[...]
DB_USERNAME=[...]
DB_DATABASE_NAME=[...]
```

### Reproduction steps

```bash
1.
2.
3.
...
```
