### ISSUE TITLE
iOS unable to login via OAuth

### ISSUE THREAD

**Issue by noosters** [immich-app/immich#10229]
### The bug

I am unable to login using the iOS and OAuth/Authelia after upgrading to server version 1.106.3 and app version 1.106.1. OAuth still works fine for web and Android clients. After entering a valid login, the Authelia login screen dismisses and the app returns to the login screen. Attempting to login again results in the web view for the Authelia page opening and immediately closing by itself along with a new copy of the relevant log message. If I clear the Safari cache for the domain then the Authelia login page will show up again, but attempting to login is still unsuccessful.

Thanks for any help you can provide!

### The OS that Immich Server is running on

Alpine 3.20/Docker

### Version of Immich Server

1.106.3

### Version of Immich Mobile App

1.106.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/pictures/2024:/mnt/media/external/2024:ro
      - /media/pictures/2023:/mnt/media/external/2023:ro
      - /media/pictures/2022:/mnt/media/external/2022:ro
      - /media/pictures/2021:/mnt/media/external/2021:ro
      - /media/pictures/2020:/mnt/media/external/2020:ro
      - /media/pictures/2019:/mnt/media/external/2019:ro
      - /media/pictures/2018:/mnt/media/external/2018:ro
      - /media/pictures/2017:/mnt/media/external/2017:ro
      - /media/pictures/2016:/mnt/media/external/2016:ro
      - /media/pictures/2015:/mnt/media/external/2015:ro
      - /media/pictures/2014:/mnt/media/external/2014:ro
      - /media/pictures/2013:/mnt/media/external/2013:ro
      - /media/pictures/2012:/mnt/media/external/2012:ro
      - /media/pictures/2011:/mnt/media/external/2011:ro
      - /media/pictures/2010:/mnt/media/external/2010:ro
      - /media/pictures/2009:/mnt/media/external/2009:ro
      - /media/pictures/2008:/mnt/media/external/2008:ro
      - /media/pictures/2007:/mnt/media/external/2007:ro
      - /media/pictures/2006:/mnt/media/external/2006:ro
      - /media/pictures/2005:/mnt/media/external/2005:ro
      - /media/pictures/2004:/mnt/media/external/2004:ro
      - /media/pictures/2003:/mnt/media/external/2003:ro
      - /media/pictures/2002:/mnt/media/external/2002:ro
      - /media/pictures/2001:/mnt/media/external/2001:ro
      - /media/pictures/2000:/mnt/media/external/2000:ro
      - /media/pictures/1999:/mnt/media/external/1999:ro
      - /media/pictures/1998:/mnt/media/external/1998:ro
      - /media/pictures/1997:/mnt/media/external/1997:ro
      - /media/pictures/1996:/mnt/media/external/1996:ro
      - /media/pictures/1995:/mnt/media/external/1995:ro
      - /media/pictures/1994:/mnt/media/external/1994:ro
      - /media/pictures/1993:/mnt/media/external/1993:ro
      - /media/pictures/1992:/mnt/media/external/1992:ro
      - /media/pictures/1991:/mnt/media/external/1991:ro
      - /media/pictures/1990:/mnt/media/external/1990:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres

    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/uploads/


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=SSzDGh9Hs3qAuw
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default, 
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1. On login page for iOS app 1.106.1 try login via OAuth.
2. Enter valid credentials on OAuth provider's page (in this case, Authelia)
3. OAuth provider's page will dismiss and we are back at the Immich login screen without being logged in.
```

### Relevant log output

```shell
App log after entering valid credentials:

Message:
OAuth login failed
Details:
ApiException 400: {"message": "User exists", "error": "Bad Request", "statusCode": 400, "correlationId":"4zdwd1y8"}
From:
OAuthService
Stack Trace:
#0 OAuthApi.finishOAuth (package:openapi/api/o_auth_api.dart:54)
<asynchronous suspension>
#1 OAuthService.oAuthLogin (package:immich_mobile/services/oauth.service.dart:33)
<asynchronous suspsension>
#2 LoginForm.build.oAuthLogin (package:immich_mobile/widgets/forms/login/login_form.dart:242)
<asynchronous suspension>

Server log:
immich_server            | [Nest] 19  - 06/12/2024, 7:27:56 PM     LOG [Api:AuthService~4zdwd1y8] Registering new user: <redacted>@gmail.com/1f82e1eb-f728-458e-8c74-cb118881d8f9
```
