### ISSUE TITLE
Video transcode resolution is always 720p no matter what the option is selected

### ISSUE THREAD

**Issue by f0ff886f** [immich-app/immich#10225]
### The bug

No matter what I set, I always get 720p encoded videos out of immich.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - ${RO_EXTERNAL_PATH}:/usr/src/app/ro-external:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/raid_old/immich/immich-data
# The location where your database files are stored
DB_DATA_LOCATION=/raid_old/immich/pgdata

# External library paths
EXTERNAL_PATH=/raid_old/photo-library
RO_EXTERNAL_PATH=/raid_old/ro-photo-library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. First, my transcoding resolution was set to 720p so all my videos on disk are 720p
2. I went to the administration -> transcoding settings, and set the transcode target resolution to 1080p, click save
3. I selected a 1080p video (verified by downloading the source file), and selected "refresh encoded video"
4. I watched the job start + stop in the logs of the `immich-server` container:


[Nest] 7  - 06/12/2024, 5:56:35 PM     LOG [Microservices:MediaService] Started encoding video 6c553572-5c9a-4f5d-bcd4-9bf9f3634a42 {"inputOptions":["-hwaccel cuda","-hwaccel_output_format cuda","-noautorotate","-threads 1"],"outputOptions":["-tune hq","-qmin 0","-rc-lookahead 20","-i_qfactor 0.75","-c:v h264_nvenc","-c:a copy","-movflags faststart","-fps_mode passthrough","-map 0:0","-map 0:1","-g 256","-v verbose","-vf tonemap_cuda=desat=0:matrix=bt709:primaries=bt709:range=pc:tonemap=hable:transfer=bt709:format=nv12","-preset p4","-cq:v 23"],"twoPass":false}
[Nest] 7  - 06/12/2024, 5:56:37 PM     LOG [Microservices:MediaService] Successfully encoded 6c553572-5c9a-4f5d-bcd4-9bf9f3634a42
```

I refreshed the page, and inspected the video served with my browser tools (Firefox), and saw it is still serving 720p. Visually I would say this is true.

Moreover, I have tried the original setting as well, and the command line is the exact same.
```


### Relevant log output

_No response_

### Additional information

_No response_
