### ISSUE TITLE
Immich unreachable after upgrade to v1.106.3

### ISSUE THREAD

**Issue by pietrouk** [immich-app/immich#10266]
### The bug

After upgrading to v1.106.3 and trying to connect to server via browser, I get 
```
"Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later."
```

Steps to reproduce:
1. I stopped all the containers except postgres.
2. Connected to database and performed REINDEX DATABASE immich; successfully
3. Removed all images, volumes and containers from Portainer
4. Rebooted host
5. created brand new immich-app folder and moved docker-compose and env file there
6. docker compose pull && docker compose up -d

output:
```
docker compose pull && docker compose up -d
[+] Pulling 62/46
 ✔ immich-server Pulled                                                                                                                                                                                                            135.9s 
 ✔ immich-machine-learning Pulled                                                                                                                                                                                                  133.3s 
 ✔ redis Pulled                                                                                                                                                                                                                     49.2s 
 ✔ database Pulled                                                                                                                                                                                                                  76.1s 
                                                                                                                                                                                                                                      
[+] Running 5/5
 ✔ Network immich_default             Created                                                                                                                                                                                        0.1s 
 ✔ Container immich_redis             Started                                                                                                                                                                                        9.9s 
 ✔ Container immich_machine_learning  Started                                                                                                                                                                                       10.0s 
 ✔ Container immich_postgres          Started                                                                                                                                                                                       10.1s 
 ✔ Container immich_server            Started 
```

7. docker compose ps

```
NAME                      IMAGE                                                                                                                  COMMAND                  SERVICE                   CREATED          STATUS                        PORTS
immich_machine_learning   ghcr.io/immich-app/immich-machine-learning:release                                                                     "tini -- ./start.sh"     immich-machine-learning   16 minutes ago   Up 16 minutes (healthy)       
immich_postgres           docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0   "docker-entrypoint.s…"   database                  16 minutes ago   Up 16 minutes (healthy)       5432/tcp
immich_redis              docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900                     "docker-entrypoint.s…"   redis                     16 minutes ago   Up 16 minutes (healthy)       6379/tcp
immich_server             ghcr.io/immich-app/immich-server:release                                                                               "tini -- /bin/bash s…"   immich-server             16 minutes ago   Up About a minute (healthy)   0.0.0.0:2283->3001/tcp, :::2283->3001/tcp
```

8. docker container logs immich_server
```
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 6  - 06/13/2024, 8:59:54 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 16  - 06/13/2024, 8:59:54 AM     LOG [Api:EventRepository] Initialized websocket server
Migration "RemoveLibraryType1715804005643" failed, error: could not create unique index "UQ_assets_owner_checksum"
QueryFailedError: could not create unique index "UQ_assets_owner_checksum"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RemoveLibraryType1715804005643.up (/usr/src/app/dist/migrations/1715804005643-RemoveLibraryType.js:21:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
    at async /usr/src/app/dist/services/database.service.js:133:17
    at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
  query: 'CREATE UNIQUE INDEX "UQ_assets_owner_checksum" ON "assets" ("ownerId", "checksum") WHERE "libraryId" IS NULL',
  parameters: undefined,
  driverError: error: could not create unique index "UQ_assets_owner_checksum"
      at /usr/src/app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async RemoveLibraryType1715804005643.up (/usr/src/app/dist/migrations/1715804005643-RemoveLibraryType.js:21:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
      at async /usr/src/app/dist/services/database.service.js:133:17
      at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
    length: 311,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(f37f8176-816e-4570-b85b-ce768cd06f5b, \\x0caccd4e75440ca23668eb73a5649912ab19c7d6) is duplicated.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: 'parallel worker',
    schema: 'public',
    table: 'assets',
    column: undefined,
    dataType: undefined,
    constraint: 'UQ_assets_owner_checksum',
    file: 'tuplesort.c',
    line: '4297',
    routine: 'comparetup_index_btree'
  },
  length: 311,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("ownerId", checksum)=(f37f8176-816e-4570-b85b-ce768cd06f5b, \\x0caccd4e75440ca23668eb73a5649912ab19c7d6) is duplicated.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'parallel worker',
  schema: 'public',
  table: 'assets',
  column: undefined,
  dataType: undefined,
  constraint: 'UQ_assets_owner_checksum',
  file: 'tuplesort.c',
  line: '4297',
  routine: 'comparetup_index_btree'
}
microservices worker exited with code 1
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
```
9. docker container logs immich_postgres

```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-06-13 08:59:27.886 UTC [1] LOG:  redirecting log output to logging collector process
2024-06-13 08:59:27.886 UTC [1] HINT:  Future log output will appear in directory "log".
```




### The OS that Immich Server is running on

linux aarch64 Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.106.3

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    env_file:
      - .env
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    env_file:
      - .env
    restart: always

volumes:
  model-cache:
```


### Your .env content

```Shell
UPLOAD_LOCATION=/my/folder/photos
IMMICH_VERSION=release
DB_PASSWORD=pass
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/my/folder/db
```


### Reproduction steps

```bash
See above
```


### Relevant log output

```shell
See above
```


### Additional information

_No response_
