### ISSUE TITLE
An error occurred while configuring transcoding options: Error: No QSV device found

### ISSUE THREAD

**Issue by hsu1943** [immich-app/immich#10263]
### The bug

I occasionally see the immich_server container outputting error logs: "An error occurred while configuring transcoding options: Error: No QSV device found". When I click on MISSING under Jobs > TRANSCODE VIDEOS, I see the following batch error output. I'm not sure what the cause is.

```shell
[Nest] 7  - 06/13/2024, 8:52:55 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
[Nest] 7  - 06/13/2024, 8:52:56 AM   ERROR [Microservices:MediaService] An error occurred while configuring transcoding options: Error: No QSV device found
```

export config: immich-config.json

```json
{
  "ffmpeg": {
    "crf": 23,
    "threads": 0,
    "preset": "medium",
    "targetVideoCodec": "h264",
    "acceptedVideoCodecs": [
      "h264"
    ],
    "targetAudioCodec": "aac",
    "acceptedAudioCodecs": [
      "aac",
      "mp3",
      "libopus"
    ],
    "targetResolution": "1080",
    "maxBitrate": "0",
    "bframes": -1,
    "refs": 0,
    "gopSize": 0,
    "npl": 0,
    "temporalAQ": false,
    "cqMode": "auto",
    "twoPass": false,
    "preferredHwDevice": "auto",
    "transcode": "required",
    "tonemap": "hable",
    "accel": "qsv",
    "accelDecode": false
  },
  "job": {
    "backgroundTask": {
      "concurrency": 5
    },
    "smartSearch": {
      "concurrency": 2
    },
    "metadataExtraction": {
      "concurrency": 5
    },
    "faceDetection": {
      "concurrency": 2
    },
    "search": {
      "concurrency": 5
    },
    "sidecar": {
      "concurrency": 5
    },
    "library": {
      "concurrency": 5
    },
    "migration": {
      "concurrency": 5
    },
    "thumbnailGeneration": {
      "concurrency": 3
    },
    "videoConversion": {
      "concurrency": 1
    },
    "notifications": {
      "concurrency": 5
    }
  },
  "logging": {
    "enabled": true,
    "level": "log"
  },
  "machineLearning": {
    "enabled": true,
    "url": "http://immich-machine-learning:3003",
    "clip": {
      "enabled": true,
      "modelName": "XLM-Roberta-Large-Vit-B-16Plus"
    },
    "duplicateDetection": {
      "enabled": true,
      "maxDistance": 0.0155
    },
    "facialRecognition": {
      "enabled": true,
      "modelName": "buffalo_l",
      "minScore": 0.8,
      "maxDistance": 0.7,
      "minFaces": 3
    }
  },
  "map": {
    "enabled": true,
    "lightStyle": "",
    "darkStyle": ""
  },
  "reverseGeocoding": {
    "enabled": true
  },
  "oauth": {
    "autoLaunch": false,
    "autoRegister": true,
    "buttonText": "Login with OAuth",
    "clientId": "",
    "clientSecret": "",
    "defaultStorageQuota": 0,
    "enabled": false,
    "issuerUrl": "",
    "mobileOverrideEnabled": false,
    "mobileRedirectUri": "",
    "scope": "openid email profile",
    "signingAlgorithm": "RS256",
    "storageLabelClaim": "preferred_username",
    "storageQuotaClaim": "immich_quota"
  },
  "passwordLogin": {
    "enabled": true
  },
  "storageTemplate": {
    "enabled": true,
    "hashVerificationEnabled": true,
    "template": "{{y}}/{{MM}}{{dd}}/{{filename}}"
  },
  "image": {
    "thumbnailFormat": "webp",
    "thumbnailSize": 250,
    "previewFormat": "jpeg",
    "previewSize": 1440,
    "quality": 80,
    "colorspace": "p3",
    "extractEmbedded": false
  },
  "newVersionCheck": {
    "enabled": true
  },
  "trash": {
    "enabled": true,
    "days": 30
  },
  "theme": {
    "customCss": ""
  },
  "library": {
    "scan": {
      "enabled": true,
      "cronExpression": "30 3 * * *"
    },
    "watch": {
      "enabled": false
    }
  },
  "server": {
    "externalDomain": "",
    "loginPageMessage": ""
  },
  "notifications": {
    "smtp": {
      "enabled": false,
      "from": "",
      "replyTo": "",
      "transport": {
        "ignoreCert": false,
        "host": "",
        "port": 587,
        "username": "",
        "password": ""
      }
    }
  },
  "user": {
    "deleteDelay": 7
  }
}
```

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

v1.106.2

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.nju.edu.cn/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/photos
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.nju.edu.cn/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: library/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - redis-data:/data
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
  redis-data:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/docker-app-data/immich-app/library
IMMICH_VERSION=release
DB_PASSWORD=<password>
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
EXTERNAL_PATH=/data1/photos
DB_DATA_LOCATION=/docker-app-data/immich-app/postgres
```

### Reproduction steps

```bash
1. click on MISSING under Jobs > TRANSCODE VIDEOS
```

### Additional information

CPU:  intel i5-8500T
MEM: 8G * 2
