### ISSUE TITLE
Could not create unique index "UQ_assets_owner_checksum" after upgrading to v1.106

### ISSUE THREAD

**Issue by RosaEinhorn** [immich-app/immich#10270]
### The bug

Hi, 

after upgrading immich to v1.106.3 (from v1.105.1) I am getting a checksum error:
`failed, error: could not create unique index "UQ_assets_owner_checksum"`
Immich is running on unraid 6.12.10 with docker compose.

This issue was also discussed in #10186.
A few others (e.g. @junder873 and @alex-cardenas) and me have previously moved libraries from one user to another. There may be a connection to this issue.

Any help on solving this is really appreciated. Thanks in advance.🙏

### The OS that Immich Server is running on

unraid 6.12.10

### Version of Immich Server

v1.106.3

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    ports:
      - 2283:3001
    restart: always
    devices:
      - /dev/dri:/dev/dri
    labels:
      <traefik-labels>
    networks:
      default: null
      <additional-network>

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/user/appdata/immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    #healthcheck:
    #  test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    #  interval: 5m
    #  start_interval: 30s
    #  start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

networks:
  <network-config>
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_PASSWORD=<somepassword>
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/mnt/user/appdata/immich/pgdata

# Optional Database settings:
# DB_PORT=5432

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/photos
```

### Reproduction steps

```bash
1. Have a running immich instance on v1.105.1
2. Pull latest images and `docker-compose.yaml` and adapt to specific needs
3. `docker compose down && docker compose up -d`
4. See the mentioned error in the logs
```

### Relevant log output

```shell
Migration "RemoveLibraryType1715804005643" failed, error: could not create unique index "UQ_assets_owner_checksum"
QueryFailedError: could not create unique index "UQ_assets_owner_checksum"
    at PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RemoveLibraryType1715804005643.up (/app/immich/server/dist/migrations/1715804005643-RemoveLibraryType.js:21:9)
    at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/app/immich/server/dist/repositories/database.repository.js:169:9)
    at async /app/immich/server/dist/services/database.service.js:133:17
    at async /app/immich/server/dist/repositories/database.repository.js:177:23 {
  query: 'CREATE UNIQUE INDEX "UQ_assets_owner_checksum" ON "assets" ("ownerId", "checksum") WHERE "libraryId" IS NULL',
  parameters: undefined,
  driverError: error: could not create unique index "UQ_assets_owner_checksum"
      at /app/immich/server/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/app/immich/server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async RemoveLibraryType1715804005643.up (/app/immich/server/dist/migrations/1715804005643-RemoveLibraryType.js:21:9)
      at async MigrationExecutor.executePendingMigrations (/app/immich/server/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/app/immich/server/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/app/immich/server/dist/repositories/database.repository.js:169:9)
      at async /app/immich/server/dist/services/database.service.js:133:17
      at async /app/immich/server/dist/repositories/database.repository.js:177:23 {
    length: 311,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(1ee4f2f4[hex?], \\xd96a19e[hex?]) is duplicated.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: 'parallel worker',
    schema: 'public',
    table: 'assets',
    column: undefined,
    dataType: undefined,
    constraint: 'UQ_assets_owner_checksum',
    file: 'tuplesort.c',
    line: '4297',
    routine: 'comparetup_index_btree'
  },
  length: 311,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("ownerId", checksum)=(1ee4f2f4-[hex?] \\xd96a19e[hex?]) is duplicated.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: 'parallel worker',
  schema: 'public',
  table: 'assets',
  column: undefined,
  dataType: undefined,
  constraint: 'UQ_assets_owner_checksum',
  file: 'tuplesort.c',
  line: '4297',
  routine: 'comparetup_index_btree'
}
microservices worker exited with code 1
Detected CPU Cores: 20
Starting api worker
Starting microservices worker
[Nest] 769  - 06/12/2024, 6:58:17 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 788  - 06/12/2024, 6:58:17 AM     LOG [Api:EventRepository] Initialized websocket server
Migration "RemoveLibraryType1715804005643" failed, error: could not create unique index "UQ_assets_owner_checksum"
```
