### ISSUE TITLE
No running Jobs

### ISSUE THREAD

**Issue by mluettermann** [immich-app/immich#10315]
### The bug

no job is started when new images are loaded into the database, therefore no thumbnails are generated, videos are transcoded and so on

### The OS that Immich Server is running on

Ubuntun 22.04

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

1.10.6.3 build.160

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server_2
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    networks:
      - default
      - traefik_proxy
    restart: always
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_proxy
      traefik.http.routers.pictures.rule: Host(`pictures2.mydomain.com`)
      traefik.http.routers.pictures.entrypoints: websecure
      traefik.http.routers.pictures.service: pictures
      traefik.http.services.pictures.loadbalancer.server.port: 3001
      traefik.http.routers.pictures.middlewares: hsts
      traefik.http.middlewares.hsts.headers.stsSeconds: 31536000
      
  immich-machine-learning:
    container_name: immich_machine_learning_2
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${FILES_LOCATION}/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis_2
    image: redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    restart: always
    volumes:
      - ${FILES_LOCATION}/redis_data:/data

  database:
    container_name: immich_postgres_2
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${FILES_LOCATION}/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always


volumes:
  pgdata:
  model-cache:

networks:
  traefik_proxy:
    external: true
  default:
    driver: bridge
    ipam:
     config:
       - subnet: "10.255.0.64/28"
         gateway: "10.255.0.65"
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/ssd/docker/pictures/upload
IMMICH_VERSION=release
TYPESENSE_API_KEY=XXXX
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres_2
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis_2
FILES_LOCATION=/media/ssd/docker/pictures
DB_ROOTUSER=root
DB_ROOTPASSWORD=XXX
LOG_LEVEL=warn
```

### Reproduction steps

```bash
1. create a new server from the scratch
2. change my URL in the Iphone APP
3. Start synchronisation process (Backup) on the iphone
4. check the Jobs on the Admin interface, but no running jobs
```

### Relevant log output

```shell
[Nest] 17  - 06/14/2024, 9:02:16 AM     LOG [Api:EventRepository] Websocket Disconnect: 4ZrjmgCAWOTV5Dd3AAAF
[Nest] 17  - 06/14/2024, 9:02:21 AM     LOG [Api:SystemConfigService~765hrmyo] LogLevel=log (set via system config)
[Nest] 17  - 06/14/2024, 9:02:21 AM     LOG [Api:SystemConfigService~765hrmyo] LogLevel=log (set via system config)
[Nest] 17  - 06/14/2024, 9:04:55 AM     LOG [Api:EventRepository] Websocket Connect:    -dCXej8xfIwNrImlAAAJ
```
