### ISSUE TITLE
1.106.3 - 1.106.4 - 360 videos Support removed from PWA.

### ISSUE THREAD

**Issue by juanjax** [immich-app/immich#10322]
### The bug

Since the release of 1.106.2 thru 1.106.4 the support for 360 degree video has failed on mobile devices. Either while accessing via a web directly or via a PWA. This has been tested on Android and iOS using Chrome and Edge web browser. The support was there for 1.105. Can this support be returned?

### The OS that Immich Server is running on

Debían 12

### Version of Immich Server

1.106.4

### Version of Immich Mobile App

1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#
#     *** ADDED DEVICE FOR HWACCEL ***
#
    devices:
      - "/dev/dri:/dev/dri" 
#      
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
#     - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
#     - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
#     - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
#    network_mode: bridge

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
#    network_mode: bridge

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
#    network_mode: bridge

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
#    network_mode: bridge
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Photos
DB_DATA_LOCATION=/mnt/LXCs-AppData/Docker-Containers/immich/data
THUMBS_LOCATION=/mnt/thumbs
IMMICH_VERSION=release
DB_PASSWORD=immichdb
DB_USERNAME=immichdb
DB_DATABASE_NAME=immich
TYPESENSE_API_KEY=something-goes-here
```

### Reproduction steps

```bash
1.after installing immich
2.pull Immich content using Chrome or Edge browser.
3.attempt to playback a 360 video content
4. Video loads in dark screen. Audio is available, however video is not displayed.
5. Attempted resetting web browsers.
6. Tested on multiple devices; iPhone 12, Galaxy S23, iPad 3rd Gen., Galaxy S8 Ultra. Same results. Either via browser or installed Progressive Web App.
...
```
