### ISSUE TITLE
Smart Search broken after 1.106 update

### ISSUE THREAD

**Issue by dizzybro** [immich-app/immich#10375]
### The bug

Hello, 
My smart search is no longer working in 1.10.6. I get the following error in my server log when I conduct a search:
[Nest] 23  - 06/15/2024, 6:24:50 PM   ERROR [Api:Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
    at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:96:27)~c7uqkc5y] Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
#      - typesense
    restart: always

 # immich-microservices:
  #  container_name: immich_microservices
   # image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
   # extends:
   #    file: hwaccel.yml
   #    service: hwaccel
   # command: ["start.sh", "microservices"]
   # volumes:
   #   - ${UPLOAD_LOCATION}:/usr/src/app/upload
   #   - /etc/localtime:/etc/localtime:ro
   # env_file:
   #   - stack.env
   # depends_on:
   #   - redis
   #   - database
#      - typesense
   # restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  #immich-web:
  #  container_name: immich_web
  #  image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
  #  env_file:
  #    - stack.env
  #  restart: always

#  typesense:
#    container_name: immich_typesense
#    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
#    environment:
#      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
#      - TYPESENSE_DATA_DIR=/data
#      # remove this to get debug messages
#      - GLOG_minloglevel=1
#    volumes:
#      - tsdata:/data
#    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
#    image: tensorchord/pgvecto-rs:pg14-v0.1.11
#    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

 # immich-proxy:
  #  container_name: immich_proxy
  #  image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
  #  ports:
    #  - 2284:8080
   # depends_on:
   #   - immich-server
   #   - immich-web
  #  restart: always

volumes:
  pgdata:
  model-cache:
#  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/MediaPool/MediaPool/Immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=452ref235t423rt4q.q,qert
DB_PASSWORD=**************
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
NVIDIA_DRIVER_CAPABILITIES=all
TZ=America/Los_Angeles
IMMICH_HOST=localhost
```

### Reproduction steps

```bash
1.open immich web or app
2.type a serach term
3.no results shown
...
```

### Relevant log output

```shell
[Nest] 23  - 06/15/2024, 6:24:50 PM   ERROR [Api:Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
    at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:96:27)~c7uqkc5y] Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning
```

### Additional information

Everything was working great before this update
