### ISSUE TITLE
RuntimeError: /onnxruntime_src/onnxruntime/core/providers/cuda/cuda_call.cc

### ISSUE THREAD

**Issue by muammar** [immich-app/immich#10404]
### The bug

Thank you very much for this project that has helped me to get rid of Google Photos. Everything has been solid except for the error noted in the title. 

From time to time, I am required to **restart** the`[immich_machine_learning]` container to get the search option to run again. My NVIDIA GPU is working perfectly fine with other services on my server, but immich is the only one having issues with loading the ML model. 

Attached you will find the log files of the `immich_machine_learning` container. Let me know if this is helpful. 

Best, 

[_immich_machine_learning_logs.txt](https://github.com/user-attachments/files/15859136/_immich_machine_learning_logs.txt)


### The OS that Immich Server is running on

Debian Testing 

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # command: ['start.sh', 'immich'] Removed v1.106.1
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  # Removed from v1.106.1
  # immich-microservices:
  #   container_name: immich_microservices
  #   image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
  #   #   file: hwaccel.transcoding.yml
  #   #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
  #   command: ['start.sh', 'microservices']
  #   volumes:
  #     - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #     - /etc/localtime:/etc/localtime:ro
  #   env_file:
  #     - stack.env
  #   depends_on:
  #     - redis
  #     - database
  #   restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  # pgdata:
  model-cache:
```
```


### Your .env content

```Shell
UPLOAD_LOCATION=/path/to/Immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/path/to/immich/data
```


### Reproduction steps

```bash
1.Use search function. 
2.Expect results from search but the system returns an error.
```


### Relevant log output

```shell
RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:123 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:116 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             100: no CUDA-capable device is detected ;          
                             GPU=-451060998 ; hostname=5d07834094fa ;           
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;         
                             expr=cudaSetDevice(info_.device_id);               
                                                                                
                                                                                
                                                                                
                             The above exception was the direct cause of the    
                             following exception:                               
                                                                                
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:151 in predict             │
                             │                                                 │
                             │   148 │   │   inputs = text                     │
                             │   149 │   else:                                 │
                             │   150 │   │   raise HTTPException(400, "Either  │
                             │ ❱ 151 │   response = await run_inference(inputs │
                             │   152 │   return ORJSONResponse(response)       │
                             │   153                                           │
                             │   154                                           │
                             │                                                 │
                             │ /usr/src/app/main.py:174 in run_inference       │
                             │                                                 │
                             │   171 │   │   response[entry["task"]] = output  │
                             │   172 │                                         │
                             │   173 │   without_deps, with_deps = entries     │
                             │ ❱ 174 │   await asyncio.gather(*[_run_inference │
                             │   175 │   if with_deps:                         │
                             │   176 │   │   await asyncio.gather(*[_run_infer │
                             │   177 │   if isinstance(payload, Image):        │
                             │                                                 │
                             │ /usr/src/app/main.py:168 in _run_inference      │
                             │                                                 │
                             │   165 │   │   │   except KeyError:              │
                             │   166 │   │   │   │   message = f"Task {entry[' │
                             │       output of {dep}"                          │
                             │   167 │   │   │   │   raise HTTPException(400,  │
                             │ ❱ 168 │   │   model = await load(model)         │
                             │   169 │   │   output = await run(model.predict, │
                             │   170 │   │   outputs[model.identity] = output  │
                             │   171 │   │   response[entry["task"]] = output  │
                             │                                                 │
                             │ /usr/src/app/main.py:200 in load                │
                             │                                                 │
                             │   197 │   │   return model                      │
                             │   198 │                                         │
                             │   199 │   try:                                  │
                             │ ❱ 200 │   │   await run(_load, model)           │
                             │   201 │   │   return model                      │
                             │   202 │   except (OSError, InvalidProtobuf, Bad │
                             │   203 │   │   log.warning(                      │
                             │                                                 │
                             │ /usr/src/app/main.py:187 in run                 │
                             │                                                 │
                             │   184 │   if thread_pool is None:               │
                             │   185 │   │   return func(*args, **kwargs)      │
                             │   186 │   partial_func = partial(func, *args, * │
                             │ ❱ 187 │   return await asyncio.get_running_loop │
                             │   188                                           │
                             │   189                                           │
                             │   190 async def load(model: InferenceModel) ->  │
                             │                                                 │
                             │ /usr/local/lib/python3.11/concurrent/futures/th │
                             │ read.py:58 in run                               │
                             │                                                 │
                             │ /usr/src/app/main.py:196 in _load               │
                             │                                                 │
                             │   193 │                                         │
                             │   194 │   def _load(model: InferenceModel) -> I │
                             │   195 │   │   with lock:                        │
                             │ ❱ 196 │   │   │   model.load()                  │
                             │   197 │   │   return model                      │
                             │   198 │                                         │
                             │   199 │   try:                                  │
                             │                                                 │
                             │ /usr/src/app/models/base.py:54 in load          │
                             │                                                 │
                             │    51 │   │                                     │
                             │    52 │   │   self.download()                   │
                             │    53 │   │   log.info(f"Loading {self.model_ty │
                             │       to memory")                               │
                             │ ❱  54 │   │   self.session = self._load()       │
                             │    55 │   │   self.loaded = True                │
                             │    56 │                                         │
                             │    57 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/app/models/clip/textual.py:29 in _load │
                             │                                                 │
                             │   26 │   │   self.tokenizer = self._load_tokeni │
                             │   27 │   │   log.debug(f"Loaded tokenizer for C │
                             │   28 │   │                                      │
                             │ ❱ 29 │   │   return super()._load()             │
                             │   30 │                                          │
                             │   31 │   @abstractmethod                        │
                             │   32 │   def _load_tokenizer(self) -> Tokenizer │
                             │                                                 │
                             │ /usr/src/app/models/base.py:80 in _load         │
                             │                                                 │
                             │    77 │   │   )                                 │
                             │    78 │                                         │
                             │    79 │   def _load(self) -> ModelSession:      │
                             │ ❱  80 │   │   return self._make_session(self.mo │
                             │    81 │                                         │
                             │    82 │   def clear_cache(self) -> None:        │
                             │    83 │   │   if not self.cache_dir.exists():   │
                             │                                                 │
                             │ /usr/src/app/models/base.py:119 in              │
                             │ _make_session                                   │
                             │                                                 │
                             │   116 │   │   │   case ".armnn":                │
                             │   117 │   │   │   │   session = AnnSession(mode │
                             │   118 │   │   │   case ".onnx":                 │
                             │ ❱ 119 │   │   │   │   session = ort.InferenceSe │
                             │   120 │   │   │   │   │   model_path.as_posix() │
                             │   121 │   │   │   │   │   sess_options=self.ses │
                             │   122 │   │   │   │   │   providers=self.provid │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:43 │
                             │ 2 in __init__                                   │
                             │                                                 │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │    431 │   │   │   │   except Exception as fall │
                             │ ❱  432 │   │   │   │   │   raise fallback_error │
                             │    433 │   │   │   # Fallback is disabled. Rais │
                             │    434 │   │   │   raise e                      │
                             │    435                                          │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:42 │
                             │ 7 in __init__                                   │
                             │                                                 │
                             │    424 │   │   │   │   │   print(f"EP Error {e} │
                             │    425 │   │   │   │   │   print(f"Falling back │
                             │    426 │   │   │   │   │   print("************* │
                             │ ❱  427 │   │   │   │   │   self._create_inferen │
                             │    428 │   │   │   │   │   # Fallback only once │
                             │    429 │   │   │   │   │   self.disable_fallbac │
                             │    430 │   │   │   │   │   return               │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:48 │
                             │ 3 in _create_inference_session                  │
                             │                                                 │
                             │    480 │   │   │   disabled_optimizers = set(di │
                             │    481 │   │                                    │
                             │    482 │   │   # initialize the C++ InferenceSe │
                             │ ❱  483 │   │   sess.initialize_session(provider │
                             │    484 │   │                                    │
                             │    485 │   │   self._sess = sess                │
                             │    486 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeError:                                      
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:123 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void]               
                             /onnxruntime_src/onnxruntime/core/providers/cuda/cu
                             da_call.cc:116 std::conditional_t<THRW, void,      
                             onnxruntime::common::Status>                       
                             onnxruntime::CudaCall(ERRTYPE, const char*, const  
                             char*, ERRTYPE, const char*, const char*, int)     
                             [with ERRTYPE = cudaError; bool THRW = true;       
                             std::conditional_t<THRW, void,                     
                             onnxruntime::common::Status> = void] CUDA failure  
                             100: no CUDA-capable device is detected ;          
                             GPU=-451060998 ; hostname=5d07834094fa ;           
                             file=/onnxruntime_src/onnxruntime/core/providers/cu
                             da/cuda_execution_provider.cc ; line=280 ;         
                             expr=cudaSetDevice(info_.device_id);
```


### Additional information

_No response_
