### ISSUE TITLE
Thumbnails not generating and All jobs going to waiting state

### ISSUE THREAD

**Issue by balavenkateshs** [immich-app/immich#10405]
### The bug

Thumbnails not generating in web based and whenever uploading the images from mobile app or web based 
Using latest version 106.4
![Screenshot_2024-06-16-22-42-05-33_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/immich-app/immich/assets/35548750/c1046ade-1b05-4fed-b700-c5ac2508d63e)

### The OS that Immich Server is running on

Ubuntu latest version

### Version of Immich Server

106.4

### Version of Immich Mobile App

106.4

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"


name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ 'start.sh', 'immich' ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - i_model-cache:/cache
    env_file:
      - stack.env
    restart: always
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - i_redis:/data
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - i_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  i_pgdata:
    external: true
    name: i_pgdata
  i_redis:
    external: true
    name: i_redis
  i_model-cache:
    external: true
    name: i_model-cache
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich_data/immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
MMICH_METRICS=true
```

### Reproduction steps

```bash
1.thumbnail not showing 
2.jobs not running ans all jobs going to waiting state 
3.
...
```
