### ISSUE TITLE
Images Uploaded from iOS Do Not Show Up

### ISSUE THREAD

**Issue by mtwb47** [immich-app/immich#10421]
### The bug

Any images uploaded after the latest release now only show up as error icons. 

![Screenshot_20240616_234733](https://github.com/immich-app/immich/assets/32562514/cf7e0c91-9b42-48ea-9f50-064676cebda4)

Images uploaded via the web interface show up fine on both the web and back on the iOS app

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

106.4

### Version of Immich Mobile App

1.106.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/rustdrive/immich/data
DB_DATA_LOCATION=/rustdrive/immich/database
IMMICH_VERSION=release
DB_PASSWORD=======
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Upload either manually or via autobackup from iOS app
2. Go to web, images do not appear.
3.
...
```

### Relevant log output

```shell
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id/statistics, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id/thumbnail, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id/assets, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id/reassign, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/people/:id/merge, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] ReportController {/api/reports}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/reports, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/reports/checksum, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/reports/fix, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SearchController {/api/search}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/metadata, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/smart, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/explore, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/person, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/places, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/cities, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/search/suggestions, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] ServerInfoController {/api/server-info}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/storage, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/ping, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/version, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/features, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/theme, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/config, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/statistics, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/media-types, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SessionController {/api/sessions}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions/:id, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SharedLinkController {/api/shared-links}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/me, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, PATCH} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SyncController {/api/sync}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] TagController {/api/tags}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PATCH} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 17  - 06/17/2024, 3:44:50 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.106.4] [PRODUCTION] 
[Nest] 17  - 06/17/2024, 3:44:53 AM     LOG [Api:EventRepository] Websocket Connect:    x1WTU44venQsNeYOAAAB
[Nest] 17  - 06/17/2024, 3:44:53 AM     LOG [Api:EventRepository] Websocket Connect:    NknGUjLcPEl4SOtOAAAD
[Nest] 17  - 06/17/2024, 3:44:58 AM     LOG [Api:EventRepository] Websocket Disconnect: NknGUjLcPEl4SOtOAAAD
[Nest] 17  - 06/17/2024, 3:45:23 AM     LOG [Api:EventRepository] Websocket Disconnect: x1WTU44venQsNeYOAAAB
[Nest] 17  - 06/17/2024, 3:45:23 AM     LOG [Api:EventRepository] Websocket Connect:    L9eXn0ahP-X5eAHEAAAF
[Nest] 7  - 06/17/2024, 3:45:59 AM     LOG [Microservices:MediaService] Successfully generated JPEG image preview for asset 1e1a7337-736f-4f5b-b8cb-5807ecc03172
[Nest] 7  - 06/17/2024, 3:46:00 AM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 1e1a7337-736f-4f5b-b8cb-5807ecc03172
[Nest] 17  - 06/17/2024, 3:46:09 AM     LOG [Api:EventRepository] Websocket Connect:    nWLEkHP9ekqDh6z8AAAH
[Nest] 17  - 06/17/2024, 3:46:13 AM     LOG [Api:EventRepository] Websocket Disconnect: nWLEkHP9ekqDh6z8AAAH
[Nest] 17  - 06/17/2024, 3:48:44 AM     LOG [Api:EventRepository] Websocket Connect:    AvjNe2nCVsqOf4tXAAAJ
```

### Additional information

Not sure if this is because of the iOS version mismatch or not?
