### ISSUE TITLE
Errors in Immich logs, Smart search and face detection not working

### ISSUE THREAD

**Issue by Julian-1-2-3-4-5** [immich-app/immich#10492]
### The bug

After the update, smart search and face detection don't seem to work anymore for me

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    hostname: immich-server
    #ports:
    #     - 2283:3001 #not needed anymore because of reverse proxy
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
       file: hwaccel.transcoding.yml
       service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    networks: 
      - default
      - reverse_proxy_net

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      - default

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks: 
      - default

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
    networks: 
      - default

volumes:
  model-cache:

networks:
  reverse_proxy_net:
    name: reverse_proxy_net
    external: true
```

### Your .env content

```Shell
You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=2378124907214

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=DB_Data
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. restart immich
2. start smart search job
```

### Relevant log output

```shell
immich_redis             | 1:M 19 Jun 2024 19:40:06.457 * 10000 changes in 60 seconds. Saving...
immich_redis             | 1:M 19 Jun 2024 19:40:06.457 * Background saving started by pid 41
immich_redis             | 41:C 19 Jun 2024 19:40:06.465 * DB saved on disk
immich_redis             | 41:C 19 Jun 2024 19:40:06.466 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 19 Jun 2024 19:40:06.558 * Background saving terminated with success
immich_machine_learning  | [06/19/24 21:40:07] INFO     Setting 'nllb-clip-large-siglip__v1' execution     
immich_machine_learning  |                              providers to ['OpenVINOExecutionProvider',         
immich_machine_learning  |                              'CPUExecutionProvider'], in descending order of    
immich_machine_learning  |                              preference                                         
immich_machine_learning  | [06/19/24 21:40:07] INFO     Loading visual model 'nllb-clip-large-siglip__v1'  
immich_machine_learning  |                              to memory                                          
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f61d4020080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4020080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f61d4020080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4020080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f61d4030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f61d4030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_free: pointer might not point to a valid heap region: 0x7f61d4030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_free: pointer might not point to a valid heap region: 0x7f61d4020080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f61d4020080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f6148020080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f6148020080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f6148020080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7f6148020080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7f6148030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_server            |     at async SearchRepository.upsert (/usr/src/app/dist/repositories/search.repository.js:212:9)
immich_server            |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:9)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "ffc48865-c592-4a06-aa3f-d0b4c242c1d1"
immich_server            | }
immich_server            | 
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_server            |     at async SearchRepository.upsert (/usr/src/app/dist/repositories/search.repository.js:212:9)
immich_server            |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:9)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "a580f671-6d2b-455c-977f-196aa0236dfd"
immich_server            | }
immich_server            | 
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_server            |     at async SearchRepository.upsert (/usr/src/app/dist/repositories/search.repository.js:212:9)
immich_server            |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:9)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 06/19/2024, 9:40:36 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "d4b8c5d0-3113-439c-bfdb-c07f82a9a2b0"
immich_server            | }
immich_server            | 
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_server            |     at async SearchRepository.upsert (/usr/src/app/dist/repositories/search.repository.js:212:9)
immich_server            |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:9)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "b5c9f6bf-ddda-4881-a4c6-0c0b57bff69f"
immich_server            | }
immich_server            | 
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] QueryFailedError: pgvecto.rs: The given vector is invalid for input.
immich_server            | ADVICE: Check if dimensions and scalar type of the vector is matched with the index.
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_server            |     at async SearchRepository.upsert (/usr/src/app/dist/repositories/search.repository.js:212:9)
immich_server            |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:9)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 06/19/2024, 9:40:37 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "8ee4703f-6fae-4ece-9622-186f580b1ecc"
immich_server            | }
```

### Additional information

i'm running hardware accelerated machine learning via Openvino on intel arc
