### ISSUE TITLE
Editing the description of a photo is only visible in the App after manual refresh

### ISSUE THREAD

**Issue by MexHigh** [immich-app/immich#10551]
### The bug

When editing the description of a photo, it is not shown in the apps timeline (Android) instantly. Only a manual refresh pulls the description. 

This also happens, when the description is **added in the same app the image is examined on**: the description just vanishes again until a manual refresh of the timeline.

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS within Docker 26.1.4

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3 build.143

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 8050:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION="/mnt/nas/immich/library"

# The location where your database files are stored
DB_DATA_LOCATION="/mnt/nas/immich/database"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.106.4"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD="***redacted***"

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Set a description on the latest photo in the timeline (either on web or mobile, does not matter), close the image
2. Open the edited image on mobile
3. Description is not there
4. Pull down the timeline for manual refresh (Android)
5. Open image again
6. Description is there!

This even happens if you set the description on the app, then close the information dialogue and open the image again: The description is gone, since it was only updated on the server.
```

### Relevant log output

```shell
Nothing relevant found, neither in-app nor on the server.
```

### Additional information

Related to #8188, especially this comment (at "EDIT"): https://github.com/immich-app/immich/issues/8188#issuecomment-2051478504
