### ISSUE TITLE
[BUG] .NEF (Nikon RAW file) does not display post upload.

### ISSUE THREAD

**Issue by stephenmond** [immich-app/immich#1057]
**Describe the bug**
Since the merge of #746 , As a user, I would expect to be able to upload a .NEF RAW file from the web interface, CLI, or mobile application, and have it successful display in my library. Although the web interface, CLI, and mobile application all denote that the NEF file was successfully uploaded to my server, the file itself will not display and there is no thumbnail or any other indication it exists.

**Task List**

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my `docker-compose` file.
- [X] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1. Have or create a NIKON RAW image file .NEF
2. Attempt to upload the file via the CLI or UI web interface/mobile application.
3. Observe a successful message.
4. Refresh the UI and observe no thumbnail or indication of the uploaded photo.

**Additional Tests/Establishing Bug**
- Other photo file types upload without issue 
- Verbose Logs provided no meaningful output
- Tested multiple other NEF files with same lack of result of actual upload
- Regenerate Thumbnail job produced no result 
- Tested on localhost in event of proxy limit, same issue 
- CLI produced same result, photos identified but nothing displayed in library

**Expected behavior**
I would expect to be able to upload a .NEF RAW file from the web interface, CLI, or mobile application, and have it successful display in my library. 

**Screenshots**
### Uploading dialog on web UI:
![Screenshot from 2022-12-03 18-32-17](https://user-images.githubusercontent.com/93291292/205471883-17998aca-bdc4-4412-a1dc-939b566d897b.png)

### Upload Complete Banner on web UI:
![Screenshot from 2022-12-03 18-29-44](https://user-images.githubusercontent.com/93291292/205471896-048c02d7-0ee8-440e-ad8d-f5d31fd46bbe.png)

### Batch job for missing thumbnails, no missing found:

![Screenshot from 2022-12-03 18-25-00](https://user-images.githubusercontent.com/93291292/205471905-edb7d681-193b-4128-a21c-880a401bb7b3.png)

### Test Image file in question: 
![Screenshot from 2022-12-03 18-58-36](https://user-images.githubusercontent.com/93291292/205472085-c8541f12-e643-4e62-bb16-8b2653eb12d8.png)

Also tried various files from this source with same result: http://www.luminescentphoto.com/nx2/nefs.html

### Library after refresh:
![Screenshot from 2022-12-03 19-01-04](https://user-images.githubusercontent.com/93291292/205472107-84172258-3b8e-4ebe-ab7c-cfb9576091fc.png)

### File in question, compressed due to git hub restriction :
[DSC_0024.zip](https://github.com/immich-app/immich/files/10147786/DSC_0024.zip)

**System**
- Phone OS [iOS]: `16.1.1`
- Server Version: `1.37.0`
- Mobile App Version: `1.36.1.build.72`

**Additional context**

## docker-compose:
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

```

## .env file:
```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich


###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=*****

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose

###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=*******


###################################################################################
# Reverse Geocoding
####################################################################################


####################################################################################
# WEB - Optional
####################################################################################


####################################################################################
# OAUTH  - Optional
####################################################################################

OAUTH_ENABLED=true
OAUTH_ISSUER_URL=*****
OAUTH_CLIENT_ID=*****
OAUTH_CLIENT_SECRET=*****
OAUTH_BUTTON_TEXT=*****
OAUTH_AUTO_REGISTER=True
```
