### ISSUE TITLE
Album shows date range but all image a from same day

### ISSUE THREAD

**Issue by garbast** [immich-app/immich#10575]
### The bug

I create an album with images that are all shot on 23. January 2021. But the Album show a date range 23. Jan. 2021 - 20. June 2024.

When i checked the image details, they all show the correct date 23. Jan. 2021

### The OS that Immich Server is running on

Docker image

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

Only web app was used

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

name: immich

networks:
  backend:
  proxy:
    external: true

volumes:
  iconfig:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_FOLDER:-.}/config
  ilibrary:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DATA_FOLDER:-.}/library
  nextcloud:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/Nextcloud
  backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BACKUP_FOLDER:-.}
  icache:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INSTANCE_FOLDER}/cache
  pgdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${INSTANCE_FOLDER}/postgres

services:
  database:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m

    networks:
      - backend

  redis:
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - backend

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    volumes:
      - ilibrary:/usr/src/app/upload
      - icache:/cache
      # needed for a symlink to the image folder of cloud users
      - nextcloud:/mnt/Nextcloud
    networks:
      backend:
        aliases:
          - immich-machine-learning

  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    restart: unless-stopped
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    volumes:
      - ilibrary:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # needed for a symlink to the image folder of cloud users
      - nextcloud:/mnt/Nextcloud
    #ports:
    #  - 2283:3001
    depends_on:
      - redis
      - database
    networks:
      - proxy
      - backend
    labels:
      # common
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'

      # production / staging
      - 'traefik.http.routers.${APP_NAME}-https.rule=Host(`${HTTP_PRODUCTION_DOMAIN}`)'
      - 'traefik.http.routers.${APP_NAME}-https.entrypoints=web-secured'
      - 'traefik.http.routers.${APP_NAME}-https.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.${APP_NAME}-https.service=${APP_NAME}-http'
      - 'traefik.http.services.${APP_NAME}-http.loadbalancer.server.port=3001'
      - 'traefik.http.services.${APP_NAME}-http.loadbalancer.server.scheme=http'
```

### Your .env content

```Shell
APP_NAME=immich
INSTANCE_FOLDER=/srv/Immich
DATA_FOLDER=/mnt/Docker/Immich
BACKUP_FOLDER=/mnt/Docker/Immich/backup
IMMICH_VERSION=v1.106.4
DB_DATABASE_NAME=immich
DB_USERNAME=immich
DB_PASSWORD=[redacted]
HTTP_PRODUCTION_DOMAIN=[redacted]
```

### Reproduction steps

```bash
1. upload images
2. select images in the Photos module
3. add to album
4. create New Album test
5. switch to Albums module
6. find wrong date range below album title
```
