### ISSUE TITLE
Filename collision results in incorrect GPS coordinates and photo stacking

### ISSUE THREAD

**Issue by pasiphaegh** [immich-app/immich#10680]
### The bug

I have photos and scanned images taken with my camera and friends' cameras over the years. When we share them and combine into our own libraries, some have the same filename, e.g. IMG_8912.JPG for 3 different photos taken at 3 different geolocations.

When added to immich, there seems to be two issues:
- GPS coordinates/geolocations from one of the photos with a common filename are applied to all of the photos with the same filename. The EXIF data contained in the original photos is correct and untouched, as expected, but when viewed through immich via the main Map or the inidividual photos' maps within the web UI or mobile app, the geolocation of one photo is incorrectly applied to all of the photos with the same filename.
- Photos with the same filename are incorrectly stacked together, which is very confusing when they are unrelated events.

I worked with @simulot (author of immich-go) to confirm it was not an issue with immich-go's upload function. It seems to be the main immich application causing an issue.

These issues appear in both the web UI and the mobile app (iOS).

### The OS that Immich Server is running on

Linux Mint 21.3 (Virginia)

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.3 build160

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=XXXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload 2 or more photos with the same filename, e.g. IMG_8912.JPG, but with different geolocation tag coordinates.
2. View the Map or view the maps within the individual photos. Both/all photos with the same filename will be shown at only one location, which is the location of one of those photos. It just seems to be apply the geolocation from one of the photos to all photos of the same filename.
3. View the same individual photos to see the photos with the same filename are incorrectly stacked together.
```

### Additional information

Here is the [initial issue posted in the immich-go application's issues list](https://github.com/simulot/immich-go/issues/286). It contains some of the analysis that @simulot and I went through to see if immich-go was causing the issue, which it was confirmed as not causing the issue. We took the conversation offline to Discord and worked directly with each other.

I also intentionally masked the `DB_PASSWORD` in my .env file in this submission but that's the only thing that was changed.
