### ISSUE TITLE
【ERROR】After upgraded the software version, there was a problem with the database

### ISSUE THREAD

**Issue by 9k001** [immich-app/immich#10768]
### The bug

```
QueryFailedError: column "embedding" of relation "smart_search" does not exist
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:17:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
    at async /usr/src/app/dist/services/database.service.js:134:17
    at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
  query: 'ALTER TABLE smart_search ALTER COLUMN embedding SET STORAGE EXTERNAL',
  parameters: undefined,
  driverError: error: column "embedding" of relation "smart_search" does not exist
      at /usr/src/app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:17:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
      at async /usr/src/app/dist/services/database.service.js:134:17
      at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
    length: 125,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'tablecmds.c',
    line: '8216',
    routine: 'ATExecSetStorage'
  },
  length: 125,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '8216',
  routine: 'ATExecSetStorage'
}

Node.js v20.14.0
api worker exited with code 1
```

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.107.0

### Version of Immich Mobile App

v1.107.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.5'
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/immich-server/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ SERVER_MAPPING_PORT }}:${SERVER_PORT}"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/{{ MODE_ENV }}/server.env
    command: [ "start.sh", "immich" ]
    environment:
      - TZ=Asia/Shanghai
      - MODE_ENV={{ MODE_ENV }}

  immich-machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich-machine_learning
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/machine_learning/cache:/cache
    ports:
      - "{{ MACHINE_LEARNING_MAPPING_PORT }}:${MACHINE_LEARNING_PORT}"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/{{ MODE_ENV }}/machine_learning.env
    environment:
      - TZ=Asia/Shanghai
      - MODE_ENV={{ MODE_ENV }}

networks:
  default:
    name: "{{ MODE_ENV }}"
    external: true
```
```


### Your .env content

```Shell
IMMICH_VERSION=release
SERVER_PORT=3001
MACHINE_LEARNING_PORT=3003
```
```


### Reproduction steps

```bash
1. Upgrade Version
2. Run
3.
...
```

**Comment by mmomjian** [comment]
Please take a pg_dumpall of your database before trying anything: https://immich.app/docs/administration/backup-and-restore/

**Comment by 9k001** [comment]
View Database Version
```
tensorchord/pgvecto-rs             pg14-v0.2.0   sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0   2e2cb40c55b8   5 months ago   676MB
```

**Comment by 9k001** [comment]
> Please take a pg_dumpall of your database before trying anything: https://immich.app/docs/administration/backup-and-restore/
OK I have backed up the database.
It looks like the capacity is only 12M

**Comment by alextran1502** [comment]
Are you running a custom database, not from the stack?

**Comment by andyxpert** [comment]
340-ish MB mine, waiting for updates, similar situation as OP

**Comment by alextran1502** [comment]
@andyxpert Can you provide your docker-compose file?

**Comment by andyxpert** [comment]
version: "3.9"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 4000M
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/andyxpert/usb/Pictures:/Pictures:ro
    env_file:
      - stack.env
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 4000M
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 4000M
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: 4000M
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:

**Comment by andyxpert** [comment]
And the stack trace

Starting microservices worker
[Nest] 7  - 07/02/2024, 8:44:46 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 16  - 07/02/2024, 8:44:46 PM     LOG [Api:EventRepository] Initialized websocket server
Migration "AddFaceSearchRelation1718486162779" failed, error: internal error: entered unreachable code
QueryFailedError: internal error: entered unreachable code
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:23:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
    at async /usr/src/app/dist/services/database.service.js:134:17
    at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
  query: '\n' +
    '            CREATE INDEX face_index ON face_search\n' +
    '            USING hnsw (embedding vector_cosine_ops)\n' +
    '            WITH (ef_construction = 300, m = 16)',
  parameters: undefined,
  driverError: error: internal error: entered unreachable code
      at /usr/src/app/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:23:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
      at async /usr/src/app/dist/services/database.service.js:134:17
      at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
    length: 82,
    severity: 'ERROR',
    code: 'XX000',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'utils.rs',
    line: '21',
    routine: undefined
  },
  length: 82,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'utils.rs',
  line: '21',
  routine: undefined
}
microservices worker exited with code 1
Detected CPU Cores: 1
Starting api worker
Starting microservices worker

**Comment by bo0tzz** [comment]
We're seeing a few cases of this error, also in #10767.

**Comment by 9k001** [comment]
> Are you running a custom database, not from the stack?



> Are you running a custom database, not from the stack?

My database is deployed independently by docker.
However, the version is consistent with immich's requirements.
```
version: '3.5'
services:
  pgvecto_rs:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: db-pgvecto_rs
    restart: always
    volumes:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/db/conf/{{ MODE_ENV }}/pgvecto_rs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ${APP_DATA_HOME}/project/db/pgvecto-rs:/var/lib/postgresql/data
      - ${LOG_HOME}/project/db/pgvecto_rs:/var/lib/postgresql/data/log
    ports:
      - "{{ DB_PGVECTO_RS_MAPPING_PORT }}:${DB_PGVECTO_RS_PORT}"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/db/env/{{ MODE_ENV }}/pgvecto_rs.env
    environment:
      - TZ=Asia/Shanghai
      - MODE_ENV={{ MODE_ENV }}

networks:
  default:
    name: "{{ MODE_ENV }}"
    external: true
```
Check that the sha version of the database mirror meets immich requirements.
