### ISSUE TITLE
IOS client cannot play video when connect through https domain

### ISSUE THREAD

**Issue by MFYDev** [immich-app/immich#10777]
### The bug

I reported this issue long time ago and also reported this in the discord help, however it has been already a long time and many users met the same issue as mine, no solution or fix are provided.

The issue is when I connect to my immich which is running behind Nginx Reverse Proxy, I use let's encrypt SSL, the video will become blank. It cannot be played. However if I use the ip to connect to it, which means bypass nginx reverse proxy, the video can play. **This issue is only happening on IOS client.**

**My full nginx config is attached in [this reply](https://github.com/immich-app/immich/issues/10777#issuecomment-2204274411) below**

I am a software engineer and I am fully aware what I am talking. **There is no issue on Android client, or web, no error at all.** And this has significantly influence my using experience now

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.107.1

### Version of Immich Mobile App

v1.107.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "0 */4 * * *"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 30
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=**redacted**

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=**redacted**
DB_PASSWORD=**redacted**

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=**redacted**

REDIS_HOSTNAME=**redacted**

PUBLIC_LOGIN_PAGE_MESSAGE=**redacted**
```

### Reproduction steps

```bash
1. Use IOS client connect to the immich by using https domain behind nginx
2. play a video
3. fully blank and grey out
...
```

### Relevant log output

```shell
Instance of 'FlutterErrorDetails'
Exception: PlatformException(VideoError, Failed to load video: Operation Stopped, null, null)
Library: widgets library
Context: Instance of 'ErrorDescription'



#1      AsyncError.value (package:riverpod/src/common.dart:494:0)
#2      VideoViewerPage.build (package:immich_mobile/pages/common/video_viewer.page.dart:36:0)
#3      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476:0)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:5599:0)
#5      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539:0)
#6      HookElement.build (package:flutter_hooks/src/framework.dart:438:0)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5487:0)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#11     HookElement.update (package:flutter_hooks/src/framework.dart:400:0)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#14     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#15     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:0)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#19     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:0)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#33     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#47     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:0)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6776:0)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#54     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#56     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#60     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:0)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#63     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#64     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#65     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#68     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:0)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#70     StatefulElement.update (package:flutter/src/widgets/framework.dart:5673:0)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:0)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:0)
#74     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:0)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:0)
#76     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:155:0)
#77     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:0)
#78     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:173:0)
#79     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688:0)
#80     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:0)
#81     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688:0)
#82     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:248:0)
#83     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:331:0)
#84     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:0)
#85     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:0)
#86     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:0)
#87     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:0)
#88     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:0)
#89     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:0)
#90     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:0)
#91     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:0)
#92     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:0)
#93     _invoke (dart:ui/hooks.dart:312:0)
#94     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:0)
#95     _drawFrame (dart:ui/hooks.dart:283:0)
```
