### ISSUE TITLE
immich_postgres keeps restarting due to chown of /var/lib/postgresql/data

### ISSUE THREAD

**Issue by CountParadox** [immich-app/immich#10825]
### The bug

immich_postgres keeps restarting due to chown of /var/lib/postgresql/data, this causes an infinite loop of it restarting and immich_server is unable to start

### The OS that Immich Server is running on

Unraid 6.12.8

### Version of Immich Server

v1.106.4

### Version of Immich Mobile App

v1.106.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${IMPORT_LOCATION}:/import
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
   #   start_interval: 30s
   #   start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Unraid/immich

IMPORT_LOCATION=/mnt/user/Unraid/Photography

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Australia/Sydney

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. docker compose up
2. postgres keeps restarting with error
3. unable to start
...
```

### Relevant log output

```shell
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres exited with code 0
immich_machine_learning  | [07/04/24 08:18:40] INFO     Started server process [10]
immich_machine_learning  | [07/04/24 08:18:40] INFO     Waiting for application startup.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Created in-memory cache with unloading after 300s
immich_machine_learning  |                              of inactivity.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Initialized request thread pool with 8 threads.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Application startup complete.
immich_postgres exited with code 0
immich_postgres exited with code 0
```

### Additional information

```
root@NUC:/boot/config/plugins/compose.manager/projects/Immich# ls
docker-compose.override.yml  docker-compose.yml  name  postgres/
root@NUC:/boot/config/plugins/compose.manager/projects/Immich# docker compose pull && docker compose up
[+] Pulling 4/4
 ✔ database Pulled                                                                                            26.5s
 ✔ redis Pulled                                                                                               24.1s
 ✔ immich-server Pulled                                                                                       27.9s
 ✔ immich-machine-learning Pulled                                                                             27.2s
[+] Running 5/5
 ✔ Network immich_default             Created                                                                  2.5s
 ✔ Container immich_machine_learning  Created                                                                  6.3s
 ✔ Container immich_redis             Created                                                                  6.3s
 ✔ Container immich_postgres          Created                                                                  6.3s
 ✔ Container immich_server            Created                                                                  2.1s
Attaching to immich_machine_learning, immich_postgres, immich_redis, immich_server
immich_redis             | 1:C 03 Jul 2024 22:16:15.259 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis             | 1:C 03 Jul 2024 22:16:15.259 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis             | 1:C 03 Jul 2024 22:16:15.259 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis             | 1:M 03 Jul 2024 22:16:15.260 * monotonic clock: POSIX clock_gettime
immich_redis             | 1:M 03 Jul 2024 22:16:15.260 * Running mode=standalone, port=6379.
immich_redis             | 1:M 03 Jul 2024 22:16:15.260 # Server initialized
immich_redis             | 1:M 03 Jul 2024 22:16:15.260 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis             | 1:M 03 Jul 2024 22:16:15.260 * Ready to accept connections
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_server            | Detected CPU Cores: 8
immich_machine_learning  | [07/04/24 08:16:38] INFO     Starting gunicorn 22.0.0
immich_machine_learning  | [07/04/24 08:16:38] INFO     Listening at: http://[::]:3003 (9)
immich_machine_learning  | [07/04/24 08:16:38] INFO     Using worker: app.config.CustomUvicornWorker
immich_machine_learning  | [07/04/24 08:16:38] INFO     Booting worker with pid: 10
immich_postgres exited with code 0
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres exited with code 0
immich_postgres exited with code 0
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres exited with code 0
immich_machine_learning  | [07/04/24 08:18:40] INFO     Started server process [10]
immich_machine_learning  | [07/04/24 08:18:40] INFO     Waiting for application startup.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Created in-memory cache with unloading after 300s
immich_machine_learning  |                              of inactivity.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Initialized request thread pool with 8 threads.
immich_machine_learning  | [07/04/24 08:18:40] INFO     Application startup complete.
immich_postgres exited with code 0
immich_postgres exited with code 0
immich_postgres exited with code 0
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_postgres          | chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_postgres exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 2/4
[+] Stopping 2/4ich_machine_learning  Stopped                                                                                                   10.0s
[+] Stopping 2/4ich_machine_learning  Stopped                                                                                                   10.0s
[+] Stopping 4/4ich_machine_learning  Stopped                                                                                                   10.0s
 ✔ Container immich_machine_learning  Stopped                                                                                                   10.0s
 ✔ Container immich_server            Stopped                                                                                                   18.3s
 ✔ Container immich_redis             Stopped                                                                                                   14.5s
 ✔ Container immich_postgres          Stopped                                                                                                   18.2s
canceled


```
