### ISSUE TITLE
Photo search scroll position

### ISSUE THREAD

**Issue by mbay0r** [immich-app/immich#10882]
### The bug

If I open a photo under Photos that is not at the top and then close it, I remain where I opened the photo in the overview.

However, if I use the search function to open a photo that is further down and then close it again, the browser jumps back to the top to the first photo

Is there a way to do this in the search so that the browser does not jump back up to the first result and remains where I opened the last photo?

I hope it is understandable

thanks!

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

1.107.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    privileged: true
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload:rw
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs:rw
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile:rw
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video:rw
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video:rw
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library:rw
      - ${FOTOS_LOCATION}:/Fotos:rw
      - ${VIDEOS_LOCATION}:/Filme:rw


      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration-openvino
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always



volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/sata/share/Fotos/immich/uploads/
THUMB_LOCATION=/mnt/nvme/appdata/immich/thumbs/
ENCODED_VIDEO_LOCATION=/mnt/nvme/appdata/immich/encoded-video/
VIDEO_LOCATION=/mnt/nvme/appdata/immich/encoded-video/
PROFILE_LOCATION=/mnt/nvme/appdata/immich/profile/
LIBRARY_LOCATION=/mnt/sata/appdata_sata/immich/uploads/
FOTOS_LOCATION=/mnt/sata/share/Fotos/
VIDEOS_LOCATION=/mnt/sata/share/Filme/


# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################

DB_HOSTNAME=xx
DB_USERNAME=postgres
DB_PASSWORD=xx
DB_DATABASE_NAME=immich
DB_PORT=5433
```

### Reproduction steps

```bash
1. Search for Person
2. Scroll down to a Photo
3. Open the Picture
4. Close the Picture
5. I am back at the beginning of the search results and not where I had scrolled to.
```
