### ISSUE TITLE
Unable to delete External Library, even after removing the only Import Path

### ISSUE THREAD

**Issue by kayg04** [immich-app/immich#10893]
### The bug

I have been using Immich as my Nextcloud folder read-only client for a while now, just to test/dip my toes before getting wet. That has worked flawlessly. I recently took the plunge and uploaded all my media to Immich, which also worked flawlessly through immich cli. 

What hasn't worked flawlessly is removing the External Library (Nextcloud folder) that was added to Immich. Whenever I tried to remove it, I get the usual confirmation dialog but then nothing happens. There are no relevant logs in `immich_server` container either. 

Please let me know if you'd like more info. Here's a video recording of the possible bug:

https://github.com/immich-app/immich/assets/30401343/2df94298-6c56-46d7-8236-1b4122052d6c

### The OS that Immich Server is running on

Debian Bookworm

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${NEXTCLOUD}:/mnt/nextcloud:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/hdd/kayg-immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/nvme/kayg-immich/db

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=kayg_immich
DB_DATABASE_NAME=kayg_immich

# External photos on Nextcloud
NEXTCLOUD=/mnt/hdd/apps/nextcloud-aio/data
```

### Reproduction steps

```bash
Try to delete an external library, see it persist even after confirmation that it will be gone forever.
```

### Relevant log output

```shell
Could not find any relevant logs in immich_server but please let me know if you need any specific log output.
```
