### ISSUE TITLE
Update from 1.106.4 => 1.107.2 immich-server can't start

### ISSUE THREAD

**Issue by SuberSeb** [immich-app/immich#10892]
### The bug

After updating 1.106.4 => 1.107.2 immich-server container can't start anymore.

I'm running pgvectro postgres image from the official docker-compose, no any changes to the db was made recently. I've tried to update to 0.2.1 but no luck. Vectors extension is installed and updated.

Solutions from this thread didn't help https://github.com/immich-app/immich/issues/10767

### The OS that Immich Server is running on

Unraid 6.12.10

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

networks:
  immich-network:
    name: immich-network
    ipam:
      config:
        - subnet: 172.20.80.0/24

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:release
    extends:
      file: ../addons/immich-gpu.yaml
      service: gpu
    env_file:
      - ../envs/immich.env
    networks:
      - immich-network
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${MNT_CACHE_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${MNT_CACHE_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${MNT_CACHE_LOCATION}/profile:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    mem_limit: 6144m
    cpus: 8

  immich-machine-learning:
    container_name: immich-machinelearning
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    extends:
      file: ../addons/immich-gpu.yaml
      service: gpu
    env_file:
      - ../envs/immich.env
    networks:
      - immich-network
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${MNT_CACHE_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${MNT_CACHE_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${MNT_CACHE_LOCATION}/profile:/usr/src/app/upload/profile
      - ${MNT_CACHE_LOCATION}/machinelearning/cache:/cache
    restart: unless-stopped
    mem_limit: 6144m
    cpus: 8

  immich-postgres:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.1
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    ulimits:
      nofile:
        soft: 80000
        hard: 80000
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passhere
      - POSTGRES_USER=postgres
      - POSTGRES_INITDB_ARGS='--data-checksums'
      - TZ=Europe/Moscow
    networks:
      - immich-network
    ports:
      - 5450:5432/tcp
    volumes:
      - /mnt/user/Appdata/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: unless-stopped

  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:6.2-alpine
    environment:
      - TZ=Europe/Moscow
    networks:
      - immich-network
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
```

### Your .env content

```Shell
# Postgres
DB_HOSTNAME=192.168.1.45
DB_PORT=5450
DB_USERNAME=immichuser
DB_PASSWORD=passhere
DB_DATABASE_NAME=immich

# Redis
REDIS_HOSTNAME=immich-redis
REDIS_PORT=6379
REDIS_DBINDEX=5

# Config
UPLOAD_LOCATION=/mnt/user/Photos/Immich/Upload
LOG_LEVEL=log
JWT_SECRET=sec
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=1

# Cache
MNT_CACHE_LOCATION=/mnt/user/Apps/immich
```

### Reproduction steps

```bash
Just start the stack.
```

### Relevant log output

```shell
[Nest] 7  - 07/04/2024, 4:31:15 PM     LOG [Microservices:EventRepository] Initialized websocket server Migration "AddFaceSearchRelation1718486162779" failed, error: type "vector" does not exist QueryFailedError: type "vector" does not exist at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:12:9) at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17) at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35) at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9) at async /usr/src/app/dist/services/database.service.js:134:17 at async /usr/src/app/dist/repositories/database.repository.js:177:23 { query: '\n' + '            CREATE TABLE face_search (\n' + '            "faceId"  uuid PRIMARY KEY REFERENCES asset_faces(id) ON DELETE CASCADE,\n' + '            embedding  vector(512) NOT NULL )', parameters: undefined,
```

### Additional information

Tried
```
SET search_path TO "$user", public, vectors;
DROP INDEX face_index;
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE real[];
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE vector(512);
```
but not working still
