### ISSUE TITLE
immich_postgres memory leak?

### ISSUE THREAD

**Issue by TermeHansen** [immich-app/immich#10901]
### The bug

I'm noticing that the immich_postgres container grow it's memory footprint over time. It starts around 50Mb, and after a couple of days I need to restart the container as the usage is well over 2Gb

![image](https://github.com/immich-app/immich/assets/6922018/eb2d6950-a988-4bfe-9265-8be743fd8d0f)
Here my memory usage over the last couple of days.

### The OS that Immich Server is running on

dietpi

### Version of Immich Server

1.107.2

### Version of Immich Mobile App

1.107.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
#    ports:
#      - 2283:3001
    restart: always
    networks:
      - immich_net
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich_net

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich_net

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_net


volumes:
  model-cache:

networks:
  proxy:
    external: true
  immich_net:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=**********
DB_PASSWORD=**********

PORT=3000
TZ=Europe/Copenhagen
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. start container setup
2. monitor container usage with "dc stats"
3.
...
```
