### ISSUE TITLE
iOS Upload - Few photos error with "Live photo vide must be a video"

### ISSUE THREAD

**Issue by undaunt** [immich-app/immich#10910]
### The bug

Upon running an iOS upload, a few specific photos fail each time. The error used to be more general but recently I saw it show "Live photo vide must be a video". All of the photos are HEIC photos from 2023.

### The OS that Immich Server is running on

Ubuntu 22.04 LTS, Docker

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1 build.162

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich
    restart: unless-stopped
    networks:
      - ${PROXY_NETWORK}
      - ${APP_NETWORK}
    depends_on:
      - immich-redis
      - immich-db
    cpus: 3
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${PHOTOSDIR}/immich:/usr/src/app/upload
      - ${PHOTOSDIR}/icloud:/icloud:ro
      - ${APPDATA}/photos/immich/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: ${POSTGRES_IMMICH_HOST}
      DB_DATABASE_NAME: ${POSTGRES_IMMICH_DB}
      DB_USERNAME: ${POSTGRES_IMMICH_USER}
      DB_PASSWORD: ${POSTGRES_IMMICH_PASS}
      REDIS_HOSTNAME: ${IMMICH_REDIS_HOSTNAME}

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    volumes:
      - ${APPDATA}/photos/immich/models:/cache
    restart: unless-stopped
    networks:
      - ${APP_NETWORK}

  immich-redis:
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - ${APP_NETWORK}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  immich-db:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich-db
    restart: unless-stopped
    networks:
      - ${APP_NETWORK}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_IMMICH_PASS}
      POSTGRES_USER: ${POSTGRES_IMMICH_USER}
      POSTGRES_DB: ${POSTGRES_IMMICH_DB}
    volumes:
      - ${APPDATA}/photos/immich/db:/var/lib/postgresql/data
```

### Your .env content

```Shell
IMMICH_VERSION=release
POSTGRES_IMMICH_HOST=immich-db
POSTGRES_IMMICH_DB=immich
POSTGRES_IMMICH_USER=postgres
POSTGRES_IMMICH_PASS=xxxxxx
IMMICH_REDIS_HOSTNAME=immich-redis
```

### Reproduction steps

```bash
1. Start iOS back of 'Recents (All)' folder
2. Note 3 photos fail to upload
```

### Additional information

I didn't see any specific errors on the iOS app logs but I can pull whatever may be relevant from wherever instructed to do so. Thank you.
