### ISSUE TITLE
Wrong size displayed in external libraries

### ISSUE THREAD

**Issue by ilopmar** [immich-app/immich#10927]
### The bug

I've upgraded from `v1.106.4` to `v1.107.2` and I've noticed that the external ilbraries size is missing the decimal point (and I'm not sure about the units)

This is after the upgrade:

![image](https://github.com/immich-app/immich/assets/559192/17ab91fd-dcee-4d9c-be42-9bb439024c9c)

The size should be 318.3, 27.3,... And as mentioned I think in previous version it also displayed the units, like `318.3 GB`

### The OS that Immich Server is running on

Ubunbu Server 22.04.4

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.9'

services:
  immich-server:
    container_name: immich_server
    # The version needs to be the same in `immich-machine-learning` local or remote (check `remote-ml.yml`)
    image: ghcr.io/immich-app/immich-server:v1.107.2
    networks:
      - traefik_proxy
      - immich_default
    volumes:
      - ./upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # My volumes
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    depends_on:
      - redis
      - database

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - immich_default

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: unless-stopped
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    networks:
      - immich_default

networks:
  traefik_proxy:
    external: true
  immich_default:
    name: immich_default
```

### Your .env content

```Shell
# Only change `DB_PASSWORD`
DB_PASSWORD=__PUT_HERE_DATABASE_PASSWORD__

# Do not change this
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOSTNAME=immich_postgres
```

### Reproduction steps

```bash
- Use an external library
- Check the size
```
