### ISSUE TITLE
Immich not able to refresh / add new External Library files anymore. Library task 'waiting' all the time

### ISSUE THREAD

**Issue by dgtal1** [immich-app/immich#10941]
### The bug

I upgraded to 1.107 today and uploaded new photos from my phone to my NAS. I ran the 'Refresh' library option in immich to rescan the library and add the new files. Nothing's happening. So far this was an easy and quick process in the previous versions, but not anymore.
The library task is stuck in the 'waiting status' all the time. Immich is not starting the reindex operation. I do not want to delete and reindex everything as this will take a few days due to the size of my library.

Any idea what can be wrong? How to fix this?

This is wat I see in the admin page under tasks:
![image](https://github.com/immich-app/immich/assets/27864579/3e1d2c49-2304-49e0-9bd5-adf4d7aa0a6e)

### The OS that Immich Server is running on

Ubuntu WSL

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1 build.146

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video      
      - /etc/localtime:/etc/localtime:ro
      - "photo:/external_originals/photo:ro"
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      #- database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:      
      - ${MODEL_CACHE_LOCATION}:/cache  #- model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

volumes: 
  #model-cache:

  photo: 
    driver_opts: 
      type: cifs 
      o: "iocharset=utf8,username=****,password=****,vers=3.0" 
      device: "//192.168.0.13/photo" 
      
  thumbs: 
    driver_opts: 
      type: cifs 
      o: "iocharset=utf8,username=****,password=****,vers=3.0" 
      device: "//192.168.0.13/satashare/docker/immich/artifacts/thumbs"       
      
  encoded-video: 
    driver_opts: 
      type: cifs 
      o: "iocharset=utf8,username=****,password=****,vers=3.0" 
      device: "//192.168.0.13/satashare/docker/immich/artifacts/encoded-video"       
  
  model-cache: 
    driver_opts: 
      type: cifs 
      o: "iocharset=utf8,username=****,password=****,vers=3.0" 
      device: "//192.168.0.13/satashare/docker/immich/artifacts/model-cache"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=storage/upload
THUMB_LOCATION=thumbs
ENCODED_VIDEO_LOCATION=encoded-video

MODEL_CACHE_LOCATION=model-cache

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=*******

# The values below this line do not need to be changed
###################################################################################
#DB_HOSTNAME=immich_postgres
DB_HOSTNAME=192.168.0.13
DB_PORT=5433
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./db_data

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Administration
2. External Libraries
3. Click 'Scan All Libraries"
...
```

### Relevant log output

```shell
No errors in logs
```

### Additional information

I'm able to browse photos, watch videos. However this seems to be some geenral issue with jobs as when I try to recreate thumbnails for a single photo - the thumbnails job is also stuck:
![image](https://github.com/immich-app/immich/assets/27864579/97a71dac-3618-4207-b259-981f0c02f570)

I'm using immich since 1.101 and until 1.106 everything was working fine.
