### ISSUE TITLE
Cannot download album with a public share link

### ISSUE THREAD

**Issue by milenpenchev** [immich-app/immich#10951]
### The bug

Share an album with a public link (download enabled) and open it in an incognito browser. The download button on individual images works, but the download button on the album level does not work. The following JS error is seen in the console:

`asset-utils.D9Q8eUVV.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'download')
    at ie (asset-utils.D9Q8eUVV.js:1:4557)
    at Ge (asset-utils.D9Q8eUVV.js:1:4303)
    at HTMLButtonElement.U (18.09ibMD7n.js:1:9595)
    at scheduler.Bogm_FVb.js:1:9812
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.he (scheduler.Bogm_FVb.js:1:9799)
    at HTMLButtonElement.S (circle-icon-button.Bm_xjEoA.js:1:2457)`

It seems that here `archiveSize: s.download.archiveSize` - s is undefined.

This works fine if the user is logged into Immich with their own account and has access to the album. But it does not for public users/incognito shares.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - custom_network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - custom_network

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - custom_network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - custom_network

networks:
  custom_network:
    external: true

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Sofia

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=itisasecret

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immesh
```

### Reproduction steps

```bash
1. Create an album
2. Create a shared album link (public download should be enabled)
3. Copy the URl of the link and open in a different browser where you are not logged into Immich (or Incognito)
4. Click the download album button at the top right

Expected behaviour - a zip of the album should start downloading. Instead, nothing happens and a log message is visible in the JS console
```

### Relevant log output

```shell
asset-utils.D9Q8eUVV.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'download')
    at ie (asset-utils.D9Q8eUVV.js:1:4557)
    at Ge (asset-utils.D9Q8eUVV.js:1:4303)
    at HTMLButtonElement.U (18.09ibMD7n.js:1:9595)
    at scheduler.Bogm_FVb.js:1:9812
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.he (scheduler.Bogm_FVb.js:1:9799)
    at HTMLButtonElement.S (circle-icon-button.Bm_xjEoA.js:1:2457)
```
