### ISSUE TITLE
Immich is no longer running jobs and throwing an error when attempting to view jobs after upgrading vector.rs

### ISSUE THREAD

**Issue by VirtualDisk** [immich-app/immich#10966]
### The bug

Turns out my thumbnails haven't been updating for a few weeks after upgrading vector.rs to v0.2.1. 

This is the error I get when going to `administration` -> `jobs` in the UI:

```
Internal Server Error - 500
de@https://photo.asinine.world/_app/immutable/chunks/fetch-client.vy9D4DHV.js:1:2948
fe@https://photo.asinine.world/_app/immutable/chunks/fetch-client.vy9D4DHV.js:1:2872
```

I left the corresponding pod logs in the fields below.

### The OS that Immich Server is running on

Talos K8s Cluster

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
helm values:

postgresql:                                                                                                                                                                       
  global:                                                                                                                                                                         
    postgresql:                                                                                                                                                                   
      auth:                                                                                                                                                                       
        existingSecret: immich-postgresql-auth                                                                                                                                    
env:                                                                                                                                                                              
  REDIS_HOSTNAME: "dragonfly.datastores.svc.cluster.local"                                                                                                                        
  DB_HOSTNAME:                                                                                                                                                                    
    valueFrom:                                                                                                                                                                    
      secretKeyRef:                                                                                                                                                               
        name: immich-postgresql-auth                                                                                                                                              
        key: hostname                                                                                                                                                             
  DB_USERNAME:                                                                                                                                                                    
    valueFrom:                                                                                                                                                                    
      secretKeyRef:                                                                                                                                                               
        name: immich-postgresql-auth                                                                                                                                              
        key: username                                                                                                                                                             
  DB_DATABASE_NAME:                                                                                                                                                               
    valueFrom:                                                                                                                                                                    
      secretKeyRef:                                                                                                                                                               
        name: immich-postgresql-auth                                                                                                                                              
        key: database                                                                                                                                                             
  DB_PASSWORD:                                                                                                                                                                    
    valueFrom:                                                                                                                                                                    
      secretKeyRef:                                                                                                                                                               
        name: immich-postgresql-auth                                                                                                                                              
        key: password                                                                                                                                                             
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance 
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"                                                                                                              
image:                                                                                                                                                                            
  # renovate: datasource=docker depName=ghcr.io/immich-app/immich-server                                                                                                          
  tag: v1.107.2                                                                                                                                                                   
immich:                                                                                                                                                                           
  persistence:                                                                                                                                                                    
    library:                                                                                                                                                                      
      existingClaim: immich-photos                                                                                                                                                
microservices:                                                                                                                                                                    
  controller:                                                                                                                                                                     
    replicas: 2                                                                                                                                                                   
redis:                                                                                                                                                                            
  enabled: false                                                                                                                                                                  
server:                                                                                                                                                                           
  ingress:                                                                                                                                                                        
    main:                                                                                                                                                                         
      annotations:                                                                                                                                                                
        acme.cert-manager.io/http01-edit-in-place: "true"                                                                                                                         
        cert-manager.io/cluster-issuer: letsencrypt-prod                                                                                                                          
        cert-manager.io/common-name: &host "photo.asinine.world"                                                                                                                  
        cert-manager.io/issue-temporary-certificate: "true"                                                                                                                       
      enabled: true                                                                                                                                                               
      hosts:                                                                                                                                                                      
        - host: *host                                                                                                                                                             
          paths:                                                                                                                                                                  
            - path: /                                                                                                                                                             
      ingressClassName: ingress-nginx-ext                                                                                                                                         
      tls:                                                                                                                                                                        
        - hosts:                                                                                                                                                                  
            - *host                                                                                                                                                               
          secretName: immich-cert                                                                                                                                                 
typesense:                                                                                                                                                                        
  enabled: true                                                                                                                                                                   
  persistence:                                                                                                                                                                    
    tsdata:                                                                                                                                                                       
      enabled: true
```

### Your .env content

```Shell
Environment:
      DB_DATABASE_NAME:             <set to the key 'database' in secret 'immich-postgresql-auth'>  Optional: false
      DB_HOSTNAME:                  <set to the key 'hostname' in secret 'immich-postgresql-auth'>  Optional: false
      DB_PASSWORD:                  <set to the key 'password' in secret 'immich-postgresql-auth'>  Optional: false
      DB_USERNAME:                  <set to the key 'username' in secret 'immich-postgresql-auth'>  Optional: false
      IMMICH_MACHINE_LEARNING_URL:  http://immich-machine-learning:3003
      REDIS_HOSTNAME:               dragonfly.datastores.svc.cluster.local
```

### Reproduction steps

```bash
1. Have immich connected to a database on vector.rs v0.2.0
2. Upgrade vector.rs to v0.2.1
```

### Relevant log output

```shell
[Nest] 17  - 07/09/2024, 3:11:11 AM   ERROR [Api:ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)~ixii6m9z] ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
[Nest] 17  - 07/09/2024, 3:11:11 AM   ERROR [Api:ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)~j8k6qfbi] Failed to get all jobs status
[Nest] 17  - 07/09/2024, 3:11:11 AM   ERROR [Api:ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)~j8k6qfbi] ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
[Nest] 17  - 07/09/2024, 3:11:11 AM   ERROR [Api:ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)~tjegon1h] Failed to get all jobs status
[Nest] 17  - 07/09/2024, 3:11:11 AM   ERROR [Api:ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
    at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)~tjegon1h] ReplyError: ERR Error running script (call to c3492fe177eb731466da99249adcb24b4985f0f3): @user_script:27: script tried accessing undeclared key, key: immich_bull:thumbnailGeneration:active
```
