### ISSUE TITLE
Motion Photos on Android are updated as regular non motion photos

### ISSUE THREAD

**Issue by nachadan** [immich-app/immich#10986]
### The bug

Hello, motion photos uploaded to the immich server are losing motion function after being uploaded. After downloading here provided file i am able to see motion with the windows photos. I am also able to see motion in google photos but i dont see any motion in Immich. Do you have any ideas, how to resolve this? Thank you very much for support

[PXL_20240709_181812848.MP.jpg.zip](https://github.com/user-attachments/files/16149860/PXL_20240709_181812848.MP.jpg.zip)

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.107.1 build.146

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /mnt/shared_data/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'

    volumes:
      - /mnt/shared_data/immich/db_data:/var/lib/postgresql/data
      - /mnt/shared_data/immich/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: pg_isready --dbname=immich || exit 1; Chksum="$$(psql --dbname=immich --username=postgres -c 'SELECT last_vacuum FROM pg_stat_user_tables WHERE relname=''media'';' -t -A)"; if [ -z "$$Chksum" ]; then exit 1; fi
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors']
    restart: always


volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immi                                                                                   ch.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/shared_data/immich/upload
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/shared_data/immich/db_data

DB_HOST=immich_postgres
DB_PORT=5432

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifi                                                                                   er from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#                                                                                   List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.                                                                                   0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
################################################################################                                                                                   ###
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1.
2.
3.
...
```
