### ISSUE TITLE
Error downloading bulk from link-share

### ISSUE THREAD

**Issue by SamedHaveri** [immich-app/immich#11013]
### The bug

When sharing media with link it allows to download only one image per time. If the button Top Right corner is pressed it throws error and also when i select multiple items.
![Screenshot 2024-07-10 220352](https://github.com/immich-app/immich/assets/106157591/e672dc72-a621-4237-9ca9-1092cf9a1446)

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

1.107.2

### Version of Immich Mobile App

1.108.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/b/Backups/immich_backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.107.2

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=123

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Share media with link
2. Open link (also used password)
3. Try to download multiple items
...
```

### Relevant log output

```shell
Web console log:
asset-utils.BziJEGvZ.js:1 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'download')
    at ie (asset-utils.BziJEGvZ.js:1:4557)
    at HTMLButtonElement.c (download-action.mjMUTs1y.js:1:1695)
    at scheduler.Bogm_FVb.js:1:9812
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.he (scheduler.Bogm_FVb.js:1:9799)
    at HTMLButtonElement.S (circle-icon-button.Bm_xjEoA.js:1:2457)
```
