### ISSUE TITLE
The option "Display a link to People in the sidebar" is not user specific

### ISSUE THREAD

**Issue by pinbong** [immich-app/immich#11020]
### The bug

Enabling/disabling the option :
Account Settings -> App Settings -> People
Enables/disables the option for all users

### The OS that Immich Server is running on

Debian 12, fully updated

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
        #- ${EXTERNAL_PATH_John}:/usr/src/app/external/john
        #- ${EXTERNAL_PATH_Michelle}:/usr/src/app/external/michelle
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
        #- pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  #pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./immich/upload
PGDATA=./immich/pgdata

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Log into Immich via a web browser as user A (Firefox in this case)
2. Enable Account Settings -> App Settings -> People
3. Log out user A
4. Log into Immich via a web browser as user B
5. The "People" link is already enabled.
6. Disnable Account Settings -> App Settings -> People
7. Log out user B
8. Log into Immich via a web browser as user A
9. The "People" link is now disabled
```

### Additional information

This is a brand new installation an hour ago. Immich has not been installed on this machine previously
Only one photo was uploaded then deleted (as admin user)
Two users were added
Storage templates are enabled, used the default template with no changes

Docker version 27.0.3, build 7d4bcd8
