### ISSUE TITLE
Android app does not load full/original image

### ISSUE THREAD

**Issue by wlamers** [immich-app/immich#11048]
### The bug

While zooming in on an image asset in the Android app (at least since v105 till v108) the original image is never loaded/shown. Only the small and medium thumb are shown. Zooming in on the asses in the web browser does work flawlessly. I have tried all combinations of the following setting in the Android app with no success/difference:
```
Asset Viewer->Load preview image
Asset Viewer->Load original image
Advanced->Prefer remote images
```

I even tried to replace the original image on the server (SSH'ing into it) with another random image. If I then look at the image in thew web browser I indeed see the small thumb, medium thumb and when I zoom I indeed see the new random (totally different) image. In the Android app it keeps showing the medium thumb, and never loads the random image.

I also played with the Admin->Image setting, settings. Currently I have:
```
Thumbnail format: WebP
Thumbnail resolution: 200p
Preview format: JPEG
Preview resolution: 720p
Quality: 70
Prefer wide gamut: on
Prefer embedded preview: off
```

Is there something I am missing?

### The OS that Immich Server is running on

Debian 12, docker-ce

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0 build.148

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      # service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTOSVIDEOS_LOCATION}:/mnt/PhotosVideos/CURRENT:ro
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    # image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      # service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
  
volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Immich/upload
PHOTOSVIDEOS_LOCATION=/mnt/PhotosVideos/CURRENT
THUMB_LOCATION=/mnt/disk2/Immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/disk2/Immich/encoded-video
PROFILE_LOCATION=/mnt/disk2/Immich/profile
DB_DATA_LOCATION=/mnt/disk2/postgres
IMMICH_VERSION=release
DB_PASSWORD=xxx
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. upload image
2. process thumb and preview
3. watch image in Android app, zoom in on image -> only the medium preview is show
```

### Relevant log output

```shell
No output visible using 'docker compose logs -f' when loading or zooming in.
```

### Additional information

-
