### ISSUE TITLE
[BUG] microservices container keep restarting

### ISSUE THREAD

**Issue by PeterBasista** [immich-app/immich#1104]
**Describe the bug**
Microservices container keep restarting.

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [ ] I have included my `docker-compose` file.
- [ ] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

(I'am using default docker compose based on immich page installation guide)

**To Reproduce**
1. Start the stack (portainer)
2. microservices container keep restaring

**Expected behavior**
Microservices container keep running.

**Screenshots**
<img width="1087" alt="Snímka obrazovky 2022-12-14 o 9 32 30" src="https://user-images.githubusercontent.com/58752440/207545659-8834ba94-70ea-4ed0-974e-b4feb104768c.png">

Container log:
```
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +226ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] JwtModule dependencies initialized +3ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +41ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:20 AM     LOG [InstanceLoader] BullModule dependencies initialized +3ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +624ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG Initialising Reverse Geocoding
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] ImmichJwtModule dependencies initialized +36ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] ImmichConfigModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] CommunicationModule dependencies initialized +1ms
[Nest] 7  - 12/14/2022, 8:32:21 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +2ms
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 11 on line 44811
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:933:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:896:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1325:26)
    at Parser.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:723:7)
    at finishMaybe (node:internal/streams/writable:733:5)
    at afterWrite (node:internal/streams/writable:504:3)
    at onwrite (node:internal/streams/writable:477:7)
    at Parser.Transform._read (node:internal/streams/transform:245:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 7569408,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 44811,
  records: 44810,
  columns: false,
  error: undefined,
  header: false,
  [] index: 11,
  raw: undefined,
  column: 11,
  quoting: false,
  record: [
    '2874142', 'Malberg',
    'Malberg', '',
    '50.05',   '6.58333',
    'P',       'PPLA4',
    'DE',      '',
    '08'
  ]
}
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +232ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] JwtModule dependencies initialized +3ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +3ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +34ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] BullModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] BullModule dependencies initialized +3ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +584ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG Initialising Reverse Geocoding
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] ImmichJwtModule dependencies initialized +57ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] ImmichConfigModule dependencies initialized +2ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] CommunicationModule dependencies initialized +1ms
[Nest] 7  - 12/14/2022, 8:32:44 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +3ms
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 11 on line 44811
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:933:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:896:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1325:26)
    at Parser.final [as _final] (node:internal/streams/transform:112:25)
    at callFinal (node:internal/streams/writable:694:27)
    at prefinish (node:internal/streams/writable:723:7)
    at finishMaybe (node:internal/streams/writable:733:5)
    at afterWrite (node:internal/streams/writable:504:3)
    at onwrite (node:internal/streams/writable:477:7)
    at Parser.Transform._read (node:internal/streams/transform:245:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 7569408,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 44811,
  records: 44810,
  columns: false,
  error: undefined,
  header: false,
  [] index: 11,
  raw: undefined,
  column: 11,
  quoting: false,
  record: [
    '2874142', 'Malberg',
    'Malberg', '',
    '50.05',   '6.58333',
    'P',       'PPLA4',
    'DE',      '',
    '08'
  ]
}

```

**System**
- Phone OS [iOS, Android]: `IOS`
- Server Version: `1.38.2`
- Mobile App Version: `1.38.0 Build.75`

**Comment by bo0tzz** [comment]
Can you post the full logs of the microservices container after recreating it up to the latest error you posted?

**Comment by PeterBasista** [comment]
The problem is that I managed to capture a bit more probably by accident. After the container recreate, the logs of the old container are cleared and a loop starts with the microservices starting and then above (loop) log. Which means I can't get to the log of the old container. The only thing I know is that it generated a thumbnail for the video (mov) before and ended up with an error from ffmpeg that the file is invalid... But I don't remember the exact error.

**Comment by PeterBasista** [comment]
Okay, it happened to me again, I'm attaching a file with logs (entire log, 18mb and a slice, something before the first error and then a loop - 145kb)

P.s.: Error from object detection is fine for me, the container is turned off because I don't need it to detect objects
Logs are from docker

Line 85 - the first error that triggered a container restart loop - [min.log](https://github.com/immich-app/immich/files/10235505/4c7d9ec16a4a9db32802bc2342997a5a82224916e5f31b4f9a2d6a03e84210d8-json.min.log)
Line 85 -> line 59380 [fulllog.log](https://github.com/immich-app/immich/files/10235506/4c7d9ec16a4a9db32802bc2342997a5a82224916e5f31b4f9a2d6a03e84210d8-json.log)

**Comment by bo0tzz** [comment]
When the microservices container starts, it tries to download the geocoder data in the background. That process is failing - the network connection is timing out or aborting. From inside the microservices container, can you test whether it can reach the geodata URL with `wget https://download.geonames.org/export/dump/`?

**Comment by PeterBasista** [comment]
Here is the result
<img width="1080" alt="Snímka obrazovky 2022-12-15 o 12 31 46" src="https://user-images.githubusercontent.com/58752440/207848934-e08ccd97-4cff-4c37-aa94-2d3c8d0af1e9.png">

**Comment by alextran1502** [comment]
Can you include your `docker-compose` content?

**Comment by PeterBasista** [comment]
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    profiles:
      - donotstart
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```
