### ISSUE TITLE
[BUG] Sony RAW(.ARW) cannot be uploaded

### ISSUE THREAD

**Issue by missuo** [immich-app/immich#1109]
**Describe the bug**
I can't upload all the photos in my phone that end with ".ARW"(Sony RAW).

**Task List**
- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Open `Immich` on iOS.
2. Waiting for automatic upload.
3. See error

**Expected behavior**
It can be uploaded normally as a normal photo and can be previewed.

**Screenshots**

![417cff77c1d5ade59f193](https://telegraph.eowo.us/file/417cff77c1d5ade59f193.png)

**System**
- Phone OS [iOS]: `16.2/16.3 Beta1`
- Server Version: `1.38.2`
- Mobile App Version: `1.36.1 Build.72`

**Additional context**
## docker-compose
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 12283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

## .env
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/pool2/Immich
LOG_LEVEL=simple
JWT_SECRET=W0ofOoybvrbk6JmumwXW71vDdY1l1a1pkzmF29pkcP3Yr/YXDrcaFXzYj63DQHBvVMKv9K1jhaQYsDqkKVPg2dPdB0lOJG/EmiZk6tbTf2a+cddFpOGl+50uFGic4XaZkzplpufjQq5slp3KQqMY4GGxxTUzbzztmmsLSqU/zRI=
PUBLIC_LOGIN_PAGE_MESSAGE=
```
