### ISSUE TITLE
API not working on fresh install - Cannot connect App

### ISSUE THREAD

**Issue by akorb90** [immich-app/immich#11111]
### The bug

Good Morning everyone,

I have just set up a fresh install using docker compose in portainer.
I've followed the official docks and my instance is running fine when using a webbrowser.
Unfortunately I can't connect the App, it tells me my instance is unreachable.
When accessing the API URL in the browser I get this error:
![2024-07-15 07_46_17-Bestelldetails - Brave](https://github.com/user-attachments/assets/62f36c9f-9f1b-4e10-b34a-4fbf19bf951a)

I'd appreciate any sort of help :)

### The OS that Immich Server is running on

Debian 12 LXC on Proxmox

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/data/library
DB_DATA_LOCATION=/data/postgres
IMMICH_VERSION=release
DB_PASSWORD=verysecurepassword
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Accessing http://fqdn:2283/api in a webbrowser
2. Accessing http://fqdn:2283/api in the android app
```

### Relevant log output

```shell
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] ReportController {/api/reports}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/reports, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/reports/checksum, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/reports/fix, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SearchController {/api/search}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/metadata, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/smart, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/explore, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/person, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/places, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/cities, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/search/suggestions, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] ServerController {/api/server}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/about, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/storage, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/ping, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/version, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/features, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/theme, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/config, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/statistics, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/media-types, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server/license, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] ServerInfoController {/api/server-info}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/about, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/storage, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/ping, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/version, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/features, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/theme, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/config, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/statistics, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/server-info/media-types, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SessionController {/api/sessions}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/sessions/:id, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SharedLinkController {/api/shared-links}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/me, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, PATCH} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/shared-links/:id/assets, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SyncController {/api/sync}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/full-sync, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/sync/delta-sync, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SystemConfigController {/api/system-config}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/defaults, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-config/storage-template-options, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] SystemMetadataController {/api/system-metadata}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/admin-onboarding, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/system-metadata/reverse-geocoding-state, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] TagController {/api/tags}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PATCH} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 17  - 07/15/2024, 5:51:18 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.108.0] [PRODUCTION]
```
