### ISSUE TITLE
Newly uploaded pictures are not visible / Library Jobs are not running anymore after updating to 1.108.0

### ISSUE THREAD

**Issue by nickelswitte** [immich-app/immich#11116]
### The bug

After updating to 1.108.0, I uploaded some more pictures. They seem to be uploaded (I could download the original), but they were not displaying in the gallery:
![grafik](https://github.com/user-attachments/assets/b8439cff-2f39-4cf7-8b8d-7a774bdaccac)

Digging a little deeper, I could find out that Immich is not running the library jobs anymore (in this case, the thumbnail job seems to be the one preventing me from seeing my pictures). They are shown as 'waiting' but are never executed.

### The OS that Immich Server is running on

Ubuntu 20.04.6

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

networks:
  default:
    external: true
    name: nginx-proxy-manager
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
TZ=Europe/Brussels
DB_PASSWORD=<pass>
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Upload files
2. Refresh Page
3. Check Thumbnails
4. Check jobs in Administration pane
5. See that they are not executed
```

### Relevant log output

```shell
Nothing is printed regarding jobs, even on loglevel debug
```
