### ISSUE TITLE
Some files are not synchronized on android 14, realme 12

### ISSUE THREAD

**Issue by zlo2k** [immich-app/immich#11164]
### The bug

Some files are not synchronized, Camera folder is selected, all photos are taken by the built-in camera app, the app shows that all files are synchronized, however when manually adding a file is synchronized, but the file count does not increase.

<details>

<summary>Normal file information </summary>

```json
   {
  "id": 229148,
  "remoteId": "ec5a036d-15be-4056-b7ab-023a5b6ee4f7",
  "localId": "1000015013",
  "checksum": "11VKuSsz9VMBt+lp5F9xYqVmr/8=",
  "ownerId": -1252206354784749421,
  "livePhotoVideoId": "N/A",
  "stackCount": "null",
  "stackParentId": "N/A",
  "fileCreatedAt": "2024-07-01 12:34:10.102",
  "fileModifiedAt": "2024-07-01 12:34:10.000",
  "updatedAt": "2024-07-01 15:33:39.801",
  "durationInSeconds": 0,
  "type": "AssetType.image",
  "fileName": "IMG20240701123410.jpg",
  "isFavorite": false,
  "isRemote": true,
  "storage": "AssetState.merged",
  "width": 4096,
  "height": 2304,
  "isArchived": false,
  "isTrashed": false,
  "isOffline": false,
}
```

</details>

<details>

<summary>Missing file information </summary>

```json
   {
  "id": 229220,
  "remoteId": "N/A",
  "localId": "1000015012",
  "checksum": "u6raMzpiUDpzxbH23o7vr2CgL+g=",
  "ownerId": -1252206354784749421,
  "livePhotoVideoId": "N/A",
  "stackCount": "0",
  "stackParentId": "N/A",
  "fileCreatedAt": "2024-07-01 12:34:05.000",
  "fileModifiedAt": "2024-07-01 12:34:05.000",
  "updatedAt": "2024-07-01 12:34:05.000",
  "durationInSeconds": 0,
  "type": "AssetType.image",
  "fileName": "IMG20240701123405.jpg",
  "isFavorite": false,
  "isRemote": false,
  "storage": "AssetState.local",
  "width": 4096,
  "height": 2304,
  "isArchived": false,
  "isTrashed": false,
  "isOffline": false,
}
```

</details>

<details>

<summary>Synchronization status information</summary>

![image](https://github.com/user-attachments/assets/93d07a7f-edf7-448e-b22e-8f1fc998393d)

</details>

![image](https://github.com/user-attachments/assets/8ef7bf13-f8fb-4634-ba40-c7083c9fb5b2)

### The OS that Immich Server is running on

Ubuntu 20.04.5 LTS x86_64(Py3.7.9)

### Version of Immich Server

v1.108.0

### Version of Immich Mobile App

v1.108.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001  
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs    
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

LOG_LEVEL=log

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

#UPLOAD_LOCATION=/home/im_photos/
UPLOAD_LOCATION=/mnt/disk1/im_photos/


# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=sdfuysdfuywnrkvhvslkddgsb
TYPESENSE_ENABLED=true

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Photos"

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

THUMBS_LOCATION=/home/im_photos/thumb
```

### Reproduction steps

```bash
1. Select Camera album for backup
2. Run backup
3. Restart app, check local album Camera in app
```
