### ISSUE TITLE
dynamic (live) photo is static

### ISSUE THREAD

**Issue by ilyaChuk** [immich-app/immich#11171]
### The bug

I am taking dynamic (live) photos on my pixel 7 com.google.android.Google Camera 9.4.103.641377609.23. 

In the Google Photos app, the picture can be played as a video. Even from the web interface from a computer. 
In immich, the same picture cannot be played, there is no dynamic photo icon. Neither from a smartphone nor from a computer web browser.
![image](https://github.com/user-attachments/assets/43160bd0-2890-466c-a786-f38b3155b715)

There is also a problem if you upload photos from your smartphone. And if from a computer web interface.
website https://dj0001.github.io/Motion-Photo-Viewer/ can play this photo.
this photo - https://github.com/user-attachments/assets/1100a0c6-4394-4cbe-a463-8f5d20f74064

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.108.0

### Version of Immich Mobile App

1.108.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.3

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.4

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.5

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.2

networks:
  immich_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/pi/raid/immich/lib
DB_DATA_LOCATION=/home/pi/raid/immich/db

IMMICH_VERSION=release
DB_PASSWORD=--------
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. download my live photo https://github.com/user-attachments/assets/1100a0c6-4394-4cbe-a463-8f5d20f74064
2. drag and drop it to immich chrome 126 http:// web ui. or upload from android app.
3. see the inability to play this video (no icon button)
```

### Relevant log output

```shell
https://github.com/user-attachments/files/16273464/logsimmich.txt
```
