### ISSUE TITLE
Both machine learning and main server containers no longer start up in latest release

### ISSUE THREAD

**Issue by Woodie-07** [immich-app/immich#11190]
### The bug

I'm running Immich under Umbrel on a Pi 5, and after updating to the latest release, both the main server container and the machine learning container no longer starts up. Configs are mostly from default Umbrel, but with the container versions updated to latest.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.109.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.7"

x-environment: &env
  NODE_ENV: "production"
  DB_HOSTNAME: "immich_postgres_1"
  DB_USERNAME: &db_username "immich"
  DB_PASSWORD: &db_password "moneyprintergobrrr"
  DB_DATABASE_NAME: &db_database_name "immich"
  REDIS_HOSTNAME: "immich_redis_1"
  LOG_LEVEL: "log"
  JWT_SECRET: ${APP_SEED}
  DISABLE_REVERSE_GEOCODING: "false"
  REVERSE_GEOCODING_PRECISION: "3"
  PUBLIC_LOGIN_PAGE_MESSAGE: ""
  IMMICH_MACHINE_LEARNING_URL: "http://immich_machine-learning_1:3003"

services:
  app_proxy:
    environment:
      APP_HOST: immich_server_1
      APP_PORT: 3001
      PROXY_AUTH_WHITELIST: "/api/*,/search/*"

  server:
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      <<: *env
    ports:
      - "3002:3001"
    depends_on:
      - redis
      - postgres
    restart: on-failure

  microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${APP_DATA_DIR}/data/upload:/usr/src/app/upload
    environment:
      <<: *env
    depends_on:
      - redis
      - postgres
    restart: on-failure

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${APP_DATA_DIR}/data/model-cache:/cache
    environment:
      <<: *env
    restart: on-failure

  redis:
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data

  postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    user: "1000:1000"
    environment:
      <<: *env
      POSTGRES_PASSWORD: *db_password
      POSTGRES_USER: *db_username
      POSTGRES_DB: *db_database_name
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    restart: on-failure
```

### Your .env content

```Shell
#!/usr/bin/env bash
# This script sets up necessary directories/permissions that have changed in the app since the initial release. 

set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Create model-cache directory if it doesn't exist
MODEL_CACHE_DIR="${APP_DATA_DIR}/model-cache"
[ ! -d "${MODEL_CACHE_DIR}" ] && mkdir -p "${MODEL_CACHE_DIR}" && chown 1000:1000 "${MODEL_CACHE_DIR}"

# delete tsdata directory if it exists
TYPESENSE_DIR="${APP_DATA_DIR}/tsdata"
[ -d "${TYPESENSE_DIR}" ] && rm -rf "${TYPESENSE_DIR}"
```

### Reproduction steps

```bash
1. Launch the latest version of Immich in Docker under Debian 12 on ARM64 machine
2. Check container logs
```

### Relevant log output

```shell
Machine learning container error:
usage: gunicorn [OPTIONS] [APP_MODULE]
gunicorn: error: argument -w/--workers: invalid int value: ''

Main server container error:
Node.js v20.15.1
Detected CPU Cores: 4
/usr/src/app/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
  ^

Error: Could not load the "sharp" module using the linux-arm64 runtime
ERR_DLOPEN_FAILED: libwebpdemux.so.2: cannot open shared object file: No such file or directory
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
```
