### ISSUE TITLE
Migration "AddFaceSearchRelation1718486162779" failed

### ISSUE THREAD

**Issue by LJAM96** [immich-app/immich#11202]
### The bug

Since at least version v1.107.2, my Immich server has stopped functioning after updates, with the issue seemingly originating from the Postgres server. 
I've updated to v1.109.2 hoping to resolve the problem, but it persists.

Based on similar logs and suggested fixes, I've tried the following SQL commands:
```
DROP INDEX face_index;
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE real[];
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE vector(512);
```

However, these attempts have not resolved the issue.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

V

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
volumes:
  pgdata:
  model-cache:
  redis:
  pgadmin-data:
  
networks:
  frontend:
    name: frontend
    external: true
  backend:
    name: backend
    external: true
    
services:
  immich-server:
    container_name: immich_server
    image: 'ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}'
    volumes:
      - '${UPLOAD_LOCATION}:/usr/src/app/upload'
      - '/etc/localtime:/etc/localtime:ro'
    env_file:
      - stack.env
    networks:
      - frontend
      - backend
    ports:
      - '2283:3001'
    depends_on:
      - redis
      - database
    restart: always

    
  immich-machine-learning:
    container_name: immich_machine_learning
    image: 'ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}'
    volumes:
      - 'model-cache:/cache'
    env_file:
      - stack.env
    networks:
      - backend
    restart: always
    
  redis:
    container_name: immich_redis
    image: 'redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b'
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - 'redis:/data'
    networks:
      - backend
    restart: always
    
  database:
    container_name: immich_postgres
    image: 'tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0'
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_DB: '${DB_DATABASE_NAME}'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    networks:
      - backend
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=********
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/home/ubuntu/appdata/immich
TYPESENSE_API_KEY=********
PUBLIC_LOGIN_PAGE_MESSAGE="*****"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
PUID=1001
PGID=1001
TZ=Europe/London
```

### Reproduction steps

```bash
1. update to v1.107.2 
2. u/k
3. u/k
...
```

### Relevant log output

```shell
Detected CPU Cores: 4

Starting api worker

Starting microservices worker

[Nest] 7  - 07/18/2024, 10:46:50 PM     LOG [Microservices:EventRepository] Initialized websocket server

[Nest] 17  - 07/18/2024, 10:46:50 PM     LOG [Api:EventRepository] Initialized websocket server

Migration "AddFaceSearchRelation1718486162779" failed, error: pgvecto.rs: The extension is upgraded so all index files are outdated.

ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.

QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.

ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.

    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:39:9)

    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)

    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)

    at async /usr/src/app/dist/services/database.service.js:136:17

    at async /usr/src/app/dist/repositories/database.repository.js:177:23 {

  query: '\n' +

    '      CREATE INDEX IF NOT EXISTS clip_index ON smart_search\n' +

    '      USING hnsw (embedding vector_cosine_ops)\n' +

    '      WITH (ef_construction = 300, m = 16)',

  parameters: undefined,

  driverError: error: pgvecto.rs: The extension is upgraded so all index files are outdated.

  ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.

      at /usr/src/app/node_modules/pg/lib/client.js:526:17

      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)

      at async AddFaceSearchRelation1718486162779.up (/usr/src/app/dist/migrations/1718486162779-AddFaceSearchRelation.js:39:9)

      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)

      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)

      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)

      at async /usr/src/app/dist/services/database.service.js:136:17

      at async /usr/src/app/dist/repositories/database.repository.js:177:23 {

    length: 203,

    severity: 'ERROR',

    code: 'XX000',

    detail: undefined,

    hint: undefined,

    position: undefined,

    internalPosition: undefined,

    internalQuery: undefined,

    where: undefined,

    schema: undefined,

    table: undefined,

    column: undefined,

    dataType: undefined,

    constraint: undefined,

    file: 'error.rs',

    line: '7',

    routine: undefined

  },

  length: 203,

  severity: 'ERROR',

  code: 'XX000',

  detail: undefined,

  hint: undefined,

  position: undefined,

  internalPosition: undefined,

  internalQuery: undefined,

  where: undefined,

  schema: undefined,

  table: undefined,

  column: undefined,

  dataType: undefined,

  constraint: undefined,

  file: 'error.rs',

������
  line: '7',

  routine: undefined

}

microservices worker exited with code 1
```

```[tasklist]
### Tasks
```
