### ISSUE TITLE
【ERROR】My 'GENERATE THUMBNAILS' function has been unable to complete

### ISSUE THREAD

**Issue by 9k001** [immich-app/immich#11211]
### The bug

First of all, my fault stems from the failure of IOS image upload thumbnail generation,
1. Photo thumbnails appear cracked on the Web page.
2. The photo on the Web page does not contain any EXIF information, including latitude and longitude.
After I recently upgraded to v1.109.2 (both server and mobile), regenerating the cache still does not solve the problem.
The number of jobs has reached 33.
![image](https://github.com/user-attachments/assets/9f4784ac-0065-4dd4-8327-df479d482ad3)
Check docker logs of the server and database. No error is reported.
How can I solve this problem?

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.109.2

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.5'
services:
  immich-server:
    image: {{ PERFIX_DOCKER }}immich-app/immich-server:${IMMICH_VERSION}
    container_name: immich-server
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/immich-server/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ SERVER_MAPPING_PORT }}:${SERVER_PORT}"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/{{ MODE_ENV }}/server.env
    command: [ "start.sh", "immich" ]
    environment:
      - TZ=Asia/Shanghai
      - MODE_ENV={{ MODE_ENV }}

  immich-machine_learning:
    image: {{ PERFIX_DOCKER }}immich-app/immich-machine-learning:${IMMICH_VERSION}
    container_name: immich-machine_learning
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/machine_learning/cache:/cache
    ports:
      - "{{ MACHINE_LEARNING_MAPPING_PORT }}:${MACHINE_LEARNING_PORT}"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/{{ MODE_ENV }}/machine_learning.env
    environment:
      - TZ=Asia/Shanghai
      - MODE_ENV={{ MODE_ENV }}

networks:
  default:
    name: "{{ MODE_ENV }}"
    external: true
```

### Your .env content

```Shell
PERFIX_DOCKER={{ PERFIX_DOCKER }}

IMMICH_VERSION=release

SERVER_PORT=3001

MACHINE_LEARNING_PORT=3003
```

### Reproduction steps

```bash
1. Randomly select an image that's malfunctioning and click on "Refresh thumbnails"
```
