### ISSUE TITLE
Error 400 when saving Email Notification Settings

### ISSUE THREAD

**Issue by small-grey-dog** [immich-app/immich#11227]
### The bug

In the Administration Settings of the Immich web interface, I'm trying to enable email notifications using my Mailgun SMTP information. I've confirmed that all of the Mailgun information is correct. I've tried ports 25, 465, and 587.

When I click on 'Send test email and save', I receive the following error: **Error: 400 (Immich Server Error)**
When I click on 'Save', I receive the following error: **Invalid SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:587 (Immich Server Error)**

I've deployed Immich in Docker via Portainer Stack. I'm using Mailgun SMTP with my other self-hosted services without issue. Immich is accessible both on my local network and on the internet via NGINX reverse proxy.

I receive this error when I'm accessing the web interface both via my local network, and externally.

![Screenshot 2024-07-19 at 12 04 34 PM](https://github.com/user-attachments/assets/7351577e-d83d-4d37-be9c-c4c6d2e27398)

![Screenshot 2024-07-19 at 12 04 46 PM](https://github.com/user-attachments/assets/471b4c6a-4094-4875-9345-bdb03ca328cb)

### The OS that Immich Server is running on

Debian 12 (Linux 6.5.11-7-pve)

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.109.2 build.164

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_DATA_LOCATION=/root/docker/immich/database
DB_PASSWORD=*******************************
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
UPLOAD_LOCATION=/root/docker/immich/upload
THUMB_LOCATION=/root/docker/immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/data/photos/encoded-video
PROFILE_LOCATION=/root/docker/immich/profile
LIBRARY_LOCATION=/mnt/data/photos/library
```

### Reproduction steps

```bash
1. Log in to Immich web interface.
2. Go to 'Administration'.
3. Go to 'Settings'
4. Go to 'Notification Settings'
5. Click on 'Email'
6. Toggle 'Enable Email Notifications' on.
7. Enter SMTP information.
8. Click on either 'Send test email and save' or 'Save'
```

### Relevant log output

```shell
[Nest] 17  - 07/19/2024, 6:12:18 PM   ERROR [Api:NotificationService~clm397zc] Failed to validate SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:587
Error: connect ECONNREFUSED 0.0.0.0:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 07/19/2024, 6:12:18 PM    WARN [Api:SystemConfigService~clm397zc] Unable to save system config due to a validation error: Error: Invalid SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:587
[Nest] 17  - 07/19/2024, 6:12:19 PM   ERROR [Api:NotificationService~o45cnacs] Failed to validate SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:587
Error: connect ECONNREFUSED 0.0.0.0:587
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 07/19/2024, 6:12:19 PM    WARN [Api:SystemConfigService~o45cnacs] Unable to save system config due to a validation error: Error: Invalid SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:587
[Nest] 17  - 07/19/2024, 6:12:32 PM   ERROR [Api:NotificationService~kffcn6aw] Failed to validate SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:25
Error: connect ECONNREFUSED 0.0.0.0:25
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 07/19/2024, 6:12:32 PM    WARN [Api:SystemConfigService~kffcn6aw] Unable to save system config due to a validation error: Error: Invalid SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:25
[Nest] 17  - 07/19/2024, 6:12:37 PM   ERROR [Api:NotificationService~qw3rx8p1] Failed to validate SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:25
Error: connect ECONNREFUSED 0.0.0.0:25
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 07/19/2024, 6:12:37 PM    WARN [Api:SystemConfigService~qw3rx8p1] Unable to save system config due to a validation error: Error: Invalid SMTP configuration: Error: connect ECONNREFUSED 0.0.0.0:25
```

### Additional information

I'm using Mailgun as my SMTP provider. I've used it with all of my other self-hosted services without issue.
