### ISSUE TITLE
Android app does not play live photo

### ISSUE THREAD

**Issue by ilyaChuk** [immich-app/immich#11229]
### The bug

after the previous bug #11171 and the fix, the situation with live photos still doesn't work perfectly. They play normally from the browser. But with the android app, when you click on the live photo icon button, it gets stuck on the first frame of the video. And it doesn't move. the problem is not with all photos. the old ones are working fine.

Example of a non-working photo - https://github.com/user-attachments/assets/1100a0c6-4394-4cbe-a463-8f5d20f74064
An example of a working photo - https://github.com/user-attachments/assets/e5153cb6-4bf5-43f7-a5af-dcf95e54120f

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.109.2

### Version of Immich Mobile App

1.109.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.3

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.4

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.5

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.18.0.2

networks:
  immich_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/pi/raid/immich/lib
DB_DATA_LOCATION=/home/pi/raid/immich/db

IMMICH_VERSION=release
DB_PASSWORD=--------
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Upload this photo https://github.com/user-attachments/assets/1100a0c6-4394-4cbe-a463-8f5d20f74064.
2. Open this photo in the android application and click the live photo icon at the top.
3. You will see that the video is not moving. There's only the first frame hanging there.
4. But this photo is normally played in the browser
```

### Relevant log output
x.x.x.x I hid my ip address.
```shell
the server with the problematic photo:
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM     LOG [Api:EventRepository] Websocket Connect:    y3kEIQbFsZ7PkLBlAAAx
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~vuzhmg4r] GET /api/users 200 2.12ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:EventRepository] Server event: websocket.connect (send)
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~8nvjfhtj] GET /api/server-info/features 200 10.90ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~5mc0sm3o] GET /api/partners?direction=shared-by 200 3.69ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~7cqolw85] GET /api/assets/memory-lane?day=19&month=7 200 23.37ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~oj9flq7c] GET /api/partners?direction=shared-by 200 13.62ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~odi373zc] GET /api/server-info/storage 200 11.26ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~yldl1erb] GET /api/server-info/config 200 47.16ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~qv8a0mpk] GET /api/partners?direction=shared-with 200 10.45ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~iqv3x76q] GET /api/partners?direction=shared-with 200 5.23ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~ppruja3f] GET /api/albums 200 19.24ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:39 PM   DEBUG [Api:LoggingInterceptor~j15k2vah] POST /api/sync/delta-sync 200 9.17ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:41 PM   DEBUG [Api:LoggingInterceptor~c4sxxy0y] GET /api/assets/device/f76f75687eeb4284daca3a0c75982a74426bb3f3f8808ba2032b3bca2eb881c4 200 5.39ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:42 PM   DEBUG [Api:LoggingInterceptor~fon3bwuw] GET /api/users 200 1.89ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:42 PM   DEBUG [Api:LoggingInterceptor~fpvy6uvz] GET /api/partners?direction=shared-by 200 1.33ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:42 PM   DEBUG [Api:LoggingInterceptor~866dc3t9] GET /api/partners?direction=shared-with 200 1.28ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:42 PM   DEBUG [Api:LoggingInterceptor~v579o82l] POST /api/sync/delta-sync 200 8.00ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:47 PM   DEBUG [Api:LoggingInterceptor~0dn3cttg] POST /api/auth/validateToken 200 0.17ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:52 PM   DEBUG [Api:LoggingInterceptor~yzntzved] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 126.16ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:52 PM   DEBUG [Api:LoggingInterceptor~utuzw2mn] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 3.69ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:52 PM   DEBUG [Api:LoggingInterceptor~mgn3fh49] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 223.35ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:52 PM   DEBUG [Api:LoggingInterceptor~dx4458wd] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 124.33ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:52 PM   DEBUG [Api:LoggingInterceptor~9bl00g7o] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.97ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:53 PM   DEBUG [Api:LoggingInterceptor~79q4n6q8] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 275.18ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:53 PM   DEBUG [Api:LoggingInterceptor~0w1awige] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 114.99ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:53 PM   DEBUG [Api:LoggingInterceptor~smm1id6s] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.39ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:53 PM   DEBUG [Api:LoggingInterceptor~dovh9z8c] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 462.98ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:54 PM   DEBUG [Api:LoggingInterceptor~c54rcese] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 115.84ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:54 PM   DEBUG [Api:LoggingInterceptor~fb14pshy] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.90ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:54 PM   DEBUG [Api:LoggingInterceptor~qjpmnmvn] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 187.58ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:54 PM   DEBUG [Api:LoggingInterceptor~cs6c2grk] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 163.22ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:54 PM   DEBUG [Api:LoggingInterceptor~erybqmir] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.71ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:55 PM   DEBUG [Api:LoggingInterceptor~4szcbjjl] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 410.91ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:55 PM   DEBUG [Api:LoggingInterceptor~75ei25re] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 111.92ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:55 PM   DEBUG [Api:LoggingInterceptor~dwyv3tiq] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.08ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:55 PM   DEBUG [Api:LoggingInterceptor~7jhr0wmw] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 92.85ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:55 PM   DEBUG [Api:LoggingInterceptor~p8tgywzu] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 54.59ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:56 PM   DEBUG [Api:LoggingInterceptor~2zl5y9in] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 3.44ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:56 PM   DEBUG [Api:LoggingInterceptor~5wpvirmc] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 148.02ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:56 PM   DEBUG [Api:LoggingInterceptor~d0ce2936] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 48.70ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:56 PM   DEBUG [Api:LoggingInterceptor~or7f5omj] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 7.51ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:56 PM   DEBUG [Api:LoggingInterceptor~2z11dshp] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 169.88ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~ar9hqrzi] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 61.33ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~fgg7rsbr] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 3.73ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~0hererxc] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 211.50ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~91q950kj] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 119.30ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~u8o3dj8n] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 3.64ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:57 PM   DEBUG [Api:LoggingInterceptor~hxa2xp45] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 112.90ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~ilegicyc] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 61.95ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~u2f2y727] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.10ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~bkr1u7pq] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 184.28ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~6k9ruqk5] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 114.85ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~7zyzrqhd] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.45ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:58 PM   DEBUG [Api:LoggingInterceptor~avndu5ce] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 197.45ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~u3laijux] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 137.53ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~6alzens9] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 4.63ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~3m1iwmup] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 192.21ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~rhrg19ve] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 117.87ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~vp6zpytt] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 3.10ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:06:59 PM   DEBUG [Api:LoggingInterceptor~rssxe9st] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 206 90.96ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:07:00 PM   DEBUG [Api:LoggingInterceptor~6p7cl9e3] GET /api/assets/0a1ad819-b9da-464d-916f-a9a47a868a51/video/playback 200 143.94ms ::ffff:x.x.x.x
etc infinite


----------------


the server in the successful case:
immich_server            | [Nest] 17  - 07/19/2024, 7:13:04 PM   DEBUG [Api:LoggingInterceptor~buvbicla] POST /api/auth/validateToken 200 0.14ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~7mchtpq5] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 35.69ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~6ooqoxk8] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 5.67ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~x7yw63ie] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.17ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~6z8ylyby] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.13ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~vot994ty] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.07ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:07 PM   DEBUG [Api:LoggingInterceptor~qjx3hme8] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.57ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:08 PM   DEBUG [Api:LoggingInterceptor~dua1n4lh] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 9.78ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:08 PM   DEBUG [Api:LoggingInterceptor~6gnnmonb] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.13ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:08 PM   DEBUG [Api:LoggingInterceptor~z5mq1a4c] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 9.01ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:08 PM   DEBUG [Api:LoggingInterceptor~y6l302jr] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 10.19ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:08 PM   DEBUG [Api:LoggingInterceptor~l204q6oj] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.36ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:09 PM   DEBUG [Api:LoggingInterceptor~algcwptk] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 9.64ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:09 PM   DEBUG [Api:LoggingInterceptor~f57gdgbf] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 15.44ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:09 PM   DEBUG [Api:LoggingInterceptor~dph38p6s] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 8.00ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:09 PM   DEBUG [Api:LoggingInterceptor~hbf0m32e] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.68ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~q6p7ta65] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.92ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~lqiy8i25] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.31ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~x8ei2yvt] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.20ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~v0mvkju3] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.93ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~pk9cktp6] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.52ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:10 PM   DEBUG [Api:LoggingInterceptor~hest3gt8] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 8.25ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:11 PM   DEBUG [Api:LoggingInterceptor~r09kr9rm] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.18ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:11 PM   DEBUG [Api:LoggingInterceptor~njar1ycq] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.97ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:11 PM   DEBUG [Api:LoggingInterceptor~kb7xa8ic] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 8.05ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:11 PM   DEBUG [Api:LoggingInterceptor~6p9n8hps] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.29ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:12 PM   DEBUG [Api:LoggingInterceptor~mn2lyxfl] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.15ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:12 PM   DEBUG [Api:LoggingInterceptor~kjvi6um8] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.98ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:12 PM   DEBUG [Api:LoggingInterceptor~tzanjleo] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 8.69ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:13 PM   DEBUG [Api:LoggingInterceptor~b3xgr1ok] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 10.10ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:15 PM   DEBUG [Api:LoggingInterceptor~2ssxvnk9] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 7.48ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:17 PM   DEBUG [Api:LoggingInterceptor~zb3efv3r] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.13ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:19 PM   DEBUG [Api:LoggingInterceptor~q45glqc6] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.35ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:21 PM   DEBUG [Api:LoggingInterceptor~45xjgz35] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 5.72ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:23 PM   DEBUG [Api:LoggingInterceptor~l1q44s3h] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.44ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:25 PM   DEBUG [Api:LoggingInterceptor~kh4akd8f] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.30ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:27 PM   DEBUG [Api:LoggingInterceptor~spp60hcf] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 5.44ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:29 PM   DEBUG [Api:LoggingInterceptor~gphg3igr] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 4.79ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:31 PM   DEBUG [Api:LoggingInterceptor~q9fozhb9] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.35ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:33 PM   DEBUG [Api:LoggingInterceptor~1et22lqc] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.93ms ::ffff:x.x.x.x
immich_server            | [Nest] 17  - 07/19/2024, 7:13:35 PM   DEBUG [Api:LoggingInterceptor~xrjg1ypj] GET /api/assets/f6854d83-a6e0-4de7-8591-355f1d7948fe/video/playback 200 6.10ms ::ffff:x.x.x.x
```

### Additional information

The problem was with the 1.109.2 server and the 1.108 application. And with both 1.109.2. I tried to clear the application cache
