### ISSUE TITLE
import HEIF photo failure on 1.109.x immich server

### ISSUE THREAD

**Issue by LoadingZhang** [immich-app/immich#11247]
i got error after update from 108 -> 109 in website, rollback 108 then get back to normal.
```
[Nest] 7  - 07/20/2024, 10:08:29 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-preview): Error: Input file has corrupt header: magickload: Magick: UnableToLoadModule '/usr/local/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/heic.la': file not found @ error/module.c/OpenModule/1293 (null)
[Nest] 7  - 07/20/2024, 10:08:29 PM   ERROR [Microservices:JobService] Error: Input file has corrupt header: magickload: Magick: UnableToLoadModule '/usr/local/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/heic.la': file not found @ error/module.c/OpenModule/1293 (null)
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at MediaService.generateThumbnail (/usr/src/app/dist/services/media.service.js:164:48)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGeneratePreview (/usr/src/app/dist/services/media.service.js:135:29)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 07/20/2024, 10:08:29 PM   ERROR [Microservices:JobService] Object:
{
  "id": "6797f51d-30bc-4d82-b950-463f62729377",
  "source": "upload"
}
```

file:
[IMG_20240720_230151.zip](https://github.com/user-attachments/files/16321693/IMG_20240720_230151.zip)

### The OS that Immich Server is running on

Debian WSL2

### Version of Immich Server

v1.109.x

### Version of Immich Mobile App

null

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    devices: ["/dev/dri"]
    env_file: [".env"]
    ports: ["2283:3001"]
    depends_on:
      - redis
      - database
    restart: on-failure
```

### Your .env content

```Shell
Upload again if you need to
```

### Reproduction steps

```bash
upload HEIF file from web or app
```
