### ISSUE TITLE
When download download information stuck under search

### ISSUE THREAD

**Issue by benni347** [immich-app/immich#11267]
### The bug

Hey, I am trying to download any media file when searching for it in the search ui, e.g: `https://instnace/search?query=%7B%22city%22%3A%22Berlin%22%7D` the query can be anything. When downloading a media from this subpage I always get the download information stuck in place.
![image](https://github.com/user-attachments/assets/e2906f0c-8ccb-46a2-b8fa-b0d0cec99d3d)

### The OS that Immich Server is running on

Debian 12 bookworm

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
cat docker-compose.yml 
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - immich
      - proxy
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - immich
      # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      #   file: hwaccel.ml.yml
      #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
networks:
  immich:
  proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/storage/cimmich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Zurich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Go to the search subpage
2. Search something
3. Download a file
```

### Additional information

This is the boxes html:
```html
<div class="absolute bottom-10 left-2 z-[10000] max-h-[270px] w-[315px] rounded-2xl border bg-immich-bg p-4 text-sm shadow-sm" style=""><p class="mb-2 text-xs text-gray-500">DOWNLOADING</p> <div class="my-2 mb-2 flex max-h-[200px] flex-col overflow-y-auto text-sm"><div class="mb-2 flex place-items-center"><div class="w-full pr-10"><div class="flex place-items-center justify-between gap-2 text-xs font-medium"><p class="truncate">■ IMG_20150203_085847_c5m7BA.jpg</p> <p class="whitespace-nowrap">912.2 KiB</p></div> <div class="flex place-items-center gap-2"><div class="h-[7px] w-full rounded-full bg-gray-200 dark:bg-gray-700"><div class="h-[7px] rounded-full bg-immich-primary" style="width: 100%"></div></div> <p class="min-w-[4em] whitespace-nowrap text-right"><span class="text-immich-primary">100%</span></p></div></div> <div class="absolute right-2"><button title="Close" type="button" class="flex place-content-center place-items-center rounded-full bg-transparent hover:bg-[#d3d3d3] dark:text-immich-dark-fg p-3 transition-all hover:dark:text-immich-dark-gray dark:text-immich-dark-gray "><svg width="20" height="20" viewBox="0 0 24 24" class=" " role="img" aria-label="Close"><path d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z" fill="currentColor"></path></svg></button></div> </div></div></div>
```
