### ISSUE TITLE
error 400 while deleting images

### ISSUE THREAD

**Issue by ptocadoa** [immich-app/immich#11285]
### The bug

I have currently rights as admin for me and another user.
I have searched for images stored with context="whatsapp". 
I select all images that meet this condition and try to delete them, error 400 (internal error) appears.

### The OS that Immich Server is running on

Linux NAS164B9C 5.10.60-qnap #1 SMP Wed Apr 17 06:31:22 CST 2024 x86_64 GNU/Linux

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      #- /share/dockervolumes/immich/etc:/usr/src/app/etc
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /share/docs:/mnt/docs
    env_file:
      - stack.env
    ports:
      - 2283:3001
    network_mode: mqtnet
    command: ['start.sh', 'immich']
    privileged: true

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      #- /share/dockervolumes/immich/etc:/usr/src/app/etc
      - ${UPLOAD_LOCATION}:/usr/src/app/upload      
    env_file:
      - stack.env
    network_mode: mqtnet
    restart: always


  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /share/dockervolumes/immich/cache:/cache
    env_file:
      - stack.env
    network_mode: mqtnet

  
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    network_mode: host
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/docs/immich
IMMICH_VERSION=release
DB_PASSWORD=secret
DB_USERNAME=secret
DB_DATABASE_NAME=immich
DB_HOSTNAME=192.168.1.4
REDIS_HOSTNAME=192.168.1.4
TZ=Europe/Andorra
THUMB_LOCATION=/share/docs/immich/thumbs
ENCODED_VIDEO_LOCATION=/share/docs/immich/video
PROFILE_LOCATION=/share/docs/immich/profile
DB_DATA_LOCATION=/share/dockervolumes/postgres
```

### Reproduction steps

```bash
I have currently rights as admin for me and another user.

1) I have searched for images stored with context="whatsapp". 
2) I select all images that meet this condition and 
3) try to delete them, error 400 (internal error) appears.
```
