### ISSUE TITLE
Android App Turn on/off background backup cause previous selected folders setting lost

### ISSUE THREAD

**Issue by EverettSummer** [immich-app/immich#11293]
### The bug

I have been using Immich for several months, I have used foreground backup. but recently want to try background backup. I turn it only (while the foreground backup is uploading). and exit app, when I reopen the app, and click the backup button. All settings of the backup folders are gone.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

 v1.109.2

### Version of Immich Mobile App

1.109.0 build.149

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=fake_password

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_DATABASE_NAME=fake_db_name

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. select backup folders, only turn on foreground backup some images 
2. when it's working, enter the backup setting then turn on background backup.
3. exit app, the background backup should have a notification showing progress,
4. reopen the app and enter the backup setting, the backup settings are reset, and both foreground and background backup are off.
...
```

### Additional information
Oh, I am not sure if it's an app version mismatch with the server version. I turned off the auto-update of the app, the app was one version? behind the latest. I just upgraded the server version to the latest release.

I have to turn off auto upgrade app, because it will break the update quickly when the server not upgrading, too frequently server upgrade is a bit inconvenient using docker compose.
