### ISSUE TITLE
Cannot Change Date of Pictures after update

### ISSUE THREAD

**Issue by bauerbyter** [immich-app/immich#11316]
### The bug

Cannot change the Date of an Image.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

 v1.108.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${DATA}/immich/uploads:/usr/src/app/upload
      - /data/share/pics:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - immich-redis
      - immich-database
      - traefik
    restart: always
    environment:
      DB_USERNAME: ${IMMICH_DB_USER}
      DB_PASSWORD: ${IMMICH_DB_PWD}
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich-redis
      DB_HOSTNAME: immich-database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photo.entrypoints=http"
      - "traefik.http.routers.photo.rule=Host(`photo.********.*****`)"
      - "traefik.http.middlewares.photo-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.photo.middlewares=photo-https-redirect"
      - "traefik.http.routers.photo-secure.entrypoints=https"
      - "traefik.http.routers.photo-secure.rule=Host(`photo.*****.*****`)"
      - "traefik.http.routers.photo-secure.tls=true"
      - "traefik.http.routers.photo-secure.service=photo"
      - "traefik.http.services.photo.loadbalancer.server.port=3001"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${DATA}/immich/model-cache:/cache
    restart: always

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    restart: always

  immich-database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PWD}
      POSTGRES_USER: ${IMMICH_DB_USER}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DATA}/immich/postgres:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1. Some Images have the wrong time stamp (was already like this before). Select one or multiple images
2. Click "change date" from the menu or single picture: click on the pen icon
3. Add new Date and click "confirm"
4. Nothing happens
...
```

### Relevant log output

```shell
Nothing relevent found
```
