### ISSUE TITLE
[BUG] Storage template migration ignores old iOS uploaded live video assets

### ISSUE THREAD

**Issue by PhasecoreX** [immich-app/immich#11324]
### The bug

This is a continuation of #11131. With the latest version of Immich, I see that the archived files are now being moved correctly! However the other half of my issue was about Live Photo videos not being moved, which couldn't be replicated. I had done some research, which I had posted on the previous issue, but I will also summarize and list here.

It seems that something got fixed somewhere between January 7th 2024 and February 2024, as my library shows all the mov files being moved correctly for iOS uploads after February. Before that date, only iOS uploads seem to have this issue where the photo part of a Live Photo gets migrated correctly, but the video part does not move. CLI uploaded media seems to always migrate correctly, though I am not 100% certain on that.

The way I figured that out is because I looked at my wife's account/storage, and all of hers migrated correctly. The difference between her and my account is that I have been using Immich much longer than her. All of her iOS uploads happened probably a month or two ago, whereas mine has been over the course of a couple of years now.

My guess is that something wasn't linking the photo and video together correctly. I assume the database is pointing at the correct (old) location of the video, since the frontend still shows the video part correctly and it doesn't show up in the Repair tab. But maybe something is misconfigured in the database that it isn't eligible to be moved for some reason?

Please let me know what other information I can get you. Thank you again!

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

v1.109.2

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

networks:
  proxy:
    name: proxy
    external: true

volumes:
  database-dump:
    name: database-dump
    external: true
  z-model-cache:
  z-redis-data:

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - "3001"
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    networks:
      - default
      - proxy

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - z-model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    volumes:
      - z-redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-postgres:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ../volumes/immich/database:/var/lib/postgresql/data
      - database-dump:/database-dump
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/ext/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=...

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich-redis
```

### Reproduction steps

```bash
1. Go back in time to sometime before January 7th 2024, and install that version of the server and iOS client
2. Upload a Live Photo from the iOS client
3. Change the storage template so that these photos will move
4. Run storage template migration
5. Notice that the photo part of the Live Photo moves to the correct location, but the video part is still in it's original spot
```

### Additional information

Here's a copy and paste of my last post on the previous issue, un-summarized, so you don't have to click over to it, and in case I missed anything above:

> But I did notice something (I think). When I looked at the storage, I noticed that there was a jpeg file with associated mov that had successfully migrated over. However the HEIC ones seem to leave behind their mov files. I don't know if it has something to do with the issue? Actually that might just be coincidence, see below:
> 
> The only other thing I can think of is if you are uploading via CLI or via mobile app. Looking at the storage, it seems that the ones I have CLI uploaded do migrate both photo/video successfully, but iOS app uploaded ones only migrate the photo part. Maybe there's a difference between the two ways of uploading? That would be weird though. But it does explain how all the older ones in my library migrate correctly, and all the new app uploaded ones don't.
> 
> Sorry, I just keep finding more patterns and then keep writing them down before submitting. I looked at my wife's account/storage, and all of hers migrated correctly! The difference is that I have been using the app way longer than her, only just recently having her start using it. It looks like this upload difference between CLI and iOS app stopped being an issue sometime between January 7th 2024 and February 2024, as my library shows all the mov files being moved correctly for iOS uploads after February. So that explains how you couldn't reproduce it, as you were either using CLI, or using the newest iOS app. In an older iOS app, it wasn't doing something correctly, and those affected files have this weird bug.
> 
> Hopefully that helps! Let me know if you need anything else! And again, thank you!
