### ISSUE TITLE
Server cannot start because Redis port is not available

### ISSUE THREAD

**Issue by widewing** [immich-app/immich#11341]
### The bug

I'm trying to install Immich on my Raspberry Pi 4 (8GB). I used the official docker compose method to install, with mostly default settings. Everything else seems started correctly (DB,Redis,ML) but the Immich server refused to start with the following error message.

### The OS that Immich Server is running on

OpenWrt on Raspberry Pi 4b

### Version of Immich Server

v1.109.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    network_mode: bridge
    image: m.daocloud.io/ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /mnt/disk1/immich_upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    links:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    network_mode: bridge
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: m.daocloud.io/ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    links:
      - redis
      - database

  redis:
    container_name: immich_redis
    network_mode: bridge
    image: m.daocloud.io/docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    command:
      - redis-server
      - --ignore-warnings
      - ARM64-COW-BUG

  database:
    container_name: immich_postgres
    network_mode: bridge
    image: m.daocloud.io/docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/disk1/wxx
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.109.2

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=KXU4W5NegPnZvBt

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
Install with the official docker compose installation guide
```

### Relevant log output

```shell
stderr: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type number (NaN).
stderr:     at lookupAndConnect (node:net:1297:5)
stderr:     at Socket.connect (node:net:1254:5)
stderr:     at connect (node:net:237:17)
stderr:     at /usr/src/app/node_modules/ioredis/built/connectors/StandaloneConnector.js:54:66
stderr:     at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
stderr:   code: 'ERR_SOCKET_BAD_PORT'
stderr: }
stdout: [32m[Nest] 7  - [39m07/25/2024, 2:23:15 AM [32m    LOG[39m [33m[Microservices:EventRepository][39m [32mInitialized websocket server[39m
stderr: missing 'error' handler on this Redis client
stderr: 
stderr: node:internal/event_target:1094
stderr:   process.nextTick(() => { throw err; });
stderr:                            ^
stderr: RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received type number (NaN).
stderr:     at lookupAndConnect (node:net:1297:5)
stderr:     at Socket.connect (node:net:1254:5)
stderr:     at connect (node:net:237:17)
stderr:     at /usr/src/app/node_modules/ioredis/built/connectors/StandaloneConnector.js:54:66
stderr:     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
stderr: Emitted 'error' event on Worker instance at:
stderr:     at [kOnErrorMessage] (node:internal/worker:326:10)
stderr:     at [kOnMessage] (node:internal/worker:337:37)
stderr:     at MessagePort.<anonymous> (node:internal/worker:232:57)
stderr:     at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
stderr:     at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28) {
stderr:   code: 'ERR_SOCKET_BAD_PORT'
stderr: }
stderr: 
stderr: Node.js v20.15.1
stdout: Detected CPU Cores: 4
```
