### ISSUE TITLE
[BUG] Can't run microservices container as non-root user

### ISSUE THREAD

**Issue by virusperfect** [immich-app/immich#1135]
**Describe the bug**
Creating the microservices container doesn't work if the container is run as a non-root user.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Run microservices container with `user: "UID:GID"`
2. The container will keep restarting with the following error message:
```
Error: EACCES: permission denied, mkdir '/usr/src/app/.reverse-geocoding-dump/'
    at Object.mkdirSync (node:fs:1349:3)
    at Object.init (/usr/src/app/node_modules/local-reverse-geocoder/index.js:659:10)
    at /usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:62:42
    at new Promise (<anonymous>)
    at geocoderInit (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:61:12)
    at new MetadataExtractionProcessor (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors/metadata-extraction.processor.js:83:13)
    at Injector.instantiateClass (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:330:19)
    at callback (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/@nestjs/core/injector/injector.js:122:24) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/usr/src/app/.reverse-geocoding-dump/'
}
```

**Expected behavior**
Microservices should run even as non-root user. I thought this issue was solved in #338.

**System**
- Server Version: `1.39.0`

**Additional context**

### docker-compose
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    user: "158:168"
    restart: unless-stopped

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    user: "158:168"
    restart: unless-stopped

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    user: "158:168"
    restart: unless-stopped

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    environment:
      - PUID=158
      - PGID=168
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /opt/config/immich/data:/var/lib/postgresql/data
    user: "158:168"
    restart: unless-stopped

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 127.0.0.1:2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: unless-stopped
```
### .env
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/nas/backup/immich/upload
LOG_LEVEL=simple
JWT_SECRET=redacted
PUBLIC_LOGIN_PAGE_MESSAGE=
```
