### ISSUE TITLE
Incorrect redis server naming in example docker-compose triggers Redis NOAUTH error

### ISSUE THREAD

**Issue by a10kiloham** [immich-app/immich#11377]
### The bug

In the docker-compose the redis image is named 'immich_redis' which is sensible. However in the default sample .env, this is not included, so those using that will get NOAUTH errors because without REDIS_HOSTNAME configured, it defaults to 'redis' which is undefined unless one is already running a local redis image accessible under that name.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich
    restart: always
```

### Your .env content

```Shell
# Fix
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Curl the existing docker-compose.yml and .env files
```

### Additional information

Submitting PR to fix this
