### ISSUE TITLE
Redis server is disconnecting, Immich-server restarts every 2 minutes

### ISSUE THREAD

**Issue by fluffy-catpawz** [immich-app/immich#11397]
### The bug

After I updated to the latest version, I've noticed that the "immich-server" container keeps crashing/restarting, and my phone can't really upload stuff, because the server is down too often. i've tried restarting my host machine, and re-pulling the images again, but it didn't work.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

v1.110.0 build.151

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/HDD1/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Paris

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Update immich by using the instructions in the docs
2. Boot up your containers
3. Immich-server container crashes/restarts all the time
```

### Relevant log output

```shell
Immich-server container logs:
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
missing 'error' handler on this Redis client
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
Error: connect EHOSTUNREACH 172.18.0.2:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '172.18.0.2',
  port: 6379
}
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client


Immich-redis container logs:
21329:C 27 Jul 2024 07:46:42.124 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 07:46:42.201 * Background saving terminated with success
1:M 27 Jul 2024 07:51:43.021 * 100 changes in 300 seconds. Saving...
1:M 27 Jul 2024 07:51:43.022 * Background saving started by pid 21403
21403:C 27 Jul 2024 07:51:43.046 * DB saved on disk
21403:C 27 Jul 2024 07:51:43.047 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 07:51:43.122 * Background saving terminated with success
1:M 27 Jul 2024 07:56:44.037 * 100 changes in 300 seconds. Saving...
1:M 27 Jul 2024 07:56:44.037 * Background saving started by pid 21474
21474:C 27 Jul 2024 07:56:44.061 * DB saved on disk
21474:C 27 Jul 2024 07:56:44.062 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 07:56:44.138 * Background saving terminated with success
1:M 27 Jul 2024 08:01:45.091 * 100 changes in 300 seconds. Saving...
1:M 27 Jul 2024 08:01:45.092 * Background saving started by pid 21542
21542:C 27 Jul 2024 08:01:45.116 * DB saved on disk
21542:C 27 Jul 2024 08:01:45.117 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 08:01:45.192 * Background saving terminated with success
1:M 27 Jul 2024 08:06:46.039 * 100 changes in 300 seconds. Saving...
1:M 27 Jul 2024 08:06:46.040 * Background saving started by pid 21614
21614:C 27 Jul 2024 08:06:46.062 * DB saved on disk
21614:C 27 Jul 2024 08:06:46.063 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 08:06:46.140 * Background saving terminated with success
1:M 27 Jul 2024 08:11:47.000 * 100 changes in 300 seconds. Saving...
1:M 27 Jul 2024 08:11:47.001 * Background saving started by pid 21686
21686:C 27 Jul 2024 08:11:47.023 * DB saved on disk
21686:C 27 Jul 2024 08:11:47.024 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 08:11:47.101 * Background saving terminated with success
1:M 27 Jul 2024 09:11:48.007 * 1 changes in 3600 seconds. Saving...
1:M 27 Jul 2024 09:11:48.008 * Background saving started by pid 22514
22514:C 27 Jul 2024 09:11:48.029 * DB saved on disk
22514:C 27 Jul 2024 09:11:48.030 * RDB: 0 MB of memory used by copy-on-write
1:M 27 Jul 2024 09:11:48.108 * Background saving terminated with success

Immich-postgres container logs:
2024-07-25 08:04:56.453 UTC [1] LOG:  redirecting log output to logging collector process
2024-07-25 08:04:56.453 UTC [1] HINT:  Future log output will appear in directory "log".
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-26 06:11:43.210 UTC [1] LOG:  redirecting log output to logging collector process
2024-07-26 06:11:43.210 UTC [1] HINT:  Future log output will appear in directory "log".
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-07-26 06:31:57.216 UTC [1] LOG:  redirecting log output to logging collector process
2024-07-26 06:31:57.216 UTC [1] HINT:  Future log output will appear in directory "log".
```
