### ISSUE TITLE
TLS Client certificate Server is not reachable

### ISSUE THREAD

**Issue by AdriDevelopsThings** [immich-app/immich#11399]
### The bug

I'm trying to use the new client certificate feature on iOS 17.5.1 but I'm a `Server is not reachable` Toast.

The client certificate was set as you can see in the log section.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

v1.110.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`**********`)
      - traefik.http.routers.immich.tls.options=client_certificate@file
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - default
      - traefik
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
volumes:
  model-cache:
networks:
  traefik:
    name: traefik
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=******
IMMICH_VERSION=release
DB_PASSWORD=******
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. configure your reverse proxy to require a client certificate
2. open the immich app on iOS and log out
3. import the client certificate in the api
4. try to connect to server
```

### Relevant log output

```shell
2024-07-27 17:35:50.641116 | SEVERE   | ApiService           | Error while checking server availability | 
        TLSV1_ALERT_CERTIFICATE_REQUIRED(tls_record.cc:592) error 268436572 |
#0      IOClient.send (package:http/src/io_client.dart:96)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93)
<asynchronous suspension>
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:949)
<asynchronous suspension>
#3      ApiService._isEndpointAvailable (package:immich_mobile/services/api.service.dart:105)
<asynchronous suspension>
#4      ApiService._resolveEndpoint (package:immich_mobile/services/api.service.dart:85)
<asynchronous suspension>
#5      ApiService.resolveAndSetEndpoint (package:immich_mobile/services/api.service.dart:67)
<asynchronous suspension>
#6      LoginForm.build.getServerLoginCredential (package:immich_mobile/widgets/forms/login/login_form.dart:99)
<asynchronous suspension>
2024-07-27 17:33:34.408656 | INFO     | HttpSSLCertOverride  | Setting client certificate |
```
