### ISSUE TITLE
Docker Compose, new setup: immich_server exited with code 0

### ISSUE THREAD

**Issue by Kofl** [immich-app/immich#11391]
### The bug

Setup via docker compose fails based on the official documentation, immich_server exited with code 0
So no web interface on port 2283 is available.

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

not used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
Following the docker compose installation guide
1. mkdir ./immich-app
2. cd ./immich-app
2. wget -O docker-compose.yml https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
3. wget -O .env https://github.com/immich-app/immich/releases/latest/download/example.env
4. docker compose up -d
```

### Relevant log output

```shell
immich_postgres          |
immich_postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres          |
immich_postgres          | 2024-07-27 10:16:18.600 UTC [1] LOG:  redirecting log output to logging collector process
immich_postgres          | 2024-07-27 10:16:18.600 UTC [1] HINT:  Future log output will appear in directory "log".
immich_redis             | 1:C 27 Jul 2024 10:16:18.304 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis             | 1:C 27 Jul 2024 10:16:18.304 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis             | 1:C 27 Jul 2024 10:16:18.304 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis             | 1:M 27 Jul 2024 10:16:18.304 * monotonic clock: POSIX clock_gettime
immich_redis             | 1:M 27 Jul 2024 10:16:18.305 * Running mode=standalone, port=6379.
immich_redis             | 1:M 27 Jul 2024 10:16:18.305 # Server initialized
immich_redis             | 1:M 27 Jul 2024 10:16:18.305 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis             | 1:M 27 Jul 2024 10:16:18.305 * Ready to accept connections
immich_server exited with code 0
immich_machine_learning  | [07/27/24 10:16:19] INFO     Starting gunicorn 21.2.0
immich_machine_learning  | [07/27/24 10:16:19] INFO     Listening at: http://[::]:3003 (9)
immich_machine_learning  |[07/27/24 10:16:19]INFO Using worker: app.config.CustomUvicornWorker
immich_machine_learning  | [07/27/24 10:16:19] INFO     Booting worker with pid: 14
immich_server exited with code 0
immich_server exited with code 0
immich_machine_learning  | [07/27/24 10:16:22] INFO     Started server process [14]
immich_machine_learning  |[07/27/24 10:16:22]INFO Waiting for application startup.
immich_machine_learning  |[07/27/24 10:16:22]INFO Created in-memory cache with unloading after 300s
immich_machine_learning  |         of inactivity.
immich_machine_learning  | [07/27/24 10:16:22] INFO     Initialized request thread pool with 4 threads.
immich_machine_learning  |[07/27/24 10:16:22]INFO Application startup complete.
```
