### ISSUE TITLE
Edit shared links are all defaults

### ISSUE THREAD

**Issue by QYG2297248353** [immich-app/immich#11438]
### The bug

Immich App Share > > Share Links > > Edit All values are defaults

![image](https://github.com/user-attachments/assets/65d8efdf-a99e-4908-9c66-174b952c518c)

![image](https://github.com/user-attachments/assets/b3b3046b-ffe6-492b-bc24-d608f9844695)

![image](https://github.com/user-attachments/assets/4189a4f1-1c45-4f8a-aed4-f002faa61480)

### The OS that Immich Server is running on

almalinux 9

### Version of Immich Server

1.110.0

### Version of Immich Mobile App

1.110.0 build.165

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich
networks:
    1panel-network:
        external: true
services:
    immich-machine-learning:
        container_name: immich-machine-learning-${CONTAINER_NAME}
        devices:
            - /dev/dri:/dev/dri
        env_file:
            - /etc/1panel/envs/global.env
            - ${ENV_FILE:-/etc/1panel/envs/default.env}
        image: ghcr.io/immich-app/immich-machine-learning:v1.110.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${PANEL_APP_PORT_MACHINE_LEARNING}:3003
        restart: always
        volumes:
            - ${IMMICH_ROOT_PATH}/data/cache:/cache
    immich-pg14-vectors:
        command:
            - postgres
            - -c
            - shared_preload_libraries=vectors.so
            - -c
            - search_path="$$user", public, vectors
            - -c
            - logging_collector=on
            - -c
            - max_wal_size=2GB
            - -c
            - shared_buffers=512MB
            - -c
            - wal_compression=on
        container_name: pg14-vectors-${CONTAINER_NAME}
        environment:
            POSTGRES_DB: ${DB_DATABASE_NAME:-immich}
            POSTGRES_INITDB_ARGS: --data-checksums
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME:-postgres}
        healthcheck:
            interval: 5m
            start_interval: 30s
            start_period: 5m
            test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
        image: tensorchord/pgvecto-rs:pg14-v0.2.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${PANEL_APP_PORT_DB:-5432}:5432
        restart: always
        volumes:
            - ${IMMICH_ROOT_PATH}/pg14/data:/var/lib/postgresql/data
    immich-server:
        container_name: immich-server-${CONTAINER_NAME}
        depends_on:
            - immich-pg14-vectors
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        devices:
            - /dev/dri:/dev/dri
        env_file:
            - /etc/1panel/envs/global.env
            - ${ENV_FILE:-/etc/1panel/envs/default.env}
        image: ghcr.io/immich-app/immich-server:v1.110.0
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3001
        restart: always
        volumes:
            - ${IMMICH_ROOT_PATH}/data/library:/usr/src/app/upload
            - /etc/localtime:/etc/localtime
version: "3.8"
```

### Your .env content

```Shell
CONTAINER_NAME="immich-ms"
CPUS=0
DB_DATABASE_NAME="immich"
DB_HOSTNAME="immich-pg14-vectors"
DB_PASSWORD="password"
DB_USERNAME="postgres"
HF_ENDPOINT="https://hf-mirror.com"
HOST_IP=""
IMMICH_DRIVE_PATH="/dev/dri"
IMMICH_ROOT_PATH="/home/data/immich-app"
MACHINE_LEARNING_PRELOAD__CLIP="XLM-Roberta-Large-Vit-B-16Plus"
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION="buffalo_l"
MEMORY_LIMIT=0
PANEL_APP_PORT_DB=5434
PANEL_APP_PORT_HTTP=2283
PANEL_APP_PORT_MACHINE_LEARNING=3003
PANEL_REDIS_SERVICE="Local_Redis7"
PANEL_REDIS_TYPE="redis"
REDIS_DBINDEX=0
REDIS_HOSTNAME="127.0.0.1"
REDIS_PASSWORD="password"
REDIS_PORT=6379
REDIS_USERNAME=""
TZ="Asia/Shanghai"
ENV_FILE=/opt/1panel/apps/local/immich/immich/.env
```

### Reproduction steps

```bash
Share > > Share Links > > Edit 

All values are defaults, Configuration when there is no read share
```

### Additional information

I'm not sure if it's a problem, but I hope, he's normal
