### ISSUE TITLE
Immich PosgreSQL user require superuser rights. Database migration try to create exising extension 

### ISSUE THREAD

**Issue by landure** [immich-app/immich#11441]
### The bug

Immich installation requires a PostgreSQL superuser, even if extensions are manually added to the database.

See: #7835

I'm very reluctant to give a superuser access to PostgreSQL to an app. Immich migrations should test for the required extensions existences before trying to create them.

### The OS that Immich Server is running on

Debian Bookworm, with Docker version 25.0.4, build 1a576c5

### Version of Immich Server

v1.110.0

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# compose.yml for immich
networks:
  postgres:
    name: postgres-net
    external: true
  prometheus:
    name: prometheus-net
    external: true
  traefik:
    name: traefik-net
    external: true
volumes:
  immich-machine-learning-cache:
    # immich-machine-learning service's Model cache volume
    driver: local
  immich-server-data:
    # immich-server service's data volume (photo storage)
    driver: local
  valkey-data:
    # Valkey persistent data volume
    driver: local
secrets:
  db_name:
    file: secrets/db_name.secret
  db_username:
    file: secrets/db_username.secret
  db_password:
    file: secrets/db_password.secret
  valkey-ssl-key:
    file: secrets/valkey-ssl-key.secret
  valkey-ssl-cert:
    file: secrets/valkey-ssl-cert.secret
  mkcert-root-ca:
    file: secrets/mkcert-root-ca.secret
  default_user_password:
    file: secrets/default_user_password.secret
configs:
  valkey.conf:
    file: ./etc/valkey.conf
  users.acl:
    file: ./etc/users.acl
services:
  valkey:
    image: valkey/valkey:latest
    group_add:
      - "1000"
    user: valkey
    command:
      - valkey-server
      - /usr/local/etc/valkey/valkey.conf
      - --save
      - "360"
      - "1"
      - "300"
    - "100"
      - "60"
      - "1000"
      - --appendonly
      - yes
      - --appendfsync
      - everysec
      - --loglevel
      - notice
      - --tls-cert-file
      - /run/secrets/valkey-ssl-cert
      - --tls-key-file
      - /run/secrets/valkey-ssl-key
      - --tls-ca-cert-file
      - /run/secrets/mkcert-root-ca
      - --tls-protocols
      - TLSv1.2 TLSv1.3
      - --tls-replication
      - yes
      - --tls-cluster
      - yes
      - --databases
      - "16"
      - --aclfile
      - /usr/local/etc/valkey/users.acl
      - --maxmemory
      - "268435456"
      - --maxmemory-policy
      - noeviction
    networks:
      default: {}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - valkey-data:/data
    secrets:
      - valkey-ssl-key
      - valkey-ssl-cert
      - mkcert-root-ca
    configs:
      - source: valkey.conf
        target: /usr/local/etc/valkey/valkey.conf
      - source: users.acl
        target: /usr/local/etc/valkey/users.acl
    healthcheck:
      test:
        - CMD
        - valkey-cli
        - ping
      start_period: 10s
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    group_add:
      - "1000"
    env_file:
      - ./env/immich.env
    depends_on:
      - valkey
    networks:
      default: {}
      traefik: {}
      postgres: {}
      prometheus: {}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - immich-server-data:/usr/src/app/upload
    secrets:
      - db_name
      - db_username
      - db_password
      - default_user_password
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.exposed-by-instance: traefik-public
      traefik.http.services.immich-immich-server-service.loadbalancer.server.port: 3001
      traefik.http.services.immich-immich-server-service.loadbalancer.server.scheme: http
      traefik.http.routers.immich-immich-server-https.entrypoints: websecure,web
      traefik.http.routers.immich-immich-server-https.service: immich-immich-server-service@docker
      traefik.http.routers.immich-immich-server-https.rule: Host(`immich.domain.fr`)
      traefik.http.routers.immich-immich-server-https.middlewares: hsts@file,security@file,compression@file
      traefik.http.routers.immich-immich-server-https.tls: "true"
      traefik.http.routers.immich-immich-server-https.tls.certresolver: default
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    group_add:
      - "1000"
    env_file:
      - ./env/immich.env
    depends_on:
      - valkey
    networks:
      default: {}
      postgres: {}
      prometheus: {}
    secrets:
      - db_name
      - db_username
      - db_password
      - default_user_password
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - immich-machine-learning-cache:/cache
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
```

### Your .env content

```Shell
# Listening host
IMMICH_HOST=0.0.0.0

# Listening port
# 3001 for server, 3003 for machine learning
# IMMICH_PORT=3001

# Amount of cores available to the immich server
# Default to auto-detected cpu core count
# CPU_CORES=

# When true, generate thumbnails for invalid images
# IMMICH_PROCESS_INVALID_IMAGES=

# List of comma separated IPs set as trusted proxies
# IMMICH_TRUSTED_PROXIES=

# Only run these workers.
# This should be set by container.
# See https://immich.app/docs/administration/jobs-workers/
# IMMICH_WORKERS_INCLUDE=

# Do not run these workers.
# This should be set by container.
# Matches against default workers, or IMMICH_WORKERS_INCLUDE if specified.
# See https://immich.app/docs/administration/jobs-workers/
# IMMICH_WORKERS_EXCLUDE=

# Database URL
# DB_URL_FILE=/run/secrets/db_url

# Database Host
DB_HOSTNAME=postgres

# Database Port
DB_PORT=5432

# Database User
DB_USERNAME_FILE=/run/secrets/db_username

# Database Password
DB_PASSWORD_FILE=/run/secrets/db_password

# Database Name
DB_DATABASE_NAME_FILE=/run/secrets/db_name

# Database Vector Extension (one of [pgvector, pgvecto.rs])
DB_VECTOR_EXTENSION=pgvecto.rs

# Whether to skip running migrations on startup (one of [true, false])
# DB_SKIP_MIGRATIONS=false

# Redis URL
# see https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
# REDIS_URL=ioredis://
# Toggle metrics for database queries, image processing, etc.
# (one of [true, false])
# IMMICH_IO_METRICS=true

# Toggle metrics for jobs and queues (one of [true, false])
# IMMICH_JOB_METRICS=true

# Port for the api OTEL metrics
# IMMICH_API_METRICS_PORT=8081

# Port for the microservices OTEL metrics
# IMMICH_MICROSERVICES_METRICS_PORT=8082

# Inactivity time (s) before a model is unloaded (disabled if <= 0)
# MACHINE_LEARNING_MODEL_TTL=300

# Interval (s) between checks for the model TTL (disabled if <= 0)
# MACHINE_LEARNING_MODEL_TTL_POLL_S=10

# Directory where models are downloaded
# MACHINE_LEARNING_CACHE_FOLDER=/cache

# Thread count of the request thread pool (disabled if <= 0)
# Default to number of CPU cores
# MACHINE_LEARNING_REQUEST_THREADS=

# Number of parallel model operations
# MACHINE_LEARNING_MODEL_INTER_OP_THREADS=1

# Number of threads for each model operation
# MACHINE_LEARNING_MODEL_INTRA_OP_THREADS=2

# Number of worker processes to spawn
# MACHINE_LEARNING_WORKERS=1

# Maximum time (s) of unresponsiveness before a worker is killed
# MACHINE_LEARNING_WORKER_TIMEOUT=120

# Name of a CLIP model to be preloaded and kept in cache
# MACHINE_LEARNING_PRELOAD__CLIP=

# Name of a facial recognition model to be preloaded and kept in cache
# MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION=

# Enable ARM-NN hardware acceleration if supported
# MACHINE_LEARNING_ANN=True

# Execute operations in FP16 precision: increasing speed, reducing precision
# (applies only to ARM-NN)
# MACHINE_LEARNING_ANN_FP16_TURBO=False

# ARM-NN GPU tuning level (1: rapid, 2: normal, 3: exhaustive)
# MACHINE_LEARNING_ANN_TUNING_LEVEL=2
```

### Reproduction steps

```bash
Create a database and user manually with:


CREATE ROLE "${db_username}" PASSWORD '${db_password}'
              NOCREATEDB NOCREATEROLE NOSUPERUSER INHERIT LOGIN;
CREATE DATABASE "${db_name}" WITH OWNER "${db_username}" ENCODING 'UTF8';
CREATE EXTENSION cube;
CREATE EXTENSION earthdistance;
CREATE EXTENSION vectors;
ALTER DATABASE "${db_name}" SET search_path TO "\$user", public, vectors;


Start Immich server. It fails at `Geodata1700362016675` migration with permission denied error.
```

### Relevant log output

```shell
immich-server-1            | Migration "Geodata1700362016675" failed, error: permission denied to create extension "earthdistance"
immich-server-1            | QueryFailedError: permission denied to create extension "earthdistance"
immich-server-1            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich-server-1            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich-server-1            |     at async Geodata1700362016675.up (/usr/src/app/dist/migrations/1700362016675-Geodata.js:8:9)
immich-server-1            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich-server-1            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich-server-1            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
immich-server-1            |     at async /usr/src/app/dist/services/database.service.js:136:17
immich-server-1            |     at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
immich-server-1            |   query: 'CREATE EXTENSION IF NOT EXISTS earthdistance',
immich-server-1            |   parameters: undefined,
immich-server-1            |   driverError: error: permission denied to create extension "earthdistance"
immich-server-1            |       at /usr/src/app/node_modules/pg/lib/client.js:526:17
immich-server-1            |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich-server-1            |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich-server-1            |       at async Geodata1700362016675.up (/usr/src/app/dist/migrations/1700362016675-Geodata.js:8:9)
immich-server-1            |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich-server-1            |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich-server-1            |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:169:9)
immich-server-1            |       at async /usr/src/app/dist/services/database.service.js:136:17
immich-server-1            |       at async /usr/src/app/dist/repositories/database.repository.js:177:23 {
immich-server-1            |     length: 170,
immich-server-1            |     severity: 'ERROR',
immich-server-1            |     code: '42501',
immich-server-1            |     detail: undefined,
immich-server-1            |     hint: 'Must be superuser to create this extension.',
immich-server-1            |     position: undefined,
immich-server-1            |     internalPosition: undefined,
immich-server-1            |     internalQuery: undefined,
immich-server-1            |     where: undefined,
immich-server-1            |     schema: undefined,
immich-server-1            |     table: undefined,
immich-server-1            |     column: undefined,
immich-server-1            |     dataType: undefined,
immich-server-1            |     constraint: undefined,
immich-server-1            |     file: 'extension.c',
immich-server-1            |     line: '910',
immich-server-1            |     routine: 'execute_extension_script'
immich-server-1            |   },
immich-server-1            |   length: 170,
immich-server-1            |   severity: 'ERROR',
immich-server-1            |   code: '42501',
immich-server-1            |   detail: undefined,
immich-server-1            |   hint: 'Must be superuser to create this extension.',
immich-server-1            |   position: undefined,
immich-server-1            |   internalPosition: undefined,
immich-server-1            |   internalQuery: undefined,
immich-server-1            |   where: undefined,
immich-server-1            |   schema: undefined,
immich-server-1            |   table: undefined,
immich-server-1            |   column: undefined,
immich-server-1            |   dataType: undefined,
immich-server-1            |   constraint: undefined,
immich-server-1            |   file: 'extension.c',
immich-server-1            |   line: '910',
immich-server-1            |   routine: 'execute_extension_script'
immich-server-1            | }
```
