### ISSUE TITLE
(bug) web: Repair Page very slow

### ISSUE THREAD

**Issue by MickLesk** [immich-app/immich#11481]
### Short remark:
The repairs page is damn slow, as soon as I open it the “reports” query sometimes hangs for a long time. When I switch from this page to others, they also become slower.

### Steps:
**1) Go to the “Administration” section at the top right of the user account**

**2) Users are the first selection** 

**3) Switch to Settings or Jobs or Other = quick (< 200 ms - reports pending are 4.)**
![image](https://github.com/user-attachments/assets/20ee52ff-ceb3-4d8e-8269-0573ed5ab5d8)

**4) Switch to Repair = Slow (pending done from 3. - 13 sec. to view the page)**
![image](https://github.com/user-attachments/assets/21b21a67-37d9-415c-9903-4aa1f545fa63)

**5.) Switch to external library or other = slightly slower than in 3. (> 4 sec.) and then switch back to repair = extremely slow (30 sec)**
![image](https://github.com/user-attachments/assets/25f82f88-0d39-4b38-a08b-c360d4c45464)

### The OS that Immich Server is running on

Debian 12 (Docker)

### Version of Immich Server

1.111.0

### Version of Immich Mobile App

1.111.0 Build 152

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
  pgdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=***************
DB_HOSTNAME=*********
DB_USERNAME=*********
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=./postgres
```

### Relevant log output

```shell
no log, but the Preview Output of "reports" 

{
  "orphans": [],
  "extras": [
    "/usr/src/app/upload/library/admin/2024/06/28/449220594_8371129499571983_500727103517236991_n.jpg",
    "/usr/src/app/upload/thumbs/47bdfb0e-5600-48ff-9973-d8926347661a/5e/9b/5e9b834d-b060-4f3d-b3d3-a96489fea5f3.jpeg",
    "/usr/src/app/upload/thumbs/47bdfb0e-5600-48ff-9973-d8926347661a/77/1f/771f7ae5-536c-48f1-a1fb-7415815b3cef.jpeg",
    "/usr/src/app/upload/thumbs/47bdfb0e-5600-48ff-9973-d8926347661a/7e/e9/7ee9de7d-64a7-4817-996c-9e82b006538e.jpeg",
    "/usr/src/app/upload/thumbs/47bdfb0e-5600-48ff-9973-d8926347661a/b5/ff/b5ff53b3-0547-420b-b0ab-1692121905db.jpeg",
    "/usr/src/app/upload/thumbs/47bdfb0e-5600-48ff-9973-d8926347661a/c5/2d/c52d7352-e0e4-4fd5-b4d4-ae07ed494500.jpeg",
    "/usr/src/app/upload/thumbs/8a2c54a6-b64f-41ca-b2fd-c576b77e5939/0f/6f/0f6f5192-0076-4cf8-b61b-2711d8e7471a.jpeg",
    "/usr/src/app/upload/thumbs/8a2c54a6-b64f-41ca-b2fd-c576b77e5939/1c/f5/1cf5bd94-946d-4569-9c1c-1f9298397638.jpeg",
    "/usr/src/app/upload/thumbs/8a2c54a6-b64f-41ca-b2fd-c576b77e5939/7b/82/7b82f85e-58c2-41bb-882d-c04e58ad02c6.jpeg",
    "/usr/src/app/upload/thumbs/edba30ad-b947-4d6e-a277-be7150d620b5/3b/44/3b44a0c2-fd3f-4d47-a8e7-0506a1baf6b2-preview.jpeg",
    "/usr/src/app/upload/thumbs/edba30ad-b947-4d6e-a277-be7150d620b5/3b/44/3b44a0c2-fd3f-4d47-a8e7-0506a1baf6b2-thumbnail.webp",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/00/61/00619c2b-affc-4b0c-8404-d7d2ffcfe89f.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/02/e4/02e4c6e8-48b9-475b-a986-872c0ef8b78d.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/17/7d/177d6472-84ef-448b-a7f9-a97ca8acb41f.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/19/b8/19b8a262-347d-41ce-9227-33337b1babe4.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/1b/62/1b621cba-7c44-44ec-9940-ef8dafe5a7cd.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/1c/a0/1ca0f2aa-e4c4-4f37-bde1-41a42d3edc04.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/1c/f4/1cf436dd-5358-45e7-b13d-f175222b289a.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/14/a2/14a2c0f7-4a10-41c0-8ef3-1397f2bfd2ab.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/2e/a9/2ea90eca-1b9e-46b9-a387-98f0a63e54c1.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/33/8e/338e7276-8f06-49ef-ae09-2f9ce56756b8.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/3d/69/3d6998ef-3ea0-4a36-9034-0b177df252d0.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/49/a3/49a31cc4-10e8-4dc6-8c6a-96c136b7f817.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/49/a7/49a71799-b1f1-4021-8cc3-ea3e749358f5.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/4d/50/4d50ccf0-315d-415d-a193-873a2d5797f8.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/4f/0c/4f0cf4c4-521a-48fd-9501-f9c745112a67.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/5e/2f/5e2f7d61-e1b2-471b-a948-0924d724faa6.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/5f/39/5f394e86-d8a0-4bcf-8a41-6b9106eedfb3.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/65/c8/65c8dfd0-fa2c-49d3-a3b3-802b9bd5cf36.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/67/44/6744e25f-d4e5-474d-ad25-e62aa2022fec.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/69/82/6982df52-7898-4400-899e-4050e826bbb9.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/6c/75/6c7514f4-90a9-4422-8a2b-97335f7efda5.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/73/9f/739f3818-7a3f-41ac-ae23-e308676c8f9f.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/7a/94/7a94d7e6-b9a7-48a3-864e-84f24a1d6264.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/7c/72/7c72bc93-3c85-4422-b948-b270783737ee.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/7c/fc/7cfc1ed4-8806-4068-a15d-a8ab9bf7c795.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/84/1d/841d7930-6cb4-4838-a5c1-d8d5082487e0.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/86/9f/869fd730-1b93-4eeb-a5ad-d463248366b0.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/82/46/82463169-15a4-4d0b-84ed-3d3c07864796.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/8b/68/8b6897a1-9a46-4bff-bed4-d9b02478fff6.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/97/fa/97fa452d-979b-46b4-a4c8-78c8cdfe1aa5.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/98/d6/98d69499-e4d7-4d18-823a-6899d33bf93d.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/9d/12/9d125baa-c7bb-4ea9-94bc-218292b72df7.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/a9/35/a935c01c-c39d-4ef9-9da5-ccefb251d242.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/b0/83/b08350aa-f432-4ca5-8eb5-3035a1d9713f.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/b0/a9/b0a91955-9077-45ea-8dd5-69ec27f5ded2.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/b3/c1/b3c16080-cee4-4b4f-8590-09916ba0b063.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/81/c2/81c24e8a-a7fd-402d-a6ec-98466ae8e3f2.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/c8/c7/c8c79540-8000-4769-8148-e80913a8af4c.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/cc/3c/cc3c588a-3bd8-4113-93ab-f3740e1414a1.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/d0/1e/d01ebc0f-b8d8-409d-8ba8-725ce9bd109a.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/d0/54/d054d55a-0b27-481b-8acb-ccf87519dad7.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/d4/8f/d48f39dc-86fc-4415-b51d-a14c062e023a.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/d6/28/d628f1e4-44e8-4be1-98df-831ca5e6790b.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/d8/45/d845c073-2ecb-45fc-8700-236792b18465.jpg",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/e2/89/e289ea50-6afb-4b48-8900-7e18398a5045.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/e8/37/e8374b41-ed25-4200-a650-4281c40d8fa8.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/eb/af/ebaf0d63-20f2-47b9-97b3-6cc9761ba57a.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/ed/0a/ed0a01d6-a30f-4fc5-92d5-aa995cec7e71.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/ed/43/ed439da8-c35f-4154-93cb-b7ce1addb58e.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/f0/2a/f02adfd8-c63c-4dc5-98ee-23532e741551.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/f0/c5/f0c5db77-521e-403c-b595-c3dde5a83216.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/f2/d9/f2d9fa80-5ff9-4bd9-8bb0-cc5025945e85.mp4",
    "/usr/src/app/upload/upload/47bdfb0e-5600-48ff-9973-d8926347661a/f2/db/f2dbfe31-3a4c-4671-9411-685cde39a40e.mp4"
  ]
}
```
![image](https://github.com/user-attachments/assets/6d0f53c6-47f2-4791-a67b-8ce978dd3d74)
