### ISSUE TITLE
Immich Web App titling recent days "last month"

### ISSUE THREAD

**Issue by williamkray** [immich-app/immich#11504]
### The bug

today is July 31st. current time is 7:07PM PDT.

In my timeline on the web app, I have pictures from July 31st, and July 30th (as well as before then).

Instead of dating the pictures from today as "Today", the header is "Last Month". Same for the pictures from July 30th, instead of "Yesterday" it titles them "Last Month".

Selecting the radio button next to either of these "Last Month" titles selects BOTH title radio buttons, but only appears to select the pictures from the day of the originally selected radio button. 

Adding the `TZ` env var to my docker deployment does not impact the titling.

This behavior was not noticed on the previous version of the server. Mobile apps correctly title the pictures from "Today" as "Wed, July 31".

![image](https://github.com/user-attachments/assets/b6e47c34-323c-4467-97c0-368d11fce527)

### The OS that Immich Server is running on

Docker Compose

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich:
    image: ghcr.io/immich-app/immich-server:release
    restart: always
    volumes:
      - ./storage/immich/media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./storage/photoprism/photolibrary:/legacy:ro # photoprism library
    expose:
      - 3001
    environment:
      DB_PASSWORD: REDACTED
      DB_USERNAME: REDACTED
      DB_DATABASE_NAME: REDACTED
      TZ: America/Los_Angeles
    depends_on:
      - immich-redis
      - immich-psql
    networks:
      - traefik
      - immichdb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=le"
      - "traefik.http.routers.immich.rule=Host(`immich.my.host`)"
```

### Your .env content

```Shell
env variables are added to my service definitions in my docker compose file
```

### Reproduction steps

```bash
1. run immich in docker containers
2. have pictures from the last few days
3. visit the page on July 31st (not sure if this is relevant but it feels important)
```

### Relevant log output

```shell
no relevant log data from the server is generated.
```
