### ISSUE TITLE
bug(mobile): Immich iOS App on iOS 18 Beta incorrectly treats Live Photos as Motion Photos on restore and saves only the image file

### ISSUE THREAD

**Issue by ankit5902** [immich-app/immich#11519]
### The bug

I uploaded/backed up a bunch of live photos using the Immich iOS App v1.111.0 on iOS 18. When downloading or restoring the live photo (on any device), only the still image is downloaded or restored, not the video part, thereby it loses the Live Photo functionality. It is treating as a motion photo, even though it is a live photo and saves only the still image file. (shown in the Immich iOS App Logs)

![IMG_7189](https://github.com/user-attachments/assets/254ea101-3c57-44b1-b7e0-244eed056117)

I tried creating a fresh Immich instance and uploading the live pictures from the iOS app, but it seems the issue still persists. The image is being treated as a motion photo. It could be that this might be due to changes in the Photos app on iOS 18 Beta 4. Images captured and uploaded from iOS 18 Beta version are being treated as motion photos in Immich App when restoring, while images captured on a stable version of iOS are working fine. Even if I airdrop an image from the iOS 18 Beta version device to a device running the stable version of iOS and then upload it, the issue still remains. It seems that something has changed in the Photos app in the unreleased iOS 18.

### The OS that Immich Server is running on

Debian 12 (Bookworm)

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0 on iOS 18 Beta

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    environment:
      - TZ=Asia/Kolkata
    restart: always
    depends_on:
       - redis
       - postgres

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - './model-cache:/cache'
    env_file:
      - .env
    networks:
      - traefik-proxy
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Asia/Kolkata
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - './config:/data'
    environment:
      - TZ=Asia/Kolkata
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy

  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    container_name: postgres
    volumes:
      - './postgres/data:/var/lib/postgresql/data'
      - './backups:/backups'
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_HOST=${DB_HOSTNAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_INITDB_ARGS='--data-checksums'
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

networks:
  traefik-proxy:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich

UPLOAD_LOCATION=./library
```

### Reproduction steps

```bash
1. Upload or back up the live photos using the Immich iOS app on iOS 18.
2. When downloading or restoring the live photo (on any device), only the still image is downloaded or restored, not the video part.
3. It is treated as a motion photo, even though it is a live photo. (shown in the Immich iOS App Logs)
```

### Relevant log output

![IMG_7189](https://github.com/user-attachments/assets/9d495a1c-54cf-4461-af97-260b4101b6cd)
