### ISSUE TITLE
Remove Offline Files doesn't remove files in trash

### ISSUE THREAD

**Issue by pjft** [immich-app/immich#11529]
### The bug

Hi. Since I have my external library in read-only mode, I found myself deleting files manually from my HDD after Trashing them on Immich.

However, after deleting them, they show up on Immich's trash as Offline (expected) but when I remove offline files from the External Library, the files still seem to stay there. Is this intended? I'd expect it to work whether the files are in the Trash or not.

### The OS that Immich Server is running on

Raspberry Pi OS

### Version of Immich Server

1.111.0

### Version of Immich Mobile App

1.111.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "autoheal=true"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    labels:
      - "autoheal=true"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=300
      - AUTOHEAL_START_PERIOD=60
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=120
      - AUTOHEAL_ONLY_MONITOR_RUNNING=true
      - CURL_TIMEOUT=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-label-HDD/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/dev-disk-by-label-HDD/immich/postgres

EXTERNAL_PATH=/srv/dev-disk-by-label-HDD/root/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=<redacted>
DB_DATABASE_NAME=<redacted>
```

### Reproduction steps

```bash
1. Have some external library files in trash.
2. Remove files from source drive, some that are in trash, some that aren't in trash.
3. Remove offline files.

Outcome: Offline files not in trash are removed. Ones in trash aren't.
```

### Relevant log output

```shell
[Nest] 197  - 08/01/2024, 11:13:28 PM VERBOSE [Api:LibraryService~fyi9ulij] Removing offline files from library: xxxx
[Nest] 197  - 08/01/2024, 11:13:28 PM   DEBUG [Api:LoggingInterceptor~fyi9ulij] POST /api/libraries/xxxx/removeOffline 204 8.14ms 46.189.193.127
[Nest] 7  - 08/01/2024, 11:13:28 PM   DEBUG [Microservices:LibraryService] Removing 1 offline assets
```

### Additional information

Just that. This happens both from web and via API.

Thank you!
