### ISSUE TITLE
Motion Photo Videos not Loading

### ISSUE THREAD

**Issue by CrossR** [immich-app/immich#11541]
### The bug

Hi,

I have a certain subset of pictures / motion photos that don't seem to work in Immich.

They are correctly identified as motion photos, but the actual embedded videos themselves don't ever load and seem corrupt / broken.

I've uploaded the files manually via the web, and tested that the `.jpg` files (produced from a Samsung S21, downloaded directly from the Google Photo Web UI) are valid and contain a video via the demo site over at https://github.com/dj0001/Motion-Photo-Viewer. I left the server for a few hours, and kicked off every type of job a few times, to make sure the metadata was extracted / transcoded videos etcetc to see if that was the issue (though I only have something like 10 images in the sever whilst I figure out this issue).

You should be able to see the issue below, where Immich can identify its a motion photo, and if you hover it does try to start the video (you can see the colours shift a bit), but the video doesn't actually contain any data. You can see this better when I click through and the seek bar goes crazy.

https://github.com/user-attachments/assets/580d1609-eeab-4ee7-a6d1-95513c518b9d

If I use the download button in the UI, I get back a valid image that does contain the motion data still, but the video can't be played by the Windows default media player. VLC can open the file and thinks its a 10s video of a static image, despite the fact the actual video is less than 3 seconds long.

This only seems to be an issue for some subset of my pictures, with pictures before a certain date being fine, it being broken for a year or so, then back to working again.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - default
      - traefik_proxy
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=http"
      - "traefik.http.routers.immich.rule=Host(`XXXXXXXXXXXXXXXXXXXXXXXX`)"
      - "traefik.http.middlewares.immich-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.immich.middlewares=immich-https-redirect"
      - "traefik.http.routers.immich-secure.entrypoints=https"
      - "traefik.http.routers.immich-secure.rule=Host(`XXXXXXXXXXXXXXXXXXXXXXXX`)"
      - "traefik.http.routers.immich-secure.tls=true"
      - "traefik.http.routers.immich-secure.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=3001"
      - "traefik.docker.network=traefik_proxy"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    labels:
      - "diun.enable=true"
    restart: always
    networks:
      - default

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    labels:
      - "diun.enable=true"
    restart: always
    networks:
      - default

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
    networks:
      - default

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

volumes:
  pgdata:
  model-cache:

networks:
  default:
  traefik_proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/ryan/docker/immich/library/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload photo to Immich via the website
2. Try and view the motion photo data
3. See a broken video, stuck at the start of the video
```
