### ISSUE TITLE
Browser halts processing page in publicly shared album

### ISSUE THREAD

**Issue by ArjenR** [immich-app/immich#11593]
### The bug

When accessing an album using a share link with password, the browser stops interpreting/processing the page with an error in the debug console. Tested with Firefox and Thorium (Chromium based) browsers.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

1.108.0.build.148

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    command: [ "start.sh", "immich" ]
    extends: 
      file: hwaccel.transcoding.yml
      service: nvenc 

    volumes:
      - /srv/tank01/@containers/immich-photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    # ports:
    #   - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - default
      - cryptproxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - /var/storage/raid0/immich/model-cache:/cache:Z
      - /var/storage/raid0/immich/apt:/opt/extra/deb:Z
#      - ./selinux_machine_learning.sh:/usr/src/app/selinux_machine_learning.sh:Z
    env_file:
      - .env
#    command: ["./selinux_machine_learning.sh"]
    healthcheck:
      disable: false
    restart: always
    networks:
      - default

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - default

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /var/storage/raid1/immich/pgdata:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - default

networks:
  cryptproxy:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

UID=1000
GID=1000
```

### Reproduction steps

```bash
1. Create an album and add photo's.
2. Share using a link with password and allow uploads.
3. Access share via link.
4. Scroll through photo's.
5. Then click a photo to show large size. 
6. Photo loads, but loading indicator stops before 50%.
7. Browser does not respond to any buttons in the page or the back or the back button. Only by jumping back to another page all together or closing the tab/window are you able to leave the page.
```

### Relevant log output

```shell
Uncaught (in promise) TypeError: URL constructor: XXXXXX.XXXXXXX.XX is not a valid URL.
    Immutable 23
    <anonymous> https://XXXXXX.XXXXXXX.XX/share/nNcO7JTYz7NPS2vJgnvnqs2-U61eVzYfIibL_GTTZxKLArXjZtlZdP8vryBCi_9kb1s:79
    promise callback* https://XXXXXX.XXXXXXX.XX/share/nNcO7JTYz7NPS2vJgnvnqs2-U61eVzYfIibL_GTTZxKLArXjZtlZdP8vryBCi_9kb1s:78
0.B_Hu6Y4Z.js:9:13901
```

### Additional information

Immich is hosted behind Caddy proxy
