### ISSUE TITLE
Reverse proxy with Caddy only works with subdomains (and not subpaths)

### ISSUE THREAD

**Issue by FilipHarald** [immich-app/immich#11666]
### The bug

I realize that this might not be a bug because this is how it's intended to work. But in that case I think it can be good to write in the documentation so that future users don't encounter the same problem that I did. (To be clear: the docs suggests the correct way of doing it already. But it does not say that subpath does not work.)

In short, this works...:
```
photos.{$DOMAIN} {
...
  reverse_proxy immich-server:8097
}
```
...and this does not work:
```
{$DOMAIN} {
...
    handle_path /photos/* {
      reverse_proxy jellyfin:8097
    }
}
```

### The OS that Immich Server is running on

Docker on a Raspberry Pi

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      DOMAIN: ${YOUR_DOMAIN}

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

YOUR_IP=example.com
```

### Reproduction steps

```bash
Copy `docker-compose.yml`, `.env` and add this `Caddyfile`:

{$DOMAIN} {
  handle_path /photos/* {
    reverse_proxy immich-server:2283
  }
}
photos.{$DOMAIN} {
  reverse_proxy immich-server:2283
}
```

Update `YOUR_DOMAIN` in `.env`

Try to visit `photos.[YOUR_DOMAIN]` (this will work) and `[YOUR_DOMAIN]/photos/` (this will not work).
```


### Relevant log output

```shell
I do not see any errors/problems in the caddy and immich-server logs (with verbose logs).

What I can see in Chrome console is errors like this:
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Additional information

![Screenshot from 2024-08-09 11-42-34](https://github.com/user-attachments/assets/1195eb91-58f4-4d52-8c41-e6cfa9194221)
![Screenshot from 2024-08-09 11-42-47](https://github.com/user-attachments/assets/430b9593-a47c-4c4f-9dd6-93c324c9cb99)
![Screenshot from 2024-08-09 11-42-54](https://github.com/user-attachments/assets/0bd47554-8ce9-45af-85c1-0afc143f7194)
![Screenshot from 2024-08-09 11-43-11](https://github.com/user-attachments/assets/9d9ba5ee-191a-45d4-8122-5e1714f763aa)
