### ISSUE TITLE
Removing image from album actually deletes it completely from immich using Android mobile app

### ISSUE THREAD

**Issue by vfedetz** [immich-app/immich#11670]
### The bug

When trying to remove an image from an album using the Android mobile app, the image actually is deleted. 

Expected behavior: remove image from the album, do not delete from immich.

### The OS that Immich Server is running on

Docker running on Unbuntu

### Version of Immich Server

1.111.0

### Version of Immich Mobile App

1.111.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # external libraries
      - /mnt/data/media/photos/misc-photos-vfedetz:/mnt/photos/vfedetz:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/vfedetz/docker/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/data/media/photos/immich
DB_DATA_LOCATION=/home/vfedetz/docker/immich
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. You can recreate the issue by long pressing the image in the album and selecting "remove from album" as well as tapping an individual image and selecting "remove from album". 
2. The app then asks for confirmation to "allow immich to delete this photo". 
3. If you then press "allow" the image will be deleted from the album as well as immich itself with notification "asset trashed".
...
```
