### ISSUE TITLE
A few minor problems with the mobile client

### ISSUE THREAD

**Issue by pyccl** [immich-app/immich#11681]
### The bug

1.Android phone client opens Picture Editing → Crop, default is Free, click back and forth 1: 1 or some other scale, The latter is scaled to the minimum width before clicking.Eventually it shrinks to a cross icon.
![Screenshot_2024-08-10-14-47-07-222_app alextran immich](https://github.com/user-attachments/assets/ff8f8cba-151f-4429-9e38-cbbb744f4138)

2.The city in the GPS information is wrong, the correct is the People's Republic of China, Fujian Province, Sanming City, Sanyuan District, Results GPS information is the People's Republic of China, Fujian Province, Xubi Town, (Sanming City is correct, Xubi Town is two grades smaller than Sanming City )
![1723274960063](https://github.com/user-attachments/assets/3aab8b59-31be-4762-8555-6cbf23c3e7f7)
3.The list of cities is large, so when you click search, the city column will fill the phone screen, and you can't click on the blank space to return (no white space). The height of the following list should be limited here.
In China, the administrative divisions from big to small are provinces, cities, districts, counties and towns.
Address information or English, not changed to the corresponding Chinese.
![Screenshot_2024-08-10-14-49-14-618_app alextran immich](https://github.com/user-attachments/assets/6700b470-0a16-463e-abb1-cffa7f04368c)
4.Mobile phone maps are displayed in minimum size. But there are no photos, you have to swipe them manually to find them, Hope to automatically identify the GPS position and automatically zoom according to the position of the photo.
![Screenshot_2024-08-10-14-50-36-011_app alextran immich](https://github.com/user-attachments/assets/8ccf33a1-b29e-4331-b4b2-3a8c853a129a)

### The OS that Immich Server is running on

windows 11 docker desktop v4.30.0

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0.build.152

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "E:/My photo:/mnt/media/myphoto"
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: m.daocloud.io/docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: m.daocloud.io/docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1.Normal use, directly open will find
2.
3.
...
```

### Additional information

中华人民共和国的行政区划依次是1.省(直辖市、自治区、特别行政区)，2.市(直辖市中的区)，3.县(县级市)，4.乡镇。
台湾是属于中华人民共和国的一个省，不能作为一个国家出现。台湾的行政区划有所不同，台湾省下一级是市或县(市或县同级别)。

The administrative divisions of the People's Republic of China are 1. provinces (municipalities directly under the central government, autonomous regions and special administrative regions), 2. cities (districts in municipalities directly under the central government), 3. Counties (county-level cities), 4. Villages and towns. 
Important:Taiwan is a province belonging to the People's Republic of China and cannot appear as a country. Taiwan's administrative divisions are different, the next level of Taiwan Province is the city or county (city or county with the same level).
