### ISSUE TITLE
IOS login issue v1.111: can't login after logout

### ISSUE THREAD

**Issue by thucngyyen** [immich-app/immich#11781]
### The bug

- Web works fine.
- On IOS v1.111, everything was working until I sign out and I can't sign in with error `Error logging you in, check server URL, email and password`.

- Try on different device (with different account) and get the same error, now I have two phone with no Immich :(

Turn on `Verbose` log, I got this on server side:
```
immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:LoggingInterceptor~v0w7pkzh] GET /api/server-info/ping 200 0.27ms 172.71.154.110
immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:HttpExceptionFilter~4e2bzdyg] HttpException(404) {"message":"Cannot GET /api/.well-known/immich","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:LoggingInterceptor~wphms3bc] GET /api/server-info/ping 200 0.18ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~ijjwz4yo] POST /api/auth/login 201 88.92ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM VERBOSE [Api:LoggingInterceptor~ijjwz4yo] {"email":"thucnguyen1952000@gmail.com","password":"********"}
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~unbl5eps] GET /api/users/me 200 0.34ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~ylji4r1b] GET /api/users/me/preferences 200 0.27ms 172.71.154.142

```

### The OS that Immich Server is running on

OMV - 7.3.0-5 (Sandworm)

### Version of Immich Server

v1.111

### Version of Immich Mobile App

v1.111

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
redacted
```

### Reproduction steps

```bash
1. On IOS app v1.111, sign in
2. Sign out
3. Can't sign in anymore
```

### Relevant log output

```shell
Turn on `Verbose` log, I got this on server side:

immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:LoggingInterceptor~v0w7pkzh] GET /api/server-info/ping 200 0.27ms 172.71.154.110
immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:HttpExceptionFilter~4e2bzdyg] HttpException(404) {"message":"Cannot GET /api/.well-known/immich","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 08/14/2024, 6:04:32 PM   DEBUG [Api:LoggingInterceptor~wphms3bc] GET /api/server-info/ping 200 0.18ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~ijjwz4yo] POST /api/auth/login 201 88.92ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM VERBOSE [Api:LoggingInterceptor~ijjwz4yo] {"email":"thucnguyen1952000@gmail.com","password":"********"}
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~unbl5eps] GET /api/users/me 200 0.34ms 172.71.158.212
immich_server            | [Nest] 17  - 08/14/2024, 6:04:33 PM   DEBUG [Api:LoggingInterceptor~ylji4r1b] GET /api/users/me/preferences 200 0.27ms 172.71.154.142

```
```


### Additional information

NA
