### ISSUE TITLE
Error after v.112.1 upgrade - Could not retrieve CLIP dimension size

### ISSUE THREAD

**Issue by alceasan** [immich-app/immich#11801]
### The bug

After upgrade to v.112.1 the server is restarting, I can't access.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /mnt/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    ports:
      - 2283:3001
    restart: unless-stopped
    network_mode: bridge

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    environment:
      MACHINE_LEARNING_REQUEST_THREADS: 4
    ports:
      - 3003:3003
    volumes:
      - /data/immich/model-cache:/cache
    restart: unless-stopped
    network_mode: bridge
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Upgrade to v.112.1
```

### Relevant log output

```shell
microservices worker exited with code 1
Error: Could not retrieve CLIP dimension size
    at SearchRepository.getDimensionSize (/usr/src/app/dist/repositories/search.repository.js:216:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/repositories/database.repository.js:186:23
    at async /usr/src/app/dist/services/smart-info.service.js:70:31
```

### Additional information

I already tried to update pgvecto.rs to 0.3.0, but the same error prevails. My current CLIP model is **XLM-Roberta-Large-Vit-B-16Plus**
