### ISSUE TITLE
Error after updating Immich to v1.112.1

### ISSUE THREAD

**Issue by utrack** [immich-app/immich#11803]
### The bug

Hi there! After an update from v1.111.0 to 112.1, the server started crashing with this log:

(not a `code` block to enable word wrapping)
immich_server            |   "passwordLogin": true,                                                                                                                                                                                                                                         immich_server            |   "configFile": false,                                                                                                                                                                                                                                           immich_server            |   "email": false                                                                                                                                                                                                                                                 immich_server            | }                                                                                                                                                                                                                                                                immich_server            | [Nest] 7  - 08/15/2024, 9:31:41 AM   ERROR [Microservices:An instance of SystemConfigDto has failed the validation:                                                                                                                                              immich_server            |  - property server.externalDomain has failed the following constraints: isUrl                                                                                                                                                                                    immich_server            | ] Validation error                                                                                                                                                                                                                                               immich_server            | [Nest] 17  - 08/15/2024, 9:31:41 AM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | [Nest] 7  - 08/15/2024, 9:31:41 AM   ERROR [Microservices:An instance of SystemConfigDto has failed the validation:                                                                                                                                              immich_server            |  - property server.externalDomain has failed the following constraints: isUrl                                                                                                                                                                                    immich_server            | ] Validation error 

### The OS that Immich Server is running on

Docker in Arch

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

<not needed>

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /opt/docked/immich/passwd:/etc/passwd
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    env_file:
      - .env
    cpuset: "15-18"
    ports:
      - 2283:3001
    group_add:
      - 989
      - 985
    user: "1004:1004"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    #image: ghcr.io/immich-app/immich-machine-learning:main-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
      #user: "1004:1004"
      #group_add:
      #- 989
      #- 985
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
      #cpuset: "12-18"
    volumes:
      - model-cache:/cache
      - /opt/docked/immich/passwd:/etc/passwd
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
      #user: "1004:1004"
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/docked/immich/pgdb:/var/lib/postgresql/data
    restart: always
    user: "1004:1004"

volumes:
  pgdata:
  model-cache:
```


### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables


UPLOAD_LOCATION=/mnt/raidbfs/immich
PUID=
IMMICH_VERSION=release
DB_PASSWORD=super-secret-redacted-password :)

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=some user :)
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
PUID=1004
PGID=1001
LOG_LEVEL=debug
```


### Reproduction steps

```bash
1. Update to v1.112.1
```


### Relevant log output

```shell
immich_server            |   "passwordLogin": true,                                                                                                                                                                                                                                         immich_server            |   "configFile": false,                                                                                                                                                                                                                                           immich_server            |   "email": false                                                                                                                                                                                                                                                 immich_server            | }                                                                                                                                                                                                                                                                immich_server            | [Nest] 7  - 08/15/2024, 9:31:41 AM   ERROR [Microservices:An instance of SystemConfigDto has failed the validation:                                                                                                                                              immich_server            |  - property server.externalDomain has failed the following constraints: isUrl                                                                                                                                                                                    immich_server            | ] Validation error                                                                                                                                                                                                                                               immich_server            | [Nest] 17  - 08/15/2024, 9:31:41 AM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | [Nest] 7  - 08/15/2024, 9:31:41 AM   ERROR [Microservices:An instance of SystemConfigDto has failed the validation:                                                                                                                                              immich_server            |  - property server.externalDomain has failed the following constraints: isUrl                                                                                                                                                                                    immich_server            | ] Validation error
```


### Additional information

_No response_
