### ISSUE TITLE
Android motion pictures aren't recognized correcty, and the app has an unconsistant behavior

### ISSUE THREAD

**Issue by simulot** [immich-app/immich#11886]
### The bug

We expect that motion pictures to be handled as IPhone live photos: The video plays when the  thumb is hovered by the mouse.
A motion picture consists in a pair of files: 
- IMAGE.MP file which is actually a MP4 file, containing the movie,
- IMAGE.MP.JPG file with static image, containing also a compressed version of the movie.

The video part when detected doesn't play.
Most of the time the .MP isn't took into account.

### The OS that Immich Server is running on

linux mint 21.3

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
UPLOAD_LOCATION=/home/user/Dev/immich-test
LOG_LEVEL=verbose
TYPESENSE_API_KEY=some-random-text
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_VERSION=main
```

### Reproduction steps

```bash
### When the 2 files are dropped on the web application's page:

Most of the times the the picture appears, without the "play" icon. This is a "still" photo. In this case there isn't file in encoded-video folder.

Sometimes, the  picture appears, with the "play" icon. But the movie doesn't play when hovered. 
When opening the image, we  get the the movie progression, be the image is still.

We get 2 files in the encoded-video: a GUID.MP4 and a GUID-PM.mp4 files.  None is playable.

### When using immich-go:
The image appears with a play icon, but the movie isn't playable.
Immich-go detects the .MP and .MP.JPG couples and upload first the MP files pretending it's a MP4, gets its ID, and then upload the JPG files and give the MP's ID as Livephoto ID.
```

### Additional information

This method used to work with immich v1.109. 

related issues:
- #10986
- #10374
- https://github.com/simulot/immich-go/issues/303

Be sure to restart your immich instance and to clear the browser cache between your tests.
