### ISSUE TITLE
unstacking causes server 500 error

### ISSUE THREAD

**Issue by mattzjack** [immich-app/immich#11906]
### The bug

I unstacked a pair of photos, and ran into a server 500 error. I also only see one of the 2 photos left. The other one seems to be gone.

### The OS that Immich Server is running on

Raspberry Pi OS (Debian 12)

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/kyz/Volume/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
I'm not sure which of the steps matters, but here's what I did. I haven't tried reproducing this.

1. From deduplicate, press the Stack button (seems to be new to v1.112)
2. Delete the stack (put into trash)
3. Restore from trash
4. Attempt to unstack
5. See a server 500 toast, and only 1 photo exists
```

### Relevant log output

```shell
## This is what I get for running `sudo docker logs <server container id>`

[Nest] 17  - 08/19/2024, 4:34:33 AM     LOG [Api:EventRepository] Websocket Disconnect: W2_PauIq9xYYlC0iAAAB
[Nest] 17  - 08/19/2024, 4:40:28 AM   ERROR [Api:QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async AssetRepository.updateAll (/usr/src/app/dist/repositories/asset.repository.js:189:9)
    at async descriptor.value (/usr/src/app/dist/decorators.js:48:24)
    at async AssetService.updateAll (/usr/src/app/dist/services/asset.service.js:195:9)~ijvbh3mb] Failed to update assets
[Nest] 17  - 08/19/2024, 4:40:28 AM   ERROR [Api:QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:83:33)
    at async AssetRepository.updateAll (/usr/src/app/dist/repositories/asset.repository.js:189:9)
    at async descriptor.value (/usr/src/app/dist/decorators.js:48:24)
    at async AssetService.updateAll (/usr/src/app/dist/services/asset.service.js:195:9)~ijvbh3mb] QueryFailedError: deadlock detected
[Nest] 17  - 08/19/2024, 4:40:39 AM     LOG [Api:EventRepository] Websocket Disconnect: odyeww2sJDhiZlSjAAAD
```
