### ISSUE TITLE
Cannot restore postgres database - ERROR: role "postgres" already exists

### ISSUE THREAD

**Issue by Aspyryan** [immich-app/immich#11962]
### The bug

Hi, I have automatic backups for postgres and immich with restic enabled and now I want to add some automated disaster recovery testing. Right now when I try to run the postgres migrations I get some errors like:
```
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists
```

I have followed the [documentation](https://immich.app/docs/administration/backup-and-restore) to restore but still not working. Is this because the postgres is already running somewhere else or something? Can't figure it out. If you need any extra information, please let me know. Tried this a couple of times but I cannot get it to work.

**EDIT:** The backup was made from the original running instances with the exact same .env and docker-compose file (other then removing the machine-learning and pg backup container)

**EDIT 2**: Another error I see in Portainer is the following:
![/var/run/postgresql:5432 - accepting connections psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: database "immich" does not exist checksum failure count is](https://github.com/user-attachments/assets/c32bf689-f305-40af-98c5-68ff537697dc)

**Edit 3:** Please could anyone check this out, I need this before fully using the service - please :D

The original and restore instance together in portainer:
![image](https://github.com/user-attachments/assets/3fb7d223-6092-49ea-a2e0-2ddd941f98eb)



PS: My `docker-compose` version it the right version and I am not able to get `docker compose` since I'm on Synology DSM

<details>
  <summary>Env</summary>

```env
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

</details>

Full log (Error last command):
```console
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ls -la
total 36
drwxrwxrwx+  5 root   root  4096 Aug 16 00:20 .
drwxrwxrwx+  7 root   root  4096 Aug 15 01:19 ..
-rwxr-xr-x   1 Jasper users  289 Aug 13 10:19 backup-to-azure.sh
-rwxrwxrwx   1 Jasper users 2491 Aug 16 00:03 docker-compose.yml
-rwxrwxrwx   1 Jasper users  862 Aug 16 00:19 .env
drwxr-xr-x   4 Jasper users 4096 Aug  2 00:04 library
drwxr-xr-x   6 Jasper users 4096 Aug 11 02:07 pgbackups
drwx------  21    999 users 4096 Aug 16 00:40 postgres
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ cat docker-compose.yml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich-restore-test

services:
  immich-server:
    container_name: immich_server_restore_test
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 1283:3001
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis_restore_test
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres_restore_test
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ls
backup-to-azure.sh  docker-compose.yml  library  pgbackups  postgres
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker-compose down -v
Password:
[+] Running 4/4
 ⠿ Container immich_server_restore_test    Removed                                                                                                                                                                                                                                 0.0s
 ⠿ Container immich_postgres_restore_test  Removed                                                                                                                                                                                                                                 0.3s
 ⠿ Container immich_redis_restore_test     Removed                                                                                                                                                                                                                                 0.0s
 ⠿ Network immich-restore-test_default     Removed                                                                                                                                                                                                                                 0.2s
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ls
backup-to-azure.sh  docker-compose.yml  library  pgbackups  postgres
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo rm -r postgres/
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ls
backup-to-azure.sh  docker-compose.yml  library  pgbackups
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ls -la
total 32
drwxrwxrwx+ 4 root   root  4096 Aug 16 00:54 .
drwxrwxrwx+ 7 root   root  4096 Aug 15 01:19 ..
-rwxr-xr-x  1 Jasper users  289 Aug 13 10:19 backup-to-azure.sh
-rwxrwxrwx  1 Jasper users 2491 Aug 16 00:03 docker-compose.yml
-rwxrwxrwx  1 Jasper users  862 Aug 16 00:19 .env
drwxr-xr-x  4 Jasper users 4096 Aug  2 00:04 library
drwxr-xr-x  6 Jasper users 4096 Aug 11 02:07 pgbackups
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker-compose down -v^C
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ ^C
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker-compose create
[+] Running 4/4
 ⠿ Network immich-restore-test_default     Created                                                                                                                                                                                                                                 0.3s
 ⠿ Container immich_postgres_restore_test  Created                                                                                                                                                                                                                                 0.1s
 ⠿ Container immich_redis_restore_test     Created                                                                                                                                                                                                                                 0.1s
 ⠿ Container immich_server_restore_test    Created                                                                                                                                                                                                                                 0.1s
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker start immich_postgres_restore_test
Error response from daemon: Bind mount failed: '/volume1/docker/immich-restore-test/postgres' does not exists
Error: failed to start containers: immich_postgres_restore_test
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ mkdir postgres
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker start immich_postgres_restore_test
immich_postgres_restore_test
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sudo docker logs immich_postgres_restore_test
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are enabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
waiting for server to start....2024-08-15 22:55:40.043 UTC [49] LOG:  redirecting log output to logging collector process
2024-08-15 22:55:40.043 UTC [49] HINT:  Future log output will appear in directory "log".
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down.... done
server stopped

PostgreSQL init process complete; ready for start up.

2024-08-15 22:55:40.581 UTC [1] LOG:  redirecting log output to logging collector process
2024-08-15 22:55:40.581 UTC [1] HINT:  Future log output will appear in directory "log".
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ sleep 10
Jasper@SYNOLOGY:/volume1/docker/immich-restore-test$ gunzip < "./pgbackups/daily/immich-latest.sql.gz" | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" | sudo docker exec -i immich_postgre
s_restore_test psql --username=postgres
SET
SET
SET
DROP DATABASE
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists
ALTER ROLE
SET
SET
SET
SET
SET
     set_config
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
UPDATE 1
DROP DATABASE
ERROR:  option "locale_provider" not recognized
LINE 1: ...late1 WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PRO...
                                                             ^
ERROR:  database "template1" does not exist
\connect: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  database "template1" does not exist
```

### The OS that Immich Server is running on

Synology DSM 7.2.1-69057 Update 5

### Version of Immich Server

v1.111.0

### Version of Immich Mobile App

v1.111.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  pgbackups:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    restart: always
    env_file:
      - .env
    volumes:
      - ./pgbackups:/backups
    depends_on:
      - database
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'

volumes:
  model-cache:
```


### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```


### Reproduction steps

```bash
1. Take a backup of immich following the tutorial at https://immich.app/docs/administration/backup-and-restore
2. Make a second folder with the same docker-compose file with different port.
3. Follow restore steps at  https://immich.app/docs/administration/backup-and-restore and as seen above in my console output
4. Cry
```


### Relevant log output

_No response_

### Additional information

_No response_
