### ISSUE TITLE
External Library not finding new files

### ISSUE THREAD

**Issue by deddy2101gmg** [immich-app/immich#11972]
### The bug

Hi,
with a freshly new installation of immich, the sw cannot find any new file. i can add the external folder to the external libraries but when it starts to scan says:
"Found 0 original files, 0 thumbnails, 0 encoded videos, 0 profile files"

The folder is correcly mounted and the files are visible to the docker container

### The OS that Immich Server is running on

Ubuntu 23.04 lxc privileged

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

1.112.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"  # or "3.10"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${FILE_PAST}:/usr/src/app/ext
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    env_file:
      - stack.env
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    env_file:
      - stack.env
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    env_file:
      - stack.env
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    volumes:
      - ${UPLOAD_LOCATION}/postgres:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION. /mnt/immich
IMMICH_VERSION. release
DB_PASSWORD ...
DB_HOSTNAME ...
DB_USERNAME ...
DB_DATABASE_NAME ...
REDIS_HOSTNAME immich_redis
FILE_PAST /mnt/disk/data/data/deddy/files/RANGERSPUBBLICO/
```

### Reproduction steps

```bash
The compose file is managed via portainer,
Initiated the sw i followed this guide :https://immich.app/docs/guides/external-library/
the library has a green mark on the side,
pressed the scan new library files,
in the jobs section n green cards exixst all jobs are set to 0 exept for Extract metadata, and Library with one waiting
```

### Relevant log output

```shell
Nest] 17  - 08/22/2024, 7:19:08 AM     LOG [Api:EventRepository] Websocket Connect:    dITzszoqqpD38mGKAAAB
[Nest] 17  - 08/22/2024, 7:24:58 AM     LOG [Api:AuditService~0eyz4dii] Found 0 original files, 0 thumbnails, 0 encoded videos, 0 profile files
[Nest] 17  - 08/22/2024, 7:24:58 AM     LOG [Api:AuditService~0eyz4dii] Found 0 assets, 1 users, 0 people
[Nest] 17  - 08/22/2024, 7:25:13 AM     LOG [Api:AuditService~cqqp2scj] Found 0 original files, 0 thumbnails, 0 encoded videos, 0 profile files
[Nest] 17  - 08/22/2024, 7:25:13 AM     LOG [Api:AuditService~cqqp2scj] Found 0 assets, 1 users, 0 people
[Nest] 17  - 08/22/2024, 7:25:14 AM     LOG [Api:AuditService~1vyq5zzg] Found 0 original files, 0 thumbnails, 0 encoded videos, 0 profile files
[Nest] 17  - 08/22/2024, 7:25:14 AM     LOG [Api:AuditService~1vyq5zzg] Found 0 assets, 1 users, 0 people
[Nest] 17  - 08/22/2024, 7:25:32 AM     LOG [Api:AuditService~7yykb73b] Found 0 original files, 0 thumbnails, 0 encoded videos, 0 profile files
```

### Additional information

files that i',m trying to add 
<img width="762" alt="Screenshot 2024-08-22 at 09 43 07" src="https://github.com/user-attachments/assets/826a4761-29f6-4f4c-9343-68c6aa6c0b1a">

job status 
![Screenshot 2024-08-22 at 09 41 04](https://github.com/user-attachments/assets/68270d8f-02d9-4563-a8b1-c7c4cb7018b0)

external library 

![Screenshot 2024-08-22 at 09 44 21](https://github.com/user-attachments/assets/b72b9461-6eaf-4e9a-a9b3-7c72a2e9cb7c)
