### ISSUE TITLE
Camera model empty list on web UI

### ISSUE THREAD

**Issue by tzxmaster** [immich-app/immich#11991]
### The bug

After selecting the camera make, I can see the request in console for all the camera models, they are present in the response but the values do not appear in the dropdown in the Web UI. It works on the phone app.
All other filters work just fine

### The OS that Immich Server is running on

Mint 22

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

1.112.1 build 154

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_1}
        target: /originals
        read_only: true
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_2}
        target: /originals2
        read_only: true        
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_1}
        target: /originals
        read_only: true
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_2}
        target: /originals2
        read_only: true         
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_1}
        target: /originals
        read_only: true
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_2}
        target: /originals2
        read_only: true         
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_1}
        target: /originals
        read_only: true
      - type: bind
        source: ${ORIGINALS_NEXTCLOUD_2}
        target: /originals2
        read_only: true      
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/data/immich/immich_storage
DB_DATA_LOCATION=/media/data/immich/immich_database
IMMICH_VERSION=release
DB_PASSWORD=pass_here
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
ORIGINALS_NEXTCLOUD_1=/media/data/nextcloud/1/files/InstantUpload/Camera
ORIGINALS_NEXTCLOUD_2=/media/data/nextcloud/2/files/Photos
```

### Reproduction steps

```bash
1.Open Web UI filter page
2.Select camera make
3.Empty camera models in dropdown
```
