### ISSUE TITLE
bug(web): Filter view - shift key multi-selection of photos is broken

### ISSUE THREAD

**Issue by jo-gross** [immich-app/immich#12016]
### The bug

I've applied a filter, such as "photos not in an album." While the filtered view opens as expected, I'm only able to select one asset at a time, and holding the Shift key doesn't allow me to select multiple assets between the first and last clicks. My expectation is that the Shift key would function as it does in the normal view, selecting all assets between the first and last selected items. 

### The OS that Immich Server is running on

Unraid (Docker) 6.12.11

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1 build.152

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_MEDIA}:/mnt/media:ro
      - ${EXTERNAL_MEDIA_ALBUMS}:/mnt/immich-albums:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2284:3001
    depends_on:
      - redis
      - database
    restart: always

    cpus: 2

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      - ${CONFIG_LOCATION}/model-cache:/cache
    env_file:
      - stack.env
    restart: always
    cpus: 2

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

    volumes:
      - ${CONFIG_LOCATION}/pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/user/photos/immich
CONFIG_LOCATION=/mnt/user/appdata/immich
NVIDIA_DRIVER_CAPABILITIES=all
NVIDIA_VISIBLE_DEVICES=all
EXTERNAL_MEDIA=/mnt/user/photos/media
EXTERNAL_MEDIA_ALBUMS=/mnt/user/photos/albums
```

### Reproduction steps

```bash
1. Open the default page with all images
2. Open the filter pane and apply any filter (e.g. 'archived only')
3. Select one asset, hold shift and select another one some assets away. Only the clicked ones get selected.
```
