### ISSUE TITLE
Unable to view some videos after restoring from backup

### ISSUE THREAD

**Issue by Aspyryan** [immich-app/immich#12010]
### The bug

I restored my immich fully from a backup (just testing) and after running all the thumbnail generation, transcoding etc... I cannot watch some videos. they appear with a red exclamation mark in the right upper corner without any additional information.
Video not wanting to preview:
![image](https://github.com/user-attachments/assets/3c409ffe-50d6-4441-975c-17f4fe5ca20b)

Image keeps loading when opening:
![image](https://github.com/user-attachments/assets/25c3d211-cf33-4e74-9bd5-c7a1ab30eb34)

When downloading the video, I can play it just fine. 

This is the response of the server: `{"statusCode":500,"message":"Internal server error"}` (logs below)
When I download the video it is in `.heic`, maybe this is the cause?

### The OS that Immich Server is running on

Synology DSM 7.2.1-69057 Update 5

### Version of Immich Server

V1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich_restore_test

services:
  immich-server:
    container_name: immich_server_restore_test
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 1283:3001
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis_restore_test
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres_restore_test
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Backup immich
2. Restore immich from backup
3. Run all jobs
4. Unable to watch some videos
```

### Relevant log output

```shell
[Nest] 16  - 08/24/2024, 8:15:04 AM    WARN [Api:ExpressAdapter~qv39lq4j] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.playAssetVideo (/usr/src/app/dist/controllers/asset-media.controller.js:60:9)
[Nest] 16  - 08/24/2024, 8:15:04 AM   ERROR [Api:ExceptionsHandler~qv39lq4j] ENOENT: no such file or directory, access 'upload/encoded-video/64669380-2429-40dd-8d3f-acc0dfdc59fd/cf/11/cf114f79-60ed-4698-b89d-fed6c2764111.mp4'
Error: ENOENT: no such file or directory, access 'upload/encoded-video/64669380-2429-40dd-8d3f-acc0dfdc59fd/cf/11/cf114f79-60ed-4698-b89d-fed6c2764111.mp4'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.playAssetVideo (/usr/src/app/dist/controllers/asset-media.controller.js:60:9)
```
