### ISSUE TITLE
Can't Login From Mobile

### ISSUE THREAD

**Issue by MoustafaAMahmoud** [immich-app/immich#12098]
### The bug

I installed Immich Chart version `0.7.1`, which includes app version `v1.106.1`, in my K8S home lab. I set up the ingress, but I cannot access the application through the URL (e.g., immich.homelab.com) from within my home network.

Additionally, when I tried to install the mobile app (version `v1.112.1`), I was unable to log in. I attempted to enter the URL in various formats, such as `immich.homelab.com` and `immich.homelab.com/api`, but neither worked.

```sh
#0      UserPreferencesResponseDto.fromJson (package:openapi/model/user_preferences_response_dto.dart:78)
#1      ApiClient.fromJson (package:openapi/api_client.dart:579)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      UsersApi.getMyPreferences (package:openapi/api/users_api.dart:177)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#5      AuthenticationNotifier.setSuccessLoginInfo (package:immich_mobile/providers/authentication.provider.dart:172)
<asynchronous suspension>
#6      LoginForm.build.login (package:immich_mobile/widgets/forms/login/login_form.dart:188)
<asynchronous suspension>
```
![photo_5942733153129055051_y](https://github.com/user-attachments/assets/99149c28-6159-4571-9066-2f2b45a98d30)
![photo_5942733153129055050_y](https://github.com/user-attachments/assets/a65692ab-bdc9-4760-9e18-240ee2bd09cb)
![photo_5942733153129055049_y](https://github.com/user-attachments/assets/2925797f-cca5-4448-a0cd-131582419b2a)

### The OS that Immich Server is running on

Immich Chart 0.7.1

### Version of Immich Server

v1.106.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
ArgoCD APP


project: default
source:
  repoURL: 'https://immich-app.github.io/immich-charts'
  targetRevision: 0.7.1
  helm:
    parameters:
      - name: immich.metrics.enabled
        value: 'false'
      - name: immich.persistence.library.existingClaim
        value: photo-library-pvc
      - name: postgresql.enabled
        value: 'true'
      - name: redis.enabled
        value: 'true'
    values: |-
      server:
        ingress:
          main:
            enabled: true
            className: nginx  # Ensure this matches your Ingress controller            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            hosts:
              - host: <redacted-domain>  # Replace with your actual domain
                paths:
                  - path: "/"
                    pathType: ImplementationSpecific
            tls:
              - hosts:
                  - <redacted-domain>  # Match this with the domain in the hosts section
                secretName: letsencrypt-production 
  chart: immich
destination:
  server: 'https://kubernetes.default.svc'
  namespace: media
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

### Your .env content

```Shell
ArgoCD APP


project: default
source:
  repoURL: 'https://immich-app.github.io/immich-charts'
  targetRevision: 0.7.1
  helm:
    parameters:
      - name: immich.metrics.enabled
        value: 'false'
      - name: immich.persistence.library.existingClaim
        value: photo-library-pvc
      - name: postgresql.enabled
        value: 'true'
      - name: redis.enabled
        value: 'true'
    values: |-
      server:
        ingress:
          main:
            enabled: true
            className: nginx  # Ensure this matches your Ingress controller            
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
              nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            hosts:
              - host: <redacted-domain>  # Replace with your actual domain
                paths:
                  - path: "/"
                    pathType: ImplementationSpecific
            tls:
              - hosts:
                  - <redacted-domain>  # Match this with the domain in the hosts section
                secretName: letsencrypt-production 
  chart: immich
destination:
  server: 'https://kubernetes.default.svc'
  namespace: media
syncPolicy:
  syncOptions:
    - CreateNamespace=true
```

### Reproduction steps

1. Open the app try to login will have the same issues with the provided versions

### Relevant log output

```shell
#0      UserPreferencesResponseDto.fromJson (package:openapi/model/user_preferences_response_dto.dart:78)
#1      ApiClient.fromJson (package:openapi/api_client.dart:579)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      UsersApi.getMyPreferences (package:openapi/api/users_api.dart:177)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:524)
<asynchronous suspension>
#5      AuthenticationNotifier.setSuccessLoginInfo (package:immich_mobile/providers/authentication.provider.dart:172)
<asynchronous suspension>
#6      LoginForm.build.login (package:immich_mobile/widgets/forms/login/login_form.dart:188)
<asynchronous suspension>
```
