### ISSUE TITLE
Untitled album disappears after uploading asset and clicking it

### ISSUE THREAD

**Issue by enteryournamehere** [immich-app/immich#12110]
### The bug

Creating a new empty album in the web UI, not naming it, *uploading* an image to it, and clicking the image, results in the album being deleted, the image stays uploaded but the album is gone.

Not uploading an image, but selecting an existing one, causes the bug not to appear.

### The OS that Immich Server is running on

OpenSUSE Tumbleweed

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
TZ=Europe/Amsterdam
IMMICH_VERSION=release
DB_PASSWORD=...
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. On web, click "Create Album". Do not enter a name yet.
![Screenshot from 2024-08-29 09-31-40](https://github.com/user-attachments/assets/8e0f76d0-2e38-4a0d-b509-f47f7200a613)
2. Click "Select photos", then "Select from computer".
3. Upload an image that isn't in Immich yet.
4. This completes fine. At this point, opening the album in a new tab works fine as well.
![Screenshot from 2024-08-29 09-33-46](https://github.com/user-attachments/assets/4dc88e99-ca69-466a-9448-f172570d8329)
5. Now, remaining on the album page, click the piece of just uploaded media.
6. Briefly, in the info panel, it'll show that it's part of the album, which then disappears.
![Screenshot from 2024-08-29 09-33-53](https://github.com/user-attachments/assets/3f882942-b7c0-4581-852c-cea3171962bc)
![Screenshot from 2024-08-29 09-33-56](https://github.com/user-attachments/assets/20420c5e-fd10-4d70-a475-8a4c9b8e0812)
7. Navigating back to the main album view, or reloading the image-in-album page, results in `Not found or no album.read access (400)`.
![Screenshot from 2024-08-29 09-34-01](https://github.com/user-attachments/assets/e8adb32d-e598-4ed5-97fa-bf80dd0229fb)
8. The album is gone but the piece of media stays/is in the timeline.

Giving the album a name before step 5 causes the bug not to appear.
Not uploading an image, but selecting an existing one, causes the bug not to appear.

### Relevant log output
~~Nothing odd in the `immich_server` logs.~~ See comment below with `DEBUG` logs.
```
[Nest] 17  - 08/29/2024, 9:46:30 AM     LOG [Api:EventRepository] Websocket Connect:    0UHciPaK2prx-SeQAAAn
[Nest] 7  - 08/29/2024, 9:46:48 AM     LOG [Microservices:MediaService] Successfully generated JPEG image preview for asset eebc2f2e-cc39-47dd-a75d-fa9573e1dadd
[Nest] 7  - 08/29/2024, 9:46:48 AM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset eebc2f2e-cc39-47dd-a75d-fa9573e1dadd
```
