### ISSUE TITLE
Issue with adding assets to album via Immich API

### ISSUE THREAD

**Issue by bmachek** [immich-app/immich#12135]
### The bug

I'm developing a Lightroom Classic plugin which uploads assets to an Immich server. Additionally the plugin creates albums and adds assets to it. The plugin uses the Immich API.

Sometimes the assets get uploaded, and the album created, but the assets do not show up or are note being added to the album. All API calls seems to be OK:

Immich server log: 
```
immich_server  | [Nest] 16  - 08/30/2024, 9:40:49 AM   DEBUG [Api:LoggingInterceptor~34mun5wg] PUT /api/albums/d3306b42-4953-4def-8167-e349aad91914/assets 200 11.81ms ::ffff:172.20.0.1
```
Log output from my plugin
```
2024-08-30 11:39:51.3910000+02:00, TRACE	ImmichAPI: Preparing PUT request /albums/d3306b42-4953-4def-8167-e349aad91914/assets
2024-08-30 11:39:51.4200000+02:00, TRACE	ImmichAPI PUT request succeeded: [{"id":"60ce7ed5-d1bf-41ab-9eea-dbb82e9a8eb9","success":true}]
```

But the album stays empty.

Funnily if I got to the album list in mobile or web the album has a valid thumbnail image.

If I repeat the request with curl:
```
curl -L -X PUT 'http://localhost:2283/api/albums/d3306b42-4953-4def-8167-e349aad91914/assets' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'x-api-key: xxx' -d '{
  "ids": [
    "7231a6c1-e61b-4a58-8538-c50e83a4ae5e"
  ]
}'
```
 I get the following response:
```
[{"id":"60ce7ed5-d1bf-41ab-9eea-dbb82e9a8eb9","success":false,"error":"duplicate"}]
````

Is this in any way a known behavior/bug?
How can I dig deeper into Immich server to debug this?
Is IMMICH_LOG_LEVEL=verbose the most verbose level of logging?

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    environment:
      DISABLE_JEMALLOC: true

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    environment:
      DISABLE_JEMALLOC: true

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    environment:
      DISABLE_JEMALLOC: true


  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      DISABLE_JEMALLOC: true
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=-xxx
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/opt/immich-app/immich-data


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=-xxx
#TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=xxx

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

IMMICH_API_URL_EXTERNAL=xxx

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=

IMMICH_LOG_LEVEL=verbose
#
DB_DATA_LOCATION=./postgres
MACHINE_LEARNING_WORKERS=1
```

### Reproduction steps

1. Create album with API call
2. Upload or replace assets with API
3. Add assets to created album via API
4. Look at album via web or mobile.

### Relevant log output

```shell
immich_server  | [Nest] 16  - 08/30/2024, 9:40:49 AM   DEBUG [Api:LoggingInterceptor~34mun5wg] PUT /api/albums/d3306b42-4953-4def-8167-e349aad91914/assets 200 11.81ms ::ffff:172.20.0.1
```

### Additional information

My repo: https://github.com/bmachek/lrc-immich-plugin
