### ISSUE TITLE
immich_server startup fails with Fatal error in , line 0. unreachable code

### ISSUE THREAD

**Issue by lpummer** [immich-app/immich#12133]
### The bug

Trying out Immich for the first time, following the Docker Compose instructions, the `immich_server` container keeps restarting. The output of `docker logs -f immich_server` is given in the Logs section.

The crash at startup started with v1.109.0 and continues through v1.112.1, though the strack traces look a little different under v1.109.0. I've pasted what I see in v1.112.1. By editing IMMICH_VERSION I was able to find that v1.108.0 is the last version that starts up reliably.

### The OS that Immich Server is running on

Linux version 6.6.47-0-virt (buildozer@build-3-20-x86_64) (gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, GNU ld (GNU Binutils) 2.42) #1-Alpine SMP PREEMPT_DYNAMIC 2024-08-19 08:18:35

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# unmodified wget of https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml on August 29, 2024

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# based on wget of https://github.com/immich-app/immich/releases/latest/download/example.env on August 29, 2024

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# work
#IMMICH_VERSION=v1.106.4
#IMMICH_VERSION=v1.108.0
# doesn't work
IMMICH_VERSION=release
#IMMICH_VERSION=v1.109.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. mkdir -p docker-compose/immich-app
2. cd docker-compose/immich-app
3. wget -O docker-compose.yml https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
4. wget -O .env https://github.com/immich-app/immich/releases/latest/download/example.env
5. docker compose up -d
6. watch docker ps
7. observe immich_server never goes healthy, keeps restarting

### Relevant log output

```shell
Detected CPU Cores: 4
Detected CPU Cores: 4


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffd11894d70
----- Native stack trace -----

 1: 0xd39331  [node]
 2: 0x21702c1 V8_Fatal(char const*, ...) [node]
 3: 0x12d3c18  [node]
 4: 0x12d3cba  [node]
 5: 0x13c2f9a v8::internal::Object::GetProperty(v8::internal::LookupIterator*, bool) [node]
 6: 0x1532229 v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::int
ernal::Object>, bool*) [node]
 7: 0x11cca0b v8::internal::KeyedLoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
 8: 0x11cccf1 v8::internal::Runtime_KeyedLoadIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x1964ef6  [node]
Detected CPU Cores: 4
Detected CPU Cores: 4
Detected CPU Cores: 4


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7fff37503f00
----- Native stack trace -----

 1: 0xd39331  [node]
 2: 0x21702c1 V8_Fatal(char const*, ...) [node]
 3: 0x12d3c18  [node]
 4: 0x12d3cba  [node]
 5: 0x13c2f9a v8::internal::Object::GetProperty(v8::internal::LookupIterator*, bool) [node]
 6: 0x1532229 v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::int
ernal::Object>, bool*) [node]
 7: 0x11cca0b v8::internal::KeyedLoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
 8: 0x11cccf1 v8::internal::Runtime_KeyedLoadIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x1964ef6  [node]
Detected CPU Cores: 4


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7ffdd1a4ef00
----- Native stack trace -----

 1: 0xd39331  [node]
 2: 0x21702c1 V8_Fatal(char const*, ...) [node]
 3: 0x12d3c18  [node]
 4: 0x12d3cba  [node]
 5: 0x13c2f9a v8::internal::Object::GetProperty(v8::internal::LookupIterator*, bool) [node]
 6: 0x1532229 v8::internal::Runtime::GetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::int
ernal::Object>, bool*) [node]
 7: 0x11cca0b v8::internal::KeyedLoadIC::Load(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
 8: 0x11cccf1 v8::internal::Runtime_KeyedLoadIC_Miss(int, unsigned long*, v8::internal::Isolate*) [node]
 9: 0x1964ef6  [node]
```
