### ISSUE TITLE
Mobile app on Android counts down

### ISSUE THREAD

**Issue by warkdarrior** [immich-app/immich#12136]
### The bug

The Backup screen shows "Total" counting down as files get uploaded. See video:
https://github.com/user-attachments/assets/013676c4-e1c5-400f-ad62-1319b87215c5

### The OS that Immich Server is running on

Android 14

### Version of Immich Server

1.112.1

### Version of Immich Mobile App

1.112.1 build.154

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
docker-compose.yml is identical to https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

I am using the following docker-compose.override.yml:

---
services:
  database:
    networks:
      - immich-internal
  redis:
    networks:
      - immich-internal
  immich-server:
    ports: !reset []
    expose:
      - "3001"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.backend=server
      - traefik.http.routers.immich.entryPoints=HTTPS
      - traefik.http.routers.immich.rule=Host("###")
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.tls.certresolver=LetsEncrypt
      - traefik.http.routers.immich.tls.options=default
      - traefik.http.services.immich.loadbalancer.server.port=3001
    networks:
      - immich-internal
      - traefik
  immich-machine-learning:
    networks:
      - immich-internal


networks:
  immich-internal:
    internal: true
  traefik:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=###/immich
# The location where your database files are stored
DB_DATA_LOCATION=./data/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=###

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Tap the cloud icon in the Android mobile app, to go to the Backup screen

```[tasklist]
### Tasks
```
