### ISSUE TITLE
Thumbnails failing to generate after update 1.113.0

### ISSUE THREAD

**Issue by SpookyUSAF** [immich-app/immich#12193]
### The bug

Seems like thumbnails are failing to generate to anything uploaded. I just converted to a storage template (default settings) so not sure if this is version related or storage template conversion related. Logs are indicating that the "upload/" folder is being added to the path where it shouldn't be.

Also, in the information button in Immich web, the file location is shown as "upload/library/admin/2006/2006-09-04/BABY_A.AVI" when it's actually "library/admin/2006/2006-09-04/BABY_A.AVI"

Here's logs showing this:
* [Nest] 7  - 08/31/2024, 11:40:25 AM     LOG [Microservices:MediaService] Successfully generated JPEG video preview for asset 89734cd9-3706-49de-bf96-e808f8eb251e
* [Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbhash): Error: Input file is missing: upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg
* [Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Error: Input file is missing: upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.generateThumbhash (/usr/src/app/dist/repositories/media.repository.js:141:14)
    at MediaService.handleGenerateThumbhash (/usr/src/app/dist/services/media.service.js:243:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)

### The OS that Immich Server is running on

Docker compose latest (Synology DS920+)

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

Latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/data/Photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<removed>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Uploaded a video via web browser.
2. found video in timeline, shows "Error loading image" with a red exclamation mark !
3. Video will not play.

### Relevant log output

```shell
[Nest] 7  - 08/31/2024, 11:40:25 AM     LOG [Microservices:MediaService] Successfully generated JPEG video preview for asset 89734cd9-3706-49de-bf96-e808f8eb251e
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbhash): Error: Input file is missing: upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Error: Input file is missing: upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.generateThumbhash (/usr/src/app/dist/repositories/media.repository.js:141:14)
    at MediaService.handleGenerateThumbhash (/usr/src/app/dist/services/media.service.js:243:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: ENOENT: no such file or directory, open 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, open 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async open (node:internal/fs/promises:639:25)
    at async readFile (node:internal/fs/promises:1249:14)
    at async MachineLearningRepository.getFormData (/usr/src/app/dist/repositories/machine-learning.repository.js:54:48)
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:17:26)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:132:27)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Object:
{
  "id": "89734cd9-3706-49de-bf96-e808f8eb251e",
  "source": "upload"
}
all values are hidden
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/face-detection): Error: ENOENT: no such file or directory, open 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Error: ENOENT: no such file or directory, open 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async open (node:internal/fs/promises:639:25)
    at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:33:26)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:286:52)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:JobService] Object:
{
  "id": "89734cd9-3706-49de-bf96-e808f8eb251e",
  "source": "upload"
}
all values are hidden
[Nest] 7  - 08/31/2024, 11:40:27 AM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libpostproc    57.  1.100 / 57.  1.100
[h264 @ 0x52f941c0580] Reinit context to 1088x1920, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/admin/2017/2017-05-07/IMG_0438.MOV':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
  Stream #0:0[0x1](und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 1080x1920 (1088x1920) [SAR 1:1 DAR 9:16], 4329 kb/s, 30 fps, 30 tbr, 90k tbn (default)
    Metadata:
[Nest] 31  - 08/31/2024, 11:42:13 AM   ERROR [Api:LoggerRepository~84krif5q] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 31  - 08/31/2024, 11:42:13 AM    WARN [Api:ExpressAdapter~84krif5q] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 31  - 08/31/2024, 11:42:13 AM   ERROR [Api:ExceptionsHandler~84krif5q] ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
Error: ENOENT: no such file or directory, access 'upload/thumbs/064a81a4-c0a7-43e8-8833-da5d6df5b736/89/73/89734cd9-3706-49de-bf96-e808f8eb251e-preview.jpeg'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:55:9)
    at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:57:9)
[Nest] 7  - 08/31/2024, 11:47:38 AM   ERROR [Microservices:MediaRepository] ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[avi @ 0x52a60140180] parser not found for codec rawvideo, packets or times may be invalid.
    Last message repeated 1 times
Input #0, avi, from 'upload/library/admin/2006/2006-09-04/BABY_A.AVI':
  Duration: 00:00:28.51, start: 0.000000, bitrate: 17093 kb/s
  Stream #0:0: Video: rawvideo, 1 reference frame, bgra, 406x293, 17226 kb/s, 4.49 fps, 4.50 tbr, 4.49 tbn
    Metadata:
      title           : XTD
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> mjpeg (native))
Press [q] to stop, [?] for help
[Parsed_thumbnail_1 @ 0x52a60151500] batch size: 12 frames
[Parsed_scale_5 @ 0x52a60151800] w:-2 h:1440 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[graph 0 input from stream 0:0 @ 0x52a60151980] w:406 h:293 pixfmt:bgra tb:100/449 fr:9/2 sar:0/1
[auto_scale_0 @ 0x52a60151ec0] w:iw h:ih flags:'' interl:0
[format @ 0x52a60151bc0] auto-inserting filter 'auto_scale_0' between the filter 'Parsed_format_6' and the filter 'format'
[Parsed_fps_0 @ 0x52a60151440] fps=12/1
[Parsed_scale_5 @ 0x52a60151800] w:406 h:293 fmt:bgra sar:0/1 -> w:1996 h:1440 fmt:yuv420p sar:0/1 flags:0x00042200
[swscaler @ 0x52a60916000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x52a60151ec0] w:1996 h:1440 fmt:yuv420p sar:0/1 -> w:1996 h:1440 fmt:yuvj420p sar:0/1 flags:0x00000004
[Parsed_fps_0 @ 0x52a60151440] Set first pts to 0
[Parsed_thumbnail_1 @ 0x52a60151500] frame id #5 (pts_time=0.416667) selected from a set of 12 images
[Parsed_thumbnail_1 @ 0x52a60151500] frame id #4 (pts_time=1.333333) selected from a set of 12 images
[Nest] 7  - 08/31/2024, 11:47:38 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-preview): Error: ffmpeg was killed with signal SIGSEGV
[Nest] 7  - 08/31/2024, 11:47:38 AM   ERROR [Microservices:JobService] Error: ffmpeg was killed with signal SIGSEGV
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:178:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[Nest] 7  - 08/31/2024, 11:47:38 AM   ERROR [Microservices:JobService] Object:
{
  "id": "6f93ac90-406b-404d-92a8-cb07d0a29e34",
  "source": "upload"
}
```
