### ISSUE TITLE
Android showing different in timeline than IOS/Firefox

### ISSUE THREAD

**Issue by ndewijer** [immich-app/immich#12227]
### The bug

My wife, while watching the "one year ago" feed, got a video that should not be there. It's highlighted in red.
On the screen it's 0:14 but when clicking it, it becomes a video over a minute long.

![WhatsApp Image 2024-09-02 at 09 41 55](https://github.com/user-attachments/assets/61bd9979-3a31-42c8-bd7d-7e4c15fdaba6)

Looking at my own phone and on the browser, I don't see that video but a different video instead that is indeed 0:14 long and fits the context of the pictures around it perfectly. Highlighted in blue.
![IMG_6916](https://github.com/user-attachments/assets/725de888-e2cd-4557-a0b6-d3d6c03e78b5)

When opening the video, no errors are written to the log so I'm not sure how to further expand on this from a troubleshooting perspective.

My wife's phone is a Pixel 7a with Immich 1.113.0 build 156
my phone is an IPhone 14 with Immich 1.113.0 build 171

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.113.0

### Version of Immich Mobile App

1.113.0 build 156

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    networks:
      - dockerlan
    ports:
      - 2283:3001
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - database

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - dockerlan
    volumes:
      - ${DOCKERPATH}/immich/model:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    networks:
      - dockerlan
    restart: always

  database:
    container_name: immich_postgres
    #image: tensorchord/pgvecto-rs:pg14-v0.1.11
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: always
    networks:
      - dockerlan
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DOCKERPATH}/immich/postgresql:/var/lib/postgresql/data
    labels:
      - "postgresql-backup"   

networks:
  dockerlan:
    external: true
```

### Your .env content

```Shell
DOCKERPATH=/mnt/user/appdata
CACHEPATH=/mnt/cache/appdata
TZ=Europe/Amsterdam
UPLOAD_LOCATION=/mnt/user/immich
IMMICH_VERSION=release
DB_PASSWORD=xxxx
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. unknown
2.
3.
...

### Relevant log output

```shell
None. Please support in additional sources of logging.
```
