### ISSUE TITLE
Storage template not respected for some items (album sync)

### ISSUE THREAD

**Issue by DrieWielRr** [immich-app/immich#12242]
### The bug

When I select a album to upload to the server it works great and starts uploading the content of the albums. 
I also see the albums being created within Immich but when I check the physical storage location on disk I see that some pictures are not being put in the correct folders.
On disk I only should be seeing the following testing folders:
   - Camera
   - WhatsApp Images
   - WhatsApp Video

But im seeing:
   - Camera
   - WhatsApp Images
   - WhatsApp Video
   - 2022
   - 2023
   - 2024

The total count of all folders is 4581 items, which matches what the app on my phone tells me but a number of items are not in the correct folder:
   - 2022, 1 item (all jpg)
   - 2023, 465 items (all jpg)
   - 2024, 222 items (all jpg)

Im using the following storage template "{{album}}/{{y}}/{{MM}}/{{assetId}}".

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

1.113.0 build.156

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: '3'
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    networks:
      macvlan_network:
        ipv4_address: 192.168.60.10
      internal:
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    networks:
      macvlan_network:
        ipv4_address: 192.168.60.11
      internal:
    volumes:
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 4000000000
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    networks:
      internal:
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      internal:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

networks:
  macvlan_network:
    name: macvlan_60
    external: true
  internal:
    internal: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/zpool-ssd/media/multimedia/library
DB_DATA_LOCATION=/zpool-ssd/docker-data/databases/immich-server/postgres
TZ=Europe/Amsterdam
IMMICH_VERSION=v1.113.0
DB_PASSWORD=somerandompassword
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_PORT=80
```

### Reproduction steps

1. Create  storage template with the following template "{{album}}/{{y}}/{{MM}}/{{assetId}}"
2. Sync album on mobile (in my case android)
3. Check storage location
