### ISSUE TITLE
Error: getaddrinfo ENOTFOUND redis

### ISSUE THREAD

**Issue by ilyaChuk** [immich-app/immich#12252]
### The bug

giant amount of 
```
immich_server            | Error: getaddrinfo ENOTFOUND redis
immich_server            |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
immich_server            |   errno: -3008,
immich_server            |   code: 'ENOTFOUND',
immich_server            |   syscall: 'getaddrinfo',
immich_server            |   hostname: 'redis'
immich_server            | }
```
an elusive problem. I had it 4 times in a row, but as soon as I reloaded the container while writing the issue, it was fixed.
```
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RoutesResolver] ViewController {/api/view}:
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:NestApplication] Nest application successfully started
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:3001 [v1.113.0] [PRODUCTION]
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM     LOG [Api:EventRepository] Websocket Connect:    8Kz09u2NJQObbJVcAAAB
immich_server            | [Nest] 17  - 09/03/2024, 12:07:13 AM   DEBUG [Api:EventRepository] Server event: websocket.connect (send)
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | missing 'error' handler on this Redis client
immich_server            | Error: getaddrinfo ENOTFOUND redis
immich_server            |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
immich_server            |   errno: -3008,
immich_server            |   code: 'ENOTFOUND',
immich_server            |   syscall: 'getaddrinfo',
immich_server            |   hostname: 'redis'
immich_server            | }
immich_server            | Error: getaddrinfo ENOTFOUND redis
immich_server            |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
immich_server            |   errno: -3008,
immich_server            |   code: 'ENOTFOUND',
immich_server            |   syscall: 'getaddrinfo',
immich_server            |   hostname: 'redis'
immich_server            | }
```
I noticed this error because my disks let me know. they were cracking from the heavy load. fatrace showed:
```
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2652
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2651
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2679
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2678
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2610
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/3455
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2663
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2662
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/1259
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/3081
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/3080
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/3079
unknown(1912043): CW  /home/pi/raid/immich/db/base/62235/2601
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/81399
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/63905
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/81373
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/63829
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/1247_vm
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2615_vm
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2704
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2703
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/1247
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2685
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2684
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2615
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2601_vm
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/1259_vm
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2610_vm
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2652
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2651
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2679
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2678
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2610
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/3455
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2663
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2662
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/1259
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/3081
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/3080
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/3079
postgres(1912055): CW  /home/pi/raid/immich/db/base/62235/2601
postgres(1912037): CW  /home/pi/raid/immich/db/base/62235/81399
postgres(1912037): CW  /home/pi/raid/immich/db/base/62235/63905
postgres(1912037): CW  /home/pi/raid/immich/db/base/62235/2601
postgres(1912042): CW  /home/pi/raid/immich/db/base/62235/81399
postgres(1912042): CW  /home/pi/raid/immich/db/base/62235/63905
postgres(1912042): CW  /home/pi/raid/immich/db/base/62235/2601
runc:[2:INIT](1912425): C   /home/pi/raid/immich/lib
postgres(1915254): O   /home/pi/raid/immich/db/base/62235/2610_vm
postgres(1915254): O   /home/pi/raid/immich/db/base/62235/1259_vm
postgres(1915254): O   /home/pi/raid/immich/db/base/62235/2601_vm
postgres(1909830): RO  /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing
postgres(1909830): RCO /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing/raw
postgres(1909830): R   /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing
postgres(1909830): C   /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing
postgres(1909830): O   /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing
postgres(1909830): R   /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing
postgres(1909830): RO  /home/pi/raid/immich/db/pg_vectors/indexes/81450/segments/c3f550a1-9076-4c29-ba14-98d783a705d3/indexing/raw
```
(infinite)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.113.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.9'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      REDIS_HOST: 172.30.0.2
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.30.0.3

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.30.0.4

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.30.0.2

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      immich_network:
        ipv4_address: 172.30.0.5

networks:
  immich_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/pi/raid/immich/lib
DB_DATA_LOCATION=/home/pi/raid/immich/db

IMMICH_VERSION=release

DB_PASSWORD=------

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

cant.. in the evening, I took a couple of photos on my smartphone, and after a couple of hours postgresql started working hard with disks.
