### ISSUE TITLE
Android date slider disappears

### ISSUE THREAD

**Issue by ScubyG** [immich-app/immich#12333]
### The bug

On the main screen the slider bar dissappears past the visible area when scrolling down to the bottom.

### The OS that Immich Server is running on

Alpine Linux (Docker)

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

v1.113.1 Build 2157

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
container_name: immich_server
image: ghcr.io/immich-app/immich-server:${IMMICH_VER>
command: [ "start.sh", "immich" ]
volumes:
- ${UPLOAD_LOCATION}:/usr/src/app/upload
#- /etc/localtime:/etc/localtime:ro
env_file:
- .env
ports:
- 2283:3001
depends_on:
- redis
- database
restart: always

  immich-microservices:
container_name: immich_microservices
image: ghcr.io/immich-app/immich-server:${IMMICH_VER>
command: [ "start.sh", "microservices" ]
volumes:
- ${UPLOAD_LOCATION}:/usr/src/app/upload
#- /etc/localtime:/etc/localtime:ro
env_file:
- .env
depends_on:
- redis
- database
restart: always

  immich-machine-learning:
container_name: immich_machine_learning
image: ghcr.io/immich-app/immich-machine-learning:${>
```

### Your .env content

```Shell
UPLOAD_LOCATION=/root/media
TZ=Europe/London
IMMICH_VERSION=release
DB_PASSWORD={Redacted}
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open app
2. Scroll photos to bottom

### Relevant log output

```shell
No error logs
```

### Additional information

GrapheneOS Pixel 6 Pro

PHOTOS
0000000071403
VIDEOS
0000000002504
STORAGE SPACE
0000000000405
