### ISSUE TITLE
Tags not removed when they are removed from image externally

### ISSUE THREAD

**Issue by ronbruins** [immich-app/immich#12338]
### The bug

When a tag is removed from an external library asset, with e.g. exiftool or digikam, the tag is not removed in image. Not after metadata scan nor a refresh metadata on the asset itself.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.113.1

### Version of Immich Mobile App

v1.113.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume1/docker/compose_files/mbpro/immich/mbpro/config:/usr/src/app/config
      - /etc/localtime:/etc/localtime:ro
      - photo:/mnt/media/photo:rw
      - homes:/mnt/media/homes:rw
      - /volume2/docker/immich/debug_lib:/mnt/media/debug_lib:rw
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
      #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      #file: hwaccel.ml.yml
      #service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      #- C:\Users\Bruins\docker\immich\model-cache:/cache
      - /volume1/docker_local/immich/model-cache:/cache
    ports:
      - 3003:3003
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    ports:
      - 6379:6379
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      #- C:\Users\Bruins\docker\immich\database:/var/lib/postgresql/data
      - /volume1/docker_local/immich/database:/var/lib/postgresql/data
    restart: always

volumes:
  photo:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.35,nfsvers=4,nolock,soft,rw"
      device: ":/volume1/photo"
  homes:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.35,nfsvers=4,nolock,soft,rw"
      device: ":/volume1/homes"
```

### Your .env content

```Shell
# The location where your uploaded files are stored
#UPLOAD_LOCATION=C:\Users\Bruins\docker\immich\library
UPLOAD_LOCATION=/volume3/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_LOG_LEVEL=verbose
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
TZ=Europe/Amsterdam

IMMICH_CONFIG_FILE=/usr/src/app/config/mbpro_config.json
```

### Reproduction steps

1.remove all tags from an image (exiftool, digicam)
2.rerun extract metadata (or refresh meta on asset(s))
3. tag is still seen in immich

When a new tag is added the others are removed:
1.add new tag to image
2.rerun extract metadata (or refresh meta on asset(s))
3. new tag is seen, old tags are gone
...
