### ISSUE TITLE
Unable to run job handler (smartSearch/smart-search)

### ISSUE THREAD

**Issue by xiagw** [immich-app/immich#12430]
### The bug

immich_server            | [Nest] 17  - 09/07/2024, 10:04:08 AM   ERROR [Api:ErrorInterceptor~8s833zhn] Unknown error: Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

1.113.1 

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis                                                                                                                                                                                            - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    ports:
      - 6379:6379

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers
=512MB", "-c", "wal_compression=on"]
    ports:
      - 5432:5432
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=pg01

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=pg01
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. search context on text
2. error
3. no result 
...

### Relevant log output

```shell
immich_machine_learning  | [09/07/24 10:02:11] ERROR    Worker (pid:7838) was sent code 139!
immich_machine_learning  | [09/07/24 10:02:11] INFO     Booting worker with pid: 7862
immich_machine_learning  | [09/07/24 10:02:14] INFO     Started server process [7862]
immich_machine_learning  | [09/07/24 10:02:14] INFO     Waiting for application startup.
immich_machine_learning  | [09/07/24 10:02:14] INFO     Created in-memory cache with unloading after 300s
immich_machine_learning  |                              of inactivity.
immich_machine_learning  | [09/07/24 10:02:14] INFO     Initialized request thread pool with 8 threads.
immich_machine_learning  | [09/07/24 10:02:14] INFO     Application startup complete.
immich_machine_learning  | [09/07/24 10:02:14] INFO     Loading visual model 'XLM-Roberta-Large-Vit-L-14'
immich_machine_learning  |                              to memory
immich_machine_learning  | [09/07/24 10:02:14] INFO     Setting execution providers to
immich_machine_learning  |                              ['CUDAExecutionProvider', 'CPUExecutionProvider'],
immich_machine_learning  |                              in descending order of preference
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     |     at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
immich_microservices     |     at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
immich_microservices     |     at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
immich_microservices     |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:132:27)
immich_microservices     |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "f7f66dcb-d92e-4063-80d1-bab0e3ef4a86"
immich_microservices     | }
immich_microservices     |
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     |     at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
immich_microservices     |     at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
immich_microservices     |     at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:42:26)
immich_microservices     |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:132:27)
immich_microservices     |     at async /usr/src/app/dist/services/job.service.js:148:36
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 09/07/2024, 10:02:15 AM   ERROR [Microservices:JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "3bd1f6ba-23db-4328-99c3-21f9fbe8aa4d"
immich_microservices     | }
immich_microservices     |
```

### Additional information

no
