### ISSUE TITLE
Mispositioned imported face regions and missing person thumbnails

### ISSUE THREAD

**Issue by wonx** [immich-app/immich#12440]
### The bug

Yesterday I tested the recently implemented face import feature (this is something I had been waiting for a long time, thanks!), but I noticed some issues. Some face regions appear to be misplaced, so, when you hover over the person's thumbnail in the info sidebar, the face rectangle does not correspond to the person's face. In my case, These faces were tagged in Digikam (and in some cases, in Picasa).
![Untitled](https://github.com/user-attachments/assets/21e854c1-f4b3-43b6-93cd-bb0a74a74ab9)

Moreover, face thumbnails from these pictures are not generated, and the affected person won't appear in the People sidebar.
![Captura](https://github.com/user-attachments/assets/6a630d0d-e382-4219-b937-c36503af4e57)

Seems to particularly affect photos taken from iPhones (mostly vertical pictures), although I'm not certain if it affects other devices as well.

I've seen that behavior before. Digikam also had this bug in the past: https://bugs.kde.org/show_bug.cgi?id=372340
And same for pigallery2: https://github.com/bpatrik/pigallery2/issues/515

I can provide picture samples if needed, although I'd prefer to do that in private.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

1.113.1 build.157

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/md0/Media/Fotos:/Biblioteques/Fotos:ro
      - /mnt/md0/Personal/Marc/Fotos:/Biblioteques/Fotos Marc:ro
      - /mnt/md0/mountpoints/shared_with_marc:/Biblioteques/Fotos Nextcloud Shared Marc:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/opt/appdata/immich/library
DB_DATA_LOCATION=/opt/appdata/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upgraded immich to version v1.114.0
2. Re-imported metadata (Administration, Jobs, Extract Metadata, All)
3. Wait for the import to end.
4. Open pictures with people faces.
...
