### ISSUE TITLE
Many photos and videos showing "Error Loading Image"

### ISSUE THREAD

**Issue by elmuziko** [immich-app/immich#12472]
### The bug

Several of my photos now show Error Loading Image as a thumbnail from the desktop version. When I click the photo/video, it loads without issue. On my (iOS) mobile app I have an exclamation mark. If the item is a video it will play without issue, if a photo I get a file type image with a line through it.

Desktop: 
![image](https://github.com/user-attachments/assets/d0ce7bb2-1423-44ef-9ebb-4c904d1863cb)

Mobile:
![20240908_133953000_iOS](https://github.com/user-attachments/assets/52ae5663-9083-4476-a34d-12e7b4e0235d)

You'll have to forgive me if the docker-compose.yml content isn't exactly what you're after. I'm on unraid which doesn't use it out of the box. I got this using `docker inspect <ID>`

### The OS that Immich Server is running on

Unraid 6.12.10

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

1.113.1 build 172

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
[
    {
        "Id": "ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749",
        "Created": "2024-09-07T16:11:31.852064468Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 28715,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-09-08T03:48:51.684742989Z",
            "FinishedAt": "2024-09-08T03:48:21.51314524Z"
        },
        "Image": "sha256:d4a9962003b2831f84171e215c3c499b79fba1cb26bfcb764beb0f2c0486a9cf",
        "ResolvConfPath": "/var/lib/docker/containers/ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749/hostname",
        "HostsPath": "/var/lib/docker/containers/ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749/hosts",
        "LogPath": "/var/lib/docker/containers/ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749/ae47b54025a37155cb76141c29c15ccaad2b5e71409b583098dfbbdced07a749-json.log",
        "Name": "/immich",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/mnt/user/Photos/Immich/:/photos:rw",
                "/mnt/user/Photos/Photos/:/import:ro",
                "/mnt/user/appdata/immich:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {
                    "max-file": "1",
                    "max-size": "50m"
                }
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8086"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": [],
            "BlkioDeviceWriteBps": [],
            "BlkioDeviceReadIOps": [],
            "BlkioDeviceWriteIOps": [],
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/user/Photos/Photos",
                "Destination": "/import",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/appdata/immich",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "f38f13086ea7faad64cffa99f3f04af936b3db0442e1fd8510f7dbf71947a830",
                "Source": "/var/lib/docker/volumes/f38f13086ea7faad64cffa99f3f04af936b3db0442e1fd8510f7dbf71947a830/_data",
                "Destination": "/libraries",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/user/Photos/Immich",
                "Destination": "/photos",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "ae47b54025a3",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "MACHINE_LEARNING_WORKERS=1",
                "MACHINE_LEARNING_WORKER_TIMEOUT=120",
                "PUID=99",
                "PGID=100",
                "UMASK=022",
                "REDIS_PASSWORD=REMOVED",
                "HOST_HOSTNAME=Tower",
                "HOST_CONTAINERNAME=immich",
                "DB_HOSTNAME=192.168.4.26",
                "DB_USERNAME=REMOVED",
                "DB_PORT=5433",
                "REDIS_PORT=6379",
                "MACHINE_LEARNING_GPU_ACCELERATION=",
                "TZ=Europe/London",
                "DB_DATABASE_NAME=REMOVED",
                "DB_PASSWORD=REMOVED",
                "REDIS_HOSTNAME=192.168.4.26",
                "HOST_OS=Unraid",
                "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
                "S6_VERBOSITY=1",
                "S6_STAGE2_HOOK=/docker-mods",
                "VIRTUAL_ENV=/lsiopy",
                "IMMICH_BUILD_DATA=/app/immich/server",
                "IMMICH_ENV=production",
                "IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003",
                "IMMICH_MEDIA_LOCATION=/photos",
                "IMMICH_PORT=8080",
                "MACHINE_LEARNING_CACHE_FOLDER=/config/machine-learning/models",
                "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
                "TRANSFORMERS_CACHE=/config/machine-learning/models",
                "NODE_ENV=production"
            ],
            "Cmd": null,
            "Image": "ghcr.io/imagegenius/immich",
            "Volumes": {
                "/config": {},
                "/libraries": {}
            },
            "WorkingDir": "/",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "build_version": "ImageGenius Version:- v1.114.0-ig323 Build-date:- 2024-09-07T01:00:07+10:00",
                "maintainer": "hydazz, martabal",
                "net.unraid.docker.icon": "https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png",
                "net.unraid.docker.managed": "dockerman",
                "net.unraid.docker.webui": "http://[IP]:[PORT:8080]",
                "org.opencontainers.image.authors": "imagegenius.io",
                "org.opencontainers.image.created": "2024-09-07T01:00:07+10:00",
                "org.opencontainers.image.description": "Immich is a high performance self-hosted photo and video backup solution.",
                "org.opencontainers.image.documentation": "https://docs.linuxserver.io/images/docker-baseimage-ubuntu",
                "org.opencontainers.image.licenses": "GPL-3.0-only",
                "org.opencontainers.image.ref.name": "ebfadeedba5497e5ddb49bcfb3d0ab1548fec4f6",
                "org.opencontainers.image.revision": "ebfadeedba5497e5ddb49bcfb3d0ab1548fec4f6",
                "org.opencontainers.image.source": "https://github.com/imagegenius/docker-immich",
                "org.opencontainers.image.title": "Immich",
                "org.opencontainers.image.url": "https://github.com/imagegenius/docker-immich/packages",
                "org.opencontainers.image.vendor": "imagegenius.io",
                "org.opencontainers.image.version": "v1.114.0-ig323"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ee8b9d4eea8f1a52ab1310462b40865d7b047ab2af35c83e95506efaddd13f33",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8086"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "8086"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/ee8b9d4eea8f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "25ee0506fa225da22c745fd1399b060d68e63eeeba737aa7e335d2450451188d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "468009c5af8e88f33ae71a4f4159d497bc05684ab902230deb83f4e4bccd65d3",
                    "EndpointID": "25ee0506fa225da22c745fd1399b060d68e63eeeba737aa7e335d2450451188d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

### Your .env content

```Shell
"Env": [
                "MACHINE_LEARNING_WORKERS=1",
                "MACHINE_LEARNING_WORKER_TIMEOUT=120",
                "PUID=99",
                "PGID=100",
                "UMASK=022",
                "REDIS_PASSWORD=REMOVED",
                "HOST_HOSTNAME=Tower",
                "HOST_CONTAINERNAME=immich",
                "DB_HOSTNAME=192.168.4.26",
                "DB_USERNAME=REMOVED",
                "DB_PORT=5433",
                "REDIS_PORT=6379",
                "MACHINE_LEARNING_GPU_ACCELERATION=",
                "TZ=Europe/London",
                "DB_DATABASE_NAME=REMOVED",
                "DB_PASSWORD=REMOVED",
                "REDIS_HOSTNAME=192.168.4.26",
                "HOST_OS=Unraid",
                "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "HOME=/root",
                "LANGUAGE=en_US.UTF-8",
                "LANG=en_US.UTF-8",
                "TERM=xterm",
                "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0",
                "S6_VERBOSITY=1",
                "S6_STAGE2_HOOK=/docker-mods",
                "VIRTUAL_ENV=/lsiopy",
                "IMMICH_BUILD_DATA=/app/immich/server",
                "IMMICH_ENV=production",
                "IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003",
                "IMMICH_MEDIA_LOCATION=/photos",
                "IMMICH_PORT=8080",
                "MACHINE_LEARNING_CACHE_FOLDER=/config/machine-learning/models",
                "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility",
                "TRANSFORMERS_CACHE=/config/machine-learning/models",
                "NODE_ENV=production"
            ],
```

### Reproduction steps

1. Updated to v1.114.0
2. Added new photos, most of which would not load so removed, re-added, and same issue.
3. Ran Thumbnail generation job, countless older photos suddenly dropped off.
...

### Additional information

Following a few other discussions surrounding this matter, I have tried switching from WEBP to JPG, which did nothing, then converted back. I pushed my docker image back to v1.112.1 but that did far more damage than good so restored.
I have a second unraid server I use to back everything up. This is vanilla in that its only use is to be a carbon copy of my main server. This too has inherited this issue meaning messing around with thumbnails and downgrading docker have not caused the problem.
