### ISSUE TITLE
Scrolling up on web causes spurious jumps

### ISSUE THREAD

**Issue by iqapps** [immich-app/immich#12499]
### The bug

Have a long uneven timeline 1978-today and 10000+ images. When in he middle of this, and scrolling slowly up, at some point, the page jumps any number of images up, skipping the view of a handfull images, I guess its when the page need to cache another set from the timeline. This happens again and again with intervals.

### The OS that Immich Server is running on

Synology container

### Version of Immich Server

1.114.0

### Version of Immich Mobile App

1.114.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=Europe/Copenhagen
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg15-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "***", "-U", "***"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: 1026:100
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Copenhagen
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 2283:3001
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started


  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Europe/Copenhagen
TYPESENSE_API_KEY=***
DB_HOSTNAME=immich-db
DB_USERNAME=***
DB_PASSWORD=***
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=warn
JWT_SECRET=***=
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Open web to immich in std. view
2. Use timeline to jump to somewhere in middle of timeline
3. Use mousewheel to scroll up, keep scrolling up
4. At some point, the webpage suddenly refresh and shows images from a newer point in timeline.
5. Immich seems to have lost control of where on the timeline it actually is and refreshing makes a jump.
