### ISSUE TITLE
Ios iphone 13 pro - front camera photos (mostly)

### ISSUE THREAD

**Issue by krypton9208** [immich-app/immich#12501]
### The bug

Almost all photos take by front camera (live photos) was't correctly uploded,
Mobile app upload video, by image wasn't uploaded.

### The OS that Immich Server is running on

helm

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
configuration:
    ffmpeg:
      crf: 23
      threads: 0
      preset: ultrafast
      targetVideoCodec: h264
      acceptedVideoCodecs:
        - h264
      targetAudioCodec: aac
      acceptedAudioCodecs:
        - aac
        - mp3
        - libopus
      targetResolution: '720'
      maxBitrate: '4500k'
      bframes: -1
      refs: 0
      gopSize: 0
      npl: 0
      temporalAQ: false
      cqMode: auto
      twoPass: true
      preferredHwDevice: auto
      transcode: required
      tonemap: hable
      accel: disabled
    job:
      backgroundTask:
        concurrency: 5
      smartSearch:
        concurrency: 2
      metadataExtraction:
        concurrency: 5
      faceDetection:
        concurrency: 2
      search:
        concurrency: 5
      sidecar:
        concurrency: 5
      library:
        concurrency: 5
      migration:
        concurrency: 5
      thumbnailGeneration:
        concurrency: 10
      videoConversion:
        concurrency: 3
    logging:
      enabled: true
      level: log
    machineLearning:
      enabled: true
      url: http://immich-machine-learning:3003
      clip:
        enabled: true
        modelName: ViT-B-32__openai
      facialRecognition:
        enabled: true
        modelName: buffalo_l
        minScore: 0.7
        maxDistance: 0.6
        minFaces: 3
    map:
      enabled: true
      lightStyle: ''
      darkStyle: ''
    reverseGeocoding:
      enabled: true
    oauth:
      enabled: false
      issuerUrl: ''
      clientId: ''
      clientSecret: ''
      scope: openid email profile
      signingAlgorithm: RS256
      storageLabelClaim: preferred_username
      storageQuotaClaim: immich_quota
      defaultStorageQuota: 0
      buttonText: Login with OAuth
      autoRegister: true
      autoLaunch: false
      mobileOverrideEnabled: false
      mobileRedirectUri: ''
    passwordLogin:
      enabled: true
    storageTemplate:
      enabled: false
      hashVerificationEnabled: true
      template: "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
    image:
      thumbnailFormat: webp
      thumbnailSize: 250
      previewFormat: jpeg
      previewSize: 1440
      quality: 80
      colorspace: p3
      extractEmbedded: false
    newVersionCheck:
      enabled: true
    notifications:
      smtp:
        enabled: true
        from: 'Immich Photo Server hidden'
        replyTo: 'hidden'
        transport:
          ignoreCert: false
          host: 'smtp.sendgrid.net'
          port: 465
          username: 'apikey'
          password: 'hidden'
    trash:
      enabled: true
      days: 30
    theme:
      customCss: ''
    user:
      deleteDelay: 7
    library:
      scan:
        enabled: true
        cronExpression: 0 0 * * *
      watch:
        enabled: true
    server:
      externalDomain: 'https://hidden'
```

### Your .env content

```Shell
REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
  TZ: "Poland"
```

### Reproduction steps

1. Take selfie with live fotos
2. Open app to backup it
3. App finish backup
4. Only video from live photo is saved, photo was't uploaded
