### ISSUE TITLE
[Android APP] Download button disappears when selecting multiple images

### ISSUE THREAD

**Issue by DrieWielRr** [immich-app/immich#12554]
### The bug

When selecting multiple images there is no way to download the selected images to the phone, the regular download button that shows on the top right is nowhere to be found.
I can still go with "share with" and send it to whatsapp or something but downloading the images from the server straight to the phone storage is not possible.

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.113.0

### Version of Immich Mobile App

1.113.0 build.156

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# Debug container use "entrypoint: ["sh", "-c", "sleep 2073600"]"

version: '3'
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    networks:
      macvlan_network:
        ipv4_address: 192.168.60.10
      internal:
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    networks:
      macvlan_network:
        ipv4_address: 192.168.60.11
      internal:
    volumes:
      - type: tmpfs
        target: /cache
        tmpfs:
          size: 4000000000
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    networks:
      internal:
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      internal:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - stack.env
    networks:
      internal:
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "30 */6 * * *"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - /zpool-ssd/docker-data/databases/immich-server/db_dumps:/db_dumps
    depends_on:
      - database

networks:
  macvlan_network:
    name: macvlan_60
    external: true
  internal:
    internal: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/zpool-ssd/media/multimedia/library
DB_DATA_LOCATION=/zpool-ssd/docker-data/databases/immich-server/postgres
TZ=Europe/Amsterdam
IMMICH_VERSION=v1.113.0
DB_PASSWORD=somerandompassword
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_PORT=80
```

### Reproduction steps

1. open mobile app
2. go in to an album
3. select multiple images
4. try to download those (not possible)
