### ISSUE TITLE
Android error when updating person name

### ISSUE THREAD

**Issue by KasiBurnsRed** [immich-app/immich#12579]
### The bug

When updating a person name an error occurs. "

### The OS that Immich Server is running on

Debian

### Version of Immich Server

V1.114.0

### Version of Immich Mobile App

V1.114.0 build 158

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

      - /mnt/host/synophotos:/mnt/synophotos
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    environment:
      UPLOAD_LOCATION: $UPLOAD_LOCATION
      DB_DATA_LOCATION: $DB_DATA_LOCATION
      IMMICH_VERSION: $IMMICH_VERSION
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    networks:
      immichnetwork:
      
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    environment:
      UPLOAD_LOCATION: $UPLOAD_LOCATION
      DB_DATA_LOCATION: $DB_DATA_LOCATION
      IMMICH_VERSION: $IMMICH_VERSION
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    networks:
      immichnetwork:
      
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    environment:
      UPLOAD_LOCATION: $UPLOAD_LOCATION
      DB_DATA_LOCATION: $DB_DATA_LOCATION
      IMMICH_VERSION: $IMMICH_VERSION
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    networks:
      immichnetwork:

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'

      UPLOAD_LOCATION: $UPLOAD_LOCATION
      DB_DATA_LOCATION: $DB_DATA_LOCATION
      IMMICH_VERSION: $IMMICH_VERSION
      DB_PASSWORD: $DB_PASSWORD
      DB_USERNAME: $DB_USERNAME
      DB_DATABASE_NAME: $DB_DATABASE_NAME
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
     immichnetwork:

volumes:
  model-cache:

networks:
 immichnetwork:
  external: true
  name: immichnetwork
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/host/immichphotos/Immich
DB_DATA_LOCATION=/immich_db/db3
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.open android app
2. Click on search icon
3. Choose any person
4. Edit name
5. Click save

### Relevant log output

```shell
Message:
Error while updating person name

Details:
Null check operator used on a null value

From:
Person Service

Stack Trace:
#0      PersonResponseDto.fromJson (package:openapi/model/person_response_dto.dart:94)
#1      ApiClient.fromJson (package:openapi/api_client.dart:423)
#2      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#3      PeopleApi.updatePerson (package:openapi/api/people_api.dart:541)
<asynchronous suspension>
#4      PersonService.updateName (package:immich_mobile/services/person.service.dart:72)
<asynchronous suspension>
#5      updatePersonName (package:immich_mobile/providers/search/people.provider.dart:39)
<asynchronous suspension>
#6      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>
```
