### ISSUE TITLE
Apple ProRaw (.DNG) thumbnails are way too dark when viewed by a browser after importing photograph

### ISSUE THREAD

**Issue by bradpedersen** [immich-app/immich#12600]
### The bug

The thumbnails of ProRaw (.DNG) photographs taken with an iPhone 15 Pro appear way too dark when viewed with either the Chrome or Edge browser on Windows 11 or Safari on the iPhone.    They appear correct when viewed using the Immich iPhone mobile application.

### The OS that Immich Server is running on

as a docker container on UNRAID 6.12.13

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.114.0 build.173

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/backup/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1.  Take either a ProRAW or ProRAW Max photograph on a iPhone 15 Pro
2.  Import the photograph using the immich iPhone mobile application
3. View the photograph using the immich iPhone mobile application (the photograph thumbnail appears normal)
4. View the photograph using Safari on the iPhone (the photograph thumbnail appears too dark)
5. View the photograph using either Chrome or Edge on Windows (the photograph thumbnail appears too dark)
