### ISSUE TITLE
Incorrect persons displayed for images with similar filenames

### ISSUE THREAD

**Issue by yuks** [immich-app/immich#12668]
### The bug

When opening an image in Immich, incorrect persons are displayed. This issue does not occur with every image but appears to be linked to images whose filenames begin with the same string. Specifically, the incorrect persons displayed belong to another image that has a similar filename.

For example, in my Immich library, I have `IMG_6952_1.JPG` and `IMG_6952.HEIC`. The image `IMG_6952_1.JPG` was added first, and `IMG_6952.HEIC` was added a couple of months later. Now, I see the persons from `IMG_6952_1.JPG` shown for `IMG_6952.HEIC`. I am using only external libraries, so I am unsure if this issue also occurs with internal libraries.

I have attached an example screenshot to illustrate the issue. I have many images like this.

Thank you for creating such a nice project!

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-119-generic x86_64)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - 2283:3001
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/hddusb1/filebrowser/data/Photos:/media/hddusb1/filebrowser/data/Photos:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PG_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/hddusb1/immich/uploads
PG_DATA_LOCATION=/home/xxx/immich/pgdata

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=XXX
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1.
2.
3.
...
