### ISSUE TITLE
immich_server fails to start after upgrading to 1.115

### ISSUE THREAD

**Issue by indam** [immich-app/immich#12664]
### The bug

I run Immich on Raspberry Pi 4B. Try to upgrade the server from v1.114.0 to v1.115.0. immich_server container keeps restarting. I try to clean all the image, and re-pull the v1.115.0 version, still have same problem. Please help, Thank you.

### The OS that Immich Server is running on

Debian GNU/Linux 10 (buster)   Linux i 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
$ cat docker-compose.yml
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/station/Photos/Outputs/2024:/import/camera2024:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      #POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    #command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]


volumes:
  pgdata:
  model-cache:

networks:
  default:
    external:
      name: swag
```

### Your .env content

```Shell
$ cat .env
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
#DB_HOSTNAME=immich_postgres
DB_USERNAME=pi_immich
DB_PASSWORD=postgres_immich
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

TZ=Asia/Shanghai

DB_DATA_LOCATION=/media/entertainment/docker-files/immich/pgdata

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/station/Photos/immich_upload


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

#IMMICH_WEB_URL=http://immich-web:3000
#IMMICH_SERVER_URL=http://immich-server:3001
#IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=pr-3512
IMMICH_VERSION=release
```

### Reproduction steps

1. docker-compose pull 
2. docker-compose up -d 
3. Then, you can see immich-server restarting in docker ps
...

### Relevant log output

```shell
$ docker logs -f 44f0b8740880
Detected CPU Cores: 4

  #  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xca4664 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd19844 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd19900 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc5e828  [node]
 5: 0xc5f9dc node::Start(int, char**) [node]
 6: 0x7facbf229c  [/lib/aarch64-linux-gnu/libc.so.6]
 7: 0x7facbf2370 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0xbbde20  [node]
Detected CPU Cores: 4

  #  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xca4664 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd19844 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd19900 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc5e828  [node]
 5: 0xc5f9dc node::Start(int, char**) [node]
 6: 0x7fb016229c  [/lib/aarch64-linux-gnu/libc.so.6]
 7: 0x7fb0162370 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0xbbde20  [node]
Detected CPU Cores: 4

  #  node[8]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xca4664 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd19844 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd19900 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc5e828  [node]
 5: 0xc5f9dc node::Start(int, char**) [node]
 6: 0x7f9440229c  [/lib/aarch64-linux-gnu/libc.so.6]
 7: 0x7f94402370 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0xbbde20  [node]
Detected CPU Cores: 4

  #  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xca4664 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd19844 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd19900 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc5e828  [node]
 5: 0xc5f9dc node::Start(int, char**) [node]
 6: 0x7fb5cd229c  [/lib/aarch64-linux-gnu/libc.so.6]
 7: 0x7fb5cd2370 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0xbbde20  [node]
Detected CPU Cores: 4

  #  node[8]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xca4664 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd19844 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd19900 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc5e828  [node]
 5: 0xc5f9dc node::Start(int, char**) [node]
 6: 0x7f870d229c  [/lib/aarch64-linux-gnu/libc.so.6]
 7: 0x7f870d2370 __libc_start_main [/lib/aarch64-linux-gnu/libc.so.6]
 8: 0xbbde20  [node]
```
