### ISSUE TITLE
Failed to upload asset - Unknown system error -74

### ISSUE THREAD

**Issue by sidyes** [immich-app/immich#12669]
### The bug

When uploading images/media from my Android phone via the immich app, the upload is getting stuck after a few images. 
Sometimes I see the failed upload and it continues again until it gets stuck again.

Im running Immich on a Raspberry PI 4 with the upload location on a mounted external SSD drive (`/mnt/immich`). It seems that it is very slow and gets stuck. The longer I try the upload the ealier my filesystem is completely broken and I have to format the drive again.

The error that is coming up for failed uploads can be seen in the error logs. What can I do?

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<pw>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Synchronize images/albums on Android app with immich server
2. it randomly fails at some point with the given error
3. Stopping and starting the job starts the same procedure again (a few work, a few dont)
...

### Relevant log output

```shell
[Nest] 7  - 09/14/2024, 11:37:30 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-preview): Error: Unknown system error -74: Unknown system error -74, mkdir 'upload/thumbs/6818250b-370e-4543-9b2a-930223ac54dc/72/35'
[Nest] 7  - 09/14/2024, 11:37:30 AM   ERROR [Microservices:JobService] Error: Unknown system error -74: Unknown system error -74, mkdir 'upload/thumbs/6818250b-370e-4543-9b2a-930223ac54dc/72/35'
    at mkdirSync (node:fs:1372:26)
    at StorageRepository.mkdirSync (/usr/src/app/dist/repositories/storage.repository.js:125:37)
    at StorageCore.ensureFolders (/usr/src/app/dist/cores/storage.core.js:202:32)
    at MediaService.generateThumbnail (/usr/src/app/dist/services/media.service.js:159:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MediaService.handleGeneratePreview (/usr/src/app/dist/services/media.service.js:141:29)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 09/14/2024, 11:37:30 AM   ERROR [Microservices:JobService] Object:
{
  "id": "7235aae9-f48e-45cc-9f1a-f568eee3dcf1",
  "source": "upload"
}

[Nest] 17  - 09/14/2024, 11:37:30 AM   ERROR [Api:ErrorInterceptor~4gpmjxxu] Unknown error: Error: Unknown system error -74: Unknown system error -74, mkdir 'upload/upload/6818250b-370e-4543-9b2a-930223ac54dc/5b/cb'
[Nest] 17  - 09/14/2024, 11:37:30 AM   DEBUG [Api:LoggingInterceptor~4gpmjxxu] POST /api/assets 201 23.41ms ::ffff:192.168.178.35
[Nest] 17  - 09/14/2024, 11:37:30 AM   DEBUG [Api:GlobalExceptionFilter~4gpmjxxu] HttpException(500): {"message":"Failed to upload asset","error":"Internal Server Error","statusCode":500}
```

### Additional information

It seems that the `mkdir` command randomly fails. Any idea why or what I could do? I have used an USB drive before and thought that it might be too slow which is why I switched to an external SSD drive but it is the same issue.
