### ISSUE TITLE
The ios app cannot connect to the server

### ISSUE THREAD

**Issue by Desirrry** [immich-app/immich#12671]
### The bug

When I upgraded the server, I found that the ios app could not be connected. After I logged it out, I still could not reconnect. Normal connection could be made on the ios browser.
The link for the ios app is http://xxxxx:2283/api
The ip address, account number, and password are correct
And the ipad connected successfully after not logging out for a while

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.107.2

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      UPLOAD_LOCATION: './library'
      DB_DATA_LOCATION: './postgres'
      TZ: 'Asia/Shanghai'
      IMMICH_VERSION: 'release'
      DB_PASSWORD: ''
      DB_USERNAME: 'postgres'
      DB_DATABASE_NAME: 'immich'
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    environment:
      UPLOAD_LOCATION: './library'
      DB_DATA_LOCATION: './postgres'
      TZ: 'Asia/Shanghai'
      IMMICH_VERSION: 'release'
      DB_PASSWORD: ''
      DB_USERNAME: ''
      DB_DATABASE_NAME: 'immich'
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      UPLOAD_LOCATION: './library'
      DB_DATA_LOCATION: './postgres'
      TZ: 'Asia/Shanghai'
      IMMICH_VERSION: 'release'
      DB_PASSWORD: ''
      DB_USERNAME: ''
      DB_DATABASE_NAME: 'immich'
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.退出后重新连接无法连接
2.
3.
...
