### ISSUE TITLE
Mobile App Sync Issue: two thumbnails for the same asset - one shown as remote only and one shown as local with no backup

### ISSUE THREAD

**Issue by MrColumbo** [immich-app/immich#12693]
### The bug

Since a long time i sometimes see some assets twice in the mobile app (see screenshot).
 
![immich sync issue](https://github.com/user-attachments/assets/81c4f730-0251-4648-bb05-61f7526fe4f0)

One asset shows as remote only and the other one as local and it is not possible to do a backup of that local one - well - in fact it is already backed up but it is not linked to the backed up asset

Here are the details from the mobile app from the 2 assets 

{
  "id": 155348,
  "remoteId": "N/A",
  "localId": "1000043592",
  "checksum": "XitsjGjEMnRpF2Z2gUw8FzucTm4=",
  "ownerId": -990403609085095454,
  "livePhotoVideoId": "N/A",
  "stackId": "N/A",
  "stackPrimaryAssetId": "N/A",
  "stackCount": "0",
  "fileCreatedAt": "2024-09-13 17:32:13.000",
  "fileModifiedAt": "2024-09-13 17:32:13.000",
  "updatedAt": "2024-09-13 17:32:13.000",
  "durationInSeconds": 10,
  "type": "AssetType.video",
  "fileName": "PXL_20240913_153156753.TS.mp4",
  "isFavorite": false,
  "isRemote": false,
  "storage": "AssetState.local",
  "width": 1920,
  "height": 1080,
  "isArchived": false,
  "isTrashed": false,
  "isOffline": false,
}

{
  "id": 155398,
  "remoteId": "fb79d634-1add-48e0-85df-686626ae795b",
  "localId": "N/A",
  "checksum": "db/nOxVNReJqtU9YAW7g6TSyx78=",
  "ownerId": -990403609085095454,
  "livePhotoVideoId": "N/A",
  "stackId": "N/A",
  "stackPrimaryAssetId": "N/A",
  "stackCount": "0",
  "fileCreatedAt": "2024-09-13 17:32:13.000",
  "fileModifiedAt": "2024-09-13 17:32:13.000",
  "updatedAt": "2024-09-15 10:10:19.659",
  "durationInSeconds": 10,
  "type": "AssetType.video",
  "fileName": "PXL_20240913_153156753.TS.mp4",
  "isFavorite": false,
  "isRemote": true,
  "storage": "AssetState.remote",
  "width": 1920,
  "height": 1080,
  "isArchived": false,
  "isTrashed": false,
  "isOffline": false,
}

### The OS that Immich Server is running on

Alpine LXC on Proxmox

### Version of Immich Server

v1.115.0 build 159

### Version of Immich Mobile App

v1.115.0 

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /fileshare/Bilder:/mnt/media/Bilder:ro
      - /fileshare/BilderSicherung:/mnt/media/Bildersicherung:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /immich/db:/var/lib/postgresql/data
    restart: always
volumes:
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=++++++++++++++++
DB_PASSWORD=++++++++++++++++++++++++++++

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=++++++++++++++++++++
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
#IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. not quite sure about why it works for some assets but not for all
2. look at mobile app and find thumbnails which look the same and one is remote only and local only
3. validate via filename if it is the same asset
...
