### ISSUE TITLE
Remember selection state on mobile

### ISSUE THREAD

**Issue by leleogere** [immich-app/immich#12718]
### The bug

I do not use automatic background upload, as I prefer to choose which assets I upload myself.

Let say I have a large video to upload from my mobile. I start the upload, then while it is uploading, I scroll and select some other assets to upload too. Once I'm satisfied with the selection, I tap on the "Upload" button, but I got a message saying that an upload is already happening, and that I should wait for it to end before uploading other assets. But now my selection is lost, and I need to do it again (it happened to me a few times, with a few dozen assets, and it can be quite frustrating).

I see two solutions for this :
- Keep the error message, but remember the selection so that when the first upload is done, I only have to click on "Upload" again to upload my selection
- Add the selected assets into a queue of assets to be uploaded after the current upload is done (better)

Also, related to mobile selection, I often confuse the buttons to share as link, and to share the assets directly. And similarly, when I select the wrong button, and I back out to choose the other one, my selection is also lost (quite frustrating again). The problem is similar, but should I open a different issue for this?

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.112.1

### Version of Immich Mobile App

v1.112.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
THUMB_LOCATION=/home/user/immich_generated_data/thumbs
ENCODED_VIDEO_LOCATION=/home/user/immich_generated_data/encoded-video

# External library
EXTERNAL_PATH=/media/user/external

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.112.1"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD="XXX"

# Time zone
TZ="Europe/Paris"

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

Issue 1: 
1. Upload some large assets to the library (that will take more than a few seconds to upload)
2. While uploading, select some more assets
3. Click on "Upload" (as the first upload is still running)
4. An error is displayed and the selection is gone

Issue 2:
1. Select a few assets
2. Click on the share button
3. Realize that you clicked on the wrong share button
4. Click on back in order to choose the correct share button
5. The selection is gone
