### ISSUE TITLE
Videos from a different account are visible under "Search -> Videos"

### ISSUE THREAD

**Issue by gregoryjjb** [immich-app/immich#12783]
### The bug

I have a server with 3 accounts. On one account, "J", when they navigate to Search -> Videos on mobile (I'm not aware of a similar screen on web), they can see videos that belong to another account, "G". 

This is the only instance of this issue I can find; no other account sees the wrong videos in their Videos page. The videos in question are in an external library belonging to G. The issue happens on both the iOS and Android apps.

See screenshots:

![immichbug](https://github.com/user-attachments/assets/8186dec5-286e-4b89-a1c9-fd0d395a1527)

### The OS that Immich Server is running on

NixOS

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION:?error}:/usr/src/app/upload
      - ${ARCHIVES_LOCATION:?error}:/mnt/media/archives:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 127.0.0.1:2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - diun.enable=true
      - diun.watch_repo=true
      - diun.include_tags=^v

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${GSERVER_VOLUMES_TMP:?error}/immich-postgres:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# WARNING! This file is not gitignored; do not store secrets

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/storage/photos/immich-uploads

# Location of photo archives (not uploaded by Immich)
ARCHIVES_LOCATION=/mnt/storage/photos/archives

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.115.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open the app as "J"
2. Click on "Search" at the bottom
3. Click on "Videos", towards the bottom of the Search screen
4. See videos that don't belong to you

### Relevant log output

I see the following server logs when I click on the Videos tab as J:

```
[Nest] 17  - 09/19/2024, 6:58:38 AM   DEBUG [Api:LoggingInterceptor~q1xnv8q8] GET /api/people/1e9d86c6-a680-411f-be92-28d798b20a2a/thumbnail 200 62.79ms 100.91.54.102
[Nest] 17  - 09/19/2024, 6:58:42 AM   DEBUG [Api:LoggingInterceptor~w9vw7yu3] POST /api/auth/validateToken 200 0.30ms 100.91.54.102
[Nest] 17  - 09/19/2024, 6:58:42 AM   DEBUG [Api:GlobalExceptionFilter~5d939e6j] HttpException(404): {"message":"Asset media not found","error":"Not Found","statusCode":404}
[Nest] 17  - 09/19/2024, 6:58:42 AM   DEBUG [Api:LoggingInterceptor~5d939e6j] GET /api/assets/82e1af6d-8f95-42b0-a460-7f53779f27a5/thumbnail?size=thumbnail 404 6.44ms 100.91.54.102
```

That `/api/auth/validateToken` call happens every time 🤔 

Another interesting line that appears sometimes, but not consistently as I click the button:

```
[Nest] 17  - 09/19/2024, 7:00:33 AM VERBOSE [Api:LoggingInterceptor~zoa322ml] {"updatedAfter":"2024-09-19T06:57:42.706251Z","userIds":["cfaab19f-c6d6-45d2-8808-063c8d74c2a5","d369fc74-4dd4-4ef2-9c5e-1fe6035cf90e"]}
```

` d369fc74-4dd4-4ef2-9c5e-1fe6035cf90e` is G's user ID
