### ISSUE TITLE
Error loading thumbs

### ISSUE THREAD

**Issue by dodg3r** [immich-app/immich#12810]
### The bug

When backing up my iphone photos sometimes no thumbs is generated

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - pictures:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
  pictures:
    driver_opts:
      type: nfs
      o: addr=X.X.X.X,nfsvers=3
      device: X.X.X.X:/mnt/Backup/Immich_pictures
```

### Your .env content

```Shell
# The location where your uploaded files are stored
# UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
TZ=Europe/Stockholm

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=***

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Backup photo with iphone
2. 
3.
...

### Relevant log output

```shell
[Nest] 7  - 09/20/2024, 7:58:28 AM    WARN [Microservices:MetadataService] Asset cfcbb89d-6e49-49e5-9715-7f80ad4eab3a has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 09/20/2024, 7:58:28 AM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: exifTags.ModifyDate?.toDate is not a function
[Nest] 7  - 09/20/2024, 7:58:28 AM   ERROR [Microservices:JobService] TypeError: exifTags.ModifyDate?.toDate is not a function
    at MetadataService.getDates (/usr/src/app/dist/services/metadata.service.js:508:46)
    at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:194:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 09/20/2024, 7:58:28 AM   ERROR [Microservices:JobService] Object:
{
  "id": "cfcbb89d-6e49-49e5-9715-7f80ad4eab3a",
  "source": "upload"
}
```

### Additional information

When I press resfresh thumbnail it works.

```
[Nest] 7  - 09/20/2024, 11:20:32 AM     LOG [Microservices:MediaService] Successfully generated JPEG video preview for asset cfcbb89d-6e49-49e5-9715-7f80ad4eab3a
[Nest] 7  - 09/20/2024, 11:20:33 AM     LOG [Microservices:MediaService] Successfully generated WEBP video thumbnail for asset cfcbb89d-6e49-49e5-9715-7f80ad4eab3a
```
