### ISSUE TITLE
Only 1 tag displayed in web display

### ISSUE THREAD

**Issue by djmccullers** [immich-app/immich#12839]
### The bug

On Immich v1.115.0, when using the "Tag" feature, 

![Immich_1](https://github.com/user-attachments/assets/89abaa5e-e62c-4a80-9555-d046956b0cc2)

only the top most tag is ever displayed.

![Immich_2](https://github.com/user-attachments/assets/7c04d383-90da-4000-ab28-dff3abe0c008)

### The OS that Immich Server is running on

Linux Mint 22.0

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
#      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-latest}
#      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-next}
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-next}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-next}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/don/ImmichDrive/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/media/don/ImmichDrive/immich/postgres
# The Immich version to use.
IMMICH_VERSION=release
# PostgreSQL password. Change it to a secure one.
DB_PASSWORD=xyzzy

# The values below this line do not need to be changed
#######################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Click the "three dots" (What's that called? I know that these "..." are ellipsis (sp?)
2. Create two or more tags, either all at once or at different times
3. Repeat step 1
4. Observer that you can only see the top most tag. You can use the arrow keys to move to the 2nd and other tags BUT they are not displayed nor are they scrolled into view nor can you adjust the size of the popup window.
