### ISSUE TITLE
Android uploading more than it should?

### ISSUE THREAD

**Issue by realmers** [immich-app/immich#12853]
### The bug

![image](https://github.com/user-attachments/assets/e967a1d2-f26b-498a-8bc0-a43b3db6bb48)

I have 40GB on my user but the upload folder is 142GB large according to the command below:

du -sh ./upload/

gives 142G

This is a fresh install of immich with me uploading for the first time from an android device. The upload was not smooth with it keep on resetting a video or image upload, after i switch apps or such.

Im using an android 14 oneplus 10 pro.

### The OS that Immich Server is running on

Debian 12, docker compose

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: $DOCKERDIR/appdata/traefik3/rules/udms/immich-hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${IMMICH_UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=$TZ
      - UPLOAD_LOCATION=$IMMICH_UPLOAD_LOCATION
      - DB_DATA_LOCATION=$IMMICH_DB_DATA_LOCATION
      - DB_USERNAME=$IMMICH_DB_USERNAME
      - DB_PASSWORD=$IMMICH_DB_PASSWORD
      - DB_DATABASE_NAME=$IMMICH_DB_DATABASE_NAME
      - IMMICH_VERSION=$IMMICH_VERSION
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - t3_proxy
      - socket_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.immich-rtr.rule=Host(`proximmich.$DOMAINNAME_1`)"
      - "traefik.http.routers.immich-rtr.entrypoints=websecure"
      # Middlewares
      # HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=3001"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: $DOCKERDIR/appdata/traefik3/rules/udms/immich-hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - TZ=$TZ
      - UPLOAD_LOCATION=$IMMICH_UPLOAD_LOCATION
      - DB_DATA_LOCATION=$IMMICH_DB_DATA_LOCATION
      - DB_USERNAME=$IMMICH_DB_USERNAME
      - DB_PASSWORD=$IMMICH_DB_PASSWORD
      - DB_DATABASE_NAME=$IMMICH_DB_DATABASE_NAME
      - IMMICH_VERSION=$IMMICH_VERSION
    restart: always
    healthcheck:
      disable: false
    networks:
      - t3_proxy
      - socket_proxy

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - t3_proxy
      - socket_proxy

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_USER: ${IMMICH_DB_USERNAME}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${IMMICH_DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${IMMICH_DB_DATABASE_NAME}' --username='${IMMICH_DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${IMMICH_DB_DATABASE_NAME}' --username='${IMMICH_DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - t3_proxy
      - socket_proxy

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
IMMICH_UPLOAD_LOCATION="./library"
# The location where your database files are stored
IMMICH_DB_DATA_LOCATION="./postgres"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="release"

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
IMMICH_DB_PASSWORD="postgres"

# The values below this line do not need to be changed
###################################################################################
IMMICH_DB_USERNAME="postgres"
IMMICH_DB_DATABASE_NAME=""
```

### Reproduction steps

1. Start docker container and configure setup
2. Start backup process

### Relevant log output

```shell
[Nest] 7  - 09/22/2024, 7:34:55 PM    WARN [Microservices:MetadataService] Asset 21db6f9d-a3ad-4471-8812-a263ad95576f has no time zone information
[Nest] 7  - 09/22/2024, 7:34:55 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 21cc5a9a-97a1-4a83-8119-b33b668219ff
[Nest] 7  - 09/22/2024, 7:34:56 PM     LOG [Microservices:MediaService] Successfully generated WEBP image preview for asset 21db6f9d-a3ad-4471-8812-a263ad95576f
[Nest] 7  - 09/22/2024, 7:34:57 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 21db6f9d-a3ad-4471-8812-a263ad95576f
[Nest] 7  - 09/22/2024, 7:34:58 PM    WARN [Microservices:MetadataService] Asset 3261f615-e9e0-4ba3-8ee7-85c885df55f2 has no time zone information
[Nest] 7  - 09/22/2024, 7:35:00 PM     LOG [Microservices:MediaService] Successfully generated WEBP image preview for asset 3261f615-e9e0-4ba3-8ee7-85c885df55f2
[Nest] 7  - 09/22/2024, 7:35:01 PM    WARN [Microservices:MetadataService] Asset 7c52c158-2a04-4eb6-b2a7-5bd8a5040105 has no time zone information
[Nest] 7  - 09/22/2024, 7:35:11 PM    WARN [Microservices:MetadataService] Asset 9c716f8d-3317-487f-bc87-196d59b5e28d has no time zone information
[Nest] 7  - 09/22/2024, 7:35:13 PM     LOG [Microservices:MediaService] Successfully generated WEBP image preview for asset 7c52c158-2a04-4eb6-b2a7-5bd8a5040105
[Nest] 7  - 09/22/2024, 7:35:13 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 3261f615-e9e0-4ba3-8ee7-85c885df55f2
[Nest] 7  - 09/22/2024, 7:35:14 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 7c52c158-2a04-4eb6-b2a7-5bd8a5040105
[Nest] 7  - 09/22/2024, 7:35:14 PM     LOG [Microservices:MediaService] Successfully generated WEBP image preview for asset 9c716f8d-3317-487f-bc87-196d59b5e28d
[Nest] 7  - 09/22/2024, 7:35:18 PM     LOG [Microservices:MediaService] Successfully generated WEBP image thumbnail for asset 9c716f8d-3317-487f-bc87-196d59b5e28d
```
