### ISSUE TITLE
Does not start immich_server after “down and remove orhpans”

### ISSUE THREAD

**Issue by ivsafronov** [immich-app/immich#12864]
### The bug

Hi, I apologize for possible mistakes, writing about the problem for the first time.

I am using Immich in docker on openmediavault 7 in the standard compose plugin.
By my own silliness, I used the “down and remove orhpans” function to remove unnecessary files after experiments. After that the immich_server container cannot start.
The log shows an error on encoded video, but in general I disabled this option and use unencoded files. That's why I didn't even specify their location.
![2024-09-23_14-42-01](https://github.com/user-attachments/assets/97499acd-2f9c-45d6-a617-d22cbb7a731f)
I was successfully able to get it working only by rolling back to v1.114.0.

### The OS that Immich Server is running on

OMV 7.4.8-1 (Sandworm)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
#      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
    env_file:
      - immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
LIBRARY_LOCATION=/srv/hdd/files/photos
UPLOAD_LOCATION=/srv/ssd/cache/immich_cache/upload
THUMBS_LOCATION=/srv/ssd/cache/immich_cache/thumbs
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Moscow

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Working version v1.115.0. Everything worked stably
2. In the compose manager I used the function: down and remove orphans
3. immich_server won't start
4. Trying to enter IMMICH_VERSION=v1.114.0
5. Сontainer is launching

### Relevant log output

```shell
immich_server  | Detected CPU Cores: 4
immich_server  | Starting api worker
immich_server  | Starting microservices worker
immich_server  | [Nest] 7  - 09/23/2024, 2:45:52 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server  | [Nest] 7  - 09/23/2024, 2:45:52 PM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
immich_server  | [Nest] 7  - 09/23/2024, 2:45:52 PM     LOG [Microservices:MapRepository] Initializing metadata repository
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM     LOG [Api:EventRepository] Initialized websocket server
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM     LOG [Api:SystemConfigService] LogLevel=log (set via system config)
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM     LOG [Api:ServerService] Feature Flags: {
immich_server  |   "smartSearch": true,
immich_server  |   "facialRecognition": true,
immich_server  |   "duplicateDetection": true,
immich_server  |   "map": true,
immich_server  |   "reverseGeocoding": true,
immich_server  |   "importFaces": false,
immich_server  |   "sidecar": true,
immich_server  |   "search": true,
immich_server  |   "trash": true,
immich_server  |   "oauth": false,
immich_server  |   "oauthAutoLaunch": false,
immich_server  |   "passwordLogin": true,
immich_server  |   "configFile": false,
immich_server  |   "email": false
immich_server  | }
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM     LOG [Api:StorageService] Verifying system mount folder checks
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM   ERROR [Api:StorageService] Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'
immich_server  | [Nest] 17  - 09/23/2024, 2:45:52 PM   ERROR [Api:StorageService] The "encoded-video" folder appears to be offline/missing, please make sure the volume is mounted with the correct permissions
immich_server  | api worker exited with code 1
```
