### ISSUE TITLE
Using Apple M2 chip to run Remote Machine Learning natively

### ISSUE THREAD

**Issue by juneix** [immich-app/immich#12867]
### The bug

Hello, I ran immich on a very old J1900 chip machine, which is pretty good as a NAS, but it responds slowly when running machine learning. I also have a Mac mini with M2 chip, because of the low power consumption, it basically never shuts down. I want to use Docker to run Remote Machine Learning on it, but it seems that the hardware acceleration function cannot be enabled? It is not as fast as I imagined. I would like to ask if it is possible to support it in the future, after all, M-series chips have advantages in running AI applications. If it has no advantage over immich, please let me know.

### The OS that Immich Server is running on

Debian 12 with J1900, Mac mini with M2

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich_remote_ml

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.ml.yml
    #   service: # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003

volumes:
  model-cache:
```

### Your .env content

```Shell
none
```

### Reproduction steps

1.none
2.
3.
...
