### ISSUE TITLE
"I cannot log into the Immich web page on Safari, Edge, or Chrome browsers on my iPhone."

### ISSUE THREAD

**Issue by MRRockGG** [immich-app/immich#12904]
### The bug

When I access my Immich web page using IPv6 over a mobile network on my iPhone, I can reach the web page and communicate with the server normally (for example, entering an incorrect password results in an error, and accessing the URL/api returns information). However, when I enter the correct username and password and click the login button, it does not redirect correctly to the 2283/photos interface; it only shows a spinning circle on the login button.

1、This issue occurs on three different iPhones.
2、The same issue is observed when using Edge and Chrome browsers.
3、A Xiaomi phone can redirect normally.

Lastly, to explain my network configuration: I deployed Immich using Docker Desktop on my Windows computer. I have a public IPv6 address. By allowing port 2283 on both Windows and the router's firewall, I can access http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:2283 over a mobile network that supports IPv6. Additionally, the iOS app can use all functionalities normally through this address.

### The OS that Immich Server is running on

windows10/22h2，dockerdesktop v4.34.2，Ubuntu 22.04.3 LTS (GNU/Linux 5.15.153.1-microsoft-standard-WSL2 x86_64)

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

1.115.0 build.175

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
      
      
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #file: hwaccel.ml.yml
        #service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - D:/docker/immich-app/machine/model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
# UPLOAD_LOCATION=./library
UPLOAD_LOCATION=D:\docker\immich-app\library

# The location where your database files are stored
# DB_DATA_LOCATION=./postgres
DB_DATA_LOCATION=D:\docker\immich-app\postgres
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
#MACHINE_LEARNING_HOST=0.0.0.0
```

### Reproduction steps

1. Install Immich and ensure that the iOS app can connect to the server using the address: `http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:2283` to access or upload photos.

2. Open Safari and enter the address `http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:2283` in the address bar. You should see the login page at `http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:2283/auth/login`.

3. Enter the username and password, then click the login button. At this point, the text "Login" disappears from the button, and a spinning circle appears on the button. However, it does not correctly redirect to `http://[xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:2283/photo`.

4. Meanwhile, on the web backend on the computer, you can see that the authorized devices section has a record for iOS • Mobile Safari.
