### ISSUE TITLE
Error when setting database password using environment variable

### ISSUE THREAD

**Issue by ezpc98** [immich-app/immich#12912]
### The bug

Documentation suggests set of environment variables available that support docker secrets. For Postgres DB, using DB_PASSWORD_FILE instead of DB_PASSWORD is generating warning "The "DB_PASSWORD" variable is not set. Defaulting to a blank string." and server logs showing error that password file (pointed in DB_PASSWORD_FILE variable) not found.

Any guidance to resolve will be much appreciated.

### The OS that Immich Server is running on

Debian 12.7

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# Immich variables
# Documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
IMMICH_VERSION=release
UPLOAD_LOCATION=/mnt/media/immich-library # Location where uploaded files are stored
DB_DATA_LOCATION=/mnt/dietpi_userdata/docker-data/appdata/immich-postgres # Location where database files are stored
DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD_FILE=./immich_db_pwd.txt
```

### Reproduction steps

1. Create a flat text file with password for Postgres database
2. In .env file, remove DB_PASSWORD variable. Add DB_PASSWORD_FILE varilable with path to the password file in step 1. In my case, I saved password file in same directory as .env file for ease of testing the feature and referred it to DB_PASSWORD_FILE variable.
4. Create docker compose yml file as per recommended setup and save it in the same directory as .env file. I did not declare any secrets in compose file though.
5. Start the service using docker compose -f <yml file> up -d command as root user.
...

### Relevant log output

```shell
Permissions for .env, compose and password files:
-----------
root@4WiseGaba:/mnt/dietpi_userdata/docker-data/compose/immich# ls -la
total 20
drwxr-xr-x 2 root root 4096 Sep 24 19:31 .
drwxrwxr-x 3 root root 4096 Sep 24 19:29 ..
-rw-r--r-- 1 root root  436 Sep 24 19:55 .env
-rw-r--r-- 1 root root    9 Sep 24 19:31 immich_db_pwd.txt
-rw-r--r-- 1 root root 3203 Sep 24 19:29 immich.yml
-----------

On starting service through docker compose, containers are created but warning message appear stating DB_PASSWORD not set.
---------
root@4WiseGaba:/mnt/dietpi_userdata/docker-data/compose/immich# docker compose -f immich.yml up -d
WARN[0000] The "DB_PASSWORD" variable is not set. Defaulting to a blank string.
[+] Running 5/5
 ✔ Network immich_default             Created                                                                                          0.4s
 ✔ Container immich_postgres          Started                                                                                          4.7s
 ✔ Container immich_redis             Started                                                                                          4.6s
 ✔ Container immich_machine_learning  Started                                                                                          4.6s
 ✔ Container immich_server            Started
----------

Logs from immich_server container says password file not found.
----------
Node.js v20.17.0
cat: ./immich_db_pwd.txt: No such file or directory
Detected CPU Cores: 6
/usr/src/app/node_modules/@nestjs/config/dist/config.module.js:86
                throw new Error(`Config validation error: ${error.message}`);
                ^

Error: Config validation error: "DB_PASSWORD" is not allowed to be empty
    at ConfigModule.forRoot (/usr/src/app/node_modules/@nestjs/config/dist/config.module.js:86:23)
    at Object.<anonymous> (/usr/src/app/dist/app.module.js:59:27)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/dist/main.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)

Node.js v20.17.0
cat: ./immich_db_pwd.txt: No such file or directory
Detected CPU Cores: 6
```

### Additional information

On scanning start.sh in Github repo, I believe it simply attempts to read the content of file pointed by DB_PASSWORD_FILE and assign it values to DB_PASSWORD variable. However, in this case, it simply is not finding the password file itself depsite it being physically present in the same directory of compose file and doesn't seem to be any permission issue either.
