### ISSUE TITLE
deleting assets that have one duplicate via REST API will not remove them from duplicate review tool

### ISSUE THREAD

**Issue by sonntam** [immich-app/immich#12928]
### The bug

First of all thank you for the development of immich! It is a superb image organization tool and I don't know how I could have been missing it for the past couple of years.

About the issue:
I have multiple duplicate groups with two duplicate candidate files. These are visible in the duplicate review tool in the web UI.

I used the REST APIs
`GET /duplicates`
`DELETE /assets`
with some PowerShell scripting in between to automatically select and delete unwanted duplicates (the API is very handy!).

Now I expected that after deleting the duplicates that they should not be visible anymore in the duplicates review tool, i.e. having no more duplicates to choose from. Instead in the tool I now get shown single images, see this screenshot for an example:

![image](https://github.com/user-attachments/assets/4dc84f93-de4b-43f2-9b25-1ed2331d1629)

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

v1.115.0 Build 175

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_LIBRARY}:/mnt/extlib1
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/docker/immich/library
DB_DATA_LOCATION=/volume1/docker/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=REDACTED
DB_USERNAME=REDACTED
DB_DATABASE_NAME=immich
EXTERNAL_LIBRARY=/volume1/Medien/Digitalphotos
```

### Reproduction steps

1. Have a duplicate group with at least two duplicates.
2. Delete all but one members of the duplicate group via REST API `DELETE /assets`
3. Refresh the duplicate review tool.
4. There will be a single image shown on the UI and the duplicate group still seems to exist

### Additional information

The images in question are located in an external library.
