### ISSUE TITLE
Date Change Not Reflecting in Timeline After Import

### ISSUE THREAD

**Issue by Grudging0042** [immich-app/immich#12948]
### The bug

Hi everyone,

I recently imported approximately 10,000 photos from the Photos app on my Mac into Immich. The import process seemed to go smoothly, but I noticed that around 200 of the pictures are showing the wrong date in the timeline. For some reason, these photos have the export date (16th September 2024) instead of their actual taken date.

I’m not too concerned about why they have the wrong date, but I want to fix it. I selected this group of photos in the Immich web app and changed the date to 1st January 1970 to move them to the bottom of the timeline. However, despite updating the date (when I click “Info,” I can see the new date of 1st January 1970), the pictures are still appearing in the timeline under the export date of 16th September 2024.

Has anyone experienced a similar issue or know what could be causing this? Is there anything I can do to fix it?

Thanks in advance for your help!

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

1.115.0

### Version of Immich Mobile App

1.115.0 build.175

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/odin/Applications/Immich/photos:/photos
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   volumes:
  #     - model-cache:/cache
  #   env_file:
  #     - .env
  #   restart: always
  #   healthcheck:
  #     disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /home/odin/Applications/Immich/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - /mnt/nas_backup/odin_valhalla/db:/db_dumps
    depends_on:
      - database

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/odin/Pictures/uploads

# The location where your database files are stored
DB_DATA_LOCATION=/home/odin/Applications/Immich/postgres

# Set the timezone
TZ=Europe/Prague

# The Immich version to use. Pin it to a specific version or use the latest release
IMMICH_VERSION=release

# Connection secret for postgres. Change it to a secure random password
DB_PASSWORD=XXX

# Postgres credentials
DB_USERNAME=postgres
DB_DATABASE_NAME=immich-v2
```

### Reproduction steps

1. Select a photo from timeline
2. With context menu - change the date
3.
...

### Relevant log output

```shell
[Nest] 7  - 09/24/2024, 2:06:14 PM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: exifTags.ModifyDate?.toDate is not a function
    at MetadataService.getDates (/usr/src/app/dist/services/metadata.service.js:508:46)
    at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:194:80)
    at async /usr/src/app/dist/services/job.service.js:148:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```
