### ISSUE TITLE
Error after upgrade to v1.116.0 & v1.116.1

### ISSUE THREAD

**Issue by webstudiobond** [immich-app/immich#12996]
### The bug

Hello.

The following is used for the immich server in docker compose:
```
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      # - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - "/mnt/imlib:/usr/src/app/upload/library"
      - "/mnt/imext:/mnt/media:ro"
    env_file:
      - .env
    ports:
      - 127.0.0.1:12283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '4G'
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    user: '1038:33'
```
The permissions in the system are set as follows:
```
ls -na /mnt
...
drwxr-x---  1 1038 33    0 Sep 17 21:44 imext
drwxr-x---  1 1038 33    0 Sep 27 21:08 imlib
```
The permissions in the container (v1.115.0):
```
I have no name!@2706689c7ad1:/usr/src/app$ ls -na /usr/src/app/upload
total 24
drwxr-xr-x 7 1038 33 4096 Aug 31 21:32 .
drwxr-xr-x 1    0  0 4096 Sep 27 21:22 ..
drwxr-xr-x 3 1038 33 4096 Sep 26 19:49 encoded-video
drwxr-x--- 1 1038 33    0 Sep 27 21:08 library
drwxr-xr-x 5 1038 33 4096 Sep 26 20:09 profile
drwxr-xr-x 5 1038 33 4096 Sep 26 19:49 thumbs
drwxr-xr-x 4 1038 33 4096 Sep 26 19:50 upload
```

Up to v1.115.0 everything works fine.

<img width="1347" alt="Снимок экрана 2024-09-27 в 21 23 48" src="https://github.com/user-attachments/assets/ba8acff2-d5eb-4be2-bb88-30d751dfb2fc">

After upgrading to v1.116.0 and v1.116.1, errors occur:

```
ERROR [Api:StorageService] Failed to write upload/library/.immich: AggregateError: EPERM: operation not permitted, write
ERROR [Api:StorageService] The "library" folder cannot be written to, please make sure the volume is mounted with the correct permissions
```

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.116.1

### Version of Immich Mobile App

v1.116.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    # image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    image: ghcr.io/immich-app/immich-server:v1.115.0 
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    # devices:
      # - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      # - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - "/mnt/imlib:/usr/src/app/upload/library"
      - "/mnt/imext:/mnt/media:ro"
    env_file:
      - .env
    ports:
      - 127.0.0.1:12283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          # Number of CPU threads
          cpus: '2.00'
          # Gigabytes of memory
          memory: '4G'
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    user: '1038:33'

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
  #   # Example tag: ${IMMICH_VERSION:-release}-cuda
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   #   file: hwaccel.ml.yml
  #   #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #   volumes:
  #     - ./model-cache:/cache
  #   env_file:
  #     - .env
  #   restart: always
  #   healthcheck:
  #     disable: false
  #   deploy:
  #     resources:
  #       limits:
  #         # Number of CPU threads
  #         cpus: '2.00'
  #         # Gigabytes of memory
  #         memory: '4G'
  #   security_opt:
  #     # Prevent escalation of privileges after the container is started
  #     - no-new-privileges:true
  #   cap_drop:
  #     # Prevent access to raw network traffic
  #     - NET_RAW
  #   user: '1038:33'

  redis:
    container_name: immich_redis
    image: redis:7-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - ./redis-data:/data
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    user: '1038:1038'

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    user: '999:1038'
```

### Your .env content

```Shell
UPLOAD_LOCATION=./storage
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=redacted
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=Europe/Kyiv
```

### Reproduction steps

1. Separate mounting for /usr/src/app/upload/library
2. Individual user:group
3. Upgrade to v1.116.1
More details in the first post above

### Relevant log output

```shell
ERROR [Api:StorageService] Failed to write upload/library/.immich: AggregateError: EPERM: operation not permitted, write
ERROR [Api:StorageService] The "library" folder cannot be written to, please make sure the volume is mounted with the correct permissions
```
