### ISSUE TITLE
Web Version: Incomplete Video Display When Scrolling Through Large Library

### ISSUE THREAD

**Issue by pipe-organ** [immich-app/immich#13002]
### The bug

I have thousands of videos in my Immich library. The "Search > Show Video" feature works perfectly on iOS — I can scroll all the way down and see my oldest videos. However, on the web version, it seems like there’s a limit to how many videos can be displayed at once. When I scroll to the bottom, the older videos don’t appear. If I narrow the date range to only show the older videos, they do display properly on the web version. It just seems like scrolling through the entire library cuts off at some point on the web, but not on iOS.

### The OS that Immich Server is running on

MacOS, Fedora 39, Fedora 40, Debian 12

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.115.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photos/incoming:/mnt/photos/incoming
    env_file:
      - stack.env
    ports:
      - 192.168.1.100:2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/photos/apps/immich
DB_DATA_LOCATION=/mnt/ssd/docker-data/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
THUMB_LOCATION=/mnt/ssd/docker-data/immich/thumbs
PROFILE_LOCATION=/mnt/ssd/docker-data/immich/profile
```

### Reproduction steps

1. Web version > Show search options
2. Media Type > Video > Search
3. Scroll all the way down.
...
