### ISSUE TITLE
External tag not added unless immich tag added and deleted

### ISSUE THREAD

**Issue by ronbruins** [immich-app/immich#13015]
### The bug

When adding tags images (written to xml sidecars) with upon refresh metadata the tag is not seen. When in immich a tag is added and deleted the tag does show up.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.116.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      #- /volume1/docker/compose_files/mbpro/immich/mbpro/config:/usr/src/app/config
      - /volume1/docker/compose_files/mbpro/immich/config:/usr/src/app/config
      - /etc/localtime:/etc/localtime:ro
      - photo:/mnt/media/photo:rw
        #- photo:/volume1/photo:rw
      - homes:/mnt/media/homes:rw
        #- homes:/volume1/homes:rw
      - /volume2/docker/immich/debug_lib:/mnt/media/debug_lib:rw
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
      #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      #file: hwaccel.ml.yml
      #service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume1/docker_local/immich/model-cache:/cache
    ports:
      - 3003:3003
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    ports:
      - 6379:6379
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - /volume1/docker_local/immich/database:/var/lib/postgresql/data
    restart: always

volumes:
  photo:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.35,nfsvers=4,nolock,soft,rw"
      device: ":/volume1/photo"
  homes:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.35,nfsvers=4,nolock,soft,rw"
      device: ":/volume1/homes"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume3/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_LOG_LEVEL=verbose
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
TZ=Europe/Amsterdam

IMMICH_CONFIG_FILE=/usr/src/app/config/mbpro_config.json
```

### Reproduction steps

1. makes ure digicam writes to sidecars
2.add tag to image in digicam
3.refresh metadata for assets
Tag is not seen
4. add a tag in immich
5. remove this tag
now the tag IS seen

**No tags in digiKam**
<img width="1470" alt="before_tag" src="https://github.com/user-attachments/assets/38192ddd-5a2a-44af-9f7b-edf9f594f82a">

**Tags added in DigiKAM**
<img width="1465" alt="After_tag" src="https://github.com/user-attachments/assets/7a2b5c76-2f50-499e-9356-5c2bcdfd2f85">

**Sidecars created:**
<img width="610" alt="Screenshot 2024-09-28 at 10 46 35" src="https://github.com/user-attachments/assets/749debd8-aa32-4f26-b1e4-bd1d6e9c8fff">

**Immich refreshed (read metadata) no tags seen, then adding a tag and removing it in Immich, makes the initial tag appear automatically:**

https://github.com/user-attachments/assets/10e5c65d-4326-4ce1-9567-2ae22d14cdf4
