### ISSUE TITLE
Can't share media from main screen

### ISSUE THREAD

**Issue by bbklopfer** [immich-app/immich#13039]
### The bug

Can't share media (using "share to" to share media via other apps).

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.116.1

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
#    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# Having trouble with my Samsung showing incorrect dates.
TZ=America/Los_Angeles
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# THIS SHOULD BE release INSTEAD, but there are some bugs for my setup! See github issues...
IMMICH_VERSION=release



# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=hunter2

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open immich on mobile (iOS and Android both exhibit this behavior)
2. Long-press item to select
3. Press "Share To"

Expect to open up app list. Instead, get error on main screen, "Cannot fetch offline asset(s), skipping."

### Relevant log output

```shell
Log detail:

Message:

No asset can be retrieved for share

From

ShareService
```

### Additional information

If I instead tap the image to make it full screen, and press "Share" from there, I get the expected behavior of an app selection list.

I have dumped my database, removed containers/volumes (docker compose down -v) and restored. No change in behavior.

I also experience these issues --- they're pretty serious from a usability perspective (my Android basically can't play any videos any more): #12828, #12730, #11689. Since they haven't been fixed, I'm guessing not everyone is experiencing them --- wonder if my setup is unique in some way? Happy to provide logs, etc., of course. Anything to help Immich :)
