### ISSUE TITLE
[BUG] machine-learning exited with code 132 without further 

### ISSUE THREAD

**Issue by xcojonny** [immich-app/immich#1304]
**Describe the bug**
Running immich with docker-compose. 
start stack with `docker-compose up -d`
`docker-compose logs -f` 
`machine-learning exited with code 132 `
-> no additional infos

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x ] I have read thoroughly the README setup and installation instructions.
- [x ] I have included my `docker-compose` file.
- [x ] I have included my redacted `.env` file.
- [x ] I have included information on my machine, and environment.

**To Reproduce**
start container

**Expected behavior**
container does not fail or gives a log entry

**Screenshots**

**System**
- Ubuntu minimal server 22.04 as VM on Proxmox
- docker and docker-compose

**Additional context**

Anyone can help?

```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: "always"


  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - default


volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /opt/containers/DATA/DBs/immich/
      o: bind
  NAS:
    driver_opts:
      type: cifs
      o: "username=docker,password=BjM9mEYXd5n9D,rw"
      device: "//192.xxxx/Immich"

```

.env
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=user
DB_PASSWORD=pw
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=NAS

LOG_LEVEL=simple

JWT_SECRET=sec

```
