### ISSUE TITLE
Video duration from XMP persisted as "[object object]"

### ISSUE THREAD

**Issue by Hixxey** [immich-app/immich#13095]
### The bug

I was getting an error on the web when a single video came into view. The js error (below) was erroring because the assets.Duration field was set to [object object] in the database. 
If I remove the xmpDM:duration element from the sidecar file and refresh the metadata the correct duration of 00:22:11.360 is saved to the table and the error in the UI goes away. I suspect this is because the duration is being read from the file and the sidecar file and it's creating an array?

The fix for me was to remove the element from the sidecar file but I wanted to raise it because I don't know how many other files will have this issue.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')`
from the below function
`function bl(t) {
    const e = t.split(":");
    e[2] = e[2].split(".").slice(0, 2).join(".");
    const [l,a,n] = e.map(Number);
    return We.fromObject({
        hours: l,
        minutes: a,
        seconds: n
    }).as("seconds")
}`

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.116.2

### Version of Immich Mobile App

v1.116.1 build.177

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #command: [ "start.sh", "immich" ]
    volumes:
      - ./immich/library:/usr/src/app/upload/library
      - ./immich/cache/upload:/usr/src/app/upload/upload
      - ./immich/cache/thumbs:/usr/src/app/upload/thumbs
      - ./immich/cache/profile:/usr/src/app/upload/profile
      - ./immich/cache/encoded-video:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
      - ${HOMEDATA}/Pictures:/photos:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    environment:
      DB_USERNAME: ${ADMIN_USER}
      DB_PASSWORD: ${ADMIN_PASSWORD}
      DB_DATABASE_NAME: immich
      DB_HOSTNAME: immich_postgres
      REDIS_HOSTNAME: immich_redis
      TZ: ${TIMEZONE}
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    labels:
      autoheal-app: true
  
  immich-machine-learning: #needs to be hyphenated otherwise the url doesn't work
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./immich/library:/usr/src/app/upload/library
      - ./immich/cache/upload:/usr/src/app/upload/upload
      - ./immich/cache/thumbs:/usr/src/app/upload/thumbs
      - ./immich/cache/profile:/usr/src/app/upload/profile
      - ./immich/cache/encoded-video:/usr/src/app/upload/encoded-video
      - ./immich-machine-learning/model-cache:/cache
    restart: always
    environment:
      TZ: ${TIMEZONE}
    labels:
      autoheal-app: true
  
  immich_redis:
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    container_name: immich_redis
    restart: always
    environment:
      TZ: ${TIMEZONE}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./immich-redis:/data
    labels:
      autoheal-app: true
  
  immich_postgres:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${ADMIN_PASSWORD}
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5432:5432"
    volumes:
      - ./immich-postgres:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    labels:
      autoheal-app: true
```

### Your .env content

```Shell
IMMICH_VERSION=v1.116.2
ADMIN_USER=***
ADMIN_PASSWORD=*********
USER_ID=1000
GROUP_ID=1000
TIMEZONE="Europe/London"
HOMEDATA="/mnt/home"
```

### Reproduction steps

1. Add `<xmpDM:duration xmpDM:scale="1/90000" xmpDM:value="119827200"/>` to the sidecar file.
2. Refresh metadata for that particular file.
3. See error in UI when scrolling past the video.
4. I tested with another video and got the same results.
