### ISSUE TITLE
Some Exif info lost when upload with android phone

### ISSUE THREAD

**Issue by charlieshen7** [immich-app/immich#13188]
### The bug

The same photo
when I upload it with my andriod phone (app version is 1.117.0), some exif info will lost, such as Make, Model, ModifyDate,Focal Length etc.
but if i upload it with web, exif info will not lost

how can i fix this problem?
[the_photo_in_my_phone.zip](https://github.com/user-attachments/files/17262015/the_photo_in_my_phone.zip)
[the_photo_uploaded_with_android_phone_then_download_in_web.zip](https://github.com/user-attachments/files/17262016/the_photo_uploaded_with_android_phone_then_download_in_web.zip)

### The OS that Immich Server is running on

docker

### Version of Immich Server

1.117.0

### Version of Immich Mobile App

1.117.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml 
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - /mnt/media_rw/5cda1ac3-58fe-4df5-97f6-6eb0aa662c51/.ugreen_nas/214558/1_Pictures/Immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media_rw/5cda1ac3-58fe-4df5-97f6-6eb0aa662c51/.ugreen_nas/214558/1_Pictures/Archive:/mnt/archive
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      network:
        ipv4_address: 172.24.0.5


  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      # file: hwaccel.ml.yml
      # service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /mnt/media_rw/e68d7880-8c05-493e-8b92-b956aebeac0c/.ugreen_nas/214558/Docker/Immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      network:
        ipv4_address: 172.24.0.3

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      network:
        ipv4_address: 172.24.0.4

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /mnt/media_rw/e68d7880-8c05-493e-8b92-b956aebeac0c/.ugreen_nas/214558/Docker/Immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      network:
        ipv4_address: 172.24.0.6

networks:
  network:
    ipam:
      config:
      - subnet: 172.24.0.0/16
        gateway: 172.24.0.1
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=H4#Xhgti7%FoCQ
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/media_rw/5cda1ac3-58fe-4df5-97f6-6eb0aa662c51/.ugreen_nas/214558/Pictures/Immich
LOG_LEVEL=log
TYPESENSE_API_KEY=QCkiTy*f*fCNJ6iU7cr3q@bmf67bgtX#uec9B
PUBLIC_LOGIN_PAGE_MESSAGE="My Family Photos and Videos Backup Server"
```

### Reproduction steps

1. open the_photo_in_my_phone.jpg directly in pc, you can see full exif info
2. upload it with andriod phone, most exif info lost (you can  download it and check the exif info)
