### ISSUE TITLE
Basic auth is automatically removed from the domain

### ISSUE THREAD

**Issue by volkovd** [immich-app/immich#13191]
### The bug

Previously, I was able to add a basic auth into the domain for public shared links in settings, like this: https://user:password@immich.mydomain.com. Now, the auth information is being removed after save. I need this to generate share links with the auth credentials included.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.117.0 build.162

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /srv/dev-disk-by-uuid-23033302-5a91-4b71-8c2b-1ac25a749f60/immich-photo:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /immich-pg:/var/lib/postgresql/data
      - /mnt/tmpfs:/var/lib/postgresql/stats_temp
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open Administration
2. Go to settings
3. Open server settings 
4. Enter https://user:password@immich.mydomain.com into "Domain for public shared links"
5. Save
6. https://immich.mydomain.com is actually saved
