### ISSUE TITLE
immich_server ERROR [TypeOrmModule] Unable to connect to the database. 

### ISSUE THREAD

**Issue by kellandJuniper** [immich-app/immich#13209]
### The bug

immich_server ERROR [TypeOrmModule] Unable to connect to the database. 
how to fix it?

```bash
immich_server            | Starting api worker
immich_server            | Starting microservices worker                  
immich_server            | [Nest] 7  - 10/05/2024, 3:01:54 AM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 7  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | microservices worker exited with code 1
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
```

my Docker Compose version is v2.29.1

### The OS that Immich Server is running on

Ubuntu 24.04 LTS (GNU/Linux 6.8.0-45-generic x86_64)

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.117.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./ExternalLibrary/SynologyPhotos:/mnt/media/SynologyPhotos
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    environment:
      TZ: "Asia/Shanghai"
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on", "-c" , "jit=off"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Deploy it.

docker compose up

### Relevant log output

```shell
immich_server            | Starting api worker
immich_server            | Starting microservices worker                  
immich_server            | [Nest] 7  - 10/05/2024, 3:01:54 AM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 7  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | microservices worker exited with code 1
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server            | [Nest] 17  - 10/05/2024, 3:01:54 AM   ERROR [ExceptionHandler] Connection terminated unexpectedly
immich_server            | Error: Connection terminated unexpectedly
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:633:28)
immich_server            |     at Connection.emit (node:events:519:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:519:28)
immich_server            |     at TCP.<anonymous> (node:net:339:12)
immich_server exited with code 0
```
