### ISSUE TITLE
Uploading file info get stuck for .MOV

### ISSUE THREAD

**Issue by Samaze123** [immich-app/immich#13228]
### The bug

![IMG_0519](https://github.com/user-attachments/assets/e4f262f2-b11a-40b9-a0dd-a3ee81332c5c)

And it get stuck forever. So every photos or videos after this one get never uploaded.

### The OS that Immich Server is running on

Debian 12 Bookworm

### Version of Immich Server

1.117.0

### Version of Immich Mobile App

1.117.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      default: null
      home-servers_network: null
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
volumes:
  model-cache: null
networks:
  home-servers_network:
    external: true
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./Data/Library
# The location where your database files are stored
DB_DATA_LOCATION=./Data/Postgres

TZ=Europe/Brussels

IMMICH_VERSION=release

DB_PASSWORD=password

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Wait for a video (.mov) to be uploaded)

### Additional information

I thought it was my reverse proxy (Nginx proxy manager) that blocked "big" files but i tried from a computer directly to the ip adress of the immich server cutting off the reverse proxy but  the upload got stuck too.
