### ISSUE TITLE
Renaming albums leads to empty folders on disk

### ISSUE THREAD

**Issue by aaron-iles** [immich-app/immich#13247]
### The bug

If the server is configured with a custom storage template that contains the album name somewhere in it and someone renames an album with assets in it, the old album name still exists on disk as an empty folder. To be clear: the assets are correctly moved from the folder with the old album name to the new album name, but the empty folder is not removed. This is more of a housekeeping issue than anything.

### The OS that Immich Server is running on

Fedora 40

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.117.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich                                                                                                                                                                 
                                                                                                                                                                             
services:                                                                                                                                                                    
  immich-server:                                                                                                                                                             
    container_name: immich_server                                                                                                                                            
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                                                                                       
    # extends:                                                                                                                                                               
    #   file: hwaccel.transcoding.yml                                                                                                                                        
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding                                                                 
    volumes:                                                                                                                                                                 
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file                       
      - ${UPLOAD_LOCATION}:/usr/src/app/upload                                                                                                                               
      - /etc/localtime:/etc/localtime:ro                                                                                                                                     
    env_file:                                                                                                                                                                
      - .env                                                                                                                                                                 
    ports:                                                                                                                                                                   
      - 2283:3001                                                                                                                                                            
    depends_on:                                                                                                                                                              
      - redis                                                                                                                                                                
      - database                                                                                                                                                             
    restart: always                                                                                                                                                          
    healthcheck:                                                                                                                                                             
      disable: false                                                                                                                                                         
                                                                                                                                                                             
  immich-machine-learning:                                                                                                                                                   
    container_name: immich_machine_learning                                                                                                                                  
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag. 
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```


### Your .env content

```Shell
IMMICH_JOB_METRICS=true
IMMICH_IO_METRICS=true
IMMICH_HOST_METRICS=true
IMMICH_API_METRICS=true
IMMICH_METRICS=true
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich
# The location where your database files are stored
DB_DATA_LOCATION=/immich-app/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```


### Reproduction steps

1. Apply a custom storage template enabled with the album name somewhere in the path. In my instance I am using `{{y}}/{{#if album}}{{album}}{{else}}Other/{{MM}}{{/if}}/{{filename}}`.
2. Create an album named "X".
3. Add photos to the album named "X".
4. Rename the album from "X" to "Y".
5. Navigate to the `UPLOAD_LOCATION` and cd down to the directory and find an empty folder named "X". 

### Relevant log output

_No response_

### Additional information

_No response_
