### ISSUE TITLE
regression: qsv acceleration params not applied to ffmpeg, logs lie to me

### ISSUE THREAD

**Issue by Thinkscape** [immich-app/immich#13275]
### The bug

This used to work, but stopped after one of last few updates.

With QSV enabled, on machine that supports it, the ffmpeg command doesn't include `-hwaccel` anymore

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /var/data/immich/upload:/usr/src/app/upload
      - /dev/dri:/dev/dri
      - /etc/localtime:/etc/localtime:ro
    env_file: /var/data/config/immich/immich.env
    depends_on:
      - redis
      - database
    networks:
      - internal
      - traefik_public
    deploy:
      mode: global
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=traefik_public

        - "traefik.http.routers.immich.rule=Host(`something.example.com`)"
        - "traefik.http.routers.immich.entrypoints=https"
        - "traefik.http.routers.immich.tls.domains[0].main=something.example.com"
        - "traefik.http.routers.immich.tls=true"
        - "traefik.http.routers.immich.tls.certresolver=main"
        - "traefik.http.routers.immich.service=immich"
        - "traefik.http.services.immich.loadbalancer.server.port=3001"

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /var/data/immich/cache:/cache
      - /dev/dri:/dev/dri
    env_file: /var/data/config/immich/immich.env
    networks:
      - internal
    deploy:
      mode: global
      labels:
        - traefik.enable=false

  redis:
    image: redis:6.2
    networks:
      - internal
    deploy:
      labels:
        - traefik.enable=false

  db:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file: /var/data/config/immich/immich.env
    volumes:
      - /var/data/runtime/immich/database:/var/lib/postgresql/data
    networks:
      - internal
    deploy:
      labels:
        - traefik.enable=false


networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.8.0/24
```

### Your .env content

```Shell
N/A
```

## Steps 

<img width="400" alt="image" src="https://github.com/user-attachments/assets/aa8eca8a-2374-42b4-8ed1-dd028635a39c">

1. In admin, video transcode settings
2. Enable acceleration with QSV (quicksync)
3. Re-encode a video

## Expected

ffmpeg is called with qsv

## Actual

No qsv params get to ffmpeg and the logs lie about that

```
[Nest] 7  - 10/08/2024, 2:17:57 PM     LOG [Microservices:MediaService] Encoding video ece6d38b-458a-4a3b-899e-4217a09c55c3 with QSV acceleration
[Nest] 7  - 10/08/2024, 2:20:21 PM     LOG [Microservices:MediaService] Successfully encoded ece6d38b-458a-4a3b-899e-4217a09c55c3
```

`ps -Af | grep ffmpeg` shows:
 
```
/usr/bin/ffmpeg -i upload/library/admin/2024/2024-10-06/IMG_0229.MOV -y -c:v h264 -c:a copy -movflags faststart -fps_mode passthrough -map 0:0 -strict unofficial -map 0:1 -v verbose -vf zscale=t=linear:npl=100,tonemap=hable:desat=0,zscale=p=bt709:t=bt709:m=bt709:range=pc,format=yuv420p -preset slow -crf 40 upload/encoded-video/ef0c6f2b-87bc-4be0-b236-bb885652168b/ec/e6/ece6d38b-458a-4a3b-899e-4217a09c55c3.mp4
```

### Relevant log output

```shell
[Nest] 7  - 10/08/2024, 2:17:57 PM     LOG [Microservices:MediaService] Encoding video ece6d38b-458a-4a3b-899e-4217a09c55c3 with QSV acceleration
[Nest] 7  - 10/08/2024, 2:20:21 PM     LOG [Microservices:MediaService] Successfully encoded ece6d38b-458a-4a3b-899e-4217a09c55c3
```
