### ISSUE TITLE
Unselected folders will be automatically uploaded to the server/没有选中的文件夹会被自动上传服务器

### ISSUE THREAD

**Issue by shenyan-008** [immich-app/immich#13273]
### The bug

Unselected folders will be automatically uploaded to the server/没有选中的文件夹会被自动上传服务器

### The OS that Immich Server is running on

Synology3622xs+ 7.2.1 docker 

### Version of Immich Server

1.117

### Version of Immich Mobile App

1.117

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services: 
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.3.75
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.3.75
      - DB_PORT=51606 #optional
      - REDIS_PORT=51604 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /volume3/docker/immich/config:/config
      - /volume3/immich/photos:/photos
      - /volume3/immich/imports:/import:ro #optional
    ports:
      - 51605:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 51604:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 51606:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /volume3/docker/immich/db:/var/lib/postgresql/data
```

### Your .env content

```Shell
services: 
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.3.75
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.3.75
      - DB_PORT=51606 #optional
      - REDIS_PORT=51604 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /volume3/docker/immich/config:/config
      - /volume3/immich/photos:/photos
      - /volume3/immich/imports:/import:ro #optional
    ports:
      - 51605:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 51604:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 51606:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /volume3/docker/immich/db:/var/lib/postgresql/data
```

### Reproduction steps

1.Enable foreground backup
2.Enable background backup
