### ISSUE TITLE
Photos Web UI page chokes loading many images with same timestamp

### ISSUE THREAD

**Issue by ryanwwest** [immich-app/immich#13319]
### The bug

I set up Immich in May 2024, but it has never really loaded more than a few images just when opening the web app, and today I updated to the latest server version and tried to figure out why. It hits 100-300% CPU usage as indicated by `docker stat` or `htop` even with 0 running jobs, and the verbose logs below seem to indicate that it's a problem with loading the main `/photos` HTTP endpoint in a browser. Loading the Photos "timeline" page starts with the most recent, which correctly shows 7 photos with incorrect timestamps from year 4501, but the next most recent 'set' is from May 2024. Maybe Immich thinks there are a ton of images in this set as the log error shows it probably timing out: `[Nest] 17  - 10/09/2024, 3:26:44 PM   DEBUG [Api:LoggingInterceptor~2rrmvqcs] GET /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2024-05-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true 200 37585.19ms ::ffff:172.23.0.1`, then  `[Nest] 17  - 10/09/2024, 3:26:50 PM   ERROR [Api:GlobalExceptionFilter~2rrmvqcs] Unknown error: RangeError: Invalid string length`. I can't find any images with that timestamp in the folder it's scanning for photos, and after timing out the UI is mostly unresponsive (none of the supposed photos from May 2024 are clickable in the UI, just showing grey boxes (so I can't figure out what Immich thinks these are here either). As I set up Immich in May 2024 my best guess is it set a default timestamp for tons of pictures and is now choking on loading them all together. 

But even if there _were_ tons of photos from this date, I still wouldn't expect it to effectively break Immich - it takes 10+ seconds to open one of the 7 loaded pictures to to try fix the bad metadata dates (which don't save when I edit them), and sometimes fails with a 500. No photos earlier than this load. Same for opening administration setttings. I have 800k photos.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

not used

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /nas/photo/:/photo:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /nas/photo/:/photo:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/nas/photo/immich/
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Log into Immich Web UI
2. Wait for photos to load... and only the ones from year 4501 do.

### Relevant log output

```shell
[Nest] 17  - 10/09/2024, 3:26:05 PM     LOG [Api:EventRepository] Websocket Disconnect: -qhs7ePglVE2q2qOAAAZ                                                                                                
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~o09ra989] GET /custom.css 200 16.43ms ::ffff:172.23.0.1                                                                                 
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~lt2dcova] GET /api/users/me 200 1.19ms ::ffff:172.23.0.1                                                                                
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~lsza7tp5] GET /api/server/features 200 22.36ms ::ffff:172.23.0.1                                                                        
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~hf8o0p16] GET /api/users/me/preferences 200 0.21ms ::ffff:172.23.0.1                                                                    
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~ooh0meeh] GET /api/server/config 200 20.97ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~1frary5k] GET /api/server/about 200 143.99ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:05 PM   DEBUG [Api:LoggingInterceptor~v3y88z2h] GET /api/server/storage 200 2.46ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:06 PM     LOG [Api:EventRepository] Websocket Connect:    Yc13jRxuq97wAJ0LAAAb                                                                                                
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~uyxypdtn] GET /api/assets/memory-lane?day=9&month=10 200 31.03ms ::ffff:172.23.0.1                                                      
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~w57v5wqc] GET /api/server/storage 200 1.01ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~98xc0ypd] GET /api/server/about 200 52.94ms ::ffff:172.23.0.1                                                                           
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~txpta6ut] GET /api/server/version-history 200 1.26ms ::ffff:172.23.0.1                                                                  
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~gddvr1ld] GET /api/server/about 200 46.33ms ::ffff:172.23.0.1                                                                           
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~ofye8rs9] GET /api/timeline/buckets?isArchived=false&size=MONTH&withPartners=true&withStacked=true 200 503.43ms ::ffff:172.23.0.1       
[Nest] 17  - 10/09/2024, 3:26:06 PM   DEBUG [Api:LoggingInterceptor~mfne3hmj] GET /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=4501-01-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true 200 177.83ms ::ffff:172.23.0.1                                                                                                                                                                            
[Nest] 17  - 10/09/2024, 3:26:07 PM   DEBUG [Api:LoggingInterceptor~2u7hz4ps] GET /api/assets/8451e327-caad-4ecd-8c04-dc1065bab990/thumbnail?size=preview 200 125.04ms ::ffff:172.23.0.1                    
[Nest] 17  - 10/09/2024, 3:26:07 PM   DEBUG [Api:LoggingInterceptor~5apd2o7w] GET /api/assets/f5024fa4-0ead-43e3-8baf-d3a15ec32051/thumbnail?size=preview 200 293.50ms ::ffff:172.23.0.1                    
[Nest] 17  - 10/09/2024, 3:26:07 PM   DEBUG [Api:LoggingInterceptor~2nu7fhjf] GET /api/assets/5cb1b066-64c4-4d1b-a31e-97171415fee4/thumbnail?size=preview 200 333.58ms ::ffff:172.23.0.1                    
[Nest] 17  - 10/09/2024, 3:26:10 PM   DEBUG [Api:LoggingInterceptor~6ph4bhm7] GET /api/server/storage 200 1.20ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:10 PM   DEBUG [Api:LoggingInterceptor~2ejvsxjj] GET /api/assets/memory-lane?day=9&month=10 200 133.60ms ::ffff:172.23.0.1                                                     
[Nest] 17  - 10/09/2024, 3:26:10 PM   DEBUG [Api:LoggingInterceptor~80gguv5h] GET /api/server/storage 200 27.89ms ::ffff:172.23.0.1                                                                         
[Nest] 17  - 10/09/2024, 3:26:10 PM   DEBUG [Api:LoggingInterceptor~k7584t0n] GET /api/server/about 200 345.84ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:10 PM   DEBUG [Api:LoggingInterceptor~b2e52ttm] GET /api/server/version-history 200 29.47ms ::ffff:172.23.0.1                                                                 
[Nest] 17  - 10/09/2024, 3:26:11 PM   DEBUG [Api:LoggingInterceptor~5sp91x7m] GET /api/server/about 200 478.15ms ::ffff:172.23.0.1                                                                          
[Nest] 17  - 10/09/2024, 3:26:11 PM   DEBUG [Api:LoggingInterceptor~ur547xdg] GET /api/timeline/buckets?isArchived=false&size=MONTH&withPartners=true&withStacked=true 200 718.18ms ::ffff:172.23.0.1       
[Nest] 17  - 10/09/2024, 3:26:11 PM   DEBUG [Api:LoggingInterceptor~cjyrgdrn] GET /api/albums/statistics 200 64.03ms ::ffff:172.23.0.1                                                                      
[Nest] 17  - 10/09/2024, 3:26:11 PM   DEBUG [Api:LoggingInterceptor~ih5bcm4r] GET /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=4501-01-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true 200 217.98ms ::ffff:172.23.0.1                                                                                                                                                                            
[Nest] 17  - 10/09/2024, 3:26:44 PM   DEBUG [Api:LoggingInterceptor~2rrmvqcs] GET /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2024-05-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true 200 37585.19ms ::ffff:172.23.0.1                                                                                                                                                                          
[Nest] 17  - 10/09/2024, 3:26:50 PM   ERROR [Api:GlobalExceptionFilter~2rrmvqcs] Unknown error: RangeError: Invalid string length 
```
```


### Additional information

_No response_
