### ISSUE TITLE
Live photos: Video connected to a live photo can't be played

### ISSUE THREAD

**Issue by gauner1986** [immich-app/immich#13354]
### The bug

When trying to play a video that belongs to a live photo the video doesn't play.
The following error is shown in the error log:

`[Nest] 18  - 10/10/2024, 3:42:38 PM   ERROR [Api:LoggerRepository~fkbp8oxe] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/encoded-video/4882afae-f208-417e-aa64-ccc2c8fe581b/a1/df/a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9.mp4'
    at async access (node:internal/fs/promises:606:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:50:9)
    at async AssetMediaController.playAssetVideo (/usr/src/app/dist/controllers/asset-media.controller.js:61:9)
[Nest] 18  - 10/10/2024, 3:42:38 PM   ERROR [Api:GlobalExceptionFilter~fkbp8oxe] Unknown error: Error: ENOENT: no such file or directory, access 'upload/encoded-video/4882afae-f208-417e-aa64-ccc2c8fe581b/a1/df/a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9.mp4'`

Upon inspection of this location i found a file that has the appendix -MP.

`root@09c22b83f786:/usr/src/app# ls -lh upload/encoded-video/4882afae-f208-417e-aa64-ccc2c8fe581b/a1/df/a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9*
-rw-r--r-- 1 root root 2.0M Oct  9 23:35 upload/encoded-video/4882afae-f208-417e-aa64-ccc2c8fe581b/a1/df/a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9-MP.mp4`

If i rename the file by removing the -MP appendix i can play the video in immich

`root@09c22b83f786:/usr/src/app/upload/encoded-video/4882afae-f208-417e-aa64-ccc2c8fe581b/a1/df# mv a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9-MP.mp4 a1df2754-51fb-4a33-bc2e-7d5e6c0e63c9.mp4`

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

Web app was used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${UPLOAD_UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
#IMMICH_LOG_LEVEL=verbose

# The location where your uploaded files are stored
UPLOAD_LOCATION=./immich_ssd_files
UPLOAD_UPLOAD_LOCATION=/mnt/hdd/immich/upload
LIBRARY_LOCATION=/mnt/hdd/immich/library
THUMB_LOCATION=./immich_ssd_files/thumbs
ENCODED_VIDEO_LOCATION=/mnt/hdd/immich/encoded-video
PROFILE_LOCATION=./immich_ssd_files/profile
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload a photo with a live video
2. Open the photo
3. Press the play button

### Additional information

Photo was taken with a Samsung Android Smartphone
