### ISSUE TITLE
GPS Coordinates do not update if manually inputting Lat/Long values on Mobile app

### ISSUE THREAD

**Issue by jimeelicious** [immich-app/immich#13379]
### The bug

When manually editing GPS coordinates with the value, clicking "Update" does not update photo GPS coordinates.

### The OS that Immich Server is running on

Docker Compose on Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.117.0 build.162

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${FAMILY_PHOTOS}:/mnt/familyphotos
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# Timezone
TZ=America/Los_Angeles

# Family photos that are mounted in the LXC, not Docker container
FAMILY_PHOTOS=/mnt/familyphotos/

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=[REDACTED( ͡° ͜ʖ ͡°) ]

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open info on any image via mobile app (Android)
![image](https://github.com/user-attachments/assets/dabad168-a60f-4a16-b124-3c4fd9778a41)

2. Edit any GPS value manually and hit the update button
![image](https://github.com/user-attachments/assets/63c713b0-c9d8-49c0-9a6e-d3602c0da2ab)

3. Manually inputted GPS values do not appear and remains not updated
![image](https://github.com/user-attachments/assets/f98833bf-fa80-43e1-bb89-d8aba9b14173)

also shown as updated via the Web
![image](https://github.com/user-attachments/assets/72dcfde6-928c-4292-ad9f-ead1a899da26)

### Relevant log output

```shell
[Nest] 7  - 10/11/2024, 9:38:12 AM    WARN [Microservices:MetadataService] Asset 7bc184fb-a398-437d-8492-ec89fb2c324b has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:38:12 AM    WARN [Microservices:MetadataService] Asset 7bc184fb-a398-437d-8492-ec89fb2c324b has no time zone information
[Nest] 17  - 10/11/2024, 9:38:16 AM     LOG [Api:EventRepository] Websocket Disconnect: 7kWPN0bZwQ5JxnKpAABb
[Nest] 7  - 10/11/2024, 9:38:24 AM    WARN [Microservices:MetadataService] Asset 7bc184fb-a398-437d-8492-ec89fb2c324b has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 17  - 10/11/2024, 9:38:29 AM     LOG [Api:EventRepository] Websocket Connect:    FNUfUdAa_w1woH93AABd
[Nest] 7  - 10/11/2024, 9:38:46 AM    WARN [Microservices:MetadataService] Asset 7bc184fb-a398-437d-8492-ec89fb2c324b has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:39:06 AM    WARN [Microservices:MetadataService] Asset 7bc184fb-a398-437d-8492-ec89fb2c324b has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:40:20 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 17  - 10/11/2024, 9:40:48 AM     LOG [Api:EventRepository] Websocket Disconnect: FNUfUdAa_w1woH93AABd
[Nest] 17  - 10/11/2024, 9:43:59 AM     LOG [Api:EventRepository] Websocket Connect:    eoVRqwjekJgcTeITAABf
[Nest] 17  - 10/11/2024, 9:44:05 AM     LOG [Api:EventRepository] Websocket Connect:    7gC58sQaF7XMRm8RAABh
[Nest] 7  - 10/11/2024, 9:44:18 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 17  - 10/11/2024, 9:44:44 AM     LOG [Api:EventRepository] Websocket Disconnect: eoVRqwjekJgcTeITAABf
[Nest] 17  - 10/11/2024, 9:44:59 AM     LOG [Api:TrashService~n0idws18] Restored 1 assets from trash
[Nest] 7  - 10/11/2024, 9:45:18 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:45:18 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no time zone information
[Nest] 7  - 10/11/2024, 9:45:18 AM    WARN [Microservices:MapRepository] Response from database for reverse geocoding latitude: 3, longitude: -122.461982727 was null
[Nest] 7  - 10/11/2024, 9:45:18 AM    WARN [Microservices:MapRepository] Response from database for natural earth reverse geocoding latitude: 3, longitude: -122.461982727 was null
[Nest] 17  - 10/11/2024, 9:45:26 AM     LOG [Api:EventRepository] Websocket Disconnect: 7gC58sQaF7XMRm8RAABh
[Nest] 7  - 10/11/2024, 9:45:44 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:45:44 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no time zone information
[Nest] 17  - 10/11/2024, 9:45:51 AM     LOG [Api:EventRepository] Websocket Connect:    kw-4sPIxyQHqsNZqAABj
[Nest] 17  - 10/11/2024, 9:46:11 AM     LOG [Api:EventRepository] Websocket Disconnect: kw-4sPIxyQHqsNZqAABj
[Nest] 17  - 10/11/2024, 9:46:16 AM     LOG [Api:EventRepository] Websocket Connect:    KCqsYAsoPOEEq8SqAABl
[Nest] 7  - 10/11/2024, 9:46:35 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:46:35 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no time zone information
[Nest] 7  - 10/11/2024, 9:46:45 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:46:45 AM    WARN [Microservices:MetadataService] Asset fff28a0c-4004-40be-aa4b-97aa26b698fa has no time zone information
[Nest] 17  - 10/11/2024, 9:46:47 AM     LOG [Api:EventRepository] Websocket Disconnect: KCqsYAsoPOEEq8SqAABl
[Nest] 17  - 10/11/2024, 9:46:50 AM     LOG [Api:EventRepository] Websocket Connect:    iDPySI1nbVeTxquXAABn
[Nest] 17  - 10/11/2024, 9:47:03 AM     LOG [Api:EventRepository] Websocket Disconnect: iDPySI1nbVeTxquXAABn
[Nest] 17  - 10/11/2024, 9:47:06 AM     LOG [Api:EventRepository] Websocket Connect:    rof5vQ1hc8foupKsAABp
[Nest] 17  - 10/11/2024, 9:47:10 AM     LOG [Api:EventRepository] Websocket Disconnect: Ruj_nMnxpMwI894WAABZ
[Nest] 17  - 10/11/2024, 9:47:10 AM     LOG [Api:EventRepository] Websocket Connect:    SpGyGv-uThxZXlpyAABr
[Nest] 7  - 10/11/2024, 9:47:32 AM    WARN [Microservices:MetadataService] Asset db04d22d-b5ac-4a5c-acec-eb781e41862d has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:47:32 AM    WARN [Microservices:MetadataService] Asset db04d22d-b5ac-4a5c-acec-eb781e41862d has no time zone information
[Nest] 7  - 10/11/2024, 9:47:32 AM    WARN [Microservices:MetadataService] Asset c09907f0-d4fa-4b31-ad02-e0858646bbd5 has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:47:32 AM    WARN [Microservices:MetadataService] Asset c09907f0-d4fa-4b31-ad02-e0858646bbd5 has no time zone information
[Nest] 7  - 10/11/2024, 9:47:33 AM    WARN [Microservices:MetadataService] Asset dee3728c-814e-40aa-bac0-9e8bc931def0 has no valid date (undefined), falling back to asset.fileCreatedAt
[Nest] 7  - 10/11/2024, 9:47:33 AM    WARN [Microservices:MetadataService] Asset dee3728c-814e-40aa-bac0-9e8bc931def0 has no time zone information
```

### Additional information

- Using map and the pointer seems to work. Hitting update changes the GPS location as expected.
- Not an issue with the Web app. Updating coordinate values manually there seems to work as expected as well.

As always, thank you for your work!
