### ISSUE TITLE
"Could not load the "sharp" module using the linux-x64 runtime" on docker-compose install

### ISSUE THREAD

**Issue by evanraalte** [immich-app/immich#13402]
### The bug

App crashes on startup, using the docker compose method. I am a first time Immich user, so can't confirm if other versions do work. I was able to reproduce the issue with the original docker compose files.

### The OS that Immich Server is running on

Ubuntu 24.04.1 (LTS)

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Amsterdam
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=githubissuepw

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Download files
2. Docker compose up

### Relevant log output

```shell
immich_server            | /usr/src/app/node_modules/sharp/lib/sharp.js:113
immich_server            |   throw new Error(help.join('\n'));
immich_server            |   ^
immich_server            | 
immich_server            | Error: Could not load the "sharp" module using the linux-x64 runtime
immich_server            | ERR_DLOPEN_FAILED: /lib/x86_64-linux-gnu/libOpenEXR-3_1.so.30: undefined symbol: _ZTVSt9basic_iosKcSt11char_traitsIcEE, version GLIBCXX_3.4
immich_server            | Possible solutions:
immich_server            | - Ensure optional dependencies can be installed:
immich_server            |     npm install --include=optional sharp
immich_server            | - Ensure your package manager supports multi-platform installation:
immich_server            |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server            | - Add platform-specific dependencies:
immich_server            |     npm install --os=linux --cpu=x64 sharp
immich_server            | - Consult the installation documentation:
immich_server            |     See https://sharp.pixelplumbing.com/install
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:113:9)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1469:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
immich_server            |     at Module.load (node:internal/modules/cjs/loader:1288:32)
immich_server            |     at Module._load (node:internal/modules/cjs/loader:1104:12)
immich_server            |     at Module.require (node:internal/modules/cjs/loader:1311:19)
immich_server            |     at require (node:internal/modules/helpers:179:18)
immich_server            |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server            |     at Module._compile (node:internal/modules/cjs/loader:1469:14)
immich_server            |     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
immich_server            | 
immich_server            | Node.js v20.17.0
```
