### ISSUE TITLE
[issue] Add to album does not update filter

### ISSUE THREAD

**Issue by MickLesk** [immich-app/immich#13460]
### The bug

Hi Guys,

In a nutshell, it's about a missing update flag for active filters in the photo overview. If a filter no longer applies, it is still displayed.
The following steps are defined below (Reproduction steps)

In my case, this occurs when adding to an album, but it is also possible that it is exactly the same problem with other filters.

### The OS that Immich Server is running on

Debian 12 LXC (Docker)

### Version of Immich Server

v1.118.0

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
  pgdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=*****************
DB_HOSTNAME=************
DB_USERNAME=*********
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=./postgres
```

### Reproduction steps

1. go to the “Photos” tab
2. go to the search field and click on the filter icon on the right
3. select the display option “in no album”
4. click on “Search”. Now I have X photos that are not yet assigned to an album
5. select 1-X photos and add them with the “+” to an existing or new album

=> Now the filter “in no album” should actually filter out exactly these 1-X photos and no longer display them. Unfortunately, the “selected” number remains the same and the photos are only no longer available after a complete refresh. This is very confusing if, for example, you want to sort 100 photos into 9 different albums.

### Additional information

Use Portainer as Docker-Deploy
