### ISSUE TITLE
Immich v1.118.0 does not start

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#13473]
### The bug

Immich v1.118.0 does not start. The container will launch and provide some logging, but then fail without any indication as to why. I monitored the resource usage to confirm it was not CPU or RAM limited. I also set `IMMICH_LOG_LEVEL=verbose` I did not find any additional details. There is also a significant amount of outbound network traffic when the container is starting which is not present with running v1.117.0.

### The OS that Immich Server is running on

Linux Mint 21.3

### Version of Immich Server

v1.118.0

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# swarm deployment extension
x-deploy-swarm: &deploy_swarm
  mode: replicated
  replicas: 1
  update_config:
    parallelism: 1
    delay: 10s
    order: stop-first

services:
  app:
    image: ghcr.io/immich-app/immich-server:v1.118.0
    environment:
      NODE_ENV: production
      DB_HOSTNAME: db
      DB_DATABASE_NAME: ${IMMICH_DB:-immich}
      DB_USERNAME: ${IMMICH_DB_USERNAME:-immich}
      DB_PASSWORD: ${IMMICH_DB_PASSWORD:-immich}
    volumes:
      - /media/pictures/immich:/usr/src/app/upload/library
      - ${STORAGE_PATH}/{{index .Service.Labels "com.docker.stack.namespace"}}/upload:/usr/src/app/upload/upload
      - ${STORAGE_PATH}/{{index .Service.Labels "com.docker.stack.namespace"}}/profile:/usr/src/app/upload/profile
      - ${STORAGE_PATH}/{{index .Service.Labels "com.docker.stack.namespace"}}/thumbs:/usr/src/app/upload/thumbs
      - ${STORAGE_PATH}/{{index .Service.Labels "com.docker.stack.namespace"}}/encoded-video:/usr/src/app/upload/encoded-video
      - /media/pictures:/media/pictures
    networks:
      - frontend
      - database
      - machine-learning
      - redis
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: ${IMMICH_APP_CPU_LIMIT}
          memory: ${IMMICH_APP_MEM_LIMIT}
      restart_policy:
        delay: 120s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == McMint

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.118.0
    volumes:
      - ${STORAGE_PATH}/immich/ml-cache:/cache
    networks:
      - machine-learning
    deploy:
      <<: *deploy_swarm
      placement:
        constraints:
          - node.platform.arch == x86_64
      resources:
        limits:
          cpus: ${IMMICH_ML_CPU_LIMIT}
          memory: ${IMMICH_ML_MEM_LIMIT}

  db:
    extends:
      file: common.yml
      service: database-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    environment:
      POSTGRES_DB: ${IMMICH_DB:-immich}
      POSTGRES_USER: ${IMMICH_DB_USERNAME:-immich}
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD:-immich}
    deploy:
      resources:
        limits:
          cpus: ${IMMICH_DB_CPU_LIMIT}
          memory: ${IMMICH_DB_MEM_LIMIT}

  redis:
    extends:
      file: common.yml
      service: redis
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  frontend:
    external: true
    name: core_frontend
  database:
    driver: overlay
  machine-learning:
    driver: overlay
  redis:
    driver: overlay
```

### Your .env content

```Shell
STORAGE_PATH=/mnt/swarm

# Immich
IMMICH_APP_CPU_LIMIT = '4.0'
IMMICH_APP_MEM_LIMIT = '2.0G'

IMMICH_DB_CPU_LIMIT = '0.3'
IMMICH_DB_MEM_LIMIT = '256M'

IMMICH_ML_CPU_LIMIT = '4.0'
IMMICH_ML_MEM_LIMIT = '3.0G'
```

### Reproduction steps

1. Start v1.118.0

### Relevant log output

```shell
immich_app.1.suiofc471pao@McMint    | Initializing Immich v1.118.0
immich_app.1.suiofc471pao@McMint    | DEBUG: cgroup v2 detected.
immich_app.1.suiofc471pao@McMint    | Detected CPU Cores: 4
immich_app.1.suiofc471pao@McMint    | Starting api worker
immich_app.1.suiofc471pao@McMint    | Starting microservices worker
immich_app.1.suiofc471pao@McMint    | [Nest] 7  - 10/15/2024, 7:14:51 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_app.1.suiofc471pao@McMint    | [Nest] 7  - 10/15/2024, 7:14:52 PM     LOG [Microservices:MapRepository] Initializing metadata repository
immich_app.1.suiofc471pao@McMint    | [Nest] 16  - 10/15/2024, 7:14:52 PM     LOG [Api:EventRepository] Initialized websocket server
```
