### ISSUE TITLE
[App]: Missing some translation(codes) for Android (iOS?) App

### ISSUE THREAD

**Issue by MickLesk** [immich-app/immich#13496]
### The bug

Hi,

I primarily maintain the localizely for the German Immich translation. I noticed in the app that there are still some places that do not have a translation code. 
I have collected and marked these places in 3 screenshots
![Screenshot_20241016-120412](https://github.com/user-attachments/assets/a1ba24f7-f17f-4331-9d33-1a60f9816ef5)
![Screenshot_20241016-120419](https://github.com/user-attachments/assets/c91844ac-03d4-44cf-a6a8-22e254b2ea3b)
![Screenshot_20241016-120430](https://github.com/user-attachments/assets/1ea45399-37d2-47e7-914d-ecde78ddae24)

### The OS that Immich Server is running on

Debian 12 (Docker)

### Version of Immich Server

v1.118.1

### Version of Immich Mobile App

v1.118.1 build 163

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
  pgdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=*****************
DB_HOSTNAME=************
DB_USERNAME=*********
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=./postgres
```

### Reproduction steps

Many Steps, i think better when you look @ Screenshots

### Relevant log output

```shell
-
```

### Additional information

I'm not sure if iOS is also affected, I don't have an Apple device to test this.
