### ISSUE TITLE
API component binds to localhost

### ISSUE THREAD

**Issue by rkojedzinszky** [immich-app/immich#13501]
### The bug

After upgrading from v1.117.0 to v1.118.*, the api component binds to localhost, not to wildcard address. Log shows:

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.118.1

### Version of Immich Mobile App

v1.117.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
n/a
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Upgrade from v1.117.0 to v1.118.*
2. Observe logs

### Relevant log output

```shell
[Nest] 17  - 10/16/2024, 11:54:41 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.118.1] [production]
```

### Additional information

[Documentation](https://immich.app/docs/install/environment-variables#ports) shows that `IMMICH_HOST` should control this, howewer, the default value is `0.0.0.0`. Also, setting this explicitly still dont help. Reading the code, it turns out that app uses the [HOST](https://github.com/immich-app/immich/blob/main/server/src/workers/api.ts#L18) environment variable, not `IMMICH_HOST`. Howewer, setting this explicitly to `0.0.0.0` also does not help. The application does process the environment variable, as the log message changes to
```
[Nest] 17  - 10/16/2024, 11:59:09 AM     LOG [Api:Bootstrap] Immich Server is listening on http://127.0.0.1:2283 [v1.118.1] [production]
```
Howewer, still not listening on `0.0.0.0`. In kubernetes, the following workaround is working, howewer, I think that the app should bind to `0.0.0.0` as before.

```
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
```

**Comment by bo0tzz** [comment]
How are you running Immich?

**Comment by rkojedzinszky** [comment]
@bo0tzz it is run inside Kubernetes, with the following Deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server-api
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: server-api
    spec:
      containers:
      - env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: immich-postgresql
        - name: IMMICH_WORKERS_INCLUDE
          value: api
        - name: NODE_OPTIONS
          value: --max-old-space-size=384
        - name: HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: immich-server-environment
        image: ghcr.io/immich-app/immich-server:v1.118.1
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /api/server/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: immich-server
        ports:
        - containerPort: 2283
          name: http
          protocol: TCP
        - containerPort: 8081
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/server/ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 384Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - NET_RAW
        volumeMounts:
        - mountPath: /usr/src/app/upload
          name: library
      enableServiceLinks: false
      securityContext:
        runAsGroup: 8080
        runAsNonRoot: true
        runAsUser: 18760
      volumes:
      - name: library
        persistentVolumeClaim:
          claimName: immich
```

`immich-server-environment` ConfigMap contents:
```
apiVersion: v1
data:
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: immich-postgresql
  DB_USERNAME: immich
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
  IMMICH_METRICS: "true"
  REDIS_HOSTNAME: immich-redis
kind: ConfigMap
metadata:
  name: immich-server-environment
```
