### ISSUE TITLE
502 Gateway Error when viewing photos post 1.118.1 upgrade

### ISSUE THREAD

**Issue by adrianvanderwal** [immich-app/immich#13509]
### The bug

Upgraded from 1.117.1 to 1.118.1, accessed web UI and clicked on any thumbnail in the gallery to view the image.
Instead of a modal popup, the screen goes black.
502 Bad Gateway errors are present in the browser console.
![image](https://github.com/user-attachments/assets/abd3e761-7cfa-452a-83f5-43c1ac925827)

A similar error is shown when attempting to view memories:
![image](https://github.com/user-attachments/assets/618a5859-47e9-40ca-9874-a1c961e9f550)

### The OS that Immich Server is running on

Ubuntu 24.04.01, Docker version 27.3.1, build ce12230

### Version of Immich Server

v1.118.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/path/to/immich/library
IMMICH_VERSION=release
DB_PASSWORD=password
DB_HOSTNAME=db_hostname
DB_USERNAME=db_username
DB_DATABASE_NAME=db_name
REDIS_HOSTNAME=redis_hostname
```

### Reproduction steps

1. Restart stack post upgrade to v1.118.1
2. Log into web UI
3. Click on any thumbnail
4. View errors in web Browser Console

Issue is reproducible in Google Chrome (129.0.6668.101 (Official Build) (64-bit)) and Microsoft Edge (129.0.2792.89 (Official build) (64-bit))

### Relevant log output

```shell
No errors appear in the immich-server container logs

Web Browser Console logs:
/photos/95ea4bce-6cf…a3d5-d3ad2d379db2:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://<immich.app>/_app/immutable/chunks/asset-viewer.C-8J9utO.js
Promise.then
V @ await_block.BDR3ixd6.js:1
gs @ asset-interaction.store.CTDFLYsC.js:2
p @ asset-interaction.store.CTDFLYsC.js:2
Ct @ scheduler.7z7EQB7W.js:1
p @ portal.Cfoe1jPi.js:1
yt @ scheduler.7z7EQB7W.js:1
mt @ scheduler.7z7EQB7W.js:1
Promise.then
ht @ scheduler.7z7EQB7W.js:1
ht @ index.DoTFCMjV.js:4
(anonymous) @ index.DoTFCMjV.js:4
s.$$set @ app.BCuZtPj-.js:2
$set @ index.DoTFCMjV.js:4
J @ entry.B2Tl78kO.js:1
await in J
Ie @ entry.B2Tl78kO.js:1
un @ entry.B2Tl78kO.js:1
w @ navigation.CJq_3ng7.js:1
T @ navigation.CJq_3ng7.js:1
De @ asset-interaction.store.CTDFLYsC.js:2
re @ asset-interaction.store.CTDFLYsC.js:2
f @ asset-interaction.store.CTDFLYsC.js:2
N @ thumbnail.BxQ_uAjx.js:1
lt @ thumbnail.BxQ_uAjx.js:1
```

### Additional information

Container is proxied behind Nginx Proxy Manager
