### ISSUE TITLE
Storage template settings gone

### ISSUE THREAD

**Issue by hathagat** [immich-app/immich#13508]
### The bug

After enabling storage template, the slider is not visible anymore. As well as the settings which should appear, when storage template is enabled.  
The screenshot shows it pretty good:
![grafik](https://github.com/user-attachments/assets/c4a99e1b-ef6d-40c0-adbd-3c0c6b9ca0dd)  
Before enabling, it just looked like in the [screenshot](https://immich.app/assets/images/enable-storage-template-0e3db4a19d4d379c4dfbefd960df181d.png) in the docs.  
I tried a different browser and restarted immich, but no luck.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.118.1

### Version of Immich Mobile App

v1.118.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - '2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      ['postgres', '-c', 'shared_preload_libraries=vectors.so', '-c', 'search_path="$$user", public, vectors', '-c', 'logging_collector=on', '-c', 'max_wal_size=2GB', '-c', 'shared_buffers=512MB', '-c', 'wal_compression=on']
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=<my_lib_location>
DB_DATA_LOCATION=<my_db_location>
TZ=Europe/Berlin
IMMICH_VERSION=v1.118.1
DB_PASSWORD=<my_db_pw>

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. docker compose up
2. do not enable the storage template during the initial setup process
3. enable storage template in admin settings
