### ISSUE TITLE
Immich update  v1.118.0 cannot see images in web or mobile

### ISSUE THREAD

**Issue by neilanthonystuckey** [immich-app/immich#13510]
### The bug

Updated Immich containers with docker compose pull and docker compose up -d.  After I was unable to access GUI until i changed the docker port from 2283:3001 to 2283:2283. I can access the GUI but its just blank.  My mobile app is still connected and backing up photos but i cannot see anything in the web app or mobile.  I removed the containers and ran docker compose up -d to see if that would help but same issues 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.118.0

### Version of Immich Mobile App

v.1.118.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/sdb1:/mnt/sdb1
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - /mnt/sdb1:/mnt/sdb1
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_data>
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/sdb1/backups/photos
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/sdb1/dockers/immich/db/postgres
# The Immich version to use.
IMMICH_VERSION=release
# PostgreSQL password. Change it to a secure one.
DB_PASSWORD=postgres_pass

# The values below this line do not need to be changed
#######################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Immich was fine
2. docker compose pull
3.docker compose up -d
4. Immich broken
5. I tried to follow your guide to fix but i am unsure where to go from here ?
...

### Relevant log output

```shell
docker compose logs -f these errors loop over and over

immich_server            | [Nest] 7  - 10/16/2024, 12:52:33 AM   ERROR [Microservices:JobService] Error: Input file is missing: /mnt/usb2/backups/photos/thumbs/2c930f90-26d0-41f0-b8df-6305ce333263/49/6d/496d6eb8-5281-4299-b42e-153cf3c7dffd-preview.jpeg
immich_server            |     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
immich_server            |     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
immich_server            |     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:153:63)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:101:25)
immich_server            |     at async /usr/src/app/dist/services/job.service.js:163:36
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 10/16/2024, 12:52:33 AM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "e6d040cf-0ffe-484c-bc21-b0c5d451e642"
immich_server            | }
```

### Additional information

I copied the compose file from your github  wget -O docker-compose.yml https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml but i am not seeing anything different than mine.  The containers are running and sort of working.  Mobile uploads are still uploading but my web gui is blank and so is mobile app except for recent uploads but anything older from say 2023 and back does not show. Maybe becuae i added them as external library in web gui Do i need to exec into containers to make any changes or is there an  example .yml to follow ?
