### ISSUE TITLE
People thumbnails broken, Generate Thumbnails job doesn't recreate them

### ISSUE THREAD

**Issue by jkjustjoshing** [immich-app/immich#13515]
### The bug

A while ago, the drive with my Immich install died and I restored from a backup. I didn't back up certain generated folders, which included the featured photo thumbnails for People.

When I restored the files to a new drive and got Immich back up and running, the thumbnails were broken

![image](https://github.com/user-attachments/assets/02c10f94-10f7-4720-8fb8-a0eac3f645e2)

I'd expect the "Generate Thumbnails" job to re-generate these, but it doesn't. For my most-photographed people, I've manually gone in and re-selected the featured photo, but I'd like to repair/regenerate these thumbnails for everyone automatically.

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.115.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}:/usr/src/app/static-library:ro
      - immich-machine-learning:/.config
      - immich-machine-learning:/.cache
      - redis:/data
    user: "${PUID}:${GUID}"
    env_file:
      - .env
    extends:
      file: hwaccel.yml
      service: hwaccel
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`photos.jkjustjoshing.com`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=jkjustjoshing
      - traefik.http.services.immich.loadbalancer.server.port=3001
      - traefik.docker.network=traefik
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich-server
      - traefik

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    user: "${PUID}:${GUID}"
    volumes:
      - model-cache:/cache
      - immich-machine-learning:/.config
      - immich-machine-learning:/.cache
      - redis:/data
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
    restart: always
    networks:
      - immich-server

  # typesense:
  #   container_name: immich_typesense
  #   image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
  #   environment:
  #     - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
  #     - TYPESENSE_DATA_DIR=/data
  #     # remove this to get debug messages
  #     - GLOG_minloglevel=1
  #   labels:
  #     - com.centurylinklabs.watchtower.monitor-only="true"
  #   volumes:
  #     - tsdata:/data
  #   restart: always
  #   networks:
  #     - immich-server

  redis:
    container_name: immich_redis
    user: "${PUID}:${GUID}"
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich-server
    volumes:
      - immich-machine-learning:/.config
      - immich-machine-learning:/.cache
      - redis:/data
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
    restart: always
    networks:
      - immich-server

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    user: "${PUID}:${GUID}"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${DB_HOSTNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_NUM_KEEP: 7
      BACKUP_DIR: /db_dumps
    volumes:
      - ${BACKUP_LOCATION}:/db_dumps
    networks:
      - immich-server
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:
  immich-machine-learning:
  redis:

networks:
  immich-server:
    driver: bridge
  traefik:
    name: traefik
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# https://immich.app/docs/FAQ/#how-can-i-run-immich-as-a-non-root-user
PUID=1000
GUID=1000
#UPLOAD_LOCATION
#LIBRARY_LOCATION
#BACKUP_LOCATION

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/disk2/immich
BACKUP_LOCATION=/mnt/data/disk2/immich-postgres-backup
LIBRARY_LOCATION=/mnt/data/disk2/immich-static-library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.115.0

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=XXX
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1.
2.
3.
...
