### ISSUE TITLE
Android App Fails to Handle Strong Passwords Correctly

### ISSUE THREAD

**Issue by lukababu** [immich-app/immich#13520]
### The bug

I encountered an issue while trying to log into the Immich Android app using a very strong password generated by my password manager. Although I was able to log into the web UI without any issues using the same credentials, the Android app consistently returned:

> Error logging you in, check server URL, email and password.

The problem I think stems from how the Android app processes or handles complex passwords. My password included a variety of characters, and I used the autofill feature from my password manager, so the likelihood of mistyping was eliminated.

The password: 

> 7bm8kEv6FJ^eWFEaf4ihm

After changing my password to something less complex (less characters, no symbols), I was able to log in successfully through the Android app.

Expected Behavior: The Android app should correctly process and handle strong passwords, matching the behavior of the web UI.

Actual Behavior: The Android app returns a failed login attempt for valid credentials when a very strong password is used, while the web UI logs in successfully.

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS, in Portianer Business Edition 2.21.3

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the stack.env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/immich/iscsi
DB_DATA_LOCATION=/srv/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=NOT_MY_PASSWORD
DB_USERNAME=postgres_luka
DB_DATABASE_NAME=immich_luka
```

### Reproduction steps

1. Using an Administrator account create a new account
2. Toggle the require password change on first log on to off
3. Use a password manager to generate and store a very strong password (including upper/lower case, numbers, symbols)
4. Attempt to log into the Android app using the autofill feature.
5. Try the same credentials in the web UI, which will succeed.
...

### Relevant log output

```shell
[Nest] 17  - 10/17/2024, 2:53:02 AM   DEBUG [Api:LoggingInterceptor~8rqsk87w] GET /api/server/ping 200 0.21ms 10.100.1.1
[Nest] 17  - 10/17/2024, 2:53:02 AM   DEBUG [Api:LoggingInterceptor~gcansn7d] GET /.well-known/immich 200 0.19ms 10.100.1.1
[Nest] 17  - 10/17/2024, 2:53:02 AM   DEBUG [Api:LoggingInterceptor~b1dmrm7p] GET /api/server/ping 200 0.13ms 10.100.1.1
[Nest] 17  - 10/17/2024, 2:53:02 AM    WARN [Api:AuthService~79rn2jet] Failed login attempt for user luka@iremadze.com from ip address 10.100.1.1
[Nest] 17  - 10/17/2024, 2:53:02 AM   DEBUG [Api:LoggingInterceptor~79rn2jet] POST /api/auth/login 201 71.01ms 10.100.1.1
[Nest] 17  - 10/17/2024, 2:53:02 AM VERBOSE [Api:LoggingInterceptor~79rn2jet] {"email":"luka@domain.com","password":"********"}
[Nest] 17  - 10/17/2024, 2:53:02 AM   DEBUG [Api:GlobalExceptionFilter~79rn2jet] HttpException(401): {"message":"Incorrect email or password","error":"Unauthorized","statusCode":401}
```
