### ISSUE TITLE
Sharing picture to AOSP SMS app fails on GrapheneOS Android 15

### ISSUE THREAD

**Issue by Eirikr70** [immich-app/immich#13558]
### The bug

When trying to share a picture to the AOSP SMS app, the SMS app opens but the picture is not sent. I have to download the picture to the phone and then send the picture. I am not capable of saying whether this might be an Immich issue, or an AOSP 15 or GrapheneOS issue so I report it to both Immich and GrapheneOS.

### The OS that Immich Server is running on

GrapheneOS Android 15

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    user: 1000:1000
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /srv/nas/logs:/var/log/immich
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    cpus: "3.5"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#    user: 1000:1000
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    cpus: "3.0"

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always
#    user: 1000:1000
    labels:
      - com.centurylinklabs.watchtower.enable=false

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
#    user: 1000:1000
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    restart: unless-stopped
    env_file:
      - .env
#    user: 1000:1000
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_NUM_KEEP: 7
      BACKUP_DIR: /db_dumps
    volumes:
      - ${DB_DUMPS_LOCATION}:/db_dumps
    depends_on:
      - database

volumes:
#  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/nas/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=PHello !
DB_PASSWORD=Hi !

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/srv/nas/immich-data/postgres
DB_DUMPS_LOCATION=/srv/nas/immich-data/db_dumps

GEOCODING_LOCATION=/srv/nas/immich-data/reverse-geocoding

REDIS_HOSTNAME=immich_redis

LOG_FILE="/var/log/immich/immich_server.log"

#IMMICH_MACHINE_LEARNING_URL=http://192.168.1.102:3003
#IMMICH_MACHINE_LEARNING_ENABLED=true
```

### Reproduction steps

1.Open Immich Android app on GrapheneOS Android 15
2.Tap on a picture
3.Tap on Share
4.Select SMS/MMS (AOSP SMS app)
5.Select a contact
6.The message is empty.
