### ISSUE TITLE
iOS app never finish backup

### ISSUE THREAD

**Issue by an0o0nym** [immich-app/immich#13562]
### The bug

Immich iOS 18.0 mobile app gets stuck at 1 asset remaining.
![IMG_7013](https://github.com/user-attachments/assets/7f9604bd-10a7-439e-ad28-03c8cf78e489)

- Total: 990
- Backup: 989
- Remainder: 1
- Uploading file info: is empty. There is no file name no ID, and Created on seems to be set to some default placeholder date.

The cloud icon on the home screen in the immich app has 'loading circle' always spinning. The upload is stuck at 1 remaining asset. Which I believe may be a bug, cause there is no details about which asset it is, nor it ever starts the upload. 

I've tried different things, from force quiting app, to restarting the server etc, But nothing works.

After some time error came up in the logs about missing asset:

![IMG_7012](https://github.com/user-attachments/assets/3f92b02f-2011-4389-9ad3-e7ded8cb589f)

It would be super nice to be able to click on that 'Remainder' to see a list of what exact assets are being stuck in the queue. [perhaps this could be a feature request?]

But for now, can you point me in some direction on how to debug the issue?

### The OS that Immich Server is running on

Debian 6.1.112-1

### Version of Immich Server

v.1.118.0

### Version of Immich Mobile App

v.1.118.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ports:
      - "2283:2283"
    # extends:
    #  file: hwaccel.transcoding.yml
    #  service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${PATH_TO_DOCKER_DATA}/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    depends_on:
      - immich-redis
      - immich-database
    networks:
      - npm_default
      - immich_default
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich-redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    networks:
      - immich_default
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

 immich-database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${PATH_TO_APPDATA}/immich/postgres:/var/lib/postgresql/data
    networks:
      - immich_default
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

networks:
  npm_default:
    external: true
  immich_default:
    external: true
```

### Your .env content

```Shell
IMMICH_VERSION=v1.118.0

DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich-redis
DB_HOSTNAME=immich-database
```

### Reproduction steps

1. Install Immich
2. Start backup of a 'recent' folder on iPhone
3. Wait until it finishes uploading all files
4.
