### ISSUE TITLE
postgres service is not supporting mounted external disk on raspberry

### ISSUE THREAD

**Issue by Ranadheer-senani** [immich-app/immich#13580]
### The bug

Facing "chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted" error while trying to run immich on external mounted disk.

Disk formatting: "vfat"

### The OS that Immich Server is running on

Raspbian 64 Bit

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library #located on mounted disk
# The location where your database files are stored
DB_DATA_LOCATION=./postgres #located on mounted disk

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zon>
TZ=Asia/Kolkata

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=passw0rd

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Mount an external hard disk on Raspberry Pi
2. Point UPLOAD_LOCATION & DB_DATA_LOCATION on to the mounted disk
3. Docker compose
...

### Relevant log output

```shell
$ sudo docker logs immich_server
Initializing Immich v1.118.2
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [NestFactory] Starting Nest application...
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] ClsModule dependencies initialized +1ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
[Nest] 17  - 10/18/2024, 8:01:56 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
api worker exited with code 1
Initializing Immich v1.118.2
Detected CPU Cores: 4
Starting api worker
Starting microservices worker


$ sudo docker logs immich_postgres
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
```
