### ISSUE TITLE
Repair page is missing from admin sidebar

### ISSUE THREAD

**Issue by polgarc** [immich-app/immich#13638]
### The bug

The `Repair` page is missing from the admin sidebar:

<details>
<summary>screenshot 1</summary>

![image](https://github.com/user-attachments/assets/ee7dc2e0-2206-43d1-8285-be6a16290426)

</details>

Note if I type the proper URL, I can access the page:

<details>
<summary>screenshot 1</summary>

![image](https://github.com/user-attachments/assets/9cc65e93-12c1-4f6a-8e5d-1cf45bc36bc6)

</details>

Or am I missing something and the `Repair` page was moved to somewhere else? The [docs](https://v1.118.2.archive.immich.app/docs/administration/repair-page) says it should be under the admin settings.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
      # file: hwaccel.transcoding.yml
      # service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photo:/mnt/photo
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`immich.mydomain.cc`)"
      - "traefik.http.routers.immich.tls.certresolver=myresolver"
      - "traefik.http.routers.immich.tls=true"
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich
      - traefik_net

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_db
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - immich

  pgadmin:
    image: dpage/pgadmin4
    container_name: immich_pgadmin
    restart: always
    # ports:
      # - "58888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - immich

volumes:
  model-cache:
  db:
  pgadmin-data:
  data:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=10.90.10.20,rw"
      device: ":/volume1/docker/immich"

networks:
  immich:
  traefik_net:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
# The location where your database files are stored
#DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Log in as admin user
2. Go to `Administration` page
3. The `Repair` page is missing from the side bar

### Additional information

Tested with Firefox and Chome - it's the same. Also can't see anything interesting the the server logs.
