### ISSUE TITLE
[GPU] out of GPU resources 

### ISSUE THREAD

**Issue by alakenda** [immich-app/immich#13701]
### The bug

An error occured when immich processes face dection job for about 30000+ photos(The job count is limited to 1), and the processing speed is very slow,plz help!
The possible reason maybe out of GPU memory,how can I solve it?
CLIP Model: XLM-Roberta-Large-Vit-B-16Plus

### The OS that Immich Server is running on

QNAP TS-464C CPU:N5095 Memory: 8G

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    environment:
      IMMICH_VERSION: release
      TZ: Asia/Shanghai
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: xxx
      DB_PASSWORD: xxx
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
    devices:
    - /dev/dri:/dev/dri
    volumes:
      - /share/Container/immich/upload:/usr/src/app/upload
      - /share/Container/immich/geodata:/build/geodata 
      - /share/Container/immich/i18n-iso-countries:/usr/src/app/node_modules/i18n-iso-countries
      - /etc/localtime:/etc/localtime:ro
      - /share/CACHEDEV1_DATA/Photo:/photo
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri

    environment:
      IMMICH_VERSION: release
      TZ: Asia/Shanghai
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: xxx
      DB_PASSWORD: xxx
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
      IMMICH_LOG_LEVEL: debug
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: xxx
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /share/Container/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='xxx' || exit 1; Chksum="$$(psql --dbname='immich' --username='xxx' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1.immich processes face dection job for about 30000+ photos in QNAP
2.
3.
...

### Relevant log output

```shell
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    environment:
      IMMICH_VERSION: release
      TZ: Asia/Shanghai
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: xxx
      DB_PASSWORD: xxx
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
    devices:
    - /dev/dri:/dev/dri
    volumes:
      - /share/Container/immich/upload:/usr/src/app/upload
      - /share/Container/immich/geodata:/build/geodata 
      - /share/Container/immich/i18n-iso-countries:/usr/src/app/node_modules/i18n-iso-countries
      - /etc/localtime:/etc/localtime:ro
      - /share/CACHEDEV1_DATA/Photo:/photo
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri

    environment:
      IMMICH_VERSION: release
      TZ: Asia/Shanghai
      DB_HOSTNAME: immich_postgres
      DB_USERNAME: xxx
      DB_PASSWORD: xxx
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
      IMMICH_LOG_LEVEL: debug
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: xxx
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /share/Container/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='immich' --username='xxx' || exit 1; Chksum="$$(psql --dbname='immich' --username='xxx' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped

volumes:
  model-cache:
```
