### ISSUE TITLE
Unable to connect to the database

### ISSUE THREAD

**Issue by zero617** [immich-app/immich#13720]
### The bug

immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | [Nest] 18  - 10/24/2024, 12:57:10 PM   ERROR [ExceptionHandler] connect ECONNREFUSED 172.21.0.2:5432
immich_server            | Error: connect ECONNREFUSED 172.21.0.2:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
immich_server            | api worker exited with code 1

### The OS that Immich Server is running on

unraid  6.12.13

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: 	ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: 	ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    # healthcheck:
    #   test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
    #   interval: 5m
    #   start_interval: 30s
    #   start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    
  # backup:
  #   container_name: immich_db_dumper
  #   image: prodrigestivill/postgres-backup-local:14
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_HOST: database
  #     POSTGRES_CLUSTER: 'TRUE'
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     SCHEDULE: "@daily"
  #     POSTGRES_EXTRA_OPTS: '--clean --if-exists'
  #     BACKUP_DIR: /db_dumps
  #   volumes:
  #     - /mnt/user/data/immich_backup:/db_dumps
  #   depends_on:
  #     - database

volumes:
  model-cache:

```
```


### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/photo
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/appdata/postgresql14

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

```
```


### Reproduction steps

1.
2.
3.
...


### Relevant log output

```shell
postgres
immich_postgres          | This user must also own the server process.
immich_postgres          | 
immich_postgres          | The database cluster will be initialized with locale "en_US.utf8".
immich_postgres          | The default database encoding has accordingly been set to "UTF8".
immich_postgres          | The default text search configuration will be set to "english".
immich_postgres          | 
immich_postgres          | Data page checksums are enabled.
immich_postgres          | 
immich_postgres          | fixing permissions on existing directory /var/lib/postgresql/data ... ok
immich_postgres          | creating subdirectories ... ok
immich_postgres          | selecting dynamic shared memory implementation ... posix
immich_postgres          | selecting default max_connections ... 100
immich_postgres          | selecting default shared_buffers ... 128MB
immich_postgres          | selecting default time zone ... Etc/UTC
immich_postgres          | creating configuration files ... ok
immich_postgres          | running bootstrap script ... ok
immich_postgres          | performing post-bootstrap initialization ... ok
immich_postgres          | syncing data to disk ... ok
immich_postgres          | 
immich_postgres          | initdb: warning: enabling "trust" authentication for local connections
immich_postgres          | You can change this by editing pg_hba.conf or using the option -A, or
immich_postgres          | --auth-local and --auth-host, the next time you run initdb.
immich_postgres          | 
immich_postgres          | Success. You can now start the database server using:
immich_postgres          | 
immich_postgres          |     pg_ctl -D /var/lib/postgresql/data -l logfile start
immich_postgres          | 
immich_postgres          | waiting for server to start....2024-10-24 12:57:11.205 UTC [49] LOG:  redirecting log output to logging collector process
immich_postgres          | 2024-10-24 12:57:11.205 UTC [49] HINT:  Future log output will appear in directory "log".
immich_postgres          |  done
immich_postgres          | server started
immich_postgres          | CREATE DATABASE
immich_postgres          | 
immich_postgres          | 
immich_postgres          | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
immich_postgres          | 
immich_postgres          | waiting for server to shut down.... done
immich_postgres          | server stopped
immich_postgres          | 
immich_postgres          | PostgreSQL init process complete; ready for start up.
immich_postgres          | 
immich_postgres          | 2024-10-24 12:57:20.856 UTC [1] LOG:  redirecting log output to logging collector process
immich_postgres          | 2024-10-24 12:57:20.856 UTC [1] HINT:  Future log output will appear in directory "log".
```
```


### Additional information

_No response_
