### ISSUE TITLE
Assets automatically moved to trash

### ISSUE THREAD

**Issue by Thloluvin** [immich-app/immich#13731]
### The bug

Hello,

My assest are moved trash bin after a few hours once they have been added. This affects only assets added from an external library. A rescan is doing nothing as the assets still remain in the trash bin. Only removing the library and readding starts scanning and adding again the assets. But a few hours laters the assets are moved again to the trash bin. All Albums are emptied, so it shows that there are 0 Assets inside. Restoring the assets from trash bin is not working, all assets remain there. 
I am running immich about two years and an never had this problem in the past and I thought the problem was caused due to the breaking change in 1.118 and so I updated compose file to the latest version I found on Github.
Since latest version I am running Immich in portainer, this problem was before there and is still present.
I have now deactivated trash features in admin settings and will check now if this problem remains.

BR
Richard

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.118.2

### Version of Immich Mobile App

v1.118.0 build .163

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /path/4_MA-Verein:/usr/src/app/ma:ro
      - /path/5_Musical:/usr/src/app/musical:ro
      - /path/6_KulturhausWartberg:/usr/src/app/khw:ro
      - /path/7_Geburtstage:/usr/src/app/bdays:ro
      - /path/8_Hochzeiten&JGA:/usr/src/app/hochzeit:ro
      - /path/9_Konzerte&Festivals:/usr/src/app/konzerte:ro
      - /path/10_Lanpartys:/usr/src/app/lan:ro
      - /path/11_Lost_Places:/usr/src/app/lostplaces:ro
      - /path/12_Partys:/usr/src/app/partys:ro
      - /path/13_Radfahren:/usr/src/app/radfahren:ro
      - /path/14_Sylvester:/usr/src/app/sylvester:ro
      - /path/15_Urlaube:/usr/src/app/urlaub:ro
      - /path/16_Wandern:/usr/src/app/wandern:ro

    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`immich.domain.eu`)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=http_resolver"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.immich.middlewares=default@file"
    networks:
      - immich
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - immich

volumes:
  model-cache:
networks:
  proxy:
    external: true
  immich:
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_DATA_LOCATION=path/database
DB_DATABASE_NAME=DB_Name
DB_USERNAME=DB_User
DB_PASSWORD=DB_Pass
UPLOAD_LOCATION=/path/upload
LOG_LEVEL=warn
```

### Reproduction steps

1. adding assets 
2. waiting a few hours
3. assets are moved to trash

### Additional information

My immich config:
[immich-config.json](https://github.com/user-attachments/files/17512174/immich-config.json)
