### ISSUE TITLE
Immich is unstable after updating to 1.118.2

### ISSUE THREAD

**Issue by ngosang** [immich-app/immich#13747]
### The bug

I have been running Immich for 2 years and never have any problem like this before.
After updating to 1.118.2 Immich is unstable from the Web and from the Android App. It's unusable.
Sometimes I can't login, sometimes it freezes loading images...
I reviewed the docker-compose for new changes.
I also monitored the Postgres database and it's fine.
I see errors/timeouts in the Immich log related to Postgres, but Postgres is fine. Maybe you are making too heavy queries or something like that... My collection is not tat big, around 12.000 photos.

### The OS that Immich Server is running on

Ubuntu / Running in Docker

### Version of Immich Server

1.118.2

### Version of Immich Mobile App

1.118.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich:
    image: ghcr.io/imagegenius/immich:1.118.2
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DB_HOSTNAME=pgvecto-rs
      - DB_USERNAME=postgres
      - DB_PASSWORD=dfffffffff
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - /root/docker/immich_volume/config:/config
      - /root/docker/immich_volume/photos:/photos
      - /root/docker/immich_volume/import:/import:ro
    ports:
      - 6378:8080
    devices:
       - /dev/dri:/dev/dri # For H/W transcoding
    restart: unless-stopped

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  pgvecto-rs:
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    container_name: pgvecto-rs
    environment:
      - TZ=Europe/Madrid
      - PGTZ=Europe/Madrid
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xxxxxxxxx
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        # this redirects logs to a file instead of stdout
        # '-c',
        # 'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    ports:
      - 5434:5432
    volumes:
      - /root/docker/pgvecto-rs_volume/data:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
.
```

### Reproduction steps

[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RoutesResolver] ViewController {/api/view}:
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 237  - 10/26/2024, 12:48:05 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:8080 [v1.118.2] [production] 
Connection to localhost (::1) 8080 port [tcp/http-alt] succeeded!
Detected CPU Cores: 4
[ig-init] done.
[Nest] 237  - 10/26/2024, 12:48:09 PM     LOG [Api:EventRepository] Websocket Connect:    yzbIknLrafaXArRuAAAB
[10/26/24 12:48:10] INFO     Starting gunicorn 23.0.0                           
[10/26/24 12:48:10] INFO     Listening at: http://0.0.0.0:3003 (253)            
[10/26/24 12:48:10] INFO     Using worker: uvicorn.workers.UvicornWorker        
[10/26/24 12:48:10] INFO     Booting worker with pid: 288                       
Starting microservices worker
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
[Nest] 237  - 10/26/2024, 12:48:17 PM     LOG [Api:SystemConfigService] LogLevel=log (set via system config)
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:ServerService] Feature Flags: {
  "smartSearch": true,
  "facialRecognition": true,
  "duplicateDetection": true,
  "map": true,
  "reverseGeocoding": true,
  "importFaces": false,
  "sidecar": true,
  "search": true,
  "trash": false,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false,
  "email": false
}
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:StorageService] Verifying system mount folder checks (enabled=true)
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:StorageService] Successfully verified system mount folder checks
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:NestFactory] Starting Nest application...
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] OpenTelemetryModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] OpenTelemetryCoreModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] ConfigHostModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] DiscoveryModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] ClsModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] ConfigModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:InstanceLoader] MicroservicesModule dependencies initialized
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:NestApplication] Nest application successfully started
[Nest] 258  - 10/26/2024, 12:48:17 PM     LOG [Microservices:Bootstrap] Immich Microservices is running [v1.118.2] [production] 
[10/26/24 12:48:18] INFO     Started server process [288]                       
[10/26/24 12:48:18] INFO     Waiting for application startup.                   
[10/26/24 12:48:18] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[10/26/24 12:48:18] INFO     Initialized request thread pool with 4 threads.    
[10/26/24 12:48:18] INFO     Application startup complete.                      
[Nest] 237  - 10/26/2024, 12:48:20 PM     LOG [Api:EventRepository] Websocket Disconnect: yzbIknLrafaXArRuAAAB
[Nest] 237  - 10/26/2024, 12:48:21 PM     LOG [Api:EventRepository] Websocket Connect:    qsah7d7GFMvOaTc8AAAD
[Nest] 237  - 10/26/2024, 12:48:32 PM     LOG [Api:EventRepository] Websocket Connect:    beoOD4D-SZH7rfhTAAAF
[Nest] 237  - 10/26/2024, 12:49:07 PM   ERROR [Api:GlobalExceptionFilter~spv26twb] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:50:12 PM   ERROR [Api:GlobalExceptionFilter~qqoyqppk] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:55:20 PM   ERROR [Api:GlobalExceptionFilter~ggl5nxpl] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:55:30 PM   ERROR [Api:GlobalExceptionFilter~g7kcuqlb] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:55:30 PM   ERROR [Api:GlobalExceptionFilter~7g8omkme] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:55:36 PM     LOG [Api:EventRepository] Websocket Disconnect: beoOD4D-SZH7rfhTAAAF
[Nest] 237  - 10/26/2024, 12:56:32 PM   ERROR [Api:GlobalExceptionFilter~0punu9fh] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:56:36 PM   ERROR [Api:GlobalExceptionFilter~s1xqueqf] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:56:42 PM     LOG [Api:EventRepository] Websocket Connect:    TeKrU-30_bUHMCK4AAAH
[Nest] 237  - 10/26/2024, 12:57:59 PM   ERROR [Api:GlobalExceptionFilter~hnks9b9p] Unknown error: Error: Connection terminated due to connection timeout
[Nest] 237  - 10/26/2024, 12:58:30 PM     LOG [Api:EventRepository] Websocket Disconnect: TeKrU-30_bUHMCK4AAAH
[Nest] 237  - 10/26/2024, 12:58:30 PM   ERROR [Api:GlobalExceptionFilter~o1bz71kg] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:58:33 PM   ERROR [Api:GlobalExceptionFilter~hmiiksod] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:58:33 PM   ERROR [Api:GlobalExceptionFilter~g3pa5jpa] Unknown error: Error: connect EHOSTUNREACH 172.18.0.17:5432
[Nest] 237  - 10/26/2024, 12:58:36 PM   ERROR [Api:GlobalExceptionFilter~if8sdjsp] Unknown error: Error: Connection terminated due to connection timeout
[Nest] 237  - 10/26/2024, 12:58:36 PM   ERROR [Api:GlobalExceptionFilter~bstpycb7] Unknown error: Error: Connection terminated due to connection timeout
