### ISSUE TITLE
Sync status not updating correctly

### ISSUE THREAD

**Issue by palitu** [immich-app/immich#13769]
### The bug

I have a number of images (and videos) on the android app, that are showing as not sync'd to the cloud, but are visible through the web client. I have attached screenshots.

The backup screen is also showing weird numbers that do not make sense.

It is potentially because i have copied files into the camera directory (the only directory sync'd), from dates in the past.  It seems like these are primarily the ones not being sync'd, but i have not confirmed that.

I have also found all the assets showing as not sync'd and performed an "upload" through the android app.  whilst these now show in the web client, they are still not showing as sync'd in the android app.

![Screenshot_20241028-105804](https://github.com/user-attachments/assets/48b7a628-3b04-4865-9d54-339a228b0861)

![ksnip_20241028-105916](https://github.com/user-attachments/assets/8c61ff2c-29c6-478b-81cd-4ed4a0472f4d)

![Screenshot_20241028-110116](https://github.com/user-attachments/assets/936c5c4e-dce0-4243-9cce-24c2ea56d641)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.114.0

### Version of Immich Mobile App

v1.118.0 build.163

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always


  immich-redis:
    container_name: immich-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
  immich-postgres:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      -  ./immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-machine-learning:
    container_name: immich-ML
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./immich/model-cache:/cache
    env_file:
      - .env
    restart: always
```

### Your .env content

```Shell
##########################################
# IMMICH
#########################################
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich-redis

UPLOAD_LOCATION=/home/xxx/appdata/immich/uploads

JWT_SECRET=xxxxx


# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=


# This is the URL of your vm/server where you host Immich, so that the web frontend
# know where can it make the request to.
# For example: If your server IP address is 10.1.11.50, the environment variable will
# be VITE_SERVER_ENDPOINT=http://10.1.11.50:2283
VITE_SERVER_ENDPOINT=http://192.xx.1.xx:xx/api

# Typesense
TYPESENSE_API_KEY=xxxx
# TYPESENSE_ENABLED=false

DISABLE_REVERSE_GEOCODING=true
# REVERSE_GEOCODING_PRECISION=3

# IMMICH_API_URL_EXTERNAL=https://immich.xxxxx.com
```

### Reproduction steps

unknown.  potentially copying in old assets to the sync folder.
