### ISSUE TITLE
Public shared links call /api/shared-links/me endpoint which returns email address of album owner

### ISSUE THREAD

**Issue by chris114782** [immich-app/immich#13823]
### The bug

If I share an album publicly using the shared link system and a user visits the link, their browser hits the API endpoint /api/shared-links/me with a key as a query string parameter.

That endpoint returns album details including the album owner object.

The album owner object contains the email address of the owner, this is sensitive information and users (or at least, me) don't want it publicly exposed to people I share my albums with.

```json
{
	"owner": {
		"id": "20289577-c3ff-4da2-b81e-94ad7d38a2d7",
		"email": "c***********@g******l.com",
		"name": "Chris",
		"profileImagePath": "upload/profile/20289577-c3ff-4da2-b81e-94ad7d38a2d7/9e0f61a8-7a09-4135-8329-4aa9a22cfb2e.png",
		"avatarColor": "amber",
		"profileChangedAt": "2024-09-26T18:04:04.947Z"
	}
}
```

Consider changing this endpoint to not include more than the minimum information required to render the page.

### The OS that Immich Server is running on

Ubuntu 24.04 (docker 27.2.0)

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - ingress
      - photos
      - monitoring

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - photos

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    networks:
      - photos

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - photos

  db_backup:
    image: prodrigestivill/postgres-backup-local:14
    user: 1001:1001
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: '@daily'
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /backups/immich_db_dumps
      TZ: Europe/London
    volumes:
      - backups:/backups
    depends_on:
      - database
    networks:
      - photos

networks:
  photos:
    driver: bridge
  monitoring:
    external: true
  ingress:
    external: true

volumes:
  model-cache:
  backups:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/storage/immich/library
IMMICH_VERSION=release
DB_PASSWORD=***redacted***
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/mnt/storage/immich/database
REDIS_HOSTNAME=immich_redis
IMMICH_TELEMETRY_INCLUDE=all
```

### Reproduction steps

1. Create an album in Immich
2. Create a public sharing link for the album
3. View the album in a browser whle not signed in to Immich
4. Inspect the API calls in the browser's dev toolbar
5. Look at the call to /api/shared-links/me
...
