### ISSUE TITLE
When deleting in batches in the mobile recycle bin logic is reversed.

### ISSUE THREAD

**Issue by NiuHK** [immich-app/immich#13828]
### The bug

When deleting in batches in the mobile recycle bin, the selected items will be retained but the unselected items will be deleted. The logic is reversed.

### The OS that Immich Server is running on

windows docker with wsl2

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

v1.119.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Select in the mobile recycle bin and click on batch delete
2. Delete all unselected items and keep the selected items

### Relevant log output

```shell
## the total log is attaxhed behind
2024-10-30 14:12:24.328081 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: Exception: Asset at index 22 does no longer exist in database
Library: widgets library
Context: Instance of 'ErrorDescription' |
#0      RenderList.loadAsset (package:immich_mobile/widgets/asset_grid/asset_grid_data_structure.dart:123)
#1      GalleryViewerPage.build (package:immich_mobile/pages/common/gallery_viewer.page.dart:64)
#2      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:476)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729)
#4      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:539)
#5      HookElement.build (package:flutter_hooks/src/framework.dart:438)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5333)
#9      BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693)
#10     BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176)
#17     _invoke (dart:ui/hooks.dart:312)
#18     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419)
#19     _drawFrame (dart:ui/hooks.dart:283)


2024-10-30 13:46:20.698059 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: Null check operator used on a null value
Library: image resource service
Context: Instance of 'ErrorDescription' |
#0      ImageCache._checkCacheSize (package:flutter/src/painting/image_cache.dart:517)
#1      ImageCache._touch (package:flutter/src/painting/image_cache.dart:294)
#2      ImageCache.putIfAbsent.listener (package:flutter/src/painting/image_cache.dart:429)
#3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:755)
#4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:1105)
#5      MultiImageStreamCompleter._decodeNextFrameAndSchedule (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:154)
<asynchronous suspension>

2024-10-30 13:46:06.810389 | SEVERE   | ImmichErrorLogger    | FlutterError - Catch all | Instance of 'FlutterErrorDetails'
Exception: Null check operator used on a null value
Library: image resource service
Context: Instance of 'ErrorDescription' |
#0      ImageCache._checkCacheSize (package:flutter/src/painting/image_cache.dart:517)
#1      ImageCache._touch (package:flutter/src/painting/image_cache.dart:294)
#2      ImageCache.putIfAbsent.listener (package:flutter/src/painting/image_cache.dart:429)
#3      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:755)
#4      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:1105)
#5      MultiImageStreamCompleter._decodeNextFrameAndSchedule (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:154)
<asynchronous suspension>
```

### Additional information

none
[log.zip](https://github.com/user-attachments/files/17574649/log.zip)
