### ISSUE TITLE
Bug on iOS App: Scrolling in search results leads to refresh

### ISSUE THREAD

**Issue by github-cli** [immich-app/immich#13869]
### The bug

In the iOS mobile app, if you scroll to the bottom of search results, the page refreshes on its own and brings you to the beginning of the results again, this makes it difficult to see the last few results. it almost always happens when scrolling immediately to the bottom, if it does not, one more scroll does the trick then.

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

v2.119.1

### Version of Immich Mobile App

v1.119.0 build.181

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich
services:
  immich-server:
    container_name: immich_server
    hostname: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    shm_size: 2G
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/sda/+Photos:/ext-library/Photos:rw
      - ./vols/config:/config
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      swag4:
      immich-shared:
      macvlan8:
 
  immich-machine-learning:
    container_name: immich_machine_learning
    hostname: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    shm_size: 1g
    volumes:
      - /mnt/sda/+DockerVolumes/immich/model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      immich-shared:
        aliases:
          - immshrd-machine-learning
      macvlan8:

  redis:
    container_name: immich_redis
    volumes:
      - ./vols/redis/data:/data
    hostname: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      immich-shared:
  database:
    container_name: immich_postgres
    hostname: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo ">
      interval: 5m
      start_interval: 30s
      start_period: 30s
    shm_size: 1g
    volumes:
      - /mnt/sda/+DockerVolumes/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      immich-shared:

include:
  - /data/docker/netconf.yml
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/sda/+DockerVolumes/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# Additional variables from https://immich.app/docs/install/environment-variables
###################################################################################
TZ=Europe/Zurich
EXTERNAL_PATH=/ext-library/
#IMMICH_CONFIG_FILE=/config/immich.conf
#LOG_LEVEL=verbose
```

### Reproduction steps

1. Search for anything in the mobile app
2. scroll down to the bottom of the search results
3. scroll down just a little further
...
