### ISSUE TITLE
 image error jpg 

### ISSUE THREAD

**Issue by seancork** [immich-app/immich#13860]
### The bug

since 1.118 version my images taken with my phone (jpg) wont load the images on Immich. still happening on newest version, only fix for me right now is to downgrade to 1.117 and it works fine(images are not corrupted).

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

1.119.0 build.164

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.y                  ml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/maindrive/photos:/mnt/maindrive/photos:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the imag                  e tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda

    labels:
      - com.centurylinklabs.watchtower.enable=false
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://                  immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for a                  ccelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31                  ca2ca48c79536c0de82
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5a                  b410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
volumes:
  model-cache: null
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://imm>

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/maindrive/immichData/library

# The Immich version to use. You can pin this to a specific version like "v1.71>
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###############################################################################>
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/mnt/maindrive/immichData/db
```

### Reproduction steps

After taking image with my phone I upload using Photosync and it wont show the image then on immich its just broken

### Relevant log output

```shell
immich_server | [Nest] 7 - 10/30/2024, 6:51:12 PM ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file has corrupt header: VipsJpeg: ./lib/jpegli/decode_marker.cc:417: Invalid ICC chunk order.

immich_server | [Nest] 7 - 10/30/2024, 6:51:12 PM ERROR [Microservices:JobService] Error: Input file has corrupt header: VipsJpeg: ./lib/jpegli/decode_marker.cc:417: Invalid ICC chunk order.
```

### Additional information

example image from my phone(nothing 2a)
![IMG_20241030_200839581](https://github.com/user-attachments/assets/aa596350-0dfd-4d87-ad81-abcb3f6e06aa)
