### ISSUE TITLE
Sync Progress Bar jumping up and down in Android app

### ISSUE THREAD

**Issue by cstmth** [immich-app/immich#13894]
### The bug

The progress bar is jumping up and down. 

Video: https://github.com/user-attachments/assets/e98de499-e42c-40f1-a1c3-20a7a79960cb

The uploads appear to work, but I don't know whether this is cause for concern and whether the actual uploading is slower (i.e. it's a visual bug) or if there are some actual issues.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

1.119.0 build.164

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/Immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/Immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Enable sync in mobile app

### Relevant log output

```shell
immich_server            | [Nest] 17  - 11/03/2024, 12:01:26 PM     LOG [Api:EventRepository] Websocket Disconnect: 4moYcKub29AABhUmAACm
immich_server            | [Nest] 17  - 11/03/2024, 12:40:00 PM     LOG [Api:EventRepository] Websocket Connect:    JdCFIEOXcgQVobHiAACo
immich_server            | [Nest] 17  - 11/03/2024, 12:57:02 PM     LOG [Api:EventRepository] Websocket Disconnect: JdCFIEOXcgQVobHiAACo
immich_server            | [Nest] 17  - 11/03/2024, 12:57:03 PM     LOG [Api:EventRepository] Websocket Connect:    YhfvYKQEaCfndmbYAACq
immich_server            | [Nest] 17  - 11/03/2024, 12:57:04 PM     LOG [Api:EventRepository] Websocket Disconnect: YhfvYKQEaCfndmbYAACq
immich_server            | [Nest] 17  - 11/03/2024, 12:57:06 PM     LOG [Api:EventRepository] Websocket Connect:    J5pcawlVSKqzIfNKAACs
immich_server            | [Nest] 17  - 11/03/2024, 12:58:02 PM     LOG [Api:EventRepository] Websocket Disconnect: J5pcawlVSKqzIfNKAACs
immich_server            | [Nest] 17  - 11/03/2024, 12:59:03 PM     LOG [Api:EventRepository] Websocket Connect:    ENJF0_ZYwuZib64ZAACu
immich_server            | [Nest] 17  - 11/03/2024, 12:59:09 PM     LOG [Api:EventRepository] Websocket Disconnect: ENJF0_ZYwuZib64ZAACu
immich_server            | [Nest] 17  - 11/03/2024, 12:59:19 PM     LOG [Api:EventRepository] Websocket Connect:    d3U_CRK-H0Tipp74AACw
immich_server            | [Nest] 17  - 11/03/2024, 1:00:41 PM     LOG [Api:EventRepository] Websocket Connect:    ALCDh2T6dP4KhsMaAACy
```

### Additional information

It might be relevant that both the database and the library folders are mounted as Samba network shares. It general, it is working absolutely perfectly and the logs do not imply any issues with it but I thought I'd mention it anyway.
