### ISSUE TITLE
Map is not working properly in web

### ISSUE THREAD

**Issue by davydes** [immich-app/immich#13959]
### The bug

Map page suddenly stop working. Seems browser can't fetch external resources.

![image](https://github.com/user-attachments/assets/7eed2978-1ed3-462f-9488-303f06133876)
![image](https://github.com/user-attachments/assets/0c130f58-e529-4499-a43c-d9c1ab12c116)

Why does it depend on external resources? Could it work fully offline?

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

v1.119.1

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}    
    restart: unless-stopped
    environment:
      DB_PASSWORD: <redacted>
      DB_USERNAME: <redacted>
      DB_DATABASE_NAME: <redacted>
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    volumes:
      - type: volume
        source: appdata
        target: /usr/src/app/upload
        volume:
          nocopy: true
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database

  ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '4'
    volumes:
      - model-cache:/cache
```

### Your .env content

```Shell
IMMICH_VERSION=v1.119.1
```

### Reproduction steps

1. Open "Map" page

### Relevant log output

```shell
entry.Cv4Sd8Jo.js:1 
https://tiles.immich.cloud/v1/style/dark.json net::ERR_TIMED_OUT
```
