### ISSUE TITLE
ARW images not showing in Android App

### ISSUE THREAD

**Issue by BlazeCodeDev** [immich-app/immich#13998]
### The bug

.arw (Sony raw) images are not showing in the Android App. It's working in Browser 

![Screenshot_20241107-104112](https://github.com/user-attachments/assets/38c989cb-41ff-4267-9a19-0ce963f1bfc0)
![Screenshot_20241107-104107](https://github.com/user-attachments/assets/301895cb-22c6-405d-9326-b2f2301eeafd)
![Screenshot_20241107-104059](https://github.com/user-attachments/assets/71c1b343-e586-4f41-aa70-ace6dbf092ac)

### The OS that Immich Server is running on

Ubuntu Server 22.04.5 LTS

### Version of Immich Server

1.120.1

### Version of Immich Mobile App

1.119.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - /mnt/smb_share/Immich:/usr/src/app/upload

      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5

    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - stack.env



volumes:
  model-cache:
```

### Your .env content

```Shell
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=redacted
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_URL=http://192.168.178.21:2283
IMMICH_API_KEY=redacted
```

### Reproduction steps

1. Open any .ARW file on android
