### ISSUE TITLE
Update reminder opens on all browsers when a new connection is made.

### ISSUE THREAD

**Issue by AdamT20054** [immich-app/immich#14009]
### The bug

If you have Immich open on a desktop browser, opening the mobile app will trigger the update reminder popup on the desktop browser. If multiple tabs have Immich open, and you open the mobile app, the popup will trigger on all of the browser tabs.

I discovered this while logged into the same immich account. I am on v1.117.0, I plan on upgrading to the latest version later today and will test if the bug is still occuring.

### The OS that Immich Server is running on

Debian LXC

### Version of Immich Server

v1.117.0

### Version of Immich Mobile App

v1.19.0 build.164

### Platform with the issue

- [ ] Server
- [X] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning

    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=***
DB_DATA_LOCATION=***
IMMICH_VERSION=release
DB_PASSWORD=***
DB_USERNAME=***
DB_DATABASE_NAME=***
NVIDIA_VISIBLE_DEVICES=all
```

### Reproduction steps

1. Open immich on a desktop browser
2. Open immich on the mobile browser
3. If you're not on the latest Immich Server version, the update reminder popup will trigger when any new connection to immich is made (either by opening the mobile app, or openning immich in another tab.
...

### Additional information

Not running latest verson, will re-test with the latest version later on.
