### ISSUE TITLE
Database Backup Failure

### ISSUE THREAD

**Issue by laneyweb** [immich-app/immich#14021]
### The bug

I have a new instance of Immich running on a Ubuntu host. All is working well. Thank you!

However, in the logs I see that the DB backup fails each night. I can see the following error:

[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn pg_dumpall ENOENT] Backup failed with error
[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn pg_dumpall ENOENT] Database Backup Failure
[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:BackupService] Gzip exited with code 0 but pgdump exited with -2

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

v1.119.0 164

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1024
      - PGID=100
      - TZ=Europe/London
      - DB_HOSTNAME=postgres_immich
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis_immich
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /root/docker/immich/config:/config
      - /mnt/jellyfin/immich:/photos
      - /mnt/jellyfin/Photos:/mnt/photos #optional
    ports:
      - 2283:8080
    restart: unless-stopped
  # This container requires an external application to be run separately.
  # By default, ports for the databases are opened, be careful when deploying it
  # Redis:
  redis:
    image: redis
    #    ports:
    #      - 6379:6379
    container_name: redis_immich
  # PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    #    ports:
    #      - 5432:5432
    container_name: postgres_immich
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /root/docker/immich/data:/var/lib/postgresql/data
networks: {}
```

### Your .env content

```Shell
within above (all in one).
```

### Reproduction steps

1. View Server logs. 
2. Each night at 2am, the failure is logged.

### Relevant log output

```shell
[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn pg_dumpall ENOENT] Backup failed with error
[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:Error: spawn pg_dumpall ENOENT] Database Backup Failure
[Nest] 199  - 11/08/2024, 2:00:00 AM   ERROR [Microservices:BackupService] Gzip exited with code 0 but pgdump exited with -2
```
