### ISSUE TITLE
Hostname ignored in DB_URL

### ISSUE THREAD

**Issue by serge005** [immich-app/immich#14040]
### The bug

When using [Pre-existing Postgres](https://immich.app/docs/administration/postgres-standalone/), instructions state to set the following env variable:
DB_URL='postgresql://immichdbusername:immichdbpassword@postgreshost:postgresport/immichdatabasename'

However, immich_server ignores the hostname set in the connection string and tries to connect to hostname 'database'. I had to set my postgres server to respond to the alias 'database' to get it working.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

latest

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
IMMICH_VERSION=release
IMMICH_LOG_LEVEL=verbose
UPLOAD_LOCATION=/immich/library
REDIS_HOSTNAME=redis
DB_URL='postgresql://immich:PASSWORD@postgres:5432/immich'
```

### Reproduction steps

1. Set DB_URL hostname
2. View immich_server logs
3. Note that it is trying to connect to host 'database' and not 'postgres' per connection string
