### ISSUE TITLE
Website not working when DB on NFS share

### ISSUE THREAD

**Issue by JuSenshi** [immich-app/immich#14054]
### The bug

When installing Immich via Docker, i populated the .env file with (besides others) the following values:
```
UPLOAD_LOCATION=/mnt/nfs/immich/library
DB_DATA_LOCATION=/mnt/nfs/immich/postgres
```
The path /mnt/nfs/immich is a NFS mount to another server, my fstab:
`<redacted_ip-adress>:/shared_pool/immich /mnt/nfs/immich nfs auto 0 0`
All the following directories have rights 777:
```
/shared_pool on NFS server
/shared_pool/immich on NFS server
/mnt/nfs on Immich VM
/mnt/nfs/immich on Immich VM
```
If i don't have the rights setup like this, i get an error when doing `docker compose up -d,` saying that it cant `chown /mnt/nfs/immich/postgres`

When i now start the system, i can't access with `<ip-adress>:2283` in browser, i get an `ERR_CONNECTION_REFUSED`
I am not sure if it is a "security feature" because it doesn't want the postgresql DB reachable/with wrong rights but on the other hand it doesn't work without the rights setup like this.

### The OS that Immich Server is running on

Ubuntu 24.04.01

### Version of Immich Server

v1.120.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/nfs/immich/library
DB_DATA_LOCATION=/mnt/nfs/immich/postgres

TZ=Europe/Berlin

IMMICH_VERSION=release

DB_PASSWORD=<redacted>

###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Connect to NFS share via /etc/fstab
2. Change rights of said directory to 777
3. Reboot system
4. Install Immich via docker-compose.yml and .env file, changing the data and db paths to the share
5. Launch browser and try to access the website
