### ISSUE TITLE
cyrillic folder and file names are not displayed/imported into the library

### ISSUE THREAD

**Issue by LWoBTbl** [immich-app/immich#14063]
### The bug

cyrillic folder and file names are not displayed, the library scan runs with multiple error messages, web interface folder view does not display the file and folders with Cyrillic chars.

### The OS that Immich Server is running on

ghcr.io/immich-app/immich-server

### Version of Immich Server

1.119.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - foto:/Library
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
     resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities:
              - gpu
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
  foto:
    driver: local
    driver_opts:
      type: cifs
      o: username=username,password=password,uid=1000,gid=1000,file_mode=0775,dir_mode=0775
      device: //server/Foto
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Etc/GMT+4

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

IMMICH_LOG_LEVEL=log
```

### Reproduction steps

1. enable folder view - http://localhost:2283/user-settings?isOpen=feature+folders
2. go to folder view - http://localhost:2283/folders
3. see that Cyrillic directories and files are missing

### Relevant log output

```shell
2024-11-10 23:32:21 [Nest] 7  - 11/10/2024, 11:32:21 PM   ERROR [Microservices:LibraryService] File not found: /Library/20181230_172546 - ???? ? ????? ? ?????? ?????.mp4
2024-11-10 23:32:39 [Nest] 7  - 11/10/2024, 11:32:39 PM   ERROR [Microservices:LibraryService] File not found: /Library/??????????? 005.jpg
2024-11-10 23:32:39 [Nest] 7  - 11/10/2024, 11:32:39 PM   ERROR [Microservices:LibraryService] File not found: /Library/??????????? 009.jpg
2024-11-10 23:32:39 [Nest] 7  - 11/10/2024, 11:32:39 PM   ERROR [Microservices:LibraryService] File not found: /Library/??????????? 007.jpg
2024-11-10 23:32:39 [Nest] 7  - 11/10/2024, 11:32:39 PM   ERROR [Microservices:LibraryService] File not found: /Library/??????????? 011.jpg
```
