### ISSUE TITLE
Immich won't start after clearing backup directory

### ISSUE THREAD

**Issue by dsm1212** [immich-app/immich#14109]
### The bug

This may just be a clarification and not a bug, I just don't see a reason for it. As I was setting up backups and trying to get my docker config correct, I caused the system to try to start from a new backup directory. After that immich would not start. I had cat the file earlier in a shell window so I recreated it. Why does this prevent startup and did putting back the old file (which looks like it contains a timestamp?) cause me to have an incomplete backup? I must have originally started immich with backups enabled the first time and an empty folder because I use a immich config editted via shell. So there must be some backup "info" stored outside the backup folder that says there was a prior backup and that triggers the requirement for the existance of the file. I'm curious why this behavior exists and what it is doing for me? I don't think the backups are incremental are they?

### The OS that Immich Server is running on

debian

### Version of Immich Server

1.120.2

### Version of Immich Mobile App

1.120.1 build 183

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    network_mode: svcnet
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload                               #SKIP_BACKUP
      - /etc/localtime:/etc/localtime:ro                                     #SKIP_BACKUP
      - /media/pictures/McAfee-Belles:/media/pictures/McAfee-Belles:ro       #SKIP_BACKUP
      - /media/pictures/uploads:/media/pictures/uploads                      #SKIP_BACKUP
      - /media/pictures/immich:/media/pictures/immich                        #SKIP_BACKUP
      - /media/pictures/Grace/Pictures:/media/pictures/Grace:ro              #SKIP_BACKUP
      - /media/pictures/Andrew/Pictures:/media/pictures/Andrew:ro            #SKIP_BACKUP
      - /media/pictures/Nicholas/Pictures:/media/pictures/Nicholas:ro        #SKIP_BACKUP
      - /backups:/backups                                                    #SKIP_BACKUP
      - /apps/immich:/apps/immich
    user: "1030:1001"
#    ports:
#      - 2283:3001
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    network_mode: svcnet
    user: "1030:1001"
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always

  redis:
    container_name: immich_redis
    hostname: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    network_mode: svcnet
    user: "1030:1001"
    volumes:
      - redisdata:/data
      - /etc/passwd:/etc/passwd:ro                             #SKIP_BACKUP
    restart: always

  database:
    container_name: immich_postgres
    hostname: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    network_mode: svcnet
    env_file:
      - immich.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    user: "1030:1001"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro                              #SKIP_BACKUP
    restart: always

volumes:
  model-cache:
  redisdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/unsafe/immich
DB_DATA_LOCATION=/apps/immich/postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

IMMICH_CONFIG_FILE=/apps/immich/immich.config

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<redacted>
DB_PASSWORD=<redacted>

TZ=America/New_York

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

Let immich backup run
Stop immich
clear the backup folder of all contents including .immich file.
Start immich 
<observe that it won't start due to error opening .immich file>
