### ISSUE TITLE
Lines appear at some photos on the web view

### ISSUE THREAD

**Issue by 1Euro7Cent** [immich-app/immich#14229]
### The bug

Some images have wiered lines across the whole image. These lines are only when viewing the file on the web. The lines are gone after downloading it
https://github.com/user-attachments/assets/b1b5fac1-5ab3-4c55-baeb-a8c1b5a45df2

### The OS that Immich Server is running on

Unraid 6.12.13 in a docker

### Version of Immich Server

1.120.2

### Version of Immich Mobile App

1.120.2 build.167

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  #immich-microservices:
  #  container_name: immich_microservices
  #  image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
  #  command: [ "start.sh", "microservices" ]
  #  volumes:
  #    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #    - /etc/localtime:/etc/localtime:ro
  #  env_file:
  #    - .env
  #  depends_on:
  #    - redis
  #    - database
  #  restart: always

#  immich-machine-learning:
#    container_name: immich_machine_learning
#    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#    volumes:
#      - model-cache:/cache
#    env_file:
#      - .env
#    restart: always

  redis:
    container_name: immich_redis
    #image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/images/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=removed for reasons
DB_PASSWORD=removed for reasons

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

DB_DATA_LOCATION=/mnt/user/images/db
```

### Reproduction steps

Don't know exact steps, but upload the image below. And then view it on the web.

![20241114_193710](https://github.com/user-attachments/assets/01ce9ac9-f3f9-4d1d-8535-c2b5140ff868)
