### ISSUE TITLE
Server does not accept connections

### ISSUE THREAD

**Issue by sbogomolov** [immich-app/immich#14230]
### The bug

I have deployed immich using official Help charts. The relevant section of the flux's `HelmRelease` manifest is pasted below. I have also pasted the complete immich-server log output. All volumes and secrets are found and mounted correctly, there are no errors anywhere. However startup probe fails because immich-server does not accept connections.

I tried to forward ports to the container and connect with `telnet` - connection succeeds and than gets closed immediately.
```
$ telnet localhost 2283
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

### The OS that Immich Server is running on

k8s

### Version of Immich Server

v1.119.0

### Version of Immich Mobile App

none

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
valuesFrom:
  - kind: Secret
    name: immich-config
    valuesKey: redis-password
    targetPath: env.REDIS_PASSWORD
  - kind: Secret
    name: immich-config
    valuesKey: redis-password
    targetPath: redis.auth.password
  - kind: Secret
    name: immich-config
    valuesKey: db-password
    targetPath: postgresql.global.postgresql.auth.password
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
    postgresql:
      enabled: true
      primary:
        persistence:
          existingClaim: immich-postgres-pvc
    redis:
      enabled: true
      auth:
        enabled: true
      master:
        persistence:
          existingClaim: immich-redis-pvc
    server:
      ingress:
        main:
          enabled: false
    machine-learning:
      persistence:
        cache:
          type: pvc
          existingClaim: immich-machine-learning-cache-pvc
```

### Your .env content

```Shell
none
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
Initializing Immich v1.119.0                                                                                                                                                                                        
Detected CPU Cores: 5                                                                                                                                                                                               
Starting api worker                                                                                                                                                                                                 
Starting microservices worker                                                                                                                                                                                       
[Nest] 7  - 11/19/2024, 7:17:47 PM     LOG [Microservices:EventRepository] Initialized websocket server                                                                                                             
[Nest] 7  - 11/19/2024, 7:17:47 PM     LOG [Microservices:MapRepository] Initializing metadata repository                                                                                                           
[Nest] 17  - 11/19/2024, 7:17:48 PM     LOG [Api:EventRepository] Initialized websocket server
```
