### ISSUE TITLE
Error when editing face assignments from within photos

### ISSUE THREAD

**Issue by Dulanic** [immich-app/immich#14239]
### The bug

When I am viewing a photo, and clicking to edit the people tagged, I can select an exiting person, but when I click done, it does not save and shows this error:

![image](https://github.com/user-attachments/assets/ea41fd38-144b-44e2-b8a0-179768a85d2f)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.120.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - DB_HOSTNAME=postgres
      - DB_USERNAME=*redacted*
      #- DB_PORT=5433
      - DB_PASSWORD=*redacted*
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis_immich
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - ./immich:/config
      - /mnt/tank/immich:/photos
      - /mnt/tank/photos/originals:/import:ro #optional
    ports:
      - 8187:8080
    depends_on:
      - redis_immich
    restart: unless-stopped

  redis_immich:
    image: redis
    ports:
      - 6379:6379
    container_name: redis_immich

  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    ports:
      - 5433:5432
    container_name: postgres
    environment:
      POSTGRES_USER: *redacted*
      POSTGRES_PASSWORD: *redacted*
      POSTGRES_DB: immich
    volumes:
      - ./postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
DB_PASSWORD=*redacted*
PUID=1000
HOSTNAME=e04dbfd14659
S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0
LANGUAGE=en_US.UTF-8
DB_HOSTNAME=postgres
PWD=/
DB_DATABASE_NAME=immich
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
NODE_ENV=production
TZ=America/Chicago
TRANSFORMERS_CACHE=/config/machine-learning/models
HOME=/root
LANG=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:
PGID=1000
VIRTUAL_ENV=/lsiopy
IMMICH_BUILD_DATA=/app/immich/server
IMMICH_MEDIA_LOCATION=/photos
S6_VERBOSITY=1
S6_STAGE2_HOOK=/docker-mods
IMMICH_PORT=8080
DB_USERNAME=immich
MACHINE_LEARNING_WORKERS=1
REDIS_HOSTNAME=redis_immich
TERM=xterm
IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003
SHLVL=1
MACHINE_LEARNING_WORKER_TIMEOUT=120
IMMICH_ENV=production
MACHINE_LEARNING_CACHE_FOLDER=/config/machine-learning/models
PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

### Reproduction steps

1. Click on a photo /w identified faces that are unassigned.
2. Press "Edit People" pencil icon.
3. Click the pencil next to the face you want to assign.
4. Search for face to assign and select.
5. Press done

### Relevant log output

```shell
immich  | [Nest] 180  - 11/19/2024, 5:50:06 PM   DEBUG [Api:LoggingInterceptor~oviag3hf] GET /api/people/7891d3ae-a018-4dc2-9cfe-138cc4f36644/thumbnail?updatedAt=2024-09-11T11%3A54%3A13.486Z 304 2.20ms 47.187.158.65
immich  | [Nest] 180  - 11/19/2024, 5:50:21 PM   DEBUG [Api:LoggingInterceptor~zyzn5r2j] GET /api/search/person?name=S 200 2.43ms 47.187.158.65
immich  | [Nest] 180  - 11/19/2024, 5:50:26 PM   DEBUG [Api:LoggingInterceptor~5f85usrg] PUT /api/faces/c3abdb3c-5b16-4009-957b-21a1bd11b48b 200 3.84ms 47.187.158.65
immich  | [Nest] 180  - 11/19/2024, 5:50:26 PM VERBOSE [Api:LoggingInterceptor~5f85usrg] {"id":"317ef7b1-fdaa-436e-8c3d-4c2bd31888b6"}
immich  | [Nest] 180  - 11/19/2024, 5:50:26 PM   DEBUG [Api:GlobalExceptionFilter~5f85usrg] HttpException(400): {"message":"Not found or no person.create access","error":"Bad Request","statusCode":400}
immich  | [Nest] 180  - 11/19/2024, 5:50:26 PM   DEBUG [Api:LoggingInterceptor~fan5e5yg] GET /api/assets/821080b8-1179-44b6-a801-372c62bd72b6 200 26.75ms 47.187.158.65
```

### Additional information

I use a shared library, but I tried it with both users, just to be sure that wasnt the problem.
