### ISSUE TITLE
Error: heif: Unsupported feature: Unsupported color conversion (4.3003)

### ISSUE THREAD

**Issue by flosoft** [immich-app/immich#14316]
### The bug

Immich seems to have issues with the 200MP photos from my Samsung Galaxy S24.
The picture has been uploaded directly to the file storage and is mounted into Immich via an external library.

The Image that fails can be found here: https://pam.bcn.jensen.ovh/sharing/tLiM6m1xY

### The OS that Immich Server is running on

Docker

### Version of Immich Server

V1.121.0

### Version of Immich Mobile App

V1.121.0 build.168

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume1/photo/:/mnt/photo:ro
      - /var/services/homes/florian/Photos:/mnt/photo-florian:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #  file: hwaccel.ml.yml
    #  service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=#########
DB_HOSTNAME=immich_postgres
DB_USERNAME=#######
DB_DATABASE_NAME=#######
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

Upload image to server.
Refresh image thumbnails.
Image thumbnail generation will continue to fail.

### Relevant log output

```shell
immich_server            | [Nest] 7  - 11/24/2024, 2:24:15 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: heif: Unsupported feature: Unsupported color conversion (4.3003)
immich_server            | [Nest] 7  - 11/24/2024, 2:24:15 PM   ERROR [Microservices:JobService] Error: heif: Unsupported feature: Unsupported color conversion (4.3003)
immich_server            |     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
immich_server            |     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
immich_server            |     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:158:63)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:108:25)
immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:151:28)
immich_server            |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_server            | [Nest] 7  - 11/24/2024, 2:24:15 PM   ERROR [Microservices:JobService] Object:
immich_server            | {
immich_server            |   "id": "85d4b07f-18cb-45e0-8a6e-f75b46a31de4"
immich_server            | }
immich_server            |
```
```


### Additional information

_No response_
