### ISSUE TITLE
Unable to change date and time

### ISSUE THREAD

**Issue by Vojtik69** [immich-app/immich#14312]
### The bug

It is unable to change date and time for jpg pictures in external library. Maybe can be important that my pictures has no xmp file, just use exif

### The OS that Immich Server is running on

pi4

### Version of Immich Server

v1.120.2

### Version of Immich Mobile App

v1.120.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /mnt:/mnt:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/2TB/Obrázky/Immich
THUMB_LOCATION=./library/thumbs
ENCODED_VIDEO_LOCATION=./library/encoded-video
PROFILE_LOCATION=./library/profile
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=26789094
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Change date and time 
2. nothing happens
3.
...

### Relevant log output

```shell
[Nest] 7  - 11/24/2024, 10:21:46 AM    WARN [Microservices:MetadataRepository] Error writing exif data (/mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny/MR-1124181435.jpg.xmp): Error: Error creating file: /mnt/2TB/Obr&aacute;zky/Fotky/2023-11/Mikul&aacute;&scaron;-narozeniny/MR-1124181435.jpg.xmp - /mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny/MR-1124181435.jpg.xmp
[Nest] 7  - 11/24/2024, 10:21:46 AM    WARN [Microservices:Error: File not found - /mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny/MR-1124181435.jpg.xmp
    at ReadTask._ExifToolTask_parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:76:71)
    at ReadTask.parser (/usr/src/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:47:167)
    at ReadTask._Task_resolve (/usr/src/app/node_modules/batch-cluster/dist/Task.js:146:40)] Error reading exif data (/mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny/MR-1124181435.jpg.xmp): Error: File not found - /mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny/MR-1124181435.jpg.xmp
[Nest] 7  - 11/24/2024, 10:21:46 AM    WARN [Microservices:MetadataService] Asset 79d54a14-9300-4430-bab5-8c07237eae88 has no time zone information
[Nest] 7  - 11/24/2024, 10:21:46 AM    WARN [Microservices:MetadataService] Asset 79d54a14-9300-4430-bab5-8c07237eae88 has no valid date, falling back to asset.fileCreatedAt
```

### Additional information

mnt/2TB/Obrázky/Fotky/2023-11/Mikuláš-narozeniny $ ls -ld
drwxrwxrwx 1 root root 4096 Nov 28  2023 .
