### ISSUE TITLE
Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by RetroZelda** [immich-app/immich#14333]
### The bug

The server starts with this error:
Error: Could not load the "sharp" module using the linux-x64 runtime
 ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory

This has been happening for a while, including with latest v1.121.0

### The OS that Immich Server is running on

Debian Trixie - kernel 6.11.9-amd64

### Version of Immich Server

1.121.0

### Version of Immich Mobile App

0.0.0.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```


### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/path/to/folder
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=**password**

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```


### Reproduction steps

1. start immich docker container
2.
3.
...


### Relevant log output

```shell
$ docker compose up
[+] Running 3/0
 ✔ Container immich_redis     Running                                                                                                                                                                                                                                                                                                                         0.0s 
 ✔ Container immich_postgres  Running                                                                                                                                                                                                                                                                                                                         0.0s 
 ✔ Container immich_server    Created                                                                                                                                                                                                                                                                                                                         0.0s 
Attaching to immich_postgres, immich_redis, immich_server
immich_server    | Initializing Immich v1.121.0
immich_server    | Detected CPU Cores: 4
immich_server    | /usr/src/app/node_modules/sharp/lib/sharp.js:113
immich_server    |   throw new Error(help.join('\n'));
immich_server    |   ^
immich_server    | 
immich_server    | Error: Could not load the "sharp" module using the linux-x64 runtime
immich_server    | ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
immich_server    | Possible solutions:
immich_server    | - Ensure optional dependencies can be installed:
immich_server    |     npm install --include=optional sharp
immich_server    | - Ensure your package manager supports multi-platform installation:
immich_server    |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server    | - Add platform-specific dependencies:
immich_server    |     npm install --os=linux --cpu=x64 sharp
immich_server    | - Consult the installation documentation:
immich_server    |     See https://sharp.pixelplumbing.com/install
immich_server    |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:113:9)
immich_server    |     at Module._compile (node:internal/modules/cjs/loader:1546:14)
immich_server    |     at Object..js (node:internal/modules/cjs/loader:1689:10)
immich_server    |     at Module.load (node:internal/modules/cjs/loader:1318:32)
immich_server    |     at Function._load (node:internal/modules/cjs/loader:1128:12)
immich_server    |     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
immich_server    |     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
immich_server    |     at Module.require (node:internal/modules/cjs/loader:1340:12)
immich_server    |     at require (node:internal/modules/helpers:141:16)
immich_server    |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server    | 
immich_server    | Node.js v22.11.0
immich_server exited with code 0
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 3/3
 ✔ Container immich_server    Stopped                                                                                                                                                                                                                                                                                                                         0.3s 
 ✔ Container immich_postgres  Stopped                                                                                                                                                                                                                                                                                                                         0.4s 
 ✔ Container immich_redis     Stopped                                                                                                                                                                                                                                                                                                                         0.4s 
canceled
```


### Additional information

_No response_
