### ISSUE TITLE
Failed to upgrade to v1.121.0

### ISSUE THREAD

**Issue by liangshixing** [immich-app/immich#14358]
### The bug

we upgrade to v1.121.0, migration failed.

immich_server            | 2024-11-21T02:54:06.730467216Z Migration "NaturalEarthCountriesIdentityColumn1732072134943" failed, error: type "public.earth" does not exist
immich_server            | 2024-11-21T02:54:06.734871635Z QueryFailedError: type "public.earth" does not exist
immich_server            | 2024-11-21T02:54:06.734899247Z     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            | 2024-11-21T02:54:06.734904728Z     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            | 2024-11-21T02:54:06.734908679Z     at async NaturalEarthCountriesIdentityColumn1732072134943.up (/usr/src/app/dist/migrations/1732072134943-NaturalEarthCountriesIdentityColumn.js:9:9)
immich_server            | 2024-11-21T02:54:06.734912709Z     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            | 2024-11-21T02:54:06.734916570Z     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            | 2024-11-21T02:54:06.734920419Z     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:189:9)
immich_server            | 2024-11-21T02:54:06.734924114Z     at async /usr/src/app/dist/services/database.service.js:96:17
immich_server            | 2024-11-21T02:54:06.734927775Z     at async /usr/src/app/dist/repositories/database.repository.js:197:23 {
immich_server            | 2024-11-21T02:54:06.734931442Z   query: '\n' +
immich_server            | 2024-11-21T02:54:06.734935297Z     '      CREATE FUNCTION ll_to_earth_public(latitude double precision, longitude double precision) RETURNS public.earth PARALLEL SAFE IMMUTABLE STRICT LANGUAGE SQL AS $$\n' +
immich_server            | 2024-11-21T02:54:06.734944214Z     '        SELECT public.cube(public.cube(public.cube(public.earth()*cos(radians(latitude))*cos(radians(longitude))),public.earth()*cos(radians(latitude))*sin(radians(longitude))),public.earth()*sin(radians(latitude)))::public.earth\n' +
immich_server            | 2024-11-21T02:54:06.734948604Z     '    $$',
immich_server            | 2024-11-21T02:54:06.734952223Z   parameters: undefined,
immich_server            | 2024-11-21T02:54:06.734967245Z   driverError: error: type "public.earth" does not exist
immich_server            | 2024-11-21T02:54:06.734970622Z       at /usr/src/app/node_modules/pg/lib/client.js:535:17
immich_server            | 2024-11-21T02:54:06.734973472Z       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            | 2024-11-21T02:54:06.734976135Z       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_server            | 2024-11-21T02:54:06.734978683Z       at async NaturalEarthCountriesIdentityColumn1732072134943.up (/usr/src/app/dist/migrations/1732072134943-NaturalEarthCountriesIdentityColumn.js:9:9)
immich_server            | 2024-11-21T02:54:06.734981640Z       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            | 2024-11-21T02:54:06.734986006Z       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            | 2024-11-21T02:54:06.734988955Z       at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:189:9)
immich_server            | 2024-11-21T02:54:06.734991842Z       at async /usr/src/app/dist/services/database.service.js:96:17
immich_server            | 2024-11-21T02:54:06.734994316Z       at async /usr/src/app/dist/repositories/database.repository.js:197:2

### The OS that Immich Server is running on

Arch Linux

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

1.121.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
PUBLIC_LOGIN_PAGE_MESSAGE="******"

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/photo

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
#IMMICH_VERSION=v1.120.2
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=******

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis

# To set a timezone
TZ="Asia/Shanghai"
```

### Reproduction steps

failed to boot every time.
...
