### ISSUE TITLE
v121: Thumbnail generation hangs

### ISSUE THREAD

**Issue by dekiesel** [immich-app/immich#14360]
### The bug

Since updating to v121 thumbnail generation hangs. Once core is constantly running at 100%.

### The OS that Immich Server is running on

Alpine 3.15

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0 build .168

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      #    extends:
      #      file: hwaccel.yml
      #      service: hwaccel
        #command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICHUPLOADDIR}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/samba/sambaserver/storageuser1:/mnt/users/user1/samba/sambaserver/storageuser1:ro
      - /mnt/samba/sambaserver/storageuser2:/mnt/users/user2/samba/sambaserver/storageuser2:ro
      - /mnt/pc:/mnt/users/users/pc:ro
    env_file:
      - .env
    ports:
      - 80:2283
    depends_on:
      - redis
      - database
    restart: always
    logging:
      driver: "syslog"
      options:
        tag: "immich-server"


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MLMODELCACHE}:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
      #image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${MYPGDATA}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# Custom
IMMICHUPLOADDIR=/root/app/persistant-data/immich/uploads
MLMODELCACHE=/root/app/persistant-data/ml/model-cache
MYPGDATA=/root/app/persistant-data/postgres/data
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.121.0"


# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=secretpw

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
IMMICH_LOG_LEVEL=debug
```

### Reproduction steps

1. Update to v.121
2. Log in as admin
3. Click on "Generate Thumbnails"

### Relevant log output

```shell
immich_machine_learning  | [11/26/24 07:13:48] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:13:53 AM   DEBUG [Api:LoggingInterceptor~ykq4guw9] GET /api/jobs 200 4.78ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:13:58] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:13:59 AM   DEBUG [Api:LoggingInterceptor~k3gr0kqe] GET /api/jobs 200 4.51ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:14:01 AM   DEBUG [Api:LoggingInterceptor~8y2vrr15] GET /api/server/ping 200 0.18ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 11/26/2024, 7:14:05 AM   DEBUG [Api:LoggingInterceptor~7ijrzjcu] GET /api/jobs 200 4.45ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:08] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:14:11 AM   DEBUG [Api:LoggingInterceptor~btl7mkkl] GET /api/jobs 200 4.24ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:14:17 AM   DEBUG [Api:LoggingInterceptor~3euhes6o] GET /api/jobs 200 3.77ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:18] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:14:23 AM   DEBUG [Api:LoggingInterceptor~5xy43oqq] GET /api/jobs 200 5.55ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:28] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:14:29 AM   DEBUG [Api:LoggingInterceptor~2hjdtkus] GET /api/jobs 200 4.00ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:14:32 AM   DEBUG [Api:LoggingInterceptor~y6crjp2j] GET /api/server/ping 200 0.18ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 11/26/2024, 7:14:34 AM   DEBUG [Api:LoggingInterceptor~24fk9wmn] GET /api/jobs 200 4.43ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:38] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:14:40 AM   DEBUG [Api:LoggingInterceptor~zk8yp27l] GET /api/jobs 200 4.40ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:14:46 AM   DEBUG [Api:LoggingInterceptor~ylwhhodq] GET /api/jobs 200 3.83ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:48] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:14:52 AM   DEBUG [Api:LoggingInterceptor~nhxf4zed] GET /api/jobs 200 5.98ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:14:58 AM   DEBUG [Api:LoggingInterceptor~0rbb1mx5] GET /api/jobs 200 4.29ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:14:58] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:03 AM   DEBUG [Api:LoggingInterceptor~52yx4tse] GET /api/server/ping 200 0.17ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 11/26/2024, 7:15:04 AM   DEBUG [Api:LoggingInterceptor~vs1vi98h] GET /api/jobs 200 5.80ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:08] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:10 AM   DEBUG [Api:LoggingInterceptor~60otlrsz] GET /api/jobs 200 8.23ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:15:16 AM   DEBUG [Api:LoggingInterceptor~l5plngy8] GET /api/jobs 200 5.71ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:18] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:22 AM   DEBUG [Api:LoggingInterceptor~g8i8mml8] GET /api/jobs 200 4.82ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:15:28 AM   DEBUG [Api:LoggingInterceptor~7jfpwh9u] GET /api/jobs 200 16.02ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:28] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:33 AM   DEBUG [Api:LoggingInterceptor~6m5ng1cd] GET /api/server/ping 200 0.34ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 11/26/2024, 7:15:34 AM   DEBUG [Api:LoggingInterceptor~0v9srl0r] GET /api/jobs 200 7.95ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:38] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:40 AM   DEBUG [Api:LoggingInterceptor~ie9cnxto] GET /api/jobs 200 23.18ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:15:46 AM   DEBUG [Api:LoggingInterceptor~jfx82hpe] GET /api/jobs 200 8.53ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:48] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:15:52 AM   DEBUG [Api:LoggingInterceptor~60s0vy13] GET /api/jobs 200 6.03ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:15:58 AM   DEBUG [Api:LoggingInterceptor~hrwcldcg] GET /api/jobs 200 28.39ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:15:58] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:04 AM   DEBUG [Api:LoggingInterceptor~1hwwdruq] GET /api/server/ping 200 0.14ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 11/26/2024, 7:16:04 AM   DEBUG [Api:LoggingInterceptor~yls5dj8g] GET /api/jobs 200 6.52ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:16:08] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:10 AM   DEBUG [Api:LoggingInterceptor~5i4qr4g7] GET /api/jobs 200 5.49ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:16:16 AM   DEBUG [Api:LoggingInterceptor~6ttbel0u] GET /api/jobs 200 4.30ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:16:18] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:22 AM   DEBUG [Api:LoggingInterceptor~f04k8egj] GET /api/jobs 200 4.17ms 10.1.100.153
immich_redis             | 1:M 26 Nov 2024 07:16:24.028 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 26 Nov 2024 07:16:24.028 * Background saving started by pid 21
immich_redis             | 21:C 26 Nov 2024 07:16:24.031 * DB saved on disk
immich_redis             | 21:C 26 Nov 2024 07:16:24.031 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 26 Nov 2024 07:16:24.128 * Background saving terminated with success
immich_machine_learning  | [11/26/24 07:16:28] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:28 AM   DEBUG [Api:LoggingInterceptor~2hhtur7b] GET /api/jobs 200 5.95ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:16:34 AM   DEBUG [Api:LoggingInterceptor~7xrldp9d] GET /api/jobs 200 3.89ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:16:34 AM   DEBUG [Api:LoggingInterceptor~ppgld1gn] GET /api/server/ping 200 0.17ms ::ffff:127.0.0.1
immich_machine_learning  | [11/26/24 07:16:38] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:40 AM   DEBUG [Api:LoggingInterceptor~ib41w9zl] GET /api/jobs 200 5.15ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:16:46 AM   DEBUG [Api:LoggingInterceptor~nkjn7djk] GET /api/jobs 200 7.07ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:16:48] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:16:52 AM   DEBUG [Api:LoggingInterceptor~gq7fwryf] GET /api/jobs 200 3.65ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:16:58 AM   DEBUG [Api:LoggingInterceptor~mi284bys] GET /api/jobs 200 3.58ms 10.1.100.153
immich_machine_learning  | [11/26/24 07:16:58] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:17:04 AM   DEBUG [Api:LoggingInterceptor~3lo6jszs] GET /api/jobs 200 4.63ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:17:05 AM   DEBUG [Api:LoggingInterceptor~918xesaa] GET /api/server/ping 200 0.17ms ::ffff:127.0.0.1
immich_machine_learning  | [11/26/24 07:17:08] DEBUG    Checking for inactivity...                         
immich_server            | [Nest] 17  - 11/26/2024, 7:17:10 AM   DEBUG [Api:LoggingInterceptor~saki0oj4] GET /api/jobs 200 3.70ms 10.1.100.153
immich_server            | [Nest] 17  - 11/26/2024, 7:17:16 AM   DEBUG [Api:LoggingInterceptor~brk7z9sn] GET /api/jobs 200 9.92ms 10.1.100.153
```

### Additional information

Just to make it clear: The log is set to debug and repeats those lines over and over.
Let me know if I can supply anything else.
