### ISSUE TITLE
Server not starting encoded-video error 

### ISSUE THREAD

**Issue by Ukey89** [immich-app/immich#14373]
### The bug

ERROR [Microservices:StorageService] Failed to read upload/encoded-video/.immich: Error: ENOENT: no such file or directory, open 'upload/encoded-video/.immich'

microservices worker error: Error: Failed to read "<UPLOAD_LOCATION>/encoded-video/.immich - Please see https://immich.app/docs/administration/system-integrity#folder-checks for more information."

microservices worker exited with code 1

Killing api process

### The OS that Immich Server is running on

Debian / docker - latest 

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

Latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:->
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp,>
    volumes:
      # Do not edit the next line. If you want to change the m>
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded->
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
```

### Your .env content

```Shell
UPLOAD_LOCATION=/root/immich/update/immich_file
THUMB_LOCATION=/root/immich/update/thumbs
ENCODED_VIDEO_LOCATION=/root/immich/update/encoded-video/
PROFILE_LOCATION=/root/immich/update/profile
BACKUP_LOCATION=/root/immich/update/backups
```

### Reproduction steps

1.mount /update folder in my docker (ser files from my nas) 
2.change docker compose and .env file (add path) 
3.run docker compose up - d
...
