### ISSUE TITLE
Folder removed from backup albums when emptied

### ISSUE THREAD

**Issue by jdrewsteiner** [immich-app/immich#14406]
### The bug

If I have a folder selected to backup in the "Backup Albums" setting. It disappears if the folder becomes empty (even if the folder itself still exists). And if a photo is stored there again, it is no longer selected as a backup folder. 

### The OS that Immich Server is running on

DSM 7.2.2-72806 Update 1

### Version of Immich Server

1.121.0

### Version of Immich Mobile App

1.121.0 build.168

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume1/photo:/mnt/media/albums:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  #immich-microservices:
   # container_name: immich_microservices
   # image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
   # command: ["start.sh", "microservices"]
   # volumes:
    #  - ${UPLOAD_LOCATION}:/usr/src/app/upload
    #  - /volume1/photo:/mnt/media/albums:ro
    #  - /etc/localtime:/etc/localtime:ro
   # env_file:
   #   - stack.env
   # depends_on:
   #   - redis
    #  - database
   # restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

#  immich-web:
#    container_name: immich_web
#    labels:
#      - "com.centurylinklabs.watchtower.enable=false"
#    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
#    env_file:
#      - stack.env
#    restart: always

#  typesense:
#    container_name: immich_typesense
#    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
#    environment:
#      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
#      - TYPESENSE_DATA_DIR=/data
#      # remove this to get debug messages
#      - GLOG_minloglevel=1
#    volumes:
#      - tsdata:/data
#    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
#    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

#  immich-proxy:
#    container_name: immich_proxy
#    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
#    ports:
#      - 2283:8080
#    depends_on:
#      - immich-server
#      - immich-web
#    restart: always

volumes:
  pgdata:
  model-cache:
#  tsdata:
```

### Your .env content

```Shell
NA
```

### Reproduction steps

1. select folder to be backed up (ex. screen shots)
2. delete photos from screenshot folder on device
3. navigate back to backup albums settings in immich and see that screenshot folder it not in list of available folders to select. 
4. Take a screenshot which adds an image in the screenshot folder 
5. navigate back to backup albums setting in immich and see the screenshots folder but it's not selected to be backed up
...
