### ISSUE TITLE
Bug when trying to permanently delete assets (previously moved to trash from web UI) from Android app

### ISSUE THREAD

**Issue by macvenez** [immich-app/immich#14431]
### The bug

I recently removed some assets (moved to trash with remove duplicates utility) using Immich Web UI.
Afterwards I tried permanently deleting those images using the Android app (I selected many of them at once).
The trash section on the app now only shows those deleted images and nothing else (Image 1).
The main section of the app now shows all images as not backupped (cloud with slash icon) (Image 2).
I can only restore the previous state by logging out and back in in the app.

My goal was to also remove those duplicated images also from the phone memory storage because permanently removing them only through the web UI would have left those images on the phone storage

## Image 1
![immich-1](https://github.com/user-attachments/assets/c8f0c6f3-1ce8-4cd2-8df2-a51994c429a8)

## Image 2
![immich-2](https://github.com/user-attachments/assets/50e00e06-ffba-4748-8ec2-c0303c563115)

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always


  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=*REDACTED*

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=*REDACTED*
DB_PASSWORD=*REDACTED*

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Remove some assets using Immich Web UI (actually deleted them through remove duplicates utility)
2. Try to permanently delete them using Android app by selecting multiple at once

### Relevant log output

```shell
I couldn't find any error in immich_server container (the output is just like normal)
Same for Android App, no log here
```
