### ISSUE TITLE
Can't start after 1.22.0 update

### ISSUE THREAD

**Issue by kimberlyeet** [immich-app/immich#14498]
### The bug

immich-server container keeps restarting with the attached error log after updating to 1.222.0.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

1.222.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.122.0
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    healthcheck:
      disable: false
    depends_on:
      - immich_redis
      - database
    networks:
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.122.0
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    healthcheck:
      disable: false
    networks:
      - proxy

  immich_redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - proxy

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - proxy

volumes:
  pgdata:
  model-cache:
  immich-files:
    external: true
networks:
  proxy:
    external: true
```

### Your .env content

```Shell
IMMICH_LOG_LEVEL=log
UPLOAD_LOCATION=immich-files
IMMICH_VERSION=release
DB_PASSWORD=censored
DB_HOSTNAME=immich_postgres
DB_USERNAME=censored
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Update to 1.222.0
2. Start stack
3. See Error log
...

### Relevant log output

```shell
[Nest] 16  - 12/05/2024, 7:13:29 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.122.0] [production] 
[Nest] 7  - 12/05/2024, 7:13:33 PM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: QueryFailedError: Connection terminated unexpectedly
QueryFailedError: Connection terminated unexpectedly
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/dist/repositories/database.repository.js:201:21
error: the database system is in recovery mode
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  length: 109,
  severity: 'FATAL',
  code: '57P03',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postmaster.c',
  line: '2357',
  routine: 'ProcessStartupPacket'
}
microservices worker error: error: the database system is in recovery mode
microservices worker exited with code 1
Killing api process
Initializing Immich v1.122.0
Detected CPU Cores: 10
Starting api worker
Starting microservices worker
```
