### ISSUE TITLE
Recent albums dropdown arrow misaligned

### ISSUE THREAD

**Issue by literallyfiro** [immich-app/immich#14496]
### The bug

Hello,

After updating Immich to the latest version, I noticed that the new albums dropdown arrow becomes misaligned with the `Albums` button after you click on any sidebar button

![image](https://github.com/user-attachments/assets/4d68bbeb-4468-4b91-9663-e3809c4aaf27)

![image](https://github.com/user-attachments/assets/e979bf65-35fe-4f6a-9d72-faae10ac4358)

### The OS that Immich Server is running on

Rocky Linux 9.3

### Version of Immich Server

v1.122.0

### Version of Immich Mobile App

v1.122.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    hostname: immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /dev/dri:/dev/dri
    env_file:
      - stack.env

    depends_on:
      - redis
      - database
    restart: always
    networks:
      - frontend
      - backend

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
      - backend
      
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    restart: always
    networks:
      - backend

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    env_file:
      - stack.env
    restart: always
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    networks:
      - backend

volumes:
  model-cache:

networks:
  backend:
    external: true
  frontend:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/storage/immich
DB_DATA_LOCATION=/mnt/storage/postgres
IMMICH_VERSION=release
DB_PASSWORD=redacted
DB_USERNAME=redacted
DB_DATABASE_NAME=redacted
```

### Reproduction steps

1. Click on any sidebar button
2. The recent albums dropdown arrow becomes misaligned

### Additional information

Not sure if this is any helpful, but the web browser I'm using is Firefox 133.0
