### ISSUE TITLE
Missing lock for job

### ISSUE THREAD

**Issue by almottier** [immich-app/immich#14491]
### The bug

Hello,

Every time I start the Immich Docker stack, I encounter multiple errors. Additionally, thumbnails are not being generated even when I start the job manually. I have to restart the stack manually to fix the thumbnails issues but still having "Missing lock for job" erros.

```
Error: Missing lock for job 14. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/05/2024, 1:17:37 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:17:37 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
```

### The OS that Immich Server is running on

GNU/Linux synology_apollolake_218+

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

?

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/immich
# The location where your database files are stored
DB_DATA_LOCATION=/volume1/docker/immich/database

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
```

### Reproduction steps

docker-compose up -d

### Relevant log output

```shell
sh-4.4# docker logs -f immich_server
Initializing Immich v1.121.0
Detected CPU Cores: 2
Starting api worker
Starting microservices worker
...
Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 1. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/05/2024, 1:16:38 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:38 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] Object:
{}

[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:38 PM   ERROR [Microservices:JobService] Object:
{}

Error: Missing lock for job 2. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 2. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/05/2024, 1:16:41 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:41 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] Object:
{}

[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:41 PM   ERROR [Microservices:JobService] Object:
{}

Error: Missing lock for job 3. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 3. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/05/2024, 1:16:43 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] Object:
{}

[Nest] 7  - 12/05/2024, 1:16:43 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:43 PM   ERROR [Microservices:JobService] Object:
{}

Error: Missing lock for job 4. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 4. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/05/2024, 1:16:46 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:46 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] Object:
{}

[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:46 PM   ERROR [Microservices:JobService] Object:
{}

Error: Missing lock for job 5. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 5. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 34  - 12/05/2024, 1:16:48 PM     LOG [Api:EventRepository] Websocket Disconnect: dMMBThedAyCEYNA_AAAB
[Nest] 34  - 12/05/2024, 1:16:50 PM     LOG [Api:EventRepository] Websocket Connect:    4YWYR-61wiDOHnhfAAAF
[Nest] 7  - 12/05/2024, 1:16:52 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:52 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
[Nest] 7  - 12/05/2024, 1:16:52 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 12/05/2024, 1:16:52 PM   ERROR [Microservices:JobService] TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:152:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:122:13)
[Nest] 7  - 12/05/2024, 1:16:52 PM   ERROR [Microservices:JobService] Object:
{}
```
