### ISSUE TITLE
[BUG] iOS app live photos upload leaves .MOV file in user folder

### ISSUE THREAD

**Issue by qu1j0t3buendia** [immich-app/immich#14506]
### The bug

When I upload live photos from Immich iOS mobile app (iPhone 12) a .HEIC file is uploaded to the correct folder album but a .MOV file is left in the user folder. The live photo work as expected on Immich app and the files are linked by the livePhotoCID entry in the exif table. No errors appear in the server log (verbose level). This issue seems to be related to #11324 but in that issue they say it was solved around February 2024. I just tested it and it's still happening for me.

This is not a big deal because the live photos work, but I  am using Immich to organize my photos and it would be great if the live photo video was uploaded to the same folder of the image file.

Thank you for your help and for the amazing work of creating this software.

### The OS that Immich Server is running on

Docker (Windows 10)

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-latest}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile	
      - /etc/localtime:/etc/localtime:ro      
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=E:/immich_library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
# You can find documentation for all the supported env variables [here](/docs/install/environment-variables)

# Custom location where your uploaded, thumbnails, and transcoded video files are stored
THUMB_LOCATION=./thumbs
ENCODED_VIDEO_LOCATION=./encoded-video
PROFILE_LOCATION=./profile

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Etc/GMT+3

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<REDACTED>

IMMICH_LOG_LEVEL=verbose

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Take a live photo with iPhone
2. Open Immich app and wait for upload
3. Check the library folder: .MOV file is in the /library/user folder and .HEIC file is in the /library/user/album folder
4. The live photo work as expected when visualized in app

### Relevant log output

```shell
[Nest] 19  - 12/05/2024, 8:11:40 PM VERBOSE [Api:LoggingInterceptor~4u4hizf7] {"deviceAssetId":"C47E9697-7A27-42DB-87CF-B02DF206ED45/L0/001","deviceId":"bf7f2c427b3332316927dab4302a02e6c977da77548f46d910e494ae2afc849f","fileCreatedAt":"2024-12-05T23:09:25.000Z","fileModifiedAt":"2024-12-05T23:10:20.000Z","isFavorite":"false","duration":"0:00:00.000000"}
[Nest] 19  - 12/05/2024, 8:11:40 PM   DEBUG [Api:LoggingInterceptor~cqljprvt] POST /api/assets 201 808.89ms ::ffff:172.18.0.1
[Nest] 19  - 12/05/2024, 8:11:40 PM VERBOSE [Api:LoggingInterceptor~cqljprvt] {"deviceAssetId":"C47E9697-7A27-42DB-87CF-B02DF206ED45/L0/001","deviceId":"bf7f2c427b3332316927dab4302a02e6c977da77548f46d910e494ae2afc849f","fileCreatedAt":"2024-12-05T23:09:25.000Z","fileModifiedAt":"2024-12-05T23:10:20.000Z","isFavorite":"false","duration":"0:00:00.000000","livePhotoVideoId":"53703923-656d-49c3-868f-fabd0821a33c"}
[Nest] 19  - 12/05/2024, 8:11:40 PM   DEBUG [Api:LoggingInterceptor~a6qtsufi] GET /api/server/storage 200 4.29ms ::ffff:172.18.0.1
[Nest] 19  - 12/05/2024, 8:11:41 PM   DEBUG [Api:LoggingInterceptor~0mblqqsh] PUT /api/albums/029d0c4a-997e-47c3-9613-bc2453342b66/assets 200 353.94ms ::ffff:172.18.0.1
[Nest] 19  - 12/05/2024, 8:11:41 PM VERBOSE [Api:LoggingInterceptor~0mblqqsh] {"ids":["de8e252b-9720-483d-ada5-2d0f725189d4"]}
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Exif Tags
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Object:
{
  "SourceFile": "/usr/src/app/upload/upload/c8627fb7-3bc8-4054-a184-4cf098600cc4/aa/72/aa7224e2-6bb3-4d88-856b-61e873690969.MOV",
  "errors": [],
  <REDACTED>
}

[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset 53703923-656d-49c3-868f-fabd0821a33c date time is 2024-12-05T20:09:25-03:00
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset 53703923-656d-49c3-868f-fabd0821a33c timezone is America/Sao_Paulo (via GPSLatitude/GPSLongitude)
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset 53703923-656d-49c3-868f-fabd0821a33c has a local time of 2024-12-05T20:09:25.000Z
[Nest] 7  - 12/05/2024, 8:11:41 PM   DEBUG [Microservices:MapRepository] Request: <REDACTED>
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MapRepository] Raw: {<REDACTED>}
[Nest] 19  - 12/05/2024, 8:11:41 PM   DEBUG [Api:LoggingInterceptor~ns4qy241] GET /api/server/ping 200 0.64ms ::ffff:127.0.0.1
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Exif Tags
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Object:
{
  "SourceFile": "/usr/src/app/upload/upload/c8627fb7-3bc8-4054-a184-4cf098600cc4/50/62/5062eb18-350c-4ede-8c93-4b0dd7086166.HEIC",
  "errors": [],
  <REDACTED>
  "warnings": []
}

[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset de8e252b-9720-483d-ada5-2d0f725189d4 date time is 2024-12-05T20:09:25.810-03:00
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset de8e252b-9720-483d-ada5-2d0f725189d4 timezone is UTC-3 (via OffsetTime)
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MetadataService] Asset de8e252b-9720-483d-ada5-2d0f725189d4 has a local time of 2024-12-05T20:09:25.810Z
[Nest] 7  - 12/05/2024, 8:11:41 PM   DEBUG [Microservices:MapRepository] Request: <REDACTED>
[Nest] 7  - 12/05/2024, 8:11:41 PM VERBOSE [Microservices:MapRepository] Raw: {<REDACTED>}
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:APIKeyService] Attempting to rename file: upload/upload/c8627fb7-3bc8-4054-a184-4cf098600cc4/aa/72/aa7224e2-6bb3-4d88-856b-61e873690969.MOV => upload/library/You/IMG_8561.MOV
[Nest] 7  - 12/05/2024, 8:11:42 PM VERBOSE [Microservices:MediaService] Thumbnail generation skipped for asset 53703923-656d-49c3-868f-fabd0821a33c: not visible
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:APIKeyService] Attempting to rename file: upload/upload/c8627fb7-3bc8-4054-a184-4cf098600cc4/50/62/5062eb18-350c-4ede-8c93-4b0dd7086166.HEIC => upload/library/You/Recentes/IMG_8561.HEIC
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:DuplicateService] Asset 53703923-656d-49c3-868f-fabd0821a33c is not visible, skipping
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:MediaService] No devices found in /dev/dri.
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:MediaService] OpenCL not available for transcoding, so RKMPP acceleration will use CPU tonemapping
[Nest] 7  - 12/05/2024, 8:11:42 PM     LOG [Microservices:MediaService] Transcoding video 53703923-656d-49c3-868f-fabd0821a33c without hardware acceleration
[Nest] 7  - 12/05/2024, 8:11:42 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -i upload/library/You/IMG_8561.MOV -y -c:v h264 -c:a copy -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -v verbose -vf scale=720:-2 -preset ultrafast -crf 23 upload/encoded-video/c8627fb7-3bc8-4054-a184-4cf098600cc4/53/70/53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:43 PM   DEBUG [Microservices:MediaRepository] Transcoding 9.09% done, estimated 10s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:44 PM   DEBUG [Microservices:MediaRepository] Transcoding 27.27% done, estimated 4s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:44 PM   DEBUG [Microservices:MediaRepository] Transcoding 43.18% done, estimated 2s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:45 PM   DEBUG [Microservices:MediaRepository] Transcoding 59.09% done, estimated 1s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 19  - 12/05/2024, 8:11:45 PM   DEBUG [Api:LoggingInterceptor~ce5rrwvq] POST /api/auth/validateToken 200 0.33ms ::ffff:172.18.0.1
[Nest] 7  - 12/05/2024, 8:11:45 PM   DEBUG [Microservices:MediaRepository] Transcoding 77.27% done for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:45 PM   DEBUG [Microservices:MediaRepository] Transcoding 100.00% done for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:45 PM     LOG [Microservices:MediaService] Successfully encoded 53703923-656d-49c3-868f-fabd0821a33c
[Nest] 7  - 12/05/2024, 8:11:46 PM     LOG [Microservices:MediaService] Transcoding video 53703923-656d-49c3-868f-fabd0821a33c without hardware acceleration
[Nest] 7  - 12/05/2024, 8:11:46 PM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -i upload/library/You/IMG_8561.MOV -y -c:v h264 -c:a copy -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -v verbose -vf scale=720:-2 -preset ultrafast -crf 23 upload/encoded-video/c8627fb7-3bc8-4054-a184-4cf098600cc4/53/70/53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:47 PM   DEBUG [Microservices:MediaRepository] Transcoding 20.45% done, estimated 7s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:48 PM   DEBUG [Microservices:MediaRepository] Transcoding 40.91% done, estimated 3s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:48 PM   DEBUG [Microservices:MediaRepository] Transcoding 63.64% done, estimated 1s remaining for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:50 PM   DEBUG [Microservices:MediaRepository] Transcoding 100.00% done for output 53703923-656d-49c3-868f-fabd0821a33c.mp4
[Nest] 7  - 12/05/2024, 8:11:50 PM     LOG [Microservices:MediaService] Successfully encoded 53703923-656d-49c3-868f-fabd0821a33c
[Nest] 7  - 12/05/2024, 8:11:54 PM   DEBUG [Microservices:PersonService] 1 faces detected in upload/thumbs/c8627fb7-3bc8-4054-a184-4cf098600cc4/de/8e/de8e252b-9720-483d-ada5-2d0f725189d4-preview.jpeg
[Nest] 7  - 12/05/2024, 8:11:55 PM     LOG [Microservices:PersonService] Detected 1 new faces in asset de8e252b-9720-483d-ada5-2d0f725189d4
[Nest] 7  - 12/05/2024, 8:11:55 PM VERBOSE [Microservices:JobRepository] Waiting for undefined queue to stop...
[Nest] 7  - 12/05/2024, 8:11:56 PM   DEBUG [Microservices:PersonService] Skipping facial recognition queueing because 1 job is already queued
[Nest] 7  - 12/05/2024, 8:11:56 PM   DEBUG [Microservices:PersonService] Face d8ea32e9-610a-4ac3-a2b5-5e4a80d40776 has 64 matches
[Nest] 7  - 12/05/2024, 8:11:56 PM   DEBUG [Microservices:PersonService] Assigning face d8ea32e9-610a-4ac3-a2b5-5e4a80d40776 to person be94051e-b265-485e-afc3-71c51edc9f8e
```

### Additional information

I removed all metadata and location information from the log.
