### ISSUE TITLE
SVCB/HTTPS Resource Record is not supported

### ISSUE THREAD

**Issue by KYLN24** [immich-app/immich#14513]
### The bug

My network is under a carrier-grade Full Cone NAT (NAT 1). I deployed immich on a server and use [natter](https://github.com/MikeWang000000/Natter) to expose the server to a dynamic IPv4 address with a random dynamic port. I write a script to update the HTTPS RR of my DNS when the address or port is changed.

I can use Safari and Firefox to access my immich server through web. But the mobile app seems to be unable to resolve the domain name.

![img_v3_02ha_f8ba6b66-c643-4fef-a2e0-da2655e6332g](https://github.com/user-attachments/assets/525634c0-3349-4ca8-aca6-c535379871e5)
![img_v3_02ha_f6343865-674c-468a-a179-9d62af0fe00g](https://github.com/user-attachments/assets/bb338c0e-4075-4c20-afca-3181908650e9)

Could you please consider support HTTPS RR?

### The OS that Immich Server is running on

Ubuntu Server 24.04 LTS

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
TZ=Asia/Shanghai
IMMICH_VERSION=release
DB_PASSWORD=***
DB_USERNAME=***
DB_DATABASE_NAME=***
```

### Reproduction steps

1. Launch the container and expose the service on any port other than 443
2. Create a HTTPS RR on the DNS. For example, the value may be `immich.example.com. alpn="h2" port="53441"`
3. Make sure the website can be accessed using Safari or Firefox (Chrome and Edge seems not supported)
4. Try to connect to the server on the mobile app and get error.
