### ISSUE TITLE
Live Photo download on iOS app and web only saves the image, not the video

### ISSUE THREAD

**Issue by ThisIsCyreX** [immich-app/immich#14518]
### The bug

I can correctly view Live Photos in the iPhone iOS app and on the web using Safari, with both image and motion playing as expected. However, when I use the download button in the top right:

- Only the still image is saved to the Photos app, and the motion part of the Live Photo is missing/not playing.
- The app will log an error (see below).

### The OS that Immich Server is running on

Linux Mint 21.3 Virginia

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0 build.184

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 127.0.0.1:2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=../immich-app-uploads

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the Immich app on iOS 18.1.1/iPhone 12 Pro.
2. Scroll to any Live Photo.
3. Tap the photo and confirm that motion plays.
4. Use the cloud icon in the top right to download the file.
5. Check the saved file in the Files app or Photos app on the phone.
6. The saved image no longer contains motion and is just a still photo.

### Relevant log output

```shell
The app logged this:

Message
Error saving live photo

Details:
PlatformException(PHPPhotosErrorDomain (3302), Der Vorgang konnte nicht abgeschlossen werden. PHPPhotosErrorDomain-Fehler 3302.), No failure reason provided, null)

From:
DownloadService

Stack Trace:
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
<asynchronous suspension>
#2      IosPlugin.saveLivePhoto (package:photo_manager/src/internal/plugin.dart:713)
<asynchronous suspension>
#3      FileMediaRepository.saveLivePhoto (package:immich_mobile/repositories/file_media.repository.dart:48)
<asynchronous suspension>
#4      DownloadService.saveLivePhotos (package:immich_mobile/services/download.service.dart:120)
<asynchronous suspension>
```

### Additional information

- On macOS: Using Firefox to download the Live Photo from Immich-web works as expected, and Firefox saves two files: a JPEG and a MOV.
