### ISSUE TITLE
The server cannot provide files and images cannot be viewed.

### ISSUE THREAD

**Issue by Gloryandel** [immich-app/immich#14521]
### The bug

Updated to version 1.22, can be started, but an error is reported.No files can be opened. Thumbnails cannot be generated.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

1.122

### Version of Immich Mobile App

1.122

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    hostname: Arc
    extends:
      file: hwaccel.transcoding.yaml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/mnt/Pictures
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    hostname: Arc
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yaml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    hostname: Arc
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/pool/appdata/1000/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/pool/appdata/1000/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=
DB_DATABASE_NAME=immich

EXTERNAL_PATH=
```

### Reproduction steps

Updated to version 1.22, can be started, but an error is reported.No files can be opened. Thumbnails cannot be generated.
![image_47](https://github.com/user-attachments/assets/f5a91890-4db1-4bc3-8532-e84decc94066)

### Relevant log output

```shell
[immich-server]           | [Nest] 16  - 12/06/2024, 9:58:57 PM   ERROR [Api:GlobalExceptionFilter~paiw5zxe] Unknown err                                                                                                      or: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
[immich-server]           | TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Content-Disposition"]
[immich-server]           |     at ServerResponse.setHeader (node:_http_outgoing:702:3)
[immich-server]           |     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
[immich-server]           |     at sendFile (/usr/src/app/dist/utils/file.js:48:17)
[immich-server]           |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[immich-server]           |     at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.contr                                                                                                      oller.js:58:9)
```

### Additional information

Podman deploy immich
