### ISSUE TITLE
Server incorrectly resolves Redis DNS, it attempts to use the search-domain first.

### ISSUE THREAD

**Issue by bartmeuris** [immich-app/immich#14532]
### The bug

When making the Redis connection, the DNS resolving incorrectly resolves to `redis.<searchdomain>` before attempting to resolve the bare domain. When that entry does resolve on the local DNS server, it fails to find the local container in the docker network.

I'm not sure this can be fixed in immich itself, since most likely this will be handled in the Redis library that's being used.

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS, Docker version 27.3.1, build ce12230

### Version of Immich Server

v1.122.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - immich-redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=host(`immich.home.mydomain.com`)"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.docker.network=proxy"

  immich-machine-learning:
    container_name: immich_machine_learning-openvino
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped

volumes:
  model-cache:

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Brussels

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
#IMMICH_VERSION=release
IMMICH_VERSION=v1.122.1

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=...

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

# REDIS_HOSTNAME=redis
```

### Reproduction steps

1. Configure a search domain in your network, like `home.mydomain.com`
2. Configure a wildcard DNS record `*.home.mydomain.com` and point it somewhere
3. Attempt to use the `docker-compose` setup, the redis connection will fail and point the the IP `*.home.mydomain.com` resolves to.

### Relevant log output

```shell
immich_server                     | Error: connect ECONNREFUSED 192.168.50.123:6379
immich_server                     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1610:16) {
immich_server                     |   errno: -111,
immich_server                     |   code: 'ECONNREFUSED',
immich_server                     |   syscall: 'connect',
immich_server                     |   address: '192.168.50.123',
immich_server                     |   port: 6379
immich_server                     | }
```

### Additional information

Some important context about my setup: on my network, my DNS search-domain is let's assume `home.mydomain.com`, *and* there is also a wildcard DNS record `*.home.mydomain.com` which points unknown DNS entries to my docker server with the IP `192.168.50.123`. This server runs all my docker services, including a Traefik reverse proxy with a wildcard TLS certificate provided by let's encrypt with DNS validation. This means any new docker service I spin up on that server with the correct Traefik labels will just magically work. Immich would in this setup be accessible through `immich.home.mydomain.com` without any other configuration other than some minimal configuration in it's `docker-compose.yaml` file.

Now any DNS resolving within a docker network normally attempts to just resolve the bare service, and then attempts to use the search domain if that's not available. For some reason, for redis, this does happen, but it immediately attempts to use the search domain, attempting to look up `immich-redis.home.mydomain.com`, resolving to the IP address of my server instead of the IP of the `immich-redis` container within the docker network.
