### ISSUE TITLE
[BUG] Uploaded assets do not show in web, android, or data folder

### ISSUE THREAD

**Issue by oscarale-camorlinga** [immich-app/immich#1453]
**Describe the bug**
After a fresh install of immich I am unable to upload some assets. It looks like everything uploads fine but the asset never shows either in the web interface, on android, or even in my data folder. Logs do not show any errors except `missing 'error' handler on this Redis client` for immich_server and immich_microservices. Some images do upload ok.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Go to web interface at https://immich.example.com
2. Click on `Upload`
3. Select file from my computer
4. File is uploaded, message displays `Upload success. Refresh the page to see new upload assets`
5. Refresh the page
6. Some assets show, others do not
7. Same case on Android

**Expected behavior**
Expect to see assets, but some do not show. I have tried with png's, jpgs, and jpegs. Some work, some do not

**System**
- Android: `8.1.0`
- Server Version: `1.43.0`
- Mobile App Version: `1.42.0 build.65`
- Windows 10 Host running a VirtualBox `7.0.6` client with Ubuntu Server `22.04.1`
- Nginx `1.18.0` reverse proxy
- Docker `20.10.23`

**Additional context**
- I have an instance of Nextcloud running on the same vm.
- I am using an external hard drive connected to the Windows 10 host machine as the data folder.

Uploads correctly
![This png uploads](https://user-images.githubusercontent.com/94387753/215218177-d5e698fa-7fb4-4db7-948b-8988e60277ab.png)

Does not upload
![This png does not upload](https://user-images.githubusercontent.com/94387753/215218259-5664f32d-66f3-4cdf-9419-09f26775e1ef.png)

**docker-compose.yml**
```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

**.env**
```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/media/oscarale/photos
JWT_SECRET=secret
PUBLIC_LOGIN_PAGE_MESSAGE="My Photos"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_API_URL_EXTERNAL=https://immich.aleyoscar.com
```
