### ISSUE TITLE
Multitouch completely broken in Immich iOS app 1.122.0

### ISSUE THREAD

**Issue by Stooovie** [immich-app/immich#14553]
### The bug

Pinch to zoom is completely impossible in 1.122.0. The image just dances around erratically, Details pane goes up, but the image doesn't zoom in, at all. Pinch to zoom is 100% impossible, double tap to zoom also. [See video of me doing](https://youtube.com/shorts/JgHRQp__bU4?si=l76qkg9DaXaf0qdY) the same thing in Immich and then in Photos app. It is not fixed by force quitting the app or rebooting the phone. 

### The OS that Immich Server is running on

Proxmox LXC (Debian)

### Version of Immich Server

1.122.1

### Version of Immich Mobile App

1.122.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /media/Public/immich:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/media/Public/immich
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/root/media
TYPESENSE_API_KEY=some-random-text
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Launch Immich on iPhone
2. Open a photo 
3. Pinch to zoom 
...

### Additional information

IOS 18.1.1, iPhone 13 Pro
