### ISSUE TITLE
Immich throws a 500 error on trying to open duplicates utility

### ISSUE THREAD

**Issue by gcs8** [immich-app/immich#14562]
### The bug

Internal server error (500)

Stacktrace
Error: Error: 500
    at Object.it [as ok] (http://10.13.37.146:2283/_app/immutable/chunks/fetch-client.CaJy2xxb.js:1:7428)
    at async ue (http://10.13.37.146:2283/_app/immutable/nodes/27.C_P36dUw.js:2:1837)
    at async Ue (http://10.13.37.146:2283/_app/immutable/chunks/entry.rm4Wplw8.js:1:15799)

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.122.1

### Version of Immich Mobile App

v1.122.0 build.169

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # Mount specific NVIDIA library files individually
      - /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1:/usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
      - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1
      - /usr/local/cuda/lib64:/usr/local/cuda/lib64:ro
#      - /mnt/ext:/mnt/ext
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      # Mount specific NVIDIA library files individually
#      - /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1:/usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
#      - /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
#      - /usr/lib/x86_64-linux-gnu/libcuda.so.1:/usr/lib/x86_64-linux-gnu/libcuda.so.1
#      - /usr/local/cuda/lib64:/usr/local/cuda/lib64:ro
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELE>
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

  # set IMMICH_TELEMETRY_INCLUDE=all in .env to enable metrics
  immich-prometheus:
    container_name: immich_prometheus
    ports:
      - 9090:9090
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus


volumes:
  model-cache:
  prometheus-data:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
 TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all


NODE_OPTIONS=--max-old-space-size=8192
IMMICH_TELEMETRY_INCLUDE=all
```

### Reproduction steps

in web Ui, under user bea@, go to utilities > duplicates > sadness happens

### Relevant log output

```shell
[Nest] 17  - 12/07/2024, 1:38:21 PM   DEBUG [Api:LoggingInterceptor~k94ouyqm] GET /api/server/storage 200 131.29ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:21 PM   DEBUG [Api:LoggingInterceptor~5cajux4e] GET /api/albums 200 276.06ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:21 PM   DEBUG [Api:LoggingInterceptor~qnmoslol] GET /api/server/storage 200 129.03ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:21 PM   DEBUG [Api:LoggingInterceptor~mjbi1137] GET /api/server/about 200 843.66ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:21 PM   DEBUG [Api:LoggingInterceptor~ybt75hid] GET /api/server/version-history 200 129.96ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:22 PM   DEBUG [Api:LoggingInterceptor~y8r4dn8p] GET /api/server/about 200 931.54ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:50 PM   DEBUG [Api:LoggingInterceptor~a0c34htf] GET /api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2024-05-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true 200 37042.20ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:38:58 PM   DEBUG [Api:LoggingInterceptor~7i9iyxfa] GET /api/server/ping 200 0.54ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:38:58 PM     LOG [Api:EventRepository] Websocket Disconnect: 3qCjyuDFEnagd-mrAAAB
[Nest] 17  - 12/07/2024, 1:38:58 PM     LOG [Api:EventRepository] Websocket Disconnect: SnyvxlLqXlXynIFHAAAD
[Nest] 17  - 12/07/2024, 1:38:58 PM     LOG [Api:EventRepository] Websocket Connect:    IJEHERggqOWcqTMFAAAF
[Nest] 17  - 12/07/2024, 1:38:58 PM     LOG [Api:EventRepository] Websocket Connect:    vsbv1HlvCoaOX7e5AAAH
[Nest] 17  - 12/07/2024, 1:39:10 PM   DEBUG [Api:LoggingInterceptor~1m6avl2n] GET /api/server/ping 200 0.82ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:41:01 PM   DEBUG [Api:LoggingInterceptor~ky0q1ut5] GET /api/duplicates 200 122818.68ms ::ffff:10.6.66.161
[Nest] 17  - 12/07/2024, 1:41:19 PM   ERROR [Api:RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/usr/src/app/node_modules/express/lib/response.js:1160:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:271:14)
    at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
    at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17~ky0q1ut5] Unknown error: RangeError: Invalid string length
[Nest] 17  - 12/07/2024, 1:41:19 PM     LOG [Api:EventRepository] Websocket Disconnect: vsbv1HlvCoaOX7e5AAAH
[Nest] 17  - 12/07/2024, 1:41:19 PM     LOG [Api:EventRepository] Websocket Disconnect: IJEHERggqOWcqTMFAAAF
[Nest] 17  - 12/07/2024, 1:41:19 PM   DEBUG [Api:LoggingInterceptor~uzau4xsc] GET /api/server/ping 200 0.52ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:41:20 PM   DEBUG [Api:LoggingInterceptor~6u8803v6] GET /api/server/ping 200 0.26ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:41:20 PM   DEBUG [Api:LoggingInterceptor~idkf7h24] GET /api/server/ping 200 0.29ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:41:20 PM   DEBUG [Api:LoggingInterceptor~69gyqhu7] GET /api/server/ping 200 0.26ms ::ffff:127.0.0.1
[Nest] 17  - 12/07/2024, 1:41:20 PM     LOG [Api:EventRepository] Websocket Connect:    6mvZFMcgLzOjQAyvAAAP
[Nest] 17  - 12/07/2024, 1:41:20 PM     LOG [Api:EventRepository] Websocket Connect:    q25q04As6ziihW3XAAAQ
```

### Additional information

User: Bea
Photos: 1,311,335 (1 TiB)
Videos: 8,400 (1 TiB)
Usage: 2 TiB

all things imported with immich cli (not immich-go)
