### ISSUE TITLE
Photos (HEIC/JPG) are corrupted when uploading via iOS app

### ISSUE THREAD

**Issue by obale** [immich-app/immich#14587]
### The bug

Photos (HEIC) uploaded via the Immich iOS app are showing up as corrupted in the Immich web interface and as (corrupted) replicated image on mobile. The corrupted photos are visualized flawed and are showing green (anod other colored) artifacts. These artifacts are not always in the same location when deleting and re-uploading the photo, at least as far as I can tell.

In version v1.121.0 and before I didn't experience this issue. Downgrading the server to v1.121.0 didn't solve the issue, so it may be related to the iOS version or a combination of both (server and mobile).

Was searching for a related issue, but couldn't find any.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.122.1

### Version of Immich Mobile App

v1.122.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#                        
# WARNING: Make sure to use the docker-compose.yml of the current release:
#              
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#                                           
# The compose file on main may not be compatible with the latest release.
#                            
                                                                       
name: immich                 
                                                                       
services:          
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:  
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nextcloud:/mnt/nextcloud:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=[CENSORED}


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=pgdata

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open iOS mobile app and upload a photo
2. Check the web interface for the photo. The photo is either showing up with (green) artifacts, indicating that the file is corrupted or no thumbnail is generated (not sure if that is unrelated and fixed by now).
3. Check the iOS app to see the uploaded photo being replicated, one version is the original and one is the corrupted one.

### Relevant log output

```shell
immich_server            | [Nest] 18  - 12/08/2024, 9:28:04 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.122.1] [production] 
immich_server            | [Nest] 18  - 12/08/2024, 9:28:17 PM     LOG [Api:EventRepository] Websocket Connect:    M_FX6JytsMXxu2DzAAAB
immich_server            | [Nest] 18  - 12/08/2024, 9:28:19 PM     LOG [Api:EventRepository] Websocket Disconnect: M_FX6JytsMXxu2DzAAAB
immich_server            | [Nest] 18  - 12/08/2024, 9:28:20 PM     LOG [Api:EventRepository] Websocket Connect:    4QtHIi_eTn3YIYZ1AAAD
immich_server            | [Nest] 18  - 12/08/2024, 9:28:30 PM     LOG [Api:EventRepository] Websocket Connect:    mPXfSQvIA_W4POYGAAAF       
immich_server            | [Nest] 18  - 12/08/2024, 9:28:32 PM     LOG [Api:EventRepository] Websocket Connect:    9H78SuAWjaXxJ6-YAAAH
immich_machine_learning  | [12/08/24 21:28:39] INFO     Loading detection model 'buffalo_l' to memory                                         
immich_machine_learning  | [12/08/24 21:28:39] INFO     Setting execution providers to                     
immich_machine_learning  |                              ['CPUExecutionProvider'], in descending order of                       
immich_machine_learning  |                              preference                                          
immich_machine_learning  | [12/08/24 21:28:39] INFO     Loading visual model 'ViT-B-32__openai' to memory  
immich_machine_learning  | [12/08/24 21:28:39] INFO     Setting execution providers to                     
immich_machine_learning  |                              ['CPUExecutionProvider'], in descending order of   
immich_machine_learning  |                              preference                                          
immich_machine_learning  | [12/08/24 21:28:42] INFO     Loading recognition model 'buffalo_l' to memory    
immich_machine_learning  | [12/08/24 21:28:42] INFO     Setting execution providers to                     
immich_machine_learning  |                              ['CPUExecutionProvider'], in descending order of   
immich_machine_learning  |                              preference                                          
immich_server            | [Nest] 18  - 12/08/2024, 9:28:59 PM     LOG [Api:EventRepository] Websocket Disconnect: 9H78SuAWjaXxJ6-YAAAH
immich_server            | [Nest] 18  - 12/08/2024, 9:29:22 PM     LOG [Api:EventRepository] Websocket Disconnect: 4QtHIi_eTn3YIYZ1AAAD
immich_server            | [Nest] 18  - 12/08/2024, 9:29:23 PM     LOG [Api:EventRepository] Websocket Connect:    4fqbhA9d9TETaplXAAAJ
immich_server            | [Nest] 18  - 12/08/2024, 9:29:40 PM     LOG [Api:EventRepository] Websocket Disconnect: mPXfSQvIA_W4POYGAAAF
```
