### ISSUE TITLE
Remote Machine Learning Docs Incorrect Add Url option

### ISSUE THREAD

**Issue by owenxuereb** [immich-app/immich#14585]
### The bug

In the Remote Machine Learning Docs, There is a part stating that one can use Add Url to add a remote server so that if it goes offline, the local server url can be used. However, on the interface it is missing.

### The OS that Immich Server is running on

TOS 6.0.553

### Version of Immich Server

v1.121.0

### Version of Immich Mobile App

v1.121.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich_remote_ml

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003

volumes:
  model-cache:
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Go to: /admin/system-settings?isOpen=machine-learning+video-transcoding
2. Try to find Add Url option
3.
...
