### ISSUE TITLE
Server thinks its the following day

### ISSUE THREAD

**Issue by supershree** [immich-app/immich#14613]
### The bug

Have the timezone set to New York, but my server thinks that its Tuesday when  I am writing this on a Monday at 10:45 at night. 

### The OS that Immich Server is running on

WSL Windows

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

v1.122.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
DB_DATA_LOCATION	D:\Docker\local-immich\postgres
DB_DATABASE_NAME	immich
DB_PASSWORD	abusively-hump-casern-spammy
DB_USERNAME	postgres
IMMICH_BUILD	12226349825
IMMICH_BUILD_IMAGE	v1.122.2
IMMICH_BUILD_IMAGE_URL	https://github.com/immich-app/immich/pkgs/container/immich-server
IMMICH_BUILD_URL	https://github.com/immich-app/immich/actions/runs/12226349825
IMMICH_REPOSITORY	immich-app/immich
IMMICH_REPOSITORY_URL	https://github.com/immich-app/immich
IMMICH_SOURCE_COMMIT	03eb5903fe590532346f87a6cfbc62730911088e
IMMICH_SOURCE_REF	v1.122.2
IMMICH_SOURCE_URL	https://github.com/immich-app/immich/commit/03eb5903fe590532346f87a6cfbc62730911088e
IMMICH_VERSION	release
LD_LIBRARY_PATH	/usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib:
NODE_ENV	production
NODE_VERSION	22.11.0
NVIDIA_DRIVER_CAPABILITIES	all
NVIDIA_VISIBLE_DEVICES	all
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/bin
TZ	America/New_York
UPLOAD_LOCATION	D:\Docker\local-immich\library
YARN_VERSION	1.22.22
```

### Reproduction steps

1. Its displayed on the home page
2.
3.
...
![Screenshot 2024-12-09 224740](https://github.com/user-attachments/assets/95f66e8f-b075-480b-8453-cd733e09ee61)
