### ISSUE TITLE
Error: The pgvecto.rs extension version is 0.4.0, but Immich only supports >=0.2 <0.4

### ISSUE THREAD

**Issue by davralin** [immich-app/immich#14654]
### The bug

Error: The pgvecto.rs extension version is 0.4.0, but Immich only supports >=0.2 <0.4

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

v1.122.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
values:
    env:
      REDIS_HOSTNAME: "immich-valkey-primary"
      DB_HOSTNAME: "immich-postgres-v17-rw"
      DB_DATABASE_NAME: "immich"
    image:
      tag: "v1.122.2"
    immich:
      metrics:
        enabled: "${MONITORING_PROMETHEUS}"
      persistence:
        library:
          existingClaim: immich
    machine-learning:
      persistence:
        cache:
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: "${STORAGE_READWRITEONCE}"
        external:
          enabled: true
          existingClaim: nextcloud
          readOnly: true
    server:
      persistence:
        external:
          enabled: true
          existingClaim: nextcloud
          readOnly: true
      ingress:
        main:
          enabled: true
          annotations:
            haproxy.org/response-set-header: |
              Strict-Transport-Security "max-age=31536000"
              X-Frame-Options "DENY"
              X-Content-Type-Options "nosniff"
              Referrer-Policy "no-referrer-when-downgrade"
          hosts:
            - host: "immich.${SECRET_DEFAULT_DOMAIN}"
              paths:
                - path: "/"
          tls:
            - secretName: "${SECRET_DEFAULT_DOMAIN_CERT}"
```

### Your .env content

```Shell
values:
    env:
      REDIS_HOSTNAME: "immich-valkey-primary"
      DB_HOSTNAME: "immich-postgres-v17-rw"
      DB_DATABASE_NAME: "immich"
    image:
      tag: "v1.122.2"
    immich:
      metrics:
        enabled: "${MONITORING_PROMETHEUS}"
      persistence:
        library:
          existingClaim: immich
    machine-learning:
      persistence:
        cache:
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: "${STORAGE_READWRITEONCE}"
        external:
          enabled: true
          existingClaim: nextcloud
          readOnly: true
    server:
      persistence:
        external:
          enabled: true
          existingClaim: nextcloud
          readOnly: true
      ingress:
        main:
          enabled: true
          annotations:
            haproxy.org/response-set-header: |
              Strict-Transport-Security "max-age=31536000"
              X-Frame-Options "DENY"
              X-Content-Type-Options "nosniff"
              Referrer-Policy "no-referrer-when-downgrade"
          hosts:
            - host: "immich.${SECRET_DEFAULT_DOMAIN}"
              paths:
                - path: "/"
          tls:
            - secretName: "${SECRET_DEFAULT_DOMAIN_CERT}"
```

### Reproduction steps

````
# kubectl -n nextcloud logs -f deploy/nextcloud-immich-server
Initializing Immich v1.122.2
Detected CPU Cores: 12
Starting api worker
Starting microservices worker
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 7  - 12/11/2024, 8:19:42 PM     LOG [Microservices:EventRepository] Initialized websocket server
Error: The pgvecto.rs extension version is 0.4.0, but Immich only supports >=0.2 <0.4.
    Please change pgvecto.rs to a compatible version in the Postgres instance.
    at /usr/src/app/dist/services/database.service.js:79:23
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/dist/repositories/database.repository.js:197:23
microservices worker error: Error: The pgvecto.rs extension version is 0.4.0, but Immich only supports >=0.2 <0.4.
    Please change pgvecto.rs to a compatible version in the Postgres instance.
microservices worker exited with code 1
Killing api process
````

I see from #11624 that the max-version was hard-coded, and that #13231 speaks of a missing 17-image.

The image is out now, `ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.2-v0.4.0`
