### ISSUE TITLE
[Mobile Android] App dims when watching backup screen in progress

### ISSUE THREAD

**Issue by stephen304** [immich-app/immich#14679]
### The bug

This is an odd bug, the app itself dims on the backup screen - not my screen but just the app itself like it has a dark overlay - but I can still interact with the screen (scroll), but only when I tap does the app brighten back up. Switching apps you can see the app is super dark. It feels kind of like some idle dimming but it doesn't feel consistent. It felt like switching apps might trigger it because it has happened soon after switching apps but other times when I sit and watch the upload it doesn't want to happen. I haven't exactly nailed down when it happens but it seems trivial to reproduce in my recording:

https://github.com/user-attachments/assets/baf7d199-260a-49f5-8bf7-12de71853457

### The OS that Immich Server is running on

Synology Docker

### Version of Immich Server

v1.122.2

### Version of Immich Mobile App

v1.122.2 build.170

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
#    ports:
#      - 2283:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`example.com`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=mytlschallenge"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    networks:
      - default
      - ingress
      - mail
    depends_on:
      - redis
      - database

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    restart: always
    volumes:
      - ./volumes/ml-cache:/cache
    env_file:
      - .env

  redis:
    container_name: immich_redis
    image: docker.io/library/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: always
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESC>
      interval: 5m
#      start_interval: 30s
      start_period: 5m
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

networks:
  ingress:
    external: true
  mail:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./volumes/library
# The location where your database files are stored
DB_DATA_LOCATION=./volumes/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time>
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.122.2

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

0. Possibly have background backups enabled
1. Start backup on backup screen
2. Watch backup progress
3. Try switching apps while backup in progress
4. App dims after a bit
5. Scrolling doesn't un-dim, only tapping
