### ISSUE TITLE
Something Is Wrong With Jobs

### ISSUE THREAD

**Issue by coltenkrauter** [immich-app/immich#14715]
### The bug

Recently, the jobs page has become inaccessible to me and thumbnails are not being generated for new uploaded assets. 

I screen recorded my experience and logs: https://www.youtube.com/watch?v=_7CGnakJGHg

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm) – TrueNas Scale Electric Eel > Dockge > Compose Stack

### Version of Immich Server

v1.122.3

### Version of Immich Mobile App

v1.122.3

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 8484:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    environment:
      - IMMICH_LOG_LEVEL=verbose
      # - IMMICH_TRUSTED_PROXIES=127.0.0.1,172.17.0.0/16 # Trust localhost and Docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-server.rule=Host(`immich.krautership.com`)
      - traefik.http.routers.immich-server.entrypoints=websecure
      - traefik.http.routers.immich-server.tls.certresolver=letsencrypt
      - traefik.http.services.immich-server.loadbalancer.server.port=2283
      - traefik.docker.network=traefik_proxy
    networks:
      - traefik_proxy
      - immich_network
    deploy:
      resources:
        limits:
          memory: 12GB
          cpus: "6.0"
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich_network
    deploy:
      resources:
        limits:
          memory: 12GB
          cpus: "6.0"
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich_network
    deploy:
      resources:
        limits:
          memory: 12GB
          cpus: "6.0"
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
    networks:
      - immich_network
    deploy:
      resources:
        limits:
          memory: 12GB
          cpus: "6.0"
volumes:
  model-cache: null
networks:
  immich_network:
    driver: bridge
  traefik_proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt//******//Applications/Immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/******/Applications/Immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# IMMICH_VERSION=release
IMMICH_VERSION=v1.122.3

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD='***********'

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Go to the admin `jobs` page and it won't load. Also, new thumbnails are not being generated.

### Relevant log output

```shell
Nest] 16  - 12/15/2024, 8:52:35 PM   DEBUG [Api:LoggingInterceptor~4k5c4c2k] GET /api/server/ping 200 0.56ms ::ffff:127.0.0.1
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
missing 'error' handler on this Redis client
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:216:20)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

### Additional information

Not sure why this is happening... The only action I have recently taken is [bulk deleting some images via the API](https://github.com/immich-app/immich/discussions/14674#discussioncomment-11550760) and also, I ran a job to transcode videos (After I started the job for the first time against my large library, it said something like 40k were waiting).
