### ISSUE TITLE
Error getting places

### ISSUE THREAD

**Issue by 1bieber** [immich-app/immich#14767]
### The bug

First: I'm switching from Google Phtos and: I LOVE YOUR APP! It's genious! So, now my question:
I installad immich (1.123) a few days ago in a proxmox 8.3.0 ubuntu 24.04 LTS  LXC via the "official" Portainer instruction. The LXC is only for immich. Nothing else is running here. Everything is working fine beside the places.
If I open the Android Immich app and switch to "Places" I get the error message "Error getting places". If I click on the map, then I can see places
![photo_5406646274524047169_y](https://github.com/user-attachments/assets/81ca70f0-7419-471b-a935-9c2683e2e695)

Found similar issue here: https://github.com/immich-app/immich/issues/14696
I repeated the following steps:

- Open immich_postgres shell and exec: UPDATE system_metadata SET key = '_' || key WHERE key = 'reverse-geocoding-state';
- Afterwards I redeployed the container

Unfortunately it doesn't fix my issue. Therefore I rolled back without the database renaming. Yesterday I asked this question in discord but I did not get any helpful answer. https://discord.com/channels/979116623879368755/1318525978225676338

Maybe it helps but I had a similar issue in the past with the machine learning. It was solved via discord support in: https://discord.com/channels/979116623879368755/1049703391762321418/threads/1317823559896403988

Could anyone help me? Thank you!

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.222.3 build .171

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
TZ=Europe/Berlin
IMMICH_VERSION=release
DB_PASSWORD=xxxxxxxx
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open Immich Android App
2. Click on Library
3.Click on places
You see the map and the message "Error getting places"

OR
1. Open Immich in browser
2. Click on Explore
You see only faces, no places
