### ISSUE TITLE
User deleted after updating from v1.122.2 to v1.123.0

### ISSUE THREAD

**Issue by Mehyar-ALS** [immich-app/immich#14771]
### The bug

After updating from [v1.122.2](https://github.com/immich-app/immich/releases/tag/v1.122.2) to [v1.123.0](https://github.com/immich-app/immich/releases/tag/v1.123.0), the app signed out and when I tried to check Immich from the browser directly I was greeted with the initial greeting message from Immich as if my instance was just created. The admin user (which is my only user) was deleted. I tried and created the user again with the exact same information and logged in, but I can't see my photos. I have downgraded back to [v1.122.2](https://github.com/immich-app/immich/releases/tag/v1.122.2) but still didn't fix it.

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS aarch64

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

V1.22.3 build.171

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    user: ${PUID}:${GUID}
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    user: ${PUID}:${GUID}
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=/mnt/hdd/immich
#UPLOAD_LOCATION=/mnt/truenas/mehyar/immich
UPLOAD_LOCATION=/mnt/truenas/immich

# run as user Mehyar
PUID=1000
GUID=1000

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.123.0"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Update from v1.122.2 to  v1.123.0
