### ISSUE TITLE
V1.123 - database password not accepted.

### ISSUE THREAD

**Issue by Prankish8407** [immich-app/immich#14773]
### The bug

Docker-compose file:
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${data_path}/__mediaPersonal/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${data_path}/__mediaPersonal/immich/cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${data_path}/__mediaPersonal/immich/database:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

global docker-enviroment for immich:
```
# ------------------------------------------------------------------------------------------------------
# immich
# ------------------------------------------------------------------------------------------------------
data_path="/srv/dev-disk-by-uuid-33c07464-b0c9-421e-9048-a97110e44943/data"
IMMICH_VERSION="v1.123.0"
DB_PASSWORD="MYsuperSECRETpasswordFORimmichV1123"
DB_USERNAME="postgres"
DB_DATABASE_NAME="immich"`


Now i've made a few changes, so you dont have look for them:

1: i removed .env from the 4 services as i use global enviroments for all my containers to have everything in a single file.
2:  i've changed these things in docker-compose to match the global enviroment variables:

`  immich-server:
    volumes:
      - ${data_path}/__mediaPersonal/immich/library:/usr/src/app/upload`

`  immich-machine-learning:
    volumes:
      - ${data_path}/__mediaPersonal/immich/cache:/cache`

`  database:
    volumes:
      - ${data_path}/__mediaPersonal/immich/database:/var/lib/postgresql/data\
```

now the logs give me an error for the database password, even if i keep it as default with postgres.
see logs below:

### The OS that Immich Server is running on

Debian (docker-compose)

### Version of Immich Server

V1.123

### Version of Immich Mobile App

na

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
see above
```

### Your .env content

```Shell
see above
```

### Reproduction steps

see above

### Relevant log output

```shell
immich_redis             | 1:C 18 Dec 2024 11:28:16.729 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis             | 1:C 18 Dec 2024 11:28:16.729 # Redis version=6.2.16, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis             | 1:C 18 Dec 2024 11:28:16.729 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis             | 1:M 18 Dec 2024 11:28:16.730 * monotonic clock: POSIX clock_gettime
immich_redis             | 1:M 18 Dec 2024 11:28:16.730 * Running mode=standalone, port=6379.
immich_redis             | 1:M 18 Dec 2024 11:28:16.730 # Server initialized
immich_redis             | 1:M 18 Dec 2024 11:28:16.730 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis             | 1:M 18 Dec 2024 11:28:16.731 * Ready to accept connections
immich_machine_learning  | [12/18/24 11:28:18] INFO     Starting gunicorn 23.0.0                           
immich_machine_learning  | [12/18/24 11:28:18] INFO     Listening at: http://[::]:3003 (9)                 
immich_server            | Initializing Immich v1.123.0
immich_machine_learning  | [12/18/24 11:28:18] INFO     Using worker: app.config.CustomUvicornWorker       
immich_server            | Detected CPU Cores: 4
immich_machine_learning  | [12/18/24 11:28:18] INFO     Booting worker with pid: 10                        
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | (node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
immich_server            | (Use `node --trace-deprecation ...` to show where the warning was created)
immich_server            | (node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
immich_server            | (Use `node --trace-deprecation ...` to show where the warning was created)
immich_server            | (node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
immich_server            | (Use `node --trace-deprecation ...` to show where the warning was created)
immich_postgres          | 
immich_postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres          | 
immich_postgres          | 2024-12-18 11:28:16.906 UTC [1] LOG:  redirecting log output to logging collector process
immich_postgres          | 2024-12-18 11:28:16.906 UTC [1] HINT:  Future log output will appear in directory "log".
immich_machine_learning  | [12/18/24 11:28:26] INFO     Started server process [10]                        
immich_machine_learning  | [12/18/24 11:28:26] INFO     Waiting for application startup.                   
immich_machine_learning  | [12/18/24 11:28:26] INFO     Created in-memory cache with unloading after 300s  
immich_machine_learning  |                              of inactivity.                                     
immich_machine_learning  | [12/18/24 11:28:26] INFO     Initialized request thread pool with 4 threads.    
immich_machine_learning  | [12/18/24 11:28:26] INFO     Application startup complete.                      
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 12/18/2024, 11:28:49 AM   ERROR [ExceptionHandler] password authentication failed for user "postgres"
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | api worker exited with code 1
```

### Additional information

see above
