### ISSUE TITLE
NVEC encoder not working 

### ISSUE THREAD

**Issue by rirze** [immich-app/immich#14782]
### The bug

I think my `immich_server` is defaulting to cpu transcoding after failing to utilize my 3090 gpu with the following errors in the log. 
The facial recognition is working, so I think it's not a problem with the docker container accessing my gpu....

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    profiles:
      - immich
    networks:
      - caddy_network
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      PUID: "1000"
      PGID: "1000"
    
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
    ports:
      - '2283:2283'
    labels:
      caddy: immich.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 2283}}"
    depends_on:
      - immich_redis
      - immich_postgres
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    profiles:
      - immich
    networks:
      - caddy_network    
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000          
    restart: always
    healthcheck:
      disable: false

  immich_redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    profiles:
      - immich
    networks:
      - caddy_network
    environment:
      - PUID=1000
      - PGID=1000          
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich_postgres:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    profiles:
      - immich
    networks:
      - caddy_network    
    environment:
      PUID: "1000"
      PGID: "1000"    
    
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=$MEDIA_ROOT/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<some_password>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Backup some video files (these specific files were taken on an iPhone12)
2. Observe this error in logs
3.
...

### Relevant log output

```shell
[Nest] 7  - 12/18/2024, 9:43:18 PM   ERROR [Microservices:MediaService] Retrying with NVENC-accelerated encoding and software decoding
[Nest] 7  - 12/18/2024, 9:43:21 PM   ERROR [Microservices:MediaRepository]   libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[aist#0:1/pcm_s16le @ 0x46e72194e80] Guessed Channel Layout: mono
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/57e50fbe-43c7-497a-8e29-1d3c54648ab9/2024/2024-10-18/IMG_2358.MOV':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2024-10-18T12:44:59.000000Z
    com.apple.quicktime.live-photo.auto: 1
    com.apple.quicktime.content.identifier: 0255B69E-5496-438E-A04E-B9D8DDC2029E
    com.apple.quicktime.live-photo.vitality-score: 1.000000
    com.apple.quicktime.live-photo.vitality-scoring-version: 0
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 12 Pro
    com.apple.quicktime.software: 15.5
    com.apple.quicktime.creationdate: 2024-10-18T18:14:59+0530
  Duration: 00:00:02.70, start: 0.000000, bitrate: 13463 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, smpte170m/smpte432/bt709, left), 1920x1440, 12645 kb/s, 14.39 fps, 17.75 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-10-18T12:44:59.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](und): Audio: pcm_s16le (lpcm / 0x6D63706C), 44100 Hz, mono, s16, 705 kb/s (default)
      Metadata:
        creation_time   : 2024-10-18T12:44:59.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-10-18T12:44:59.000000Z
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 30 kb/s (default)
      Metadata:
        creation_time   : 2024-10-18T12:44:59.000000Z
        handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 504 kb/s (default)
      Metadata:
        creation_time   : 2024-10-18T12:44:59.000000Z
        handler_name    : Core Media Metadata
[out#0/mp4 @ 0x46e721712c0] Adding streams from explicit maps...
[vost#0:0/av1_nvenc @ 0x46e73456a80] Created video stream from input stream 0:0
[aost#0:1/copy @ 0x46e73456d80] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> av1 (av1_nvenc))
  Stream #0:1 -> #0:1 (copy)
[vost#0:0/av1_nvenc @ 0x46e73456a80] Starting thread...
[vf#0:0 @ 0x46e73631440] Starting thread...
[vist#0:0/hevc @ 0x46e721945c0] [dec:hevc @ 0x46e7206ea00] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080] Starting thread...
Press [q] to stop, [?] for help
[graph 0 input from stream 0:0 @ 0x46e78050b40] w:1920 h:1440 pixfmt:yuvj420p tb:1/600 fr:71/4 sar:0/1 csp:smpte170m range:pc
[auto_scale_0 @ 0x46e78050d80] w:iw h:ih flags:'' interl:0
[transpose @ 0x46e78050a80] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:0' and the filter 'transpose'
[swscaler @ 0x46e78686000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x46e78050d80] w:1920 h:1440 fmt:yuvj420p csp:unknown range:pc sar:0/1 -> w:1920 h:1440 fmt:yuv420p csp:unknown range:unknown sar:0/1 flags:0x00000004
[transpose @ 0x46e78050a80] w:1920 h:1440 dir:1 -> w:1440 h:1920 rotation:clockwise vflip:0
[graph 0 input from stream 0:0 @ 0x46e78050b40] video frame properties congruent with link at pts_time: 0
[swscaler @ 0x46e78686000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x46e78050d80] w:1920 h:1440 fmt:yuvj420p csp:unknown range:pc sar:0/1 -> w:1920 h:1440 fmt:yuv420p csp:unknown range:unknown sar:0/1 flags:0x00000004
[swscaler @ 0x46e78686000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x46e78050d80] w:1920 h:1440 fmt:yuvj420p csp:unknown range:pc sar:0/1 -> w:1920 h:1440 fmt:yuv420p csp:unknown range:unknown sar:0/1 flags:0x00000004
[swscaler @ 0x46e78686000] deprecated pixel format used, make sure you did set range correctly
[auto_scale_0 @ 0x46e78050d80] w:1920 h:1440 fmt:yuvj420p csp:smpte170m range:pc sar:0/1 -> w:1920 h:1440 fmt:yuv420p csp:unknown range:unknown sar:0/1 flags:0x00000004
[av1_nvenc @ 0x46e721b8180] Using input frames context (format cuda) with av1_nvenc encoder.
[av1_nvenc @ 0x46e721b8180] Loaded Nvenc version 12.2
[av1_nvenc @ 0x46e721b8180] Nvenc initialized successfully
[av1_nvenc @ 0x46e721b8180] Codec not supported
[av1_nvenc @ 0x46e721b8180] Provided device doesn't support required NVENC features
[av1_nvenc @ 0x46e721b8180] Nvenc unloaded
[vost#0:0/av1_nvenc @ 0x46e73456a80] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 0x46e73631440] Error sending frames to consumers: Function not implemented
[vf#0:0 @ 0x46e73631440] Task finished with error code: -38 (Function not implemented)
[vf#0:0 @ 0x46e73631440] Terminating thread with return code -38 (Function not implemented)
[vist#0:0/hevc @ 0x46e721945c0] [dec:hevc @ 0x46e7206ea00] Decoder returned EOF, finishing
[vist#0:0/hevc @ 0x46e721945c0] [dec:hevc @ 0x46e7206ea00] Terminating thread with return code 0 (success)
[vist#0:0/hevc @ 0x46e721945c0] All consumers of this stream are done
[vost#0:0/av1_nvenc @ 0x46e73456a80] Encoder thread received EOF
[vost#0:0/av1_nvenc @ 0x46e73456a80] Could not open encoder before EOF
[vost#0:0/av1_nvenc @ 0x46e73456a80] Task finished with error code: -22 (Invalid argument)
[vost#0:0/av1_nvenc @ 0x46e73456a80] Terminating thread with return code -22 (Invalid argument)
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080] Terminating thread with return code 0 (success)
[out#0/mp4 @ 0x46e721712c0] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[AVIOContext @ 0x46e72069640] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080] Input file #0 (upload/library/57e50fbe-43c7-497a-8e29-1d3c54648ab9/2024/2024-10-18/IMG_2358.MOV):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080]   Input stream #0:0 (video): 29 packets read (3327353 bytes); 3 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080]   Input stream #0:1 (audio): 117 packets read (238484 bytes); 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x46e72122080]   Total: 146 packets (3565837 bytes) demuxed
[AVIOContext @ 0x46e72067ac0] Statistics: 5334836 bytes read, 57 seeks
Conversion failed!
```

### Additional information

My transcoding settings:
```
{
....
  "ffmpeg": {
    "accel": "nvenc",
    "accelDecode": true,
    "acceptedAudioCodecs": [
      "aac",
      "mp3",
      "libopus",
      "pcm_s16le"
    ],
    "acceptedContainers": [
      "mov",
      "ogg",
      "webm"
    ],
    "acceptedVideoCodecs": [
      "av1"
    ],
    "bframes": -1,
    "cqMode": "auto",
    "crf": 35,
    "gopSize": 0,
    "maxBitrate": "10000",
    "preferredHwDevice": "auto",
    "preset": "veryslow",
    "refs": 0,
    "targetAudioCodec": "aac",
    "targetResolution": "original",
    "targetVideoCodec": "av1",
    "temporalAQ": true,
    "threads": 0,
    "tonemap": "hable",
    "transcode": "required",
    "twoPass": true
  },
....
```
