### ISSUE TITLE
Cannot download selected images via the WebUI - Cannot read properties of undefined (reading 'selectedAssets')

### ISSUE THREAD

**Issue by lusu007** [immich-app/immich#14797]
### The bug

I attempted to download assets shared via Partner sharing. I selected multiple assets and clicked download, but nothing happened. Additionally, the back button appears to be broken.

### The OS that Immich Server is running on

24.04.1 LTS

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - public
      - tunnel
      - immich
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`images.redacted.cloud`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:

networks:
  public:
    external: true
    name: public
  tunnel:
    external: true
    name: tunnel
  immich:
    external: true
    name: immich
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/ssd-1tb/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/ssd-1tb/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
#DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

#REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Go to the Overview page of a shared account
2. Select images 
3. Click download

### Relevant log output

Log from the browser´s console when clicking the download button
```shell
asset-interaction.svelte.BFRtm1No.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'selectedAssets')
    at clearMultiselect (asset-interaction.svelte.BFRtm1No.js:1:2957)
    at HTMLButtonElement.a [as __click] (download-action.Bf8GO955.js:1:793)
    at HTMLDivElement.A (store.DM1mbn8n.js:1:2297)
```

Log from the browser´s console when clicking the discard/back button
```shell
store.DM1mbn8n.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'selectedAssets')
    at clearMultiselect (asset-interaction.svelte.BFRtm1No.js:1:2957)
    at HTMLButtonElement.j [as __click] (control-app-bar.C0mI-DDn.js:1:1321)
    at HTMLDivElement.A (store.DM1mbn8n.js:1:2297)
```
