### ISSUE TITLE
Mobile App Issues: Crashing on video playback and Media refresh issue post deletion from mobile

### ISSUE THREAD

**Issue by schizovivek** [immich-app/immich#14845]
### The bug

So there are two issues I'm currently observing. Have two phones; S22+ and LG v30. The issues are persistent on both phones.

What I'm currently doing is backing up the pics from our phones into immich. Once I do that I move the backed up files into another folder on my NAS thereby deleting it from the phone.

First Issue:
App crashes on playing a video not on the phone. 
If I play any video that's no longer on the phone the app just straight up crashes. No error no nothing. Just closes.

Second Issue:
Thumbnails don't refresh for media moved out of phone.
Once I've moved all the media out of the phone (post backup) the app just shows blurred out images for all the media that's been deleted. On clicking the actual image doesn't seem to load. 
The only way I found to resolve this was to sign out and sign back in. That's the only time the data seems to refresh on the app. I tried a pull down to refresh and that did nothing.

![image](https://github.com/user-attachments/assets/27450cf5-7168-43d8-b966-42fd44c6cd36)

### The OS that Immich Server is running on

Ubuntu 23.04

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0 build.172

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
Doesn't seem related
```

### Your .env content

```Shell
Doesn't seem related
```

### Reproduction steps

1. Backup data from phone to server
2. Delete data on the phone
3. Re-launch Immich
4. Check if the images are being shown (that were deleted from the phone) 
5. Sign out and sign back in
6. Now try to launch a video that is only on the server

**Comment by schizovivek** [comment]
Just realize something. The App crashes even if I swipe into a video from an image.

**Comment by alextran1502** [comment]
How did you remove the media from the phone? is it through the file explorer or the native photos app?

**Comment by schizovivek** [comment]
Yeh. Used the file explorer .. X-plore to be precise

**Comment by alextran1502** [comment]
That is probably why the app does not get notified why files are deleted

**Comment by schizovivek** [comment]
Just wondering. Is there a better way to refresh the cache other than signing out and signing back in?

The first issue is a bit more concerning for me. We have a lot of videos and app crashing makes the app basically unusable. I have a feeling this issue is not recent and has been an issue since the version with the rendering issue.

**Comment by alextran1502** [comment]
@schizovivek it was not designed with that action in mind so we will have to look at the implementation on how to clear the cache that way

**Comment by schizovivek** [comment]
The caching isn't the biggest concern honestly.  For the app crashing on the video is there something I can provide that could help debug the issue?

**Comment by alextran1502** [comment]
@schizovivek Yes, the video as well as your video transcoding settings

**Comment by schizovivek** [comment]
Haven't changed any of the default settings.
The video issue is with any video. I'm just attaching here a video that I was sent and that I uploaded to immich. 

**Note:**
These same videos cause no issues when already present on the mobile device. They only cause an issue when they have to load from the server

**Transcoding settings**
![image](https://github.com/user-attachments/assets/1cbb63a5-22d8-4b17-9ce0-68d9d2dfa5c1)

**Video:**
https://github.com/user-attachments/assets/97137939-6c2d-4079-afde-94456be01d60

**Comment by alextran1502** [comment]
Hmm, settings looks fine, do you see any button to reset to default on the bottom of the transcoding settings section?

FWIW, I uploaded the video to my instance and it was playing fine as a remote asset on both Pixel 8 and Samsung S23

**Comment by schizovivek** [comment]
Just did the following
1. Reset the transcoding settings
2. Ran the transcoding job
3. On my LG cleared the App cache and data
4. Added the URLs again 
5. Logged in
6. Launched the same video
7. Crash

These are the logs I see in my immich docker server

```logs
ESC[32m[Nest] 17  - ESC[39m12/19/2024, 10:43:33 PM ESC[32m    LOGESC[39m ESC[33m[Api:RouterExplorer]ESC[39m ESC[32mMapped {/api/assets/statistics, GET} routeESC[39m
[Nest] 7  - 12/20/2024, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 12/20/2024, 12:00:00 AM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:161:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/20/2024, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "07fbf4cd-718b-40d9-8474-7cee66a0f155"
}

[Nest] 17  - 12/20/2024, 1:29:58 AM   ERROR [Api:DatabaseService~ws13zg9j] Database disconnected: error: terminating connection due to administrator command
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:17) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:7) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[Nest] 7  - 12/21/2024, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 12/21/2024, 12:00:00 AM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:161:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 12/21/2024, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "07fbf4cd-718b-40d9-8474-7cee66a0f155"
}

[Nest] 17  - 12/21/2024, 11:03:31 AM   ERROR [Api:StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:415:29)
    at ServerResponse.emit (node:events:536:35)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 12/21/2024, 11:03:41 AM   ERROR [Api:StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:415:29)
    at ServerResponse.emit (node:events:536:35)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 17  - 12/21/2024, 11:03:59 AM   ERROR [Api:StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:415:29)
    at ServerResponse.emit (node:events:536:35)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```

**Comment by schizovivek** [comment]
Looks like they're older logs. Don't see anything in the most recent logs
This is all I see

```
[Nest] 17  - 12/21/2024, 9:19:00 PM     LOG [Api:EventRepository] Websocket Connect:    UN7MrEPsd1a0x6SVAACF
[Nest] 17  - 12/21/2024, 9:19:10 PM     LOG [Api:EventRepository] Websocket Disconnect: VWFYEzP3x2YJ9CzTAACD
[Nest] 17  - 12/21/2024, 9:19:13 PM     LOG [Api:EventRepository] Websocket Connect:    KlnwZRFVsCnQMaUGAACH
[Nest] 17  - 12/21/2024, 9:19:19 PM     LOG [Api:EventRepository] Websocket Disconnect: KlnwZRFVsCnQMaUGAACH
[Nest] 17  - 12/21/2024, 9:19:22 PM     LOG [Api:EventRepository] Websocket Connect:    wR_A1RTiEXPG7OAIAACJ
[Nest] 17  - 12/21/2024, 9:21:13 PM     LOG [Api:EventRepository] Websocket Disconnect: wR_A1RTiEXPG7OAIAACJ
[Nest] 17  - 12/21/2024, 9:21:16 PM     LOG [Api:EventRepository] Websocket Connect:    b9hEuKeSuJ4_Fsn7AACL
[Nest] 17  - 12/21/2024, 9:21:23 PM     LOG [Api:EventRepository] Websocket Connect:    H7dNyrxERulMry_AAACN
[Nest] 17  - 12/21/2024, 9:21:25 PM     LOG [Api:EventRepository] Websocket Disconnect: UN7MrEPsd1a0x6SVAACF
[Nest] 17  - 12/21/2024, 9:21:29 PM     LOG [Api:EventRepository] Websocket Disconnect: H7dNyrxERulMry_AAACN
[Nest] 17  - 12/21/2024, 9:21:31 PM     LOG [Api:EventRepository] Websocket Connect:    GKinTga4kg3o3OKvAACP
[Nest] 17  - 12/21/2024, 9:21:56 PM     LOG [Api:EventRepository] Websocket Disconnect: GKinTga4kg3o3OKvAACP
[Nest] 17  - 12/21/2024, 9:22:44 PM     LOG [Api:EventRepository] Websocket Connect:    vRKNVhSFrGv3G7aWAACR
[Nest] 17  - 12/21/2024, 9:22:57 PM     LOG [Api:EventRepository] Websocket Disconnect: vRKNVhSFrGv3G7aWAACR
[Nest] 17  - 12/21/2024, 9:24:54 PM     LOG [Api:EventRepository] Websocket Connect:    3ChN8WPo_Ev5m3M3AACT
[Nest] 17  - 12/21/2024, 9:25:28 PM     LOG [Api:EventRepository] Websocket Disconnect: 3ChN8WPo_Ev5m3M3AACT
```

**Comment by alextran1502** [comment]
How did you install Immich on your instance?

**Comment by schizovivek** [comment]
docker compose

.env file
```yaml
# THESE TWO VARIABLES COME FROM ANOTHER ENV FILE
HOST_USER=<my user>
HOST_GROUP=<same as above>

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/pool/personal/memories
EXTERNAL_LIBRARY=/mnt/pool/personal/memories_non_immich
# The location where your database files are stored
DB_DATA_LOCATION=/home/<my user>/.config/dockerapps/immich/db

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/London

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.123.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<my pwd>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=db
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=redis

MODEL_CACHE=/home/<my user>/.config/dockerapps/immich/model-cache

# Config variable
#IMMICH_CONFIG_FILE=immich.json
```

compose.yaml
```yaml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  server:
    # container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      # - ${EXTERNAL_LIBRARY}:${EXTERNAL_LIBRARY}:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      user: ${HOST_USER}:${HOST_GROUP}
    ports:
      - 9006:2283
    depends_on:
      - redis
      - db
    restart: unless-stopped
    healthcheck:
      disable: false

  ml:
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${MODEL_CACHE}:/cache
    env_file:
      - .env
    environment:
      user: ${HOST_USER}:${HOST_GROUP}
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    environment:
      user: ${HOST_USER}:${HOST_GROUP}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    # env_file:
    #   - .env
    environment:
      user: ${HOST_USER}:${HOST_GROUP}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
```
