### ISSUE TITLE
Thumbnail generation fails, Immich server crashes (VipsJpeg: Messages are not supported)

### ISSUE THREAD

**Issue by tbham** [immich-app/immich#14855]
### The bug

When generating thumbnails, Immich server crashes. Error messages provided below.

Following the crash, Immich server continually attempts to restart (docker container is set to restart unless stopped), but crashes again as soon as the web server starts. There is no log output provided by Immich server for these subsequent crashes.

The issue appears to relate to thumbnail generation for Sony .ARW files. I've not observed the issue with jpeg files. Uncompressed raw and Lossless compressed raw have been tried.

The issue occurs following upload of .ARW via the web browser and the automatic thumbnail generation job, and when running the thumbnail generation job manually on missing thumbnails.

First encountered in v1.122.X, and occurring in v1.123.0 (I didn't own a raw capable camera prior to v1.122.X, so cannot speak to earlier versions).

Docker compose and env below. Note that I have replace docker volumes with bind mounts, and I am running as non-root.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: "${IMMICH_UID}:${IMMICH_GID}"
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}/upload:/usr/src/app/upload/upload
      - ${UPLOAD_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${UPLOAD_LOCATION}/library:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}/profile:/usr/src/app/upload/profile
      - ${UPLOAD_LOCATION}/backups:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    restart: always

immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    user: "${IMMICH_UID}:${IMMICH_GID}"
    volumes:
      #- model-cache:/cache
      - ${MACHINE_LEARNING_DATA}/cache:/cache
      - ${MACHINE_LEARNING_DATA}/.cache:/.cache
      - ${MACHINE_LEARNING_DATA}/.config:/.config
    env_file:
      - .env
    healthcheck:
      disable: false
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    user: "${IMMICH_UID}:${IMMICH_GID}"
    volumes:
      - ${REDIS_DATA}:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    #user: "${IMMICH_UID}:${IMMICH_GID}" # running postgres as non-root results in permission error. it is unclear if this has an impact.
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_U>
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/photos/immich
THUMBS_LOCATION=./data/thumbs
DB_DATA_LOCATION=./data/db
MACHINE_LEARNING_DATA=./data/ml
REDIS_DATA=./data/redis/data

# The Immich version to use. Previous stable version "v1.122.3"
IMMICH_VERSION="v1.123.0"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# Define host user/group to run immich as
IMMICH_UID=1007
IMMICH_GID=1006

# Define timezone
TZ="..."


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1a. Upload .ARW files via web UI, or
1b. Manually trigger thumbnail generation job for .ARW files which are missing thumbnails
2. Immich crashes, producing below error message
3. Immich continually restarts and crashes as soon as web server starts, no log entries provided for these crashes
4. Manually stop docker container and restart
...

### Relevant log output

```shell
[Nest] 7  - 12/22/2024, 9:51:44 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 12/22/2024, 9:51:44 AM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:161:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

### Additional information

Nil
