### ISSUE TITLE
Cannot download multiple files at once

### ISSUE THREAD

**Issue by abelmarquez14** [immich-app/immich#14895]
### The bug

![errorImmich](https://github.com/user-attachments/assets/9cc33378-54ad-4262-a7bd-6587364ae067)

Error while downloading a bunch of files, with large size.
Happened 3+ times in the same IOS device with the same album.

### The OS that Immich Server is running on

Synology DSM 7.2.1-69057 Update 6

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=America/Mexico_City
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=America/Mexico_City
      - POSTGRES_DB=immich
      - POSTGRES_USER=<secret>
      - POSTGRES_PASSWORD=<secret>
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
UPLOAD_LOCATION=./volume1/docker/immich/upload
DB_DATA_LOCATION=./volume1/docker/immich/db
DB_USERNAME=<secret>
DB_PASSWORD=<secret>
DB_DATABASE_NAME=immich
DB_HOSTNAME=<secret>
NOVE_ENV=production
REDIS_HOSTNAME=immich-redis
TZ=America/Mexico_City
LOG_LEVEL=log
JWT_SECRET=<secret>
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1.Open a folder
2.Click download button
3.Error appears

### Relevant log output

```shell
[Nest] 7  - 12/19/2024, 1:41:26 PM     LOG [Microservices:MapRepository] 180000 geodata records imported
[Nest] 7  - 12/19/2024, 1:41:28 PM     LOG [Microservices:MapRepository] 190000 geodata records imported
[Nest] 7  - 12/19/2024, 1:41:28 PM     LOG [Microservices:MapRepository] 200000 geodata records imported
[Nest] 7  - 12/19/2024, 1:41:43 PM     LOG [Microservices:MapRepository] Geodata import completed
[Nest] 7  - 12/19/2024, 1:41:43 PM     LOG [Microservices:MetadataService] Initialized local reverse geocoder
[Nest] 7  - 12/19/2024, 1:41:43 PM     LOG [Microservices:ServerService] Feature Flags: {
  "smartSearch": true,
  "facialRecognition": true,
  "duplicateDetection": true,
  "map": true,
  "reverseGeocoding": true,
  "importFaces": false,
  "sidecar": true,
  "search": true,
  "trash": true,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false,
  "email": false
}
[Nest] 7  - 12/19/2024, 1:41:43 PM     LOG [Microservices:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
[Nest] 7  - 12/19/2024, 1:41:43 PM     LOG [Microservices:StorageService] Successfully verified system mount folder checks
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:SystemConfigService] LogLevel=log (set via system config)
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:NestFactory] Starting Nest application...
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] OpenTelemetryModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] OpenTelemetryCoreModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] DiscoveryModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] ClsModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] BullModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] TypeOrmCoreModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] TypeOrmModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:InstanceLoader] MicroservicesModule dependencies initialized
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:NestApplication] Nest application successfully started
[Nest] 7  - 12/19/2024, 1:41:44 PM     LOG [Microservices:Bootstrap] Immich Microservices is running [v1.123.0] [production] 
[Nest] 25  - 12/19/2024, 1:47:13 PM     LOG [Api:EventRepository] Websocket Connect:    gGB-v1HFGgvvQaDiAAAB
[Nest] 25  - 12/19/2024, 1:56:38 PM     LOG [Api:EventRepository] Websocket Connect:    g0fop0BnRNjak5AHAAAD
[Nest] 25  - 12/19/2024, 1:56:40 PM     LOG [Api:EventRepository] Websocket Connect:    Sr79RMzi8W-f159GAAAF
[Nest] 25  - 12/19/2024, 1:57:41 PM     LOG [Api:EventRepository] Websocket Disconnect: Sr79RMzi8W-f159GAAAF
[Nest] 25  - 12/19/2024, 1:57:42 PM     LOG [Api:EventRepository] Websocket Connect:    WC44AWO_klgpgLaLAAAH
[Nest] 25  - 12/19/2024, 1:58:36 PM   ERROR [Api:StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:415:29)
    at ServerResponse.emit (node:events:536:35)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 25  - 12/19/2024, 1:59:17 PM     LOG [Api:EventRepository] Websocket Disconnect: WC44AWO_klgpgLaLAAAH
[Nest] 25  - 12/19/2024, 1:59:28 PM     LOG [Api:EventRepository] Websocket Disconnect: g0fop0BnRNjak5AHAAAD
[Nest] 25  - 12/19/2024, 2:03:32 PM   ERROR [Api:StreamableFile] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at ServerResponse.<anonymous> (node:internal/streams/pipeline:415:29)
    at ServerResponse.emit (node:events:536:35)
    at emitCloseNT (node:_http_server:1033:10)
    at Socket.onServerResponseClose (node:_http_server:284:5)
    at Socket.emit (node:events:536:35)
    at TCP.<anonymous> (node:net:350:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
[Nest] 25  - 12/19/2024, 2:10:51 PM     LOG [Api:EventRepository] Websocket Connect:    oAuFIi1Zj_7QrjD_AAAJ
[Nest] 25  - 12/19/2024, 2:10:53 PM     LOG [Api:EventRepository] Websocket Connect:    Bf9--mFs_YT3T_HiAAAL
[Nest] 25  - 12/19/2024, 2:11:03 PM     LOG [Api:EventRepository] Websocket Connect:    qR7JHKPVLMMWowX2AAAN
[Nest] 25  - 12/19/2024, 2:11:06 PM     LOG [Api:EventRepository] Websocket Connect:    DtKEt4_aRBXtSadDAAAP
[Nest] 25  - 12/19/2024, 2:11:06 PM     LOG [Api:EventRepository] Websocket Connect:    x4566KEYVt09qKaWAAAR
[Nest] 25  - 12/19/2024, 2:11:09 PM     LOG [Api:EventRepository] Websocket Connect:    NY71-3pue1GgzwNRAAAT
[Nest] 7  - 12/19/2024, 2:11:35 PM    WARN [Microservices:MetadataService] Asset 7b679c8d-0fb5-4500-a391-8d553e70f236 has no time zone information
[Nest] 7  - 12/19/2024, 2:11:35 PM    WARN [Microservices:MetadataService] Asset 7b679c8d-0fb5-4500-a391-8d553e70f236 has no valid date, falling back to asset.fileCreatedAt
[Nest] 25  - 12/19/2024, 2:11:36 PM     LOG [Api:EventRepository] Websocket Disconnect: oAuFIi1Zj_7QrjD_AAAJ
[Nest] 25  - 12/19/2024, 2:11:38 PM     LOG [Api:EventRepository] Websocket Disconnect: Bf9--mFs_YT3T_HiAAAL
[Nest] 25  - 12/19/2024, 2:11:48 PM     LOG [Api:EventRepository] Websocket Disconnect: qR7JHKPVLMMWowX2AAAN
[Nest] 25  - 12/19/2024, 2:11:51 PM     LOG [Api:EventRepository] Websocket Disconnect: DtKEt4_aRBXtSadDAAAP
[Nest] 25  - 12/19/2024, 2:11:51 PM     LOG [Api:EventRepository] Websocket Disconnect: x4566KEYVt09qKaWAAAR
[Nest] 25  - 12/19/2024, 2:13:13 PM     LOG [Api:EventRepository] Websocket Disconnect: NY71-3pue1GgzwNRAAAT
[Nest] 25  - 12/19/2024, 2:13:29 PM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 25  - 12/19/2024, 2:13:29 PM    WARN [Api:FileUploadInterceptor] Error: aborted
[Nest] 7  - 12/19/2024, 2:13:58 PM    WARN [Microservices:MetadataService] Asset 86fd77e8-b168-4c3d-a83e-5b5c7792cf8f has no time zone information
[Nest] 7  - 12/19/2024, 2:13:58 PM    WARN [Microservices:MetadataService] Asset 86fd77e8-b168-4c3d-a83e-5b5c7792cf8f has no valid date, falling back to asset.fileCreatedAt
[Nest] 7  - 12/19/2024, 2:14:03 PM    WARN [Microservices:MetadataService] Asset 15254d3b-8fb4-480c-93bc-123f9e521f0f has no time zone information
[Nest] 7  - 12/19/2024, 2:14:03 PM    WARN [Microservices:MetadataService] Asset 15254d3b-8fb4-480c-93bc-123f9e521f0f has no valid date, falling back to asset.fileCreatedAt
[Nest] 7  - 12/19/2024, 2:14:11 PM     LOG [Microservices:PersonService] Detected 2 new faces in asset 86fd77e8-b168-4c3d-a83e-5b5c7792cf8f
[Nest] 25  - 12/19/2024, 2:14:12 PM     LOG [Api:EventRepository] Websocket Connect:    LckacCtxKh43yMsyAAAV
[Nest] 7  - 12/19/2024, 2:14:14 PM     LOG [Microservices:PersonService] Detected 8 new faces in asset 15254d3b-8fb4-480c-93bc-123f9e521f0f
[Nest] 25  - 12/19/2024, 2:14:33 PM     LOG [Api:EventRepository] Websocket Disconnect: LckacCtxKh43yMsyAAAV
[Nest] 25  - 12/19/2024, 2:16:34 PM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 25  - 12/19/2024, 2:16:34 PM    WARN [Api:FileUploadInterceptor] Error: aborted
[Nest] 25  - 12/19/2024, 2:18:56 PM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 25  - 12/19/2024, 2:18:56 PM    WARN [Api:FileUploadInterceptor] Error: aborted
[Nest] 25  - 12/19/2024, 2:19:00 PM     LOG [Api:EventRepository] Websocket Connect:    qxvEb9BAgg_SVDphAAAX
[Nest] 25  - 12/19/2024, 2:19:06 PM     LOG [Api:EventRepository] Websocket Connect:    JFTIvWWc-sl1toZeAAAZ
[Nest] 25  - 12/19/2024, 2:22:43 PM     LOG [Api:EventRepository] Websocket Disconnect: JFTIvWWc-sl1toZeAAAZ
[Nest] 25  - 12/19/2024, 2:22:43 PM     LOG [Api:EventRepository] Websocket Disconnect: qxvEb9BAgg_SVDphAAAX
[Nest] 25  - 12/19/2024, 2:22:43 PM    WARN [Api:FileUploadInterceptor] Request error while uploading file, cleaning up
[Nest] 25  - 12/19/2024, 2:22:43 PM    WARN [Api:FileUploadInterceptor] Error: aborted
[Nest] 25  - 12/19/2024, 2:25:37 PM     LOG [Api:EventRepository] Websocket Connect:    nGkJ2s-VAUVu7jyPAAAb
[Nest] 25  - 12/19/2024, 2:26:22 PM     LOG [Api:EventRepository] Websocket Disconnect: nGkJ2s-VAUVu7jyPAAAb
[Nest] 25  - 12/19/2024, 2:57:11 PM     LOG [Api:EventRepository] Websocket Disconnect: gGB-v1HFGgvvQaDiAAAB
```
