### ISSUE TITLE
Postgress permission issue, SELinux prevents creation of `upload/encoded-video`

### ISSUE THREAD

**Issue by james-pre** [immich-app/immich#14912]
### The bug

Originally, the database wouldn't start. `docker logs immich_postgres` showed an error:
```
chmod: changing permissions of '/var/lib/postgresql/data': Permission denied
```

I was able to resolve the problem by changing the `DB_DATA_LOCATION` in `.env` from `./postgres` to `postgres` and adding `postgress` to the `volumes` in `docker-compose.yml`, which I saw on a Stack Overflow post.

This lead to a second error, this time with `immich_server`:
```
[Nest] 17  - 12/24/2024, 4:19:03 PM   ERROR [Api:StorageService] Failed to create upload/encoded-video/.immich: Error: EACCES: permission denied, mkdir 'upload/encoded-video'
```

After some digging, I was able to resolve this as a SELinux issue. `grep "denied" /var/log/audit/audit.log | audit2allow -M immich && semodule -i immich.pp` created this policy:

```

module immich 1.0;

require {
	type init_t;
	type container_t;
	type systemd_homed_t;
	type var_t;
	class dir { add_name create read setattr write };
	class file { create execute execute_no_trans ioctl open read write };
}

#============= container_t ==============
allow container_t var_t:dir { add_name create setattr write };
allow container_t var_t:file { create open read write };

#============= init_t ==============
allow init_t var_t:file { execute execute_no_trans ioctl open read };

#============= systemd_homed_t ==============
allow systemd_homed_t var_t:dir read;
```

I was then able to run `restorecon -R /var/lib/docker/overlay2/b17db39b7785b3cc0def65484448499b78a88b1f8d3d6b43bc31c45bb77a3453`, which allows the server to run correctly.

### The OS that Immich Server is running on

Fedora 41

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  postgres:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[[redacted]]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

This bug occurred after a default install using the [install sscript](https://immich.app/docs/install/script).

### Relevant log output

```shell
See messages above
```
