### ISSUE TITLE
iOS: syncing files hangs after a while, uploading "flickers" forever

### ISSUE THREAD

**Issue by umrath** [immich-app/immich#14948]
### The bug

When syncing files from an iPhone or iPad (observed on an iPad Pro 2019, iPhone 12 and iPhone 15, all on the latest software) to immich it works fine until eventually it hangs at a certain asset (usually a video) and stays there forever, flickering the state between some percentage and 0. (see attached video)

This happens at different stages on different devices and is not related to the size of the file (although it is usally a video) as other files of the same size work just fine.

Reinstalling the app on the iPhone won't change anything. It will eventually hang in this state forever.
As a side effect this heats up the device significantly.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@hourly"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=CET

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. install immich server
2. install immich app on iOS (iPhone/iPad)
3. sync whole photos libary
4. wait

https://github.com/user-attachments/assets/71b8375e-9059-4842-b262-12b9ffb628a3

### Relevant log output

```shell
Not sure if relevant, but the server spams errors like this, which I cannot make sense of:

[Nest] 17  - 12/27/2024, 9:36:56 AM   ERROR [Api:AssetMediaService~11fery8n] Error uploading file BadRequestException: Live photo video must be a video
BadRequestException: Live photo video must be a video
    at onBeforeLink (/usr/src/app/dist/utils/asset.util.js:102:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:100:17)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:40:29)
[Nest] 17  - 12/27/2024, 9:36:58 AM   ERROR [Api:AssetMediaService~50stk12b] Error uploading file BadRequestException: Live photo video must be a video
BadRequestException: Live photo video must be a video
    at onBeforeLink (/usr/src/app/dist/utils/asset.util.js:102:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:100:17)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:40:29)
[Nest] 17  - 12/27/2024, 9:37:00 AM   ERROR [Api:AssetMediaService~ormecd4i] Error uploading file BadRequestException: Live photo video must be a video
BadRequestException: Live photo video must be a video
    at onBeforeLink (/usr/src/app/dist/utils/asset.util.js:102:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:100:17)
    at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:40:29)
```

### Additional information

Sometimes, the upload does not end up in a "flicker" but simply resets in some way and starts anew.
Evntually it will end up in the described state, though.
