### ISSUE TITLE
Android app shows .arw / .dng files originally taken in portrait mode with wrong orientation in detail view

### ISSUE THREAD

**Issue by pr10dr** [immich-app/immich#14957]
### The bug

The android app shows .arw  and .dng files (generated from .arw) 90 degrees turned to the right.
Tested about 30 images in my collection and all exhibit the described behaviour.

The thumbnail is orientated correctly.
The initial (my guess preview image) is orientated correctly.
But after a short brief initial period of roughly 1s the full size image is loaded (as configured by me).

Sample files can be found here:
https://drive.google.com/file/d/1mhu4FMg4ffTIeXfFYTTEA3hLvLGJJHcn/view?usp=sharing

incorrect_portrait.dng - It is a portrait image that will be shown with the wrong orientation in the android app.
correct_horizontal.dng - Is a landscape image that will be shown correctly in the android app. Taken with the same camera as above image.

 

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

v1.123

### Version of Immich Mobile App

v1.123 build. 172

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:    
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file: stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      

    devices:
        - /dev/dri:/dev/dri
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
      

      
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    env_file: stack.env
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    restart: always
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri

  

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    env_file: stack.env
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file: stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

volumes:
  model-cache:
  postgres-data:
```

### Your .env content

```Shell
UPLOAD_LOCATION: /mnt/remote/immich
DB_DATA_LOCATION: postgres-data
IMMICH_VERSION: release
DB_PASSWORD: donthackme
DB_USERNAME: hackerman
DB_DATABASE_NAME: immich
```

### Reproduction steps

1. Upload attached images
2. set android app to show "full size images" 
3. after showing the file in android app correctly for about 1 second the high resolution image should be loaded
4. The high res image should be shown with the wrong orientation in the app.

### Relevant log output

```shell
exiftool incorrect_portrait.dng

ExifTool Version Number         : 13.10
File Name                       : incorrect_portrait.dng
Directory                       : .
File Size                       : 24 MB
File Modification Date/Time     : 2024:12:27 16:40:30+01:00
File Access Date/Time           : 2024:12:27 16:49:54+01:00
File Inode Change Date/Time     : 2024:12:27 16:49:52+01:00
File Permissions                : -rw-r--r--
File Type                       : DNG
File Type Extension             : dng
MIME Type                       : image/x-adobe-dng
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : SONY
Camera Model Name               : ILCE-7
Strip Offsets                   : 24302452
Orientation                     : Rotate 270 CW
Rows Per Strip                  : 171
Strip Byte Counts               : 131328
Software                        : Adobe Photoshop Lightroom 5.7 (Windows)
Modify Date                     : 2015:02:22 13:33:09
Image Width                     : 6048
Image Height                    : 4024
Bits Per Sample                 : 16
Compression                     : JPEG
Photometric Interpretation      : Color Filter Array
Samples Per Pixel               : 1
Planar Configuration            : Chunky
CFA Repeat Pattern Dim          : 2 2
CFA Pattern 2                   : 0 1 1 2
CFA Plane Color                 : Red,Green,Blue
CFA Layout                      : Rectangular
Black Level Repeat Dim          : 2 2
Black Level                     : 512 512 512 512
White Level                     : 16300
Default Scale                   : 1 1
Default Crop Origin             : 12 12
Default Crop Size               : 6000 4000
Bayer Green Split               : 250
Anti Alias Strength             : 1
Best Quality Scale              : 1
Active Area                     : 0 0 4024 6048
Opcode List 3                   : WarpRectilinear
Preview Image Start             : 23720316
Preview Image Length            : 89431
Y Cb Cr Coefficients            : 0.299 0.587 0.114
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Y Cb Cr Positioning             : Co-sited
Reference Black White           : 0 255 128 255 128 255
Subfile Type                    : Reduced-resolution image
Tile Width                      : 256
Tile Length                     : 176
Tile Offsets                    : 24288556
Tile Byte Counts                : 13895
Opcode List 2                   : MapPolynomial, MapPolynomial, MapPolynomial
Cache Version                   : 0.1.0.0
XMP Toolkit                     : Adobe XMP Core 5.5-c002 1.148022, 2012/07/15-18:06:45
Lens                            : DT 0mm F0 SAM
Lens Distort Info               : 33084/32768 -50562690/1073741824 62045843/1073741824 -24649026/1073741824
Format                          : image/dng
Date Created                    : 2015:02:22 13:33:09
Creator Tool                    : Adobe Photoshop Lightroom 5.7 (Windows)
Metadata Date                   : 2015:03:05 20:43:08+01:00
Document ID                     : xmp.did:34a8129e-47c1-b848-ad9f-bfb4d56c9e9e
Instance ID                     : xmp.iid:affc818a-39a6-164f-aaed-50618da46689
Original Document ID            : 1532198AA39B240AEF1CE577E78CF3A8
Version                         : 8.7
Process Version                 : 6.7
Auto White Version              : 134348800
Tint                            : +5
Luminance Smoothing             : 0
Color Noise Reduction           : 25
Vignette Amount                 : 0
Shadow Tint                     : 0
Red Hue                         : 0
Red Saturation                  : 0
Green Hue                       : 0
Green Saturation                : 0
Blue Hue                        : 0
Blue Saturation                 : 0
Vibrance                        : 0
Hue Adjustment Red              : 0
Hue Adjustment Orange           : 0
Hue Adjustment Yellow           : 0
Hue Adjustment Green            : 0
Hue Adjustment Aqua             : 0
Hue Adjustment Blue             : 0
Hue Adjustment Purple           : 0
Hue Adjustment Magenta          : 0
Saturation Adjustment Red       : 0
Saturation Adjustment Orange    : 0
Saturation Adjustment Yellow    : 0
Saturation Adjustment Green     : 0
Saturation Adjustment Aqua      : 0
Saturation Adjustment Blue      : 0
Saturation Adjustment Purple    : 0
Saturation Adjustment Magenta   : 0
Luminance Adjustment Red        : 0
Luminance Adjustment Orange     : 0
Luminance Adjustment Yellow     : 0
Luminance Adjustment Green      : 0
Luminance Adjustment Aqua       : 0
Luminance Adjustment Blue       : 0
Luminance Adjustment Purple     : 0
Luminance Adjustment Magenta    : 0
Split Toning Shadow Hue         : 0
Split Toning Shadow Saturation  : 0
Split Toning Highlight Hue      : 0
Split Toning Highlight Saturation: 0
Split Toning Balance            : 0
Parametric Shadows              : 0
Parametric Darks                : 0
Parametric Lights               : 0
Parametric Highlights           : 0
Parametric Shadow Split         : 25
Parametric Midtone Split        : 50
Parametric Highlight Split      : 75
Sharpen Radius                  : +1.0
Sharpen Detail                  : 25
Sharpen Edge Masking            : 0
Post Crop Vignette Amount       : 0
Grain Amount                    : 0
Color Noise Reduction Detail    : 50
Color Noise Reduction Smoothness: 50
Lens Profile Enable             : 0
Lens Manual Distortion Amount   : 0
Perspective Vertical            : 0
Perspective Horizontal          : 0
Perspective Rotate              : 0.0
Perspective Scale               : 100
Perspective Aspect              : 0
Perspective Upright             : Off
Auto Lateral CA                 : 0
Exposure 2012                   : 0.00
Contrast 2012                   : 0
Highlights 2012                 : 0
Shadows 2012                    : +40
Whites 2012                     : 0
Blacks 2012                     : 0
Clarity 2012                    : 0
Defringe Purple Amount          : 0
Defringe Purple Hue Lo          : 30
Defringe Purple Hue Hi          : 70
Defringe Green Amount           : 0
Defringe Green Hue Lo           : 40
Defringe Green Hue Hi           : 60
Convert To Grayscale            : False
Tone Curve Name                 : Medium Contrast
Tone Curve Name 2012            : Linear
Camera Profile                  : Adobe Standard
Camera Profile Digest           : 24DB427054E183A10DED3CF64B3851FA
Lens Profile Setup              : LensDefaults
Has Settings                    : True
Already Applied                 : False
Raw File Name                   : springer india 2015-02437.dng
Derived From Document ID        : 1532198AA39B240AEF1CE577E78CF3A8
Derived From Original Document ID: 1532198AA39B240AEF1CE577E78CF3A8
History Action                  : derived, saved, saved
History Parameters              : converted from image/x-sony-arw to image/dng, saved to new location
History Changed                 : /, /metadata
History Instance ID             : xmp.iid:34a8129e-47c1-b848-ad9f-bfb4d56c9e9e, xmp.iid:affc818a-39a6-164f-aaed-50618da46689
History Software Agent          : Adobe Photoshop Lightroom 5.7 (Windows), Adobe Photoshop Lightroom 5.7 (Windows)
History When                    : 2015:02:28 14:33:07+01:00, 2015:03:05 20:43:08+01:00
Tone Curve                      : 0, 0, 32, 22, 64, 56, 128, 128, 192, 196, 255, 255
Tone Curve Red                  : 0, 0, 255, 255
Tone Curve Green                : 0, 0, 255, 255
Tone Curve Blue                 : 0, 0, 255, 255
Tone Curve PV2012               : 0, 0, 255, 255
Tone Curve PV2012 Red           : 0, 0, 255, 255
Tone Curve PV2012 Green         : 0, 0, 255, 255
Tone Curve PV2012 Blue          : 0, 0, 255, 255
Exposure Time                   : 1/500
F Number                        : 4.0
ISO                             : 100
Sensitivity Type                : Recommended Exposure Index
Recommended Exposure Index      : 100
Exif Version                    : 0230
Date/Time Original              : 2015:02:22 13:33:09
Create Date                     : 2015:02:22 13:33:09
Shutter Speed Value             : 1/500
Aperture Value                  : 4.0
Brightness Value                : 8.3609375
Exposure Compensation           : 0
Max Aperture Value              : 2.8
Metering Mode                   : Center-weighted average
Light Source                    : Unknown
Flash                           : Off, Did not fire
Focal Length                    : 38.0 mm
Color Space                     : sRGB
Focal Plane X Resolution        : 1675.257385
Focal Plane Y Resolution        : 1675.257385
Focal Plane Resolution Unit     : cm
File Source                     : Digital Camera
Scene Type                      : Directly photographed
Custom Rendered                 : Normal
Digital Zoom Ratio              : 1
Focal Length In 35mm Format     : 38 mm
Scene Capture Type              : Standard
Lens Model                      : DT 0mm F0 SAM
GPS Version ID                  : 2.2.0.0
GPS Latitude Ref                : North
GPS Longitude Ref               : East
GPS Time Stamp                  : 11:34:03
GPS Map Datum                   : WGS-84
GPS Date Stamp                  : 2015:02:22
DNG Version                     : 1.4.0.0
DNG Backward Version            : 1.3.0.0
Unique Camera Model             : Sony ILCE-7
Color Matrix 1                  : 0.7491 -0.3027 0.0351 -0.4231 1.1579 0.3031 -0.0818 0.1721 0.7466
Color Matrix 2                  : 0.5271 -0.0712 -0.0347 -0.6153 1.3653 0.2763 -0.1601 0.2366 0.7242
Camera Calibration 1            : 0.9935 0 0 0 1 0 0 0 0.9918
Camera Calibration 2            : 0.9935 0 0 0 1 0 0 0 0.9918
Analog Balance                  : 1 1 1
As Shot Neutral                 : 0.401254 1 0.729345
Baseline Exposure               : 0.35
Baseline Noise                  : 0.6
Baseline Sharpness              : 1.33
Linear Response Limit           : 1
Shadow Scale                    : 1
Rating                          : 0
Contrast                        : 0
Saturation                      : 0
Sharpness                       : 0
Brightness                      : 0
Long Exposure Noise Reduction   : Off
High ISO Noise Reduction        : Off
HDR                             : Off; Uncorrected image
WB Shift AB GM                  : 0 0
Face Info Offset                : 94
Sony Date Time                  : 2015:02:22 13:33:09
Sony Image Height               : 4000
Sony Image Width                : 6000
Faces Detected                  : 0
Face Info Length                : 37
Meta Version                    : DC7303320222000
Creative Style                  : Standard
Color Temperature               : Auto
Color Compensation Filter       : 0
Scene Mode                      : Standard
Zone Matching                   : ISO Setting Used
Dynamic Range Optimizer         : Auto
Image Stabilization             : Off
Color Mode                      : Standard
Full Image Size                 : 6000x4000
Preview Image Size              : 1616x1080
File Format                     : ARW 2.3.1
Quality                         : RAW
Flash Exposure Compensation     : 0
White Balance Fine Tune         : 0
White Balance                   : Auto
Sony Model ID                   : ILCE-7
Teleconverter                   : None
Multi Frame Noise Reduction     : Off
Picture Effect                  : Off
Soft Skin Effect                : Off
Vignetting Correction           : Auto
Lateral Chromatic Aberration    : Auto
Distortion Correction Setting   : Off
Lens Type                       : Sony DT 50mm F1.8 SAM (SAL50F18) or Tamron Lens or Commlite CM-EF-NEX adapter
Lens Spec                       : Unknown (01 0 0 0 0 02)
Auto Portrait Framed            : No
Flash Action                    : Did not fire
Electronic Front Curtain Shutter: On
Focus Mode                      : Manual
AF Area Mode Setting            : Flexible Spot
Flexible Spot Position          : 320 240
AF Point Selected               : n/a
AF Points Used                  : (none)
AF Tracking                     : Off
Multi Frame NR Effect           : Normal
Exposure Mode                   : Shutter speed priority AE
Flash Level                     : Normal
Release Mode                    : Continuous
Sequence Number                 : 2
Anti-Blur                       : Off
Shot Number Since Power Up      : 7
Sequence Image Number           : 2
Sequence File Number            : 2
Sequence Length                 : Continuous
Camera Orientation              : Rotate 270 CW
Quality 2                       : RAW
Model Release Year              : 2014
AF Area Mode                    : Manual
Focus Position 2                : 255
Exposure Program                : Shutter speed priority AE
Intelligent Auto                : Off
Lens Zoom Position              : 0%
Sony ISO                        : 100
Base ISO                        : 100
Stops Above Base ISO            : 0
Sony Exposure Time 2            : 1/512
Sony Max Aperture Value         : 3.0
Sony Image Width Max            : 6024
Sony Image Height Max           : 4024
Picture Effect 2                : Off
Distortion Correction           : None
Distortion Corr Params          : -1 -1 -7 -15 -29 -45 -67 -91 -120 -151 -187 0 0 0 0 0
Vignetting Corr Params          : 0 6 32 75 134 208 296 387 505 676 919 0 0 0 0 0
Chromatic Aberration Corr Params: -25 -16 0 26 61 124 159 91 -10 -111 -183 -183 -183 -183 -183 -183 -178 -106 -34 41 118 201 279 337 401 491 624 624 624 624 624 624
Battery Temperature             : 41.1 C
Battery Level                   : 58%
Lens Mount 2                    : Unknown
Lens Type 3                     : Sony LA-EA1 or Sigma MC-11 Adapter
Camera E-mount Version          : 1.40
Release Mode 3                  : Continuous
Self Timer                      : Off
Flash Mode                      : Wireless
HDR Setting                     : Off
Picture Profile                 : Gamma Still - Standard/Neutral (PP2)
WB RGB Levels                   : 639 256 350
Min Focal Length                : 0.0 mm
Distortion Corr Params Number   : 16 (Full-frame)
Aspect Ratio                    : 3:2
Shutter                         : Mechanical (2851 5192 6529)
Flash Status                    : No Flash present
Shutter Count                   : 5479
Sony Exposure Time              : 1/512
Sony F Number                   : 3.8
Shutter Count 2                 : 5479
Sony Date Time 2                : 2015:02:22 12:33:09
Release Mode 2                  : Continuous Low
Internal Serial Number          : 15ff7b0a
Lens Mount                      : A-mount
Lens Format                     : APS-C
Distortion Corr Params Present  : Yes
APS-C Size Capture              : Off
Lens Spec Features              : DT SAM
SR2 Sub IFD Offset              : 48864
SR2 Sub IFD Length              : 56958
SR2 Sub IFD Key                 : 0x44332211
Warning                         : [minor] Bad IDC_IFD SubDirectory start
Calibration Illuminant 1        : Standard Light A
Calibration Illuminant 2        : D65
Raw Data Unique ID              : 00000000000000000F6B2487E6898559
Original Raw File Name          : DSC02437.ARW
Camera Calibration Sig          : com.adobe
Profile Calibration Sig         : com.adobe
Profile Name                    : Adobe Standard
Profile Hue Sat Map Dims        : 90 30 1
Profile Hue Sat Map Data 1      : (large array of 8100 float values)
Profile Hue Sat Map Data 2      : (large array of 8100 float values)
Profile Embed Policy            : Allow Copying
Profile Copyright               : Copyright 2013 Adobe Systems, Inc.
Forward Matrix 1                : 0.5906 0.2451 0.1285 0.3866 0.5739 0.0395 0.2397 0.0005 0.5849
Forward Matrix 2                : 0.5654 0.2335 0.1654 0.3604 0.5881 0.0515 0.1882 0.0024 0.6345
Preview Application Name        : Adobe Photoshop Lightroom
Preview Application Version     : 5.7
Preview Settings Digest         : cc2cad0ca1f9a27abc24af40d99cb22e
Preview Color Space             : sRGB
Preview Date Time               : 2015:02:28 14:33:07+01:00
Profile Look Table Dims         : 36 8 16
Profile Look Table Data         : (large array of 13824 float values)
Noise Profile                   : 1.85534447241932e-05 5.44607495481391e-09 1.87075608453498e-05 5.41347766991977e-09 1.8997482261387e-05 5.40183578245757e-09
New Raw Image Digest            : 1dc6c126678b8405923d5b5458da1f71
Aperture                        : 4.0
CFA Pattern                     : [Red,Green][Green,Blue]
Image Size                      : 6048x4024
Lens ID                         : DT 0mm F0 SAM
Megapixels                      : 24.3
Preview Image                   : (Binary data 89431 bytes, use -b option to extract)
Shutter Speed                   : 1/500
Thumbnail TIFF                  : (Binary data 131544 bytes, use -b option to extract)
GPS Date/Time                   : 2015:02:22 11:34:03Z
GPS Latitude                    : 18 deg 55' 26.14" N
GPS Longitude                   : 72 deg 49' 56.35" E
Focus Distance 2                : inf
Blue Balance                    : 1.367188
GPS Position                    : 18 deg 55' 26.14" N, 72 deg 49' 56.35" E
Light Value                     : 13.0
Red Balance                     : 2.496094
Scale Factor To 35 mm Equivalent: 1.0
Circle Of Confusion             : 0.030 mm
Field Of View                   : 50.7 deg
Focal Length                    : 38.0 mm (35 mm equivalent: 38.0 mm)
Hyperfocal Distance             : 12.01 m
```
