### ISSUE TITLE
The Live Photo in HEIC Format Cannot Be Converted Properly

### ISSUE THREAD

**Issue by weicheng199** [immich-app/immich#14991]
### The bug

[20240825094426_IMG_0249.zip](https://github.com/user-attachments/files/18274778/20240825094426_IMG_0249.zip)
Images can be opened using potplayer video player software,The server can also convert the thumbnails normally,But there is no preview of the big picture.
Previews are also not displayed properly in the timeline,When we execute the thumbnail task, we get a log error

![image](https://github.com/user-attachments/assets/a001f839-3e91-4619-80f7-8d7130e5dd78)

![image](https://github.com/user-attachments/assets/aca2957a-0663-4a8e-a653-a3d77172238a)

![image](https://github.com/user-attachments/assets/5f579ca8-eba2-402b-8e85-c29a19872ce8)

### The OS that Immich Server is running on

Docker Desktop win10

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.123.1 build.186(IOS)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "G:\\Docker\\相册\\2024:/mnt/media/my-media:ro" # import path in Windows system.
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

HEIC files are synched to windows using a Pho APP from the IOS App Store.
https://apps.apple.com/cn/app/pho-%E5%90%8C%E6%AD%A5%E7%85%A7%E7%89%87%E5%88%B0nas-%E7%BD%91%E7%9B%98/id6451428709
 

### Relevant log output

```shell
2024-12-30 21:05:07 [Nest] 7  - 12/30/2024, 1:05:07 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
2024-12-30 21:05:07 [Nest] 7  - 12/30/2024, 1:05:07 PM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
2024-12-30 21:05:07     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
2024-12-30 21:05:07     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:57:68)
2024-12-30 21:05:07     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:161:63)
2024-12-30 21:05:07     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-30 21:05:07     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:111:25)
2024-12-30 21:05:07     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
2024-12-30 21:05:07     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:134:13)
2024-12-30 21:05:07     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
2024-12-30 21:05:07     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
2024-12-30 21:05:07 [Nest] 7  - 12/30/2024, 1:05:07 PM   ERROR [Microservices:JobService] Object:
2024-12-30 21:05:07 {
2024-12-30 21:05:07   "id": "64b353f6-4136-4b80-87b4-0ad1e1e07a51"
2024-12-30 21:05:07 }
```
