### ISSUE TITLE
Memories 0 years ago 

### ISSUE THREAD

**Issue by Dawo9889** [immich-app/immich#14998]
### The bug

Hi
I seem to have noticed a bug on the web app where one photo from Dec 31, 2023 appears in a memory that is 0 years ago. On the mobile app it works fine. I also have other photos from that day and they appear normally. In the same way, when I select the button to go to the original photo it can't find it. When I manually go through it displays on the timeline of December 31. 
I did not see any error log. Does it have a connection to this warning in the logs? But I see the date appears normally in the image.

![image](https://github.com/user-attachments/assets/bd71d31a-499e-4e11-bdbb-14252d4f9d42)

![image](https://github.com/user-attachments/assets/7e39f9e5-562c-45eb-af65-18b1d58b4ad5)

### The OS that Immich Server is running on

NAME="Debian GNU/Linux" VERSION_ID="12" VERSION="12 (bookworm)"

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=<UPLOAD LOCATION>

# The location where your database files are stored
DB_DATA_LOCATION=/docker/immich/postgres/

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Warsaw
IMMICH_API_TOKEN=<TOKEN> 
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<PASSWORD>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

PUID=1000
PGID=1000
```

### Reproduction steps

1. Open web
2. See memories section
3.
...

### Relevant log output

```shell
immich_server  | [Nest] 7  - 12/31/2024, 12:00:36 AM    WARN [Microservices:PersonService] Face 9add3c74-5e90-49db-a26b-3b263f65eac0 not found
immich_server  | [Nest] 7  - 12/31/2024, 2:35:57 AM    WARN [Microservices:MetadataService] Asset 5fbb9b6e-1542-4a1e-bfb5-41691d8eb4e8 has no time zone information
immich_server  | [Nest] 7  - 12/31/2024, 2:35:57 AM    WARN [Microservices:MetadataService] Asset 5fbb9b6e-1542-4a1e-bfb5-41691d8eb4e8 has no valid date, falling back to asset.fileCreatedAt
immich_server  | [Nest] 7  - 12/31/2024, 2:36:02 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 5fbb9b6e-1542-4a1e-bfb5-41691d8eb4e8
immich_server  | [Nest] 7  - 12/31/2024, 4:25:52 AM    WARN [Microservices:MetadataService] Asset 4094d37b-5f25-4a9c-b9aa-77a90b6f8398 has no time zone information
immich_server  | [Nest] 7  - 12/31/2024, 4:25:52 AM    WARN [Microservices:MetadataService] Asset 4094d37b-5f25-4a9c-b9aa-77a90b6f8398 has no valid date, falling back to asset.fileCreatedAt
immich_server  | [Nest] 17  - 12/31/2024, 9:22:41 AM     LOG [Api:EventRepository] Websocket Connect:    pLw129YMptIsKL0LAACc
immich_server  | [Nest] 17  - 12/31/2024, 9:24:25 AM     LOG [Api:EventRepository] Websocket Disconnect: pLw129YMptIsKL0LAACc
immich_server  | [Nest] 17  - 12/31/2024, 9:26:38 AM     LOG [Api:EventRepository] Websocket Connect:    LA9h-4gXBX-KaThRAACe
immich_server  | [Nest] 17  - 12/31/2024, 9:28:36 AM     LOG [Api:EventRepository] Websocket Connect:    qNbsNVyGiYV6E95-AACg
immich_server  | [Nest] 17  - 12/31/2024, 9:28:41 AM     LOG [Api:EventRepository] Websocket Disconnect: LA9h-4gXBX-KaThRAACe
immich_server  | [Nest] 17  - 12/31/2024, 9:33:11 AM     LOG [Api:EventRepository] Websocket Connect:    Kj_C1uXDvxWCNk33AACi
```
