### ISSUE TITLE
Not saving external library import path

### ISSUE THREAD

**Issue by Patesz22** [immich-app/immich#14999]
### The bug

When I try to add an external library path to immich it says that the path is valid (there's a green checkmark beside the path) but when I press the "Scan library" button nothing happens and the log says "Invalid path"
Also, the previously added path disappears after a page refresh
Whenever I try to add a path, it says "This path already exists"

### The OS that Immich Server is running on

Raspberry Pi OS - basically debian

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Kepek/Kepek:/kepek
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - data:/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  data:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/patrik/docker/immich/upload
DB_DATA_LOCATION=/home/patrik/docker/immich/db
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
12/31/2024, 11:22:00 AM   DEBUG [Api:LoggingInterceptor~ad7fx2jk] GET /api/libraries 200 6.08ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:00 AM   DEBUG [Api:LoggingInterceptor~cfsj2xme] GET /api/server/ping 200 0.72ms ::ffff:127.0.0.1
[Nest] 18  - 12/31/2024, 11:22:01 AM   DEBUG [Api:LoggingInterceptor~sdyunxiu] GET /api/admin/users 200 8.99ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:02 AM   DEBUG [Api:LoggingInterceptor~b69d227m] POST /api/libraries 201 14.79ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:02 AM VERBOSE [Api:LoggingInterceptor~b69d227m] {"ownerId":"3ab28bdf-c8c3-4b13-bb17-56df0c9d172a"}
[Nest] 18  - 12/31/2024, 11:22:02 AM   DEBUG [Api:LoggingInterceptor~64ia0dxs] GET /api/libraries 200 6.21ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:02 AM   DEBUG [Api:LoggingInterceptor~hyodv6gk] GET /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/statistics 200 11.79ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:02 AM   DEBUG [Api:LoggingInterceptor~g9l59gdn] GET /api/admin/users/3ab28bdf-c8c3-4b13-bb17-56df0c9d172a 200 9.67ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:04 AM   DEBUG [Api:LoggingInterceptor~rndpkx2k] POST /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/validate 200 3.25ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:04 AM VERBOSE [Api:LoggingInterceptor~rndpkx2k] {"importPaths":[]}
[Nest] 18  - 12/31/2024, 11:22:08 AM   DEBUG [Api:LoggingInterceptor~8hasjbyq] POST /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/validate 200 5.75ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:08 AM VERBOSE [Api:LoggingInterceptor~8hasjbyq] {"importPaths":["/kepek"]}
[Nest] 18  - 12/31/2024, 11:22:13 AM   DEBUG [Api:LoggingInterceptor~1b5oppku] POST /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/scan 204 67.42ms ::ffff:192.168.0.46
[Nest] 8  - 12/31/2024, 11:22:13 AM     LOG [Microservices:LibraryService] Refreshing library 1fde7024-a87d-4fbd-b59b-59fd65d80fb8 for new assets
[Nest] 8  - 12/31/2024, 11:22:13 AM    WARN [Microservices:LibraryService] No valid import paths found for library 1fde7024-a87d-4fbd-b59b-59fd65d80fb8
[Nest] 8  - 12/31/2024, 11:22:13 AM     LOG [Microservices:LibraryService] Scanning library 1fde7024-a87d-4fbd-b59b-59fd65d80fb8 for removed assets
[Nest] 8  - 12/31/2024, 11:22:13 AM   DEBUG [Microservices:LibraryService] Discovered 0 asset(s) in library 1fde7024-a87d-4fbd-b59b-59fd65d80fb8...
[Nest] 8  - 12/31/2024, 11:22:13 AM   DEBUG [Microservices:LibraryService] Queued check of 0 asset(s) in library 1fde7024-a87d-4fbd-b59b-59fd65d80fb8...
[Nest] 18  - 12/31/2024, 11:22:14 AM   DEBUG [Api:LoggingInterceptor~kskybtpb] POST /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/validate 200 1.85ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:14 AM VERBOSE [Api:LoggingInterceptor~kskybtpb] {"importPaths":["/kepek"]}
[Nest] 18  - 12/31/2024, 11:22:22 AM     LOG [Api:EventRepository] Websocket Disconnect: uhg6_nS9R9VyfFibAAAD
[Nest] 18  - 12/31/2024, 11:22:22 AM   DEBUG [Api:LoggingInterceptor~gji8e90z] GET /custom.css 200 44.70ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:22 AM   DEBUG [Api:LoggingInterceptor~8hpi8cfa] GET /api/users/me 200 2.06ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~isxbe508] GET /api/server/features 200 64.13ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~ewzxa8gt] GET /api/server/config 200 86.67ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~rmliev1o] GET /api/users/me/preferences 200 1.32ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~isjemqki] GET /api/server/about 200 119.73ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~454omuzi] GET /api/server/storage 200 1.51ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~ptdk0nyi] GET /api/admin/users?withDeleted=false 200 7.52ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM     LOG [Api:EventRepository] Websocket Connect:    hdyWyAGjBpwhXGYYAAAF
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~i5v9rgeo] GET /api/server/storage 200 6.70ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~pof0ix8t] GET /api/server/version-history 200 11.09ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~rye0c5q5] GET /api/libraries 200 7.76ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~vqgw6rai] GET /api/server/about 200 140.94ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~y97ze23s] GET /api/server/about 200 105.04ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~42wctk3s] GET /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/statistics 200 9.08ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:23 AM   DEBUG [Api:LoggingInterceptor~zrn6ddcb] GET /api/admin/users/3ab28bdf-c8c3-4b13-bb17-56df0c9d172a 200 7.89ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:24 AM   DEBUG [Api:LoggingInterceptor~dbqdcw3s] POST /api/libraries/1fde7024-a87d-4fbd-b59b-59fd65d80fb8/validate 200 1.69ms ::ffff:192.168.0.46
[Nest] 18  - 12/31/2024, 11:22:24 AM VERBOSE [Api:LoggingInterceptor~dbqdcw3s] {"importPaths":[]}
[Nest] 18  - 12/31/2024, 11:22:31 AM   DEBUG [Api:LoggingInterceptor~ol8mz3kg] GET /api/server/ping 200 0.98ms ::ffff:127.0.0.1
```

### Additional information

https://www.youtube.com/watch?v=zDNthkR6c9w

I've already tried and didn't work:
- Restart
- Delete relevant images, volumes before redeploy -> "fresh install"
- Portainer install
- Experimental script install
- Reinstall docker
- Reformat os drive and then reinstall
- Setting perms to 777 on the drive that is being mounted to the container
- (also the container defiantly has access to the drive without setting prems to 777, because I can read/write to the disk from the container)
- Mounting different parts of the system drive / home directory

![pic](https://github.com/user-attachments/assets/7273925e-1231-421b-aa7c-d52cd8f1c553)
