### ISSUE TITLE
API searchRandom does not apply filter options

### ISSUE THREAD

**Issue by jeena** [immich-app/immich#15010]
### The bug

I'm trying to find 5 random pictures of 2 people to show them on the TV. I wrote this script:

```python
headers = {
  'Accept': 'application/json',
  'x-api-key': os.getenv('IMMICH_API_KEY')
}
payload = json.dumps({
	'personIds': ['9b8c1758-f2ae-4505-92c7-15920052e2ad', '43866db9-3967-4943-8d23-312a711bce58'],
	'page': 0,
	'size': 5,
	'type': 'IMAGE',
	'withPeople': True
})
response = requests.request("POST", server_url + '/search/random', headers=headers, data=payload)
items = response.json()
print(len(items))
print(items[0]['people'])

# Returns
# 250 instead of 5
# [] and the picture is without any person in it
```

From my understanding it should only return 5 because I set size to 5.

Similarly it should only return photos with at least one of the personIds, or if there are none then it should not return any pictures. But it returns a random picture which often has no people in it.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.123.0 build.172

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${USER1_PATH1}
      - ${USER1_PATH2}
      - ${USER2_PATH1}
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: no

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: no

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: no

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: no
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION='/mnt/MyBook/jeena/immich/upload' 
# The location where your database files are stored
DB_DATA_LOCATION='/mnt/MyBook/jeena/immich/db' 

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.123.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=foo

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

# User paths
USER1_PATH1="/home/jeena/Pictures:/import/jeena/Pictures:ro"
USER1_PATH2="/mnt/MyBook/jeena/immich/synology/jeena:/import/jeena/Synology:ro"
USER2_PATH1="/mnt/MyBook/jeena/immich/synology/foo:/import/foo/Computer:ro"
```

### Reproduction steps

1. Write the script
2.Run the script
3.See the results of  the query being wrong
...
