### ISSUE TITLE
[ISSUE/BUG] upgrading pgvecto.rs to 0.4.0

### ISSUE THREAD

**Issue by dasunsrule32** [immich-app/immich#15044]
### The bug

Attempting to upgrade to `tensorchord/pgvecto-rs:pg16-v0.4.0` docker image for my postgres server. Docs say `0.4.0` say Immich sounds like it's not recognizing it correclty.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.123.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

Immich:
```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    volumes:
      - ${UPLOAD_PATH}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    env_file:
      - .env
    ports:
      - 2283:2283
    healthcheck:
      disable: false
  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    container_name: immich-ml
    restart: unless-stopped
    volumes:
      - ${CACHE_PATH}:/cache
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    env_file:
      - .env
    healthcheck:
      disable: false
```
Postgres:
```YAML
services:
  postgres:
    image: tensorchord/pgvecto-rs:pg16-v0.4.0
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
```
Redis:
```YAML
services:
  redis:
    image: docker.io/library/redis:latest
    container_name: redis
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}:/data
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 1G
    env_file:
      - .env
```
```


### Your .env content

Immich:
```Shell
# App
UPLOAD_PATH=/mnt/media/immich
CACHE_PATH=/mnt/data/immich
TZ=US/Eastern
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

# Database
DB_USERNAME=immich
DB_PASSWORD=PASSWORD
DB_DATABASE_NAME=immich
DB_HOSTNAME=postgres.lan.domain.co
DB_PORT=5432
DB_VECTOR_EXTENSION=pgvecto.rs

# Caching
REDIS_HOSTNAME=redis.lan.domain.co
REDIS_PORT=6379
```
Postgres:
```Shell
# App
DB_PATH=/mnt/db/postgres
PGDATA=/var/lib/postgresql/data/pgdata

# Database
POSTGRES_DB=postgres
POSTGRES_USER=admin
POSTGRES_PASSWORD=PASSWORD
```
Redis:
```SHELL
# App
DATA_PATH=/mnt/db/redis
```
### Reproduction steps

1. Upgrade to tensorchord/pgvecto-rs:pg16-v0.4.0
2. Upgrade vectors plugin: https://docs.vectorchord.ai/admin/upgrading.html
3. Restart postgres and redis
4. Get error

### Relevant log output

```shell
immich microservices worker error: Error: The pgvecto.rs extension version is 0.4.0, but Immich only supports >=0.2 <0.4.
```
