### ISSUE TITLE
rotated live-photo

### ISSUE THREAD

**Issue by dnlweijers** [immich-app/immich#15068]
### The bug

If the original live-photo was filmed horizontal, but needs to be vertical (i believe), the preview is vertical, correctly, but the live photo not (if you play the live photo) 

https://github.com/user-attachments/assets/87b293c2-710e-4799-95ae-4cf8df2c5749

https://github.com/user-attachments/assets/33106993-3192-4171-bc6a-718c7774a44b

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

1.123.0 build.172

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-server:
    image: "ghcr.io/immich-app/immich-server:v1.123.0"
    container_name: "immich-server"
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-postgres:
        condition: service_healthy
    environment:
      TZ: "Europe/Amsterdam"
      DB_HOSTNAME: "immich-postgres"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "<password>"
      REDIS_HOSTNAME: "immich-redis"
      IMMICH_ENV: "production"
      IMMICH_PROCESS_INVALID_IMAGES: "true"
    volumes:
      - "/mnt/2tb_hdd/immich/data:/usr/src/app/upload"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default
      - immich-intern
    devices:
      - "/dev/dri:/dev/dri"
    restart: always

  immich-redis:
    image: "redis:latest"
    container_name: "immich-redis"
    volumes:
      - "/data/immich/redis:/data"
    networks:
      - immich-intern
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  immich-postgres:
    image: "docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0"
    container_name: "immich-postgres"
    environment:
      POSTGRES_PASSWORD: "<password>"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "immich"
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - "/data/immich/postgresql:/var/lib/postgresql/data"
    networks:
      - immich-intern
    command: >
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    healthcheck:
      test: >
        pg_isready --dbname=immich --username=postgres || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s
    restart: always

  immich-power-tools:
    container_name: immich-power-tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8095:3000"
    environment:
      IMMICH_API_KEY: "<api key>"
      IMMICH_URL: "http://immich-server:2283"
      EXTERNAL_IMMICH_URL: "https://foto.dnlweijers.nl"
      DB_HOSTNAME: "192.168.2.175"
      DB_USERNAME: postgres
      DB_PASSWORD: "<password>"
      DB_HOST: immich-postgres
      DB_PORT: 5432
      DB_DATABASE_NAME: immich
      GOOGLE_MAPS_API_KEY: "<api key>"
      GEMINI_API_KEY: "<api key>"
    networks:
      - default
      - immich-intern
    restart: always

networks:
  immich-intern:
    driver: bridge
  default:
    name: "apps_network"
    external: true
```

### Your .env content

```Shell
In compose
```

### Reproduction steps

1. Upload the (live)photos (video files)
2. Open 1
3. Click play button
...
