### ISSUE TITLE
Over 100K photos generated when uploading from folder that contains only videos

### ISSUE THREAD

**Issue by BitcoinCode** [immich-app/immich#15060]
### The bug

I have a folder that contains only videos, when pointing immich to it, then looking at jobs I see 106k photos created and 4333 videos, the video count is correct but the photo count is wrong , I don't have any photos on the folder all are videos .mp4.

I made sure that the external library is not on the same location as the upload location 

Please help me on this issue 

### The OS that Immich Server is running on

Proxmox LXC 

### Version of Immich Server

"Ubuntu 24.04 LTS" Proxmox container

### Version of Immich Mobile App

1.123.0 build.172

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ptv/extlib:/extlib:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/immich_upload
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxx
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Just navigate to immich and looks at the jobs 
2.
3.
...

### Relevant log output

```shell
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face 69d4e137-9d3f-465e-a1b4-d6d14add8b8a
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face c6448442-d949-41d8-88a5-56a846fe476d
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face ee820e82-9862-4e0c-95f8-89fdd76b5946
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face 0527d780-b440-4f5e-941c-0c67146f6c3d
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face 9a9d9178-4f42-4fd1-a69e-cdccaa3d3077
[Nest] 6  - 01/03/2025, 3:03:01 AM     LOG [Microservices:PersonService] Creating new person for face 81745b16-b0f2-472d-b1a8-42c74d2a66a8
[Nest] 6  - 01/03/2025, 3:03:06 AM     LOG [Microservices:PersonService] Creating new person for face fd5b6dc0-d425-4a41-9c5b-d042e5b2d14f
[Nest] 6  - 01/03/2025, 3:03:07 AM     LOG [Microservices:PersonService] Creating new person for face 8d79edd1-217a-43ad-9e3b-35fd9b65aabe
[Nest] 6  - 01/03/2025, 3:03:07 AM     LOG [Microservices:PersonService] Creating new person for face 87a72792-9361-491b-b02d-a05ddc8e135a
[Nest] 6  - 01/03/2025, 3:03:08 AM     LOG [Microservices:PersonService] Creating new person for face 2e41e50d-fdd9-454b-acf7-13c7f6ede244
[Nest] 6  - 01/03/2025, 3:03:08 AM     LOG [Microservices:PersonService] Creating new person for face 1d9a253f-7fe7-454f-ba92-2c356fe4bd3b
[Nest] 6  - 01/03/2025, 3:03:08 AM     LOG [Microservices:PersonService] Creating new person for face c893c848-6e18-4ec4-aaaf-f0280c64c892
[Nest] 6  - 01/03/2025, 3:03:15 AM     LOG [Microservices:PersonService] Creating new person for face 3b817dc1-3066-4136-88f1-87b77cdfcadb
[Nest] 6  - 01/03/2025, 3:03:21 AM     LOG [Microservices:PersonService] Creating new person for face cf33fa42-58c0-4ada-a5a1-1af10f8185f5
[Nest] 6  - 01/03/2025, 3:03:21 AM     LOG [Microservices:PersonService] Creating new person for face 3df34092-e5d9-4e70-a5b1-1dda8d1c40b0
[Nest] 6  - 01/03/2025, 3:03:34 AM     LOG [Microservices:PersonService] Creating new person for face 08e0618e-f72d-45f6-941f-40344e2f16c3
[Nest] 6  - 01/03/2025, 3:03:43 AM     LOG [Microservices:PersonService] Creating new person for face 78ba0cee-ae96-4eb7-97be-f9af9d920bac
[Nest] 6  - 01/03/2025, 3:03:44 AM     LOG [Microservices:PersonService] Creating new person for face 962ea986-25e3-4ac6-8f88-72b16e78bdb4
[Nest] 6  - 01/03/2025, 3:04:01 AM     LOG [Microservices:PersonService] Creating new person for face fba349a5-3bcf-42bb-b2e5-d1fc5e5ad062
[Nest] 6  - 01/03/2025, 3:04:05 AM     LOG [Microservices:PersonService] Creating new person for face 331fd3e1-3297-4fdf-a21c-eeb9e976484f
[Nest] 6  - 01/03/2025, 3:04:06 AM     LOG [Microservices:PersonService] Creating new person for face 08a55cc1-06ab-448e-b110-33b4be47ef5d
[Nest] 6  - 01/03/2025, 3:04:08 AM     LOG [Microservices:PersonService] Creating new person for face 66e2cf0a-2a66-4d68-9292-fb9d50bcb194
[Nest] 6  - 01/03/2025, 3:04:09 AM     LOG [Microservices:PersonService] Creating new person for face 6d379dd1-81ad-4203-877a-23716ec0473d
[Nest] 6  - 01/03/2025, 3:04:09 AM     LOG [Microservices:PersonService] Creating new person for face d455aa35-28c9-4653-9435-e45e2863d27a
[Nest] 6  - 01/03/2025, 3:04:15 AM     LOG [Microservices:PersonService] Creating new person for face 0ba4e551-2791-426a-8ad1-f0cd8b99e64d
[Nest] 6  - 01/03/2025, 3:04:15 AM     LOG [Microservices:PersonService] Creating new person for face 0ecbbfde-5643-4107-b60e-88af31252b39
[Nest] 6  - 01/03/2025, 3:04:24 AM     LOG [Microservices:PersonService] Creating new person for face e33a4df5-6de1-415c-a38d-4d7f4aeb9c56
[Nest] 6  - 01/03/2025, 3:04:26 AM     LOG [Microservices:PersonService] Creating new person for face 12c2851d-5fa7-4b9b-a304-569b7baed647
[Nest] 6  - 01/03/2025, 3:04:32 AM     LOG [Microservices:PersonService] Creating new person for face 81e0086f-ad0d-40cd-a73f-53edc0d72d77
[Nest] 6  - 01/03/2025, 3:04:34 AM     LOG [Microservices:PersonService] Creating new person for face 673ee755-c1a4-4cf5-985a-06efd592868c
[Nest] 6  - 01/03/2025, 3:04:57 AM     LOG [Microservices:PersonService] Creating new person for face 916a852b-d9bc-4dbf-aa58-51ac3c13c73e
[Nest] 16  - 01/03/2025, 9:44:44 AM     LOG [Api:EventRepository] Websocket Disconnect: 9bfLS6rFccrZvT8qAAAd
```

### Additional information

N/A
