### ISSUE TITLE
Navigation between pictures does not work (next, previous, exit)

### ISSUE THREAD

**Issue by MCerk** [immich-app/immich#15113]
### The bug

The navigation does not work when full screen. Here is the recorded Jam:
https://jam.dev/c/efe3bdd8-3640-4643-9aec-ae585e76557e

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

# name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${EXTERNAL_LIBRARY_LOCATION}:/usr/src/app/data/existing:ro
      - ${EXTERNAL_LIBRARY_LOCATION_NIKA}:/usr/src/app/data/existing-nika:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich

  #immich-microservices:
  #  container_name: immich_microservices
  #  image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
  #  volumes:
  #    - ${UPLOAD_LOCATION}:/usr/src/app/upload
      #- ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded_video
  #    - ${EXTERNAL_LIBRARY_LOCATION}:/usr/src/app/data/existing:ro
  #    - ${EXTERNAL_LIBRARY_LOCATION_NIKA}:/usr/src/app/data/existing-nika:ro
  #    - /etc/localtime:/etc/localtime:ro
  #  env_file:
  #    - .env
  #  depends_on:
  #    - redis
  #    - database
  #  restart: always
  #  networks:
  #    - immich

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      # - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich


volumes:
  pgdata:
  model-cache:

networks:
  immich:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
EXTERNAL_LIBRARY_LOCATION=/mnt/d/pictures
EXTERNAL_LIBRARY_LOCATION_NIKA=/mnt/d/pictures-nika

ENCODED_VIDEO_LOCATION=/mnt/d/encoded_video

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=################


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open immich in web browser (Chrome, latest)
2. Click on one image in album
3. Click forward, backward icon (it does not navigate images) - please check the JAM, I've sent to see console log.
