### ISSUE TITLE
On iOs albums dont follow Photo Grid setting for Group By

### ISSUE THREAD

**Issue by wtangofoxtrot** [immich-app/immich#15152]
### The bug

When opening albums on iOs the photos are not grouped by month/date but are shown as a single continuous wall of photos. 

In iOs app I have settings -> Photo Grid -> set to `Group by` Month + day or just plain Month however the app shows a wall of photos when looking at an album with no grouping.

In the app the Photos tab will show the grid using Month+day, (this looks correct):
<img height="500" src="https://github.com/user-attachments/assets/be8ca957-dbf2-4691-ae83-519796380ccc" />

On the web UI an album will show the photo grid using month+day  (this also looks correct):
<img width="1130" alt="Screenshot 2025-01-07 at 2 50 37 PM" src="https://github.com/user-attachments/assets/5ce5ae9c-f7ac-40bd-a27b-a4051e1f4777" />

The albums view on the iOs mobile app however will be a continuous wall (this doesnt look correct):
<img height="500" src="https://github.com/user-attachments/assets/b6e5b92a-8e34-47c1-a63e-250d862de319" />

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.124.0

### Version of Immich Mobile App

1.123.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-network
      - immich-reverse-proxy-network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-network

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - immich-network

volumes:
  data:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich"
  db:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich_db"
  model-cache:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich_model_cache"

networks:
  immich-network:
    driver: bridge
  immich-reverse-proxy-network:
    external:
      name: proxy-network # this connects to the swag proxy network
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
# The location where your database files are stored
#DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=omalley

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=blarg

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=honk
DB_DATABASE_NAME=bleep
```

### Reproduction steps

1. open album on iOs app with photos taken across multiple dates (example recents)
2. will be presented with a wall of photos with no indication of what dates they belong to
