### ISSUE TITLE
Not found or no asset.delete access (immich server error)

### ISSUE THREAD

**Issue by Ronnie-J** [immich-app/immich#15165]
### The bug

> Not found or no asset.delete access (immich server error)

When I try and delete an image I get this error.

<img width="295" alt="billede" src="https://github.com/user-attachments/assets/e43a853b-5262-4da5-9127-7fa098525b7c" />

<img width="1437" alt="billede" src="https://github.com/user-attachments/assets/31f3d1f0-e24b-46c9-87f3-c02de63d86df" />

I was cleaning up in my images searching by "screenshot". Marked a lot of images and they deleted fine and continued. Then suddenly I got that error. Started narrowing it down and it came down to one image I am not able to delete. 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.124.0

### Version of Immich Mobile App

1.123.0 build.186

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@immich-docker:~/immich-app# cat docker-compose.yml 
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    user: 3001:3001

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich-nas
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Copenhagen

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. I did a search on "screenshot"
2. I marked images
3. Pressed the three dots and chose delete

### Relevant log output

```
[Nest] 17  - 01/08/2025, 1:16:36 PM   DEBUG [Api:LoggingInterceptor~q9otq3vh] DELETE /api/assets 204 0.69ms ::ffff:192.168.0.176
[Nest] 17  - 01/08/2025, 1:16:36 PM VERBOSE [Api:LoggingInterceptor~q9otq3vh] {"ids":["e6339ee3-5cef-4fe3-9172-c7b8a205290e"],"force":false}
[Nest] 17  - 01/08/2025, 1:16:36 PM   DEBUG [Api:GlobalExceptionFilter~q9otq3vh] HttpException(400): {"message":"Not found or no asset.delete access","error":"Bad Request","statusCode":400}
```

### Additional information

I searched for the ID on the mount point and it could look like the main images have been removed but I am left with the thumbnail for some reason? Might be why I get the error?

```
immich@immich-docker:/mnt/immich-nas$ find /mnt/immich-nas/ -name e6339ee3-5cef-4fe3-9172-c7b8a205290e*
/mnt/immich-nas/thumbs/9d767c80-cacc-431b-a948-020527c634bc/e6/33/e6339ee3-5cef-4fe3-9172-c7b8a205290e-thumbnail.webp
/mnt/immich-nas/thumbs/9d767c80-cacc-431b-a948-020527c634bc/e6/33/e6339ee3-5cef-4fe3-9172-c7b8a205290e-preview.jpeg
```

_No response_
