### ISSUE TITLE
[BUG] App re-uploads everything after reinstall

### ISSUE THREAD

**Issue by dorianim** [immich-app/immich#1517]
**Describe the bug**
I just had to reinstall the immich app, because I switched from the f-droid version to the apk from the GitHub release.
When I logged in again, all photos and videos are being re-uploaded. The App thinks, they are all new.
The number of `Total` assets also changes after a while and becomes incorrect. The `Backup`-counter is correct, though.

**To Reproduce**
1. Uninstall app
2. Install app
3. Login with the same account
4. Select some photos which are already uploaded

**Expected behavior**
Immich should detect that the photos already exist and shouldn't try to upload them.

**Screenshots**
![image](https://user-images.githubusercontent.com/30153207/216270109-36ca04f4-abbf-4dd1-b5e4-82eb6354eafc.png)

**System**
- Phone OS [Android]: `12`
- Server Version: `1.44.0`
- Mobile App Version: `1.44.0`

**Additional context**
- I use oauth2 for authentication
`docker-compose.yml`
```yml
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: itsblue.dev/dorian/immich-machine-learning-no-avx
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: "Host(`photos.example.com`)"
      traefik.http.routers.immich.entrypoints: webs
```
`.env`
```yml
DB_HOSTNAME=immich_postgres
DB_USERNAME=<user>
DB_PASSWORD=<password>
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=/mnt/data/immich

JWT_SECRET=<secret>

MAPBOX_KEY
ENABLE_MAPBOX=true
MAPBOX_KEY=<key>

VITE_LOGIN_PAGE_MESSAGE=
```
