### ISSUE TITLE
Video memories no longer play

### ISSUE THREAD

**Issue by bmayfi3ld** [immich-app/immich#15182]
### The bug

This popped up within the last three months (apologies I do not know the exact version change that did it).

When viewing memories. Any memory that is a video does not play. Both on mobile and web. 

Interesting thing on mobile, if I go to view the day and then watch the video and then go back to the memory, the video will also then play in the memory viewer.  Then I can kill the app, relaunch, and the video won't play anymore. 

### The OS that Immich Server is running on

default container OS, on Ubuntu 22

### Version of Immich Server

v1.124.1

### Version of Immich Mobile App

1.123.0 build 172

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: immich-server
          env:
            - name: DB_DATABASE_NAME
              value: immich
            - name: IMMICH_PORT
              value: "3001"
            - name: DB_HOSTNAME
              value: postgresql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-credentials
                  key: DB_PASSWORD
            - name: DB_USERNAME
              value: myuser
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://localhost:3003
            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: "6379"
          # https://github.com/immich-app/immich/releases
          # don't forget ML down below
          image: ghcr.io/immich-app/immich-server:v1.124.1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 3001
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /images
              name: images
            - mountPath: /usr/src/app/upload
              name: library
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 750Mi
        - name: immich-machine-learning
          env:
            - name: TRANSFORMERS_CACHE
              value: /cache
            - name: MACHINE_LEARNING_PORT
              value: "3003"
            - name: MACHINE_LEARNING_HOST
              value: "0.0.0.0"
            - name: IMMICH_PORT
              value: "3003"
          image: ghcr.io/immich-app/immich-machine-learning:v1.124.1
          ports:
            - containerPort: 3003
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /cache
              name: cache
          resources:
            limits:
              cpu: 4000m
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 200Mi
      volumes:
        - name: library
          nfs:
            # redacted
        - emptyDir: {}
          name: cache
---
apiVersion: v1
kind: Service
metadata:
  name: immich
spec:
  ports:
    - name: http
      port: 3001
      protocol: TCP
      targetPort: http
  selector:
    app: immich-server
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: immich
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: immich-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 1000
```

### Your .env content

```Shell
embedded in the file above
```

### Reproduction steps

1. have a video that would show up in the memories
2. attempt to view the memory

### Additional information

I also tried re-encoding all the videos, didn't help.
