### ISSUE TITLE
Album : Wrong date range display ("fileCreatedAt" not updated/set correctly)

### ISSUE THREAD

**Issue by davidXire** [immich-app/immich#15189]
### The bug

Hello

I have several albums with a date range issue for the photos.
For example:

- I have an album whose timeline (scroll) shows photos from August 9th to August 16th, 2016.
- The album summary indicates "Jan 28, 2018 - Jan 11, 2023 • 333 items". This issue impacts the grouping of albums by year.
![image](https://github.com/user-attachments/assets/7d32c441-be36-4c6f-999b-db2c5f1adb27)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.124

### Version of Immich Mobile App

v1.124

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich-app

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/elrond/photo:/mnt/media/elrond:ro
    extends:
       file: hwaccel.yml
       service: hwaccel
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:%                                                                                                                                              
beelink immich-
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./data/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=********
DB_PASSWORD=********

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

#LOG_LEVEL=debug
```

### Reproduction steps

1.
2.
3.
...
