### ISSUE TITLE
Merge People not sorting by similarity when featured photo's original asset is deleted

### ISSUE THREAD

**Issue by cynicalsquare** [immich-app/immich#15319]
### The bug

When clicking on Merge People, the list of faces to merge is not sorted by similarity. It's only showing the default 'People' view from /people

When I click the Sort by Similarity button, I get this error in the firefox error console:
![image](https://github.com/user-attachments/assets/f3ac5a02-ff43-43ca-8767-ef5453538689)

The URL that it tries to access is:
http://192.168.1.122:2283/api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false

If I try to access that URL manually, I get this:
![image](https://github.com/user-attachments/assets/15325a89-8b7a-4c34-b5f9-4224a0108b3f)

I'm not sure if its an issue with the jobs/face recognition, I've already tried:
- Running missing on Generate Thumbnails
- Running missing on Extract Metadata
- Refresh on Library
- Discover on Sidecar Metadata
- Missing on Smart Search
- Missing on Duplicate Detection
- Missing on Face Detection
- Missing Facial Recognition

The only thing I haven't tried is reset on FACE DETECTION, which I really don't want to do since it will take forever.

EDIT: To add, this was working for a while and I was able to merge a few faces.
EDIT2: This seems to be working for SOME faces

### The OS that Immich Server is running on

Debian 12 - Bookworm

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/library/upload
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
EXTERNAL_PATH=/mnt/pictures
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_LOG_LEVEL=verbose
```

### Reproduction steps

1. Click Explore and select any Face
2. Click Menu, Merge People
...

### Relevant log output

```shell
immich_server            | [Nest] 17  - 01/13/2025, 4:59:05 PM   DEBUG [Api:LoggingInterceptor~zroxmk4k] GET /api/server/ping 200 0.97ms ::ffff:127.0.0.1
immich_server            | [Nest] 17  - 01/13/2025, 4:59:23 PM   DEBUG [Api:LoggingInterceptor~0h5xja0g] GET /api/people?withHidden=false 200 408.51ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:24 PM   DEBUG [Api:LoggingInterceptor~5tkvjp4c] GET /api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false 200 1.04ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:24 PM   DEBUG [Api:GlobalExceptionFilter~5tkvjp4c] HttpException(404): {"message":"Person not found","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 01/13/2025, 4:59:25 PM   DEBUG [Api:LoggingInterceptor~3v2vqkak] GET /api/people?withHidden=false 200 380.63ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:26 PM   DEBUG [Api:LoggingInterceptor~8z4mcl2w] GET /api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false 200 1.11ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:26 PM   DEBUG [Api:GlobalExceptionFilter~8z4mcl2w] HttpException(404): {"message":"Person not found","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:LoggingInterceptor~qzruktxz] GET /api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false 200 2.04ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:GlobalExceptionFilter~qzruktxz] HttpException(404): {"message":"Person not found","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:LoggingInterceptor~tpywcgk9] GET /api/people?withHidden=false 200 404.84ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:LoggingInterceptor~a5mac6bh] GET /api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false 200 4.81ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:GlobalExceptionFilter~a5mac6bh] HttpException(404): {"message":"Person not found","error":"Not Found","statusCode":404}
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:LoggingInterceptor~pkskgrlh] GET /api/people?withHidden=false 200 405.55ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:LoggingInterceptor~lgqz88qa] GET /api/people?closestPersonId=6763c84b-ef11-4e99-90d9-0b6f33d00018&withHidden=false 200 1.86ms ::ffff:192.168.1.45
immich_server            | [Nest] 17  - 01/13/2025, 4:59:27 PM   DEBUG [Api:GlobalExceptionFilter~lgqz88qa] HttpException(404): {"message":"Person not found","error":"Not Found","statusCode":404}
```
