### ISSUE TITLE
ERROR [Api:RangeError: Invalid string length

### ISSUE THREAD

**Issue by vipenm** [immich-app/immich#15332]
### The bug

`/api/timeline/bucket?isArchived=false&size=MONTH&timeBucket=2025-01-01T00%3A00%3A00.000Z&withPartners=true&withStacked=true` returns a 500 error when trying to load images. Using `docker logs -f immich_server` I get:
```bash
[Nest] 16  - 01/14/2025, 9:36:46 AM   ERROR [Api:RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/usr/src/app/node_modules/express/lib/response.js:1160:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:271:14)
    at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
    at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17~kareu8tc] Unknown error: RangeError: Invalid string length
[Nest] 16  - 01/14/2025, 9:36:46 AM     LOG [Api:EventRepository] Websocket Disconnect: EtSQlrv_zdE4XWzNAABA
[Nest] 16  - 01/14/2025, 9:36:46 AM     LOG [Api:EventRepository] Websocket Connect:    IDLxXP16_TM1pz2CAABC
[Nest] 16  - 01/14/2025, 9:37:35 AM   ERROR [Api:RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at stringify (/usr/src/app/node_modules/express/lib/response.js:1160:12)
    at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:271:14)
    at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
    at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
    at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17~3m245v6l] Unknown error: RangeError: Invalid string length
```
It manages to load memories and I'm able to view them but struggles when trying to load the rest of my images:

![image](https://github.com/user-attachments/assets/272a171a-9b1c-41ba-8b9e-1179839cd56f)

I'm accessing Imimch via nginx:

```
# Upgrade WebSocket if requested, otherwise use keepalive
map $http_upgrade $connection_upgrade_keepalive {
    default upgrade;
    ''      '';
}

server {
    listen 443 ssl http2;
    server_name _;

    # SSL configuration
    ssl_certificate     ssl.crt;
    ssl_certificate_key ssl.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # allow large file uploads
    client_max_body_size 50000M;

    # Set headers
    proxy_set_header Host              $http_host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Proxy to Docker container
    location / {
        proxy_pass http://192.168.50.10:2283;
        proxy_http_version 1.1;

        # Enable WebSocket support if needed
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
	proxy_redirect     off;

        # Timeout settings
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        send_timeout       600s;

        # Buffer settings
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;

        # Disable buffering for real-time applications
        proxy_request_buffering off;
    }

    location = /.well-known/immich {
        proxy_pass http://192.168.50.10:2283;
    }
}
```

Nginx returns no errors using `tail`.

I'm also getting the following console error:
```
[handleError]: Failed to load assets pt: Error: 500
    at Object.ht [as ok] (https://<URL>/_app/immutable/chunks/fetch-client.DqMPutSq.js:1:7918)
    at async fo.loadBucket (https://<URL>/_app/immutable/chunks/shortcut.DcbiiuPu.js:9:49632) Error: Error: 500
    at Object.ht [as ok] (https://<URL>/_app/immutable/chunks/fetch-client.DqMPutSq.js:1:7918)
    at async fo.loadBucket (<URL>/_app/immutable/chunks/shortcut.DcbiiuPu.js:9:49632)
```

It might be worth noting that I have currently paused all jobs just so that I could test the app (so not all thumbnails, metadata etc have been generated).

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

Not using

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    deploy:
      resources:
        limits:
          cpus: "2.0"  # Limit to 2 CPU cores
          memory: 8g  # Limit to 8GB of RAM
        reservations:
          cpus: "2.0"  # Limit to 2 CPU cores
          memory: 2g  # Reserve 2GB of RAM
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/Photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=password
DB_DATA_LOCATION=./config

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=username
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Run the app
2. Wait for /api/timeline/buckets to timeout
