### ISSUE TITLE
Motion photos are not counted correctly

### ISSUE THREAD

**Issue by schang1146** [immich-app/immich#15379]
### The bug

Motion photos in Immich have some wonky behavior:
- They are not counted correctly in an album:
Album says "10 selected" when using CTRL+A to select all but says there's "18 items" in the album
![image](https://github.com/user-attachments/assets/c89786dd-aa4f-4b57-aa2d-e811c884a19a)
- Deleting the moving image from the album still shows 8 items in the album until the trash has been emptied
![image](https://github.com/user-attachments/assets/e87c1cd8-381f-47c7-ae5f-0db0e8e0ab1a)
![image](https://github.com/user-attachments/assets/f4235514-baeb-4ab1-a843-548c3d86eab4)
- Phone view shows all the images but the videos for the moving images are separate and have no thumbnail
![image](https://github.com/user-attachments/assets/adab2a98-da71-443d-b473-d177eed5099b)

### The OS that Immich Server is running on

Ubuntu 24.04 Server

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.2 build.175

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      traefik.enable: true
      # increase readingTimeouts for the entrypoint used here
      traefik.http.routers.immich.tls: true
      traefik.http.routers.immich.tls.certresolver: letsencrypt_resolver
      traefik.http.routers.immich.tls.domains: immich.domain.com
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.rule: Host(`immich.domain.com`)
      traefik.http.routers.immich.service: immich-svc@file
      traefik.http.services.immich-svc.loadbalancer.server.port: 2283

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/md0/docker/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/md0/docker/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxxxx
DB_DATABASE_NAME=xxxxx
```

### Reproduction steps

1. Upload 2 attached files to album
Expected: See 1 file and album says there's 1 file
Actual: See 1 file and album says there's 2 files

2. Try deleting the file in album
Expected: See 0 files and album says there's no files
Actual: See 0 files and album says there's 1 file
![MVIMG_20171117_105233](https://github.com/user-attachments/assets/83ebe606-2a5f-45a0-b27e-188848e1918f)

https://github.com/user-attachments/assets/9feae9f2-e1e7-4b10-9a40-f9dd02570454
