### ISSUE TITLE
Postgres causing "Too manty open files" error and crashing multiple unrelated containers

### ISSUE THREAD

**Issue by Handrail9** [immich-app/immich#15383]
### The bug

After being up for roughly 24 to 48 hours my Immich postgres container crashes with the error "Too many open files", and over the course of minutes other containers on the same system crash as well with the same error.

### The OS that Immich Server is running on

Fedora Server 41

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    security_opt:
      - no-new-privileges:true
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload:Z
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    environment:
      - DOCKER_HOST=tcp://dockersocket:2375
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    environment:
      - DOCKER_HOST=tcp://dockersocket:2375
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    security_opt:
      - no-new-privileges:true
    restart: always
    environment:
      - DOCKER_HOST=tcp://dockersocket:2375
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      DOCKER_HOST: tcp://dockersocket:2375
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:Z
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' ||
        exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}'
        --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT
        COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
        "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$$user", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
volumes:
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/immich-app/library
# The location where your database files are stored
DB_DATA_LOCATION=/opt/immich-app/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random passwaord
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REMOVED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Start Immich
2. Wait about 24-48 hours (No user interaction required)
3. Crash

### Relevant log output

```shell
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-10_070006.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-10_075947.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-11_000000.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-12_024142.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-12_030741.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-14_081905.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-14_082158.log’: Too many open files
find: ‘/var/lib/postgresql/data/log/postgresql-2025-01-15_000000.log’: Too many open files

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-01-15 07:07:10.371 UTC [1] LOG:  redirecting log output to logging collector process
2025-01-15 07:07:10.371 UTC [1] HINT:  Future log output will appear in directory "log".

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-01-15 07:48:38.064 UTC [1] LOG:  redirecting log output to logging collector process
2025-01-15 07:48:38.064 UTC [1] HINT:  Future log output will appear in directory "log".

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-01-15 07:55:14.351 UTC [1] LOG:  redirecting log output to logging collector process
2025-01-15 07:55:14.351 UTC [1] HINT:  Future log output will appear in directory "log".

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-01-15 23:33:18.802 UTC [1] LOG:  redirecting log output to logging collector process
2025-01-15 23:33:18.802 UTC [1] HINT:  Future log output will appear in directory "log".
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/segments/3dca3458-7310-4497-bda5-87e23616b9dd’: Too many open files
find: ‘/var/lib/postgresql/data/pg_vectors/indexes/1758594/startup/0’: Too many open files
```

### Additional information

This immich library contains around 60k photos (over 200G) for 5 users.
Immich is running under a QEMU KVM with other containers related to cloud storage.
VirtioFS is being utilized to pass through a path on the host directory to store the Immich files to allow A) portability of the VM, B) Easy access to the photos for backups
The soft and hard file limit for this system are both set to 50000000.
I suspect the issue to be with immich because it is the only container that accesses a large amount of files, and it's postgres container is the first container to crash when this happens.
