### ISSUE TITLE
New photos suddenly not detected

### ISSUE THREAD

**Issue by tof245** [immich-app/immich#15382]
### The bug

**note: changed phone and used data transferred mechanism**

As of a few days ago, immich stopped detecting new photos on my phone and updating the DB. I hadn't updated anything. I tried connecting directly to the IP but there's no change. The new photos show up in the thumbnail previews of the backed up folders that I have selected but not in the actual timeline. The error that shows up in the logs are as follows 
Message 
```
PlatformDispatcher - Catch all`
Details
`Bad state: Unable to fetch properties for path -1033394188.`
Stack Trace 
`#0      AssetPathEntity.obtainPathFromProperties (package:photo_manager/src/types/entity.dart:162)
<asynchronous suspension>
#1      AssetPathEntity.fromId (package:photo_manager/src/types/entity.dart:59)
<asynchronous suspension>
#2      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:44)
<asynchronous suspension>
#3      HashService.getHashedAssets (package:immich_mobile/services/hash.service.dart:38)
<asynchronous suspension>
#4      SyncService._syncDeviceAlbumFast (package:immich_mobile/services/sync.service.dart:656)
<asynchronous suspension>
#5      SyncService._syncAlbumInDbAndOnDevice (package:immich_mobile/services/sync.service.dart:563)
<asynchronous suspension>
#6      diffSortedLists (package:immich_mobile/utils/diff.dart:23)
<asynchronous suspension>
#7      SyncService._syncLocalAlbumAssetsToDb (package:immich_mobile/services/sync.service.dart:510)
<asynchronous suspension>
#8      AlbumService.refreshDeviceAlbums (package:immich_mobile/services/album.service.dart:132)
<asynchronous suspension>
#9      AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:56)
<asynchronous suspension>
#10     AppLifeCycleNotifier.handleAppResume (package:immich_mobile/providers/app_life_cycle.provider.dart:67)
<asynchronous suspension>
```

I updated my server to the latest with no change.
Any idea what could have suddenly caused this?

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

1.124.2

### Version of Immich Mobile App

1.124.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
      - /home/rtx970/Desktop/testfold:/home/rtx970/Desktop/testfold
      - /home/rtx970/immich-server/library/library:/home/rtx970/immich-server/library/library
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
THUMB_LOCATION=./library/thumbs

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Use Immich as normal
2. Notice new local photos aren't being uploaded
3. Update server, empty cache, connect directly to local IP - nothing helps
...
