### ISSUE TITLE
geoclue user appearing after starting docker compose.

### ISSUE THREAD

**Issue by user9091** [immich-app/immich#15399]
### The bug

geoclue user appearing after starting docker compose.
the postgres folder owner changes to geoclue when i try to docker compose up.

before starting docker:
-rw-r--r--. 1 root root 3919 docker-compose.yml
drwxr-xr-x. 1 root root   56  external_config
drwxr-xr-x. 1 root root    0  library
drwxr-xr-x. 1 root root  542  postgres

after docker compose up:
-rw-r--r--. 1 root    root 3919  docker-compose.yml
drwxr-xr-x. 1 root    root   56  external_config
drwxr-xr-x. 1 root    root    0  library
drwx------. 1 geoclue root  570  postgres

### The OS that Immich Server is running on

Fedora Linux 41 (Workstation Edition)

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

v1.234.0 build.187

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  ts-webserver2:
    image: tailscale/tailscale:latest
    hostname: immich
    environment:
      - TS_AUTHKEY=tskey-XXX?ephemeral=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/external.json
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
    volumes:
      - tailscale-data-webserver2:/var/lib/tailscale
      - ./external_config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the>
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
    #  - '2283:2283'
    network_mode: service:ts-webserver2
    depends_on:
      - redis
      - database
      - ts-webserver2
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where>
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in>
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  tailscale-data-webserver2:
    driver: local
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/hdd1/immich-data/
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_>
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.docker compose down
2.reboot fedora
3.ls -l to check the owner of all folders. postgres folder is owned by root.
3.docker compose up -d
4.postgres folder owner changes to geoclue

drwx------. 1 geoclue root  570  postgres

### Relevant log output

```shell
postgres container logs from docker 

docker logs immich_postgres
PostgreSQL Database directory appears to contain a database; Skipping initialization

 LOG:  redirecting log output to logging collector process
 HINT:  Future log output will appear in directory "log".
```
