### ISSUE TITLE
Unknown error: RangeError: Invalid string length

### ISSUE THREAD

**Issue by CannonFodderr** [immich-app/immich#15397]
### The bug

Server was working well until few days ago then I Started getting these logs.
Web UI does not how any images.
I am able to access the  server from the mobile app and view the thumbnails, but the web UI is very slow and times out.

### The OS that Immich Server is running on

Ubuntu server 

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

1.124.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: homelab
networks:
  net:
    driver: 'bridge'
services:
  immich-server:
    networks:
      net: {}
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${SHARED_PHOTOS_LOCATION}:/shared/bu/photos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../env/immich.env
    ports:
      - 2283:2283
    expose:
      - 2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    networks:
      net: {}
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - ../env/immich.env
    restart: always
    healthcheck:
      disable: false
  redis:
    networks:
      net: {}
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    networks:
      net: {}
    container_name: postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
volumes:
  model-cache:
```

### Your .env content

```Shell
# IMMICH
# The location where your uploaded files are stored
UPLOAD_LOCATION=~/storage/external/shared/photos/immich

# The location where your database files are stored
DB_DATA_LOCATION=../immich-data

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
DB_DATABASE_NAME=immich

# POSTGRES
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=reducted

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=reducted
SHARED_PHOTOS_LOCATION=~/storage/external/shared/backup/photos
```

### Reproduction steps

Not sure how to reproduce.

### Relevant log output

```shell
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17~yyvxgabr] Unknown error: RangeError: Invalid string length
immich_server            | [Nest] 17  - 01/16/2025, 9:02:25 PM     LOG [Api:EventRepository] Websocket Disconnect: yp63d9S0NWEC4fnzAAAa
immich_server            | [Nest] 17  - 01/16/2025, 9:02:30 PM     LOG [Api:EventRepository] Websocket Connect:    tEqvhd_YrdGMQkemAAAf
immich_redis             | 1:M 16 Jan 2025 21:06:59.072 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 16 Jan 2025 21:06:59.075 * Background saving started by pid 370
immich_redis             | 370:C 16 Jan 2025 21:06:59.100 * DB saved on disk
immich_redis             | 370:C 16 Jan 2025 21:06:59.101 * RDB: 0 MB of memory used by copy-on-write
immich_redis             | 1:M 16 Jan 2025 21:06:59.176 * Background saving terminated with success
immich_server            | [Nest] 17  - 01/16/2025, 9:09:04 PM   ERROR [Api:RangeError: Invalid string length
immich_server            |     at JSON.stringify (<anonymous>)
immich_server            |     at stringify (/usr/src/app/node_modules/express/lib/response.js:1160:12)
immich_server            |     at ServerResponse.json (/usr/src/app/node_modules/express/lib/response.js:271:14)
immich_server            |     at ExpressAdapter.reply (/usr/src/app/node_modules/@nestjs/platform-express/adapters/express-adapter.js:62:62)
immich_server            |     at RouterResponseController.apply (/usr/src/app/node_modules/@nestjs/core/router/router-response-controller.js:15:36)
immich_server            |     at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:176:48
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:47:13
immich_server            |     at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17~3tdr43m8] Unknown error: RangeError: Invalid string length
```

### Additional information

Aside from this bug immich is an amazing piece of software 🥇
