### ISSUE TITLE
Inconsistent timezone conversion between web and app

### ISSUE THREAD

**Issue by pingu8007** [immich-app/immich#15404]
### The bug

Timezone conversion is inconsistent between web app and mobile app, the time shown on mobile app is double converted.

JPG on mobile app - 20250116 0335 (8hrs quicker)
![Image](https://github.com/user-attachments/assets/aefe98ee-4593-4854-919e-9b202605c670)
RAW on mobile app - 20250116 0335 (8hrs quicker)
![Image](https://github.com/user-attachments/assets/1e9b3284-bed1-4d6c-9e69-732216a09054)
RAW on web app - 20250115 1935
![Image](https://github.com/user-attachments/assets/3aecd957-3b6e-41c8-b646-b15968914ee2)
JPG on web app - 20250115 1935
![Image](https://github.com/user-attachments/assets/81460906-bb72-4fcb-9c9f-1f5c65b40261)

### The OS that Immich Server is running on

Docker on Asustor ADM

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
networks:
  default:
    name: commons
    driver: bridged
    external: true

services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    restart: always
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /share/Docker/Immich/app:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment: &immich_env
      TZ: Asia/Taiwan
      DB_HOSTNAME: 127.0.0.1
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD: _TOP_SECRET_
      REDIS_HOSTNAME: 127.0.0.1
    healthcheck:
      disable: false
  redis:
    image: redis:alpine
    restart: always
    network_mode: service:immich
    healthcheck:
      test: redis-cli ping || exit 1
  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: always
    network_mode: service:immich
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: _TOP_SECRET_
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /share/Docker/Immich/db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

volumes:
  model-cache:
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Config timezone to something other than +0
2. Upload a photo shoot in the configured timezone (I did this via web app)
3. Check the timestamp on both web and mobile side

### Relevant log output

```shell

```
