### ISSUE TITLE
Older iPhone 13 Pro Max Videos Still Cause Crashes and Aspect Ratio Issues After PR #12104

### ISSUE THREAD

**Issue by mosalski** [immich-app/immich#15407]
### The bug

Issue [#11689](https://github.com/immich-app/immich/issues/11689) was marked resolved by [PR #12104](https://github.com/immich-app/immich/pull/12104) in version v1.122.0, but older videos (uploaded before December 2024) are still problematic:

-   Older iPhone 13 Pro Max videos (uploaded around November 2024 and earlier) show up on Android (Samsung Galaxy S22 Ultra) with an incorrect aspect ratio.
-   Even older iPhone 13 Pro Max videos (uploaded before November 2024) cause the Immich app to crash on Android when opened.
-   On an iPhone 13 Pro Max, these older iPhone videos also sometimes show an incorrect aspect ratio, but do not crash the app.
-   Videos recorded on the Samsung Galaxy S22 Ultra do not have this issue at all.
-   Videos uploaded in December 2024 and throughout 2025 work correctly without any problems.

It appears the fix included in PR #12104 doesn’t apply retroactively to older uploads. Is there a way to reprocess or fix these videos so they work correctly?

### The OS that Immich Server is running on

Linux Mint 22

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.0 build.173

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/vlad/Base/existing_pictures:/existing_pictures
      - /media/vlad/Base/photo:/media/vlad/Base/photo:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=im    
DB_PASSWORD=mich
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/vlad/Base/immich


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=some-random-text
# TYPESENSE_ENABLED=false

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

Use the Immich app on a Samsung Galaxy S22 Ultra (Android).
Go to an album or timeline containing older iPhone 13 Pro Max videos (uploaded before December 2024).
Attempt to open/play one of these videos.

    Observed behavior: The app either crashes immediately or the video displays with an incorrect aspect ratio.

Repeat on an iPhone 13 Pro Max.

    Observed behavior: The video may show an incorrect aspect ratio, but does not crash.

### Relevant log output

```shell
No errors on server side
```

### Additional information

![Image](https://github.com/user-attachments/assets/f35df3a5-e3c8-46a9-87b6-8fd77bb79b73)
