### ISSUE TITLE
IOS: Persistent "Uploading" in Immich App

### ISSUE THREAD

**Issue by mayrmartin** [immich-app/immich#15419]
### Description:
I recently imported all my photos from my iPhone to the Immich app. Although the backup has been successful the app indicates that one image in my library has not been uploaded and continues to attempt the upload. The image the app is trying to upload is neither on my phone nor on the server. On that specific date I can not find an image in my Photos app (also checked the recently deleted + "hidden" album). 

The home screen displays a spinner indicating that a backup is currently running; however, in the backup section, the upload progress bar remains stagnant and does not move.  In the backup section I see that there is one missing image which has not been backed up with no name (just 3 dots) and a date where I can not find a photo in my Photos app:

![Image](https://github.com/user-attachments/assets/f26a8de9-21ec-4498-9901-d2ddef92b74c)

Here is a screenshot of the app Logs where it seams, that the app thinks that everything has been backed up so maybe the issue I'm encountering is just an UI bug?
![Image](https://github.com/user-attachments/assets/0190c006-0881-4547-9b5a-c18231026b3d)

### Environment:
- **Mobile App + Server Version:** v1.124.2
- **iOS Version:** 18.1.1
- Portainer + Docker on Ubuntu 22.04

### The OS that Immich Server is running on

Portainer + Docker on Ubuntu 22.04

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.2

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich-model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  immich-model-cache:
  immich-db:
```

### Your .env content

```Shell
UPLOAD_LOCATION=######
DB_DATA_LOCATION==######
TZ=Europe/Vienna
IMMICH_VERSION=v1.124.2
DB_PASSWORD=######
DB_USERNAME=######
DB_DATABASE_NAME=######
```

### Reproduction steps

I don't really know i just imported the photos from iPhone to Immich via the app.

### Relevant log output

```shell

```
