### ISSUE TITLE
inotify watch limit reached

### ISSUE THREAD

**Issue by ratti** [immich-app/immich#15426]
### The bug

I have a large external image library. I randomly discovered the option in admin interface it's possible (experimental) to watch external libraries for changes. I activated that.

Some time later, I did some maintenance on my server not related to immich, and when I tried to restart apache, I got this error:

```
root@pizza:~# service apache2 restart
Failed to add a watch for /run/systemd/ask-password: inotify watch limit reached
```

I did some research, I installed tool to see who/what is taking away inotify watches, and I got this result:

```
root@pizza:~# inotify-info
------------------------------------------------------------------------------
INotify Limits:
  max_queued_events    16,384
  max_user_instances   128
  max_user_watches     45,296
------------------------------------------------------------------------------
       Pid Uid        App                      Watches  Instances
      2327 0          node                      45,190          1
         1 0          systemd                       79          5
       270 0          udevadm                       15          1
       543 100        dbus-daemon                    3          1
      2028 0          containerd-shim-runc-v2        2          1
      2029 0          containerd-shim-runc-v2        2          1
      2030 0          containerd-shim-runc-v2        2          1
      2036 0          containerd-shim-runc-v2        2          1
      2118 0          containerd-shim-runc-v2        2          1
      2702 1000       imap                           2          1
      2704 1000       imap                           2          1
       533 997        systemd-timesyncd              1          1
       559 0          systemd-logind                 1          1
       568 0          agetty                         1          1
      3359 0          systemd                        0          1
------------------------------------------------------------------------------
Total inotify Watches:   45304
Total inotify Instances: 19
------------------------------------------------------------------------------

```

I am not experienced with inotify, however, for me it looks like immich is "taking away" an “unusual amount“ of watches.

I then tried to find out how to increase the amount, doubled the number, just to find out it's still not enough.

At that point I remembered I had turned on that option in immich, and turned it off again.

I hope this doesn't sound like inappropiate critizising, what I want so say is: 
If a userspace tool is taking away so many system ressources, even root can't restart an important service anymore, there should be at least a bigger warning than “Experimental“. For me “Experimental“ means “Immich might crash, or delete files, or fill up the harddrive“, but not as “Your headless server might become unreachable“.

So I suggest to hide that option in a way you find it in the docs only, with a more detailled warning,
— or —
even better, there should be a limit. Don't know if node can do that.

### The OS that Immich Server is running on

Debian 12.9

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /e/Fotos/Ereignisse/public:/e/Fotos/Ereignisse/public:ro
      - /e/Fotos/Ereignisse_Lotta:/e/Fotos/Ereignisse_Lotta:ro
      - /e/Handy/Fotos:/e/Handy/Fotos:ro
      #- /mnt/photos2:/mnt/photos2:ro # you can delete this line if you only have one mount point, or you can add more lines if you have more than two
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false



  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:2283/api
      API_KEY: xxxxxxxxxxxxxxXXXXXXXXxxxxxxx
      ROOT_PATH: /e/Fotos/Ereignisse/public
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Berlin



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=XXXXXXX
DB_DATABASE_NAME=XXXXXXX
```

### Reproduction steps

1. Have > 1000 albums (wild guess), each one is in a folder named $year/$year_$month_$date__$title
2. Einstellungen —> Externe Bibliothek —> Bibliotheksüberwachung: Switch on (config, external libraries, watch)
3. all inotify watchers are consumed

### Relevant log output

```shell
-
```

### Additional information

-
