### ISSUE TITLE
Immich app isarworker crashing randomly in background due to MTE bug

### ISSUE THREAD

**Issue by Youngblood50** [immich-app/immich#15436]
### The bug

I'm using GrapheneOS on a Pixel 8 Pro with MTE enabled. Sometimes the app crashes in the background due to an MTE error. It happens very rarely though, the first time was 3 months ago and the second time a couple of days ago. The following log is the MTE crash:

```
type: crash
osVersion: google/husky/husky:15/AP4A.250105.002/2025011500:user/release-keys
uid: 10245 (u:r:untrusted_app:s0:c245,c256,c512,c768)
cmdline: app.alextran.immich
processUptime: 7s

signal: 11 (SIGSEGV), code 9 (SEGV_MTESERR), faultAddr c00d082c9327bd0
threadName: isarworker
MTE: enabled

backtrace:
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc 70278)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc a5ca8)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc 4ff60)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc 415ac)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc d09d0)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc cfad0)
    /data/app/~~NkuRWGhZWpOun2_Ut-qjgw==/app.alextran.immich-rHH6FoJ_AEhXklMvuoxMFA==/split_config.arm64_v8a.apk (pc cf70c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204, pc 7969c)
    /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68, pc 6a064)
```

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.124.2

### Version of Immich Mobile App

1.124.0 build 173

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - Immich.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - Immich.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: .
      POSTGRES_USER: immichh
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=.

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immichh
DB_DATABASE_NAME=immich
```

### Reproduction steps

Have MTE enabled for the app, then it randomly crashes in background (very rarely)

### Relevant log output

```shell

```
