### ISSUE TITLE
Canon R5 MKII CR3 images not rendering properly

### ISSUE THREAD

**Issue by aktk946** [immich-app/immich#15457]
### The bug

Hello and firstly thanks for creating this beautiful app.

My CR3 files from Canon R5 Mark II are not rendering properly in web and mobile both. 
1. All of them have this pink/purple haze on them
2. They also are slightly off the frame and there is this black border on bottm and top of the images.

The CR3 from R7 and R6 Mark II were rendered perfectly without any issues

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.124.2

### Version of Immich Mobile App

v1.124.0 build 187

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
networks:
  mynet:
    external: true
    name: mynet
  immich:
    name: immich
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: immich
      com.docker.network.name: immich
volumes:
  immich_postgres:
    external: true
  immich_library:
    external: true
  immich_model_cache:

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      IMMICH_PORT: 80
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/data/photos/:/media/data/photos
    env_file:
      - .env
    networks:
      mynet:
        ipv4_address: 10.10.10.123
      immich:
    restart: always
    links:
      - redis
      - database
      - immich-machine-learning

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - immich_model_cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich:

  redis:
    container_name: immich_redis
    #network_mode: service:immich-server
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich:

  database:
    container_name: immich_postgres
    #network_mode: service:immich-server
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures),
 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      immich:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/data/other/cnfmount/immich/_data/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.124.2

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<removed>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=immich_postgres
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. docker-compose up -d
2. open up the web UI and see one of the photos shot by Canon R5 Mkii
3. open up the IOS App  and see one of the photos shot by Canon R5 Mkii

Se attached files - screenshots from webUI and app and also raw CR3 file

![Image](https://github.com/user-attachments/assets/528efa8a-5cd7-49fd-82d0-15fe753b6180)
![Image](https://github.com/user-attachments/assets/bfbc184a-baef-42de-9700-4c2956370f9f)

Raw image uploaded here: https://1drv.ms/u/c/580f844239557dda/EdvuYwyAc2VLgWVniUquN4oB0y8tB2KSlxMmKL5M1ckQVw?e=Ccnb4Q

(funnily enough even OneDrive web view renders is exactly like immich)

### Relevant log output

```shell

```
