### ISSUE TITLE
1.125.1: Trying to search any text errors

### ISSUE THREAD

**Issue by camilosampedro** [immich-app/immich#15577]
### The bug

After updating to `1.125.1`, if I search for any text, the server logs an error and UI doesn't show any result.

It may be related to the new DB changes in this release.

I'm running the Docker images provided by https://github.com/imagegenius/docker-immich, but I wonder if it's an issue in official Docker images as well.

Thank you for all the hard work!

### The OS that Immich Server is running on

NixOS 24.11, running on Docker

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

v1.124.2

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    image: ghcr.io/imagegenius/immich:1.125.1
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - DB_HOSTNAME=immich_postgres14
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MACHINE_LEARNING_HOST=0.0.0.0
      - MACHINE_LEARNING_PORT=3003
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_WORKER_TIMEOUT=120
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /var/lib/docker/volumes/immich_config:/config
      - /media/personal_data/containers/immich/photos:/photos
    ports:
      - 2284:8080
    restart: unless-stopped

  # This container requires an external application to be run separately.
  # By default, ports for the databases are opened, be careful when deploying it
  # Redis:
  immich_redis:
    image: redis
    ports:
      - 6379:6379
    container_name: immich_redis
  # PostgreSQL 14:
  immich_postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5432:5432
    container_name: immich_postgres14
    environment:
      POSTGRES_DB: immich
    volumes:
      - /var/lib/docker/volumes/immich_pgdata:/var/lib/postgresql/data
```

### Your .env content

```Shell
In the docker-compose.yml
```

### Reproduction steps

1. Run 1.124.2
2. Update to 1.125.1
3. Open WebUI or Android app.
4. Go to search view
5. Type any search query, for example 'meme' or 'text'
6. UI shows error. Logs also show error.

### Relevant log output

```shell
Query failed : {
   durationMs: 3.780862999963574,
   error: PostgresError: pgvecto.rs: Bad literal.
   INFORMATION: hint = Bad character with ascii 0x2d.
       at ErrorResponse (/app/immich/server/node_modules/postgres/cjs/src/connection.js:788:26)
       at handle (/app/immich/server/node_modules/postgres/cjs/src/connection.js:474:6)
       at Socket.data (/app/immich/server/node_modules/postgres/cjs/src/connection.js:315:9)
       at Socket.emit (node:events:518:28)
       at addChunk (node:internal/streams/readable:561:12)
       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
       at Readable.push (node:internal/streams/readable:392:5)
       at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
       at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
     severity_local: 'ERROR',
     severity: 'ERROR',
     code: 'XX000',
     where: "unnamed portal parameter $4 = '...'",
     file: 'error.rs',
     line: '7'
   },
   sql: `select "assets".*, (select jsonb_agg(case when "person"."id" is not null then jsonb_insert(to_jsonb("asset_faces"), '{person}'::text[], to_jsonb("person")) else to_jsonb("asset_faces") end) as "faces" from "asset_faces" left join "person" on "person"."id" = "asset_faces"."personId" where "asset_faces"."assetId" = "assets"."id") as "faces" from "assets" inner join "smart_search" on "assets"."id" = "smart_search"."assetId" where "assets"."ownerId" = any($1::uuid[]) and "assets"."isFavorite" = $2 and "assets"."isArchived" = $3 and "assets"."deletedAt" is null order by smart_search.embedding <=> $4 limit $5 offset $6`,
   params: [
     '{362e4276-7b40-449f-986f-0715731b007b}',
     false,
     false,
     [
         -0.011650036,   -0.04304119,  -0.015934544,   -0.021627339,
          0.029922409,  -0.003308879, -0.0021047862,  -0.0041569346,
          0.005721999,   0.030487416,  -0.041531973,  -0.0072471243,
         0.0056789443,  -0.017849222,  0.0092843985,   -0.009674756,
       -0.00044469332,   0.008767618,   0.010377952,   -0.022272285,
         -0.030817283, -0.0037038454,  -0.023179658,    0.009994929,
          0.014155174,   0.011300233,    0.32783318,    -0.06867674,
        -0.0014683407,   0.021358568,  0.0046278643,   -0.016047057,
          0.046293955,  -0.011975319,   0.028682597,   -0.024467926,
         -0.041959148,  -0.006460622,    0.01621693,    0.021778995,
        -0.0052941754, -0.0024293521,  -0.031191621,   -0.028091403,
         -0.008525613, -0.0030913972, -0.0108902175,    0.010546324,
          0.032146197,   0.023754273, -0.0026042971,  -0.0039419676,
       -0.00013337744,   0.016754406,   -0.04183347,    0.008150557,
         0.0058608297,  -0.012353393,  0.0039917966,     0.02024135,
        -0.0059669837,   0.014201661,  -0.007829968,   -0.043456044,
          0.017810728,    0.03954511,  -0.026486164,  0.00044377346,
          0.010480688,   0.025167137,    0.02475301,  -0.0068036327,
          0.014338164, -0.0015087944,   0.058549937, -0.00053300406,
          0.011303152,  0.0011262348,  -0.024974605,     0.02245266,
          0.003601826,   0.020690551,  -0.036596302,   -0.018741198,
         -0.030310584,  -0.013223111,    0.01772232,  -0.0014298457,
          0.013712479,   0.011857711,  -0.017234225,  -0.0022907173,
        -0.0075893574, -0.0036748836,   0.016279804,    0.002796594,
         -0.026113722,  -0.011479759,   0.026660299,    -0.02036727,
       ... 924 more items
     ],
     1001,
     0
   ]
 }
 [Nest] 235  - 01/24/2025, 9:38:07 AM   ERROR [Api:PostgresError: pgvecto.rs: Bad literal.
```

### Additional information

After reverting to 1.124.2, all works again.
