### ISSUE TITLE
Map and People data empty for user with access to shared albums

### ISSUE THREAD

**Issue by wtangofoxtrot** [immich-app/immich#15572]
### The bug

I have setup my family on my Immich server and shared albums that contain location and face recognition data and am seeing a variety of behaviors that appear wrong.
1. Location data is viewable by the other users when they open an asset in a shared album. Their map however is empty so they cannot search using it like I as the share creator can.
2. Face recognition data is also not visible by the users I shared the albums with. The search tab shows no People tab for them and opening a shared image also shows no People section on their accounts but they do on the creator's account.

### The OS that Immich Server is running on

Ubuntu 

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  
  immich-server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      # - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - data:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-network
      - immich-reverse-proxy-network

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-network

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - immich-network

volumes:
  data:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich"
  db:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich_db"
  model-cache:
    driver_opts:
      type: nfs
      o: "addr=some-ip,rw"
      device: ":/immich_model_cache"

networks:
  immich-network:
    driver: bridge
  immich-reverse-proxy-network:
    external:
      name: proxy-network # this connects to the swag proxy network
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
# The location where your database files are stored
#DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=omalley

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=blarg

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=honk
DB_DATABASE_NAME=bleep
```

### Reproduction steps

1. share an album with another user on your server. The album should include photos with geolocation data as well as tagged people.
2. log into the other user's account
3. open maps and confirm the shared photos are not searchable there
4. Open people and confirm the people from the shared photos are not there. This can also be done by opening a photo from the shared album and confirm the lack of the people section under the photo's Info panel. 
...

### Relevant log output

```shell

```
