### ISSUE TITLE
Album display order doesn't work as expect

### ISSUE THREAD

**Issue by reply2future** [immich-app/immich#15586]
### The bug

It doesn't work to set the display order(`oldest first` or `newest first`) using the album in the web browser after I updated the server from v1.124.0 to v1.125.1. I am sure it works in v1.124.0 in web browser and mobile app.

### The OS that Immich Server is running on

Official Docker version

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

v1.124.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3'

x-common-log-conf: &common_log_conf
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: 3

x-immich-env: &immich_env
  - DB_PASSWORD=${DB_PASSWORD}
  - DB_HOSTNAME=${DB_HOSTNAME}
  - DB_USERNAME=${DB_USERNAME}
  - DB_DATABASE_NAME=${DB_DATABASE_NAME}
  - REDIS_HOSTNAME=${REDIS_HOSTNAME}

services:
  immich_server:
    container_name: immich_server
    hostname: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # command: [ "start.sh", "immich" ]
    volumes:
      - ${EXTERNAL_DATA_PATH}/immich/upload:/usr/src/app/upload
    networks:
      - immich
    environment: *immich_env
    ports:
      - 2283:2283
    depends_on:
      - immich_redis
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    <<: *common_log_conf

  immich_machine_learning:
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${EXTERNAL_DATA_PATH}/immich/model-cache:/cache
    networks:
      - immich
    environment: *immich_env
    restart: unless-stopped
    <<: *common_log_conf

  immich_redis:
    container_name: immich_redis
    hostname: immich_redis
    image: redis:alpine
    networks:
      - immich
    restart: unless-stopped
    <<: *common_log_conf

networks:
  immich:
```

### Your .env content

```Shell
IMMICH_VERSION=v1.125.1
EXTERNAL_DATA_PATH=/mnt/external-drive/data
DB_PASSWORD=<...>
DB_HOSTNAME=<...>
DB_USERNAME=immich
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. open a album in the web browser
2. set the `display order` to `Oldest first`

### Relevant log output

```shell

```

### Additional information

now the mobile app v1.124.0 and v1.123.0 works as expected
