### ISSUE TITLE
Album display order "Oldest first" no longer works with v1.125.1

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [immich-app/immich#15589]
### The bug

By default, album options have a **Display order** of **Newest first**, but you can change this to **Oldest first** so that photos appear in the order they were taken.

This was working fine with v1.124.2, but has stopped working with v1.125.1. The albums now shows photos in **Newest first** order, even if you set the order to **Oldest first**.

The problem occurs with the web interface. It shows the correct order with the Android app.

### The OS that Immich Server is running on

Ubuntu 24.10

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# Docker Compose [Recommended] | Immich
# https://immich.app/docs/install/docker-compose

name: immich

services:
  # Helper to provision your docker volumes with appropriate permissions chown and chmod
  # https://github.com/hasnat/docker-volumes-provisioner

  # We want to run immich-server as user so that when photos get added to the library
  # folder using the the storage template, they are owned by user and not root.
  # But when the named volume is first created by docker, it is owned by root, so
  # immich-server is unable to access it. The volumes-provisioner fixes this.

  volumes-provisioner:
    container_name: immich-volumes-provisioner
    image: hasnat/volumes-provisioner
    environment:
      PROVISION_DIRECTORIES: "${UID}:${GID}:755: /server /library /scans"
    volumes:
      - server:/server
      - $DATA_DIR/library:/library
      - $DATA_DIR/scans:/scans
    network_mode: none

  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - server:/usr/src/app/upload
      - $DATA_DIR/library:/usr/src/app/upload/library
      - $DATA_DIR/scans:/external/scans
      - /etc/localtime:/etc/localtime:ro
    user: "${UID}:${GID}"
    env_file:
      - .env
    ports:
      - 2283:2283
    networks:
      - default
      - traefik
    restart: always
    healthcheck:
      disable: false

    depends_on:
      volumes-provisioner:
        condition: service_completed_successfully
      redis:
        condition: service_started
      database:
        condition: service_started

    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: Host(`subdomain.domain.com`)
      traefik.http.routers.immich.entrypoints: https,https-external
      traefik.http.routers.immich.tls.certresolver: letsencrypt
      traefik.http.services.immich.loadbalancer.server.port: 2283

      kuma.immich.docker.name: Immich

      wud.watch: true
      wud.tag.include: ^v\d+\.\d+\.\d+$ # https://github.com/immich-app/immich/tags

  immich-machine-learning:
    container_name: immich-machine-learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - learning:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich-redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    volumes:
      - redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: [
        "postgres",
        "-c", "shared_preload_libraries=vectors.so",
        "-c", 'search_path="$$user", public, vectors',
        "-c", "logging_collector=on",
        "-c", "max_wal_size=2GB",
        "-c", "shared_buffers=512MB",
        "-c", "wal_compression=on"
      ]
    restart: always

networks:
  traefik:
    external: true

volumes:
  server:
  learning:
  redis:
  postgres:
```

### Your .env content

```Shell
# Environment Variables | Immich
# https://immich.app/docs/install/environment-variables/

IMMICH_VERSION=v1.125.1

# System Integrity | Immich
# https://immich.app/docs/administration/system-integrity/

# We do not backup the Immich server's named volume, since the following folders will
# get recreated automatically: upload, thumbs, encoded-video, backup. The only two folders
# we need to backup are library and profile, which we have as bind mounts.

# When we restore, the postgres database gets restored, so Immich thinks this is not
# a first-time run and it expects its folders to exist and contain .immich files.
# So Immich fails to start. The following environment variable removes .immich file checks.

IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true

UID=1000
GID=1000

TZ=Europe/London

DATA_DIR=~/Immich

DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD=B4n4n4
```

### Reproduction steps

1. Change the album display order to **Oldest first**.
2. The display order does not change.

### Relevant log output

```shell

```
