### ISSUE TITLE
Error when changing location for multiple images at once

### ISSUE THREAD

**Issue by meminens** [immich-app/immich#15609]
### The bug

Receiving an error message when changing the location of multiple photos. But the location information appears to have been entered correctly. Following error is shown in the upper right corner of the browser window.

![Image](https://github.com/user-attachments/assets/d24ba3e8-1484-4280-9353-d77c847de260)

### The OS that Immich Server is running on

Debian 6.1.124-1

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

v1.124.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/meminens/Pictures:/usr/src/app/external
      - /home/meminens/Photography/Videos:/usr/src/app/external2
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

# Immich Power Tools
  immich_power_tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=<redacted>immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=<redacted>immich/postgres

# Immich Power Tools
IMMICH_URL="<redacted> # Immich URL
IMMICH_API_KEY="<redacted>" # Immich API Key
DB_HOST="database"
DB_PORT="5432"
```

### Reproduction steps

1. Search photos with unkown location in a desktop browser. Chrome in my case.
2. Select multiple photos.
3. Select change location from the three-dot menu.
4. Enter LAT and LONG values.
5. Click OK.

### Relevant log output

```shell
Query failed : {
  durationMs: 0.23959300015121698,
  error: Error: UNDEFINED_VALUE: Undefined values are not allowed
      at handleValue (/usr/src/app/node_modules/postgres/cjs/src/types.js:83:20)
      at /usr/src/app/node_modules/postgres/cjs/src/connection.js:225:38
      at Array.forEach (<anonymous>)
      at build (/usr/src/app/node_modules/postgres/cjs/src/connection.js:225:25)
      at Object.execute (/usr/src/app/node_modules/postgres/cjs/src/connection.js:167:7)
      at Query.handler (/usr/src/app/node_modules/postgres/cjs/src/index.js:229:13)
      at Query.handle (/usr/src/app/node_modules/postgres/cjs/src/query.js:140:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
    code: 'UNDEFINED_VALUE'
  },
  sql: `with "assets" as (update "assets" set "isVisible" = $1 where "id" = $2::uuid returning *) select "assets".*, to_json("exif") as "exifInfo", (select jsonb_agg(case when "person"."id" is not null then jsonb_insert(to_jsonb("asset_faces"), '{person}'::text[], to_jsonb("person")) else to_jsonb("asset_faces") end) as "faces" from "asset_faces" left join "person" on "person"."id" = "asset_faces"."personId" where "asset_faces"."assetId" = "assets"."id") as "faces" from "assets" left join "exif" on "assets"."id" = "exif"."assetId"`,
  params: [ false, undefined ]
}
[Nest] 7  - 01/24/2025, 4:16:46 PM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/link-live-photos): Error: UNDEFINED_VALUE: Undefined values are not allowed
[Nest] 7  - 01/24/2025, 4:16:46 PM   ERROR [Microservices:JobService] Error: UNDEFINED_VALUE: Undefined values are not allowed
    at handleValue (/usr/src/app/node_modules/postgres/cjs/src/types.js:83:20)
    at /usr/src/app/node_modules/postgres/cjs/src/connection.js:225:38
    at Array.forEach (<anonymous>)
    at build (/usr/src/app/node_modules/postgres/cjs/src/connection.js:225:25)
    at Object.execute (/usr/src/app/node_modules/postgres/cjs/src/connection.js:167:7)
    at Query.handler (/usr/src/app/node_modules/postgres/cjs/src/index.js:229:13)
    at Query.handle (/usr/src/app/node_modules/postgres/cjs/src/query.js:140:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[Nest] 7  - 01/24/2025, 4:16:46 PM   ERROR [Microservices:JobService] Object:
{
  "id": "d50da37f-fcbd-4da3-a84a-d052b7cad667",
  "source": "sidecar-write"
}
```
