### ISSUE TITLE
Image location does not match in mobile app when removed with web browser.

### ISSUE THREAD

**Issue by Phyxsius7** [immich-app/immich#15614]
### The bug

not sure what to make of this, so any advice would me much appreciated.
the only issues I can find is that when a image is deleted using web browser it is clearly moved to the trash but when using mobile app the image is still visible in my timeline and can be opened/viewed, the image is not in trash. Refreshing timeline or trash does not change this.

My issues look similar to 
https://github.com/immich-app/immich/issues/15382

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

1.125.1

### Version of Immich Mobile App

1.124.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Update the volume path to point to E:/ImmichMedia
      - E:/ImmichMedia:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Amsterdam  # Set the timezone to Amsterdam
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./l****
# The location where your database files are stored
DB_DATA_LOCATION=./p****

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=P****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=U****
DB_DATABASE_NAME=D****
```

### Reproduction steps

1. at image to Immich
2. remove image from immich using web browser
3. check if images location with Immich mobile app (Android) and matches that with web browser (timeline and Trash)

### Relevant log output

```shell
`Message
PlatformDispatcher - Catch all

Details
Bad state: Unable to fetch properties for path -1739773001.

From
ImmichErrorLogger

Stack trace
#0      AssetPathEntity.obtainPathFromProperties (package:photo_manager/src/types/entity.dart:162)
<asynchronous suspension>
#1      AssetPathEntity.fromId (package:photo_manager/src/types/entity.dart:59)
<asynchronous suspension>
#2      AlbumMediaRepository.getAssets (package:immich_mobile/repositories/album_media.repository.dart:44)
<asynchronous suspension>
#3      HashService.getHashedAssets (package:immich_mobile/services/hash.service.dart:38)
<asynchronous suspension>
#4      SyncService._syncDeviceAlbumFast (package:immich_mobile/services/sync.service.dart:656)
<asynchronous suspension>
#5      SyncService._syncAlbumInDbAndOnDevice (package:immich_mobile/services/sync.service.dart:563)
<asynchronous suspension>
#6      diffSortedLists (package:immich_mobile/utils/diff.dart:23)
<asynchronous suspension>
#7      SyncService._syncLocalAlbumAssetsToDb (package:immich_mobile/services/sync.service.dart:510)
<asynchronous suspension>
#8      AlbumService.refreshDeviceAlbums (package:immich_mobile/services/album.service.dart:132)
<asynchronous suspension>
#9      AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:56)
<asynchronous suspension>
`
```

### Additional information

The error message shows up twice a the same time at the following moments:
11:41 AM
11:27 AM
07:38 AM
00:14 AM
