### ISSUE TITLE
Random image search Internal Error (v1.125.1)

### ISSUE THREAD

**Issue by zackslash** [immich-app/immich#15624]
### The bug

Hi, I am experiencing an issue with the search API, this issue has first appeared in v1.125.1 of immich-server

Making a request to the search API to retrive a random image now fails:

Example of a curl request i'm making
```

curl --request POST \
  --url https://my-immich-instance/api/search/random \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: <MY_API_KEY>' \
  --data '{
	"size":1,
	"type": "IMAGE",
	"isFavorite": true
}'
```

Results in the response
```
{
	"message": "Failed to search random",
	"error": "Internal Server Error",
	"statusCode": 500,
	"correlationId": "qccpavwp"
}
```

The immich server logs are attached,

Previous to version v1.125.1 this endpoint sucessfully returned a random image.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.125.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

### Your .env content

```Shell
UPLOAD_LOCATION=<REM>
DB_DATA_LOCATION=<REM>
IMMICH_VERSION=v1.125.1
DB_PASSWORD=<REM>
DB_USERNAME=<REM>
DB_DATABASE_NAME=<REM>
TZ=<REM>
```

### Reproduction steps

1. Create an API key
2. Make cURL request to the search API
```
curl --request POST \
  --url https://my-immich-instance/api/search/random \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'x-api-key: <MY_API_KEY>' \
  --data '{
	"size":1,
	"type": "IMAGE",
	"isFavorite": true
}'
```

### Relevant log output

```shell
[Nest] 16  - 01/24/2025, 5:52:21 PM   ERROR [Api:ErrorInterceptor~qccpavwp] Unknown error: TypeError: items.map is not a function

TypeError: items.map is not a function

    at SearchService.searchRandom (/usr/src/app/dist/services/search.service.js:52:22)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```
