### ISSUE TITLE
Migration "AddTimeBucketIndices1734574016301" failed, error: functions in index expression must be marked IMMUTABLE

### ISSUE THREAD

**Issue by zhelyan** [immich-app/immich#15649]
### The bug

booting up v1.125.2 - server crashes with:

```
immich_server            | Migration "AddTimeBucketIndices1734574016301" failed, error: functions in index expression must be marked IMMUTABLE
immich_server            | QueryFailedError: functions in index expression must be marked IMMUTABLE
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:6:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:96:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
immich_server            |   query: `CREATE INDEX idx_local_date_time_month ON assets ((date_trunc('MONTH', "localDateTime" at time zone 'UTC') at time zone 'UTC'))`,
immich_server            |   parameters: undefined,
immich_server            |   driverError: error: functions in index expression must be marked IMMUTABLE

```

### The OS that Immich Server is running on

bookworm x64

### Version of Immich Server

v1.125.2

### Version of Immich Mobile App

v1.125.2 2178

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/nas/photos/immich
BACKUP_LOCATION=/mnt/nas/photos/immich/backups
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xyz
DB_PASSWORD=zyx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. download the latest docker compose file
2. run `docker-compose up -d`
2.
3.
...

### Relevant log output

```shell
immich_postgres          | 2025-01-25 12:21:19.323 UTC [1] HINT:  Future log output will appear in directory "log".
immich_redis             | 1:C 25 Jan 2025 12:22:11.849 # Redis version=6.2.17, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis             | 1:C 25 Jan 2025 12:22:11.849 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis             | 1:M 25 Jan 2025 12:22:11.851 * monotonic clock: POSIX clock_gettime
immich_redis             | 1:M 25 Jan 2025 12:22:11.854 * Running mode=standalone, port=6379.
immich_redis             | 1:M 25 Jan 2025 12:22:11.854 # Server initialized
immich_redis             | 1:M 25 Jan 2025 12:22:11.854 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis             | 1:M 25 Jan 2025 12:22:11.855 * Ready to accept connections
immich_server            | Initializing Immich v1.125.2
immich_server            | Detected CPU Cores: 8
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 01/25/2025, 12:22:28 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | Migration "AddTimeBucketIndices1734574016301" failed, error: functions in index expression must be marked IMMUTABLE
immich_server            | QueryFailedError: functions in index expression must be marked IMMUTABLE
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:6:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:96:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
immich_server            |   query: `CREATE INDEX idx_local_date_time_month ON assets ((date_trunc('MONTH', "localDateTime" at time zone 'UTC') at time zone 'UTC'))`,
immich_server            |   parameters: undefined,
immich_server            |   driverError: error: functions in index expression must be marked IMMUTABLE
immich_server            |       at /usr/src/app/node_modules/pg/lib/client.js:535:17
immich_server            |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_server            |       at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:6:9)
immich_server            |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
immich_server            |       at async /usr/src/app/dist/services/database.service.js:96:17
immich_server            |       at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
immich_server            |     length: 120,
immich_server            |     severity: 'ERROR',
immich_server            |     code: '42P17',
immich_server            |     detail: undefined,
immich_server            |     hint: undefined,
immich_server            |     position: undefined,
immich_server            |     internalPosition: undefined,
immich_server            |     internalQuery: undefined,
immich_server            |     where: undefined,
immich_server            |     schema: undefined,
immich_server            |     table: undefined,
immich_server            |     column: undefined,
immich_server            |     dataType: undefined,
immich_server            |     constraint: undefined,
immich_server            |     file: 'indexcmds.c',
immich_server            |     line: '1917',
immich_server            |     routine: 'ComputeIndexAttrs'
immich_server            |   },
immich_server            |   length: 120,
immich_server            |   severity: 'ERROR',
immich_server            |   code: '42P17',
immich_server            |   detail: undefined,
immich_server            |   hint: undefined,
immich_server            |   position: undefined,
immich_server            |   internalPosition: undefined,
immich_server            |   internalQuery: undefined,
immich_server            |   where: undefined,
immich_server            |   schema: undefined,
immich_server            |   table: undefined,
immich_server            |   column: undefined,
immich_server            |   dataType: undefined,
immich_server            |   constraint: undefined,
immich_server            |   file: 'indexcmds.c',
immich_server            |   line: '1917',
immich_server            |   routine: 'ComputeIndexAttrs'
immich_server            | }
immich_server            | microservices worker error: QueryFailedError: functions in index expression must be marked IMMUTABLE
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server exited with code 0
immich_server            | Detected CPU Cores: 8
```
