### ISSUE TITLE
Setting GPS coordinate to picture fails (Postres error)

### ISSUE THREAD

**Issue by amadeous** [immich-app/immich#15641]
### The bug

When trying to setting the GPS coordinates for an image, from the web interface, the following error is displayed:

![Image](https://github.com/user-attachments/assets/2c6b24f6-a884-4e14-a247-5f76b6079013)

I tried to trigger the bug from the mobile app but did not manage to raise the issue. The assets are correctly modified.

Could be linked to #15609.

### The OS that Immich Server is running on

Debian 12 (on RPi5)

### Version of Immich Server

1.125.2

### Version of Immich Mobile App

1.124.2 build.175

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
      #- 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "traefik.enable=true"
      # LOTS of traefik labels
    networks:
      - immich_network
      - traefik_proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich_network

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich_network

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_network

volumes:
  model-cache:

networks:
  immich_network:
    driver: bridge
  traefik_proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=****REDACTED****

# Location of postgres data
DB_DATA_LOCATION=./pgdata

IMMICH_TELEMETRY_INCLUDE=all

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=***REDACTED***
DB_USERNAME=***REDACTED***
DB_DATABASE_NAME=***REDACTED***

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. On web interface, select at least one image and select "Edit location"
2. Provide coordinates (e.g. 43,639721168971 / 11,5318430445394)
3. Observe error notification & following trace in the logs

### Relevant log output

```shell
immich_server            | Query failed : {
immich_server            |   durationMs: 0.8830970000126399,
immich_server            |   error: PostgresError: syntax error at or near "where"
immich_server            |       at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
immich_server            |       at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
immich_server            |       at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |       at Socket.emit (node:events:524:28)
immich_server            |       at addChunk (node:internal/streams/readable:561:12)
immich_server            |       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |       at Readable.push (node:internal/streams/readable:392:5)
immich_server            |       at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            |       at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
immich_server            |     severity_local: 'ERROR',
immich_server            |     severity: 'ERROR',
immich_server            |     code: '42601',
immich_server            |     position: '22',
immich_server            |     file: 'scan.l',
immich_server            |     line: '1176',
immich_server            |     routine: 'scanner_yyerror'
immich_server            |   },
immich_server            |   sql: 'update "assets" set  where "id" = any($1::uuid[])',
immich_server            |   params: [
immich_server            |     '{356179a3-3b5a-4e5d-9fc8-4867d30d3609,c0044ba2-7f4f-4690-92dc-09d17551162a}'
immich_server            |   ]
immich_server            | }
immich_server            | [Nest] 17  - 01/25/2025, 9:37:43 AM   ERROR [Api:ErrorInterceptor~l6ralalo] Unknown error: PostgresError: syntax error at or near "where"
immich_server            | PostgresError: syntax error at or near "where"
immich_server            |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
immich_server            |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
immich_server            |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```
