### ISSUE TITLE
Failed to update assets

### ISSUE THREAD

**Issue by Phyxsius7** [immich-app/immich#15664]
### The bug

Bulk change of location (geo-coordinates) produces error message
Failed to update assets (Immich server error)

![Image](https://github.com/user-attachments/assets/8cb65060-30b0-4c60-930b-798e56abc188)

This started after updating to version 1.125.2

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

1.125.2

### Version of Immich Mobile App

1.125.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Update the volume path to point to E:/ImmichMedia
      - E:/ImmichMedia:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Amsterdam  # Set the timezone to Amsterdam
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./l****
# The location where your database files are stored
DB_DATA_LOCATION=./p****

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=P****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=U****
DB_DATABASE_NAME=D****
```

### Reproduction steps

1. select more then one image
2. choose "Change location"
3. enter coordinates and confirm
4. observe toast error message on the top right 

### Relevant log output

```shell
>see also server log at the end<
------- web inspection (F12) > console --------------
DzcTizWE.js:1 
        
        
       PUT https://10.79.80.127/api/assets 500 (Internal Server Error)
window.fetch @ DzcTizWE.js:1
en @ DzcTizWE.js:1
fetch @ DzcTizWE.js:1
o @ BYB68Yzy.js:1
n @ BYB68Yzy.js:1
an @ BYB68Yzy.js:1
w @ LJ-OC26D.js:1
N @ BV3QDg7K.js:2
E @ DiQDYzDK.js:1
A @ CSQmm1Qz.js:1
CeBM9qXI.js:1 [handleError]: Unable to update location yt: Error: 500
    at Object.mt [as ok] (https://10.79.80.127/_app/immutable/chunks/BYB68Yzy.js:1:8008)
    at async Object.w [as onConfirm] (https://10.79.80.127/_app/immutable/chunks/LJ-OC26D.js:1:1452) Error: Error: 500
    at Object.mt [as ok] (https://10.79.80.127/_app/immutable/chunks/BYB68Yzy.js:1:8008)
    at async Object.w [as onConfirm] (https://10.79.80.127/_app/immutable/chunks/LJ-OC26D.js:1:1452)
E @ CeBM9qXI.js:1
w @ LJ-OC26D.js:1
await in w
N @ BV3QDg7K.js:2
E @ DiQDYzDK.js:1
A @ CSQmm1Qz.js:1
DzcTizWE.js:1 
        
        
       PUT https://10.79.80.127/api/assets 500 (Internal Server Error)
window.fetch @ DzcTizWE.js:1
en @ DzcTizWE.js:1
fetch @ DzcTizWE.js:1
o @ BYB68Yzy.js:1
n @ BYB68Yzy.js:1
an @ BYB68Yzy.js:1
w @ LJ-OC26D.js:1
N @ BV3QDg7K.js:2
E @ DiQDYzDK.js:1
A @ CSQmm1Qz.js:1
CeBM9qXI.js:1 [handleError]: Unable to update location yt: Error: 500
    at Object.mt [as ok] (https://10.79.80.127/_app/immutable/chunks/BYB68Yzy.js:1:8008)
    at async Object.w [as onConfirm] (https://10.79.80.127/_app/immutable/chunks/LJ-OC26D.js:1:1452) Error: Error: 500
    at Object.mt [as ok] (https://10.79.80.127/_app/immutable/chunks/BYB68Yzy.js:1:8008)
    at async Object.w [as onConfirm] (https://10.79.80.127/_app/immutable/chunks/LJ-OC26D.js:1:1452)
E @ CeBM9qXI.js:1
w @ LJ-OC26D.js:1
await in w
N @ BV3QDg7K.js:2
E @ DiQDYzDK.js:1
A @ CSQmm1Qz.js:1

--------- Immich Server log -----------
Query failed : {
  durationMs: 1.4385030000048573,
  error: PostgresError: syntax error at or near "where"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '42601',
    position: '22',
    file: 'scan.l',
    line: '1176',
    routine: 'scanner_yyerror'
  },
  sql: 'update "assets" set  where "id" = any($1::uuid[])',
  params: [
    '{e1e31da1-3759-4c24-b8ea-aa8bde983bcf,45a256af-4491-4609-9d32-5407a7bf3930,b0c62dba-096d-4565-8eed-df62bf2e308e,04e21db8-352c-4f54-aa11-284284cb9fe0,b3f0d696-d30a-4009-a9d6-a2b583eda752,7a854958-4d97-4344-b064-8e9ba7e96272,6575329e-f93d-4c5b-aa4e-38f93b5185c9,e3c281bc-48aa-46e3-828d-e63cab53402f}'
  ]
}
[Nest] 19  - 01/25/2025, 5:28:51 PM   ERROR [Api:ErrorInterceptor~83jmle8k] Unknown error: PostgresError: syntax error at or near "where"
PostgresError: syntax error at or near "where"
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
```
