### ISSUE TITLE
Failed to get all albums (500)

### ISSUE THREAD

**Issue by francoisWeber** [immich-app/immich#15684]
### The bug

Hi, 

I suddenly experimented an error when I try to show my albums on my Immich account. 

The following error message appears:
```
Failed to get all albums - 500
yt@https://myhost.com/_app/immutable/chunks/BYB68Yzy.js:1:8084
mt@https://myhost.com/_app/immutable/chunks/BYB68Yzy.js:1:8008
```

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.125.3

### Version of Immich Mobile App

v1.125.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /var/nextcloud/data/francois/files/Pictures:/data/francois:rw
      - /var/nextcloud/data/louise/files/PHOTOS/Tel:/data/louise/tel:rw
     # - /var/nextcloud/data/louise/files/Photos\ Importées\ Du\ Téléphone:/data/louise
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1) Just log into my immich account
2) clic on "Albums"

### Relevant log output

```shell
My `immich_server` docker logs contain 29,702 errors `ENOSPC` like this one:

[Nest] 8  - 01/26/2025, 3:31:14 PM   ERROR [Microservices:LibraryService] Library watcher for library 423fe688-42a7-409b-a432-9ce5326edb88 encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/data/louise/tel/2025/01/25-01-24 18-43-48 0924.jpg'
```

### Additional information

Let me mention that immediately before experiencing this issue, I had another one related to albums:
- I was the owner of a shared album with another user B. User B putted some photos in this album and the sharing was working fine during weeks.
- user B suddenly ceased to see this album in her own albums
- this album was still visible by myself and accessible via a previously created sharing link
To tackle this issue, I deleted user B (let me mention user B is my wife 😅) and re-created it. Former "user B" and new "user B" have the same external drive connected to Immich (like the path `/data/louise/tel/` in the error log above). 

Might be related to https://github.com/immich-app/immich/discussions/14859 but the error logs are different.
