### ISSUE TITLE
Can't display albums list if there is empty album anymore (1.125.3): TypeError: Cannot read properties of undefined (reading 'startDate')

### ISSUE THREAD

**Issue by dionorgua** [immich-app/immich#15686]
### The bug

Not sure what I did. I was cleaning up photos. 
Photos from phone are automatically uploaded to "Camera" album. And my goal is to keep it empty by moving everything to proper place.

So I've moved some photos to other albums and deleted them. Most likely "Camera" albums is empty. And Immich web is now unable to display "Albums" page at all:

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.125.3

### Version of Immich Mobile App

1.125.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - 8001:3000
    env_file:
      - .env
    environment:
      IMMICH_URL: http://immich_server:2283 # Your immich instace ip address and port
      EXTERNAL_IMMICH_URL: https://immich.emerald-frog.ts.net # External address of immich

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Warsaw

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=fielu5ailuax3diesahv7eemooHei1haecaa7ohne9maiy3HahlaWai8eK8dah3d

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

DB_HOST=immich_postgres
DB_PORT=5432
```

### Reproduction steps

Most likely
1. Upload something from phone to Camera album
2. Add these photos to other album
3. Delete everything from camera album

### Relevant log output

```shell
immich_server  | [Nest] 17  - 01/26/2025, 4:51:29 PM   ERROR [Api:ErrorInterceptor~xps3c9pu] Unknown error: TypeError: Cannot read properties of undefined (reading 'startDate')
immich_server  | TypeError: Cannot read properties of undefined (reading 'startDate')
immich_server  |     at /usr/src/app/dist/services/album.service.js:53:52
immich_server  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server  |     at async Promise.all (index 0)
immich_server  | [Nest] 17  - 01/26/2025, 4:51:30 PM     LOG [Api:EventRepository] Websocket Disconnect: i438hH4u_hUYLaLZAAAB
immich_server  | [Nest] 17  - 01/26/2025, 4:51:31 PM     LOG [Api:EventRepository] Websocket Connect:    KQ_2-YrghWprHKh8AAAD
```
