### ISSUE TITLE
Select albums loading spinner loads indefinitely when no photos/videos are detected on device

### ISSUE THREAD

**Issue by catalin-l** [immich-app/immich#15703]
### The bug

Just did a fresh install of Graphene OS on my Pixel 8 Pro and during this I had to wipe it. After I installed the Immich app, I went to select the device albums to backup and noticed the spinner continued to spin no matter how long I waited. After force closing the app a few times without any change, I realized it was due to having no photos/videos on device.

I took a picture and went back to the app and it succesfully detected it.

This is a minor thing, but can be confusing to the user. Maybe some kind of error/info message could help.

### The OS that Immich Server is running on

TrueNAS-24.10.0.2

### Version of Immich Server

v1.125.3

### Version of Immich Mobile App

v1.125.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      - traefik
      - immich
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.immich.loadbalancer.server.port=2283
      # internal
      - traefik.http.routers.immich-local.rule=Host(`photos.local.domain.dev`)
      - traefik.http.routers.immich-local.entrypoints=https
      - traefik.http.routers.immich-local.tls=true
      # external
      - traefik.http.routers.immich-external.rule=Host(`photos.domain.dev`)
      - traefik.http.routers.immich-external.entrypoints=https-external
      - traefik.http.routers.immich-external.tls=true
    user: 3000:3000
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    networks:
      - immich
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    networks:
      - immich
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      - immich
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
volumes:
  model-cache: null
networks:
  immich:
    name: immich
  traefik:
    external: true
```

### Your .env content

```Shell
# Timezone
TZ=America/Toronto
# Location for the DB dump
BACKUP_LOCATION=/mnt/backups/immich
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/photos/immich
# The location where your DB files are stored
DB_DATA_LOCATION=/mnt/docker/data/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=_super_secure_pw

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Setup Immich server
2. Install Android app
3. Make sure you have no photos/videos on the mobile device
4. Access `Backup -> Backup Albums`
5. Watch the spinner go

### Relevant log output

```shell

```

### Additional information

I've been a happy user for more than half a year, thanks for everything you guys do!
