### ISSUE TITLE
Failedtosearchsmart (lmmich Server Error)

### ISSUE THREAD

**Issue by weiyideai520** [immich-app/immich#15714]
### The bug

Smart search not working

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.125.2

### Version of Immich Mobile App

v1.125.2

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${MODEL_CACHE_LOCATION}:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: dockerpull.org/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: dockerpull.org/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/Docker/immich/library
DB_DATA_LOCATION=/share/Docker/immich/postgres
TZ=Asia/Shanghai
HF_ENDPOINT=https://hf-mirror.com
IMMICH_VERSION=release
DB_PASSWORD=postgres
MACHINE_LEARNING_WORKER_TIMEOUT=1800
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
MODEL_CACHE_LOCATION=/share/Docker/immich/model-cache
```

### Reproduction steps

1. load: http://172.25.166.159:2283/photos
2. Login
3. Search : Dog

### Relevant log output

```shell
[Nest] 19  - 01/27/2025, 12:58:33 PM     LOG [Api:EventRepository] Websocket Connect:    s8CjzfGjjvxk8M9IAAAT

Query failed : {

  durationMs: 5.066462993621826,

  error: PostgresError: pgvecto.rs: Bad literal.

  INFORMATION: hint = Bad character with ascii 0x30.

      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)

      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)

      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)

      at Socket.emit (node:events:524:28)

      at addChunk (node:internal/streams/readable:561:12)

      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)

      at Readable.push (node:internal/streams/readable:392:5)

      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)

      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {

    severity_local: 'ERROR',

    severity: 'ERROR',

    code: 'XX000',

    where: "unnamed portal parameter $4 = '...'",

    file: 'error.rs',

    line: '7'

  },

  sql: 'select "assets".*, to_json("exif") as "exifInfo" from "assets" inner join "exif" on "assets"."id" = "exif"."assetId" inner join "smart_search" on "assets"."id" = "smart_search"."assetId" where "assets"."ownerId" = any($1::uuid[]) and "assets"."isVisible" = $2 and "assets"."isArchived" = $3 and "assets"."deletedAt" is null order by smart_search.embedding <=> $4 limit $5 offset $6',

  params: [

    '{761f0b09-db81-4679-b1fe-822302552731}',



,

    false,

    [

        0.032220796,  -0.007053845,  -0.0031618306,    0.016186545,

        0.017385073,  -0.054259013,   -0.011719328,     0.03159065,

       -0.019484933,  0.0061441315,     0.03879578,   -0.033455327,

        0.047082733,   0.025688564,    0.034769826,     0.03090894,

      -0.0013050088,   0.033440255,    0.029940302,    -0.07387418,

       -0.017582264,   0.009251902,  -0.0038594208,    -0.06062349,

        -0.03607378,   0.014354036,     0.05246047,   -0.047206268,

        0.017839985,    0.03811142,   -0.012637572,    0.026553614,

       -0.011845227,  -0.029143756,    0.016236193, -0.00092134374,

        -0.01939384,  -0.051995926,   -0.018391816,     0.13875194,

        0.010952712,  -0.016627004,   -0.011058661,    0.007176612,

       -0.006630199,  -0.027293673, -0.00038161624,  -0.0076599848,

        0.006648556,   0.025380354,     0.09828033,   -0.024134519,

        0.016294923, -0.0054568728,  -0.0073106806,    0.039004557,

        0.019939868,  -0.023415128,  -0.0011610063,    0.023989521,

       -0.001438305,   -0.02502716,    0.005366509,   -0.006863739,

         0.02157283,  -0.015972154,   -0.039008796,    0.012195207,

       0.0049374723, -0.0019668294,   -0.032430686,     0.02080147,

         0.01454077, -0.0035782068,    0.025098288,    -0.03465637,

        0.021631353,   0.046904564,     0.00874507,   0.0029808395,

         0.03445747,    0.03344881,     0.00937221,    -0.01825825,

       -0.011811473,   0.023871254,   -0.043953262,     -0.0162658,

      -0.0041205413,   0.005056571,    0.034768976,    0.007564244,

       -0.039138075,  -0.005130478,  -0.0022242416,   -0.027897144,

        0.012669752,    0.01979079,     -0.0495513,    0.008036255,

      ... 540 more items

    ],

    101,

    0

  ]

}

[Nest] 19  - 01/27/2025, 12:58:41 PM   ERROR [Api:PostgresError: pgvecto.rs: Bad literal.

INFORMATION: hint = Bad character with ascii 0x30.

    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)

    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)

    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)

    at Socket.emit (node:events:524:28)

    at addChunk (node:internal/streams/readable:561:12)

    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)

    at Readable.push (node:internal/streams/readable:392:5)

    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)

    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)~un5pvz8c] Unknown error: PostgresError: pgvecto.rs: Bad literal.

INFORMATION: hint = Bad character with ascii 0x30.
```
