### ISSUE TITLE
Failed to get all albums (Immich Server Error) - Unknown error: TypeError: Cannot read properties of undefined (reading 'startDate')

### ISSUE THREAD

**Issue by HackerJL** [immich-app/immich#15720]
### The bug

Updated from 1.124.2 to 1.125.3 on Ubuntu VM on proxmox.
library is on external SMB NAS, as is one external library of about 6 photos only.

Update went well, no errors, but met with the error on refresh of screen.  Docker logs below, as well.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

1.125.3

### Version of Immich Mobile App

1.125.2

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/icloudpd/icloudpd:/mnt/media/icloudpd:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - 8001:3000
    env_file:
      - .env
    restart: always
    environment:
      DB_HOST: database
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/NASDrive/Immich/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=SUPERCOOLPASSWORD

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOST="192.168.1.195" # Postgres Host (IP address or hostname of the database)
DB_PORT="5432" # Postgres Port number (Default: 5432)
IMMICH_API_KEY=<REDACTED>
IMMICH_URL = "http://192.168.1.195:2283" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL = "https://my.awesome.domain" # External address of immich

# Optional
GOOGLE_MAPS_API_KEY= # Google Maps API Key
GEMINI_API_KEY= # Gemini API Key
```

### Reproduction steps

1. docker compose down
2.docker compose pull
3. docker compose up -d
...

### Relevant log output

```shell
[Nest] 7  - 01/27/2025, 12:34:14 PM     LOG [Microservices:StorageService] Successfully verified system mount folder checks
[Nest] 17  - 01/27/2025, 12:34:14 PM     LOG [Api:StorageService] Verifying system mount folder checks, current state: {"mountFiles":true,"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
[Nest] 17  - 01/27/2025, 12:34:14 PM     LOG [Api:StorageService] Successfully verified system mount folder checks
[Nest] 17  - 01/27/2025, 12:35:04 PM   ERROR [Api:ErrorInterceptor~wrt5wy1a] Unknown error: TypeError: Cannot read properties of undefined (reading 'startDate')
TypeError: Cannot read properties of undefined (reading 'startDate')
    at /usr/src/app/dist/services/album.service.js:53:52
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 4)
[Nest] 17  - 01/27/2025, 12:35:11 PM   ERROR [Api:ErrorInterceptor~r25arjt3] Unknown error: TypeError: Cannot read properties of undefined (reading 'startDate')
TypeError: Cannot read properties of undefined (reading 'startDate')
    at /usr/src/app/dist/services/album.service.js:53:52
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Promise.all (index 4)
```

### Additional information

![Image](https://github.com/user-attachments/assets/f450a387-7dd4-40f0-b10b-72a81e54b9f2)
