### ISSUE TITLE
Error code: Out of memory when loading /photos page

### ISSUE THREAD

**Issue by Menghini** [immich-app/immich#15749]
### The bug

When going to my Immich /photos page (after logging in), it will attempt to load but will eventually go to the "Aw, Snap! Something went wrong with dispalying this webpage. Eorr code: Out of Memory" page. This is occuring right after I updated to v1.125.6 (from v1.125.2).

![Image](https://github.com/user-attachments/assets/7384f8b2-7169-480a-bc78-f5b76135d4b3)

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.125.6

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  #***Start of where power-tools is***
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - .env
  #***End of where power-tools is***

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media1/immich-library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=redacted
DB_PASSWORD=redacted
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

#***Start of where immich-power-tools start***
IMMICH_API_KEY=redacted
IMMICH_URL="http://immich_server:3001" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL="redacted" # External address of immich
```

### Reproduction steps

1. Go to http://immich_server:2283 which will redirect to http://immich_server:2283/photos
2. It will crash with the out of memory.
3. I can still go to other pages such as /albums which will load successfully.
...

### Relevant log output

```shell
https://drive.google.com/file/d/1Sq58_4QElk2YQlfVo5cJIpf-7Zvgar1j/view?usp=sharing
```
