### ISSUE TITLE
[Bug] Can't set profile picture

### ISSUE THREAD

**Issue by lukaslindnermusic** [immich-app/immich#15812]
### The bug

I can't set a profile picture for my admin account (I only have one account at the moment).
When I select an image and then click the option, the menu where I can resize & reposition the photo appears.
But no matter how I position the photo and no matter what type of photo I choose, when trying to safe it, I get:
`Error: Profile pictures cannot have transparent pixels. Please zoom in and/or move the image.`

However, I am fully zoomed in, and this also happens with photos that are squared aka. where there is no empty/transparent space around the photo in the first place.

This problem appears in Chrome as well as Safari.

(not sure if the problem is with the web version or with the server, so I checked both.)

### The OS that Immich Server is running on

Synology DSM 7.2.2-72806 Update 2

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

1.125.3 build.191

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/Media/Media/Photos/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/Media/Media/Photos/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=******
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/Media/Media/Photos/immich/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/Media/Media/Photos/immich/upload:/usr/src/app/upload:rw
      - /volume1/Media/Media/Photos/immich/cache:/cache:rw
      - /volume1/Media/Media/Photos/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=*******
DB_USERNAME=immichuser
DB_DATABASE_NAME=immich
DB_HOSTNAME=immich-db
REDIS_HOSTNAME=immich-redis
NODE_ENV=production
LOG_LEVEL=log
JWT_SECRET=*****
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Choose a photo in the web version and click it
2. Click on the three dots and choose "Set as profile picture" 
3. Zoom in so that the image fills the whole circle
4. Click "Set as profile picture"
5. The Error message appears

### Relevant log output

```shell

```
