### ISSUE TITLE
Failed to get asset duplicates (500) after update to v1.125.1

### ISSUE THREAD

**Issue by biligodos** [immich-app/immich#15813]
### The bug

After update to v1.125.1 i got this error
Failed to get asset duplicates - 500
yt@http://192.168.1.10:2283/_app/immutable/chunks/BYB68Yzy.js:1:8084
mt@http://192.168.1.10:2283/_app/immutable/chunks/BYB68Yzy.js:1:8008

I updated all the way to v1.125.7 but the problem still persists.

Container log files show the following error

[Nest] 18  - 01/31/2025, 7:31:28 PM   ERROR [Api:ErrorInterceptor~y9yjhm8a] Unknown error: TypeError: Cannot read properties of null (reading 'id')

TypeError: Cannot read properties of null (reading 'id')

    at mapAsset (/usr/src/app/dist/dtos/asset-response.dto.js:139:20)

    at /usr/src/app/dist/services/duplicate.service.js:27:77

    at Array.map (<anonymous>)

    at /usr/src/app/dist/services/duplicate.service.js:27:28

    at Array.map (<anonymous>)

    at DuplicateService.getDuplicates (/usr/src/app/dist/services/duplicate.service.js:25:27)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

### The OS that Immich Server is running on

openmediavault 7.6.0

### Version of Immich Server

v1.125.7 

### Version of Immich Mobile App

v1.125.7 

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /srv/dev-disk-by-uuid-047e9102-bd20-4b94-9528-9902537d361e/Media-Storage:/mnt/media/ext-pics:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    logging:
      driver: "journald"
      options:
        tag: "immich-server"

    
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-047e9102-bd20-4b94-9528-9902537d361e/Media-imm/library
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-047e9102-bd20-4b94-9528-9902537d361e/Media-imm/postgres
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.update to v1.125.1
2.
3.
...

### Relevant log output

```shell
[Nest] 18  - 01/31/2025, 7:31:28 PM   ERROR [Api:ErrorInterceptor~y9yjhm8a] Unknown error: TypeError: Cannot read properties of null (reading 'id')

TypeError: Cannot read properties of null (reading 'id')

    at mapAsset (/usr/src/app/dist/dtos/asset-response.dto.js:139:20)

    at /usr/src/app/dist/services/duplicate.service.js:27:77

    at Array.map (<anonymous>)

    at /usr/src/app/dist/services/duplicate.service.js:27:28

    at Array.map (<anonymous>)

    at DuplicateService.getDuplicates (/usr/src/app/dist/services/duplicate.service.js:25:27)

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

### Additional information

No env file I run in portainer
