### ISSUE TITLE
Album missing, sync error

### ISSUE THREAD

**Issue by Erdk2** [immich-app/immich#15824]
### The bug

When I trying to sync Albums in iOS (last version 18.3) an album is missing:

Failed to add album from server: assetCount 7019  != asset array length 7618 for album xxxxxxxxxxxx at 09:47:35.732 in SyncService

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    #command: ['start.sh', 'immich']
    volumes:
      - /mnt/WD/Immich:/usr/src/app/upload
      #- /mnt/WD/Imagenes:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      #- 2283:3001
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /home/nuc/docker/immich-app/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: inmich
    volumes:
      - /home/nuc/docker/immich-app/postgres:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
.
```

### Reproduction steps

When I trying to sync Albums in iOS (last version 18.3) an album is missing:

Failed to add album from server: assetCount 7019  != asset array length 7618 for album xxxxxxxxxxxx at 09:47:35.732 in SyncService

### Relevant log output

```shell

```
