### ISSUE TITLE
Smart Search results take 10+ seconds to load on Android app

### ISSUE THREAD

**Issue by aeozyalcin** [immich-app/immich#15837]
### The bug

This appears to be an Android app issue, rather than backend. When I do a smart search on the Android Immich app, the results take anywhere from 10-30 seconds to load. I am using Openvino acceleration for the ML container.

Things I already tried:
* I know it's not because of the model caching time - I have my env variables set to preload the CLIP models. I confirmed that models are being loaded at startup by looking at container logs.
* Even when I do back to back searches, results are still slow to load on Android app.
* Issue doesn't seem to exist for web. Doing searches back to back on the web UI loads the results in <2 seconds.

### The OS that Immich Server is running on

Ubuntu 24

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.5

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    #command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      # - 2283:3001
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
#    env_file:
#      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align -->      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size>    restart: always


volumes:
  #pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variabl>

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/raid1_hdd/immich/library
DB_DATA_LOCATION=/mnt/raid1_hdd/immich/postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

#MACHINE_LEARNING_PRELOAD__CLIP=ViT-H-14-378-quickgelu__dfn5b
MACHINE_LEARNING_PRELOAD__CLIP__TEXTUAL=ViT-H-14-378-quickgelu__dfn5b
MACHINE_LEARNING_PRELOAD__CLIP__VISUAL=ViT-H-14-378-quickgelu__dfn5b
```

### Reproduction steps

1. Configure ML container to use openvino acceleration
2. Do a smart search on the Android app, and see how long it takes
3. Repeat smart search on Web UI, and see how much quicker it is to load
...

### Relevant log output

```shell

```
