### ISSUE TITLE
Can't upload or sync any files larger than ca. 1 MByte

### ISSUE THREAD

**Issue by HearthisAt** [immich-app/immich#15832]
### The bug

The upload and sync stops to work and gives errors on mobile app and inside the browser

### The OS that Immich Server is running on

Ubuntu 2022

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.7

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/immich-app/import:/mnt/immich-app/import:ro
      - /mnt/HC_Volume_101864884/import:/mnt/HC_Volume_101864884/import:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  # Other services...
  #power-tools:
  #  container_name: immich_power_tools
  #  image: ghcr.io/varun-raj/immich-power-tools:latest
  #  ports:
  #    - "8001:3000"
  #  env_file:
  #    - .env
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

#  immich-prometheus:
#    container_name: immich_prometheus
#    ports:
      # this exposes the default port for Prometheus so you can interact with it
#      - 9090:9090
#    image: prom/prometheus
#    volumes:
      # the Prometheus configuration file - a barebones one is provided to get started
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # a named volume defined in the bottom of the Compose file; it can also be a mounted folder
 #     - prometheus-data:/prometheus

 # immich-grafana:
 #   container_name: immich_grafana
 #   command: [ './run.sh', '-disable-reporting' ] # this is to disable Grafana's telemetry
 #   ports:
 #     - 3000:3000
 #   image: grafana/grafana
 #   volumes:
      # stores your pretty dashboards and panels
 #     - grafana-data:/var/lib/grafana

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
#  prometheus-data:
#  grafana-data:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

IMMICH_API_KEY=XXXXX # your_immich_api_key
IMMICH_URL = "XXXX" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL = "XXXX" # External address of immich
IMMICH_TELEMETRY_INCLUDE=all
```

### Reproduction steps

1. No special workflow
2.
3.
...

### Relevant log output

```shell
Query failed : {
  durationMs: 1.962465999997221,
  error: PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(653488fb-6cce-4dc1-a6bc-56585db136d0, \\xbd6340d4cef95daea39ce4470d6257b6fa6db0cc) already exists.',
    schema_name: 'public',
    table_name: 'assets',
    constraint_name: 'UQ_assets_owner_checksum',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    '653488fb-6cce-4dc1-a6bc-56585db136d0',
    null,
    <Buffer bd 63 40 d4 ce f9 5d ae a3 9c e4 47 0d 62 57 b6 fa 6d b0 cc>,
    'upload/upload/653488fb-6cce-4dc1-a6bc-56585db136d0/2a/6f/2a6f293d-d895-4db9-be81-d72c703255a0.MOV',
    'EADB0BCB-3D19-4096-BDDE-5F787FB6667E/L0/001',
    'eb80d4cac098749043953788ff54d63f8f565e1f435e1aaf5359100485536a5e',
    2023-10-07T17:19:14.000Z,
    2023-10-13T07:12:01.000Z,
    2023-10-07T17:19:14.000Z,
    'VIDEO',
    false,
    false,
    '0:00:06.000000',
    true,
    'IMG_3120.MOV'
  ]
}

Query failed : {
  durationMs: 8.934757000009995,
  error: PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(653488fb-6cce-4dc1-a6bc-56585db136d0, \\xa120a281bd234f9293b647ca3b98c7f1165de63b) already exists.',
    schema_name: 'public',
    table_name: 'assets',
    constraint_name: 'UQ_assets_owner_checksum',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    '653488fb-6cce-4dc1-a6bc-56585db136d0',
    null,
    <Buffer a1 20 a2 81 bd 23 4f 92 93 b6 47 ca 3b 98 c7 f1 16 5d e6 3b>,
    'upload/upload/653488fb-6cce-4dc1-a6bc-56585db136d0/80/6e/806e9870-4122-40cc-bec2-95464cdcd875.HEIC',
    '5EC5422D-890B-47E4-BB67-F3673B9D46F5/L0/001',
    'eb80d4cac098749043953788ff54d63f8f565e1f435e1aaf5359100485536a5e',
    2023-10-27T17:16:01.000Z,
    2023-10-27T17:16:02.000Z,
    2023-10-27T17:16:01.000Z,
    'IMAGE',
    false,
    false,
    '0:00:00.000000',
    true,
    'IMG_4879.HEIC'
  ]
}
```
