### ISSUE TITLE
All face recognition fails with PostgresError: pgvecto.rs: Bad literal. INFORMATION: hint = Bad character with ascii 0x2d.

### ISSUE THREAD

**Issue by AdamLukeTaylor** [immich-app/immich#15848]
### The bug

After a clean install of Immich the face detection throws errors.  I've tried swapping ML models and using local and remote ML.  

This to me looks some sort of schema change.  I've previously had the ML running fine with the previous version, but this is a clean install for unrelated reasons.  the remote ML is also at v1.125.7

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.7

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
#    user: "1000:1000"
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/external_drive/immich-data/library
# The location where your database files are stored
DB_DATA_LOCATION=/media/external_drive/immich-data/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/London

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Set either remote/local ML
2.Hit refresh faces via jobs or a photo
3. No faces found in explore, check docker logs 

### Relevant log output

```shell
[Nest] 17  - 02/02/2025, 9:55:31 AM     LOG [Api:SystemConfigService~pe8jop7g] LogLevel=log (set via system config)
Query failed : {
  durationMs: 3.1370799988508224,
  error: PostgresError: pgvecto.rs: Bad literal.
  INFORMATION: hint = Bad character with ascii 0x2d.
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: 'XX000',
    where: "unnamed portal parameter $10 = '...'",
    file: 'error.rs',
    line: '7'
  },
  sql: 'with "added" as (insert into "asset_faces" ("id", "assetId", "imageHeight", "imageWidth", "boundingBoxX1", "boundingBoxY1", "boundingBoxX2", "boundingBoxY2") values ($1, $2, $3, $4, $5, $6, $7, $8)), "added_embeddings" as (insert into "face_search" ("faceId", "embedding") values ($9, $10)) select from (select 1) as "dummy"',
  params: [
    'd14ab558-74fb-47bc-b65d-2dad3a9d5154',
    'c73bd689-c1f5-4f41-9c40-c46aa4221c7f',
    1920,
    1440,
    729,
    621,
    1175,
    1117,
    'd14ab558-74fb-47bc-b65d-2dad3a9d5154',
    [
       -0.4672986,  0.36502957,  -0.9272251,  0.012039751,   0.34464693,
        -1.121846,     1.44556,     0.69203, -0.031252623,    -1.810544,
        0.8490009,  -0.7618176,    3.414967,   0.35469455,    0.3234002,
       0.93653595,  0.61429334, -0.36333203,   0.33501402,   0.74523854,
       0.27649277,   0.9108709, -0.40040964,   -1.4385912,     3.797318,
         1.351433,  -1.1965101,  0.53755766,   -1.1128632,    1.0462097,
       -0.7330754,   1.1529657, 0.101291895,    -1.912059,    0.5283977,
        -1.510734,  -1.9122422,  0.63438195,  -0.05806023,   -1.5753376,
      -0.32912296,  0.17497355,  -1.8653961,   -1.0692775,   -1.8475666,
       0.68600404,  0.89895725,  -0.7959367,     0.756675,   -1.1717799,
        0.3264103,  -1.1359568,   0.5256244,   0.41825348,    1.0753565,
       0.28944585,   0.8495392,   1.0236053,    -1.389407,   -0.2635857,
      -0.42135736, -0.15468132,   1.6011531,  -0.87958914,    1.9386789,
        1.4228343,  -1.1312698, -0.17966557,   -1.3682473,   -0.5914395,
        0.2383228,  0.69958967, -0.66688836,  -0.23820007,    0.8242754,
      -0.17343116,   0.9544601,  -1.7635946,   0.23073149,   -0.8743715,
        1.7263639,   1.1213398, -0.13137746,   0.84391975,    -2.459688,
       0.25544518,  0.13142267,  0.79952407,   -0.3077214,     1.267015,
        1.0058471,    1.724227,  0.70721924,  0.070133954,   -2.8696768,
        0.8230253,   0.1689989, -0.92659646,   0.53891754, -0.015362944,
      ... 412 more items
    ]
  ]
}
[Nest] 7  - 02/02/2025, 9:55:45 AM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/face-detection): PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x2d.
[Nest] 7  - 02/02/2025, 9:55:45 AM   ERROR [Microservices:JobService] PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x2d.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
[Nest] 7  - 02/02/2025, 9:55:45 AM   ERROR [Microservices:JobService] Object:
{
  "id": "c73bd689-c1f5-4f41-9c40-c46aa4221c7f"
}
```
