### ISSUE TITLE
Issues with HDR/Dolby Vision Video Transcoding and RAW Lens Correction in Thumbnail Generation

### ISSUE THREAD

**Issue by Polaris-Ye** [immich-app/immich#15867]
### The bug

1. Incorrect Color Mapping in HDR/Dolby Vision Video Transcoding
When transcoding HDR or Dolby Vision videos, the generated thumbnail cover and low-bitrate video exhibit incorrect color mapping, displaying a green-purple color shift. Is there any plan to address this issue in future updates?

![Image](https://github.com/user-attachments/assets/84b69e7b-a9c5-4100-9f0c-2328ab0247d2)

![Image](https://github.com/user-attachments/assets/84ce7fb8-a906-4f9f-bcb1-9152e4216661)

2. Lens Correction for RAW Photo Thumbnails
When generating thumbnails for RAW photos, would it be possible to apply lens correction data embedded in the RAW metadata?
I have noticed that on my DJI Mavic 3 Pro, the primary camera's DNG files have severe lens distortion if left uncorrected. This results in distorted thumbnails that do not properly reflect the original image quality. Would it be feasible to incorporate lens correction during thumbnail generation?

![Image](https://github.com/user-attachments/assets/3ac03e4c-2700-4d7b-abd3-72cf1bfac2c0)

1. HDR/杜比视界视频转码的颜色映射错误
在转码 HDR 或杜比视界视频时，生成的缩略图封面和低码率视频存在颜色映射错误，画面呈现 绿色-紫色 的偏色情况。请问是否有计划在未来的更新中修复该问题？

2. RAW 照片缩略图的镜头畸变矫正
在生成 RAW 格式照片的缩略图时，是否可以考虑读取并应用 RAW 文件中的镜头矫正数据？
我使用 DJI Mavic 3 Pro 时发现，主摄的 DNG 文件如果未解析镜头校正数据，会产生明显的镜头畸变，导致生成的缩略图失真，影响观感。请问是否可能在缩略图生成过程中加入镜头校正的支持？

### The OS that Immich Server is running on

Synology DSM 7.2.2

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v.125.3

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.nju.edu.cn/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.nju.edu.cn/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume1/docker/immich/cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.1panel.top/library/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.1panel.top/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
This problem probably not related to this file.
```

### Reproduction steps

1.Just normal usage

### Relevant log output

```shell

```

### Additional information

I appreciate the team's efforts in developing Immich, and I believe these improvements would significantly enhance the user experience. Looking forward to your thoughts on these issues.
感谢开发团队对 Immich 的持续优化，我相信这些改进会进一步提升用户体验。期待您的反馈！
