### ISSUE TITLE
Browser uploaded videos only working in App not Browser (Mime-Type issue)

### ISSUE THREAD

**Issue by indiana11011100** [immich-app/immich#15897]
### The bug

Moin everyone,
I really like immich, it is extremly awsome and I got fully addicted to it, so I already bought a License to support this project :smile:

Sadly there is just one anoying issue with videos showing in Browser (mime-type: see reproduction steps).  I don't know how to get more details to get / find a solution. So I hope I can get some description / help here.
Also a description from [firefox support](https://support.mozilla.org/en-US/questions/1048378) wasn't helping me. Edge, Firefox or even Chrome all are not able to play these videos :cry:

All Videos have been recorded from old, no longer existing Android mobiles (Samsung S9, Pixel 6, etc.).
Weired thing is, my actual Pixel 8 does play the videos in the App without any issues.
Next weired thing, synchronized Videos from my Pixel 8 are playing in Browser and App. Only the manuall uploaded files via Browser have this issue. What's the difference?

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.125.7

### Version of Immich Mobile App

1.125.5 build.181

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Portainer Immich Stack:

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the stack.env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=---
DB_DATA_LOCATION=---
IMMICH_VERSION=release
DB_PASSWORD=---
DB_USERNAME=---
DB_DATABASE_NAME=---
```

### Reproduction steps

1. Upload a video via Browser (Firefox, Chrome or Edge)
2. Try to preview in the albums overview (Grid or single Picture dosn't matter)
3. See Error Message (translated from german) "No video with supported format and MIME type found"
![Image](https://github.com/user-attachments/assets/9d0d63c4-1568-47e8-9928-35e5d77a9bbd)
![Image](https://github.com/user-attachments/assets/c211fe8e-47e5-406a-ae18-34a1e393252e)

### Relevant log output

```shell
Where can I find the needed log (Is it the Docker Log)?
The Docker log latest entries are older and do show an error at midnight (UTC - Locale Time (Europe/Berlin) while writing 04.02.2025 09:20). I was not connected at midnight!

[Nest] 6  - 02/04/2025, 12:00:00 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/04/2025, 12:00:00 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/04/2025, 12:00:00 AM   ERROR [Microservices:JobService] Object:
{
  "id": "868b17ba-81ea-4d88-8d30-f342fa628c04"
}
[Nest] 6  - 02/04/2025, 2:00:00 AM     LOG [Microservices:BackupService] Database Backup Starting. Database Version: 14
[Nest] 6  - 02/04/2025, 2:00:12 AM     LOG [Microservices:BackupService] Database Backup Success
[Nest] 16  - 02/04/2025, 7:55:06 AM     LOG [Api:EventRepository] Websocket Connect:    2ZJHiPa328ft3PasAAA5
[Nest] 16  - 02/04/2025, 7:55:16 AM     LOG [Api:EventRepository] Websocket Disconnect: 2ZJHiPa328ft3PasAAA5
[Nest] 16  - 02/04/2025, 7:56:54 AM     LOG [Api:EventRepository] Websocket Connect:    jtSYOaUibzXeEAEaAAA7
[Nest] 16  - 02/04/2025, 7:59:02 AM     LOG [Api:EventRepository] Websocket Disconnect: jtSYOaUibzXeEAEaAAA7
[Nest] 16  - 02/04/2025, 7:59:02 AM     LOG [Api:EventRepository] Websocket Connect:    hpyDSW_w32hcYa0mAAA9
[Nest] 16  - 02/04/2025, 8:00:32 AM     LOG [Api:EventRepository] Websocket Disconnect: hpyDSW_w32hcYa0mAAA9
[Nest] 16  - 02/04/2025, 8:00:32 AM     LOG [Api:EventRepository] Websocket Connect:    O_ud0zQnL2VtS3TmAAA_
[Nest] 16  - 02/04/2025, 8:00:47 AM     LOG [Api:EventRepository] Websocket Disconnect: O_ud0zQnL2VtS3TmAAA_
[Nest] 16  - 02/04/2025, 8:01:25 AM     LOG [Api:EventRepository] Websocket Connect:    srRlnX0D_945kNMiAABB
[Nest] 16  - 02/04/2025, 8:01:40 AM     LOG [Api:EventRepository] Websocket Disconnect: srRlnX0D_945kNMiAABB
[Nest] 16  - 02/04/2025, 8:01:41 AM     LOG [Api:EventRepository] Websocket Connect:    M1NV8xy8xlzmSC5_AABD
[Nest] 16  - 02/04/2025, 8:02:10 AM     LOG [Api:EventRepository] Websocket Connect:    u4vaUzlGVwPcDHV-AABF
[Nest] 16  - 02/04/2025, 8:02:37 AM     LOG [Api:EventRepository] Websocket Disconnect: u4vaUzlGVwPcDHV-AABF
[Nest] 16  - 02/04/2025, 8:10:29 AM     LOG [Api:EventRepository] Websocket Disconnect: M1NV8xy8xlzmSC5_AABD
[Nest] 16  - 02/04/2025, 8:10:30 AM     LOG [Api:EventRepository] Websocket Connect:    bpNbgcUknTju8oZsAABH
[Nest] 16  - 02/04/2025, 8:16:50 AM     LOG [Api:EventRepository] Websocket Disconnect: bpNbgcUknTju8oZsAABH
[Nest] 16  - 02/04/2025, 8:16:54 AM     LOG [Api:EventRepository] Websocket Connect:    ePlyIWX4SQYzBqERAABJ
```

### Additional information

As I wrote at the top I don't know how get more information about which mime-type is being requested, given or ...
Anyway, I know the most files are ".mp4" but I'm not sure if the file suffix is being used for mime-type or if any additional information in the file is existing / needed. At least, if information would be needed how can I add this (where) and it would be a lot of files :wink:

Apreciate any help!
