### ISSUE TITLE
Immich Android App reaches for "/.well-known/immich"

### ISSUE THREAD

**Issue by Krankenkasse** [immich-app/immich#15950]
### The bug

```
[07/Feb/2025:18:23:24 +0100] - 200 200 - GET https XXX.de "/api/server/ping" [Client XXX] [Length 14] [Gzip -] [Sent-to 192.168.178.xxx] "Dart/3.5 (dart:io)" "-"
[07/Feb/2025:18:23:24 +0100] - 200 200 - GET https XXX.de "/api/server/ping" [Client XXX] [Length 14] [Gzip -] [Sent-to 192.168.178.xxx] "Dart/3.5 (dart:io)" "-"
[07/Feb/2025:18:23:24 +0100] - 404 404 - GET https XXX.de "/api/.well-known/immich" [Client XXX] [Length 112] [Gzip -] [Sent-to 192.168.178.xxx] "Dart/3.5 (dart:io)" "-"
[07/Feb/2025:18:23:24 +0100] - 404 404 - GET https XXX.de "/api/.well-known/immich" [Client XXX] [Length 112] [Gzip -] [Sent-to 192.168.178.xxx] "Dart/3.5 (dart:io)" "-"
[07/Feb/2025:18:23:24 +0100] - 200 200 - GET https XXX.de "/api/users/me" [Client XXX] [Length 469] [Gzip -] [Sent-to 192.168.178.xxx] "Dart/3.5 (dart:io)" "-"
``` 

Thats the requests that are comming from the app when doing a "cold start" of the app.

The first log in the app is Failed to fetch users at /api/users

The problem is that my reverse proxy fail to ban banned the client for receiving to many 404 ( -> the /api/.well-known/immich requests )

https://xxx.xxx.de/.well-known/immich is reachable and has following payload:

```
{"api":{"endpoint":"/api"}}
```
**So maybe the app is reaching for the wrong endpoint?**

### The OS that Immich Server is running on

Debian 12 / Docker version 27.5.1,

### Version of Immich Server

1.125.7

### Version of Immich Mobile App

1.125.5 build.181

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/uploads/
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/db/

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_>
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Do a coldstart of the app outside the local network

### Relevant log output

```shell

```
