### ISSUE TITLE
Thumbnail Generation Fails with VIPS JPEG Decoding Errors resulting in high memory and disk i/o usage

### ISSUE THREAD

**Issue by Guuude** [immich-app/immich#15969]
### The bug

While running Immich in Docker, thumbnail generation jobs fail due to repeated VIPS JPEG decoding errors. Logs indicate issues such as skipped bytes before restart markers and failed DCT block decoding. Additionally, some images are flagged as "unsupported image format."

System information shows high memory usage (98.6% by Immich process) but low CPU utilization. No other services seem to be experiencing high resource consumption.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.5 build.181

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

networks:
  npm:
    external: true
  internal:
    internal: true


services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
      # - '2283:2283'
    networks:
      - internal
      - npm
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks:
      - internal


  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped
    networks:
      - internal


volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/immich-app/library
# The location where your database files are stored
DB_DATA_LOCATION=/opt/immich-app/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*********************

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=***********
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Run Immich server in Docker.
2. Upload JPEG images (potentially with large file sizes).
3. Observe the failure of thumbnailGeneration/generate-thumbnails jobs in the logs.

### Relevant log output

```shell
[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2491635 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2491635 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Object:
{
  "id": "dee23a11-d2ed-4fd6-b5a4-3e3a1b9165be"
}

[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:06 AM   ERROR [Microservices:JobService] Object:
{
  "id": "e3353c4a-5d1d-486f-92bd-14858449a4d7"
}

[Nest] 6  - 02/09/2025, 12:00:07 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 1598526 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:07 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 1598526 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:07 AM   ERROR [Microservices:JobService] Object:
{
  "id": "d5e07289-1025-4a8b-a27e-b179512de0da"
}

[Nest] 6  - 02/09/2025, 12:00:08 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 3843735 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:08 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 3843735 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:08 AM   ERROR [Microservices:JobService] Object:
{
  "id": "fd0d7cc9-0b68-44b6-976e-44331adfdee7"
}

[Nest] 6  - 02/09/2025, 12:00:12 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 6597957 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:12 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 6597957 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:12 AM   ERROR [Microservices:JobService] Object:
{
  "id": "8e134d17-5de3-4881-a7b1-512c337f4a12"
}

[Nest] 6  - 02/09/2025, 12:00:15 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/09/2025, 12:00:15 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:15 AM   ERROR [Microservices:JobService] Object:
{
  "id": "c26d610b-b1a2-4229-b53c-a00bb06ca657"
}

[Nest] 6  - 02/09/2025, 12:00:22 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4359910 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:22 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4359910 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:22 AM   ERROR [Microservices:JobService] Object:
{
  "id": "1f837ca5-fd5f-4196-8ef8-ac578def9094"
}

[Nest] 6  - 02/09/2025, 12:00:25 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/09/2025, 12:00:25 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:25 AM   ERROR [Microservices:JobService] Object:
{
  "id": "b351e7a4-4ebc-4956-b8e5-971c0c938a7f"
}

[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2516278 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4864948 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2516278 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4864948 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Object:
{
  "id": "c5a022e1-234c-4d67-81f8-c84a3c8f8fa4"
}

[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2516278 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4864948 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 2516278 bytes before restart marker
VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 4864948 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:26 AM   ERROR [Microservices:JobService] Object:
{
  "id": "e5213e8e-d73f-4c51-9939-2a5960e09792"
}

[Nest] 6  - 02/09/2025, 12:00:27 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 6  - 02/09/2025, 12:00:27 AM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:27 AM   ERROR [Microservices:JobService] Object:
{
  "id": "7a69413c-37cc-462a-89b0-d80c9934a65d"
}

[Nest] 6  - 02/09/2025, 12:00:28 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 8419201 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
[Nest] 6  - 02/09/2025, 12:00:28 AM   ERROR [Microservices:JobService] Error: VipsJpeg: ./lib/jpegli/decode_scan.cc:454: Skipped 8419201 bytes before restart marker
VipsJpeg: ./lib/jpegli/decode_scan.cc:539: Failed to decode DCT block
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:28 AM   ERROR [Microservices:JobService] Object:
{
  "id": "56fbe0a1-0d5e-4c4d-901b-a69f5b6e36a6"
}

[Nest] 6  - 02/09/2025, 12:00:48 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: extract_area: bad extract area
[Nest] 6  - 02/09/2025, 12:00:48 AM   ERROR [Microservices:JobService] Error: extract_area: bad extract area
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:90:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:62:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:441:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/09/2025, 12:00:48 AM   ERROR [Microservices:JobService] Object:
{
  "id": "77056b0a-b360-4062-87d3-a7bec10a539a"
}
```
