### ISSUE TITLE
PUBLIC_IMMICH_SERVER_URL changes in .env not synced with database configuration

### ISSUE THREAD

**Issue by dascth** [immich-app/immich#15985]
### Description
When using the official docker-compose.yml configuration and changing `PUBLIC_IMMICH_SERVER_URL` in `.env`, the server's external domain stored in the database (`system_metadata` table) is not automatically updated. This leads to shared links continuing to use the old domain until the database value is manually updated.

This occurs when using the standard configuration method (`.env` file) as specified in the official docker-compose.yml from the latest release.

### Current Behavior
1. Change `PUBLIC_IMMICH_SERVER_URL` in `.env` to a new domain
2. Restart containers
3. Shared links continue to use old domain because `server.externalDomain` in `system_metadata` table retains the old value

### Expected Behavior
When `PUBLIC_IMMICH_SERVER_URL` is changed in `.env` and containers are restarted, the `server.externalDomain` in the database should be automatically updated to match.

### Database Investigation
The issue can be observed by checking the system_metadata table:
```sql
SELECT * FROM system_metadata WHERE key = 'system-config';
```

This shows the server configuration including the externally facing domain:
```json
{
  "server": {
    "externalDomain": "https://old.domain.com"
  }
  // ... other config options
}
```

Even after updating `.env` and restarting containers, this value remains unchanged.

### Workaround
Manually update the database value:
```sql
UPDATE system_metadata 
SET value = jsonb_set(
    value::jsonb, 
    '{server,externalDomain}', 
    '"https://new.domain.com"'
) 
WHERE key = 'system-config';
```

Then restart the Immich containers:
```bash
docker compose down
docker compose up -d
```

Note: After applying the fix, users may need to perform a hard refresh (Shift+F5) in their browsers to clear any cached domain values.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.5

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      - NODE_CONFIG={"server":{"host":"0.0.0.0"}}

    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
        #storage_opt:
        #  dm.directio_enabled: "true"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
#
PUBLIC_IMMICH_SERVER_URL=https://hidden

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
UPLOAD_LOCATION=/srv/immich/library/

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=hidden

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

NODE_ENV=production
ENABLE_WEBSOCKET=true
```

### Reproduction steps

1. Set up Immich with initial domain (e.g., domain1.example.com) in `.env`:
   ```
   PUBLIC_IMMICH_SERVER_URL=https://domain1.example.com
   ```
2. Create a shared link in the UI
3. Change domain in `.env`:
   ```
   PUBLIC_IMMICH_SERVER_URL=https://domain2.example.com
   ```
4. Restart containers: `docker compose down && docker compose up -d`
5. Create new shared link
6. Observe: New shared links still use old domain

### Relevant log output

```shell

```

### Additional information

- Using the official docker-compose.yml from latest release
- The database value persists even after container restarts
- Client-side caching can mask the issue (requires hard refresh after fix)
- This could cause confusion when migrating to a new domain
- The current behavior suggests a synchronization issue between the environment configuration in `.env` and the database storage of this setting
- We verified this occurs with the standard deployment method, not using any custom configuration

This is my first contribution to open source in my life. Thanks for making something I felt compelled to support with my brain, and not just my money.
