### ISSUE TITLE
Shared Library Partner Cannot See People in Photos

### ISSUE THREAD

**Issue by azhirov** [immich-app/immich#15996]
### The bug

When adding a partner to a shared library, they are unable to see detected people in photos. Other features, such as location tags (if enabled) and the photo timeline (if configured), work correctly. However, there is no option to enable or configure people visibility for the partner.

I would like to use Immich as a family photo archive, and it would be great if family members had the same ability to view and search for people as the administrator.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

no

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`${IMMICH_HOSTNAME}`)"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsEncrypt"
      - "traefik.http.services.immich.loadbalancer.passhostheader=true"
      - "traefik.http.routers.immich.middlewares=compresstraefik,filter-ip@file"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/var/immich
IMMICH_VERSION=release
DB_PASSWORD=***
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
EXTERNAL_PATH=/var/photos
IMMICH_HOSTNAME=example.com
```

### Reproduction steps

1. Add a partner to a shared library.
2. Ensure that people detection is enabled in the main account.
3. Log in as the partner and check if detected people are visible.

**Expected behavior:**
Partners should have an option to view and search for detected people in shared libraries, similar to the administrator.

### Relevant log output

```shell

```

### Additional information

This feature would improve the usability of Immich for family archives, allowing shared users to fully benefit from the people recognition system.
