### ISSUE TITLE
[android] Certain photos missing from Android timeline

### ISSUE THREAD

**Issue by stephen304** [immich-app/immich#16006]
### The bug

I've been noticing an issue of photos missing from immich, and after investigating I've found that some photos from my camera roll don't show up in the Immich app, which presumably is causing them to not be uploaded:

Here is the media visible in Gphotos:
![Image](https://github.com/user-attachments/assets/cd2482a1-18f7-4576-9bd2-184a85588fb9)

(Note the 2 cat standing tall pictures and 1 video as well as 4 pictures of cat in box)

And in immich:
![Image](https://github.com/user-attachments/assets/d84eeee8-796f-4b34-9062-556b984b2c2d)
Only 1 picture of cat standing tall (1 missing photo and 1 missing video). None of the missing items are edits, all taken directly from the camera.

I checked on the immich server:
```
library/admin/2025/2025-02-07# ls -al
total 108788
d---------+ 1 root root      368 Feb  7 22:30 .
d---------+ 1 root root      560 Feb 10 11:45 ..
----------+ 1 root root  2658681 Feb  7 10:38 PXL_20250207_153852538.jpg
----------+ 1 root root  1070634 Feb  7 10:40 PXL_20250207_153855062~2.jpg
----------+ 1 root root  2691806 Feb  7 10:39 PXL_20250207_153855062.jpg
----------+ 1 root root 97173254 Feb  7 12:10 PXL_20250207_170946253.mp4
----------+ 1 root root  2412902 Feb  7 14:42 PXL_20250207_194205451.jpg
----------+ 1 root root  3180034 Feb  7 14:42 PXL_20250207_194211232.jpg
----------+ 1 root root  2194316 Feb  7 22:20 PXL_20250208_032049075.jpg
```

So I can verify that they weren't uploaded - the missing cat standing tall image is `PXL_20250208_032046747.jpg` and the missing video `PXL_20250208_032020273.mp4`.

There is another example recently - the 2 pictures of laptop parts are missing entirely from Immich (one is a crop of the other), as well as a bunch of pictures of the meshtastic box are also missing:
![Image](https://github.com/user-attachments/assets/93e5bf67-247a-4894-ac27-88467750586c)
![Image](https://github.com/user-attachments/assets/5a48025c-15f3-447d-8f7b-b82804dee40f)
I'm on the latest server version but still on app version 1.125.5 since the play store version for the latest update isn't available to me yet - but I checked the changelog and didn't see anything related to this.

I also tried logging out and back in to the app to rebuild the timeline but it didn't change anything. I'm assuming it has to have something to do with the images somehow, since I have no other explanation for why specific images are invisible to immich when they are all in the same place, some even taken within seconds of each other in the case of the cat and meshtastic device pictures.

Also, since there are GPS coordinates in my media and I don't want to risk confounding the troubleshooting by editing the files, is there an email I can privately send them to?

### The OS that Immich Server is running on

Synology Docker

### Version of Immich Server

1.126.1 and 1.125.7

### Version of Immich Mobile App

1.125.5

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
#    ports:
#      - 2283:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`xxxxxxxx`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=mytlschallenge"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    networks:
      - default
      - ingress
      - mail
    depends_on:
      - redis
      - database

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    restart: always
    volumes:
      - ./volumes/ml-cache:/cache
    env_file:
      - .env
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: always
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
#      start_interval: 30s
      start_period: 5m
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

networks:
  ingress:
    external: true
  mail:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./volumes/library
# The location where your database files are stored
DB_DATA_LOCATION=./volumes/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_datab>
TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.126.1

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Have these images in your camera roll
2. Open immich app
3. ???
4. Not there
...

### Relevant log output

```shell

```
