### ISSUE TITLE
Wrong storage space calculation after update

### ISSUE THREAD

**Issue by radiantwave** [immich-app/immich#16002]
### The bug

Logged in with my admin user without quota before the update:

![Image](https://github.com/user-attachments/assets/6394a1e6-b88b-4b9f-aec5-08e22590bad2)
Directly after pulling and recreating with v1.126.0:

![Image](https://github.com/user-attachments/assets/ea6896f4-9d68-4837-beb1-cf40da3e814f)

Actual usage as shown by the hetzner robot interface for the storage-box mounted for uploads:

![Image](https://github.com/user-attachments/assets/274e42a4-d517-4f76-b969-2dc86604515e) (11 GB Snapshots)

I can't make sense of the new numbers immich is showing.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.126.0

### Version of Immich Mobile App

v1.125.5

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-server.rule=Host(`mydomain.de`)"
      - "traefik.http.routers.immich-server.entrypoints=websecure"
      - "traefik.http.routers.immich-server.tls=true"
      - "traefik.http.routers.immich-server.tls.certresolver=myresolver"
      - "traefik.http.services.immich-server.loadbalancer.server.port=2283"
      - "traefik.docker.network=proxy"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - immich

volumes:
  model-cache:
networks:
  proxy:
    external: true
  immich:
```

### Your .env content

```Shell
DB_DATA_LOCATION=/srv/docker/immich/postgres
UPLOAD_LOCATION=/mnt/storagebox-immich
THUMB_LOCATION=/srv/docker/immich/thumbs
IMMICH_VERSION=v1.126.0

DB_PASSWORD=12345
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Have v1.125.7
2. Update to v1.126.0
3. ???

### Relevant log output

```shell

```
