### ISSUE TITLE
Tag search field not showing

### ISSUE THREAD

**Issue by helgew** [immich-app/immich#16030]
### The bug

I do not see the Tag search field in my filter options:

<img width="892" alt="Image" src="https://github.com/user-attachments/assets/ce894dac-f0bc-4f2f-b20f-5593b280d0cd" />

Based on the v1.126.0 release notes, I was expecting a Tag field under the first search field.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.125.3 build.191

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - proxy
      - redis_redis
      - default
    restart: always
    healthcheck:
      disable: false
    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: Host(`******************`)
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.service: immich-svc
      traefik.http.services.immich-svc.loadbalancer.server.port: 2283

      # Sets the maximum request body to 10GB
      traefik.http.routers.immich.middlewares: limit@docker
      traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: 10737418240
      traefik.http.middlewares.limit.buffering.memRequestBodyBytes: 200000000
      traefik.http.middlewares.limit.buffering.maxResponseBodyBytes: 10737418240
      traefik.http.middlewares.limit.buffering.memResponseBodyBytes: 200000000


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

volumes:
  model-cache:

networks:
  proxy:
    external: true
  redis_redis:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=****************
DB_PASSWORD=****************

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgresql/data

REDIS_HOSTNAME=redis
TZ=America/Los_Angeles
UID=1000
```

### Reproduction steps

1. Open the website and marvel at the beauty that is Immich 
2. Click on the filter icon

### Relevant log output

```shell

```
