### ISSUE TITLE
ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by aliuq** [immich-app/immich#16039]
### The bug

Container log throws a large number of errors after startup    

```bash
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/1.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/2.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/3.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/4.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/5.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/6.jpg'
immich_server    | [Nest] 8  - 02/12/2025, 3:54:02 AM   ERROR [Microservices:LibraryService] Library watcher for library cb0faac1-14cd-4feb-8856-e32ad9666e0d encountered error: Error: ENOSPC: System limit for number of file watchers reached, watch '/usr/src/app/external_share/7.jpg'
```

### The OS that Immich Server is running on

synology_geminilake_920+

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

0.0.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    restart: always
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH_SHARE}:/usr/src/app/external_share
      - ${EXTERNAL_PATH_NSFW}:/usr/src/app/external_nsfw
      - ${EXTERNAL_PATH_SELF}:/usr/src/app/external_self
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   restart: always
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   volumes:
  #     - ./ml-cache:/cache
  #   env_file:
  #     - .env
  #   healthcheck:
  #     disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

EXTERNAL_PATH_SHARE=/volume1/photo
EXTERNAL_PATH_NSFW=/volume1/photo_nsfw
EXTERNAL_PATH_SELF=/volume1/photo_self
```

### Reproduction steps

1. `docker-compose up -d`
2. `docker-compose logs -f`

### Relevant log output

```shell

```
