### ISSUE TITLE
Error generating thumbnails in v1.126.1

### ISSUE THREAD

**Issue by iwinstar** [immich-app/immich#16044]
### The bug

Similar to #13465.

I'm using the latest server version v1.126.1.  But some pictures still can't generate thumbnails. I've provided some images as attachments for upstream to debug.

### The OS that Immich Server is running on

Docker ( Synology x86_64 4.4.180+)

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
redis:
    container_name: Redis
    image: redis:latest
    network_mode: host
    user: "${UID}:${GID}"
    volumes:
      - /volume2/docker/Redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    container_name: Postgres
    network_mode: host
    user: "${UID}:${GID}"
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /volume2/docker/Postgres:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --port=${DB_PORT} || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --port=${DB_PORT} --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
      -p ${DB_PORT}
    restart: unless-stopped

  immich:
    container_name: Immich
    network_mode: host
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /volume2/docker/Immich/library:/usr/src/app/upload
      - /volume1/Photo:/data/Photo:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    healthcheck:
      disable: false
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    container_name: ImmichMachineLearning
    network_mode: host
    # user: "${UID}:${GID}"
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    volumes:
      - /volume2/docker/Immich/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
```

### Your .env content

```Shell
UID=1026
GID=100
TZ=Asia/Shanghai

DB_PORT=5433
DB_HOSTNAME=localhost
DB_USERNAME=***
DB_PASSWORD=***
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=localhost

MACHINE_LEARNING_ANN=False
MACHINE_LEARNING_PRELOAD__CLIP=XLM-Roberta-Large-Vit-B-16Plus
MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION=buffalo_l
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
[Nest] 7  - 02/12/2025, 6:11:05 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
[Nest] 7  - 02/12/2025, 6:11:05 AM   ERROR [Microservices:JobService] Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/12/2025, 6:11:05 AM   ERROR [Microservices:JobService] Object(1) {
  id: 'b3c63b36-fb78-4ce1-be30-e18da04a97fd'
}
```

### Additional information

[images.zip](https://github.com/user-attachments/files/18759433/images.zip)
