### ISSUE TITLE
Microservices workers failed and caused tasks to get stuck after the entire restart

### ISSUE THREAD

**Issue by Transwarpcom** [immich-app/immich#16054]
### The bug

immich_server            | microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')
immich_server            |     at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)
immich_server            |     at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)
immich_server            |     at connectTimedOut (/usr/src/app/node_modules/postgres/cjs/src/connection.js:257:5)
immich_server            |     at Timeout.done [as _onTimeout] (/usr/src/app/node_modules/postgres/cjs/src/connection.js:1033:8)
immich_server            |     at listOnTimeout (node:internal/timers:596:11)
immich_server            |     at process.processTimers (node:internal/timers:529:7)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server            | Initializing Immich v1.126.1
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | Starting microservices worker

### The OS that Immich Server is running on

Windows (Docker Latest)

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

None

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - D:/Gallery-dl:/mnt/media/Gallery-dl:rshared
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      # file: hwaccel.ml.yml
      # service: openvino-wsl # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  pgdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=pgdata

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.Follow the guide to install immich on Docker (Windows)
2.Add External Libraries
3.Start GENERATE THUMBNAILS && EXTRACT METADATA && LIBRARY etc.
4.After a error(immich_server            | microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')
immich_server            |     at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)
immich_server            |     at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)
immich_server            |     at connectTimedOut (/usr/src/app/node_modules/postgres/cjs/src/connection.js:257:5)
immich_server            |     at Timeout.done [as _onTimeout] (/usr/src/app/node_modules/postgres/cjs/src/connection.js:1033:8)
immich_server            |     at listOnTimeout (node:internal/timers:596:11)
immich_server            |     at process.processTimers (node:internal/timers:529:7)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server            | Initializing Immich v1.126.1
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | Starting microservices worker)
immich starts trying to restart itself after throwing this error, after restarting all jobs will be stuck forever until manually restarting the docker container multiple times, then this error will be triggered randomly (these happen again)

### Relevant log output

```shell
immich_server            | microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')
immich_server            |     at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)
immich_server            |     at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)
immich_server            |     at connectTimedOut (/usr/src/app/node_modules/postgres/cjs/src/connection.js:257:5)
immich_server            |     at Timeout.done [as _onTimeout] (/usr/src/app/node_modules/postgres/cjs/src/connection.js:1033:8)
immich_server            |     at listOnTimeout (node:internal/timers:596:11)
immich_server            |     at process.processTimers (node:internal/timers:529:7)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server            | Initializing Immich v1.126.1
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | Starting microservices worker


immich_server            | [Nest] 7  - 02/12/2025, 7:30:15 PM   ERROR [Microservices:JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error: Connection terminated due to connection timeout
immich_server            | [Nest] 7  - 02/12/2025, 7:30:15 PM   ERROR [Microservices:JobService] Error: Connection terminated due to connection timeout
immich_server            |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:131:73)
immich_server            |     at Object.onceWrapper (node:events:638:28)
immich_server            |     at Connection.emit (node:events:524:28)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at TCP.<anonymous> (node:net:351:12)
immich_server            | [Nest] 7  - 02/12/2025, 7:30:15 PM   ERROR [Microservices:JobService] Object(2) {
immich_server            |   id: '54aa7b55-661c-4c46-85e3-188c3e2e6103',
immich_server            |   source: 'upload'
immich_server            | }
immich_redis             | 1:M 12 Feb 2025 11:31:49.076 * 100 changes in 300 seconds. Saving...
immich_redis             | 1:M 12 Feb 2025 11:31:49.093 * Background saving started by pid 81
immich_server            | [Nest] 19  - 02/12/2025, 7:31:49 PM     LOG [Api:EventRepository] Websocket Connect:    DdfDhByoepegJWGYAAAB
immich_redis             | 81:C 12 Feb 2025 11:31:51.611 * DB saved on disk
immich_redis             | 81:C 12 Feb 2025 11:31:51.613 * RDB: 1 MB of memory used by copy-on-write
immich_redis             | 1:M 12 Feb 2025 11:31:51.717 * Background saving terminated with success


immich_machine_learning  | [02/12/25 19:34:54] INFO     Shutting down due to inactivity.                   
immich_machine_learning  | [02/12/25 19:34:54] INFO     Shutting down                                      
immich_machine_learning  | [02/12/25 19:34:54] INFO     Waiting for application shutdown.                  
immich_machine_learning  | [02/12/25 19:34:54] INFO     Application shutdown complete.                     
immich_machine_learning  | [02/12/25 19:34:54] INFO     Finished server process [9]                        
immich_machine_learning  | [02/12/25 19:34:54] ERROR    Worker (pid:9) was sent SIGINT!                    
immich_machine_learning  | [02/12/25 19:34:54] INFO     Booting worker with pid: 134
```
