### ISSUE TITLE
PostgresError: pgvecto.rs: Bad literal and PostgreSQL COREs when trying re-create face_index on asset_faces

### ISSUE THREAD

**Issue by bugacha** [immich-app/immich#16057]
### The bug

I'm running latest version of Immich via docker-compose with external immich-machine-learning.

When I refresh Smart Search I see Immich uses my external ML host but immich-server log file full of errors :

```
[Nest] 7  - 02/12/2025, 1:04:07 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x2d.
[Nest] 7  - 02/12/2025, 1:04:07 PM   ERROR [Microservices:JobService] PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x2d.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:524:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
[Nest] 7  - 02/12/2025, 1:04:07 PM   ERROR [Microservices:JobService] Object(1) {
  id: '4524396a-228d-44a5-83d8-dcadb3364538'
}
```

I've googled it up and people suggest to re-create clip_index and face_index indicies in PostgresSQL - Altho I'm not using external SQL so no idea why they were not created correctly in the first place.

Anyway, clip_index on smart_search table was re-created fine but I'm having problem with face_index on assert_faces table.

1. First of all `embedding` column didnt even exist. I created it manually

2. Secondly, the following Create Index command CORES PostgresSQL
(`embedding column has correct data type - vector(512);`)

```
SET vectors.pgvector_compatibility=on;
CREATE INDEX IF NOT EXISTS face_index ON asset_faces 
    USING hnsw (embedding vector_cosine_ops)
    WITH (ef_construction = 300, m = 16);
```
Postgres log : 

```
2025-02-12 11:49:21.779 UTC [1] LOG:  database system is ready to accept connections
2025-02-12 11:49:38.104 UTC [71] ERROR:  column "embedding" of relation "asset_faces" already exists
2025-02-12 11:49:38.104 UTC [71] STATEMENT:  ALTER TABLE asset_faces add COLUMN embedding real[]
2025-02-12 11:50:19.009 UTC [1] LOG:  server process (PID 71) was terminated by signal 11: Segmentation fault
2025-02-12 11:50:19.009 UTC [1] DETAIL:  Failed process was running: CREATE INDEX IF NOT EXISTS face_index ON asset_faces
            USING hnsw (embedding vector_cosine_ops)
            WITH (ef_construction = 300, m = 16)
2025-02-12 11:50:19.009 UTC [1] LOG:  terminating any other active server processes
2025-02-12 11:50:19.015 UTC [1] LOG:  all server processes terminated; reinitializing
2025-02-12 11:50:19.142 UTC [77] LOG:  database system was interrupted; last known up at 2025-02-12 11:49:21 UTC
```

Does anyone know how to fix this ???

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photos:/mnt/photos:ro
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    hostname: redis
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5432:5432"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

REDIS_HOSTNAME=redis

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/immich/upload
# The location where your database files are stored
DB_DATA_LOCATION=/data/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Amsterdam

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open psql connection to postgresl
2. Run this
```
DROP INDEX IF EXISTS face_index;
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE real[];
ALTER TABLE asset_faces ALTER COLUMN embedding SET DATA TYPE vector(512);
SET vectors.pgvector_compatibility=on;
CREATE INDEX IF NOT EXISTS face_index ON asset_faces 
    USING hnsw (embedding vector_cosine_ops)
    WITH (ef_construction = 300, m = 16);
```
3. PostgresSQL will core

### Relevant log output

```shell
2025-02-12 11:49:21.779 UTC [1] LOG:  database system is ready to accept connections
2025-02-12 11:49:38.104 UTC [71] ERROR:  column "embedding" of relation "asset_faces" already exists
2025-02-12 11:49:38.104 UTC [71] STATEMENT:  ALTER TABLE asset_faces add COLUMN embedding real[]
2025-02-12 11:50:19.009 UTC [1] LOG:  server process (PID 71) was terminated by signal 11: Segmentation fault
2025-02-12 11:50:19.009 UTC [1] DETAIL:  Failed process was running: CREATE INDEX IF NOT EXISTS face_index ON asset_faces
            USING hnsw (embedding vector_cosine_ops)
            WITH (ef_construction = 300, m = 16)
2025-02-12 11:50:19.009 UTC [1] LOG:  terminating any other active server processes
2025-02-12 11:50:19.015 UTC [1] LOG:  all server processes terminated; reinitializing
2025-02-12 11:50:19.142 UTC [77] LOG:  database system was interrupted; last known up at 2025-02-12 11:49:21 UTC
```
