### ISSUE TITLE
Default locale Time for Panamá isn't correct

### ISSUE THREAD

**Issue by rdmitre** [immich-app/immich#16067]
### The bug

For America (Panama), the default time format is dd/mm/YYYY HH:MM:SS AM/PM. A valid example is as follows: 12/02/2025 04:47:48 p. m. Currently, when the Default Locale is selected in the APP settings, something similar to 02/12/2025 04:50:40 p. m. is displayed. This is not the commonly used time format in Panama.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

v1.125.5 build.181

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - ${EXTERNAL_LOCATION}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Qnap/upload
THUMB_LOCATION=/mnt/Qnap/upload/thumbs
ENCODED_VIDEO_LOCATION=/mnt/Qnap/upload/encoded-video
PROFILE_LOCATION=/mnt/Qnap/upload/profile
BACKUP_LOCATION=/mnt/Qnap/upload/backups
LIBRARY_LOCATION=/mnt/Qnap/upload/library
EXTERNAL_LOCATION=/mnt/Qnap/external
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=v1.125.7
DB_PASSWORD=password
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=America/Panama
```

### Reproduction steps

1. I go to Account Settings,
2. Then to App Settings,
3. Then click on Default Locale.
4. I changed the language from English to Spanish hoping that this would solve the problem, but regardless of the selected language, the date format remains the same.
...

### Relevant log output

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/45f07a26-137e-43a8-af3b-d97863798bae)
