### ISSUE TITLE
Bundled ImageMagick can't seem to handle certain Z9 NEF files

### ISSUE THREAD

**Issue by shoikan** [immich-app/immich#16060]
### The bug

When importing 'older' NEF files (created by D3200, D7100, D750, and Z6), everything works as expected. But NEF files generated by Z9 do not always seem to be read properly. [ImageMagick apparently uses libraw for processing NEF](https://github.com/ImageMagick/ImageMagick/discussions/7044), and it does not appear to have support for certain compression algorithms on the Z9 yet, but I currently have no easy way of checking if I changed compression settings along the way. In below info you can see that there is a difference in Z9 firmware versions between a known working and known broken NEF file. Log file will show error below. In GUI it shows a 'Error loading image' message on where the thumbnail should be.

### The OS that Immich Server is running on

Docker on Armbian 24.11.2

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  redis:
    container_name: immich-redis
    image: docker.io/library/redis:7
    restart: unless-stopped
    logging:
      driver: json-file

  immich-postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000012
      - PGID=1000003
      - TZ=Europe/Luxembourg
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=xxxxxxx
      - POSTGRES_DB=immich
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-local/immich/postgres:/var/lib/postgresql/data
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on

  immich:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    restart: unless-stopped
    logging:
      driver: json-file
    ports:
      - 2283:2283
    environment:
      - PUID=1000012
      - PGID=1000003
      - TZ=Europe/Luxembourg
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=immich
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=xxxxxxx
    volumes:
      - /data/htpc/configs/immich/immich-upload:/usr/src/app/upload
      - /data/htpc/configs/immich/immich-external:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
      - /photos/Imported:/mnt/imported:ro
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: unless-stopped
    logging:
      driver: json-file
    environment:
      - PUID=1000012
      - PGID=1000003
      - TZ=Europe/Luxembourg
    volumes:
      - /tmp/immich-ml:/cache
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
```

### Your .env content

```Shell
?
```

### Reproduction steps

1. Import 'broken' NEF file
2. Watch log
3.
...

### Relevant log output

```shell
[Nest] 7  - 02/12/2025, 5:00:23 PM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file has corrupt header: magickload: Magick: Unsupported file format or not RAW file `/mnt/imported/2022/11/26a/20221126-DSC_3231.NEF' @ error/dng.c/ReadDNGImage/532 (null)
[Nest] 7  - 02/12/2025, 5:00:23 PM   ERROR [Microservices:JobService] Error: Input file has corrupt header: magickload: Magick: Unsupported file format or not RAW file `/mnt/imported/2022/11/26a/20221126-DSC_3231.NEF' @ error/dng.c/ReadDNGImage/532 (null)
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/12/2025, 5:00:23 PM   ERROR [Microservices:JobService] Object(1) {
  id: '84509c75-72ea-4381-a61c-295041a14d71'
```

### Additional information

Mediainfo on 'broken' Z9 NEF file:
```
General
Complete name                            : ./20221126-DSC_3586.NEF
Format                                   : TIFF
File size                                : 31.4 MiB
Writing application                      : NIKON CORPORATION Ver.03.00
Writing library                          : NIKON Z 9
FileExtension_Invalid                    : tiff tif

Image
Format                                   : JPEG (TIFF v6)
Format settings                          : Little
Bit depth                                : 1 bit
Encoded date                             : 2022:11:26 20:53:32
Density                                  : 300 dpi
```

Mediainfo on 'working' Z9 NEF file:
```
General
Complete name                            : 20221016-DSC_4059.NEF
Format                                   : TIFF
File size                                : 51.4 MiB
Writing application                      : NIKON CORPORATION Ver.02.10
Writing library                          : NIKON Z 9
FileExtension_Invalid                    : tiff tif

Image
Format                                   : JPEG (TIFF v6)
Format settings                          : Little
Bit depth                                : 1 bit
Encoded date                             : 2022:10:16 01:04:38
Density                                  : 300 dpi
```
