### ISSUE TITLE
Error: connect ECONNREFUSED [::]:6379 immich_server | at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)

### ISSUE THREAD

**Issue by adrivn** [immich-app/immich#16087]
### The bug

Upon starting, the immich_server loops constantly and throws this error, which I think might have something to do with Redis

```
immich_server            | Error: connect ECONNREFUSED 172.18.0.5:6379
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
immich_server            |   errno: -111,
immich_server            |   code: 'ECONNREFUSED',
immich_server            |   syscall: 'connect',
immich_server            |   address: '172.18.0.5',
immich_server            |   port: 6379
immich_server            | }
```

### The OS that Immich Server is running on

Arch (CachyOS)

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
  model-cache:

services:

  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - caddy
    ports:
      - '2283:2283'
    labels:
      caddy: pics.localhost
      caddy.reverse_proxy: "{{upstreams 2283}}"
    depends_on:
      - immich-redis
      - immich-db
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    networks:
      - caddy
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    networks:
      - caddy
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-db:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - caddy
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
PUID=1000
PGID=1000

# The location where your uploaded files are stored
# UPLOAD_LOCATION=./apps/immich/library
UPLOAD_LOCATION=/home/me/Memories/
# The location where your database files are stored
DB_DATA_LOCATION=./apps/immich/postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Fire up `docker compose up`
2. ???
3. Profit
...

### Relevant log output

```shell
immich_server            | Error: connect ECONNREFUSED 172.18.0.5:6379
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
immich_server            |   errno: -111,
immich_server            |   code: 'ECONNREFUSED',
immich_server            |   syscall: 'connect',
immich_server            |   address: '172.18.0.5',
immich_server            |   port: 6379
immich_server            | }
```
