### ISSUE TITLE
Android App: photos marked as blacklisted / "not backed up" while theyare indeed backed up on the server

### ISSUE THREAD

**Issue by licryle** [immich-app/immich#16101]
### The bug

Hi there,

TLDR: fresh sync from my phone with 400 pictures uploaded 400, but marked 200 as "not backed up" while they are on the server. They just don't seem to be detected as "already uploaded".

Full version:
Fresh immich install with large import of 200k photos on the backend.
I just installed the app on Android and synced the photos from the phone, which are ~400 behind the import.

I started with app v1,1.125.7 - the sync worked but I noticed many pictures not marked as backed up.
Trying to reupload them would yield PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
My bad for not checking the Web UI is the photo was here.

Tried to log out, noticed the App is behind the server.
Uninstalled the app v1.125.7, installed v1.126.1

Redid a sync and configuration.

Sync successfully completed as well, but about half of the pictures on the device are marked as "not synced".
I tracked the picture down on the web server this time, it is present.

I tried to manually upload one picture from the app, which yields:
- Success in the App
- PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum" on the Server logs.

I tracked down the "blacklisted" files on the mobile app, cleared them, reuploaded.
Same behavior.

In sum:
- all pictures from the phone got uploaded
- half got marked as "successfully uploaded"
- half got marked as "blacklisted" / "not backedup"

### The OS that Immich Server is running on

ElementaryOS

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/videos:/videos
      - /mnt/photos:/photos
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
App:
[_startUpload] Manual Upload Completed - success: 1, failed: 0

Server:
Query failed : {
  durationMs: 55.30890299938619,
  error: PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(fa8c4dd0-169c-4b67-b9d4-e1419ef525f1, \\x3b865eba5a1d8817d4f0b615158eefa136995ea8) already exists.',
    schema_name: 'public',
    table_name: 'assets',
    constraint_name: 'UQ_assets_owner_checksum',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    'fa8c4dd0-169c-4b67-b9d4-e1419ef525f1',
    null,
    <Buffer 3b 86 5e ba 5a 1d 88 17 d4 f0 b6 15 15 8e ef a1 36 99 5e a8>,
    'upload/upload/fa8c4dd0-169c-4b67-b9d4-e1419ef525f1/50/44/50445347-379d-4499-8ba2-920e007633d3.jpg',
    '1000441900',
    '3b6e650de55d92b80d4187d48c0b351134a12269b6816cac3116ee22fa65fe7e',
    2024-12-28T05:20:23.000Z,
    2024-12-28T05:20:24.000Z,
    2024-12-28T05:20:23.000Z,
    'IMAGE',
    false,
    false,
    '0:00:00.000000',
    true,
    'IMG_20241228_132023.jpg'
  ]
}
```
