### ISSUE TITLE
Can't perform check for corrupt asset backups: LateInitializationError: Field '_db@952341375'

### ISSUE THREAD

**Issue by Deathproof76** [immich-app/immich#16126]
### The bug

Hello there, 

I'm not able to perform the check for corrupt asset backups from the mobile app. Tested from my and my wifes account. In both cases the error seems to be contained only to the mobile app logs. Nothing in Docker logs. Everything else seems to be working without a problem.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.126.1 using imagegenius/immich:openvino

### Version of Immich Mobile App

v1.126.1 on Android

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    image: ghcr.io/imagegenius/immich:openvino
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - c 189:* rmw
    container_name: immich
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOSTNAME=postgres16
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis2
      - REDIS_PASSWORD=******************
      - MACHINE_LEARNING_WORKERS=1
      - MACHINE_LEARNING_MODEL_TTL=0
      - MACHINE_LEARNING_HOST=127.0.0.1
      - MACHINE_LEARNING_PORT=3003
      - MACHINE_LEARNING_MAX_BATCH_SIZE__FACIAL_RECOGNITION=1
      - CPU_CORES=6
    deploy:
      resources:
        limits:
          cpus: "6.0"
    volumes:
      - /mnt/velodrive/docker-services/immich/config:/config
      - /mnt/velodrive/docker-services/immich/photos:/photos
      - /etc/localtime:/etc/localtime:ro
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 2283:8080
  redis2:
    image: redis
    container_name: redis2
    restart: unless-stopped
    command: redis-server --requirepass ******************
    volumes:
      - /etc/localtime:/etc/localtime:ro
  postgres16:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: postgres16
    restart: unless-stopped
    ports:
      - 5433:5432
    deploy:
      resources:
        limits:
          cpus: "6.0"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
      TZ: Europe/Berlin
    volumes:
      - /mnt/velodrive/docker-services/immich/postgres16:/var/lib/postgresql/data
      - /mnt/velodrive/docker-services/immich/dbback:/dbback
      - /etc/localtime:/etc/localtime:ro
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 15888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ******************
      PGADMIN_DEFAULT_PASSWORD: ******************
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data
```

### Your .env content

```Shell
none
```

### Reproduction steps

1. Enable additional features for Troubleshooting
2.  Go to Settings -> Backup -> Perform check
3. Nothing seems to happen

### Relevant log output

```shell
2025-02-15 19:05:42.128668 | SEVERE   | ImmichErrorLogger    | PlatformDispatcher - Catch all | LateInitializationError: Field '_db@952341375' has not been initialized. |
#0      Store.put (package:immich_mobile/entities/store.entity.dart)
#1      ApiService.setAccessToken (package:immich_mobile/services/api.service.dart:154)
#2      BackupVerificationService._computeSaveToDelete (package:immich_mobile/services/backup_verification.service.dart:128)
<asynchronous suspension>
#3      _RemoteRunner._run (dart:isolate:1092)
<asynchronous suspension>
```

### Additional information

I'm using the monolythic docker image from imagegenius with tensorchord/pgvecto-rs:pg16-v0.2.0.  There may be a database problem, as there is one album,  my account can scroll through without a problem, but the app on my wifes phone crashes. We are both using Samsung phones (S23U and Z5 Flip) with "Prefer remote images" enabled.
