### ISSUE TITLE
Videos in External Libraries has wrong timestamp

### ISSUE THREAD

**Issue by mumuxijili** [immich-app/immich#16141]
### The bug

Hi guys! I find that videos in External Libraries add timezone unnecessarily. My local time is GMT+8, photos have correct timestamp, but videos add another 8 hours to the timestamp. This happens on both web ui and ios app. I'm not sure if it's a common issue or my settings are wrong, because this bug exists for a long time(I started from v1.115). Any suggestions?

### The OS that Immich Server is running on

QNAP NAS OS(based on Linux kernal 5.10.60 I believe)

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3'
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.126.1
    environment:
      DB_PASSWORD: xxx
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - immich/upload:/usr/src/app/upload
      - immich/Photos/SOOC:/opt/external
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.126.1
    environment:
      DB_PASSWORD: xxx
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    volumes:
      - immich/cache:/cache
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2.14-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich/data:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
```

### Your .env content

```Shell
merged in docker-compose.yml
```

### Reproduction steps

1. Copy videos to External Libraries
2. Scan

### Relevant log output

```shell

```
