### ISSUE TITLE
Thumbnails are not created automatically, error when creating thumbnails manually

### ISSUE THREAD

**Issue by Kiirdnej** [immich-app/immich#16154]
### The bug

Since the upgrade to v.1.126.1 I have the problem that no preview is automatically generated for uploaded media.  
The file is uploaded and displayed in Immich without a preview (Pic 1). 
![Image](https://github.com/user-attachments/assets/c0cc7db6-6e9d-4dcc-b7cd-72597ebe4329)

If you try to open the image, it fails (Pic 2). 
![Image](https://github.com/user-attachments/assets/af155c2a-3025-41e4-8eb1-b8d620371109)

The “Generate Thumbnail” job is set to zero for Active and zero for Waiting (Pic 3).
![Image](https://github.com/user-attachments/assets/6b281108-7f0a-423b-843c-b701fb05935b)

If I start the job manually by clicking on “Missing”, an image is first loaded in “Waiting” and then in “Active” (Pic 4). 
![Image](https://github.com/user-attachments/assets/5091a172-030a-4d21-9b6f-698936c2b97a)

The error can then be observed in the log.
After running the job manually, the preview images are available in the Immich interface.
The thumbnails are now available and you can open the image (Pic 5)
![Image](https://github.com/user-attachments/assets/4cd43eb1-a9c0-44fc-a048-8a55aa53a97d)

I have already tested a rollback to v.1.125.7 and purged the old images, unfortunately no difference.

Many thanks in advance

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1 build.184

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      internal_bridge:
        ipv4_address: 192.168.70.3
      external_bridge:
        ipv4_address: 192.168.69.4

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      internal_bridge:
        ipv4_address: 192.168.70.4

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      internal_bridge:
        ipv4_address: 192.168.70.5

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      internal_bridge:
        ipv4_address: 192.168.70.6

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - stack.env
    networks:
      internal_bridge:
        ipv4_address: 192.168.70.8

volumes:
  model-cache:

networks:
  internal_bridge:
    external: true
  external_bridge:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/docker/immich/data/upload
DB_DATA_LOCATION=/docker/immich/db
IMMICH_VERSION=release
DB_PASSWORD=xxxxxx
DB_USERNAME=xxxxxx
DB_DATABASE_NAME=immich
IMMICH_API_KEY=xxxxxx
IMMICH_URL="http://192.168.70.3:2283" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL="https://immich.domain.tld" # External address of immich
GOOGLE_MAPS_API_KEY=xxxxxx
GEMINI_API_KEY=xxxxxx
DB_HOST=192.168.70.6
DB_PORT=5432
```

### Reproduction steps

1. Upload image or video
2. Seeing not thumbnail is generated
3. Manually triggering the thumbnail Job
4. Error get displayed in Docker Logs
5. Uploaded image or video now have a thumbnail

### Relevant log output

```shell
[Nest] 18  - 02/17/2025, 10:09:57 AM     LOG [Api:EventRepository] Websocket Connect:    UM2qevO0S0rvwRA5AAAf
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[h264 @ 0x3a6ac1e0580] Reinit context to 720x1280, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/upload/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/3c/78/3c78d158-0688-4706-b874-388605edf5ac.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2018-10-01T12:36:29.000000Z
  Duration: 00:00:00.65, start: 0.000000, bitrate: 2078 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, bt709, progressive, left), 720x1280 [SAR 1:1 DAR 9:16], 2096 kb/s, 30 fps, 30 tbr, 90k tbn (default)
      Metadata:
        creation_time   : 2018-10-08T17:56:09.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 10/08/2018.
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 125 kb/s (default)
      Metadata:
        creation_time   : 2018-10-08T17:56:09.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 10/08/2018.
        vendor_id       : [0][0][0][0]
[out#0/webp @ 0x3a6ac1a2640] No explicit maps, mapping streams automatically...
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Created video stream from input stream 0:0
[Parsed_thumbnail_1 @ 0x3a6ac1a3000] batch size: 12 frames
[Parsed_scale_5 @ 0x3a6ac110d80] w:250 h:-2 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[Parsed_fps_0 @ 0x3a6ac1a2e80] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> webp (libwebp_anim))
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Starting thread...
[vf#0:0 @ 0x3a6ac098880] Starting thread...
[vist#0:0/h264 @ 0x3a6ac220780] [dec:h264 @ 0x3a6ac220a80] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280] Starting thread...
Press [q] to stop, [?] for help
[h264 @ 0x3a6ac1e0580] Reinit context to 720x1280, pix_fmt: yuv420p
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280] Terminating thread with return code 0 (success)
[vist#0:0/h264 @ 0x3a6ac220780] [dec:h264 @ 0x3a6ac220a80] Decoder thread received EOF packet
[vist#0:0/h264 @ 0x3a6ac220780] [dec:h264 @ 0x3a6ac220a80] Decoder returned EOF, finishing
[Parsed_thumbnail_1 @ 0x3a6ae0506c0] batch size: 12 frames
[Parsed_scale_5 @ 0x3a6ae0509c0] w:250 h:-2 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[graph 0 input from stream 0:0 @ 0x3a6ae050a80] w:720 h:1280 pixfmt:yuv420p tb:1/90000 fr:30/1 sar:1/1 csp:bt709 range:tv
[Parsed_fps_0 @ 0x3a6ae050540] fps=12/1
[Parsed_scale_5 @ 0x3a6ae0509c0] w:720 h:1280 fmt:yuv420p csp:bt709 range:tv sar:1/1 -> w:250 h:444 fmt:yuv420p csp:bt709 range:pc sar:999/1000 flags:0x00042200
[graph 0 input from stream 0:0 @ 0x3a6ae050a80] video frame properties congruent with link at pts_time: 0.333333
[Parsed_fps_0 @ 0x3a6ae050540] Set first pts to 4
[vist#0:0/h264 @ 0x3a6ac220780] [dec:h264 @ 0x3a6ac220a80] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x3a6ac098880] Filtergraph returned EOF, finishing
[vf#0:0 @ 0x3a6ac098880] All consumers returned EOF
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] No filtered frames for output stream, trying to initialize anyway.
Output #0, webp, to 'upload/thumbs/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/b7/78/b7786459-da51-42da-b862-63d0a266e4c2-thumbnail.webp':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf61.1.100
  Stream #0:0(und): Video: webp, 1 reference frame, yuv420p(progressive), 250x444 [SAR 999:1000 DAR 9:16], q=2-31, 200 kb/s, 12 fps, 1k tbn (default)
      Metadata:
        creation_time   : 2018-10-08T17:56:09.000000Z
        handler_name    : ISO Media file produced by Google Inc. Created on: 10/08/2018.
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.3.100 libwebp_anim
[out#0/webp @ 0x3a6ac1a2640] Starting thread...
[Parsed_fps_0 @ 0x3a6ae050540] 2 frames in, 0 frames out; 2 frames dropped, 0 frames duplicated.
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Encoder thread received EOF
[libwebp encoder @ 0x3a6ac060e00] WebPAnimEncoderAssemble() failed with error: 1
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Error submitting video frame to the encoder
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Error flushing encoder: Cannot allocate memory
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Task finished with error code: -12 (Cannot allocate memory)
[vost#0:0/libwebp_anim @ 0x3a6ac0d2b80] Terminating thread with return code -12 (Cannot allocate memory)
[out#0/webp @ 0x3a6ac1a2640] All streams finished
[out#0/webp @ 0x3a6ac1a2640] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x3a6ac098880] Terminating thread with return code 0 (success)
[AVIOContext @ 0x3a6ac0611c0] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[out#0/webp @ 0x3a6ac1a2640] Output file #0 (upload/thumbs/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/b7/78/b7786459-da51-42da-b862-63d0a266e4c2-thumbnail.webp):
[out#0/webp @ 0x3a6ac1a2640]   Output stream #0:0 (video): 0 frames encoded; 0 packets muxed (0 bytes); 
[out#0/webp @ 0x3a6ac1a2640]   Total: 0 packets (0 bytes) muxed
[out#0/webp @ 0x3a6ac1a2640] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
[out#0/webp @ 0x3a6ac1a2640] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280] Input file #0 (upload/upload/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/3c/78/3c78d158-0688-4706-b874-388605edf5ac.mp4):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280]   Input stream #0:0 (video): 18 packets read (157207 bytes); 2 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x3a6ac110280]   Total: 18 packets (157207 bytes) demuxed
[AVIOContext @ 0x3a6ac060680] Statistics: 168895 bytes read, 0 seeks
Conversion failed!
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: ffmpeg exited with code 244: Conversion failed!
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Error: ffmpeg exited with code 244: Conversion failed!
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Object(1) {
  id: 'b7786459-da51-42da-b862-63d0a266e4c2'
}
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[h264 @ 0x496962c0580] Reinit context to 848x640, pix_fmt: yuv420p
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/upload/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/d4/12/d41264fe-7ed4-4526-93a1-e82aa6acbc86.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
  Duration: 00:03:55.80, start: 0.000000, bitrate: 1300 kb/s
  Stream #0:0[0x1](und): Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(tv, reserved, progressive, left), 848x636, 1181 kb/s, 30 fps, 30 tbr, 30k tbn (default)
      Metadata:
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 116 kb/s (default)
      Metadata:
        vendor_id       : [0][0][0][0]
[out#0/image2 @ 0x496961a0fc0] No explicit maps, mapping streams automatically...
[vost#0:0/mjpeg @ 0x496960d3780] Created video stream from input stream 0:0
[Parsed_thumbnail_1 @ 0x496961a1440] batch size: 12 frames
[Parsed_fps_0 @ 0x496961a0e40] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
[vost#0:0/mjpeg @ 0x496960d3780] Starting thread...
[vf#0:0 @ 0x496960984c0] Starting thread...
[vist#0:0/h264 @ 0x49696230500] [dec:h264 @ 0x496960f0780] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280] Starting thread...
Press [q] to stop, [?] for help
[h264 @ 0x496962c1980] Reinit context to 848x640, pix_fmt: yuv420p
[Parsed_thumbnail_1 @ 0x4969a050540] batch size: 12 frames
[graph 0 input from stream 0:0 @ 0x4969a050840] w:848 h:636 pixfmt:yuv420p tb:1/30000 fr:30/1 sar:0/1 csp:reserved range:tv
[graph 0 input from stream 0:0 @ 0x4969a050840] Invalid color range
[Parsed_fps_0 @ 0x4969a0503c0] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
[vf#0:0 @ 0x496960984c0] Error reinitializing filters!
[vf#0:0 @ 0x496960984c0] Task finished with error code: -22 (Invalid argument)
[vf#0:0 @ 0x496960984c0] Terminating thread with return code -22 (Invalid argument)
[vost#0:0/mjpeg @ 0x496960d3780] Encoder thread received EOF
[vost#0:0/mjpeg @ 0x496960d3780] Could not open encoder before EOF
[vost#0:0/mjpeg @ 0x496960d3780] Task finished with error code: -22 (Invalid argument)
[vost#0:0/mjpeg @ 0x496960d3780] Terminating thread with return code -22 (Invalid argument)
[vist#0:0/h264 @ 0x49696230500] [dec:h264 @ 0x496960f0780] Decoder returned EOF, finishing
[vist#0:0/h264 @ 0x49696230500] [dec:h264 @ 0x496960f0780] Terminating thread with return code 0 (success)
[vist#0:0/h264 @ 0x49696230500] All consumers of this stream are done
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280] All consumers are done
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280] Terminating thread with return code 0 (success)
[out#0/image2 @ 0x496961a0fc0] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280] Input file #0 (upload/upload/7fbc1247-9b89-4bcf-ad9d-bcbb41fade6f/d4/12/d41264fe-7ed4-4526-93a1-e82aa6acbc86.mp4):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280]   Input stream #0:0 (video): 318 packets read (1372972 bytes); 2 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x49696110280]   Total: 318 packets (1372972 bytes) demuxed
[AVIOContext @ 0x49696060680] Statistics: 1617938 bytes read, 0 seeks
Conversion failed!
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: ffmpeg exited with code 234: Conversion failed!
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Error: ffmpeg exited with code 234: Conversion failed!
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (node:events:524:28)
    at ChildProcess._handle.onexit (node:internal/child_process:293:12)
[Nest] 7  - 02/17/2025, 10:10:25 AM   ERROR [Microservices:JobService] Object(1) {
  id: 'dce2a8f8-a9cc-4c69-93bf-d14e1170a86a'
}
```
