### ISSUE TITLE
Storage Space not reported correctly

### ISSUE THREAD

**Issue by quiode** [immich-app/immich#16152]
### The bug

If I have a unlimited quota, the used storage space is displayed wrong (it says no space is used):

![Image](https://github.com/user-attachments/assets/5bcf7bb9-3983-4ae3-9321-86f226229e8b)

But if I enable any quota, the used storage is now reported correctly:

![Image](https://github.com/user-attachments/assets/be3d12af-f4e3-4207-b92d-c2476331caf7)

I use zfs on my host platform (and use it for immich) so this could maybe cause an issue.

### The OS that Immich Server is running on

Docker and Host NixOS 24.11

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    runtime: nvidia
    volumes:
      - /hdd/non-critical/immich/data:/usr/src/app/upload
      - /hdd/critical/immich/data/library:/usr/src/app/upload/library
      - /hdd/critical/immich/data/upload:/usr/src/app/upload/upload
      - /hdd/critical/immich/data/profile:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /run/agenix/immich_db_pw
      - .env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-internal
      - immich-external
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=immich'
      - 'traefik.http.routers.immich.rule=Host(`immich.dominik-schwaiger.ch`)'
      - 'traefik.http.routers.immich.tls=true'
      - 'traefik.http.routers.immich.tls.certresolver=letsencrypt'

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    runtime: nvidia
    volumes:
      - model-cache:/cache
    env_file:
      - /run/agenix/immich_db_pw
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - immich-internal

  redis:
    container_name: immich_redis
    image: redis
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    networks:
      - immich-internal
    env_file:
      - /run/agenix/immich_db_pw
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /ssd/critical/immich/database:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:

networks:
  immich-internal:

  immich-external:
    name: immich
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Zurich

# The Immich version to use. You can pin this to a specific version like "v1.71.0" (instead of "release")
IMMICH_VERSION=v1.126.1

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# DB_PASSWORD=postgres defined as a secret!

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. setup immich like in my setup https://github.com/quiode/beaststation-config
2. set/unset quota on any account

### Relevant log output

```shell

```
