### ISSUE TITLE
External Library Dates not always correct

### ISSUE THREAD

**Issue by Fonzi03** [immich-app/immich#16150]
### The bug

OS: Docker LXC : https://community-scripts.github.io/ProxmoxVE/scripts?id=docker
Debian 12

Immich: v1.125.7

![Image](https://github.com/user-attachments/assets/48340b11-b6d7-449e-8ea9-57aaea6d78f9)

I have an external library that I have a few thousand organized photos in. Most, about 75% or so are showing up with the correct date. Others however are showing up I believe based off the date they were scanned into immich. 

Immich shows: 01/10/25 @2:40AM which sounds about right for when I would have gotten things running/scanning
(I tried refreshing metadata as well)

![Image](https://github.com/user-attachments/assets/e41f7dab-57c7-4551-a7b1-f043e197e7b0)

exif:
```
ExifTool Version Number         : 13.19
File Name                       : Blue8.png
Directory                       : A:/Photos/Jefe + Angelina Litter 2023 (Hugo)/Blue
File Size                       : 24 MB
File Modification Date/Time     : 2024:01:22 01:12:28-05:00
File Access Date/Time           : 2025:02:16 23:09:11-05:00
File Creation Date/Time         : 2024:02:13 22:44:50-05:00
File Permissions                : -rw-rw-rw-
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 2992
Image Height                    : 2000
Bit Depth                       : 8
Color Type                      : RGB with Alpha
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Profile Name                    : ICC profile
Profile CMM Type                : Little CMS
Profile Version                 : 4.3.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2024:01:22 06:11:03
Profile File Signature          : acsp
Primary Platform                : Microsoft Corporation
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             :
Device Model                    :
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Little CMS
Profile ID                      : 0
Profile Description             : GIMP built-in sRGB
Profile Copyright               : Public Domain
Media White Point               : 0.9642 1 0.82491
Chromatic Adaptation            : 1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
Red Matrix Column               : 0.43604 0.22249 0.01392
Blue Matrix Column              : 0.14305 0.06061 0.71393
Green Matrix Column             : 0.38512 0.7169 0.09706
Red Tone Reproduction Curve     : (Binary data 32 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 32 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 32 bytes, use -b option to extract)
Chromaticity Channels           : 3
Chromaticity Colorant           : Unknown
Chromaticity Channel 1          : 0.64 0.33002
Chromaticity Channel 2          : 0.3 0.60001
Chromaticity Channel 3          : 0.15001 0.06
Device Mfg Desc                 : GIMP
Device Model Desc               : sRGB
Background Color                : 255 255 255
Pixels Per Unit X               : 11811
Pixels Per Unit Y               : 11811
Pixel Units                     : meters
Modify Date                     : 2024:01:22 06:12:28
Comment                         : Created with GIMP
Image Size                      : 2992x2000
Megapixels                      : 6.0
```

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.125.7

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=####
      - PGID=####
      - TZ=America/New_York
      - DB_HOSTNAME=x.x.x.x
      - DB_USERNAME=####
      - DB_PASSWORD=####
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=x.x.x.x
      - DB_PORT=#### #optional
      - REDIS_PORT=#### #optional
      - REDIS_PASSWORD= #### #optional
      - MACHINE_LEARNING_HOST=#### #optional
      - MACHINE_LEARNING_PORT=#### #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - /immich/config:/config
      - /FileShare/immich_uploads:/photos
      - /FileShare/Photos:/libraries #optional
    ports:
      - ####
    restart: unless-stopped
    network_mode: bridge
# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - ####
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - ####
    container_name: postgres
    environment:
      POSTGRES_USER: ####
      POSTGRES_PASSWORD: ####
      POSTGRES_DB: immich
    volumes:
      - /immich/data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
```

### Your .env content

```Shell
*
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
In default log level I dont see anything relevant to this file/ others with the issue stated.
```
