### ISSUE TITLE
Albums on mobile (iOS) are created on the immich server but empty even after album sync

### ISSUE THREAD

**Issue by Devirex** [immich-app/immich#16183]
### The bug

I have 8000 synced Items of the iOS device in the album "Recent" (iOS standard). 
When selecting another album in the mobile app to sync it gets created on the server successful but is empty.
It i go to "Backup -> Backup options -> Sync albums -> Sync" there is a loading circle which runs forever but nothing happens. 
Debug log on the immich_server displays the POST call for the /api/albums endpoint which creates the album when selectiung it on the mobile app. 
There is no api call when pressing the "Sync" button in the mobile app.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - backend-net
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: "3.5"
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - backend-net
    restart: always
    healthcheck:
      disable: false
    deploy:
      resources:
        limits:
          cpus: "3.5"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - backend-net
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - backend-net
    restart: always

volumes:
  model-cache:
networks:
  backend-net:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/images
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Sync Recent on the iOS App
2. Wait for it to finish
3. Select another album
4. Sync albums
5. See that album is empty

### Relevant log output

```shell
[Nest] 17  - 02/18/2025, 9:18:47 AM   DEBUG [Api:LoggingInterceptor~b6o23iw8] DELETE /api/albums/bfef8345-1c15-4e3f-a14a-b9b7487a6122 200 10.01ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:18:47 AM   DEBUG [Api:LoggingInterceptor~py6lhn7e] POST /api/auth/validateToken 200 0.66ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:18:51 AM   DEBUG [Api:LoggingInterceptor~xsf240r7] GET /api/server/storage 200 1.19ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:18:51 AM   DEBUG [Api:LoggingInterceptor~ixdte2h9] GET /api/users/me 200 0.87ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:18:51 AM   DEBUG [Api:LoggingInterceptor~hqo29c4b] GET /api/users/me/preferences 200 0.43ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:18:54 AM   DEBUG [Api:LoggingInterceptor~up34klni] POST /api/auth/validateToken 200 0.64ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:19:09 AM   DEBUG [Api:LoggingInterceptor~ed8ej0fj] POST /api/auth/validateToken 200 0.71ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:19:09 AM   DEBUG [Api:LoggingInterceptor~8c8s56jt] GET /api/server/storage 200 0.98ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:19:10 AM   DEBUG [Api:LoggingInterceptor~15v1uo2t] GET /api/assets/device/bb92dce9294fad973b0cdd1c33d229f1a58b65e27da7e60c6b1f19ba980cca39 200 29.34ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:19:11 AM   DEBUG [Api:LoggingInterceptor~84m1zqg2] POST /api/albums 201 20.08ms 127.0.0.1
[Nest] 17  - 02/18/2025, 9:19:11 AM   DEBUG [Api:LoggingInterceptor~8hzu7d6h] GET /api/server/ping 200 0.23ms ::ffff:127.0.0.1
```
