### ISSUE TITLE
Immich shares faulty images if they were edited

### ISSUE THREAD

**Issue by rinurinu** [immich-app/immich#16210]
### The bug

**Steps to reproduce Bug**
Immich Android App: Take a picture. Edit it in immich, specifically rotate it. Save it. Success message appears. Theres a new image.
Open this new image (still in immich app), share it, in share menu select signal. An error appears.

Some digging reveals the edited file is saved to a different folder:
Original is saved in /storage/emulated/0/DCIM/Camera
Edited is saved in /storage/emulated/0/Pictures

I guess Immich doesnt have access to the file it saved, or thinks it saved it somewhere else. Then when trying to share it it comes up with nothing and the next app receives nothing useful.

I'd expect the edited file to overwrite the original (unless prompted otherwise) or at least save it to the same folder. And of course be able to share edited pictures.

At the moment, if you took a picture with the wrong orientation, there's no possibility to rotate and share it with immich, you have to open google photos again for that.

### The OS that Immich Server is running on

ubuntu server 24.10.1 LTS

### Version of Immich Server

v1.123.0

### Version of Immich Mobile App

Latest Android App (from 10.02.2025 I guess)

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    extends:
#      file: hwaccel.transcoding.yml
#      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of U>
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 'SOMEPORT:SOMEPORT'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acc>
#      file: hwaccel.ml.yml
#      service: cuda 
    # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 w>
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

    database:
      container_name: immich_postgres
      image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e>
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
        POSTGRES_INITDB_ARGS: '--data-checksums'
      volumes:
        # Do not edit the next line. If you want to change the database storage location on your system, edit the value o>
        - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
        - ${DB_BACKUP_LOCATION}:/usr/src/db/db-backup-location
      healthcheck:
        test: >-
          pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
          Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
          --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
          echo "checksum failure count is $$Chksum";
          [ "$$Chksum" = '0' ] || exit 1
        interval: 5m
        start_interval: 30s
        start_period: 5m
      command: >-
        postgres
        -c shared_preload_libraries=vectors.so
        -c 'search_path="$$user", public, vectors'
        -c logging_collector=on
        -c max_wal_size=2GB
        -c shared_buffers=512MB
        -c wal_compression=on
      restart: always

  volumes:
    model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variabl>

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
# Folder to put the db dump before backing up
DB_BACKUP_LOCATION=./database-backup


# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia>
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=*******************
DB_DATABASE_NAME=*******************
```

### Reproduction steps

1. Immich Android App: Take a picture. 
2. Edit it in immich, specifically rotate it. 
3. Save it. Success message appears. Theres a new image.
4. Open this new image (still in immich app), share it, in share menu select signal. 
5. An error appears in Signal

### Relevant log output

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/617cd69d-908e-491d-b2b5-623f139d5943)
