### ISSUE TITLE
Failed jobs not reported in the UI

### ISSUE THREAD

**Issue by licryle** [immich-app/immich#16215]
### The bug

Since v1.126.1, the failed jobs are no longer reported in the Jobs UI for me.
They are just silently happening. I see them in the servers logs, but nothing gets displayed in the Jobs UI.

### The OS that Immich Server is running on

RasPIan + ElementaryOS

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/videos:/videos
      - /mnt/photos:/photos
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Start server
2. Configure bogus remote ML server
3. launch a ML job

### Relevant log output

```shell
[Nest] 6  - 02/19/2025, 2:43:41 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://192.168.2.217:3003" failed: fetch failed
[Nest] 6  - 02/19/2025, 2:43:41 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://192.168.2.217:3003" failed: fetch failed
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:38:15)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:56:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:104:27)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Object(2) {
  id: 'c7fbd9ea-d9aa-4681-9697-1cf2f8c1162e',
  source: 'upload'
}
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:38:15)
    at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:47:26)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:240:52)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:148:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:130:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 02/19/2025, 2:43:41 PM   ERROR [Microservices:JobService] Object(2) {
  id: 'c7fbd9ea-d9aa-4681-9697-1cf2f8c1162e',
  source: 'upload'
}
Query failed : {
  durationMs: 5.079476999118924,
  error: Error: write CONNECTION_DESTROYED database:5432
      at Object.execute (/usr/src/app/node_modules/postgres/cjs/src/connection.js:156:35)
      at Query.handler (/usr/src/app/node_modules/postgres/cjs/src/index.js:229:13)
      at Query.handle (/usr/src/app/node_modules/postgres/cjs/src/query.js:140:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
    code: 'CONNECTION_DESTROYED',
    errno: 'CONNECTION_DESTROYED',
    address: [ 'database' ],
    port: [ 5432 ]
  },
  sql: 'with "cte" as (select "asset_faces"."id", "asset_faces"."personId", face_search.embedding <=> $1 as "distance" from "asset_faces" inner join "assets" on "assets"."id" = "asset_faces"."assetId" inner join "face_search" on "face_search"."faceId" = "asset_faces"."id" where "assets"."ownerId" = any($2::uuid[]) and "assets"."deletedAt" is null order by face_search.embedding <=> $3 limit $4) select * from "cte" where "cte"."distance" <= $5',
  params: [
    '[0.4652866, -0.074719965, -0.43557382, -2.0757039, -0.006155506, 0.33857873, 0.44538912, 1.5522541, -0.9451454, -0.3153829, 1.4910874, -0.28889132, -0.234276, 2.1564174, 1.0947546, -0.7662517, 1.1969916, -0.7526362, 0.35557878, 0.6659475, 0.5970803, 0.46836692, -0.46696633, 1.3327273, -0.073552, 1.1580166, -1.0367069, -0.062747285, -0.25584576, -0.7089869, 0.331312, 2.1770205, -0.02453871, -0.25715265, 0.58289313, 1.535429, 1.3766654, 0.38711366, 0.22851866, -0.9677486, 1.5680592, -1.3531561, 0.44648162, -1.6341362, 1.0362071, -0.22133565, 0.94446856, -1.840911, 0.59772956, 0.39494708, 0.065267764, -0.04500293, 1.9813685, -1.5594162, -1.376203, -0.06036231, -0.87750834, -0.0334756, -0.6245589, -1.8171649, 0.76720876, -0.81323254, -0.69532716, -1.4999127, 1.7184564, 1.5246929, -0.87694126, -0.7245487, 1.5735712, 1.7814275, -0.64009094, 0.32978183, 1.0929987, -0.6626482, -1.7513537, -0.40914252, -0.05090657, -0.09392206, -2.5857887, -0.019401371, 2.3636527, 2.0094545, 0.36453056, 0.7137281, -0.47597337, -2.0221088, 0.27529258, -1.5121351, -0.84136146, 1.144513, 1.5414867, 0.77590376, -0.90221596, -0.59794956, 0.4113668, 0.1793949, 0.76486945, -0.3036774, 0.29455674, -0.94171727, -0.6380215, -1.106572, 1.7381903, 0.14959261, 0.958907, 1.744387, -0.25663817, 1.151472, 2.1726875, 2.377908, -0.65143913, 1.0692852, -2.1875408, 0.6310904, 0.20176302, -1.3587949, -0.8545687, 2.1123388, -2.0960472, 0.8826807, -0.48126855, -0.17151415, -0.53508914, 0.76012063, -0.20471813, 0.73679996, 0.042328373, 2.2918546, -0.63469034, 0.48255703, 0.87362045, -0.28113773, -0.63671976, 1.0774547, -0.038666684, -0.06625033, -2.4695373, -1.248762, -0.26047713, 0.88428277, 0.8588763, -1.6432279, 1.3438826, -0.06390993, 0.4198477, 1.8437611, -0.5634798, -1.7412633, -1.838879, -0.7545315, 1.5027257, 0.13429856, -0.17437565, 0.8004119, 1.7390156, 1.6395636, -0.18667938, -0.22044548, 0.05807309, 0.46965536, -2.356098, 1.9571522, -1.312718, 0.14620714, -0.9211849, 0.57816297, 0.2998605, -1.1843914, 1.9383495, 0.72738284, -1.1533883, -3.5220222, 0.587199, 1.2962968, -1.1854699, 0.20310104, 0.58892083, 1.1293483, -0.95170146, -1.2851702, 0.72974986, -1.2088946, 0.3269023, -0.15029512, -1.0821544, -0.37184674, -0.41597387, -0.0820696, 0.12804352, -0.742989, 0.15349446, 1.2746637, 2.2399492, 1.5069021, -1.3943844, -0.6676409, -0.15324022, -0.36313528, 0.5574756, -0.8640217, -0.16240728, -2.1146958, 0.6542311, 0.04987888, -0.18922746, 0.39446732, -0.41081712, 0.4722517, -1.7793039, -0.7020821, 0.7492231, 0.725211, 0.62989795, 1.2773223, -0.45644975, 0.8189671, 0.0023894012, 1.7441987, 0.57226855, -0.6726271, -0.7281414, -2.103989, -2.0639987, 1.2735475, -2.1091263, 0.034836706, 2.6719089, -0.62034124, 0.92969435, 1.0920153, 0.8796908, -1.7824627, -1.7492478, -0.14636132, 0.8331858, 1.6240242, 1.0365918, 1.8648173, 2.0948994, -0.7707634, 1.7817327, 1.6794834, -0.36165065, 0.193428, -0.8866241, -2.660523, 0.82118, 0.9150586, -0.79674613, 1.6530731, -1.6302242, 1.0793873, -0.9780754, -0.23717037, 0.5884197, -1.9282416, -0.5367032, -0.79544604, -0.1315023, 1.7414926, -0.7759566, -0.9904616, 0.83949256, -1.8679335, 1.1949469, -0.9250802, 0.32539397, -0.43584588, 0.8896206, -1.3837489, 2.2673929, 1.2989005, -0.7230908, -0.15627533, -0.86176544, 1.821836, -1.6310921, 0.5470575, 0.20617205, -0.6282078, -0.475434, -1.519616, -0.23740886, 1.1643673, 0.12674724, 0.453519, -0.39049435, -0.88951564, -0.14839189, 0.051362686, -0.21681495, 0.8121807, 1.7750483, 0.74938655, -0.1223368, -3.260095, 0.6506827, 0.08634487, -0.206522, -0.8038017, -0.08430341, -0.6251509, -0.9866978, 0.41164932, -1.4421546, -0.19376081, 2.040334, 2.9539547, 0.13809381, 1.5156132, 0.33843395, -0.48057297, 0.797439, -0.8875822, 1.2229389, -0.43633783, 2.5984995, -3.2181942, -1.8443285, -1.1227268, 0.06739183, -0.42171657, -0.07691527, 1.6703712, -2.3950799, 0.87138116, 0.12339215, 1.942229, 0.57583284, 0.1101347, -1.1637383, 0.08867014, -0.04613988, -0.71139735, 0.9719322, 1.1689882, 0.44944537, -0.9615987, 0.5313864, -1.2716353, 0.4689219, 1.0707183, 1.9192188, 0.56671566, -1.9214691, 0.35384873, 0.35823694, 1.6461557, 1.6562854, -2.5547059, 1.0587735, 0.7192484, 1.8092622, 1.1959006, -0.7735014, -1.5441909, 0.69451743, -1.1132009, -1.7025166, 0.93055093, 0.8826847, 0.3110134, 1.2040839, 0.82321435, 0.786091, -1.3367343, 1.3027178, -1.3337002, -1.4391177, 0.64968926, -1.1350143, -1.0051868, 0.18602663, 0.36247814, -1.3023798, -0.4965431, -0.8540612, -0.6966992, 0.4484934, 1.0077778, 0.40938878, 1.5360612, -0.6936574, 0.28560647, -0.451872, -0.45049083, 0.80240464, -1.454942, -0.11688423, -0.84185004, 0.61467236, 0.20096467, -0.80238926, -1.3034075, 2.252065, 0.6838388, 0.73616093, -0.93416095, 1.050968, 0.884215, -0.54898566, 0.015664294, -0.49478585, -0.97138274, 1.5712566, -1.1097984, -0.6570895, -1.3638076, 0.040054843, 0.30249906, -1.674371, -0.43201342, -1.3592114, 0.17712305, 2.4117975, -0.017187595, 0.5615811, -0.3067689, 1.2792495, 0.44480807, 0.6066823, 1.0478498, -0.5453564, 1.3631608, 0.53961915, -0.36470413, -0.52146375, 0.28799203, -0.52115405, 1.0540729, 0.9966775, -0.62210965, 2.0156002, 1.8694099, 0.6205024, -0.11824955, -0.09562084, 0.5344934, 0.49404028, 0.86111593, 0.0024100244, 0.7056496, 0.010611691, -1.6250627, -1.0980494, 0.6498485, 0.43907964, 0.54607314, -0.10442185, 0.9685036, 0.8249581, -0.6925303, -1.2273462, 1.1007866, -0.8339876, -0.41569236, -2.178211, -0.14224195, -0.42380178, 1.4018862, 0.54851395, -0.32793477, -1.7826487, -1.011199, 0.4577486, 0.19519119, 0.111533344, -2.1419284, -0.8059742, 0.21455699, -0.31509534, 0.45276025, -0.1837812, 1.5918353, -0.13743533, 1.1036242, -0.11940483, 1.7154105, 0.8462591, 1.1559192, -1.9793508, 0.098804355, -0.039967105, 0.55647904, -0.6554509, 0.6110082, -0.73800963, -2.8941593, -1.2505543, 0.30286986, -1.1762133, -0.38090584, -0.11321305, 0.10818289, -2.1638663, 2.1331768, 0.45802125, -0.26214972, 0.90817595, -0.40233415, 1.7813402, -1.5549746, -0.8587821, 0.1157864, -1.495181, -0.5650546, -1.5044831, -0.45834267, 0.18500903, -1.694574, -1.2439449, -0.49236745]',
    '{fa8c4dd0-169c-4b67-b9d4-e1419ef525f1}',
    '[0.4652866, -0.074719965, -0.43557382, -2.0757039, -0.006155506, 0.33857873, 0.44538912, 1.5522541, -0.9451454, -0.3153829, 1.4910874, -0.28889132, -0.234276, 2.1564174, 1.0947546, -0.7662517, 1.1969916, -0.7526362, 0.35557878, 0.6659475, 0.5970803, 0.46836692, -0.46696633, 1.3327273, -0.073552, 1.1580166, -1.0367069, -0.062747285, -0.25584576, -0.7089869, 0.331312, 2.1770205, -0.02453871, -0.25715265, 0.58289313, 1.535429, 1.3766654, 0.38711366, 0.22851866, -0.9677486, 1.5680592, -1.3531561, 0.44648162, -1.6341362, 1.0362071, -0.22133565, 0.94446856, -1.840911, 0.59772956, 0.39494708, 0.065267764, -0.04500293, 1.9813685, -1.5594162, -1.376203, -0.06036231, -0.87750834, -0.0334756, -0.6245589, -1.8171649, 0.76720876, -0.81323254, -0.69532716, -1.4999127, 1.7184564, 1.5246929, -0.87694126, -0.7245487, 1.5735712, 1.7814275, -0.64009094, 0.32978183, 1.0929987, -0.6626482, -1.7513537, -0.40914252, -0.05090657, -0.09392206, -2.5857887, -0.019401371, 2.3636527, 2.0094545, 0.36453056, 0.7137281, -0.47597337, -2.0221088, 0.27529258, -1.5121351, -0.84136146, 1.144513, 1.5414867, 0.77590376, -0.90221596, -0.59794956, 0.4113668, 0.1793949, 0.76486945, -0.3036774, 0.29455674, -0.94171727, -0.6380215, -1.106572, 1.7381903, 0.14959261, 0.958907, 1.744387, -0.25663817, 1.151472, 2.1726875, 2.377908, -0.65143913, 1.0692852, -2.1875408, 0.6310904, 0.20176302, -1.3587949, -0.8545687, 2.1123388, -2.0960472, 0.8826807, -0.48126855, -0.17151415, -0.53508914, 0.76012063, -0.20471813, 0.73679996, 0.042328373, 2.2918546, -0.63469034, 0.48255703, 0.87362045, -0.28113773, -0.63671976, 1.0774547, -0.038666684, -0.06625033, -2.4695373, -1.248762, -0.26047713, 0.88428277, 0.8588763, -1.6432279, 1.3438826, -0.06390993, 0.4198477, 1.8437611, -0.5634798, -1.7412633, -1.838879, -0.7545315, 1.5027257, 0.13429856, -0.17437565, 0.8004119, 1.7390156, 1.6395636, -0.18667938, -0.22044548, 0.05807309, 0.46965536, -2.356098, 1.9571522, -1.312718, 0.14620714, -0.9211849, 0.57816297, 0.2998605, -1.1843914, 1.9383495, 0.72738284, -1.1533883, -3.5220222, 0.587199, 1.2962968, -1.1854699, 0.20310104, 0.58892083, 1.1293483, -0.95170146, -1.2851702, 0.72974986, -1.2088946, 0.3269023, -0.15029512, -1.0821544, -0.37184674, -0.41597387, -0.0820696, 0.12804352, -0.742989, 0.15349446, 1.2746637, 2.2399492, 1.5069021, -1.3943844, -0.6676409, -0.15324022, -0.36313528, 0.5574756, -0.8640217, -0.16240728, -2.1146958, 0.6542311, 0.04987888, -0.18922746, 0.39446732, -0.41081712, 0.4722517, -1.7793039, -0.7020821, 0.7492231, 0.725211, 0.62989795, 1.2773223, -0.45644975, 0.8189671, 0.0023894012, 1.7441987, 0.57226855, -0.6726271, -0.7281414, -2.103989, -2.0639987, 1.2735475, -2.1091263, 0.034836706, 2.6719089, -0.62034124, 0.92969435, 1.0920153, 0.8796908, -1.7824627, -1.7492478, -0.14636132, 0.8331858, 1.6240242, 1.0365918, 1.8648173, 2.0948994, -0.7707634, 1.7817327, 1.6794834, -0.36165065, 0.193428, -0.8866241, -2.660523, 0.82118, 0.9150586, -0.79674613, 1.6530731, -1.6302242, 1.0793873, -0.9780754, -0.23717037, 0.5884197, -1.9282416, -0.5367032, -0.79544604, -0.1315023, 1.7414926, -0.7759566, -0.9904616, 0.83949256, -1.8679335, 1.1949469, -0.9250802, 0.32539397, -0.43584588, 0.8896206, -1.3837489, 2.2673929, 1.2989005, -0.7230908, -0.15627533, -0.86176544, 1.821836, -1.6310921, 0.5470575, 0.20617205, -0.6282078, -0.475434, -1.519616, -0.23740886, 1.1643673, 0.12674724, 0.453519, -0.39049435, -0.88951564, -0.14839189, 0.051362686, -0.21681495, 0.8121807, 1.7750483, 0.74938655, -0.1223368, -3.260095, 0.6506827, 0.08634487, -0.206522, -0.8038017, -0.08430341, -0.6251509, -0.9866978, 0.41164932, -1.4421546, -0.19376081, 2.040334, 2.9539547, 0.13809381, 1.5156132, 0.33843395, -0.48057297, 0.797439, -0.8875822, 1.2229389, -0.43633783, 2.5984995, -3.2181942, -1.8443285, -1.1227268, 0.06739183, -0.42171657, -0.07691527, 1.6703712, -2.3950799, 0.87138116, 0.12339215, 1.942229, 0.57583284, 0.1101347, -1.1637383, 0.08867014, -0.04613988, -0.71139735, 0.9719322, 1.1689882, 0.44944537, -0.9615987, 0.5313864, -1.2716353, 0.4689219, 1.0707183, 1.9192188, 0.56671566, -1.9214691, 0.35384873, 0.35823694, 1.6461557, 1.6562854, -2.5547059, 1.0587735, 0.7192484, 1.8092622, 1.1959006, -0.7735014, -1.5441909, 0.69451743, -1.1132009, -1.7025166, 0.93055093, 0.8826847, 0.3110134, 1.2040839, 0.82321435, 0.786091, -1.3367343, 1.3027178, -1.3337002, -1.4391177, 0.64968926, -1.1350143, -1.0051868, 0.18602663, 0.36247814, -1.3023798, -0.4965431, -0.8540612, -0.6966992, 0.4484934, 1.0077778, 0.40938878, 1.5360612, -0.6936574, 0.28560647, -0.451872, -0.45049083, 0.80240464, -1.454942, -0.11688423, -0.84185004, 0.61467236, 0.20096467, -0.80238926, -1.3034075, 2.252065, 0.6838388, 0.73616093, -0.93416095, 1.050968, 0.884215, -0.54898566, 0.015664294, -0.49478585, -0.97138274, 1.5712566, -1.1097984, -0.6570895, -1.3638076, 0.040054843, 0.30249906, -1.674371, -0.43201342, -1.3592114, 0.17712305, 2.4117975, -0.017187595, 0.5615811, -0.3067689, 1.2792495, 0.44480807, 0.6066823, 1.0478498, -0.5453564, 1.3631608, 0.53961915, -0.36470413, -0.52146375, 0.28799203, -0.52115405, 1.0540729, 0.9966775, -0.62210965, 2.0156002, 1.8694099, 0.6205024, -0.11824955, -0.09562084, 0.5344934, 0.49404028, 0.86111593, 0.0024100244, 0.7056496, 0.010611691, -1.6250627, -1.0980494, 0.6498485, 0.43907964, 0.54607314, -0.10442185, 0.9685036, 0.8249581, -0.6925303, -1.2273462, 1.1007866, -0.8339876, -0.41569236, -2.178211, -0.14224195, -0.42380178, 1.4018862, 0.54851395, -0.32793477, -1.7826487, -1.011199, 0.4577486, 0.19519119, 0.111533344, -2.1419284, -0.8059742, 0.21455699, -0.31509534, 0.45276025, -0.1837812, 1.5918353, -0.13743533, 1.1036242, -0.11940483, 1.7154105, 0.8462591, 1.1559192, -1.9793508, 0.098804355, -0.039967105, 0.55647904, -0.6554509, 0.6110082, -0.73800963, -2.8941593, -1.2505543, 0.30286986, -1.1762133, -0.38090584, -0.11321305, 0.10818289, -2.1638663, 2.1331768, 0.45802125, -0.26214972, 0.90817595, -0.40233415, 1.7813402, -1.5549746, -0.8587821, 0.1157864, -1.495181, -0.5650546, -1.5044831, -0.45834267, 0.18500903, -1.694574, -1.2439449, -0.49236745]',
    3,
    0.5
  ]
}
[Nest] 6  - 02/19/2025, 2:44:44 PM   ERROR [Microservices:JobService] Unable to run job handler (facialRecognition/facial-recognition): Error: write CONNECTION_DESTROYED database:5432
[Nest] 6  - 02/19/2025, 2:44:44 PM   ERROR [Microservices:JobService] Error: write CONNECTION_DESTROYED database:5432
    at Object.execute (/usr/src/app/node_modules/postgres/cjs/src/connection.js:156:35)
    at Query.handler (/usr/src/app/node_modules/postgres/cjs/src/index.js:229:13)
    at Query.handle (/usr/src/app/node_modules/postgres/cjs/src/query.js:140:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[Nest] 6  - 02/19/2025, 2:44:44 PM   ERROR [Microservices:JobService] Object(2) {
  id: 'cf33c098-0343-46a5-aab9-96ed7a40ec3f',
  deferred: false
}
```
