### ISSUE TITLE
Existing date of birth of a person is not displayed in the update dialog

### ISSUE THREAD

**Issue by kho-git** [immich-app/immich#16221]
### The bug

If you select the “Set date of birth” option in the “People” window, no current date of birth is displayed in the dialog, although one is available in the database.

### The OS that Immich Server is running on

Ubuntu and RasPi

### Version of Immich Server

v1.126.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      # v1.118 :3001 -> :2283
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PWD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin


  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always


volumes:
  model-cache:
  pgadmin-data:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=***
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
PGA_USERNAME=***
PGA_PWD=***
TZ=Europe/Berlin
IMMICH_API_KEY=***
IMMICH_URL=DELLE:2283
```

### Reproduction steps

1. Start Immich
2. Go to /people
3. Go to '...'
4. Select the “Set date of birth” 
5. A dialog with 'tt.mm.jjjj' is displayed, instead of '28.11.1887' (German formatting)
...

### Relevant log output

```shell

```

### Additional information

Database result of

SELECT * FROM public.person
where "birthDate" is not null and "name" like 'Alex%'
ORDER BY name ASC 

"id","createdAt","updatedAt","ownerId","name","thumbnailPath","isHidden","birthDate","faceAssetId","isFavorite","color"
"fe93d295-ad63-4763-bc28-fce00ce90f89","2024-09-20 10:55:24.776482+00","2025-01-28 21:32:32.827636+00","1464281f-b277-438a-9c3b-ab7c804de8a9","Alexander Folkers †1925 [813]","upload/thumbs/1464281f-b277-438a-9c3b-ab7c804de8a9/fe/93/fe93d295-ad63-4763-bc28-fce00ce90f89.jpeg",False,"1887-11-28","5cdfed19-fe95-475b-8fa8-17c4bca9467b",False,NULL

![Image](https://github.com/user-attachments/assets/b3c42f10-914f-4cd0-9a55-2d5aa6ba2909)
