### ISSUE TITLE
Wrong order when stacking photos.

### ISSUE THREAD

**Issue by PaulEins** [immich-app/immich#16250]
### The bug

Stacking photos messes up the order. But why? It's not because of the order in which they are selected.

Subsequent changes are also not possible.

And they are not sorted by date either. I have not recognized the logic behind this.

With a recipe where I have noted every step, I can't look it up because then a completely different photo appears -.-

![Image](https://github.com/user-attachments/assets/1226e0ba-415d-4926-897f-0eee827f87ab)

### The OS that Immich Server is running on

Synology Docker

### Version of Immich Server

new

### Version of Immich Mobile App

new

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume2/docker2/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume2/docker2/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=newimmich88pw
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume2/docker2/immich/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    devices: # selber hinzugefügt wegen iGPu, erstmal weglassen.
      - /dev/dri:/dev/dri # selber hinzugefügt wegen iGPu , sonst loeschen
    group_add: # das auch neu, soll mit dazu zu dem darüberliegenden.
      - 937  # das gehört auch dazu.
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume2/docker2/immich/upload:/usr/src/app/upload:rw
      - /volume2/docker2/immich/cache:/cache:rw
      - /volume2/docker2/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
i dont have
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
