### ISSUE TITLE
"Error while getting remote assets" Android mobile app

### ISSUE THREAD

**Issue by MrZander** [immich-app/immich#16286]
### The bug

Freshly installed mobile app, none of the remote assets will load, only the local assets are showing up in the main Photos page.

I can still view photos in shared albums.

Search does not work either, gives the same error.
` Error while getting remote assets | Null check operator used on a null value`

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.126.1

### Version of Immich Mobile App

1.126.1 build.184

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
$ cat docker-compose.yml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

1. Install app
2. Login
3. Remote assets not visible in Photos

### Relevant log output

```shell
2025-02-23 21:25:30.893609 | SEVERE   | AssetService         | Error while getting remote assets | Null check operator used on a null value |
#0      AssetResponseDto.fromJson (package:openapi/model/asset_response_dto.dart:292)
#1      ApiClient.fromJson (package:openapi/api_client.dart:260)
#2      ApiClient.fromJson.<anonymous closure> (package:openapi/api_client.dart:657)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:163)
#6      new _List.of (dart:core-patch/array.dart:128)
#7      new List.of (dart:core-patch/array_patch.dart:39)
#8      ListIterable.toList (dart:_internal/iterable.dart:224)
#9      ApiClient.fromJson (package:openapi/api_client.dart:658)
#10     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#11     SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:108)
<asynchronous suspension>
#12     AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:145)
<asynchronous suspension>
#13     SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:267)
<asynchronous suspension>
#14     SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:257)
<asynchronous suspension>
#15     SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:92)
<asynchronous suspension>
#16     AsyncMutex.run.<anonymous closure> (package:immich_mobile/utils/async_mutex.dart:15)
<asynchronous suspension>

2025-02-23 21:25:24.150948 | SEVERE   | MemoryService        | Cannot get memories | ApiException 500: {"message":"Failed to get memory lane","error":"Internal Server Error","statusCode":500,"correlationId":"942cramp"} |
#0      AssetsApi.getMemoryLane (package:openapi/api/assets_api.dart:449)
<asynchronous suspension>
#1      MemoryService.getMemoryLane (package:immich_mobile/services/memory.service.dart:29)
<asynchronous suspension>
#2      memoryFutureProvider.<anonymous closure> (package:immich_mobile/providers/memory.provider.dart:9)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>

2025-02-23 21:13:04.034722 | SEVERE   | MemoryService        | Cannot get memories | ApiException 500: {"message":"Failed to get memory lane","error":"Internal Server Error","statusCode":500,"correlationId":"8ppllvup"} |
#0      AssetsApi.getMemoryLane (package:openapi/api/assets_api.dart:449)
<asynchronous suspension>
#1      MemoryService.getMemoryLane (package:immich_mobile/services/memory.service.dart:29)
<asynchronous suspension>
#2      memoryFutureProvider.<anonymous closure> (package:immich_mobile/providers/memory.provider.dart:9)
<asynchronous suspension>
#3      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:348)
<asynchronous suspension>
```
