### ISSUE TITLE
Time-based memories missing on web since v1.127.0

### ISSUE THREAD

**Issue by agross** [immich-app/immich#16357]
### The bug

Memories do not show up. They did before upgrading to v1.127.0 from v1.126.1.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

unrelated

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/usr/src/app/upload
      - ./immich-config.json:/immich-config.json:ro
    env_file:
      - .env
    ports:
      - 127.0.0.1:2283:2283
    depends_on:
      - redis
      - db

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ml-model-cache:/cache
    env_file:
      - .env

  redis:
    image: redis:alpine
    volumes:
      - ./redis:/data
    healthcheck:
      test: redis-cli ping | grep -xq PONG
      start_period: 5s
      interval: 5s

  db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: --locale-provider=icu --icu-locale=de-DE --data-checksums
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: >-
        psql --username="$$POSTGRES_USER" --dbname="$$POSTGRES_DB" --command='SELECT 1' || exit 1;
        failures="$$(psql --username="$$POSTGRES_USER" --dbname="$$POSTGRES_DB" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "Checksum failure count is $$failures";
        [ "$$failures" = 0 ] || exit 1
      start_interval: 5s
      start_period: 1m
      interval: 5m

volumes:
  db-data:
  ml-model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at
# https://immich.app/docs/install/environment-variables

IMMICH_CONFIG_FILE=/immich-config.json

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

DB_HOSTNAME=db
DB_DATABASE_NAME=immich
DB_USERNAME=immich
DB_PASSWORD=immich

TZ=Europe/Berlin
```

### Reproduction steps

1. Upgrade to v1.127.0

### Relevant log output

```shell

```

### Additional information

<img width="595" alt="Image" src="https://github.com/user-attachments/assets/b3a48ea7-e2a5-4027-bb6a-ccde3c33230b" />

Time-based memories are enabled for my account. I tried turning that option off and on again™ 

<img width="711" alt="Image" src="https://github.com/user-attachments/assets/ef605387-5853-4f6a-8f28-8430aeb475d1" />
