### ISSUE TITLE
Duplicates reappear after choosing "Keep All"

### ISSUE THREAD

**Issue by wwhite59** [immich-app/immich#16359]
### The bug

Duplicates reappear after choosing "Keep All" and reloading the "Review Duplicates" utility

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

1.127.0

### Version of Immich Mobile App

1.127.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich0

services:
  immich-server:
    container_name: immich_server0
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    user: "${MY_PUID}:${MY_PGID}"
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      #- /etc/localtime:/etc/localtime:ro
    networks: 
     - immich_network
    dns:
     - 172.20.0.5
    env_file:
      - immich0.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning0
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    user: "${MY_PUID}:${MY_PGID}"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/immich0/model-cache:/cache
    networks: 
     - immich_network
    dns:
     - 172.20.0.5
    env_file:
      - immich0.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis0
    image: docker.io/redis:7.4.1-alpine
    # docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    user: "${MY_PUID}:${MY_PGID}"
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/immich0/redis-data:/data
    networks: 
     - immich_network
    dns:
     - 172.20.0.5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres0
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    user: "${MY_PUID}:${MY_PGID}"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks: 
     - immich_network
    dns:
     - 172.20.0.5
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: unless-stopped
networks:
  immich_network:
    name: bridge0
    driver: bridge
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-7efde501-e730-44bf-8702-af3d5872713c/immich_library
# The location where your database files are stored
DB_DATA_LOCATION=CHANGE_TO_COMPOSE_DATA_PATH/immich0/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.127.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=ZunxjN3P762RTPWAaqJiAwQavjzW

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open "Utilities" > "Review Duplicates"
2. Choose "Keep All"
3. Next time you open "Review Duplicates" the same duplicates are being shown

### Relevant log output

```shell

```
