### ISSUE TITLE
Manually tagged people removed when faces refreshed

### ISSUE THREAD

**Issue by Vyerni** [immich-app/immich#16374]
### The bug

When you manually assign a face to a photo, and you run "Refresh Faces" within that photo, the list of people reverts back to the automatically applied faces.

This is all on the web. I haven't used the latest release on the phone yet

### The OS that Immich Server is running on

TrueNAS Scale 24.10.2

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

v1.126.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:?err}
    container_name: immich
    env_file: .env
    volumes:
      - ${UPLOAD_LOCATION:?err}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - immich_redis
      - immich_database
      - immich_machine_learning
    healthcheck:
      disable: false
    restart: unless-stopped

  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:?err}
    container_name: immich_machine_learning
    env_file: .env
    volumes:
      - ./cache:/cache
    healthcheck:
      disable: false
    restart: unless-stopped

  immich_redis:
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    container_name: immich_redis
    volumes:
      - ./redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  immich_database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich_database
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?err}
      POSTGRES_USER: ${DB_USERNAME:?err}
      POSTGRES_DB: ${DB_DATABASE_NAME:?err}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        "postgres",
        "-c",
        "shared_preload_libraries=vectors.so",
        "-c",
        'search_path="$$user", public, vectors',
        "-c",
        "logging_collector=on",
        "-c",
        "max_wal_size=2GB",
        "-c",
        "shared_buffers=512MB",
        "-c",
        "wal_compression=on",
      ]
    restart: unless-stopped
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=Super_Secret_Password
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# This is the location where uploaded files are stored.
UPLOAD_LOCATION=/mnt/Data

TZ=Australia/Sydney

IMMICH_VERSION=v1.127.0
```

### Reproduction steps

1. Manually tag a person in a photo
2. Select "Refresh Faces"
3. Notice that the manually added people in the people list for that photo revert back to the originally automatically applied people

### Relevant log output

```shell

```
