### ISSUE TITLE
Manually adding a face incorrectly sets sourceType "machine-learning"

### ISSUE THREAD

**Issue by dfyx** [immich-app/immich#16379]
### The bug

When manually adding a face via the mechanism introduced in #7301 and #16062, the face's `sourceType` is incorrectly set to "machine-learning". It should be "manual".

The `createFace` API endpoint currently doesn't expose the `sourceType` field. I'm not sure if the field should be added or if all faces created via the API should be marked as "manual".

### The OS that Immich Server is running on

Ubuntu 24.04.1 (via official docker image)

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

not applicable

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /tank/Fotos:/tank/Fotos
    env_file:
      - .env
    networks:
      - traefik
      - default
    healthcheck:
      disable: false
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.immich.rule: 'Host(`<redacted>`)'
        traefik.http.services.immich.loadbalancer.server.port: 2283
      placement:
        constraints:
          - node.labels.storage.tank == true

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/tank/immich/uploads
# The location where your database files are stored
DB_DATA_LOCATION=/tank/immich/database

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.127.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Manually add a face to a photo through the web UI
2. Get the photo's metadata from the API, eg. `https://immich.example.com/api/assets/772549f1-1ee3-4b5c-9885-88f20407ec1c`
3. Notice, that the face has `"sourceType": "machine-learning"`

### Relevant log output

```shell

```

### Additional information

Full asset data, slightly redacted. One face was actually detected by machine learning, the other was added manually:

```json
{
    "id": "772549f1-1ee3-4b5c-9885-88f20407ec1c",
    "deviceAssetId": "IMG_5803.JPG",
    "ownerId": "0bade9f2-765a-43a3-b62f-4e816b3b61e1",
    "owner": {
        "id": "0bade9f2-765a-43a3-b62f-4e816b3b61e1",
        "email": "dfyx@<redacted>",
        "name": "DFYX",
        "profileImagePath": "",
        "avatarColor": "amber",
        "profileChangedAt": "2024-09-30T12:42:22.072778+00:00"
    },
    "deviceId": "Library Import",
    "libraryId": "f624bf58-e94f-443a-8297-c4a7509ac85d",
    "type": "IMAGE",
    "originalPath": "/tank/Fotos/<redacted>/IMG_5803.JPG",
    "originalFileName": "IMG_5803.JPG",
    "originalMimeType": "image/jpeg",
    "thumbhash": "DggODYKmh2aPeXiJd5dniHJ/KPV3",
    "fileCreatedAt": "2024-12-24T19:22:54.090Z",
    "fileModifiedAt": "2024-12-24T20:22:55.000Z",
    "localDateTime": "2024-12-24T21:22:54.090Z",
    "updatedAt": "2025-02-25T10:44:17.394Z",
    "isFavorite": false,
    "isArchived": false,
    "isTrashed": false,
    "duration": "0:00:00.00000",
    "exifInfo": {
        "make": "Canon",
        "model": "Canon EOS 6D Mark II",
        "exifImageWidth": 6240,
        "exifImageHeight": 4160,
        "fileSizeInByte": 5172983,
        "orientation": "1",
        "dateTimeOriginal": "2024-12-24T19:22:54.09+00:00",
        "modifyDate": "2024-12-24T19:22:54.09+00:00",
        "timeZone": "Europe/Berlin",
        "lensModel": "EF28-70mm f/2.8L USM",
        "fNumber": 2.8,
        "focalLength": 47,
        "iso": 400,
        "exposureTime": "1/180",
        "latitude": <redacted>,
        "longitude":<redacted>,
        "city": "<redacted>",
        "state": "<redacted>",
        "country": "Germany",
        "description": "",
        "projectionType": null,
        "rating": 0
    },
    "livePhotoVideoId": null,
    "tags": [],
    "people": [
        {
            "id": "0ac0b591-fc6f-4870-b61b-3c0386cca290",
            "name": "<added manually>",
            "birthDate": null,
            "thumbnailPath": "upload/thumbs/0bade9f2-765a-43a3-b62f-4e816b3b61e1/0a/c0/0ac0b591-fc6f-4870-b61b-3c0386cca290.jpeg",
            "isHidden": false,
            "isFavorite": false,
            "updatedAt": "2025-02-27T10:19:21.108642+00:00",
            "faces": [
                {
                    "id": "9fa8f24a-1db1-48fd-9038-8110ab32492c",
                    "imageHeight": 1440,
                    "imageWidth": 2160,
                    "boundingBoxX1": 350,
                    "boundingBoxX2": 774,
                    "boundingBoxY1": 321,
                    "boundingBoxY2": 633,
                    "sourceType": "machine-learning"
                }
            ]
        },
        {
            "id": "1aca0f2c-e6aa-419a-9853-b402310e5b2c",
            "name": "<detected through machine learning>",
            "birthDate": null,
            "thumbnailPath": "upload/thumbs/0bade9f2-765a-43a3-b62f-4e816b3b61e1/1a/ca/1aca0f2c-e6aa-419a-9853-b402310e5b2c.jpeg",
            "isHidden": false,
            "isFavorite": false,
            "updatedAt": "2024-09-18T07:19:43.469844+00:00",
            "faces": [
                {
                    "id": "1deb7eda-508e-4807-8fc5-e491e7b08f2a",
                    "imageHeight": 1440,
                    "imageWidth": 2160,
                    "boundingBoxX1": 758,
                    "boundingBoxX2": 1036,
                    "boundingBoxY1": 285,
                    "boundingBoxY2": 674,
                    "sourceType": "machine-learning"
                }
            ]
        }
    ],
    "unassignedFaces": [],
    "checksum": "yY196T4KX4AI5aa+WqkBzkfGIn8=",
    "stack": {
        "id": "4694a887-68be-4a47-95b9-22a9f0e99633",
        "primaryAssetId": "1a81ce09-bbc0-47d0-a567-e54f15558616",
        "assetCount": 2
    },
    "isOffline": false,
    "hasMetadata": true,
    "duplicateId": null,
    "resized": true
}
```
