### ISSUE TITLE
Person Tagging - missing person preview

### ISSUE THREAD

**Issue by yayaasd** [immich-app/immich#16372]
### The bug

I am facing issues with preview pictures of people.
resulting in:

![Image](https://github.com/user-attachments/assets/662ba454-a29a-4c94-bb41-ae11d23e1e4d)

I did already re-generate the preview's but still not resulting in a solution.
Any Ideas how to fix this? 

### The OS that Immich Server is running on

Docker on truenas

### Version of Immich Server

 v1.127.0

### Version of Immich Mobile App

 v1.127.0 build 195

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    environment:
      - TZ=Europe/Zurich
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - MACHINE_LEARNING_WORKERS=1
      - IMMICH_TRUSTED_PROXIES=10.1.1.1
      - NODE_OPTIONS=--max-old-space-size=8192
    volumes:
      - /mnt/Data/Photo/.immich:/usr/src/app/upload:rw
      - /mnt/Data/Photo/:/mnt/media/photos:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
empty
```

### Reproduction steps

1. click on People
2. see missing preview picture

### Relevant log output

```shell
checked docker logs immich_server --> no errors see here.
any other place to check?
```
