### ISSUE TITLE
When deleting a person from a photo, the person gallery doesn't remove the photo

### ISSUE THREAD

**Issue by mstewart14** [immich-app/immich#16402]
### The bug

Using the latest toys I found the system had labelled the brother of one of my other people as this other person.  I don't have a person for the brother and they look so much alike the system isn't providing a separate face for me... so I've deleted the recognition of the bother altogether.  However there were 25 assets before for this person and after deleting 13 images of the brother... there are still 25 assets.  The very same ones in fact.  

### The OS that Immich Server is running on

Docker on Debian (on proxmox)

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

v1.26.1 build 184

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-server.rule=Host(`<url>`)
      - traefik.docker.network=proxy
      - traefik.http.services.immich-server.loadbalancer.server.port=2283
      - traefik.http.routers.immich-server.tls.certresolver=<resolvername>
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immichproxy

    environment:
      - TZ=America/Vancouver
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    networks:
      - immichproxy
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: tiredofit/redis:7  # redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    networks:
      - immichproxy
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - immichproxy
    restart: always

volumes:
  model-cache:

networks:
  immichproxy:
    name: proxy
    external: true
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<pwd>

# timezone setting
TZ=America/Vancouver

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=<username>
DB_DATABASE_NAME=<dbname>

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open a "person" and open several images
2. edit "people" and hit the delete button on the image of the person you want to remove from this image (small red trashcan button)
3. click done or move on to the next image
4. Close this person gallery and open it again... note the number of assets doesn't change, nor do the chosen images.  This person is still "associated" with ALL the images as they were originally

### Relevant log output

```shell

```

### Additional information

This is a very awesome feature... once it's working I will be very happy... 
One thing missing which might be a feature request... in the case where the system is unable to distinguish well between 2 related individuals, can you give me the power to add a whole new person, by choosing THIS image to create a new person from this thumbnail?  After I delete the connection to the "wrong" person for example, then this person goes back to being "Unassigned" and from there I can make a "new" person?  I'll guess this might be a gnarly mess but hopefully you get the idea... It would be awesome if it was possible.
