### ISSUE TITLE
The page for adding photos to the album cannot be navigated back using gestures

### ISSUE THREAD

**Issue by ExceptionsOccur** [immich-app/immich#16409]
### The bug

After updating to version 1.127, the album's add photo interface cannot be navigated back using gestures.

### The OS that Immich Server is running on

ubuntu 22.04.4

### Version of Immich Server

1.125.7

### Version of Immich Mobile App

1.127.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server@sha256:217cddb1e0fa3f4878e1573fe1fd4b9dc24f737015cc5c917910787a5ec0f85e
    volumes:
      - ${IMMICH_UPLOAD_PATH}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${IMMICH_GEO_CN_PATH}:/build/geodata
      - ${IMMICH_I18N_PATH}:/usr/src/app/node_modules/i18n-iso-countries
    depends_on:
      - redis
      - immich_postgres
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - nginx_ipv4

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning@sha256:c6ac56b2147dc716c4813c14ffc66b3aa91b0e1aaa74493a3a77d97cf4a98d7a
    volumes:
      - ${IMMICH_MODEL_CACHE_PATH}:/cache
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - nginx_ipv4
      
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - nginx_ipv4

  immich_postgres:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.1
    user: "1000:1000"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${IMMICH_PG_DATA_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - nginx_ipv4
```

### Your .env content

```Shell
# immich
IMMICH_UPLOAD_PATH=/home/immich/data
IMMICH_MODEL_CACHE_PATH=/home/immich/model-cache
IMMICH_PG_DATA_PATH=/home/immich/pgdata

IMMICH_GEO_CN_PATH=/home/immich/geodata
IMMICH_I18N_PATH=/home/immich/i18n-iso-countries

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# IMMICH_VERSION="v1.98.2"
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD="PassPostgres"
# The values below this line do not need to be changed
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Open the album, click Add Photo to enter the photo selection interface
2. Use gestures to go back one level

### Relevant log output

```shell

```

### Additional information

The gesture on the interface for selecting photos when creating a new album is normal. After the album is created, if the album is not empty, the gesture fails.
