### ISSUE TITLE
Can't update star rating when filtering by star in 1.127.0

### ISSUE THREAD

**Issue by adambeck7** [immich-app/immich#16405]
### The bug

I can't update the star rating when in filter view. 

1. Filter by star rating. 
2. Click on photo.
3. Update star rating. 
4. Revisit photo in library, star rating hasn't been updated. 

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

v.1.127.0

### Version of Immich Mobile App

v1.127.0 build.195

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - /mnt/user/Pictures:/home/user/photos1:ro
    ports:
      - 2283:2283
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    runtime: nvidia

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    ports:
      - 5434:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA2: /var/lib/postgresql/data
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

#   immich-proxy:
#     container_name: immich_proxy
#     image: ghcr.io/immich-app/immich-proxy:release
#     environment:
#       # Make sure these values get passed through from the env file
#       - IMMICH_SERVER_URL
#       - IMMICH_WEB_URL
#     ports:
#       - 2283:8080
#     logging:
#       driver: none
#     depends_on:
#       - immich-server
#       - immich-web
#     restart: always

volumes:
  pgdata2:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_PASSWORD=pass
DB_HOSTNAME=host
DB_USERNAME=user
DB_DATABASE_NAME=name

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################


###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/immich/upload
THUMB_LOCATION=/mnt/user/immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/user/immich/encoded-video
PROFILE_LOCATION=/mnt/user/immich/profile
LIBRARY_LOCATION=/mnt/user/immich/library

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=log

###################################################################################
# JWT SECRET
#
# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
###################################################################################

JWT_SECRET=my jwt
TYPESENSE_API_KEY=typesense-key

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

 DISABLE_REVERSE_GEOCODING=false
 REVERSE_GEOCODING_PRECISION=3
```

### Reproduction steps

1. Filter by star rating. 
2. Click on photo.
3. Update star rating. 
4. Revisit photo in library, star rating hasn't been updated. 

### Relevant log output

```shell
[Nest] 7  - 02/27/2025, 3:49:46 PM    WARN [Microservices:MetadataRepository] Error writing exif data (/home/user/photos1/2022/12/20221224_205114_A072C4E6.jpg.xmp): Error: Error creating file: /home/user/photos1/2022/12/20221224_205114_A072C4E6.jpg.xmp_exiftool_tmp - /home/user/photos1/2022/12/20221224_205114_A072C4E6.jpg.xmp
```

### Additional information

I tried updating multiple images, but all had the same log message as above and none would update their star rating.
