### ISSUE TITLE
iOS Live Photo

### ISSUE THREAD

**Issue by mentex23** [immich-app/immich#16401]
### The bug

Live Photos in iOS App not showing correctly. There are 2 files shown, one with an image and the other one is black with a "!" in it. On Safari and other web browsers live photo is shown correctly.

### The OS that Immich Server is running on

Docker, Ubuntu 22.10

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

v.1.127.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external/:ro
      - ${EXTERNAL_PATH_...}:/usr/src/app/external/:ro
    env_file:
      - .env
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
       file: hwaccel.transcoding.yml
       service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    ports:
      - 2283:2283
    security_opt:
      - "label=disable"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
#    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
#       file: hwaccel.ml.yml
#       service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external/:ro
      - ${EXTERNAL_PATH_....}:/usr/src/app/external/:ro
    env_file:
      - .env
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
       file: hwaccel.transcoding.yml
       service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    ports:
      - 2283:2283
    security_opt:
      - "label=disable"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
#    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
#       file: hwaccel.ml.yml
#       service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://192.168.1.5:2283/api
      API_KEY: j3qIV2W9ZjdQGYYl5sVHZrXx1oWcNw3NbilbaBmLzI
      ROOT_PATH: /usr/src/app/external/
      CRON_EXPRESSION: "*/5 * * * *"
      TZ: Europe/Berlin
      ALBUM_LEVELS: 10
      ALBUM_SEPARATOR: " - "

  immich-folder-album-creator_f:
    container_name: immich_folder_album_creator_f
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://192.168.1.5:2283/api
      API_KEY: WSMecMt7itoDCYQAADKQcWQjJ2xhwBqRmgNZ48R0
      ROOT_PATH: /usr/src/app/external/
      CRON_EXPRESSION: "*/5 * * * *"
      TZ: Europe/Berlin
      ALBUM_LEVELS: 10
      ALBUM_SEPARATOR: " - "

volumes:
  pgdata:
  model-cache:
    restart: always

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://192.168.1.5:2283/api
      API_KEY: j3qIV2W9ZjdQGYYl5sVHZrXx1oWcNw3NbilbaBmLzI
      ROOT_PATH: /usr/src/app/external/
      CRON_EXPRESSION: "*/5 * * * *"
      TZ: Europe/Berlin
      ALBUM_LEVELS: 10
      ALBUM_SEPARATOR: " - "

  immich-folder-album-creator_f:
    container_name: immich_folder_album_creator_f
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://192.168.1.5:2283/api
      API_KEY: WSMecMt7itoDCYQAADKQcWQjJ2xhwBqRmgNZ48R0
      ROOT_PATH: /usr/src/app/external/
      CRON_EXPRESSION: "*/5 * * * *"
      TZ: Europe/Berlin
      ALBUM_LEVELS: 10
      ALBUM_SEPARATOR: " - "

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/.../Photos/immich-lib

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=...

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=...
DB_DATABASE_NAME=..

REDIS_HOSTNAME=immich_redis
EXTERNAL_PATH=/mnt/.../Photos/Bilder
EXTERNAL_PATH_...=/mnt/../Bilder
MACHINE_LEARNING_WORKER_TIMEOUT=600
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
