### ISSUE TITLE
persistens notification and crash on immich mobile app for android

### ISSUE THREAD

**Issue by babushanaelsa** [immich-app/immich#16416]
### The bug

Since the update to Version 127.0 opening the immich app on Android 15 starts a background notification "searching for new assets". After about 2 minutes this background job crashes and says "immich has stopped working". After another 2 minutes it starts again with the notification and the exact behaviour.

What I've tried so far:

- Redeploy immich stack
- Force stop Android app
- clear cache of android app
- sign out and in the android app

### The OS that Immich Server is running on

Ubuntu 24

### Version of Immich Server

127.0

### Version of Immich Mobile App

127.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich-server
    user: 1000:1000
    labels: 
     - com.centurylinklabs.watchtower.monitor-only=true
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /var/lib/docker/volumes/immich:/usr/src/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - stack.env
    networks:
      - reverse_proxy
      - default
    environment:
      - NODE_ENV=production
      - TZ=Europe/Zurich
    logging:
      driver: "syslog"
    depends_on:
      valkey:
       condition: service_started
      database:
       condition: service_started
    restart: always

  immich-machine-learning:
    container_name: immich-machine-learning
    user: 1000:1000
    labels: 
     - com.centurylinklabs.watchtower.monitor-only=true
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - default
    volumes:
      - /var/lib/docker/volumes/immich/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Zurich
    depends_on:
      valkey:
       condition: service_started
      database:
       condition: service_started
    restart: always

  valkey:
    container_name: immich_valkey
    image: valkey/valkey:bookworm
    networks:
      - default
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Zurich
    restart: always
    volumes:
     - /var/lib/docker/volumes/immich/valkey:/data
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro

  database:
    container_name: immich_db
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=off", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      
    networks:
     - default
    labels: 
     - com.centurylinklabs.watchtower.monitor-only=true
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      TZ: Europe/Zurich
    volumes:
      - /var/lib/docker/volumes/immich/db:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    

networks:
  reverse_proxy:
    external: true
  default:
    external: false
```

### Your .env content

```Shell
DB_HOSTNAME
immich_db

DB_USERNAME
postgres


DB_PASSWORD
*******

DB_DATABASE_NAME
immich

REDIS_HOSTNAME
immich_valkey

UPLOAD_LOCATION
/var/lib/docker/volumes/immich/
```

### Reproduction steps

1.Open Immich App on Android
2.
3.
...

### Relevant log output

```shell
Theres nothing happening in the server log
```
