### ISSUE TITLE
Review duplicates utility does not stack photos or save changes (v1.127.0)

### ISSUE THREAD

**Issue by reven** [immich-app/immich#16413]
### The bug

Using the Duplicates utility does not save changes. After using "Stack" button, the images disappear and the next pair/group is loaded in. The process continues without any issues or error messages. Navigating away from the tool after one or various changes and then coming back to the tool, the exact same pairs/groups of images are listed for resolution and the total number of duplicates is the same as before any duplicates were resolved.

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

v1.127.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/nibbler/Photo_Library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Choose "Utilities" in the web menu
2. Choose "Review Duplicates"
3. Select "Stack" (In my case Immich is mostly detecting CR2 and JPG pairs). No error and Duplicates number at the top decreases.
4. Repeat 3 any number of times
5. Navigate away from tool, for example clicking on Photos
6. Repeat steps 1 and 2
7. The exact same images are offered for resolution as before steps 3 and 4, and the "Duplicates" number has not decreased.
...

### Relevant log output

```shell
[Nest] 17  - 02/27/2025, 7:53:24 PM   DEBUG [Api:LoggingInterceptor~h79tdwwl] GET /api/search/explore 200 10.60ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:24 PM   DEBUG [Api:LoggingInterceptor~7d5q9s4b] GET /api/people?withHidden=false 200 114.54ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:28 PM   DEBUG [Api:LoggingInterceptor~iy98hgrm] GET /api/duplicates 200 29.30ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:28 PM   DEBUG [Api:LoggingInterceptor~pk12eing] GET /api/albums?assetId=ba97b0f4-78d1-4bbe-a831-72c23ad482f2 200 2.87ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:28 PM   DEBUG [Api:LoggingInterceptor~dljb5nhi] GET /api/albums?assetId=e35bc277-48a5-4126-a49c-e320533cd0d2 200 3.88ms ::ffff:192.168.1.5




[Nest] 17  - 02/27/2025, 7:53:37 PM   DEBUG [Api:LoggingInterceptor~83jw5jxd] GET /api/server/ping 200 0.10ms ::ffff:127.0.0.1
[Nest] 17  - 02/27/2025, 7:53:42 PM   DEBUG [Api:LoggingInterceptor~57zqmx4o] POST /api/stacks 201 17.77ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:42 PM   DEBUG [Api:LoggingInterceptor~pfm0rqgn] PUT /api/assets 204 0.91ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:43 PM   DEBUG [Api:LoggingInterceptor~4n8ujkdi] GET /api/albums?assetId=894ccdf0-e646-452e-9375-617701fcff5c 200 3.38ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:43 PM   DEBUG [Api:LoggingInterceptor~n9rxfnnb] GET /api/albums?assetId=62e3d860-232e-4cb9-b0f2-6a9275648114 200 2.79ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:47 PM   DEBUG [Api:LoggingInterceptor~7e2j1v9t] POST /api/stacks 201 31.88ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:47 PM   DEBUG [Api:LoggingInterceptor~nctx97or] PUT /api/assets 204 0.78ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:47 PM   DEBUG [Api:LoggingInterceptor~regbttnt] GET /api/albums?assetId=49d1780e-341f-438e-9966-bb6a30ba3e75 200 2.75ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:47 PM   DEBUG [Api:LoggingInterceptor~wdjxgh94] GET /api/albums?assetId=a3fb2851-4434-4b03-93f0-7668b1d5f9a6 200 3.47ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:48 PM   DEBUG [Api:LoggingInterceptor~bskq36rj] POST /api/stacks 201 21.56ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:49 PM   DEBUG [Api:LoggingInterceptor~jh33qe6q] PUT /api/assets 204 0.79ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:49 PM   DEBUG [Api:LoggingInterceptor~3s6c3qib] GET /api/albums?assetId=56ebea59-852a-4e68-9df3-b63e1cac8f76 200 3.60ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:49 PM   DEBUG [Api:LoggingInterceptor~far317w4] GET /api/albums?assetId=dad84f8a-43b4-4514-906c-5a301ec8feb7 200 4.47ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:50 PM   DEBUG [Api:LoggingInterceptor~mi6hcqeh] POST /api/stacks 201 29.08ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:50 PM   DEBUG [Api:LoggingInterceptor~rv72nqwv] PUT /api/assets 204 0.86ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:50 PM   DEBUG [Api:LoggingInterceptor~q43m3sj9] GET /api/albums?assetId=bec75871-8484-49e2-baf5-f1cf5dca37df 200 4.15ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:50 PM   DEBUG [Api:LoggingInterceptor~zy58orwa] GET /api/albums?assetId=1949760f-7015-4c8f-9a2c-433cfe42f6a5 200 3.70ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:51 PM   DEBUG [Api:LoggingInterceptor~bewuv4q4] POST /api/stacks 201 18.50ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:51 PM   DEBUG [Api:LoggingInterceptor~jf04klm9] PUT /api/assets 204 0.93ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:51 PM   DEBUG [Api:LoggingInterceptor~nladr2po] GET /api/albums?assetId=db8a6cf2-6030-4208-9d07-9e7499f48c0d 200 3.57ms ::ffff:192.168.1.5
[Nest] 17  - 02/27/2025, 7:53:51 PM   DEBUG [Api:LoggingInterceptor~rkh6wt6i] GET /api/albums?assetId=723a8270-4f74-4dde-98d6-7bea74e3da9a 200 4.74ms ::ffff:192.168.1.5
```
