### ISSUE TITLE
Photos doesn't appear on web after upgrade to v1.128.0

### ISSUE THREAD

**Issue by JcMinarro** [immich-app/immich#16448]
### The bug

I just updated to version v1.128.0 and pictures are not shown on the main screen on the web.
I can see there is an error on the Javascript console and I think the issue is within [this function](https://github.com/immich-app/immich/blob/f11080cc2d72c832c3816e90219649d16c7577ee/web/src/lib/stores/assets.store.ts#L382) but I am not sure.

### The OS that Immich Server is running on

Debian, Docker

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

1.127.0 build.185

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '30041:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg15-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always


#########################
### Third party tools ###
#########################
  immich-public-proxy:
    image: alangrainger/immich-public-proxy:latest
    container_name: immich-public-proxy
    restart: always
    volumes:
      - ./volumes/immich-public-proxy/config.json:/app/config.json:ro
    ports:
      - "30042:3000"
    environment:
      - IMMICH_URL=PRIVATE_DATA
    healthcheck:
      test: wget -q --spider http://localhost:3000/share/healthcheck || exit 1
      start_period: 10s
      timeout: 5s

  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "30043:3000"
    env_file:
      - .env.power-tools

  immich-duplicate-finder:
    container_name: immich-duplicate-finder
    hostname: immich-duplicate-finder
    restart: unless-stopped
    ports:
      - 30044:8501
    volumes:
      - ./volumes/immich-duplicate-finder/data:/immich_duplicate_finder/data
      - ./volumes/immich-duplicate-finder/cache:/root/.cache/torch/
    env_file:
      - .env.immich-duplicate-finder
    build:
      dockerfile: './immich-duplicate-finder/Dockerfile'
  

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./volumes/upload
# The location where your database files are stored
DB_DATA_LOCATION=./volumes/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Madrid

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=PRIVATE_DATA

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich

IMMICH_URL=PRIVATE_DATA
CPU_CORES=4

IMMICH_API_KEY = PRIVATE_DATA
EXTERNAL_IMMICH_URL=PRIVATE_DATA
DB_HOST=database
DB_PORT=5432
```

### Reproduction steps

1. Open main immich instance web
2. Memories are load but pictures not

![Image](https://github.com/user-attachments/assets/b82df966-3049-4fb3-9b35-4e9412ee42d6)

### Relevant log output

```shell
Uncaught (in promise) TypeError: e.map is not a function
    at fo.initialiazeTimeBuckets (DMCCp51r.js:9:48722)
    at async fo.init (DMCCp51r.js:9:48496)
```

![Image](https://github.com/user-attachments/assets/0c8a06ce-09bb-4b98-8d41-997ba52f08a9)

![Image](https://github.com/user-attachments/assets/655e0b16-5ec8-4788-ae73-fa78346588f7)
