### ISSUE TITLE
iPhone app not uploading all directories / albums

### ISSUE THREAD

**Issue by cjdw94** [immich-app/immich#16464]
### The bug

Hi all,

I posted this in the Discord, but I’m not seeing any traction, so I’m going to cross-post.   I apologize if this is considered inappropriate.

I'm having trouble with the iOS app of Immich.   It claims (from within the app) to have the capability to back up all of my phone's albums (the iOS app shows no errors for these extra albums), but when I go to view the images in Immich, many (if not all) of the albums (except the core albums "All", "Recents", "Videos", etc.) are completely empty.  I am running my Immich server on a Asustor Lockstore Gen 2 AS6704T.

My Dropbox Photos folder shows up in the web UI,  But if I try to access it, I'm met with this error message:

"Not found or no album.read access (400)"

Steps performed while trying to fix another problem simultaneously:
- Ran several tasks: generated thumbnails, extracted metadata, performed sidecar metadata, ran Smart Search, ran Duplicate Detection, and ran Face Detection.

Attempted to upload just the Dropbox Photos folder from iOS, but Immich believes that its contents already exist in my collection of items.

### The OS that Immich Server is running on

Lockerstore Asustor AS6704T - ADM 4.3 (?)

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

iOS v1.128.0 build.196

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    ports:
      - 3003:3003

    env_file:
      - stack.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/Immich/Pictures
DB_DATA_LOCATION=/share/Immich/Database
IMMICH_VERSION=release
DB_PASSWORD=[redacted]
DB_USERNAME=[redacted]
DB_DATABASE_NAME=Immich
```

### Reproduction steps

1. Used upload feature from iOS Immich app.
2. Albums are confirmed transferable from the iOS client app.
3. Empty (and duplicate empty) folders are generated server-side for several albums instead of being populated with photos.
4. Several albums are being populated, however, including “Recents”, “Videos”, “Live Photos”, “Screenshots”, my bulk library, and shared albums “Guy savoy”, “Joel robuchon”, and “Gwen & Ben”.   So those are functioning properly.

### Relevant log output

```shell

```

### Additional information

I am currently on iOS 18.3.1 on an iPhone SE 3rd generation.
