### ISSUE TITLE
Memories "years ago" are zero based

### ISSUE THREAD

**Issue by tvillini** [immich-app/immich#16474]
### I have searched the existing issues to make sure this is not a duplicate report.

- [x] Yes

### The bug

Not a huge priority obviously, but sorta funny. My memories are showing up offset by a year. So 1 year ago is showing 0 years ago. 2 is 1, 3 is 2, etc.

![Image](https://github.com/user-attachments/assets/bc832b55-04bd-41e7-b81e-f85d747035d7)

### The OS that Immich Server is running on

Docker Container

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.128.0
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=immich
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/media/Docker/immich_data:/usr/src/app/upload
    networks:
      - npm_proxy
      - internal
    depends_on:
      - redis
      - db
    healthcheck:
      disable: false
      
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.128.0
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=***
      - DB_PASSWORD=***
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=immich
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - model-cache:/cache
    networks:
      - internal

  redis:
    image: redis:6.2
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - internal

  db:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - DB_DATABASE_NAME=immich
      - DB_USERNAME=***
      - DB_PASSWORD=***
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=immich
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      - /mnt/ceph_docker/immich_db:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
    
networks:
  npm_proxy:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.25.0/24

volumes:
  model-cache:
```

### Your .env content

```Shell
No ENV content... doing this in Swarm.
```

### Reproduction steps

Open Immich, observe 0-based memories.

### Relevant log output

```shell

```
