### ISSUE TITLE
Multiple Memories at top

### ISSUE THREAD

**Issue by HippoBloke** [immich-app/immich#16484]
### I have searched the existing issues to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi all

I seem to have multiple memories for each year. Any idea ?

I may have started additional jobs in my impatience to see them after the recent change but they continue after a restart. Is there any way I can find active jobs and stop the extras ?

Thanks
Hippo

### The OS that Immich Server is running on

Unraid 7.0.1

### Version of Immich Server

v1.28.0

### Version of Immich Mobile App

v1.28.0

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/iCloud_Photos:/import
      - /mnt/user/Cine:/Cine
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
      
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    volumes:
      - /mnt/user/Immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /mnt/user/Immich/cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
     - '5432:5432'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Immich
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/Immich/database

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/London

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxxxxx
DB_DATABASE_NAME=xxxxxx
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```

**Comment by YarosMallorca** [comment]
I have the same issue.
As I commented [here](https://github.com/immich-app/immich/issues/16425#issuecomment-2692676047):

> It definitely should show the job in the list like all the other jobs. Users get confused as to why the memory generation job isn't being created and try multiple times, leading to this.

![Image](https://github.com/user-attachments/assets/a2a82af3-2eba-48e8-9725-17209de20a67)

**Comment by alextran1502** [comment]
Please follow the exact step below to resolve this issue. From the command line, run the following command to clean the state of the memories generation

```
docker exec immich_postgres psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memory cascade;"
```

Then go into the job page, and run the memories generation jobs

![Image](https://github.com/user-attachments/assets/f9a522c3-ad95-41c3-b698-bcfbd6a117d7)

@YarosMallorca That was a bug in 1.127.0, from 1.128.0 no duplicate memories should be generated

**Comment by thomasss02** [comment]
+1
I attach the JSON response at /api/memories?for=2025-03-02T11%3A42%3A14.048Z

[memories.json](https://github.com/user-attachments/files/19043087/memories.json)

**Comment by HippoBloke** [comment]
All good here - thanks @alextran1502 - you are a star !!

**Comment by res80** [comment]
Had a similar issue, all my memories were misplaced by one year (so memories from 2024 showed 0 years ago, 2023 showed 1 year ago etc.
After running the given command, everythink works OK again :) Thanks a lot!

**Comment by YarosMallorca** [comment]
@HippoBloke, if everything works as expected, please close this issue. If it doesn't describe the issue.

**Comment by waclaw66** [comment]
> Please follow the exact step below to resolve this issue. From the command line, run the following command to clean the state of the memories generation
> 
> ```
> docker exec immich_postgres psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"
> ```

It worked for me, although there should be gui fix for that. Memory cleanup doesn't work for that.

**Comment by Nordlicht-13** [comment]
> Please follow the exact step below to resolve this issue. From the command line, run the following command to clean the state of the memories generation
> 
> ```
> docker exec immich_postgres psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"
> ```
> 
> Then go into the job page, and run the memories generation jobs
> 
> ![Image](https://github.com/user-attachments/assets/f9a522c3-ad95-41c3-b698-bcfbd6a117d7)
> 
> [@YarosMallorca](https://github.com/YarosMallorca) That was a bug in 1.127.0, from 1.128.0 no duplicate memories should be generated

Where do I run this command?
I have setup immich under dockge on my TrueNAS.
Do I use the TrueNAS Shell, dockge >_Batch or something else?

**Comment by alextran1502** [comment]
@waclaw66 shouldn't happen again, the bug was from memories generated from 1.127.0, Any generated memories going forward won't have this issue

**Comment by AndresSalinasB** [comment]
I'm having the same issue here but I'm hosting immich in truenas (using the provided version) and I don't have a dedicated container for postgres.

how can I get this fixed?

**Comment by Nordlicht-13** [comment]
> I'm having the same issue here but I'm hosting immich in truenas (using the provided version) and I don't have a dedicated container for postgres.
> 
> how can I get this fixed?

In the TrueNAS-App the Postgres Data Storage is the last volume at the bottom.
You can start a shell of the database-volume under the point "Workloads" of the app.
There you can ran
`psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"`

**Comment by dinosmm** [comment]
> Please follow the exact step below to resolve this issue. From the command line, run the following command to clean the state of the memories generation
> 
> ```
> docker exec immich_postgres psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"
> ```
> 
> Then go into the job page, and run the memories generation jobs
> 
> ![Image](https://github.com/user-attachments/assets/f9a522c3-ad95-41c3-b698-bcfbd6a117d7)
> 
> [@YarosMallorca](https://github.com/YarosMallorca) That was a bug in 1.127.0, from 1.128.0 no duplicate memories should be generated

This worked for me, thank you. I didn't have duplicate memories but memories were showing a year less than what they were. Now that's fixed. Was this a one-off or will it need running again until a fix is provided in a future version?

**Comment by YarosMallorca** [comment]
> Was this a one-off or will it need running again until a fix is provided in a future version?

@dinosmm This was a one-off in v1.127.0. Unless this bug somehow reappears, it isn't necessary to do it in the future. It has been patched by v1.128.0

**Comment by ARVEDz** [comment]
Thanks. Had the same issue since 1.28.0, but the workaround works!

**Comment by kikendo** [comment]
I don't think the way memories work now is practical and whatever speed benefits or others it might have brought forward are not worth the drawbacks it's generating.

Thanks for sharing how to fix this in my now broken DB but it would be better of this whole feature was restored to how it was working last year.

**Comment by Quarzer** [comment]
> > I'm having the same issue here but I'm hosting immich in truenas (using the provided version) and I don't have a dedicated container for postgres.
> > how can I get this fixed?
> 
> In the TrueNAS-App the Postgres Data Storage is the last volume at the bottom. You can start a shell of the database-volume under the point "Workloads" of the app. There you can ran `psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"`

Hey dude,

can you help me on that? I can't get it to run. Which workload should I pick? Permissions is the last on my side. When I click on shell that came up: "/bin/sh" When I klick enter I'm in the shell overview and when I paste your code into nothing happen. I tried all other workloads as well, but it never worked. What are the steps I need to do?

**Comment by alextran1502** [comment]
@kikendo there was a bug and is now fixed

**Comment by AndresSalinasB** [comment]
> > > I'm having the same issue here but I'm hosting immich in truenas (using the provided version) and I don't have a dedicated container for postgres.
> > > how can I get this fixed?
> > 
> > 
> > In the TrueNAS-App the Postgres Data Storage is the last volume at the bottom. You can start a shell of the database-volume under the point "Workloads" of the app. There you can ran `psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"`
> 
> Hey dude,
> 
> can you help me on that? I can't get it to run. Which workload should I pick? Permissions is the last on my side. When I click on shell that came up: "/bin/sh" When I klick enter I'm in the shell overview and when I paste your code into nothing happen. I tried all other workloads as well, but it never worked. What are the steps I need to do?
> 
> Got also that one: "psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory Is the server running locally and accepting connections on that socket?"

it's the same issue I have. There is no postgres container in workloads.

I have 5 containers: 
- server
- machine-learning
- pgvecto
- redis
- permissions

**Comment by alextran1502** [comment]
@AndresSalinasB I think you need to access to the pgvecto container

**Comment by Quarzer** [comment]
> [@AndresSalinasB](https://github.com/AndresSalinasB) I think you need to access to the pgvecto container

Hey,

I tried on that but got "psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  role "postgres" does not exist"

**Comment by AndresSalinasB** [comment]
same result for me trying to use the pgvecto container

**Comment by schmitzkr** [comment]
> > [@AndresSalinasB](https://github.com/AndresSalinasB) I think you need to access to the pgvecto container
> 
> Hey,
> 
> I tried on that but got "psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL: role "postgres" does not exist"

On Truenas SCALE, community app, I used the the command Alex provided but changed the user to `immich` user in the `pgvecto` container and it worked.

**Comment by AndresSalinasB** [comment]
that's the trick! thanks a lot!

for reference I used this command `docker exec ix-immich-pgvecto-1 psql --dbname=immich --username=immich -c "delete from system _metadata where key like 'memories-state'; truncate table memories cascade;"`

**Comment by Quarzer** [comment]
This was working for me in TrueNas SCALE pgvecto container: `psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"`

**Comment by biligodos** [comment]
After upgrade to v1.128.0 I get duplicate memories in my timeline.

**Comment by cch000** [comment]
The suggested solution doesn't work on nixos:

```
 > psql --dbname=immich --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;" 

psql: error: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "postgres"
```

I've also tried with --username=immich

**Comment by alextran1502** [comment]
@cch000 update to the latest version 1.129.0 also fix this issue

**Comment by rwlove** [comment]
I'm still getting this in 1.30.3.

**Comment by sakibstark11** [comment]
So I've ran the sql query and regenerated the memories but when I do, it ends up duplicating it thrice.
I am using the latest versions.

**Comment by RogerSik** [comment]
@sakibstark11 i created a new issue because this issue is closed and really long. https://github.com/immich-app/immich/issues/18215

**Comment by chemicalsam** [comment]
If I add the Memory Creation job, it says created but doesn't seem to make anything in the GUI for me to initiate the job.

**Comment by MrScripter85** [comment]
Its also not working for me - for several months already. Whenever I click on that "create job" 

<img width="616" height="398" alt="Image" src="https://github.com/user-attachments/assets/8584cb43-6e27-4a4f-b982-43fbce328a5a" />

it says that it was sucessful:

<img width="400" height="199" alt="Image" src="https://github.com/user-attachments/assets/ab75699b-dbb3-4908-983f-0f31d25a2efb" />

but not any job shows up and also not any memory is being created.

This is my docker file:

```
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1000:10
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/immich/redis:/data:rw
    restart: always

  immich-db:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.0
    #image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: always

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/immich/upload:/usr/src/app/upload:rw
    restart: always
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - 44
      - 105 
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1000:10
    
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /volume1/immich/upload:/usr/src/app/upload:rw
      - /volume1/immich/cache:/cache:rw
      - /volume1/immich/matplotlib:/matplotlib:rw
    environment: 
      - MPLCONFIGDIR=/matplotlib

    restart: always
    depends_on:
      immich-db:
        condition: service_started
```
