### ISSUE TITLE
Casaos Install Issue

### ISSUE THREAD

**Issue by mousethatischarles** [immich-app/immich#16496]
### I have searched the existing issues to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm very impressed with Immich, however the latest supplied Docker Compose install doesn't play 'nice' with my Casaos on DietPi setup - all fully up to date, including docker.
Two issues:
The recommended Docker Compose instal files and method seem to work fine, but:
1) When the icon for Immich appears on the Casaos desktop it won't run a and the path to its configs has changed in the following way:
If the path was of the form 'path to config files' it becomes 'path to config files/path to config files'
The path to the images folder is unaffected.
2a) On checking via Portainer I note the 'immich_postgres' and 'immich_redis' containers are stuck in 'starting'.
2b) Having 'fixed' point 2a both containers are 'unhealthy' and while to server starts none of the 'AI' functions work.

Fixes, see my custom .yml file:
1) It seems some interaction between the supplied .yml .env files and when Casaos first 'imports' the docker is duplicating the affected path - no idea why, but ditching the .env file and manually entering the revenant variables and paths in to the .yml fixes this. Note: The paths contained in the .yml below are specifically for my system and not those supplied by the developers. Also where you find <my password> and <my user> are simply where I have substituted my private info for this report.
2a) Commenting out the 'healthcheck:' code for the offending containers fixes the non-starting issue. As it happens I commented out all the 'healthcheck:' lines with no issue.
2b) The above still resulted in the offending containers not running happily - they seemed to run but did not function. I fixed this by giving each a memory: 1024M. Less did not work, more seems unnecessary - I ended up doing this for all the containers as... why not..?

Notes: 
i) As Immich's containers mostly hits my server pretty hard for seemingly no good reason I also added cpu_shares: 50 to all the containers to rein them in a bit. I suspect lower would be fine for all but the machine learning container. I gave the machine-learning container a cpu_shares: 90 as it does seem to idle properly and when it is in use I wanted it to fun as fast as possible as I currently don't have any acceleration configured. 
My home server is a multi-core Xeon-based machine running Esxi VM's so I don't think my issues are related to a lack of resources!
ii) From 'x-casaos:' down are just my minimal additions to get the .yml to give Casaos a nice desktop icon and slot in a few relevant paths without having to do it after the fact.

I hope that helps.
Kind regards,

### The OS that Immich Server is running on

Casaos v0.4.15 on DietPi (x64) v9_11 - Debian base

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  database:
    cpu_shares: 50
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    container_name: immich_postgres
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=<my password>
      - POSTGRES_USER=<my user>
    hostname: immich_postgres
#    healthcheck:
#      test:
#        - CMD-SHELL
#        - pg_isready --dbname="" --username="" || exit 1; Chksum="$(psql
#          --dbname="" --username="" --tuples-only --no-align --command='SELECT
#          COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo
#          "checksum failure count is "; [ "" = '0' ] || exit 1
#      interval: 5m0s
#      start_period: 5m0s
#      start_interval: 30s
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/Store/Config/immich/data
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    networks:
      - immich_default
    privileged: false
  immich-machine-learning:
    cpu_shares: 90
    command: []
    container_name: immich_machine_learning
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - DB_DATA_LOCATION=./media/Store/Config/immich/data
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=OpelGT
      - DB_USERNAME=admin
      - IMMICH_VERSION=release
      - TZ=Europe/London
      - UPLOAD_LOCATION=./media/Store/Images/Library
#    env_file:
#      - /media/Store/Config/immich/.env
    hostname: immich_machine_learning
#    healthcheck: {}
    image: ghcr.io/immich-app/immich-machine-learning:release
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/model-cache
        target: /cache
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    networks:
      - immich_default
    privileged: false
  immich-server:
    cpu_shares: 50
    command: []
    container_name: immich_server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - DB_DATA_LOCATION=./media/Store/Config/immich/data
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=<my password>
      - DB_USERNAME=admin
      - IMMICH_VERSION=release
      - TZ=Europe/London
      - UPLOAD_LOCATION=./media/Store/Images/Library
#    env_file:
#      - /media/Store/Config/immich/.env
    hostname: immich_server
#    healthcheck: {}
    image: ghcr.io/immich-app/immich-server:release
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    ports:
      - mode: ingress
        target: 2283
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /media/Store/Images/Library
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    networks:
      - immich_default
    privileged: false
  redis:
    cpu_shares: 50
    command: []
    container_name: immich_redis
    deploy:
      resources:
        limits:
          memory: 1024M
    hostname: immich_redis
#    healthcheck:
#      test:
#        - CMD-SHELL
#        - redis-cli ping || exit 1
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - immich_default
    privileged: false
networks:
  immich_default:
    name: immich_default
x-casaos:
  author: CharlesMouse
  category: Gallery
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png
  index: /
  is_uncontrolled: true
  port_map: "2283"
  scheme: http
  title:
    custom: Immich
```

### Your .env content

```Shell
No .env file used!
```

### Reproduction steps

1.See above for issue and how I resolved them.
2.
3.
...

### Relevant log output

```shell
none
```

### Additional information

I hope the above is useful and of interest. No idea why the default setup for Immich does this, I have had no such issues with any other docker images I've tried with Casaos on DietPi so I presume this is an immich issue and not directly to do with either of the others.

I hope my included fixes are helpful in both diagnosis and any changes going forward. Kind regards.
