### ISSUE TITLE
Memories are repeated

### ISSUE THREAD

**Issue by manilx** [immich-app/immich#16524]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Since the last update, memories has been unreliable (and they were perfect before).
I now get repeating memories, all the same picture but with different years.

### The OS that Immich Server is running on

debian 12

### Version of Immich Server

Build 13595031799 Build Image v1.128.0

### Version of Immich Mobile App

last

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:3995fe6ea6a619313e31046bd3c8643f9e70f8f2b294ff82659d409b47d06abb
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=ejkfbvkwjefvnvhe
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=
DB_USERNAME=
DB_DATABASE_NAME=
REDIS_HOSTNAME=immich_redis

#IMMICH_SERVER_URL=https://immich.
#IMMICH_WEB_URL=https://immich.
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
