### ISSUE TITLE
Video uploads with UTC incorrectly

### ISSUE THREAD

**Issue by mstewart14** [immich-app/immich#16557]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

when uploading videos from my android phone, photos have the correct timezone (-8) applied but videos from the same shoot get UTC.  

### The OS that Immich Server is running on

Docker on Debian (on Proxmox)

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0 build 186

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-server.rule=Host(`<url>`)
      - traefik.docker.network=proxy
      - traefik.http.services.immich-server.loadbalancer.server.port=2283
      - traefik.http.routers.immich-server.tls.certresolver=<resolvername>
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immichproxy

    environment:
      - TZ=America/Vancouver
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    networks:
      - immichproxy
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: tiredofit/redis:7  # redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    networks:
      - immichproxy
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - immichproxy
    restart: always

volumes:
  model-cache:

networks:
  immichproxy:
    name: proxy
    external: true
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<pwd>

# timezone setting
TZ=America/Vancouver

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=<username>
DB_DATABASE_NAME=<dbname>

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. take pics and video, open mobile app and "backup" photos
2. look on the web and notice that last night's photos appear in a list with photos from today (closer examination shows the timezone for the video as UTC (+8 relative to my timezone) which moves the video into the next day (in the middle of the night).  Photos have no issues timezone and date/time stamps make sense.
...

### Relevant log output

```shell

```

### Additional information

There appears to be a discussion about this [here ](https://github.com/immich-app/immich/discussions/7701).  I don't think I should have to create sidecar files for this to just simply work...
