### ISSUE TITLE
Immich server duplicated memories and memories with 0 years...

### ISSUE THREAD

**Issue by krypton9208** [immich-app/immich#16567]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After update to 1.128.0. 
Memories are duplicated (i upgrade yesterday...) 
And from some time i see memories from 0 years ago.... I am a software developer and maybe is because 2024 year have one MORE day (366 day)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '14385:2283'
    depends_on:
      - redis
      - database
    restart: always
    privileged: true
    runtime: nvidia
    networks:
      - immich_default
      - immich-internal
    healthcheck:
      disable: false
      test: ''

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/storage_immich/model_cache:/cache
    env_file:
      - .env
    restart: always
    privileged: true
    runtime: nvidia
    networks:
      - immich_default # machine learning requires internet connecting for model download
      - immich-internal
    healthcheck:
      test: ''
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    volumes:
      - /mnt/storage_immich/redis:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich-internal
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

networks:
  immich_default:
    external: true
  immich-internal:
    internal: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/storage_immich/files/

# The location where your database files are stored
DB_DATA_LOCATION=/mnt/storage_immich/db/
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ: "Poland"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.128.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=***********

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all
REDIS_HOSTNAME=redis
IMMICH_PROCESS_INVALID_IMAGES=true
```

### Reproduction steps

<img width="985" alt="Image" src="https://github.com/user-attachments/assets/504a18ab-58b5-4424-9656-b007bc7cd1a9" />

### Relevant log output

```shell

```

### Additional information

All entries from years are duplicated. I run task "Memory cleanup" but nothing change.
