### ISSUE TITLE
Broken Switches in User Map Settings dialog - Click on Text instead of Switch

### ISSUE THREAD

**Issue by KernelSailor** [immich-app/immich#16603]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

When you try to show photos of your partner in the web app, the toggle button is grayed out and in the center.

![Image](https://github.com/user-attachments/assets/edb73943-00d7-478c-9b71-0411def25f48)

In the mobile App (for Android tested) partner photos can be shown on the Map.

### The OS that Immich Server is running on

ubuntu server with docker

### Version of Immich Server

1.128.0

### Version of Immich Mobile App

1.128.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped



#############
#Machine Learning cointainer also present and working, but not in this config
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/imagepath
DB_DATA_LOCATION=/mnt/dockerdata/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=<something>
DB_USERNAME=<db-user>
DB_DATABASE_NAME=<db-name>
TZ=Europe/Berlin
IMMICH_TRUSTED_PROXIES=<some-IPs>
```

### Reproduction steps

1. upload some pictures from multiple accounts
2. enable partner sharing from one account
3. try to view the pictures in the map for both accounts (via the sharing function)

### Relevant log output

```shell

```
