### ISSUE TITLE
Downloading album slow and has misleading progress bar

### ISSUE THREAD

**Issue by rhyst** [immich-app/immich#16609]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When downloading an album from web there is a long time before the browser actually starts downloading. Presumably this is while the files are being zipped. This does not seem to improve after it has been downloaded once (i.e. the archive does not seem to be cached). In addition there is a progress popup that just displays 100% which is confusing and does not give an indication that anything is actually happening.

![Image](https://github.com/user-attachments/assets/1247b5c3-d0ba-48ab-9b6c-55e308fa44a2)

### The OS that Immich Server is running on

Ubuntu 20.04.6 LTS

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# This is ansible but broadly similair
- name: start immich redis container
  become: true
  docker_container:
    name: immich-redis
    image: "registry.hub.docker.com/library/redis:{{ immich_redis_version }}"
    state: started
    recreate: true
    restart: true
    restart_policy: unless-stopped
    networks:
      - name: all
      - name: immich-network
        aliases:
          - immich_redis
    container_default_behavior: no_defaults
  tags: [immich]

- name: start immich postgres container
  become: true
  docker_container:
    name: immich-postgres
    image: "registry.hub.docker.com/tensorchord/pgvecto-rs:{{ immich_postgres_version }}"
    state: started
    recreate: true
    restart: true
    restart_policy: unless-stopped
    env: "{{ default_immich_db_env_yaml | combine(immich_db_env_yaml) }}"
    volumes: "{{ default_immich_db_volumes + immich_db_volumes }}"
    networks:
      - name: all
      - name: immich-network
        aliases:
          - immich_postgres
    container_default_behavior: no_defaults
  tags: [immich]

- name: Start immich server container
  become: true
  docker_container:
    name: immich-server
    image: "ghcr.io/immich-app/immich-server:{{ immich_version }}"
    state: started
    recreate: true
    restart: true
    restart_policy: unless-stopped
    env: "{{ default_immich_env_yaml | combine(immich_env_yaml) }}"
    volumes: "{{ default_immich_volumes + immich_volumes }}"
    networks:
      - name: all
      - name: immich-network
        aliases:
          - immich_server
    container_default_behavior: no_defaults
  tags: [immich]

- name: Start immich machine learning container
  become: true
  docker_container:
    name: immich-machine-learning
    image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_version }}"
    state: started
    recreate: true
    restart: true
    restart_policy: unless-stopped
    env: "{{ default_immich_machine_learning_env_yaml | combine(immich_machine_learning_env_yaml) }}"
    volumes: "{{ default_immich_machine_learning_volumes + immich_machine_learning_volumes }}"
    networks:
      - name: all
      - name: immich-network
        aliases:
          - immich_machine_learning
    container_default_behavior: no_defaults
  tags: [immich]
```

### Your .env content

```Shell
immich_version: v1.128.0
immich_redis_version: 6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
immich_postgres_version: pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

# Immich api and workers

immich_directories:
  - "/srv/immich/"
  - "/srv/immich/model-cache"
  - "/srv/immich/db"

immich_images:
  - "ghcr.io/immich-app/immich-server:{{ immich_version }}"
  - "ghcr.io/immich-app/immich-machine-learning:{{ immich_version }}"
  - "registry.hub.docker.com/library/redis:{{ immich_redis_version }}"
  - "registry.hub.docker.com/tensorchord/pgvecto-rs:{{ immich_postgres_version }}"

default_immich_volumes:
  - /etc/localtime:/etc/localtime:ro
  - "{{ storage_path }}/AppData/Immich:/usr/src/app/upload"
  - "{{ storage_path }}/Pictures/library:/usr/src/app/upload/library" 
  - "{{ storage_path }}/:/mnt/media/storage"

immich_volumes: []

default_immich_env_yaml:
  TZ: "Europe/London"
  PUID: "{{ service_user_id }}"
  PGID: "{{ service_group_id }}"
  UMASK: "002"
  DB_PASSWORD: "{{ vault_immich_db_password }}"
  DB_HOSTNAME: immich_postgres
  DB_USERNAME: postgres
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: immich_redis

immich_env_yaml: {}

# Immich machine learning

default_immich_machine_learning_volumes:
  - "/srv/immich/model-cache:/cache"

immich_machine_learning_volumes: []

default_immich_machine_learning_env_yaml: "{{ default_immich_env_yaml }}"

immich_machine_learning_env_yaml: {}

# Immich db

default_immich_db_volumes:
  - "/srv/immich/db:/var/lib/postgresql/data"

immich_db_volumes: []

default_immich_db_env_yaml:
  POSTGRES_DB: immich
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "{{ vault_immich_db_password }}"

immich_db_env_yaml: {}
```

### Reproduction steps

1. Create an album
2. Download the album

### Relevant log output

```shell
[Nest] 20  - 03/05/2025, 12:54:11 PM   DEBUG [Api:LoggingInterceptor~b3yo30d5] POST /api/download/archive 200 78.44ms 109.150.80.173
[Nest] 20  - 03/05/2025, 12:54:11 PM VERBOSE [Api:LoggingInterceptor~b3yo30d5] {"assetIds":["84aeedca-98a4-4462-90bf-909c61843361","58dab327-ae7d-4807-8cc0-89fb0cfd92fb","f388ea0b-be90-47c1-9e29-0f7d877e8393","f65bed23-dc69-43ab-8f1c-55c52a0d0e19","03d3fd08-b159-4b63-aab3-cdcbce0c416f","c1a14ff5-d45c-49c6-b163-887d6dff0d95","573e509e-b71c-4869-8023-675d0bbfc0c3","ff458623-182d-415c-a6bb-ddb5ac2e674d","c9306a7b-e54d-4bf3-9bff-0fea0521c70f","d3f4ae31-b817-49b7-802b-79ac2795e9ac","f28011fb-3040-486c-b09b-ed168ce2e06a","27fc394e-281e-4831-ab1a-6297d621d548","78965e0c-a352-441b-9c89-9681bd996918","7fe64129-0b93-435a-bb02-ac8242fee2b8","10d03530-7c39-4a2a-94e6-16784115d5d9","19d92b3f-3319-49f5-903a-426b0250a5c5","a2471610-3425-4785-a483-bb8f65c3dcdd","ee717976-813a-4cd2-ac65-0396776acaf6","e790579b-74ae-40f8-84f5-a7700b927d04","35366bc8-8dfb-45a8-99ef-a83ddf8b5d91","0391781a-8416-47d5-b6a8-3986908a74ff","941310c6-8d33-4b52-9a1b-f4bad14b38b1","981e42f0-5607-4ed7-a18f-51df12a2363c","2de2f343-d46c-4983-babb-7aaf61c6c59c","d47768f2-8bd4-4ab0-9cc6-f251f0736936","90db080a-1311-4f5f-9b88-d516cc0fa303","e2144149-4eda-4475-8bda-5028b6568bae","6f0de64c-ce6b-4ddc-a2e1-519a8b289ba0","af9bdaed-2ce6-4d5a-875c-dfdde12a64c2","ba32f71a-57df-49f7-85fe-e81ec6e4c208","d3dbea7d-3f6a-4d44-aa49-ccc2238d37c0","378e8a2c-1c73-4cde-9f8e-507ff2f798ef","bf0aba4d-2d0b-4d2f-97a8-29d6539e1b87","8c063a15-8f05-4bc9-b5f8-b7ff44963601","87ac7de6-2111-48eb-9a5a-43836951bf57","b234d1f8-1032-42a1-9dc4-30a9118966fb","8d540f32-efc5-4d29-8dcb-287226647218","4d5c33b9-b264-40fc-8e61-f4eff6994939","8d0560cd-ca45-49e7-89d6-578563403e62","37b1dab3-a8c4-41b0-ba4a-0e648e5768d2","040557f1-b90f-4392-83b2-e525250d34d5","c8ca8abd-6058-43f8-8970-3eba9f5c018e","82478008-e6d2-4b94-bc82-72e6dc69b8c3","af8f6289-c22e-4efc-bd60-37a63183562b","ec39d215-2a38-4801-a42c-3035dec3a734","d9edbebf-9ac0-4801-96ce-7f6ff2dd0c56"]}
```

### Additional information

Tried in Firefox, Firefox mobile, and Chrome.
