### ISSUE TITLE
Immich Service restarting in a loop after upgrade

### ISSUE THREAD

**Issue by lippelae** [immich-app/immich#16625]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello,

I have been running immich in portainer for over a year now, and applying updates as they have been released.  I'm currently running 1.127.0, and its solid.  I have tried to update to 1.128.0 and 1.129.0, and every time the immich_server service keeps flapping.  It starts and stops.  I have to revert my snapshot each time I try to update.  I'm not docker expert, and kind of stuck to why the service is flapping.  Any help would be appreciated.  
Thanks

### The OS that Immich Server is running on

Ubuntu 22.04.5

### Version of Immich Server

1.127.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#Old Command    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

#Microservices module no longer needed
#  immich-microservices:
#   container_name: immich_microservices
#    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
#    command: ['start.sh', 'microservices']
#    volumes:
#      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - ${EXTERNAL_PATH}:/usr/src/app/external
#      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - stack.env
#    depends_on:
#      - redis
#      - database
#   restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=default values
DB_HOSTNAME=immich_postgres
DB_USERNAME=default values
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1.Log into portainer, re-pull image to update
2.Once the update completes all services start, except the the immich_server service.  It starts and stops.
3.
...

### Relevant log output

```shell

```

### Additional information

This is currently running in vmware 8.0U3. 4 vCPU 8Gig Ram.
Running the docker stack in portainer.  (Latest version)
Hardware, Cisco UCS c220M5.
