### ISSUE TITLE
Sidebar: Text cropped if is to long

### ISSUE THREAD

**Issue by MickLesk** [immich-app/immich#16637]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi all, 😄 

a little prio z issue. When i open the Administration, there are the "external library" cropped, because its in german a little bit longer. 

I had first considered opening a PR to dynamically determine the width, but I think that breaks the conventions in this case. That's why I decided against a PR, because you can make a better decision.

It's just a visual issue. With albums, for example, the name is ... and a mouseover with the full text is possible. However, I find this somehow quite unnecessary for the admin page, where (in my opinion) a dynamic layout would be better. But I'm also not a frontend dev. So I'm happy to pass this on to you :-)

Image:
![Image](https://github.com/user-attachments/assets/903c52ec-fe9d-48c5-91dd-03762c9810c3)

Affected Code-Line
https://github.com/immich-app/immich/blob/c110c9b00e5ad1625bbe9871afbb7ed1ba257e08/web/src/lib/components/shared-components/side-bar/side-bar-section.svelte#L14

### The OS that Immich Server is running on

Docker-LXC Debian 12 with Portainer

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"


volumes:
  model-cache:
  pgdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=*****************
DB_HOSTNAME=*********
DB_USERNAME=*******
DB_DATABASE_NAME=******
REDIS_HOSTNAME=**********
DB_DATA_LOCATION=./postgres
```

### Reproduction steps

1. Open Immich WebUI
2. Click on User Icon (upper right)
3. Click on Administration

(maybe change lang. to german) 

Affected site: 
url.immich.photo**/admin/user-management**

### Relevant log output

```shell

```

### Additional information

Immich
[v1.129.0](https://github.com/immich-app/immich/releases/tag/v1.129.0)
ExifTool
13.00

Node.js
v22.13.1

Libvips
8.15.3

ImageMagick
7.1.1-40

FFmpeg
7.0.2-7

Repository
[immich-app/immich](https://github.com/immich-app/immich)
Quellcode
[v1.129.0@31dd15ce8](https://github.com/immich-app/immich/commit/31dd15ce8afc86b40c033ded906c2e7a5173ef11)
Build
[13684778336](https://github.com/immich-app/immich/actions/runs/13684778336)
Build Abbild
[v1.129.0](https://github.com/immich-app/immich/pkgs/container/immich-server)
