### ISSUE TITLE
Error message:Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')

### ISSUE THREAD

**Issue by colaKot** [immich-app/immich#16641]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When upgrading to 1.129.0, I retrieved one-dimensional data again, but it remained stuck and could not be executed. Upon checking the logs, I found an error
This error also occurs when restarting, 
Maybe I set it up before
- "D:/docker/imm/geodata:/build/geodata"
- "D:/docker/imm/i18n-iso-countries/langs:/usr/src/app/node_modules/i18n-iso-countries/langs"

Used to obtain Chinese GPS decompilation

### The OS that Immich Server is running on

Windows 11  Wsl2  DockerDesktop

### Version of Immich Server

1.129.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "D:/winnas/photos:/mnt/photos:rm"
      - "D:/winnas/gexuan/Photos:/mnt/gxphotos:rm"
      - "D:/winnas/bibi/Photos:/mnt/bibiphotos:rm"
      - "D:/winnas/share:/mnt/share:rm"
    env_file:
      - .env
    ports:
      - '88:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - "D:/docker/imm/model:/cache"
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=D:/winnas/photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

MACHINE_LEARNING_PRELOAD__CLIP=XLM-Roberta-Large-Vit-B-16Plus
```

### Reproduction steps

1.Directly start, it will appear
2.
3.
...

### Relevant log output

```shell
immich_server            | Initializing Immich v1.129.0
immich_server            | Detected CPU Cores: 10
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 03/06/2025, 9:09:06 AM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | [Nest] 19  - 03/06/2025, 9:09:06 AM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | [Nest] 7  - 03/06/2025, 9:09:06 AM   ERROR [Microservices:{"id":"cf31178c-2f5b-419d-8222-dd5840b063a5"}] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            | TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            |     at mapUpsertColumns (/usr/src/app/dist/utils/database.js:25:49)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:126
immich_server            |     at parseUpdateObjectExpression (/usr/src/app/node_modules/kysely/dist/cjs/parser/update-set-parser.js:20:67)
immich_server            |     at OnConflictBuilder.doUpdateSet (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/on-conflict-builder.js:198:81)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:76
immich_server            |     at InsertQueryBuilder.onConflict (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/insert-query-builder.js:607:29)
immich_server            |     at AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:55:14)
immich_server            |     at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:172:36)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich_server            | [Nest] 7  - 03/06/2025, 9:09:06 AM   ERROR [Microservices:{"id":"e72a9074-0dd5-4e9e-93f6-2fa88c416472"}] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            | TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            |     at mapUpsertColumns (/usr/src/app/dist/utils/database.js:25:49)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:126
immich_server            |     at parseUpdateObjectExpression (/usr/src/app/node_modules/kysely/dist/cjs/parser/update-set-parser.js:20:67)
immich_server            |     at OnConflictBuilder.doUpdateSet (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/on-conflict-builder.js:198:81)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:76
immich_server            |     at InsertQueryBuilder.onConflict (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/insert-query-builder.js:607:29)
immich_server            |     at AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:55:14)
immich_server            |     at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:172:36)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich_server            | [Nest] 7  - 03/06/2025, 9:09:07 AM   ERROR [Microservices:{"id":"c5c25901-4a4b-45b2-9006-61143ba77977"}] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            | TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
immich_server            |     at mapUpsertColumns (/usr/src/app/dist/utils/database.js:25:49)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:126
immich_server            |     at parseUpdateObjectExpression (/usr/src/app/node_modules/kysely/dist/cjs/parser/update-set-parser.js:20:67)
immich_server            |     at OnConflictBuilder.doUpdateSet (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/on-conflict-builder.js:198:81)
immich_server            |     at /usr/src/app/dist/repositories/asset.repository.js:55:76
immich_server            |     at InsertQueryBuilder.onConflict (/usr/src/app/node_modules/kysely/dist/cjs/query-builder/insert-query-builder.js:607:29)
immich_server            |     at AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:55:14)
immich_server            |     at MetadataService.handleMetadataExtraction (/usr/src/app/dist/services/metadata.service.js:172:36)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich_server            | [Nest] 7  - 03/06/2025, 9:09:07 AM   ERROR [Microservices:{"id":"189e14a0-e617-4bf0-84c1-a85948c5ce62"}] Unable to run job handler (metadataExtraction/metadata-extraction): TypeError: Cannot read properties of undefined (reading 'dateTimeOriginal')
```
