### ISSUE TITLE
Photos not showing as backed up

### ISSUE THREAD

**Issue by krishne35** [immich-app/immich#16676]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

So I switched to new phone on March 02 after installing and logging in with immich all photos shows up and when I select to backup everything it just backups all the photos which shows up in web page
But on the app it still shows as not backed up (small cloud icon on the corner of photo) but the backup page shows all the photos are backed up
I Uninstalled reinstalled immich
Cleaed duplicate
Logged out and logged back in

![Image](https://github.com/user-attachments/assets/b2c4d3e2-ab92-4f97-b1ec-0f74b025d72c)
![Image](https://github.com/user-attachments/assets/0e83cb5e-886f-400d-ab0d-7d56b91f89e3)

### The OS that Immich Server is running on

Alpine + Docker on prpxmox

### Version of Immich Server

1.29

### Version of Immich Mobile App

1.29

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    command: ['start.sh', 'immich']
    group_add:
      - '106'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
#    image: ghcr.io/krishne35/immich-machine-learning:main-openvino
#    image: ghcr.io/snuupy/immich-machine-learning:v1.107.2-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - immich-model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    group_add:
      - '107'
    devices:
      - /dev/dri/
    device_cgroup_rules:
      - "c 189:* rmw"
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    volumes:
      - immich-redis:/data
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
volumes:
  immich-model-cache:
    external: true
  immich-redis:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/NVME/immich/library
DB_DATA_LOCATION=/mnt/NVME/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=immich_postgress
DB_DATABASE_NAME=immich
DB_HOSTNAME=immich_postgres
REDIS_HOSTNAME=immich_redis
IMMICH_LOG_LEVEL=log
```

### Reproduction steps

1.Install immich on new phone 
2.login to immich
3.Upload photos
4.Will show up in web but doesn't show in mobile as backed up :(

...

### Relevant log output

```shell
Getting this error in application tho
#0      AssetResponseDto.fromJson (package:openapi/model/asset_response_dto.dart:291)
#1      ApiClient.fromJson (package:openapi/api_client.dart:264)
#2      ApiClient.fromJson.<anonymous closure> (package:openapi/api_client.dart:677)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:385)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:354)
#5      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:163)
#6      new _List.of (dart:core-patch/array.dart:128)
#7      new List.of (dart:core-patch/array_patch.dart:39)
#8      ListIterable.toList (dart:_internal/iterable.dart:224)
#9      ApiClient.fromJson (package:openapi/api_client.dart:678)
#10     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#11     SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:147)
<asynchronous suspension>
#12     AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:150)
<asynchronous suspension>
#13     SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:267)
<asynchronous suspension>
#14     SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:257)
<asynchronous suspension>
#15     SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:92)
<asynchronous suspension>
#16     AssetService.refreshRemoteAssets (package:immich_mobile/services/asset.service.dart:90)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:67)
<asynchronous suspension>
#18     AppLifeCycleNotifier.handleAppResume (package:immich_mobile/providers/app_life_cycle.provider.dart:70)
<asynchronous suspension>
```
