### ISSUE TITLE
No fallback when browser cannot stream original video

### ISSUE THREAD

**Issue by Ashex** [immich-app/immich#16688]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When a video is opened in the browser and played, if it is not able to be streamed by the browser an error `Video cannot be played because the file is corrupt` is displayed when in fact the browser simply doesn't support the codec.

For the video I'm playing, Firefox cannot stream it due to YUV444 chrome subsampling [1]. It can be played when downloaded. If I force transcoding of the video, immich does not play the transcode and shows the same error. Debug logs show that it did succeed in transcoding it. 

I would expect immich to fallback to the transcoded video or at least provide the option.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1368063

#### Codec info

```
General
Complete name                            : MVI_0125.AVI
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format settings                          : BitmapInfoHeader / PcmWaveformat
File size                                : 1.58 MiB
Duration                                 : 6 s 133 ms
Overall bit rate                         : 2 158 kb/s
Frame rate                               : 15.000 FPS
Mastered date                            : 2003-12-17 17:34:51
Writing application                      : CanonMVI01

Video
ID                                       : 0
Format                                   : JPEG
Codec ID                                 : MJPG
Duration                                 : 6 s 133 ms
Bit rate                                 : 2 064 kb/s
Width                                    : 320 pixels
Height                                   : 240 pixels
Display aspect ratio                     : 4:3
Frame rate                               : 15.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 1.791
Stream size                              : 1.51 MiB (96%)

Audio
ID                                       : 1
Format                                   : PCM
Format settings                          : Unsigned
Codec ID                                 : 1
Duration                                 : 6 s 133 ms
Bit rate mode                            : Constant
Bit rate                                 : 88.2 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 11.024 kHz
Bit depth                                : 8 bits
Stream size                              : 66.0 KiB (4%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 876  ms (13.14 video frames)
Interleave, preload duration             : 1000  ms
```

### The OS that Immich Server is running on

Fedora 41

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

1.128.0 build.196

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/Pictures:/mnt/media/Picture
      - /media/Dropbox/Camera Uploads:/mnt/media/Camera
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /media/cache/immchi:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/cache/immchi/uploads
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=secret

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=secret
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. In immich web browse to a video with YUVV444 color subsampling, 
2. Hover of video and see red exclamation icon appear

<img width="287" alt="Image" src="https://github.com/user-attachments/assets/fb067339-8d3b-48a8-86c5-dfe1bd8d0340" />

4. Click on video to open it
5. Click Play

<img width="727" alt="Image" src="https://github.com/user-attachments/assets/0fa43187-01e3-4459-a2cc-42e1205fe205" />

### Relevant log output

```shell
[Nest] 7  - 03/07/2025, 11:09:47 AM     LOG [Microservices:MediaService] Transcoding video 45fc8bc2-233e-4d62-8764-a79dd98c0e82 with NVENC-accelerated encoding and decoding
[Nest] 7  - 03/07/2025, 11:09:47 AM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -hwaccel cuda -hwaccel_output_format cuda -noautorotate -threads 1 -i /mnt/media/Picture/Misc/untitled folder/101CANON/MVI_0125.AVI -y -tune hq -qmin 0 -rc-lookahead 20 -i_qfactor 0.75 -c:v h264_nvenc -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -g 256 -v verbose -vf format=nv12 -preset p1 -cq:v 23 upload/encoded-video/ce19b8b7-d573-42a7-a274-1c6b213de504/45/fc/45fc8bc2-233e-4d62-8764-a79dd98c0e82.mp4
[Nest] 7  - 03/07/2025, 11:09:48 AM   DEBUG [Microservices:MediaRepository] ffmpeg -n 10 /usr/bin/ffmpeg -init_hw_device cuda=cuda:0 -filter_hw_device cuda -i /mnt/media/Picture/Misc/untitled folder/101CANON/MVI_0125.AVI -y -tune hq -qmin 0 -rc-lookahead 20 -i_qfactor 0.75 -c:v h264_nvenc -c:a aac -movflags faststart -fps_mode passthrough -map 0:0 -map 0:1 -g 256 -v verbose -vf hwupload_cuda -preset p1 -cq:v 23 upload/encoded-video/ce19b8b7-d573-42a7-a274-1c6b213de504/45/fc/45fc8bc2-233e-4d62-8764-a79dd98c0e82.mp4
[Nest] 7  - 03/07/2025, 11:09:48 AM   DEBUG [Microservices:MediaRepository] Transcoding 100.00% done for output 45fc8bc2-233e-4d62-8764-a79dd98c0e82.mp4
[Nest] 7  - 03/07/2025, 11:09:48 AM     LOG [Microservices:MediaService] Successfully encoded 45fc8bc2-233e-4d62-8764-a79dd98c0e82
```

### Additional information

Mozilla Firefox 136.0b9 (aarch64) console output

```
Go European content script loaded content.js:2:9
Media resource https://totallyawebsite.com/api/assets/45fc8bc2-233e-4d62-8764-a79dd98c0e82/video/playback?c=GfgJFYJmiXaPmmZliceHilqCYCYJ could not be decoded. 45fc8bc2-233e-4d62-8764-a79dd98c0e82
Current hostname: totallyawebsite.com Current URL: https://totallyawebsite.com/folders/photos/45fc8bc2-233e-4d62-8764-a79dd98c0e82?path=mnt%2Fmedia%2FPicture%2FMisc%2Funtitled+folder%2F101CANON content.js:8:13
Response from background: 
Object { alternatives: [] }
content.js:25:21
Media resource https://totallyawebsite.com/api/assets/45fc8bc2-233e-4d62-8764-a79dd98c0e82/video/playback?c=GfgJFYJmiXaPmmZliceHilqCYCYJ could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_FATAL_ERR (0x806e0005)
Details: auto mozilla::SupportChecker::AddMediaFormatChecker(const TrackInfo &)::(anonymous class)::operator()() const: Decoder may not have the capability to handle the requested video format with YUV444 chroma subsampling. 45fc8bc2-233e-4d62-8764-a79dd98c0e82
The resource at “https://totallyawebsite.com/_app/immutable/assets/OverpassMono.XkUhFDDw.ttf” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. 45fc8bc2-233e-4d62-8764-a79dd98c0e82
```
