### ISSUE TITLE
Fetch fail with 1.129.0

### ISSUE THREAD

**Issue by jyvern** [immich-app/immich#16687]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Until today everything works well. I've change the model to immich-app/antelopev2 and redo facial recognition. Everything has worked fine. Then I uploaded a new set (about more than 3000 assets) and laundh the process of "face detection" and "facial recognition". Then I see for every asset an error in the logs every 5 minutes.

If I upload from my mobile an asset (I use "sharing with Immich" approach on my mobile to tranfer the asset), the asset is well analyzed.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

V1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    ###    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik_lan
      - traefik.http.routers.immich.rule=Host(`xxx.yyy.zzz`)
      - traefik.http.routers.immich.entrypoints=https
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.service=immich
      - traefik.http.services.immich.loadbalancer.server.port=2283
    healthcheck:
      disable: false
    networks:
      traefik_lan:

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./data/model-cache:/cache
    env_file:
      - .env
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      disable: false
    networks:
      traefik_lan:

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      traefik_lan:

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      traefik_lan:

networks:
  traefik_lan:
    external: true

volumes:
  nas-immich:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=aaa.bbb.ccc.ddd,nolock,soft,rw
      device: :/volume1/immich
```

### Your .env content

```Shell
UPLOAD_LOCATION=nas-immich

IMMICH_VERSION=release

DB_HOSTNAME=immich_postgres
DB_USERNAME=yyyyyyyy
DB_PASSWORD=zzzzzzzz
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./data/pgdata

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. I go to the admin page of the immich server
2. I ask to lauch the procees of treating the asset that have not be analyzed (I've about 3067)
3. It takes a long time for the server to give an error (about 5 minutes)
...

### Relevant log output

```shell
immich_server            | [Nest] 8  - 03/07/2025, 10:08:29 AM   ERROR [Microservices:{"id":"f9fe6542-4ca4-418e-bc8c-eecbbdbd1382"}] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"antelopev2","options":{"minScore":0.7}},"recognition":{"modelName":"antelopev2"}}}' failed for all URLs
immich_server            | Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"antelopev2","options":{"minScore":0.7}},"recognition":{"modelName":"antelopev2"}}}' failed for all URLs
immich_server            |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:97:15)
immich_server            |     at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:106:26)
immich_server            |     at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:239:52)
immich_server            |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich_server            |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server            |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server            |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```
