### ISSUE TITLE
401 with fresh admin API keys

### ISSUE THREAD

**Issue by christopherarter** [immich-app/immich#16695]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm attempting to make requests to the Immich API. 

- Any request I send gives me a 401
- API key is for the admin account
- Neither fresh nor existing keys work
- Attempted to use `IMMICH_API_KEY` but does not work.

CURL request (with actual values removed)
```
curl --request POST \
  --url <immich-url-here>/api/search/metadata \
  --header 'accept: application/json' \
  --header 'authorization: Bearer <token-here>' \
  --header 'content-type: application/json' \
  --data '{
  "createdAfter": "2025-03-01T15:09:28Z"
}'
```
Result for all requests:
```
{
  "message": "Invalid user token",
  "error": "Unauthorized",
  "statusCode": 401,
  "correlationId": "onqvdlfa"
}
```

Oddly enough, `immich-go` export tool works with the given keys. 

### The OS that Immich Server is running on

Linux Mint 22.1

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

NA

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: Make sure to use the docker-compose.yml of the current release:
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
# The compose file on main may not be compatible with the latest release.

name: immich

services:


  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # Hardware acceleration configuration (uncomment if needed)
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu  # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    environment:
      IMMICH_API_KEY: ${IMMICH_API_KEY}

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # Hardware acceleration configuration (uncomment if needed)
    # extends:
    #   file: hwaccel.ml.yml
    #   service: cpu  # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/storage/immich_data/upload
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_API_KEY=<key here>
```

### Reproduction steps

1. Create API token in admin profile
2. Run curl request to any endpoint using bearer token auth
3. See 401 response

### Relevant log output

```shell

```
