### ISSUE TITLE
Partial Uploads

### ISSUE THREAD

**Issue by nkrabben** [immich-app/immich#16709]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

In the past few versions, upload stopped working on my instance, but only for media. Files are successfully parsed, checked for duplicates, and then an XMP file is created in the expected location in uploads, but the media file can't be written there.

In the web interface I get an error, "Unable to upload file". From the logs, I get an error about utime issues.

AFter the failed upload, there is a broken thumbnail image. I can edit that broken image's metadata and the xmp file and database can be updated, but since the media file never made it, there is no image to view unless I manually upload it to the correct location.

This also occurs on mobile uploads and with all file formats.

If the file upload fails, I'd prefer that no additional database or xmp records get created.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    user: 0:0
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on -c
      listen_addresses='*'
    restart: always
volumes:
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/data
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

## db password stuff
```

### Reproduction steps

1. Upload file
2. Wait for upload to fail
3. Find emptyish record in app/web

### Relevant log output

```shell
immich_server            | [Nest] 17  - 03/07/2025, 9:47:46 PM   ERROR [Api:AssetMediaService~u8np5bqj] Error uploading file Error: EPERM: operation not permitted, utime 'upload/upload/319f2ac9-7e6a-422c-9799-2c829003a1de/91/60/9160beab-e77c-4c77-a5fe-31fc13f78079.png'
immich_server            | Error: EPERM: operation not permitted, utime 'upload/upload/319f2ac9-7e6a-422c-9799-2c829003a1de/91/60/9160beab-e77c-4c77-a5fe-31fc13f78079.png'
immich_server            |     at async Object.utimes (node:internal/fs/promises:1132:10)
immich_server            |     at async AssetMediaService.create (/usr/src/app/dist/services/asset-media.service.js:281:9)
immich_server            |     at async AssetMediaService.uploadAsset (/usr/src/app/dist/services/asset-media.service.js:100:27)
immich_server            |     at async AssetMediaController.uploadAsset (/usr/src/app/dist/controllers/asset-media.controller.js:40:29)
immich_server            | [Nest] 17  - 03/07/2025, 9:47:46 PM   DEBUG [Api:LoggingInterceptor~u8np5bqj] POST /api/assets 201 9.77ms ::ffff:192.168.0.144
immich_server            | [Nest] 17  - 03/07/2025, 9:47:46 PM   DEBUG [Api:GlobalExceptionFilter~u8np5bqj] HttpException(500): {"message":"Failed to upload asset","error":"Internal Server Error","statusCode":500}
```
