### ISSUE TITLE
Redis: Unable to generate thumbnails when run as non-root

### ISSUE THREAD

**Issue by bradley-rose** [immich-app/immich#16719]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Thumbnail generation job isn't able to be executed when run as non-root user.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    user: 1003:1003
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    user: 1003:1003
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    user: 1003:1003
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    user: 1003:1003
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
# This is an NFS mount of which UID/GID 1003 have r/w permissions
UPLOAD_LOCATION=/mnt/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Vancouver

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<Omitted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Login to the web interface
2. Navigate to Administration settings
3. Click "All" or "Missing" on Generate Thumbnails
...

### Relevant log output

```shell
immich_server            | ReplyError: ERR Error running script (call to f_b4cd4bbdf096cd8d06246080315ae81c56e05a46): @user_script:222: @user_script: 222: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
immich_server            |     at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
immich_server            |     at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14) {
immich_server            |   command: {
immich_server            |     name: 'evalsha',
immich_server            |     args: [
immich_server            |       'b4cd4bbdf096cd8d06246080315ae81c56e05a46',
immich_server            |       '10',
immich_server            |       'immich_bull:duplicateDetection:wait',
immich_server            |       'immich_bull:duplicateDetection:active',
immich_server            |       'immich_bull:duplicateDetection:prioritized',
immich_server            |       'immich_bull:duplicateDetection:events',
immich_server            |       'immich_bull:duplicateDetection:stalled',
immich_server            |       'immich_bull:duplicateDetection:limiter',
immich_server            |       'immich_bull:duplicateDetection:delayed',
immich_server            |       'immich_bull:duplicateDetection:paused',
immich_server            |       'immich_bull:duplicateDetection:meta',
immich_server            |       'immich_bull:duplicateDetection:pc',
immich_server            |       'immich_bull:duplicateDetection:',
immich_server            |       '1741330645769',
immich_server            |       '',
immich_server            |       <Buffer de 00 03 a5 74 6f 6b 65 6e d9 26 66 36 38 30 39 39 35 61 2d 35 30 34 30 2d 34 33 39 37 2d 62 33 32 66 2d 65 33 64 64 32 38 33 64 63 36 36 34 3a 30 ac ... 24 more bytes>
immich_server            |     ]
immich_server            |   }
immich_server            | }
```
