### ISSUE TITLE
Global map shows empty

### ISSUE THREAD

**Issue by wulianer** [immich-app/immich#16726]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have been running Immich server through docker compose for a long while and it used to work well after several version updates.

Yesterday I upgraded the app from 1.126.0 to latest 1.129.0. 

The Map page shows an empty grey view there. No map gets loaded.

![Image](https://github.com/user-attachments/assets/fbd974c5-4a39-4590-8b2e-9740d50dc225)

Tried both Chrome and Safari browser from the same Mac and they showed the same issue.

So I rolled back the docker image version to 1.126.0 and the same issue still happened. I have not used this Map feature for a while so not sure from which version it started.

After checking the Chrome Developer Console, there are several web Fetch failure:

- https://static.immich.cloud/tiles/sprites/v1/light.json
- https://static.immich.cloud/tiles/sprites/v1/light.png
- https://static.immich.cloud/tiles/fonts/Noto%20Sans%20Italic/0-255.pbf
- https://static.immich.cloud/tiles/fonts/Noto%20Sans%20Medium/0-255.pbf
- https://static.immich.cloud/tiles/fonts/Noto%20Sans%20Regular/1024-1279.pb

I searched the key words 'light.json' in the repo and got several links like this:

https://tiles.immich.cloud/v1/style/light.json

So it looks like this is a web server config issue that causes these urls not accessible? CDN?

I disabled AD blocker in the browser. Still the same

### The OS that Immich Server is running on

RHEL 9

### Version of Immich Server

1.129.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0 
#    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee 
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/hide/for/pricy/immich-app/immich-data

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

#UPLOAD_MAX_SIZE=3G
EXTERNAL_PATH=/hide/for/pricy.  

TZ=America/Denver
```

### Reproduction steps

1. Open the web page to immich
2. Click 'Maps' from left sidebar menu
3.
...

### Relevant log output

```shell

```
