### ISSUE TITLE
ARMNN FP16 not working anymore

### ISSUE THREAD

**Issue by todorangrg** [immich-app/immich#16744]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Had immich setup for a couple of months on my CM3588 (rk3588 board). Everything was working fine, and I tested a bunch of models until settling to:
- smart search: ViT-L-14__laion2b-s32b-b82k
- facial recognition: anthelopev2
- MACHINE_LEARNING_ANN_FP16_TURBO=True

Even if the above do not have the top-level (fp32) model.armnn for some models, they do have the fp16 .armnn versions for all the models. This was working correctly and I could see the models loaded from the fp16 folder and running on the GPU.

Currently no FP16 models are ever loaded. Either the fp32 are (if the model exists) or the CPU version.

I can also confirm:
`docker exec -it immich_machine_learning env | grep MACHINE_LEARNING_*`
`MACHINE_LEARNING_ANN_FP16_TURBO=True`

### The OS that Immich Server is running on

Debian bookworm

### Version of Immich Server

V1.129.0

### Version of Immich Mobile App

V1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - video
    devices:
      - /dev/rga:/dev/rga
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mpp_service:/dev/mpp_service
      - /dev/mali0:/dev/mali0 # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
    volumes:
      - /etc/OpenCL:/etc/OpenCL:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      - /usr/lib/aarch64-linux-gnu/libmali.so.1:/usr/lib/aarch64-linux-gnu/libmali.so.1:ro # only required to enable OpenCL-accelerated HDR -> SDR tonemapping
      - ${UPLOAD_LOCATION}:/usr/src/app/upload # Do not this line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - '2283:2283'
    networks:
      - default   
      - reverse_proxy
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-armnn
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
      - /usr/lib/aarch64-linux-gnu/libmali.so:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)
      - ${MODEL_CACHE_LOCATION}:/cache
    env_file:
      - immich.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - default

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - default

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data # Do not edit this line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
  reverse_proxy:
    external: true
```

### Your .env content

```Shell
IMMICH_URL = "http://immich_server:2283"
EXTERNAL_IMMICH_URL = "redacted"
DB_HOST = "immich_postgres"
DB_PORT = "5432"

UPLOAD_LOCATION=/something/immich-library
DB_DATA_LOCATION=/something/immich-db
MODEL_CACHE_LOCATION=/somethingelse/immich_cache

TZ=sometimezone
IMMICH_VERSION=release

DB_PASSWORD=apassword
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

#IMMICH_LOG_LEVEL=debug
#MACHINE_LEARNING_ANN=True
#MACHINE_LEARNING_ANN_TUNING_LEVEL=2
MACHINE_LEARNING_ANN_FP16_TURBO=True
#MACHINE_LEARNING_MODEL_TTL=0
#MACHINE_LEARNING_PRELOAD__CLIP=immich-app/ViT-L-14__laion2b-s32b-b82k
```

### Reproduction steps

1. Trigger smart search textual by searching something
2. Trigger smart search visual by uploading a new file
3. Trigger facial detection/recognition in similar way

### Relevant log output

```shell
[03/09/25 09:05:02] INFO     Loading textual model 'ViT-L-14__laion2b-s32b-b82k'
                             to memory
[03/09/25 09:05:02] ERROR    Model file not found:
                             /cache/clip/ViT-L-14__laion2b-s32b-b82k/textual/mod
                             el.armnn
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:225 in _load               │
                             │                                                 │
                             │   222 │   │   │   raise HTTPException(500, f"Fa │
                             │   223 │   │   with lock:                        │
                             │   224 │   │   │   try:                          │
                             │ ❱ 225 │   │   │   │   model.load()              │
                             │   226 │   │   │   except FileNotFoundError as e │
                             │   227 │   │   │   │   if model.model_format ==  │
                             │   228 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/app/models/base.py:53 in load          │
                             │                                                 │
                             │    50 │   │   self.download()                   │
                             │    51 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    52 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │ ❱  53 │   │   self.session = self._load()       │
                             │    54 │   │   self.loaded = True                │
                             │    55 │                                         │
                             │    56 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/app/models/clip/textual.py:26 in _load │
                             │                                                 │
                             │    23 │   │   return serialize_np_array(res)    │
                             │    24 │                                         │
                             │    25 │   def _load(self) -> ModelSession:      │
                             │ ❱  26 │   │   session = super()._load()         │
                             │    27 │   │   log.debug(f"Loading tokenizer for │
                             │    28 │   │   self.tokenizer = self._load_token │
                             │    29 │   │   tokenizer_kwargs: dict[str, Any]  │
                             │                                                 │
                             │ /usr/src/app/models/base.py:78 in _load         │
                             │                                                 │
                             │    75 │   │   )                                 │
                             │    76 │                                         │
                             │    77 │   def _load(self) -> ModelSession:      │
                             │ ❱  78 │   │   return self._make_session(self.mo │
                             │    79 │                                         │
                             │    80 │   def clear_cache(self) -> None:        │
                             │    81 │   │   if not self.cache_dir.exists():   │
                             │                                                 │
                             │ /usr/src/app/models/base.py:104 in              │
                             │ _make_session                                   │
                             │                                                 │
                             │   101 │                                         │
                             │   102 │   def _make_session(self, model_path: P │
                             │   103 │   │   if not model_path.is_file():      │
                             │ ❱ 104 │   │   │   raise FileNotFoundError(f"Mod │
                             │   105 │   │                                     │
                             │   106 │   │   match model_path.suffix:          │
                             │   107 │   │   │   case ".armnn":                │
                             ╰─────────────────────────────────────────────────╯
                             FileNotFoundError: Model file not found:
                             /cache/clip/ViT-L-14__laion2b-s32b-b82k/textual/mod
                             el.armnn
[03/09/25 09:05:03] WARNING  ARMNN is available, but model
                             'ViT-L-14__laion2b-s32b-b82k' does not support it.
[03/09/25 09:05:03] INFO     Attempt #2 to load textual model
                             'ViT-L-14__laion2b-s32b-b82k' to memory
[03/09/25 09:05:03] INFO     Setting execution providers to
                             ['CPUExecutionProvider'], in descending order of
                             preference
[03/09/25 09:07:24] INFO     Downloading detection model 'antelopev2'. This may
                             take a while.
Fetching 7 files: 100%|██████████| 7/7 [00:11<00:00,  1.63s/it]
[03/09/25 09:07:35] INFO     Loading detection model 'antelopev2' to memory
[03/09/25 09:07:35] ERROR    Model file not found:
                             /cache/facial-recognition/antelopev2/detection/mode
                             l.armnn
                             ╭─────── Traceback (most recent call last) ───────╮
                             │ /usr/src/app/main.py:225 in _load               │
                             │                                                 │
                             │   222 │   │   │   raise HTTPException(500, f"Fa │
                             │   223 │   │   with lock:                        │
                             │   224 │   │   │   try:                          │
                             │ ❱ 225 │   │   │   │   model.load()              │
                             │   226 │   │   │   except FileNotFoundError as e │
                             │   227 │   │   │   │   if model.model_format ==  │
                             │   228 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/app/models/base.py:53 in load          │
                             │                                                 │
                             │    50 │   │   self.download()                   │
                             │    51 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    52 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │ ❱  53 │   │   self.session = self._load()       │
                             │    54 │   │   self.loaded = True                │
                             │    55 │                                         │
                             │    56 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/app/models/facial_recognition/detectio │
                             │ n.py:21 in _load                                │
                             │                                                 │
                             │   18 │   │   super().__init__(model_name, **mod │
                             │   19 │                                          │
                             │   20 │   def _load(self) -> ModelSession:       │
                             │ ❱ 21 │   │   session = self._make_session(self. │
                             │   22 │   │   self.model = RetinaFace(session=se │
                             │   23 │   │   self.model.prepare(ctx_id=0, det_t │
                             │   24                                            │
                             │                                                 │
                             │ /usr/src/app/models/base.py:104 in              │
                             │ _make_session                                   │
                             │                                                 │
                             │   101 │                                         │
                             │   102 │   def _make_session(self, model_path: P │
                             │   103 │   │   if not model_path.is_file():      │
                             │ ❱ 104 │   │   │   raise FileNotFoundError(f"Mod │
                             │   105 │   │                                     │
                             │   106 │   │   match model_path.suffix:          │
                             │   107 │   │   │   case ".armnn":                │
                             ╰─────────────────────────────────────────────────╯
                             FileNotFoundError: Model file not found:
                             /cache/facial-recognition/antelopev2/detection/mode
                             l.armnn
[03/09/25 09:07:35] WARNING  ARMNN is available, but model 'antelopev2' does not
                             support it.
[03/09/25 09:07:35] INFO     Attempt #2 to load detection model 'antelopev2' to
                             memory
[03/09/25 09:07:35] INFO     Setting execution providers to
                             ['CPUExecutionProvider'], in descending order of
                             preference
[03/09/25 09:07:36] INFO     Loading recognition model 'antelopev2' to memory
arm_release_ver: g13p0-01eac0, rk_so_ver: 11
[03/09/25 09:07:36] INFO     Loading ANN model
                             /cache/facial-recognition/antelopev2/recognition/mo
                             del.armnn ...
[03/09/25 09:07:41] INFO     Loaded ANN model with ID 0
```
