### ISSUE TITLE
[Android App] Video playback/download not working in-app for remote videos

### ISSUE THREAD

**Issue by jackroberts-gh** [immich-app/immich#16745]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**Issue**
Unable to play or download _remote_ (i.e. video stored on immich-server, not present on local device) on the Android Immich app. However, the videos can be played and downloaded via the Chrome browser on the device, and by other devices on the network using the Chrome browser. The only place it doesn't work is via the Immich Android app. Video format is an mp4. I haven't touched any transcode settings to change from the default.

Turning the log verbosity up on the logs in the app, the error is:

```
Error stopping video: MissingPluginException(No implementation found for method getPlaybackPosition on channel me.albemala.native._video_player.api.1) .. in NativeVideoViewerPage
```

**Affected Version(s)**
App v1.129.0 build.187

**Other information**
FWIW, possible other pertinent info:
1. Immich running on a Raspberry Pi 4b via docker compose
2. Using a self-signed cert, but application is set to "Allow self-signed SSL certificates". Root CA is installed/trusted on all devices mentioned.
3. Device is a Google Pixel 6a.

### The OS that Immich Server is running on

Raspbian (latest)

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0 build.187

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

  caddy:
    container_name: caddy
    image: caddy:2.9
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /opt/caddy/conf:/etc/caddy
      - /opt/caddy/site:/srv
      - /opt/caddy/caddy_data:/data
      - /opt/caddy/caddy_config:/config

volumes:
  model-cache:
  caddy_data:
  caddy_config:
```

### Your .env content

```Shell
# Immich
UPLOAD_LOCATION=/mnt/media/library
DB_DATA_LOCATION=/opt/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Via app, try to download a remote video not stored on local device
2. Observe that the loading icon just continually spins
3. Clicking "download" immediately returns a "Download failed for file <file>" toast notification

### Relevant log output

```shell
Error stopping video: MissingPluginException(No implementation found for method getPlaybackPosition on channel me.albemala.native._video_player.api.1) .. in NativeVideoViewerPage
```

### Additional information

See original issue info.
