### ISSUE TITLE
Restore command in documentation doesn't restore user data

### ISSUE THREAD

**Issue by digitalgenesiskompound** [immich-app/immich#16755]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When following the Immich docs for restoring a database, the suggested command uses:
```
sudo docker compose down -v  # CAUTION! Deletes all Immich data to start from scratch
## Uncomment the next line and replace DB_DATA_LOCATION with your Postgres path to permanently reset the Postgres database
# sudo rm -rf DB_DATA_LOCATION # CAUTION! Deletes all Immich data to start from scratch
sudo docker compose pull             # Update to latest version of Immich (if desired)
sudo docker compose create           # Create Docker containers for Immich apps without running them
sudo docker start immich_postgres    # Start Postgres server
sleep 10                        # Wait for Postgres server to start up
# Check the database user if you deviated from the default
sudo gunzip < "/home/ngk/immich/immich-db-backup-1741338000004.sql.gz" \
  | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
  | sudo docker exec -i immich_postgres psql --username=postgres --dbname=immich
sudo docker compose up -d            # Start remainder of Immich apps
sudo docker compose logs -f
```
While this command appears to run, no user data (and sometimes other table data) is actually restored. The tables might get created, but they end up empty (e.g., no users in the users table).

Why This Happens
By default, gunzip < file.gz does not send its decompressed content to stdout for further piping. It tries to decompress the file in place. As a result, the actual table rows never reach sed and psql. This leads to the restore completing with an empty or partial database (particularly missing user data).

### The OS that Immich Server is running on

Debian 12.9

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0 build.197

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data:rw
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/ngk/nas-storage/Immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/home/ngk/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=*************

IMMICH_SERVER_URL=https://immich.*************.net/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*****************

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create a backup with Immich’s built-in mechanism.
2. Attempt to restore in a fresh clean Immich environment, using the restore command in the Immich docs.
3. Observe that while the restore seems to run, the users table (and possibly others) ends up empty.

### Relevant log output

```shell
SET
SET
SET
ERROR:  cannot drop the currently open database
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists
ALTER ROLE
...
COPY 0
COPY 2
COPY 3714
COPY 0
COPY 1
COPY 832
COPY 5382
COPY 2696
COPY 0
...
```

### Additional information

Proposed Fix?
Update the docs to recommend using gunzip -c so the data is sent to stdout and properly piped into psql. For example:
```
sudo gunzip -c /home/ngk/immich/immich-db-backup-1741338000004.sql.gz | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" | sudo docker exec -i immich_postgres psql --username=postgres --dbname=immich 
```
With -c, the entire decompressed SQL stream is passed along, ensuring all tables and rows (including the users table) are restored. This worked for me... I am unsure if anyone else will even have this issue. I used AI to help diagnose and explain the issue as I also had to use AI to understand why I couldn't restore a **very important** backup. Thanks, hopefully this is proper and informative... :)
