### ISSUE TITLE
GENERATE THUMBNAILS fails with various errors

### ISSUE THREAD

**Issue by bugacha** [immich-app/immich#16774]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Whenever I re-generate THUMBNAILS I see following errors in `docker compose logs -f`

I don't know how identify photos / videos that cause them

I enabled IMMICH_LOG_LEVEL=verbose - buut no new information in the log, doesnt even log file name

`immich_server    | [Nest] 7  - 03/10/2025, 4:02:21 PM   ERROR [Microservices:{"id":"913a1559-5353-4b5e-92ce-851cac778ed6"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format

immich_server    | [Nest] 7  - 03/10/2025, 4:02:21 PM   ERROR [Microservices:{"id":"59b5c2f2-cef7-4995-8c9e-9f67c4a0351d"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: VipsJpeg: Message codes are not supported, error message is in msg_parm.s string

immich_server    | [Nest] 7  - 03/10/2025, 4:02:21 PM   ERROR [Microservices:{"id":"b214e20f-84a5-4d5f-92a2-fd4b0026eadf"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Unknown error`

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photos:/mnt/photos
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    hostname: redis
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - "5432:5432"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
```

### Your .env content

```Shell
REDIS_HOSTNAME=redis

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/immich/upload
# The location where your database files are stored
DB_DATA_LOCATION=/data/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Amsterdam

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=111

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

IMMICH_LOG_LEVEL=verbose
```

### Reproduction steps

1. Open Jobs and re-run Generate thumbnails
2. Go to docker folder and run `docker compose logs -f`

### Relevant log output

```shell
`immich_server    | [Nest] 7  - 03/10/2025, 4:02:21 PM   ERROR [Microservices:{"id":"5fc74035-ffc4-4e70-a772-f11b775874f2"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
immich_server    | Error: Input file contains unsupported image format
immich_server    |     at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
immich_server    |     at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
immich_server    |     at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
immich_server    |     at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
immich_server    |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server    |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_server    |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)`
```

### Additional information

Searching immich upload for ` find . -type f -iname "5fc74035-ffc4-4e70-a772-f11b775874f2*"` doesn't find anything
