### ISSUE TITLE
Can't scroll before February 2013 in my Timeline

### ISSUE THREAD

**Issue by smartVanture** [immich-app/immich#16788]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi, first of all, let me tell you how much I love Immich. 
My issue is, that in web view, I can never scroll past February 2013. Sometimes it gets stuck at 18th sometimes at 27th but it's always around that date. I have a large number of photos (over 400.000) and I'm wonderin, if there is a limit or what else might cause that problem? In my Android app however it's working fine. Searching/filtering by date before that date also works fine in the web version. 

### The OS that Immich Server is running on

Unraid 6.12.8

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_LOCATION}/photos:/mnt/media/photos
      - ${LIBRARY_LOCATION}/videos:/mnt/media/videos
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - traefik_default

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${CACHE_LOCATION}:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - traefik_default

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - traefik_default

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    networks:
      - traefik_default

volumes:
  model-cache:


networks:
  traefik_default:
    external: true
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Open Immich web
2. Scroll down via the right handed time line bar
3. Scrolling gets stuck at Feb. 2013
...

### Relevant log output

```shell
2025-03-11T00:17:49.127720605Z [Nest] 17  - 03/11/2025, 12:17:49 AM     LOG [Api:EventRepository] Websocket Disconnect: 13dSwLC2dS7PtJQbAACN
2025-03-11T00:17:50.810499629Z [Nest] 17  - 03/11/2025, 12:17:50 AM     LOG [Api:EventRepository] Websocket Connect:    OEsEtaL-ENFuvMvXAACT
2025-03-11T00:17:57.259707030Z [Nest] 17  - 03/11/2025, 12:17:57 AM     LOG [Api:EventRepository] Websocket Disconnect: OEsEtaL-ENFuvMvXAACT
2025-03-11T00:18:00.180637565Z [Nest] 17  - 03/11/2025, 12:18:00 AM     LOG [Api:EventRepository] Websocket Connect:    GaBkwSUevbzCpIJDAACV
2025-03-11T00:20:01.020703338Z [Nest] 17  - 03/11/2025, 12:20:01 AM     LOG [Api:EventRepository] Websocket Disconnect: GaBkwSUevbzCpIJDAACV
2025-03-11T00:20:40.868015055Z [Nest] 17  - 03/11/2025, 12:20:40 AM     LOG [Api:EventRepository] Websocket Connect:    w5KCP1TC8N7-y7R_AACX
```

### Additional information

I'm using Chrome 133.0.6943.142 and have also tested it on Firefox 136.0 and Edge 134.0.3124.5 - always same results.
