### ISSUE TITLE
can't start the immich-server container after version 1.123.0

### ISSUE THREAD

**Issue by sowensupgrade** [immich-app/immich#16830]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I tried multiple version 129, 128, 125.7 - all fail to get past this line
Initializing Immich v1.129.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 03/12/2025, 1:22:18 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 03/12/2025, 1:22:19 PM     LOG [Api:EventRepository] Initialized websocket server

It freezes for a while after that, and then the container eventually dies. I was on 122 for a while, but moved to 123 successfully, but couldn't move to any other versions I specified. Below are the logs

Initializing Immich v1.129.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 03/12/2025, 1:22:18 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 03/12/2025, 1:22:19 PM     LOG [Api:EventRepository] Initialized websocket server
Migration "AddTimeBucketIndices1734574016301" failed, error: deadlock detected
QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:8:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
    at async /usr/src/app/dist/services/database.service.js:96:17
    at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
  query: 'DROP INDEX "IDX_day_of_month"',
  parameters: undefined,
  driverError: error: deadlock detected
      at /usr/src/app/node_modules/pg/lib/client.js:535:17
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:8:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
      at async /usr/src/app/dist/services/database.service.js:96:17
      at async /usr/src/app/dist/repositories/database.repository.js:211:23 {
    length: 294,
    severity: 'ERROR',
    code: '40P01',
    detail: 'Process 67 waits for AccessExclusiveLock on relation 24599 of database 16384; blocked by process 57.\n' +
      'Process 57 waits for ShareLock on transaction 3940513; blocked by process 67.',
    hint: 'See server log for query details.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'deadlock.c',
    line: '1147',
    routine: 'DeadLockReport'
  },
  length: 294,
  severity: 'ERROR',
  code: '40P01',
  detail: 'Process 67 waits for AccessExclusiveLock on relation 24599 of database 16384; blocked by process 57.\n' +
    'Process 57 waits for ShareLock on transaction 3940513; blocked by process 67.',
  hint: 'See server log for query details.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'deadlock.c',
  line: '1147',
  routine: 'DeadLockReport'
}
microservices worker error: QueryFailedError: deadlock detected, stack: QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddTimeBucketIndices1734574016301.up (/usr/src/app/dist/migrations/1734574016301-AddTimeBucketIndices.js:8:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:203:9)
    at async /usr/src/app/dist/services/database.service.js:96:17
    at async /usr/src/app/dist/repositories/database.repository.js:211:23
microservices worker exited with code 1

### The OS that Immich Server is running on

ubuntu

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

not sure

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.3'

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.123.0
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - /media/nas/immich/:/usr/src/app/upload # /media/nas/owncloud-files/simon/files/elizabeth-laptop-photos/2023-02
      - /etc/localtime:/etc/localtime:ro
      - /media/nas/photos-and-videos:/laptop-photos
    environment:
      - IMMICH_IGNORE_MOUNT_CHECK_ERRORS=true
    depends_on:
      - redis
      - database
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.immich.entrypoints=web-secure"
        - "traefik.http.routers.immich.rule=Host(`photos.${DOMAIN}`)" # change hostname!
        - "traefik.http.routers.immich.tls=true"
        - "traefik.http.routers.immich.middlewares=secHeaders@file"
        - "traefik.http.services.immich-src.loadbalancer.server.port=2283" # set port the container listenes toimage: traefik/hydra:latest
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.128.0-openvino
    volumes:
      - /media/apps/immich/model-cache:/cache
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5


  immich-machine-learning2:
    image: ghcr.io/immich-app/immich-machine-learning:v1.128.0-openvino
    volumes:
      - /media/apps/immich/model-cache:/cache
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
  
  redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /media/apps/immich/postgres:/var/lib/postgresql/data
    #healthcheck:
     #test: >-
     #   pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
     #   Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
     #   --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
     #   echo "checksum failure count is $$Chksum";
     #   [ "$$Chksum" = '0' ] || exit 1
      #interval: 5m
      #start_interval: 30s
      #start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

networks:
  gateway:
    external: true

simon@localhost:/media/nas/config/compose$ vi immich/docker-compose.yml 

      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /media/apps/immich/postgres:/var/lib/postgresql/data
    #healthcheck:
     #test: >-
     #   pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
     #   Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
     #   --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
     #   echo "checksum failure count is $$Chksum";
     #   [ "$$Chksum" = '0' ] || exit 1
      #interval: 5m
      #start_interval: 30s
      #start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    networks:
      - gateway
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5

networks:
  gateway:
    external: true
```

### Your .env content

```Shell
same as .env online. mine has other secrets
```

### Reproduction steps

start server. ensure other dependencies succeed. server fails

### Relevant log output

```shell

```
