### ISSUE TITLE
There is no problem with the https connection of immich on both sides of IOS and WEB, but Android (Xiaomi 14, Android Simulator) will report a certificate error.

### ISSUE THREAD

**Issue by zhz-we** [immich-app/immich#16844]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**certificate**
![Image](https://github.com/user-attachments/assets/8f2e185d-fbbb-4cf3-82ce-8fca06538153)

There is no problem with the https connection of immich on both sides of IOS and WEB, but Android (Xiaomi 14, Android Simulator) will report a certificate error.
![Image](https://github.com/user-attachments/assets/8cd67298-4e19-4d1d-ae98-a52181942ee5)

**Nginx** 

server {
    listen 80;
    server_name ****.life;

    # 强制 HTTP 转 HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ****.life;

    # 允许大文件上传
    client_max_body_size 50000M;

    # 证书配置（根据实际路径调整）
    ssl_certificate /etc/ssl/_.****.life-crt.pem;
    ssl_certificate_key /etc/ssl/_.****.life-key.pem;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # 代理配置
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade           $http_upgrade;
    proxy_set_header Connection        "upgrade";
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    # 代理所有请求到 Immich
    location / {
        proxy_pass http://immich-server:2283;
    }

    # 兼容 Let's Encrypt 和 Immich 发现路径
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location = /.well-known/immich {
        proxy_pass http://immich-server:2283;
    }
}

### The OS that Immich Server is running on

Windows 11 DockerDesktop 4.36

### Version of Immich Server

129

### Version of Immich Mobile App

129

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi-wsl # 设置为[nvenc,quicksync,rkmpp,vaapi,vaapi-wsl]之一以加速代码转换
    volumes:
      # 不要编辑下一行。如果您想更改系统上的媒体存储位置，请编辑. dev文件中UPLOAD_LOCATION的值
      # 上传路径
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # 外部库
      - Z:/photos/hzh:/mnt/media/hzh
      - Z:/photos/lxp:/mnt/media/lxp
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: 'openvino-wsl' # 设置为[armnn,cuda,openvino,opnevino-wsl]之一以进行加速推理-在适用的情况下使用WSL 2的“-wsl”版本
    volumes:
      - ${CACHE_LOCATION}:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: [ 'postgres', '-c', 'shared_preload_libraries=vectors.so', '-c', 'search_path="$$user", public, vectors', '-c', 'logging_collector=on', '-c', 'max_wal_size=2GB', '-c', 'shared_buffers=512MB', '-c', 'wal_compression=on' ]
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/proxy.conf.template:/etc/nginx/proxy.conf.template
      - ./nginx/https.conf.template:/etc/nginx/https.conf.template
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint-mount.sh
      - E:/Certificate:/etc/ssl # 证书目录（遗留）
      - ./volumes/certbot/conf/live:/etc/letsencrypt/live # cert dir (with certbot container)
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/html
    entrypoint: [ 'sh', '-c', "cp /docker-entrypoint-mount.sh /docker-entrypoint.sh && sed -i 's/\r$$//' /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh && /docker-entrypoint.sh" ]
    command: ["bash", "-c", "nginx -t && tail -f /dev/null"]  # 临时命令，验证配置后停止
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME:-_}
      NGINX_HTTPS_ENABLED: ${NGINX_HTTPS_ENABLED:-false}
      NGINX_SSL_PORT: ${NGINX_SSL_PORT:-443}
      NGINX_PORT: ${NGINX_PORT:-80}
      # You're required to add your own SSL certificates/keys to the `./nginx/ssl` directory
      # and modify the env vars below in .env if HTTPS_ENABLED is true.
      NGINX_SSL_CERT_FILENAME: ${NGINX_SSL_CERT_FILENAME:-dify.crt}
      NGINX_SSL_CERT_KEY_FILENAME: ${NGINX_SSL_CERT_KEY_FILENAME:-dify.key}
      NGINX_SSL_PROTOCOLS: ${NGINX_SSL_PROTOCOLS:-TLSv1.1 TLSv1.2 TLSv1.3}
      NGINX_WORKER_PROCESSES: ${NGINX_WORKER_PROCESSES:-auto}
      NGINX_CLIENT_MAX_BODY_SIZE: ${NGINX_CLIENT_MAX_BODY_SIZE:-15M}
      NGINX_KEEPALIVE_TIMEOUT: ${NGINX_KEEPALIVE_TIMEOUT:-65}
      NGINX_PROXY_READ_TIMEOUT: ${NGINX_PROXY_READ_TIMEOUT:-3600s}
      NGINX_PROXY_SEND_TIMEOUT: ${NGINX_PROXY_SEND_TIMEOUT:-3600s}
      NGINX_ENABLE_CERTBOT_CHALLENGE: ${NGINX_ENABLE_CERTBOT_CHALLENGE:-false}
      CERTBOT_DOMAIN: ${CERTBOT_DOMAIN:-}
    depends_on:
      immich-server:
        condition: service_healthy
      immich-machine-learning:
        condition: service_healthy
    ports:
      # - '${EXPOSE_NGINX_PORT:-80}:${NGINX_PORT:-80}'
      - '${EXPOSE_NGINX_SSL_PORT:-443}:${NGINX_SSL_PORT:-443}'
  # The Weaviate vector store.
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=Z:/immich/library 
# The location where your database files are stored
DB_DATA_LOCATION=./postgres
# Ai
CACHE_LOCATION=./cache
# 外部库
HZH=Z:/photos/hzh
LXP=Z:/photos/lxp
# mklink /j "E:\Docker Container Config\immich\external\aaasssddd" "E:\Docker Container Config\immich\external\hzh"

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

# Nginx
NGINX_SERVER_NAME=****.life
NGINX_HTTPS_ENABLED=true
# HTTP port
NGINX_PORT=80
# 仅当 HTTPS_ENABLED 为真时才应用SSL设置
NGINX_SSL_PORT=443
# 如果HTTPS_ALEBLED为真，则需要将您自己的SSL证书/密钥添加到'./ nginx/ssl '目录
#并相应修改下面的环境变量。
NGINX_SSL_CERT_FILENAME=_.******.life-crt.pem
NGINX_SSL_CERT_KEY_FILENAME=_.******.life-key.pem
NGINX_SSL_PROTOCOLS=TLSv1.1 TLSv1.2 TLSv1.3
# 域名
CERTBOT_DOMAIN=*******.life
# 设置为true以接受/.众所周知的/acme-challenge/的请求
NGINX_ENABLE_CERTBOT_CHALLENGE=true
# Nginx性能调优
NGINX_WORKER_PROCESSES=auto
NGINX_CLIENT_MAX_BODY_SIZE=50000M
NGINX_KEEPALIVE_TIMEOUT=65

# 代理设置
NGINX_PROXY_READ_TIMEOUT=3600s
NGINX_PROXY_SEND_TIMEOUT=3600s


# ------------------------------
# Docker编写服务暴露主机端口收件箱
# ------------------------------
EXPOSE_NGINX_PORT=80
EXPOSE_NGINX_SSL_PORT=443
```

### Reproduction steps

1.The picture and configuration above are detailed
2.
3.
...

### Relevant log output

```shell

```
