### ISSUE TITLE
Issue on loading videos in the mobile app

### ISSUE THREAD

**Issue by leokaos** [immich-app/immich#16841]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have the application running and working on web on my PC and web in my cell phone. However, in the mobile app, the videos are not loaded and keeps loading forever, with no response or error. There is only 1 video that loads. Videos made by my phone, Samsung A05s, works fine, but videos made by my HERO12 Black and my Canon EOS 1300D, don't.

I already tried the following:

1. connect direct, avoiding the nginx
2. ran the TRANSCODE VIDEOS job, several times

### The OS that Immich Server is running on

Raspberry Pi 4 

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:commit-0a3c3f51e6f1b2eb7cb27beb509d88192c99819b@sha256:7a93a537f4aaaec28583e3ae000d4f5cac97b5a7de70c5eb25b8e97ce36bd84b
    platform: linux/arm64/v8
    privileged: true
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /external-library/VIAGENS:/mnt/media/viagens
      - /etc/localtime:/etc/localtime:ro
    ports:
        - "2283:2283"
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:commit-c61ed6e7058d116c6a911faf290e33176e06cbcb@sha256:cc4fb075af82b96d2ff04b624ff283029cc2ba81b9cbd64f53e33c15d78c1da4
    platform: linux/arm64/v8
    privileged: true
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    platform: linux/arm64/v8
    privileged: true
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:33e6a6c52532c14b8f42bd739e57e69db6839bddc2379f533fe0d50346f39c63
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    
  nginx:
      image: nginx:latest
      container_name: immich_nginx
      healthcheck:
        test: service nginx status || exit 1
      ports:
        - "443:443"
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
        - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/immich-library
DB_DATA_LOCATION=/immich-postgres
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload the video from GoPro
2. Run the TRANSCODE VIDEOS job
3. Open in the mobile application

### Relevant log output

```shell

```

### Additional information

[immich-config.json](https://github.com/user-attachments/files/19217976/immich-config.json)

[info_video.json](https://github.com/user-attachments/files/19218003/info_video.json)

![Image](https://github.com/user-attachments/assets/9d38280a-8d3a-4f38-9b81-b7fa92d8b651)
