### ISSUE TITLE
immich-server 1.128.0 doesn't start

### ISSUE THREAD

**Issue by raisercostin** [immich-app/immich#16848]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After starting immich even with debug enabled it freezes here:
```
2025-03-13T15:20:35.926104581Z Initializing Immich v1.128.0
2025-03-13T15:20:35.972950493Z DEBUG: cgroup v1 detected.
2025-03-13T15:20:35.972991105Z DEBUG: /sys/fs/cgroup/cpu/cpu.cfs_quota_us or /sys/fs/cgroup/cpu/cpu.cfs_period_us not found.
2025-03-13T15:20:35.995322276Z Detected CPU Cores: 4
2025-03-13T15:20:49.524154640Z Starting api worker
2025-03-13T15:20:49.530378675Z Starting microservices worker
2025-03-13T15:20:55.668025652Z [Nest] 7 - 03/13/2025, 3:20:55 PM LOG [Microservices:EventRepository] Initialized websocket server
2025-03-13T15:20:56.168520510Z [Nest] 17 - 03/13/2025, 3:20:56 PM LOG [Api:EventRepository] Initialized websocket server
```

If I downgrade and start v1.127.0 it properly starts, so a database corruption should be ruled out.
If I run with `DB_SKIP_MIGRATIONS=true` it also starts up but I don't know what are the implications (should I run them later?).

Similar issues
- https://github.com/immich-app/immich/issues/16506 (database corruption)
- https://github.com/immich-app/immich/discussions/16717 (discussion about database corruption)
- https://github.com/immich-app/immich/discussions/16481

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.128.0

### Version of Immich Mobile App

v1.128.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - REDIS_HOSTNAME=immich_redis
    networks: 
      - overlay_default
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - immich_redis
      - immich_postgres

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /dev/shm:/cache
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_default

  immich_redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    deploy:
      placement:
        constraints:
          - node.role == worker
    networks:
      - overlay_default

  immich_postgres:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    deploy:
      placement:
        constraints:
          - node.role == worker
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - overlay_default
    
networks:
  overlay_default:
    external: true
```

### Your .env content

```Shell
Probably not relevant
```

### Reproduction steps

1. Upgrade to v1.128.0 is freezing
2. Downgrade to v1.127.0 is working
3. Upgrade to v1.128.0 is freezing again
4. Upgrade to v1.128.0 with `DB_SKIP_MIGRATIONS=true` is working

No debug/logs are shown

### Relevant log output

```shell

```
