### ISSUE TITLE
Renamed 20 ext library sub folders, reprocessing, file size of db grows

### ISSUE THREAD

**Issue by Roachforlife** [immich-app/immich#16864]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Just trying to understand this one. So Im working with the immich auto album folder tool and realized I need to rename like 20 sub directories in my Ext Library to make it display right. This meant reprocessing a lot of images and videos. Since they are the same, simply moved to a new folder, I anticipated the DB size would remain more of less the same (since its deleting the old and adding the new, which are identical files). I've noticed its increased by 20gb. Its still running so no idea what it will be at.

Will it possibly do some clean up at the end? Maybe I need to run some cleanup job or command? Also to note, it added all of the files to the Trash which I deleted as well thinking that would give me my space back but no change.

Any help is appreciated

EDIT - It finished and for stats, I renamed folders representing 700gig of photos/videos. My DB size increased by30gig in the process. 30gb isnt the end of the world but I would prefer to get that space back if anyone knows how. Thanks

Using version 1.29 of Immich

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.29

### Version of Immich Mobile App

v1.29

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/immich:/photos
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false



  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
```

### Your .env content

```Shell
embedded
```

### Reproduction steps

1. Renamed folders in ext library to remove name in front (so Daughter 1st Birthday) became 1st Birthday. I did this for 20 folders
2. Rescanned library via Jobs page
3. Processed everything again
4. Old images ended up in trash, deleted trash
5. DB grew 30gb but I would have expected to be around the same since the same images were just moved
6. Seems like the DB has the old data still present in it?
...

### Relevant log output

```shell

```

### Additional information

Thanks!
