### ISSUE TITLE
removed files from external library can't be deleted from the trash view

### ISSUE THREAD

**Issue by dahool** [immich-app/immich#16866]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I added some external libraries, then I did some cleanup on the filesystem (removed some images) and reescaned the library.
All the removed assets where moved to trash, everything fine here.

The trash can can't be cleared, it just says 'Permanently deleted 0 assets', but it never gets cleared, the assets are still in the DB, and all the thumbs taking space.

From the server log file:

```
[Nest] 17  - 03/14/2025, 10:27:32 AM   ERROR [Api:GlobalExceptionFilter~g4olmyf9] Unknown error: Error: ENOENT: no such file or directory, access '/nas/library/MVI_2553.mp4'

Error: ENOENT: no such file or directory, access '/nas/library//MVI_2553.mp4'
```

if the file doesn't exists, it just simply continue as it has been deleted succesfully and perform the clean up

### The OS that Immich Server is running on

Ubuntu Server - Docker

### Version of Immich Server

1.129

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #user: 1001:1002
    devices:
      - /dev/dri:/dev/dri
    #service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - ${DATA_LOCATION}/thumbs:/usr/src/app/upload/thumbs
      - ${DATA_LOCATION}/upload:/usr/src/app/upload/upload
      - ${DATA_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video
      - ${DATA_LOCATION}/profile:/usr/src/app/upload/profile
      - /nas/vault1/photos:/nas/library
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - database
      - redis
    restart: unless-stopped
    healthcheck:
      disable: false
      
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped
    healthcheck:
      disable: false
      
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped
    ports:
      - '5532:5432'      
    user: 1001:1002

volumes:
  model-cache:
```

### Your .env content

```Shell
DB_DATA_LOCATION=/data/docker/immich/db
IMMICH_VERSION=release
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
BACKUP_LOCATION=/nas/vault2/backup/immich/db
LIBRARY_LOCATION=/nas/vault1/photos/immich
DATA_LOCATION=/data/docker/immich
```

### Reproduction steps

1. Add an scan a External library
2. Remove media from external library
3. Reescan
4. The images should be moved to Trash
5. Try emptying the trash
...

### Relevant log output

```shell

```
