### ISSUE TITLE
Partner Sharing not working as expected

### ISSUE THREAD

**Issue by dwantstocode** [immich-app/immich#16873]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have an issue where I am using immich external libraries that are backed up using synology photos in respective user directories. The external libraries are imported fine in immich, but partner sharing is behaving a bit weird. 

I have 3 users: Admin, D and N.

Admin and D can see each other's shared photos.
N can see both admin and D's shared photos. 
Neither Admin nor D can see N's shared photos.

![Image](https://github.com/user-attachments/assets/2126dc68-36ef-4450-a541-d56881b3b82b)
![Image](https://github.com/user-attachments/assets/ba3d66da-32a4-4977-9553-c31e466f3f0a)
![Image](https://github.com/user-attachments/assets/6987945f-f6f1-4b25-a59b-cf4c1d62e1e9)

### The OS that Immich Server is running on

docker on synology NAS

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0 build 197

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=America/Los_Angeles
      - POSTGRES_DB=[DB NAME]
      - POSTGRES_USER=[DB USER NAME]
      - POSTGRES_PASSWORD=[DB PASS]
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1030:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
      - /volume1/homes/D/Photos:/volume1/homes/D/Photos:ro
      - /volume1/homes/N/Photos:/volume1/homes/N/Photos:ro
      - /volume1/photo:/volume1/photo:ro
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1031:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
      - /volume1/homes/D/Photos:/volume1/homes/D/Photos:ro
      - /volume1/homes/N/Photos:/volume1/homes/N/Photos:ro
      - /volume1/photo:/volume1/photo:ro
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=America/Los_Angeles
DB_HOSTNAME=[db name]
DB_USERNAME=[user name]
DB_PASSWORD=[password]
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=[unique secret]
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
