### ISSUE TITLE
MacOS - scrolling to show details of a photo shows duplicate bottom sheets

### ISSUE THREAD

**Issue by JustAdreamerFL** [immich-app/immich#16886]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When i want to open info of a picture, when i scroll with two fingers, depending on how fast i scroll, i get multiple open bottom sheets. This only happens when scrolling with two fingers.
I have provided logs that are created when this happens.

If enough duplicates are created, my whole mac becomes unresponsive and macs oom-killer eventually kills it. 

The video bellow demonstrates this behavior but i couldn’t record when it completely lags my mac.

https://github.com/user-attachments/assets/20dadc38-073b-4131-92aa-87a3c904c568

### The OS that Immich Server is running on

Mint 22.1

### Version of Immich Server

1.129.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/server/Documents/immich-upload
# The location where your database files are stored
DB_DATA_LOCATION=/home/server/Documents/immich-data

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Bratislava

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=Gr4ndt0ur

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open Immich on Mac with touchpad
2. Open any photo
3. Scroll with two fingers upwards
4.  Based on the speed of scrolling you will see more or less of duplicated bottom sheets showing

### Relevant log output

```shell
[ Message ]
FlutterError - Catch all

[ Details ]

Instance of 'FlutterErrorDetails'
Exception: Null check operator used on a null value
Library: gesture library
Context: Instance of 'ErrorDescription'

[ From ]
ImmichErrorLogger


[ Stack Trace ]

#0      PhotoViewGestureRecognizer._decideIfWeAcceptEvent (package:immich_mobile/widgets/photo_view/src/core/photo_view_gesture_detector.dart:209)
#1      PhotoViewGestureRecognizer.handleEvent (package:immich_mobile/widgets/photo_view/src/core/photo_view_gesture_detector.dart:180)
#2      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98)
#3      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633)
#5      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141)
#6      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127)
#7      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:501)
#8      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
#9      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
#10     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
#11     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
#12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
#13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
#14     _invoke1 (dart:ui/hooks.dart:328)
#15     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
#16     _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
```
