### ISSUE TITLE
Jobs not running - TypeError: Cannot read properties of undefined (reading 'replaceAll')

### ISSUE THREAD

**Issue by RestartB** [immich-app/immich#16929]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello! I recently created a new instance of Immich using Docker Compose. I've uploaded some media from my phone. however I can see that if I go to jobs, it's gotten stuck. I can also see in the logs a lot of errors that are either the same or look very similar. I've added an example in the logs section.

Here's a screenshot showing the stuck jobs:

![Image](https://github.com/user-attachments/assets/d5f3197b-e198-4923-84b7-5a74c0237972)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich-https.tls=true
      - traefik.http.routers.immich-https.tls.certresolver=cloudflare
      - traefik.http.routers.immich-https.entrypoints=websecure
      - traefik.http.routers.immich-https.rule=Host(`censored`)
      - traefik.http.services.immich-https.loadbalancer.server.port=2283
    networks:
      - traefik
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - traefik
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - traefik
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      - traefik

volumes:
  model-cache:

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich/library
DB_DATA_LOCATION=/mnt/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=censored
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload some media
2. Go to the jobs page and the Docker logs
3. See the jobs get stuck and errors appear in the Docker logs

### Relevant log output

```shell
[Nest] 7  - 03/17/2025, 9:02:27 PM    WARN [Microservices:JobRepository] Skipping unknown job: "undefined"
[Nest] 7  - 03/17/2025, 9:02:27 PM   ERROR [Microservices:{}] Unable to run job handler (metadataExtraction/undefined): TypeError: Cannot read properties of undefined (reading 'replaceAll')
TypeError: Cannot read properties of undefined (reading 'replaceAll')
    at JobService.onJobStart (/usr/src/app/dist/services/job.service.js:154:55)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
Error: Missing lock for job 207. failed
    at Scripts.finishedErrors (/usr/src/app/node_modules/bullmq/dist/cjs/classes/scripts.js:272:24)
    at Job.moveToFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/job.js:427:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async handleFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:379:21)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```
