### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by omigeot** [immich-app/immich#16946]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Starting with v1.126.0, I keep having this error whenever I docker-compose up : 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.126.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# Immich
# 
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich_server.rule=Host(`my-hostname`)"
      - "traefik.http.routers.immich_server.entrypoints=websecure"
      - "traefik.http.routers.immich_server.tls.certresolver=myresolver"
#      - "traefik.http.services.immich_server.loadBalancer.server.port=2283"
    networks:
      - app-frontend


  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - app-frontend


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - app-frontend


  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    networks:
      - app-frontend

volumes:
  model-cache:
  
networks:
  app-frontend:
    external: true  # Use existing network
```

### Your .env content

```Shell
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# environment file for Immich
# 

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Paris

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.126.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upgrade env and compose file from v1.125.7 to v1.126.0
2. docker compose up
3. immich_server container loops error
...

### Relevant log output

```shell
immich_redis     | 1:C 18 Mar 2025 08:40:01.394 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
immich_redis     | 1:C 18 Mar 2025 08:40:01.394 # Redis version=6.2.17, bits=64, commit=00000000, modified=0, pid=1, just started
immich_redis     | 1:C 18 Mar 2025 08:40:01.394 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
immich_redis     | 1:M 18 Mar 2025 08:40:01.395 * monotonic clock: POSIX clock_gettime
immich_redis     | 1:M 18 Mar 2025 08:40:01.396 * Running mode=standalone, port=6379.
immich_redis     | 1:M 18 Mar 2025 08:40:01.396 # Server initialized
immich_redis     | 1:M 18 Mar 2025 08:40:01.396 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 * Loading RDB produced by version 6.2.17
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 * RDB age 21 seconds
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 * RDB memory usage when created 0.85 Mb
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 # Done loading RDB, keys loaded: 18, keys expired: 15.
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 * DB loaded from disk: 0.000 seconds
immich_redis     | 1:M 18 Mar 2025 08:40:01.397 * Ready to accept connections
immich_postgres  | 
immich_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres  | 
immich_postgres  | 2025-03-18 08:40:02.330 UTC [1] LOG:  redirecting log output to logging collector process
immich_postgres  | 2025-03-18 08:40:02.330 UTC [1] HINT:  Future log output will appear in directory "log".
immich_server    | Initializing Immich v1.126.0
immich_server    | Detected CPU Cores: 8
immich_server    | node:internal/perf/performance:1
immich_server    | 
immich_server    | 
immich_server    | 
immich_server    | SyntaxError: Invalid or unexpected token
immich_server    |     at node:internal/perf/performance:1:6135
immich_server    |     at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
immich_server    |     at requireBuiltin (node:internal/bootstrap/realm:430:14)
immich_server    |     at node:perf_hooks:24:5
immich_server    |     at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
immich_server    |     at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
immich_server    |     at loadBuiltinModule (node:internal/modules/helpers:110:7)
immich_server    |     at Function._load (node:internal/modules/cjs/loader:1095:17)
immich_server    |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
immich_server    |     at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
immich_server    | 
immich_server    | Node.js v22.13.1
```
