### ISSUE TITLE
Cant restore from backup - database auth fail

### ISSUE THREAD

**Issue by HelloMihai** [immich-app/immich#16958]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

restoring from immich automatic backup fails when starting containers due to authentication failure with user "postgres"

this is a fresh new volume and images pull

docker compose has custom password for postgres.  Same password, never changed... in new build or duration of backups.

desired backup source location"
`/home/myuser/docker/immich_backup/backups/immich-db-backup-1741744800030.sql.gz`

after restoring, immich_server fails to authenticate with the DB

I have tried:
1) console into the immich_postgres container and manually setting the password
```
myuser@server:~/docker/immich$ docker-compose up -d
myuser@ server:~/docker/immich$ docker exec -it immich_postgres bash
# inside immich_postgres container
root@123456abcdefg:/# psql -U postgres -d immich

## see all users, only postgres listed
immich=# \du

immich=# ALTER USER postgres WITH PASSWORD 'mycustompassword123';
```
2) checking postgres permissions and setting to my user
```
ls -ld /home/myuser/docker/immich/postgres ## ownser was root likely due to sudo in backup command
sudo chown -R myuser:myuser /home/myuser/docker/immich/postgres
ls -ld /home/myuser/docker/immich/postgres ## owner changed to myuser
```

### The OS that Immich Server is running on

Ubuntu Server 24.04

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0 build.197

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${PHOTO_LIBRARY_PATH}:${IMMICH_IMPORT_PATH}:ro  # Map 4T SSD Photos directory, :ro = read only
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/myuser/docker/immich/library
DB_DATA_LOCATION=/home/myuser/docker/immich/postgres
PHOTO_LIBRARY_PATH=/mnt/nfs_mounted_library
IMMICH_IMPORT_PATH=/usr/src/app/import
IMMICH_VERSION=release
DB_PASSWORD=mycustompassword123
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. ssh into server
2. cd to docker compose path
3. execute commands from docs
```
myuser@server: $ cd /home/myuser/docker/
myuser@server:/home/myuser/docker $ mkdir -p immich/library

myuser@server:/home/myuser/docker $ cd immich
myuser@server:/home/myuser/docker/immich $ sudo docker compose pull
myuser@server:/home/myuser/docker/immich $ sudo docker compose create
myuser@server:/home/myuser/docker/immich $ sudo docker start immich_postgres
myuser@server:/home/myuser/docker/immich $ sleep 10
myuser@server:/home/myuser/docker/immich $ sudo docker ps | grep immich ## confirm immich_postgres container is running

myuser@server:/home/myuser/docker/immich $ gunzip < "/home/myuser/docker/immich_backup/backups/immich-db-backup-1741744800030.sql.gz" \
| sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
| sudo docker exec -i immich_postgres psql --dbname=postgres --username=postgres
```
 log from restore
```
SET
SET
SET
DROP DATABASE
ERROR:  current user cannot be dropped
ERROR:  role "postgres" already exists
ALTER ROLE
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
UPDATE 1
DROP DATABASE
CREATE DATABASE
ALTER DATABASE
You are now connected to database "template1" as user "postgres".
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
COMMENT
ALTER DATABASE
You are now connected to database "template1" as user "postgres".
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
REVOKE
GRANT
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
CREATE DATABASE
ALTER DATABASE
You are now connected to database "immich" as user "postgres".
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
ALTER DATABASE
You are now connected to database "immich" as user "postgres".
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
CREATE SCHEMA
ALTER SCHEMA
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
CREATE TYPE
ALTER TYPE
CREATE TYPE
ALTER TYPE
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
SET
SET
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
COMMENT
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
COPY 20
COPY 4
COPY 30151
COPY 7
COPY 1
COPY 229107
COPY 317982
COPY 161894
COPY 1
COPY 161894
COPY 3318
COPY 161894
COPY 228813
COPY 210499
COPY 1
COPY 110
COPY 1390
COPY 192
COPY 0
COPY 4274
COPY 1
COPY 0
COPY 5178
COPY 0
COPY 39
COPY 10490
COPY 61
COPY 158898
COPY 0
COPY 0
COPY 7
COPY 553
COPY 19
COPY 19
COPY 1
COPY 5
COPY 0
COPY 11
 setval 
--------
   3318
(1 row)

 setval 
--------
    192
(1 row)

 setval 
--------
   4274
(1 row)

 setval 
--------
      1
(1 row)

ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
CREATE TRIGGER
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
DROP DATABASE
CREATE DATABASE
ALTER DATABASE
You are now connected to database "postgres" as user "postgres".
SET
SET
SET
SET
SET
     set_config     
--------------------
 public, pg_catalog
(1 row)

SET
SET
SET
SET
COMMENT
```

### Relevant log output

```shell
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [NestFactory] Starting Nest application...
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] ClsCommonModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] KyselyModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] KyselyCoreModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +1ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] ClsRootModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich_server            | [Nest] 17  - 03/18/2025, 5:37:43 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich_server            | error: password authentication failed for user "postgres"
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:524:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)

...
...


immich_server            |   length: 104,
immich_server            |   severity: 'FATAL',
immich_server            |   code: '28P01',
immich_server            |   detail: undefined,
immich_server            |   hint: undefined,
immich_server            |   position: undefined,
immich_server            |   internalPosition: undefined,
immich_server            |   internalQuery: undefined,
immich_server            |   where: undefined,
immich_server            |   schema: undefined,
immich_server            |   table: undefined,
immich_server            |   column: undefined,
immich_server            |   dataType: undefined,
immich_server            |   constraint: undefined,
immich_server            |   file: 'auth.c',
immich_server            |   line: '335',
immich_server            |   routine: 'auth_failed'
immich_server            | }
immich_server            | api worker exited with code 1
```
