### ISSUE TITLE
[BUG] Immich cause unraid server freezes

### ISSUE THREAD

**Issue by Snyaify** [immich-app/immich#1698]
### The bug

I use the latest version of immich on unraid deployed via docker-composer. The problem is the following, when uploading photos/ videos via a mobile application on android, the server freezes causing a machine check exception. I can't figure out what to deal with, the server itself worked stably for a couple of years before installing immich. 
I assume that this is due to Machine learning (Tensorflow) when processing photos after uploading. 
Before that, I used Photoprism and there was no such problem
hardware config:
Xeon 2430 V3
Huananzhi X99-F8
32 gb 2133 Samsung Ram

Postgresql and Redis database server in separate containers

### The OS that Immich Server is running on

unraid 6.11.5 (via docker compose)

### Version of Immich Server

v1.45.0

### Version of Immich Mobile App

1.45.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - redis
    #   - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - redis
    #   - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  # redis:
  #   container_name: immich_redis
  #   image: redis:6.2
  #   restart: always

  # database:
  #   container_name: immich_postgres
  #   image: postgres:14
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     PG_DATA: /var/lib/postgresql/data
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

# volumes:
#   pgdata:
networks:
  default:
      name: ipv6
      external: true
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=postgresql14
DB_USERNAME=immich
DB_PASSWORD=$hidden
DB_DATABASE_NAME=immich

# Optional Database settings:
DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=Redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/photo/immich/

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1. Launching the Android app
2. Starting back up
3. After 3-7 photos upload server freezes
...
```
