### ISSUE TITLE
Smart search / machine learning not working

### ISSUE THREAD

**Issue by feasly** [immich-app/immich#16990]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Smart search doesn't show any results, no error message is displayed in immich web-gui.
Please see the log.

immich running on ProxMox in LXC (14 cores, 16GB RAM, nVidia GTX1070 8GB).
nvidia-smi shows the GPU working.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - xxx:/usr/src/app/xxx
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    ports:
      - 3003:3003
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
volumes:
  model-cache: null
  xxx:
    driver_opts:
      type: cifs
      o: iocharset=utf8,username=xxx,password=xxx,rw
      device: xxx
networks: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Using smart search
2. No results found

### Relevant log output

```shell
immich_machine_learning  | [03/19/25 21:53:23] INFO     Loading textual model 'ViT-B-32__laion2b-s34b-b79k'
immich_machine_learning  |                              to memory                                          
immich_machine_learning  | [03/19/25 21:53:23] INFO     Setting execution providers to                     
immich_machine_learning  |                              ['CUDAExecutionProvider', 'CPUExecutionProvider'], 
immich_machine_learning  |                              in descending order of preference                  
immich_machine_learning  | 2025-03-19 21:53:23.006818268 [E:onnxruntime:Default, env.cc:234 ThreadMain] pthread_setaffinity_np failed for thread: 273, index: 2, mask: {3, 17, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004020000
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004020000 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004020000
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004020000 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004030080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x750004030080 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7500040300b0
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7500040300b0 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x7500040300b0
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | mimalloc: warning: (yes, the previous pointer 0x7500040300b0 was valid after all)
immich_machine_learning  | mimalloc: warning: mi_usable_size: pointer might not point to a valid heap region: 0x750004040080
immich_machine_learning  | (this may still be a valid very large allocation (over 64MiB))
immich_machine_learning  | 2025-03-19 21:53:23.780037432 [W:onnxruntime:, transformer_memcpy.cc:74 ApplyImpl] 2 Memcpy nodes are added to the graph main_graph for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
```

### Additional information

I tried with different models, all give the same result.
