### ISSUE TITLE
Query Failed, Thumbnail generation and jellyfin ffmeg issue

### ISSUE THREAD

**Issue by fOO223Fr** [immich-app/immich#17020]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

seeing lots of below errors like:
```Query failed : {
  durationMs: 4.776115998625755,
  error: PostgresError: duplicate key value violates unique constraint "UQ_assets_owner_checksum"
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:524:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
      at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("ownerId", checksum)=(4747bfba-0706-4d02-b5a7-912b1f437ec0, \\x6865e1d48d3c2685f20d414a0716c4127803f0a4) already exists.',
    schema_name: 'public',
    table_name: 'assets',
    constraint_name: 'UQ_assets_owner_checksum',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique'
  },
  sql: 'insert into "assets" ("ownerId", "libraryId", "checksum", "originalPath", "deviceAssetId", "deviceId", "fileCreatedAt", "fileModifiedAt", "localDateTime", "type", "isFavorite", "isArchived", "duration", "isVisible", "originalFileName") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) returning *',
  params: [
    '4747bfba-0706-4d02-b5a7-912b1f437ec0',
    null,
    <Buffer 68 65 e1 d4 8d 3c 26 85 f2 0d 41 4a 07 16 c4 12 78 03 f0 a4>,
    'upload/upload/4747bfba-0706-4d02-b5a7-912b1f437ec0/33/82/33821600-d082-439f-bd24-2f33a6ef976a.mp4',
    '574',
    'c45112a9b594639b8ce6629508c03a1a00c2592284f0abfe77f85dde566376d1',
    2024-12-15T17:37:53.000Z,
    2024-12-15T17:38:06.000Z,
    2024-12-15T17:37:53.000Z,
    'VIDEO',
    false,
    false,
    '0:00:10.000000',
    true,
    'PXL_20241215_173753237.LS.mp4'
  ]
}
```

Then thumbnail generation errors:

```
[Nest] 7  - 03/21/2025, 12:00:00 AM   ERROR [Microservices:{"id":"8bbff739-985f-4a4d-a8ed-3483a6126f7f"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
Error: Input file contains unsupported image format
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:163:17)
    at MediaRepository.decodeImage (/usr/src/app/dist/repositories/media.repository.js:54:68)
    at MediaService.generateImageThumbnails (/usr/src/app/dist/services/media.service.js:164:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async MediaService.handleGenerateThumbnails (/usr/src/app/dist/services/media.service.js:114:25)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:153:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```
and lastly jellyfin ffmeg errors:

```
[Nest] 7  - 03/21/2025, 12:00:00 AM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto=auto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libharfbuzz --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8170180] Skipped opening external track: stream 0, alias: path='/Users//laurakidd//Movies//iMovie Events.localized//bebes//IMG_5240.mov', dir='bebes', filename='IMG_5240.mov', volume='Macintosh HD', nlvl_from=2, nlvl_to=1.Set enable_drefs to allow this.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8170180] Skipped opening external track: stream 1, alias: path='/Users//laurakidd//Movies//iMovie Events.localized//bebes//MVI_5328.mov', dir='bebes', filename='MVI_5328.mov', volume='Macintosh HD', nlvl_from=2, nlvl_to=1.Set enable_drefs to allow this.
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8170180] Skipped opening external track: stream 2, alias: path='/Users//laurakidd//Movies//iMovie Events.localized//bebes//MVI_5328.mov', dir='bebes', filename='MVI_5328.mov', volume='Macintosh HD', nlvl_from=2, nlvl_to=1.Set enable_drefs to allow this.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/laura/2015/March/Cache-30.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2015-03-11T01:27:59.000000Z
  Duration: 00:04:23.73, start: 0.000000, bitrate: 1 kb/s
  Stream #0:0[0x1](eng): Video: aic, 1 reference frame (icod / 0x646F6369), yuv420p(bt709, progressive), 960x540, 34195 kb/s, 29.98 fps, 29.97 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2015-03-11T01:27:59.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        encoder         : Apple Intermediate Codec
  Stream #0:1[0x2](eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, stereo, s16, 1536 kb/s (default)
      Metadata:
        creation_time   : 2015-03-11T01:27:59.000000Z
        handler_name    : Apple Sound Media Handler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Video: aic, 1 reference frame (icod / 0x646F6369), yuv420p(smpte170m/bt709/bt709, progressive), 960x540, 16989 kb/s, 29.97 fps, 29.97 tbr, 30k tbn (default)
      Metadata:
        creation_time   : 2015-03-11T01:33:19.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        encoder         : Apple Intermediate Codec
[out#0/webp @ 0x363c8161980] No explicit maps, mapping streams automatically...
[vost#0:0/libwebp_anim @ 0x363c8170780] Created video stream from input stream 0:0
[Parsed_thumbnail_1 @ 0x363c8120c80] batch size: 12 frames
[Parsed_scale_5 @ 0x363c8121080] w:-2 h:480 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[Parsed_fps_0 @ 0x363c8120a80] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
Stream mapping:
  Stream #0:0 -> #0:0 (aic (native) -> webp (libwebp_anim))
[vost#0:0/libwebp_anim @ 0x363c8170780] Starting thread...
[vf#0:0 @ 0x363c8150880] Starting thread...
[vist#0:0/aic @ 0x363c8220a80] [dec:aic @ 0x363c8220780] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280] Starting thread...
Press [q] to stop, [?] for help
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280] EOF while reading input
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280] Terminating thread with return code 0 (success)
[vist#0:0/aic @ 0x363c8220a80] [dec:aic @ 0x363c8220780] Decoder thread received EOF packet
[vist#0:0/aic @ 0x363c8220a80] [dec:aic @ 0x363c8220780] Decoder returned EOF, finishing
[vist#0:0/aic @ 0x363c8220a80] [dec:aic @ 0x363c8220780] Terminating thread with return code 0 (success)
[Parsed_thumbnail_1 @ 0x363ce0506c0] batch size: 12 frames
[Parsed_scale_5 @ 0x363ce0509c0] w:-2 h:480 flags:'lanczos+accurate_rnd+full_chroma_int' interl:0
[graph 0 input from stream 0:0 @ 0x363ce050a80] w:960 h:540 pixfmt:yuv420p tb:1/600 fr:30000/1001 sar:0/1 csp:bt709 range:unknown
[Parsed_fps_0 @ 0x363ce050540] fps=12/1
[Parsed_scale_5 @ 0x363ce0509c0] w:960 h:540 fmt:yuv420p csp:bt709 range:unknown sar:0/1 -> w:854 h:480 fmt:yuv420p csp:bt709 range:pc sar:0/1 flags:0x00042200
[vf#0:0 @ 0x363c8150880] Filtergraph returned EOF, finishing
[vf#0:0 @ 0x363c8150880] All consumers returned EOF
[vost#0:0/libwebp_anim @ 0x363c8170780] No filtered frames for output stream, trying to initialize anyway.
Output #0, webp, to 'upload/thumbs/8966894f-67d6-4620-90c1-50d3b17094f2/a4/2d/a42d2267-8d2d-4236-a524-63b016c56ae6-thumbnail.webp':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    encoder         : Lavf61.1.100
  Stream #0:0(eng): Video: webp, 1 reference frame, yuv420p(progressive), 854x480, q=2-31, 200 kb/s, 12 fps, 1k tbn (default)
      Metadata:
        creation_time   : 2015-03-11T01:27:59.000000Z
        handler_name    : Apple Video Media Handler
        vendor_id       : appl
        encoder         : Lavc61.3.100 libwebp_anim
[out#0/webp @ 0x363c8161980] Starting thread...
[Parsed_fps_0 @ 0x363ce050540] 0 frames in, 0 frames out; 0 frames dropped, 0 frames duplicated.
[vost#0:0/libwebp_anim @ 0x363c8170780] Encoder thread received EOF
[libwebp encoder @ 0x363c81506c0] WebPAnimEncoderAssemble() failed with error: 1
[vost#0:0/libwebp_anim @ 0x363c8170780] Error submitting video frame to the encoder
[vost#0:0/libwebp_anim @ 0x363c8170780] Error flushing encoder: Cannot allocate memory
[vost#0:0/libwebp_anim @ 0x363c8170780] Task finished with error code: -12 (Cannot allocate memory)
[vost#0:0/libwebp_anim @ 0x363c8170780] Terminating thread with return code -12 (Cannot allocate memory)
[out#0/webp @ 0x363c8161980] All streams finished
[out#0/webp @ 0x363c8161980] Terminating thread with return code 0 (success)
[vf#0:0 @ 0x363c8150880] Terminating thread with return code 0 (success)
[AVIOContext @ 0x363c8061940] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[out#0/webp @ 0x363c8161980] Output file #0 (upload/thumbs/8966894f-67d6-4620-90c1-50d3b17094f2/a4/2d/a42d2267-8d2d-4236-a524-63b016c56ae6-thumbnail.webp):
[out#0/webp @ 0x363c8161980]   Output stream #0:0 (video): 0 frames encoded; 0 packets muxed (0 bytes); 
[out#0/webp @ 0x363c8161980]   Total: 0 packets (0 bytes) muxed
[out#0/webp @ 0x363c8161980] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
[out#0/webp @ 0x363c8161980] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280] Input file #0 (upload/library/laura/2015/March/Cache-30.mov):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280]   Input stream #0:0 (video): 0 packets read (0 bytes); 0 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x363c8120280]   Total: 0 packets (0 bytes) demuxed
[AVIOContext @ 0x363c8060540] Statistics: 59657 bytes read, 0 seeks
Conversion failed!
```

### The OS that Immich Server is running on

LXC container: Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSIO=v1.129.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
