### ISSUE TITLE
[BUG] Database connection error

### ISSUE THREAD

**Issue by HipyCas** [immich-app/immich#1702]
### The bug

For some reason I do not yet understand, with the latest release of Immich accessing either the web app or the android app is impossible due to the following error:

```bash
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [NestFactory] Starting Nest application...
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +107ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] DownloadModule dependencies initialized +1ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +1ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +12ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
immich-server  | [Nest] 1  - 02/07/2023, 5:56:30 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:33 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:36 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:39 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:42 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:45 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:48 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:51 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:54 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
immich-server  | [Nest] 1  - 02/07/2023, 5:56:54 PM   ERROR [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:5432
immich-server  | Error: connect ECONNREFUSED 127.0.0.1:5432
immich-server  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

This has happened suddenly and no config was changed. I've checked the DB logs and it is running perfectly.

### The OS that Immich Server is running on

Debian GNU/Linux 11 (bullseye)

### Version of Immich Server

release

### Version of Immich Mobile App

v1.43.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"

volumes:
  pgdata:

services:
  immich-server:
    image: altran1502/immich-server:release
    container_name: immich-server
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME:?immich server db username not set}
      - DB_PASSWORD=${DB_PASSWORD:?immich server db password not set}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME:?server db name not set}
      - JWT_SECRET=${JWT_SECRET}
      - ENABLE_MAPBOX=${ENABLE_MAPBOX}
      - MAPBOX_KEY=${MAPBOX_KEY}
    depends_on:
      - immich-redis
      - immich-database
    restart: unless-stopped

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - ENABLE_MAPBOX=${ENABLE_MAPBOX}
      - MAPBOX_KEY=${MAPBOX_KEY}
    depends_on:
      - immich-redis
      - immich-database
    restart: unless-stopped

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-database
    restart: unless-stopped

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      - PUBLIC_TZ=${TZ}
    restart: unless-stopped

  immich-redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    mem_limit: 2G

  immich-database:
    container_name: immich_postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 9999:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: unless-stopped
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=dbusername
DB_PASSWORD=dbpassword
DB_DATABASE_NAME=dbdatabasename

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=/path/to/uploads

LOG_LEVEL=verbose

JWT_SECRET=ramdonlygeneratedJTWsecret

ENABLE_MAPBOX=true
MAPBOX_KEY=mymapboxkey
```

### Reproduction steps

```bash
1. Set up Immich following the documentation
2. Upload photos with the app and keep Immich running for a while
3. At some point, it will fail like this :(
```
