### ISSUE TITLE
Unable to run job handler. Error: extract_area: bad extract area

### ISSUE THREAD

**Issue by mazaleyrat** [immich-app/immich#17086]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Some thumbs and images broken but download ok.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.129.0

### Version of Immich Mobile App

v1.129.0

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
    env_file:
    - .env
    ports:
    - '2283:2283'
    depends_on:
    - redis
    - database
    restart: always
    environment:
    - PUID=1000
    - PGID=10000
    - TZ=Etc/UTC
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
    - model-cache:/cache
    env_file:
    - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
    - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/photos/mobile
IMMICH_VERSION=release
DB_PASSWORD=placeholder
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Go to the webapp or mobileapp
2. See this kind of screen

![Image](https://github.com/user-attachments/assets/61cf8201-754c-4c57-822e-78bee644f272)

### Relevant log output

```shell
Nest] 7  - 03/25/2025, 11:44:12 AM   ERROR [Microservices:JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: extract_area: bad extract area

[Nest] 7  - 03/25/2025, 11:44:12 AM   ERROR [Microservices:JobService] Error: extract_area: bad extract area

    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:90:19)

    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)

    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:453:36)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async /usr/src/app/dist/services/job.service.js:148:36

    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)

    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

[Nest] 7  - 03/25/2025, 11:44:12 AM   ERROR [Microservices:JobService] Object:

{

  "id": "ac879144-aa58-4675-b467-4345aceacb79"
```
