### ISSUE TITLE
People tagged in external libraries are no longer shown in people section

### ISSUE THREAD

**Issue by dDiverVS** [immich-app/immich#17110]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating to version v1.130.0 all the faces in the external libraries are no longer shown in the people section. The stragest thing is that if I go to a picture which has faces from an external library I still can see the mapped faces and names.

### The OS that Immich Server is running on

Docker on TrueNAS Scale 25.04-RC.1

### Version of Immich Server

v1.130.0

### Version of Immich Mobile App

v1.129.0 build.187

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
      - /mnt/seedBox/media/Pictures:/pictures
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      - com.centurylinklabs.watchtower.enable=true
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    labels:
      - com.centurylinklabs.watchtower.enable=true
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
volumes:
  model-cache: null
networks: {}
```

### Your .env content

```Shell
# The location where your uploaded files are stored
#UPLOAD_LOCATION=/mnt/seedBox/media/Pictures/immich
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/ssd-storage/appdata/immich/postgres
# Custom location where your uploaded, thumbnails, and transcoded video files are stored
UPLOAD_LOCATION=/mnt/seedBox/media/Pictures/immich/upload
THUMB_LOCATION=/mnt/seedBox/media/Pictures/immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/seedBox/media/Pictures/immich/encoded-video
PROFILE_LOCATION=/mnt/ssd-storage/appdata/immich/profile
BACKUP_LOCATION=/mnt/ssd-storage/appdata/immich/backups


# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Madrid

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_VERSION=v1.124.1
#IMMICH_VERSION=v1.125.2

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=dDiver
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Update immich from v1.129.0 to v1.130.0
2. Login and go to people section
3. Check that faces are no longer shown
4. Go to a picture which is in an external library and has faces on it and check the detailed information (faces are recognized there)

### Relevant log output

```shell

```
