### ISSUE TITLE
Image does not start after upgrade to 1.130.1 - Migration "AddExifUpdateId1741281344519" failed

### ISSUE THREAD

**Issue by talexbikes** [immich-app/immich#17133]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I upgraded (docker compose) from 1.129.0 to 1.130.1 and the immich_server container does not restart.

Docker logs are provided below.

Given I haven't seen anyone else report this image, I expect it is something specific to my setup/photos.

### The OS that Immich Server is running on

Ubuntu Server 24.04.2

### Version of Immich Server

v1.130.1

### Version of Immich Mobile App

v1.129.0.build.187

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=


# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upgrade from immich 1.290.0 to 1.130.1
2. Image does not start
...

### Relevant log output

```shell
Initializing Immich v1.130.1
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 03/26/2025, 9:52:25 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 03/26/2025, 9:52:25 AM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
[Nest] 17  - 03/26/2025, 9:52:25 AM     LOG [Api:EventRepository] Initialized websocket server
Migration "AddExifUpdateId1741281344519" failed, error: could not create unique index "PK_c0117fdbc50b917ef9067740c44"
QueryFailedError: could not create unique index "PK_c0117fdbc50b917ef9067740c44"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddExifUpdateId1741281344519.up (/usr/src/app/dist/migrations/1741281344519-AddExifUpdateId.js:7:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
    at async /usr/src/app/dist/services/database.service.js:93:17
    at async /usr/src/app/dist/repositories/database.repository.js:197:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20) {
  query: 'ALTER TABLE "exif" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()',
  parameters: undefined,
  driverError: error: could not create unique index "PK_c0117fdbc50b917ef9067740c44"
      at /usr/src/app/node_modules/pg/lib/client.js:545:17
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddExifUpdateId1741281344519.up (/usr/src/app/dist/migrations/1741281344519-AddExifUpdateId.js:7:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
      at async /usr/src/app/dist/services/database.service.js:93:17
      at async /usr/src/app/dist/repositories/database.repository.js:197:27
      at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20 {
    length: 250,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key ("assetId")=(ee581ecd-b728-470e-bdac-57553f3608a1) is duplicated.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'exif',
    column: undefined,
    dataType: undefined,
    constraint: 'PK_c0117fdbc50b917ef9067740c44',
    file: 'tuplesort.c',
    line: '4297',
    routine: 'comparetup_index_btree'
  },
  length: 250,
  severity: 'ERROR',
  code: '23505',
  detail: 'Key ("assetId")=(ee581ecd-b728-470e-bdac-57553f3608a1) is duplicated.',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'exif',
  column: undefined,
  dataType: undefined,
  constraint: 'PK_c0117fdbc50b917ef9067740c44',
  file: 'tuplesort.c',
  line: '4297',
  routine: 'comparetup_index_btree'
}
microservices worker error: QueryFailedError: could not create unique index "PK_c0117fdbc50b917ef9067740c44", stack: QueryFailedError: could not create unique index "PK_c0117fdbc50b917ef9067740c44"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddExifUpdateId1741281344519.up (/usr/src/app/dist/migrations/1741281344519-AddExifUpdateId.js:7:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
    at async /usr/src/app/dist/services/database.service.js:93:17
    at async /usr/src/app/dist/repositories/database.repository.js:197:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
microservices worker exited with code 1
Killing api process
```
