### ISSUE TITLE
1.130.2 folder watching stop working

### ISSUE THREAD

**Issue by tanpro260196** [immich-app/immich#17147]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Folder Watch no longer detect any changes within external library.
The library is local on a HDD, not network.
My inotify watches limit is >800k, immich uses ~10k at best.

Downgrade back to 1.130.1 fixes it.

### The OS that Immich Server is running on

Docker, Ubuntu 24.04 LTS

### Version of Immich Server

1.130.2

### Version of Immich Mobile App

1.130

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    network_mode: "media-net"
    user: "1001:1001"
    deploy:
      endpoint_mode: dnsrr
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/storage/Pictures/:/external
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Torrent_Temp/Tapo:/Tapo
    env_file:
      - .env
    depends_on:
      - redis
      - immich_postgres
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich-machine-learning
    network_mode: "media-net"
    user: "1001:1001"
    deploy:
      endpoint_mode: dnsrr
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - ./immich-machine-learning/.config:/.config
      - ./immich-machine-learning/.cache:/.cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich_postgres:
    container_name: immich_postgres
    network_mode: "media-net"
    user: "1001:1001"
    deploy:
      endpoint_mode: dnsrr
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION="/mnt/storage/Pictures/Immich Upload"
# The location where your database files are stored
DB_DATA_LOCATION=./immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Vancouver

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
IMMICH_LOG_LEVEL=debug
DB_HOSTNAME=immich_postgres
#IMMICH_HOST=127.0.0.1
```

### Reproduction steps

1. Made any changes to external library outside of immich (delete/addition)
2. Nothing will happens within immich, no log entries, nothing.

### Relevant log output

```shell

```
