### ISSUE TITLE
Clean install 1.130.2 causes microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by o10s** [immich-app/immich#17174]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Created a new issue due to a comment from @bo0tzz on discussion topic https://github.com/immich-app/immich/discussions/17152

### The OS that Immich Server is running on

Kubernetes RKE2 - On top of ubuntu server 24.10

### Version of Immich Server

v1.130.2

### Version of Immich Mobile App

v1.130.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I use a custom helm, the following is my values file should provide all information required for debugging I suppose

immichPostgres:
  applicationName: immich-psql
  deployment: 
    enabled: false
  service:
    enabled: false
  externalSecret:
    enabled: true
    secretStore:
      name: bitwarden-secretsmanager
      kind: ClusterSecretStore
    files: 
      credentials:
        data:
          postgres-password:
            remoteRef:
              key: <REDACTED>
          password:
            remoteRef:
              key: <REDACTED>
          replication-password:
            remoteRef:
              key: <REDACTED>

immichServer:
  applicationName: immich-server
  deployment: 
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.130.2
    env:
      IMMICH_CONFIG_FILE:
        value: /config/immich-config.yaml
      DB_HOSTNAME:
        value: immich-postgresql
      DB_USERNAME:
        value: immich
      DB_DATABASE_NAME:
        value: immich
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-psql-credentials
            key: postgres-password
      IMMICH_MACHINE_LEARNING_URL:
        value: http://immich-machine-learning:3003
      REDIS_HOSTNAME:
        value: immich-redis-headless

    resources:
      limits:
        cpu: 4000m
        memory: 10Gi
      requests:
        cpu: 1000m
        memory: 512Mi
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    volumes:
      nfs-photos:
        nfs:
          server: <REDACTED>
          path: <REDACTED>
      dev-dri:
        hostPath:
          path: /dev/dri
          type: Directory
    volumeMounts:
      nfs-photos:
        mountPath: /usr/src/app/upload
      dev-dri:
        mountPath: /dev/dri
  persistence:
    enabled: true
    mountPVC: true
    mountPath: "/config"
    storageSize: 10Gi
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 2283
        targetPort: 2283
  ingress:
    enabled: true
    hosts:
      - host: immich.<REDACTED>
        paths:
          - path: /
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
    tls:
      - secretName: immich-tls
        hosts:
          - immich.<REDACTED>

immichMachineLearning:
  applicationName: immich-machine-learning
  deployment: 
    enabled: true
    image:
      repository: ghcr.io/immich-app/immich-machine-learning
      tag: v1.130.2-openvino
    env:
      TRANSFORMERS_CACHE:
        value: /cache
      DB_HOSTNAME:
        value: immich-postgresql.immich.svc.cluster.local
      DB_USERNAME:
        value: immich
      DB_DATABASE_NAME:
        value: immich
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-psql-credentials
            key: postgres-password
      IMMICH_MACHINE_LEARNING_URL:
        value: http://immich-machine-learning:3003
      REDIS_HOSTNAME:
        value: immich-redis-headless
    containerSecurityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    volumes:
      dev-dri:
        hostPath:
          path: /dev/dri
          type: Directory
      dev-bus-usb:
        hostPath:
          path: /dev/bus/usb
          type: Directory
    volumeMounts:
      dev-dri:
        mountPath: /dev/dri
      dev-bus-usb:
        mountPath: /dev/bus/usb
  service:
    enabled: true
    type: ClusterIP
    ports:
      - name: http
        port: 3003
        targetPort: 3003

redis:
  architecture: standalone
  auth:
    enabled: false

postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        existingSecret: "immich-psql-credentials"
        secretKeys:
          adminPasswordKey: postgres-password
          userPasswordKey: password
          replicationPasswordKey: replication-password
  primary:
    containerSecurityContext:
      readOnlyRootFilesystem: false
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;
```

### Your .env content

```Shell
All envs are defined above in the values file
```

### Reproduction steps

1. Launch with the given values
2. Wait
3. Crash of the server
...

### Relevant log output

```shell
Initializing Immich v1.130.2
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 03/27/2025, 3:35:16 PM     LOG [Microservices:EventRepository] Initialized websocket server
microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')
    at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)
    at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:318:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
microservices worker exited with code 1
Killing api process
```

### Additional information

It could be due to a bug in alpine as described here: https://github.com/immich-app/immich/discussions/17152
Or it could be due to a communication issue but I don't see how...
