### ISSUE TITLE
[BUG] Cannot select pictures at end of timeline 

### ISSUE THREAD

**Issue by EnochPrime** [immich-app/immich#1717]
### The bug

The popup menu for multiselect blocks images at the bottom of the timeline and there is no over scroll to be able to select them. 

### The OS that Immich Server is running on

Various (docker swarm)

### Version of Immich Server

v1.46.0

### Version of Immich Mobile App

v1.46.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"

# swarm deployment extension
x-deploy-swarm: &deploy_swarm
  mode: replicated
  replicas: 1
  update_config:
    parallelism: 1
    delay: 10s
    order: start-first

# immich environment
x-immich-env: &immich_environment
  NODE_ENV: production
  ENABLE_MAPBOX: "false"
  DB_HOSTNAME: db
  DB_DATABASE_NAME: immich
  DB_USERNAME: immich
  DB_PASSWORD_FILE: /run/secrets/MYSQL_IMMICH_PASSWORD

services:
  app:
    image: ghcr.io/immich-app/immich-web:v1.46.0
    entrypoint: /bin/sh ./entrypoint.sh
    environment:
      IMMICH_SERVER_URL: http://server:3001
    networks:
      - frontend
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  server:
    image: ghcr.io/immich-app/immich-server:v1.46.0
    entrypoint: /bin/sh ./start-server.sh
    environment:
      <<: *immich_environment
    secrets:
      - MYSQL_IMMICH_PASSWORD
    volumes:
      - /mnt/swarm/immich/upload:/usr/src/app/upload
    networks:
      - frontend
      - database
      - redis
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
      restart_policy:
        delay: 120s
        max_attempts: 3

  microservices:
    image: ghcr.io/immich-app/immich-server:v1.46.0
    entrypoint: /bin/sh ./start-microservices.sh
    environment:
      <<: *immich_environment
      IMMICH_MACHINE_LEARNING_URL: http://machine_learning:3003
    secrets:
      - MYSQL_IMMICH_PASSWORD
    volumes:
      - /mnt/swarm/immich/upload:/usr/src/app/upload
    networks:
      - backend
      - database
      - redis
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: '1.0'
          memory: 1.0G
      restart_policy:
        delay: 120s
        max_attempts: 3

  machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.46.0
    entrypoint: /bin/sh ./entrypoint.sh
    volumes:
      - /mnt/swarm/immich/upload:/usr/src/app/upload
    networks:
      - backend
    deploy:
      <<: *deploy_swarm
      placement:
        constraints:
          - node.platform.arch == x86_64
          - node.hostname == node-hp
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  db:
    image: postgres:14.6
    secrets:
      - MYSQL_IMMICH_PASSWORD
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/MYSQL_IMMICH_PASSWORD
    volumes:
      - /mnt/swarm/immich/db:/var/lib/postgresql/data
    networks:
      - database
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

  redis:
    image: redis:7.0
    networks:
      - redis
    deploy:
      <<: *deploy_swarm
      resources:
        limits:
          cpus: '0.1'
          memory: 32M

networks:
  frontend:
    external: true
    name: core_frontend
  backend:
    driver: overlay
  database:
    driver: overlay
  redis:
    driver: overlay

secrets:
  MYSQL_IMMICH_PASSWORD:
    external: true
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Open app on mobile
2. Scroll to bottom of timeline
3. Long press to select an image
4. Menu appears which covers bottom images
5. Cannot over scroll to view them
```
