### ISSUE TITLE
Files renamed with duplicate extension

### ISSUE THREAD

**Issue by pixil98** [immich-app/immich#17176]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

While troubleshooting a different issue, I started the Storage Template job and it decided to rename a bunch of my assets to have duplicate extensions.

Logs:
```
[Nest] 7  - 03/27/2025, 1:36:33 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3019.mp4 => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3019.MP4.mp4
[Nest] 7  - 03/27/2025, 1:36:33 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3019.mp4.xmp => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3019.MP4.mp4.xmp
[Nest] 7  - 03/27/2025, 1:36:33 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.heic => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.HEIC.heic
[Nest] 7  - 03/27/2025, 1:36:33 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.heic.xmp => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.HEIC.heic.xmp
[Nest] 7  - 03/27/2025, 1:36:33 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2021/2021-01-22/IMG_3573.heic => upload/library/aaron@reismanorg/2021/2021-01-22/IMG_3573.HEIC.heic
[Nest] 7  - 03/27/2025, 1:36:34 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2021/2021-01-22/IMG_3573.heic.xmp => upload/library/aaron@reismanorg/2021/2021-01-22/IMG_3573.HEIC.heic.xmp
[Nest] 7  - 03/27/2025, 1:36:34 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3013.mp4 => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3013.MP4.mp4
[Nest] 7  - 03/27/2025, 1:36:34 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3013.mp4.xmp => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3013.MP4.mp4.xmp
[Nest] 7  - 03/27/2025, 1:36:34 AM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3020.heic => upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3020.HEIC.heic
```

Folder on the NAS:
```
aaron@truenas:~$ ls /mnt/main/kubernetes/production/photos-immich-library/aaron@reismanorg/2020/2020-01-06/
IMG_20200106_102310.jpg      IMG_20200106_121203.jpg.xmp  IMG_2965.MP4.mp4        IMG_2976.MP4.mp4.xmp    IMG_2988.HEIC.heic      IMG_2999.HEIC.heic.xmp  IMG_3011.MP4.mp4        IMG_3023.MP4.mp4.xmp
IMG_20200106_102310.jpg.xmp  IMG_20200106_121231.jpg      IMG_2965.MP4.mp4.xmp    IMG_2977.HEIC.heic      IMG_2988.HEIC.heic.xmp  IMG_2999.MP4.mp4        IMG_3011.MP4.mp4.xmp    IMG_3024.HEIC.heic
IMG_20200106_102445.jpg      IMG_20200106_121231.jpg.xmp  IMG_2966.HEIC.heic      IMG_2977.HEIC.heic.xmp  IMG_2988.MP4.mp4        IMG_2999.MP4.mp4.xmp    IMG_3012.HEIC.heic      IMG_3024.HEIC.heic.xmp
IMG_20200106_102445.jpg.xmp  IMG_20200106_121548.jpg      IMG_2966.HEIC.heic.xmp  IMG_2977.MP4.mp4        IMG_2988.MP4.mp4.xmp    IMG_3001.HEIC.heic      IMG_3012.HEIC.heic.xmp  IMG_3024.MP4.mp4
IMG_20200106_111754.jpg      IMG_20200106_121548.jpg.xmp  IMG_2966.MP4.mp4        IMG_2977.MP4.mp4.xmp    IMG_2989.HEIC.heic      IMG_3001.HEIC.heic.xmp  IMG_3012.MP4.mp4        IMG_3024.MP4.mp4.xmp
IMG_20200106_111754.jpg.xmp  IMG_20200106_122534.jpg      IMG_2966.MP4.mp4.xmp    IMG_2978.HEIC.heic      IMG_2989.HEIC.heic.xmp  IMG_3001.MP4.mp4        IMG_3012.MP4.mp4.xmp    IMG_3025.HEIC.heic
IMG_20200106_111757.jpg      IMG_20200106_122534.jpg.xmp  IMG_2967.HEIC.heic      IMG_2978.HEIC.heic.xmp  IMG_2989.MP4.mp4        IMG_3001.MP4.mp4.xmp    IMG_3013.HEIC.heic      IMG_3025.HEIC.heic.xmp
IMG_20200106_111757.jpg.xmp  IMG_20200106_122540.jpg      IMG_2967.HEIC.heic.xmp  IMG_2978.MP4.mp4        IMG_2989.MP4.mp4.xmp    IMG_3002.HEIC.heic      IMG_3013.HEIC.heic.xmp  IMG_3025.MP4.mp4
IMG_20200106_111805.jpg      IMG_20200106_122540.jpg.xmp  IMG_2967.MP4.mp4        IMG_2978.MP4.mp4.xmp    IMG_2990.HEIC.heic      IMG_3002.HEIC.heic.xmp  IMG_3013.MP4.mp4        IMG_3025.MP4.mp4.xmp
IMG_20200106_111805.jpg.xmp  IMG_20200106_141127.jpg      IMG_2967.MP4.mp4.xmp    IMG_2979.HEIC.heic      IMG_2990.HEIC.heic.xmp  IMG_3002.MP4.mp4        IMG_3013.MP4.mp4.xmp    IMG_3026.HEIC.heic
IMG_20200106_112205.jpg      IMG_20200106_141127.jpg.xmp  IMG_2968.HEIC.heic      IMG_2979.HEIC.heic.xmp  IMG_2990.MP4.mp4        IMG_3002.MP4.mp4.xmp    IMG_3014.HEIC.heic      IMG_3026.HEIC.heic.xmp
IMG_20200106_112205.jpg.xmp  IMG_20200106_143201.jpg      IMG_2968.HEIC.heic.xmp  IMG_2979.MP4.mp4        IMG_2990.MP4.mp4.xmp    IMG_3003.HEIC.heic      IMG_3014.HEIC.heic.xmp  IMG_3026.MP4.mp4
IMG_20200106_112457.jpg      IMG_20200106_143201.jpg.xmp  IMG_2968.MP4.mp4        IMG_2979.MP4.mp4.xmp    IMG_2991.HEIC.heic      IMG_3003.HEIC.heic.xmp  IMG_3014.MP4.mp4        IMG_3026.MP4.mp4.xmp
IMG_20200106_112457.jpg.xmp  IMG_20200106_143204.jpg      IMG_2968.MP4.mp4.xmp    IMG_2980.HEIC.heic      IMG_2991.HEIC.heic.xmp  IMG_3003.MP4.mp4        IMG_3014.MP4.mp4.xmp    IMG_3027.HEIC.heic
IMG_20200106_112514.jpg      IMG_20200106_143204.jpg.xmp  IMG_2969.HEIC.heic      IMG_2980.HEIC.heic.xmp  IMG_2991.MP4.mp4        IMG_3003.MP4.mp4.xmp    IMG_3015.HEIC.heic      IMG_3027.HEIC.heic.xmp
IMG_20200106_112514.jpg.xmp  IMG_20200106_143206.jpg      IMG_2969.HEIC.heic.xmp  IMG_2980.MP4.mp4        IMG_2991.MP4.mp4.xmp    IMG_3004.HEIC.heic      IMG_3015.HEIC.heic.xmp  IMG_3027.MP4.mp4
IMG_20200106_112834.jpg      IMG_20200106_143206.jpg.xmp  IMG_2969.MP4.mp4        IMG_2980.MP4.mp4.xmp    IMG_2992.HEIC.heic      IMG_3004.HEIC.heic.xmp  IMG_3015.MP4.mp4        IMG_3027.MP4.mp4.xmp
IMG_20200106_112834.jpg.xmp  IMG_20200106_143247.jpg      IMG_2969.MP4.mp4.xmp    IMG_2981.HEIC.heic      IMG_2992.HEIC.heic.xmp  IMG_3004.MP4.mp4        IMG_3015.MP4.mp4.xmp    IMG_3028.HEIC.heic
IMG_20200106_113032.jpg      IMG_20200106_143247.jpg.xmp  IMG_2970.HEIC.heic      IMG_2981.HEIC.heic.xmp  IMG_2992.MP4.mp4        IMG_3004.MP4.mp4.xmp    IMG_3016.HEIC.heic      IMG_3028.HEIC.heic.xmp
IMG_20200106_113032.jpg.xmp  IMG_20200106_143248.jpg      IMG_2970.HEIC.heic.xmp  IMG_2981.MP4.mp4        IMG_2992.MP4.mp4.xmp    IMG_3005.HEIC.heic      IMG_3016.HEIC.heic.xmp  IMG_3028.MP4.mp4
IMG_20200106_113327.jpg      IMG_20200106_143248.jpg.xmp  IMG_2970.MP4.mp4        IMG_2981.MP4.mp4.xmp    IMG_2993.HEIC.heic      IMG_3005.HEIC.heic.xmp  IMG_3016.MP4.mp4        IMG_3028.MP4.mp4.xmp
IMG_20200106_113327.jpg.xmp  IMG_20200106_144404.jpg      IMG_2970.MP4.mp4.xmp    IMG_2982.HEIC.heic      IMG_2993.HEIC.heic.xmp  IMG_3005.MP4.mp4        IMG_3016.MP4.mp4.xmp    IMG_3029.HEIC.heic
IMG_20200106_113333.jpg      IMG_20200106_144404.jpg.xmp  IMG_2971.HEIC.heic      IMG_2982.HEIC.heic.xmp  IMG_2993.MP4.mp4        IMG_3005.MP4.mp4.xmp    IMG_3018.HEIC.heic      IMG_3029.HEIC.heic.xmp
IMG_20200106_113333.jpg.xmp  IMG_20200106_144541.jpg      IMG_2971.HEIC.heic.xmp  IMG_2982.MP4.mp4        IMG_2993.MP4.mp4.xmp    IMG_3006.HEIC.heic      IMG_3018.HEIC.heic.xmp  IMG_3029.MP4.mp4
IMG_20200106_113402.jpg      IMG_20200106_144541.jpg.xmp  IMG_2971.MP4.mp4        IMG_2982.MP4.mp4.xmp    IMG_2994.HEIC.heic      IMG_3006.HEIC.heic.xmp  IMG_3018.MP4.mp4        IMG_3029.MP4.mp4.xmp
IMG_20200106_113402.jpg.xmp  IMG_20200106_144829.jpg      IMG_2971.MP4.mp4.xmp    IMG_2983.HEIC.heic      IMG_2994.HEIC.heic.xmp  IMG_3006.MP4.mp4        IMG_3018.MP4.mp4.xmp    IMG_3030.HEIC.heic
IMG_20200106_113438.jpg      IMG_20200106_144829.jpg.xmp  IMG_2972.HEIC.heic      IMG_2983.HEIC.heic.xmp  IMG_2994.MP4.mp4        IMG_3006.MP4.mp4.xmp    IMG_3019.HEIC.heic      IMG_3030.HEIC.heic.xmp
IMG_20200106_113438.jpg.xmp  IMG_20200106_144841.jpg      IMG_2972.HEIC.heic.xmp  IMG_2983.MP4.mp4        IMG_2994.MP4.mp4.xmp    IMG_3007.HEIC.heic      IMG_3019.HEIC.heic.xmp  IMG_3030.MP4.mp4
IMG_20200106_114538.jpg      IMG_20200106_144841.jpg.xmp  IMG_2972.MP4.mp4        IMG_2983.MP4.mp4.xmp    IMG_2995.HEIC.heic      IMG_3007.HEIC.heic.xmp  IMG_3019.MP4.mp4        IMG_3030.MP4.mp4.xmp
IMG_20200106_114538.jpg.xmp  IMG_20200106_150221.jpg      IMG_2972.MP4.mp4.xmp    IMG_2984.HEIC.heic      IMG_2995.HEIC.heic.xmp  IMG_3007.MP4.mp4        IMG_3019.MP4.mp4.xmp    IMG_3031.HEIC.heic
IMG_20200106_114846.jpg      IMG_20200106_150221.jpg.xmp  IMG_2973.HEIC.heic      IMG_2984.HEIC.heic.xmp  IMG_2995.MP4.mp4        IMG_3007.MP4.mp4.xmp    IMG_3020.HEIC.heic      IMG_3031.HEIC.heic.xmp
IMG_20200106_114846.jpg.xmp  IMG_20200106_151123.jpg      IMG_2973.HEIC.heic.xmp  IMG_2984.MP4.mp4        IMG_2995.MP4.mp4.xmp    IMG_3008.HEIC.heic      IMG_3020.HEIC.heic.xmp  IMG_3031.MP4.mp4
IMG_20200106_114938.jpg      IMG_20200106_151123.jpg.xmp  IMG_2973.MP4.mp4        IMG_2984.MP4.mp4.xmp    IMG_2996.HEIC.heic      IMG_3008.HEIC.heic.xmp  IMG_3020.MP4.mp4        IMG_3031.MP4.mp4.xmp
IMG_20200106_114938.jpg.xmp  IMG_20200106_152504.jpg      IMG_2973.MP4.mp4.xmp    IMG_2985.HEIC.heic      IMG_2996.HEIC.heic.xmp  IMG_3008.MP4.mp4        IMG_3020.MP4.mp4.xmp    IMG_3032.HEIC.heic
IMG_20200106_115216.jpg      IMG_20200106_152504.jpg.xmp  IMG_2974.HEIC.heic      IMG_2985.HEIC.heic.xmp  IMG_2996.MP4.mp4        IMG_3008.MP4.mp4.xmp    IMG_3021.HEIC.heic      IMG_3032.HEIC.heic.xmp
IMG_20200106_115216.jpg.xmp  IMG_20200106_152508.jpg      IMG_2974.HEIC.heic.xmp  IMG_2985.MP4.mp4        IMG_2996.MP4.mp4.xmp    IMG_3009.HEIC.heic      IMG_3021.HEIC.heic.xmp  IMG_3032.MP4.mp4
IMG_20200106_115227.jpg      IMG_20200106_152508.jpg.xmp  IMG_2974.MP4.mp4        IMG_2985.MP4.mp4.xmp    IMG_2997.HEIC.heic      IMG_3009.HEIC.heic.xmp  IMG_3021.MP4.mp4        IMG_3032.MP4.mp4.xmp
IMG_20200106_115227.jpg.xmp  IMG_20200106_152915.jpg      IMG_2974.MP4.mp4.xmp    IMG_2986.HEIC.heic      IMG_2997.HEIC.heic.xmp  IMG_3009.MP4.mp4        IMG_3021.MP4.mp4.xmp    IMG_3033.HEIC.heic
IMG_20200106_120642.jpg      IMG_20200106_152915.jpg.xmp  IMG_2975.HEIC.heic      IMG_2986.HEIC.heic.xmp  IMG_2997.MP4.mp4        IMG_3009.MP4.mp4.xmp    IMG_3022.HEIC.heic      IMG_3033.HEIC.heic.xmp
IMG_20200106_120642.jpg.xmp  IMG_2962.HEIC.heic           IMG_2975.HEIC.heic.xmp  IMG_2986.MP4.mp4        IMG_2997.MP4.mp4.xmp    IMG_3010.HEIC.heic      IMG_3022.HEIC.heic.xmp  IMG_3033.MP4.mp4
IMG_20200106_120651.jpg      IMG_2962.HEIC.heic.xmp       IMG_2975.MP4.mp4        IMG_2986.MP4.mp4.xmp    IMG_2998.HEIC.heic      IMG_3010.HEIC.heic.xmp  IMG_3022.MP4.mp4        IMG_3033.MP4.mp4.xmp
IMG_20200106_120651.jpg.xmp  IMG_2962.MP4.mp4             IMG_2975.MP4.mp4.xmp    IMG_2987.HEIC.heic      IMG_2998.HEIC.heic.xmp  IMG_3010.MP4.mp4        IMG_3022.MP4.mp4.xmp    IMG_3034.JPG.jpg
IMG_20200106_121012.jpg      IMG_2962.MP4.mp4.xmp         IMG_2976.HEIC.heic      IMG_2987.HEIC.heic.xmp  IMG_2998.MP4.mp4        IMG_3010.MP4.mp4.xmp    IMG_3023.HEIC.heic      IMG_3034.JPG.jpg.xmp
IMG_20200106_121012.jpg.xmp  IMG_2965.HEIC.heic           IMG_2976.HEIC.heic.xmp  IMG_2987.MP4.mp4        IMG_2998.MP4.mp4.xmp    IMG_3011.HEIC.heic      IMG_3023.HEIC.heic.xmp
IMG_20200106_121203.jpg      IMG_2965.HEIC.heic.xmp       IMG_2976.MP4.mp4        IMG_2987.MP4.mp4.xmp    IMG_2999.HEIC.heic      IMG_3011.HEIC.heic.xmp  IMG_3023.MP4.mp4
```

Database entry for one of the above assets
```
id                  |     deviceAssetId     |               ownerId                | deviceId | type  |                            originalPath                            |     fileCreatedAt      |     fileModifiedAt     | isFavorite | duration | encodedVideoPath |                  checksum                  | isVisible |           livePhotoVi
deoId           |          updatedAt           |           createdAt           | isArchived | originalFileName |                              sidecarPath                               |                  thumbhash                   | isOffline | libraryId | isExternal | deletedAt |     localDateTime      | stackId | duplicateId | status |               updateId
               
--------------------------------------+-----------------------+--------------------------------------+----------+-------+--------------------------------------------------------------------+------------------------+------------------------+------------+----------+------------------+--------------------------------------------+-----------+----------------------
----------------+------------------------------+-------------------------------+------------+------------------+------------------------------------------------------------------------+----------------------------------------------+-----------+-----------+------------+-----------+------------------------+---------+-------------+--------+-----------------------
---------------
 fa2e0cc1-de84-4cd2-aff7-8b2e073d67a4 | IMG_3025.HEIC-2548401 | df1dc8c3-0aa5-433b-86ca-c7dd959226c0 | Giraffe  | IMAGE | upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.HEIC.heic | 2020-01-06 21:15:28+00 | 2025-03-14 05:55:41+00 | f          |          |                  | \x085d97cad0e7439f56370508fc21e49d628fec8f | t         | 692bf75e-1324-42c8-a9
f3-07677b1a7655 | 2025-03-27 06:36:33.84064+00 | 2025-03-14 05:55:39.112128+00 | f          | IMG_3025.HEIC    | upload/library/aaron@reismanorg/2020/2020-01-06/IMG_3025.HEIC.heic.xmp | \x94f8091502f5698b7b98887767778788c78fa809a5 | f         |           | f          |           | 2020-01-06 15:15:28+00 |         |             | active | 0195d651-18b0-760c-909
d-8045d87b6010
(1 row)
```

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.130.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: photos
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: immich
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: immich-server
          image: registry.lab.reisman.org/proxy.ghcr.io/immich-app/immich-server:v1.130.2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
            - name: DB_DATABASE_NAME
              value: "immich"
            - name: DB_HOSTNAME
              value: "immich-postgresql"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-postgresql-user
                  key: password
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-postgresql-user
                  key: username
                  optional: false
            - name: IMMICH_CONFIG_FILE
              value: "/config/immich.json"
            - name: IMMICH_TELEMETRY_INCLUDE
              value: "all"
            - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
              value: "true"
            - name: REDIS_HOSTNAME
              value: "immich-redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-redis-password
                  key: password
                  optional: false
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
            - name: monitoring
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "8"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /usr/src/app/upload/library
            - name: upload
              mountPath: /usr/src/app/upload/upload
            - name: encoded-video
              mountPath: /usr/src/app/upload/encoded-video
            - name: profile
              mountPath: /usr/src/app/upload/profile
            - name: thumbs
              mountPath: /usr/src/app/upload/thumbs
          startupProbe:
            httpGet:
              path: /api/server/ping
              port: http
            failureThreshold: 60
            periodSeconds: 5
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
            periodSeconds: 60
            timeoutSeconds: 1
      volumes:
        - name: config
          secret:
            secretName: immich-server-config
        - name: library
          persistentVolumeClaim:
            claimName: immich-library
        - name: upload
          persistentVolumeClaim:
            claimName: immich-upload
        - name: encoded-video
          persistentVolumeClaim:
            claimName: immich-encoded-video
        - name: profile
          persistentVolumeClaim:
            claimName: immich-profile
        - name: thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs
```

### Your .env content

```Shell
See above
```

### Reproduction steps

I'm unsure how to cause this to happen again as, now that it finished, it doesn't do it again if I start the job.

1. Start the Storage Template Migration job

### Relevant log output

```shell

```
