### ISSUE TITLE
Memories: despite the fix, I see an incorrect date between the memories.

### ISSUE THREAD

**Issue by 416c6578-dev** [immich-app/immich#17189]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Like many here, I had an issue with the Memories after the 1.127 update. However, even after applying the fix from the posts, I still keep seeing the 5th of April 2020 in between my correct Memories that are showing the current date. It's always this date. And it's only in the Mobile APP.

What I have already done:

Docker exec truncate command in the CLI
Cleaned up memories in the GUI
Regenerated memories in the GUI
Regenerated metadata in the GUI
Deinstall and Install the Mobile APP (IOS)
Unfortunately, none of this has led to the desired result. What else can I do?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v1.130.3

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1000:10
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume2/docker/immich/redis:/data:rw
    restart: unless-stopped

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume2/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: unless-stopped

  immich-server:
    image: ghcr.io/immich-app/immich-server:release 
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/@home/Alex/docker/immich:/usr/src/app/upload:rw
    restart: unless-stopped
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release

    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/@home/Alex/docker/immich:/usr/src/app/upload:rw
      - /volume2/docker/immich/cache:/cache:rw
      - /volume2/docker/immich/matplotlib:/matplotlib:rw
    environment: 
      - MPLCONFIGDIR=/matplotlib
    restart: unless-stopped
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
.
```

### Reproduction steps

.

### Relevant log output

```shell

```
