### ISSUE TITLE
Memories function gets disrupted when deleting a photo.

### ISSUE THREAD

**Issue by 416c6578-dev** [immich-app/immich#17206]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I view photos in the "Memories" section and delete one or more photos there, the entire "Memories" function gets confused. It suddenly starts loading photos from other days. This issue only occurs in the mobile app. Simply cleaning up the "Memories" function in the GUI is not enough; I have to execute the Docker Truncate command to properly reorganize the "Memories."

### The OS that Immich Server is running on

Debian 

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v.1.130.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1000:10
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume2/docker/immich/redis:/data:rw
    restart: unless-stopped

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume2/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: unless-stopped

  immich-server:
    image: ghcr.io/immich-app/immich-server:release 
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/@home/Alex/docker/immich:/usr/src/app/upload:rw
    restart: unless-stopped
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release

    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1000:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/@home/Alex/docker/immich:/usr/src/app/upload:rw
      - /volume2/docker/immich/cache:/cache:rw
      - /volume2/docker/immich/matplotlib:/matplotlib:rw
    environment: 
      - MPLCONFIGDIR=/matplotlib
    restart: unless-stopped
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
.
```

### Reproduction steps

1. Scroll through your Memories
2. Delete a photo
3. If I now restart the app, either today or on another day, not only today's date is displayed in the Memories, but also some random other day. However, the photos from this other day do not all match the actual date. Example: Today is March 29, 2025, I scroll further, and pictures from October 24 appear. You can also notice that scrolling through the incorrect days runs a bit less smoothly.

- Restarting the app has no effect
- Cleaning up Memories has no effect
- Only "docker exec Immich-DB psql --dbname=immich --username=immichuser -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;" help

### Relevant log output

```shell

```
