### ISSUE TITLE
Large video files can't be uploaded

### ISSUE THREAD

**Issue by bossi86** [immich-app/immich#17216]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When uploading large video files (at least greater than 2.19GB), I receive an "Unable to upload file" error. I try to upload a mp4 file.
<img width="309" alt="Image" src="https://github.com/user-attachments/assets/1826246b-7080-4c7c-9215-089430365b8b" />

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      immich_default: null
      50_HH-bridge:
        ipv4_address: 192.168.255.248
    dns:
      - 192.168.255.254
    dns_search:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=false
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      immich_default: null
      50_HH-bridge: null
    dns:
      - 192.168.255.254
    dns_search:
      - local
    labels:
      - com.centurylinklabs.watchtower.enable=false
    env_file:
      - stack.env
    volumes:
      - ${MODELCACHE_LOCATION}:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    networks:
      immich_default: null
    labels:
      - com.centurylinklabs.watchtower.enable=false
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    networks:
      immich_default: null
    labels:
      - com.centurylinklabs.watchtower.enable=false
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
networks:
  immich_default: null
  50_HH-bridge:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/storagepool_1/container/immich/library
DB_DATA_LOCATION=/mnt/storagepool_1/container/immich/postgres
MODELCACHE_LOCATION=/mnt/storagepool_1/tmp/immich/model-cache
BACKUP_LOCATION=/mnt/storagepool_1/tmp/immich/backup
TZ=Europe/Berlin
IMMICH_VERSION=v1.130.3
DB_PASSWORD=xxx
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload a mp4 video file greater than 2.19GB via Web UI.

### Relevant log output

```shell
No log output found, even with log mode verbose.
```

### Additional information

A file with the size of 1,970,040,285 bytes can be uploaded, a file with 2,185,874,894 bytes not. I think there might be a problem with files larger than 2GB.
