### ISSUE TITLE
I can't get any version past 1.127.0 to work

### ISSUE THREAD

**Issue by carterlando** [immich-app/immich#17214]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I've installed Immich with docker but watching it in Portainer immich_server and immich_postgres both show as either 'starting' or 'unhealthy'

I have no idea what I'm supposed to do to fix the issue.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v1.130.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH_MIHA}:/usr/src/app/external_miha
      - ${EXTERNAL_PATH_CATA}:/usr/src/app/external_cata
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    command: redis-server --appendonly no --save ""
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/cata/ssd_1t/mediaLibrary
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=hidden

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

EXTERNAL_PATH_MIHA=/media/cata/bkp_1t/Photos/Mihaela
EXTERNAL_PATH_CATA=/media/cata/bkp_1t/Photos/Catalin
```

### Reproduction steps

I'm just using 'docker compose pull && docker compose up' to upgrade from v1.127.0

### Relevant log output

```shell
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 6  - 03/29/2025, 4:17:15 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | [Nest] 6  - 03/29/2025, 4:17:15 PM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
immich_server            | [Nest] 16  - 03/29/2025, 4:17:15 PM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | Migration "AddUpdateIdColumns1740586617223" failed, error: invalid page in block 1289 of relation base/16384/17603
immich_server            | QueryFailedError: invalid page in block 1289 of relation base/16384/17603
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |     at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
immich_server            |     at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20) {
immich_server            |   query: 'UPDATE "asset_files" SET "updateId" = immich_uuid_v7("updatedAt")',
immich_server            |   parameters: undefined,
immich_server            |   driverError: error: invalid page in block 1289 of relation base/16384/17603
immich_server            |       at /usr/src/app/node_modules/pg/lib/client.js:545:17
immich_server            |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_server            |       at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |       at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |       at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |       at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20 {
immich_server            |     length: 118,
immich_server            |     severity: 'ERROR',
immich_server            |     code: 'XX001',
immich_server            |     detail: undefined,
immich_server            |     hint: undefined,
immich_server            |     position: undefined,
immich_server            |     internalPosition: undefined,
immich_server            |     internalQuery: undefined,
immich_server            |     where: undefined,
immich_server            |     schema: undefined,
immich_server            |     table: undefined,
immich_server            |     column: undefined,
immich_server            |     dataType: undefined,
immich_server            |     constraint: undefined,
immich_server            |     file: 'bufmgr.c',
immich_server            |     line: '1037',
immich_server            |     routine: 'ReadBuffer_common'
immich_server            |   },
immich_server            |   length: 118,
immich_server            |   severity: 'ERROR',
immich_server            |   code: 'XX001',
immich_server            |   detail: undefined,
immich_server            |   hint: undefined,
immich_server            |   position: undefined,
immich_server            |   internalPosition: undefined,
immich_server            |   internalQuery: undefined,
immich_server            |   where: undefined,
immich_server            |   schema: undefined,
immich_server            |   table: undefined,
immich_server            |   column: undefined,
immich_server            |   dataType: undefined,
immich_server            |   constraint: undefined,
immich_server            |   file: 'bufmgr.c',
immich_server            |   line: '1037',
immich_server            |   routine: 'ReadBuffer_common'
immich_server            | }
immich_server            | microservices worker error: QueryFailedError: invalid page in block 1289 of relation base/16384/17603, stack: QueryFailedError: invalid page in block 1289 of relation base/16384/17603
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |     at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
immich_server            |     at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server exited with code 0
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 03/29/2025, 4:18:47 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | [Nest] 7  - 03/29/2025, 4:18:47 PM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
immich_server            | [Nest] 17  - 03/29/2025, 4:18:47 PM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | Migration "AddUpdateIdColumns1740586617223" failed, error: invalid page in block 1289 of relation base/16384/17603
immich_server            | QueryFailedError: invalid page in block 1289 of relation base/16384/17603
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |     at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
immich_server            |     at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20) {
immich_server            |   query: 'UPDATE "asset_files" SET "updateId" = immich_uuid_v7("updatedAt")',
immich_server            |   parameters: undefined,
immich_server            |   driverError: error: invalid page in block 1289 of relation base/16384/17603
immich_server            |       at /usr/src/app/node_modules/pg/lib/client.js:545:17
immich_server            |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_server            |       at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |       at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |       at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |       at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20 {
immich_server            |     length: 118,
immich_server            |     severity: 'ERROR',
immich_server            |     code: 'XX001',
immich_server            |     detail: undefined,
immich_server            |     hint: undefined,
immich_server            |     position: undefined,
immich_server            |     internalPosition: undefined,
immich_server            |     internalQuery: undefined,
immich_server            |     where: undefined,
immich_server            |     schema: undefined,
immich_server            |     table: undefined,
immich_server            |     column: undefined,
immich_server            |     dataType: undefined,
immich_server            |     constraint: undefined,
immich_server            |     file: 'bufmgr.c',
immich_server            |     line: '1037',
immich_server            |     routine: 'ReadBuffer_common'
immich_server            |   },
immich_server            |   length: 118,
immich_server            |   severity: 'ERROR',
immich_server            |   code: 'XX001',
immich_server            |   detail: undefined,
immich_server            |   hint: undefined,
immich_server            |   position: undefined,
immich_server            |   internalPosition: undefined,
immich_server            |   internalQuery: undefined,
immich_server            |   where: undefined,
immich_server            |   schema: undefined,
immich_server            |   table: undefined,
immich_server            |   column: undefined,
immich_server            |   dataType: undefined,
immich_server            |   constraint: undefined,
immich_server            |   file: 'bufmgr.c',
immich_server            |   line: '1037',
immich_server            |   routine: 'ReadBuffer_common'
immich_server            | }
immich_server            | microservices worker error: QueryFailedError: invalid page in block 1289 of relation base/16384/17603, stack: QueryFailedError: invalid page in block 1289 of relation base/16384/17603
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server            |     at async AddUpdateIdColumns1740586617223.up (/usr/src/app/dist/migrations/1740586617223-AddUpdateIdColumns.js:50:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:188:9)
immich_server            |     at async /usr/src/app/dist/services/database.service.js:93:17
immich_server            |     at async /usr/src/app/dist/repositories/database.repository.js:197:27
immich_server            |     at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
immich_server            |     at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
```
