### ISSUE TITLE
[BUG] v.1.30.x Server unable to extract date metadata for some images.

### ISSUE THREAD

**Issue by iBenzene** [immich-app/immich#17218]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

For certain images, iOS apps are able to correctly recognize their metadata and display them in the correct position on the timeline before uploading (such as 2022-11-10). However, after the images are uploaded, the server cannot extract the creation or modification dates of these images, so the time of these images will be mistakenly changed to the current time (2025-03-xx).

I know that metadata extraction is implemented on the server side rather than the client side, so I kept the client version v1.130.3 unchanged during testing. After testing, this issue did not occur in server versions v1.21.0, v1.24.2, and v.1.29.0 after rollback. But when the server version was upgraded to v1.30.0, this bug occurred and was not fixed in v.130.3.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.21.0、v1.24.2、v.1.29.0、v1.30.0 - v1.30.3 (bug occurred)

### Version of Immich Mobile App

v1.30.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # image: altran1502/immich-server:v1.130.0
    # image: altran1502/immich-server:v1.129.0
    # image: altran1502/immich-server:v1.124.2
    # image: altran1502/immich-server:v1.121.0
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immich-network
    ports:
      - 2283:2283
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    networks:
      - immich-network
    env_file:
      - stack.env
    healthcheck:
      disable: false
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      - immich-network
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich-network
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

networks:
  immich-network:
    driver: bridge
    name: immich

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-aca50c78-30ca-48d1-b482-87fb577d8da3/Immich/upload
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-aca50c78-30ca-48d1-b482-87fb577d8da3/Immich/data
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
[Nest] 7  - 03/29/2025, 7:23:44 PM    WARN [Microservices:MetadataService] Missing file creation or modification date for asset 2a9162d8-a531-4a6f-b832-7fd202cdbea5: upload/upload/4d4fc28b-a22f-429d-8a5e-c88a7f86481d/d0/7d/d07d061c-48ea-4cee-8727-e522c61defcf.PNG
﻿
[Nest] 7  - 03/29/2025, 7:23:44 PM    WARN [Microservices:MetadataService] Missing file creation or modification date for asset 676f2203-843a-4316-8bcd-b41d4cbce186: upload/upload/4d4fc28b-a22f-429d-8a5e-c88a7f86481d/3a/c2/3ac21742-1db5-4d89-a5af-5c5705905964.JPG
```
