### ISSUE TITLE
Mobile: quickly swiping between MotionPhoto enabled and normal pictures breaks the gallery view

### ISSUE THREAD

**Issue by viv24pt** [immich-app/immich#17220]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When quickly swiping through the gallery after enabling MotionPhoto playback, the gallery view can get stuck on the still picture part of a MotionPhoto.  
Swiping to new photos does renders them until they are the active picture at which point they become invisible.   
If they are also MotionPhotos, their video part still gets rendered.  
Exiting the gallery back to the timeline or stopping MotionPhoto playback resolves the issue.  

https://github.com/user-attachments/assets/6f817147-2459-45d6-9e9a-17e659ff5f01

### The OS that Immich Server is running on

Ubuntu 24.04.2 

### Version of Immich Server

1.30.3

### Version of Immich Mobile App

1.130.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

networks:
  immich-internal:
    external: false


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich-internal
    ports:
      - 127.0.0.1:4001:2283



  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
      - immich-internal

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-internal

volumes:
  pgdata:
  model-cache:
  #tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=
TYPESENSE_API_KEY=
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich_server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003
```

### Reproduction steps

1. Open a MotionPhoto picture in the android app
2. Quickly swipe back and forth between the MotionPhoto and another normal picture

### Relevant log output

```shell

```
