### ISSUE TITLE
Unable to run 2 Instances of Immich on the Same Docker Host

### ISSUE THREAD

**Issue by pipe-organ** [immich-app/immich#17227]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm attempting to run two independent instances of Immich on the same Docker host. I've attached the origial (1st) immich's docker compose and did the following:
- Unique services names
- Unique container names
- Gave each container fresh IPs
- Changed   depends_on:  - redis - database to new service names
but the second one fail to start properly. Is there a correct way to do this? 
Please help! Thank you so much in advance.

### The OS that Immich Server is running on

Fedora Server 41

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

Not using mobile

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photo/incoming:/mnt/photo/incoming
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      vlan30_network:
        ipv4_address: 192.168.30.53
        mac_address: 86:2b:c2:29:2a:de





  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      vlan30_network:
        ipv4_address: 192.168.30.54
        mac_address: 7e:8c:bd:e4:0c:18




  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      vlan30_network:
        ipv4_address: 192.168.30.55
      
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
    networks:
      vlan30_network:
        ipv4_address: 192.168.30.56
        mac_address: 62:45:7b:b3:73:e9

volumes:
  model-cache:

networks:
  vlan30_network:
    external: true
```

### Your .env content

```Shell
(portainer)stack.env
UPLOAD_LOCATION: /mnt/ssd/docker-data/immich/upload
DB_DATA_LOCATION: /mnt/ssd/docker-data/immich/postgres
IMMICH_VERSION: release
DB_PASSWORD: postgres
DB_USERNAME: postgres
DB_DATABASE_NAME: immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
