### ISSUE TITLE
Missing nested subfolders in external library

### ISSUE THREAD

**Issue by psychoberries** [immich-app/immich#17224]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Thank you very much for this app. It is truly a wonder!
  
After successfully adding my first external library, upon scanning it, I noticed that:

- if a subfolder at level 2 depth (see graph below for level explanation) contains only subfolders but no pictures, even if these subfolders (Level 3) do contain pictures, Immich skips any pictures contained in the L3 subfolders, and neither the L2 folder nor the L3 folders are shown in the folder view (if folder view is enabled in the the user settings)

  
  This happens when I check the contents in a browser. I have not tried the the mobile app.
  
However:

1. if I add any picture to a L2 missing folder and rescan the library, Immich does find the folder. It will still not show the subfolders.
2. if I add the missing folder path as an additional import path of the same library and rescan the library, Immich does find the folder and its subfolders. However, I have plenty of subfolders, so it would be impractical to manually add them all.

  
In the example below:

1. ./mnt/media/BKPGO is level 0 and it is the external library import path
2. .Immich does not list pictures from UK>event3 and any of its subfolders. No pictures are containted in event3. Its subfolders do contain pictures.
3. ./mnt/media/BKPGO/UK/event2 contains a picture and 2 subfolders. Event2 is listed, but its sbufolders and their content are not.
4. .everything else seems to be correctly listed. E.G.  /mnt/media/BKPGO/Spain/Stuff1 works
5. .I tried adding/mnt/media/BKPGO/UK/event3 as an import path to the same library, but nothing changed
6. .I tried adding/mnt/media/BKPGO/UK/event3 as an import path to the a new library, but Immich reports "1 Path failed validation"
7. .The folders are contained in a NTFS drive. Read/Write permissions and user access seem to be identical for offending and non offending folders.

  
![Image](https://github.com/user-attachments/assets/f4a87b3f-d18f-4f8a-b5af-4f9cd6df57fe)

  
  
  Is there any setting that specifies the depth of a library scan?
  Thank you very much for any pointers.

### The OS that Immich Server is running on

Win 10 Home, 10.0.19045

### Version of Immich Server

1.130.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "./mydata/BKPGO:/mnt/media/BKPGO"
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - './db_dumps/:/db_dumps'
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./immich-data
# The location where your database files are stored
DB_DATA_LOCATION=./immich-postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
 TZ=Asia/Tokyo

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<Redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.Import external folder with structure as per example in main text
2.Scan library
3.Check if L3 folders and their files are missing
...

### Relevant log output

```shell

```

### Additional information

Immich is launched via Docker Desktop 4.39.0 (184744)
