### ISSUE TITLE
Can't see archive and update of library in mobile apps (iOS ans Android

### ISSUE THREAD

**Issue by yukes33** [immich-app/immich#17232]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi everyone, 
First of all, thank for this amazing piece of software. Using it for the past months replacing Synology Photos (Moments) and won't ever going back 👍 .

I'm having an issue on mobile apps (realizing it just this week but the issue may be older).

While opening the app on iOS and Android, both phones can't see any photos on the Archive album (showing 0 as the number of photos even though it's not). Moreover, all the new uploaded photos are not shown in the mobile apps. The uploads are done (the web library is perfectly fine with new uploads coming from both phones) but don't show up on any phone. The first phone showing its own photos not backed up although they are in the web library, and the same for the other phone.

The log shows the following error : 
2025-03-30 12:05:54.038893 | severe   | AssetService         | Error while getting remote assets | Null check operator used on a null value |
#0      AssetResponseDto.fromJson (package:openapi/model/asset_response_dto.dart:291)
#1      ApiClient.fromJson (package:openapi/api_client.dart:264)
#2      ApiClient.fromJson.<anonymous closure> (package:openapi/api_client.dart:683)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:402)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:371)
#5      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:166)
#6      new _List.of (dart:core-patch/array.dart:130)
#7      new List.of (dart:core-patch/array_patch.dart:40)
#8      ListIterable.toList (dart:_internal/iterable.dart:224)
#9      ApiClient.fromJson (package:openapi/api_client.dart:684)
#10     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#11     SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:147)
<asynchronous suspension>
#12     AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:149)
<asynchronous suspension>
#13     SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:291)
<asynchronous suspension>
#14     SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:281)
<asynchronous suspension>
#15     SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:110)
<asynchronous suspension>
#16     AsyncMutex.run.<anonymous closure> (package:immich_mobile/utils/async_mutex.dart:15)
<asynchronous suspension>

Tried the database fix to see if there were same odd aloe files and I don't have any : 
root@docker:~# docker exec immich_postgres psql --dbname=immich --username=postgres -c 'select a."fileModifiedAt" from assets a order by a."fileModifiedAt" limit 10;'
     fileModifiedAt     
------------------------
 2003-09-21 19:54:54+00
 2006-09-02 12:04:44+00
 2006-09-02 15:16:48+00
 2006-09-02 15:58:26+00
 2006-09-08 12:00:22+00
 2006-09-08 13:37:32+00
 2006-09-08 13:38:40+00
 2006-09-08 13:39:32+00
 2006-09-08 13:39:44+00
 2006-09-08 13:40:42+00
(10 rows)

Don't know how to fix it (tried also a local access instead of NPM and didn't work).

Thanks for the help

### The OS that Immich Server is running on

LXC in Proxmox

### Version of Immich Server

1.130.3

### Version of Immich Mobile App

1.130.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    # Transcodage materiel : NAS avec un processeur Intel, retirer les 2 # ci-dessous
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/nas/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/nas/photos/:/mnt/media/photo
    environment:
      UPLOAD_LOCATION: /usr/src/app/upload
      TZ: Europe/Paris
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /docker/immich/model-cache:/cache
    environment:
      TZ: Europe/Paris
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.1
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      #PUID: 999
    volumes:
      - /docker/immich/postgres:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="immich" --username="postgres" || exit 1;
      interval: 5m
      retries: 3
      start_period: 5m
    restart: always
networks: {}
```

### Your .env content

```Shell
-
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
