### ISSUE TITLE
Photos from external libraries show up in the web-GUI but not in the Android App

### ISSUE THREAD

**Issue by MrStrobe** [immich-app/immich#17243]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi,
First of all thanks for the great project and all your hard work!
I'm running Immich v1.130.3 on Docker with an external library mounted via Docker volume. I successfully scanned and indexed all photos and videos from that external source. The files are visible in the web UI and I can browse them just fine.

However, in the mobile app, these photos do not appear in the main "Library" stream. They are only accessible under the "Folders" section in the app.

I would like to see these external assets in the main photo stream of the app.

Expected behavior:
Assets visible in external libraries should optionally be shown in the app stream.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v1.130.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/                                                                                                             docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.y                                                                                                             ml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl]                                                                                                              for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage locat                                                                                                             ion on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /data/immich/import-from-nextcloud:/mnt/nextcloud-import:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn]                                                                                                              to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://                                                                                                             immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl,                                                                                                              rknn] for accelerated inference - use the `-wsl` version for WSL2 where applica                                                                                                             ble
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    devices:
      - /dev/dri:/dev/dri

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123e                                                                                                             eb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f7                                                                                                             96dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage lo                                                                                                             cation on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||                                                                                                              exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}                                                                                                             " --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0)                                                                                                              FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksu                                                                                                             m" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user",                                                                                                              public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=5                                                                                                             12MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-08a5e45f-e6be-423c-90a7-66dfb02423a3/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-08a5e45f-e6be-423c-90a7-66dfb02423a3/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the app
2. All assets, that were not uploaded from this devices (imported via external libraries) are not visible
3. open Web-GUI
4. All assets are visible
...

### Relevant log output

```shell

```
