### ISSUE TITLE
People "Featured Photo" from external library comes in as very blury

### ISSUE THREAD

**Issue by Nertskull** [immich-app/immich#17245]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have a fresh install. I added an external library with a few photos (already tagged in digikam w/ faces and .xmp sidecar files).  The names and faces come in. But the featured photo looks as below.

![Image](https://github.com/user-attachments/assets/d9111c10-4e2a-435d-a832-f6bc004ebe0b).

### The OS that Immich Server is running on

Ubuntu 20.04.6

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v1.130.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: ${PUID}:${PGID}
    volumes:
      - ${DATA_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
        # Photos
      - ${EXTERNAL_PHOTOS}/2012:/mnt/media/photos/2012
      - ${EXTERNAL_PHOTOS}/2017:/mnt/media/photos/2017
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${DATA_LOCATION}/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    #image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    #image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    #image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07
    #image: tensorchord/pgvecto-rs:pg14-v0.1.11
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DATA_LOCATION}/pgdata:/var/lib/postgresql/data
    restart: always

#volumes:
  #pgdata:
  #model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
DATA_LOCATION=./immichData
EXTERNAL_PHOTOS=./externalPhotos
EXTERNAL_VIDEOS=./externalVideos

PUID=1000
PGID=1000

TZ=America/New_York

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.130.3

# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=###

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Install
2. Turn on face detection/machine learning
3. Add external library of faces above
4. Let scan and wait for people to be deteceted
5. Go to People page and see like the photo above
...

### Relevant log output

```shell
No errors
```

### Additional information

Half of the files I uploaded were .NEF (nikon raw) and half were .jpg from a phone. Initially I was thinking it was maybe a raw photo picture, but I don't think it is.

I've tried redoing thumbnails at small and large sizes and then re-assigning featured photos. The thumbnail for the featured photo may change a little, but it never gives me a full face.

In the individual photos page, the "selection box" for the identified face does cover the whole face, but it's like the thumbnail for the "featured photo" is only like 30 pixels and small.

There is ony photo you can see in the third row that kind of gets the face correctly, this is a very small face in the background, an quite small in the photo, and it seems to kind of work.  So my theory is that maybe "featured photos" are being selected from the full size image, but only getting a few pixels that should be coming from a different thumbnail that is smaller, but instead getting just a few pixels from the full size photo. No idea if that's actually what is happening though.
