### ISSUE TITLE
Mobile android app shows only photos in albums

### ISSUE THREAD

**Issue by solluh** [immich-app/immich#17255]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Just like #16046 and #17249 my 2 mobile devices are showing only photos marked as "in album".
The solutions posted here didn't work.

#16046:
1st answer: 

```
      fileCreatedAt      
------------------------
 1962-10-01 09:21:06+01 
 1963-04-14 12:36:03+01 
 1963-10-06 11:31:45+01
 1966-03-15 10:23:35+01
 1966-05-25 11:37:30+01
 1966-08-01 11:34:00+01
 1966-11-15 11:33:51+01
 1968-09-10 11:34:07+01
 1968-12-01 13:01:01+01
 1969-11-01 08:18:59+01
(10 rows)
```
2nd answer:

```
     fileModifiedAt     
------------------------
 2000-05-16 22:44:20+02
 2000-05-16 22:44:56+02
 2000-05-16 22:45:40+02
 2001-07-14 16:40:06+02
 2001-07-14 16:47:06+02
 2001-07-14 17:17:12+02
 2001-07-14 17:17:42+02
 2001-07-14 17:18:46+02
 2001-07-14 18:04:14+02
 2001-07-14 18:18:28+02
(10 rows)
```

So no wrong dates in my database.

What can I do to get my mobile's immich working correctly?

### The OS that Immich Server is running on

Synology NAS via Portainer

### Version of Immich Server

v1.130.3

### Version of Immich Mobile App

v1.130.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=******
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:101
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/immichphotos:/usr/src/app/upload:rw     #neu
      - /volume1/photo:/photo:rw
      - /volume1/homes/Solluh/Photos:/solluh:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/immichphotos:/usr/src/app/upload:rw    #neues
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
---
```

### Reproduction steps

1. Open mobile app
2. Timeline not complete
3. Check logs

### Relevant log output

```shell
Message
Error while getting remote assets

Details
Null check operator used on a null value

From
Assetservice

Stack Trace
Null check operator used on a null value

#0      AssetResponseDto.fromJson (package:openapi/model/asset_response_dto.dart:291)
#1      ApiClient.fromJson (package:openapi/api_client.dart:264)
#2      ApiClient.fromJson.<anonymous closure> (package:openapi/api_client.dart:683)
#3      MappedIterable.elementAt (dart:_internal/iterable.dart:402)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:371)
#5      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:166)
#6      new _List.of (dart:core-patch/array.dart:130)
#7      new List.of (dart:core-patch/array_patch.dart:40)
#8      ListIterable.toList (dart:_internal/iterable.dart:224)
#9      ApiClient.fromJson (package:openapi/api_client.dart:684)
#10     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#11     SyncApi.getFullSyncForUser (package:openapi/api/sync_api.dart:147)
<asynchronous suspension>
#12     AssetService._getRemoteAssets (package:immich_mobile/services/asset.service.dart:149)
<asynchronous suspension>
#13     SyncService._syncRemoteAssetsForUser (package:immich_mobile/services/sync.service.dart:291)
<asynchronous suspension>
#14     SyncService._syncRemoteAssetsFull (package:immich_mobile/services/sync.service.dart:281)
<asynchronous suspension>
#15     SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/services/sync.service.dart:110)
<asynchronous suspension>
#16     AssetService.refreshRemoteAssets (package:immich_mobile/services/asset.service.dart:90)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/providers/asset.provider.dart:68)
<asynchronous suspension>
#18     AppLifeCycleNotifier.handleAppResume (package:immich_mobile/providers/app_life_cycle.provider.dart:71)
<asynchronous suspension>
```

### Additional information

My photos mostly are located in external libraries.
Thanks in advance, I preciate it!

Solluh
