### ISSUE TITLE
Updating to v1.131.0 permissions and machine-learning issues

### ISSUE THREAD

**Issue by andreibrebene** [immich-app/immich#17267]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Until updating to v1.131.0, everything worked fine, without error regarding the containers running as non-root. When I first created the immich docker-compose I used this FAQ to run it with non-root, https://immich.app/docs/FAQ/#how-can-i-run-immich-as-a-non-root-user and it was running without issues until version v1.131.0, now I rollback to v1.130.3 to be able to run it.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.131.0

### Version of Immich Mobile App

v1.130.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# Immich Cloud Standalone Docker Compose

networks:
  home_network:
    external: true

services:

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: "1000:1000"
    group_add:
      - 105
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    extends:
      file: ./immich-server/hwacceleration/hwaccel.transcoding.yml
      service: quicksync
    networks:
      - home_network
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    user: "1000:1000"
    group_add:
      - 105
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    extends:
      file: ./immich-server/hwacceleration/hwaccel.ml.yml
      service: openvino
    networks:
      - home_network
    volumes:
      - ${MODEL_CACHE_LOCATION}:/cache
      - ./immich-server/machine-learning:/.config
      - ./immich-server/machine-learning:/.cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    networks:
      - home_network
    volumes:
      - ${REDIS_DATA_LOCATION}:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW
    networks:
      - home_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/cloud/immich
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=test
DB_DATABASE_NAME=test
MODEL_CACHE_LOCATION=/cloud/immich/model-cache
REDIS_DATA_LOCATION=./redis
```

### Reproduction steps

1. Update the containers to v1.131.0.
2. Run the containers.

### Relevant log output

```shell
Machine-Learning container:
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[03/31/25 23:35:21] INFO     Starting gunicorn 23.0.0                           
[03/31/25 23:35:21] INFO     Listening at: http://[::]:3003 (8)                 
[03/31/25 23:35:21] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[03/31/25 23:35:21] INFO     Booting worker with pid: 9                         
[03/31/25 23:35:22] INFO     Started server process [9]                         
[03/31/25 23:35:22] INFO     Waiting for application startup.                   
[03/31/25 23:35:22] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[03/31/25 23:35:22] INFO     Initialized request thread pool with 18 threads.   
[03/31/25 23:35:22] INFO     Application startup complete.  

Immich-Server:
microservices worker error: Error: EACCES: permission denied, mkdir '/usr/src/app/dist/schema/migrations', stack: Error: EACCES: permission denied, mkdir '/usr/src/app/dist/schema/migrations'
    at async mkdir (node:internal/fs/promises:857:10)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:195:9)
    at async /usr/src/app/dist/services/database.service.js:93:17
    at async /usr/src/app/dist/repositories/database.repository.js:228:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async /usr/src/app/dist/repositories/database.repository.js:225:13
microservices worker exited with code 1
```
