### ISSUE TITLE
machine_learning container unhealthy after 1.131.1 Update.

### ISSUE THREAD

**Issue by juanjax** [immich-app/immich#17275]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Well, out of no where, all of a sudden. My machine_learning container is unhealthy. Any ideas?

No Proxies used or defined.

Why after 1.131.1?

Also, I've noticed when pulling down new containers sometimes it errors out. Like servers a busy or something. I keep trying and it eventually updates. But, why? Is this normal?

By the way, I'm using standard Docker_Compose.yml

### The OS that Immich Server is running on

Promox Debian 12

### Version of Immich Server

1.131.1

### Version of Immich Mobile App

1.130.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#
#     *** ADDED DEVICE FOR HWACCEL ***
#
    devices:
      - "/dev/dri:/dev/dri" 
#      
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
#     - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
#     - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
#     - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
#    network_mode: bridge

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-openvino
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
#    network_mode: bridge


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
#   image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672    
    restart: always
#    network_mode: bridge

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
#   image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0    

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
#    network_mode: bridge
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Photos
DB_DATA_LOCATION=/mnt/LXCs-AppData/Docker-Containers/immich/data
THUMBS_LOCATION=/mnt/thumbs
IMMICH_VERSION=release
DB_PASSWORD=-----
DB_USERNAME=----
DB_DATABASE_NAME=immich
TYPESENSE_API_KEY=----
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
