### ISSUE TITLE
Cannot change dates of assets in v1.131.1

### ISSUE THREAD

**Issue by mooinglemur** [immich-app/immich#17281]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

It appears with 1.131.1, and possibly earlier, that I am no longer able to edit the date of an asset through the web interface.   The interface accepts the new date and time, but it retains the old date and time.

I **can** however change the asset's time zone.  It's only the dates/times that are not changing.

This happens on both images with embedded EXIF data, as well as assets without.

At the same time, I get an error that I can see with the command `docker compose logs -f`

```
immich_server            | [Nest] 7  - 04/01/2025, 1:06:18 AM    WARN [Microservices:MetadataService] Missing file creation or modification date for asset 3bdd1b9b-00cc-49cb-828f-ec0931e90549: upload/library/admin/2010/2010-06-15/2010-06-15 21.03.45.jpg
```

### The OS that Immich Server is running on

Rocky Linux 9.5, docker

### Version of Immich Server

v1.131.1

### Version of Immich Mobile App

v1.130.0 build.1.8.8

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:                                           
  check-mount:  
    image: busybox
    command: ["sh", "-c", "if [ ! -d /localdata/immich-app ]; then echo 'Mount not found, exiting with failure.'; exit 1; fi; echo 'Mount detected.'; while true; do sleep 10; done"]
    volumes:                                                                                                                                 
      - /localdata:/localdata:ro                                                                                                             
    restart: always                               
    healthcheck:                      
      test: ["CMD", "test", "-d", "/localdata/immich-app"]
      interval: 5s       
      retries: 1      
      start_period: 2s
                                                                      
  immich-server:                            
    container_name: immich_server               
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release} 
    # extends:           
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:       
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env                                                                                                                                 
    ports:               
      - '2283:2283'
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
      check-mount:
        condition: service_healthy
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:         
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:                           
      POSTGRES_PASSWORD: ${DB_PASSWORD}                                                                                                      
      POSTGRES_USER: ${DB_USERNAME}               
      POSTGRES_DB: ${DB_DATABASE_NAME}                                                                                                       
      POSTGRES_INITDB_ARGS: '--data-checksums'                                                                                               
    volumes:                
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:          
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s       
      start_period: 5m                                                                                                                       
    command: >- 
      postgres                      
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB          
      -c shared_buffers=512MB                                                                                                                
      -c wal_compression=on
    restart: always                    
                                                                      
volumes:                              
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/localdata/immich-app
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
