### ISSUE TITLE
Immich machine learning container unhealthy from version 1.131.0 and up

### ISSUE THREAD

**Issue by tgruijters** [immich-app/immich#17291]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

From the immich_machine_learning container it reports that it can't load an object.

ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

The object is not there. However version 1.130.3 doesn't need the object?

This way the docker container of immich_machine_learning reports 'unhealthy'.

### The OS that Immich Server is running on

Unraid OS 7.0

### Version of Immich Server

v1.131.1

### Version of Immich Mobile App

v1.131.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.131.1
    restart: on-failure
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - database
    networks:
      immich:
        aliases:
          - immich_server
      swarm:
    devices:
      - /dev/dri:/dev/dri
    environment:
      PUID: ${PUID:-99}
      PGID: ${PGID:-100}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    labels:
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/109746326?s=200&v=4.png
      net.unraid.docker.managed: dockge
      net.unraid.docker.shell: /bin/sh     
  
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.1-openvino
    restart: on-failure
    volumes:
      - /dev/shm/cache/immich/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    networks:
      immich:
        aliases:
          - immich_machinelearning
    devices:
      - /dev/dri:/dev/dri
    device_cgroup_rules:
      - c 189:* rmw
    labels:
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/109746326?s=200&v=4.png
      net.unraid.docker.managed: dockge
      net.unraid.docker.shell: /bin/sh     
 
  redis:
    container_name: immich_redis
    image: redis:${REDIS_VERSION:-latest}
    restart: on-failure
    volumes:
      - /dev/shm/cache/immich/redis:/data
    networks:
      immich:
        aliases:
          - immich_redis
    labels:
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/1529926?s=200&v=4.png
      net.unraid.docker.managed: dockge
      net.unraid.docker.shell: /bin/sh 

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:${POSTGRES_VERSION:-latest}
    restart: on-failure
    volumes:
      - ${APPDATA}/immich/postgresql:/var/lib/postgresql/data
    networks:
      immich:
        aliases:
          - immich_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    labels:
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/177543?s=200&v=4.png
      net.unraid.docker.managed: dockge
      net.unraid.docker.shell: /bin/sh       

networks:
  immich:
    name: immich
    driver: bridge
  swarm:
    name: swarm-overlay
    external: true
```

### Your .env content

```Shell
# Global Configuration
APPDATA=<redacted>
PUID=99
PGID=100

# Versions
REDIS_VERSION=6.2-alpine
POSTGRES_VERSION=pg14-v0.2.0

# Application configuration
UPLOAD_LOCATION=<redacted>

DB_HOSTNAME=<redacted>
DB_DATABASE_NAME=<redacted>
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
```

### Reproduction steps

1.Update from immich_server 1.130.3 to 1.131.1.
2. Update from immich_machine_learning 1.130.3 tot 1.131.1
3. Rolled back both immich_server and immich_machine_learning from 1.131.1 to 1.131.0
...

### Relevant log output

```shell
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libmimalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[04/01/25 07:09:14] INFO     Starting gunicorn 23.0.0                           
[04/01/25 07:09:14] INFO     Listening at: http://[::]:3003 (8)                 
[04/01/25 07:09:14] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[04/01/25 07:09:14] INFO     Booting worker with pid: 9                         
[04/01/25 07:09:18] INFO     Started server process [9]                         
[04/01/25 07:09:18] INFO     Waiting for application startup.                   
[04/01/25 07:09:18] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/01/25 07:09:18] INFO     Initialized request thread pool with 4 threads.    
[04/01/25 07:09:18] INFO     Application startup complete.
```

### Additional information

Because of this, the immich_machine_learning docker container reports an "unhealthy" status and it triggers the monitoring and so on.
