### ISSUE TITLE
Migration wrongly renames thumb to fullsize on 1.131.0 to 1.131.2

### ISSUE THREAD

**Issue by nalsai** [immich-app/immich#17301]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Running the MIGRATION job on any version from 1.131.0 to 1.131.2 breaks the thumbnails for me. Looking at the thumbs directory, it seems that the migration renames my -thumb.webp files to -fullsize.jpeg which results in immich being unable to find them.

### The OS that Immich Server is running on

Fedora Linux 41

### Version of Immich Server

v1.131.2

### Version of Immich Mobile App

v1.130.3 build.199

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.hachiman.nils.moe`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]
    restart: always
    networks:
      - internal

volumes:
  model-cache:

networks:
  internal:
  traefik:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/immich
THUMB_LOCATION=/mnt/data-ssd/immich/thumbs
ENCODED_VIDEO_LOCATION=/mnt/data-ssd/immich/encoded-video
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=SECRET

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Start any immich version between 1.131.0 and 1.131.2
2. Upload some pictures and let it create thumbnails
3. Run the MIGRATION job

### Relevant log output

```shell
immich_server            | [Nest] 17  - 04/01/2025, 2:35:13 PM   ERROR [Api:LoggingRepository~uqww815i] Unable to send file: Error
immich_server            | Error: ENOENT: no such file or directory, access 'upload/thumbs/26f57f60-bc4e-4f4c-93f8-2f7cd0e1353c/cb/c7/cbc75bc8-743c-48c5-9ace-878ac8beaf78-thumbnail.webp'
immich_server            |     at async access (node:internal/fs/promises:605:10)
immich_server            |     at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
immich_server            |     at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:60:13)
immich_server            | [Nest] 17  - 04/01/2025, 2:35:13 PM   ERROR [Api:GlobalExceptionFilter~uqww815i] Unknown error: Error: ENOENT: no such file or directory, access 'upload/thumbs/26f57f60-bc4e-4f4c-93f8-2f7cd0e1353c/cb/c7/cbc75bc8-743c-48c5-9ace-878ac8beaf78-thumbnail.webp'
immich_server            | Error: ENOENT: no such file or directory, access 'upload/thumbs/26f57f60-bc4e-4f4c-93f8-2f7cd0e1353c/cb/c7/cbc75bc8-743c-48c5-9ace-878ac8beaf78-thumbnail.webp'
immich_server            |     at async access (node:internal/fs/promises:605:10)
immich_server            |     at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
immich_server            |     at async AssetMediaController.viewAsset (/usr/src/app/dist/controllers/asset-media.controller.js:60:13)
```
