### ISSUE TITLE
android app "upload to immich" screen UI/UX issues

### ISSUE THREAD

**Issue by LaurentAtJoes** [immich-app/immich#17302]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I found 2 issues with the Share > Upload to Immich feature on my android phone.
(NB: not brand new, Samsung S9 + android 10, if needed I can test on a newer galaxy tablet, or my wife's S21)

FIRST ISSUE :
if the Immich app is closed when you start the action of sharing, it opens on the Upload screen, but then goes back to the timeline (as if a start-up navigation was triggered on open, but here should be by-passed when accessing directly the upload screen)
See video IMMICH_01.mp4 (and note there is no screen tap or action when it switches to the timeline)

SECOND ISSUE :
once the app is open, you can indeed upload the picture, but then if you go back directly to the phone's gallery, and choose to upload another image, the "upload" button on the upload screen stays disabled, as if it wasn't refreshed from showing previous upload results.
See video IMMICH_02.mp4

### The OS that Immich Server is running on

Docker on Ubuntu 22.04.5

### Version of Immich Server

v1.131.2

### Version of Immich Mobile App

v1.130.3 build 191

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
# NOTE : ML is running on remote machine

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume1/homes/XXX/Photos:/mnt/media/xxx:rw
      - /volume1/homes/YYY/Photos:/mnt/media/yyy:rw
      - /volume1/Photos/_DIVERS_:/mnt/media/divers:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false


  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      #start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/Photos/_IN_
DB_DATA_LOCATION=/volume1/docker/immich-2/pgdata

IMMICH_VERSION=release

DB_PASSWORD=**********

# The values below this line do not need to be changed
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

FIRST ISSUE :
1. Make sure Immich app is closed on mobile device
2. From the device's pictures, Share > Upload to Immich
3. Immich app opens, briefly shows upload screen, then goes back to timeline...

SECOND ISSUE :
1. Now that the Immich app is open, upload a picture
2. Go back (directly) to the device's gallery, and repeat Share > Upload for another picture
3. The button on upload screen stays disabled

### Relevant log output

```shell

```

### Additional information

https://github.com/user-attachments/assets/8eb569e2-c8b9-4367-a7b8-3cc629b7792e
https://github.com/user-attachments/assets/b48a9369-7426-49ad-b961-71df4611aa39
