### ISSUE TITLE
smart search does not work when using openvino

### ISSUE THREAD

**Issue by banto6** [immich-app/immich#17326]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When using immich-machine-learning:v1.131.3-openvino, every search results in an error and returns an empty value. However, using immich-machine-learning:v1.131.3 works fine. I can't see more detailed logs. If there's a way to do so, please let me know

### The OS that Immich Server is running on

Ubuntu24

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I'm not using Docker Compose, but Kubernetes

containers:
  - image: altran1502/immich-server:v1.131.3
    name: immich-server
    imagePullPolicy: IfNotPresent
    env: &env
    - name: TZ
      value: "Asia/Shanghai"
    - name: DB_HOSTNAME
      value: "immich-dependency"
    - name: DB_USERNAME
      value: "postgres"
    - name: DB_DATABASE_NAME
      value: "immich"
    - name: DB_PASSWORD
      value: "xxxxxxxx"
    - name: REDIS_HOSTNAME
      value: "immich-dependency"
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PASSWORD
      value: "xxxxxxxxx"
    - name: IMMICH_PORT
      value: "3001"
    ports:
    - containerPort: 3001
      name: http
    volumeMounts: &common-mounts
    - name: immich-data
      subPath: uploads
      mountPath: /usr/src/app/upload

  - image: altran1502/immich-machine-learning:v1.131.3-openvino
    name: immich-machine-learning
    imagePullPolicy: IfNotPresent
    env:
    - name: HTTPS_PROXY
      value: "http://proxy.local.com:1080"
    - name: HTTP_PROXY
      value: "http://proxy.local.com:1080"
    - name: IMMICH_HOST
      value: "0.0.0.0"
    - name: IMMICH_PORT
      value: "3003"
    volumeMounts:
    - name: immich-data
      subPath: cache
      mountPath: /cache
    resources:
      limits:
        gpu.intel.com/i915: 1
    livenessProbe:
      httpGet:
        path: /ping
        port: 3003
      initialDelaySeconds: 30
      timeoutSeconds: 10
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. The issue can be reproduced by entering any content into the search bar

### Relevant log output

```shell
immich-server 

Error: Machine learning request '{"clip":{"textual":{"modelName":"nllb-clip-large-siglip__mrl","options":{"language":"zh-CN"}}}}' failed for all URLs                                                                                    │
     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)                                                                                                                           │
     at async MachineLearningRepository.encodeText (/usr/src/app/dist/repositories/machine-learning.repository.js:121:26)                                                                                                                 │
     at async SearchService.searchSmart (/usr/src/app/dist/services/search.service.js:62:27)



immich-machine-learning

│ [04/02/25 03:31:45] INFO     Loading textual model 'nllb-clip-large-siglip__mrl'                                                                                                                                                         │
│                              to memory                                                                                                                                                                                                   │
│ [04/02/25 03:31:45] INFO     Setting execution providers to                                                                                                                                                                              │
│                              ['OpenVINOExecutionProvider',                                                                                                                                                                               │
│                              'CPUExecutionProvider'[], in descending order of                                                                                                                                                            │
│                              preference                                                                                                                                                                                                  │
│ [04/02/25 03:31:58] ERROR    Worker (pid:63) was sent code 139!                                                                                                                                                                          │
│ [04/02/25 03:31:58] INFO     Booting worker with pid: 104                                                                                                                                                                                │
│ [04/02/25 03:32:00] INFO     Started server process [104[]                                                                                                                                                                               │
│ [04/02/25 03:32:00] INFO     Waiting for application startup.                                                                                                                                                                            │
│ [04/02/25 03:32:00] INFO     Created in-memory cache with unloading after 300s                                                                                                                                                           │
│                              of inactivity.                                                                                                                                                                                              │
│ [04/02/25 03:32:00] INFO     Initialized request thread pool with 6 threads.                                                                                                                                                             │
│ [04/02/25 03:32:00] INFO     Application startup complete.
```
