### ISSUE TITLE
process smart search job failed

### ISSUE THREAD

**Issue by drmcachr** [immich-app/immich#17331]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

after I change to nllb model and re-processing all photo, the status page report has two error, and I checked the log

server report as 

[Nest] 6  - 04/02/2025, 4:11:55 PM    WARN [Microservices:MachineLearningRepository] Machine learning request to "http://immich-machine-learning:3003" failed: fetch failed
[Nest] 6  - 04/02/2025, 4:11:55 PM   ERROR [Microservices:{"id":"0389f030-4815-4c53-ae48-3c72a3fca056"}] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"nllb-clip-large-siglip__v1"}}}' failed for all URLs
Error: Machine learning request '{"clip":{"visual":{"modelName":"nllb-clip-large-siglip__v1"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:116:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:103:27)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:156:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

ml report as:

                             │   224 │   │   │   try:                          │
                             │ ❱ 225 │   │   │   │   model.load()              │
                             │   226 │   │   │   except FileNotFoundError as e │
                             │   227 │   │   │   │   if model.model_format ==  │
                             │   228 │   │   │   │   │   raise e               │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:54 in load    │
                             │                                                 │
                             │    51 │   │   self.download()                   │
                             │    52 │   │   attempt = f"Attempt #{self.load_a │
                             │       else "Loading"                            │
                             │    53 │   │   log.info(f"{attempt} {self.model_ │
                             │       '{self.model_name}' to memory")           │
                             │ ❱  54 │   │   self.session = self._load()       │
                             │    55 │   │   self.loaded = True                │
                             │    56 │                                         │
                             │    57 │   def predict(self, *inputs: Any, **mod │
                             │                                                 │
                             │ /usr/src/immich_ml/models/facial_recognition/de │
                             │ tection.py:21 in _load                          │
                             │                                                 │
                             │   18 │   │   super().__init__(model_name, **mod │
                             │   19 │                                          │
                             │   20 │   def _load(self) -> ModelSession:       │
                             │ ❱ 21 │   │   session = self._make_session(self. │
                             │   22 │   │   self.model = RetinaFace(session=se │
                             │   23 │   │   self.model.prepare(ctx_id=0, det_t │
                             │   24                                            │
                             │                                                 │
                             │ /usr/src/immich_ml/models/base.py:116 in        │
                             │ _make_session                                   │
                             │                                                 │
                             │   113 │   │   │   case ".armnn":                │
                             │   114 │   │   │   │   session: ModelSession = A │
                             │   115 │   │   │   case ".onnx":                 │
                             │ ❱ 116 │   │   │   │   session = OrtSession(mode │
                             │   117 │   │   │   case ".rknn":                 │
                             │   118 │   │   │   │   session = rknn.RknnSessio │
                             │   119 │   │   │   case _:                       │
                             │                                                 │
                             │ /usr/src/immich_ml/sessions/ort.py:28 in        │
                             │ __init__                                        │
                             │                                                 │
                             │    25 │   │   self.providers = providers if pro │
                             │    26 │   │   self.provider_options = provider_ │
                             │       self._provider_options_default            │
                             │    27 │   │   self.sess_options = sess_options  │
                             │       self._sess_options_default                │
                             │ ❱  28 │   │   self.session = ort.InferenceSessi │
                             │    29 │   │   │   self.model_path.as_posix(),   │
                             │    30 │   │   │   providers=self.providers,     │
                             │    31 │   │   │   provider_options=self.provide │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:41 │
                             │ 9 in __init__                                   │
                             │                                                 │
                             │    416 │   │   disabled_optimizers = kwargs.get │
                             │    417 │   │                                    │
                             │    418 │   │   try:                             │
                             │ ❱  419 │   │   │   self._create_inference_sessi │
                             │        disabled_optimizers)                     │
                             │    420 │   │   except (ValueError, RuntimeError │
                             │    421 │   │   │   if self._enable_fallback:    │
                             │    422 │   │   │   │   try:                     │
                             │                                                 │
                             │ /opt/venv/lib/python3.11/site-packages/onnxrunt │
                             │ ime/capi/onnxruntime_inference_collection.py:48 │
                             │ 3 in _create_inference_session                  │
                             │                                                 │
                             │    480 │   │   │   disabled_optimizers = set(di │
                             │    481 │   │                                    │
                             │    482 │   │   # initialize the C++ InferenceSe │
                             │ ❱  483 │   │   sess.initialize_session(provider │
                             │    484 │   │                                    │
                             │    485 │   │   self._sess = sess                │
                             │    486 │   │   self._sess_options = self._sess. │
                             ╰─────────────────────────────────────────────────╯
                             RuntimeException: [ONNXRuntimeError] : 6 :         
                             RUNTIME_EXCEPTION : Exception during               
                             initialization:                                    
                             /onnxruntime/onnxruntime/core/providers/openvino/ov
                             _interface.cc:85                                   
                             onnxruntime::openvino_ep::OVExeNetwork             
                             onnxruntime::openvino_ep::OVCore::CompileModel(std:
                             :shared_ptr<const ov::Model>&,                     
                             std::__cxx11::string&, ov::AnyMap&,                
                             std::__cxx11::string) [OpenVINO-EP]  Exception     
                             while Loading Network for graph:                   
                             OpenVINOExecutionProvider_OpenVINO-EP-subgraph_3_0E
                             xception from src/inference/src/cpp/core.cpp:109:  
                             Exception from src/inference/src/dev/plugin.cpp:54:
                             Exception from                                     
                             src/plugins/intel_gpu/src/runtime/ocl/ocl_stream.cp
                             p:433:                                             
                             [GPU] clWaitForEvents, error code: -14             

### The OS that Immich Server is running on

FS6706T

### Version of Immich Server

131.3

### Version of Immich Mobile App

131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/Media/Photos:/share/Media/Photos:ro
      - /share/Media/Videos:/share/Media/Videos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
    

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /share/Docker/Immich/model-cache
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/Docker/Immich/Backup
IMMICH_VERSION=release
DB_PASSWORD=xxxxxx
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DATA_LOCATION=/share/Docker/Immich/pgdata
HF_ENDPOINT=https://hf-mirror.com
TZ=Asia/Shanghai
```

### Reproduction steps

1. change model
2. re-processing
3.
...

### Relevant log output

```shell

```
