### ISSUE TITLE
HEIC/HEIF original images not loading in Safari 18.3.1

### ISSUE THREAD

**Issue by hackrush01** [immich-app/immich#17334]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Even when enabling the "Display original photos" option in the settings of a user, only the preview image is shown for ".heic" images in Safari (version 18.3.1) browser on Mac. Confirm that I am seeing the preview image by changing the preview resolution to 720p and quality to 2, so the images are categorically and visually bad.. Also, checked through the "inspect element" that the asset is showing up as 720p image.

I have kept the new "Full-size image generation" option disabled.

JPEG full size images are showing up fine (verified through inspector as well).

Up until a couple of days ago, I was able to view the original heic images in the browser (confirmed through the above same methods).

Could this commit be causing the issue - https://github.com/immich-app/immich/pull/14446??

### The OS that Immich Server is running on

Debian 12 VM managed using portainer

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

1.130.3 (latest version not available yet in playstore)

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/immich/Gallery:/home/Gallery
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich/appdata/library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=
DB_DATABASE_NAME=immich
IMMICH_LOG_LEVEL=debug
```

### Reproduction steps

1. Have heic images in library
2. enable "display original asset"
3. verify that the original asset is not being displayed on Safari 18.3.1 (which should be supported according to - https://caniuse.com/?search=heic)
4. Zooming in also does not load the original image
5. Original asset is correctly displayed in the immich app (even on android).

### Relevant log output

```shell
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~qaxs6fwn] GET /api/assets/53d631ef-1e01-4541-be51-bee076c8e4ce/thumbnail?size=fullsize&c=9MeYu%2FzdtrkO4Wba0UYV1KOsOWs%3D 302 1.98ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~sufw5619] GET /api/people/92d3a56e-47f4-4b8a-8200-4da7d3de5901/thumbnail?updatedAt=2025-04-02T08%3A39%3A43.189438%2B00%3A00 200 2.86ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~2qr2itd5] GET /api/albums?assetId=53d631ef-1e01-4541-be51-bee076c8e4ce 200 4.26ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~vf0o6y1c] GET /api/assets/53d631ef-1e01-4541-be51-bee076c8e4ce 200 6.74ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~iwpffwhj] GET /api/albums?assetId=53d631ef-1e01-4541-be51-bee076c8e4ce 200 3.54ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:01:49 AM   DEBUG [Api:LoggingInterceptor~391gk06m] GET /api/assets/53d631ef-1e01-4541-be51-bee076c8e4ce/thumbnail?size=preview&c=9MeYu%2FzdtrkO4Wba0UYV1KOsOWs%3D 200 2.34ms ::ffff:172.18.0.1
[Nest] 18  - 04/02/2025, 10:02:03 AM   DEBUG [Api:LoggingInterceptor~ak6r7h43] GET /api/server/ping 200 0.14ms ::ffff:127.0.0.1
```
