### ISSUE TITLE
Timeline in web UI not showing

### ISSUE THREAD

**Issue by charlotron** [immich-app/immich#17349]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Timeline in web UI not showing any photos it appears the section does not exists. There is no problem with memories besides the timeline or persons, directories, etc. sections are loading photos without any problem.

No errors on chrome developer console (F12)
No errors on docker logs

Tried with incognito session of chrome to discard caching problems without solving it.

### The OS that Immich Server is running on

Docker in Raspberry pi 5 8Gb with Raspbian 

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.130.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

services:
      
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      TZ: ${TZ}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_LIB_LOCATION}:/usr/src/app/external:ro
      - /etc/localtime:/etc/localtime:ro
      #- ${DOCKER_IMMICH_LOCATION}/start-photo-album-creator.sh:/start-photo-album-creator.sh
      - ${DOCKER_IMMICH_LOCATION}/immich_server_start.sh:/usr/src/app/immich_server_start
      - ${DOCKER_IMMICH_LOCATION}/immich_server_configure_cron.sh:/usr/src/app/immich_server_configure_cron
      - ${DOCKER_IMMICH_LOCATION}/immich_server_fix_orphans.sh:/usr/src/app/immich_server_fix_orphans
      - ${DOCKER_IMMICH_LOCATION}/immich_server_fix_offlines.sh:/usr/src/app/immich_server_fix_offlines
      - ${DOCKER_IMMICH_LOCATION}/immich_server_detect_offline_files.sh:/usr/src/app/immich_server_detect_offline_files
      - ${DOCKER_IMMICH_LOCATION}/immich_server_delete_empty_albums.sh:/usr/src/app/immich_server_delete_empty_albums
    ports:
      - 2283:2283
    entrypoint: /usr/src/app/immich_server_start
    #entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
    #tty: true  # Habilitar la interfaz de terminal
    #stdin_open: true  # Abrir stdin para interactividad
    depends_on:
      - redis
      - database
    deploy:
      restart_policy:
        condition: any
    networks:
      - overlay_network


  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich-server:2283/api
      API_KEY: P8996apd0kaVFLGN6hdyJv5rrUz2yWx4luA48Jme8o
      ROOT_PATH: /usr/src/app/external
      CRON_EXPRESSION: "*/30 * * * *"
      TZ: Europe/Madrid
      LOG_LEVEL: DEBUG
      ALBUM_LEVELS: 2,15
    #entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
    #tty: true  # Habilitar la interfaz de terminal
    #stdin_open: true  # Abrir stdin para interactividad
    networks:
      - overlay_network

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    user: "0"
    environment:
      MACHINE_LEARNING_WORKER_TIMEOUT: 300
      MACHINE_LEARNING_WORKERS: 1
      MACHINE_LEARNING_MODEL_INTRA_OP_THREADS: 1
      MACHINE_LEARNING_MODEL_INTER_OP_THREADS: 1
      MACHINE_LEARNING_REQUEST_THREADS: 1
      IMMICH_LOG_LEVEL: DEBUG
      #MACHINE_LEARNING_PRELOAD__CLIP: nllb-clip-base-siglip__v1
      #MACHINE_LEARNING_PRELOAD__FACIAL_RECOGNITION: buffalo_s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ML_CACHE_LOCATION}:/cache
      - ${DOCKER_IMMICH_LOCATION}/ml_start.sh:/ml_start
    entrypoint: /ml_start
    #tty: true  # Habilitar la interfaz de terminal
    #stdin_open: true  # Abrir stdin para interactividad
    healthcheck:
      test: ["CMD-SHELL", "pidof python || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '1.00'
          #memory: '4G'
    networks:
      - overlay_network

  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      - ${DOCKER_IMMICH_LOCATION}/postgres_start.sh:/postgres_start
    entrypoint: /postgres_start
    #entrypoint: tail -f /dev/null
    #tty: true  # Habilitar la interfaz de terminal
    #stdin_open: true  # Abrir stdin para interactividad
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints: [node.hostname == rpi1]
    networks:
      - overlay_network

  redis:
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    #tty: true  # Habilitar la interfaz de terminal
    #stdin_open: true  # Abrir stdin para interactividad
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: any
    networks:
      - overlay_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_USERNAME}@local.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - overlay_network

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - /home/xarly/common/docker/immich/postgres:/db_dumps
    healthcheck:
      test: ["CMD-SHELL", "pidof go-cron || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - database
    networks:
      - overlay_network

volumes:
  pgadmin-data:


networks:
  overlay_network:
    driver: overlay
```

### Your .env content

```Shell
prefer not to do it, there are sensitive data
```

### Reproduction steps

1. Updated from a previous version, 1.29? (dont remember)
2. Open web UI
3. Timeline disappeared

### Relevant log output

```shell
No errors, refreshed page, these are the logs:

[Nest] 5204  - 04/03/2025, 1:40:26 AM   DEBUG [Api:LoggingInterceptor~ufpw72px] GET /api/server/ping 200 0.35ms ::ffff:127.0.0.1

[Nest] 5204  - 04/03/2025, 1:40:56 AM   DEBUG [Api:LoggingInterceptor~fwmkyj3s] GET /api/server/ping 200 0.19ms ::ffff:127.0.0.1

[Nest] 5204  - 04/03/2025, 1:41:21 AM     LOG [Api:EventRepository] Websocket Disconnect: AteF4vNjcahq2ixAAAAj

[Nest] 5204  - 04/03/2025, 1:41:21 AM   DEBUG [Api:LoggingInterceptor] GET /custom.css 200 10.92ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:21 AM   DEBUG [Api:LoggingInterceptor~11qq3jtv] GET /api/server/features 200 9.51ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:21 AM   DEBUG [Api:LoggingInterceptor~0io0yk4d] GET /api/server/config 200 12.26ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:21 AM   DEBUG [Api:LoggingInterceptor~ibhbumxg] GET /api/users/me 200 4.98ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:21 AM   DEBUG [Api:LoggingInterceptor~vmmwkgsr] GET /api/users/me/preferences 200 3.96ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~u854lyor] GET /api/server/about 200 196.55ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM     LOG [Api:EventRepository] Websocket Connect:    CfIw3caV54CKR-yWAAAl

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~gzrvlgin] GET /api/server/storage 200 10.09ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~etffu3wp] GET /api/memories?for=2025-04-03T01%3A41%3A21.256Z 200 23.35ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~jx8kpqqk] GET /api/server/storage 200 4.46ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~idmddggc] GET /api/users/3a37b9e7-a52a-4ea4-ad87-70768fd35f74/profile-image?updatedAt=2025-03-23T00%3A28%3A29.356Z 304 22.71ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~ve9oyo3q] GET /api/server/version-history 200 1.81ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~b53qcrjz] GET /api/server/about 200 85.57ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~zny38zjl] GET /api/timeline/buckets?isArchived=false&size=MONTH&withPartners=true&withStacked=true 200 92.26ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~reas9a58] GET /api/server/about 200 65.25ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:22 AM   DEBUG [Api:LoggingInterceptor~nl2amhnj] GET /api/albums 200 230.87ms 172.20.0.1

[Nest] 5204  - 04/03/2025, 1:41:26 AM   DEBUG [Api:LoggingInterceptor~urchjmda] GET /api/server/ping 200 0.20ms ::ffff:127.0.0.1
```
