### ISSUE TITLE
[BUG] Media in Timeline are grouped in wrong days

### ISSUE THREAD

**Issue by gitmen74** [immich-app/immich#1736]
### The bug

The timeline contains several photos that have been taken in a different timezone. Some of them are counted as part of the next day, probably caused by a different timezone (where the image has been created and the server) and the offset is not considered while grouping them.

See the following screenshots for reference:
- timeline:
![immagine](https://user-images.githubusercontent.com/125159027/218281699-580a3ec1-7238-4873-80eb-98a6d0b1acfe.png)
- details panel:
![immagine](https://user-images.githubusercontent.com/125159027/218281730-569c8ff5-3376-4d8d-b78e-a929beeb716d.png)
- exif metadata:
![immagine](https://user-images.githubusercontent.com/125159027/218281792-c73bc1dd-b2b7-4e07-9be2-e98a6c65e2a7.png)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.45.0

### Version of Immich Mobile App

v1.45.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<removed>
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=<removed>
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1.Ensure your server is in a different timezone (example: UTC+02)
2.Upload a picture taken in the afternoon in a very different timezone (example: UTC-07)
3.Image is grouped in the following day (timezone is not considered)
```

### Additional information

Google Photos is correctly grouping medias with different timezones
