### ISSUE TITLE
Error in starting IMMICH server in docker

### ISSUE THREAD

**Issue by aGhosh02** [immich-app/immich#17381]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Unable to start immich in docker environment using the official immich docker compose and images.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

NA

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - docker_global
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)"
      - "traefik.http.routers.immich.entrypoints=web,websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=cloudflare"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
      - "traefik.http.services.immich.loadbalancer.server.scheme=http"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: unless-stopped

volumes:
  model-cache:

networks:
  docker_global:
    name: docker_global
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-42a18729-028c-448d-9ab8-b6ccad188135/immich/photos
DB_DATA_LOCATION=/srv/dev-disk-by-uuid-42a18729-028c-448d-9ab8-b6ccad188135/immich/postgres
IMMICH_VERSION=release
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Running immich using docker compose up -d

### Relevant log output

```shell
[Nest] 7  - 04/04/2025, 1:00:49 PM     LOG [Microservices:EventRepository] Initialized websocket server

[Nest] 17  - 04/04/2025, 1:00:49 PM     LOG [Api:EventRepository] Initialized websocket server

/usr/src/app/node_modules/postgres/cjs/src/connection.js:389

      stack: { value: err.stack + query.origin.replace(/.*\n/, '\n'), enumerable: options.debug },

                                               ^

TypeError: Cannot read properties of undefined (reading 'replace')

    at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)

    at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)

    at Socket.error (/usr/src/app/node_modules/postgres/cjs/src/connection.js:376:5)

    at Socket.emit (node:events:518:28)

    at emitErrorNT (node:internal/streams/destroy:170:8)

    at emitErrorCloseNT (node:internal/streams/destroy:129:3)

    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)

Node.js v22.14.0

microservices worker error: TypeError: Cannot read properties of undefined (reading 'replace'), stack: TypeError: Cannot read properties of undefined (reading 'replace')

    at queryError (/usr/src/app/node_modules/postgres/cjs/src/connection.js:389:48)

    at errored (/usr/src/app/node_modules/postgres/cjs/src/connection.js:384:17)

    at Socket.error (/usr/src/app/node_modules/postgres/cjs/src/connection.js:376:5)

    at Socket.emit (node:events:518:28)

    at emitErrorNT (node:internal/streams/destroy:170:8)

    at emitErrorCloseNT (node:internal/streams/destroy:129:3)

    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
```
