### ISSUE TITLE
extension of file and immich dont match

### ISSUE THREAD

**Issue by Mathijs0** [immich-app/immich#17380]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

​**The problem:**
After changing the Storage Template, some files have no thumbnail.

**What I found:**
In the UI under info the location of the files has .jpeg. While the real file has .jpg.
Rest of the URL matches.
Changing the actual file extension from .jpg to .jpeg to fix the problem.
But doing this manual is not fun.
It also isn't consistent so changing all .jpg to .jpeg would just move the problem to the files that are working.

File name immich ui:
![Image](https://github.com/user-attachments/assets/112a9afb-c3fe-4a9f-a2fc-332434b6f71d)

File name in folder:
![Image](https://github.com/user-attachments/assets/18811ead-c33a-4076-ab81-b74ddf93c5c8)

**Pesseble fix:** (Im nowhere near a coder)
If immich can't find a file with the .jpeg extension, try the same url with the .jpg extension, and vica versa.

### The OS that Immich Server is running on

debian

### Version of Immich Server

V1.131.3

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - "./photos:/usr/src/app/upload"
      - "/sf_Media/Fotos/1. Fotos Immich:/usr/src/app/upload/library"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks: 
      mrl:
        ipv4_address: 10.1.1.50

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ./cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks: 
      mrl:
        ipv4_address: 10.1.1.51

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    networks: 
      mrl:
        ipv4_address: 10.1.1.52

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test:  >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: unless-stopped
    networks: 
      mrl:
        ipv4_address: 10.1.1.53

networks:
  mrl:
    external: true
```

### Your .env content
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
# The location where your database files are stored
#DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Amsterdam
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
IMMICH_ENV=production

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich


#######
DB_HOSTNAME=10.1.1.53
DB_PORT=5432

REDIS_HOSTNAME=10.1.1.52
REDIS_PORT=6379

IMMICH_TRUSTED_PROXIES=xxxxxx


```
### Storage template

**old:**
```
{{y}}/{{y}}-{{MM}}-{{dd}} {{HH}}.{{mm}}.{{ss}}
```
**new:**
```
{{#if album}}{{y}}-{{album}}{{else}}{{y}}{{/if}}/{{y}}-{{MM}}-{{dd}} {{HH}}.{{mm}}.{{ss}}
```

![Image](https://github.com/user-attachments/assets/4a80bdc0-ef27-4a63-890e-711d2e55c2f1)

### Reproduction steps

1. Have a working library with all photos and thumbnails working.
2. Change storage template, and migrate.
3. Now of some files the extensions of the files don't match the immich ui/ database.
...

### Relevant log output

```shell

```
