### ISSUE TITLE
Hierarchical tag separator getting ingested incorrectly from sidecar.

### ISSUE THREAD

**Issue by richadams** [immich-app/immich#17388]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have an external library where every asset has a standard XMP sidecar. In the sidecar I have tags for assets which are `/` separated, to indicate hierarchy. For example `Taken By/Rich`. When ingested to Immich, these are getting changed to non-hierarchical tags using `|` separators instead. So I end up with `Taken By|Rich` and no hierarchy.

According to the [initial release of tagging](https://github.com/immich-app/immich/pull/11980), `/` is the correct separator to use (I couldn't find any reference to it in the latest documentation though, so maybe it changed?).

I enabled verbose logging and see that the EXIF data from the sidecar is being correctly identified as `/` by Immich, so I don't think it's a sidecar issue, but rather something internal to Immich is changing it to `|`.

```
  SourceFile: '/external/google/[...].xmp'
  [...]
  Subject: [
    'Google Imported',
    'Taken By/Rich'
  ],
  HierarchicalSubject: [
    'Google Imported',
    'Taken By/Rich'
  ],
  Keywords: [
    'Google Imported',
    'Taken By/Rich'
  ],
```

I found [this part of the code](https://github.com/immich-app/immich/blob/main/server/src/services/metadata.service.ts#L404-L410) which I think might be responsible. Based on the comment it's trying to convert `|` to `/` in tags, presumably to support Lightroom-style hierarchical tags which use the `|` separator and converting them to the Immich `/` separator. However, if there's no `|` in the original string it seems to do the opposite.

If you give it `/` separated, it converts to `|`, and vice versa. I would expect it to always output using the Immich `/` separator instead.

```
# What actually happens.
"Taken By|Rich" => "Taken By/Rich"
"Taken By/Rich" => "Taken By|Rich"

# What I expected to happen.
"Taken By|Rich" => "Taken By/Rich"
"Taken By/Rich" => "Taken By/Rich"
```

One potential fix is to only run the current conversion if a `|` appears in the original string, and skip it otherwise.

I _think_ something like this would fix it, but I've never done typescript before and it makes a a nested ternary which might not be desirable from a code readability perspective. 

```
# Convert | to / to support Lightroom-style separators. Leave alone otherwise.
tag.includes('|')
  ? tag.split('|')
       .map((tag) => tag.replaceAll('/', '|'))
       .join('/')
  : tag
```

Hopefully this is enough information for someone with more knowledge than me to be able to fix it.

### The OS that Immich Server is running on

Ubuntu 22.04.1

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/immich/google:/external/google:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored  
UPLOAD_LOCATION=./library  
# The location where your database files are stored  
DB_DATA_LOCATION=./postgres  
  
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List  
# TZ=Etc/UTC  
  
# The Immich version to use. You can pin this to a specific version like "v1.71.0"  
IMMICH_VERSION=release  
  
# Connection secret for postgres. You should change it to a random password  
DB_PASSWORD=<REDACTED>  
  
# The values below this line do not need to be changed  
###################################################################################  
DB_USERNAME=postgres  
DB_DATABASE_NAME=immich
```

### Reproduction steps

Add an external library with an image or video with this example sidecar.

```
<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 4.4.0-Exiv2">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:lr="http://ns.adobe.com/lightroom/1.0/"
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:video="http://www.video/"
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
   exif:DateTimeOriginal="2019-10-14T20:07:01"
   tiff:DateTime="2019-10-14T20:07:01"
   xmp:CreateDate="2019-10-14T20:07:01"
   xmp:MetadataDate="2019-10-14T20:07:01"
   xmp:ModifyDate="2019-10-14T20:07:01"
   video:DateTimeOriginal="2019-10-14T20:07:01"
   video:DateUTC="2019-10-14T20:07:01"
   video:ModificationDate="2019-10-14T20:07:01"
   photoshop:DateCreated="2019-10-14T20:07:01">
   <lr:hierarchicalSubject>
    <rdf:Bag>
     <rdf:li>Taken By/Rich</rdf:li>
     <rdf:li>Google Imported</rdf:li>
    </rdf:Bag>
   </lr:hierarchicalSubject>
   <dc:subject>
    <rdf:Bag>
     <rdf:li>Taken By/Rich</rdf:li>
     <rdf:li>Google Imported</rdf:li>
    </rdf:Bag>
   </dc:subject>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>
```

After being ingested, look at the tags view or the information for the image, and you'll see it has no hierarchy and has been changed to `Taken By|Rich` instead.

![Image](https://github.com/user-attachments/assets/0ba18d0a-9d27-4358-8de3-fea84bbb0ecd)

If you change to `|` separator in the sidecar, the opposite happens and Immich will convert it to `/` and it will have the proper hierarchy.

### Relevant log output

```shell

```
