### ISSUE TITLE
iOS: Not displaying/loading memories

### ISSUE THREAD

**Issue by Langa87** [immich-app/immich#17441]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

iOS app fails to load/display memories while it is working in the web app.

Log shows this message:

`Cannot get memories`

`Null check operator used on a null value`

Found something about corrupted media files in an issue related to null check, but `'select a.id, a."fileCreatedAt"  from assets a where a."fileCreatedAt" is null;'` returns 0 rows.

No other issues with image display have been observed.

### The OS that Immich Server is running on

DSM 7.2.2-72806 Update 3

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=immich
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
      - /volume1/docker/immich/cache:/cache:rw
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Europe/Berlin
DB_HOSTNAME=immich-db
DB_USERNAME=***
DB_PASSWORD=***
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=***
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:2283
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Open iOS app (iOS 18.4 22E240)
2. Memories not showing
3.
...

### Relevant log output

```shell
#0      AssetResponseDto.fromJson (package:openapi/model/asset_response_dto.dart:292)
#1      AssetResponseDto.listFromJson (package:openapi/model/asset_response_dto.dart:324)
#2      MemoryResponseDto.fromJson (package:openapi/model/memory_response_dto.dart:160)
#3      ApiClient.fromJson (package:openapi/api_client.dart:386)
#4      ApiClient.fromJson.<anonymous closure> (package:openapi/api_client.dart:685)
#5      MappedIterable.elementAt (dart:_internal/iterable.dart:402)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:371)
#7      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:166)
#8      new _List.of (dart:core-patch/array.dart:130)
#9      new List.of (dart:core-patch/array_patch.dart:40)
#10     ListIterable.toList (dart:_internal/iterable.dart:224)
#11     ApiClient.fromJson (package:openapi/api_client.dart:686)
#12     ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#13     MemoriesApi.searchMemories (package:openapi/api/memories_api.dart:331)
<asynchronous suspension>
#14     MemoryService.getMemoryLane (package:immich_mobile/services/memory.service.dart:28)
<asynchronous suspension>
#15     memoryFutureProvider.<anonymous closure> (package:immich_mobile/providers/memory.provider.dart:9)
<asynchronous suspension>
#16     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355)
<asynchronous suspension>
```
