### ISSUE TITLE
[BUG] Changing case of file extension on external libraries results in duplicate entires

### ISSUE THREAD

**Issue by skylatian** [immich-app/immich#17473]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I changed the case of the file extension of some files and now there are two versions appearing in Immich. 

Screenshot from the folders section of immich:
<img width="494" alt="Image" src="https://github.com/user-attachments/assets/58ce99e4-38c4-44e1-9f1a-1fa7eec0f1f1" />

They also appear as separate assets in the timeline, but when the path is clicked on, they lead to the same file.

<img width="264" alt="Image" src="https://github.com/user-attachments/assets/dd169c5b-3428-4f32-9b98-8e0ae8342b8d" />

<img width="278" alt="Image" src="https://github.com/user-attachments/assets/b3f1e47f-846e-45e6-8a0b-61cea41543f6" />

### The OS that Immich Server is running on

Docker on Windows Server

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3.build.201

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "D:/nas/Media:/nas/Media:ro"
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
      
      
  immich-auto-stack:
    container_name: immich-auto-stack
    #image: ghcr.io/tenekev/immich-auto-stack:latest
    build: https://github.com/Majorfi/immich-auto-stack.git#
    restart: unless-stopped 
    environment:

      # This is default. Can be omitted. 
      API_URL: http://immich_server:2283/api # used to be :3001/api but immich changed it

      # https://immich.app/docs/features/command-line-interface#obtain-the-api-key
      API_KEY: [redacted]

      # This is default. Can be omitted. When true, prints output but does not submit any change
      DRY_RUN: False

      # Whether or not to modify photos that are already in stacks. Going over all assets takes a lot more time.
      SKIP_PREVIOUS: True

      # This is default. Can be omitted. Read further for customization.
      # CRITERIA: '[{"key": "originalFileName","split": {"key": ".","index": 0}},{"key": "localDateTime"}]'
      # You can also break this into a multi-line string for better readability
      # CRITERIA: >
      #   [
      #     {
      #       "key": "originalFileName",
      #       "split": {
      #         "key": ".",
      #         "index": 0
      #       }
      #     },
      #     {
      #       "key": "localDateTime"
      #     }
      #   ]
      
       # from https://github.com/tenekev/immich-auto-stack?tab=readme-ov-file#-regex-customization-of-the-criteria

      # This is default. Can be omitted. If you want to promote other parent criteria like "HDR" or "Edit".
      # PARENT_PROMOTE: ""
      
      # This is default. Can be omitted. Consider setting to true if you have a CRITERIA regex that
      # is not intended to match all the photos in your library.
      # SKIP_MATCH_MISS: False

      # Run every hour. Use https://crontab.guru/ to generate new expressions.
      CRON_EXPRESSION: "0 */1 * * *"
      TZ: America/Los_Angeles
      
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
          - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION="D:/immich-library"
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[redacted]

# IMMICH_API_KEY=[redacted] # for immich power tools (commented out so that it makes your log in)
IMMICH_URL = "http://immich-server:2283" # Your immich instace ip address and port (immich power tools)
EXTERNAL_IMMICH_URL = [redacted]
DB_HOST="immich_postgres"
DB_PORT ="5432"
# Optional (immich power tools)
GOOGLE_MAPS_API_KEY=[redacted]
GEMINI_API_KEY=[redacted] # Gemini API Key

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Have an image on an external library with a lowercase extension (eg. `jpg`)
2. Change extension to uppercase (eg `jpg` --> `JPG`)
3. Re-scan external library: file extension still shows lowercase
4. For good measure, attempt workaround detailed in #17186
5. Files now appear duplicated, with a `.jpg` version and a `.JPG` version.

<img width="494" alt="Image" src="https://github.com/user-attachments/assets/58ce99e4-38c4-44e1-9f1a-1fa7eec0f1f1" />

I double-checked, and only one file (the uppercase `.JPG`) exists on disk.

### Relevant log output

```shell

```

### Additional information

External library is read-only.
