### ISSUE TITLE
Wrong date time when scanning videos in External Library

### ISSUE THREAD

**Issue by mumuxijili** [immich-app/immich#17495]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi, I use External Library to sync both photos and videos shot from Nikon Z50II, It turns out that all videos will be add another timezone offset. I dig into the code and find that it maybe the Date Time Original in exif has been wrongly parsed.
Here's part of the eixf tags output
```
  DateTimeOriginal: ExifDateTime {
    year: 2025,
    month: 3,
    day: 30,
    hour: 4,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 20:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
```
log after parsing is: `VERBOSE [Microservices:MetadataService] Date and time is 2025-03-30T04:14:32+08:00 for asset 5b17cdfa-6400-4944-8984-5ec09968fa21: /opt/external/DSC_2740.MOV`
The parsed date time(2025-03-30T04:14:32+08:00) add another 8 hours to the correct date time(2025:03:29 20:14:32). I'm not quite familiar with the Exif spec but I think the DateTimeOriginal string is the date time that already consider the timezone(though the photos I shot with the same camera have a '+08:00' at the end of the DateTimeOriginal string, and it has been parsed correctedly).
Am I missing some configurations?

### The OS that Immich Server is running on

QNAP NAS OS(based on Linux kernal 5.10.60 I believe)

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3'
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.131.3
    environment:
      DB_PASSWORD: xxx
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      TZ: Asia/Shanghai
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - immich/upload:/usr/src/app/upload
      - immich/Photos/SOOC:/opt/external
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.3
    environment:
      DB_PASSWORD: xxx
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      TZ: Asia/Shanghai
    volumes:
      - immich/cache:/cache
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2.14-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich/data:/var/lib/postgresql/data
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: unless-stopped
```

### Your .env content

```Shell
already merged in docker-compose.yml
      DB_PASSWORD: xxx
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
      TZ: Asia/Shanghai
      POSTGRES_PASSWORD: xxx
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
```

### Reproduction steps

1. Copy videos to External Libraries
2. Scan

### Relevant log output

```shell
Full exif from verbose log

[Nest] 6  - 04/05/2025, 2:12:39 AM VERBOSE [Microservices:MetadataService] Exif Tags
[Nest] 6  - 04/05/2025, 2:12:39 AM VERBOSE [Microservices:MetadataService] Object(239) {
  SourceFile: '/opt/external/DSC_2740.MOV',
  errors: [],
  GPSLatitude: 39.91642,
  GPSLongitude: 116.310043,
  GPSLatitudeRef: 'N',
  GPSLongitudeRef: 'E',
  tz: 'UTC+8',
  tzSource: 'TimeZone',
  Duration: 1.4014,
  PreviewDuration: 0,
  SelectionDuration: 0,
  TrackDuration: 1.4014,
  MediaDuration: 1.40133333333333,
  GPSAltitude: 55,
  GPSPosition: '39.91642 116.310043333333',
  FocalLength: 35,
  FileSize: 57626200,
  ExifToolVersion: 13.26,
  FileName: 'DSC_2740.MOV',
  Directory: '/opt/external',
  FileModifyDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 12,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 0,
    rawValue: '2025:03:29 12:14:32Z',
    zoneName: 'UTC',
    inferredZone: false,
    zone: 'UTC'
  },
  FileAccessDate: ExifDateTime {
    year: 2025,
    month: 4,
    day: 5,
    hour: 17,
    minute: 12,
    second: 8,
    millisecond: undefined,
    tzoffsetMinutes: 0,
    rawValue: '2025:04:05 17:12:08Z',
    zoneName: 'UTC',
    inferredZone: false,
    zone: 'UTC'
  },
  FileCreateDate: ExifDateTime {
    year: 2025,
    month: 4,
    day: 5,
    hour: 17,
    minute: 3,
    second: 44,
    millisecond: undefined,
    tzoffsetMinutes: 0,
    rawValue: '2025:04:05 17:03:44Z',
    zoneName: 'UTC',
    inferredZone: false,
    zone: 'UTC'
  },
  FilePermissions: '-rw-rw-rw-',
  FileType: 'MOV',
  FileTypeExtension: 'mov',
  MIMEType: 'video/quicktime',
  MajorBrand: 'Apple QuickTime (.MOV/QT)',
  MinorVersion: '2016.9.0',
  CompatibleBrands: [ 'qt  ', 'niko' ],
  MovieHeaderVersion: 0,
  ModifyDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 20,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 12:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  TimeScale: 60000,
  PreferredRate: 1,
  PreferredVolume: '100.00%',
  PreviewTime: '0 s',
  PosterTime: '0 s',
  SelectionTime: '0 s',
  CurrentTime: '0 s',
  NextTrackID: 3,
  TrackHeaderVersion: 0,
  TrackCreateDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 20,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 12:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  TrackModifyDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 20,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 12:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  TrackID: 1,
  TrackLayer: 0,
  TrackVolume: '0.00%',
  ImageWidth: 3840,
  ImageHeight: 2160,
  GraphicsMode: 'srcCopy',
  OpColor: '0 0 0',
  CompressorID: 'hvc1',
  SourceImageWidth: 3840,
  SourceImageHeight: 2160,
  XResolution: 72,
  YResolution: 72,
  BitDepth: 24,
  ColorProfiles: 'nclc',
  ColorPrimaries: 'BT.709',
  TransferCharacteristics: 'BT.709',
  MatrixCoefficients: 'BT.709',
  VideoFrameRate: 59.94,
  MatrixStructure: '1 0 0 0 1 0 0 0 1',
  MediaHeaderVersion: 0,
  MediaCreateDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 20,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 12:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  MediaModifyDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 20,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 12:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  MediaTimeScale: 48000,
  Balance: 0,
  HandlerClass: 'Data Handler',
  HandlerType: 'Alias Data',
  AudioFormat: 'lpcm',
  Make: 'NIKON CORPORATION',
  Model: 'NIKON Z50_2',
  Software: 'NIKON Z50_2 Ver.01.00',
  CreateDate: ExifDateTime {
    year: 2025,
    month: 3,
    day: 30,
    hour: 4,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 20:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  DateTimeOriginal: ExifDateTime {
    year: 2025,
    month: 3,
    day: 30,
    hour: 4,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 20:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  FrameCount: 84,
  FrameRate: 59.94,
  FrameWidth: 3840,
  FrameHeight: 2160,
  AudioChannels: 2,
  AudioBitsPerSample: 24,
  AudioSampleRate: 48000,
  NikonDateTime: ExifDateTime {
    year: 2025,
    month: 3,
    day: 30,
    hour: 4,
    minute: 14,
    second: 32,
    millisecond: undefined,
    tzoffsetMinutes: 480,
    rawValue: '2025:03:29 20:14:32',
    zoneName: 'UTC+8',
    inferredZone: true,
    zone: 'UTC+8'
  },
  ElectronicVR: 'Off',
  ExposureTime: '1/800',
  FNumber: 1.7,
  ExposureProgram: 'Shutter speed priority AE',
  ExposureCompensation: 0,
  MeteringMode: 'Multi-segment',
  SerialNumber: 8000688,
  LensInfo: '35mm f/1.7',
  LensMake: '',
  LensModel: 'Viltrox AF 35/1.7 Z',
  LensSerialNumber: '0         ',
  MakerNoteVersion: 2.11,
  WhiteBalance: 'NATURAL AUTO',
  FocusMode: 'AF-F  ',
  CropHiSpeed: '1.5x Movie Crop (5600x3728 cropped to 3872x2192 at pixel 864,768)',
  VRInfoVersion: '0200',
  VibrationReduction: 'Off',
  VRMode: 'Normal',
  VRType: 'Unknown (0)',
  'ActiveD-Lighting': 'Off',
  PictureControlVersion: '0310',
  PictureControlName: 'Nature_Links',
  PictureControlBase: 'Flexible Color',
  PictureControlAdjust: 'Quick Adjust',
  PictureControlQuickAdjust: 'n/a',
  Sharpness: 2,
  MidRangeSharpness: 1,
  Clarity: 0.5,
  Contrast: 'n/a',
  Brightness: 'n/a',
  Saturation: 'n/a',
  Hue: 'n/a',
  FilterEffect: 'n/a',
  ToningEffect: 'n/a',
  ToningSaturation: 'n/a',
  PictureControlData: BinaryField {
    bytes: 108,
    rawValue: '(Binary data 108 bytes, use -b option to extract)'
  },
  TimeZone: '+08:00',
  DaylightSavings: 'No',
  DateDisplayFormat: 'Y/M/D',
  ISO: 12800,
  ISOExpansion: 'Off',
  ISO2: 12800,
  ISOExpansion2: 'Off',
  VignetteControl: 'Normal',
  WhiteBalanceFineTune: '0 0',
  LensType: 'AF',
  Lens: '35mm f/1.7',
  FlashMode: 'Did Not Fire',
  LensDataVersion: '0802',
  LensID: 'Unknown (2826)',
  LensFirmwareVersion: '0.15.0',
  MaxAperture: 1.7,
  FocusDistance: '7.43 m',
  LensPositionAbsolute: 23,
  LensMountType: 'Z-mount',
  ShutterCount: 2671,
  VariProgram: '               ',
  HighISONoiseReduction: 'Normal',
  AFInfo2Version: '0402',
  AFDetectionMethod: 'Hybrid',
  AFAreaMode: 'Auto',
  AFCoordinatesAvailable: 'No',
  FocusResult: 'Out of Focus',
  GPSVersionID: '2.3.0.0',
  GPSAltitudeRef: 'Above Sea Level',
  GPSTimeStamp: ExifTime {
    hour: 12,
    minute: 13,
    second: 10,
    millisecond: 50,
    rawValue: '12:13:10.05',
    inferredZone: true,
    zone: 'UTC'
  },
  GPSSatellites: '00',
  GPSMapDatum: 'WGS-84',
  GPSDateStamp: ExifDate { year: 2025, month: 3, day: 29, rawValue: '2025:03:29' },
  ThumbnailImage: BinaryField {
    bytes: 8369,
    rawValue: '(Binary data 8369 bytes, use -b option to extract)'
  },
  PreviewImage: BinaryField {
    bytes: 2138538,
    rawValue: '(Binary data 2138538 bytes, use -b option to extract)'
  },
  PreviewImage1: BinaryField {
    bytes: 49339,
    rawValue: '(Binary data 49339 bytes, use -b option to extract)'
  },
  PreviewImage2: BinaryField {
    bytes: 545563,
    rawValue: '(Binary data 545563 bytes, use -b option to extract)'
  },
  MediaDataSize: 54742608,
  MediaDataOffset: 2883592,
  Aperture: 1.7,
  ImageSize: '3840x2160',
  Megapixels: 8.3,
  ShutterSpeed: '1/800',
  GPSDateTime: ExifDateTime {
    year: 2025,
    month: 3,
    day: 29,
    hour: 12,
    minute: 13,
    second: 10,
    millisecond: 50,
    tzoffsetMinutes: 0,
    rawValue: '2025:03:29 12:13:10.05Z',
    zoneName: 'UTC',
    inferredZone: false,
    zone: 'UTC'
  },
  AutoFocus: 'On',
  ContrastDetectAF: 'Off',
  LensSpec: '35mm f/1.7 AF',
  AvgBitrate: '313 Mbps',
  Rotation: 0,
  FocalLength35efl: '35.0 mm',
  LightValue: 4.2,
  warnings: []
}
```
