### ISSUE TITLE
Editing an asset removes it's location when reverse geocoding is disabled

### ISSUE THREAD

**Issue by jack66128** [immich-app/immich#17511]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I edit an asset in any way (add/remove tag, change location, description, date, etc..) the location is removed from the asset. (The lat and lng values are set to null in the database.)

I first noticed this when adding tags in bulk on version v1.130.0. All assets tagged had their location stripped. I downgraded to v1.129.0 and things worked fine. I've since upgraded to the latest version and the issue is still here.

While investigating, I found that enabling reverse geocoding solves the issue. However, I usually keep reverse geocoding disabled because it's not very accurate in my area.

When an asset is first uploaded, its location is set just fine. Though, it can't then be edited without removing its location data.

### The OS that Immich Server is running on

Docker (on Ubuntu 24.04.1 LTS)

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3-build.193

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - proxy
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
    volumes:
      - ./model_cache:/cache
    networks:
      - proxy
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    volumes:
      - ./redisdata:/data
    networks:
      - proxy
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - proxy
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=./data
DB_DATA_LOCATION=./pgdata

TZ=Pacific/Auckland
IMMICH_VERSION=release

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_PASSWORD=password
```

### Reproduction steps

1. Disable reverse geocoding.
2. Edit an asset.

### Relevant log output

```shell

```
