### ISSUE TITLE
After the update, there are many error logs.

### ISSUE THREAD

**Issue by VvLin-61** [immich-app/immich#17514]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After the update, there are many log errors that cannot be consistently reproduced. The web interface sometimes directly displays error codes.

### The OS that Immich Server is running on

unraid 7.0.1

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/imch_import:/mnt/user/imch_import
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #file: hwaccel.ml.yml
    #service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/imch_photos
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/user/appdata/immich/db

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.My update history is as follows: On April 9, 2025, I installed version 1.131.3. On March 26, 2025, I installed version 1.130.1. On March 23, 2025, I installed version 1.129.0. 

2.After updating to v1.131.3, I noticed that the web interface sometimes keeps loading indefinitely. I checked the logs and found many errors, which I have attached below. 
3.It appears that many photos were deleted, but I didn't perform any actions. Sometimes, other errors also occur, and I will attach the logs again if they appear.

### Relevant log output

```shell
[Nest] 17  - 04/10/2025, 9:25:55 AM   ERROR [Api:GlobalExceptionFilter~l9nv3cui] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:25:56 AM   ERROR [Api:LoggingRepository~fob8ugxn] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:25:56 AM   ERROR [Api:GlobalExceptionFilter~fob8ugxn] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:25:57 AM   ERROR [Api:LoggingRepository~x614rz6o] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:25:57 AM   ERROR [Api:GlobalExceptionFilter~x614rz6o] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:01 AM   ERROR [Api:LoggingRepository~qvofmny7] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:01 AM   ERROR [Api:GlobalExceptionFilter~qvofmny7] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:01 AM   ERROR [Api:LoggingRepository~12k2w7v5] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:01 AM   ERROR [Api:GlobalExceptionFilter~12k2w7v5] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:08 AM   ERROR [Api:LoggingRepository~601sbxsh] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:08 AM   ERROR [Api:GlobalExceptionFilter~601sbxsh] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:09 AM   ERROR [Api:LoggingRepository~b4iwlu08] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:09 AM   ERROR [Api:GlobalExceptionFilter~b4iwlu08] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:11 AM   ERROR [Api:LoggingRepository~qvd3ngxt] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:11 AM   ERROR [Api:GlobalExceptionFilter~qvd3ngxt] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:15 AM   ERROR [Api:LoggingRepository~enfqt6cw] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:15 AM   ERROR [Api:GlobalExceptionFilter~enfqt6cw] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:17 AM   ERROR [Api:LoggingRepository~hqtl8eic] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:17 AM   ERROR [Api:GlobalExceptionFilter~hqtl8eic] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:18 AM   ERROR [Api:LoggingRepository~aluszhhq] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:18 AM   ERROR [Api:GlobalExceptionFilter~aluszhhq] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:20 AM   ERROR [Api:LoggingRepository~jirwj3q9] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:20 AM   ERROR [Api:GlobalExceptionFilter~jirwj3q9] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:21 AM   ERROR [Api:LoggingRepository~4q8poifq] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:21 AM   ERROR [Api:GlobalExceptionFilter~4q8poifq] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:22 AM   ERROR [Api:LoggingRepository~tl8nr3m6] Unable to send file: Error
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
[Nest] 17  - 04/10/2025, 9:26:22 AM   ERROR [Api:GlobalExceptionFilter~tl8nr3m6] Unknown error: Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
Error: ENOENT: no such file or directory, access 'upload/profile/8fb2c8d7-db5d-4e55-a668-2ab64c7651b1/7a288158-d5c6-4662-8b9d-6f25afb9340e.jpg'
    at async access (node:internal/fs/promises:605:10)
    at async sendFile (/usr/src/app/dist/utils/file.js:53:9)
    at async UserController.getProfileImage (/usr/src/app/dist/controllers/user.controller.js:72:9)
```
