### ISSUE TITLE
Conditional logic in storage template breaks directory structure unexpectedly

### ISSUE THREAD

**Issue by Novapixel1010** [immich-app/immich#17543]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

# Bug
Using a storage template like this:

`{{#if album}}{{album}}/{{else}}Other{{/if}}/{{y}}/{{MM}}/{{filename}}`

Results in unexpected paths:

  With album: `/AlbumName/y/MM/filename.jpg`

  Without album: `/y/Other/MM/filename.jpg`

Expected:

  With album: `AlbumName/filename.jpg`

  Without album: `Other/2025/04/filename.jpg`

It appears that anything after {{/if}} is inserted in both cases, even though it should be evaluated separately based on the condition.

### The OS that Immich Server is running on

portainer v2.21.1

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - "${IMMICH_HOST}:2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/storage/admin/mike/photos/immich
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=v1.131.3
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_HOST=0.0.0.0
```

### Reproduction steps

# Workaround

Rewriting the template like this fixes it:

`{{#if album}}{{album}}/{{filename}}{{else}}Other/{{y}}/{{MM}}/{{filename}}{{/if}}`

But this defeats the purpose of reusing common path segments outside the conditional, especially if only the first part (album/Other) varies.

### Steps to Reproduce

 1. Go to Admin Panel > External Library Templates

 2. Set storage template:

`{{#if album}}{{album}}/{{else}}Other{{/if}}/{{y}}/{{MM}}/{{filename}}`

3. Import photos with and without albums

4. Observe the path structure
...

### Relevant log output

```shell
[Nest] 7  - 04/11/2025, 5:22:54 PM     LOG [Microservices:StorageTemplateService] Starting storage template migration

[Nest] 7  - 04/11/2025, 5:24:16 PM     LOG [Microservices:StorageTemplateService] Finished storage template migration

[Nest] 17  - 04/11/2025, 5:39:00 PM     LOG [Api:EventRepository] Websocket Connect:    L_vS5Rw3ZJjuNdCTAAZo

[Nest] 17  - 04/11/2025, 5:39:40 PM     LOG [Api:EventRepository] Websocket Disconnect: L_vS5Rw3ZJjuNdCTAAZo
```

### Additional information

I can provide pictures if need?
