### ISSUE TITLE
GET /api/assets and /api return 404, while other authenticated routes work (v1.131.3, Portainer Stack, No Reverse Proxy)

### ISSUE THREAD

**Issue by franciscorochacompt** [immich-app/immich#17565]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Subject: GET /api/assets and /api return 404, while other authenticated routes work (v1.131.3, Portainer Stack, No Reverse Proxy)

Version:
Immich v1.131.3

Bug Description:
I am encountering a consistent 404 Not Found error when trying to access the GET /api/assets endpoint and the API documentation root (/api or /api/). This occurs despite other API endpoints, including authenticated ones like GET /api/albums and unauthenticated ones like GET /api/server/version, working correctly on the same instance. I am not using any reverse proxy; requests are going directly to the immich-server service as defined in the Portainer stack.

Logs:
The immich-server startup logs (from docker logs immich_server or viewed via Portainer) show that various routes are mapped by the Api:RouterExplorer. Critically, there is no entry showing Mapped {/api/assets, GET} route. However, other related asset routes like PUT /api/assets, DELETE /api/assets, GET /api/assets/:id, and POST /api/assets are listed as mapped. Routes for /api/albums and /api/server/version are also correctly listed.

The logs also show the server listening internally within the container on http://[::1]:2283. Despite this specific internal listening address, requests to working endpoints like /api/server/version and /api/albums function correctly when accessed via the host's mapped port (e.g., http://<host_ip>:2283).

Environment:

    Immich Version: v1.131.3

    Deployment Method: Portainer Stack

    Reverse Proxy: None

    Operating System: Debian 12

    Docker Version:
 Client: Docker Engine - Community
 Version:           28.0.1
 API version:       1.48
 Go version:        go1.23.6
 Git commit:        068a01e
 Built:             Wed Feb 26 10:41:16 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.0.1
  API version:      1.48 (minimum version 1.24)
  Go version:       go1.23.6
  Git commit:       bbd0a17
  Built:            Wed Feb 26 10:41:16 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.25
  GitCommit:        bcc810d6b9066471b0b6fa75f557a15a1cbf31bb
 runc:
  Version:          1.2.4
  GitCommit:        v1.2.4-0-g6c52b3f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Portainer Stack YAML: Attach
      

### The OS that Immich Server is running on

docker image

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
#    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
#    env_file:
#      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /root/docker/immich/model-cache:/cache
#    env_file:
#      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/sda1/XXX/XXXXXX/XXXXXXX
DB_DATA_LOCATION=/root/docker/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=XXXXX
DB_USERNAME=XXXXX
DB_DATABASE_NAME=XXXXX
```

### Reproduction steps

    Deploy Immich v1.131.3 using a Portainer stack (YAML provided below).

    Generate a valid API Key via the web UI.

    Attempt to list assets using curl (replace YOUR_API_KEY and YOUR_IMMICH_URL - likely http://<host_ip>:2283 based on standard config):

          
    curl -X GET \
         -H "Accept: application/json" \
         -H "x-api-key: YOUR_API_KEY" \
         "YOUR_IMMICH_URL/api/assets"

Attempt to access the API documentation root using curl or a browser:

      
curl "YOUR_IMMICH_URL/api"
# or
curl "YOUR_IMMICH_URL/api/"

(For confirmation) Successfully retrieve albums using the same API key:
      
curl -X GET \
     -H "Accept: application/json" \
     -H "x-api-key: YOUR_API_KEY" \
     "YOUR_IMMICH_URL/api/albums"

(For confirmation) Successfully retrieve server version:

      
curl "YOUR_IMMICH_URL/api/server/version"

### Relevant log output

```shell

```

### Additional information

Expected Behavior:

    The GET /api/assets request should return a JSON array of assets.

    The GET /api or GET /api/ request should return the HTML content of the Swagger UI documentation page.

Actual Behavior:

    The GET /api/assets request returns a 404 Not Found error.

    The GET /api and GET /api/ requests return a 404 Not Found error.

    Requests to GET /api/albums (with the same API key) and GET /api/server/version succeed.

Additional Context:
Restarting the immich-server service/container via Portainer does not resolve the issue. The successful operation of other authenticated and unauthenticated API routes points strongly towards an issue within the immich-server process itself regarding the registration or serving of the GET /api/assets and /api routes for this specific version or configuration.
