### ISSUE TITLE
[BUG] Uploading photos through album public link does not show in album

### ISSUE THREAD

**Issue by jbalcao** [immich-app/immich#1757]
### The bug

I tried letting others upload photos through the album public link. The uploads were successful and can be viewed under the timeline of the user who created the link but the uploaded photos does not show up in the  public album. 

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.47.2

### Version of Immich Mobile App

v1.47

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - /mnt/sda/srv/immich/upload:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Singapore
      - IMMICH_MACHINE_LEARNING_URL=false
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /mnt/sda/srv/immich/upload:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - IMMICH_MACHINE_LEARNING_URL=false
    depends_on:
      - redis
      - database
    restart: always

#  immich-machine-learning:
#    image: altran1502/immich-machine-learning:release
#    container_name: immich_machinelearning
#    entrypoint: ["/bin/sh", "./entrypoint.sh"]
#    volumes:
#      - /mnt/sda/srv/immich/upload:/usr/src/app/upload
    #env_file:
   #   - .env
  #  environment:
 #     - NODE_ENV=production
 #   depends_on:
#      - database
#    restart: always

  immich-web:
    image: altran1502/immich-web:release
    container_name: immich_web
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:7
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:15
    env_file:
      - .env
    environment:
    #  POSTGRES_PASSWORD: ${DB_PASSWORD}
    #  POSTGRES_USER: ${DB_USERNAME}
    #  POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /srv/immich/pgdata:/var/lib/postgresql/data
    restart: always


  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release

    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=
DB_PASSWORD=
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/srv/immich/upload
JWT_SECRET=
ENABLE_MAPBOX=false
```

### Reproduction steps

```bash
1. Create album
2. Create link (public sharing)
3. Allow public upload
4. Let others upload photos using the link
5. Upload success but the photos won't show in the shared album
...
```
