### ISSUE TITLE
Machine learning Assertion error

### ISSUE THREAD

**Issue by Cdfghglz** [immich-app/immich#17584]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Smart search does not work:

![Image](https://github.com/user-attachments/assets/b26a4c34-af36-42ae-a92c-3152813c4918)

### The OS that Immich Server is running on

4.9.337-tegra

### Version of Immich Server

1.131.3

### Version of Immich Mobile App

1.131.3 build.193

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

version: '3'
#name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. docker-compose up
2. search for any string in the GUI

### Relevant log output

```shell
[04/14/25 08:02:10] INFO     Starting gunicorn 23.0.0                           
[04/14/25 08:02:10] INFO     Listening at: http://[::]:3003 (8)                 
[04/14/25 08:02:10] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[04/14/25 08:02:10] INFO     Booting worker with pid: 9                         
[04/14/25 08:02:17] INFO     Started server process [9]                         
[04/14/25 08:02:17] INFO     Waiting for application startup.                   
[04/14/25 08:02:17] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/14/25 08:02:17] INFO     Initialized request thread pool with 4 threads.    
[04/14/25 08:02:17] INFO     Application startup complete.                      
[04/14/25 08:04:41] INFO     Loading visual model 'ViT-B-32__openai' to memory  
[04/14/25 08:04:41] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         
/opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[04/14/25 08:04:45] ERROR    Worker (pid:9) was sent code 134!                  
[04/14/25 08:04:45] INFO     Booting worker with pid: 58                        
[04/14/25 08:04:52] INFO     Started server process [58]                        
[04/14/25 08:04:52] INFO     Waiting for application startup.                   
[04/14/25 08:04:52] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[04/14/25 08:04:52] INFO     Initialized request thread pool with 4 threads.    
[04/14/25 08:04:52] INFO     Application startup complete.                      
[04/14/25 08:04:52] INFO     Loading detection model 'buffalo_l' to memory      
[04/14/25 08:04:52] INFO     Setting execution providers to                     
                             ['CPUExecutionProvider'], in descending order of   
                             preference                                         
/opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
[04/14/25 08:04:53] ERROR    Worker (pid:58) was sent code 134!
```
