### ISSUE TITLE
microservices worker error: QueryFailedError: deadlock detected, stack: QueryFailedError: deadlock detected

### ISSUE THREAD

**Issue by mengjianjia** [immich-app/immich#17641]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

    severity_local: 'ERROR',
    severity: 'ERROR',
    code: '42703',
    position: '107',
    file: 'parse_relation.c',
    line: '3647',
    routine: 'errorMissingColumn'
  },
  sql: 'select "person".* from "person" left join "asset_faces" on "asset_faces"."personId" = "person"."id" where "asset_faces"."deletedAt" is null group by "person"."id" having count("asset_faces"."assetId") = $1',
  params: [ 0 ]
}
[Nest] 8  - 04/16/2025, 4:30:58 AM   ERROR [Microservices:{}] Unable to run job handler (backgroundTask/person-cleanup): PostgresError: column asset_faces.deletedAt does not exist
PostgresError: column asset_faces.deletedAt does not exist
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:788:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:474:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddIsFavoritePerson1734879118272.up (/usr/src/app/dist/migrations/1734879118272-AddIsFavoritePerson.js:7:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:192:9)
    at async /usr/src/app/dist/services/database.service.js:93:17
    at async /usr/src/app/dist/repositories/database.repository.js:231:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20) {
  query: 'ALTER TABLE "person" ADD "isFavorite" boolean NOT NULL DEFAULT false',
  parameters: undefined,
  driverError: error: deadlock detected
      at /usr/src/app/node_modules/pg/lib/client.js:545:17
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
      at async AddIsFavoritePerson1734879118272.up (/usr/src/app/dist/migrations/1734879118272-AddIsFavoritePerson.js:7:9)
      at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
      at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
      at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:192:9)
      at async /usr/src/app/dist/services/database.service.js:93:17
      at async /usr/src/app/dist/repositories/database.repository.js:231:27
      at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20 {
    length: 317,
    severity: 'ERROR',
    code: '40P01',
    detail: 'Process 639 waits for AccessExclusiveLock on relation 16901 of database 16384; blocked by process 637.\n' +
      'Process 637 waits for AccessShareLock on relation 16913 of database 16384; blocked by process 639.',
    hint: 'See server log for query details.',
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'deadlock.c',
    line: '1147',
    routine: 'DeadLockReport'
  },
  length: 317,
  severity: 'ERROR',
  code: '40P01',
  detail: 'Process 639 waits for AccessExclusiveLock on relation 16901 of database 16384; blocked by process 637.\n' +
    'Process 637 waits for AccessShareLock on relation 16913 of database 16384; blocked by process 639.',
  hint: 'See server log for query details.',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'deadlock.c',
  line: '1147',
  routine: 'DeadLockReport'
}
microservices worker error: QueryFailedError: deadlock detected, stack: QueryFailedError: deadlock detected
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AddIsFavoritePerson1734879118272.up (/usr/src/app/dist/migrations/1734879118272-AddIsFavoritePerson.js:7:9)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
    at async DatabaseRepository.runMigrations (/usr/src/app/dist/repositories/database.repository.js:192:9)
    at async /usr/src/app/dist/services/database.service.js:93:17
    at async /usr/src/app/dist/repositories/database.repository.js:231:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:413:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
microservices worker exited with code 1
Killing api process
Initializing Immich v1.131.3
Detected CPU Cores: 4
Starting api worker
Starting microservices worker

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

1.112.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${CACHE}:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume2/docker/immich/photos
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
CACHE=/volume2/docker/immich/cache
DB_PATH=/volume2/docker/immich/db
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
