### ISSUE TITLE
Email templates "Invite Album Template" and "Update Album Template" don't work

### ISSUE THREAD

**Issue by veilside03** [immich-app/immich#17702]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

"Invite Album Template" and "Update Album Template" don't work at all, or not triggered by the app. However the "Welcome email template" works fine, so the invited person gets the invitation email.

### The OS that Immich Server is running on

Kicksecure 17.2.8.5

### Version of Immich Server

1.131.3

### Version of Immich Mobile App

1.131.3 build.201

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:

      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUPS_LOCATION}:/usr/src/app/upload/backups
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    environment:
      - IMMICH_WEB_URL=https://my.url.com
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      - scoobydoo

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    networks:
      - scoobydoo

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - scoobydoo

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      - scoobydoo

volumes:
  model-cache:

networks:
  scoobydoo:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/upload
ENCODED_VIDEO_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/encoded-video
THUMBS_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/thumbs
PROFILE_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/profile
BACKUPS_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/backups
LIBRARY_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/library/library
DB_DATA_LOCATION=/mnt/4b889afd-49d2-460a-8283-b98a306f8aea/docker-stacks/immich/postgres
IMMICH_VERSION=release
DB_PASSWORD=dbpassword
DB_USERNAME=dbusername
DB_DATABASE_NAME=immich
MAIL_ENABLED=true
MAIL_HOST=smtp.mailersend.net
MAIL_PORT=587
MAIL_USER=email@mydomain.com
MAIL_PASSWORD=mypassword
MAIL_FROM_NAME=Immich Photos
MAIL_FROM_ADDRESS=email@mydomain.com
MAIL_USE_TLS=true
```

### Reproduction steps

1. Test SMTP settings: Welcome email sent out to "user". "user" got the email, SMTP is ok. 
2. Navigate to "Administration/Settings/Notification Settings/Email Templates"
3. Create an "Invite Album Template" and/or an "Update Album Template"
4. Share an album with "user" (for invite album template) or add a photo to a shared album where "user" is already a member (update album template).
5. Check the emails of "user". No emails are received from the Immich server.

### Relevant log output

```shell

```
