### ISSUE TITLE
CF Tunnel: Android app won't upload "Multipart: Unexpected end of form"

### ISSUE THREAD

**Issue by ggrensteiner** [immich-app/immich#17729]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When attempting to upload backups to immich from android app it fails instantly with 

`[Nest] 17  - 04/20/2025, 8:10:04 AM   DEBUG [Api:GlobalExceptionFilter~b5sejo5z] HttpException(400): {"message":"Multipart: Unexpected end of form","error":"Bad Request","statusCode":400}`

Uploads via the web interface work without issue.

Running under cloudflare proxy (fails with proxy off too) and cloudflared tunnel (fails direct too)

### The OS that Immich Server is running on

Ubuntu 24 - docker

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

v1.131.3 build.193

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: '3.3'
name: immich
services:
  immich-server:
    container_name: immich_server
    runtime: nvidia
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - /meh:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    expose:
      - '2283'
    depends_on:
      - redis
      - database
    restart: always
    environment:
      - TIMEZONE=America/Denver
      - TZ=America/Denver
      - NVIDIA_VISIBLE_DEVICES=ALL
      - NVIDIA_DRIVER_CAPABILITIES=ALL 
      - IMMICH_LOG_LEVEL=debug
    healthcheck:
      disable: false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pix.rule=Host(`immich.example.com`)"
      - "traefik.http.routers.pix.tls=true"
    networks:
     - traefik


volumes:
  model-cache:


networks:
  traefik:
    external: true
```

### Your .env content

```Shell
Stanard
```

### Reproduction steps

1.Login with android app
2. Select a folder to backup
3. Touch backup

### Relevant log output

```shell
[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:LoggingInterceptor~p50eebkx] GET /api/server/storage 200 0.28ms 172.18.0.11

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:LoggingInterceptor~etcer7rp] GET /api/assets/device/ac22669ef1a8b0462779f1efb54d166a2638f088f72f038dadf0534262ee0949 200 9.10ms 172.18.0.11

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:LoggingInterceptor~aesxho1k] POST /api/assets 201 0.67ms 172.18.0.11

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:GlobalExceptionFilter~aesxho1k] HttpException(400): {"message":"Multipart: Unexpected end of form","error":"Bad Request","statusCode":400}

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:LoggingInterceptor~j916jvd8] POST /api/assets 201 0.66ms 172.18.0.11

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:GlobalExceptionFilter~j916jvd8] HttpException(400): {"message":"Multipart: Unexpected end of form","error":"Bad Request","statusCode":400}

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:LoggingInterceptor~4wgd9m2o] POST /api/assets 201 0.61ms 172.18.0.11

[Nest] 17  - 04/20/2025, 8:18:21 AM   DEBUG [Api:GlobalExceptionFilter~4wgd9m2o] HttpException(400): {"message":"Multipart: Unexpected end of form","error":"Bad Request","statusCode":400}
```
