### ISSUE TITLE
Immich server container crashing with error node:events:496

### ISSUE THREAD

**Issue by bruvv** [immich-app/immich#17723]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I couldn't find these errors anywhere but as of latly I just keep getting that my container is crashing randomly. Not that I am doing anything. Android and iOS are uploading in the background but that is it.

### The OS that Immich Server is running on

Docker - Synology DS918+

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

latest

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    network_mode: cloudflared_cloudflaretunnel
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/homes/niels/Photos:/extralib:rw
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      # - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    network_mode: cloudflared_cloudflaretunnel
    healthcheck:
      disable: false

  # redis:
  #   container_name: immich_redis
  #   image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
  #   network_mode: cloudflared_cloudflaretunnel
  #   healthcheck:
  #     test: redis-cli ping || exit 1
  #   restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    network_mode: cloudflared_cloudflaretunnel
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
# UPLOAD_LOCATION=./library
UPLOAD_LOCATION=/volume1/immich/
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Amsterdam
PUID=1030
PGID=100

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOSTNAME=immich_postgres
REDIS_HOSTNAME=10.92.69.2
```

### Reproduction steps

I do not know

### Relevant log output

```shell
| Tijdstip        | Logregel                                                                 |
|----------------|--------------------------------------------------------------------------|
| 19-04-2025 23:23 | api worker exited with code 1                                           |
| 19-04-2025 23:23 | Node.js v22.14.0                                                        |
| 19-04-2025 23:23 | }                                                                       |
| 19-04-2025 23:23 | storageErrors: []                                                       |
| 19-04-2025 23:23 | at process.processTicksAndRejections (node:internal/process/task_queues:90:21) { |
| 19-04-2025 23:23 | at emitErrorCloseNT (node:internal/streams/destroy:129:3)              |
| 19-04-2025 23:23 | at emitErrorNT (node:internal/streams/destroy:170:8)                   |
| 19-04-2025 23:23 | Emitted 'error' event on Multipart instance at:                        |
| 19-04-2025 23:23 | at process.processTicksAndRejections (node:internal/process/task_queues:90:21) |
| 19-04-2025 23:23 | at endReadableNT (node:internal/streams/readable:1698:12)              |
| 19-04-2025 23:23 | at IncomingMessage.emit (node:events:518:28)                           |
| 19-04-2025 23:23 | at Object.onceWrapper (node:events:632:28)                             |
| 19-04-2025 23:23 | at IncomingMessage.onend (node:internal/streams/readable:948:10)       |
| 19-04-2025 23:23 | at Writable.end (node:internal/streams/writable:845:5)                 |
| 19-04-2025 23:23 | at finishMaybe (node:internal/streams/writable:930:5)                  |
| 19-04-2025 23:23 | at prefinish (node:internal/streams/writable:916:14)                   |
| 19-04-2025 23:23 | at Multipart._final (/usr/src/app/node_modules/busboy/lib/types/multipart.js:588:17) |
| 19-04-2025 23:23 | Error: Unexpected end of form                                          |
| 19-04-2025 23:23 | ^                                                                       |
| 19-04-2025 23:23 | throw err; // Unhandled 'error' event                                  |
| 19-04-2025 23:23 | at node:events:496                                                      |
| 19-04-2025 21:12 | [Nest] 17 - 04/19/2025, 9:12:51 PM LOG [Api:EventRepository] Websocket Disconnect: n380rO5pgx3MTpVtAAAF |
| 19-04-2025 21:12 | [Nest] 17 - 04/19/2025, 9:12:46 PM LOG [Api:EventRepository] Websocket Connect: n380rO5pgx3MTpVtAAAF    |
| 19-04-2025 18:32 | [Nest] 17 - 04/19/2025, 6:32:34 PM LOG [Api:EventRepository] Websocket Disconnect: FpJ0JsP2Tf8-o1V7AAAD |
```
