### ISSUE TITLE
Immich Server does not work on linux-arm64 after updating to 1.132.0

### ISSUE THREAD

**Issue by Infiniteez** [immich-app/immich#17821]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After upgrading to v1.132.0 on a linux-arm64 based machine, Immich Server keeps restarting and the only output is this Node.js error:
"Error: Could not load the "sharp" module using the linux-arm64 runtime"

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS on linux-arm64

### Version of Immich Server

v1.132.0

### Version of Immich Mobile App

v1.132.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Rome

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. On a linux-arm64 docker host, upgrade to v1.132.0 and restart Immich (docker compose pull && docker compose up -d)
2. Run `docker compose logs -f immich-server`

### Relevant log output

```shell
immich_server  | Initializing Immich v1.132.0
immich_server  | Detected CPU Cores: 4
immich_server  | /usr/src/app/node_modules/sharp/lib/sharp.js:113
immich_server  |   throw new Error(help.join('\n'));
immich_server  |   ^
immich_server  |
immich_server  | Error: Could not load the "sharp" module using the linux-arm64 runtime
immich_server  | Possible solutions:
immich_server  | - Ensure optional dependencies can be installed:
immich_server  |     npm install --include=optional sharp
immich_server  | - Ensure your package manager supports multi-platform installation:
immich_server  |     See https://sharp.pixelplumbing.com/install#cross-platform
immich_server  | - Add platform-specific dependencies:
immich_server  |     npm install --os=linux --cpu=arm64 sharp
immich_server  | - Consult the installation documentation:
immich_server  |     See https://sharp.pixelplumbing.com/install
immich_server  |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:113:9)
immich_server  |     at Module._compile (node:internal/modules/cjs/loader:1554:14)
immich_server  |     at Object..js (node:internal/modules/cjs/loader:1706:10)
immich_server  |     at Module.load (node:internal/modules/cjs/loader:1289:32)
immich_server  |     at Function._load (node:internal/modules/cjs/loader:1108:12)
immich_server  |     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
immich_server  |     at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
immich_server  |     at Module.require (node:internal/modules/cjs/loader:1311:12)
immich_server  |     at require (node:internal/modules/helpers:136:16)
immich_server  |     at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)
immich_server  |
immich_server  | Node.js v22.14.0
```
