### ISSUE TITLE
OAuth Login into iOS App fails with "400 OAuth State Missing"

### ISSUE THREAD

**Issue by eltomato89** [immich-app/immich#17827]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Fresh installation of Immich (Docker compose, v1.132.0).

Setup OAuth login using Authentik (which works in the Browser!)

Wanted to start using the Immich app on iOS (v1.131.3, iOS 18.4). Entered Server Address, got forwarded to Login Form.
After Tap on "Login with OAuth", Browser opens, I login using my credentials, Browser dismisses, Error Appears.

Verbose Logs shows:
```
immich_server            | [Nest] 17  - 04/24/2025, 12:03:01 AM   DEBUG [Api:LoggingInterceptor~qydd0ubb] POST /api/oauth/authorize 201 1891.90ms 192.168.9.3
immich_server            | [Nest] 17  - 04/24/2025, 12:03:01 AM VERBOSE [Api:LoggingInterceptor~qydd0ubb] {"redirectUri":"app.immich:///oauth-callback"}
immich_server            | [Nest] 17  - 04/24/2025, 12:03:03 AM   DEBUG [Api:LoggingInterceptor~7cgmir7m] POST /api/oauth/callback 201 2.50ms 192.168.9.3
immich_server            | [Nest] 17  - 04/24/2025, 12:03:03 AM VERBOSE [Api:LoggingInterceptor~7cgmir7m] {"url":"app.immich:///oauth-callback?code=73190c0b0e1648bdbf1bd64f35681cf0&state=tFYg_7bFsWK4NSyFnsGBwNI7SjoNz4KIEZTwxQklZ_o"}
immich_server            | [Nest] 17  - 04/24/2025, 12:03:03 AM   DEBUG [Api:GlobalExceptionFilter~7cgmir7m] HttpException(400): {"message":"OAuth state is missing","error":"Bad Request","statusCode":400}
```

### The OS that Immich Server is running on

Ubuntu 24.04 LTS

### Version of Immich Server

v1.132.0

### Version of Immich Mobile App

v1.131.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=[REDACTED]

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Install Immich
2. Setup Authentik OAuth Provider + Application
3. Setup Oauth in Immich
4. Login using browser (works)
5. Login using iOS App (fails)

### Relevant log output

```shell
immich_server            | [Nest] 17  - 04/24/2025, 12:03:01 AM   DEBUG [Api:LoggingInterceptor~qydd0ubb] POST /api/oauth/authorize 201 1891.90ms 192.168.9.3
immich_server            | [Nest] 17  - 04/24/2025, 12:03:01 AM VERBOSE [Api:LoggingInterceptor~qydd0ubb] {"redirectUri":"app.immich:///oauth-callback"}
immich_server            | [Nest] 17  - 04/24/2025, 12:03:03 AM   DEBUG [Api:LoggingInterceptor~7cgmir7m] POST /api/oauth/callback 201 2.50ms 192.168.9.3
immich_server            | [Nest] 17  - 04/24/2025, 12:03:03 AM VERBOSE [Api:LoggingInterceptor~7cgmir7m] {"url":"app.immich:///oauth-callback?code=73190c0b0e1648bdbf1bd64f35681cf0&state=tFYg_7bFsWK4NSyFnsGBwNI7SjoNz4KIEZTwxQklZ_o"}
```
