### ISSUE TITLE
1.132.0: aarch64: Error: Could not load the "sharp" module using the linux-arm64 runtime (

### ISSUE THREAD

**Issue by rolsch** [immich-app/immich#17820]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hardware
Linux rock5b02 6.1.99-vendor-rk35xx #1 SMP Sat Apr  5 13:50:49 UTC 2025 aarch64 GNU/Linux

Upgrade from 1.131.1 to 1.132.0
docker compose pull && docker compose up -d

immich-server show this error:

`Initializing Immich v1.132.0
Detected CPU Cores: 8
/usr/src/app/node_modules/sharp/lib/sharp.js:113
  throw new Error(help.join('\n'));
  ^
Error: Could not load the "sharp" module using the linux-arm64 runtime

- see log output

### The OS that Immich Server is running on

 v25.2.3 for Rock 5B running Armbian Linux 6.1.99-vendor-rk35xx

### Version of Immich Server

v1.132.0

### Version of Immich Mobile App

not in use, web only

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: rkmpp # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-rknn
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: rknn # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=***

# How many threads of RKNN runtime should be spinned up while inferencing.
MACHINE_LEARNING_RKNN_THREADS=3

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Upgrade from 1.131.3 to 1.132.0
docker compose pull && docker compose up -d
- show log

### Relevant log output

```shell
`Initializing Immich v1.132.0

Detected CPU Cores: 8

/usr/src/app/node_modules/sharp/lib/sharp.js:113

  throw new Error(help.join('\n'));

  ^

Error: Could not load the "sharp" module using the linux-arm64 runtime

Possible solutions:

- Ensure optional dependencies can be installed:

    npm install --include=optional sharp

- Ensure your package manager supports multi-platform installation:

    See https://sharp.pixelplumbing.com/install#cross-platform

- Add platform-specific dependencies:

    npm install --os=linux --cpu=arm64 sharp

- Consult the installation documentation:

    See https://sharp.pixelplumbing.com/install

    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/sharp.js:113:9)



    at Module._compile (node:internal/modules/cjs/loader:1554:14)

    at Object..js (node:internal/modules/cjs/loader:1706:10)

    at Module.load (node:internal/modules/cjs/loader:1289:32)

    at Function._load (node:internal/modules/cjs/loader:1108:12)

    at TracingChannel.traceSync (node:diagnostics_channel:322:14)

    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)

    at Module.require (node:internal/modules/cjs/loader:1311:12)

    at require (node:internal/modules/helpers:136:16)

    at Object.<anonymous> (/usr/src/app/node_modules/sharp/lib/constructor.js:10:1)

Node.js v22.14.0`
```
