### ISSUE TITLE
Oauth fails on mobile with 1.132.0

### ISSUE THREAD

**Issue by Etienne-bdt** [immich-app/immich#17825]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Oauth does not complete on mobile but works as expected on web

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.132.0

### Version of Immich Mobile App

v1.132.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated 
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    environment:
      PUID: 109
      PGID: 117

  redis:
    container_name: immich_redis
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: docker.io/redis:6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    environment: 
      PUID: 109
      PGID: 117
  database:
    container_name: immich_postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      PUID: 109
      PGID: 117
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/immich-app/library
DB_DATA_LOCATION=/srv/immich-app/postgres
IMMICH_VERSION=release
DB_PASSWORD=Redacted
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Install v1.132.0 of the immich app and server
2. Log in using OAuth, complete login on the provider
3. Screen switches back to the server selection screen with an error in the logs 

### Relevant log output

```shell
Missing authentication, server, or endpoint info from the local store

Unable to login using offline or online methods - Logging out completely

Error Logging out
```

### Additional information

OAuth configuration from Immich : 

## ISSUER URL *
https://pocketid.mydomain.fr

## CLIENT ID *
an ID 

## CLIENT SECRET *
the right secret 

## SCOPE *
openid email profile picture

## SIGNING ALGORITHM *
RS256

PROFILE SIGNING ALGORITHM *
none

## STORAGE LABEL CLAIM *
email

## STORAGE QUOTA CLAIM *
immich_quota

## DEFAULT STORAGE QUOTA (GIB) *
0

## BUTTON TEXT

Login with PocketID

## AUTO REGISTER
False

## AUTO LAUNCH
False

## MOBILE REDIRECT URI OVERRIDE
False

Provider side : 

## CallBack URLs
https://photo.mydomain.fr/auth/login
app.immich:///oauth-callback
