### ISSUE TITLE
Immich not launching after update to v1.132.1

### ISSUE THREAD

**Issue by elpendor** [immich-app/immich#17839]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating my immich instance to 1.132.1, it fails to start properly.

I've attached the relevant error below. Seems to be related to a not-null constraint in geodata_places and it restarts that worker and fails over and over again 

### The OS that Immich Server is running on

Linux 6.12.20+rpt-rpi-v8

### Version of Immich Server

1.132.1

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

networks:
  app_network:
    external: false
    
services:  
  immich-cloudflared-v2:
    image: erisamoe/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=xxxxxxxxxxxxx
    depends_on:
      - immich-server
      
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}    
    volumes:
      - xxxxxxxx:/usr/src/app/xxxxxxx
      - xxxxxxxx:/usr/src/app/xxxxxxxx
      - xxxxxxxx:/usr/src/app/xxxxxxxx
      - xxxxxxxx:/usr/src/app/xxxxxxxx
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich_instance.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - app_network

  immich-machine-learning:
    networks:
      - app_network
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - immich_instance.env
    restart: always

  redis:
    networks:
      - app_network
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    networks:
      - app_network
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always
    
volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=xxxxxxxxxxxxxxxxxx
THUMB_LOCATION=xxxxxxxxxxxxxxxxxxx
# The location where your database files are stored
DB_DATA_LOCATION=xxxxxxxxxxxxxxxxxxxxx

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxxxxxxxxxxxxxx
DB_DATABASE_NAME=xxxxxxxxx
```

### Reproduction steps

1. updated from 1.131.3 using docker compose pull
2. run up again
3. immich instances returns errors

### Relevant log output

```shell
immich_server  | [Nest] 7  - 04/24/2025, 5:28:16 AM   ERROR [Microservices:MetadataService] Unable to initialize reverse geocoding: PostgresError: null value in column "name" of relation "geodata_places" violates not-null constraint
immich_server  | PostgresError: null value in column "name" of relation "geodata_places" violates not-null constraint
immich_server  |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server  |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server  |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server  |     at Socket.emit (node:events:518:28)
immich_server  |     at addChunk (node:internal/streams/readable:561:12)
immich_server  |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server  |     at Readable.push (node:internal/streams/readable:392:5)
immich_server  |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server  | Error: Metadata service init failed
immich_server  |     at MetadataService.init (/usr/src/app/dist/services/metadata.service.js:95:19)
immich_server  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server  |     at async MetadataService.onBootstrap (/usr/src/app/dist/services/metadata.service.js:74:9)
immich_server  |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server  |     at async MicroservicesModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
immich_server  |     at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
immich_server  |     at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
immich_server  |     at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
immich_server  |     at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)
immich_server  |     at async bootstrap (/usr/src/app/dist/workers/microservices.js:25:5)
immich_server  | microservices worker error: Error: Metadata service init failed, stack: Error: Metadata service init failed
immich_server  |     at MetadataService.init (/usr/src/app/dist/services/metadata.service.js:95:19)
immich_server  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server  |     at async MetadataService.onBootstrap (/usr/src/app/dist/services/metadata.service.js:74:9)
immich_server  |     at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
immich_server  |     at async MicroservicesModule.onModuleInit (/usr/src/app/dist/app.module.js:83:9)
immich_server  |     at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
immich_server  |     at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:242:13)
immich_server  |     at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
immich_server  |     at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:170:13)
immich_server  |     at async bootstrap (/usr/src/app/dist/workers/microservices.js:25:5)
immich_server  | microservices worker exited with code 1
```
