### ISSUE TITLE
OAuth workflow throwing error 500 on 0.132.1 : server responded with a challenge in the WWW-Authenticate HTTP Header

### ISSUE THREAD

**Issue by lucienastie** [immich-app/immich#17864]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I'm trying to connect to my account using OAuth it fails and tells me that the server responded with a challenge in the WWW-Authenticate HTTP Header.

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

v0.132.1

### Version of Immich Mobile App

v0.132.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /data1/immich-upload:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - immich-redis
      - immich-database
      - immich-machine-learning
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.immich-https.rule=Host(`REDACTED`)
      - traefik.http.routers.immich-https.entrypoints=https
      - traefik.http.routers.immich-https.tls=true
      - traefik.http.routers.immich-https.tls.domains[0].main=REDACTED
      - traefik.http.routers.immich-https.tls.domains[0].sans=REDACTED
      - traefik.http.routers.immich-https.tls.certresolver=dns
      - traefik.http.routers.immich-https.service=immich
      - traefik.http.routers.immich-http.rule=Host(`REDACTED`)
      - traefik.http.routers.immich-http.entrypoints=http
      - traefik.http.routers.immich-http.service=immich
      - traefik.http.services.immich.loadbalancer.server.port=2283

  immich-redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    networks:
      - proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    networks:
      - proxy
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  immich-database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: REDACTED
      POSTGRES_DB: REDACTED
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=REDACTED
DB_USERNAME=REDACTED
DB_PASSWORD=REDACTED
DB_DATABASE_NAME=REDACTED

IMMICH_TELEMETRY_INCLUDE=all

REDIS_HOSTNAME=immich_redis

REVERSE_GEOCODING_PRECISION=3
```

### Reproduction steps

1. I go to my URL and click on the OAuth login button
2. It connects to my OIDC backend then gets back to immich
3. The immich server throws error 500...

### Relevant log output

```shell
[Nest] 17  - 04/24/2025, 10:01:47 PM   ERROR [Api:ErrorInterceptor~7g7t7koc] Unknown error: WWWAuthenticateChallengeError: server responded with a challenge in the WWW-Authenticate HTTP Header
WWWAuthenticateChallengeError: server responded with a challenge in the WWW-Authenticate HTTP Header
    at checkAuthenticationChallenges (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1207:15)
    at processGenericAccessTokenResponse (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1140:5)
    at processAuthorizationCodeOAuth2Response (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1373:26)
    at Module.processAuthorizationCodeResponse (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1317:12)
    at authorizationCodeGrant (file:///usr/src/app/node_modules/openid-client/build/index.js:842:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:52:28)
```

### Additional information

I'm using an [OIDC backend](https://gitlab.com/yaal/canaille) that is still in development, so maybe you updated something in the OAuth workflow that my backend doesn't support ? Are there any changes between 0.131.3 and 0.132.2 ?

Thanks for taking the time to read my issue !

EDIT : I didn't mention it, but it used to work before and I didn't updated my backend between 0.131.3 and 0.132.1
