### ISSUE TITLE
Failed to finish oauth - authelia

### ISSUE THREAD

**Issue by Janczykkkko** [immich-app/immich#17909]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello, 

After upgrading to 1.132.0 (same on132.1) my oauth integration with authelia stopped working.

Logged in users have no issue - after loggin out can't log back in using oauth. Tried incognito etc.

Oauth in general works in other applications.

### The OS that Immich Server is running on

synology docker

### Version of Immich Server

1.132.0

### Version of Immich Mobile App

1.132.0

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3"
services:
  immich:
    image: harbor.lalala.eu/ghcr.io/imagegenius/immich:v1.132.0-ig388
    container_name: immich
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Warsaw
      - DB_HOSTNAME=immich-postgres
      - DB_USERNAME=lalala
      - DB_PASSWORD=lalala
      - DB_DATABASE_NAME=lalala
      - REDIS_HOSTNAME=immich-redis
      - DISABLE_MACHINE_LEARNING=false
      - DISABLE_TYPESENSE=false
      - DB_PORT=5432
      - S6_VERBOSITY=2
      - REDIS_PORT=6379
    volumes:
      - /volume1/docker/data/immich/config:/config
      - /volume2/photos-new/encoded-video:/photos/encoded-video
      - /volume2/photos-new/library:/photos/library
      - /volume2/photos-new/profile:/photos/profile
      - /volume2/photos-new/upload:/photos/upload
      - /volume2/photos-new/backups:/photos/backups
      - /volume2/photos-new/thumbs:/photos/thumbs
      - /volume1/docker/data/immich/ML:/config/machine-learning #optional
      - /volume1/docker/data/immich/run:/etc/s6-overlay/s6-rc.d/init-config-immich/run
    expose:
      - 8080
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`photos.lalala.eu`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.services.immich.loadbalancer.server.port=8080
      - traefik.http.routers.immich.tls=true
      - traefik.http.routers.immich.priority=10
  immich-redis:
    image: harbor.lalala.eu/dockerhub/redis
    restart: always
    environment:
      - TZ=Europe/Warsaw
    expose:
      - 6379
    container_name: immich-redis
    volumes:
      - /volume1/docker/data/immich-redis:/data
  immich-postgres:
    image: harbor.lalala.eu/dockerhub/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    expose:
      - 5432
    container_name: immich-postgres
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    restart: always
    environment:
      POSTGRES_USER: lalala
      POSTGRES_PASSWORD: lalala
      POSTGRES_DB: lalala
      TZ: Europe/Warsaw
    volumes:
      - /volume1/docker/data/immich-postgres:/var/lib/postgresql/data
networks:
  default:
    name: root
    external: true
```

### Your .env content

```Shell
in compose
```

### Reproduction steps

1. Upgrade to 1.132.0? :D
2.
3.
...

### Relevant log output

```shell
04/27/2025 5:50:55 PM
[Nest] 180  - 04/27/2025, 5:50:55 PM   DEBUG [Api:LoggingInterceptor~jkoksmgv] POST /api/oauth/authorize 201 55.45ms 172.19.0.1
04/27/2025 5:50:56 PM
[Nest] 180  - 04/27/2025, 5:50:56 PM   DEBUG [Api:LoggingInterceptor~oc6p1u27] GET /api/oauth/mobile-redirect?code=authelia_ac_jTT3REDACTEDJPAdHuwUt8dUCTPq0VKxoRFhLDV0eM.AZelwVsivvrQ_5-hbt3xIKHtPTUa7cDPokIK__MCLik&iss=https%3A%2F%2Fauth.REDACTED.eu&scope=openid+email+profile&state=wYLe9I38N4hovo0QD96sJ0-hEovPHn45T8zwth2Qp8w%3D 200 1.04ms 172.19.0.1
04/27/2025 5:50:57 PM
[Nest] 180  - 04/27/2025, 5:50:57 PM   ERROR [Api:ErrorInterceptor~oy0d52tq] Unknown error: ResponseBodyError: server responded with an error in the response body
04/27/2025 5:50:57 PM
ResponseBodyError: server responded with an error in the response body
04/27/2025 5:50:57 PM
    at checkOAuthBodyError (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:865:19)
04/27/2025 5:50:57 PM
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
04/27/2025 5:50:57 PM
    at async processGenericAccessTokenResponse (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:1141:5)
04/27/2025 5:50:57 PM
    at async processAuthorizationCodeOAuth2Response (file:///app/immich/server/node_modules/oauth4webapi/build/index.js:1373:20)
04/27/2025 5:50:57 PM
    at async authorizationCodeGrant (file:///app/immich/server/node_modules/openid-client/build/index.js:850:18)
04/27/2025 5:50:57 PM
    at async OAuthRepository.getProfile (/app/immich/server/dist/repositories/oauth.repository.js:52:28)
04/27/2025 5:50:57 PM
    at async AuthService.callback (/app/immich/server/dist/services/auth.service.js:137:25)
04/27/2025 5:50:57 PM
    at async OAuthController.finishOAuth (/app/immich/server/dist/controllers/oauth.controller.js:46:22)
04/27/2025 5:50:57 PM
[Nest] 180  - 04/27/2025, 5:50:57 PM   DEBUG [Api:LoggingInterceptor~oy0d52tq] POST /api/oauth/callback 201 56.83ms 172.19.0.1
04/27/2025 5:50:57 PM
[Nest] 180  - 04/27/2025, 5:50:57 PM   DEBUG [Api:GlobalExceptionFilter~oy0d52tq] HttpException(500): {"message":"Failed to finish oauth","error":"Internal Server Error","statusCode":500}
04/27/2025 5:50:57 PM
[Nest] 180  - 04/27/2025, 5:50:57 PM   DEBUG [Api:GlobalExceptionFilter~po83xfhv] HttpException(401): {"message":"Invalid user token","error":"Unauthorized","statusCode":401}
04/27/2025 5:50:57 PM
[Nest] 180  - 04/27/2025, 5:50:57 PM   DEBUG [Api:GlobalExceptionFilter~m207my28] HttpException(401): {"message":"Invalid user token","error":"Unauthorized","statusCode":401}
```
