### ISSUE TITLE
Some external libraries missing after update

### ISSUE THREAD

**Issue by davidakerr** [immich-app/immich#17940]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After upgrading Immich from an earlier release (prior to v1.132.3), one of my external libraries stopped working.

## Additional context
- Host OS: Pop!_OS
- Docker version: Docker version 28.1.1, build 4eba377
- Immich version: v1.132.3
- Original Immich version before upgrade: Unsure, quite old, but working previously.
- Using CIFS mounts for external folders
- Permissions and mounts confirmed correct at host and container level.

Please let me know if further info is needed. Thanks for your awesome work!

### The OS that Immich Server is running on

PopOS

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

vxxxx

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photo:/usr/src/app/external/photo:ro
      - /mnt/photo_additional_library:/usr/src/app/external/additional_library:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres

IMMICH_VERSION=release

DB_PASSWORD=XXXXXXX

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

- `/usr/src/app/external/photo` still works and displays correctly.
- `/usr/src/app/external/additional_library`  no longer shows any photos/videos.
- Both folders are properly mounted inside the container and accessible.
- additonal_library no longer shows in folder view either, suggesting its not being indexed ?
- Scan all libraries pressed and scan library specifically

The `additional_library` library was previously functional before the upgrade.  
The path is visible and correctly configured under "External Library Management," but the media content is missing.

I configured Immich to scan `/external/photo` and `/external/additional_library` (both verified and I can see that the folder has files when running `docker exec -it immich_server ls /usr/src/app/external/additional_library`)

### Relevant log output

```shell

```
