### ISSUE TITLE
Race Condition in File Processing - Files Being Moved Before Metadata Extraction

### ISSUE THREAD

**Issue by rcdailey** [immich-app/immich#17954]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I've discovered a race condition in Immich's file processing pipeline. The application attempts to rename/move uploaded files from the temporary upload directory to permanent storage locations before other processes (like metadata extraction) have completed their work.

This results in "File not found" errors in the logs as the metadata extraction service tries to access files at their original paths after they've already been moved by the API service. This appears to be a timing/synchronization issue between different services attempting to work with the same files concurrently.

For example, the logs show the ApiKeyService renaming a file:
```
DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/upload/c747a99d-c3e9-4ca1-9c69-0d54dc9235c5/3c/4b/3c4b2205-2a95-421a-99db-089055add024.jpg => upload/library/jennifer/2014/April/20140405_092955.jpg
```

And shortly after, the metadata extraction job fails because it can't find the file at its original location:
```
ERROR [Microservices:{"id":"2f83ec11-d2de-4850-8b0e-8732af89c52b","source":"copy"}] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/c747a99d-c3e9-4ca1-9c69-0d54dc9235c5/3c/4b/3c4b2205-2a95-421a-99db-089055add024.jpg'
```

This issue leads to HTTP 5xx errors being returned to the client during uploads and potentially incomplete metadata extraction for affected files.

### The OS that Immich Server is running on

Unraid (Linux)

### Version of Immich Server

v1.132.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

networks:
  reverse_proxy:
    external: true
    driver: overlay

x-logging: &logging
  driver: json-file
  options:
    max-file: "1"
    max-size: "50m"

services:
  server:
    image: ghcr.io/immich-app/immich-server:v1.132.1
    restart: unless-stopped
    logging: *logging
    depends_on: [redis, database]
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    # ports: [2283:2283]
    networks:
      default:
      reverse_proxy:
        aliases: [immich]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/photos/immich:/usr/src/app/upload
      # Override some paths for SSD performance
      - ./upload/thumbs:/usr/src/app/upload/thumbs
      - ./upload/profile:/usr/src/app/upload/profile
    labels:
      - swag=enable
      - swag_url=photos.*

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.131.2
    restart: unless-stopped
    logging: *logging
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    volumes:
      - ./ml/.config:/.config
      - ./ml/.cache:/.cache
      - ./ml/cache:/cache

  redis:
    image: redis
    restart: unless-stopped
    logging: *logging
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - ./redis:/data

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    restart: unless-stopped
    logging: *logging
    env_file: [.env]
    user: $DOCKER_UID:$DOCKER_GID
    security_opt: [no-new-privileges:true]
    cap_drop: [NET_RAW]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s # Requires docker v25
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
```

### Your .env content

```Shell
DB_PASSWORD=<snip>
DB_USERNAME=immich
DB_DATABASE_NAME=immich
TZ=America/Chicago
NO_COLOR=1
```

### Reproduction steps

1. Set up a Storage Template in Immich Settings (before any uploads) with the template pattern: `{{y}}/{{MMMM}}/{{filename}}`
2. Use immich-go to mass upload photos/videos from Google Photos Takeout archives:
   ```
   immich-go.exe upload from-google-photos --server=https://[YOUR-IMMICH-SERVER] --api-key=[YOUR-API-KEY] .\takeout-*.zip
   ```
3. Very quickly after the uploads begin, HTTP 5xx errors start to appear
4. Check the Immich server logs to observe the race condition where files are being renamed before metadata extraction is complete
5. Notice "ENOENT: no such file or directory" errors indicating files can't be found at their original paths

### Relevant log output

```shell
server-1  | [Nest] 7  - 04/28/2025, 10:58:38 PM   DEBUG [Microservices:ApiKeyService] Attempting to rename file: upload/upload/c747a99d-c3e9-4ca1-9c69-0d54dc9235c5/3c/4b/3c4b2205-2a95-421a-99db-089055add024.jpg => upload/library/jennifer/2014/April/20140405_092955.jpg

server-1  | [Nest] 7  - 04/28/2025, 10:58:38 PM   ERROR [Microservices:{"id":"2f83ec11-d2de-4850-8b0e-8732af89c52b","source":"copy"}] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ENOENT: no such file or directory, stat 'upload/upload/c747a99d-c3e9-4ca1-9c69-0d54dc9235c5/3c/4b/3c4b2205-2a95-421a-99db-089055add024.jpg'

server-1  | [Nest] 7  - 04/28/2025, 10:58:38 PM   WARN [Microservices:Error: File not found - /usr/src/app/upload/upload/c747a99d-c3e9-4ca1-9c69-0d54dc9235c5/3c/4b/3c4b2205-2a95-421a-99db-089055add024.jpg] Error reading exif data...

server-1  | [Nest] 7  - 04/28/2025, 10:58:38 PM   ERROR [Microservices:{"id":"91325a5f-0371-42a2-8bfc-c98bd527ad0c","source":"sidecar-write"}] Unable to run job handler (metadataExtraction/metadata-extraction): Error: ffprobe exited with code 1
```

### Additional information

The issue is particularly evident when using immich-go to mass upload a large dataset like Google Photos Takeout archives (~200GB). This creates a high-concurrency scenario that exposes the race condition in the file processing pipeline.

The presence of a Storage Template is a key factor in triggering this bug, as it causes the system to rename files according to the template pattern during processing. Despite these errors, the system does continue to function and process some files successfully.

This appears to be a synchronization issue between different services that needs better coordination of file operations between the API service and microservices. The file renaming operation should likely happen after all metadata extraction is complete, or paths should be properly updated across all services when files are moved.
