### ISSUE TITLE
OIDC does not work with Authentik

### ISSUE THREAD

**Issue by uladzimir-shelhunou-v2** [immich-app/immich#17973]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I am not able to login via Authentik starting from 1.132.0.

I am getting the following error:

ApiException 500: ("message":"Failed to finish oauth","error":"Internal Server Error ","statusCode":500,"correlationId":"I6niisrd"}

![Image](https://github.com/user-attachments/assets/aa6449b8-0d7a-496a-9037-d131bc1e2763)

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  proxy:
    container_name: immich_proxy
    image: nginx:latest
    ports:
      - 443:443
      - 8443:8443
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs/:/etc/nginx/certs
    depends_on:
      - immich-server
    restart: always

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
      - /root/immich-app/certs/home-ca.crt:/etc/ca.crt
    env_file:
      - .env
    environment:
      IMMICH_WORKERS_INCLUDE: 'api'
    ports:
      - '2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /root/immich-app/ca.crt:/etc/ca.crt
    env_file:
      - .env
    environment:
      IMMICH_WORKERS_EXCLUDE: 'api'
    ports:
      - '2283'
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
    - "5432"
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
BACKUP_LOCATION=/mnt/backups
# The location where your database files are stored
DB_DATA_LOCATION=/var/lib/postgresql
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this
list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<hidden>
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=<hidden>
DB_DATABASE_NAME=immich
# CA
NODE_EXTRA_CA_CERTS=/etc/ca.crt
```

### Reproduction steps

1. Configure OIDC with Authentik
2. Login with OIDC via mobile
3. 500 error is displayed

### Relevant log output

```shell
immich_server  | [Nest] 17  - 04/29/2025, 5:51:00 PM    WARN [Api:OAuthRepository~3l61kpx8] Invalid response from authorization server. Cause: unexpected JWT "alg" header parameter
immich_server  | [Nest] 17  - 04/29/2025, 5:51:00 PM   ERROR [Api:ErrorInterceptor~3l61kpx8]
Unknown error: OperationProcessingError: unexpected JWT "alg" header parameter
immich_server  | OperationProcessingError: unexpected JWT "alg" header parameter
immich_server  |     at OPE (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:92:12)
immich_server  |     at checkSigningAlgorithm (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1924:19)
immich_server  |     at validateJwt (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1655:5)
immich_server  |     at processGenericAccessTokenResponse (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1184:39)
immich_server  |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server  |     at async processAuthorizationCodeOAuth2Response (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1373:20)
immich_server  |     at async authorizationCodeGrant (file:///usr/src/app/node_modules/openid-client/build/index.js:850:18)
immich_server  |     at async OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:52:28)
immich_server  |     at async AuthService.callback (/usr/src/app/dist/services/auth.service.js:137:25)
immich_server  |     at async OAuthController.finishOAuth (/usr/src/app/dist/controllers/oauth.controller.js:46:22)
```
