### ISSUE TITLE
I have a error on face recognizing

### ISSUE THREAD

**Issue by reheinz** [immich-app/immich#17981]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have a error on face recognizing

### The OS that Immich Server is running on

Synology

### Version of Immich Server

v.1.132.1 to 1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/TEST
      - /volume3/photo/01_Hj_So:/usr/src/app/01_Hj_So
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${MODEL_CACHE}:/cache
    env_file:
      - stack.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    healthcheck:
      disable: false
    
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; 
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
#     start_interval: 30s            Need Docker Engine v25
      start_period: 5m
      
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
      
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume3/docker/04_immich/library
EXTERNAL_PATH=/volume3/photo/TEST
DB_DATA_LOCATION=/volume3/docker/04_immich/pgdata
MODEL_CACHE=/volume3/docker/04_immich/model-cache
IMMICH_VERSION=release
DB_PASSWORD=............
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Asia/Seoul
REDIS_DATA=/volume3/docker/04_immich/redis
PGTZ=Asia/Seoul
```

### Reproduction steps

1. After update v1.132.1
2. I can find Something changed redis and database version.
3. I changed the database ver. and redis ver.
4. 4
5.  After My server can't recognize face about additional pictures.
...

### Relevant log output

```shell
[Nest] 7  - 04/30/2025, 5:37:30 AM   ERROR [Microservices:{"id":"3bfe0e49-6fea-465f-a8e5-be0c8d26f995"}] Unable to run job handler (faceDetection/face-detection): PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x30.
PostgresError: pgvecto.rs: Bad literal.
INFORMATION: hint = Bad character with ascii 0x30.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
```
