### ISSUE TITLE
Memories - Duplicates Images

### ISSUE THREAD

**Issue by guydelarea** [immich-app/immich#17984]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After searching and trying the solution suggested at Issue-16484 on GitHub https://github.com/immich-app/immich/issues/16484#issuecomment-2692718993, the problem seems to persist.

When I run the commands against my database and retry the image generation, the problem seems to be fixed for about a couple of days, and then it returns to show duplicates.

The commands:
```sql
delete from system_metadata where key like 'memories-state'; truncate table memories cascade
```

This issue started around `1.127.0` and i have been updating regulary to the latest releases.

### The OS that Immich Server is running on

Ubuntu 22.04.5 | k3s v1.30.4

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3 build.187

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  immich-server
  namespace: immich
  labels:
    app: immich-server
spec:
  selector:
    matchLabels:
      app: immich-server
  replicas: 6
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      securityContext:
        runAsUser: 0
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data
        - name: nextcloud-share
          persistentVolumeClaim:
            claimName: nextcloud-share
      containers:
      - name:  immich-server
        image:  ghcr.io/immich-app/immich-server:v1.132.3
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /usr/src/app/upload
            name: immich-data
          - mountPath: /usr/src/app/XXXXX
            name: nextcloud-share
        envFrom:
        - configMapRef:
            name: immich-env
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich-machine-learning
spec:
  selector:
    matchLabels:
      app: immich-machine-learning
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  immich-machine-learning
    spec:
      volumes:
        - name: immich-data
          persistentVolumeClaim:
            claimName: immich-data
      runtimeClassName: nvidia
      containers:
      - name: immich-machine-learning
        image: ghcr.io/immich-app/immich-machine-learning:v1.132.3-cuda
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /cache
            name: immich-data
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        envFrom:
        - configMapRef:
            name: immich-env
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      nodeSelector:
        gpu: "yes"
```

### Your .env content

```Shell
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-env
  namespace: immich
data:
  UPLOAD_LOCATION: "./library"
  DB_PASSWORD: XXX
  DB_HOSTNAME: "XXXXX"
  DB_USERNAME: "XXXXXX"
  DB_PORT: "5431"
  DB_DATABASE_NAME: "XXXXXXXX"
  REDIS_HOSTNAME: "XXXXXXXX"
  REDIS_PASSWORD: XXXXXXXXXXXXX
  IMMICH_LOG_LEVEL: "debug"
```

### Reproduction steps

1. Run the commands to clear memories from the database.
2. Regenerate memories using jobs.
3. Wait a couple of days, and then the memories get duplicated.

### Relevant log output

```shell

```

### Additional information

Screenshot:

![Image](https://github.com/user-attachments/assets/0996941e-88b5-4328-9e58-62fdfa9f3201)
