### ISSUE TITLE
[ML] Smare Search job hangs RKNN_QUERY_INPUT_DYNAMIC_RANGE

### ISSUE THREAD

**Issue by TheSainEyereg** [immich-app/immich#17982]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I'm aware about https://github.com/immich-app/immich/issues/17098, however it's about `CumSum` and not about RKNN_QUERY_INPUT_DYNAMIC_RANGE

When running a Smart Search job on my Orange Pi 5 Plus (rk3588), the task hangs and a bunch of error messages appear in the container output

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.131.3

### Version of Immich Mobile App

Any

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich_remote_ml

services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-rknn
    extends:
      file: hwaccel.ml.yml
      service: rknn # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    env_file:
      - ./.env
    volumes:
      - model-cache:/cache
    restart: always
    ports:
      - 3003:3003

volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_VERSION=release
MACHINE_LEARNING_RKNN_THREADS=3
```

### Reproduction steps

1. Set `ViT-SO400M-16-SigLIP2-384__webli` as ML model
2. Attach to container
3. Run Smart Search job
4. See a bunch of errors (Smart Search job hangs)

### Relevant log output

```shell
Will attach later (sorry)
```

### Additional information

Same as https://github.com/immich-app/immich/issues/17098#issuecomment-2760582012, but made it a separate issue
