### ISSUE TITLE
Transcoding fails on Intel UHD 770 (vp9_qsv encoder error)

### ISSUE THREAD

**Issue by dvbthien** [immich-app/immich#18001]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When uploading some HEVC (Main10, Dolby Vision) videos from an iPhone 15 to Immich (running inside Docker in an unprivileged Proxmox LXC container), transcoding fails when using Intel UHD 770 hardware acceleration with vp9_qsv, showing the error: Error occurred during transcoding: ffmpeg exited with code 234: Conversion failed!.  

### The OS that Immich Server is running on

Ubuntu 24.10

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    hostname: immich-server
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    networks:
      - docker_proxy
    ports:
      - 2283:2283
    environment:
      - TZ=$TZ
      - LOG_LEVEL=log
      - DB_HOSTNAME=
      - DB_DATABASE_NAME=
      - DB_USERNAME=
      - DB_PASSWORD=
    volumes:
      - $DOCKERDIR/appdata/immich/config:/config
      - /mnt/immich_photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich-api-https.entrypoints=https"
      - "traefik.http.routers.immich-api-https.rule=Host(`immich.$DOMAIN_HOME`)"
      - "traefik.http.routers.immich-api-https.service=immich-api"
      - "traefik.http.routers.immich-api-https.middlewares=chain-https-no-auth@file"
      - "traefik.http.routers.immich-api-http.entrypoints=http"
      - "traefik.http.routers.immich-api-http.rule=Host(`immich.$DOMAIN_HOME`)"
      - "traefik.http.routers.immich-api-http.middlewares=chain-redirect-to-https@file"
      - "traefik.http.services.immich-api.loadbalancer.server.port=2283"
    restart: unless-stopped
    depends_on:
      - immich_redis
      - immich_db

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release-openvino
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    security_opt:
      - no-new-privileges:true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri:/dev/dri
    networks:
      - docker_proxy
    environment:
      - MPLCONFIGDIR=/matplotlib
    volumes:
      - $DOCKERDIR/appdata/immich/model-cache:/cache
      - $DOCKERDIR/appdata/immich/model-cache/matplotlib:/matplotlib
      - /mnt/immich_photos:/usr/src/app/upload
    restart: unless-stopped
 
  immich_db:
    image: tensorchord/pgvecto-rs:pg15-v0.3.0
    container_name: immich_postgres
    hostname: immich_postgres
    security_opt:
      - no-new-privileges:true
    networks:
      - docker_proxy
    environment:
      - TZ=$TZ
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - $DOCKERDIR/appdata/immich/db:/var/lib/postgresql/data
    restart: unless-stopped

  immich_redis:
    image: valkey/valkey:8-bookworm
    container_name: immich_redis
    hostname: immich_redis
    security_opt:
      - no-new-privileges:true
    networks:
      - docker_proxy
    expose:
      - 6379
    volumes:
      - $DOCKERDIR/appdata/immich/redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
```

### Your .env content

```Shell
No relevant
```

### Reproduction steps

1. Upload a .mov video recorded on iPhone 15 (HEVC 10-bit, Dolby Vision, bt2020 color space) to Immich.
2. Wait for automatic transcoding to start.
3. The video will fail to transcode, though other videos with different codecs succeed.

### Relevant log output

```shell
[Nest] 7  - 04/30/2025, 12:44:58 AM   ERROR [Microservices:MediaService] Error occurred during transcoding: ffmpeg exited with code 234: Conversion failed!
[Nest] 7  - 04/30/2025, 12:44:58 AM   ERROR [Microservices:MediaService] Retrying with QSV-accelerated encoding and software decoding
[Nest] 7  - 04/30/2025, 12:44:58 AM     LOG [Microservices:MediaService] Successfully encoded a3c75bed-e9b5-4c06-8576-b0beea73233d
[Nest] 7  - 04/30/2025, 12:44:58 AM     LOG [Microservices:MediaService] Transcoding video 7fcc04e0-0b3c-49d4-bd98-4ba9a9178025 with QSV-accelerated encoding and decoding
[Nest] 7  - 04/30/2025, 12:44:59 AM     LOG [Microservices:MediaService] Successfully encoded 7fcc04e0-0b3c-49d4-bd98-4ba9a9178025
[Nest] 7  - 04/30/2025, 12:44:59 AM     LOG [Microservices:MediaService] Transcoding video 88a44a96-02b9-4087-a8a7-88ed6944d78f with QSV-accelerated encoding and decoding
[Nest] 7  - 04/30/2025, 12:45:02 AM     LOG [Microservices:MediaService] Successfully encoded 88a44a96-02b9-4087-a8a7-88ed6944d78f
[Nest] 7  - 04/30/2025, 12:45:02 AM     LOG [Microservices:MediaService] Transcoding video fca6e3bb-787c-4034-ab2a-b607ca349f4a with QSV-accelerated encoding and decoding
[Nest] 7  - 04/30/2025, 12:45:02 AM   ERROR [Microservices:MediaRepository] Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/admin/2024/2024-03-23/IMG_8039.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 0
    compatible_brands: qt  
    creation_time   : 2024-03-23T05:46:56.000000Z
    com.apple.quicktime.location.accuracy.horizontal: 3.535534
    com.apple.quicktime.location.ISO6709: +17.7736+106.0726+158.203/
    com.apple.quicktime.make: Apple
    com.apple.quicktime.model: iPhone 15
    com.apple.quicktime.software: 17.3.1
    com.apple.quicktime.creationdate: 2024-03-23T12:46:56+0700
  Duration: 00:00:09.36, start: 0.000000, bitrate: 57811 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main 10), 1 reference frame (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67, left), 3840x2160, 57524 kb/s, 59.94 fps, 59.94 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-03-23T05:46:56.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 10, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4
        displaymatrix: rotation of -90.00 degrees
        Ambient Viewing Environment, ambient_illuminance=314.000000, ambient_light_x=0.312700, ambient_light_y=0.329000
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 183 kb/s (default)
      Metadata:
        creation_time   : 2024-03-23T05:46:56.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](und): Data: none (mebx / 0x7862656D), 0 kb/s (default)
      Metadata:
        creation_time   : 2024-03-23T05:46:56.000000Z
        handler_name    : Core Media Metadata
  Stream #0:3[0x4](und): Data: none (mebx / 0x7862656D), 1 kb/s (default)
      Metadata:
        creation_time   : 2024-03-23T05:46:56.000000Z
        handler_name    : Core Media Metadata
  Stream #0:4[0x5](und): Data: none (mebx / 0x7862656D), 82 kb/s (default)
      Metadata:
        creation_time   : 2024-03-23T05:46:56.000000Z
        handler_name    : Core Media Metadata
[out#0/mp4 @ 0x43c7412d380] Adding streams from explicit maps...
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Created video stream from input stream 0:0
[aost#0:1/copy @ 0x43c74c61080] Created audio stream from input stream 0:1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_qsv) -> vp9 (vp9_qsv))
  Stream #0:1 -> #0:1 (copy)
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Starting thread...
[vf#0:0 @ 0x43c74c09c80] Starting thread...
[vist#0:0/hevc @ 0x43c74181680] [dec:hevc_qsv @ 0x43c74068b00] Starting thread...
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80] Starting thread...
Press [q] to stop, [?] for help
[AVHWDeviceContext @ 0x43c7a020480] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x43c7a020480] Driver not found in known nonstandard list, using standard behaviour.
[hevc_qsv @ 0x43c74203980] Decoder: output is video memory surface
[hevc_qsv @ 0x43c74203980] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[AVHWDeviceContext @ 0x43c7a020a80] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x43c7a020a80] Driver not found in known nonstandard list, using standard behaviour.
[hevc_qsv @ 0x43c74203980] Decoder: output is video memory surface
[hevc_qsv @ 0x43c74203980] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[graph 0 input from stream 0:0 @ 0x43c76060840] w:3840 h:2160 pixfmt:qsv tb:1/600 fr:60000/1001 sar:0/1 csp:bt2020nc range:tv
[AVHWDeviceContext @ 0x43c76060c00] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x43c76060c00] Driver not found in known nonstandard list, using standard behaviour.
[Parsed_scale_qsv_0 @ 0x43c76060480] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[Parsed_scale_qsv_0 @ 0x43c76060480] VPP: input is video memory surface
[Parsed_scale_qsv_0 @ 0x43c76060480] VPP: output is video memory surface
[AVHWDeviceContext @ 0x43c76060240] 0.0: Intel(R) OpenCL Graphics / Intel(R) UHD Graphics 770
[AVHWDeviceContext @ 0x43c76060240] Intel QSV to OpenCL mapping function found (clCreateFromVA_APIMediaSurfaceINTEL).
[AVHWDeviceContext @ 0x43c76060240] Intel QSV in OpenCL acquire function found (clEnqueueAcquireVA_APIMediaSurfacesINTEL).
[AVHWDeviceContext @ 0x43c76060240] Intel QSV in OpenCL release function found (clEnqueueReleaseVA_APIMediaSurfacesINTEL).
[AVHWDeviceContext @ 0x43c760624c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 24.4.2 (b6b411f).
[AVHWDeviceContext @ 0x43c760624c0] Driver not found in known nonstandard list, using standard behaviour.
[graph 0 input from stream 0:0 @ 0x43c76060840] video frame properties congruent with link at pts_time: 0
[vp9_qsv @ 0x43c74203180] Using input frames context (format qsv) with vp9_qsv encoder.
[vp9_qsv @ 0x43c74203180] Encoder: input is video memory surface
[vp9_qsv @ 0x43c74203180] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
[vp9_qsv @ 0x43c74203180] Using the constant quantization parameter (CQP) ratecontrol method
[vp9_qsv @ 0x43c74203180] Error initializing the encoder: invalid video parameters (-15)
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 0x43c74c09c80] Error sending frames to consumers: Invalid argument
[vf#0:0 @ 0x43c74c09c80] Task finished with error code: -22 (Invalid argument)
[vf#0:0 @ 0x43c74c09c80] Terminating thread with return code -22 (Invalid argument)
[vist#0:0/hevc @ 0x43c74181680] [dec:hevc_qsv @ 0x43c74068b00] Decoder returned EOF, finishing
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Encoder thread received EOF
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Could not open encoder before EOF
[vist#0:0/hevc @ 0x43c74181680] [dec:hevc_qsv @ 0x43c74068b00] Terminating thread with return code 0 (success)
[vist#0:0/hevc @ 0x43c74181680] All consumers of this stream are done
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Task finished with error code: -22 (Invalid argument)
[vost#0:0/vp9_qsv @ 0x43c74c60d80] Terminating thread with return code -22 (Invalid argument)
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80] Terminating thread with return code 0 (success)
[out#0/mp4 @ 0x43c7412d380] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A    
[AVIOContext @ 0x43c74064140] Statistics: 0 bytes written, 0 seeks, 0 writeouts
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80] Input file #0 (upload/library/admin/2024/2024-03-23/IMG_8039.mov):
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80]   Input stream #0:0 (video): 21 packets read (3560165 bytes); 7 frames decoded; 0 decode errors; 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80]   Input stream #0:1 (audio): 199 packets read (108672 bytes); 
[in#0/mov,mp4,m4a,3gp,3g2,mj2 @ 0x43c7412ce80]   Total: 220 packets (3668837 bytes) demuxed
[AVIOContext @ 0x43c74065680] Statistics: 31958214 bytes read, 311 seeks
```
