### ISSUE TITLE
External images show in gallery, but thumbs, etc not created (possibly due to slow file creation?)

### ISSUE THREAD

**Issue by MWP** [immich-app/immich#18023]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have a large external library that frequently has many images/videos added to it.

When media is added, immich (with "Library watching" enabled) shows the images in the gallery, but they are all shown as "error loading image".
I need to manually run an external library scan job for immich to create the thumbs, do facial recog, etc, etc.

The images/videos are downloaded to the external library from the internet at a relatively slow speed.
Could the problem be due to immich's "library watching" feature attempting to run the jobs on the new files before they have completed being downloaded/written, so are seen as being corrupted?

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - '/pool/media/inet-import:/mnt/media/inet-import'
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: "no"
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./data/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.132.3"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=impass123

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./data/postgres-data

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. immihc with external library watching enabled
2. slowly (ie, 100kb/sec) write large media docs to external library
3. see web view gallery

### Relevant log output

```shell

```
