### ISSUE TITLE
Android app not properly connecting to server

### ISSUE THREAD

**Issue by PMaxx-Gaming** [immich-app/immich#18044]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I can't seem to get the Android app to connect to the server correctly.

It signs in, shows me my library, it seems to be able to upload photos, but won't let me delete any photos.

Also, there is a red circle around my user icon. This happens whether I'm on my local network, or connecting remotely. I've tried connecting through my reverse proxy, as well as using the server address directly, while on my LAN.

I can connect without issue using a web browser on the same device, regardless of whether I'm remote or local - using my reverse proxy, or server IP.

The issue is strictly limited to when I'm using the Android app. Both app and server are up to date.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
     # start_interval: 30s
      start_period: 5m

    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/immich-library
DB_DATA_LOCATION=./postgres
IMMICH_VERSION=release
DB_PASSWORD=(redacted)
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Login with Android app
2. Notice red circle around user icon
3. Be unable to delete any files.
4. Check logs and notice that I haven't been logged in properly
...

### Relevant log output

```shell
#First Error:

Error getting user information from the server [CATCH ALL]

ParallelWaitError(2 errors): ApiException 401:
{"message":"Invalid user token","error":"Unauthorized","statusCode":401,"correlationId":"rsuc3ewa"}

#Second Error:

Unable to login using offline or online methods - Logging out completely

#Third Error:

Error logging out

ApiException 401: {"message":"Invalid user token","error":"Unauthorized","statusCode":401,"correlationIs":"ew2sfwho"}
```

### Additional information

I'm more than willing to add any other information which might be helpful; I'm new to Immich and I'd really like it to work for us, I'm testing it with my photos for now and want to get the hang of it and iron out any wrinkles before I go ahead and move my wife over to it.

I'm 100% sure I'm using the correct user/pass, I've uninstalled/reinstalled the app, cleared cache, data, etc.

Everything works as expected when logging in with a web browser.
