### ISSUE TITLE
Immich is reporting non-existent local images

### ISSUE THREAD

**Issue by Daniel-dev22** [immich-app/immich#18049]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When I open immich the timeline has at least 50 non-existent images.

### The OS that Immich Server is running on

Truenss scale

### Version of Immich Server

1.132.1

### Version of Immich Mobile App

1.132.3 build.197

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ${CURRENT_IMMICH_SERVER_IMAGE}
    devices:
    - /dev/dri/renderD128:/dev/dri
    volumes:
    - /mnt/raid_array/docker_container_volumes/immich_storage:/usr/src/app/upload
    - /etc/localtime:/etc/localtime:ro
    networks:
      traefik-network:
        ipv4_address: 10.0.1.20
      immich-stack-network:
        ipv4_address: 10.0.2.2
    environment:
      UPLOAD_LOCATION: /mnt/raid_array/docker_container_volumes/immich_storage/upload
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
    - redis
    - database
    restart: always
    healthcheck:
      disable: false
    labels:
    - traefik.enable=true
    - traefik.http.routers.immich.rule=Host(`photos.domain.com`)
    - traefik.http.routers.immich.entrypoints=websecure
    - traefik.http.routers.immich.tls=true
    - traefik.http.routers.immich.tls.certresolver=le
    - traefik.http.routers.immich.service=immich
    - traefik.http.services.immich.loadbalancer.server.port=2283
    - traefik.http.routers.immich.middlewares=secured-headers@file
    - traefik.docker.network=traefik-network
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ${CURRENT_IMMICH_MACHINE_LEARNING_IMAGE}
    device_cgroup_rules:
    - c 189:* rmw
    devices:
    - /dev/dri/renderD128:/dev/dri
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.3
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /mnt/fast_storage/docker_container_volumes/immich/model_cache:/cache
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: ${CURRENT_IMMICH_REDIS_IMAGE}
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.4
  database:
    container_name: immich_postgres
    image: ${CURRENT_IMMICH_POSTGRES_IMAGE}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      DB_DATA_LOCATION: /mnt/fast_storage/docker_container_volumes/immich/postgres
    volumes:
    - /mnt/fast_storage/docker_container_volumes/immich/postgres:/var/lib/postgresql/data
    networks:
      immich-stack-network:
        ipv4_address: 10.0.2.5
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}"
        --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures),
        0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user",
      public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
networks:
  traefik-network:
    external: true
  immich-stack-network:
    external: true
```

### Your .env content

```Shell
.
```

### Reproduction steps

1.somehow have non-existent images
2.try to delete them
3.
...

### Relevant log output

```shell
Error loading local image Qv1.png

PlatformException(The getFullFile method has an error: Failed to find asset 1000075603, java.lang.RuntimeException: Failed to find asset 1000075603
	at com.bumptech.glide.c.Z(Unknown Source:7)
	at T2.a.s(Unknown Source:0)
	at com.bumptech.glide.c.Y(Unknown Source:14)
	at T2.a.c(Unknown Source:212)
	at Q2.h.c(Unknown Source:1440)
	at Q2.g.c(Unknown Source:31)
	at B.a.run(Unknown Source:850)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
, {darwinFileType: 0, subtype: 0, id: 1000075603, isOrigin: true}, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370)
<asynchronous suspension>
#2      AssetEntity._getFile (package:photo_manager/src/types/entity.dart:765)
<asynchronous suspension>
#3      ImmichLocalImageProvider._codec (package:immich_mobile/providers/image/immich_local_image_provider.dart:64)
<asynchronous suspension>
#4      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26)
<asynchronous suspension>
```

### Additional information

I'm unable to delete these non existent images either immich throws an error that it couldn't delete the local asset.

![Image](https://github.com/user-attachments/assets/94bc5467-c808-4c8e-998f-3906ebdef24d)
![Image](https://github.com/user-attachments/assets/98191a68-4ea3-48de-809b-167b66a89196)
