### ISSUE TITLE
Error: Input file contains unsupported image format causes immich-server to crash

### ISSUE THREAD

**Issue by arnonm** [immich-app/immich#18059]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Bug is identical symptoms to https://github.com/immich-app/immich/issues/9694 and shows the same in log. However, when I try to run the suggested sql queries, the server crashes

sql -t -U postgres immich -c "select \"originalPath\" FROM assets WHERE id = '31c1ab4f-21e2-4683-b221-8839daf357ec'"
or even
psql -t -U postgres immich -c "select \"originalPath\" FROM assets"

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

networks:
  front-tier:
    name: internet-monitoring-front-tier
    external: true
  back-tier:
    name: internet-monitoring-back-tier
    external: true


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
        #- ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
      - "/mnt/storage/samba/photos:/usr/src/app/originals:rw"
    env_file:
      - .env
    ports:
      - '2283:2283'
      - '2284:2284'
      - '2285:2285'
    expose:
      - 2283
    depends_on:
      - redis
      - database
   restart: always
    networks:
      - back-tier
      - front-tier
    healthcheck:
      disable: false
    labels:
      - homepage.group=Services
      - homepage.name=Immich
      - homepage.icon=immich.png
      - homepage.href=http://xxxxx:2283
      - homepage.description=Photo Server
      - "traefik.enable=true"
      - "traefik.exposedByDefault = true"
      - "traefik.http.routers.immich.rule=Host(`xxx.xxx.xxx`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadbalancer.server.port=2283"
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    ports:
      - '3003:3003'
    restart: always
networks:
      - back-tier
    healthcheck:
      disable: false
    labels:
      - homepage.group=Server Services
      - homepage.name=Immich ML
      - homepage.icon=immich.png
      - homepage.description=Immich ML

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - back-tier
    labels:
      - homepage.group=Server Services
      - homepage.name=Immich Redis
      - homepage.icon=si-redis
      - homepage.description=Immich Redis

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - back-tier
  healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    labels:
      - homepage.group=Databases
      - homepage.name=Immich DB
      - homepage.icon=si-mariadb
      - homepage.description=Immich Database
    deploy:
      resources:
        limits:
          memory: "1G"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
#THUMB_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=xxxxx/xxxxxx

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

IMMICH_TELEMETRY_INCLUDE=all

IMMICH_API_METRICS_PORT=2284
IMMICH_MICROSERVICES_METRICS_PORT=2285
```

### Reproduction steps

1. press missing button for generate thumbnail
2.
3.
...

### Relevant log output

```shell
immich_server            | [Nest] 7  - 05/03/2025, 11:27:58 PM   ERROR [Microservices:{"id":"31c1ab4f-21e2-4683-b221-8839daf357ec"}] Unable to run job handler (thumbnailGeneration/generate-thumbnails): Error: Input file contains unsupported image format
immich_server            | Error: Input file contains unsupported image format
```
