### ISSUE TITLE
Images dont load in web version

### ISSUE THREAD

**Issue by BeeTwenty** [immich-app/immich#18065]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When opening immich in web version all images fails to load.

Workes on mobile

![Image](https://github.com/user-attachments/assets/b00da464-ab74-477a-b9ed-ceb01cb4eb86)
![Image](https://github.com/user-attachments/assets/b2661771-95e9-4fc6-a075-72299a144f36)
![Image](https://github.com/user-attachments/assets/1f0367b9-2340-4dbe-88d3-c2ffd340d3b2)

### The OS that Immich Server is running on

ubuntu 24.04.2

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b5473
4154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:907
24186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
################################################################################
###
# Database
################################################################################
###

# NOTE: The following four database variables support Docker secrets by adding a
 *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https:
//docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=**********
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

################################################################################
###
# Redis
################################################################################
###

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sen
tinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name
":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3
J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im
15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not config
ured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

################################################################################
###
# Upload File Location
#
# This is the location where uploaded files are stored.
################################################################################
###

UPLOAD_LOCATION=/home/beetwenty/immich-app/immich-data


################################################################################
###
# Typesense
################################################################################
###
TYPESENSE_API_KEY=***********
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" }
,
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" }
,
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" }
,
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9
ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5
leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N
0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh
0dHBzIiB9Cl0=

################################################################################
###
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION v
ariable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
################################################################################
####

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

################################################################################
####
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i
>demo@demo.de</i><br>Password: <i>demo</i>"
################################################################################
####

PUBLIC_LOGIN_PAGE_MESSAGE=

################################################################################
####
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services
 on different hosts.
# It will not change which address or port that services bind to within their co
ntainers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
################################################################################
####

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

################################################################################
####
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returne
d to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over
 a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will
continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
################################################################################
####

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

################################################################################
###
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By de
fault,
# the version is "release" but could be a specific version, like "v1.59.0".
################################################################################
###

#IMMICH_VERSION=
IMMICH_AUTH_TYPE=password,oauth
```

### Reproduction steps

1. upload immage
2. open immich web

### Relevant log output

```shell
Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()Understand this error
thumbnail:1 
            
            
           Failed to load resource: the server responded with a status of 404 ()
```
