### ISSUE TITLE
VAAPI H.264 Encoding Fails (SIGABRT in i965 driver) on Intel Haswell GPU (HD 4400) with HEVC Input

### ISSUE THREAD

**Issue by andresichelero** [immich-app/immich#18103]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When Immich attempts to transcode an input video file originally encoded with HEVC (H.265), targeting H.264 output using VAAPI acceleration, the FFmpeg process consistently crashes. The crash occurs after VAAPI has successfully initialized with the correct i965 driver but during the setup or initial processing phase of the h264_vaapi encoder. The crash manifests as a SIGABRT signal received by FFmpeg, originating from an assertion failure within the i965 driver code - `Assertion \obj_surface->fourcc == VA_FOURCC_NV12' failed`.

### Current Behavior:

1. FFmpeg successfully initializes VAAPI using the bundled i965 driver (Intel i965 driver for Intel(R) Haswell - 2.4.0.pre1 () found within /usr/lib/jellyfin-ffmpeg/lib/dri/).
2. The h264_vaapi encoder starts initialization and logs parameters (Profile: High, Entrypoint: EncSlice, RC Mode: CQP, etc.).
3. FFmpeg abruptly terminates due to a SIGABRT signal.
4. The underlying cause is an assertion failure within the i965 driver code: ffmpeg: i965_gpe_utils.c:518: gen7_gpe_set_surface2_state: Assertion 'obj_surface->fourcc == VA_FOURCC_NV12' failed.
5. Immich logs Error occurred during transcoding: ffmpeg was killed with signal SIGABRT and retries the transcode using software encoding (CPU fallback).

### Troubleshooting Done:

- Confirmed host VAAPI setup is correct and functional.
- Confirmed container has /dev/dri mapped and process should have group permissions via group_add.
- Determined that necessary VAAPI components (vainfo, i965_drv_video.so) are missing from the container's standard system paths (/usr/bin, /usr/lib/x86_64-linux-gnu/dri).
- Attempting apt-get install vainfo i965-va-driver inside the container fails due to unmet dependencies (libva2 version conflict), likely caused by mixed Debian stable/testing/sid sources in the base image.
- Discovered that the bundled Jellyfin FFmpeg build does include VAAPI libs/drivers under /usr/lib/jellyfin-ffmpeg/lib/dri/, allowing VAAPI initialization.
- Changed Immich output codec from AV1 (unsupported by HD 4400) to H.264 (supported according to host vainfo).
- Disabled Hardware Decoding, Tone-mapping, and B-Frames in Immich settings; the SIGABRT crash during H.264 encoding persists when the input is HEVC.
- **Tested with H.264 input files and confirmed transcoding works correctly**.
- This issue seems related to #14050, but manifests as a driver assertion failure rather than just inability to initialize device, specifically when encoding H.264 from HEVC input.

Could the bundled VAAPI drivers/libraries within the immich-server image, particularly the i965 driver used by the Jellyfin FFmpeg build, be investigated or updated to resolve this crash on older-but-VAAPI-capable Intel hardware like Haswell? Alternatively, could the base image dependencies be fixed to allow installation of standard Debian bookworm VAAPI packages without conflict?

### The OS that Immich Server is running on

Ubuntu Server 24.04.2 LTS Codename: noble

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

Not used

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    privileged: true
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    group_add:
      - "44"
      - "993"
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/ATLAS/nextcloud/data:/mnt/ATLAS/nextcloud/data:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/ATLAS/immich
DB_DATA_LOCATION=./postgres
TZ=Etc/UTC
IMMICH_VERSION=release
DB_PASSWORD=*******
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Set up Immich v1.132.3 via Docker Compose on a host system with an Intel Haswell generation CPU/GPU (e.g., i3-4170 / HD 4400).
2. Ensure host VAAPI drivers (i965-va-driver, libva, etc.) are correctly installed and vainfo runs successfully on the host. Ensure the user running Docker is in the render group.
3. Configure docker-compose.yml for immich-server using extends: ... service: vaapi and add group_add: with host render/video GIDs.
4. Configure Immich Transcoding Settings via UI as described above (VAAPI, H.264 output, HW Decode Off, Tone-mapping Disabled, B-frames 0).
5. Upload a video file encoded using HEVC (H.265).
6. Observe the immich_server container logs as the transcoding job is processed.

### Relevant log output

```shell
[Nest] 7  - 05/05/2025, 8:41:18 PM   ERROR [Microservices:MediaRepository] ffmpeg version 7.0.2-Jellyfin ... (configuration shown) ...
[AVHWDeviceContext @ 0x42ed414c3c0] libva: VA-API version 1.22.0
[AVHWDeviceContext @ 0x42ed414c3c0] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x42ed414c3c0] libva: /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so init failed
[AVHWDeviceContext @ 0x42ed414c3c0] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/i965_drv_video.so
[AVHWDeviceContext @ 0x42ed414c3c0] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x42ed414c3c0] Initialised VAAPI connection: version 1.22
[AVHWДeviceContext @ 0x42ed414c3c0] VAAPI driver: Intel i965 driver for Intel(R) Haswell - 2.4.0.pre1 ().
... (Input stream info: HEVC input, H.264 output target) ...
Stream mapping:
  Stream #0:1 -> #0:0 (hevc (native) -> h264 (h264_vaapi))
  Stream #0:0 -> #0:1 (aac (native) -> opus (libopus))
...
[h264_vaapi @ 0x42ed4201580] Using input frames context (format vaapi) with h264_vaapi encoder.
[h264_vaapi @ 0x42ed4201580] Input surface format is yuv420p.
[h264_vaapi @ 0x42ed4201580] Using VAAPI profile VAProfileH264High (7).
[h264_vaapi @ 0x42ed4201580] Using VAAPI entrypoint VAEntrypointEncSlice (6).
[h264_vaapi @ 0x42ed4201580] Using VAAPI render target format YUV420 (0x1).
[h264_vaapi @ 0x42ed4201580] RC mode: CQP.
... (other parameters) ...
ffmpeg: i965_gpe_utils.c:518: gen7_gpe_set_surface2_state: Assertion `obj_surface->fourcc == VA_FOURCC_NV12' failed.

[Nest] 7  - 05/05/2025, 8:41:18 PM   ERROR [Microservices:MediaService] Error occurred during transcoding: ffmpeg was killed with signal SIGABRT
[Nest] 7  - 05/05/2025, 8:41:18 PM   ERROR [Microservices:MediaService] Retrying with VAAPI acceleration disabled
```

### Hardware and Software info:
- Host CPU: Intel Core i3-4170 (Haswell architecture)
- Host GPU: Integrated Intel HD Graphics 4400 (HSW GT2)
- Host Kernel: 6.8.0-59-generic
- Host VAAPI Status:
- **vainfo** on host runs successfully.
- Loads Intel i965 driver for Intel(R) Haswell - 2.4.1.
- Reports support for VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice, VAProfileH264Main: VAEntrypointEncSlice, VAProfileH264High: VAEntrypointEncSlice.   
- Host User Permissions: User running docker compose is confirmed member of the render group (and video). Checked via groups and ls -l /dev/dri.
- Container Image Tested: ghcr.io/immich-app/immich-server:v1.132.3
- FFmpeg Version (Inside Container): 7.0.2-Jellyfin (from Immich logs)
- hwaccel.transcoding.yml: Confirmed to contain the standard vaapi: service definition with devices: ['/dev/dri:/dev/dri'].
###  Immich Transcoding Settings (Admin UI):
- Acceleration API: VAAPI
- Hardware decoding: Off
- Video codec (Output): h264
- Audio codec: opus
- Target resolution: original
- Constant rate factor (-crf): 25
- Preset (-preset): fast
- Tone-mapping: Disabled
- Maximum B-frames: 0
- (Other settings at default)
