### ISSUE TITLE
Immich iOS App does not delete in photos / move to trash

### ISSUE THREAD

**Issue by Buddinski88** [immich-app/immich#18132]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I am trying to delete a photo via the iOS app. Until recently, a dialog was always displayed stating that the image will be moved to the trash within Photos and can be restored there within 30 days.
Now the photo is deleted in Immich but not moved to the trash within Photos.

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

1,132.3 build.205

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - local.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - local.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
  library:
    driver: local
    driver_opts:
        type: nfs
        o: "nfsvers=4,addr=${NASIP},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
        device: ":${NASPATH02}/immich-app"
```

### Your .env content

```Shell
local.env

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=***

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

global.env

# NAS specific
NASIP=10.***
NASPATH02=/mnt/fast-data-pool/***
```

### Reproduction steps

1. Open the iOS App
2. Select a photo and delete it
3. Normally a dialog is displayed that the image is also moved to the trash within Photos

### Relevant log output

```shell
# server log

[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/assets, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id, DELETE} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/tags/:id/assets, DELETE} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RoutesResolver] TimelineController {/api/timeline}:
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/buckets, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/timeline/bucket, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RoutesResolver] TrashController {/api/trash}:
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/empty, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/trash/restore/assets, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RoutesResolver] UserAdminController {/api/admin/users}:
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id, DELETE} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/preferences, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/admin/users/:id/restore, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RoutesResolver] UserController {/api/users}:
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/preferences, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, PUT} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/me/license, DELETE} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, POST} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/profile-image, DELETE} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/users/:id/profile-image, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RoutesResolver] ViewController {/api/view}:
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder/unique-paths, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:RouterExplorer] Mapped {/api/view/folder, GET} route
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:NestApplication] Nest application successfully started
[Nest] 16  - 05/06/2025, 8:00:28 PM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.132.3] [production] 
[Nest] 16  - 05/06/2025, 8:00:30 PM     LOG [Api:EventRepository] Websocket Connect:    UlF0fYWTQrLZEXtMAAAB
[Nest] 16  - 05/06/2025, 8:04:36 PM     LOG [Api:EventRepository] Websocket Connect:    Nr2zF5CK_FdDzHgsAAAD
[Nest] 16  - 05/06/2025, 8:05:16 PM     LOG [Api:EventRepository] Websocket Disconnect: Nr2zF5CK_FdDzHgsAAAD

# app log
2025-05-06 20:04:52.811869 | fine     | HashService          | Hashed 10/24 assets |
2025-05-06 20:04:52.805873 | warning  | HashService          | Failed to hash file 30F4C933-791D-4AFD-A15C-D386FF2D9E34/L0/001 |
2025-05-06 20:04:52.805871 | warning  | HashService          | Failed to hash file 308F283C-6995-4161-B9A8-2A1949994FD0/L0/001 |
2025-05-06 20:04:52.805869 | warning  | HashService          | Failed to hash file 30735661-8D90-4249-B3A0-726C110B0C7B/L0/001 |
2025-05-06 20:04:52.805866 | warning  | HashService          | Failed to hash file 3071F280-B5E5-40C2-ABDF-1EEDCE6E0CBE/L0/001 |
2025-05-06 20:04:52.805863 | warning  | HashService          | Failed to hash file 302FA2D9-D4BF-4D0D-8A84-2F203ADCC2EC/L0/001 |
2025-05-06 20:04:52.805860 | warning  | HashService          | Failed to hash file 301C9D39-AD9E-477B-BB74-0601A4A1927A/L0/001 |
2025-05-06 20:04:52.805856 | warning  | HashService          | Failed to hash file 2FF6CF36-7E66-4B9E-8611-A941AF581309/L0/001 |
2025-05-06 20:04:52.805853 | warning  | HashService          | Failed to hash file 2F6D973F-705A-40A1-A3AE-749A682ACA1B/L0/001 |
2025-05-06 20:04:52.805851 | warning  | HashService          | Failed to hash file 2F5B6728-B936-4C49-8007-0AD9A6C86124/L0/001 |
2025-05-06 20:04:52.805849 | warning  | HashService          | Failed to hash file 2F583C9B-9300-4AC2-AFBD-9327515F97C3/L0/001 |
2025-05-06 20:04:52.805847 | warning  | HashService          | Failed to hash file 2F53FC09-FE4A-40EA-B614-4C8065DB449E/L0/001 |
2025-05-06 20:04:52.805844 | warning  | HashService          | Failed to hash file 2F33A705-C464-4FEA-AA85-3DE1F47722FE/L0/001 |
2025-05-06 20:04:52.805841 | warning  | HashService          | Failed to hash file 2EFCA984-A7CB-4DF9-99F6-5E507C18ED2F/L0/001 |
2025-05-06 20:04:52.805828 | warning  | HashService          | Failed to hash file 2EF4A957-503A-426F-86F5-C499600B422B/L0/001 |
2025-05-06 20:04:52.146135 | info     | HashService          | Hashing 24 files |
2025-05-06 20:04:42.900054 | fine     | socket_io_client:engine.Socket | socket receive: type "message", data "2["on_asset_trash",["a1eb4cb9-03a0-4ec1-8132-e0ed0cce9890"]]" |
2025-05-06 20:04:37.099495 | warning  | HashService          | Error getting file to hash for asset 312C63B8-2854-4360-AE27-01945BC0DE67/L0/001, name: IMG_2059.MOV, created on: 2022-01-11 18:28:45.000, skipping | PlatformException(PHPhotosErrorDomain (-1), Der Vorgang konnte nicht abgeschlossen werden. (PHPhotosErrorDomain-Fehler -1.), No failure reason provided, null) |
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370)
<asynchronous suspension>
#2      AssetEntity._getFile (package:photo_manager/src/types/entity.dart:765)
<asynchronous suspension>
#3      HashService._tryGetAssetFile (package:immich_mobile/services/hash.service.dart:110)
<asynchronous suspension>
#4      HashService.hashAssets (package:immich_mobile/services/hash.service.dart:71)
<asynchronous suspension>
#5      SyncService._addAlbumFromDevice (package:immich_mobile/services/sync.service.dart:766)
<asynchronous suspension>
#6      diffSortedLists (package:immich_mobile/utils/diff.dart:34)
<asynchronous suspension>
#7      SyncService._syncLocalAlbumAssetsToDb (package:immich_mobile/services/sync.service.dart:566)
<asynchronous suspension>
#8      AsyncMutex.run.<anonymous closure> (package:immich_mobile/utils/async_mutex.dart:15)
<asynchronous suspension>
```

### Additional information

I am using an iPhone 16 Pro with the latest iOS Beta 18.5 (22F5068a).
