### ISSUE TITLE
Custom Postgres password not accepted on first start

### ISSUE THREAD

**Issue by jwiesel** [immich-app/immich#18162]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi, thanks for providing this great tool!
I just started setting it up using docker compose.

I changed the default password to one with 20 characters [A-Za-z0-9] without special characters.
Unfortunately, the immich_server continues to restart due to an issue that the microservices couldn't connect to postgres (see logs)

I started over by deleting the postgres files and switched to the default password ("postgres"). Then the stack comes up correctly.
I can even stop the stack, change the postgres password to a custom one and successfully start the stack again afterwards. So it seems like the db_password from the .env-file is only used on initialization but not during future restarts.

### The OS that Immich Server is running on

Debian / Openmediavault

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

not yet used

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-d913755a-65ad-4e9a-9d9f-04a825426e8b/shared/photo:/mnt/media/HomeServer:ro
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model_cache:/cache
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: unless-stopped

volumes:
  model_cache:
  postgres_data:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-uuid-d913755a-65ad-4e9a-9d9f-04a825426e8b/shared/immich

# The location where your database files are stored. Network shares are not supported for the database
# DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=Ak9fRGDWCbvbqP30Iaag

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create a new stack (compose + env)
2. Set a custom DB_PASSWORD in .env file
3. Start the stack (docker compse up) and check the logs
...

### Relevant log output

```shell
immich_server            | Initializing Immich v1.132.3
immich_server            | Detected CPU Cores: 4
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 05/08/2025, 3:42:40 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | microservices worker error: PostgresError: password authentication failed for user "postgres", stack: PostgresError: password authentication failed for user "postgres"
immich_server            |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |     at Socket.emit (node:events:518:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
```

**Comment by mmomjian** [comment]
"seems like the db_password from the .env-file is only used on initialization but not during future restarts"

This is correct. Postgres password is only set when the database is initialized. After first start, you need to also change the password within the DB cluster: https://immich.app/docs/guides/database-queries/#postgres-internal

**Comment by jwiesel** [comment]
Thanks for your swift response @mmomjian !

In that case the install documentation is not very clear. It only says: 

> Consider changing DB_PASSWORD to a custom value. Postgres is not publicly exposed, so this password is only used for local authentication. To avoid issues with Docker parsing this value, it is best to use only the characters A-Za-z0-9. pwgen is a handy utility for this.

If a user needs to use the default password first and then change the password in the DB and in the compose file later, that is very complicated and should be communicated to avoid future issues for new beginners.

**Comment by mmomjian** [comment]
You don’t need to use the default first. You just need to set the PW before first start. That’s why we have that note is before the Step 3, start containers

However you can open a PR with your proposed changes if you think it needs clarification

**Comment by jwiesel** [comment]
Maybe my explanation in the ticket was not clear.

I changed the password before the first start of the stack. That does not work.
The initialization only works, if the default password is used.

**Comment by mmomjian** [comment]
That doesn't sound correct. It's most likely that the database files were still remaining from the first time you started it. If that is the case, the database will be reused instead of recreated. On a true fresh start, the database password is taken from the .env

**Comment by jwiesel** [comment]
Alright. Up to you.

I reported the issue and will work with the default password for now.
Maybe someone else will report the issue again.

**Comment by mmomjian** [comment]
Not sure how familiar you are with Bash but our own install script sets a random PW before first start. I’ve never heard of anyone else having this issue tbh

**Comment by hypochris** [comment]
I am having the same error message, but I have been unable to resolve it the past few days. Changing the password to the default 'postgres' does not resolve the issue for me either.

I have re-installed the stack, done 'docker system prune' and removed all volumes countless times, but I cannot get the postgres db to initialize.

Any help would be greatly appreciated, I'm at the end of my wits.

**Comment by jwiesel** [comment]
Hi @hypochris ,
for me it helped to delete all files in the folder defined as DB_DATA_LOCATION. In the default .env file that's a local folder in your host PC. Try deleting that folder and recreate it.
I think Docker prune does not touch contents of folders mounted from the host.

**Comment by hypochris** [comment]
Thanks for your suggestion, but I tried this too. I deleted both storage locations for the files and for the database.

**Comment by corbeil** [comment]
I had the same problem as jwiesel with the password but i found the cause for me.

```
    env_file:
      - .env
```
was missing from immich-server app config and immich-machine-learning. @jwiesel looks like you miss them too.

**Comment by NikeLaosClericus** [comment]
Using Portainer, I had to explicitly set the DB_PASSWORD for the immich-server service:

```
    container_name: immich_server
...
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
...
```
Apparently, importing the .env file into the stack does not pass those to the containers without explicit direction.

**Comment by HegewaldK** [comment]
Thanks @NikeLaosClericus I had the same issue. I use Portainer on a Synology NAS and I changed the database user and password for the DB in the env file but every time immich-server showed the same error message `password authentication failed for user "postgres"` which was weird because I already changed the DB user "postgres" to a different name. 

This means the immich-server container has it's own default DB connection setting which is not mentioned in the default yml. I've now changed the docker compose yml to set the database settings for immich-server as well:

```yml
services:
  immich-server:
    container_name: immich_server
    ...
    environment:
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ...
```
