### ISSUE TITLE
Doco Needs Updating

### ISSUE THREAD

**Issue by blakeusblade** [immich-app/immich#18172]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

As of 2025-05-09 Immich Version: 1.132.3 running in docker

Documentation mentioned here
[Storage Templates](https://immich.app/docs/administration/backup-and-restore/#asset-types-and-storage-locations)

The below statement is correct from the link above
> Storage Template Off
> Source Assets:
> Original assets uploaded through the browser interface & mobile & CLI.
> Stored in UPLOAD_LOCATION/upload/<userID>.

The below statement is incorrect from the link above.
> Storage Template On
> Source Assets:
> Original assets uploaded through the browser interface, mobile, and CLI.
> Stored in UPLOAD_LOCATION/library/<userID>.

I've been migrating over and over my photo library, destroying the immich containers and starting the migration from scratch again and again. I've witenssed  many times uploading goes to the upload directory and then storage template migration engine/task migrates it to the library directory.

I think it would benefit people to have it documented that if your migrating a large amount of assets to immich, that it be done with storage templates turned off. Then at a latter stage if you want or need it, turn it on/back on and let that migration process be completed seperately to the massive import process.
or
Have immich do exactly as the documentation says, uploads directly into the library directory.

### The OS that Immich Server is running on

Synology Docker 

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1034:100
    environment:
      - TZ=Australia/Sydney
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Australia/Sydney
      - POSTGRES_DB=REMOVED_FOR_OBVIOUS_REASONS
      - POSTGRES_USER=REMOVED_FOR_OBVIOUS_REASONS
      - POSTGRES_PASSWORD=REMOVED_FOR_OBVIOUS_REASONS
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    cpu_shares: 256
    user: 1034:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/thumbs:/usr/src/app/upload/thumbs:rw
      - /volume2/docker_extra/immich/upload:/usr/src/app/upload/upload:rw
      - /volume2/docker_extra/immich/profile:/usr/src/app/upload/profile:rw
      - /volume2/docker_extra/immich/library:/usr/src/app/upload/library:rw
      - /volume2/docker_extra/immich/backups:/usr/src/app/upload/backups:rw
      - /volume2/docker_extra/immich/encoded-video:/usr/src/app/upload/encoded-video:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    cpu_shares: 256
    user: 1034:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/thumbs:/usr/src/app/upload/thumbs:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Australia/Sydney
DB_HOSTNAME=immich-db
DB_USERNAME=REMOVED_FOR_OBVIOUS_REASONS
DB_PASSWORD=REMOVED_FOR_OBVIOUS_REASONS
DB_DATABASE_NAME=REMOVED_FOR_OBVIOUS_REASONS
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=REMOVED_FOR_OBVIOUS_REASONS
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1. Setup a fresh instance of immich
2. create local admin
3. turn on storage templates
4. create a new user
5. login to immich with user created in step4
6. create api key to use with immich cli
7. login using immich cli tool using the api key from step6
8. Use immich cli to upload assets
9. while uploading is going on, observe where the files are uploading to on the file system.
10. while uploading is going on, observe the storage template engine/task processing the incomming images and moving them into the library directory.

### Relevant log output

```shell

```

### Additional information

It might be nice to have a good migration guide and or things to think about page when migrating a large amount of assets to immich. This coud include keeping storage template engine/migration off until all process are complete.
