### ISSUE TITLE
Live photos do not work in FIREFOX - Edge seems to be working

### ISSUE THREAD

**Issue by steveredden** [immich-app/immich#18202]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Every time hovering over a live photo in the web ui on Firefox I get:

Console:
![Image](https://github.com/user-attachments/assets/6fd756d6-9251-46e7-969b-97151174d3ca)
`Invalid URI. Load of media resource  failed.`

Network call:
`https://immich.tld/api/assets/96423c74-3e73-4cd8-9791-d83f151ad452/video/playback?c=W+gNFYKKiHefhniMh8iHa8ZgdHBn` gives `206` HTTP code

The same does not occur in Microsoft Edge, nor the iOS app.

### The OS that Immich Server is running on

Ubuntu 22.04.5

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.32.3 build.205

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v1.132.3
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
      - backend
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.132.3
    env_file:
      - .env
    volumes:
      - model-cache:/cache
    restart: unless-stopped
    networks:
      - backend

  redis:
    container_name: immich-redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:4a9f847af90037d59b34cd4d4ad14c6e055f46540cf4ff757aaafb266060fa28
    env_file:
      - .env
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - backend

  database:
    container_name: immich-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_DATABASE_NAME}"
      - "POSTGRES_INITDB_ARGS='--data-checksums'"
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
	  
volumes:
  model-cache:
  redis:
  database:

networks:
  frontend:
    external: true
  backend:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/nfs/immich01
DB_DATA_LOCATION=database
DB_HOSTNAME=immich-postgres
DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD=REDACTED
REDIS_HOSTNAME=immich-redis
TZ=America/Chicago
```

### Reproduction steps

Hover, and observe nothing happens:

![Image](https://github.com/user-attachments/assets/f5708466-578f-4838-a5c0-464e141c8694)

### Additional information

Doesn't work on my Firefox...

Using the iOS app, or Microsoft Edge the live photos still work
