### ISSUE TITLE
Still Multiple Memories at top after SQL Command

### ISSUE THREAD

**Issue by RogerSik** [immich-app/immich#18215]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

![Image](https://github.com/user-attachments/assets/9a2606fe-6ba5-4db7-8654-21d0bafd58e7)

I have immich running with 1.132.3 and get the multiple memories issue. 

The solution is to execute
```
psql --dbname=app --username=postgres -c "delete from system_metadata where key like 'memories-state'; truncate table memories cascade;"
```
and regerante the memories. But tomorrow this issue will appear again.

### The OS that Immich Server is running on

Talos Linux 1.9.5

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: immich-server
  namespace: immich
  annotations:
    reloader.stakater.com/auto: 'true'
  labels:
    app: immich-server
spec:
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      automountServiceAccountToken: false
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.132.3 # {"$imagepolicy": "immich:immich-server"}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 2Gi
              cpu: 1000m
          env:
            - name: DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db-app
                  key: host
                  optional: false
            - name: DB_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: immich-db-app
                  key: dbname
                  optional: false
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: immich-db-app
                  key: username
                  optional: false
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-app
                  key: password
                  optional: false
          envFrom:
            - configMapRef:
                name: immich
                optional: false
          livenessProbe:
            httpGet:
              path: /api/server/ping
              port: 2283
            failureThreshold: 6
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/server/ping
              port: 2283
            failureThreshold: 6
            periodSeconds: 10
          securityContext:
            privileged: true # for intel quick sync
          volumeMounts:
            - name: immich-server
              mountPath: /usr/src/app/upload/
            - name: immich-hdd-upload
              mountPath: /usr/src/app/upload/upload/
      nodeSelector:
        cloud: home
        intel.feature.node.kubernetes.io/gpu: 'true'
      volumes:
        - name: immich-server
          nfs:
            server: '192.168.0.10'
            path: /volume1/k8s-nfs-ssd/immich/immich-server/
        - name: immich-hdd-upload
          nfs:
            server: '192.168.0.10'
            path: /volume2/k8s-nfs-hdd/immich/immich-upload/
```

### Your .env content

```Shell
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  namespace: immich
  labels:
    app: immich
data:
  # https://immich.app/docs/install/environment-variables/
  TZ: 'Europe/Berlin'
  REDIS_HOSTNAME: 'immich-redis-master'
  IMMICH_TELEMETRY_INCLUDE : 'all'
```

### Reproduction steps

1. Delete Memories
2. Wait a day or two
3. Issue arrives again

### Relevant log output

```shell

```

### Additional information

I have running this on a Kubernetes Cluster but the setup itself is working fine. This issues don't always appeared. I also had days where it was fine. Some cache from earlier bug which is still active?
