### ISSUE TITLE
Bad Performance Adding an asset to an album syncs all albums

### ISSUE THREAD

**Issue by OberstVonGatow** [immich-app/immich#18237]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When i add an image to an album with the android app the app freezes for 10-15 secs. After that everything works fast again. When i look in the logs i see that every (online) album is getting synced. I don't see a reason why every album should be synced after adding.

### The OS that Immich Server is running on

Docker on Proxmox LXC

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3 build.197

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the stack.env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the stack.env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/ssd/immich-app/library
DB_DATA_LOCATION=/mnt/ssd/immich-app/postgres
TZ=Europe/Berlin
IMMICH_VERSION=release
DB_PASSWORD=******
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Create 190 albums with 44000 images and 600 videos
2. In the Android App open one image and add it to any album (only 10 images in the target album)
3. After the image is added the App freezes for 10-20 seconds and you can't swipe to other images anymore

### Relevant log output

```shell
Instead of "albumname" there are all the different album names from the server (not on the device). 

2025-05-12 23:45:59.090412 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:58.754399 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:58.344347 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:58.041126 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:57.718350 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:57.276598 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
2025-05-12 23:45:56.837183 | info     | SyncService          | Synced changes of remote album "albumname" to DB |
```
