### ISSUE TITLE
[BUG] Opening a photo in the web will reset the album associated with the photo

### ISSUE THREAD

**Issue by jbalcao** [immich-app/immich#1826]
### The bug

Opening a photo in the web will reset the album associated with the photo. The album will retain only 1 photo that was opened recently.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.48

### Version of Immich Mobile App

v1.48

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - /mnt/sda/srv/immich/upload:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Singapore
      - IMMICH_MACHINE_LEARNING_URL=false
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /mnt/sda/srv/immich/upload:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - IMMICH_MACHINE_LEARNING_URL=false
    depends_on:
      - redis
      - database
    restart: always


  immich-web:
    image: altran1502/immich-web:release
    container_name: immich_web
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:7
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:15
    env_file:
      - .env
    environment:
    #  POSTGRES_PASSWORD: ${DB_PASSWORD}
    #  POSTGRES_USER: ${DB_USERNAME}
    #  POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /srv/immich/pgdata:/var/lib/postgresql/data
    restart: always


  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release

    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=
DB_PASSWORD=
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/srv/immich/upload
JWT_SECRET=
ENABLE_MAPBOX=false
```

### Reproduction steps

```bash
1. Under the photos tab in web app, open a photo that is assigned to an album with already many photos on it.
2. Open the album, then it will only show one photo, which was the photo you opened recently.
```
