### ISSUE TITLE
[web] image viewer skipping images when quickly viewing images

### ISSUE THREAD

**Issue by Ingegneus** [immich-app/immich#18281]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

in the web app when I open photos and use the arrow keys to go to the next/prev ones, it sometimes skips an image or adds an additional arrow press.

### The OS that Immich Server is running on

Ubuntu 24 LTS

### Version of Immich Server

v132.3

### Version of Immich Mobile App

v132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  database:
    cpu_shares: 90
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    container_name: immich-postgres
    deploy:
      resources:
        limits:
          memory: 3758M
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    hostname: immich-postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready --dbname='immich' --username='postgres' || exit 1;
          Chksum="$(psql --dbname='immich' --username='postgres' --tuples-only
          --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
          pg_stat_database')"; echo "checksum failure count is "; [ "" = '0' ]
          || exit 1
      interval: 5m0s
      start_period: 5m0s
      start_interval: 30s
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/pgdata
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    networks:
      - immich
    privileged: false
  immich-machine-learning:
    cpu_shares: 90
    container_name: immich-machine-learning
    deploy:
      resources:
        limits:
          memory: 3758M
    environment:
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
    hostname: immich-machine-learning
    healthcheck: {}
    image: altran1502/immich-machine-learning:release
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/model-cache
        target: /cache
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    networks:
      - immich
    privileged: false
  immich-server:
    cpu_shares: 90
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 3758M
        reservations:
          memory: "1073741824"
    environment:
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
    hostname: immich-server
    healthcheck: {}
    image: altran1502/immich-server:release
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
    ports:
      - mode: ingress
        target: 2283
        published: "2283"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Gallery/immich
        target: /usr/src/app/upload
        bind:
          create_host_path: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    command: []
    networks:
      - immich
    privileged: false
  redis:
    cpu_shares: 90
    container_name: immich-redis
    deploy:
      resources:
        limits:
          memory: 3758M
    hostname: immich-redis
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/immich/redis
        target: /data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    environment: []
    networks:
      - immich
    privileged: false
networks:
  immich:
    name: immich
x-casaos:
  architectures:
    - amd64
    - arm64
  author: Cp0204
  category: Gallery
  description:
    en_us: >
      ## Immich: Revolutionizing Your Home Media Experience


      Immich is here to transform the way you manage and enjoy your media files across your home TV, smartphones, and other devices. Unlike traditional photo albums or mainstream cloud services, immich offers a seamless and modern platform for organizing, sharing, and accessing your photos and videos. Imagine effortlessly backing up your precious moments from your mobile devices and viewing them instantly on your TV or sharing them with family members—immich makes it all possible.


      immich stands out with its automatic backup from mobile devices, a sleek web-based interface for easy media browsing, and advanced features like face recognition and object detection. You can organize your media by location, enjoy 4K video playback, and even manage RAW photos. Plus, with multi-user support, sharing memories with friends and family is a breeze. The best part? Immich offers these powerful features for low cost, ensuring you get a premium experience without breaking the bank.


      Deploying immich on a private cloud device like Zima brings unparalleled convenience. Enjoy unlimited storage capacity, blazing-fast local network speeds, and easy multi-device access. With immich on your Zima private cloud, your media is always at your fingertips, safe and secure in your home.
    zh_cn: >
      ## Immich：革新您的家庭媒体体验


      Immich 来了，它将彻底改变您在家庭电视、智能手机和其他设备上管理和享受媒体文件的方式。与传统相册或主流云服务不同，Immich 提供了一个无缝且现代化的平台，用于组织、分享和访问您的照片和视频。想象一下，轻松地从移动设备备份珍贵时刻，并立即在电视上观看或与家人分享——Immich 让这一切成为可能。


      Immich 以其从移动设备自动备份、时尚的网页界面方便浏览媒体，以及面部识别和物体检测等高级功能而脱颖而出。您可以按位置组织媒体，欣赏 4K 视频播放，甚至管理 RAW 格式照片。此外，多用户支持功能使与朋友和家人分享记忆变得轻而易举。最棒的是，Immich 以低成本提供这些强大的功能，确保您获得高级体验而不会花费太多。


      在像 Zima 这样的私有云设备上部署 Immich 带来了无与伦比的便利。享受无限存储容量、极快的本地网络速度和轻松的多设备访问。通过在 Zima 私有云上使用 Immich，您的媒体始终触手可及，安全可靠地存储在您的家中。
  developer: alextran1502
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/icon.png
  index: /
  is_uncontrolled: true
  main: immich-server
  port_map: "2283"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/screenshot-3.png
  store_app_id: immich
  tagline:
    en_us: Self-hosted media management solution
    zh_cn: 自托管媒体管理解决方案
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Immich/thumbnail.png
  tips:
    before_install:
      en_us: >
        ⚠️ The project is under very active development.

        ⚠️ Expect bugs and breaking changes.

        ⚠️ Do not use the app as the only way to store your photos and videos.

        ⚠️ Always follow 3-2-1 backup plan for your precious photos and videos!


        ## Authorized Media Files and Data

        1. Click on the settings icon in the upper right corner of the App.

        2. In the immich-server tab, map your album storage location in the Volumes section (default is `/DATA/Gallery/immich`).


        For complete project documentation and installation instructions, please [refer to](https://immich.app).
      zh_cn: >
        ⚠️ 本项目正在 非常活跃 地开发中。

        ⚠️ 可能存在 bug 或者随时有重大变更。

        ⚠️ 不要把本软件作为您存储照片或视频的唯一方式。

        ⚠️ 为了您宝贵的照片与视频，请始终遵守 3-2-1 备份方案！


        ## 授权媒体文件和数据

        1. 点击 App 图标右上角的设置

        2. 在 immich-server 选项卡 Volumes 栏目中映射您的相册储存位置（默认为 `/DATA/Gallery/immich ` ）。


        完整的项目文档以及安装教程请[参见](https://immich.app)。
  title:
    custom: ""
    en_us: Immich
```

### Your .env content

```Shell
I use casaOS so idk were that would be
```

### Reproduction steps

example:
images in gallery view: img1  img2  img3  img4  img5

I open img3 and navigate with the arrow keys: →, →, ←, ←, but then I land on img2 instead of img3  

### Relevant log output

```shell

```
