### ISSUE TITLE
People search inconsistency

### ISSUE THREAD

**Issue by protobock** [immich-app/immich#18305]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On the web interface, when I use the "People" tab on the left menu and then the "Search people" feature, I do not get the same result than when I use the "Search options / Filter people" feature.
For instance, when I search for "claude" via the "People" tab, I get a list of 8 people whose first name **begins** with claude. That seems to be pretty correct.
When I search for "claude" via the "Search options / Filter people" feature I only get a list of 3 people. Among these 3 people, one is named Jean-Claude (and it is not listed by the "Search options / Filter people" feature).
In summary:
"People Tab / Search people" finds all people whose name begins with the search string but not those whose name contains the search string.
"Search options / Filter people" misses most people (which makes this feature useless) but can find the search string even if  it is not at the beginning of the name (which is a feature I like).
In the Android mobile app, only the "Search / Filter people" is present with it's partial results.

### The OS that Immich Server is running on

Debian LXC on proxmox

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

 
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich_library_145_nfs

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=*************
DB_DATABASE_NAME=*************

REDIS_HOSTNAME=immich_redis

#
```

### Reproduction steps

On the web interface
1. People Tab
2. Search people
Or
1. Search Options
2. Filter people

On the Android app
1. Search
2. People
3. Filter People

### Relevant log output

```shell

```
