### ISSUE TITLE
[BUG] Update to v1.48.1 fails due to failed migration

### ISSUE THREAD

**Issue by cmintey** [immich-app/immich#1836]
### The bug

Updating from v1.47.3 to v1.48.1 results in the server not being able to start. 

```sh
immich_server         | Migration "FixAssetRelations1676680127415" failed, error: insert or update on table "assets" violates foreign key constraint "FK_16294b83fa8c0149719a1f631ef"
immich_server         | [Nest] 1  - 02/22/2023, 5:37:12 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
immich_server         | QueryFailedError: insert or update on table "assets" violates foreign key constraint "FK_16294b83fa8c0149719a1f631ef"
immich_server         |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich_server         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
immich_server         |     at async FixAssetRelations1676680127415.up (/usr/src/app/dist/apps/immich/libs/infra/src/db/migrations/1676680127415-FixAssetRelations.js:15:9)
immich_server         |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:223:17)
immich_server         |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:249:35)
immich_server         |     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:137:17)
```

```sh
immich_postgres       | 2023-02-22 17:37:16.414 UTC [39] ERROR:  insert or update on table "assets" violates foreign key constraint "FK_16294b83fa8c0149719a1f631ef"
immich_postgres       | 2023-02-22 17:37:16.414 UTC [39] DETAIL:  Key (livePhotoVideoId)=(111f65b7-962e-46be-962f-b78b577c4da3) is not present in table "assets".
immich_postgres       | 2023-02-22 17:37:16.414 UTC [39] STATEMENT:  ALTER TABLE "assets" ADD CONSTRAINT "FK_16294b83fa8c0149719a1f631ef" FOREIGN KEY ("livePhotoVideoId") REFERENCES "assets"("id") ON DELETE SET NULL ON UPDATE CASCADE
```

### The OS that Immich Server is running on

Ubuntu 22.04 LTS, arm64

### Version of Immich Server

v1.48.1

### Version of Immich Mobile App

v1.48.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:v1.48.1
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:v1.48.1
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:v1.48.1
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:v1.48.1
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<REDACTED>
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=./data

PUBLIC_LOGIN_PAGE_MESSAGE=

IMMICH_WEB_URL=http://immich_web:3000
IMMICH_SERVER_URL=http://immich_server:3001
```

### Reproduction steps

```bash
1. Update to v1.48.1
2. Unable to connect to app via web or app
3. Checked the logs and saw migration error
```
