### ISSUE TITLE
[BUG] Crash Loop with pgvecto.rs: IPC connection is closed unexpected After Migrating Data from macOS to Windows/WSL2

### ISSUE THREAD

**Issue by euisuh** [immich-app/immich#18369]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

## Bug Description:
After successfully migrating my Immich library and PostgreSQL data (including `pgvecto.rs` data) from a macOS environment to a Windows 11/10 environment using WSL 2, Immich (v1.132.3) services (specifically `immich-server` and/or `immich-microservices`) are stuck in a continuous restart loop. The primary error seems to be `PostgresError: pgvecto.rs: IPC connection is closed unexpected`. This prevents the UI from becoming accessible, making it impossible to use application-level tools for rescan or repair.

Initial PostgreSQL permission errors after migrating the data volume were resolved by moving the PostgreSQL data to the native WSL 2 filesystem and applying `sudo chown -R 999:999` to the data directory. However, this `pgvecto.rs` issue persists. The main PostgreSQL container logs (docker logs `immich_postgres`) do not show any obvious errors at the time this IPC error occurs in the application logs.

### Expected Behavior:
Immich services should start successfully and the application should be usable after migrating data and resolving initial PostgreSQL permissions. If vector data is problematic, the application should ideally provide a path to recovery or re-indexing, even if other parts of the UI are initially limited.

### Actual Behavior:
Immich application services are in a restart loop due to the pgvecto.rs IPC error, making the application completely inaccessible.

### The OS that Immich Server is running on

Windows 11 with WSL 2 (Ubuntu)

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.0.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/d/98_photo:/mnt/media/photo
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=/home/euisuh/docker/immich-postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Ran Immich successfully on macOS.
2. Copied the Immich library files and the entire PostgreSQL data volume to a new Windows machine.
3. Set up Immich on the Windows machine using Docker Desktop with the WSL 2 backend.
4. Initially encountered PostgreSQL permission errors related to the data volume.
5. Resolved permission errors by:
     - Stopping Immich.
     - Moving the PostgreSQL data directory (specified by DB_DATA_LOCATION in .env) to a path within the native WSL 2 filesystem (e.g., /home/mywsluser/immich_postgres_data).
     - Running sudo chown -R 999:999 on this directory.
     - Updating DB_DATA_LOCATION in the .env file to the new absolute path on the WSL 2 filesystem.
6. Upon restarting Immich, PostgreSQL starts and appears to run, but the application services that connect to it enter a restart loop, logging the pgvecto.rs error.

### Relevant log output

```shell
Initializing Immich v1.132.3
Detected CPU Cores: 16
Starting api worker
Starting microservices worker
[Nest] 7  - 05/19/2025, 10:54:49 AM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 19  - 05/19/2025, 10:54:49 AM     LOG [Api:EventRepository] Initialized websocket server
Query failed : {
  durationMs: 15007.531789,
  error: PostgresError: pgvecto.rs: IPC connection is closed unexpected.
  ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
[Nest] 7  - 05/19/2025, 10:55:04 AM    WARN [Microservices:DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: 'XX000',
    file: 'error.rs',
    line: '7'
  },
  sql: 'SELECT idx_status FROM pg_vector_index_stat WHERE indexname = $1',
  params: [ 'clip_index' ]
}
PostgresError: pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: 'XX000',
  file: 'error.rs',
  line: '7'
}
microservices worker error: PostgresError: pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`., stack: PostgresError: pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
microservices worker exited with code 1
Killing api process
Initializing Immich v1.132.3
Detected CPU Cores: 16
Starting api worker
Starting microservices worker
```
