### ISSUE TITLE
IOS app - exclamation marks instead of thumbnails

### ISSUE THREAD

**Issue by Baxter117** [immich-app/immich#18409]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When the app is not closed and running in the background ( I think this is the normal way to use an app :D ) some times per day the thumbnails view only show exclamation marks over a black square. sometimes the background is the thumbnail in the lowest available quality. But not all photos are affected. I think only the newest. when scrolling down some image thumbnails appear correct.

after closing the app and reopen everything is fine.
My server connection to the internet is very good and stabile. LAN, fast DSL... 
on my iPhone I recognize this behavior in Local WLAN ( good 5Ghz connection) but also remote over 5G LTE or in other networks with good internet.

![Image](https://github.com/user-attachments/assets/9799e5a1-5632-4390-907e-bbd2e4f5c979)
![Image](https://github.com/user-attachments/assets/764bf77a-ae5a-48c9-8cd0-9a5b8a522d8a)
![Image](https://github.com/user-attachments/assets/78963e2b-36d5-4681-b077-b46267f088cc)
![Image](https://github.com/user-attachments/assets/ade151a8-c439-404a-9eea-0a18f944e2ef)
![Image](https://github.com/user-attachments/assets/4e4cd9cc-9795-48d4-976b-59783d3b7ec5)

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

1.132.3

### Version of Immich Mobile App

1.132.3 build.205

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profiles
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups

      - /etc/localtime:/etc/localtime:ro
      - /mnt/Daten_IronWolf/Netzwerk-Daten/Raphael_Daten/Eigene_Bilder:/Raphael_Bilder
      - /mnt/Daten_IronWolf/Netzwerk-Daten/Anna_Daten/Eigene_Bilder:/Anna_Bilder
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored

UPLOAD_LOCATION=/mnt/Daten_IronWolf/Netzwerk-Daten/IMMICH_uploads
THUMB_LOCATION=/home/immich-app/library/thumbs
ENCODED_VIDEO_LOCATION=/home/immich-app/library/encoded-video
PROFILE_LOCATION=/home/immich-app/library/profiles
BACKUP_LOCATION=/mnt/Daten_Zwischensp/IMMICH_Backup

# The location where your database files are stored
DB_DATA_LOCATION=./Database

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=DE

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1.open app 
2.close app that it is running in the background
3.reopen app after some time
...

### Relevant log output

```shell

```
