### ISSUE TITLE
Postgres permission issue after updating to 1.133.0

### ISSUE THREAD

**Issue by eygraber** [immich-app/immich#18431]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating to 1.133.0 and following the upgrade instructions, I started getting the following printed in a loop, and the server is not coming online.

```
immich_server            | Detected CPU Cores: 24
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 05/21/2025, 4:32:07 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | microservices worker error: Error: getaddrinfo ENOTFOUND immich_postgres, stack: Error: getaddrinfo ENOTFOUND immich_postgres
immich_server            |     at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_postgres          | chmod: changing permissions of '/var/run/postgresql': Operation not permitted
immich_postgres          | 
immich_postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres          | 
immich_postgres          | postgres: could not access the server configuration file "/etc/postgresql/postgresql.conf": No such file or directory
```

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    user: 1000:1001
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - /disks/storage/immich/volumes/geocoding:/usr/src/app/.reverse-geocoding-dump
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    user: 1000:1001
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /disks/storage/immich/volumes/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    user: 1000:1001
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - /disks/storage/immich/volumes/pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

PUID=1000
GUID=1001

# The location where your uploaded files are stored
UPLOAD_LOCATION=/disks/storage/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=<>

TZ=America/New_York

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Update
2. Start the server

### Relevant log output

```shell

```

**Comment by alextran1502** [comment]
cc @mertalev

**Comment by mertalev** [comment]
I believe this is because of the `user: 1000:1001` line. The image runs as root by default and doesn't seem to handle running as other users. @zackpollard is there something we can do here?

**Comment by Elekam** [comment]
Making the db-container run without that line indeed makes it work again. All other containers can continue using it. 

Fixing the directory permissions manually and uncommenting the line sadly does not work though, it still complains after. 

Would be great if that could be restored, running the services inside the container as non-root is pretty neat if you don't have a true rootless container.

**Comment by zackpollard** [comment]
> I believe this is because of the `user: 1000:1001` line. The image runs as root by default and doesn't seem to handle running as other users. [@zackpollard](https://github.com/zackpollard) is there something we can do here?

Unsure, I can take a look tomorrow

**Comment by savely-krasovsky** [comment]
@Elekam even in rootless setups running rootless inside rootless container still minimizes some risks.

**Comment by skellycode** [comment]
uncommenting the `user:` line by itself wasn't enough for me to workaround this issue.  I also had to execute `chmod -R u+rwX database` (where database is the location of the immich database folder).  Then starting up the new database image was successful

**Comment by cjd** [comment]
I worked around this by changing the uid from 1001 to 999 (to match the postgresql user)
I also changed the permissions on the files in /var/lib/postgresq accordingly.

After this it was able to startup properly, and immich-server was able to connect

**Comment by samssausages** [comment]
> I worked around this by changing the uid from 1001 to 999 (to match the postgresql user)

This worked for me as well.

**Comment by FibreTTP** [comment]
It looks like this is failing because `/etc/postgresql` is owned by root (or some other non-user-specified user) inside the container, so the custom Immich entrypoint script cannot copy the config file to it. Given that the user's database data directory (`DB_DATA_LOCATION`) is mounted to `/var/lib/postgresql/data`, could you not instead copy the storage type Postgres config file to that directory?

(https://github.com/immich-app/base-images/blob/3d4050d/postgres/immich-docker-entrypoint.sh#L8):

```diff
-   cp -n "/etc/postgresql/postgresql.${DB_STORAGE_TYPE,,}.conf" /etc/postgresql/postgresql.conf
+   cp -n "/etc/postgresql/postgresql.${DB_STORAGE_TYPE,,}.conf" /var/lib/postgresql/data/postgresql.conf
``` 

Then change the Dockerfile CMD to use the config file from `/var/lib/postgresql/data`?

(https://github.com/immich-app/base-images/blob/3d4050d/postgres/Dockerfile#L40):

```diff
-CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
+CMD ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
``` 

Note that `postgresql.conf` already exists for me inside my `DB_DATA_LOCATION` directory, so `cp` would have to be executed without `-n` (or else the copy won't happen).

**Comment by zackpollard** [comment]
> It looks like this is failing because `/etc/postgresql` is owned by root (or some other non-user-specified user) inside the container, so the custom Immich entrypoint script cannot copy the config file to it. Given that the user's database data directory (`DB_DATA_LOCATION`) is mounted to `/var/lib/postgresql/data`, could you not instead copy the storage type Postgres config file to that directory?
> 
> ([immich-app/base-images@`3d4050d`/postgres/immich-docker-entrypoint.sh#L8](https://github.com/immich-app/base-images/blob/3d4050d/postgres/immich-docker-entrypoint.sh?rgh-link-date=2025-05-22T06%3A38%3A08.000Z#L8)):
> 
> -   cp -n "/etc/postgresql/postgresql.${DB_STORAGE_TYPE,,}.conf" /etc/postgresql/postgresql.conf
> +   cp -n "/etc/postgresql/postgresql.${DB_STORAGE_TYPE,,}.conf" /var/lib/postgresql/data/postgresql.conf
> 
> Then change the Dockerfile CMD to use the config file from `/var/lib/postgresql/data`?
> 
> ([immich-app/base-images@`3d4050d`/postgres/Dockerfile#L40](https://github.com/immich-app/base-images/blob/3d4050d/postgres/Dockerfile?rgh-link-date=2025-05-22T06%3A38%3A08.000Z#L40)):
> 
> -CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
> +CMD ["postgres", "-c", "config_file=/var/lib/postgresql/data/postgresql.conf"]
> 
> Note that `postgresql.conf` already exists for me inside my `DB_DATA_LOCATION` directory, so `cp` would have to be executed without `-n` (or else the copy won't happen).
> 
> (edit: it would then be a normal permission error if the copy fails - postgres wouldn't be able to run anyway)

This would likely work, however we intentionally don't overwrite the config file in /var/lib/... because we want users to be able to provide their own version of the file. We also currently just extend that config file with our own.

**Comment by zackpollard** [comment]
> I suggest making this a breaking change and informing users that they can supply their own config file by using a different name and using the [`command`](https://docs.docker.com/reference/compose-file/services/#command) element in their compose file:
> 
>   immich-database:
>     image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
>     environment:
>       POSTGRES_PASSWORD: ${DB_PASSWORD}
>       POSTGRES_USER: ${DB_USERNAME}
>       POSTGRES_DB: ${DB_DATABASE_NAME}
>       POSTGRES_INITDB_ARGS: --data-checksums
>       # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
>       # DB_STORAGE_TYPE: 'HDD'
> +   command: ["postgres", "-c", "config_file=/custom/postgresql-modified.conf"]
>     user: 2000:2000
>     volumes:
>       - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
> +     - /custom/postgresql-modified.conf:/custom/postgresql-modified.conf
>     restart: unless-stopped

This will not be necessary.

**Comment by zackpollard** [comment]
You can see my planned fixed here: https://github.com/immich-app/base-images/pull/217 @FibreTTP

**Comment by Cromoray** [comment]
Any update on how to solve?

**Comment by zackpollard** [comment]
> Any update on how to solve?

We will be publishing an updated postgres image shortly that will resolve the problem

**Comment by skatsubo** [comment]
The fix  worked for me just fine, thank you!
To test it I incorporated the changes from https://github.com/immich-app/base-images/pull/217/files.
```Dockerfile
FROM ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
RUN chmod 1777 /etc/postgresql
```
Compose:
```yaml
    build:
      context: postgres-fix
      dockerfile: ./Dockerfile
      args:
        PG_MAJOR: 14
        VECTORCHORD_TAG: 0.3.0
        PGVECTOR_TAG: 0.8.0
        PGVECTORS_TAG: 0.3.0
```

Then start-up log:
```
immich-postgres  | Using SSD storage
immich-postgres  | chmod: changing permissions of '/var/run/postgresql': Operation not permitted
immich-postgres  | 
immich-postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich-postgres  | 
immich-postgres  | 2025-05-22 10:16:22.147 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich-postgres  | 2025-05-22 10:16:22.148 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich-postgres  | 2025-05-22 10:16:35.700 UTC [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich-postgres  | 2025-05-22 10:16:35.702 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich-postgres  | 2025-05-22 10:16:35.703 UTC [1] LOG:  listening on IPv6 address "::", port 5432
immich-postgres  | 2025-05-22 10:16:35.708 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich-postgres  | 2025-05-22 10:16:35.724 UTC [15] LOG:  database system was shut down at 2025-05-22 05:54:45 UTC
immich-postgres  | [2025-05-22T10:16:35Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17332".
immich-postgres  | [2025-05-22T10:16:35Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17576".
immich-postgres  | [2025-05-22T10:16:35Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17332/segments/ded41740-aaa4-44fa-bc15-9dc4b7c8e3b2".
immich-postgres  | 2025-05-22 10:16:35.763 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by zackpollard** [comment]
The images are building now and should be pushed within the next couple of minutes 🙂

**Comment by Cromoray** [comment]
I've done another "docker compose pull", it pulled db but it still seems to get the same error:
```
Initializing Immich v1.133.0

Detected CPU Cores: 8

Starting api worker

Starting microservices worker

[Nest] 7  - 05/23/2025, 9:58:54 AM     LOG [Microservices:EventRepository] Initialized websocket server

microservices worker error: Error: getaddrinfo ENOTFOUND database, stack: Error: getaddrinfo ENOTFOUND database

    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)

microservices worker exited with code 1

Killing api process
```

**Comment by skatsubo** [comment]
> I've done another "docker compose pull", it pulled db but it still seems to get the same error:

@Cromoray could you post your database docker image details and the database container logs?

For me it works with both Postgres images released yesterday:
```sh
$ docker images | grep immich
ghcr.io/immich-app/postgres                  14-vectorchord0.3.0-pgvectors0.2.0   c0bbffd020b1   24 hours ago     741MB
ghcr.io/immich-app/immich-server             release                              d81930e8788c   39 hours ago     2.13GB
ghcr.io/immich-app/immich-machine-learning   release                              70d74cde9582   9 days ago       1.04GB

$ dc pull

$ docker images | grep immich
ghcr.io/immich-app/postgres                  14-vectorchord0.3.0-pgvectors0.2.0   79fb2ca6b87a   19 hours ago     741MB
ghcr.io/immich-app/postgres                  <none>                               c0bbffd020b1   24 hours ago     741MB
ghcr.io/immich-app/immich-server             release                              d81930e8788c   39 hours ago     2.13GB
ghcr.io/immich-app/immich-machine-learning   release                              70d74cde9582   9 days ago       1.04GB

$ dc logs database
Using SSD storage
chmod: changing permissions of '/var/run/postgresql': Operation not permitted
PostgreSQL Database directory appears to contain a database; Skipping initialization
2025-05-23 10:47:53.383 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:47:53.385 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:48:04.610 UTC [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-05-23 10:48:04.611 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-05-23 10:48:04.611 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-05-23 10:48:04.636 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-05-23 10:48:04.672 UTC [16] LOG:  database system was shut down at 2025-05-23 10:47:51 UTC
2025-05-23 10:48:04.731 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by urbaman** [comment]
Hi, sorry but it is failing with image 17-vectorchord0.3.0-pgvectors0.3.0

```
...
Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

2025-05-23 10:52:30.903 GMT [46] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:52:30.903 GMT [46] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
waiting for server to start....2025-05-23 10:52:30.920 GMT [51] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:52:30.920 GMT [51] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
.2025-05-23 10:52:31.990 UTC [51] FATAL:  could not access file "vectors.so": No such file or directory
2025-05-23 10:52:31.991 UTC [51] LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
Using HDD storage

PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-05-23 10:52:32.372 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:52:32.373 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-23 10:52:33.415 UTC [1] FATAL:  could not access file "vectors.so": No such file or directory
2025-05-23 10:52:33.416 UTC [1] LOG:  database system is shut down
Using HDD storage

PostgreSQL Database directory appears to contain a database; Skipping initialization
...
```

**Comment by Cromoray** [comment]
@skatsubo here is the information you requested:

```
$ docker images | grep immich
ghcr.io/immich-app/postgres                  16-vectorchord0.3.0-pgvectors0.3.0   f9cbc65c72e5   19 hours ago   751MB
ghcr.io/immich-app/immich-server             release                              d81930e8788c   39 hours ago   2.13GB
ghcr.io/immich-app/immich-machine-learning   release                              70d74cde9582   9 days ago     1.04GB
```

For the database logs it only show this message repeated every minute
```
immich_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres  |
immich_postgres  | 2025-05-23 11:02:38.002 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich_postgres  | 2025-05-23 11:02:38.002 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich_postgres  | 2025-05-23 11:02:38.002 UTC [1] FATAL:  database files are incompatible with server
immich_postgres  | 2025-05-23 11:02:38.002 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 16.8 (Debian 16.8-1.pgdg120+1).
```

**Comment by urbaman** [comment]
@Cromoray that is a postgres major upgrade (14->16) issue, I think.
You should use a 14-xxx image ore undergo a pg_upgrade.

**Comment by savely-krasovsky** [comment]
What helped me:
1. Changed to `ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.3.0`
2. Revert proper rights with `chown -R 1000:1000 postgres`.
3. Uncomment back Podman Quadlet rules to run rootless inside rootless container:
```
User=1000:1000
UserNS=keep-id:uid=1000,gid=1000
```

**Comment by skatsubo** [comment]
> immich_postgres  | 2025-05-23 11:02:38.002 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 16.8 (Debian 16.8-1.pgdg120+1).

@Cromoray exactly as @urbaman wrote above. It is not related to permissions.
Similar discussion of PG version incompatibilities here https://github.com/immich-app/immich/discussions/18429#discussioncomment-13235869.

**Comment by skatsubo** [comment]
@urbaman What is your compose config for database? Have you already removed the command section as per BREAKING CHANGES section in release notes?

> 2025-05-23 10:52:33.415 UTC [1] FATAL:  could not access file "vectors.so": No such file or directory

https://github.com/immich-app/immich/discussions/18429#discussioncomment-13238820 - if this is your case, then it's not related to permissions.

**Comment by urbaman** [comment]
Here is my compose for the database, I think I properly followed the breaking changes notes.
I'll check the permissions on my $DATADIR/postgresql:

`drwx------ 1    999 root            454 May 23 13:39 postgresql`

```
services:
  postgres:
    container_name: postgres
    image: ghcr.io/immich-app/postgres:17-vectorchord0.3.0-pgvectors0.3.0
    pull_policy: always
    networks:
      - databases
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - $DATADIR/postgresql:/var/lib/postgresql/data
    restart: always
```

**Comment by urbaman** [comment]
PS: the $DATADIR/postgresql directory was created by docker when I spuin up the container the first time.

And this is the content, created by the container:

```
ls -la $DATADIR/postgresql/
total 52
drwx------ 1  999 root              454 May 23 13:39 .
drwxr-xr-x 1 root root              160 May 23 12:52 ..
drwx------ 1  999 systemd-journal     6 May 23 12:52 base
drwx------ 1  999 systemd-journal   600 May 23 12:52 global
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_commit_ts
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_dynshmem
-rw------- 1  999 systemd-journal  5743 May 23 12:52 pg_hba.conf
-rw------- 1  999 systemd-journal  2640 May 23 12:52 pg_ident.conf
drwx------ 1  999 systemd-journal    76 May 23 12:52 pg_logical
drwx------ 1  999 systemd-journal    28 May 23 12:52 pg_multixact
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_notify
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_replslot
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_serial
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_snapshots
drwx------ 1  999 systemd-journal    22 May 23 12:52 pg_stat
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_stat_tmp
drwx------ 1  999 systemd-journal     8 May 23 12:52 pg_subtrans
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_tblspc
drwx------ 1  999 systemd-journal     0 May 23 12:52 pg_twophase
-rw------- 1  999 systemd-journal     3 May 23 12:52 PG_VERSION
drwx------ 1  999 systemd-journal    94 May 23 12:52 pg_wal
drwx------ 1  999 systemd-journal     8 May 23 12:52 pg_xact
-rw------- 1  999 systemd-journal    88 May 23 12:52 postgresql.auto.conf
-rw------- 1  999 systemd-journal 30777 May 23 12:52 postgresql.conf
```

**Comment by urbaman** [comment]
I can aolso confirm that doing the very same process with 14-vectorchord0.3.0-pgvectors0.2.0 works like a charm, so 17 seems to be the problematic one.

- deleting the $DATADIR/postgresql directory
- changing image to 14
- docker compose up -d

The permissions on the new directory seem to be the same as those for the 17 image.

**Comment by Cromoray** [comment]
@urbaman @skatsubo thanks you so much, finally my instance is up again

**Comment by WallK** [comment]
I'm still bashing my head on
>could not open configuration file "/etc/postgresql/postgresql.conf": Permission denied

I'm using OMV and I've pulled newer image -- still no dice

**Comment by skatsubo** [comment]
> I'm using OMV and I've pulled newer image -- still no dice

Not quite familiar with OMV, but could you post the database compose section?

**Comment by WallK** [comment]
> Not quite familiar with OMV, but could you post the database compose section?

Sure, it's exactly as proposed in hosted compose file

```
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data # BACKUP
    restart: always
```
