### ISSUE TITLE
vchord must be loaded via shared_preload_libraries

### ISSUE THREAD

**Issue by ireun** [immich-app/immich#18432]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After upgrading to newest Immich image (LOL) and adjusting docker compose as pointed it does not load.
I've tried `psql --dbname=immich --username=IreuN` and `CREATE EXTENSION IF NOT EXISTS vchord CASCADE; COMMIT;` but that has not fixed it.

### The OS that Immich Server is running on

Proxmox > Debian LXC > Portainer 

### Version of Immich Server

1.133.0

### Version of Immich Mobile App

newest?

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
docker compose:

#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/Photos/Canon:/mnt/Canon
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  # immich-machine-learning:
  #   container_name: immich_machine_learning
  #   # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
  #   # Example tag: ${IMMICH_VERSION:-release}-cuda
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
  #   #   file: hwaccel.ml.yml
  #   #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
  #   volumes:
  #     - model-cache:/cache
  #   env_file:
  #     - stack.env
  #   restart: always
  #   healthcheck:
  #     disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Photos
DB_DATA_LOCATION=/root/immich_data_postgres
IMMICH_VERSION=release
DB_PASSWORD=LOLOLOLOLOL
DB_USERNAME=IreuN
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. update immich
2. get error
3. immich does not load

### Relevant log output

```shell
log:

Initializing Immich v1.133.0
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 7  - 05/21/2025, 8:43:05 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 05/21/2025, 8:43:05 PM     LOG [Microservices:DatabaseRepository] Creating VectorChord extension
[Nest] 7  - 05/21/2025, 8:43:05 PM   FATAL [Microservices:DatabaseService] Failed to activate VectorChord extension.
    Please ensure the Postgres instance has VectorChord installed.

    If the Postgres instance already has VectorChord installed, Immich may not have the necessary permissions to activate it.
    In this case, please run 'CREATE EXTENSION IF NOT EXISTS vchord CASCADE' manually as a superuser.
    See https://immich.app/docs/guides/database-queries for how to query the database.
Query failed : {
  durationMs: 30.907586000000265,
  error: PostgresError: vchord must be loaded via shared_preload_libraries.
      at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
      at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
      at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:561:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
      at Readable.push (node:internal/streams/readable:392:5)
      at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
    severity_local: 'ERROR',
    severity: 'ERROR',
    code: 'XX000',
    file: 'lib.rs',
    line: '15',
    routine: 'vchord::_PG_init::_PG_init_inner'
  },
  sql: 'CREATE EXTENSION IF NOT EXISTS vchord CASCADE',
  params: []
}
PostgresError: vchord must be loaded via shared_preload_libraries.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: 'XX000',
  file: 'lib.rs',
  line: '15',
  routine: 'vchord::_PG_init::_PG_init_inner'
}
microservices worker error: PostgresError: vchord must be loaded via shared_preload_libraries., stack: PostgresError: vchord must be loaded via shared_preload_libraries.
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
microservices worker exited with code 1
Killing api process
```
