### ISSUE TITLE
Missing or inaccessible postgres vchord extension after upgrade 1.33.0

### ISSUE THREAD

**Issue by mafrosis** [immich-app/immich#18439]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

Upgrade from 1.32.1:

```
immich-1     | Starting api worker
immich-1     | Starting microservices worker
immich-1     | [Nest] 7  - 05/22/2025, 9:33:04 AM     LOG [Microservices:EventRepository] Initialized websocket server
immich-1     | [Nest] 7  - 05/22/2025, 9:33:04 AM     LOG [Microservices:DatabaseRepository] Creating VectorChord extension
immich-1     | [Nest] 7  - 05/22/2025, 9:33:04 AM   FATAL [Microservices:DatabaseService] Failed to activate VectorChord extension.
immich-1     |     Please ensure the Postgres instance has VectorChord installed.
immich-1     |
immich-1     |     If the Postgres instance already has VectorChord installed, Immich may not have the necessary permissions to activate it.
immich-1     | Query failed : {
immich-1     |   durationMs: 8.824166999999989,
immich-1     |   error: PostgresError: vchord must be loaded via shared_preload_libraries.
immich-1     |       at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich-1     |       at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich-1     |       at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich-1     |       at Socket.emit (node:events:518:28)
immich-1     |       at addChunk (node:internal/streams/readable:561:12)
immich-1     |       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich-1     |       at Readable.push (node:internal/streams/readable:392:5)
immich-1     |       at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
immich-1     |     severity_local: 'ERROR',
immich-1     |     severity: 'ERROR',
immich-1     |     code: 'XX000',
immich-1     |     file: 'lib.rs',
immich-1     |     line: '15',
immich-1     |     routine: 'vchord::_PG_init::_PG_init_inner'
immich-1     |   },
immich-1     |   sql: 'CREATE EXTENSION IF NOT EXISTS vchord CASCADE',
immich-1     |   params: []
immich-1     | }
immich-1     |     In this case, please run 'CREATE EXTENSION IF NOT EXISTS vchord CASCADE' manually as a superuser.
immich-1     |     See https://immich.app/docs/guides/database-queries for how to query the database.
immich-1     | PostgresError: vchord must be loaded via shared_preload_libraries.
immich-1     |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich-1     |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich-1     |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich-1     |     at Socket.emit (node:events:518:28)
immich-1     |     at addChunk (node:internal/streams/readable:561:12)
immich-1     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich-1     |     at Readable.push (node:internal/streams/readable:392:5)
immich-1     |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
immich-1     |   severity_local: 'ERROR',
immich-1     |   severity: 'ERROR',
immich-1     |   code: 'XX000',
immich-1     |   file: 'lib.rs',
immich-1     |   line: '15',
immich-1     |   routine: 'vchord::_PG_init::_PG_init_inner'
immich-1     | }
immich-1     | microservices worker error: PostgresError: vchord must be loaded via shared_preload_libraries., stack: PostgresError: vchord must be loaded via shared_preload_libraries.
immich-1     |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich-1     |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich-1     |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich-1     |     at Socket.emit (node:events:518:28)
immich-1     |     at addChunk (node:internal/streams/readable:561:12)
immich-1     |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich-1     |     at Readable.push (node:internal/streams/readable:392:5)
immich-1     |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich-1     | microservices worker exited with code 1
immich-1     | Killing api process
immich-1 exited with code 1
```

### The OS that Immich Server is running on

macOS

### Version of Immich Server

v1.33.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
volumes:
  immich-data: {}
  immich-db: {}
  immich-cache: {}
  model-cache: {}

services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    environment:
      TZ: Australia/Melbourne
      IMMICH_CONFIG_FILE: /immich.json
    volumes:
      - immich-data:/usr/src/app/upload
      - ./immich.json:/immich.json:ro
      - /etc/localtime:/etc/localtime:ro
      - /Volumes/Photos:/photos
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
      - immich-ml

  immich-ml:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    volumes:
      - model-cache:/cache

  redis:
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    restart: unless-stopped
    volumes:
      - immich-cache:/data

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich-db:/var/lib/postgresql/data
```

### Your .env content

```Shell
IMMICH_VERSION=v1.133.0
```

### Reproduction steps

1. Follow upgrade instruction
2. Start immich
3. Error
4. Rollback
...

### Relevant log output

```shell

```
