### ISSUE TITLE
Failed DB migration after updating to v1.133.0

### ISSUE THREAD

**Issue by jnstockley** [immich-app/immich#18441]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating  to new Immich and DB version container get in a boot loop and a failed DB migration

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
name: immich
services:
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - private
    restart: always
    healthcheck:
      disable: true
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.133.0
    container_name: immich_machine_learning
    depends_on:
      - database
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - private
    restart: unless-stopped
    healthcheck:
      test: python3 healthcheck.py
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 512M
    security_opt:
      - no-new-privileges:true

  immich-server:
    image: ghcr.io/immich-app/immich-server:v1.133.0
    container_name: immich_server
    depends_on:
      - database
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./healthcheck.js:/healthcheck/healthcheck.js
    env_file:
      - .env
    ports:
      - '0.0.0.0:2283:2283'
    networks:
      - proxy
      - private
    restart: unless-stopped
    healthcheck:
      test: immich-healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 100s
    deploy:
      resources:
        limits:
          memory: 1G
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    name: proxy
    external: true
  private:
    name: private
    internal: true
    external: true

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zo>
TZ=America/Chicago

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<PASSWORD>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

# Redis
REDIS_HOSTNAME=redis
REDIS_PORT=6379
REDIS_DBINDEX=1
```

### Reproduction steps

1. Update to immich v1.133.0 and new DB image
2. Restart container

### Relevant log output

```shell
immich_postgres          | Using SSD storage
immich_postgres          | 
immich_postgres          | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres          | 
immich_postgres          | 2025-05-22 00:34:23.423 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich_postgres          | 2025-05-22 00:34:23.423 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
immich_postgres          | 2025-05-22 00:34:24.405 UTC [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich_postgres          | 2025-05-22 00:34:24.405 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich_postgres          | 2025-05-22 00:34:24.405 UTC [1] LOG:  listening on IPv6 address "::", port 5432
immich_postgres          | 2025-05-22 00:34:24.418 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich_postgres          | 2025-05-22 00:34:24.452 UTC [29] LOG:  database system was shut down at 2025-05-22 00:34:01 UTC
immich_postgres          | [2025-05-22T00:34:24Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17575".
immich_postgres          | [2025-05-22T00:34:24Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17331".
immich_postgres          | [2025-05-22T00:34:24Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17331/segments/31ac6c80-8fcf-4e09-8fb7-58220fbed0e8".
immich_postgres          | [2025-05-22T00:34:24Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17575/segments/9ca1b982-2b26-449e-9934-58381090b483".
immich_postgres          | 2025-05-22 00:34:24.488 UTC [1] LOG:  database system is ready to accept connections
immich_server            | Initializing Immich v1.133.0
immich_server            | Detected CPU Cores: 6
immich_machine_learning  | [05/21/25 19:34:55] INFO     Starting gunicorn 23.0.0                           
immich_machine_learning  | [05/21/25 19:34:55] INFO     Listening at: http://[::]:3003 (8)                 
immich_machine_learning  | [05/21/25 19:34:55] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
immich_machine_learning  | [05/21/25 19:34:55] INFO     Booting worker with pid: 9                         
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_machine_learning  | [05/21/25 19:34:56] INFO     Started server process [9]                         
immich_machine_learning  | [05/21/25 19:34:56] INFO     Waiting for application startup.                   
immich_machine_learning  | [05/21/25 19:34:56] INFO     Created in-memory cache with unloading after 300s  
immich_machine_learning  |                              of inactivity.                                     
immich_machine_learning  | [05/21/25 19:34:56] INFO     Initialized request thread pool with 6 threads.    
immich_machine_learning  | [05/21/25 19:34:56] INFO     Application startup complete.                      
immich_server            | [Nest] 8  - 05/21/2025, 7:34:57 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | [Nest] 8  - 05/21/2025, 7:34:57 PM     LOG [Microservices:DatabaseRepository] targetLists=1, current=1 for clip_index of 32419 rows
immich_server            | [Nest] 8  - 05/21/2025, 7:34:57 PM     LOG [Microservices:DatabaseRepository] Reindexing clip_index
immich_server            | [Nest] 8  - 05/21/2025, 7:34:57 PM     LOG [Microservices:DatabaseRepository] targetLists=1, current=1 for face_index of 35749 rows
immich_server            | [Nest] 8  - 05/21/2025, 7:34:57 PM     LOG [Microservices:DatabaseRepository] Reindexing face_index
immich_server            | [Nest] 18  - 05/21/2025, 7:34:57 PM     LOG [Api:EventRepository] Initialized websocket server
immich_server            | Query failed : {
immich_server            |   durationMs: 3343.385511000004,
immich_server            |   error: Error: write CONNECTION_CLOSED database:5432
immich_server            |       at Socket.closed (/usr/src/app/node_modules/postgres/cjs/src/connection.js:440:57)
immich_server            |       at Socket.emit (node:events:518:28)
immich_server            |       at TCP.<anonymous> (node:net:351:12) {
immich_server            |     code: 'CONNECTION_CLOSED',
immich_server            |     errno: 'CONNECTION_CLOSED',
immich_server            |     address: [ 'database' ],
immich_server            |     port: [ 5432 ]
immich_postgres          | 2025-05-22 00:35:28.083 UTC [1] LOG:  server process (PID 57) was terminated by signal 9: Killed
immich_server            |   },
immich_postgres          | 2025-05-22 00:35:28.083 UTC [1] DETAIL:  Failed process was running: 
immich_server            |   sql: '\n' +
immich_postgres          |              ALTER TABLE smart_search
immich_server            |     '        ALTER TABLE smart_search\n' +
immich_postgres          |              ALTER COLUMN embedding
immich_server            |     '        ALTER COLUMN embedding\n' +
immich_postgres          |              SET DATA TYPE vector(512)
immich_server            |     '        SET DATA TYPE vector(512)',
immich_postgres          | 2025-05-22 00:35:28.086 UTC [1] LOG:  terminating any other active server processes
immich_server            |   params: []
immich_server            | }
immich_server            | microservices worker error: TypeError: Cannot read properties of null (reading 'write'), stack: TypeError: Cannot read properties of null (reading 'write')
immich_server            |     at Immediate.nextWrite (/usr/src/app/node_modules/postgres/cjs/src/connection.js:250:22)
immich_server            |     at process.processImmediate (node:internal/timers:491:21)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_postgres          | 2025-05-22 00:35:28.146 UTC [1] LOG:  all server processes terminated; reinitializing
immich_postgres          | 2025-05-22 00:35:28.242 UTC [85] LOG:  database system was interrupted; last known up at 2025-05-22 00:34:24 UTC
immich_postgres          | 2025-05-22 00:35:28.436 UTC [85] LOG:  database system was not properly shut down; automatic recovery in progress
immich_postgres          | 2025-05-22 00:35:28.443 UTC [85] LOG:  redo starts at 1/87C0E310
immich_postgres          | 2025-05-22 00:35:28.707 UTC [86] FATAL:  the database system is in recovery mode
immich_postgres          | 2025-05-22 00:35:29.275 UTC [85] LOG:  unexpected pageaddr 1/7E5A4000 in log segment 000000010000000100000093, offset 5914624
immich_postgres          | 2025-05-22 00:35:29.275 UTC [85] LOG:  redo done at 1/935A37A0 system usage: CPU: user: 0.13 s, system: 0.26 s, elapsed: 0.83 s
immich_server exited with code 0
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 05/21/2025, 7:35:32 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_postgres          | 2025-05-22 00:35:32.273 UTC [87] FATAL:  the database system is in recovery mode
immich_server            | microservices worker error: PostgresError: the database system is in recovery mode, stack: PostgresError: the database system is in recovery mode
immich_server            |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |     at Socket.emit (node:events:518:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_postgres          | 2025-05-22 00:35:36.048 UTC [96] FATAL:  the database system is in recovery mode
immich_postgres          | 2025-05-22 00:35:39.355 UTC [1] LOG:  database system is ready to accept connections
immich_postgres          | [2025-05-22T00:35:39Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17575".
immich_postgres          | [2025-05-22T00:35:39Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17331".
immich_postgres          | [2025-05-22T00:35:39Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17575/segments/9ca1b982-2b26-449e-9934-58381090b483".
immich_postgres          | [2025-05-22T00:35:39Z INFO  service::utils::clean] Find directory "pg_vectors/indexes/17331/segments/31ac6c80-8fcf-4e09-8fb7-58220fbed0e8".
immich_server exited with code 0
```
