### ISSUE TITLE
Fatal Error Following update to 1.133.0

### ISSUE THREAD

**Issue by hazzac181** [immich-app/immich#18454]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After following the provided instructions in the 1.133.0 release, I am encountering the following looping error in the `immich server` container. 

`2025-05-22 16:46:07.111 AEST [107] FATAL:  role "root" does not exist`

### The OS that Immich Server is running on

Fedora Workstation 42

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.132.3 build.197

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_PASSWORD=<>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
UPLOAD_LOCATION=/media/hazzac181/Data + Media/Immich/Media
DB_DATA_LOCATION=/media/hazzac181/Data + Media/Immich/Database
TZ=Australia/Melbourne
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin
GOSU_VERSION=1.17
LANG=en_US.utf8
PG_MAJOR=14
PG_VERSION=14.17-1.pgdg120+1
PGDATA=/var/lib/postgresql/data
DB_STORAGE_TYPE=HDD
```

### Reproduction steps

1.Follow instructions in v1.133.0 to update the compose.yml file
2.Deploy the contain and re-pull the image
3.
...

### Relevant log output

```shell
Using HDD storage


PostgreSQL Database directory appears to contain a database; Skipping initialization


2025-05-22 07:05:58.872 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"

2025-05-22 07:05:58.872 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"

2025-05-22 17:05:59.823 AEST [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

2025-05-22 17:05:59.823 AEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432

2025-05-22 17:05:59.823 AEST [1] LOG:  listening on IPv6 address "::", port 5432

2025-05-22 17:05:59.834 AEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"

2025-05-22 17:05:59.845 AEST [28] LOG:  database system was shut down at 2025-05-22 17:05:35 AEST

2025-05-22 17:05:59.854 AEST [1] LOG:  database system is ready to accept connections

2025-05-22 17:06:28.873 AEST [45] FATAL:  role "root" does not exist

2025-05-22 17:06:28.895 AEST [47] FATAL:  role "root" does not exist
```

### Additional information

None applicable
