### ISSUE TITLE
Deeplinks to a specific image don't work on the web

### ISSUE THREAD

**Issue by zolakt** [immich-app/immich#18472]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi,

I've just upgraded to v1.133.0 (great job), but I see this functionality is now broken, and it used to work fine in the previous version.

This is regarding the `?at=1388f12b-5c15-4310-8e83-8e16a8e7b095` url param. When you refresh the page (with the param in the url) it doesn't jump to that pictures, it just reloads the timeline from the top.

While I agree it's not a super critical issue, I do have a viable use case. I'm going through my whole library, tagging everything, fixing false-positive face recognitions, tagging people where the face isn't visible etc. This takes a lot of time, and I can only spare a few hours per day to do it. So it has been an ongoing process for some time. Previously, I would just open the next image where I'd stopped, and I wouldn't turn off my computer. Chrome would suspend (or whatever it's called) that tab when it inactive for a long time. And the next day I would just open it again, it would reload, and jump to where I'd left off.

Similarily if you open a photo by a direct url like `photos/5fe43b0d-ed09-4122-a75c-7d73b1134661` and then click back, it won't jump to that place in the timeline, it will just remain at the top.

Possibly the root cause of this is the same as for [this issue](https://github.com/immich-app/immich/issues/18455).

### The OS that Immich Server is running on

Ubuntu 22.10 on Proxmox LXC container

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - /media/share/Pictures/external:/mnt/media/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/share/Pictures
BACKUP_LOCATION=/media/backup/immich

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Zagreb

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=myPassword

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open (or refresh) a url that contains the `?at=` url param

### Relevant log output

```shell

```
