### ISSUE TITLE
Can't start after upgrade database to version 1.133

### ISSUE THREAD

**Issue by smalecwks** [immich-app/immich#18483]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I upgraded immich to wersion 1.133 with database migration, but it failed:

CONTAINER ID   IMAGE                                                            COMMAND                  CREATED        STATUS                   PORTS                                                   NAMES
6db959a8d262   ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0   "/usr/local/bin/immi…"   7 hours ago    Up 7 hours (unhealthy)   0.0.0.0:2283->2283/tcp, [::]:2283->2283/tcp, 5432/tcp   immich_server
005f5a491132   tensorchord/pgvecto-rs:pg14-v0.2.0                               "docker-entrypoint.s…"   8 hours ago    Up 7 hours               5432/tcp                                                immich_postgres
37f4266409a3   ghcr.io/immich-app/immich-machine-learning:release               "tini -- python -m i…"   8 hours ago    Up 7 hours (healthy)                                                             immich_machine_learning
86f6f3db8ee8   redis:6.2-alpine                                                 "docker-entrypoint.s…"   3 months ago   Up 7 hours (healthy)     6379/tcp                                                immich_redis

Logs say:

PostgreSQL init process complete; ready for start up.

2025-05-22 07:36:15.792 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-22 07:36:15.792 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-22 09:36:20.570 CEST [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-05-22 09:36:20.570 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-05-22 09:36:20.570 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2025-05-22 09:36:20.574 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-05-22 09:36:20.581 CEST [67] LOG:  database system was shut down at 2025-05-22 09:36:15 CEST
2025-05-22 09:36:20.592 CEST [1] LOG:  database system is ready to accept connections
2025-05-22 09:36:39.228 CEST [84] FATAL:  role "root" does not exist
2025-05-22 09:36:39.287 CEST [86] FATAL:  role "root" does not exist
2025-05-22 09:37:09.400 CEST [94] FATAL:  role "root" does not exist
2025-05-22 09:37:09.456 CEST [96] FATAL:  role "root" does not exist
2025-05-22 09:37:39.574 CEST [105] FATAL:  role "root" does not exist
2025-05-22 09:37:39.632 CEST [107] FATAL:  role "root" does not exist
2025-05-22 09:38:09.743 CEST [115] FATAL:  role "root" does not exist
2025-05-22 09:38:09.799 CEST [117] FATAL:  role "root" does not exist

### The OS that Immich Server is running on

Linux proxmox 6.8.12-8-pve

### Version of Immich Server

1.133

### Version of Immich Mobile App

1.133

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    #image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /NAS/Fotki:/NAS/Fotki
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/NAS/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=Europe/Warsaw

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_VERSION="v1.116.0"

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Updated docker-compose.yml according documentation
2. Upgrade docker with docker compose pull && docker compose up -d
3.  Failed to start
4.  Error message says:
2025-05-22 09:36:20.581 CEST [67] LOG:  database system was shut down at 2025-05-22 09:36:15 CEST
2025-05-22 09:36:20.592 CEST [1] LOG:  database system is ready to accept connections
2025-05-22 09:36:39.228 CEST [84] FATAL:  role "root" does not exist
2025-05-22 09:36:39.287 CEST [86] FATAL:  role "root" does not exist
2025-05-22 09:37:09.400 CEST [94] FATAL:  role "root" does not exist
2025-05-22 09:37:09.456 CEST [96] FATAL:  role "root" does not exist
2025-05-22 09:37:39.574 CEST [105] FATAL:  role "root" does not exist
2025-05-22 09:37:39.632 CEST [107] FATAL:  role "root" does not exist
2025-05-22 09:38:09.743 CEST [115] FATAL:  role "root" does not exist
2025-05-22 09:38:09.799 CEST [117] FATAL:  role "root" does not exist

...

### Relevant log output

```shell
PostgreSQL init process complete; ready for start up.

2025-05-22 07:36:15.792 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-22 07:36:15.792 GMT [1] LOG:  skipping missing configuration file "/var/lib/postgresql/data/postgresql.override.conf"
2025-05-22 09:36:20.570 CEST [1] LOG:  starting PostgreSQL 14.17 (Debian 14.17-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-05-22 09:36:20.570 CEST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-05-22 09:36:20.570 CEST [1] LOG:  listening on IPv6 address "::", port 5432
2025-05-22 09:36:20.574 CEST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-05-22 09:36:20.581 CEST [67] LOG:  database system was shut down at 2025-05-22 09:36:15 CEST
2025-05-22 09:36:20.592 CEST [1] LOG:  database system is ready to accept connections
2025-05-22 09:36:39.228 CEST [84] FATAL:  role "root" does not exist
2025-05-22 09:36:39.287 CEST [86] FATAL:  role "root" does not exist
2025-05-22 09:37:09.400 CEST [94] FATAL:  role "root" does not exist
2025-05-22 09:37:09.456 CEST [96] FATAL:  role "root" does not exist
2025-05-22 09:37:39.574 CEST [105] FATAL:  role "root" does not exist
2025-05-22 09:37:39.632 CEST [107] FATAL:  role "root" does not exist
2025-05-22 09:38:09.743 CEST [115] FATAL:  role "root" does not exist
2025-05-22 09:38:09.799 CEST [117] FATAL:  role "root" does not exist
```
