### ISSUE TITLE
Account deletion missing confirmation button bottom left

### ISSUE THREAD

**Issue by FasteryXD** [immich-app/immich#18487]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I just wanted to delete an account via immich web and had to search forever to figure out how to confirm my entry, since pressing enter didn't work either. It turns out that the confirmation button in the bottom left corner isn't displayed, but it works perfectly. See the images and the cursor in the bottom left corner.

![Image](https://github.com/user-attachments/assets/f4341313-e344-433a-b58d-a532641a1ee1)

![Image](https://github.com/user-attachments/assets/a740ec84-e13f-48be-b1a6-a5b340624860)

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

1.133.0 build.198

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - SERVER_HOST=0.0.0.0 #optional
      - SERVER_PORT=8080 #optional
      - MACHINE_LEARNING_HOST=0.0.0.0 #optional
      - MACHINE_LEARNING_PORT=3003 #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_libraries:/libraries #optional
    ports:
      - 8080:8080
    restart: unless-stopped

# This container requires an external application to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
/
```

### Reproduction steps

It was there from the beginning...

### Relevant log output

```shell

```
