### ISSUE TITLE
OAuth Login Failure with Casdoor (PKCE `verifier is invalid`) since v1.132.3 (current v1.133.0)

### ISSUE THREAD

**Issue by deadnessking** [immich-app/immich#18482]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**Description:**
After upgrading Immich from v1.132.2 to v1.132.3 (and subsequently to the latest v1.133.0), OAuth login/linking with Casdoor as the OIDC provider consistently fails. The failure is due to a PKCE `verifier is invalid` error, indicating an issue with the `code_verifier` and `code_challenge` exchange.

It appears the `code_verifier` parameter is missing from the token request sent by Immich to Casdoor's token endpoint, even though Immich is attempting a PKCE flow. This issue was not present in v1.132.2 and earlier, where OAuth with Casdoor (as a confidential client using PKCE) worked correctly.

**Environment:**
*   **Immich Version:** `v1.133.0` (problem observed since `v1.132.3`)
*   **OAuth Provider:** Casdoor (version [if you know it, otherwise omit or say "latest"])
*   **Immich OAuth Configuration:**
    *   `ISSUER_URL`: `https://casdoor.example.com`
    *   `CLIENT_ID`: `****************`
    *   `CLIENT_SECRET`: `****************` (problem persists whether this is filled or left blank, as per new optional behavior)
    *   `TOKEN_ENDPOINT_AUTH_METHOD`: Tried both `client_secret_post` and `client_secret_basic`. The error is the same.
    *   `AUTO_REGISTER`: true
    *   `AUTO_LAUNCH`: true
    *   `MOBILE_OVERRIDE_ENABLED`: false
    *   `SCOPE`: `openid profile email offline_access` (or your actual scope)

**Steps to Reproduce:**
1.  Configure Immich (v1.132.3 or newer) with Casdoor as an OIDC provider using the settings above.
2.  Ensure Casdoor is configured for this client, and it enforces PKCE for confidential clients (Casdoor does this by default and does not offer an option to disable it for confidential clients).
3.  Attempt to log in or link an account via OAuth in Immich.
4.  Observe the error in Immich and the request received by Casdoor.

**Expected Result:**
*   Successful OAuth login/linking with Casdoor.
*   Immich sends a token request to Casdoor's token endpoint that includes the `code_verifier` parameter as part of the PKCE flow.
*   Casdoor validates the `code_verifier` against the `code_challenge` and issues tokens.

**Actual Result:**
*   OAuth login/linking fails.
*   Immich logs show:
    ```
    [Nest] ... ERROR [Api:OAuthRepository~xxxxxx] OAuth login failed: server responded with an error in the response body
    [Nest] ... ERROR [Api:OAuthRepository~xxxxxx] ResponseBodyError: server responded with an error in the response body
    at checkOAuthBodyError (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:865:19)
    ...
    cause: {
      error: 'invalid_grant',
      error_description: 'verifier is invalid, challengeAnswer: [*******************************************], token.CodeChallenge: [*******************************************]'
    },
    code: 'OAUTH_RESPONSE_BODY_ERROR',
    error: 'invalid_grant',
    status: 400,
    error_description: 'verifier is invalid, challengeAnswer: [*******************************************], token.CodeChallenge: [*******************************************]'
    }
    [Nest] ... ERROR [Api:ErrorInterceptor~xxxxxx] Unknown error: Error: OAuth login failed
    ...
    [Nest] ... DEBUG [Api:LoggingInterceptor~xxxxxx] POST /api/oauth/link 201 ...ms 192.168.1.100
    [Nest] ... VERBOSE [Api:LoggingInterceptor~xxxxxx] {"url":"https://immich.example.com/user-settings?code=xxxxxxxxxxxxxxxxxxxx&state=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
    [Nest] ... DEBUG [Api:GlobalExceptionFilter~xxxxxx] HttpException(500): {"message":"Failed to link oauth account","error":"Internal Server Error","statusCode":500}
    ```
*   Casdoor logs (or network trace) show the POST request to Casdoor's token endpoint (`/api/login/oauth/access_token`) from Immich contains parameters like `grant_type`, `code`, `redirect_uri`, `client_id`, and `client_secret` (if `client_secret_post` is used), **but is missing the `code_verifier` parameter.** Example request body received by Casdoor:
    ```
    grant_type=authorization_code&code=xxxxxxxxxxxxxxxxxxxx&redirect_uri=https%3A%2F%2Fimmich.example.com%2Fuser-settings&client_id=****************&client_secret=****************
    ```
    (The `client_secret` part is present if `TOKEN_ENDPOINT_AUTH_METHOD` is `client_secret_post`. If `client_secret_basic` is used, it's in the Authorization header, but `code_verifier` is still missing from the body).

**Additional Context:**
*   This functionality was working correctly in Immich v1.132.2 and earlier with the same Casdoor configuration. In those versions, Immich, acting as a confidential client, correctly sent the `code_verifier` during the token exchange.
*   The issue occurs regardless of **whether `CLIENT_SECRET` is provided** in Immich's OAuth settings (since it became optional if the provider supports PKCE).
*   The `TOKEN_ENDPOINT_AUTH_METHOD` setting (tried `client_secret_post` and `client_secret_basic`) does not resolve the missing `code_verifier` issue.
*   Casdoor enforces PKCE for all clients (including confidential ones) and does not provide an option to disable it.

This strongly suggests a regression in Immich v1.132.3+ where the `code_verifier` is not being included in the token request payload when interacting with the OIDC provider, leading to the PKCE validation failure.

### The OS that Immich Server is running on

Windows Server Docker Desktop

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #    file: hwaccel.transcoding.yml
    #    service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0'] # Specify index '1' for the second GPU
              capabilities:
                - gpu
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - O:\photos:/otherphotos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    #image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    image: ghcr.nju.edu.cn/immich-app/immich-machine-learning:release-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #count: 1
              device_ids: ['0'] # Specify index '1' for the second GPU
              capabilities:
                - gpu
    volumes:
      - O:\Docker\Immich\model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    #image: docker.io/redis:7-alpine
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
     # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
     # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
UPLOAD_LOCATION=O:\Docker\Immich\library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Asia/Shanghai

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgresimmich
DB_DATABASE_NAME=immich_db

###################################################################################
# JWT SECRET
#
# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
###################################################################################

JWT_SECRET=*****
```

### Reproduction steps

1.  Configure Immich (v1.132.3 or newer) with Casdoor as an OIDC provider using the settings above.
2.  Ensure Casdoor is configured for this client, and it enforces PKCE for confidential clients (Casdoor does this by default and does not offer an option to disable it for confidential clients).
3.  Attempt to log in or link an account via OAuth in Immich.
4.  Observe the error in Immich and the request received by Casdoor.

### Relevant log output

```shell

```
