### ISSUE TITLE
OAuth: DEFAULT STORAGE QUOTA does not permit 0GB accounts

### ISSUE THREAD

**Issue by itskagee** [immich-app/immich#18504]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi,

PR [#17413](https://github.com/immich-app/immich/pull/17413) makes it possible to have 0GB / no-upload accounts.
While this works for users created in Immich (`Quota Size` can be left blank for unlimited, or set to 0 for 0GB accounts), this functionality is not present for users initiated via OAuth using the `Default Storage Quota`.

The flow here is still the old one. The info for `DEFAULT STORAGE QUOTA (GIB)` still says "Quota in GiB to be used when no claim is provided (Enter 0 for unlimited quota)", and it acts as such too.

The field cannot be left blank (defaults to 0 on save), and keeping it at 0 initiates users with an unlimited quota, while instead it should create a user with 0GB quota based on the new flow above.

### The OS that Immich Server is running on

Windows 11 - WSL2

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

#### compose.override.yml
```YAML
services:
  immich-server:
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc
    ports: !override
      - '127.0.0.1:2283:2283'
      - '${TAILSCALE_IP}:2283:2283'
      - '${HOME_IP}:2283:2283'

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
      file: hwaccel.ml.yml
      service: cuda
```

#### compose.yml
`Default`

### Your .env content

```Shell
# PERSONAL CUSTOM
TAILSCALE_IP=<redacted>
HOME_IP=<redacted>
IMMICH_TRUSTED_PROXIES=<redacted>

UPLOAD_LOCATION=/mnt/f/immich/uploads
DB_DATA_LOCATION=./postgres

TZ=<redacted>

IMMICH_VERSION=release

DB_PASSWORD=<redacted>

DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Go to Settings > Authentication Settings > OAuth.
2. Try to change `DEFAULT STORAGE QUOTA (GIB)` to blank. It reverts to 0.
3. Keep it at 0 and create a new user using OAuth without a quota claim.
4. It creates a user with unlimited quota, instead of a 0GB one.

### Relevant log output

```shell

```
