### ISSUE TITLE
postgres 14 vectorchord failes to start.

### ISSUE THREAD

**Issue by BloodBlight** [immich-app/immich#18500]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When updating, following the guide I switched to this image for Postgres:
```
ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
```

It never uses any CPU, memory (1.4MBs) or IO (4KBs) with a single line in the log:
```
2025-05-22T19:31:09.884220787Z Using SSD storage
```

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

services:
  server:
    hostname: server
    environment:
      - REDIS_HOSTNAME=redis
      - DB_PASSWORD=...
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - IMMICH_TELEMETRY_EXCLUDE=all
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - /DFS/Docker-HDD/Immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4gb
      placement:
        constraints:
          - node.platform.os == linux
          - node.role != manager

  machine-learning:
    hostname: machine-learning
    environment:
      - REDIS_HOSTNAME=redis
      - DB_PASSWORD=...
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_DATABASE_NAME=immich
      - IMMICH_TELEMETRY_EXCLUDE=all
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /DFS/Docker-SSD/Immich/model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    ports:
      - 3003:3003
    deploy:
      resources:
        limits:
          memory: 4gb
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
          - node.role != manager

  redis:
    hostname: redis
#    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    deploy:
      resources:
        limits:
          memory: 4gb
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.role != manager

  postgres:
    hostname: postgres
#    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
#    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: .....
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
     # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
     #DB_STORAGE_TYPE: 'HDD'
    volumes:
      - /DFS/Docker-SSD/Immich/postgres:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 4gb
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
          - node.role != manager
```

### Your .env content

```Shell
None.
```

### Reproduction steps

1. Start docker swarm stack.

### Relevant log output

```shell
2025-05-22T19:31:09.884220787Z Using SSD storage
```

### Additional information

Just to be sure, I did try running it on other nodes.  No change.  This is a Docker Swarm deployment.

Docker threads:
root | 2413621 | 2413598 | 0 | 19:47 | ? | 00:00:00 | bash /usr/local/bin/docker-entrypoint.sh postgres -c config_file=/etc/postgresql/postgresql.conf
-- | -- | -- | -- | -- | -- | -- | --
root | 2413693 | 2413621 | 0 | 19:47 | ? | 00:00:00 | find /var/lib/postgresql/data ! -user postgres -exec chown postgres {} +
