### ISSUE TITLE
iOS app backup stuck with 1 remainder with phantom file

### ISSUE THREAD

**Issue by biglilsteve** [immich-app/immich#18503]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

![Image](https://github.com/user-attachments/assets/1181f14d-835f-4da8-a677-0ad7aada4a0e)

I have some sort of phantom file with an October 4, 2020 date that my app gets stuck on. A few notes:
- I don't have any media or files on my phone from that date.
- I also have Google photos - there is no media from October 4, 2020 there either.
- There is no media from October 4, 2020 on my Immich server.
- I've checked all areas of the iOS native photos app, including hidden, recently deleted, etc.
- It doesn't affect any other media uploads.
- It doesn't trigger any logs on my Immich server.
- There are no blacklist/duplicate items in the iOS app Settings > Advanced.

Steps tried:
- Force close app
- Uninstall / reinstall app
- Reboot phone
- Rescan libraries from Immich web interface

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS (GNU/Linux 6.8.0-59-generic x86_64)

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0 build.206

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

  duckdns:
    container_name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/New_York
      - TOKEN=*redacted*
      - SUBDOMAINS=*redacted*
      - VALIDATE_IP=false

    restart: unless-stopped
    # Optional: To see its IP updates in logs, uncomment the next lines temporarily
    # logging:
    #   options:
    #     max-size: "1m"
    #     max-file: "1"

volumes:
  model-cache:
```

### Your .env content

```Shell
# ===============================================================================
# Immich Environment Variables
# ===============================================================================

# Docker specific variables
# -------------------------
# Change the default upload location to a directory on your host machine.
# This is where all your photos and videos will be stored.
# Example: UPLOAD_LOCATION=/mnt/data/immich
UPLOAD_LOCATION=/mnt/data/immich_uploads

# PostgreSQL specific variables
# -----------------------------
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=*redacted*
DB_DATABASE_NAME=immich
DB_PORT=5432
DB_DATA_LOCATION=./pgdata

# Redis specific variables
# ------------------------
REDIS_HOSTNAME=immich_redis
REDIS_PASSWORD=*redacted*
REDIS_PORT=6379

# Machine Learning specific variables
# -----------------------------------
# Leave this empty if you don't want to use the machine learning service.
# Supported values: CPU, CUDA
# Example: MACHINE_LEARNING_GPU_DEVICE=CUDA
MACHINE_LEARNING_GPU_DEVICE=CPU

# Reverse Proxy specific variables
# --------------------------------
# The URL to Immich that you want your users to access.
# This is used by Immich to correctly generate URLs for external access (e.g. shared links).
# Example: IMMICH_SERVER_URL=https://immich.example.com
# Set to http://localhost:2283 for local deployment
IMMICH_SERVER_URL=http://localhost:2283

# Other settings
# --------------
# Log level for the Immich services
# Supported values: fatal, error, warn, info, debug, verbose
LOG_LEVEL=debug
STORAGE_LOG_LEVEL=debug

# Enables Immich's usage telemetry
# This helps the Immich team understand how Immich is being used and prioritize features.
# See https://immich.app/docs/faq#telemetry for more details.
# Supported values: true, false
IMMICH_WEB_PORT=2283
NODE_ENV=production
TZ=America/New_York # This will be automatically detected, but you can override it
PUID=*redacted*
PGID=*redacted*
```

### Reproduction steps

Don't really need to do anything.  The backup screen always falls back to the view you see in the screenshot once uploads are caught up.

### Relevant log output

```shell
No logs are triggered, unfortunately.
```
