### ISSUE TITLE
Wrong Date Quicktime Movie From Nikon Camera

### ISSUE THREAD

**Issue by PRBB28** [immich-app/immich#18516]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Quicktime Movie created by  nikon mirrorless camera, shows wrong date in immich.

### The OS that Immich Server is running on

Proxmox 8.3.4

### Version of Immich Server

1.133.0

### Version of Immich Mobile App

1.33.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /xxxxx/xxxxx/extern_lib:/mnt/media
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/xxxxxx
# The location where your database files are stored
DB_DATA_LOCATION=/home/xxxxx

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
 TZ=Asia/xxxxx

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxxx
DB_DATABASE_NAME=xxxxx
```

### Reproduction steps

1. Create quicktime movie from Nikon Mirrorless Camera
2. Copy to external library
3. Go to immich admin and start scan of external library
4. Browse to movie in immich and look at the info. Date will be wrong.

### Relevant log output

```shell

```

### Additional information

I did a couple of test, experimenting with the metadata.

Here's what I've discovered.
Nikon quicktime does not have Creation Date metadata tag like apple mov, only Create Date. Also it contains MakerNotes tag that has CreateDate and TimeZone that seems to confuse immich.

My Test :

Nikon Movie shot around at 1:31  PM  (TZ=+08:00)
Using External Library

Nikon quicktime  movie                                          - wrong date, immich show 9:31 PM
Nikon quicktime, Added Creation date                 - same as Nikon above 9:31 PM
Nikon quicktime, remove MakerNotes                  - wrong date, immich show 5:31 AM, immich shows date in UTC.
Nikon remove Makernotes, Added CreationDate - date shows correctly in immich (1:31 PM) 👍 

I can only attached one file because of the size limit, so I attached the original file. Please use exiftool to Add Quicktime Creation Date and remove MakersNotes.

https://github.com/user-attachments/assets/5123d13c-05cf-4283-ba15-cff1f883422b
