### ISSUE TITLE
After updating to v1.133.0, photos on the timeline stopped displaying

### ISSUE THREAD

**Issue by cuppabot** [immich-app/immich#18522]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After updating to v1.133.0, photos on the timeline stopped displaying when using Firefox 115.23.1esr on mac os 10.14.

Error: Unable to display elements.

The mobile app works fine and Firefox on mac os 15 also works without complaints.

I cleared the browser cache, disabled browser extensions, the browser console is clean - no errors.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env

    ports:
      - 2283:2283

    depends_on:
      - redis
      - database

    restart: always

    healthcheck:
      disable: false

    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}

    volumes:
      - /mnt/photo@tserv2/cache:/cache

    env_file:
      - .env

    restart: always

    healthcheck:
      disable: false

    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    restart: always

    volumes:
      - /mnt/photo@tserv2/redis:/data

    healthcheck:
      test: redis-cli ping || exit 1

    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env

    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'

    volumes:
      - /mnt/photo@tserv2/database:/var/lib/postgresql/data

    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"


  backup:
    container_name: immich_db_backup
    image: prodrigestivill/postgres-backup-local

    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    env_file:
      - .env

    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 5
      BACKUP_DIR: /db_backup

    volumes:
      - ${DB_BACKUP_LOCATION}:/db_backup

    depends_on:
      - database

    # user: 33:1002

    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/photo@tserv2/immich
# The location where your daily db backup is stored
DB_BACKUP_LOCATION=/mnt/photo@tserv2/db_backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=-skip-
DB_PASSWORD=-skip-

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

Open site.

### Relevant log output

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/1ae8274a-04bb-47b7-9df5-6aeb1017cc87)
