### ISSUE TITLE
v1.33.0 Web UI breaks in older browsers

### ISSUE THREAD

**Issue by milton-lai** [immich-app/immich#18525]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Seems like in the latest version (v1.133.0), the web view breaks when showing the timeline for OLDER web browsers only (Chrome - Version 116.0.5845.187 (Official Build) (x86_64) and Firefox - 115.23.1esr (64-bit)) - iOS app and Chrome 136 is all OK.

I am wondering if the break was intentional or not? I'm not sure which library the change is tied to. Everything was working in the previous version (I think it was v1.132.-)

![Image](https://github.com/user-attachments/assets/4d85da71-a22f-4b2b-b5ff-22a34e345ad2)

It shows an error "Failed to load assets". The JS error is below. 

`hook.js:608 [handleError]: Failed to load assets TypeError: this.changedDateGroups.difference is not a function
    at get existingDateGroups [as existingDateGroups] (DD2z7eE2.js:9:7282)
    at It.addAssets (DD2z7eE2.js:9:10475)
    at DD2z7eE2.js:9:18794
    at async zt.execute (DD2z7eE2.js:1:8547)
    at async it.loadBucket (DD2z7eE2.js:9:18493) TypeError: this.changedDateGroups.difference is not a function
    at get existingDateGroups [as existingDateGroups] (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:7282)
    at It.addAssets (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:10475)
    at http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:18794
    at async zt.execute (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:1:8547)
    at async it.loadBucket (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:18493)`

### The OS that Immich Server is running on

Synology DSM 7.2.2-72806 Update 3

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

1.133.0 build.206

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/Photos/library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Australia/Sydney

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Using either an old mac (Mojave) or find the specific version of Chrome (Version 116.0.5845.187 (Official Build) (x86_64)), access /photos and the issue should appear.

### Relevant log output

```shell
[handleError]: Failed to load assets TypeError: this.changedDateGroups.difference is not a function
    at get existingDateGroups [as existingDateGroups] (DD2z7eE2.js:9:7282)
    at It.addAssets (DD2z7eE2.js:9:10475)
    at DD2z7eE2.js:9:18794
    at async zt.execute (DD2z7eE2.js:1:8547)
    at async it.loadBucket (DD2z7eE2.js:9:18493) TypeError: this.changedDateGroups.difference is not a function
    at get existingDateGroups [as existingDateGroups] (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:7282)
    at It.addAssets (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:10475)
    at http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:18794
    at async zt.execute (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:1:8547)
    at async it.loadBucket (http://192.168.1.111:2283/_app/immutable/chunks/DD2z7eE2.js:9:18493)
```
