### ISSUE TITLE
Activity buttons for shared album (comments, likes) broken

### ISSUE THREAD

**Issue by jenda69** [immich-app/immich#18524]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have an album with a bunch of photos. I've pressed like for some and wrote comments for some.
When displaying the whole album, it shows "♥︎ 💬 40". Then I click on a picture without any like or comment and it changes to "♡︎ 💬" but during the load, it flashes the previous variant and back. This happens every time. It usually ends up with the correct one.
Sometimes it doesn't and shows buttons for the whole album, which then display Activity for the whole album.
And maybe even more rarely, it displayed the correct button without comments and likes, but as soon as I clicked the heart, it changed to the buttons for the whole album and actually liked the whole album instead too...
I can't reproduce these consistently though.

### The OS that Immich Server is running on

Raspbian Bookworm

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/upload:/usr/src/app/upload
      - ${UPLOAD_LOCATION_FAST}/upload/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION_FAST}/upload/upload:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION_SLOW}/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${UPLOAD_LOCATION_FAST}/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION_FAST=/storage-fast/immich
UPLOAD_LOCATION_SLOW=/storage/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

TZ=Europe/Prague
```

### Reproduction steps

1. Open shared album with comments and likes
2. Click image

### Relevant log output

```shell

```
