### ISSUE TITLE
Jobs not being started

### ISSUE THREAD

**Issue by sparx82** [immich-app/immich#18534]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I had setup an environment where I have the API running on my NAS in docker and the microservices as well as ML on my desktop PC. This worked fine. After upgrading to 1.133.0 I observed that the jobs do not get started anymore. To put that assumption on a better base, I started from scratch, deleting the upload directory as well as the database and run everyhting on the NAS at the moment. Given the steps below, the external archive has been scanned but then the extract metadata just does nothing:

![Image](https://github.com/user-attachments/assets/72f3286a-1f89-4aba-b3e5-f69dfde1f9e2)

The logs show no errors.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.133.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-label-Data/Lightroom/PictureExport:/srv/dev-disk-by-label-Data/Lightroom/PictureExport:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
      
    environment:
      #IMMICH_WORKERS_INCLUDE: 'api'
      LETSENCRYPT_HOST: 'immich.rusterholz.me'
      VIRTUAL_HOST: 'immich.rusterholz.me'
    
    networks:
      - DockerNetwork

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      - DockerNetwork

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    #ports:
    #  - '6380:6379'
    restart: always
    networks:
      - DockerNetwork

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    restart: always
    #ports:
    #  - '5432:5432'
    networks:
      - DockerNetwork
    
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/varun-raj/immich-power-tools:latest
    ports:
      - "8001:3000"
    env_file:
      - .env
    networks:
      - DockerNetwork
   
networks:
  DockerNetwork:
    external: true 
    
volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/srv/dev-disk-by-label-Data/Lightroom/Immich_Upload
DB_DATA_LOCATION=/srv/dev-disk-by-label-Data/Oliver/Docker/Immich
IMMICH_VERSION=release
DB_PASSWORD=db_password
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
IMMICH_API_KEY=api_key
IMMICH_URL=http://immich_server:2283
EXTERNAL_IMMICH_URL=https://immich.exturl.me
DB_HOST=immich_postgres
DB_PORT=5432
```

### Reproduction steps

1. Setup everything from scratch
2. Add an external library
3. Scan the library

### Relevant log output

```shell

```
