### ISSUE TITLE
[web] Grid lines shown when zooming into photo

### ISSUE THREAD

**Issue by fish12345** [immich-app/immich#18550]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When zooming into a photo, some grid lines appear. On some images, the lines are even visible without zooming in. I'm not sure whether it's the content of the image that makes the lines pop out more, or whether some images are only affected when zooming in.

I guess the image is tiled somehow to load only the visible parts on the screen.

![Image](https://github.com/user-attachments/assets/e3fe92b7-a1a1-4ff3-8b8d-be27b6dd11b1)

In previous versions these lines where not visible, but I cannot say for sure when it was introduced.

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/data/immich-app/archive:/media/data/immich-app/archive:ro
      - /media/data/immich-app/archive/Nils:/media/data/immich-app/archive/Nils:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    ports:
      - 2283:2283
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always


volumes:
  model-cache:


networks:
  default:
    external: true
    name: scoobydoo
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxx
DB_PASSWORD=xxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/media/data/immich-app/postgres

REDIS_HOSTNAME=immich_redis

PUBLIC_IMMICH_SERVER_URL=https://immich-server:1234
```

### Reproduction steps

1. Open a photo in web view
2. Zoom into image (not necessarily needed but helps to see the issue)
3. Check image for grid lines

### Relevant log output

```shell

```
