### ISSUE TITLE
v1.133.0 main timeline:  first month is all blank

### ISSUE THREAD

**Issue by itsallyours** [immich-app/immich#18564]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

upgraded to v1.133.0

On the home page (/photos), the first bucket (month of May 2025) is all blank.  Unable to click on any of those tiles.  Earlier months are all fine.  If I browse the folders for those same missing pictures, they render fine.

Here is a picture of the blank tiles:

![Image](https://github.com/user-attachments/assets/b5e1afd5-d337-43e2-aced-121492979d04)

The following month is ok:

![Image](https://github.com/user-attachments/assets/1e35a567-d68e-4e5d-b87f-c3ca251f4f28)

This experience only happens on the web (Firefox & Chrome).  The mobile (IOS) seems ok.

### The OS that Immich Server is running on

Linux Mint 22.1 Cinnamon

### Version of Immich Server

v1.133.0 

### Version of Immich Mobile App

v1.133.0 

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - synology:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

      - /home/anthony/mnt/photo:/media/photo:ro
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups      
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
      # - webdav
    restart: no
    healthcheck:
      disable: false
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "immich" # Optional
      tsdproxy.container_port: 2283 # Optional   
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: no
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: no

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
     # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
     # DB_STORAGE_TYPE: 'HDD'      
    #user: root
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library

THUMB_LOCATION=./library/thumbs
ENCODED_VIDEO_LOCATION=./library/encoded-video
PROFILE_LOCATION=./library/profile
BACKUP_LOCATION=./library/backups


# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxx
DB_PASSWORD=xxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
IMMICH_IGNORE_MOUNT_CHECK_ERRORS=false
```

### Reproduction steps

1. upgraded to latest
2. navigated to /photos
3. bad tiles (see pictures above)
...

### Relevant log output

```shell
/api/timeline/buckets?visibility=timeline&withPartners=true&withStacked=true
[{"timeBucket":"2025-05-01T00:00:00.000Z","count":514},{"timeBucket":"2025-04-01T00:00:00.000Z","count":1229},{"timeBucket":"2025-03-01T00:00:00.000Z","count":953},{"timeBucket":"2025-02-01T00:00:00.000Z","count":33},{"timeBucket":"2025-01-01T00:00:00.000Z","count":4847},{"timeBucket":"2024-12-01T00:00:00.000Z","count":447},{"timeBucket":"2024-11-01T00:00:00.000Z","count":420},{"timeBucket":"2024-10-01T00:00:00.000Z","count":602},{"timeBucket":"2024-09-01T00:00:00.000Z","count":111},{"timeBucket":"2024-08-01T00:00:00.000Z","count":50},{"timeBucket":"2024-07-01T00:00:00.000Z","count":976},{"timeBucket":"2024-06-01T00:00:00.000Z","count":4115},{"timeBucket":"2024-05-01T00:00:00.000Z","count":1662},{"timeBucket":"2024-04-01T00:00:00.000Z","count":1433},{"timeBucket":"2024-03-01T00:00:00.000Z","count":992},{"timeBucket":"2024-02-01T00:00:00.000Z","count":196},{"timeBucket":"2024-01-01T00:00:00.000Z","count":1107},{"timeBucket":"2023-12-01T00:00:00.000Z","count":657},{"timeBucket":"2023-11-01T00:00:00.000Z","count":408},{"timeBucket":"2023-10-01T00:00:00.000Z","count":694},{"timeBucket":"2023-09-01T00:00:00.000Z","count":467},{"timeBucket":"2023-08-01T00:00:00.000Z","count":649},{"timeBucket":"2023-07-01T00:00:00.000Z","count":721},{"timeBucket":"2023-06-01T00:00:00.000Z","count":1441},{"timeBucket":"2023-05-01T00:00:00.000Z","count":3479},{"timeBucket":"2023-04-01T00:00:00.000Z","count":931},{"timeBucket":"2023-03-01T00:00:00.000Z","count":4851},{"timeBucket":"2023-02-01T00:00:00.000Z","count":686},{"timeBucket":"2023-01-01T00:00:00.000Z","count":1745},{"timeBucket":"2022-12-01T00:00:00.000Z","count":440},{"timeBucket":"2022-11-01T00:00:00.000Z","count":627},{"timeBucket":"2022-10-01T00:00:00.000Z","count":788},{"timeBucket":"2022-09-01T00:00:00.000Z","count":1118},{"timeBucket":"2022-08-01T00:00:00.000Z","count":1286},{"timeBucket":"2022-07-01T00:00:00.000Z","count":3918},{"timeBucket":"2022-06-01T00:00:00.000Z","count":6260},{"timeBucket":"2022-05-01T00:00:00.000Z","count":1610},{"timeBucket":"2022-04-01T00:00:00.000Z","count":1889},{"timeBucket":"2022-03-01T00:00:00.000Z","count":867},{"timeBucket":"2022-02-01T00:00:00.000Z","count":220},{"timeBucket":"2022-01-01T00:00:00.000Z","count":140},{"timeBucket":"2021-12-01T00:00:00.000Z","count":466},{"timeBucket":"2021-11-01T00:00:00.000Z","count":533},{"timeBucket":"2021-10-01T00:00:00.000Z","count":575},{"timeBucket":"2021-09-01T00:00:00.000Z","count":1248},{"timeBucket":"2021-08-01T00:00:00.000Z","count":740},{"timeBucket":"2021-07-01T00:00:00.000Z","count":1806},{"timeBucket":"2021-06-01T00:00:00.000Z","count":449},{"timeBucket":"2021-05-01T00:00:00.000Z","count":2280},{"timeBucket":"2021-04-01T00:00:00.000Z","count":1033},{"timeBucket":"2021-03-01T00:00:00.000Z","count":1335},{"timeBucket":"2021-02-01T00:00:00.000Z","count":2171},{"timeBucket":"2021-01-01T00:00:00.000Z","count":987},{"timeBucket":"2020-12-01T00:00:00.000Z","count":1244},{"timeBucket":"2020-11-01T00:00:00.000Z","count":826},{"timeBucket":"2020-10-01T00:00:00.000Z","count":2967},{"timeBucket":"2020-09-01T00:00:00.000Z","count":2452},{"timeBucket":"2020-08-01T00:00:00.000Z","count":2131},{"timeBucket":"2020-07-01T00:00:00.000Z","count":1249},{"timeBucket":"2020-06-01T00:00:00.000Z","count":3748},{"timeBucket":"2020-05-01T00:00:00.000Z","count":1677},{"timeBucket":"2020-04-01T00:00:00.000Z","count":1290},{"timeBucket":"2020-03-01T00:00:00.000Z","count":749},{"timeBucket":"2020-02-01T00:00:00.000Z","count":2585},{"timeBucket":"2020-01-01T00:00:00.000Z","count":907},{"timeBucket":"2019-12-01T00:00:00.000Z","count":3424},{"timeBucket":"2019-11-01T00:00:00.000Z","count":2908},{"timeBucket":"2019-10-01T00:00:00.000Z","count":4517},{"timeBucket":"2019-09-01T00:00:00.000Z","count":4104},{"timeBucket":"2019-08-01T00:00:00.000Z","count":3656},{"timeBucket":"2019-07-01T00:00:00.000Z","count":3748},{"timeBucket":"2019-06-01T00:00:00.000Z","count":1164},{"timeBucket":"2019-05-01T00:00:00.000Z","count":1970},{"timeBucket":"2019-04-01T00:00:00.000Z","count":2203},{"timeBucket":"2019-03-01T00:00:00.000Z","count":1864},{"timeBucket":"2019-02-01T00:00:00.000Z","count":3722},{"timeBucket":"2019-01-01T00:00:00.000Z","count":326},{"timeBucket":"2018-12-01T00:00:00.000Z","count":2126},{"timeBucket":"2018-11-01T00:00:00.000Z","count":895},{"timeBucket":"2018-10-01T00:00:00.000Z","count":1917},{"timeBucket":"2018-09-01T00:00:00.000Z","count":736},{"timeBucket":"2018-08-01T00:00:00.000Z","count":2282},{"timeBucket":"2018-07-01T00:00:00.000Z","count":1825},{"timeBucket":"2018-06-01T00:00:00.000Z","count":2485},{"timeBucket":"2018-05-01T00:00:00.000Z","count":2927},{"timeBucket":"2018-04-01T00:00:00.000Z","count":2319},{"timeBucket":"2018-03-01T00:00:00.000Z","count":672},{"timeBucket":"2018-02-01T00:00:00.000Z","count":597},{"timeBucket":"2018-01-01T00:00:00.000Z","count":368},{"timeBucket":"2017-12-01T00:00:00.000Z","count":1161},{"timeBucket":"2017-11-01T00:00:00.000Z","count":629},{"timeBucket":"2017-10-01T00:00:00.000Z","count":1417},{"timeBucket":"2017-09-01T00:00:00.000Z","count":962},{"timeBucket":"2017-08-01T00:00:00.000Z","count":1102},{"timeBucket":"2017-07-01T00:00:00.000Z","count":1936},{"timeBucket":"2017-06-01T00:00:00.000Z","count":3155},{"timeBucket":"2017-05-01T00:00:00.000Z","count":1379},{"timeBucket":"2017-04-01T00:00:00.000Z","count":1492},{"timeBucket":"2017-03-01T00:00:00.000Z","count":532},{"timeBucket":"2017-02-01T00:00:00.000Z","count":485},{"timeBucket":"2017-01-01T00:00:00.000Z","count":259},{"timeBucket":"2016-12-01T00:00:00.000Z","count":1240},{"timeBucket":"2016-11-01T00:00:00.000Z","count":462},{"timeBucket":"2016-10-01T00:00:00.000Z","count":1831},{"timeBucket":"2016-09-01T00:00:00.000Z","count":754},{"timeBucket":"2016-08-01T00:00:00.000Z","count":699},{"timeBucket":"2016-07-01T00:00:00.000Z","count":994},{"timeBucket":"2016-06-01T00:00:00.000Z","count":888},{"timeBucket":"2016-05-01T00:00:00.000Z","count":2027},{"timeBucket":"2016-04-01T00:00:00.000Z","count":812},{"timeBucket":"2016-03-01T00:00:00.000Z","count":1268},{"timeBucket":"2016-02-01T00:00:00.000Z","count":919},{"timeBucket":"2016-01-01T00:00:00.000Z","count":157},{"timeBucket":"2015-12-01T00:00:00.000Z","count":1201},{"timeBucket":"2015-11-01T00:00:00.000Z","count":508},{"timeBucket":"2015-10-01T00:00:00.000Z","count":1024},{"timeBucket":"2015-09-01T00:00:00.000Z","count":647},{"timeBucket":"2015-08-01T00:00:00.000Z","count":776},{"timeBucket":"2015-07-01T00:00:00.000Z","count":591},{"timeBucket":"2015-06-01T00:00:00.000Z","count":2521},{"timeBucket":"2015-05-01T00:00:00.000Z","count":370},{"timeBucket":"2015-04-01T00:00:00.000Z","count":1267},{"timeBucket":"2015-03-01T00:00:00.000Z","count":880},{"timeBucket":"2015-02-01T00:00:00.000Z","count":1523},{"timeBucket":"2015-01-01T00:00:00.000Z","count":369},{"timeBucket":"2014-12-01T00:00:00.000Z","count":2447},{"timeBucket":"2014-11-01T00:00:00.000Z","count":512},{"timeBucket":"2014-10-01T00:00:00.000Z","count":3217},{"timeBucket":"2014-09-01T00:00:00.000Z","count":2516},{"timeBucket":"2014-08-01T00:00:00.000Z","count":2430},{"timeBucket":"2014-07-01T00:00:00.000Z","count":3529},{"timeBucket":"2014-06-01T00:00:00.000Z","count":1140},{"timeBucket":"2014-05-01T00:00:00.000Z","count":1702},{"timeBucket":"2014-04-01T00:00:00.000Z","count":1176},{"timeBucket":"2014-03-01T00:00:00.000Z","count":592},{"timeBucket":"2014-02-01T00:00:00.000Z","count":443},{"timeBucket":"2014-01-01T00:00:00.000Z","count":440},{"timeBucket":"2013-12-01T00:00:00.000Z","count":2450},{"timeBucket":"2013-11-01T00:00:00.000Z","count":2481},{"timeBucket":"2013-10-01T00:00:00.000Z","count":3457},{"timeBucket":"2013-09-01T00:00:00.000Z","count":2740},{"timeBucket":"2013-08-01T00:00:00.000Z","count":2267},{"timeBucket":"2013-07-01T00:00:00.000Z","count":1369},{"timeBucket":"2013-06-01T00:00:00.000Z","count":696},{"timeBucket":"2013-05-01T00:00:00.000Z","count":1677},{"timeBucket":"2013-04-01T00:00:00.000Z","count":909},{"timeBucket":"2013-03-01T00:00:00.000Z","count":1679},{"timeBucket":"2013-02-01T00:00:00.000Z","count":852},{"timeBucket":"2013-01-01T00:00:00.000Z","count":1042},{"timeBucket":"2012-12-01T00:00:00.000Z","count":2542},{"timeBucket":"2012-11-01T00:00:00.000Z","count":1649},{"timeBucket":"2012-10-01T00:00:00.000Z","count":1247},{"timeBucket":"2012-09-01T00:00:00.000Z","count":1185},{"timeBucket":"2012-08-01T00:00:00.000Z","count":1178},{"timeBucket":"2012-07-01T00:00:00.000Z","count":2431},{"timeBucket":"2012-06-01T00:00:00.000Z","count":1691},{"timeBucket":"2012-05-01T00:00:00.000Z","count":633},{"timeBucket":"2012-04-01T00:00:00.000Z","count":1822},{"timeBucket":"2012-03-01T00:00:00.000Z","count":1025},{"timeBucket":"2012-02-01T00:00:00.000Z","count":252},{"timeBucket":"2012-01-01T00:00:00.000Z","count":507},{"timeBucket":"2011-12-01T00:00:00.000Z","count":1071},{"timeBucket":"2011-11-01T00:00:00.000Z","count":821},{"timeBucket":"2011-10-01T00:00:00.000Z","count":1452},{"timeBucket":"2011-09-01T00:00:00.000Z","count":741},{"timeBucket":"2011-08-01T00:00:00.000Z","count":2231},{"timeBucket":"2011-07-01T00:00:00.000Z","count":1035},{"timeBucket":"2011-06-01T00:00:00.000Z","count":1972},{"timeBucket":"2011-05-01T00:00:00.000Z","count":1166},{"timeBucket":"2011-04-01T00:00:00.000Z","count":1144},{"timeBucket":"2011-03-01T00:00:00.000Z","count":202},{"timeBucket":"2011-02-01T00:00:00.000Z","count":173},{"timeBucket":"2011-01-01T00:00:00.000Z","count":285},{"timeBucket":"2010-12-01T00:00:00.000Z","count":1061},{"timeBucket":"2010-11-01T00:00:00.000Z","count":763},{"timeBucket":"2010-10-01T00:00:00.000Z","count":1129},{"timeBucket":"2010-09-01T00:00:00.000Z","count":435},{"timeBucket":"2010-08-01T00:00:00.000Z","count":1143},{"timeBucket":"2010-07-01T00:00:00.000Z","count":1279},{"timeBucket":"2010-06-01T00:00:00.000Z","count":1184},{"timeBucket":"2010-05-01T00:00:00.000Z","count":713},{"timeBucket":"2010-04-01T00:00:00.000Z","count":1103},{"timeBucket":"2010-03-01T00:00:00.000Z","count":652},{"timeBucket":"2010-02-01T00:00:00.000Z","count":325},{"timeBucket":"2010-01-01T00:00:00.000Z","count":750},{"timeBucket":"2009-12-01T00:00:00.000Z","count":1273},{"timeBucket":"2009-11-01T00:00:00.000Z","count":1750},{"timeBucket":"2009-10-01T00:00:00.000Z","count":1419},{"timeBucket":"2009-09-01T00:00:00.000Z","count":861},{"timeBucket":"2009-08-01T00:00:00.000Z","count":1123},{"timeBucket":"2009-07-01T00:00:00.000Z","count":427},{"timeBucket":"2009-06-01T00:00:00.000Z","count":1708},{"timeBucket":"2009-05-01T00:00:00.000Z","count":737},{"timeBucket":"2009-04-01T00:00:00.000Z","count":423},{"timeBucket":"2009-03-01T00:00:00.000Z","count":374},{"timeBucket":"2009-02-01T00:00:00.000Z","count":75},{"timeBucket":"2009-01-01T00:00:00.000Z","count":647},{"timeBucket":"2008-12-01T00:00:00.000Z","count":988},{"timeBucket":"2008-11-01T00:00:00.000Z","count":281},{"timeBucket":"2008-10-01T00:00:00.000Z","count":389},{"timeBucket":"2008-09-01T00:00:00.000Z","count":232},{"timeBucket":"2008-08-01T00:00:00.000Z","count":619},{"timeBucket":"2008-07-01T00:00:00.000Z","count":471},{"timeBucket":"2008-06-01T00:00:00.000Z","count":112},{"timeBucket":"2008-05-01T00:00:00.000Z","count":775},{"timeBucket":"2008-04-01T00:00:00.000Z","count":800},{"timeBucket":"2008-03-01T00:00:00.000Z","count":753},{"timeBucket":"2008-02-01T00:00:00.000Z","count":389},{"timeBucket":"2008-01-01T00:00:00.000Z","count":220},{"timeBucket":"2007-12-01T00:00:00.000Z","count":376},{"timeBucket":"2007-11-01T00:00:00.000Z","count":280},{"timeBucket":"2007-10-01T00:00:00.000Z","count":581},{"timeBucket":"2007-09-01T00:00:00.000Z","count":196},{"timeBucket":"2007-08-01T00:00:00.000Z","count":1030},{"timeBucket":"2007-07-01T00:00:00.000Z","count":557},{"timeBucket":"2007-06-01T00:00:00.000Z","count":770},{"timeBucket":"2007-05-01T00:00:00.000Z","count":891},{"timeBucket":"2007-04-01T00:00:00.000Z","count":1742},{"timeBucket":"2007-03-01T00:00:00.000Z","count":512},{"timeBucket":"2007-02-01T00:00:00.000Z","count":281},{"timeBucket":"2007-01-01T00:00:00.000Z","count":227},{"timeBucket":"2006-12-01T00:00:00.000Z","count":702},{"timeBucket":"2006-11-01T00:00:00.000Z","count":236},{"timeBucket":"2006-10-01T00:00:00.000Z","count":212},{"timeBucket":"2006-09-01T00:00:00.000Z","count":54},{"timeBucket":"2006-08-01T00:00:00.000Z","count":907},{"timeBucket":"2006-07-01T00:00:00.000Z","count":199},{"timeBucket":"2006-06-01T00:00:00.000Z","count":364},{"timeBucket":"2006-05-01T00:00:00.000Z","count":115},{"timeBucket":"2006-04-01T00:00:00.000Z","count":522},{"timeBucket":"2006-03-01T00:00:00.000Z","count":323},{"timeBucket":"2006-02-01T00:00:00.000Z","count":48},{"timeBucket":"2006-01-01T00:00:00.000Z","count":71},{"timeBucket":"2005-12-01T00:00:00.000Z","count":174},{"timeBucket":"2005-11-01T00:00:00.000Z","count":60},{"timeBucket":"2005-10-01T00:00:00.000Z","count":259},{"timeBucket":"2005-09-01T00:00:00.000Z","count":129},{"timeBucket":"2005-08-01T00:00:00.000Z","count":215},{"timeBucket":"2005-07-01T00:00:00.000Z","count":222},{"timeBucket":"2005-06-01T00:00:00.000Z","count":120},{"timeBucket":"2005-05-01T00:00:00.000Z","count":155},{"timeBucket":"2005-04-01T00:00:00.000Z","count":392},{"timeBucket":"2005-03-01T00:00:00.000Z","count":263},{"timeBucket":"2005-02-01T00:00:00.000Z","count":48},{"timeBucket":"2005-01-01T00:00:00.000Z","count":104},{"timeBucket":"2004-12-01T00:00:00.000Z","count":322},{"timeBucket":"2004-11-01T00:00:00.000Z","count":49},{"timeBucket":"2004-10-01T00:00:00.000Z","count":313},{"timeBucket":"2004-09-01T00:00:00.000Z","count":121},{"timeBucket":"2004-08-01T00:00:00.000Z","count":147},{"timeBucket":"2004-07-01T00:00:00.000Z","count":208},{"timeBucket":"2004-06-01T00:00:00.000Z","count":270},{"timeBucket":"2004-05-01T00:00:00.000Z","count":231},{"timeBucket":"2004-04-01T00:00:00.000Z","count":163},{"timeBucket":"2004-03-01T00:00:00.000Z","count":153},{"timeBucket":"2004-02-01T00:00:00.000Z","count":6},{"timeBucket":"2004-01-01T00:00:00.000Z","count":85},{"timeBucket":"2003-12-01T00:00:00.000Z","count":131},{"timeBucket":"2003-11-01T00:00:00.000Z","count":58},{"timeBucket":"2003-10-01T00:00:00.000Z","count":238},{"timeBucket":"2003-09-01T00:00:00.000Z","count":1014},{"timeBucket":"2003-08-01T00:00:00.000Z","count":184},{"timeBucket":"2003-07-01T00:00:00.000Z","count":52},{"timeBucket":"2003-06-01T00:00:00.000Z","count":126},{"timeBucket":"2003-05-01T00:00:00.000Z","count":110},{"timeBucket":"2003-04-01T00:00:00.000Z","count":232},{"timeBucket":"2003-03-01T00:00:00.000Z","count":145},{"timeBucket":"2003-02-01T00:00:00.000Z","count":73},{"timeBucket":"2003-01-01T00:00:00.000Z","count":76},{"timeBucket":"2002-12-01T00:00:00.000Z","count":143},{"timeBucket":"2002-11-01T00:00:00.000Z","count":152},{"timeBucket":"2002-10-01T00:00:00.000Z","count":440},{"timeBucket":"2002-09-01T00:00:00.000Z","count":31},{"timeBucket":"2002-08-01T00:00:00.000Z","count":49},{"timeBucket":"2002-07-01T00:00:00.000Z","count":117},{"timeBucket":"2002-06-01T00:00:00.000Z","count":237},{"timeBucket":"2002-05-01T00:00:00.000Z","count":11},{"timeBucket":"2002-04-01T00:00:00.000Z","count":42},{"timeBucket":"2002-03-01T00:00:00.000Z","count":141},{"timeBucket":"2002-02-01T00:00:00.000Z","count":101},{"timeBucket":"2002-01-01T00:00:00.000Z","count":55},{"timeBucket":"2001-12-01T00:00:00.000Z","count":17},{"timeBucket":"2001-11-01T00:00:00.000Z","count":96},{"timeBucket":"2001-10-01T00:00:00.000Z","count":90},{"timeBucket":"2001-08-01T00:00:00.000Z","count":86},{"timeBucket":"2001-07-01T00:00:00.000Z","count":39},{"timeBucket":"2001-06-01T00:00:00.000Z","count":24},{"timeBucket":"2001-04-01T00:00:00.000Z","count":33},{"timeBucket":"2001-03-01T00:00:00.000Z","count":33},{"timeBucket":"2001-01-01T00:00:00.000Z","count":26},{"timeBucket":"2000-12-01T00:00:00.000Z","count":50},{"timeBucket":"2000-11-01T00:00:00.000Z","count":124},{"timeBucket":"2000-10-01T00:00:00.000Z","count":72},{"timeBucket":"2000-09-01T00:00:00.000Z","count":85},{"timeBucket":"2000-08-01T00:00:00.000Z","count":48},{"timeBucket":"2000-05-01T00:00:00.000Z","count":26},{"timeBucket":"2000-04-01T00:00:00.000Z","count":44},{"timeBucket":"2000-03-01T00:00:00.000Z","count":22},{"timeBucket":"1970-01-01T00:00:00.000Z","count":6}]
```
