### ISSUE TITLE
Crash while processing assets related to DB

### ISSUE THREAD

**Issue by niwla23** [immich-app/immich#18562]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I just had immich crash the first time ever while processing assets. Seems to be some issue with the DB connection, here are the logs of both app and db.

### The OS that Immich Server is running on

Raspberry Pi OS Bookworm

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

-

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3"
services:
  app:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
        #      - /mnt/photos:/nas_import:ro
    env_file:
      - .env
    ports:
      - 2283:3001

    networks:
      - traefik
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`REDACTED`)"
      - "traefik.http.routers.immich.tls.certresolver=le_main"
        #- "traefik.http.middlewares.immich-ipallowlist.ipallowlist.sourcerange=129.0.0.1/32"
      - "traefik.http.routers.immich.middlewares=nopublic@file"

    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - internal

  redis:
    image: docker.io/redis:6.2-alpine@sha256:e3b17ba9479deec4b7d1eeec1548a253acc5374d68d3b27937fcfe4df8d18c7e
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - internal

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

volumes:
  model-cache:


networks:
  internal:
  traefik:
    name: "traefik"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.133.1

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=-

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Not sure, it just crashed out of the blue while processing uploaded assets.

### Relevant log output

```shell
DB:

database-1  | 2025-05-23 23:37:44.950 UTC [2079] LOG:  could not receive data from client: Connection reset by peer
database-1  | 2025-05-23 23:37:44.950 UTC [2079] LOG:  unexpected EOF on client connection with an open transaction
database-1  | 2025-05-23 23:37:44.950 UTC [2078] LOG:  could not receive data from client: Connection reset by peer
database-1  | 2025-05-23 23:37:44.950 UTC [2078] LOG:  unexpected EOF on client connection with an open transaction
database-1  | 2025-05-23 23:37:44.950 UTC [2077] LOG:  could not receive data from client: Connection reset by peer
database-1  | 2025-05-23 23:37:44.953 UTC [2080] LOG:  unexpected EOF on client connection with an open transaction


app

app-1  | [Nest] 7  - 05/24/2025, 1:26:24 AM     LOG [Microservices:MediaService] Successfully encoded 9ae737f9-2b57-4b6f-9055-0bd14b6201ae
app-1  | [Nest] 7  - 05/24/2025, 1:26:24 AM     LOG [Microservices:MediaService] Transcoding video 0a9497e8-7154-4c60-8602-43f32195922b without hardware acceleration
app-1  | [Nest] 7  - 05/24/2025, 1:26:43 AM     LOG [Microservices:MediaService] Successfully encoded 0a9497e8-7154-4c60-8602-43f32195922b
app-1  | [Nest] 7  - 05/24/2025, 1:26:43 AM     LOG [Microservices:MediaService] Transcoding video 7f04c762-24c0-4a5e-896e-c99f608153f0 without hardware acceleration
app-1  | [Nest] 17  - 05/24/2025, 1:26:58 AM     LOG [Api:EventRepository] Websocket Disconnect: 1CK1oTz4fJPl994hAAAV
app-1  | [Nest] 17  - 05/24/2025, 1:27:00 AM     LOG [Api:EventRepository] Websocket Connect:    AyhCZ4CRERnEeycsAAAX
app-1  | [Nest] 17  - 05/24/2025, 1:27:38 AM     LOG [Api:EventRepository] Websocket Disconnect: j_g91bYS9g_4wYMzAAAR
app-1  | [Nest] 17  - 05/24/2025, 1:27:38 AM     LOG [Api:EventRepository] Websocket Connect:    ncYFxP8ZvlsXqvYDAAAZ
app-1  | [Nest] 7  - 05/24/2025, 1:27:52 AM     LOG [Microservices:MediaService] Successfully encoded 7f04c762-24c0-4a5e-896e-c99f608153f0
app-1  | [Nest] 7  - 05/24/2025, 1:27:52 AM     LOG [Microservices:MediaService] Transcoding video a87eb711-723b-4ad2-acc2-a2c98f757a10 without hardware acceleration
app-1  | [Nest] 7  - 05/24/2025, 1:29:51 AM     LOG [Microservices:MediaService] Successfully encoded a87eb711-723b-4ad2-acc2-a2c98f757a10
app-1  | [Nest] 7  - 05/24/2025, 1:29:51 AM     LOG [Microservices:MediaService] Transcoding video 084a3ace-14b8-4f84-a922-f99e6943d5ae without hardware acceleration
app-1  | [Nest] 7  - 05/24/2025, 1:32:17 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 9ffb9ed9-5a0f-41b4-990d-5d160d716d51
app-1  | [Nest] 7  - 05/24/2025, 1:32:25 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 4369ea8a-214d-4b27-8000-c9de83532cfc
app-1  | [Nest] 7  - 05/24/2025, 1:32:26 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 0cf8b57d-60a3-4e1b-a2b0-6fc2eb3dcf72
app-1  | [Nest] 7  - 05/24/2025, 1:32:36 AM     LOG [Microservices:PersonService] Detected 3 new faces in asset 541c9c3d-a237-4c5c-9e53-f400cb502316
app-1  | [Nest] 7  - 05/24/2025, 1:32:38 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 6b1ada46-df13-47b9-a69b-349f70bc6a52
app-1  | [Nest] 7  - 05/24/2025, 1:32:49 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 7ab447ee-a9f1-441a-a6d9-230b0ff34ece
app-1  | [Nest] 7  - 05/24/2025, 1:33:01 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset b1e29068-1a1b-4447-9142-27d0adbf9827
app-1  | [Nest] 7  - 05/24/2025, 1:33:11 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 1664b67c-e51b-4265-98c3-f62163bf574c
app-1  | [Nest] 7  - 05/24/2025, 1:33:13 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 666761ed-ab2d-498c-ab77-0bec8300caa3
app-1  | [Nest] 7  - 05/24/2025, 1:33:34 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 16fefa69-efcf-49a0-9e35-1afe883b01f1
app-1  | [Nest] 7  - 05/24/2025, 1:33:45 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 6bec8bf3-9cd9-4a56-8a22-d38d2e2d6477
app-1  | [Nest] 7  - 05/24/2025, 1:34:06 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 407a008b-fbdf-480a-b1f0-3cff5aee89e1
app-1  | [Nest] 7  - 05/24/2025, 1:34:21 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 9e9c9131-1acd-40fe-a2d4-3b93240806cd
app-1  | [Nest] 7  - 05/24/2025, 1:34:27 AM     LOG [Microservices:PersonService] Detected 18 new faces in asset 4ca301fd-7393-4423-9bb9-21cf0e8f33cb
app-1  | [Nest] 7  - 05/24/2025, 1:34:39 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset e5437765-76f7-4107-93ef-e550a7b3190c
app-1  | [Nest] 7  - 05/24/2025, 1:34:42 AM     LOG [Microservices:PersonService] Detected 4 new faces in asset e6b4dde0-f076-4f99-ae45-41ecf8d90cac
app-1  | [Nest] 7  - 05/24/2025, 1:35:00 AM     LOG [Microservices:PersonService] Detected 4 new faces in asset a7d40525-90a7-48c3-b6cc-3b2b0f2b7fb6
app-1  | [Nest] 7  - 05/24/2025, 1:35:08 AM     LOG [Microservices:PersonService] Detected 5 new faces in asset a8b0df79-5d6f-49cb-b57d-1d2ae021b755
app-1  | [Nest] 7  - 05/24/2025, 1:35:24 AM     LOG [Microservices:PersonService] Detected 5 new faces in asset 3f6466b9-6f4d-4a7c-afb4-10ea74c80fa8
app-1  | [Nest] 7  - 05/24/2025, 1:35:53 AM     LOG [Microservices:PersonService] Detected 11 new faces in asset e662e7ab-9010-4ea0-ad18-e6c78f5615f2
app-1  | [Nest] 7  - 05/24/2025, 1:36:17 AM     LOG [Microservices:PersonService] Detected 11 new faces in asset 295a7740-d43c-4245-ba7c-da2bfb34c23b
app-1  | [Nest] 7  - 05/24/2025, 1:36:35 AM     LOG [Microservices:PersonService] Detected 3 new faces in asset 0e63fef1-39dc-4320-958a-73c0d1f132ec
app-1  | [Nest] 7  - 05/24/2025, 1:36:36 AM     LOG [Microservices:PersonService] Detected 11 new faces in asset 09005eeb-5ff3-4941-a8dd-ba8e6f863053
app-1  | [Nest] 7  - 05/24/2025, 1:36:49 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset 1dd2833e-6910-4d03-9a93-113343a7ad32
app-1  | [Nest] 7  - 05/24/2025, 1:36:59 AM     LOG [Microservices:PersonService] Detected 5 new faces in asset 05ba92f4-2580-40c1-b1fa-5ee3ed3aa0c7
app-1  | [Nest] 7  - 05/24/2025, 1:37:09 AM     LOG [Microservices:PersonService] Detected 3 new faces in asset cad8d31f-3e19-4541-9ebc-fda1e4141a5c
app-1  | [Nest] 7  - 05/24/2025, 1:37:11 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset f7faacc2-1b92-4f0d-ade5-fa5e6e389277
app-1  | [Nest] 7  - 05/24/2025, 1:37:22 AM     LOG [Microservices:PersonService] Detected 2 new faces in asset c96f75f2-6529-45f0-bf10-5947d63bf6c5
app-1  | [Nest] 7  - 05/24/2025, 1:37:23 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset ebf66576-ceff-406e-a82a-6f41faa6440e
app-1  | [Nest] 7  - 05/24/2025, 1:37:33 AM     LOG [Microservices:PersonService] Detected 1 new faces in asset 6a6513c0-fec0-4382-a740-fa6b8dcac336
app-1  | /usr/src/app/node_modules/postgres/cjs/src/connection.js:388
app-1  |     if (!query || typeof query !== 'object' || !query.reject) throw err
app-1  |                                                               ^
app-1  |
app-1  | TypeError: Cannot read properties of undefined (reading '0')
app-1  |     at build (/usr/src/app/node_modules/postgres/cjs/src/connection.js:223:42)
app-1  |     at execute (/usr/src/app/node_modules/postgres/cjs/src/connection.js:167:7)
app-1  |     at ReadyForQuery (/usr/src/app/node_modules/postgres/cjs/src/connection.js:541:27)
app-1  |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
app-1  |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
app-1  |     at Socket.emit (node:events:518:28)
app-1  |     at addChunk (node:internal/streams/readable:561:12)
app-1  |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
app-1  |     at Readable.push (node:internal/streams/readable:392:5)
app-1  |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
app-1  |
```
