### ISSUE TITLE
Immich not starting and postgres stuck on DELETE with 100% cpu load after upgrade to 1.133.X

### ISSUE THREAD

**Issue by harrim4n** [immich-app/immich#18582]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I upgraded immich yesterday from I think it was 1.130.X to 1.133.X (first it was .0 and then later .1).
After the changes to the docker compose file, I restarted the containers as usual and I could see in the logs that some migrations etc. were applied.
However, the web service never came back up, I have tried restarting the containers several times now.
The latest run has been up for ~17 hours.
I cannot see any error messages in the container logs. The only output from the server container is below.

After that, nothing happens anymore. The only other thing that I can see is that some postgres process is doing some task that is taking up 100% of one core, for almost 17 hours now. I don't see any relevant log entries of the DB container.

![Image](https://github.com/user-attachments/assets/4823be68-9caa-4baa-ad2d-cad5161ccae5)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

n.a.

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich-app

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/USERNAME/pictures:/mnt/pictures:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/USERNAME/immich-lib

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=XXX
DB_PASSWORD=XXX

# The values below this line do not need to be changed
###################################################################################
#DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

#REDIS_HOSTNAME=immich_redis
IMMICH_LOG_LEVEL=debug
```

### Reproduction steps

1. Make changes required by 1.133.X release to docker-compose.yml file
2. docker compose pull
3. docker compose up

### Relevant log output

```shell
Initializing Immich v1.133.1
DEBUG: cgroup v2 detected.
DEBUG: No CPU limits set.
Detected CPU Cores: 16
Starting api worker
Starting microservices worker
[Nest] 11  - 05/23/2025, 10:50:40 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 11  - 05/23/2025, 10:50:40 PM     LOG [Microservices:DatabaseRepository] targetLists=256, current=256 for face_index of 235305 rows
[Nest] 18  - 05/23/2025, 10:50:40 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 11  - 05/23/2025, 10:50:40 PM     LOG [Microservices:DatabaseRepository] targetLists=1024, current=1024 for clip_index of 520020 rows
[Nest] 11  - 05/23/2025, 10:50:40 PM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
```
