### ISSUE TITLE
after v1.133.1 update, immich-server "unhealthy"

### ISSUE THREAD

**Issue by mglakner** [immich-app/immich#18595]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

just updated to [v1.133.0] and now Immich container wont start, just get "unhealthy" in portainer

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#     extends:
#       file: hwaccel.transcoding.yml
#       service: cpu quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
    - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ./library:/usr/src/app/upload #ORIGINAL
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
      
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    ports:
      - 3003:3003
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0    
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data

    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
DB_DATA_LOCATION=./database
IMMICH_VERSION=v1.133.1
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Change immich version to "release" in env, start
2. Change immich version to "v.1.133.0" in env, start
3. Change immich version to "v.1.133.1" in env, start
...

### Relevant log output

```shell
Starting api worker
Starting microservices worker
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:DatabaseRepository] targetLists=256, current=256 for clip_index of 152202 rows
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:DatabaseRepository] targetLists=256, current=256 for face_index of 147543 rows
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:DatabaseRepository] Running migrations, this may take a while
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:MetadataService] Bootstrapping metadata service
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:MetadataService] Initializing metadata service
[Nest] 7  - 05/24/2025, 6:21:10 PM     LOG [Microservices:MapRepository] Initializing metadata repository
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:DatabaseRepository] targetLists=256, current=256 for clip_index of 152202 rows
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:DatabaseRepository] targetLists=256, current=256 for face_index of 147543 rows
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:DatabaseRepository] Running migrations, this may take a while
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:ServerService] Feature Flags: {
  "smartSearch": true,
  "facialRecognition": true,
  "duplicateDetection": true,
  "map": true,
  "reverseGeocoding": true,
  "importFaces": false,
  "sidecar": true,
  "search": true,
  "trash": true,
  "oauth": true,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false,
  "email": false
}
[Nest] 17  - 05/24/2025, 6:21:10 PM     LOG [Api:StorageService] Verifying system mount folder checks, current state: {"mountChecks":{"thumbs":true,"upload":true,"backups":true,"library":true,"profile":true,"encoded-video":true}}
```
