### ISSUE TITLE
DNG images taken with selfie iPhone camera flipped vertically

### ISSUE THREAD

**Issue by ByDoneAgency** [immich-app/immich#18612]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I've noticed a lot of issues with image orientation, however I've found that I'm having issues with DNG photos taken exclusively with the selfie camera on an iPhone. The thumbnail and preview are flipped vertically.

![Image](https://github.com/user-attachments/assets/15532851-c8c9-44b6-bca5-6f06c559be9a)

![Image](https://github.com/user-attachments/assets/6d6210c2-bc18-425a-b1a1-45322e4a6da9)

Also, I noticed that after I turn on "Enable full-size image generation" under "Image Settings", and zoom in on the image in the preview, the orientation is correct only for zoomed in image:

![Image](https://github.com/user-attachments/assets/9d34dd30-d7b1-4f4e-899f-06b00608f635)

Note: Prefer embedded preview is enabled to preserve RAW colours. Also, DNG (RAW) photos taken with the rear camera are correctly oriented.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
not relevant
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

1. Upload iOS DNG photo taken with iPhone selfie camera (Example image provided: [IMG_5210.DNG.zip](https://github.com/user-attachments/files/20431988/IMG_5210.DNG.zip))
2. Check for image thumbnail and preview: image will be flipped vertically
3. Zoom in image (full-size image generation enabled): correct orientation

### Relevant log output

```shell

```

**Comment by Snowknight26** [comment]
Can you provide an example image taken with the rear camera?

Looks like both the image and the embedded preview image have an `Orientation` of `5` but immich might not be respecting that for the thumbnail/preview images.

**Comment by Snowknight26** [comment]
Looks like there's a path forward in some cases..

Replace
https://github.com/immich-app/immich/blob/8ea40973a736db6b8b90a6c289f2b6b20fa9fef0/server/src/repositories/media.repository.ts#L146-L158

with
```suggestion
      .withIccProfile(options.colorspace)
      .rotate();
```

This'll correctly rotate rotate images where the image itself contains the correct `Orientation` tag.
_However_, this'll break RAW images where the RAW itself contains an `Orientation` but the embedded preview images do not and _should still_ be rotated (and it'll probably break the person callstack).

Really, it looks like the following need to be done:

* If the passed image already has `Orientation` in EXIF, auto-handle that with `rotate()`
* if the passed image doesn't have `Orientation` but the parent image _does_, perform a rotation using the parent image's `Orientation`
  * the assumption here is that the parent image and thumbnail are stored in the same orientation - if they aren't that goes out the window

**Comment by ByDoneAgency** [comment]
Here is the image taken with rear camera. It is correctly displayed: [IMG_5292.DNG.zip](https://github.com/user-attachments/files/20513540/IMG_5292.DNG.zip)

**Comment by ByDoneAgency** [comment]
Meanwhile, I've noticed a strange behavior with HEVC HDR videos, again from an iPhone, but only in Chromium-based browsers (Brave Browser, Chrome). This happens on both MacOS and Windows. Some videos play, while others fail to play and show this error:

![Image](https://github.com/user-attachments/assets/c9fc1baf-353b-477d-b5ac-ed8efce8c699)

Video from above (not playing): [IMG_5295.MOV.zip](https://github.com/user-attachments/files/20513643/IMG_5295.MOV.zip)

Again, one very strange thing, however this only happens on MacOS Chromium-based browsers. All videos that play are flipped vertically. However, when I try to screenshot or record screen (using built-in screen recorder), they have normal orientation. 

Here is the screenshot of the screen:

![Image](https://github.com/user-attachments/assets/509b35e1-8f8f-4f24-b96e-aba84ea1ea73)

Here is the photo of my display:

![Image](https://github.com/user-attachments/assets/e9af62a7-7399-416e-b5c4-2b294d158fdb)

Video that plays, but flipped vertically (uploaded via gdrive because of high size): https://drive.google.com/file/d/1pLNBpVSKtfhLKbo2s-P-CdCGvi16tWJP/view?usp=drive_link

I know I can easily solve this by encoding videos, or using Safari to browse, but I just wanted to point out for issue, so you are aware of it.

**Comment by Snowknight26** [comment]
Probably worth opening separate issues for those as they're unrelated.

**Comment by per-review** [comment]
This seems to be a more general issue with multiple orientations for dng files. (Other orientations seem to be rendered correctly.)

* 2 (Mirror horizontal) is rendered as 1 (Horizontal (normal))
* 4 (Mirror vertical) is rendered as 2 (Mirror horizontal)
* 5 (Mirror horizontal and rotate 270 CW) is rendered as 4 (Mirror vertical)

When enabling verbose logging, I can confirm that Immich reads the correct orientation value. The correct value is also written to the database. But all files generated have the wrong orientation.

(Cropping is also not applied, although I can see the correct values are read when activating verbose logging.)

Here's an example: [test.dng.zip](https://github.com/user-attachments/files/21822168/test.dng.zip)

The files exported from Lightroom Classic (and with the correct orientation rendered elsewhere):

![Image](https://github.com/user-attachments/assets/4b03666f-749c-4f52-8fad-8e8c859d57d8)

The preview file from Immich:

![Image](https://github.com/user-attachments/assets/0fc2b7d9-bf15-4fcf-ae93-a03b0d5e8775)

server version: 1.138.0

exiftool output:

```
$ exiftool -Orientation# -Orientation -S test.dng
Orientation: 2
Orientation: Mirror horizontal
$ exiftool test.dng
ExifTool Version Number         : 12.76
File Name                       : test.dng
Directory                       : .
File Size                       : 12 MB
File Modification Date/Time     : 2025:08:17 13:13:44+02:00
File Access Date/Time           : 2025:08:17 13:51:59+02:00
File Inode Change Date/Time     : 2025:08:17 13:14:02+02:00
File Permissions                : -rwxrwxrwx
File Type                       : DNG
File Type Extension             : dng
MIME Type                       : image/x-adobe-dng
Exif Byte Order                 : Little-endian (Intel, II)
Image Description               : test
Make                            : Nikon
Camera Model Name               : Nikon SUPER COOLSCAN 5000 ED
Orientation                     : Mirror horizontal
Rows Per Strip                  : 173
Software                        : Adobe Photoshop Lightroom Classic 8.2.1 (Windows)
Modify Date                     : 2019:05:13 10:55:14
Image Width                     : 5634
Image Height                    : 3816
Bits Per Sample                 : 8 8 8
Compression                     : Lossy JPEG
Photometric Interpretation      : Linear Raw
Samples Per Pixel               : 3
Planar Configuration            : Chunky
Black Level Repeat Dim          : 1 1
Black Level                     : 0 0 0
White Level                     : 255 255 255
Default Scale                   : 1 1
Default Crop Origin             : 0 0
Default Crop Size               : 5634 3816
Chroma Blur Radius              : 0
Anti Alias Strength             : 1
Best Quality Scale              : 1
Preview Image Start             : 30360
Preview Image Length            : 138627
Y Cb Cr Coefficients            : 0.299 0.587 0.114
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Y Cb Cr Positioning             : Co-sited
Reference Black White           : 0 255 128 255 128 255
Subfile Type                    : Reduced-resolution image
Tile Width                      : 256
Tile Length                     : 176
Tile Offsets                    : 1036190
Tile Byte Counts                : 16461
Opcode List 2                   : MapPolynomial, MapPolynomial, MapPolynomial
Cache Version                   : 0.1.0.0
XMP Toolkit                     : Adobe XMP Core 7.0-c000 1.000000, 0000/00/00-00:00:00
Creator Tool                    : Adobe Photoshop Lightroom Classic 8.2.1 (Windows)
Metadata Date                   : 2025:08:17 13:13:44+02:00
Document ID                     : xmp.did:7aebe7a1-bb34-8146-82ce-51d0837b480b
Original Document ID            : 70DF28EA1ADBF9E1CDE96FD84E43B851
Instance ID                     : xmp.iid:8c37cd0c-e155-dd4b-8f33-442ba910bedd
Preserved File Name             : test.dng
Format                          : image/dng
Date Created                    : 2019:05:13 10:55:14
Pick                            : 0
Crop Top                        : 0.036807
Crop Left                       : 0.036507
Crop Bottom                     : 0.979907
Crop Right                      : 0.977339
Crop Angle                      : -0.17
Crop Constrain To Warp          : 0
Crop Constrain To Unit Square   : 1
Has Crop                        : True
Already Applied                 : False
Raw File Name                   : test.dng
History Action                  : derived, saved, saved, saved
History Parameters              : converted from image/x-nikon-nef to image/dng, saved to new location
History Instance ID             : xmp.iid:7aebe7a1-bb34-8146-82ce-51d0837b480b, xmp.iid:2f6fd3cc-9cf1-2a4e-8823-8bf0c923c700, xmp.iid:8c37cd0c-e155-dd4b-8f33-442ba910bedd
History When                    : 2019:05:13 10:55:14+02:00, 2025:08:17 13:08:36+02:00, 2025:08:17 13:13:44+02:00
History Software Agent          : Adobe Photoshop Lightroom Classic 8.2.1 (Windows), Adobe Photoshop Lightroom Classic 14.4 (Windows), Adobe Photoshop Lightroom Classic 14.4 (Windows)
History Changed                 : /, /metadata, /metadata
Derived From Document ID        : 70DF28EA1ADBF9E1CDE96FD84E43B851
Derived From Original Document ID: 70DF28EA1ADBF9E1CDE96FD84E43B851
Description                     : test
Exif Version                    : 0230
Date/Time Original              : 2019:05:13 10:55:14
Color Space                     : sRGB
DNG Version                     : 1.4.0.0
DNG Backward Version            : 1.4.0.0
Unique Camera Model             : NEF
Color Matrix 1                  : 1.3458 -0.2556 -0.051 -0.5444 1.5081 0.0205 0 0 1.212
Analog Balance                  : 1 1 1
As Shot White XY                : 0.3457 0.3585
Baseline Exposure               : 0
Baseline Noise                  : 1
Baseline Sharpness              : 1
Linear Response Limit           : 1
Shadow Scale                    : 1
Maker Note Version              : 2.00
Warning                         : [minor] Bad PreviewIFD SubDirectory start
Calibration Illuminant 1        : Unknown
Raw Data Unique ID              : ECE1D370EF3D3A7337F36D44884223BB
Original Raw File Name          : IMG_034.nef
Colorimetric Reference          : Output-referred (ICC Profile Dynamic Range)
Profile Name                    : Embedded
Profile Embed Policy            : Allow Copying
Preview Application Name        : Adobe Photoshop Lightroom Classic
Preview Application Version     : 8.2.1
Preview Settings Digest         : 178f8dd7654f82110eb21a8dbe0b7196
Preview Color Space             : sRGB
Preview Date Time               : 2019:05:13 10:55:14+02:00
New Raw Image Digest            : e7c354230da3a0c877f141137eda46a6
Image Size                      : 5634x3816
Megapixels                      : 21.5
Preview Image                   : (Binary data 138627 bytes, use -b option to extract)
```

`/api/assets` response:

``` json
{
  "id": "e4e0841e-fd78-4503-a70f-ea2efcebe959",
  "deviceAssetId": "web-test.dng-1755429224452",
  "ownerId": "65b3bea8-54e4-497b-9ebb-3373d41d8000",
  "owner": {
    "id": "65b3bea8-54e4-497b-9ebb-3373d41d8000",
    "email": "test@example.com",
    "name": "test",
    "profileImagePath": "",
    "avatarColor": "green",
    "profileChangedAt": "2025-08-17T09:36:15.968428+00:00"
  },
  "deviceId": "WEB",
  "libraryId": null,
  "type": "IMAGE",
  "originalPath": "/data/upload/65b3bea8-54e4-497b-9ebb-3373d41d8000/00/2f/002f43ba-7d76-443c-b75c-3f2e78018e63.dng",
  "originalFileName": "test.dng",
  "originalMimeType": "image/dng",
  "thumbhash": "FvgFFYKuRgSUuJjEi8idaHdPkfYU",
  "fileCreatedAt": "2019-05-13T10:55:14.000Z",
  "fileModifiedAt": "2025-08-17T11:13:44.452Z",
  "localDateTime": "2019-05-13T10:55:14.000Z",
  "updatedAt": "2025-08-17T11:27:32.669Z",
  "isFavorite": false,
  "isArchived": false,
  "isTrashed": false,
  "visibility": "timeline",
  "duration": "0:00:00.00000",
  "exifInfo": {
    "make": "Nikon",
    "model": "Nikon SUPER COOLSCAN 5000 ED",
    "exifImageWidth": 5634,
    "exifImageHeight": 3816,
    "fileSizeInByte": 12426789,
    "orientation": "2",
    "dateTimeOriginal": "2019-05-13T10:55:14+00:00",
    "modifyDate": "2025-08-17T11:13:44.452+00:00",
    "timeZone": null,
    "lensModel": null,
    "fNumber": null,
    "focalLength": null,
    "iso": null,
    "exposureTime": null,
    "latitude": null,
    "longitude": null,
    "city": null,
    "state": null,
    "country": null,
    "description": "test",
    "projectionType": null,
    "rating": null
  },
  "livePhotoVideoId": null,
  "tags": [],
  "people": [],
  "unassignedFaces": [],
  "checksum": "pACKVI78YzRr7dYwmwGuNQTyhv4=",
  "stack": null,
  "isOffline": false,
  "hasMetadata": true,
  "duplicateId": null,
  "resized": true
}
```

`.env`:

```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

`docker-compose.yml`:

``` yml
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose                                                                                                               #
# Make sure to use the docker-compose.yml of the current release:                                                                                                                                            #
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml                                                                                                                           #
# The compose file on main may not be compatible with the latest release.

name: immich_debug

services:                                                                                                                                                                                                      immich-server:                                                                                                                                                                                                 container_name: immich_server_debug                                                                                                                                                                          image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2284:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning_debug
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache_debug:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis_debug
    image: docker.io/valkey/valkey:8-bookworm@sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres_debug
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache_debug:
```
