### ISSUE TITLE
Video playback not working in IOS App after update to 1.133.

### ISSUE THREAD

**Issue by krypton9208** [immich-app/immich#18627]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Video not playing if i select older video with is not locally on my device.
Can not be played, i can download that file... (there is not icon to download in app...)

### The OS that Immich Server is running on

Debian - Docker compose

### Version of Immich Server

1.133.1

### Version of Immich Mobile App

1.133.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '14385:2283'
    depends_on:
      - redis
      - database
    restart: always
    privileged: true
    runtime: nvidia
    networks:
      - immich_default
      - immich-internal
    healthcheck:
      disable: false
      test: ''

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /mnt/storage_immich/model_cache:/cache
    env_file:
      - .env
    restart: always
    privileged: true
    runtime: nvidia
    networks:
      - immich_default # machine learning requires internet connecting for model download
      - immich-internal
    healthcheck:
      test: ''
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - immich-internal
    restart: always

networks:
  immich_default:
    external: true
  immich-internal:
    internal: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/storage_immich/files/

# The location where your database files are stored
DB_DATA_LOCATION=/mnt/storage_immich/db/
# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ: "Poland"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.133.1

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=***********

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=immich
DB_DATABASE_NAME=immich
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_CAPABILITIES=all
REDIS_HOSTNAME=redis
IMMICH_PROCESS_INVALID_IMAGES=true
```

### Reproduction steps

1. Create video on IPhone
2. Upload to immich by mobile app
3. Remove file from device after success upload 
4. Wait few seconds for transcoding and other jabs...
5. Play Wideo in mobile APP

### Relevant log output

```shell
/// MOBILE APP LOG - IOS
Error creating video source for asset IMG_5955.MOV: PlatformException(__NSCFString, Asset 9BC833C3-89B4-4740-9BE9-758530D8A71E/L0/001 file cannot be obtained., null, null)

// NEXT LOG ENTRY FROM IOS
FlutterError - Catch all

Instance of 'FlutterErrorDetails'
Exception: Exception: Invalid image data
Library: image resource service
Context: Instance of 'ErrorDescription'
#0      _futurize (dart:ui/painting.dart:7898)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7692)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2546)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147)
#4      ImageLoader.loadImageFromCache (package:immich_mobile/providers/image/cache/image_loader.dart:40)
<asynchronous suspension>
#5      ImmichRemoteImageProvider._codec (package:immich_mobile/providers/image/immich_remote_image_provider.dart:84)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:26)
<asynchronous suspension>
```

### Additional information

When i want to play after a second i getting this loading icon, and nothing changes...

https://github.com/user-attachments/assets/d221c3c2-5ff7-48cd-a4c1-5235da6851fe

LOG FILE from immich_server.

[_immich_server_logs (6).txt](https://github.com/user-attachments/files/20436098/_immich_server_logs.6.txt)
