### ISSUE TITLE
Timezone is not taken into account in timeline order after v1.133

### ISSUE THREAD

**Issue by szerencl** [immich-app/immich#18623]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I noticed my timeline was completely jumbled after upgrading to v1.133. Upon further investigation I noticed that my camera and phone pictures don't align in the time. In the phone app it's perfectly fine, not sure if this would be the case if I rebuilt the timeline (log out then log in).

On my phone the pictures are tagged with time in GMT+2 time-zone and on my camera with UTC time-zone (clock is set back by 2 hours on the camera, so when phone clock is 10:00 camera is 08:00).

So a picture taken at 23:01 with the camera shows up before a picture taken at 21:07 with the phone. However the datetime in the pictures is recognised correctly. Pictures zipped and attached.

![Image](https://github.com/user-attachments/assets/1429a9d4-c900-44e6-b1ab-b1b00139a638)
The pics with darker exposure were taken with the camera.

![Image](https://github.com/user-attachments/assets/f862baa4-b8d7-49d4-86be-9653ae937c0e) (Phone 21:07)
![Image](https://github.com/user-attachments/assets/779cf83a-f2ba-4ed7-87d6-bb6f669071a5) (Camera 23:01, ignore the small time drift on the camera)

[immich-20250525_233222.zip](https://github.com/user-attachments/files/20432843/immich-20250525_233222.zip)

### The OS that Immich Server is running on

DSM 7.2.2

### Version of Immich Server

v1.133 and v.1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

#name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=[redacted]
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Take picture with UTC time-zone and with GMT+X
2. Wait X hours
3. Take picture with UTC time-zone and with GMT+X
4. Upload all 4 pictures
5. Check timeline in browser

### Relevant log output

```shell

```
