### ISSUE TITLE
Previews and thumbnails for HEIC HDR images look flat

### ISSUE THREAD

**Issue by leolabs** [immich-app/immich#18636]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I usually take pictures using a Sony A7C II which I edit in Photomator and export as HDR HEIC files. When viewing these files in Preview on macOS, they look great on both HDR and non-HDR capable displays. However, when I import them into Immich, the thumbnails look washed out, like they're missing some kind of tone mapping.

Here's a comparison using the following file: https://filedn.eu/lzxyiPUpTfXyGSc90YOvYiX/immich/issues/photomator-hdr.heic

![Image](https://github.com/user-attachments/assets/62b5ceac-73dc-4183-af98-4c1536ea5e1d)

The left side shows Immich's generated preview, and the right side shows the same file in macOS's Preview app.

I've tried the same using an HDR JPG file of the same picture, which seems to work better: https://filedn.eu/lzxyiPUpTfXyGSc90YOvYiX/immich/issues/photomator-hdr.jpg

![Image](https://github.com/user-attachments/assets/9f800a4a-bece-435b-875b-8ba338925549)

This issue does not occur when uploading HDR HEIC images created from an iPhone camera, so it might have to do with differences in the pictures' metadata. The HEIC images taken with my iPhone are also in 8-bit with 3 channels while the exported HEIC images from Photomator are in 10-bit with 4 channels (RGBA maybe?).

Thank you in advance for looking into this!

### The OS that Immich Server is running on

TrueNAS Scale

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

irrelevant

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    networks:
      internal: null
      macvlan_network:
        ipv4_address: 192.168.1.248
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      internal: null
    device_cgroup_rules:
      - c 189:* rmw
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:148bb5411c184abd288d9aaed139c98123eeb8824c5d3fce03cf721db58066d8
    networks:
      internal: null
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    networks:
      internal: null
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: postgres -c shared_preload_libraries=vectors.so -c
      'search_path="$$user", public, vectors' -c logging_collector=on -c
      max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
volumes:
  model-cache: null
networks:
  internal: {}
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/M2/Media/Immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/M2/Containers/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload the provided HEIC file to your Immich library
2. Wait for the thumbnails and previews to be generated
3. See that the preview and thumbnail are washed out

### Relevant log output

```shell

```
