### ISSUE TITLE
Broken archived functionality in ios apps

### ISSUE THREAD

**Issue by skilletskills3** [immich-app/immich#18634]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Archived picture not showing in archived inside the library. All the archived pictures are shown in the main photo gallery which seems to be the archive function not working. 

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.132.1

### Version of Immich Mobile App

v1.124.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      initContainers:
        - name: init-permissions
          image: busybox:1.37.0
          command: ['sh', '-c', 'chmod -R a+w /photos']
          volumeMounts:
            - name: photos-volume
              mountPath: /photos
      containers:
      - name: immich
        image: ghcr.io/imagegenius/immich:1.132.1-noml
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 300
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
        - name: IMMICH_PORT
          value: "8080"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Tokyo"
        - name: DB_HOSTNAME
          value: "postgres.immich.svc.cluster.local"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: REDIS_HOSTNAME
          value: "redis.immich.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: photos-volume
          mountPath: /photos
        - name: libraries-volume
          mountPath: /libraries
        - name: immich-photos
          mountPath: /mnt/picture
      volumes:
      - name: config-volume
        persistentVolumeClaim:
          claimName: immich-config-pvc
      - name: photos-volume
        persistentVolumeClaim:
          claimName: immich-photos-pvc
      - name: libraries-volume
        persistentVolumeClaim:
          claimName: immich-libraries-pvc
      - name: immich-photos
        persistentVolumeClaim:
          claimName: immich-shared-pvc
```

### Your .env content

```Shell
env:
        - name: IMMICH_PORT
          value: "8080"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Tokyo"
        - name: DB_HOSTNAME
          value: "postgres.immich.svc.cluster.local"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: DB_DATABASE_NAME
          value: "immich"
        - name: REDIS_HOSTNAME
          value: "redis.immich.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: REDIS_PORT
          value: "6379"
```

### Reproduction steps

1. Open immich
2. Open archived inside library
3. Sees 0 archived photos even though its properly shown in webui. 
...

### Relevant log output

```shell

```
