### ISSUE TITLE
No images in web time view

### ISSUE THREAD

**Issue by 000al000** [immich-app/immich#18643]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

After aupdate to v1.132.2 to v1.133.1 there is no preview picture in web time view (in Android app - all works)

It's look like 

![Image](https://github.com/user-attachments/assets/a609697e-3f0d-41be-960a-642bc63a2512)

### The OS that Immich Server is running on

ubuntu - docker

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /main/backup/Backup/Photo:/main/backup/Backup/Photo
    env_file:
      - .env
    ports:

      - 2283:2283

    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:

    container_name: immich_postgres

#    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0    
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
     # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
     # DB_STORAGE_TYPE: 'HDD'      
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. Upgrade vfrom 132 to 133.1
2. go to web view

### Relevant log output

```shell
No error in logs, all ok
```
