### ISSUE TITLE
getTimeBucket api would not accept page parameters

### ISSUE THREAD

**Issue by dannyxu2015** [immich-app/immich#18664]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

refer to the [api docs](https://immich.app/docs/api/get-time-bucket), page & pageSize should work, but it's not.
My Immich server version: v1.133.0
When I tried the api without page parameters, it work:

<img width="700" alt="Image" src="https://github.com/user-attachments/assets/4394f818-1017-4173-9241-6e62f6f185af" />

But when after add page parameters, it failed with 400:

<img width="839" alt="Image" src="https://github.com/user-attachments/assets/7ea5f6c7-966c-4c36-9e69-478706de0757" />

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

not using app

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /NAS/DATA:/mnt/photos2:ro
      - /userdata/immich-app/immich-config.json:/etc/immich-config.json
      # Chinese cities name
      - /userdata/immich-app/resources/geodata:/build/geodata
      - /userdata/immich-app/resources/i18n-iso-countries:/usr/src/app/node_modules/i18n-iso-countries
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: redis:latest
      # image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/NAS/DATA/APPDATA/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/NAS/DATA/APPDATA/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.133.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

IMMICH_CONFIG_FILE=/etc/immich-config.json
```

### Reproduction steps

1. call the api without page parameters, work normally
2. call the api with page parameters, return 400
3.
...

### Relevant log output

```shell

```

### Additional information

[Nest] 17  - 05/27/2025, 6:36:44 AM   DEBUG [Api:LoggingInterceptor~s2x4naqz] GET /api/timeline/bucket?timeBucket=2025-05-01T00%3A00%3A00.000Z&visibility=timeline&withPartners=true&withStacked=true 200 35.98ms ::ffff:192.168.31.238

[Nest] 17  - 05/27/2025, 6:48:15 AM   DEBUG [Api:LoggingInterceptor~ljfb113e] GET /api/timeline/bucket?timeBucket=2025-05-01T00:00:00.000Z&page=1&pageSize=30 200 4.54ms ::ffff:192.168.31.238

[Nest] 17  - 05/27/2025, 6:48:15 AM   DEBUG [Api:GlobalExceptionFilter~ljfb113e] HttpException(400): {"message":["page must not be less than 1","page must be an integer number","pageSize must not be less than 1","pageSize must be an integer number"],"error":"Bad Request","statusCode":400}
