### ISSUE TITLE
VectorChord 0.4.1 support (bugfix VectorChord 0.4 release)

### ISSUE THREAD

**Issue by jhu2452** [immich-app/immich#18680]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

VectorChord released a bugfix release for their VectorChord 0.4 release:
https://github.com/tensorchord/VectorChord/releases/tag/0.4.1

But it does not pass Immich's version check:

ACT: The VectorChord extension version is 0.4.1, but Immich only supports >=0.3 <0.4.
EXP: Immich happy I am running the bugfix release of 0.4

Quickfix: Include 0.4.1 in the version check.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    # JEROEN:
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
# JEROEN: pre-existing unix sockets:
      - /var/run/postgresql/:/var/run/postgresql/
      - /var/run/redis/:/var/run/redis/
    env_file:
      - .env
    ports:
      - '2283:2283'
  # JEROEN: reuse redis + pgsql
  #depends_on:
  #   - redis
  #   - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  # redis:
  #   container_name: immich_redis
  #   image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
  #   healthcheck:
  #     test: redis-cli ping || exit 1
  #   restart: always

  # database:
  #   container_name: immich_postgres
  #   image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #     POSTGRES_INITDB_ARGS: '--data-checksums'
  #   volumes:
  #     # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
  #     - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
  #   healthcheck:
  #     test: >-
  #       pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
  #       Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
  #       --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
  #       echo "checksum failure count is $$Chksum";
  #       [ "$$Chksum" = '0' ] || exit 1
  #     interval: 5m
  #     start_interval: 30s
  #     start_period: 5m
  #   command: >-
  #     postgres
  #     -c shared_preload_libraries=vectors.so
  #     -c 'search_path="$$user", public, vectors'
  #     -c logging_collector=on
  #     -c max_wal_size=2GB
  #     -c shared_buffers=512MB
  #     -c wal_compression=on
  #   restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/tank/pictures/immich
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=khc6uisndyKeFXigNdKNSJ963oG28Tux5sbn3ti6

# JEROEN:
## NOTE: https://immich.app/docs/administration/postgres-standalone/#with-superuser-permission
DB_URL='postgresql://immich:khc...ti6@%2Fvar%2Frun%2Fpostgresql/immich'
## { path: '/var/run/redis/redis-server.sock', db: 2 }
REDIS_URL='ioredis://eyAicGF0aCI6ICIvdmFyL3J1bi9yZWRpcy9yZWRpcy1zZXJ2ZXIuc29jayIsICJkYiI6IDIgfQ=='
```

### Reproduction steps

1. Install VectorChord 0.4.1
2. Run Immich server
3. Check logs
...

### Relevant log output

```shell
Error: The VectorChord extension version is 0.4.1, but Immich only supports >=0.3 <0.4.
```

### Additional information

P.S. that I am running my own Redis/PostgreSQL should not matter here...
