### ISSUE TITLE
immichCLI v2.2.67 Doesnt always respect the ignore flag

### ISSUE THREAD

**Issue by blakeusblade** [immich-app/immich#18705]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Using the immichCLI to upload/migrate from synology photos to immich isn't always respecting the --ignore flag

Using immichCLI v2.2.67 Uploading to immich server version v1.133.1

immich upload --recursive /host_homes/USERNAME/Photos/PhotoLibrary/ --ignore **/\@eaDir/**

ORIGINAL FILE (SKIPPED) file below
P7180329.MP4
SYNO FILE COPY (MIGRATED) file below
SYNOPHOTO_FILM_H264.mp4

Looking for these files using the command below I get the following output
```
find /host_homes/USERNAME/Photos/ -type f | grep "P7180329.MP4"

/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOPHOTO_FILM_M.mp4
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOPHOTO_THUMB_M.jpg
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOPHOTO_THUMB_SM.jpg
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOPHOTO_THUMB_XL.jpg
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOINDEX_VIDEO_METADATA
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/SYNOINDEX_MEDIA_INFO
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_H264.mp4/SYNOINDEX_MEDIA_INFO
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_H264.mp4/SYNOINDEX_VIDEO_METADATA
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_M.mp4/SYNOINDEX_MEDIA_INFO
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_M.mp4/SYNOINDEX_VIDEO_METADATA
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4@SynoEAStream
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/P7180329.MP4
```

```
find /host_homes/USERNAME/Photos/ -type f | grep "SYNOPHOTO_FILM_H264.mp4"

/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_H264.mp4/SYNOINDEX_MEDIA_INFO
/host_homes/USERNAME/Photos/PhotoLibrary/2010/07/@eaDir/P7180329.MP4/@eaDir/SYNOPHOTO_FILM_H264.mp4/SYNOINDEX_VIDEO_METADATA
```

This isn't just isolated to 1 file either, its many as I've been trying many different variations using the --ignore flag but I seem to get as many as 190 migrated images and or videos being migrated rather than the original file.

My only conclusion is its either broken, doesn't respect the --ignore flag further down the directory tree, or I'm doing something wrong.

I reset (ie clear all directories, databases, and setup/start from scratch/clean slate) every time I try. I've always ended up with wrong files being migrated.

### The OS that Immich Server is running on

Synology DSM 7.2 Docker

### Version of Immich Server

v1.133.1

### Version of Immich Mobile App

v1.133.1

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1034:100
    environment:
      - TZ=Australia/Sydney
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    #image: tensorchord/pgvecto-rs:pg16-v0.2.0
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
    container_name: Immich-DB
    hostname: immich-db
    cpu_shares: 256
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
      - /volume2/docker_extra/immich/backups:/usr/src/app/upload/backups:ro
    environment:
      - TZ=Australia/Sydney
      - POSTGRES_DB=REMOVEDFOROBVIOUSREASONS
      - POSTGRES_USER=REMOVEDFOROBVIOUSREASONS
      - POSTGRES_PASSWORD=REMOVEDFOROBVIOUSREASONS
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    cpu_shares: 256
    user: 1034:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/thumbs:/usr/src/app/upload/thumbs:rw
      - /volume2/docker_extra/immich/upload:/usr/src/app/upload/upload:rw
      - /volume2/docker_extra/immich/profile:/usr/src/app/upload/profile:rw
      - /volume2/docker_extra/immich/library:/usr/src/app/upload/library:rw
      - /volume2/docker_extra/immich/backups:/usr/src/app/upload/backups:rw
      - /volume2/docker_extra/immich/encoded-video:/usr/src/app/upload/encoded-video:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    cpu_shares: 256
    user: 1034:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/thumbs:/usr/src/app/upload/thumbs:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment:
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Australia/Sydney
DB_HOSTNAME=REMOVEDFOROBVIOUSREASONS
DB_USERNAME=REMOVEDFOROBVIOUSREASONS
DB_PASSWORD=REMOVEDFOROBVIOUSREASONS
DB_DATABASE_NAME=REMOVEDFOROBVIOUSREASONS
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET=REMOVEDFOROBVIOUSREASONS
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```

### Additional information

I'am behind a reverse proxy but I'm not getting any connectivity issues.
