### ISSUE TITLE
Unable to Use Existing Local Postgres OR Redis

### ISSUE THREAD

**Issue by TransRapid** [immich-app/immich#18702]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Immich cannot use my local installation of PSQL. This has been working with a native install of immich (without docker). It still works, but even after following these directions [https://immich.app/docs/administration/postgres-standalone/](https://immich.app/docs/administration/postgres-standalone/
), I get the same error.

### The OS that Immich Server is running on

Debian 12 Bookworm

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.132.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
x-name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: nvenc
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
       file: hwaccel.ml.yml
       service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
volumes:
  model-cache:
```

### Your .env content

```Shell
#IMMICH
IMMICH_VERSION=v1.132.3
IMMICH_HOST=127.0.0.1
IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003

#PSQL

DB_VECTOR_EXTENSION=pgvector
DB_URL='postgresql://immich@MYPASSWORD@localhost:5432/immich'

#Redis
REDIS_HOSTNAME=localhost
#REDIS_PORT=6379

#Media Files
UPLOAD_LOCATION=/media/Photos/Immich
THUMB_LOCATION=/media/Photos/Immich/Thumbnails
ENCODED_VIDEO_LOCATION=/media/Photos/Immich/Encoded-Video

#TZ=Etc/GMT+8
TZ=America/Los_Angeles
```

### Reproduction steps

1. docker compose up -d

...

### Relevant log output

```shell
immich_server            | missing 'error' handler on this Redis client
immich_server            | Error: connect ECONNREFUSED 127.0.0.1:6379
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
immich_server            |   errno: -111,
immich_server            |   code: 'ECONNREFUSED',
immich_server            |   syscall: 'connect',
immich_server            |   address: '127.0.0.1',
immich_server            |   port: 6379
immich_server            | }
immich_server            | missing 'error' handler on this Redis client
immich_server            | microservices worker error: Error: connect ECONNREFUSED 127.0.0.1:5432, stack: Error: connect ECONNREFUSED 127.0.0.1:5432
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
immich_server            | microservices worker exited with code 1
immich_server            | Killing api process
immich_server exited with code 1
immich_server            | Starting api worker
immich_server            | Starting microservices worker
immich_server            | [Nest] 7  - 05/27/2025, 5:36:05 PM     LOG [Microservices:EventRepository] Initialized websocket server
immich_server            | Error: connect ECONNREFUSED 127.0.0.1:6379
immich_server            |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16) {
immich_server            |   errno: -111,
immich_server            |   code: 'ECONNREFUSED',
immich_server            |   syscall: 'connect',
immich_server            |   address: '127.0.0.1',
immich_server            |   port: 6379
immich_server            | }
immich_server            | Error:
```

### Additional information

This works without issues outside of docker, but docker cannot connect even when following instructions for pre existing PSQL database, or trying base64 encoding.
