### ISSUE TITLE
Hierarchical tags from darktable are imported flat, discarding the hierarchy

### ISSUE THREAD

**Issue by steph72** [immich-app/immich#18706]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**The bug:**

I use hierarchical tags in darktable to organize my images. When importing images that have been written by darktable, the hierarchy in those tags is lost. Each hierarchical tag is imported as one entry in a flat list, (in my case) filling the "tags" list with hundreds of tags. 

**Technical background:**

Darktable stores its tags inside two nodes:  A "<lr:hierarchicalSubject>" node like so:
```
   <lr:hierarchicalSubject>
    <rdf:Bag>
     <rdf:li>darktable|format|orf</rdf:li>
     <rdf:li>unterwegs|föhr|2024</rdf:li>
    </rdf:Bag>
   </lr:hierarchicalSubject>
```

and a "<dc:subject>"  node like so:
```
   <dc:subject>
    <rdf:Bag>
     <rdf:li>2024</rdf:li>
     <rdf:li>darktable</rdf:li>
     <rdf:li>format</rdf:li>
     <rdf:li>föhr</rdf:li>
     <rdf:li>orf</rdf:li>
     <rdf:li>unterwegs</rdf:li>
    </rdf:Bag>
   </dc:subject>
```

The hierarchy is indicated in the "<lr:hierarchicalSubject>" node with the "|" sign as path delimiter.

Immich seems to only import the "<dc:subject>" node.

### The OS that Immich Server is running on

MacOS 15.5

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

1.133.1

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Volumes/Stephan/photos_developed:/Volumes/Stephan/photos_developed 
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/Volumes/Stephan/immich/images

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=/Volumes/Stephan/immich/postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=+++++++++++++++++

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. In darktable, create a hierarchical tag for an image
2. Export that image as JPG into an "External library" folder in Immich
3. Scan the folder from within Immich
4. == The hierarchy is lost.
...

### Relevant log output

```shell

```
