### ISSUE TITLE
PostgresError: column reference "assetId" is ambiguous - Unable to run job handler (queue-duplicate-detection)

### ISSUE THREAD

**Issue by Thanks-for-everything** [immich-app/immich#18716]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Afternoon 👋 

After successfully migrating to v1.133.0 I tried to run all 'missing' in the jobs to check if everything was still working fine.

Two jobs went into error as soon as the missing was clicked.

### DUPLICATE DETECTION
Complete log (after clicking on MISSING).

```
immich_postgres          | 2025-05-23 09:23:07.785 UTC [79] ERROR:  column reference "assetId" is ambiguous at character 155
immich_postgres          | 2025-05-23 09:23:07.785 UTC [79] STATEMENT:  select "assets"."id" from "assets" inner join "smart_search" on "assets"."id" = "smart_search"."assetId" inner join "asset_job_status" as "job_status" on "assetId" = "assets"."id" where "assets"."visibility" != $1 and "assets"."deletedAt" is null and "job_status"."duplicatesDetectedAt" is null
immich_server            | Query failed : {
immich_server            |   durationMs: 1.6667579999775626,
immich_server            |   error: PostgresError: column reference "assetId" is ambiguous
immich_server            |       at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |       at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |       at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |       at Socket.emit (node:events:518:28)
immich_server            |       at addChunk (node:internal/streams/readable:561:12)
immich_server            |       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |       at Readable.push (node:internal/streams/readable:392:5)
immich_server            |       at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
immich_server            |     severity_local: 'ERROR',
immich_server            |     severity: 'ERROR',
immich_server            |     code: '42702',
immich_server            |     position: '155',
immich_server            |     file: 'parse_relation.c',
immich_server            |     line: '887',
immich_server            |     routine: 'colNameToVar'
immich_server            |   },
immich_server            |   sql: 'select "assets"."id" from "assets" inner join "smart_search" on "assets"."id" = "smart_search"."assetId" inner join "asset_job_status" as "job_status" on "assetId" = "assets"."id" where "assets"."visibility" != $1 and "assets"."deletedAt" is null and "job_status"."duplicatesDetectedAt" is null',
immich_server            |   params: [ 'hidden' ]
immich_server            | }
immich_server            | [Nest] 7  - 05/23/2025, 11:23:07 AM   ERROR [Microservices:{"force":false}] Unable to run job handler (queue-duplicate-detection): PostgresError: column reference "assetId" is ambiguous
immich_server            | PostgresError: column reference "assetId" is ambiguous
immich_server            |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |     at Socket.emit (node:events:518:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
```

### EXTRACT METADATA
Complete log (after clicking on MISSING).

```
immich_postgres          | 2025-05-23 09:25:30.462 UTC [47] ERROR:  value "6153909962" is out of range for type integer
immich_postgres          | 2025-05-23 09:25:30.462 UTC [47] CONTEXT:  unnamed portal parameter $20 = '...'
immich_postgres          | 2025-05-23 09:25:30.462 UTC [47] STATEMENT:  insert into "exif" ("assetId", "dateTimeOriginal", "modifyDate", "timeZone", "latitude", "longitude", "country", "state", "city", "fileSizeInByte", "exifImageHeight", "exifImageWidth", "orientation", "projectionType", "bitsPerSample", "colorspace", "make", "model", "fps", "iso", "exposureTime", "lensModel", "fNumber", "focalLength", "description", "profileDescription", "rating", "livePhotoCID", "autoStackId") values ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29) on conflict ("assetId") do update set "description" = "excluded"."description", "exifImageWidth" = "excluded"."exifImageWidth", "exifImageHeight" = "excluded"."exifImageHeight", "fileSizeInByte" = "excluded"."fileSizeInByte", "orientation" = "excluded"."orientation", "dateTimeOriginal" = "excluded"."dateTimeOriginal", "modifyDate" = "excluded"."modifyDate", "timeZone" = "excluded"."timeZone", "latitude" = "excluded"."latitude", "longitude" = "excluded"."longitude", "projectionType" = "excluded"."projectionType", "city" = "excluded"."city", "livePhotoCID" = "excluded"."livePhotoCID", "autoStackId" = "excluded"."autoStackId", "state" = "excluded"."state", "country" = "excluded"."country", "make" = "excluded"."make", "model" = "excluded"."model", "lensModel" = "excluded"."lensModel", "fNumber" = "excluded"."fNumber", "focalLength" = "excluded"."focalLength", "iso" = "excluded"."iso", "exposureTime" = "excluded"."exposureTime", "profileDescription" = "excluded"."profileDescription", "colorspace" = "excluded"."colorspace", "bitsPerSample" = "excluded"."bitsPerSample", "rating" = "excluded"."rating", "fps" = "excluded"."fps"
immich_server            | Query failed : {
immich_server            |   durationMs: 1.357287000049837,
immich_server            |   error: PostgresError: value "6153909962" is out of range for type integer
immich_server            |       at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |       at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |       at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |       at Socket.emit (node:events:518:28)
immich_server            |       at addChunk (node:internal/streams/readable:561:12)
immich_server            |       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |       at Readable.push (node:internal/streams/readable:392:5)
immich_server            |       at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
immich_server            |     severity_local: 'ERROR',
immich_server            |     severity: 'ERROR',
immich_server            |     code: '22003',
immich_server            |     where: "unnamed portal parameter $20 = '...'",
immich_server            |     file: 'numutils.c',
immich_server            |     line: '314',
immich_server            |     routine: 'pg_strtoint32'
immich_server            |   },
immich_server            |   sql: 'insert into "exif" ("assetId", "dateTimeOriginal", "modifyDate", "timeZone", "latitude", "longitude", "country", "state", "city", "fileSizeInByte", "exifImageHeight", "exifImageWidth", "orientation", "projectionType", "bitsPerSample", "colorspace", "make", "model", "fps", "iso", "exposureTime", "lensModel", "fNumber", "focalLength", "description", "profileDescription", "rating", "livePhotoCID", "autoStackId") values ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29) on conflict ("assetId") do update set "description" = "excluded"."description", "exifImageWidth" = "excluded"."exifImageWidth", "exifImageHeight" = "excluded"."exifImageHeight", "fileSizeInByte" = "excluded"."fileSizeInByte", "orientation" = "excluded"."orientation", "dateTimeOriginal" = "excluded"."dateTimeOriginal", "modifyDate" = "excluded"."modifyDate", "timeZone" = "excluded"."timeZone", "latitude" = "excluded"."latitude", "longitude" = "excluded"."longitude", "projectionType" = "excluded"."projectionType", "city" = "excluded"."city", "livePhotoCID" = "excluded"."livePhotoCID", "autoStackId" = "excluded"."autoStackId", "state" = "excluded"."state", "country" = "excluded"."country", "make" = "excluded"."make", "model" = "excluded"."model", "lensModel" = "excluded"."lensModel", "fNumber" = "excluded"."fNumber", "focalLength" = "excluded"."focalLength", "iso" = "excluded"."iso", "exposureTime" = "excluded"."exposureTime", "profileDescription" = "excluded"."profileDescription", "colorspace" = "excluded"."colorspace", "bitsPerSample" = "excluded"."bitsPerSample", "rating" = "excluded"."rating", "fps" = "excluded"."fps"',
immich_server            |   params: [
immich_server            |     '6765a756-a7b4-42f7-ab17-1a7931659541',
immich_server            |     2022-08-27T11:25:27.000Z,
immich_server            |     2024-10-05T15:05:06.651Z,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     3373958,
immich_server            |     2592,
immich_server            |     3872,
immich_server            |     '1',
immich_server            |     null,
immich_server            |     8,
immich_server            |     'sRGB',
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     6153909962,
immich_server            |     'Bulb',
immich_server            |     'Minolta/Sony AF 75-300mm F4.5-5.6 (D)',
immich_server            |     0.71,
immich_server            |     null,
immich_server            |     'SONY DSC',
immich_server            |     null,
immich_server            |     0,
immich_server            |     null,
immich_server            |     null
immich_server            |   ]
immich_server            | }
immich_server            | [Nest] 7  - 05/23/2025, 11:25:30 AM   ERROR [Microservices:{"id":"6765a756-a7b4-42f7-ab17-1a7931659541"}] Unable to run job handler (metadata-extraction): PostgresError: value "6153909962" is out of range for type integer
immich_server            | PostgresError: value "6153909962" is out of range for type integer
immich_server            |     at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |     at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |     at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |     at Socket.emit (node:events:518:28)
immich_server            |     at addChunk (node:internal/streams/readable:561:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |     at Readable.push (node:internal/streams/readable:392:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:189:23)

```

Doesn't break anything, just wanted to share.

Be safe 👋 

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

v1.133.0

### Version of Immich Mobile App

v1.133.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/immich
THUMB_LOCATION=./thumbnails
DB_DATA_LOCATION=./postgres

TZ=Europe/Paris
IMMICH_VERSION=release

DB_PASSWORD=REDACTED
DB_USERNAME=REDACTED
DB_DATABASE_NAME=REDACTED
```

### Reproduction steps

1. [Go to https://immich.bamboozle.lan/admin/jobs-status](https://immich.bamboozle.lan/admin/jobs-status)
2. Click 'MISSING' on various jobs

### Relevant log output

```shell

```
