### ISSUE TITLE
The video upload is interrupted

### ISSUE THREAD

**Issue by Snyaify** [immich-app/immich#18736]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When the library is automatically synchronized with the server, 3 large video files cannot be downloaded (size ~700 MB, ~500 MB). I am attaching a [video ](https://trashbin.be4free.ru/u/7mnHJP.mp4) of the problem. Now the procedure of downloading these 3 files is constantly repeated unsuccessfully.
I tried to turn on the debug server logging mode, but there is no information about the download interruption.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0 build.2200

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    # healthcheck:
    #   disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    # healthcheck:
    #   disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    ports:
        - 5435:5432

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/immichlib/

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default, 
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=mypassword

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=/mnt/user/appdata/immich_pg_data

REDIS_HOSTNAME=immich_redis

TZ=Europe/Kaliningrad

IMMICH_LOG_LEVEL=debug
```

### Reproduction steps

1. Opening the mobile app
2. Opening backup
3. Start Backup
...

### Relevant log output

```shell
[Nest] 17  - 05/29/2025, 9:11:39 AM     LOG [Api:Bootstrap] Immich Server is listening on http://[::1]:2283 [v1.134.0] [production] 
[Nest] 17  - 05/29/2025, 9:11:40 AM     LOG [Api:EventRepository] Websocket Connect:    brN7ETPQk9y0Qa3FAAAB
[Nest] 17  - 05/29/2025, 9:11:43 AM     LOG [Api:EventRepository] Websocket Connect:    kZUWYHGM7SsX_spjAAAD
[Nest] 17  - 05/29/2025, 9:11:44 AM     LOG [Api:EventRepository] Websocket Connect:    P0-rtMBJB4I2WZr_AAAF
[Nest] 17  - 05/29/2025, 9:11:53 AM   DEBUG [Api:LoggingInterceptor~fgwoz5xm] GET /api/server/storage 200 2.89ms 78.36.202.208
[Nest] 17  - 05/29/2025, 9:11:53 AM   DEBUG [Api:LoggingInterceptor~xssk6v9b] GET /api/assets/device/6c7f473ad44e5cde14096846c4dafe53dac02f7eeadf96981eecfb1af229d3ef 200 137.96ms 78.36.202.208
[Nest] 17  - 05/29/2025, 9:12:02 AM   DEBUG [Api:LoggingInterceptor~qyvoexsu] GET /api/server/ping 200 1.28ms ::ffff:127.0.0.1
[Nest] 17  - 05/29/2025, 9:12:32 AM   DEBUG [Api:LoggingInterceptor~v8ks2vsf] GET /api/server/ping 200 0.47ms ::ffff:127.0.0.1
[Nest] 17  - 05/29/2025, 9:13:02 AM   DEBUG [Api:LoggingInterceptor~qzjw1gfm] GET /api/server/ping 200 0.47ms ::ffff:127.0.0.1
[Nest] 17  - 05/29/2025, 9:13:32 AM   DEBUG [Api:LoggingInterceptor~i2hgyx8g] GET /api/server/ping 200 0.36ms ::ffff:127.0.0.1
[Nest] 17  - 05/29/2025, 9:14:02 AM   DEBUG [Api:LoggingInterceptor~nto82acd] GET /api/server/ping 200 0.37ms ::ffff:127.0.0.1
[Nest] 17  - 05/29/2025, 9:14:03 AM   DEBUG [Api:LoggingInterceptor~mu2ap9i5] GET /api/assets/5012c879-b165-4069-bf29-240f5792d4be/thumbnail?size=thumbnail 200 127.19ms 
[Nest] 17  - 05/29/2025, 9:14:03 AM   DEBUG [Api:LoggingInterceptor~ec01izhg] GET /api/assets/c2c0787e-f559-44e1-b00a-d3a703ca4f16/thumbnail?size=thumbnail 200 80.26ms 78.36.202.208
[Nest] 17  - 05/29/2025, 9:14:03 AM   DEBUG [Api:LoggingInterceptor~otx4x62e] GET /api/assets/49ac7f63-2598-4c06-9163-1c2d69e26d12/thumbnail?size=thumbnail 200 72.80ms 
[Nest] 17  - 05/29/2025, 9:14:03 AM   DEBUG [Api:LoggingInterceptor~h1diq05u] GET /api/assets/4e980284-125d-4988-b371-8e1df69dab6c/thumbnail?size=thumbnail 200 72.42ms 
[Nest] 17  - 05/29/2025, 9:14:03 AM   DEBUG [Api:LoggingInterceptor~j2g5gcog] GET /api/assets/f8a95aaf-d5fd-49b1-ad57-6bdc1e66c71a/thumbnail?size=thumbnail 200 83.10ms
```
