### ISSUE TITLE
OpenVINO ML pod crashes on jobs triggered by uploads but works fine on manually triggered jobs

### ISSUE THREAD

**Issue by againstpetra** [immich-app/immich#18741]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

when I upload an image to immich and the server automatically dispatches a job to do face detection, the openvino ML pod crashes and the server is unable to complete the job. but if I go to the admin panel and then manually trigger a face detention job it works flawlessly

I am using OpenVINO with my CPU's integrated graphics and I know that can lead to more issues than an external GPU. but this issue feels more strange: the functionality does work, just not when triggered automatically on upload by the server itself

### The OS that Immich Server is running on

Arch / Kubernetes

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# this isn't a docker-compose.yml file because I don't use docker-compose. I use helm. these are the helm values.
env:
  DB_HOSTNAME: cnpg-rw.immich.svc.cluster.local
  DB_USERNAME: postgres
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: cnpg-auth
        key: password
  REDIS_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: redis-auth
        key: redis-password
image:
  tag: v1.134.0
immich:
  persistence:
    library:
      existingClaim: media
redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    existingSecret: redis-auth
    existingSecretPasswordKey: redis-password
server:
  enabled: true
  resources:
    limits:
      gpu.intel.com/i915: 1
    ingress:
      <redacted>
machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: v1.134.0-openvino
  resources:
    limits:
      gpu.intel.com/i915: 1
  persistence:
    cache:
      enabled: true
      type: pvc
      existingClaim: cache
```

### Your .env content

```Shell
n/a, see above.
```

### Reproduction steps

1. upload an image
2. the pod crashes / restarts and the job fails
3. go to admin panel and trigger the job manually, it works

### Relevant log output

```shell
the ML pods logs until it crashes (no intersting log):

[05/28/25 07:42:58] INFO     Starting gunicorn 23.0.0                           
[05/28/25 07:42:58] INFO     Listening at: http://[::]:3003 (8)                 
[05/28/25 07:42:58] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[05/28/25 07:42:58] INFO     Booting worker with pid: 9                         
[05/28/25 07:43:00] INFO     Started server process [9]                         
[05/28/25 07:43:00] INFO     Waiting for application startup.                   
[05/28/25 07:43:00] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[05/28/25 07:43:00] INFO     Initialized request thread pool with 20 threads.   
[05/28/25 07:43:00] INFO     Application startup complete.                      
[05/28/25 10:04:01] INFO     Loading detection model 'buffalo_l' to memory      
[05/28/25 10:04:01] INFO     Setting execution providers to                     
                             ['OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'], in descending order of    
                             preference                                         
[05/28/25 10:04:01] INFO     Loading visual model 'ViT-B-32__openai' to memory  
[05/28/25 10:04:01] INFO     Setting execution providers to                     
                             ['OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'], in descending order of    
                             preference    

the logs of it restarting:

[05/28/25 10:04:30] INFO     Starting gunicorn 23.0.0                           
[05/28/25 10:04:30] INFO     Listening at: http://[::]:3003 (8)                 
[05/28/25 10:04:30] INFO     Using worker: immich_ml.config.CustomUvicornWorker 
[05/28/25 10:04:30] INFO     Booting worker with pid: 9                         
[05/28/25 10:04:31] INFO     Started server process [9]                         
[05/28/25 10:04:31] INFO     Waiting for application startup.                   
[05/28/25 10:04:31] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[05/28/25 10:04:31] INFO     Initialized request thread pool with 20 threads.   
[05/28/25 10:04:31] INFO     Application startup complete. 

and then from the server:

[Nest] 7  - 05/28/2025, 10:04:24 AM   ERROR [Microservices:{"source":"upload","id":"7e6aeae2-7c34-4ca7-b783-f43491dbe0d6"}] Unable to run job handler (face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)
    at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:107:26)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:232:52)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async /usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:526:32
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:751:24)
[Nest] 7  - 05/28/2025, 10:04:24 AM   ERROR [Microservices:{"source":"upload","id":"7e6aeae2-7c34-4ca7-b783-f43491dbe0d6"}] Unable to run job handler (smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:116:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:27)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async /usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:526:32
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:751:24)
[Nest] 7  - 05/28/2025, 10:04:24 AM   ERROR [Microservices:{"source":"upload","id":"87420a98-ed41-4afa-892e-6a16d96b43cc"}] Unable to run job handler (smart-search): Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
Error: Machine learning request '{"clip":{"visual":{"modelName":"ViT-B-32__openai"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)
    at async MachineLearningRepository.encodeImage (/usr/src/app/dist/repositories/machine-learning.repository.js:116:26)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:91:27)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async /usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:526:32
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:751:24)
[Nest] 7  - 05/28/2025, 10:04:24 AM   ERROR [Microservices:{"source":"upload","id":"87420a98-ed41-4afa-892e-6a16d96b43cc"}] Unable to run job handler (face-detection): Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
Error: Machine learning request '{"facial-recognition":{"detection":{"modelName":"buffalo_l","options":{"minScore":0.7}},"recognition":{"modelName":"buffalo_l"}}}' failed for all URLs
    at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:98:15)
    at async MachineLearningRepository.detectFaces (/usr/src/app/dist/repositories/machine-learning.repository.js:107:26)
    at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:232:52)
    at async JobService.onJobStart (/usr/src/app/dist/services/job.service.js:166:28)
    at async EventRepository.onEvent (/usr/src/app/dist/repositories/event.repository.js:126:13)
    at async /usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:526:32
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:751:24)
```
