### ISSUE TITLE
App slowdown over time

### ISSUE THREAD

**Issue by kyearb** [immich-app/immich#18746]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Over the course of a few weeks/months, the android app slows down to the point that any scrolling (timeline, album, etc) results in a stuttered movement. A simple solution seems to be to uninstall the app and reinstall it, at which point everything runs smoothly. I've tried deleting the app's cache but this doesn't help with the issue.

Also possibly related is the album search not working, which coincides with the slowdown. A search would momentarily show the correct albums then jump back to the default view with all albums. An uninstall/reinstall also seems to fix this issue, but deleting the cache does nothing.

The fresh install is only a temporary fix, since the issue has come back again in the past. Unfortunately this is hard to reproduce and since I've reinstalled the app recently I am not seeing this problem. My partner's phone is experiencing this issue currently though so I can possibly post a screen recording or log files later if needed.

Phone hardware/OS: Pixel 5 running Android 14, Pixel 6a running Android 13

Note that this is not a new issue and is something I've been seeing in earlier immich versions.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: HDD
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: null
  model-cache: null
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/remotemount/nas_docker/immich/uploads

# The location where your database files are stored
DB_DATA_LOCATION=./pgdata

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=redacted

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Wait until app slows down...

### Relevant log output

```shell

```
