### ISSUE TITLE
422 Invalid request format when calling /predict on immich-machine-learning (v1.134.0)

### ISSUE THREAD

**Issue by Davelohan** [immich-app/immich#18750]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When sending a textual CLIP inference request to the /predict endpoint on immich-machine-learning, the server returns:

HTTP/1.1 422 Unprocessable Entity
{"detail":"Invalid request format."}

The backend logs show:
ERROR Invalid request format: 'list' object has no attribute 'items'
This appears to be a parsing issue when submitting entries as JSON within a multipart/form-data request, which is the format expected per the OpenAPI schema.

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    volumes:
      - immich_upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_URL: postgres://immich:${DB_PASSWORD}@immich_postgres:5432/immich
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: /usr/src/app/upload
      TZ: ${TZ}
    ports:
      - "2283:2283"
    depends_on:
      - immich_redis
      - immich_postgres
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - immich_net

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich_machine_learning
    volumes:
      - model-cache:/cache
    environment:
      DB_URL: postgres://immich:${DB_PASSWORD}@immich_postgres:5432/immich
      REDIS_HOSTNAME: immich_redis
      MPLCONFIGDIR: /cache/mplconfig
      HUGGINGFACE_HUB_CACHE: /cache/huggingface
      TMPDIR: /cache/tmp
      TZ: ${TZ}
    ports:
      - "3003:3003"
    depends_on:
      - immich_redis
      - immich_postgres
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - immich_net

  immich_redis:
    image: redis:6.2
    container_name: immich_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - immich_net

  immich_postgres:
    image: ankane/pgvector
    container_name: immich_postgres
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: immich
      TZ: ${TZ}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich_net

volumes:
  immich_upload:
  model-cache:
  pgdata:
  redis_data:

networks:
  immich_net:
    driver: bridge
```

### Your .env content

```Shell
UPLOAD_LOCATION=/usr/src/app/upload
IMMICH_VERSION=release
DB_PASSWORD=********** (redacted)
DB_USERNAME=immich
DB_DATABASE_NAME=immich
TZ=Europe/Dublin
```

### Reproduction steps

1. Run the following curl command against the container (reproducible in CLI or via script):

curl -v -X POST http://localhost:3003/predict \
  -H "accept: application/json" \
  -H "Content-Type: multipart/form-data" \
  -F 'entries=[{"task":"clip","type":"textual","modelName":"ViT-B-32__openai","options":{"language":"en"}}]' \
  -F 'text=a cat'

Expected Behavior: 
A valid vector response or confidence result from the model inference (as described in the documentation).

### Relevant log output

```shell
[05/29/25 14:53:46] ERROR    Invalid request format: 'list' object has no attribute 'items'

[05/29/25 14:58:54] INFO     Shutting down due to inactivity.
[05/29/25 14:58:54] INFO     Shutting down
[05/29/25 14:58:54] INFO     Waiting for application shutdown.
[05/29/25 14:58:54] INFO     Application shutdown complete.
[05/29/25 14:58:54] INFO     Finished server process [375]
[05/29/25 14:58:54] ERROR    Worker (pid:375) was sent SIGINT!
[05/29/25 14:58:59] INFO     Booting worker with pid: 1936
[05/29/25 14:58:59] INFO     Started server process [1936]
[05/29/25 14:58:59] INFO     Waiting for application startup.
[05/29/25 14:58:59] INFO     Created in-memory cache with unloading after 300s of inactivity.
[05/29/25 14:58:59] INFO     Initialized request thread pool with 6 threads.
[05/29/25 14:58:59] INFO     Application startup complete.
```

### Additional information

Immich version: v1.134.0
immich-machine-learning image: ghcr.io/immich-app/immich-machine-learning:release
Running via Docker Compose (on VPS)
Host OS: Ubuntu 22.04
Portainer used for deployment

I also tried with:

- application/x-www-form-urlencoded
- --form-string
- Python requests script with files= and data=
- Escaping JSON strings inside entries

All led to 422 responses or this error in the ML container:

Invalid request format: 'list' object has no attribute 'items'

This suggests the backend might be treating a parsed list as a dict and attempting .items().

Would appreciate confirmation of the expected request format, or if this is a bug in the recent release. Happy to test candidate fixes.
