### ISSUE TITLE
Deleted photos (in web) are still visible in android app (uploaded via public upload link)

### ISSUE THREAD

**Issue by tobikuch** [immich-app/immich#18773]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I've uploaded some photos via a public upload link in a album.
Now I've deleted these photos in my web app, but there still listed in the android app. Looks like that only the thumbnails are still there. Also deleting them on the android app is not working.

Photos are listed:

![Image](https://github.com/user-attachments/assets/6cda1e90-0e5a-4dbf-9bed-bbfdafed7438)

But when clicking on them:

![Image](https://github.com/user-attachments/assets/d3c130e2-9bd2-4f66-9b05-4d1f085e9c23)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0 build.200

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    ports:
      - 127.0.0.1:2283:2283
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
#### Version
IMMICH_VERSION=release

###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/home/username/immich-backup

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=log
```

### Reproduction steps

1. Upload photos over public upload link (web)
2. Delete photos in web
3. Photos are still listed in the android app

### Relevant log output

```shell
2025-05-30 11:14:07.156575 | severe   | AssetNotifier        | Failed to delete assets | ApiException 400: {"message":"Not found or no asset.delete access","error":"Bad Request","statusCode":400,"correlationId":"h01j2cgi"} |
2025-05-30 11:14:06.170183 | severe   | AssetNotifier        | Failed to delete assets | ApiException 400: {"message":"Not found or no asset.delete access","error":"Bad Request","statusCode":400,"correlationId":"t20czqq4"} |
2025-05-30 11:14:04.230505 | severe   | AssetGridDataStructure | Error precaching next image: HttpException: Invalid statusCode: 400, uri = https://foto.tobikuch.de/api/assets/79006134-ae44-47cc-bff6-f19a3bb67f11/thumbnail?size=preview,  |
```
