### ISSUE TITLE
Album owner can be added as user but not removed anymore

### ISSUE THREAD

**Issue by headtr1ck** [immich-app/immich#18791]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

It is possible to add the owner of an album as a user via the API.
But it is not possible to remove this "user" anymore, you get the error: "Cannot remove album owner"

The person shows up twice in the album page:
![Image](https://github.com/user-attachments/assets/506f3a38-bebf-436c-a411-74035beb1fd7)
the same for albums that are not shared with other people:
![Image](https://github.com/user-attachments/assets/c1851e86-2d2a-4a13-84c7-11e334872d80)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v0.134.0

### Version of Immich Mobile App

v0.134.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /mnt/immich/ml_cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
# SSD
THUMB_LOCATION=/opt/immich/thumbs
ENCODED_VIDEO_LOCATION=/opt/immich/encoded_videos
PROFILE_LOCATION=/opt/immich/profiles
# NAS
UPLOAD_LOCATION=/mnt/immich/library
BACKUP_LOCATION=/mnt/backups/immich

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=/opt/immich/db

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.134.0

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=superamazingpassword

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. create album via python API 
```python
import requests
import json

# create album
headers = {
     "Accept": "application/json",
    "Content-Type": "application/json",
    "x-api-key": API_KEY
}
data = {
    "albumName": album_name,
    "albumUsers": [
        {
            "role": "editor",
            "userId": USER_ID
        }
    ],
    "assetIds": image_ids
}
requests.post(f"{BASE_URL}/albums", headers=headers, data=json.dumps(data))
```
where the `USER_ID` is the admin /API_KEY owner
2. check the frontend, you should see a share album where you appear twice
3. try deleting the user:
```python
import requests

payload = {}
headers = {
    "Accept": "application/json",
    "x-api-key": API_KEY
}
requests.delete(f"{BASE_URL}/albums/{ALBUM_ID}/user/{USER_ID}", headers=headers, data=payload)
```

### Relevant log output

```shell

```
