### ISSUE TITLE
Partner Sharing Not Showing Other Users to Share With

### ISSUE THREAD

**Issue by TransRapid** [immich-app/immich#18834]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Partner sharing does work where it was already connected, but new partner sharing cannot be setup between users, EXCEPT for admin sharing to other users.The same also happens when trying to share an album.

![Image](https://github.com/user-attachments/assets/6c838558-6a58-4b50-a8e6-04c4f248ee10)

![Image](https://github.com/user-attachments/assets/dc130cf3-9c5d-4b75-8aff-d03d96750936)

![Image](https://github.com/user-attachments/assets/4589d2b2-01d0-4898-b7a2-5e22453c2225)

![Image](https://github.com/user-attachments/assets/ab5b784b-32b9-4165-a546-bbe3f6778e27)

### The OS that Immich Server is running on

Debian 12 6.1.0-35-amd64

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
x-name: immich

services:
  immich-server:
    user: 994:995
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
       file: hwaccel.transcoding.yml
       service: nvenc
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${IMMICH_LOCATION}:/usr/src/app/upload
      - ${IMPORT_LOCATION}:/usr/src/app/upload/upload
      - ${THUMB_LOCATION}:/usr/src/app/upload/thumbs
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${BACKUP_LOCATION}:/usr/src/app/upload/backups
    env_file:
      - .env
    network_mode: host
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
       file: hwaccel.ml.yml
       service: cuda
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
```

### Your .env content

```Shell
#Immich Hosts & Ports
IMMICH_VERSION=release
IMMICH_HOST=127.0.0.1
IMMICH_MACHINE_LEARNING_URL=http://127.0.0.1:3003

#PSQL
DB_HOSTNAME=localhost
DB_USERNAME=*****
DB_PASSWORD=*****
DB_DATABASE_NAME=*****

#Redis
REDIS_HOSTNAME=localhost

#Media Files
IMMICH_LOCATION=/media/Vault/Photos/Immich/
IMPORT_LOCATION=/media/Vault/Photos/Immich/Import
THUMB_LOCATION=/media/Vault/Photos/Immich/Thumbnails
ENCODED_VIDEO_LOCATION=/media/Vault/Photos/Immich/Encoded-Video
PROFILE_LOCATION=/media/Vault/Photos/Immich/Profile
BACKUP_LOCATION=/media/Vault/Photos/Immich/Backups

TZ=America/Los_Angeles
```

### Reproduction steps

1. Log in as non admin users.
2. Attempt to add new shared partner.
3. New partners cannot be added, even to accounts that already have one partner added.
...

### Relevant log output
Error Message (Not In Log)
```shell
Looks like you shared your photos with all users or you don't have any user to share with.
```

### Additional information

I have 4 user accounts set up.
