### ISSUE TITLE
timeline in web is empty

### ISSUE THREAD

**Issue by tomaszduda23** [immich-app/immich#18871]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

This is follow up on https://github.com/immich-app/immich/issues/16046#issuecomment-2675293648. When I re-upload photo again after fixing DB timeline is gone again. I can fix DB once but fixing after each upload is kind of painful.

### The OS that Immich Server is running on

kubernetes  v1.31.1

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
app-template:
  controllers:
    machine-learning:
      containers:
        machine-learning:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v1.134.0
    server:
      containers:
        server:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v1.134.0
  persistence:
    library:
      advancedMounts:
        server:
          server:
            - path: /usr/src/app/upload
      existingClaim: immich-library
cnpg-cluster:
  cluster:
    affinity:
      topologyKey: kubernetes.io/hostname
    imageName: "ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.2-v0.2.0"
    postgresql:
      shared_preload_libraries:
        - "vectors.so"
    storage:
      size: 5Gi
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Upload photo with incorrect date.

![Image](https://github.com/user-attachments/assets/8221d72f-9f30-4915-a960-4409ec467b91)
2. Timeline is gone

### Relevant log output

```shell

```
