### ISSUE TITLE
Facial recognition cuts off on December 31st 2024

### ISSUE THREAD

**Issue by jcjveraa** [immich-app/immich#18925]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have what I feel is a pretty strange bug. On a completely clean install on my kubernetes cluster, I've imported about 12.000 images and 600 videos. When I run facial recognition it recognizes all assets, but it has a 'magic' cut off on 31-12-2024 for all recognized faces, while there are plenty more recent pictures of myself, my son and my wife after that date. 

_I'm running immich-server and immich-machine-learning with 3 replicas, all connected to a single redis and single postgres database. I use the exact images from the latest docker compose file, and I'm a professional software/devops engineer that runs stuff on K8S on a daily basis - so this should not be the underlying issue._

### The OS that Immich Server is running on

Ubuntu 22 LTS

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

n.a.

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
_Note, I've converted the below into Kubernetes resources but it's fully equivalent. I have skipped one thing: mounting `/etc/localtime:/etc/localtime:ro`._

#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
Kustomize (kubernetes) equivalent:

configMapGenerator:
  - literals:
      - DB_DATA_LOCATION=./postgres
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - IMMICH_VERSION=release
      - UPLOAD_LOCATION=./library
      - REDIS_PORT=6379
    name: env
```

### Reproduction steps

1. Upload 12000 assets starting from 2013 up to today through the API using a custom python script
2. check if they are present: they are, I can see the images
3. check face recognition: all recognized faces are on or before 31-12-2024
4. rerun ('reset') face detection
5. same result

### Relevant log output

```shell
n.a., no logs generated
```
