### ISSUE TITLE
iOS App Locks Up

### ISSUE THREAD

**Issue by coryabooth** [immich-app/immich#18951]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I noticed the most recent iOS app version 1.134.0 build 208

When I checked Automatic Background  Backgroup, the app said, "Turn On Background Service" (which, if I recall, I already had previously set to yes)

I turned it on and the app said I must use iOS Settings to enable Background Refresh.
Ofcourse, this is already enabled, but the app continued to report like it was not.

Subsequent usage of the iOS app results in the app freezing and locking up within the first 5-10 seconds.

I was able to navigate in and shut off "Automatic Background Backup" and "Automatic Foreground" - which allowed the app to function normally.

### The OS that Immich Server is running on

QNAP Docker

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0 Build 208

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
ame: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/CACHEDEV5_DATA/Pictures:/usr/src/app/external

      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 'xxxx:xxxx'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/CACHEDEV1_DATA/Immich/upload
DB_DATA_LOCATION=/share/CACHEDEV1_DATA/Immich/database
IMMICH_VERSION=release
DB_PASSWORD=
DB_USERNAME=
DB_DATABASE_NAME=
```

### Reproduction steps

1.  Open App
2. Watch the timer circle on the "Photos" icon
3. Wait 5 seconds
...

### Relevant log output

```shell

```
