### ISSUE TITLE
Error Loading Image

### ISSUE THREAD

**Issue by barthofu** [immich-app/immich#18965]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi,

I don't really know why, but all of a sudden all new photos uploaded to Immich (either using the mobile app or the website) appear as:

![Image](https://github.com/user-attachments/assets/0c4fd66d-fcaa-447b-8d09-07c329d6a8ec)

Investigations so far:
- Even if i can't preview images in the UI, i can download the original assets.
- In the Network tab of my web dev console, the request for the image respond with a 404 not found
- The image is well uploaded as it appears in both the database (`asset` table) and in my `upload` folder at the correct location

**The issue seems to be related to the `thumbnail` system. Indeed, i can't find any new row in the `asset_file` table since the exact day when the bug started. Any idea why?**

### The OS that Immich Server is running on

Debian (host) -> K3S -> Container image

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0 build-200 (android)

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I deploy Immich on Kubernetes using bjw's `app-template` helm chart.

Here is a rough conversion in docker-compose format:

version: '3.9'

services:
  server:
    image: ghcr.io/immich-app/immich-server:v1.134.0
    container_name: immich-server
    ports:
      - "2283:2283"
    environment:
      PUID: 1000
      PGID: 100
      TZ: Europe/Paris
    env_file:
      - ./secrets/immich-secrets.env
    volumes:
      - library:/usr/src/app/upload
    depends_on:
      - redis
      - postgresql

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v1.134.0
    container_name: immich-ml
    environment:
      TRANSFORMERS_CACHE: /cache
    env_file:
      - ./secrets/immich-secrets.env
    volumes:
      - cache:/cache

  redis:
    image: redis:7.4.4-alpine
    container_name: immich-redis
    volumes:
      - redis:/data

  postgresql:
    image: docker.io/tensorchord/pgvecto-rs@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    container_name: immich-postgresql
    environment:
      POSTGRES_INITDB_ARGS: "--data-checksums"
    env_file:
      - ./secrets/immich-secrets.env
    volumes:
      - postgresql:/var/lib/postgresql/data

  # duplicate-finder:
  #   image: giuseppemazzara/immich-duplicate-finder:latest
  #   ports:
  #     - "8501:8501"
  #   depends_on:
  #     - server

volumes:
  library:
    name: pvc-smb-immich-photos
    external: true
  redis:
    name: pvc-immich-immich-redis
    external: true
  postgresql:
    name: pvc-immich-immich-postgresql
    external: true
  cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs


and here is my kube config:

immich:
  defaultPodOptions:
    securityContext:
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
    nodeSelector:
      kubernetes.io/hostname: "worker-1"

  controllers:
    main:
      replicas: 1
      containers:
        server:
          image:
            repository: ghcr.io/immich-app/immich-server
            tag: v1.134.0
          env:
            PUID: 1000
            PGID: 100
            TZ: Europe/Paris
            IMMICH_WORKERS_INCLUDE: api
            IMMICH_HOST: 0.0.0.0
            UPLOAD_LOCATION: /usr/src/app/upload
            IMMICH_LOG_LEVEL: debug
          envFrom:
            - secretRef:
                name: immich-secrets
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
          resources:
            requests:
              cpu: 250m
              memory: 256Mi

        machine-learning:
          image:
            repository: ghcr.io/immich-app/immich-machine-learning
            tag: v1.134.0
          env:
            TRANSFORMERS_CACHE: /cache
          envFrom:
            - secretRef:
                name: immich-secrets

        redis:
          image:
            repository: docker.io/library/redis
            tag: 7.4.4-alpine

        postgresql:
          # For information, i've applied the following command to the database at the first start:
          # CREATE EXTENSION cube;
          # CREATE EXTENSION earthdistance;
          # CREATE EXTENSION vectors;
          image:
            repository: docker.io/tensorchord/pgvecto-rs
            tag: pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
          env:
            POSTGRES_INITDB_ARGS: "--data-checksums"
          envFrom:
            - secretRef:
                name: immich-secrets
        
        # immich-duplicate-finder:
        #   image:
        #     repository: giuseppemazzara/immich-duplicate-finder
        #     tag: latest

  service:
    main:
      controller: main
      type: ClusterIP
      ports:
        http:
          port: 2283
        db:
          port: 5432
        http-duplicate-finder:
          port: 8501

  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: &host "photos.home.bartho.dev"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http
      tls:
        - secretName: immich-tls
          hosts:
            - *host
    duplicate-finder:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      hosts:
        - host: &hostDuplicate "photos-duplicate-finder.home.bartho.dev"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: main
                port: http-duplicate-finder
      tls:
        - secretName: immich-duplicate-tls
          hosts:
            - *hostDuplicate

  persistence:
    library:
      existingClaim: pvc-smb-immich-photos
      advancedMounts:
        main:
          server:
            - path: /usr/src/app/upload

    postgresql:
      existingClaim: pvc-immich-immich-postgresql
      advancedMounts:
        main:
          postgresql:
            - path: /var/lib/postgresql/data
              subPath: data
    
    redis:
      existingClaim: pvc-immich-immich-redis
      advancedMounts:
        main:
          redis:
            - path: /data

    cache:
      enabled: true
      type: emptyDir
      sizeLimit: 10Gi
      advancedMounts:
        main:
          machine-learning:
            - path: /cache
```

### Your .env content

```Shell
IMMICH_WORKERS_INCLUDE: 
IMMICH_HOST: 0.0.0.
UPLOAD_LOCATION: /usr/src/app/
IMMICH_LOG_LEVEL: debug

DB_DATABASE_NAME=immich
DB_HOSTNAME=localhost
DB_PASSWORD=
DB_USERNAME=

IMMICH_API_KEY=
IMMICH_MACHINE_LEARNING_URL=http://localhost:3003

POSTGRES_DB=immich
POSTGRES_PASSWORD=
POSTGRES_USER=

REDIS_HOSTNAME=localhost
```

### Reproduction steps

No clue :/

### Relevant log output

```shell
There is no relevant log outputs from the server, even when set to `IMMICH_LOG_LEVEL=debug`.
```
