### ISSUE TITLE
External PostgreSQL Extension "VectorChord" Version Validation

### ISSUE THREAD

**Issue by Antwony169** [immich-app/immich#18960]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The docker container "immich-server" does not identify supported versions of VectorChord extension in external postgresql databases. VectorChord extension versions 0.4.0, 0.4.1, and 0.4.2 are correctly detected by the container. But the container stops because 0.4.0, 0.4.1, and 0.4.2 are "not supported". In the latest docker compose file, the postgresql docker container installs with VectorChord 0.4.1.

### The OS that Immich Server is running on

UNRAID 7.1.2

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
  #    - database
    restart: always
    healthcheck:
      disable: false
    networks:
      immich-network:

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
    networks:
      immich-network:

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      immich-network:

  #database:
  #  container_name: immich_postgres
  #  image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
  #  environment:
  #    POSTGRES_PASSWORD: ${DB_PASSWORD}
  #    POSTGRES_USER: ${DB_USERNAME}
  #    POSTGRES_DB: ${DB_DATABASE_NAME}
  #    POSTGRES_INITDB_ARGS: '--data-checksums'
  #    # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
  #    # DB_STORAGE_TYPE: 'HDD'
  #  volumes:
  #    # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
  #    - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
  #  restart: always

volumes:
  model-cache:

networks:
  immich-network:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/immich_photos

# Database
DB_HOSTNAME="postgresql.local"
DB_USERNAME=immich_user
DB_PASSWORD=password
DB_DATABASE_NAME=immich_db
DB_PORT="5432"

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=ETC/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.134.0"
```

### Reproduction steps

1. Create a postgresql 17 database server.
2. Install the necessary postgresql database extensions: pgvector from the postgres APT repo and vchord directly from GitHub repository: https://github.com/tensorchord/VectorChord/releases, releases 0.4.0+
3. Modify the postgresql configuration and database to enable the required extensions. Modify the postgresql configuration to allow network connections.
4. Install Immich server according to the instructions for UNRAID server: https://immich.app/docs/install/unraid. Modify the docker compose and .env files to connect to an external postgresql database.
5. Compose up the immich containers.
...

### Relevant log output

```shell
Initializing Immich v1.134.0
Detected CPU Cores: 28
Starting api worker
Starting microservices worker
[Nest] 7  - 06/06/2025, 12:41:18 AM     LOG [Microservices:EventRepository] Initialized websocket server
Error: The VectorChord extension version is 0.4.0, but Immich only supports >=0.3 <0.4.
    Please change VectorChord to a compatible version in the Postgres instance.
    at /usr/src/app/dist/services/database.service.js:76:23
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/dist/repositories/database.repository.js:377:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async /usr/src/app/dist/repositories/database.repository.js:374:13
microservices worker error: Error: The VectorChord extension version is 0.4.0, but Immich only supports >=0.3 <0.4.
    Please change VectorChord to a compatible version in the Postgres instance., stack: Error: The VectorChord extension version is 0.4.0, but Immich only supports >=0.3 <0.4.
    Please change VectorChord to a compatible version in the Postgres instance.
    at /usr/src/app/dist/services/database.service.js:76:23
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /usr/src/app/dist/repositories/database.repository.js:377:27
    at async /usr/src/app/node_modules/kysely/dist/cjs/kysely.js:535:20
    at async DefaultConnectionProvider.provideConnection (/usr/src/app/node_modules/kysely/dist/cjs/driver/default-connection-provider.js:12:20)
    at async /usr/src/app/dist/repositories/database.repository.js:374:13
microservices worker exited with code 1
Killing api process
```
