### ISSUE TITLE
Shared album link is not accessible

### ISSUE THREAD

**Issue by bbieberle** [immich-app/immich#18978]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When i create a album, put some photos in and create a link with a password, then after accessing the link i get a 403 error.
![Image](https://github.com/user-attachments/assets/8c43e534-bec1-4e57-98e1-a15669384ac4)

Settings:
![Image](https://github.com/user-attachments/assets/95a17d0a-86d9-4b1b-aeba-999f0f84ddcb)
 it does not seem to matter weather the user is allowed to upload/downlload or not

### The OS that Immich Server is running on

Kubernetes on Ubuntu Server 24.04 on x86

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  name: immich-server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: immich
      app.kubernetes.io/name: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: immich
        app.kubernetes.io/name: server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.134.0
          imagePullPolicy: IfNotPresent
          env:
            - name: IMMICH_WORKERS_INCLUDE
              value: api
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_HOSTNAME
              value: immich-postgresql
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: dbPassword
            - name: DB_USERNAME
              value: immich
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: REDIS_HOSTNAME
              value: immich-redis-master
            - name: IMMICH_TELEMETRY_INCLUDE
              value: all
          livenessProbe: [...]
          readinessProbe: [...]
          startupProbe: [...]

          resources:
            requests:
              memory: 500Mi
              cpu: 250m
            limits:
              memory: 1500Mi
              cpu: 2000m

          ports:
            - containerPort: 2283
              name: http
              protocol: TCP
            - containerPort: 8081
              name: metrics-api
              protocol: TCP

          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: library
      restartPolicy: Always
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-data
```

### Your .env content

```Shell
-
```

### Reproduction steps

1. create album
2. add photos
3. share with settings:
   - Require Password: enabled (matters)
   - show metadata: enabled (does not seem to matter)
   - Allow public user to download: enabled (does not seem to matter)
   - Allow public user to upload: disabled (does not seem to matter)
   - expire after: Never (does not seem to matter)
4. click the shared link (preferable in private tab)
5. observe that the link cannot be accessed.
...

### Relevant log output

```shell
none
```
