### ISSUE TITLE
Database Backup Failure

### ISSUE THREAD

**Issue by IamTaoChen** [immich-app/immich#19001]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

```bash
[Nest] 7  - 06/06/2025, 2:00:00 AM   ERROR [Microservices:Backup failed with code 1] Database Backup Failure
[Nest] 7  - 06/06/2025, 2:00:00 AM   ERROR [Microservices:BackupService] Gzip exited with code 0 but pgdump exited with 1
[Nest] 7  - 06/06/2025, 2:00:00 AM   ERROR [Microservices:{}] Unable to run job handler (database-backup): Backup failed with code 1
[Nest] 7  - 06/07/2025, 2:00:00 AM   ERROR [Microservices:BackupService] Backup failed with code 1
[Nest] 7  - 06/07/2025, 2:00:00 AM   ERROR [Microservices:BackupService] pg_dumpall: error: query failed: ERROR:  permission denied for table pg_authid
pg_dumpall: detail: Query was: SELECT rolname FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 1
```

### The OS that Immich Server is running on

Debian12

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
networks:
  proxy:
    external: true
    name: ${PROXY_NETWORK_NAME:-proxy}

  postgres:
    external: true
    name: ${POSTGRES_NETWORK_NAME:-postgres}

  redis:
    external: true
    name: ${REDIS_NETWORK_NAME:-redis}

  immich:
    external: false
    name: ${IMMICH_NETWORK_NAME:-immich}

# https://immich.app/docs/administration/postgres-standalone/
services:
  immich:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: ${IMMICH_CONTAINER_NAME:-immich}
    hostname: ${IMMICH_HOSTNAME:-immich}
    restart: always
    networks:
      - proxy
      - postgres
      - redis
      - immich
    ports:
      - 25170:2283
    env_file:
      - .env
      - immich.env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${IMMICH_UPLOAD_DIR:-./upload}:/usr/src/app/upload
    extends:
      file: ./config/hwaccel.transcoding.yml
      service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding



  immich-ml:
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: ${IMMICH_CONTAINER_NAME:-immich}-ml
    hostname: ${IMMICH_HOSTNAME:-immich}-ml
    restart: always
    networks:
      - proxy
      - postgres
      - redis
      - immich
    env_file:
      - .env
      - immich.env
    volumes:
      - model-cache:/cache
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: ./config/hwaccel.ml.yml
      service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable


volumes:
  model-cache:
    driver: local
```

### Your .env content

```Shell
DB_URL=postgres://xxxx:xxxx@vectorchord:5432/immich
# redis
REDIS_HOSTNAME=redis
REDIS_PORT=6379
REDIS_USERNAME=
REDIS_PASSWORD=xxxxx
REDIS_DB=5
```

### Reproduction steps

1. Deploy `vectorchord` and create normal user `immich`

### Relevant log output

```shell

```
