### ISSUE TITLE
STORAGE TEMPLATE MIGRATION skips all files

### ISSUE THREAD

**Issue by Cyberlando** [immich-app/immich#19009]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

external libraries cant use storage template because immich thinks the files doesnt belong to it but there is no way to claim the files in immich. went through hours of troubleshooting on multiple instances with no luck getting it working. it starts then completes instantly with no output files inside the uploads or library folder.

### The OS that Immich Server is running on

docker via proxmox 8.4

### Version of Immich Server

1.34.0

### Version of Immich Mobile App

1.134.0 build 208

### Platform with the issue

- [x] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload:rw
      - /etc/localtime:/etc/localtime:ro
      - ${PHOTO_PATH}:/mnt/photos:rw
    user: "0:0"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    # env_file:
    #   - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    volumes:
      - model-cache:/cache
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:328fe6a5822256d065debb36617a8169dbfbd77b797c525288e465f56c1d392b
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: [ "postgres", "-c", "shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on" ]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
DOCKER_PATH="/zfs_volume/docker"
SHARE_PATH="/zfs_volume"
PHOTO_PATH="/mnt/pve/Multimedia/Pictures/"
DB_USERNAME="postgres"
DB_PASSWORD="postgres"
DB_DATA_LOCATION="/zfs_volume/docker/immich/postgres"
UPLOAD_LOCATION="/zfs_volume/docker/immich"
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. spin up the docker stack or compose
2. add the external library in immich
3.enable structured template migration
4. start the migration in the jobs after the files are done being indexed or just start the scan and it triggers automatically 
...

### Relevant log output

```shell
It just says the services starts then immediately exits as if there were no files to migrate.
```

### Additional information

Thanks guys! paid supporter!
