### ISSUE TITLE
m2ts video files display incorrectly in mobile app, but appear normal on web

### ISSUE THREAD

**Issue by ricky965** [immich-app/immich#19032]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Description:
When uploading .m2ts video files to Immich, the upload and transcoding complete successfully. The video plays correctly in the web interface. However, when playing the same video in the iOS/iPadOS app, the screen flashes rapidly, and there is no audio. This issue affects only the mobile app on Apple devices.

I have attached a screen recording to show the issue in the app.

Unfortunately, I do not have an Android device to test whether the issue also occurs on Android.

Note:
I’m not a native English speaker. This issue report was translated with the help of AI (ChatGPT). Please let me know if any part is unclear. Thank you for your work on Immich!

### The OS that Immich Server is running on

Synology DSM 7.2

### Version of Immich Server

1.134.0

### Version of Immich Mobile App

1.134.0 Build.208

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    entrypoint: [ "tini", "--", "/bin/bash", "-c", "bash <(curl -sSL https://raw.githubusercontent.com/RxChi1d/immich-geodata-zh-tw/refs/heads/main/update_data.sh) --install && exec /bin/bash start.sh" ]
    environment:
      - ML_ENDPOINT=


  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for 
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
   #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 
volumes:
  model-cache:
```

### Your .env content

```Shell
# 這是 Immich 的 .env 設定檔
DB_PASSWORD=postgres
JWT_SECRET=immich-secret
UPLOAD_LOCATION=/usr/src/app/upload
PUID=1000
PGID=1000
TZ=Asia/Taipei
REDIS_HOSTNAME=immich_redis
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Steps to reproduce:
	1.	Upload a .m2ts video file to Immich.
	2.	Confirm it plays correctly on the web.
	3.	Open the iOS or iPadOS Immich app and play the same video.
	4.	Observe flashing screen and lack of audio.

Expected behavior:
The video should play with both video and audio 

https://github.com/user-attachments/assets/7a3f1578-5cd1-4916-baaa-9c18c4b38848

### Relevant log output

```shell
{
  "id": 63878,
  "remoteId": "009af719-fc50-4c1c-871b-ce2150bcf725",
  "localId": "N/A",
  "checksum": "n3i9HxUYvjRLPf/roD7eLJNo0yA=",
  "ownerId": 2203180190584228551,
  "livePhotoVideoId": "N/A",
  "stackId": "N/A",
  "stackPrimaryAssetId": "N/A",
  "stackCount": "0",
  "fileCreatedAt": "2010-11-24 13:52:52.000",
  "fileModifiedAt": "2010-11-27 08:00:52.000",
  "updatedAt": "2025-06-08 21:56:00.192917",
  "durationInSeconds": 39,
  "type": "AssetType.video",
  "fileName": "20101124145252.m2ts",
  "isFavorite": false,
  "isRemote": true,
  "storage": "AssetState.remote",
  "width": 1440,
  "height": 1080,
  "isArchived": false,
  "isTrashed": false,
  "isOffline": false,
  "visibility": "AssetVisibilityEnum.timeline",
}
```
