### ISSUE TITLE
[BUG] Phone timeline doesn't load if duration doesn't match 0:00:00.000000

### ISSUE THREAD

**Issue by jagjordi** [immich-app/immich#1907]
### The bug

With the new versions, I'm getting errors and the timeline is not loading on the phone.

### The OS that Immich Server is running on

unraid (debian based)

### Version of Immich Server

1.50.1

### Version of Immich Mobile App

v1.50.0 build.73

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```
```


### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/Media/immich

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose

###################################################################################
# JWT SECRET
#
# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
###################################################################################

JWT_SECRET=***

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=Heeelouuu

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003


####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

IMMICH_API_URL_EXTERNAL=***
```
```


### Reproduction steps

```bash
1. Update server
2. Install latest apk
3. Log in and wait for timeline to load
...
```

### Additional information

APP logs
```
created_at,level,context,message,stacktrace
2023-03-01 11:18:26.191738,INFO,"AssetNotifier","Reading assets 0 from cache: 9ms",""
2023-03-01 11:18:21.860992,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:18:21.860946,INFO,"AssetNotifier","Load assets: 44024ms",""
2023-03-01 11:18:21.858065,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:17:37.836343,INFO,"AssetNotifier","Reading assets 0 from cache: 5ms",""
2023-03-01 11:16:08.340043,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:16:08.339932,INFO,"AssetNotifier","Load assets: 49041ms",""
2023-03-01 11:16:08.338821,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:15:19.298004,INFO,"AssetNotifier","Reading assets 0 from cache: 26ms",""
2023-03-01 11:15:11.207402,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:15:11.207266,INFO,"AssetNotifier","Load assets: 56059ms",""
2023-03-01 11:15:11.199264,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:14:15.147485,INFO,"AssetNotifier","Reading assets 0 from cache: 9ms",""
2023-03-01 11:13:36.345367,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:13:36.345292,INFO,"AssetNotifier","Load assets: 71742ms",""
2023-03-01 11:13:36.340251,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:12:10.739223,INFO,"AssetNotifier","Reading assets 0 from cache: 30ms",""
2023-03-01 11:09:24.773429,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:09:24.773349,INFO,"AssetNotifier","Load assets: 39634ms",""
2023-03-01 11:09:24.772669,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:08:45.138564,INFO,"AssetNotifier","Reading assets 0 from cache: 41ms",""
2023-03-01 11:08:45.091213,INFO,"AssetNotifier","state is already up-to-date",""
2023-03-01 11:08:45.091139,INFO,"AssetNotifier","Load assets: 48256ms",""
2023-03-01 11:08:45.088177,SEVERE,"AssetService","Error while getting remote assets","#0      DurationExtension.toDuration.<anonymous closure> (package:immich_mobile/utils/builtin_extensions.dart)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:344)
#3      new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#4      new _List.of (dart:core-patch/array.dart:127)
#5      new List.of (dart:core-patch/array_patch.dart:54)
#6      SetMixin.toList (dart:collection/set.dart:118)
#7      DurationExtension.toDuration (package:immich_mobile/utils/builtin_extensions.dart:4)
#8      new Asset.remote (package:immich_mobile/shared/models/asset.dart:15)
#9      SearchService.searchAsset.<anonymous closure> (package:immich_mobile/modules/search/services/search.service.dart:35)
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:344)
#12     new _List._ofEfficientLengthIterable (dart:core-patch/array.dart:162)
#13     new _List.of (dart:core-patch/array.dart:127)
#14     new List.of (dart:core-patch/array_patch.dart:54)
#15     SetMixin.toList (dart:collection/set.dart:118)
#16     AssetService.getRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:50)
<asynchronous suspension>
#17     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:132)
<asynchronous suspension>
"
2023-03-01 11:06:54.848875,INFO,"AssetNotifier","Reading assets 0 from cache: 14ms",""
```
