### ISSUE TITLE
Trust Stores Aren't loaded in Android app?

### ISSUE THREAD

**Issue by jamesonuk** [immich-app/immich#19115]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have my own CA which has signed certificates for many things including immich.   I have installed the CA cert on my Android phone and if I navigate to immich in Chrome is quite happily says the certificate is valid.    In the app however it is not connecting to me local server and will only connect to me remote one even when connected to the designated WiFi.

I have enabled the allow self-signed certificates option (before logging on) but this is a trusted certificate on Android yet I am seeing a message about there being a self-signed certificate in the chain.    This should however not need it as the certificate is trusted by the OS (hence why it is fine in Chrome and this works for other apps like Home Assistant)

I do not believe the installed Trusted CAs are being used here but also seems odd that the self signed certificate option doesn't work here (surely that should just be trusting any certificate?)

### The OS that Immich Server is running on

Unraid 7.1.3

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0m build.200

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  nginx:
    container_name: immich_nginx
    image: nginx:latest
    volumes:
      - type: bind
        source: /mnt/user/appdata/immich/immich_nginx/certs
        target: /tls
      - type: bind
        source: /mnt/user/appdata/immich/immich_nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - 192.168.40.202:2443:2443
    restart: always
    networks:
      iot-bridge:

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri:/dev/dri
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    networks:
      iot-bridge:

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    networks:
      iot-bridge:


  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      iot-bridge:

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      iot-bridge:
  immich-kiosk:
    image: ghcr.io/damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    env_file:
      - stack.env
    environment:
      LANG: "en_GB"
      TZ: "Europe/London"
      # Required settings
      KIOSK_IMMICH_URL: "http://immich_server:2283"

      # Clock
      KIOSK_SHOW_TIME: true
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: true
      KIOSK_DATE_FORMAT: YYYY/MM/DD
      KIOSK_CLOCK_SOURCE: client
      # Kiosk behaviour
      KIOSK_REFRESH: 60
      KIOSK_DISABLE_SCREENSAVER: false
      KIOSK_OPTIMIZE_IMAGES: false
      KIOSK_USE_GPU: true
      # UI
      KIOSK_LAYOUT: splitview
      # Image metadata
      KIOSK_SHOW_IMAGE_DATE: true
      KIOSK_IMAGE_DATE_FORMAT: YYYY-MM-DD
      KIOSK_SHOW_IMAGE_LOCATION: true

    ports:
      - 3000:3000
    restart: always
    networks:
      iot-bridge:

volumes:
  model-cache:
     driver_opts:
           type: none
           device: /mnt/user/appdata/immich/immich_model-cache
           o: bind

networks:
  iot-bridge:
    name: iot-bridge
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/user/immich
DB_DATA_LOCATION=/mnt/user/appdata/immich/immich_postgres
IMMICH_VERSION=release
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
KIOSK_IMMICH_API_KEY=<redacted>
KIOSK_ALBUM=<redacted>
```

### Reproduction steps

1. Setup nginx as reverse proxy with certificates signed by a local CA

[immich_nginx.txt](https://github.com/user-attachments/files/20691816/immich_nginx.txt)

2. Setup local network access to nginx proxy through Android app

### Relevant log output

```shell
ApiException 400: TLS/SSL communication failed: GET /server/ping (Inner exception: HandshakeException: Handshake error in client (OS Error: 
 CERTIFICATE_VERIFY_FAILED: self signed certificate in certificate chain(handshake.cc:391)))

#0 _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:102)
#1 _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:147)
#2 _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:1009)
#3 _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1141)
<asynchronous suspension>
```

### Additional information

Is this not loading no `TrustManagers` 
https://github.com/immich-app/immich/blob/c03e72c1da810979e820e7922996f969941dc852/mobile/android/app/src/main/kotlin/app/alextran/immich/HttpSSLOptionsPlugin.kt#L55-L58

Compare to 
https://github.com/home-assistant/android/blob/a51b3989531bbf16ce77d451f3835b65ef7931dd/common/src/main/kotlin/io/homeassistant/companion/android/common/data/TLSHelper.kt#L24-L26

which gets all `TrustManagers`
