### ISSUE TITLE
"Remove Duplicates" feature fails with "Not found or no asset.update access" – UI shows metadata but images not on server

### ISSUE THREAD

**Issue by schweppes-0x** [immich-app/immich#19128]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

When using the "Remove Duplicates" utility, clicking on "Keep All" or "Delete All" results in the error:

![Image](https://github.com/user-attachments/assets/26af565d-34a4-41b5-bfff-aec93f1cf3ea)

This prevents me from resolving the duplicate entries and I'm stuck on this screen.
To Reproduce

Expected behavior

I expect the action to process the duplicates and either delete or preserve them as requested without error.
Additional context

    Although the UI displays metadata (filename, date, etc.) on hover, the actual duplicate files do not exist on my server.

    This may indicate a mismatch between the database records and actual file storage.

Screenshot:

![Image](https://github.com/user-attachments/assets/35ac901a-1224-4d1a-924a-30cc83fbc6b8)

### The OS that Immich Server is running on

Synology DSM 7.2 (latest)

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

(Latest?)

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=X/gallery
DB_DATA_LOCATION=X/database
IMMICH_VERSION=v1.134.0
DB_PASSWORD=X
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
TZ=Europe/Amsterdam
```

### Reproduction steps

  1.  Go to the Utilities section and open Remove Duplicates.

  2.   The UI shows a list of duplicate assets.

  3.   Click on  "Trash Selected", "Keep All" or  "Delete All".

  4.   An error appears: "Not found or no asset.update access (Immich Server Error)"

### Relevant log output

```shell

```
