### ISSUE TITLE
[BUG] The archived image still appears in the main timeline view

### ISSUE THREAD

**Issue by axellebot** [immich-app/immich#19130]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hello,

Archived photo on android app are not properly archived.

After restarting the android app they are still appearing on the main timeline view. 
 

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS (GNU/Linux 5.15.0-140-generic x86_64)

### Version of Immich Server

v1.132.3

### Version of Immich Mobile App

v1.34.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

#name: photos

# Need compose version >=2
networks:
  web:
    external: true
  internal:
    external: false

services:
  server:
    # runtime: nvidia
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v${IMMICH_VERSION}
    restart: unless-stopped
    depends_on:
      - redis
      - database
    #ports:
    #  - 2283:2283

    # Content of hwaccel.transcoding.yml
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu
    #             - compute
    #             - video
    # devices:
    #   - /dev/nvidia0:/dev/nvidia0
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Database (DB)
      - DB_HOSTNAME=immich-postgres
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      # Redis
      - REDIS_HOSTNAME=immich-redis
      # Machine Leaning (ML)
      # - MACHINE_LEARNING_GPU_ACCELERATION=cuda
      - MACHINE_LEARNING_HOST=immich-machine_learning
      # Nvidia
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=compute,video,gpu
    labels:
      # Traefik
      - traefik.enable=true
      ## Router HTTPS
      - traefik.http.routers.immich-secure.entrypoints=websecure
      - traefik.http.routers.immich-secure.rule=Host(`photos.lebot.me`)
      - traefik.http.routers.immich-secure.tls=true
      - traefik.http.routers.immich-secure.tls.certresolver=defaultresolver
      ## Services
      - traefik.http.services.immich.loadbalancer.server.port=2283 # Tell Traefik to use the port 2283 to connect to `immich`
      ## Docker
      - traefik.docker.network=web # Tell Traefik to use web network to connect to `immich`
    networks:
      - web
      - internal

  machine-learning:
    # runtime: nvidia
    container_name: immich-machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v${IMMICH_VERSION} #-cuda
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    restart: unless-stopped
    # Content of hwaccel.ml.yml
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities:
    #             - gpu
    # devices:
    #   - /dev/nvidia0:/dev/nvidia0
    #   - /dev/nvidiactl:/dev/nvidiactl
    #   - /dev/nvidia-uvm:/dev/nvidia-uvm
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 5<>/dev/tcp/127.0.0.1/3003"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - model-cache:/cache 
    # environment:
      # Nvidia
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=gpu
    networks:
      - internal

  redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
    networks:
      - internal

  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${DATABASE_LOCATION}:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  model-cache:
    driver: local
  redis:
    driver: local
```

### Your .env content

```Shell
IMMICH_VERSION=1.132.3
```

### Reproduction steps

1. Archive photos on mobile
2. Restart android app
3. See the same archived photo on main timeline

### Relevant log output

```shell

```

### Additional information

I'm also adding the photo in a album before archiving.
