### ISSUE TITLE
Nikon Z5II .NEF Files Fail to Generate Valid Thumbnails/Previews

### ISSUE THREAD

**Issue by StackOvenFlow** [immich-app/immich#19139]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### Problem
.NEF RAW files from the Nikon Z5 II fail to render valid thumbnails or previews in Immich.
	•	Files import into Immich, but:
	•	Thumbnails show as corrupted (e.g. colored bands or “Error loading image”)
	•	Full-size preview may also break or show garbage
	•	These same files open fine in Lightroom or Preview, so the files themselves are valid.

### Observations
Using exiftool and comparing two .NEF files:
	•	✅ D3400 .NEF (DSC_0153.nef) works
	•	❌ Z5 II .NEF (DSC_0557.nef) fails
Files can be downloaded [here](https://drive.google.com/drive/folders/1DY5ZGemyB7BpOgYFmZyMmbiw90H1Osw_?usp=share_link)

#### Key differences:
Property | D3400 | Z5 II
-- | -- | --
MIME Type | image/x-nikon-nef | image/x-nikon-nrw
Bits Per Sample | 12 | 14
Jpg From Raw Length | ~1.3 MB | ~3.0 MB
Embedded preview location | JpgFromRaw, 12-bit | PreviewImage, 14-bit
EXIF Details | Minimal | Includes custom tone/sharpness/noise maps
Extracted Preview (CLI) | Shows fine | Shows fine with exiftool
Web Preview in Immich | ✅ | ❌

### How to Reproduce
1.	Upload .NEF files from Nikon Z5II (possibly other models) to Immich
2.	Observe:
    •	Grid thumbnails are corrupted
    •	Full preview may also fail to decode or show errors
3.	Try Refresh Thumbnail — same result

### Workaround (What I did)
I patched generateImageThumbnails() in media.service.ts to:
	•	Check if extractImage() fails
	•	Fallback to exiftool:
```bash
exiftool -b -PreviewImage "DSC_0557.NEF" > "preview.jpg"
```
•	If successful:
	•	Generate .webp thumbnail from that preview buffer
	•	Generate a thumbhash
	•	Return those instead of falling back to broken decode

This fully resolved the issue for Nikon Z5 II files.

#### Scrappy solution implemented locally
[**server/Dockerfile**](https://github.com/immich-app/immich/blob/main/server/Dockerfile#L4)
```diff
diff --git a/server/Dockerfile b/server/Dockerfile
index fcf16ea13..a409a0853 100644
--- a/server/Dockerfile
+++ b/server/Dockerfile
@@ -1,7 +1,9 @@
 # dev build
 FROM ghcr.io/immich-app/base-server-dev:202505131114@sha256:cf4507bbbf307e9b6d8ee9418993321f2b85867da8ce14d0a20ccaf9574cb995 AS dev
 
-RUN apt-get install --no-install-recommends -yqq tini
+RUN apt-get update && \
+    apt-get install --no-install-recommends -yqq tini libimage-exiftool-perl && \
+    apt-get clean
 WORKDIR /usr/src/app
 COPY server/package.json server/package-lock.json ./
 COPY server/patches ./patches
```
[**server/media.service.ts**](https://github.com/immich-app/immich/blob/main/server/src/services/media.service.ts)
```diff
diff --git a/server/src/services/media.service.ts b/server/src/services/media.service.ts
index bd419f0b3..7dcffd9e6 100644
--- a/server/src/services/media.service.ts
+++ b/server/src/services/media.service.ts
@@ -1,4 +1,6 @@
 import { Injectable } from '@nestjs/common';
+import { exec } from 'child_process';
+import * as fs from 'fs/promises';
 import { FACE_THUMBNAIL_SIZE, JOBS_ASSET_PAGINATION_SIZE } from 'src/constants';
 import { StorageCore, ThumbnailPathEntity } from 'src/cores/storage.core';
 import { Exif } from 'src/database';
@@ -42,6 +44,9 @@ import { getAssetFiles } from 'src/utils/asset.util';
 import { BaseConfig, ThumbnailConfig } from 'src/utils/media';
 import { mimeTypes } from 'src/utils/mime-types';
 import { clamp, isFaceImportEnabled, isFacialRecognitionEnabled } from 'src/utils/misc';
+import { promisify } from 'util';
+
+const execAsync = promisify(exec);
 
 @Injectable()
 export class MediaService extends BaseService {
@@ -267,6 +272,39 @@ export class MediaService extends BaseService {
     // Handle embedded preview extraction for RAW files
     const extractEmbedded = image.extractEmbedded && mimeTypes.isRaw(asset.originalFileName);
     const extracted = extractEmbedded ? await this.extractImage(asset.originalPath, image.preview.size) : null;
+    // Fallback: use exiftool to extract embedded preview JPEG
+    if (!extracted && ['.nef', '.nrw'].includes(asset.originalFileName.toLowerCase().slice(-4))) {
+      try {
+        const cmd = `exiftool -b -PreviewImage "${asset.originalPath}" > "${previewPath}"`;
+        await execAsync(cmd);
+
+        // Read the extracted JPEG buffer
+        const previewBuffer = await fs.readFile(previewPath);
+        const fileExists = previewBuffer.length > 0;
+
+        if (fileExists) {
+          this.logger.log(`✅ Extracted preview for NEF using exiftool: ${asset.originalFileName}`);
+
+          // Create the .webp thumbnail and thumbhash from the buffer
+          const decodeOptions = {
+            colorspace: Colorspace.SRGB,
+            processInvalidImages: false,
+          };
+
+          await this.mediaRepository.generateThumbnail(previewBuffer, { ...image.thumbnail, ...decodeOptions }, thumbnailPath);
+          const thumbhash = await this.mediaRepository.generateThumbhash(previewBuffer, decodeOptions);
+
+          return {
+            previewPath,
+            thumbnailPath,
+            fullsizePath: undefined,
+            thumbhash,
+          };
+        }
+      } catch (err) {
+        this.logger.warn(`❌ Exiftool NEF fallback failed for ${asset.originalFileName}: ${err}`);
+      }
+    }
     const generateFullsize = image.fullsize.enabled && !mimeTypes.isWebSupportedImage(asset.originalPath);
     const convertFullsize = generateFullsize && (!extracted || !mimeTypes.isWebSupportedImage(` .${extracted.format}`));

<!-- Failed to upload "NEF_files.zip" -->

```

### The OS that Immich Server is running on

Ubuntu 24.04.2

### Version of Immich Server

1.134.0

### Version of Immich Mobile App

1.134.0 build.208

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
IMMICH_TELEMETRY_INCLUDE=all

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Upload .NEF files from Nikon Z5II (possibly other models) to Immich
2. Observe:
• Grid thumbnails are corrupted
• Full preview may also fail to decode or show errors
3. Try Refresh Thumbnail — same result

### Relevant log output

```shell

```
