### ISSUE TITLE
Web UI zooming artifacts and inconsistent HDR results

### ISSUE THREAD

**Issue by spikeygg** [immich-app/immich#19173]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Problem 1 **Inconsistent HDR**: I commonly view photos in Immich from my Windows 10 PC /w HDR monitor which were taken with my phone, a Pixel 9 Pro. I see that when I zoom in on the photo, it becomes much brighter and displays with more contrast. I think this is HDR engaging. Once the HDR is "on" the HDR view does not go away until I go back to gallery display. If I click on the same photo again it is dull/flat until I zoom in, then HDR seems to re-engage. I still have Google Photos and when viewing the same image on their service, it immediately comes up with HDR enabled, no zooming necessary. I think this inconsistency is unintended.

Problem 2 **Thin Black Line Artifacts when zooming** : When zooming in, I can see thin black horizontal and vertical lines in the photo. These are static on the display but come and go as zoom is increased or decreased. If the photo is viewed in 1:1, no thin black horizontal nor vertical lines are present but on any increased zoom, they reappear.

I have tried to reproduce both these issues on the mobile app and they don't appear to affect that application platform.

### The OS that Immich Server is running on

Ubuntu 22.04.5 LTS

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

v1.134.0 build 200

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: nvenc # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /photos/old_photos:/photos/old_photos
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: cuda # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      test: nvidia-smi || exit 1
      interval: 1m
      timeout: 5s
      retries: 1
      start_period: 1m

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/immich_library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=America/Somewhere

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=mepasswd

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Open the web application for Immch
2. Find a photo with HDR information
3. Click on the photo to bring it up in full browser window mode
4. Notice flatness of color palette and sharpness of photo
5. Zoom in once
6. Look for thin black line artifacts and see increased color depth, contrast, brightness

### Relevant log output

```shell
none
```

### Additional information

Please keep in mind that I took these as screenshots with HDR enabled on my Windows 10 PC. When doing that, usually HDR windows get BLOWN OUT. I assume this is because the screen capture suite does not know how to properly capture the HDR information.

Here is part of a photo before zooming:
![Image](https://github.com/user-attachments/assets/bce7c83c-1d73-43ce-ae9a-4cfb217d53a6)
Here is the same part of the photo after zooming (ignore how over-exposed it is, you can see HDR is enabled now) see the horizontal line at toward the bottom):
![Image](https://github.com/user-attachments/assets/6d981e09-e5a7-4acf-a18e-000d970f84f3)
When I turn HDR off in Windows (Settings-->Display) and recapture it looks like this (I zoomed in and out so the thin black lines moved):
![Image](https://github.com/user-attachments/assets/62c58edb-eef1-4113-b93b-0565088e3331)
