### ISSUE TITLE
Failed to load assets on

### ISSUE THREAD

**Issue by wanz2003** [immich-app/immich#19208]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On Huawei phones with HarmonyOS 4.2 and above systems, both album and timeline views display errors : "Failed to load assets".  the top slide is normal.

### The OS that Immich Server is running on

unraid 6.12.13

### Version of Immich Server

v1.134.0

### Version of Immich Mobile App

1.126.1

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${PHOTO_LOCATION}:/usr/src/app/photo
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /mnt/user/other/softdata/immich-machine:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data  # 数据文件保存目录
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/appdata/immich/upload    #上传的照片存放的位置
PHOTO_LOCATION=/mnt/user/photo                     #照片存放位置
DB_DATA_LOCATION=/mnt/user/appdata/immich/postgres #数据库文件存放位置
# The Immich version to use. You can pin this to a specific version like "v1.118.2" 
IMMICH_VERSION=v1.134.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

#LOG_LEVEL=debug
```

### Reproduction steps

1.Huawei phone(HarmonyOS 4.2.0), enter the immich homepage with a browser,
2."Timeline view" Pop up 2 prompts: "Failed to load assets"
3. Enter any album,, Pop up 1 prompts: "Failed to load assets"

There are no error prompts in the server logs

### Relevant log output

```shell
[Nest] 17  - 06/16/2025, 6:41:08 PM     LOG [Api:EventRepository] Websocket Disconnect: z3v9Mns3tjsxQBNnAAAJ
[Nest] 17  - 06/16/2025, 6:41:24 PM     LOG [Api:EventRepository] Websocket Connect:    zrQzryqrPjRHmWhcAAAL
[Nest] 17  - 06/16/2025, 6:41:43 PM     LOG [Api:EventRepository] Websocket Disconnect: zrQzryqrPjRHmWhcAAAL
[Nest] 17  - 06/16/2025, 6:41:44 PM     LOG [Api:EventRepository] Websocket Connect:    cWGkbHXfCqZthwNEAAAN
[Nest] 17  - 06/16/2025, 6:42:28 PM     LOG [Api:EventRepository] Websocket Disconnect: cWGkbHXfCqZthwNEAAAN
[Nest] 17  - 06/16/2025, 6:42:28 PM     LOG [Api:EventRepository] Websocket Connect:    TShBglw1UU4ZhhH9AAAP
[Nest] 17  - 06/16/2025, 6:42:39 PM     LOG [Api:EventRepository] Websocket Disconnect: TShBglw1UU4ZhhH9AAAP
[Nest] 17  - 06/16/2025, 6:42:39 PM     LOG [Api:EventRepository] Websocket Connect:    S8CrjQO4gpCSb8HXAAAR
[Nest] 17  - 06/16/2025, 6:42:54 PM     LOG [Api:EventRepository] Websocket Disconnect: S8CrjQO4gpCSb8HXAAAR
[Nest] 17  - 06/16/2025, 6:42:55 PM     LOG [Api:EventRepository] Websocket Connect:    384edEru2y-lNCcLAAAT
[Nest] 17  - 06/16/2025, 6:43:16 PM     LOG [Api:EventRepository] Websocket Disconnect: 384edEru2y-lNCcLAAAT
[Nest] 17  - 06/16/2025, 6:43:17 PM     LOG [Api:EventRepository] Websocket Connect:    dWrAGvcDi64XqnyGAAAV
[Nest] 17  - 06/16/2025, 6:45:42 PM     LOG [Api:EventRepository] Websocket Disconnect: dWrAGvcDi64XqnyGAAAV
[Nest] 17  - 06/16/2025, 6:45:59 PM     LOG [Api:EventRepository] Websocket Connect:    vLcm0_OS4DNXrJi0AAAX
[Nest] 17  - 06/16/2025, 6:45:59 PM     LOG [Api:EventRepository] Websocket Disconnect: vLcm0_OS4DNXrJi0AAAX
[Nest] 17  - 06/16/2025, 6:46:00 PM     LOG [Api:EventRepository] Websocket Connect:    jLlBIWbH5LiAoAW9AAAZ
[Nest] 17  - 06/16/2025, 6:46:10 PM     LOG [Api:EventRepository] Websocket Disconnect: jLlBIWbH5LiAoAW9AAAZ
[Nest] 17  - 06/16/2025, 6:46:10 PM     LOG [Api:EventRepository] Websocket Connect:    TtdqMVppI8tW9rQuAAAb
[Nest] 17  - 06/16/2025, 6:46:16 PM     LOG [Api:EventRepository] Websocket Disconnect: TtdqMVppI8tW9rQuAAAb
[Nest] 17  - 06/16/2025, 6:46:17 PM     LOG [Api:EventRepository] Websocket Connect:    3s02gnmTUq-NsZ2AAAAd
[Nest] 17  - 06/16/2025, 6:47:43 PM     LOG [Api:EventRepository] Websocket Connect:    nNlNi0o89styBH0sAAAf
[Nest] 17  - 06/16/2025, 6:52:49 PM     LOG [Api:EventRepository] Websocket Connect:    -T11DuybSvNq7Uy9AAAh
[Nest] 17  - 06/16/2025, 6:54:08 PM     LOG [Api:EventRepository] Websocket Disconnect: 3s02gnmTUq-NsZ2AAAAd
[Nest] 17  - 06/16/2025, 6:57:55 PM     LOG [Api:EventRepository] Websocket Disconnect: -T11DuybSvNq7Uy9AAAh
[Nest] 17  - 06/16/2025, 7:00:39 PM     LOG [Api:EventRepository] Websocket Connect:    GErg3Myskii2QkioAAAj

There are no error prompts in the server logs
```

### Additional information

This issues only on the huawei mobile(HarmonyOS 4.2 and above) web.
