### ISSUE TITLE
WebUI not showing photos after May 30th after 1.135.0 update

### ISSUE THREAD

**Issue by clayauld** [immich-app/immich#19265]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

After I updated my server to v1.135.0 the WebUI is only showing pictures up to May 30, 2025. I know there are more photos since then, and the app show they are uploaded (cloud with checkmark). They don't show up on any accounts on the WebUI. 

### The OS that Immich Server is running on

UnRAID OS

### Version of Immich Server

v1.35.0

### Version of Immich Mobile App

1.135.0

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
#      - ${APPDATA_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video_cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      IMMICH_WORKERS_INCLUDE: 'api'
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
  #    - ${APPDATA_LOCATION}/encoded-video:/usr/src/app/upload/encoded-video_cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      IMMICH_WORKERS_EXCLUDE: 'api'
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#     extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
#       file: hwaccel.ml.yml
#       service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${APPDATA_LOCATION}/model-cache:/cache
      - /dev/bus/usb:/dev/bus/usb
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:d6c2911ac51b289db208767581a5d154544f2b2fe4914ea5056443f62dc6e900
    healthcheck:
      test: redis-cli ping || exit 1
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${APPDATA_LOCATION}/pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
  
  # power-tools:
  #   container_name: immich_power_tools
  #   image: ghcr.io/varun-raj/immich-power-tools:latest
  #   ports:
  #     - "8001:3000"
  #   env_file:
  #     - .env

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# Debug level
#LOG_LEVEL=debug

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Photos/immich
APPDATA_LOCATION=/mnt/user/appdata/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.135.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# Immich Power Tools
IMMICH_API_KEY = <redacted>
IMMICH_URL = http://immich_server:2283 # Your immich instance ip address and port
EXTERNAL_IMMICH_URL = "<redacted>" # External address of immich

# Optional
GOOGLE_MAPS_API_KEY= <redacted> # Google Maps API Key
GEMINI_API_KEY= <redacted> # Gemini API Key

#For DB Using Individual Keys
#DB_USERNAME=${DB_USERNAME} # Postgress Database Username
#DB_PASSWORD = ${DB_PASSWORD} # Postgres Database Password
DB_HOST = immich_postgres # Postgres Host (IP address or hostname of the database)
DB_PORT = "5432" # Postgres Port number (Default: 5432)
#DB_DATABASE_NAME = "" # Name of the database 
#For DB using DB URL
#DB_URL = ""
```

### Reproduction steps

1. Update Immich server to v1.135.0 from v1.134.0
2. Open WebUI and check status
3. All accounts in WebUI do not show any pictures after May 30, 2025
...

### Relevant log output

```shell

```

### Additional information

I cleared the browser cache as well as the app cache and logged in again to both to make sure the photos were uploaded. The app is showing the photos are uploaded to the server.
