### ISSUE TITLE
Can't zoom into map on info pane next to image

### ISSUE THREAD

**Issue by CyberSparkCloud** [immich-app/immich#19309]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Hi.

When viewing an image on the web version and you try to zoom into the map in the info pane, it keeps resetting back to the default view level.
Dedicated map page works fine.

I've tried when proxied through Nginx Proxy Manager / Cloudflare and I've also tried direct with the local hostname but both experience same issue.

Cheers

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS - Docker

### Version of Immich Server

v1.135.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Sections below showing versions I'm using but if you need the full file let me know.


name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.1-pgvectors0.2.0
```

### Your .env content

```Shell
# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
UPLOAD_LOCATION=/var/docker_mounted_folders/photos_backup/immich

# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# I added the below
THUMB_LOCATION=/var/docker/immich/data/thumbnails
ENCODED_VIDEO_LOCATION=/var/docker/immich/data/encoded_video
PROFILE_LOCATION=/var/docker/immich/data/profile

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/London

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOST=immich_postgres
DB_PORT=5432

# Below required for Power Tools
IMMICH_API_KEY= REDACTED
IMMICH_URL = "http://photos.lan.REDACTED.co.uk:2283" # Your immich instace ip address and port
EXTERNAL_IMMICH_URL = "https://photos.REDACTED.co.uk" # External address of immich

# Optional for Power Tools
# GOOGLE_MAPS_API_KEY= # Google Maps API Key

GEMINI_API_KEY=REDACTED
```

### Reproduction steps

1. Open photo in web version
2. Open info pane
3. Try to zoom into the map on bottom right
...

### Relevant log output

```shell

```
