### ISSUE TITLE
1.135.1 fails to start with vchord 4.2

### ISSUE THREAD

**Issue by mprovenz** [immich-app/immich#19313]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [ ] Yes

### The bug

Hi all, with 1.135 I was getting some warnings about 'vchordrq.prewarm_dim.' However with 1.135.1 it seems those have been upgraded to an error and the server fails to start:

`[Nest] 19  - 06/19/2025, 6:15:53 PM    WARN [Api:DatabaseRepository] Migration "1750323941566-UnsetPrewarmDimParameter" failed
[Nest] 19  - 06/19/2025, 6:15:53 PM   ERROR [Api:DatabaseRepository] Kysely migrations failed: PostgresError: invalid configuration parameter name "vchordrq.prewarm_dim"
PostgresError: invalid configuration parameter name "vchordrq.prewarm_dim"
    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {
  severity_local: 'ERROR',
  severity: 'ERROR',
  code: '42602',
  detail: '"vchordrq" is a reserved prefix.',
  file: 'guc.c',
  line: '1225',
  routine: 'find_option'
}
api worker exited with code 1
Initializing Immich `

### The OS that Immich Server is running on

PhotonOS

### Version of Immich Server

1.135.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ImmichPhotoData2:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
    restart: always
    healthcheck:
      disable: false

  redis:
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    ports:
      - '6379:6379'
    environment:
      - VALKEY_EXTRA_FLAGS=--requirepass uCgN4GzDh4wW8SJcQChGg9arfs
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

volumes:
  ImmichPhotoData2:
    external: true
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=[redacted]
DB_USERNAME=immich
DB_DATABASE_NAME=immich
DB_HOSTNAME=[redacted]
IMMICH_WORKERS_INCLUDE=api
REDIS_PASSWORD=[redacted]
```

### Reproduction steps

1. Run Immich 1.135.1 on a DB server with vectorchord >4

### Relevant log output

```shell
[Nest] 19  - 06/19/2025, 6:20:06 PM     LOG [Api:DatabaseRepository] Migration "1750189909087-AddAlbumUserCreateFields" succeeded

[Nest] 19  - 06/19/2025, 6:20:06 PM    WARN [Api:DatabaseRepository] Migration "1750323941566-UnsetPrewarmDimParameter" failed

[Nest] 19  - 06/19/2025, 6:20:06 PM   ERROR [Api:DatabaseRepository] Kysely migrations failed: PostgresError: invalid configuration parameter name "vchordrq.prewarm_dim"

PostgresError: invalid configuration parameter name "vchordrq.prewarm_dim"

    at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)

    at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)

    at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)

    at Socket.emit (node:events:518:28)

    at addChunk (node:internal/streams/readable:561:12)

    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)

    at Readable.push (node:internal/streams/readable:392:5)

    at TCP.onStreamRead (node:internal/stream_base_commons:189:23) {

  severity_local: 'ERROR',

  severity: 'ERROR',

  code: '42602',

  detail: '"vchordrq" is a reserved prefix.',

  file: 'guc.c',

  line: '1225',

  routine: 'find_option'

}

api worker exited with code 1

Initializing Immich v1.135.1
```
