### ISSUE TITLE
CLI is bypassing album folder names when Storage Template is defined

### ISSUE THREAD

**Issue by fragonib** [immich-app/immich#19398]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

CLI is very useful to batch upload tons of photos. However when a _Storage Template_ pattern that includes folder naming based on album name is configured:

- Storage Pattern `{{y}}/{{#if album}}{{album}}{{else}}Other/{{MM}}{{/if}}/{{filename}}`
- CLI is uploading files but files are not stored in the folder name that belongs to its album
- Instead `Other` name is selected even when CLI can infer album name and assigns asset to album in the right way.

### The OS that Immich Server is running on

Ubuntu 24.04.1 LTS

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - media:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
  database:
  media:
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_PASSWORD=**********
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Configure your account to use _Template Storage_:
      * `{{y}}/{{#if album}}{{album}}{{else}}Other/{{MM}}{{/if}}/{{filename}}`
2. Trigger CLI to batch upload files and use the subfolder name as the album name:
      * `immich upload ~/Documents/MyPhotos -r -a`
4. All images are uploaded in `Other` folders instead of `album name`

### Relevant log output

```shell

```

### Additional information

This is probably because CLI is creating albums (and adding assets to those albums) after the asset upload, when the final folder is mapped. So you don't have that album membership information at that moment.
