### ISSUE TITLE
Shared album link doesn't work on IOS 16

### ISSUE THREAD

**Issue by dnno** [immich-app/immich#19429]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

On IOS 16.7.11 I have experienced problems when opening share links for photo albums. Share links for individual photos and multiple photos work fine, only share links for albums are affected.

Safari gives an unhelpful generic error message "Error! Error when loading files". I'm attaching screenshots of the error message and system configuration for your reference.

Let me know if you need more information. The error is occuring on my mother-in-law's iPhone, so I'm not sure  what else I can provide - I'll try to get the information though, if you need more.

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [ ] Server
- [x] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich 
      - nginx_proxy
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:42cba146593a5ea9a622002c1b7cba5da7be248650cbb64ecb9c6c33d29794b1
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:739cdd626151ff1f796dc95a6591b55a714f341c737e27f045019ceabf8e8c52
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user", public, vectors' -c logging_collector=on -c max_wal_size=2GB -c shared_buffers=512MB -c wal_compression=on
    restart: always
    networks:
      - immich

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
DB_DATA_LOCATION=./postgres
TZ=Europe/Berlin
IMMICH_VERSION=release
DB_PASSWORD=<redacted>
DB_USERNAME=postgres
```

### Reproduction steps

1. Share a link to a photo album
2. Open on iPhone running iOS 16.7.11
3. Observe error

### Relevant log output

```shell

```
