### ISSUE TITLE
iCloud backup to immich stops at 9 asset remainder.

### ISSUE THREAD

**Issue by fredsco** [immich-app/immich#19430]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have over 18K assets which I want to move from iCloud to Immich. All of them went perfectly except for the last 9. 

when the remainder was at 9 it somehow doesn't process. I have tried restarting/reinstalling the app without avail. 

The logs under profile also do not log anything when I press "start backup" 

The only logs I see for Immich-Server is: 

      

```
[Nest] 7  - 06/22/2025, 3:13:10 PM     LOG [Microservices:MediaService] Successfully encoded 25361885-8ea5-4eeb-b784-1bb0f50baa2a

[Nest] 7  - 06/22/2025, 3:13:10 PM     LOG [Microservices:MediaService] Transcoding video db4aedbb-ba34-42e0-a678-04a41130555f without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:32 PM     LOG [Microservices:MediaService] Successfully encoded db4aedbb-ba34-42e0-a678-04a41130555f

[Nest] 7  - 06/22/2025, 3:13:32 PM     LOG [Microservices:MediaService] Transcoding video 6a3e76e2-8985-4c4b-9548-78364e87efa2 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:34 PM     LOG [Microservices:MediaService] Successfully encoded 6a3e76e2-8985-4c4b-9548-78364e87efa2

[Nest] 7  - 06/22/2025, 3:13:34 PM     LOG [Microservices:MediaService] Transcoding video 1fbb2b6f-9f84-4c14-b261-c9cfeaa88378 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:35 PM     LOG [Microservices:MediaService] Successfully encoded 1fbb2b6f-9f84-4c14-b261-c9cfeaa88378

[Nest] 7  - 06/22/2025, 3:13:35 PM     LOG [Microservices:MediaService] Transcoding video 34494206-70b4-43fc-a310-31e7c63407ae without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:36 PM     LOG [Microservices:MediaService] Successfully encoded 34494206-70b4-43fc-a310-31e7c63407ae

[Nest] 7  - 06/22/2025, 3:13:36 PM     LOG [Microservices:MediaService] Transcoding video fb7ddf85-e252-44a9-bd3b-f7a33ba19395 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:36 PM     LOG [Microservices:MediaService] Successfully encoded fb7ddf85-e252-44a9-bd3b-f7a33ba19395

[Nest] 7  - 06/22/2025, 3:13:37 PM     LOG [Microservices:MediaService] Transcoding video 037e96b6-a778-4c7e-bc36-6d1541cba45b without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:37 PM     LOG [Microservices:MediaService] Successfully encoded 037e96b6-a778-4c7e-bc36-6d1541cba45b

[Nest] 7  - 06/22/2025, 3:13:37 PM     LOG [Microservices:MediaService] Transcoding video 342baee3-b096-4e81-a613-9f2c2142771e without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:38 PM     LOG [Microservices:MediaService] Successfully encoded 342baee3-b096-4e81-a613-9f2c2142771e

[Nest] 7  - 06/22/2025, 3:13:38 PM     LOG [Microservices:MediaService] Transcoding video 839eef38-cf52-4a2f-a63a-577cafa45626 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:13:39 PM     LOG [Microservices:MediaService] Successfully encoded 839eef38-cf52-4a2f-a63a-577cafa45626

[Nest] 7  - 06/22/2025, 3:13:39 PM     LOG [Microservices:MediaService] Transcoding video 213697eb-ad66-4a1c-bf71-aa317d028c94 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:02 PM     LOG [Microservices:MediaService] Successfully encoded 213697eb-ad66-4a1c-bf71-aa317d028c94

[Nest] 7  - 06/22/2025, 3:14:02 PM     LOG [Microservices:MediaService] Transcoding video dabdb16c-d8bf-43b3-b1b2-0fac095a4502 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:05 PM     LOG [Microservices:MediaService] Successfully encoded dabdb16c-d8bf-43b3-b1b2-0fac095a4502

[Nest] 7  - 06/22/2025, 3:14:05 PM     LOG [Microservices:MediaService] Transcoding video 6e88232f-92cb-4a92-8131-ca937d2be80f without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:40 PM     LOG [Microservices:MediaService] Successfully encoded 6e88232f-92cb-4a92-8131-ca937d2be80f

[Nest] 7  - 06/22/2025, 3:14:40 PM     LOG [Microservices:MediaService] Transcoding video 08855c06-a512-48a4-a71c-b19aa3173f4b without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:41 PM     LOG [Microservices:MediaService] Successfully encoded 08855c06-a512-48a4-a71c-b19aa3173f4b

[Nest] 7  - 06/22/2025, 3:14:41 PM     LOG [Microservices:MediaService] Transcoding video 90891346-b342-45ad-96aa-9ba295748881 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:42 PM     LOG [Microservices:MediaService] Successfully encoded 90891346-b342-45ad-96aa-9ba295748881

[Nest] 7  - 06/22/2025, 3:14:42 PM     LOG [Microservices:MediaService] Transcoding video 64b9c406-a605-404d-bdd0-4519856bde0d without hardware acceleration

[Nest] 7  - 06/22/2025, 3:14:42 PM     LOG [Microservices:MediaService] Successfully encoded 64b9c406-a605-404d-bdd0-4519856bde0d

[Nest] 7  - 06/22/2025, 3:14:43 PM     LOG [Microservices:MediaService] Transcoding video ca9d6f90-fc6c-49cd-b388-39f150cf0314 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:15:33 PM     LOG [Microservices:MediaService] Successfully encoded ca9d6f90-fc6c-49cd-b388-39f150cf0314

[Nest] 7  - 06/22/2025, 3:15:34 PM     LOG [Microservices:MediaService] Transcoding video 13c6152c-5e7a-4bdd-b23c-fba6409106d8 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:16:31 PM     LOG [Microservices:MediaService] Successfully encoded 13c6152c-5e7a-4bdd-b23c-fba6409106d8

[Nest] 7  - 06/22/2025, 3:16:31 PM     LOG [Microservices:MediaService] Transcoding video 140d2ad1-c471-4c2c-8c6a-c5c2ef360fea without hardware acceleration

[Nest] 7  - 06/22/2025, 3:16:31 PM     LOG [Microservices:MediaService] Successfully encoded 140d2ad1-c471-4c2c-8c6a-c5c2ef360fea

[Nest] 7  - 06/22/2025, 3:16:32 PM     LOG [Microservices:MediaService] Transcoding video 34114ea2-5656-42f5-87bf-2a0ea594b5f4 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:17:03 PM     LOG [Microservices:MediaService] Successfully encoded 34114ea2-5656-42f5-87bf-2a0ea594b5f4

[Nest] 7  - 06/22/2025, 3:17:03 PM     LOG [Microservices:MediaService] Transcoding video 8dc27833-74d8-40fb-b6ec-7e6210970432 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:17:28 PM     LOG [Microservices:MediaService] Successfully encoded 8dc27833-74d8-40fb-b6ec-7e6210970432

[Nest] 7  - 06/22/2025, 3:17:28 PM     LOG [Microservices:MediaService] Transcoding video 2d7aff02-9d17-40eb-bbd4-f56735e0be90 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:17:37 PM     LOG [Microservices:MediaService] Successfully encoded 2d7aff02-9d17-40eb-bbd4-f56735e0be90

[Nest] 7  - 06/22/2025, 3:17:37 PM     LOG [Microservices:MediaService] Transcoding video 9133551a-79ce-4f94-8cd6-58f4aea22234 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:18:07 PM     LOG [Microservices:MediaService] Successfully encoded 9133551a-79ce-4f94-8cd6-58f4aea22234

[Nest] 7  - 06/22/2025, 3:18:07 PM     LOG [Microservices:MediaService] Transcoding video 77a78d2a-050d-4d05-b18f-34e9bc91cd6c without hardware acceleration

[Nest] 17  - 06/22/2025, 3:18:16 PM     LOG [Api:EventRepository] Websocket Disconnect: yecXxDyrxwEjQqMBAAAZ

[Nest] 17  - 06/22/2025, 3:18:36 PM     LOG [Api:EventRepository] Websocket Connect:    W4Bf9jwxqoQxSkNmAAAb

[Nest] 7  - 06/22/2025, 3:18:39 PM     LOG [Microservices:MediaService] Successfully encoded 77a78d2a-050d-4d05-b18f-34e9bc91cd6c

[Nest] 7  - 06/22/2025, 3:18:39 PM     LOG [Microservices:MediaService] Transcoding video 5cdb8439-55d1-4019-8219-1772f87f91ff without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:01 PM     LOG [Microservices:MediaService] Successfully encoded 5cdb8439-55d1-4019-8219-1772f87f91ff

[Nest] 7  - 06/22/2025, 3:20:01 PM     LOG [Microservices:MediaService] Transcoding video 5a3ae2fb-1a15-4728-b822-2befde92c34f without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:02 PM     LOG [Microservices:MediaService] Successfully encoded 5a3ae2fb-1a15-4728-b822-2befde92c34f

[Nest] 7  - 06/22/2025, 3:20:02 PM     LOG [Microservices:MediaService] Transcoding video a7d2fc16-94db-416c-be27-2bbe057aa112 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:03 PM     LOG [Microservices:MediaService] Successfully encoded a7d2fc16-94db-416c-be27-2bbe057aa112

[Nest] 7  - 06/22/2025, 3:20:03 PM     LOG [Microservices:MediaService] Transcoding video ef0e607b-ad0e-44ab-9fd6-87b38fbf6d4e without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:08 PM     LOG [Microservices:MediaService] Successfully encoded ef0e607b-ad0e-44ab-9fd6-87b38fbf6d4e

[Nest] 7  - 06/22/2025, 3:20:09 PM     LOG [Microservices:MediaService] Transcoding video 899ed286-7bb3-4aef-8152-f6fcf479deb7 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:21 PM     LOG [Microservices:MediaService] Successfully encoded 899ed286-7bb3-4aef-8152-f6fcf479deb7

[Nest] 7  - 06/22/2025, 3:20:21 PM     LOG [Microservices:MediaService] Transcoding video 9fd288c0-6a20-48c1-9ef0-703a1ca461aa without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:22 PM     LOG [Microservices:MediaService] Successfully encoded 9fd288c0-6a20-48c1-9ef0-703a1ca461aa

[Nest] 7  - 06/22/2025, 3:20:22 PM     LOG [Microservices:MediaService] Transcoding video e4962613-0c90-4dbd-a1c3-02219afc7703 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:23 PM     LOG [Microservices:MediaService] Successfully encoded e4962613-0c90-4dbd-a1c3-02219afc7703

[Nest] 7  - 06/22/2025, 3:20:23 PM     LOG [Microservices:MediaService] Transcoding video f694ec5b-b2cd-40bd-aa2b-3ed0a971b831 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:24 PM     LOG [Microservices:MediaService] Successfully encoded f694ec5b-b2cd-40bd-aa2b-3ed0a971b831

[Nest] 7  - 06/22/2025, 3:20:24 PM     LOG [Microservices:MediaService] Transcoding video 42bebfd4-fb93-42f6-a0e0-708eaf2b1c0d without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:25 PM     LOG [Microservices:MediaService] Successfully encoded 42bebfd4-fb93-42f6-a0e0-708eaf2b1c0d

[Nest] 7  - 06/22/2025, 3:20:25 PM     LOG [Microservices:MediaService] Transcoding video e79f9836-d15c-4fe6-baa0-f6a1d6583383 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:45 PM     LOG [Microservices:MediaService] Successfully encoded e79f9836-d15c-4fe6-baa0-f6a1d6583383

[Nest] 7  - 06/22/2025, 3:20:46 PM     LOG [Microservices:MediaService] Transcoding video fae3dc07-0297-46bd-8757-0daccc0c3354 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:46 PM     LOG [Microservices:MediaService] Successfully encoded fae3dc07-0297-46bd-8757-0daccc0c3354

[Nest] 7  - 06/22/2025, 3:20:46 PM     LOG [Microservices:MediaService] Transcoding video ce02c141-391c-4daf-9ce4-1f31faa91dae without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:47 PM     LOG [Microservices:MediaService] Successfully encoded ce02c141-391c-4daf-9ce4-1f31faa91dae

[Nest] 7  - 06/22/2025, 3:20:47 PM     LOG [Microservices:MediaService] Transcoding video d2c7a3df-50bc-4811-b8af-fe4666019bd6 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:48 PM     LOG [Microservices:MediaService] Successfully encoded d2c7a3df-50bc-4811-b8af-fe4666019bd6

[Nest] 7  - 06/22/2025, 3:20:48 PM     LOG [Microservices:MediaService] Transcoding video b9e76a12-2f6e-471c-b01b-1a9aa45c5483 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:20:49 PM     LOG [Microservices:MediaService] Successfully encoded b9e76a12-2f6e-471c-b01b-1a9aa45c5483

[Nest] 7  - 06/22/2025, 3:20:49 PM     LOG [Microservices:MediaService] Transcoding video 87cf80cc-759d-4846-9e7d-ebca605d7741 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:21:00 PM     LOG [Microservices:MediaService] Successfully encoded 87cf80cc-759d-4846-9e7d-ebca605d7741

[Nest] 7  - 06/22/2025, 3:21:00 PM     LOG [Microservices:MediaService] Transcoding video 77350d6c-621a-464e-ad23-d61004751634 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:21:01 PM     LOG [Microservices:MediaService] Successfully encoded 77350d6c-621a-464e-ad23-d61004751634

[Nest] 7  - 06/22/2025, 3:21:01 PM     LOG [Microservices:MediaService] Transcoding video eeabc3fc-4a69-4a1c-9511-306704874418 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:33 PM     LOG [Microservices:MediaService] Successfully encoded eeabc3fc-4a69-4a1c-9511-306704874418

[Nest] 7  - 06/22/2025, 3:22:33 PM     LOG [Microservices:MediaService] Transcoding video 16cba408-743c-4545-8973-3c386366ddc6 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:34 PM     LOG [Microservices:MediaService] Successfully encoded 16cba408-743c-4545-8973-3c386366ddc6

[Nest] 7  - 06/22/2025, 3:22:34 PM     LOG [Microservices:MediaService] Transcoding video cc954dca-38f7-460a-a701-0906506f2863 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:35 PM     LOG [Microservices:MediaService] Successfully encoded cc954dca-38f7-460a-a701-0906506f2863

[Nest] 7  - 06/22/2025, 3:22:35 PM     LOG [Microservices:MediaService] Transcoding video 9aaffcbc-15ec-4f41-a70a-07bb6c2a631d without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:36 PM     LOG [Microservices:MediaService] Successfully encoded 9aaffcbc-15ec-4f41-a70a-07bb6c2a631d

[Nest] 7  - 06/22/2025, 3:22:36 PM     LOG [Microservices:MediaService] Transcoding video bfd0742b-5950-4aba-b88e-5fd77ba4030e without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:37 PM     LOG [Microservices:MediaService] Successfully encoded bfd0742b-5950-4aba-b88e-5fd77ba4030e

[Nest] 7  - 06/22/2025, 3:22:37 PM     LOG [Microservices:MediaService] Transcoding video 671a2d46-8765-49f7-aac9-e53078197b94 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:38 PM     LOG [Microservices:MediaService] Successfully encoded 671a2d46-8765-49f7-aac9-e53078197b94

[Nest] 7  - 06/22/2025, 3:22:38 PM     LOG [Microservices:MediaService] Transcoding video 7f2b2de0-36ff-41ca-b56c-123d00a32b8a without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:39 PM     LOG [Microservices:MediaService] Successfully encoded 7f2b2de0-36ff-41ca-b56c-123d00a32b8a

[Nest] 7  - 06/22/2025, 3:22:39 PM     LOG [Microservices:MediaService] Transcoding video 1e85ef6d-ffb2-4900-9357-04d25699bc91 without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:41 PM     LOG [Microservices:MediaService] Successfully encoded 1e85ef6d-ffb2-4900-9357-04d25699bc91

[Nest] 7  - 06/22/2025, 3:22:41 PM     LOG [Microservices:MediaService] Transcoding video 1fd00ea2-ab10-447c-a6d8-3a3e0161d1cf without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:42 PM     LOG [Microservices:MediaService] Successfully encoded 1fd00ea2-ab10-447c-a6d8-3a3e0161d1cf

[Nest] 7  - 06/22/2025, 3:22:42 PM     LOG [Microservices:MediaService] Transcoding video dde03817-b3c0-401d-ad02-52096e15f1fa without hardware acceleration

[Nest] 7  - 06/22/2025, 3:22:43 PM     LOG [Microservices:MediaService] Successfully encoded dde03817-b3c0-401d-ad02-52096e15f1fa

[Nest] 7  - 06/22/2025, 3:22:43 PM     LOG [Microservices:MediaService] Transcoding video d9b6513c-c4c8-4852-ad47-39b473ad15b1 without hardware acceleration`
```

### The OS that Immich Server is running on

Synology

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```
version: "3"
services:

  # Container #1 - Application Server

  immich-server:
    container_name: Immich-Server
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # NAS | CONTAINER
      # Replace the left side (Left:Right) with your path to the Uploads folder in the NAS
      - /volume1/docker/immich/upload:/usr/src/app/upload
      # Uncomment if you prefer to pass your own configuration file. This will mount the config folder to the container.
      # Replace the left side (Left:Right) with your path to the config folder in the NAS
      #- /volume1/docker/Containers/Immich/config:/config
    environment:
      - TZ=US/Michigan
      - PUID=1026
      - PGID=100
      # Sample configuration file located at: https://immich.app/docs/install/config-file/
      # Uncomment if you prefer to configure using a CONFIG file instead of using the Web Interface.
      # This will tell the container, where in the /config folder is the configuration file.
      #- IMMICH_CONFIG_FILE=/config/immich.json
    ports:
      # NAS | Container
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped

  # Container #2 - ML Server

  immich-machine-learning:
    container_name: Immich-Machine-Learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    environment:
      - TZ=US/Michigan
      - PUID=1026
      - PGID=100
    ports:
      # NAS | Container
      - '3003:3003'
    restart: unless-stopped

  # Container #3 - Cache server

  redis:
    container_name: Immich-Redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    environment:
      - TZ=US/Michigan
      - PUID=1026
      - PGID=100
    restart: unless-stopped

  # Container #4 - DB Server

  database:
    container_name: Immich-Postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      - TZ=US/Michigan
      - PUID=1026
      - PGID=100
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=immich
      - DB_STORAGE_TYPE=HDD
      - POSTGRES_INITDB_ARGS:'--data-checksums'
    volumes:
      # NAS | CONTAINER
      # Replace the left side (Left:Right) with your path to the DB folder in the NAS
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:

```

### Your .env content

```Shell
NODE_ENV=production
TZ=US/Michigan
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=immichpw
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=log
JWT_SECRET={HIDDEN}
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/489a83ce-ded9-4cd6-9f84-e7a0ebbb1744" />

1. Go to the backup page
2. Select albums to backup. In my case only recents (i.e all photos) sync albums disabled.
3.  Start backup. when the remainder hits 9 it simply does not continue even if stopping/starting the process. 
...

### Relevant log output

```shell

```
