### ISSUE TITLE
Oauth: OperationProcessingError: unexpected JWT "alg" header parameter

### ISSUE THREAD

**Issue by xiaoman1221** [immich-app/immich#19445]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I used Logto (https://docs.logto.io/introduction) for verification, but there was a problem (see below for details).
The settings are as follows:

![Image](https://github.com/user-attachments/assets/3197f406-a012-400a-aa96-fad808fad8d8)

![Image](https://github.com/user-attachments/assets/ef5116ce-20cc-4250-849a-dfe27c980a54)

This is Logto Config:

![Image](https://github.com/user-attachments/assets/ae791c76-1981-40f2-bdea-81818e03317e)

![Image](https://github.com/user-attachments/assets/f26c9751-acda-4da2-a33e-dfdcfddbfba2)

![Image](https://github.com/user-attachments/assets/92da21ff-89ec-420f-a2e8-864c50cb7a24)

### The OS that Immich Server is running on

DSM 7.2(Synology) Docker

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.nju.edu.cn/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

docker-compose up
setting Logto
setting Immich
test login and faild

### Relevant log output

```shell
immich_server    | [Nest] 17  - 06/23/2025, 2:29:23 AM   ERROR [Api:OAuthRepository~uw4o4jxi] OAuth login failed: invalid response encountered
immich_server    | [Nest] 17  - 06/23/2025, 2:29:23 AM   ERROR [Api:OAuthRepository~uw4o4jxi] ClientError: invalid response encountered
immich_server    |     at e (file:///usr/src/app/node_modules/openid-client/build/index.js:116:12)
immich_server    |     at errorHandler (file:///usr/src/app/node_modules/openid-client/build/index.js:139:23)
immich_server    |     at authorizationCodeGrant (file:///usr/src/app/node_modules/openid-client/build/index.js:953:9)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:53:28)
immich_server    |     at async AuthService.link (/usr/src/app/dist/services/auth.service.js:251:34) {
immich_server    |   code: 'OAUTH_INVALID_RESPONSE',
immich_server    |   [cause]: OperationProcessingError: unexpected JWT "alg" header parameter
immich_server    |       at OPE (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:92:12)
immich_server    |       at checkSigningAlgorithm (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1924:19)
immich_server    |       at validateJwt (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1655:5)
immich_server    |       at processGenericAccessTokenResponse (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1184:39)
immich_server    |       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |       at async processAuthorizationCodeOAuth2Response (file:///usr/src/app/node_modules/oauth4webapi/build/index.js:1373:20)
immich_server    |       at async authorizationCodeGrant (file:///usr/src/app/node_modules/openid-client/build/index.js:942:18)
immich_server    |       at async OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:53:28)
immich_server    |       at async AuthService.link (/usr/src/app/dist/services/auth.service.js:251:34) {
immich_server    |     code: 'OAUTH_INVALID_RESPONSE',
immich_server    |     [cause]: {
immich_server    |       header: {
immich_server    |         alg: 'ES384',
immich_server    |         typ: 'JWT',
immich_server    |         kid: 'T6G849oDGUQHfidP--bm1aSKX8_hsYCrl088of-uk-E'
immich_server    |       },
immich_server    |       expected: 'RS256',
immich_server    |       reason: 'client configuration'
immich_server    |     }
immich_server    |   }
immich_server    | }
immich_server    | [Nest] 17  - 06/23/2025, 2:29:23 AM   ERROR [Api:ErrorInterceptor~uw4o4jxi] Unknown error: Error: OAuth login failed
immich_server    | Error: OAuth login failed
immich_server    |     at OAuthRepository.getProfile (/usr/src/app/dist/repositories/oauth.repository.js:69:19)
immich_server    |     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
immich_server    |     at async AuthService.link (/usr/src/app/dist/services/auth.service.js:251:34)
```
