### ISSUE TITLE
The map feature no longer displays preview information.

### ISSUE THREAD

**Issue by NoChantingWaterMagic** [immich-app/immich#19450]
In the older version of Immich, when using the map feature, clicking on the purple number bubbles would display a preview with thumbnails of all the photos taken at that location. This made it easy for me to quickly find the pictures and videos I wanted to view, and it was also very intuitive.

However, in the latest version of Immich, this feature seems to have disappeared — I’m not sure whether it’s due to a bug or a change in product design. Now, when I click on a purple number bubble, it takes me directly into full-screen photo viewing mode, and I can only scroll through the photos one by one. There's no way to quickly browse through them anymore.

As someone who loves photography, I often take thousands of photos at a single precise location. In such cases, using Immich now leads to a disaster like the one shown in the image below:

![Image](https://github.com/user-attachments/assets/26241b05-8003-49c1-ab15-f9b3bd9bb28a)

![Image](https://github.com/user-attachments/assets/5c08623a-a6ff-4c92-b7c5-f60b90797f7b)

I hope this issue can be addressed in a future version. What I would really like is to bring back the feature (which I believe existed in an older version of Immich) where clicking on a number bubble on the map would display a preview panel at the bottom showing thumbnails of all the photos taken at that location.

I'm not entirely sure if this feature was in Immich or if I’m remembering it from PhotoPrism, as I often use both. But either way, such a feature would be very intuitive and user-friendly.

Thank you for all your hard work — I really appreciate it!

### The OS that Immich Server is running on

Windows server 2022

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.1

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ############:/extlib
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '####:####'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:905c4ee67b8e0aa955331960d2aa745781e6bd89afc44a8584bfd13bc890f0ae
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION= ################
# The location where your database files are stored
DB_DATA_LOCATION= ################

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=postgresAzusa

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgresAzusa
DB_DATABASE_NAME=immichAzusa

# set external path
EXTERNAL_PATH=##########
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
