### ISSUE TITLE
error: PostgresError: insert or update on table "exif" violates foreign key constraint

### ISSUE THREAD

**Issue by suncore** [immich-app/immich#19451]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Getting lots of this in the output:

```
Query failed : {
immich_server            |   durationMs: 3.4763009999878705,
immich_server            |   error: PostgresError: insert or update on table "exif" violates foreign key constraint "FK_c0117fdbc50b917ef9067740c44"
immich_server            |       at ErrorResponse (/usr/src/app/node_modules/postgres/cjs/src/connection.js:790:26)
immich_server            |       at handle (/usr/src/app/node_modules/postgres/cjs/src/connection.js:476:6)
immich_server            |       at Socket.data (/usr/src/app/node_modules/postgres/cjs/src/connection.js:315:9)
immich_server            |       at Socket.emit (node:events:518:28)
immich_server            |       at addChunk (node:internal/streams/readable:561:12)
immich_server            |       at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
immich_server            |       at Readable.push (node:internal/streams/readable:392:5)
immich_server            |       at TCP.onStreamRead (node:internal/stream_base_commons:189:23)
immich_server            |       at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
immich_server            |     severity_local: 'ERROR',
immich_server            |     severity: 'ERROR',
immich_server            |     code: '23503',
immich_server            |     detail: 'Key (assetId)=(264dea0e-3813-474d-b56c-f71155468a84) is not present in table "assets".',
immich_server            |     schema_name: 'public',
immich_server            |     table_name: 'exif',
immich_server            |     constraint_name: 'FK_c0117fdbc50b917ef9067740c44',
immich_server            |     file: 'ri_triggers.c',
immich_server            |     line: '2528',
immich_server            |     routine: 'ri_ReportViolation'
immich_server            |   },
immich_server            |   sql: 'insert into "exif" ("assetId", "dateTimeOriginal", "modifyDate", "timeZone", "latitude", "longitude", "country", "state", "city", "fileSizeInByte", "exifImageHeight", "exifImageWidth", "orientation", "projectionType", "bitsPerSample", "colorspace", "make", "model", "fps", "iso", "exposureTime", "lensModel", "fNumber", "focalLength", "description", "profileDescription", "rating", "livePhotoCID", "autoStackId") values ($1::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29) on conflict ("assetId") do update set "description" = "excluded"."description", "exifImageWidth" = "excluded"."exifImageWidth", "exifImageHeight" = "excluded"."exifImageHeight", "fileSizeInByte" = "excluded"."fileSizeInByte", "orientation" = "excluded"."orientation", "dateTimeOriginal" = "excluded"."dateTimeOriginal", "modifyDate" = "excluded"."modifyDate", "timeZone" = "excluded"."timeZone", "latitude" = "excluded"."latitude", "longitude" = "excluded"."longitude", "projectionType" = "excluded"."projectionType", "city" = "excluded"."city", "livePhotoCID" = "excluded"."livePhotoCID", "autoStackId" = "excluded"."autoStackId", "state" = "excluded"."state", "country" = "excluded"."country", "make" = "excluded"."make", "model" = "excluded"."model", "lensModel" = "excluded"."lensModel", "fNumber" = "excluded"."fNumber", "focalLength" = "excluded"."focalLength", "iso" = "excluded"."iso", "exposureTime" = "excluded"."exposureTime", "profileDescription" = "excluded"."profileDescription", "colorspace" = "excluded"."colorspace", "bitsPerSample" = "excluded"."bitsPerSample", "rating" = "excluded"."rating", "fps" = "excluded"."fps"',
immich_server            |   params: [
immich_server            |     '264dea0e-3813-474d-b56c-f71155468a84',
immich_server            |     2017-09-01T10:25:39.690Z,
immich_server            |     2017-09-01T08:25:42.000Z,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     2724001,
immich_server            |     4640,
immich_server            |     3480,
immich_server            |     null,
immich_server            |     null,
immich_server            |     8,
immich_server            |     'sRGB',
immich_server            |     'OnePlus',
immich_server            |     'ONEPLUS A3003',
immich_server            |     null,
immich_server            |     160,
immich_server            |     '1/50',
immich_server            |     null,
immich_server            |     2,
immich_server            |     4.26,
immich_server            |     '',
immich_server            |     null,
immich_server            |     null,
immich_server            |     null,
immich_server            |     null
immich_server            |   ]
immich_server            | }
```

### The OS that Immich Server is running on

Ubuntu 25.04

### Version of Immich Server

1.135.3

### Version of Immich Mobile App

1.135.3

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /a/images/archive:/mnt/henrik:ro
      - /a/images/ika:/mnt/ika:ro
      - /a/ika/s20foldersync:/mnt/ikaincoming:ro
      - /a/images/amely:/mnt/amely:ro
      - /a/images/elivia:/mnt/elivia:ro
      - /a/images/mireya:/mnt/mireya:ro
      - /dev/dri:/dev/dri
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. I was scanning external libraries. Don't know how to reproduce.
2.
3.
...

### Relevant log output

```shell

```
