### ISSUE TITLE
File Location (Within Image Info) Not working anymore

### ISSUE THREAD

**Issue by gregstah** [immich-app/immich#19549]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

In the image Info panel:

Clicking on an image File location takes you to top level folders instead of the actual image file location. 

**EG:** 

https://immich.myserver.com/folders?path=%2Fhome%2Fuser%2Fgallery_immich%2F2019%2F03%2F2019.03.09+Chantel+and+Peter+-+Zimbali+Country+Club+Durban%2FFinal

Takes you to: 

https://immich.myserver.com/folders?path=

I believe it's stopped working in the most recent two or three updates. 

### The OS that Immich Server is running on

OMV

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.1 Build.202

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${immich_VERSION}
    volumes:
      - ${immich_UPLOAD_LOCATION}:/usr/src/app/upload
      #- /srv/dev-disk-by-uuid-fd535abe-33ce-4721-ab7d-88a07d6bf7f9/gallery_immich:/home/user/gallery_immich
      - /srv/dev-disk-by-id-ata-WDC_WD50EFRX-68MYMN1_WD-WX11D4421832-part1/gallery_immich:/home/user/gallery_immich
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${immich_DB_PASSWORD}
      DB_USERNAME: ${immich_DB_USERNAME}
      DB_DATABASE_NAME: ${immich_DB_DATABASE_NAME}
      DB_HOSTNAME: ${immich_DB_HOSTNAME}
      REDIS_HOSTNAME: ${immich_REDIS_HOSTNAME}
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${immich_VERSION}
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${immich_DB_PASSWORD}
      POSTGRES_USER: ${immich_DB_USERNAME}
      POSTGRES_DB: ${immich_DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${immich_DB_DATA_LOCATION}:/var/lib/postgresql/data
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="$${user}", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${immich_DB_USERNAME} -d ${immich_DB_DATABASE_NAME} || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5

volumes:
  model-cache:
```

### Your .env content

```Shell
immich_UPLOAD_LOCATION=/srv/dev-disk-by-uuid-fd535abe-33ce-4721-ab7d-88a07d6bf7f9/photos
immich_DB_DATA_LOCATION=/config/immich
immich_VERSION=release
immich_DB_PASSWORD=password
immich_DB_HOSTNAME=immich_postgres
immich_DB_USERNAME=postgres
immich_DB_DATABASE_NAME=immich
immich_REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

1. Load any image
2. Click on Info
3. Scroll to Filename and click on the "i" to show file location
4. Click on the file location link
...

### Relevant log output

```shell

```
