### ISSUE TITLE
Face recognition  not working ugreen nas

### ISSUE THREAD

**Issue by highgrade8** [immich-app/immich#19589]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Face recognition  not working on ugreen nas

### The OS that Immich Server is running on

Ugreen Nas

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

1.135.1

### Platform with the issue

- [x] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 999:10
    environment:
      - TZ=Europe/Bucharest
    volumes:
      - /volume1/docker/immich/redis:/data:rw
    restart: on-failure:5

  immich-db:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.2.0
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data:rw
    environment:
      - TZ=Europe/Bucharest
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
      #- DB_STORAGE_TYPE=HDD #Remove the red # in front of the – DB_STORAGE_TYPE=HDD if your database isn’t stored on SSDs.
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: Immich-SERVER
    hostname: immich-server
    user: 999:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    ports:
      - 8212:2283
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 999:10
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload:rw
      - /volume1/docker/immich/cache:/cache:rw
      - /volume1/docker/immich/matplotlib:/matplotlib:rw
    environment: 
      - MPLCONFIGDIR=/matplotlib
    restart: on-failure:5
    depends_on:
      immich-db:
        condition: service_started
```

### Your .env content

```Shell
n
```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell
/tmp/matplotlib-0umjam2g because the default path  
                             (/matplotlib) is not a writable directory; it is   
                             highly recommended to set the MPLCONFIGDIR         
                             environment variable to a writable directory, in   
                             particular to speed up the import of Matplotlib and
                             to better support multiprocessing.                 
[06/28/25 08:01:39] INFO     Started server process [9]                         
[06/28/25 08:01:39] INFO     Waiting for application startup.                   
[06/28/25 08:01:39] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[06/28/25 08:01:39] INFO     Initialized request thread pool with 6 threads.    
[06/28/25 08:01:39] INFO     Application startup complete.                      
[06/28/25 08:03:37] INFO     Downloading detection model 'buffalo_l'. This may  
                             take a while.                                      
Ignored error while writing commit hash to /cache/facial-recognition/buffalo_l/models--immich-app--buffalo_l/refs/main: [Errno 13] Permission denied: '/cache/facial-recognition'.
[06/28/25 08:03:37] WARNING  Ignored error while writing commit hash to         
                             /cache/facial-recognition/buffalo_l/models--immich-
                             app--buffalo_l/refs/main: [Errno 13] Permission    
                             denied: '/cache/facial-recognition'.               

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
[06/28/25 08:03:37] WARNING  Failed to load detection model 'buffalo_l'.        
                             Clearing cache.                                    
[06/28/25 08:03:37] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist                     
[06/28/25 08:03:37] INFO     Downloading detection model 'buffalo_l'. This may  
                             take a while.                                      
Ignored error while writing commit hash to /cache/facial-recognition/buffalo_l/models--immich-app--buffalo_l/refs/main: [Errno 13] Permission denied: '/cache/facial-recognition'.
[06/28/25 08:03:37] WARNING  Ignored error while writing commit hash to         
                             /cache/facial-recognition/buffalo_l/models--immich-
                             app--buffalo_l/refs/main: [Errno 13] Permission    
                             denied: '/cache/facial-recognition'.               

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
[06/28/25 08:03:37] WARNING  Failed to load detection model 'buffalo_l'.        
                             Clearing cache.                                    
[06/28/25 08:03:37] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist                     
[06/28/25 08:09:19] INFO     Shutting down due to inactivity.                   
[06/28/25 08:09:19] INFO     Shutting down                                      
[06/28/25 08:09:19] INFO     Waiting for application shutdown.                  
[06/28/25 08:09:19] INFO     Application shutdown complete.                     
[06/28/25 08:09:19] INFO     Finished server process [9]                        
[06/28/25 08:09:19] ERROR    Worker (pid:9) was sent SIGINT!                    
[06/28/25 08:09:19] INFO     Booting worker with pid: 140                       
[06/28/25 08:09:20] WARNING  Matplotlib created a temporary cache directory at  
                             /tmp/matplotlib-1ezcmirk because the default path  
                             (/matplotlib) is not a writable directory; it is   
                             highly recommended to set the MPLCONFIGDIR         
                             environment variable to a writable directory, in   
                             particular to speed up the import of Matplotlib and
                             to better support multiprocessing.                 
[06/28/25 08:09:20] INFO     Started server process [140]                       
[06/28/25 08:09:20] INFO     Waiting for application startup.                   
[06/28/25 08:09:20] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[06/28/25 08:09:20] INFO     Initialized request thread pool with 6 threads.    
[06/28/25 08:09:20] INFO     Application startup complete.                      
[06/28/25 08:11:13] INFO     Downloading detection model 'buffalo_l'. This may  
                             take a while.                                      
Ignored error while writing commit hash to /cache/facial-recognition/buffalo_l/models--immich-app--buffalo_l/refs/main: [Errno 13] Permission denied: '/cache/facial-recognition'.
[06/28/25 08:11:13] WARNING  Ignored error while writing commit hash to         
                             /cache/facial-recognition/buffalo_l/models--immich-
                             app--buffalo_l/refs/main: [Errno 13] Permission    
                             denied: '/cache/facial-recognition'.               

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
[06/28/25 08:11:13] WARNING  Failed to load detection model 'buffalo_l'.        
                             Clearing cache.                                    
[06/28/25 08:11:13] INFO     Downloading detection model 'buffalo_l'. This may  
                             take a while.                                      
[06/28/25 08:11:13] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist                     
Ignored error while writing commit hash to /cache/facial-recognition/buffalo_l/models--immich-app--buffalo_l/refs/main: [Errno 13] Permission denied: '/cache/facial-recognition'.
[06/28/25 08:11:13] WARNING  Ignored error while writing commit hash to         
                             /cache/facial-recognition/buffalo_l/models--immich-
                             app--buffalo_l/refs/main: [Errno 13] Permission    
                             denied: '/cache/facial-recognition'.               

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]
[06/28/25 08:11:13] WARNING  Failed to load detection model 'buffalo_l'.        
                             Clearing cache.                                    
[06/28/25 08:11:13] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist                     
[06/28/25 08:19:30] INFO     Shutting down due to inactivity.                   
[06/28/25 08:19:30] INFO     Shutting down                                      
[06/28/25 08:19:30] INFO     Waiting for application shutdown.                  
[06/28/25 08:19:30] INFO     Application shutdown complete.                     
[06/28/25 08:19:30] INFO     Finished server process [140]                      
[06/28/25 08:19:30] ERROR    Worker (pid:140) was sent SIGINT!                  
[06/28/25 08:19:30] INFO     Booting worker with pid: 306                       
[06/28/25 08:19:31] WARNING  Matplotlib created a temporary cache directory at  
                             /tmp/matplotlib-vta6cqxz because the default path  
                             (/matplotlib) is not a writable directory; it is   
                             highly recommended to set the MPLCONFIGDIR         
                             environment variable to a writable directory, in   
                             particular to speed up the import of Matplotlib and
                             to better support multiprocessing.                 
[06/28/25 08:19:31] INFO     Started server process [306]                       
[06/28/25 08:19:31] INFO     Waiting for application startup.                   
[06/28/25 08:19:31] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[06/28/25 08:19:31] INFO     Initialized request thread pool with 6 threads.    
[06/28/25 08:19:31] INFO     Application startup complete.
```
