### ISSUE TITLE
Uploaded photos are never moved out of the upload folder

### ISSUE THREAD

**Issue by Soukyuu** [immich-app/immich#19591]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I just opened my library folder and realized that no photos newer than November 2024 are present in it.

I can see that all the newer photos are still in the upload folder, running the storage template does not do anything.

The photos appear like this in immich:

![Image](https://github.com/user-attachments/assets/0270887a-2c8a-4ee7-9992-29a5f040578b)

That's not the folder layout on the filesystem, though:

![Image](https://github.com/user-attachments/assets/1b8ef09b-e837-44a8-9a17-bce29cf8980f)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.135.0

### Version of Immich Mobile App

v1.135.0

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/photo:/mnt/photos:ro
    env_file:
      - .env
    ports:
      - 2283:2283
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false
  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: --data-checksums
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
volumes:
  model-cache: null
networks:
  proxy-network:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./data
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=xx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. Let immich upload a photo with the android app
2. Verify on the web interface the image was uploaded
3. Look at the path where the image was stored

### Relevant log output

```shell
immich_server            |   id: 'e93b9926-98b8-4eea-81c9-6f64dad0be7c',
immich_server            |   oldPath: 'upload/upload/0b263e7f-c867-4b56-aeaa-4b5217b4d01d/68/6a/686a98d0-7d75-4821-b162-073b56a0e1ed.jpg',
immich_server            |   newPath: 'upload/library/user/2022-03/PXL_20220327_132910048 - Copy.jpg'
immich_server            | }
immich_server            | [Nest] 7  - 06/28/2025, 2:50:14 PM   ERROR [Microservices:StorageTemplateService] Problem applying storage template
immich_server            | [Nest] 7  - 06/28/2025, 2:50:14 PM   ERROR [Microservices:StorageTemplateService] Error: EACCES: permission denied, mkdir 'upload/library/user/2022-06'
```

### Additional information

Did the target folder where the library is located change with an immich version?

I'm pretty sure the library folder was under `UPLOAD_LOCATON/library`, not `UPLOAD_LOCATION/upload/library`
