### ISSUE TITLE
Items incorrectly marked as "On Device Only" and not downloading new items from server on mobile

### ISSUE THREAD

**Issue by carlosomarpabon** [immich-app/immich#19594]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Symptoms:

1. My phones automatically upload photos to the server (this is good), but the photos continue to be marked as "On device only" on one of the devices. This prevents on-server actions like "Add to Album".
2. My phones don't download or even display any new photos from the server that were taken with a different device.

Here's what I've tried to fix this but did not work:

1. I removed my devices from the server and logged back in.
2. I deleted the App Storage and App Cache on my devices.
3. I used the "Check for corrupt assets backups" feature. It crashes the app consistantly but this seems to be a known issue based on other reports.
4. I deleted every photo on my phone.
5. As suggested by others, I have added the following to my proxy in order to facilitate uploading large files:
```
# Disable buffers to fix large uploads.
proxy_request_buffering off;
proxy_buffering off;
client_max_body_size 0;
```
6. I bypassed my proxy when connected to my local network in order to interact more directly with the server

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

1.135.1 build.202

### Platform with the issue

- [x] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accele>
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your>
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the ima>
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
# extends: # uncomment this section for hardware acceleration - see https://immich.app/>
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for >
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7>
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on y>
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 immich_server immich_machine_learning immich_redis immich_postg>
    depends_on:
      - immich-server
      - immich-machine-learning
      - redis
      - database
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs>

# The location where your uploaded files are stored
UPLOAD_LOCATION=../uploads

# The location where your database files are stored. Network shares are not supported for t>
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from thi>
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=REDACTED
DB_DATABASE_NAME=REDACTED
```

### Reproduction steps

I'm not sure why this started. It might have started when the app tried to upload a large video through the reverse proxy. The reverse proxy has been fixed and confirmed to upload large videos now but this new issue persists.

### Relevant log output

```shell

```
