### ISSUE TITLE
Android app archived images in timeline

### ISSUE THREAD

**Issue by slipperybeluga** [immich-app/immich#19605]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

**Both server and app are on version 1.35.3**

As the title says, archived photos in the timeline. If I select one to view, it has the option "Unarchive" instead of "Archive", so these are recognized as archived but still being displayed in the timeline. 

### The OS that Immich Server is running on

Debian 12 bookworm

### Version of Immich Server

1.35.3

### Version of Immich Mobile App

1.35.3.build.2204

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # HW acceleration
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /path/upload:/usr/src/app/upload
      - /path/pictures/:/pictures:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # The Immich version to use. You can pin this to a specific version like "v1.71.0"
      IMMICH_VERSION: release
      DB_USERNAME: immich
      DB_DATABASE_NAME: immich
      DB_PASSWORD: REDACTED
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false
    labels:
      # traefik and authentik stuff here
      

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    device_cgroup_rules:
      - 'c 189:* rmw'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/appdata/immich/model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:a19bebed6a91bd5e6e2106fef015f9602a3392deeb7c9ed47548378dcee3dfc2
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0@sha256:fa4f6e0971f454cd95fec5a9aaed2ed93d8f46725cc6bc61e0698e97dba96da1
    environment:
      POSTGRES_PASSWORD: REDACTED
      POSTGRES_USER: immich
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - /opt/appdata/immich/postgres:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
inline in docker-compose.yml above 😬
```

### Reproduction steps

Updated both server and app to 1.35.3. Opened app. 

### Relevant log output

```shell

```
