### ISSUE TITLE
[BUG] Not able to sync all images from iOS to Immich server

### ISSUE THREAD

**Issue by trustos** [immich-app/immich#1960]
### The bug

Hi there,
First let me say how glad I am that I found Immich! A great product! And as with all great products there is always some polishing to be done. 

So I am trying to upload my collection of 11 982 photos + videos from the Immich iOS app to the Immich server. I do have it set up on a subdomain. It all goes very well up until there are 31 images left in the Remainder section.

![IMG_473C4303008A-1](https://user-images.githubusercontent.com/12433240/223362421-f08ebafe-493d-4661-8d74-29abec19ce64.jpeg)

So from there the process goes nowhere.

In the Immich server docker logs I can see the following errors appearing, apparently for all the 31 images:
`2023-03-07 10:13:40 [Nest] 1  - 03/07/2023, 8:13:40 AM   ERROR [ExceptionsHandler] Could not find any entity of type "AssetEntity" matching: {
2023-03-07 10:13:40     "where": {
2023-03-07 10:13:40         "ownerId": "ffb0e981-4be2-442f-8981-5b3f3af8dcdb",
2023-03-07 10:13:40         "checksum": {
2023-03-07 10:13:40             "type": "Buffer",
2023-03-07 10:13:40             "data": [
2023-03-07 10:13:40                 169,
2023-03-07 10:13:40                 154,
2023-03-07 10:13:40                 99,
2023-03-07 10:13:40                 131,
2023-03-07 10:13:40                 125,
2023-03-07 10:13:40                 67,
2023-03-07 10:13:40                 160,
2023-03-07 10:13:40                 107,
2023-03-07 10:13:40                 151,
2023-03-07 10:13:40                 88,
2023-03-07 10:13:40                 208,
2023-03-07 10:13:40                 40,
2023-03-07 10:13:40                 74,
2023-03-07 10:13:40                 83,
2023-03-07 10:13:40                 37,
2023-03-07 10:13:40                 8,
2023-03-07 10:13:40                 159,
2023-03-07 10:13:40                 159,
2023-03-07 10:13:40                 174,
2023-03-07 10:13:40                 29
2023-03-07 10:13:40             ]
2023-03-07 10:13:40         }
2023-03-07 10:13:40     },
2023-03-07 10:13:40     "relations": [
2023-03-07 10:13:40         "exifInfo"
2023-03-07 10:13:40     ]
2023-03-07 10:13:40 }
2023-03-07 10:13:40 EntityNotFoundError: Could not find any entity of type "AssetEntity" matching: {
2023-03-07 10:13:40     "where": {
2023-03-07 10:13:40         "ownerId": "ffb0e981-4be2-442f-8981-5b3f3af8dcdb",
2023-03-07 10:13:40         "checksum": {
2023-03-07 10:13:40             "type": "Buffer",
2023-03-07 10:13:40             "data": [
2023-03-07 10:13:40                 169,
2023-03-07 10:13:40                 154,
2023-03-07 10:13:40                 99,
2023-03-07 10:13:40                 131,
2023-03-07 10:13:40                 125,
2023-03-07 10:13:40                 67,
2023-03-07 10:13:40                 160,
2023-03-07 10:13:40                 107,
2023-03-07 10:13:40                 151,
2023-03-07 10:13:40                 88,
2023-03-07 10:13:40                 208,
2023-03-07 10:13:40                 40,
2023-03-07 10:13:40                 74,
2023-03-07 10:13:40                 83,
2023-03-07 10:13:40                 37,
2023-03-07 10:13:40                 8,
2023-03-07 10:13:40                 159,
2023-03-07 10:13:40                 159,
2023-03-07 10:13:40                 174,
2023-03-07 10:13:40                 29
2023-03-07 10:13:40             ]
2023-03-07 10:13:40         }
2023-03-07 10:13:40     },
2023-03-07 10:13:40     "relations": [
2023-03-07 10:13:40         "exifInfo"
2023-03-07 10:13:40     ]
2023-03-07 10:13:40 }
2023-03-07 10:13:40     at /usr/src/app/node_modules/typeorm/entity-manager/EntityManager.js:604:39
2023-03-07 10:13:40     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-03-07 10:13:40     at async AssetService.uploadFile (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.service.js:74:35)
2023-03-07 10:13:40     at async AssetController.uploadFile (/usr/src/app/dist/apps/immich/apps/immich/src/api-v1/asset/asset.controller.js:60:29)`

Do you have any idea why this might be happening?

I have already tried reinstalling the server from scratch 3 times (inc deleting containers + volumes) without any improvements.

Let me know If I can provide you with any additional info.

### The OS that Immich Server is running on

MacOS Docker - latest immich container version

### Version of Immich Server

1.50.1

### Version of Immich Mobile App

1.50.0 build.88

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=[redacted]
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=[redacted]

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1.Start backing up images from iOS app.
2. At some point the backup stop.
```
