### ISSUE TITLE
Postgres Init fails for immich-server  v1.135.3

### ISSUE THREAD

**Issue by grkravi** [immich-app/immich#19621]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

Container creation on Kubernetes fails for ghcr.io/immich-app/immich-server:v1.135.3 with below error -
PostgresError: multiple primary keys for table "naturalearth_countries" are not allowed.

I am using my own CloudnativePG Postgres cluster 17.5 with vectors and other extensions along with  my own Redis.

### The OS that Immich Server is running on

Ubuntu 24.04.2 LTS

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

n/a

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
piVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server
  template:
    metadata:
      labels:
        app: immich-server
    spec:
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.135.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOSTNAME
              value: pg-cluster-rw.db.svc
            - name: DB_USERNAME
              value: immich-server
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_DATABASE_NAME
              value: vectordb
            - name: REDIS_HOSTNAME
              value: redis.media.svc
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: library
              mountPath: /usr/src/app/upload
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: longhorn-media
```

### Your .env content

```Shell
reference to Postgres and Redis
```

### Reproduction steps

1.kubectl apply -f immich.yaml
2.
3.
...

### Relevant log output

```shell
PostgresError: multiple primary keys for table "naturalearth_countries" are not allowed.
```
