### ISSUE TITLE
"Select albums" setting for backup is not persistent

### ISSUE THREAD

**Issue by RafalGardas** [immich-app/immich#19631]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

The backup settings in 'Backup Albums' are not persistent. For example, if the 'Camera' album is selected and then all its photos are deleted directly from the device (not through the Immich app), the 'Backup Albums' selection is cleared.

### The OS that Immich Server is running on

Debian 12 (bookworm)

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*****

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

Prerequisites:
There is one photo on my device in the 'Camera' album.

Steps: 
1. In 'Backup Albums', **I select the 'Camera' album** (see screenshot 1 attached), then return to 'Backup' screen.
2. **I click the 'Start Backup' button** and wait until the backup is complete (see screenshot 2 attached).
3. **I remove all images from the 'Camera' album directly from my device** (this action is performed outside the Immich app), effectively clearing all local photos.
4. **I navigate to the 'Backup' settings** (via the backup icon at the top right of the Immich app screen) to check the current settings.
5. **I take a new photo**, which is saved to the 'Camera' album by default on my device (this action is also performed outside the Immich app).
6. **I navigate to the 'Backup' settings** (via the backup icon at the top right of the Immich app screen) to check the current settings.

Observed result:
1. **After Step 4**, when viewing the 'Backup Albums' section, **no album is shown as selected**.
2. **After Step 5**, the new photo taken **does not appear** in the Immich app main screen.
3. **After Step 6**, when viewing the 'Backup Albums' section, **no album is shown as selected**.
4. After Step 6, the display shows "No photos are waiting for backup" ("Remaining": 0).

Expected result:
1. **After Step 5, the new photo should appear in the Immich app main screen**, as the 'Camera' album was selected in Step 1 and was never deselected by the user. It also contains the newly taken photo.
2. **The 'Camera' album should remain selected** in 'Backup Albums' **after both Step 4 and Step 6** (the user never deselected it).

### Relevant log output

```shell

```

### Additional information

![Image](https://github.com/user-attachments/assets/6d89640a-b110-4c67-9d9b-4f71dfb2ab2e)

![Image](https://github.com/user-attachments/assets/46561b97-ac5c-4d14-944d-18d9e04d9800)
