### ISSUE TITLE
server not using mtime when missing EXIF (possible regression on 4191)

### ISSUE THREAD

**Issue by PeterTheobald** [immich-app/immich#19636]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

When EXIF date is missing, the immich-server is not using the file mtime, as sent in both the fileCreatedAt and fileModifiedAt fields in the `http://localhost:2283/api/assets AssetUpload POST` call.
This seems to be a regression on [4191](https://github.com/immich-app/immich/pull/4191), which fixed the same issue.

The original file has a correct mtime set, but not ctime or atime, (as expected). The file does not have EXIF Dates:
```
# exiftool /srv/family/photos,videos/Skya-iphone-2025-06-19-orig/2X3A5716.JPEG | grep "Date/Time"
File Modification Date/Time     : 2024:04:30 12:15:27-07:00
File Access Date/Time           : 2025:06:20 21:33:51-07:00
File Inode Change Date/Time     : 2025:06:22 15:56:59-07:00
```

Upload the file with immich-go:
```
# grep 2X3A5716 immich-go_2025-06-29_18-07-07.log
2025-06-29 18:07:07 INF scanned image file file=Skya-iphone-2025-06-19-orig:2X3A5716.JPEG
2025-06-29 18:07:09 WRN Info file=Skya-iphone-2025-06-19-orig:2X3A5716.JPEG warning=can't read metadata: exif: tag "DateTime" is not present
2025-06-29 18:07:09 INF uploaded file=Skya-iphone-2025-06-19-orig:2X3A5716.JPEG
```

Immich-go trace logs show the mtime is correctly sent to the server as BOTH fileCreatedAt and fileModifiedAt: (this is good, filesystem ctime would be useless)
```
  Post values
     assetType:  image
     deviceAssetId:  2X3A5716.JPEG-2140894
     deviceId:  sybil
     duration:  00:00:00.000000
     fileCreatedAt:  2024-04-30T19:15:27Z
     fileExtension:  .JPEG
     fileModifiedAt:  2024-04-30T19:15:27Z
     isArchived:  false
     isFavorite:  false
     isReadOnly:  false
```

Immich database shows the record with incorrect DateTime:
```
id          | originalFileName |    originalPath  |     fileCreatedAt      | visibility
5459d459-9c2e-48e2-8c63-2ca279fc34de | 2X3A5716.JPEG    | upload/library/e8175349-5cdd-4367-9dec-ae4a369108a2/2025/2025-06/2025-06-19 00.00.00.jpg | 2025-06-19 07:00:00+00 | timeline
```

The fileCreatedAt (and Storage Template path and filename) aren't using the mtime. The minutes and seconds are 00.00. The only place I could imagine this came from was the original upload file path has 2025-06-19 in it, which is the date the iPhone was downloaded and totally unrelated to this photo.

Here is the file stored in the library:
```
# ls 2025/2025-06/2025-06-19\ 00.00.00.jpg*
'2025/2025-06/2025-06-19 00.00.00.jpg'  '2025/2025-06/2025-06-19 00.00.00.jpg.xmp'
```

And the sidecar has the same incorrect dates:
```
# grep DateTimeOriginal "2025/2025-06/2025-06-19 00.00.00.jpg.xmp"
  <exif:DateTimeOriginal>2025-06-19T00:00:00-07:00</exif:DateTimeOriginal>
```

### The OS that Immich Server is running on

Ubuntu 18.04.6 LTS host, Debian GNU/Linux trixie/sid docker container

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

NA

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #environment:
    #  - HOST=0.0.0.0
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    #user: "1002:1003"
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    #user: "1002:1003"
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
    #user: "1002:1003"
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    #user: "1002:1003"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      # DB_STORAGE_TYPE: 'HDD'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/family/main-photo-video-library

# The location where your database files are stored. Network shares are not supported for the database
DB_DATA_LOCATION=./postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
# TZ=Etc/UTC
TZ=America/Los_Angeles

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=*REDACTED*

# Customized by PJT:
#IMMICH_HOST=0.0.0.0

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

1. upload image without EXIF data using immich-go (see detailed desc. above)
2.
3.
...

### Relevant log output

```shell
see above
```
