### ISSUE TITLE
Archived photos are not shown on the map when "Include archived" is selected

### ISSUE THREAD

**Issue by rovitsky** [immich-app/immich#19640]
### I have searched the existing issues, both open and closed, to make sure this is not a duplicate report.

- [x] Yes

### The bug

I have quite a lot of photos in archive. When I select "Include archived" in the map settings, these files do not appear on the map. The bug reproduces in Web and in Android app (can't confirm if this happens on iPhone as well or not).

Web with excluded archived assets:
![Image](https://github.com/user-attachments/assets/14ac91f0-ccf7-477e-b552-2e5293ad163b)

Web with included archived assets (settings were saved between these screenshots and the page was reloaded):
![Image](https://github.com/user-attachments/assets/6b4d8003-a65c-4372-aec9-50d87de8d612)

Non-empty archive:
![Image](https://github.com/user-attachments/assets/1c664d4f-def8-4894-94fa-49c9ead7612f)

Details of the archived photo that has location data (can confirm that this photo doesn't appear on the map with either settings):
![Image](https://github.com/user-attachments/assets/6f8996e0-201f-49d4-a1a0-9434599769ec)

Android app behaves pretty much the same - screenshots are identical for both situations:
![Image](https://github.com/user-attachments/assets/fdaa186c-a33a-47c1-9297-68353a0be94b)

Logs only have opened/closed websocket connections and one error while uploading a deleted photo which is not related to the problem with archive - it has started quite a bit later after the archive issue started to reproduce.

### The OS that Immich Server is running on

Docker on Ubuntu 24.04.1 LTS (VM in Hyper-V on Win11 Pro x86-64)

### Version of Immich Server

v1.135.3

### Version of Immich Mobile App

v1.135.3

### Platform with the issue

- [ ] Server
- [x] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
services:
  redis:
    image: redis:7.2.5-alpine3.20
    container_name: immich_redis
    networks:
      - immich
    restart: unless-stopped

  db:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich_db
    volumes:
      - /data/photos/db:/var/lib/postgresql/data
      - /data/photos/secrets:/run/secrets
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      - immich
    restart: unless-stopped
  db_backup:
    image: prodrigestivill/postgres-backup-local:14-alpine-3495539
    container_name: immich_db_backup
    user: "1000:1000"
    volumes:
      - /data/dbbackups/immich:/backups
      - /data/photos/secrets:/run/secrets
    environment:
      POSTGRES_HOST: immich_db
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      SCHEDULE: "@daily"
      TZ: {{LocalTimezone}}
    networks:
      - immich
    restart: unless-stopped
    depends_on:
      - db

  server:
    image: ghcr.io/immich-app/immich-server:v1.135.3
    container_name: immich_server
    ports:
      - 2283:2283
      - 20081:8081
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/photos/library:/usr/src/app/upload
      - /data/photos/ext:/usr/src/app/external
      - /data/photos/secrets:/run/secrets
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_DATABASE_NAME_FILE: /run/secrets/db_name
      REDIS_HOSTNAME: immich_redis
      TZ: {{LocalTimezone}}
      IMMICH_TELEMETRY_INCLUDE: all
    networks:
      - immich
    restart: unless-stopped
    depends_on:
      - redis
      - db
  
  ml:
    image: ghcr.io/immich-app/immich-machine-learning:v1.135.3
    container_name: immich_ml
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/photos/ml-cache:/cache
      - /data/photos/secrets:/run/secrets
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_DATABASE_NAME_FILE: /run/secrets/db_name
      REDIS_HOSTNAME: immich_redis
    networks:
      - immich
    restart: unless-stopped
    depends_on:
      - redis
      - db

networks:
  immich:
    name: immich_net
```

### Your .env content

```Shell
I have no .env file. Compose file is transformed during the deployment
```

### Reproduction steps

Scenario A: 
1. Open the map view in the web app
2. Open options, select "Include archived" and save changes

Scenario B:
1. Open Android app
2. Open Library
3. Select "Places"
4. Tap on map image
5. Open options, select "Include Archived", wait for a quick loader to confirm that changes are saved and close settings bottom sheet

Expected behavior (for both platforms): more photos shown on the map
Actual behavior (for both platforms): the same number of photos is shown on the map

### Relevant log output

```shell

```
