### ISSUE TITLE
[BUG] Thumbnail and metadata extraction timeouts when uploading several images at once

### ISSUE THREAD

**Issue by raisinbear** [immich-app/immich#1967]
### The bug

Hi,

As far as I'm aware this is new to one of the more recent releases as I haven't encountered this issue before. In short: when uploading several images - have tested with 10 .heic photos for instance - via mobile app / CLI / Web, I get quite the number of timeout errors from the microservices container à la:

```
immich-immich-microservices-1  | [Nest] 1  - 03/07/2023, 12:46:24 PM   ERROR [MediaService] Failed to generate jpeg thumbnail for asset: f0929d05-f79a-4917-ad82-2cd9d9c45998
immich-immich-microservices-1  | Error: Connection terminated due to connection timeout
immich-immich-microservices-1  |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
immich-immich-microservices-1  |     at Object.onceWrapper (node:events:641:28)
immich-immich-microservices-1  |     at Connection.emit (node:events:527:28)
immich-immich-microservices-1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
immich-immich-microservices-1  |     at Socket.emit (node:events:527:28)
immich-immich-microservices-1  |     at TCP.<anonymous> (node:net:709:12)
```

```
immich-immich-microservices-1  | [Nest] 1  - 03/07/2023, 12:45:40 PM   ERROR [MetadataExtractionProcessor] Error extracting EXIF Error: Connection terminated due to connection timeout
immich-immich-microservices-1  | Error: Connection terminated due to connection timeout
immich-immich-microservices-1  |     at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)
immich-immich-microservices-1  |     at Object.onceWrapper (node:events:641:28)
immich-immich-microservices-1  |     at Connection.emit (node:events:527:28)
immich-immich-microservices-1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:57:12)
immich-immich-microservices-1  |     at Socket.emit (node:events:527:28)
immich-immich-microservices-1  |     at TCP.<anonymous> (node:net:709:12)
immich_postgres                | 2023-03-07 12:45:44.963 UTC [1598] LOG:  could not receive data from client: Connection reset by peer
immich_postgres                | 2023-03-07 12:45:44.964 UTC [1599] LOG:  could not receive data from client: Connection reset by peer
```

Once CPU load goes down, a lot of thumbnails and metadata are missing. I assume this is in parts down to my server being generally slow to process the images and or utilized by other services at the time. At the same time, the timeout it is running into seems kind of overly strict. It isn't really that slow 😅. Also - even if _a lot_ of thumbnails / metadata are still missing, I can trigger creation in the web ui and that always succeeds.

I'll try to formulate my questions / suggestions structurally coherent:

- Has something changed in the backend that would explain why this happens now, with the recent release(s) but didn't in the past?
- The fact that the jobs, when triggered from web ui never fail with a timeout makes me wonder whether a queue is used here whereas on upload everything is attempted to be done at once.
- If it's just down to my machine being too slow, it would be great if the timeout were adjustable
- or if one could trigger the jobs via cli command in the container, making it possible to just set up a cron job on the host machine and forget about it
(- or if immich could itself schedule jobs for missing thumbnails / metadata on a regular basis. but that would probably mean ui work to set up the schedule, which imo could be overkill)

Thank you guys so much!

### The OS that Immich Server is running on

Raspbian Buster (32-bit)

### Version of Immich Server

v.1.50.1

### Version of Immich Mobile App

v.1.50.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/home/immich/data

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1. Setup immich on a not too fast machine 😉
2. Upload many images at once, mobile, web, cli, however you like. 
3. Observe timeout errors in log during metadata extraction / thumbnail creation
```
