### ISSUE TITLE
[BUG] unable to upload from android "Bad Request"

### ISSUE THREAD

**Issue by rhetr** [immich-app/immich#1972]
### The bug

I've uploaded a number of photos to my local immich server already but i am stuck on the most recent 24 photos.

Using the manual "start backup" it attempts to upload 61 times before hanging. The behavior is the same with automatic foreground backup as well as with automatic background backup.

When I clicked the "Failed (61)" button next to "Uploading file info" all it says is "Bad Request".

### The OS that Immich Server is running on

Ubuntu 20.04.5 LTS

### Version of Immich Server

v1.50.1

### Version of Immich Mobile App

1.46.0 build.69

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.http.services.immich_api.loadbalancer.server.port: 3001
      traefik.http.middlewares.immich_api_strip.stripprefix.prefixes: "/api"

      traefik.http.routers.immich_api.entrypoints: web
      traefik.http.routers.immich_api.rule: "HostRegexp(`pix{domain:.*}`) && Pathprefix(`/api`)"
      traefik.http.routers.immich_api.middlewares: immich_api_strip

      traefik.http.routers.immich_api_tls.service: immich_api
      traefik.http.routers.immich_api_tls.entrypoints: websecure
      traefik.http.routers.immich_api_tls.rule: "HostRegexp(`pix{domain:.*}`) && Pathprefix(`/api`)"
      traefik.http.routers.immich_api_tls.middlewares: immich_api_strip
      traefik.http.routers.immich_api_tls.tls: true

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: unless-stopped

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always
    networks:
      - traefik
      - default
    labels:
      traefik.enable: true
      traefik.http.routers.immich_web.rule: HostRegexp(`pix{domain:.*}`)
      traefik.http.routers.immich_web.entrypoints: web
      # traefik.http.routers.immich_web.middlewares: https_redirect@file
      traefik.http.routers.immich_tls.rule: HostRegexp(`pix{sdomain:.*}`)
      traefik.http.routers.immich_tls.entrypoints: websecure
      traefik.http.routers.immich_tls.tls: true
      traefik.http.routers.immich_tls.service: immich_web
      traefik.http.services.immich_web.loadbalancer.server.port: 3000
      traefik.http.services.immich_web.loadbalancer.server.scheme: http

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  traefik:
    external:
      name: "compose_traefnet"
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=***
DB_PASSWORD=***
DB_DATABASE_NAME=***
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=***
TYPESENSE_API_KEY=some-random-text
```

### Reproduction steps

```bash
1. login to mobile app
2. click the backup icon on the top right
3. click "Start Backup"
```
