### ISSUE TITLE
[BUG] REDIS Env not passed in to redis container in docker-compose

### ISSUE THREAD

**Issue by DragosRotaru** [immich-app/immich#1973]
### The bug

Looks like the docker-compose.yml file does not actually pass in the Redis environment variables shown in `example.env`

```
 redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
```

### The OS that Immich Server is running on

Any`

### Version of Immich Server

1.50.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
N/A (see default docker-compose.yml)
```

### Your .env content

```Shell
see example.env
```

### Reproduction steps

```bash
None
```

**Comment by alextran1502** [comment]
Did you change example.env to .env?

**Comment by DragosRotaru** [comment]
@alextran1502 

```
redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
```

its obvious just from reading this code that the environment variables have no effect. The `.env` file provided to docker-compose is not auto passed on to the container, for that you need to use the `env_file` key. Also, even if it was passed to the redis image as environment variables, the redis image would have no idea what to do with it because these settings need to be configured via the redis CLI or  via `redis.conf`. Doing a search on the repo, I see these variables are only used in Data Access Layer adapters, so I am highly confident they have no effect on Redis itself.

Sources:
- https://hub.docker.com/_/redis
- https://redis.io/docs/management/config/
- https://docs.docker.com/compose/environment-variables/set-environment-variables/
