### ISSUE TITLE
[BUG] Error while applying storage template

### ISSUE THREAD

**Issue by clam0r** [immich-app/immich#1996]
### The bug

When uploading media the immich_server log throws the following error:

```
[Nest] 1  - 03/14/2023, 2:30:40 PM   ERROR [AssetCore] Problem applying storage template

[Nest] 1  - 03/14/2023, 2:30:40 PM   ERROR [AssetCore] Error: ENOTSUP: operation not supported on socket, link 'upload/a68daa39-dcdb-48f5-acf6-e04250a59f6f/original/WEB/06d361e5-bb78-4dc0-ab8e-a11efa58e62c.png' -> 'upload/a68daa39-dcdb-48f5-acf6-e04250a59f6f/2015/2015-05-27/Screenshot_2015-05-27-16-54-12.png'

[Nest] 1  - 03/14/2023, 2:30:40 PM   ERROR [AssetCore] Object:

{

  "id": "cab59c65-c31f-4bef-b79c-92857d06c19b",

  "source": "upload/a68daa39-dcdb-48f5-acf6-e04250a59f6f/original/WEB/06d361e5-bb78-4dc0-ab8e-a11efa58e62c.png",

  "destination": "upload/a68daa39-dcdb-48f5-acf6-e04250a59f6f/2015/2015-05-27/Screenshot_2015-05-27-16-54-12.png"

}
```

The folders which should contain the images are empty

![grafik](https://user-images.githubusercontent.com/39246790/225041899-1fdb25f6-ec81-4d04-b213-9b328d626fb7.png)

 The images are apearently all stored at media/a68daa39-dcdb-48f5-acf6-e04250a59f6f/original
 
 As far as I can tell, this error is not affecting the main functions. I can still view, up- and download images.

I am using an AWS S3 Bucket mounted using S3FS

### The OS that Immich Server is running on

Ubuntu 22.04 

### Version of Immich Server

v1.50.1 Latest

### Version of Immich Mobile App

1.50.0 build.88

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - onlyoffense_network  

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - onlyoffense_network  
      
  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/clamor/proj_immich/model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - onlyoffense_network  
      
  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - stack.env
    restart: always
    networks:
      - onlyoffense_network  
      
  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - onlyoffense_network  
      
  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /home/clamor/proj_immich/sql/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - onlyoffense_network  

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - onlyoffense_network  
      
volumes:
  pgdata:
  model-cache:
  

networks:
  onlyoffense_network:
    external: true
    name: onlyoffense_network
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/home/clamor/proj_immich/media
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Upload image 
2. View container logs of immich_server, see error
```
