### ISSUE TITLE
[BUG] Gunicorn CPU & Memory utilization high even when no jobs running

### ISSUE THREAD

**Issue by uninvitedguest** [immich-app/immich#2074]
### The bug

After updating to include the typesense container and running the "Encode Clip" job, CPU and memory utilization by Gunicorn is still incredibly high.

![image](https://user-images.githubusercontent.com/24210277/227546781-cfd060ed-7700-4085-ab58-08f074281dfe.png)

Restarting the containers results in more moderate usage.

![image](https://user-images.githubusercontent.com/24210277/227553253-a5ae2115-a91b-4b17-9bee-1757f9ee7e7f.png)

Running on a Rock 5B SBC.

### The OS that Immich Server is running on

Armbian 23.02 Jammy

### Version of Immich Server

1.51.1

### Version of Immich Mobile App

1.51.0 Build 74

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - immich-internal

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich-internal

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/ssd/immich/model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - immich-internal

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - stack.env
    restart: always
    networks:
      - immich-internal

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /mnt/ssd/immich/tsdata:/data
    env_file:
      - stack.env
    networks:
      - immich-internal
      
  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - immich-internal

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /mnt/ssd/immich/database:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-internal
  
  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks:
      - proxy
      - immich-internal

volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  proxy:
    external: true
  immich-internal:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/ssd/immich/upload
TYPESENSE_API_KEY=api-key
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Click "All" to queue the Encode Clip job
2. Wait 2 days (in my case).
3. When all jobs are complete, check CPU utilization in gotop
```
