### ISSUE TITLE
[BUG] Resources Utilization Spike

### ISSUE THREAD

**Issue by azurecrash** [immich-app/immich#2134]
### The bug

I’ve deployed Immich and am trying to backup photos from iOS but after like 15 images, the resources on the server (an older 4 core x86 Mac mini) get DESTROYED by the micro services container and what appears to be ffmpeg. I am therefore assuming (perhaps incorrectly) that the transcode is killing the backup. Has been like 8 hours since deploy and I have 100 of 30k assets backed up!

My setup:
Compute: 2011 Mac mini, 4 core i5 x86, 4gb memory running Debian
Storage: Synology NAS drive, SMB share, mounted to the Mac mini

Other details:
The containers are all deployed through Portainer. Mobile app seems to work fine. Web interface seems to work fine. In writing this post and fetching the logs, I've noticed that the micro services container has restarted 104 times since it was created....

Logs from the micro services container are attached. Last 1000 lines.

[_immich_microservices_logs-5.txt](https://github.com/immich-app/immich/files/11117508/_immich_microservices_logs-5.txt)

Here is a graph of CPU load pre-and-post one of these backup spurts:

<img width="425" alt="Screenshot 2023-03-30 at 10 15 38 PM" src="https://user-images.githubusercontent.com/13999581/229005815-a6bbecf5-8e94-4c14-8cfa-b5a9e33f8246.png">

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.52.1

### Version of Immich Mobile App

1.52.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
  
  #
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/asp-photos/
TYPESENSE_API_KEY=some-random-text
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1.Instantiate containers with docker compose above.
2.Create admin user
3.Download and install iOS app (latest)
4.Initiate a foreground or background or manual backup
5.Observe 6-10 assets get uploaded then pause
6.Observe Server resource usage in Grafana get pegged
```
