### ISSUE TITLE
[BUG] iOS: Unable to build timeline and load albums in backup panel

### ISSUE THREAD

**Issue by SirBogner** [immich-app/immich#2170]
### The bug

My iOS device is stuck at loading both of the following, which I suspect might be linked.
- The timeline showing the local assets on device.
- The backup panel for picking which albums to back up. 

In the iOS settings is Immich allowed to access all photos on the device.

Let me know if you need any more information. 

### The OS that Immich Server is running on

Docker in Synology DSM 7.1.1

### Version of Immich Server

1.52.1

### Version of Immich Mobile App

1.52.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - /volume1/homes/docker/immich/photos:/usr/src/app/upload
    environment:
      DB_PASSWORD: hidden
      DB_USERNAME: hidden
      DB_HOSTNAME: immich_postgres
      DB_DATABASE_NAME: hidden
      ENABLE_MAPBOX: "true"
      MAPBOX_KEY: hidden
      NODE_ENV: production
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: /volume1/homes/docker/immich/photos
      JWT_SECRET: hidden
      VITE_SERVER_ENDPOINT: https://immich.hidden/api
      TYPESENSE_API_KEY: hidden
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /volume1/homes/docker/immich/photos:/usr/src/app/upload
    environment:
      NODE_ENV: production
      ENABLE_MAPBOX: "true"
      MAPBOX_KEY: hidden
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: /volume1/homes/docker/immich/photos
      JWT_SECRET: hidden
      DB_PASSWORD: hidden
      DB_USERNAME: hidden
      DB_HOSTNAME: immich_postgres
      DB_DATABASE_NAME: hidden
      VITE_SERVER_ENDPOINT: https://immich.hidden/api
      TYPESENSE_API_KEY: hidden
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      TYPESENSE_API_KEY: hidden
      TYPESENSE_DATA_DIR: /data
    logging:
      driver: none
    volumes:
      - /volume1/homes/docker/immich/tsdata:/data

  immich-machine-learning:
    image: bertmelis1/immich-machine-learning-noavx:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    expose:
      - "3000"
    volumes:
      - /volume1/homes/docker/immich/photos:/usr/src/app/upload
    environment:
      NODE_ENV: production
      REDIS_HOSTNAME: immich_redis
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      VITE_SERVER_ENDPOINT: https://immich.hidden/api 
    ports:
      - 2285:3000
    restart: always

  redis:
    container_name: immich_redis
    image: redis:latest
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: hidden
      POSTGRES_USER: hidden
      POSTGRES_DB: hidden
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /volume1/homes/docker/immich/database:/var/lib/postgresql/data
    restart: always
    
  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```

### Your .env content

```Shell
Included in the compose.
```

### Reproduction steps

```bash
1. Use a new iOS device with a new account
2. Try to enable backup by selecting albums to backup
3. Try letting the timeline load the local assets
```
