### ISSUE TITLE
[BUG] .dng files do not succussed in creating thumbnails

### ISSUE THREAD

**Issue by myhrmans** [immich-app/immich#2202]
### The bug

.dng files taken on Samsung S21 Ultra "Pro mode" fail in creating thumbnails. 

3 examples can be found here that are not successfully generated thumbnails:
https://data.myhrmans.com/s/Tt6yJGcLJKAPHqt

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.53.0

### Version of Immich Mobile App

v1.53.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
Not related to issue
```

### Reproduction steps

```bash
1.Download files here: https://data.myhrmans.com/s/Tt6yJGcLJKAPHqt
2. Upload to immich
3. Check logs of microservices
```

### Additional information

Log from microservices:

```
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:43 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:44 PM     LOG [MediaService] Generating Video Thumbnail Success 2e354c06-11fc-4002-8c91-df237118c9c7
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:44 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:45 PM     LOG [MediaService] Generating Video Thumbnail Success 8b25ee32-939e-4d16-8132-6522272ae3e3
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:47 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:47 PM     LOG [MediaService] Generating Video Thumbnail Success b4e38990-d152-402b-b339-619af6a40fbd
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:47 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=00868b4e-88e3-4086-8cbe-6739399f3de6)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:48 PM   ERROR [MediaService] Failed to generate thumbnail for asset: 00868b4e-88e3-4086-8cbe-6739399f3de6/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:48 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:49 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=295f3614-d790-475b-ad67-2c223c2e06ca)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:49 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=f2be6793-5ba0-4dd5-99ca-e25110353f2a)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:49 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:49 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=2afea684-bf0c-4634-aa69-89e46322a98c)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM     LOG [MediaService] Generating Video Thumbnail Success b2f49d98-3a79-41f4-a618-be630729c709
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM   ERROR [MediaService] Failed to generate thumbnail for asset: 295f3614-d790-475b-ad67-2c223c2e06ca/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM   ERROR [MediaService] Failed to generate thumbnail for asset: f2be6793-5ba0-4dd5-99ca-e25110353f2a/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM   ERROR [MediaService] Failed to generate thumbnail for asset: 2afea684-bf0c-4634-aa69-89e46322a98c/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:50 PM     LOG [MediaService] Generating Video Thumbnail Success 7e661971-218f-4f96-a371-3a3b2fd2cc72
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:51 PM     LOG [MediaService] Generating Video Thumbnail Success c3f53b9d-91cf-46a9-bee0-b213ba53508c
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:51 PM     LOG [MediaService] Generating Video Thumbnail Success 21da1eac-b484-4e1d-8f43-955250e64d8b
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=e7209441-e4e1-4c1d-81b1-53e02e186fcc)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=c8af6c09-5992-46a4-bbcb-44826a663652)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM     LOG [MediaService] Generating Video Thumbnail Success 6985a5fe-c6c1-400d-9299-39f6b2a91020
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM   ERROR [MediaService] Failed to generate thumbnail for asset: e7209441-e4e1-4c1d-81b1-53e02e186fcc/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:52 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:53 PM     LOG [MediaService] Generating Video Thumbnail Success fb8a7a52-acf2-4e45-bbed-da629d591f8a
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:53 PM   ERROR [MediaService] Failed to generate thumbnail for asset: c8af6c09-5992-46a4-bbcb-44826a663652/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:53 PM     LOG [MediaService] Generating Video Thumbnail Success 7bdbc378-4fb6-48ef-8ef9-fb940e7fe204
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:54 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:54 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:55 PM     LOG [MediaService] Generating Video Thumbnail Success 12d7270b-6ead-4ceb-b6ec-77beb9749282
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:55 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:55 PM     LOG [MediaService] Generating Video Thumbnail Success 85576b95-f05a-4de1-90c1-07cf2661e71b
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:56 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:56 PM     LOG [MediaService] Generating Video Thumbnail Success c074b1b8-84b2-4426-826f-993ddc647468
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:56 PM     LOG [MediaService] Generating Video Thumbnail Success cde14831-ef1c-4588-a017-f9732911a955
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:56 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:56 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:57 PM     LOG [MediaService] Generating Video Thumbnail Success 30f413d8-06d9-4fb2-997a-549d42b9e7e6
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:57 PM     LOG [MediaService] Generating Video Thumbnail Success e84d059c-c63c-446e-a274-ebb070c13da0
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:57 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:15:59 PM     LOG [MediaService] Generating Video Thumbnail Success 78b42c81-b279-4b67-98b4-20596558346e
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:01 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:02 PM     LOG [MediaService] Generating Video Thumbnail Success 8b24656b-d84e-4472-abfd-7cdbe418a80e
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:02 PM     LOG [MediaService] Start Generating Video Thumbnail
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:04 PM     LOG [MediaService] Generating Video Thumbnail Success 19cbf51f-0b05-4bc5-9977-d26fff4be412
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:05 PM    WARN [MediaService] Failed to generate jpeg thumbnail using sharp, trying with exiftool-vendored (asset=4921124e-f714-40be-b041-3e486b808c08)
immich_microservices     | [Nest] 1  - 04/07/2023, 1:16:05 PM   ERROR [MediaService] Failed to generate thumbnail for asset: 4921124e-f714-40be-b041-3e486b808c08/IMAGE
immich_microservices     | Error: 0 output files created
immich_microservices     |     at ExifTool.extractBinaryTag (/usr/src/app/node_modules/exiftool-vendored/dist/ExifTool.js:305:19)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/libs/domain/src/media/media.service.js:61:21)
immich_microservices     |     at async ThumbnailGeneratorProcessor.handleGenerateJpegThumbnail (/usr/src/app/dist/apps/microservices/apps/microservices/src/processors.js:232:9)
```
