### ISSUE TITLE
Background Uploads iOS not working at all

### ISSUE THREAD

**Issue by DwiDarmayasa** [immich-app/immich#2262]
### The bug

The background backup doesn’t work at all. even pull the notifications, it immediately stop uploading.

### The OS that Immich Server is running on

Ubuntu 20.04

### Version of Immich Server

V1.53

### Version of Immich Mobile App

V1.53

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - JWT_SECRET=somelongrandomstring
      - DISABLE_MACHINE_LEANRNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_transformers:/config/transformers #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
No env
```

### Reproduction steps

```bash
1.pull notifications which stopped uploading 
2.close app also stopped uploading 
3.
...
```
