### ISSUE TITLE
[BUG] Proxy container fails to start with 1.54.0

### ISSUE THREAD

**Issue by stumpylog** [immich-app/immich#2293]
### The bug

When running with the `:release` tag, currently equal to `:v1.54.0`, the proxy container fails to start.  Returning to `:v1.53.0` starts without issue.

```
immich-proxy             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
immich-proxy             | 20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
immich-proxy             | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
immich-proxy             | /docker-entrypoint.sh: Configuration complete; ready for start up
immich-proxy             | 2023/04/19 09:27:30 [emerg] 1#1: mkdir() "/tmp/proxy_temp" failed (13: Permission denied)
immich-proxy             | nginx: [emerg] mkdir() "/tmp/proxy_temp" failed (13: Permission denied)
immich-proxy exited with code 1
```

### The OS that Immich Server is running on

Ubuntu 22.04.x

### Version of Immich Server

1.54.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-proxy:
    container_name: "immich-proxy"
    hostname: "immich-proxy"
    depends_on:
        - "immich-server"
    image: "docker.io/altran1502/immich-proxy:release"
    networks:
      - "immich-net"
      - "reverse-proxy"
    restart: "unless-stopped"
    environment:
      TZ: "America/Los_Angeles"
    labels:
      - <snip>
```

### Your .env content

```Shell
Not applicable - see `environment:` keys
```

### Reproduction steps

```bash
1. Update images
2. Start stack
```

### Additional information

Bringing the stack down, removing all images and pulling fresh doesn't resolve the issue.

**Comment by alextran1502** [comment]
Can you update the section to match with the docker-compose file in the release?

**Comment by stumpylog** [comment]
Updated the container to:
```yaml
  immich-proxy:
    container_name: "immich-proxy"
    hostname: "immich-proxy"
    depends_on:
        - "immich-server"
    image: "docker.io/altran1502/immich-proxy:release"
    networks:
      - "immich-net"
      - "reverse-proxy"
    restart: "unless-stopped"
    environment:
      TZ: "America/Los_Angeles"
      IMMICH_SERVER_URL: "http://immich-web:3000"
      IMMICH_WEB_URL: "http://immich-server:3001"
    labels:
      - "traefik.enable=true"
      - <snip>
      - "traefik.http.services.immich-svc.loadbalancer.server.port=8080"
```

The two _URL values were missing.  But the container doesn't start still
