### ISSUE TITLE
[BUG] Storage Template links do not work on fileshare

### ISSUE THREAD

**Issue by evanreichard** [immich-app/immich#2390]
### The bug

Im pretty sure the following is the issue.

Log:
```
[Nest] 1  - 05/07/2023, 4:28:32 AM   ERROR [StorageTemplateService] Problem applying storage template
[Nest] 1  - 05/07/2023, 4:28:32 AM   ERROR [StorageTemplateService] Error: EIO: i/o error, link 'upload/upload/034dc848-001a-472d-a925-a4bdc56a60bb/33a8e421-4b9b-4ca4-9102-961c18d4c9ab.jpg' -> 'upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg'
[Nest] 1  - 05/07/2023, 4:28:32 AM   ERROR [StorageTemplateService] Object:
{
  "id": "18017194-c7cd-48d4-9c57-aeaf3b5d5db5",
  "source": "upload/upload/034dc848-001a-472d-a925-a4bdc56a60bb/33a8e421-4b9b-4ca4-9102-961c18d4c9ab.jpg",
  "destination": "upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg"
}
```

Manual attempt:
```
/usr/src/app # ln -s upload/upload/034dc848-001a-472d-a925-a4bdc56a60bb/33a8e421-4b9b-4ca4-9102-961c18d4c9ab.jpg upload/library/034dc84
8-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg
/usr/src/app # echo $?
0
/usr/src/app # ls -lah upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg 
lrwxrwxrwx    1 99       users         91 May  7 04:39 upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg -> upload/upload/034dc848-001a-472d-a925-a4bdc56a60bb/33a8e421-4b9b-4ca4-9102-961c18d4c9ab.jpg
/usr/src/app # cat upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg
cat: can't open 'upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg': No such file or directory
```

It appears because the link is established from outside of the network share, then the share doesn't know what to do. If I change my working directory to the root of the network share, then it successfully links.

### The OS that Immich Server is running on

Kubernetes v1.24.12+rke2r1 on Rocky Linux

### Version of Immich Server

v1.54.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Helm Chart
```

### Your .env content

```Shell
Helm Chart - No deviations outside of DB_PASSWORD
```

### Reproduction steps

```bash
See main report
```

**Comment by alextran1502** [comment]
Hello, thank you for reporting. Can you elaborate on your message below? I am not understanding the issue very well here.

> It appears because the link is established from outside of the network share, then the share doesn't know what to do. If I change my working directory to the root of the network share, then it successfully links.

**Comment by evanreichard** [comment]
Sure. In the container the working dir is `/usr/src/app`. Inside that dir is an `upload` folder which is mounted as an NFS share.

If I try to create a link when my working dir is `/usr/src/app`, then it won't work because its stored on the NFS share with a relative path that does not exist.

If I change my working dir to a dir that's on the share (e.g. the root dir - `/usr/src/app/upload`), then the link will work because the path is relative to all folders that the share understands.

____

The above behavior is why I think the following error happens: 

```
[Nest] 1  - 05/07/2023, 4:28:32 AM   ERROR [StorageTemplateService] Error: EIO: i/o error, link 'upload/upload/034dc848-001a-472d-a925-a4bdc56a60bb/33a8e421-4b9b-4ca4-9102-961c18d4c9ab.jpg' -> 'upload/library/034dc848-001a-472d-a925-a4bdc56a60bb/2022/2022-12-18/19-26-48-MeghanandEvanWedding-0247.jpg'
```

As those paths are _not_ relative to the share, so the share doesn't know how to understand them.

**Comment by bo0tzz** [comment]
This behaviour should probably fallback to a move or copy if links aren't supported @alextran1502

**Comment by truppelito** [comment]
I'dlike to add that I'm having what looks like to be the same issue:

```
[Nest] 1624  - 05/07/2023, 4:46:17 PM   ERROR [StorageTemplateService] Problem applying storage template
[Nest] 1624  - 05/07/2023, 4:46:17 PM   ERROR [StorageTemplateService] Object:
[Nest] 1624  - 05/07/2023, 4:46:17 PM   ERROR [StorageTemplateService] Error: ENOENT: no such file or directory, link '/photos/upload/de5e535e-ae74-4180-a43f-976adcde806a/827585c6-2e25-46d0-9aca-b70830d5a7a9.jpg' -> '/photos/library/de5e535e-ae74-4180-a43f-976adcde806a/2022/01/2022-01-30-12B4FA13-D7B4-4AEF-BF12-3E792C34781C+1.jpg'
{
  "id": "90ed8ed2-6c0a-4b96-9230-023940aae626",
  "source": "/photos/upload/de5e535e-ae74-4180-a43f-976adcde806a/827585c6-2e25-46d0-9aca-b70830d5a7a9.jpg",
  "destination": "/photos/library/de5e535e-ae74-4180-a43f-976adcde806a/2022/01/2022-01-30-12B4FA13-D7B4-4AEF-BF12-3E792C34781C+1.jpg"
}
```

In my case, the docker volume that maps to the /photos folder (and thus /photos/upload and /photos/library) is an SMB share mounted by docker itself (configured inside my docker compose file) that points to a NAS (another device on my LAN). While uploading from my iPhone (for example), many of the files go from /photos/upload to /photos/library as expected, but some get stuck in /photos/upload and never leave.

**Comment by megapearl** [comment]
Having the same problem, also remote mounted via NFS .

relevant config:

dockerhost local /etc/fstab:
```
storage.flissinger.com:/mnt/storage/Homes     /mnt/homes        nfs4 defaults,sec=sys 0 0
```
environment:
`UPLOAD_LOCATION=/mnt/homes/photos`

docker config:
```
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    ports:
      - 3007:3001
    env_file:
      - stack.env
    depends_on:
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/dockers/immich/model-cache:/cache
    env_file:
      - stack.env
    ports:
      - 3008:3003
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    ports:
      - 3006:3000
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /home/dockers/immich/tsdata:/data
    restart: always

```

immich-microservices logs:
```
{
  "id": "f36f4bfc-0c0f-4592-93b3-dc3f85ef5c31",
  "source": "upload/upload/3879145c-08e7-4ab6-a8e3-6ba3dbd57ffd/ca4b337d-f083-4114-8d22-3eb8526d3a87.mov",
  "destination": "upload/library/donald/2018/12/2018-12-06_01-37-19.mov"
}
[Nest] 1  - 05/25/2023, 7:18:12 PM   ERROR [StorageTemplateService] Problem applying storage template
[Nest] 1  - 05/25/2023, 7:18:12 PM   ERROR [StorageTemplateService] Error: ENOENT: no such file or directory, link 'upload/upload/3879145c-08e7-4ab6-a8e3-6ba3dbd57ffd/025b27b8-2caf-4553-b9a6-c2c34470f67f.jpeg' -> 'upload/library/donald/2018/07/2018-07-04_15-50-45.jpeg'
[Nest] 1  - 05/25/2023, 7:18:12 PM   ERROR [StorageTemplateService] Object:
{
  "id": "026b2b4d-f5ac-45b8-98f6-93ad08509465",
  "source": "upload/upload/3879145c-08e7-4ab6-a8e3-6ba3dbd57ffd/025b27b8-2caf-4553-b9a6-c2c34470f67f.jpeg",
  "destination": "upload/library/donald/2018/07/2018-07-04_15-50-45.jpeg"
}
```
