### ISSUE TITLE
[BUG] Machinelearning crashing on k8s deployment v1.57.1 - v1.65.0

### ISSUE THREAD

**Issue by gcarrarom** [immich-app/immich#2481]
### The bug

There's a bug when using version 1.56.1 on kubernetes using the official helm chart:
zsh ⌁ klf immich-machine-learning-54b5766488-kx4b4                                        
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/insightface/__init__.py", line 8, in <module>
    import onnxruntime
  File "/opt/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 55, in <module>
    raise import_capi_exception
  File "/opt/venv/lib/python3.10/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import (
  File "/opt/venv/lib/python3.10/site-packages/onnxruntime/capi/_pybind_state.py", line 33, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: /opt/venv/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.cpython-310-x86_64-linux-gnu.so: cannot enable executable stack as shared object requires: Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/src/main.py", line 6, in <module>
    from insightface.app import FaceAnalysis
  File "/opt/venv/lib/python3.10/site-packages/insightface/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime. 

### The OS that Immich Server is running on

Kubernetes - k3s - MicroOS

### Version of Immich Server

v1.56.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
postgresql:
      enabled: true
redis:
  enabled: true

typesense:
  enabled: true
  persistence:
    tsdata:
      enabled: true
      existingClaim: typesense-data

machine-learning:
  persistence:
    cache:
      enabled: true
      existingClaim: machinelearning-data
proxy:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: my.domain.com
          paths:
            - path: "/"
      tls:
        - hosts:
            - my.domain.com
          secretName: my-domain-com
image:
  tag: v1.56.1
immich:
  persistence:
    library:
      existingClaim: photos
```

### Your .env content

```Shell
postgresql:
      enabled: true
redis:
  enabled: true

typesense:
  enabled: true
  persistence:
    tsdata:
      enabled: true
      existingClaim: typesense-data

machine-learning:
  persistence:
    cache:
      enabled: true
      existingClaim: machinelearning-data
proxy:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: my.domain.com
          paths:
            - path: "/"
      tls:
        - hosts:
            - my.domain.com
          secretName: my-domain-com
image:
  tag: v1.56.1
immich:
  persistence:
    library:
      existingClaim: photos
```

### Reproduction steps

```bash
1. Deploy the helm chart on that version
2. Wait for all pods to come up and machinelearning to crash.
```
