### ISSUE TITLE
[BUG] Admin Registration Sign Up does not work, nothing happens

### ISSUE THREAD

**Issue by megapearl** [immich-app/immich#2499]
### The bug

Hi,

First off thanks for your great work, I switched from photoprism to immich since you got face recognition working.

I use portainer stacks, and set up Immich using the docker-compose file, using an already existing postgres and redis database and reverse proxy nginx (swag).

All dockers are running and are not giving any errors, when I browse to Immich for the first time I got the welcome image with 'Getting Started' button which I clicked, after that I got below image.

![image](https://github.com/immich-app/immich/assets/3420660/df1e3174-d43c-47c3-8469-0f4158b54664)

When I press the signup button nothing happens and no errors are logged in any of the dockers.

How to troubleshoot?

Best Regards,
Donald.

### The OS that Immich Server is running on

Photonos linux kernel 5.10.175-4.ph4-esx via Portainer virtualised via ESXi

### Version of Immich Server

release

### Version of Immich Mobile App

release

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
#    env_file:
#      - /home/dockers/immich/config/.env
    environment:
      - DB_HOSTNAME=postgresql.mydomainhere.com
      - DB_PORT=5432
      - DB_USERNAME=immich
      - DB_PASSWORD=*redacted*
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis.mydomainhere.com
      - REDIS_PORT=6379
      - TYPESENSE_API_KEY=*redacted*
      - IMMICH_WEB_URL=http://photo.mydomainhere.com:3006
      - IMMICH_SERVER_URL=http://photo.mydomainhere.com:3007
      - IMMICH_MACHINE_LEARNING_URL=http://photo.mydomainhere.com:3008
    volumes:
      - /home/dockers/immich/uploads:/usr/src/app/upload
#    depends_on:
#      - redis
#      - database
#      - typesense
    ports:
      - 3007:3001
    restart: always
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /home/dockers/immich/uploads:/usr/src/app/upload
#    depends_on:
#      - redis
#      - database
#      - typesense
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
#    env_file:
#      - /home/dockers/immich/config/.env
    volumes:
      - /home/dockers/immich/uploads:/usr/src/app/upload
      - /home/dockers/immich/model-cache:/cache
    restart: always
    ports:
      - 3008:3003
  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
#    env_file:
#      - /home/dockers/immich/config/.env
    restart: always
    ports:
      - 3006:3000
    environment:
      - IMMICH_WEB_URL=http://photo.mydomainhere.com:3006
      - IMMICH_SERVER_URL=http://photo.mydomainhere.com:3007
      - IMMICH_MACHINE_LEARNING_URL=http://photo.mydomainhere.com:3008
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=*redacted*
      - TYPESENSE_DATA_DIR=/data
#    logging:
#      driver: none
    volumes:
      - /home/dockers/immich/tsdata:/data
    restart: always
```

### Your .env content

```Shell
Somehow portainer won't read the .env so I configured them as environment variables in the docker-compose file.
```

### Reproduction steps

```bash
1. Install using docker-compose file and set the environment variables of .env file manually in compose file.
2. Browse to the web server of immich (via reverse proxy).
3. Press the getting started button, try to sign up an administrator for the first time.
```

### Additional information

Reverse proxy configuration:

```
root@dockers [ /home/dockers/swag/nginx/proxy-confs ]# cat immich.subdomain.conf
## Version 2023/02/05
# Ensure your DNS has a CNAME set for Immich and that Immich container is named.

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name photo.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth (requires ldap-location.conf in the location block)
    #include /config/nginx/ldap-server.conf;

    # enable for Authelia (requires authelia-location.conf in the location block)
    #include /config/nginx/authelia-server.conf;

    # enable for Authentik (requires authentik-location.conf in the location block)
    #include /config/nginx/authentik-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for ldap auth (requires ldap-server.conf in the server block)
        #include /config/nginx/ldap-location.conf;

        # enable for Authelia (requires authelia-server.conf in the server block)
        #include /config/nginx/authelia-location.conf;

        # enable for Authentik (requires authentik-server.conf in the server block)
        #include /config/nginx/authentik-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app photo.mydomainhere.com;
        set $upstream_port 3006;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
root@dockers [ /home/dockers/swag/nginx/proxy-confs ]#
```
