### ISSUE TITLE
[BUG] CSV_RECORD_INCONSISTENT_FIELDS_LENGTH

### ISSUE THREAD

**Issue by bibinisacmohan** [immich-app/immich#2509]
### The bug

There seems to be an issue with the geodecoding, which is causing the microservices to constantly restart. This started with the [1.56.2] update.

Log 
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +387ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:07:28 PM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 6 on line 63721
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1337:26)
    at Parser.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at Transform._read (node:internal/streams/transform:201:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 10855647,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 63721,
  records: 63720,
  columns: false,
  error: undefined,
  header: false,
  index: 6,
  raw: undefined,

  column: 6,
  quoting: false,
  record: [
    '2979202',
    'Saint-Jean-Rohrbach',
    'Saint-Jean-Rohrbach',
    'Saint Jean-Rorbach,Saint-Jean-Rohrbach',
    '49.02624',
    '6.'
  ]
}
Node.js v18.16.0
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +67ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +15ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +256ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:36 PM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 6 on line 63721
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1337:26)
    at Parser.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at Transform._read (node:internal/streams/transform:201:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 10855647,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 63721,
  records: 63720,
  columns: false,
  error: undefined,
  header: false,
  index: 6,
  raw: undefined,

  column: 6,
  quoting: false,
  record: [
    '2979202',
    'Saint-Jean-Rohrbach',
    'Saint-Jean-Rohrbach',
    'Saint Jean-Rorbach,Saint-Jean-Rohrbach',
    '49.02624',
    '6.'
  ]
}
Node.js v18.16.0

### The OS that Immich Server is running on

Synology Docker

### Version of Immich Server

1.56.2

### Version of Immich Mobile App

1.56.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "4.0"
services:
  immich-redis:
    image: redis
    container_name: Immich-redis
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: 1026:100
    environment:
      - TZ=America/New_York
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: always

  immich-db:
    image: postgres
    container_name: Immich-db
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immichuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: 1026:100
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=America/New_York
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=immichpw
    restart: always

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    container_name: Immich-server
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
    restart: always
    depends_on:
      - immich-redis
      - immich-db
      - typesense

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    container_name: Immich-microservices
    hostname: immich-microservices
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
    restart: always
    depends_on:
      - immich-redis
      - immich-db
      - typesense

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    command: [ "python", "src/main.py" ]
    container_name: Immich-learning
    hostname: immich-machine-learning
    user: 1026:100
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/data:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: always

  immich-web:
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    container_name: Immich-web
    hostname: immich-web
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
    env_file:
      - stack.env
    restart: always

 
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=anyrandomtext
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  immich-proxy:
    image: ghcr.io/immich-app/immich-proxy:release
    logging:
      driver: none
    container_name: Immich-proxy
    hostname: immich-proxy
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
    environment:
      - IMMICH_SERVER_URL=http://immich-server:3001
      - IMMICH_WEB_URL=http://immich-web:3000
    ports:
      - 8212:8080
    restart: always
    depends_on:
      - immich-server
      
volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
NODE_ENV=production
TZ=America/New_York
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=immichpw
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
LOG_LEVEL=simple
JWT_SECRET=xia7jNMRT50PgcShC0BTuFxTLPamoYnQO8OKH8jUff4iD0AdtbC8HTZp/Rv4LSdpV7kXbYTvxNrw24NzJJiag2nisYbUmEV8XbJEEboag98z+6KR5djhPPC4/oztoSJHOB2rpPXjv4VNwCAT0PvTKUo3gSY8rDja85DGugYqJ0c=
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TYPESENSE_API_KEY=anyrandomtext
```

### Reproduction steps

```bash
The microservices container keep restarting. 

[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +387ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:07:28 PM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 05/21/2023, 7:07:28 PM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 6 on line 63721
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1337:26)
    at Parser.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at Transform._read (node:internal/streams/transform:201:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 10855647,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 63721,
  records: 63720,
  columns: false,
  error: undefined,
  header: false,
  index: 6,
  raw: undefined,

  column: 6,
  quoting: false,
  record: [
    '2979202',
    'Saint-Jean-Rohrbach',
    'Saint-Jean-Rohrbach',
    'Saint Jean-Rorbach,Saint-Jean-Rohrbach',
    '49.02624',
    '6.'
  ]
}
Node.js v18.16.0
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [NestFactory] Starting Nest application...
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +67ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +15ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:35 PM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +256ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1  - 05/21/2023, 7:08:36 PM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 05/21/2023, 7:08:36 PM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
/usr/src/app/node_modules/local-reverse-geocoder/index.js:746
            throw err;
            ^
CsvError: Invalid Record Length: expect 19, got 6 on line 63721
    at Object.__onRecord (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:940:11)
    at Object.parse (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:903:36)
    at Parser._flush (/usr/src/app/node_modules/csv-parse/dist/cjs/index.cjs:1337:26)
    at Parser.final [as _final] (node:internal/streams/transform:132:10)
    at callFinal (node:internal/streams/writable:698:12)
    at prefinish (node:internal/streams/writable:710:7)
    at finishMaybe (node:internal/streams/writable:720:5)
    at afterWrite (node:internal/streams/writable:507:3)
    at onwrite (node:internal/streams/writable:480:7)
    at Transform._read (node:internal/streams/transform:201:5) {
  code: 'CSV_RECORD_INCONSISTENT_FIELDS_LENGTH',
  bytes: 10855647,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 63721,
  records: 63720,
  columns: false,
  error: undefined,
  header: false,
  index: 6,
  raw: undefined,

  column: 6,
  quoting: false,
  record: [
    '2979202',
    'Saint-Jean-Rohrbach',
    'Saint-Jean-Rohrbach',
    'Saint Jean-Rorbach,Saint-Jean-Rohrbach',
    '49.02624',
    '6.'
  ]
}
Node.js v18.16.0
```
