### ISSUE TITLE
[BUG] "STORAGE TEMPLATE MIGRATION" job makes duplicates in library

### ISSUE THREAD

**Issue by thierrybla** [immich-app/immich#2521]
### The bug

After using the "STORAGE TEMPLATE MIGRATION" job it makes quite a lot of duplicates.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.56.2

### Version of Immich Mobile App

v1.56.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Upload photos with random names
2. Click "STORAGE TEMPLATE MIGRATION" job
3. Look in your library and see duplicates
```
