### ISSUE TITLE
[BUG] column "checksum" of relation "assets" contains null values

### ISSUE THREAD

**Issue by paulmorabito** [immich-app/immich#2594]
### The bug

Manually upgraded to 1.58 after making the required changes to the docker compose. immich-service is not starting and constantly giving the following error:

```
2023-05-28 18:52:10.796 CEST [351] STATEMENT:  ALTER TABLE "assets" ALTER COLUMN "checksum" SET NOT NULL
2023-05-28 18:52:13.836 CEST [352] ERROR:  column "checksum" of relation "assets" contains null values
```

### The OS that Immich Server is running on

Debian 11 (via docker)

### Version of Immich Server

1.58

### Version of Immich Mobile App

1.58

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    image: altran1502/immich-server:release
    container_name: immich-server
    command: ["start-server.sh"]
    volumes:
      - /media/downloads/immich/:/usr/src/app/upload
    env_file:
      - immich.env
    environment:
      - NODE_ENV=production
      - TYPESENSE_API_KEY=<key>
    depends_on:
      - redis
      - postgres
      - typesense
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. docker compose -f <compose.file> pull <immich serer container>
2. docker compose -f <compose.file> up -d <immich serer container>

(in reality I did this with all containers part of immich)
```
