### ISSUE TITLE
[BUG] Request failed with status code 503

### ISSUE THREAD

**Issue by zenithyr** [immich-app/immich#2607]
### The bug

The application worked perfectly fine in docker until yesterday when I upgraded to the latest with the added typesense feature. After `docker pull & docker compose up -d`, the web portal now complains "Request failed with status code 503".

Tried to use the latest yaml and .env files with no luck. Commenting out typesense from docker-compose.yml and .env completely resulted the same error.

**UPLOAD_LOCATION does point to a folder filled with data from previously. Not sure if it's related.**

Please find container logs in the sections below.

### The OS that Immich Server is running on

OpenMediaVault 6.1.0-0.deb11.7-amd64

### Version of Immich Server

ghcr.io/immich-app/immich-server:release

### Version of Immich Mobile App

not used here

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=<omitted for sensitivity>


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=some_random_text
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1.`docker compose down`

[+] Running 9/9
 ✔ Container immich_machine_learning  Removed                                                                                                                                                                                             1.6s
 ✔ Container immich_web               Removed                                                                                                                                                                                            10.7s
 ✔ Container immich_proxy             Removed                                                                                                                                                                                             0.6s
 ✔ Container immich_microservices     Removed                                                                                                                                                                                            10.8s
 ✔ Container immich_server            Removed                                                                                                                                                                                            10.7s
 ✔ Container immich_typesense         Removed                                                                                                                                                                                             2.3s
 ✔ Container immich_redis             Removed                                                                                                                                                                                             0.7s
 ✔ Container immich_postgres          Removed                                                                                                                                                                                             0.8s
 ✔ Network immich_default             Removed


2.`docker volume prune`

```bash
WARNING! This will remove anonymous local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
69eb48024894f73603c532e308b4bd96e345bb2ef880457b01ff1609407161e6
acd4231a655103ff269cc402d85340530637af2acfb74058a4c9c097d4204416
f657a14cc239edd8d9731d92146701d5cb163ebe6e5f1230657a49535ff20eae
2d373eb5dceee436ad5db6638897a48ef42473a83593d95e4efd0547ca5e5a6b
c6f89118528443ba258fb991cf0fd0a766c4bf01e6f12b1eb6ce94700059357d
```

3.`docker compose up -d`

```bash
[+] Building 0.0s (0/0)
[+] Running 9/9
 ✔ Network immich_default             Created                                                                                                                                                                                             0.1s
 ✔ Container immich_postgres          Started                                                                                                                                                                                             1.8s
 ✔ Container immich_web               Started                                                                                                                                                                                             1.7s
 ✔ Container immich_machine_learning  Started                                                                                                                                                                                             2.1s
 ✔ Container immich_typesense         Started                                                                                                                                                                                             1.7s
 ✔ Container immich_redis             Started                                                                                                                                                                                             2.2s
 ✔ Container immich_microservices     Started                                                                                                                                                                                             3.1s
 ✔ Container immich_server            Started                                                                                                                                                                                             3.2s
 ✔ Container immich_proxy             Started
```

4. `curl http://127.0.0.1:2283 # or from remotely by http://<ip>:2283`

```bash
<omitted for brevity>
        <body>
                <div class="error">
                        <span class="status">500</span>
                        <div class="message">
                                <h1>Request failed with status code 503</h1>
                        </div>
                </div>
        </body>
```
```


### Additional information

proxy
<details></summary>immich_proxy log</summary>

```bash
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-set-env-variables.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/05/30 01:56:17 [notice] 1#1: using the "epoll" event method
2023/05/30 01:56:17 [notice] 1#1: nginx/1.23.4
2023/05/30 01:56:17 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
2023/05/30 01:56:17 [notice] 1#1: OS: Linux 6.1.0-0.deb11.7-amd64
2023/05/30 01:56:17 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/05/30 01:56:17 [notice] 1#1: start worker processes
2023/05/30 01:56:17 [notice] 1#1: start worker process 40
2023/05/30 01:56:17 [notice] 1#1: start worker process 41
2023/05/30 01:56:17 [notice] 1#1: start worker process 42
2023/05/30 01:56:17 [notice] 1#1: start worker process 43
```
</details>

server
<details></summary>immich_server log</summary>

```bash
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/count-by-user-id, GET} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id/users, PUT} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id/assets, PUT} route +1ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id, GET} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id/assets, DELETE} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id/user/:userId, DELETE} route +1ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/:id/download, GET} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [RouterExplorer] Mapped {/album/create-shared-link, POST} route +0ms
[Nest] 1  - 05/30/2023, 2:01:11 AM     LOG [SearchService] Running bootstrap
Request #1685412071893: Request to Node 0 failed due to "undefined Request failed with HTTP code 503"
Request #1685412071893: Sleeping for 4s and then retrying request...
Request #1685412071893: Request to Node 0 failed due to "undefined Request failed with HTTP code 503"
```
</details>

microservers
<details></summary>immich_microservers log</summary>

```bash
[Nest] 1  - 05/30/2023, 1:56:20 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +1ms
[Nest] 1  - 05/30/2023, 1:56:20 AM    WARN [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 1  - 05/30/2023, 1:56:20 AM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
[Nest] 1  - 05/30/2023, 1:56:36 AM     LOG [MetadataExtractionProcessor] Reverse Geocoding Initialized
[Nest] 1  - 05/30/2023, 1:56:36 AM     LOG [NestApplication] Nest application successfully started +53ms
[Nest] 1  - 05/30/2023, 1:56:36 AM     LOG [ImmichMicroservice] Running Immich Microservices in PRODUCTION environment - version 1.58.0 - Listening on port: 3002
```
</details>

web
<details></summary>immich_web log</summary>

```bash
Listening on 0.0.0.0:3000
```
</details>

typesense
<details></summary>immich_typesense log</summary>

```bash
Error response from daemon: configured logging driver does not support reading
```
</details>
