### ISSUE TITLE
[BUG] Server on v1.58.0 not starting.

### ISSUE THREAD

**Issue by kiguigui** [immich-app/immich#2609]
### The bug

After changing Version von 1.57.1 to 1.58.0, Server isnt starting anymore. New commands are applied. Its chrashing with the following error:

> Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "start-server.sh": executable file not found in $PATH: unknown

When adding .\ to new command as `.\start-server.sh` it says access denied:

>Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./start-server.sh": permission denied: unknown

### The OS that Immich Server is running on

K3S

### Version of Immich Server

v.1.58.0

### Version of Immich Mobile App

1.58.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
--- #Server

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: immich
  name: server
  labels:
    serviceName: immich
    serviceType: server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      serviceName: immich
      serviceType: server
  template:
    metadata:
      labels:
        serviceName: immich
        serviceType: server
    spec:
      containers:
      - name: server
        image: ghcr.io/immich-app/immich-server:v1.58.0

        command: ["start-server.sh"]

        resources:
          limits:
            memory: "200Mi"

        ports:
          - name: server-http
            containerPort: 3001
            protocol: TCP

        livenessProbe:
          httpGet:
            path: /server-info/ping
            port: server-http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /server-info/ping
            port: server-http
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3

        volumeMounts:
        - name: library-volume
          mountPath: /usr/src/app/upload
          
        env:
        #Common
        - name: TZ
          value: Europe/Berlin

        #Database
        - name: DB_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: database__host
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: database__user
        - name: DB_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: database__name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: database__password

      #Service URLs
        - name: REDIS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: redis__host
        - name: IMMICH_WEB_URL
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: immich__web_url
        - name: IMMICH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: immich__server_url
        - name: IMMICH_MACHINE_LEARNING_URL
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: immich__machine_learning_url
        - name: TYPESENSE_HOST
          valueFrom:
            configMapKeyRef:
              name: immich-configmap
              key: typesense__host
        #Typesense
        - name: TYPESENSE_ENABLED
          valueFrom: 
            configMapKeyRef:
              name: immich-configmap
              key: typesense__enabled
        - name: TYPESENSE_server_KEY
          valueFrom:
            secretKeyRef:
              name: immich-secret
              key: typesense__server_key

      volumes:
      - name: library-volume
        persistentVolumeClaim:
          claimName: immich-library-volume
```

### Your .env content

```Shell
--- #Configmap

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: immich
  name: immich-configmap
  labels:
    serviceName: immich
data:
# Database
  database__host: service-database-psql
  database__user: immich-database-user
  database__name: immich-database
# Service URLs
  redis__host: service-redis
  immich__web_url: http://service-web-http
  immich__server_url: http://service-server-http
  immich__machine_learning_url: http://service-machinelearning-http
  typesense__host: service-typesense-http
# Typesense
  typesense__enabled: "true"
# Stuff
  upload_location: absolute_location_on_your_machine_where_you_want_to_store_the_backup
  log_level: simple
  public_login_page_message: "My Family & Friends Photos and Videos Backup Server"

--- #Secret

apiVersion: v1
kind: Secret
metadata:
  namespace: immich
  name: immich-secret
  labels:
    serviceName: immich
data:
  # Database
  database__password: redacted
  # Typesense
  typesense__api_key: redacted
```

### Reproduction steps

```bash
1. Use K3s
2. Upgrade to Version 1.58.0
3. See it crashing
...
```
