### ISSUE TITLE
chmod required for start-server.sh and start-microservices.sh

### ISSUE THREAD

**Issue by dharapvj** [immich-app/immich#2645]
### The bug

latest release 1.59.1 does not allow me to start using podman
this is due to fact that entrypoint start-server.sh and start-microservices.sh does not have execute permissions.

I get below error
Error: crun: open executable: Permission denied: OCI permission denied 

If I ls the files in the container.. I see that those files do not have execute permissions
```shell
❯ podman run --rm -it --entrypoint /bin/sh ghcr.io/immich-app/immich-server:release
/usr/src/app # ls -ltr
total 844
-rw-r--r--    1 root     root           504 May 30 23:27 start-server.sh
-rw-r--r--    1 root     root           518 May 30 23:27 start-microservices.sh
```

### The OS that Immich Server is running on

podman on ubuntu

### Version of Immich Server

v1.59.1

### Version of Immich Mobile App

v.1.59.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["./start-server.sh"]
   immich-microservices:
     #container_name: immich_microservices
     image: ghcr.io/immich-app/immich-server:release
     entrypoint: ["./start-microservices.sh"]
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
podman-compose down
podman-compose pull
# make changes to remove /bin/bash in docker-compose.yaml
podman-componse up -d
```
