### ISSUE TITLE
[BUG] App does not check location permission during onboarding

### ISSUE THREAD

**Issue by jagjordi** [immich-app/immich#2726]
### The bug

After reinstalling the app, all the pictures on the phone that were already uploaded to the server were uploaded again.

The duplicated images look the same and have the same name, but it seems some meta-data is different. See:

![image](https://github.com/immich-app/immich/assets/14058667/a9c4c211-fb3a-4a32-9dec-f2d54fd3601b)
![image](https://github.com/immich-app/immich/assets/14058667/c9b94895-1fb2-4e51-bf9b-deb4803ed762)

```
immich=# SELECT * FROM assets  WHERE  "originalFileName" LIKE 'PXL_20230604_141741464';
                  id                  | deviceAssetId |               ownerId                |                             deviceId                             | type  |                                           originalPath                                           |                                          resizePath                                          |     fileCreatedAt      |     fileModifiedAt     | isFavorite |  mimeType  |    duration    |                                           webpPath                                           | encodedVideoPath |                  checksum                  | isVisible | livePhotoVideoId |           updatedAt           |           createdAt           | isArchived |    originalFileName    | sidecarPath 
--------------------------------------+---------------+--------------------------------------+------------------------------------------------------------------+-------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------+------------------------+------------------------+------------+------------+----------------+----------------------------------------------------------------------------------------------+------------------+--------------------------------------------+-----------+------------------+-------------------------------+-------------------------------+------------+------------------------+-------------
 81da1fb3-cbd1-4ef1-9e47-40d011dc53ff | 64340         | 9d015ed5-e62c-4dac-b6f6-3f5f25c73e00 | a678d3da8435915d87c5f9db936854f2e43a6a7a6e30f6c321c73a711226e287 | IMAGE | upload/library/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/2023/2023-06-04/PXL_20230604_141741464.jpg   | upload/thumbs/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/81da1fb3-cbd1-4ef1-9e47-40d011dc53ff.jpeg | 2023-06-04 12:17:41+00 | 2023-06-04 14:17:42+00 | f          | image/jpeg | 0:00:00.000000 | upload/thumbs/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/81da1fb3-cbd1-4ef1-9e47-40d011dc53ff.webp |                  | \x49d83bd2883617f80f8607eda1c699d28507c0f7 | t         |                  | 2023-06-04 12:17:59.802189+00 | 2023-06-04 12:17:57.523121+00 | f          | PXL_20230604_141741464 | 
 05514d6f-bef3-4724-916f-35532365f832 | 64340         | 9d015ed5-e62c-4dac-b6f6-3f5f25c73e00 | 0809c488ba04b10126ddb8bb11be2186b2203967e631f40497aa753f0903389a | IMAGE | upload/library/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/2023/2023-06-04/PXL_20230604_141741464+1.jpg | upload/thumbs/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/05514d6f-bef3-4724-916f-35532365f832.jpeg | 2023-06-04 12:17:41+00 | 2023-06-04 14:17:42+00 | f          | image/jpeg | 0:00:00.000000 | upload/thumbs/9d015ed5-e62c-4dac-b6f6-3f5f25c73e00/05514d6f-bef3-4724-916f-35532365f832.webp |                  | \x010d832609504d7e6e54e2a7f85c9ff954ae7d38 | t         |                  | 2023-06-09 14:55:01.480086+00 | 2023-06-09 14:54:58.123604+00 | f          | PXL_20230604_141741464 |
```

### The OS that Immich Server is running on

Unraid (debian based)

### Version of Immich Server

v1.60.0

### Version of Immich Mobile App

v1.60.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```
```


### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/Media/immich

###################################################################################
# Typesense
###################################################################################

TYPESENSE_API_KEY=***
# TYPESENSE_ENABLED=false

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose

###################################################################################
# JWT SECRET
#
# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
###################################################################################

JWT_SECRET=***

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Welcome to my self-hosted <a href=\"https://documentation.immich.app/\">Immich</a> instance, a FOSS replacement of Google Photos."

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich_web:3000
IMMICH_SERVER_URL=http://immich_server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003


####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

IMMICH_API_URL_EXTERNAL=https://***
```
```


### Reproduction steps

```bash
1. Have an android phone with immich and some pictures uploaded
2. Remove the app
3. Reinstall the app
4. Enable sync
5. Duplicates occur
```
