### ISSUE TITLE
[BUG] Microservices crash on migration if folders mounted seperately

### ISSUE THREAD

**Issue by klejejs** [immich-app/immich#2847]
### The bug

If Immich data folders (profile, thumbs, upload, etc.) are mounted separately and any of them are empty, Immich will try to delete them which will fail.

Error:
```
[Error: EBUSY: resource busy or locked, rmdir 'upload/upload'] {
  errno: -16,
  code: 'EBUSY',
  syscall: 'rmdir',
  path: 'upload/upload'
}
```

My workaround was to add an empty file like `.no_delete_folder` which fixes the issue as the folder is not empty anymore.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.61.0

### Version of Immich Mobile App

v1.61.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${LOCATION_ENCODED_VIDEO}:/usr/src/app/upload/encoded-video
      - ${LOCATION_THUMBS}:/usr/src/app/upload/thumbs
      - ${LOCATION_UPLOAD}:/usr/src/app/upload/upload
      - ${LOCATION_PROFILE}:/usr/src/app/upload/profile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      docker_local_server:
        ipv4_address: 192.168.1.x
```

### Your .env content

```Shell
LOCATION_LIBRARY=/mnt/nas_disk/...redacted...
LOCATION_ENCODED_VIDEO=./data/immich_data/encoded-video
LOCATION_THUMBS=./data/immich_data/thumbs
LOCATION_UPLOAD=./data/immich_data/upload
LOCATION_PROFILE=./data/immich_data/profile
```

### Reproduction steps

```bash
1. Mount Immich data folders separately
2. Run migration job when any of the folders are empty
3. See error in Docker logs
```
