### ISSUE TITLE
[BUG] Explore page does not show object, searching by tags works.

### ISSUE THREAD

**Issue by mjasny** [immich-app/immich#2984]
Hi,

I use the machine-learning and typesense container on another host (x86) the other containers run on a raspberry pi 4 (arm).

My initial immich setup was without ML+typesense, after adding the ML container on another host and waiting for the classification faces are shown in the explore page (web+app). However objects do are not shown in the overview page. When I explicitly search for something e.g. "dog" or "airplane" the search results are correct. This indicates the pictures have been tagged.

I already tried to regenerate all missing thumbnails and re-trigger the 3 ML jobs. Nothing changed. The behavior is the same in the web-app and iphone/android-app.

I can provide detailed debug logs if necessary, just tell me what you need. Thanks in advance.

![2023-06-27-084714_1269x1316_scrot](https://github.com/immich-app/immich/assets/38206637/bb92fb57-8b2d-4b08-bca5-befefe33ce4a)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

v1.64.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-server.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
        #- typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: [ "/bin/sh", "./start-microservices.sh" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
        #- typesense
    restart: always

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: [ "/bin/sh", "./entrypoint.sh" ]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    networks:
      - default
      - hosting_default
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always


networks:
  default:
    internal: false
  hosting_default:
    external: true


# x86 host:
version: "3.8"

services:
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=somekey
      - TYPESENSE_DATA_DIR=/data
    ports:
      - 8108:8108
    logging:
      driver: none
    volumes:
      - ./tsdata:/data
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    ports:
      - 3003:3003
    volumes:
      - ./model-cache:/cache
    environment:
      - NODE_ENV=production
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


UPLOAD_LOCATION=/immich/uploads

PUBLIC_LOGIN_PAGE_MESSAGE=

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://x86-host:3003

TYPESENSE_API_KEY=somekey
TYPESENSE_ENABLED=true
TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAiMTkyLjE2OC4yMDEuMTAiLCAicG9ydCI6ICI4MTA4IiwgInByb3RvY29sIjogImh0dHAiIH0KXQ==
```

### Reproduction steps

```bash
I did not try to reproduce this bug yet.

1. Setup Immich without ML + typesense
2. Add ML+typesense on separate host
```
