### ISSUE TITLE
[BUG] Map shows some pictures on Null Island

### ISSUE THREAD

**Issue by cfpwastaken** [immich-app/immich#2991]
### The bug

Some photos in my library have location data for [Null Island](https://en.wikipedia.org/wiki/Null_Island). It is the exact center point of the map.
![image](https://github.com/immich-app/immich/assets/44261356/9e084b55-8666-4d14-8a84-58b2cd88648e)
Pictures can have location data of 0 longitude, 0 latitude when the data gets stripped out or something went wrong trying to get the location when taking the picture.

### The OS that Immich Server is running on

Alpine Linux, but it is dockerized, another image creator

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

v1.64.0 build.87

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      #- DISABLE_MACHINE_LEARNING=false
      #- DISABLE_TYPESENSE=false
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - ./config:/config
      - ./photos:/photos
      - ./ml:/config/machine-learning #optional
    ports:
      - 1034:8080
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
   postgres:
```

### Your .env content

```Shell
I put the environment vars in the docker compose file
```

### Reproduction steps

```bash
1. Obtain a photo with Null Island location info
2. View the "Map" tab in Immich
3. See the issue in the middle of the map
```

### Additional information

Immich should detect that 0,0 location data and just not show those photos on the Map.
