### ISSUE TITLE
[BUG] loading timeline on mobile app needs optimization

### ISSUE THREAD

**Issue by thierrybla** [immich-app/immich#3029]
### The bug

When I open the app it takes between 10-30 seconds to see my photos.
"Building the timeline" takes very long, I am not sure if it's only with my device but heard more people saying the same with Google pixel phones.

When I open it in a webpage it is instant.

I use a Google Pixel 7 Pro with Android 13

### The OS that Immich Server is running on

Truenas Scale, K3S, ghcr.io/imagegenius/immich:latest

### Version of Immich Server

v1.64.0

### Version of Immich Mobile App

v1.64.0 build.87

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - path_to_postgres:/var/lib/postgresql/data
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Download app
2. Add server
3. Login
4. Setup albums
5. Close app
6. Open app
7. Building timeline (10-30 seconds)...
8. See photos
```
