### ISSUE TITLE
[BUG] Mobile App not Showing Sharing settings for one user

### ISSUE THREAD

**Issue by d-kholin** [immich-app/immich#3037]
### The bug

I've got the app installed and working on multiple devices with multiple users. The main admin user has issues when launching the sharing tab in the mobile app, where it's just a grey box, and I can't see my partner or shared albums. This follows the user, and if I use the app (iOS on all devices) on my phone, ipad, or computer, I get the same grey box. The second user can see and use the sharing page without issues. If the main user is logged in online, they can use the sharing page without issues. 
<img width="414" alt="image" src="https://github.com/immich-app/immich/assets/27835758/856712a8-17d5-4ce4-82ab-0e0451b14280">

### The OS that Immich Server is running on

Ubuntu 20.04.06

### Version of Immich Server

1.64.0

### Version of Immich Mobile App

1.64.0 build.104

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/home/michael/immich-uploads


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=[redacted]
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

IMMICH_VERSION=v1.64.0
```

### Reproduction steps

```bash
1. Open mobile app logged is as the main admin user, navigate to sharing tab
2. 
3.
...
```

### Additional information

The following error is logged in the app when I try to click on the share with partner button. 

```#0      _StringBase.[] (dart:core-patch/string_patch.dart:258)
#1      userAvatar (package:immich_mobile/shared/ui/user_avatar.dart:19)
#2      PartnerPage.build.buildUserList.<anonymous closure> (package:immich_mobile/modules/partner/views/partner_page.dart:102)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/scroll_delegate.dart:489)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:828)
#5      SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:758)
#6      Iterable.forEach (dart:core/iterable.dart:346)
#7      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:805)
#8      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:734)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#12     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093)
#17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#30     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#36     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#42     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#47     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#50     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#51     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#55     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#57     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093)
#58     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#62     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#65     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#66     StatelessElement.update (package:flutter/src/widgets/framework.dart:5162)
#67     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#69     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#70     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#74     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#76     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:6093)
#77     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6595)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#81     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#89     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#91     StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#95     ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#106    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#107    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6442)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#116    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#117    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#118    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#121    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#122    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#123    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#125    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#126    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#130    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#131    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#133    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#135    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#138    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#139    ProxyElement.update (package:flutter/src/widgets/framework.dart:5417)
#140    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#142    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#144    StatefulElement.update (package:flutter/src/widgets/framework.dart:5274)
#145    Element.updateChild (package:flutter/src/widgets/framework.dart:3686)
#146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5111)
#147    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
#148    Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
#149    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
#150    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
#151    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
#152    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
#153    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
#154    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
#155    _invoke (dart:ui/hooks.dart:142)
#156    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
#157    _drawFrame (dart:ui/hooks.dart:112)
```
