### ISSUE TITLE
[BUG] Release 1.66.0 archive bug

### ISSUE THREAD

**Issue by bcsteeve** [immich-app/immich#3115]
### The bug

I'm really very sure this just started with this release, as I've been using the archive feature extensively the last few days and only noticed it immediately after upgrading to 1.66.0 just now.  I'm guessing it has to do with the shift+click feature that was introduced (although it happens whether or not you use that feature).

What happens:  Visual chaos after archiving (try it and see).  The result is that they do go to archive, but they remain on the photos screen until refresh, although moved to some random-ish location.  Sometimes it is subtle and you can only see a small slice of the archived photos beneath others in another row while other times it is more prominent.  I'll try to post before and after screenshots.

Steps to reproduce:  Select multiple images and then archive them.  

Before:
![image](https://github.com/immich-app/immich/assets/7412219/a32a66ae-de29-4a9f-906c-13f6c7c02030)

I've clicked 5 images to archive:
![image](https://github.com/immich-app/immich/assets/7412219/5145f59b-8cf2-4028-9375-f9f59527b406)

After clicking archive:
![image](https://github.com/immich-app/immich/assets/7412219/73215ee3-f10a-4fa6-80d9-d87424972105)

In this particular instance, it is pretty subtle but notice the checkmarks are still there.  The images are (I think) hidden behind the others.  

Here is post-refresh (F5):
![image](https://github.com/immich-app/immich/assets/7412219/8ddf6999-2b29-4614-a25a-d11fc366c6b6)

Trying again... selected the last 8 images:
![image](https://github.com/immich-app/immich/assets/7412219/01b8d3ea-ee39-4bc9-b771-dfe8ec550f3b)

After archiving it is a mess:
![image](https://github.com/immich-app/immich/assets/7412219/a31aa41f-00bb-4616-bd67-29442de8bf6f)

I hope this helps!

ps. I tried it in Chrome and Edge on my Windows PC.  Edge hadn't accessed the page before so it won't be a caching/cookie issue.

### The OS that Immich Server is running on

Ubuntu 22.04.2 LTS

### Version of Immich Server

v1.66.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=xx
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/bigdisk/memories
TYPESENSE_API_KEY=xx
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Select multiple images
2. Click archive
```
