### ISSUE TITLE
[BUG] Android: albums to be backed up doesn't persist on some devices

### ISSUE THREAD

**Issue by cfpwastaken** [immich-app/immich#3240]
### The bug

On some devices, the albums to get backed up don't get persisted on app restarts.
However, the timeline does not empty (unsure if it would show new assets, did not test), but the backups dont resume, requiring you to set it again every restart for backups to work.

### The OS that Immich Server is running on

Alpine Linux, but it is dockerized, another image creator

### Version of Immich Server

v1.66.1

### Version of Immich Mobile App

v1.66.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DB_HOSTNAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
      #- DISABLE_MACHINE_LEARNING=false
      #- DISABLE_TYPESENSE=false
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - CUDA_ACCELERATION=false #optional
    volumes:
      - ./config:/config
      - ./photos:/photos
      - ./ml:/config/machine-learning #optional
    ports:
      - 1034:8080
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
   postgres:
```

### Your .env content

```Shell
I put the environment vars in the docker compose file
```

### Reproduction steps

```bash
1. Set up albums to get backed up
2. Fully restart the app (close it from activities menu)
3. See that the list is empty again
```
