### ISSUE TITLE
[BUG] immich-server and immich-microservice are restarting

### ISSUE THREAD

**Issue by Melotron** [immich-app/immich#3255]
### The bug

This morning both immich-server and immich-micro-service was down and in a restarting loop.
When ive tryied to restart  them but the same, the last thing ive tried are docker-compose up after removed both dockers.
And it allways stops with this error.

`immich_server exited with code 1
immich_microservices       | node:internal/modules/cjs/loader:1078
immich_microservices       |   throw err;
immich_microservices       |   ^
immich_microservices       | 
immich_microservices       | Error: Cannot find module '/usr/src/app/dist/main'
immich_microservices       |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
immich_microservices       |     at Module._load (node:internal/modules/cjs/loader:920:27)
immich_microservices       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
immich_microservices       |     at node:internal/main/run_main_module:23:47 {
immich_microservices       |   code: 'MODULE_NOT_FOUND',
immich_microservices       |   requireStack: []
immich_microservices       | }
immich_microservices       | 
immich_microservices       | Node.js v18.16.0
immich_microservices exited with code 1
immich_proxy               | 2023/07/14 05:18:21 [emerg] 1#1: host not found in upstream "immich-server:3001" in /etc/nginx/conf.d/default.conf:15
immich_proxy               | nginx: [emerg] host not found in upstream "immich-server:3001" in /etc/nginx/conf.d/default.conf:15
immich_proxy exited with code 1
immich_server              | node:internal/modules/cjs/loader:1078
immich_server              |   throw err;
immich_server              |   ^
immich_server              | 
immich_server              | Error: Cannot find module '/usr/src/app/dist/main'
immich_server              |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
immich_server              |     at Module._load (node:internal/modules/cjs/loader:920:27)
immich_server              |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
immich_server              |     at node:internal/main/run_main_module:23:47 {
immich_server              |   code: 'MODULE_NOT_FOUND',
immich_server              |   requireStack: []
immich_server              | }
immich_server              | 
immich_server              | Node.js v18.16.0
immich_server exited with code 1
immich_microservices       | node:internal/modules/cjs/loader:1078
immich_microservices       |   throw err;
immich_microservices       |   ^
immich_microservices       | 
immich_microservices       | Error: Cannot find module '/usr/src/app/dist/main'
immich_microservices       |     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
immich_microservices       |     at Module._load (node:internal/modules/cjs/loader:920:27)
immich_microservices       |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
immich_microservices       |     at node:internal/main/run_main_module:23:47 {
immich_microservices       |   code: 'MODULE_NOT_FOUND',
immich_microservices       |   requireStack: []
immich_microservices       | }
immich_microservices       | 
immich_microservices       | Node.js v18.16.0
immich_microservices exited with code 1
immich_proxy               | 2023/07/14 05:18:47 [emerg] 1#1: host not found in upstream "immich-server:3001" in /etc/nginx/conf.d/default.conf:15
immich_proxy               | nginx: [emerg] host not found in upstream "immich-server:3001" in /etc/nginx/conf.d/default.conf:15
immich_proxy exited with code 1
^CGracefully stopping... (press Ctrl+C again to force)
Stopping immich_proxy            ... done
Stopping immich_server           ... done
Stopping immich_microservices    ... done
Stopping immich_web              ... done
Stopping immich_machine_learning ... done
Stopping immich_redis            ... done
Stopping immich_postgres         ... done
Stopping immich_typesense        ... done`

### The OS that Immich Server is running on

Ubuntu 22-04

### Version of Immich Server

Created 	2023-07-14 03:10:11

### Version of Immich Mobile App

V1.66.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=XXXXXXXXXXX
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/raid1/immich-app


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=MSGmermerMSG
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1.Restart containers
2.Remove immich-server immich-microservice and docker-compose up
3.
...
```
