### ISSUE TITLE
[BUG] New Face Merge functionality unreliable in large windows on Chromium-based browsers

### ISSUE THREAD

**Issue by henley-regatta** [immich-app/immich#3266]
### The bug

I am unable to complete a workflow for the new Face Merge functionality on Chromium-based browsers if my window size is wider than about 1024ish pixels since the UI elements appear inconsistently, face positions move and (most importantly) the final "this is irreversible" dialog fails to appear.

Tested against:
  - Chrome (114)
  - Brave (1.52.130)
  - Edge (114)

It all works fine in Firefox (115). Some examples of what I've seen (taken from Chrome) are attached:

1) OBSERVATION 1: Selecting a face to merge with and scrolling down the list of faces will result in this inconsistent appearance - columns and entire rows appear to be missing:

![fig1-inconsistent-face-row](https://github.com/immich-app/immich/assets/42374576/df2ccf00-94c2-4ce8-83d0-97d96bdde2ec)

2) OBSERVATION 2: After selecting a face to merge with, the "Merge" button itself (top-right) plays hide and seek with the cursor (appearing and disappearing on hover):

![fig2-mergebuttongone](https://github.com/immich-app/immich/assets/42374576/5802a9cd-6052-4c99-855c-d1b654646505)
![fig3-mergebuttonback](https://github.com/immich-app/immich/assets/42374576/3d98d269-1a11-4514-81f7-721eec83e569)

3) OBSERVATION 3: After selecting the "Merge" button, the confirmation dialog won't appear. If you know where to hunt, hovering the mouse over it on the centre of the page MAY make part of it  re-appear:

![fig4-theamazinglyinconsitent-incomplete-confirmdialog](https://github.com/immich-app/immich/assets/42374576/3dcf59d0-0106-4cb9-bcc5-634e6567335d)

**WORKAROUND**: Re-size the browser window, particularly horizontally, to less than about 1024 pixels, and the interface springs back into life after an immediate re-paint. Sidenote: UI performance is improved the smaller the window is.

### The OS that Immich Server is running on

Docker (x86_64)

### Version of Immich Server

1.67.1

### Version of Immich Mobile App

1.66.0 build 89

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#version: "3.8"
version: "3.3"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
#      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /opt/immich-app/model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /opt/immich-app/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /opt/immich-app/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

#UPLOAD_LOCATION=absolute_location_on_your_machine_where_you_want_to_store_the_backup
UPLOAD_LOCATION=/autofs/Qmultimedia/Pictures/Immich


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=<redacted>
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="AND LO, UNTO THEE WAS BORN A GPHOTOS CLONE..."

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default, 
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1. Open Chrome/Edge/Brave or some other Chromium browser, log in to Immich
2. Re-size the window to at least 1024px wide (the effect is more noticeable the wider the window is)
3. Navigate to Explore
4. Select a person
5. From the 3-dot menu top-right, select "Merge Face"
6. Scroll down. Observe that after the first few rows, faces will load inconsistently and may appear or disappear when scrolling back up the list or when the mouse is hovered on or close to their intended position (OBSERVATION 1)
7. Select a face to merge with. Observe that the MERGE button, top right, may disappear. It may re-appear if the mouse is moved over it's intended position (OBSERVATION 2)
8. Clicking the MERGE button should present a dialog in the centre of the screen. Frequently this never appears at all. The active part of the pop-up (confirm/cancel buttons) may appear if the mouse is hovered over the centre of the screen (OBSERVATION 3)
9. In any of these steps, re-sizing the browser window to a smaller horizontal width is likely to force a re-paint that makes all symptoms disappear.
```
