### ISSUE TITLE
[BUG] fullscreen uncloseable "Drop files anywhere to upload" with bouncing icon screen constantly pops up in web interface

### ISSUE THREAD

**Issue by mynamewastaken** [immich-app/immich#3274]
### The bug

With Firefox 114.0 on Fedora 37 (actually Nobara, but I don't think that matters), I get this super annoying fullscreen upload splash screen constantly. This screen is uncloseable - I can only get rid of it by refreshing the page.

This does not happen on mobile or when I'm logged in as the initial "admin" user, this only happens as my "normal" user that has content uploaded.

I attempted to upgrade from 1.66.1 to latest 1.67.2 but that did not fix the issue.

### The OS that Immich Server is running on

Kubernetes k3s: v1.27.1+k3s1

### Version of Immich Server

v1.67.2

### Version of Immich Mobile App

1.66.1 build.89 -- sourced from f-droid

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
Running in k8s with official helm chart (immich-0.1.1) and traefik (2.9.9) as ingress - not docker compose. I'm using a basically stock values.yaml file with all the services enabled and persistence enabled on most components.

The only real non-stock thing I have is a kustomize patch to add an additional volume mount to the immich-server component as the helm-chart supports adding an additional volume mount on other components but not immich-server.


image:
  tag: v1.67.2

env:
  TZ: America/Chicago
  LOG_LEVEL: verbose
  PUBLIC_IMMICH_SERVER_URL: "https://immich.domain.org"
  PUID: 1014
  PGID: 1014

...

proxy:
  enabled: true
  ingress:
    main:
      enabled: true
      ingressClassName: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-internal-only@kubernetescrd
        gethomepage.dev/enabled: true
        gethomepage.dev/group: media
      hosts:
        - host: &host immich.domain.org
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
          - *host
```
```


### Your .env content

```Shell
See above
```

### Reproduction steps

```bash
This triggers by:
- waiting 5+ seconds
- sometimes highlighting text on the page
- changing focus to another window
```
