### ISSUE TITLE
[BUG] Unsupported file type

### ISSUE THREAD

**Issue by 1karu5** [immich-app/immich#3351]
### The bug

I have some photos from my dji drone on the iPhone and they fail to upload.
The Immich iOS app reports just failed with a bad request.
The server log containts:

```
immich_server            | [Nest] 1  - 07/20/2023, 4:16:28 PM   ERROR [AssetService] Unsupported file type dji_fly_20230617_132158_978_1687006741843_photo_optimized
```

Exiftool reports the following on the image:

```
ExifTool Version Number         : 12.60
File Name                       : dji_fly_20230617_132158_978_1687006741843_photo_optimized.JPG
Directory                       : .
File Size                       : 6.7 MB
File Modification Date/Time     : 2023:06:17 14:59:01+02:00
File Access Date/Time           : 2023:07:20 18:22:06+02:00
File Inode Change Date/Time     : 2023:07:20 18:22:04+02:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.01
Resolution Unit                 : None
X Resolution                    : 72
Y Resolution                    : 72
Exif Byte Order                 : Big-endian (Motorola, MM)
Make                            : DJI
Camera Model Name               : FC7203
Orientation                     : Horizontal (normal)
Exposure Time                   : 1/120
F Number                        : 2.8
ISO                             : 100
Aperture Value                  : 2.8
Max Aperture Value              : 2.8
Color Space                     : sRGB
Exif Image Width                : 4000
Exif Image Height               : 2250
Image Width                     : 4000
Image Height                    : 2250
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Aperture                        : 2.8
Image Size                      : 4000x2250
Megapixels                      : 9.0
Shutter Speed                   : 1/120
Light Value                     : 9.9
```

Other jpg images are working fine.

### The OS that Immich Server is running on

Linux

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

v1.67.0 build.107

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/some/location
IMMICH_VERSION=v1.68.0
```

### Reproduction steps

```bash
1. Start immich with docker compose
2. Install iOS app, try to backup some foto from the dji app/drone
3. Fails in iOS app, error message in docker logs
```
