### ISSUE TITLE
[BUG] Videos not playing in mobile browsers

### ISSUE THREAD

**Issue by FrankelJb** [immich-app/immich#3387]
### The bug

I have shared a link to an album from my desktop browser to some friends. They are able to view the shared album and images work correctly. However, they are unable to watch videos. I tested myself and the problem is reproduced on multiple devices in the mobile browser. I've checked the server and web logs and there is no output.

I'm not sure how to get the logs on mobile browser or even how to debug further. This issue does not appear to be limited to the shared albums, I cannot play videos on mobile browsers even when signed in and all videos are available.

### The OS that Immich Server is running on

Kubernetes (RKE v1.26.1+rke2r1)

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

1.68.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: cloud
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    args:
      - start-server.sh
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.68.0@sha256:b17f2525185f0a4c5c79a774d9441361dec7aabc39b9a09f7f094b98c60aec8c
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        mountPath: /usr/src/app/upload
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    service:
      main:
        ports:
          http:
            port: 3001
---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: cloud
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap
    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.68.0@sha256:44d1174efaea60ae16a9ad773f0cc0b86efabbfe292541b93e56167a782e7216
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ${ROOT_DOMAIN}
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          whitelist-source-range.home.arpa/disabled: "true"
        hosts:
          - host: &host immich.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        mountPath: /usr/src/app/upload
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
    service:
      main:
        ports:
          http:
            port: 3000
```
```


### Your .env content

```Shell
apiVersion: v1
data:
  DISABLE_REVERSE_GEOCODING: "true"
  LOG_LEVEL: "verbose"
  NODE_ENV: "production"
  REDIS_HOSTNAME: redis-master.default.svc.cluster.local
  IMMICH_SERVER_URL: http://immich-server.cloud.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.cloud.svc.cluster.local:3000
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.cloud.svc.cluster.local:3003
  TYPESENSE_HOST: immich-typesense.cloud.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: immich-configmap
  namespace: cloud
```
```


### Reproduction steps

```bash
1. Create shared album link from desktop browser
2. Share with anonymous users
3. Open the link in browser (with or without signing in)
4. Try to play video
5. Small red ! appears and video does not play
```

### Additional information

This issue does not occur on desktop browsers or in the app but is affecting all mobile browsers on both Android and iOS.
