### ISSUE TITLE
[BUG] Importing read-only gallery of 1.0 TByte size crashes frequently

### ISSUE THREAD

**Issue by JarlMorgennebel** [immich-app/immich#3416]
### The bug

```shell
docker run -it --rm -v /mnt/media/existing-morgennebel:/mnt/media/existing-morgennebel ghcr.io/immich-app/immich-cli:latest upload --key VxxxXXXxxxU --server http://192.168.1.XXX/api /mnt/media/existing-morgennebel --recursive --import
``` 

to import about 57.000 files will crash. Latest **1.68.0 server and immich-cli docker**.

```shell
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2010-2014/Familie 1403 - Lennarts Geburtstagsfeier/DSC_7221.NEF',
  reason: TypeError: mimeType.split is not a function
      at getAssetType (/usr/src/app/bin/index.js:462:21)
      at /usr/src/app/bin/index.js:319:31
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/src/app/bin/index.js:28:12)
      at startUpload (/usr/src/app/bin/index.js:317:12)
      at /usr/src/app/bin/index.js:225:51
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71,
  response: undefined
}
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2010-2014/Familie 1403 - Lennarts Geburtstagsfeier/DSC_7222.NEF',
  reason: TypeError: mimeType.split is not a function
      at getAssetType (/usr/src/app/bin/index.js:462:21)
      at /usr/src/app/bin/index.js:319:31
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/src/app/bin/index.js:28:12)
      at startUpload (/usr/src/app/bin/index.js:317:12)
      at /usr/src/app/bin/index.js:225:51
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71,
  response: undefined
}
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2010-2014/Familie 1403 - Lennarts Geburtstagsfeier/DSC_7223.NEF',
  reason: TypeError: mimeType.split is not a function
      at getAssetType (/usr/src/app/bin/index.js:462:21)
      at /usr/src/app/bin/index.js:319:31
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/src/app/bin/index.js:28:12)
      at startUpload (/usr/src/app/bin/index.js:317:12)
      at /usr/src/app/bin/index.js:225:51
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71,
  response: undefined
}
``` 

and

```shell
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2020-2024/Familie 2009 - Inekes neue Brille/IMG_20200921_072847_1.jpg',
  reason: Error: getaddrinfo EAI_AGAIN 192.168.1.XXX
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
    errno: -3001,
    code: 'EAI_AGAIN',
    syscall: 'getaddrinfo',
    hostname: '192.168.1.XXX',
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: Infinity,
      maxBodyLength: Infinity,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'post',
      maxRedirects: 0,
      url: 'http://192.168.1.XXX/api/asset/import',
      data: '{"deviceAssetId":"IMG_20200921_072847_1.jpg-4954343","deviceId":"CLI","assetType":"IMAGE","fileCreatedAt":"2020-09-21T05:28:50.000Z","fileModifiedAt":"2020-09-21T05:28:50.000Z","isFavorite":"false","fileExtension":".jpg","duration":"0:00:00.000000","isReadOnly":"true","assetPath":"/mnt/media/existing-oliver/Familie-Photos/2020-2024/Familie 2009 - Inekes neue Brille/IMG_20200921_072847_1.jpg"}'
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 395,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: true,
      socket: [Socket],
      _header: 'POST /api/asset/import HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'x-api-key: VxxxXXXxxxU\r\n' +
        'User-Agent: axios/0.26.0\r\n' +
        'Content-Length: 395\r\n' +
        'Host: 192.168.1.XXX\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/asset/import',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.1.XXX',
      protocol: 'http:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: undefined,
    isAxiosError: true,
    toJSON: [Function: toJSON]
  },
  response: undefined
}
``` 

and

```shell
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2010-2014/Familie 1401 - Opis Geburtstagsfeier/DSC_7047.dng',
  reason: TypeError: mimeType.split is not a function
      at getAssetType (/usr/src/app/bin/index.js:462:21)
      at /usr/src/app/bin/index.js:319:31
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/src/app/bin/index.js:28:12)
      at startUpload (/usr/src/app/bin/index.js:317:12)
      at /usr/src/app/bin/index.js:225:51
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71,
  response: undefined
}
Error asset:  {
  file: '/mnt/media/existing-morgennebel/Familie-Photos/2010-2014/Familie 1401 - Opis Geburtstagsfeier/DSC_7048.dng',
  reason: TypeError: mimeType.split is not a function
      at getAssetType (/usr/src/app/bin/index.js:462:21)
      at /usr/src/app/bin/index.js:319:31
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71
      at new Promise (<anonymous>)
      at __awaiter (/usr/src/app/bin/index.js:28:12)
      at startUpload (/usr/src/app/bin/index.js:317:12)
      at /usr/src/app/bin/index.js:225:51
      at Generator.next (<anonymous>)
      at /usr/src/app/bin/index.js:32:71,
  response: undefined
}
``` 

Note: API keys and server information redacted.

### The OS that Immich Server is running on

Devuan base OS, docker-compose for Immich

### Version of Immich Server

v1.68.0

### Version of Immich Mobile App

Not used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.3"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/existing-nina:/mnt/media/existing-nina:ro
      - /mnt/media/existing-oliver:/mnt/media/existing-oliver:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/existing-nina:/mnt/media/existing-nina:ro
      - /mnt/media/existing-oliver:/mnt/media/existing-oliver:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 80:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-senti
nel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/media/immich+existing


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=opsijfijsh0984u903jfv032jfsdsdf
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ld
CIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
docker run -it --rm -v /mnt/media/existing-morgennebel:/mnt/media/existing-morgennebel ghcr.io/immich-app/immich-cli:latest upload --key VxxxXXXxxxU --server http://192.168.1.XXX/api /mnt/media/existing-morgennebel --recursive --import
```

### Additional information

RAW files from Nikon and Fujifilm.
