### ISSUE TITLE
[BUG] Immich server will not start after installation

### ISSUE THREAD

**Issue by GrMoney93** [immich-app/immich#3525]
### The bug

The server gives no response

https://i.imgur.com/fEhy3ZV.png

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

If I run the docker ps --all command I see that the images are constantly restarting?

```
$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                            PORTS      NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   About a minute ago   Restarting (159) 48 seconds ago              immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   About a minute ago   Restarting (159) 1 second ago                immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago          Restarting (159) 31 seconds ago              immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago          Restarting (159) 21 seconds ago              immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago          Restarting (159) 37 seconds ago              immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        5432/tcp   immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        6379/tcp   immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago          Restarting (159) 24 seconds ago              immich_web

$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                            PORTS      NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   About a minute ago   Restarting (159) 49 seconds ago              immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   About a minute ago   Restarting (159) 3 seconds ago               immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago          Restarting (159) 33 seconds ago              immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago          Restarting (159) 23 seconds ago              immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago          Restarting (159) 38 seconds ago              immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        5432/tcp   immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        6379/tcp   immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago          Restarting (159) 25 seconds ago              immich_web

$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                            PORTS      NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   About a minute ago   Restarting (159) 50 seconds ago              immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   About a minute ago   Restarting (159) 4 seconds ago               immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago          Restarting (159) 34 seconds ago              immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago          Restarting (159) 24 seconds ago              immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago          Restarting (159) 39 seconds ago              immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        5432/tcp   immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        6379/tcp   immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago          Restarting (159) 26 seconds ago              immich_web

$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                            PORTS                                       NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   About a minute ago   Up Less than a second             0.0.0.0:2283->8080/tcp, :::2283->8080/tcp   immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   About a minute ago   Restarting (159) 5 seconds ago                                                immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago          Restarting (159) 35 seconds ago                                               immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago          Restarting (159) 25 seconds ago                                               immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago          Restarting (159) 40 seconds ago                                               immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        5432/tcp                                    immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        6379/tcp                                    immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago          Restarting (159) 27 seconds ago                                               immich_web

$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED              STATUS                            PORTS      NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   About a minute ago   Restarting (159) 3 seconds ago               immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   About a minute ago   Restarting (159) 9 seconds ago               immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago          Restarting (159) 38 seconds ago              immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago          Restarting (159) 29 seconds ago              immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago          Restarting (159) 44 seconds ago              immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        5432/tcp   immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago          Up 2 hours                        6379/tcp   immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago          Restarting (159) 31 seconds ago              immich_web

$ docker ps --all
CONTAINER ID   IMAGE                                                COMMAND                  CREATED         STATUS                            PORTS      NAMES
83d2e465097e   ghcr.io/immich-app/immich-proxy:release              "/docker-entrypoint.…"   2 minutes ago   Restarting (159) 5 seconds ago               immich_proxy
0ac10c440b4c   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 minutes ago   Restarting (159) 11 seconds ago              immich_server
be0e9c6926e5   ghcr.io/immich-app/immich-server:release             "tini -- /bin/sh sta…"   2 hours ago     Restarting (159) 40 seconds ago              immich_microservices
2c69b03c78a6   ghcr.io/immich-app/immich-machine-learning:release   "tini -- python -m a…"   2 hours ago     Restarting (159) 31 seconds ago              immich_machine_learning
df6574f577e0   typesense/typesense:0.24.1                           "/opt/typesense-serv…"   2 hours ago     Restarting (159) 46 seconds ago              immich_typesense
c6005cc5f39d   postgres:14-alpine                                   "docker-entrypoint.s…"   2 hours ago     Up 2 hours                        5432/tcp   immich_postgres
2e845ba2eb24   redis:6.2-alpine                                     "docker-entrypoint.s…"   2 hours ago     Up 2 hours                        6379/tcp   immich_redis
a1bf1d0195bf   ghcr.io/immich-app/immich-web:release                "tini -- /bin/sh ent…"   2 hours ago     Restarting (159) 33 seconds ago              immich_web
```

### The OS that Immich Server is running on

Raspbian

### Version of Immich Server

3.8

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    platform: linux/arm64
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    platform: linux/arm64
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    platform: linux/arm64
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    platform: linux/arm64
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    platform: linux/arm64
    container_name: immich_typesense
    image: typesense/typesense:0.24.1
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always


  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    platform: linux/arm64
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```


### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=xxxxxxxxxxx
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/media/user/ExternalUSBDrive/PhotoBackUp/


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=xxxxxxxxxxx
TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wb>
###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=

IMMICH_MACHINE_LEARNING_URL=false
```


### Reproduction steps

```bash
After following the guide at (https://immich.app/docs/install/docker-compose) I run the command:


 ✔ Network immich-app_default         Created                                                                                                                                                                                                                             1.3s
 ✔ Volume "immich-app_tsdata"         Created                                                                                                                                                                                                                             0.4s
 ✔ Volume "immich-app_pgdata"         Created                                                                                                                                                                                                                             0.1s
 ✔ Volume "immich-app_model-cache"    Created                                                                                                                                                                                                                             0.3s
 ✔ Container immich_postgres          Started                                                                                                                                                                                                                            27.5s
 ✔ Container immich_machine_learning  Started                                                                                                                                                                                                                            27.7s
 ✔ Container immich_typesense         Started                                                                                                                                                                                                                            28.1s
 ✔ Container immich_redis             Started                                                                                                                                                                                                                            27.9s
 ✔ Container immich_web               Started                                                                                                                                                                                                                            29.3s
 ✔ Container immich_server            Started                                                                                                                                                                                                                             7.3s
 ✔ Container immich_microservices     Started                                                                                                                                                                                                                             7.6s
 ✔ Container immich_proxy             Started                                                                                                                                                                                                                             8.3s
```

I then could not connect to the server (as shown in the above screenshot), so I restarted the pi and still have the same issue:

```
$ docker compose up -d
[+] Running 8/0
 ✔ Container immich_redis             Running                                                                                                                                                                                                                             0.0s
 ✔ Container immich_postgres          Running                                                                                                                                                                                                                             0.0s
 ✔ Container immich_typesense         Started                                                                                                                                                                                                                             0.0s
 ✔ Container immich_web               Started                                                                                                                                                                                                                             0.0s
 ✔ Container immich_machine_learning  Started                                                                                                                                                                                                                             0.0s
 ✔ Container immich_microservices     Started                                                                                                                                                                                                                             0.0s
 ✔ Container immich_server            Started                                                                                                                                                                                                                             0.0s
 ✔ Container immich_proxy             Started
```
```


### Additional information

_No response_
