### ISSUE TITLE
[BUG] RAW images show with pink overlay starting in 1.72.0

### ISSUE THREAD

**Issue by adambeck7** [immich-app/immich#3584]
### The bug

RAW images (specifically CR3 in my case) have a pink overlay in the mobile app and web GUI when uploaded via CLI or web GUI. The image on the left is a CR3 file, the image on the right is a jpeg of the same image. Both uploaded via web uploader. 
<img width="989" alt="Screenshot 2023-08-07 at 6 36 54 AM" src="https://github.com/immich-app/immich/assets/18033909/cadc3cc2-875d-449b-aaec-7d24c89bff1e">

They look the same when viewed in the mobile app. 
![immich_pink_mobile](https://github.com/immich-app/immich/assets/18033909/e37d5414-1be7-41e1-9f6d-baca414a4ce9)

One caveat I've found, if I transfer the RAW file to my phone and upload via the mobile app backup, it doesn't contain the pink overlay when viewed from the mobile app. It does still have the overlay on the web view. I uploaded hundreds of RAW files recently as two days ago through 1.71.x and it worked fine. This happens on both 1.72.0 and 1.72.1. Let me know if there is anything else I can do to help debug. Awesome work on Immich!

### The OS that Immich Server is running on

Unraid 6.11.5

### Version of Immich Server

1.72.1

### Version of Immich Mobile App

1.72.0 build 112

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - .env
    environment:
      # Rename these values for svelte public interface
      - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /mnt/user/appdata/typesense/data:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME={my_host}
DB_USERNAME={my_user}
DB_PASSWORD={my_pass}
DB_DATABASE_NAME={my_name}

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

# REDIS_HOSTNAME=

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/Pictures/Immich/

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=simple

###################################################################################
# JWT SECRET
#
# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
###################################################################################

JWT_SECRET=string
TYPESENSE_API_KEY=string

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

 DISABLE_REVERSE_GEOCODING=false
 REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="Immich"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Immich"

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

 # IMMICH_WEB_URL=
 # IMMICH_SERVER_URL=
 # IMMICH_MACHINE_LEARNING_URL=

####################################################################################
# OAuth Setting - Optional
#
# These setting will enable OAuth login for your instance of Immich
# Folow the instructions in the page https://immich.app/docs/usage/oauth to set up your OAuth provider
####################################################################################

# OAUTH_ENABLED=false
# OAUTH_ISSUER_URL=
# OAUTH_CLIENT_ID=
# OAUTH_CLIENT_SECRET=
# OAUTH_BUTTON_TEXT=Login with OAuth
# OAUTH_AUTO_REGISTER=true
# OAUTH_SCOPE="openid profile email"
```

### Reproduction steps

```bash
1. Upload a RAW file, either through web gui or CLI. You can use this one if you'd like: https://www.dropbox.com/scl/fi/y5uz3hpqxt7iexruvv2fn/IMG_1912.CR3?rlkey=ga1asxvlc5s1swqlpabo9uhkg&dl=0
2. View in web or desktop and it'll be pink.
```
