### ISSUE TITLE
[BUG] Hardware acceleration with Intel QSV

### ISSUE THREAD

**Issue by yannick-mayeur** [immich-app/immich#3595]
### The bug

Hardware acceleration is not working with Intel QSV and an intel N5095 processor. Hardware acceleration works fine on jellyfin with the same hardware.

Log of immich_microservices:
```
immich_microservices  | [Nest] 8  - 08/08/2023, 8:52:57 AM     LOG [MediaService] Start encoding video 23e7df9c-9bc1-45a5-a55c-2e2cffe2f3af {"inputOptions":["-init_hw_device qsv=hw","-filter_hw_device hw"],"outputOptions":["-vcodec h264_qsv","-g 256","-extbrc 1","-refs 5","-bf 7","-acodec aac","-movflags faststart","-fps_mode passthrough","-v verbose","-vf format=nv12,hwupload=extra_hw_frames=64,scale_qsv=720:-1","-preset 7","-global_quality 23"],"twoPass":false}
immich_microservices  | [Nest] 8  - 08/08/2023, 8:52:57 AM   ERROR [MediaRepository] ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
immich_microservices  |   built with gcc 12 (Debian 12.2.0-14)
immich_microservices  |   configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
immich_microservices  |   libavutil      58.  2.100 / 58.  2.100
immich_microservices  |   libavcodec     60.  3.100 / 60.  3.100
immich_microservices  |   libavformat    60.  3.100 / 60.  3.100
immich_microservices  |   libavdevice    60.  1.100 / 60.  1.100
immich_microservices  |   libavfilter     9.  3.100 /  9.  3.100
immich_microservices  |   libswscale      7.  1.100 /  7.  1.100
immich_microservices  |   libswresample   4. 10.100 /  4. 10.100
immich_microservices  |   libpostproc    57.  1.100 / 57.  1.100
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] Trying to use DRM render node for device 0, with matching kernel driver (i915).
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] libva: VA-API version 1.18.0
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] libva: User requested driver 'iHD'
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] libva: Found init function __vaDriverInit_1_18
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] libva: va_openDriver() returns 0
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] Initialised VAAPI connection: version 1.18
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (8d3be84).
immich_microservices  | [AVHWDeviceContext @ 0x4d816180300] Driver not found in known nonstandard list, using standard behaviour.
immich_microservices  | [AVHWDeviceContext @ 0x4d816180200] Use Intel(R) oneVPL to create MFX session, API version is 2.9, the required implementation version is 1.3
immich_microservices  | libva info: VA-API version 1.18.0
immich_microservices  | libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
immich_microservices  | libva info: Found init function __vaDriverInit_1_18
immich_microservices  | libva info: va_openDriver() returns 0
immich_microservices  | [AVHWDeviceContext @ 0x4d816180200] Initialize MFX session: implementation version is 1.35
immich_microservices  | [mov,mp4,m4a,3gp,3g2,mj2 @ 0x4d8161f4380] All samples in data stream index:id [3:4] have zero duration, stream set to be discarded by default. Override using AVStream->discard or -discard for ffmpeg command.
immich_microservices  | Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'upload/library/5441b74c-0626-44dc-8622-5e8b3bcc0996/2023/04-12/PXL_20230412_173001942.mp4':
immich_microservices  |   Metadata:
immich_microservices  |     major_brand     : isom
immich_microservices  |     minor_version   : 131072
immich_microservices  |     compatible_brands: isomiso2mp41
immich_microservices  |     creation_time   : 2023-04-12T17:30:15.000000Z
immich_microservices  |     com.android.capture.fps: 30.000000
immich_microservices  |   Duration: 00:00:11.70, start: 0.000000, bitrate: 19906 kb/s
immich_microservices  |   Stream #0:0[0x1](eng): Data: none (mett / 0x7474656D), 51 kb/s (default)
immich_microservices  |     Metadata:
immich_microservices  |       creation_time   : 2023-04-12T17:30:15.000000Z
immich_microservices  |       handler_name    : MetaHandle
immich_microservices  |   Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
immich_microservices  |     Metadata:
immich_microservices  |       creation_time   : 2023-04-12T17:30:15.000000Z
immich_microservices  |       handler_name    : SoundHandle
immich_microservices  |       vendor_id       : [0][0][0][0]
immich_microservices  |   Stream #0:2[0x3](eng): Video: hevc (Main), 1 reference frame (hvc1 / 0x31637668), yuvj420p(pc, bt709, left), 1920x1080 (1920x1088), 19656 kb/s, SAR 1:1 DAR 16:9, 29.99 fps, 30 tbr, 90k tbn (default)
immich_microservices  |     Metadata:
immich_microservices  |       creation_time   : 2023-04-12T17:30:15.000000Z
immich_microservices  |       handler_name    : VideoHandle
immich_microservices  |       vendor_id       : [0][0][0][0]
immich_microservices  |     Side data:
immich_microservices  |       displaymatrix: rotation of -90.00 degrees
immich_microservices  |   Stream #0:3[0x4](eng): Data: none (mett / 0x7474656D) (default)
immich_microservices  |     Metadata:
immich_microservices  |       creation_time   : 2023-04-12T17:30:15.000000Z
immich_microservices  |       handler_name    : MetaHandle
immich_microservices  | Stream mapping:
immich_microservices  |   Stream #0:2 -> #0:0 (hevc (native) -> h264 (h264_qsv))
immich_microservices  |   Stream #0:1 -> #0:1 (aac (native) -> aac (native))
immich_microservices  | Press [q] to stop, [?] for help
immich_microservices  | [graph 0 input from stream 0:2 @ 0x4d816205b80] w:1920 h:1080 pixfmt:yuvj420p tb:1/90000 fr:30/1 sar:1/1
immich_microservices  | [auto_scale_0 @ 0x4d816202340] w:iw h:ih flags:'' interl:0
immich_microservices  | [transpose @ 0x4d816205d00] auto-inserting filter 'auto_scale_0' between the filter 'graph 0 input from stream 0:2' and the filter 'transpose'
immich_microservices  | [swscaler @ 0x4d81650a000] deprecated pixel format used, make sure you did set range correctly
immich_microservices  | [auto_scale_0 @ 0x4d816202340] w:1920 h:1080 fmt:yuvj420p sar:1/1 -> w:1920 h:1080 fmt:nv12 sar:1/1 flags:0x00000004
immich_microservices  | [transpose @ 0x4d816205d00] w:1920 h:1080 dir:1 -> w:1080 h:1920 rotation:clockwise vflip:0
immich_microservices  | [AVHWDeviceContext @ 0x4d8161842c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (8d3be84).
immich_microservices  | [AVHWDeviceContext @ 0x4d8161842c0] Driver not found in known nonstandard list, using standard behaviour.
immich_microservices  | [AVHWDeviceContext @ 0x4d8161851c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (8d3be84).
immich_microservices  | [AVHWDeviceContext @ 0x4d8161851c0] Driver not found in known nonstandard list, using standard behaviour.
immich_microservices  | [Parsed_scale_qsv_2 @ 0x4d816205ac0] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
immich_microservices  | [Parsed_scale_qsv_2 @ 0x4d816205ac0] VPP: input is video memory surface
immich_microservices  | [Parsed_scale_qsv_2 @ 0x4d816205ac0] VPP: output is video memory surface
immich_microservices  | [swscaler @ 0x4d81650a000] deprecated pixel format used, make sure you did set range correctly
immich_microservices  | [auto_scale_0 @ 0x4d816202340] w:1920 h:1080 fmt:yuvj420p sar:1/1 -> w:1920 h:1080 fmt:nv12 sar:1/1 flags:0x00000004
immich_microservices  | [swscaler @ 0x4d81650a000] deprecated pixel format used, make sure you did set range correctly
immich_microservices  | [auto_scale_0 @ 0x4d816202340] w:1920 h:1080 fmt:yuvj420p sar:1/1 -> w:1920 h:1080 fmt:nv12 sar:1/1 flags:0x00000004
immich_microservices  | [swscaler @ 0x4d81650a000] deprecated pixel format used, make sure you did set range correctly
immich_microservices  | [auto_scale_0 @ 0x4d816202340] w:1920 h:1080 fmt:yuvj420p sar:1/1 -> w:1920 h:1080 fmt:nv12 sar:1/1 flags:0x00000004
immich_microservices  | [AVHWFramesContext @ 0x4d816123540] Use Intel(R) oneVPL to create MFX session, API version is 2.9, the required implementation version is 1.35
immich_microservices  | [AVHWFramesContext @ 0x4d816123540] Initialize MFX session: implementation version is 1.35
immich_microservices  | [h264_qsv @ 0x4d816224180] Using input frames context (format qsv) with h264_qsv encoder.
immich_microservices  | [h264_qsv @ 0x4d816224180] Encoder: input is video memory surface
immich_microservices  | [h264_qsv @ 0x4d816224180] Use Intel(R) oneVPL to create MFX session with the specified MFX loader
immich_microservices  | [h264_qsv @ 0x4d816224180] Using the intelligent constant quality (ICQ) ratecontrol method
immich_microservices  | [h264_qsv @ 0x4d816224180] Error initializing the encoder: invalid video parameters (-15)
immich_microservices  | [vost#0:0/h264_qsv @ 0x4d8161f1380] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
immich_microservices  | [AVIOContext @ 0x4d816131e00] Statistics: 0 bytes written, 0 seeks, 0 writeouts
immich_microservices  | Terminating demuxer thread 0
immich_microservices  | [AVIOContext @ 0x4d81621d880] Statistics: 2726492 bytes read, 4 seeks
immich_microservices  | Conversion failed!
immich_microservices  |
immich_microservices  | [Nest] 8  - 08/08/2023, 8:52:57 AM   ERROR [MediaService] Error: ffmpeg exited with code 1: Conversion failed!
immich_microservices  |
immich_microservices  | [Nest] 8  - 08/08/2023, 8:52:57 AM   ERROR [MediaService] Error occurred during transcoding. Retrying with QSV acceleration disabled.
```

Check for QSV codecs:
```
○ sudo docker exec -it immich_microservices /usr/lib/jellyfin-ffmpeg/vainfo
Trying display: drm
libva info: VA-API version 1.18.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_18
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (8d3be84)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSliceLP
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSliceLP
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile1            :	VAEntrypointVLD
      VAProfileVP9Profile1            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointEncSliceLP
      VAProfileVP9Profile3            :	VAEntrypointVLD
      VAProfileVP9Profile3            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain422_10         :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointVLD
      VAProfileHEVCMain444            :	VAEntrypointEncSliceLP
      VAProfileHEVCMain444_10         :	VAEntrypointVLD
      VAProfileHEVCMain444_10         :	VAEntrypointEncSliceLP
```

Check for OpenCL runtime status (n.b the error at the end):
```
○ sudo docker exec -it immich_microservices /usr/lib/jellyfin-ffmpeg/ffmpeg -v verbose -init_hw_device vaapi=va -init_hw_device opencl@va
ffmpeg version 6.0-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
[AVHWDeviceContext @ 0x55d238a992c0] Trying to use DRM render node for device 0.
[AVHWDeviceContext @ 0x55d238a992c0] libva: VA-API version 1.18.0
[AVHWDeviceContext @ 0x55d238a992c0] libva: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
[AVHWDeviceContext @ 0x55d238a992c0] libva: Found init function __vaDriverInit_1_18
[AVHWDeviceContext @ 0x55d238a992c0] libva: va_openDriver() returns 0
[AVHWDeviceContext @ 0x55d238a992c0] Initialised VAAPI connection: version 1.18
[AVHWDeviceContext @ 0x55d238a992c0] VAAPI driver: Intel iHD driver for Intel(R) Gen Graphics - 23.2.3 (8d3be84).
[AVHWDeviceContext @ 0x55d238a992c0] Driver not found in known nonstandard list, using standard behaviour.
[AVHWDeviceContext @ 0x55d238abc100] Failed to get number of OpenCL platforms: -1001.
Device creation failed: -19.
Failed to set value 'opencl@va' for option 'init_hw_device': No such device
Error parsing global options: No such device
```

My guess is that something like the OpenCL-intel mod from LSIO for jellyfin is necessary: https://github.com/linuxserver/docker-jellyfin#hardware-acceleration

### The OS that Immich Server is running on

Ubuntu 23.05

### Version of Immich Server

1.72.2

### Version of Immich Mobile App

1.72.0 build.95

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=******
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/home/yannick/immich-app/data


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=*******
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { 'host': 'typesense-1.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-2.example.net', 'port': '443', 'protocol': 'https' },
#      { 'host': 'typesense-3.example.net', 'port': '443', 'protocol': 'https' },
#  ]
# TYPESENSE_URL=ha://WwogICAgeyAnaG9zdCc6ICd0eXBlc2Vuc2UtMS5leGFtcGxlLm5ldCcsICdwb3J0JzogJzQ0MycsICdwcm90b2NvbCc6ICdodHRwcycgfSwKICAgIHsgJ2hvc3QnOiAndHlwZXNlbnNlLTIuZXhhbXBsZS5uZXQnLCAncG9ydCc6ICc0NDMnLCAncHJvdG9jb2wnOiAnaHR0cHMnIH0sCiAgICB7ICdob3N0JzogJ3R5cGVzZW5zZS0zLmV4YW1wbGUubmV0JywgJ3BvcnQnOiAnNDQzJywgJ3Byb3RvY29sJzogJ2h0dHBzJyB9LApd

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001
```

### Reproduction steps

```bash
1. Enable hardware acceleration by following: https://immich.app/docs/features/hardware-transcoding
2. Run the transcode videos job
3. Observe error in logs
```

### Additional information

hw_accel.yml file:

```
version: "3.8"

# Hardware acceleration for transcoding - Optional
# This is only needed if you want to use hardware acceleration for transcoding.
# Depending on your hardware, you should uncomment the relevant lines below.

services:
  hwaccel:
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    # volumes:
    #   - /usr/lib/wsl:/usr/lib/wsl # If using VAAPI in WSL2
    # environment:
    #   - LD_LIBRARY_PATH=/usr/lib/wsl/lib # If using VAAPI in WSL2
    #   - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
    #   - LIBVA_DRIVER_NAME=d3d12 # If using VAAPI in WSL2
    # deploy: # Uncomment this section if using NVIDIA GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
```
