### ISSUE TITLE
[BUG] <iOS app often stuck on upload>

### ISSUE THREAD

**Issue by nukewarrior** [immich-app/immich#3632]
### The bug

upload process often stuck.
I have to manually cancel and then start backup process.
![image](https://github.com/immich-app/immich/assets/10683831/71aabefc-9032-415a-bab1-39e008220616)
![image](https://github.com/immich-app/immich/assets/10683831/3a75e206-4fc4-45fe-aff2-49782386b057)

### The OS that Immich Server is running on

Unraid 6.12.3

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

v1.72.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    restart: unless-stopped
    cpuset: 4,5,10,11
    networks:
      - traefik
    expose:
      - 8080
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./immich:/photos
      - ./config:/config
      - ./machine-learning:/config/machine-learning
    environment:
      - TZ=Asia/Shanghai
      - PUID=99
      - PGID=100
      - UMASK=000
      - DB_HOSTNAME=<x.x.x.x>
      - DB_USERNAME=<username>
      - DB_PASSWORD=<password>
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=<x.x.x.x>
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      # - REDIS_PASSWORD= #optional
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # web-ui
      - "traefik.http.routers.immich.entrypoints=out"
      - "traefik.http.routers.immich.rule=Host(`photo.<mydomain>.com`)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=8080"

      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.shell=bash"
      - "net.unraid.docker.webui=https://photo.<mydomain>.com"
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/imagegenius/templates/main/unraid/img/immich.png"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
none,I just put env variables in compose file
```

### Reproduction steps

```bash
1.open app,foreground backup auto start
2.wait for a while,and the process will stuck on some pic
```
