### ISSUE TITLE
[BUG] Permission denied on video playback

### ISSUE THREAD

**Issue by kyemacdonald** [immich-app/immich#3671]
### The bug

Playback of a video fails with immich reporting permission denied to the file.  This then causes handlers to crash and time out.

Videos have been imported into immich via the android app.  The video has been processed and provides a thumbnail and exif data.

`[Nest] 8  - 08/14/2023, 5:03:40 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:04:38 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

[Nest] 8  - 08/14/2023, 5:04:38 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

[Nest] 8  - 08/14/2023, 5:04:38 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

[Nest] 8  - 08/14/2023, 5:05:02 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194437.mp4'

[Nest] 8  - 08/14/2023, 5:05:02 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:02 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

[Nest] 8  - 08/14/2023, 5:05:02 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194232.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194232.mp4'

[Nest] 8  - 08/14/2023, 5:05:20 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:20 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:21 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:27 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:47 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:05:51 AM   ERROR [ExceptionsHandler] Connection terminated due to connection timeout

Error: Connection terminated due to connection timeout

    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:132:73)

    at Object.onceWrapper (node:events:628:28)

    at Connection.emit (node:events:514:28)

    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:62:12)

    at Socket.emit (node:events:514:28)

    at TCP.<anonymous> (node:net:323:12)

[Nest] 8  - 08/14/2023, 5:06:29 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

[Nest] 8  - 08/14/2023, 5:06:31 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194426.mp4'

[Nest] 8  - 08/14/2023, 5:06:39 AM   ERROR [ExceptionsHandler] EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'

Error: EACCES: permission denied, access 'upload/library/admin/2023/2023-08-10/2023-08-10-20230810_194431.mp4'`


Output from inside the container showing file list and permission.

`root@f8ce7da4c5d3:/usr/src/app/upload# cd library/admin/2023/2023-08-10
root@f8ce7da4c5d3:/usr/src/app/upload/library/admin/2023/2023-08-10# ls -la
total 159532
drwxrwxrwx   2 root root     4096 Aug 11 09:38 .
drwxrwxrwx 223 root root    12288 Aug 11 03:24 ..
-rwxrwxrwx   1 root root  6738745 Aug 10 01:29 2023-08-10-20230810_080031.jpg
-rwxrwxrwx   1 root root  6800142 Aug 10 01:29 2023-08-10-20230810_080034.jpg
-rwxrwxrwx   1 root root  6652097 Aug 10 01:29 2023-08-10-20230810_083831.jpg
-rwxrwxrwx   1 root root  2416641 Aug 11 09:38 2023-08-10-20230810_102235.jpg
-rwxrwxrwx   1 root root  2442687 Aug 11 09:38 2023-08-10-20230810_102318.jpg
-rwxrwxrwx   1 root root  2528520 Aug 11 09:38 2023-08-10-20230810_102323.jpg
-rwxrwxrwx   1 root root  2443156 Aug 11 09:38 2023-08-10-20230810_102327.jpg
-rwxrwxrwx   1 root root  2349095 Aug 11 09:38 2023-08-10-20230810_142918.jpg
-rwxrwxrwx   1 root root  1857505 Aug 11 09:38 2023-08-10-20230810_155356.jpg
-rwxrwxrwx   1 root root 25162697 Aug 10 10:13 2023-08-10-20230810_194232.mp4
-rwxrwxrwx   1 root root  2901629 Aug 10 10:13 2023-08-10-20230810_194426.mp4
-rwxrwxrwx   1 root root  2437533 Aug 10 10:13 2023-08-10-20230810_194431.mp4
-rwxrwxrwx   1 root root 98570920 Aug 10 10:13 2023-08-10-20230810_194437.mp4
root@f8ce7da4c5d3:/usr/src/app/upload/library/admin/2023/2023-08-10# `



### The OS that Immich Server is running on

Ubuntu 22.04.02 LTS VM on Proxmox

### Version of Immich Server

v1.72.2

### Version of Immich Mobile App

1.72.0 build.95

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d7                                                                                                                                                                                                                                             77a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269cc                                                                                                                                                                                                                                             f00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a                                                                                                                                                                                                                                             4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```


### Your .env content

```Shell
server-2@server-2:/docker/nas-storage/immich-app$ cat ./.env
###################################################################################
# Database
###################################################################################

# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=**mypasswordwashere**
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# REDIS_URL will be used to pass custom options to ioredis.
# Example for Sentinel
# {"sentinels":[{"host":"redis-sentinel-node-0","port":26379},{"host":"redis-sentinel-node-1","port":26379},{"host":"redis-sentinel-node-2","port":26379}],"name":"redis-sentinel"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzdGVyIn0=

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/docker/nas-storage/immich-app/media


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=**mypasswordwashere**
# TYPESENSE_ENABLED=false
# TYPESENSE_URL uses base64 encoding for the nodes json.
# Example JSON that was used:
# [
#      { "host": "typesense-1.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-2.example.net", "port": "443", "protocol": "https" },
#      { "host": "typesense-3.example.net", "port": "443", "protocol": "https" },
# ]
# TYPESENSE_URL=ha://WwogIHsgImhvc3QiOiAidHlwZXNlbnNlLTEuZXhhbXBsZS5uZXQiLCAicG9ydCI6ICI0NDMiLCAicHJvdG9jb2wiOiAiaHR0cHMiIH0sCiAgeyAiaG9zdCI6ICJ0eXBlc2Vuc2UtMi5leGFtcGxlLm5ldCIsICJwb3J0IjogIjQ0MyIsICJwcm90b2NvbCI6ICJodHRwcyIgfSwKICB7ICJob3N0IjogInR5cGVzZW5zZS0zLmV4YW1wbGUubmV0IiwgInBvcnQiOiAiNDQzIiwgInByb3RvY29sIjogImh0dHBzIiB9Cl0=

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

#IMMICH_WEB_URL=http://immich-web:3010
#IMMICH_SERVER_URL=http://immich-server:3001
#IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```


### Reproduction steps

```bash
1.Anything that would cause the video to play, mouse over, click etc.
2.
3.
...
```


### Additional information

Doesn't seem to impact all videos.  Unsure as to what the deciding difference is between them.  However the files are in the location because immich imported them, so can't see a reason why a permission error would happen.
