### ISSUE TITLE
[BUG] Android app 400 error every few seconds.

### ISSUE THREAD

**Issue by Milkysunshine** [immich-app/immich#3729]
### The bug

fail2ban is going crazy because of all the 400 errors being thrown.

I'm not sure if I have something misconfigured in nginx proxy manager, or what. 

I'm trying to check logs in all of the immich containers, and I'm coming up empty.

Errors repeat every 5 seconds

```
[16/Aug/2023:18:54:29 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:54:35 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:54:40 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:54:45 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:54:50 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:54:56 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
[16/Aug/2023:18:55:01 +0000] - 400 400 - GET https REDACTED.com "/api/socket.io/?EIO=4&transport=websocket" [Client REDACTED-CLIENT-IP] [Length 45] [Gzip -] [Sent-to REDACTED-SERVER-IP] "Dart/3.0 (dart:io)" "-"
```

### The OS that Immich Server is running on

Docker on Debian 12

### Version of Immich Server

v1.73.0

### Version of Immich Mobile App

v1.73.0 build.96

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /docker/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - /docker/immich/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /docker/immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/docker/immich/upload
IMMICH_VERSION=release
TYPESENSE_API_KEY=REDACTED
DB_PASSWORD=REDACTED
DB_HOSTNAME=immich_postgres
DB_USERNAME=REDACTED
DB_DATABASE_NAME=REDACTED
REDIS_HOSTNAME=immich_redis
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1.open android app
2.wait 5 seconds
3.400 error on REDACTED.com/api/socket.io/?EIO=4&transport=websocket
4.wait 5 seconds
5.400 error on REDACTED.com/api/socket.io/?EIO=4&transport=websocket
...
```

### Additional information

I'm running nginx proxy manager with authelia. The error is showing in my nginx proxy manager logs.

(I'm currently writing an outline of how I got that set up because the examples and resources were limited and somewhat confusing. Plus, I ran into other undocumented issues I was able to resolve.)
