### ISSUE TITLE
[BUG] Downloading a Live Photo Throws Error on iOS/iPadOS

### ISSUE THREAD

**Issue by SNThrailkill** [immich-app/immich#3734]
### The bug

If you attempt to download a Live Photo taken on another device (like an Android phone) it will say "Download Failed". If you try to download the same photo using a browser (tried on Safari and Firefox) then it will download the photo (in this case a `.jpg` and a transcoded video of the Live Photo which seems to always be a `.mov`. The photo will download successfully but the video will always fail.

### The OS that Immich Server is running on

Kubernetes 1.24

### Version of Immich Server

1.73.0

### Version of Immich Mobile App

1.73.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

# These entries are shared between all the Immich components

env:
  REDIS_HOSTNAME: '{{ printf "%s-redis-master" .Release.Name }}'
  DB_HOSTNAME: "db.url"
  DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
  DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
  # -- You should provide your own secret outside of this helm-chart and use `postgresql.global.postgresql.auth.existingSecret` to provide credentials to the postgresql instance
  DB_PASSWORD: "{{ .Values.postgresql.global.postgresql.auth.password }}"
  TYPESENSE_ENABLED: "{{ .Values.typesense.enabled }}"
  TYPESENSE_API_KEY: "{{ .Values.typesense.env.TYPESENSE_API_KEY }}"
  TYPESENSE_HOST: '{{ printf "%s-typesense" .Release.Name }}'
  IMMICH_WEB_URL: '{{ printf "http://%s-web:3000" .Release.Name }}'
  IMMICH_SERVER_URL: '{{ printf "http://%s-server:3001" .Release.Name }}'
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
  DISABLE_REVERSE_GEOCODING: true 

# Usually you set this to have the same among all the containers, but renovate doesnt like this
#image:
#  tag: v1.73.0

immich:
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: immich-photos-nfs-pvc

# Dependencies

postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: secret

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

typesense:
  enabled: true 
  env:
    TYPESENSE_DATA_DIR: /tsdata
    TYPESENSE_API_KEY: typesense
  persistence:
    tsdata:
      # Enabling typesense persistence is recommended to avoid slow reindexing
      enabled: false
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: longhorn
  probes:
    liveness:
      spec:
        initialDelaySeconds: 60
    readiness:
      spec:
        initialDelaySeconds: 60
  image:
    repository: docker.io/typesense/typesense
    tag: 0.24.1
    pullPolicy: IfNotPresent

# Immich components

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
    tag: v1.73.0

microservices:
  enabled: true
  env:
    REVERSE_GEOCODING_DUMP_DIRECTORY: /geodata-cache
  persistence:
    geodata-cache:
      enabled: true
      size: 1Gi
      # Optional: Set this to pvc to avoid downloading the geodata every start.
      type: pvc
      accessMode: ReadWriteMany
      storageClass: longhorn
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
    tag: v1.73.0

machine-learning:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
    tag: v1.73.0
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: emptyDir
      accessMode: ReadWriteMany
      storageClass: longhorn

web:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-web
    pullPolicy: IfNotPresent
    tag: v1.73.0
  persistence:
    library:
      enabled: false

proxy:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-proxy
    pullPolicy: IfNotPresent
    tag: v1.73.0
  persistence:
    library:
      enabled: false

  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.domain
          paths:
            - path: "/"
      tls: []
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Upload a Live Photo from any device that is not iOS/iPadOS
2. From an iOS/iPadOS device, attempt download the photo locally to see error thrown
3. Attempt to download the same photo from the browser to see error thrown
```
