### ISSUE TITLE
[BUG] Panoramas from Samsung phones can't be viewed

### ISSUE THREAD

**Issue by chatpion** [immich-app/immich#3798]
### The bug

Panoramas taken on Samsung phones are not rendered in the mobile app and in the webapp. Metadata are also not extracted ("no EXIF info available"), even though they do exist in the file.

![2023-08-20_13-00](https://github.com/immich-app/immich/assets/3697923/af545db7-0b3c-47ab-840c-c368e56a5ac5)

However, I can visualize the image correctly by downloading it and opening it in another image viewer.

EDIT: it turns out that manually running a thumbnail generation job does fix the rendering issue, but the metadata are still missing nonetheless.
These errors also appeared in the logs
```
immich_microservices     | [Nest] 7  - 08/20/2023, 11:20:26 AM   ERROR [JobService] Unable to run job handler: QueryFailedError: value "3760563288" is out of range for type integer
immich_microservices     | [Nest] 7  - 08/20/2023, 11:20:26 AM   ERROR [JobService] QueryFailedError: value "3760563288" is out of range for type integer
immich_microservices     |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
immich_microservices     |     at async MetadataExtractionProcessor.handlePhotoMetadataExtraction (/usr/src/app/dist/microservices/processors/metadata-extraction.processor.js:342:9)
immich_microservices     |     at async /usr/src/app/dist/domain/job/job.service.js:104:37
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:342:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:525:24)
immich_microservices     | [Nest] 7  - 08/20/2023, 11:20:26 AM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "f031623e-8ef8-4c74-9c13-506e0e28b4ab"
immich_microservices     | }
```

Example of broken image:
![bug](https://github.com/immich-app/immich/assets/3697923/305337c7-e618-4ddf-89b8-91c1800f6960)

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.74.0

### Version of Immich Mobile App

v1.72.1 build.95

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<text>
DB_PASSWORD=<text>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload a panorama taken by a Samsung phone (bulk upload or in the web app)
2. View it in either the app or the webapp
```

### Additional information

[Photoprism also had a similar issue.](https://github.com/photoprism/photoprism/issues/3363)
