### ISSUE TITLE
[BUG] Album download reports wrong size during prep

### ISSUE THREAD

**Issue by gcarrarom** [immich-app/immich#3849]
### The bug

When sharing a large album with many videos and pictures, downloading the album reports considerably smaller footprint on the banner, then proceeds to be stuck for a while in 100% until it allows the full download to happen.
Example: 
1. Create album with over 100GB of files
2. Click download
3. Check the banner:
![CleanShot 2023-08-23 at 13 51 22](https://github.com/immich-app/immich/assets/10549675/83fdc39d-a6a0-411d-adfb-136bcb1c17f0)
4. Wait a long while after 100% hits. 
5. Check the actual download coming in:
![CleanShot 2023-08-23 at 13 33 09](https://github.com/immich-app/immich/assets/10549675/e535727f-8442-421b-a7c2-780cd79dedd5)

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.74.0

### Version of Immich Mobile App

1.74.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
postgresql:
  enabled: true
redis:
  enabled: true

typesense:
  enabled: true
  image:
    repository: docker.io/typesense/typesense
    tag: 0.24.1
    pullPolicy: Always
  persistence:
    tsdata:
      enabled: true
      existingClaim: typesense-data

machine-learning:
  enabled: true
  persistence:
    cache:
      enabled: true
      existingClaim: machinelearning-data
proxy:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: immich.fancywhale.ca
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.fancywhale.ca
          secretName: immich-fancywhale-ca-tls
image:
  tag: v1.74.0 # renovate: datasource=docker depName=altran1502/immich-server versioning=regex:^v(?<major>\d+)\.(?<minor>\d+).(?<patch>\d+)$
immich:
  persistence:
    library:
      existingClaim: photos
```

### Your .env content

```Shell
postgresql:
  enabled: true
redis:
  enabled: true

typesense:
  enabled: true
  image:
    repository: docker.io/typesense/typesense
    tag: 0.24.1
    pullPolicy: Always
  persistence:
    tsdata:
      enabled: true
      existingClaim: typesense-data

machine-learning:
  enabled: true
  persistence:
    cache:
      enabled: true
      existingClaim: machinelearning-data
proxy:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: immich.fancywhale.ca
          paths:
            - path: "/"
      tls:
        - hosts:
            - immich.fancywhale.ca
          secretName: immich-fancywhale-ca-tls
image:
  tag: v1.74.0 # renovate: datasource=docker depName=altran1502/immich-server versioning=regex:^v(?<major>\d+)\.(?<minor>\d+).(?<patch>\d+)$
immich:
  persistence:
    library:
      existingClaim: photos
```

### Reproduction steps

```bash
1. Create album with over 100GB of files
2. Click download
3. Check the banner:
![CleanShot 2023-08-23 at 13 51 22](https://github.com/immich-app/immich/assets/10549675/83fdc39d-a6a0-411d-adfb-136bcb1c17f0)
4. Wait a long while after 100% hits. 
5. Check the actual download coming in:
![CleanShot 2023-08-23 at 13 33 09](https://github.com/immich-app/immich/assets/10549675/e535727f-8442-421b-a7c2-780cd79dedd5)
```
