### ISSUE TITLE
[BUG] immich_microservices throws an error exception

### ISSUE THREAD

**Issue by LeibNici** [immich-app/immich#3915]
### The bug

immich_microservices     | [Nest] 8  - 08/30/2023, 3:18:49 AM   ERROR [JobService] Unable to run job handler: SyntaxError: Unexpected token I in JSON at position 0
immich_microservices     | [Nest] 8  - 08/30/2023, 3:18:49 AM   ERROR [JobService] SyntaxError: Unexpected token I in JSON at position 0
immich_microservices     |     at JSON.parse (<anonymous>)
immich_microservices     |     at parseJSONFromBytes (node:internal/deps/undici/undici:6662:19)
immich_microservices     |     at successSteps (node:internal/deps/undici/undici:6636:27)
immich_microservices     |     at node:internal/deps/undici/undici:1236:60
immich_microservices     |     at node:internal/process/task_queues:140:7
immich_microservices     |     at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
immich_microservices     |     at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     | [Nest] 8  - 08/30/2023, 3:18:49 AM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "6670381b-a3d2-45b5-9289-ff18d5c13951",
immich_microservices     |   "source": "upload"
immich_microservices     | }
immich_microservices     | 
immich_microservices     |

### The OS that Immich Server is running on

debian

### Version of Immich Server

v1.76.0

### Version of Immich Mobile App

未使用

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=X
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.docker compose up -d
2.create new user
3.login by new user
4.upload photos
5.docker compose logs -f --tail=30
```
