### ISSUE TITLE
[BUG] machineLearning.url must be a URL address (Immich Server Error)

### ISSUE THREAD

**Issue by Vyerni** [immich-app/immich#3927]
### The bug

With the implementation of v1.76 and the ability to adjust Facial Recognition settings, I went to just slightly lower the min detection score to see what different results I would get. 

Opening "Machine Learning Settings" > Facial Recognition > Lowering score, and pressing save returns an error message saying "machineLearning.url must be a URL address (Immich Server Error)" without having changed it. 

Machine Learning url is: http://immich_machine_learning:3003 and has been working the entire time previously, at least, as far as I know. 

### The OS that Immich Server is running on

Debian11

### Version of Immich Server

v1.76+

### Version of Immich Mobile App

v1.76.0 build.99

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
networks:
  immich_isolated:
    name: immich_isolated
    ipam:
      config:
        - subnet: 172.20.0.80/28

services:
  immich_server:
    container_name: immich_server
    user: "1000:1000"
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file: .env
    depends_on:
      - immich_redis
      - immich_database
      - immich_typesense
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_server

  immich_microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION}
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file: .env
    environment:
      - TZ=Australia/Sydney
    depends_on:
      - immich_redis
      - immich_database
      - immich_typesense
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_microservices

  immich_machine_learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    user: "1000:1000"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./immich/cache:/cache
    env_file: .env
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_machine_learning

  immich_web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION}
    env_file: .env
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_web

  immich_typesense:
    container_name: immich_typesense
    user: "1000:1000"
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - ./immich/tsdata:/data
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_typesense
          - typesense

  immich_redis:
    container_name: immich_redis
    user: 1000:1000
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    volumes:
      - ./immich/redis:/data
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_redis

  immich_database:
    container_name: immich_postgres
    user: 1000:1000
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_database

  immich_proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich_server
      - immich_web
    restart: unless-stopped
    networks:
      immich_isolated:
        aliases:
          - immich_proxy
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=password
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

# This is the location where uploaded files are stored.
UPLOAD_LOCATION=Immich

TYPESENSE_API_KEY=typesense.api

LOG_LEVEL=simple

PUBLIC_LOGIN_PAGE_MESSAGE="Photos and Videos Backup Server"

IMMICH_WEB_URL=http://immich_web:3000
IMMICH_SERVER_URL=http://immich_server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich_machine_learning:3003

IMMICH_VERSION=v1.76.1
```

### Reproduction steps

```bash
1. Open Administration > Settings > Machine Learning Settings > Facial 
2. Lower the Min Detection score from 0.7 to 0.6
3. Press Save
4. Error appears in top right corner
```
