### ISSUE TITLE
[BUG] Issues with glibc version

### ISSUE THREAD

**Issue by Scorcerer** [immich-app/immich#3937]
### The bug

Hi!
I'm using immich with docker-compose (official images from ghcr.io) and after recent upgrade of my system where the DB actually is, I'm getting the following error in immich-server container:
`[Nest] 7  - 08/31/2023, 1:07:12 PM   ERROR [AssetService] Error uploading file QueryFailedError: could not load library "/usr/lib64/postgresql-15/lib64/uuid-ossp.so": /usr/lib64/libc.so.6: version GLIBC_2.38' not found (required by /usr/lib64/postgresql-15/lib64/uuid-ossp.so)`
This causes the whole thing not to work (the web app also throws mostly the same thing)
Can the docker image be somehow regenerated to use newer version of glibc please?

### The OS that Immich Server is running on

Gentoo current via docker

### Version of Immich Server

1.76.1, ID 0acf24976518

### Version of Immich Mobile App

1.74.0 build 97

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    env_file:
      - immich.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - immich-typesense
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=host.ip
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=<redacted>
REDIS_HOSTNAME=redis
REDIS_PORT=6379
REDIS_DBINDEX=1
UPLOAD_LOCATION=<redacted>
TYPESENSE_API_KEY=s<redacted>S
TYPESENSE_HOST=immich-typesense
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_VERSION=
```

### Reproduction steps

```bash
1. Start Immich
2. Try to login/backup/anything really
```
