### ISSUE TITLE
[BUG] Archived photos still showing in Explore/Places

### ISSUE THREAD

**Issue by apperrault** [immich-app/immich#4041]
### The bug

When I archive a photo, it gets hidden from my Photo Timeline like i expect, but when I go to the Explore tab, they are still showing up under Places.  This seems to me to be a bug

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS (Docker)

### Version of Immich Server

1.77.0

### Version of Immich Mobile App

1.77.0 build.100

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    environment:
      DB_HOSTNAME: postgresql-immich
      DB_USERNAME: pguser-immich
      DB_PASSWORD: XXXXXXXXXXXXXXXXXXXXX
      DB_DATABASE_NAME: pgdb-immich
      DB_PORT: 5432
      UPLOAD_LOCATION: /usr/src/app/upload
      IMMICH_WEB_URL: http://immich-web:3000
      IMMICH_SERVER_URL: http://immich-server:3001
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
      REDIS_HOSTNAME: redis
      REDIS_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXX'
      TYPESENSE_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXX
      TYPESENSE_HOST: typesense
    ports:
      - 3001:3001
    volumes:
      - ${DOCKERCONFDIR}/immich:/data
      - ${DOCKERSTORAGEDIR}:/storage
      - /media/USB2/photos:/usr/src/app/upload
      - /media/USB2/imported_photos:/media/USB2/imported_photos:ro
    depends_on:
      - redis
      - postgresql-immich
      - typesense
    restart: always
```

### Your .env content

```Shell
environment:
      DB_HOSTNAME: postgresql-immich
      DB_USERNAME: pguser-immich
      DB_PASSWORD: XXXXXXXXXXXXXXXXXXXXX
      DB_DATABASE_NAME: pgdb-immich
      DB_PORT: 5432
      UPLOAD_LOCATION: /usr/src/app/upload
      IMMICH_WEB_URL: http://immich-web:3000
      IMMICH_SERVER_URL: http://immich-server:3001
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
      REDIS_HOSTNAME: redis
      REDIS_PASSWORD: 'XXXXXXXXXXXXXXXXXXXXXXX'
      TYPESENSE_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXX
      TYPESENSE_HOST: typesense
```

### Reproduction steps

```bash
1. Take a new picture with my phone
2. Upload picture to immich
3. Locate picture in Timeline
4. select picture
5. choose Archive (photo disappears from timeline)
6. Navigate to Explore
7. Under places are, find the "location" that you took the picture
8. verify that the archived photo shows in this location (I would think it shouldn't)
...
```

### Additional information

Unless I am thinking this through incorrectly, I assume that are archived photo will not show up anywhere besides the Archive album
