### ISSUE TITLE
[BUG] After adding photos to new album, current album is renamed to newly created album

### ISSUE THREAD

**Issue by Cantello** [immich-app/immich#4065]
### The bug

I had my photos organised in folders by year-month, which I have now imported into Immich and I am now going through each monthly album and create 'event albums' out of this. However, when I am in folder, say "2014-07", find several photos there that correspond to an event, I select them, choose "Add to album" from the plus sign (web interface), type in the new album name (e.g. "2014 Birthday Aunt Cleo". The current album, that was named "2014-07" before is now renamed to the new name and when I delete the current album, the supposedly newly created album is deleted and the one that I originally wanted to delete ("2014-07") is still present.

### The OS that Immich Server is running on

Debian 11, Docker

### Version of Immich Server

1.77.0

### Version of Immich Mobile App

1.76.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3'

services:
 
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - /opt/immich/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - immich_redis
      - immich_database
      - typesense
    restart: unless-stopped

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - /opt/immich/thumbs:/usr/src/app/upload/thumbs
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - immich_redis
      - immich_database
      - typesense
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  immich-web:
    container_name: immich-web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: unless-stopped

  immich_redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped

  immich_database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/immich/database/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - 2283:8080
    environment:
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    depends_on:
      - immich-server
      - immich-web
    restart: unless-stopped

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - tsdata:/data
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/Photos/immich

# The Immich version to use. 
IMMICH_VERSION=release

# Connection secrets for postgres and typesense.
TYPESENSE_API_KEY=random-secret-key
DB_PASSWORD=postgres

# The values below this line do not need to be changed
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Import folders of structure yyyy-mm into Immich via immich-cli
2. Select multiple photos in yyyy-mm album in Immich on web interface
3. Add selected photos to new album
4. Delete the current album (Immich says that the album you want to delete is the newly created album, even though I did not switch albums)
5. If album was deleted, there is no album with the newly created name, only the previous album (yyyy-mm) that I wanted to delete
```
