### ISSUE TITLE
[BUG] Image description missing on shared album

### ISSUE THREAD

**Issue by joeShuff** [immich-app/immich#4073]
### The bug

I have added descriptions to images in my library. Then I created a share link for the library (including all perms, exif, upload, download). But the images don't have a description when viewing that shared album. For guests it shows nothing, for owner it shows a blank field.

In this picture we have:
Left: Asset owner just on immich home page
Middle: Anonymous guest viewing shared album
Right: Asset owner viewing shared album

![image](https://github.com/immich-app/immich/assets/15524362/88dc8487-f4e6-4426-9d77-3a5c5af7bcc8)

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.77.0

### Version of Immich Mobile App

v1.77.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always


  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    command: [ "python", "src/main.py" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: ghcr.io/immich-app/immich-web:release
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data

    logging:
      driver: none
    volumes:
      - tsdata:/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/hdd/media/Photos
LOG_LEVEL=simple
JWT_SECRET=<redacted>
TYPESENSE_API_KEY=<api-key>
```

### Reproduction steps

```bash
1. Add a description to an image
2. Add that image to an album and create a share link.
3. Access the album via that link anonymously and the image has no description
```
