### ISSUE TITLE
[BUG] Immich External Library not recognising saved external path

### ISSUE THREAD

**Issue by apat183** [immich-app/immich#4183]
### The bug

I have the following path set in the external library settings. I have saved it, and even restarted container.

<img width="772" alt="Screenshot 2023-09-23 at 9 48 57 AM" src="https://github.com/immich-app/immich/assets/7892604/d6a8f329-104f-47de-88f1-16fee3dbd227">

But when I refresh lib or scan, I get the following log item in the immich microservices container. 
```
[Nest] 7  - 09/23/2023, 9:46:41 AM    WARN [LibraryService] User has no external path set, cannot refresh library
```
Not sure why it's not recognising the external path saved. 

### The OS that Immich Server is running on

Ubuntu Server 22.10 (but container)

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${PHOTOS}/Photos/Backup:/usr/src/app/upload
      - ${PHOTOS}/Photos/Camera:/mnt/media/Camera:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${PHOTOS}/Photos/Backup:/usr/src/app/upload
      - ${PHOTOS}/Photos/Camera:/mnt/media/Camera:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
Create external lib
Add path
Save
Click refresh/scan lib
```
