### ISSUE TITLE
[BUG] Importing photos from new created external library not working

### ISSUE THREAD

**Issue by eeezae** [immich-app/immich#4185]
### The bug

I followed the steps outlined in the documentation at https://immich.app/docs/features/libraries to mount the host machine's folder to the immich Docker server and microservices. 

And then I configured the desired import path in the web interface via admin. 
<img width="792" alt="image" src="https://github.com/immich-app/immich/assets/34007837/978199a6-79c3-45c4-a046-5f241e20ac27">
However, when I click the SCAN button, nothing happens, and there are neither relative logs nor any indication of activity in the server and microservices.
 
Check if mounting success to docker container:
```
docker exec -it Immich-MICROSERVICES ls /volume1/homes/eeezae/Photos/PhotoLibrary/extra/potrait
```
Also Checked server:
```
docker exec -it Immich-SERVER ls /volume1/homes/eeezae/Photos/PhotoLibrary/extra/potrait
```

Both results:
```
 107-108.jpg   118.jpg	     13.jpg	       14.jpg	     2.jpg    29.jpg	  38.jpg      49-50.jpg   6.jpg       70.jpg	  8.jpg       9.jpg	  99-100.jpg
 109-110.jpg   119-120.jpg   130.jpg	       140.jpg	     21.jpg   3.jpg	  39-40.jpg   5.jpg	  61-62.jpg   71.jpg	  80.jpg      90.jpg	  @eaDir
 111.jpg       12.jpg	     131.jpg	       141-142.jpg   22.jpg   30.jpg	  4.jpg       51-52.jpg   63.jpg      72.jpg	  81-82.jpg   91.jpg	 ''$'\345\206\205\345\260\201\351\235\242''A.jpg'
 112.jpg       121-122.jpg   132.jpg	       143.jpg	     23.jpg   31-32.jpg   41.jpg      53.jpg	  64.jpg      73.jpg	  83-84.jpg   92.jpg	 ''$'\345\206\205\345\260\201\351\235\242''B.jpg'
 113.jpg       123.jpg	     133.jpg	       144.jpg	     24.jpg   33.jpg	  42.jpg      54.jpg	  65-66.jpg   74.jpg	  85.jpg      93-94.jpg  ''$'\347\211\271\345\205\270''.jpg'
 114.jpg       124.jpg	     134.jpg	       145.jpg	     25.jpg   34.jpg	  43.jpg      55-56.jpg   67.jpg      75.jpg	  86.jpg      95.jpg
 115.jpg       125-126.jpg   135-136-137.jpg   15.jpg	     26.jpg   35.jpg	  44.jpg      57.jpg	  68.jpg      76.jpg	  87.jpg      96.jpg
 116.jpg       127-128.jpg   138.jpg	       16-17.jpg     27.jpg   36.jpg	  45-46.jpg   58.jpg	  69.jpg      77-78.jpg   88.jpg      97.jpg
 117.jpg       129.jpg	     139.jpg	       19-20.jpg     28.jpg   37.jpg	  47-48.jpg   59-60.jpg   7.jpg       79.jpg	  89.jpg      98.jpg
```

When clicking library scan btn and check Immich-MICROSERVICES logs:
```
root@Bear~# docker logs --tail 20 Immich-MICROSERVICES
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +3ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +86ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] InfraModule dependencies initialized +3ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] DomainModule dependencies initialized +3ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized +1ms
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [MetadataExtractionProcessor] Reverse geocoding is enabled
[Nest] 8  - 09/23/2023, 8:40:52 AM     LOG [MetadataExtractionProcessor] Initializing Reverse Geocoding
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [MetadataExtractionProcessor] Reverse Geocoding Initialized
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [SearchService] Running bootstrap
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [TypesenseRepository] Schema up to date: assets/assets-v8
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [TypesenseRepository] Schema up to date: albums/albums-v2
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [TypesenseRepository] Schema up to date: faces/faces-v1
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [TypesenseRepository] Alias mapping: [{"collection_name":"faces-v1","name":"faces"},{"collection_name":"albums-v2","name":"albums"},{"collection_name":"assets-v8","name":"assets"}]
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [TypesenseRepository] Collections needing migration: {"assets":false,"albums":false,"faces":false}
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [NestApplication] Nest application successfully started +13ms
[Nest] 8  - 09/23/2023, 8:41:09 AM     LOG [ImmichMicroservice] Immich Microservices is listening on http://[::1]:3002 [v1.79.1] [PRODUCTION]
```

And Immich-SERVER logs:
```
root@Bear:~# docker logs --tail 20 Immich-SERVER
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [TypesenseRepository] Schema up to date: albums/albums-v2
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [TypesenseRepository] Schema up to date: faces/faces-v1
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [TypesenseRepository] Alias mapping: [{"collection_name":"faces-v1","name":"faces"},{"collection_name":"albums-v2","name":"albums"},{"collection_name":"assets-v8","name":"assets"}]
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [TypesenseRepository] Collections needing migration: {"assets":false,"albums":false,"faces":false}
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [AppService] Feature Flags: {
  "clipEncode": true,
  "facialRecognition": true,
  "tagImage": true,
  "map": true,
  "sidecar": true,
  "search": true,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false
}
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [NestApplication] Nest application successfully started +5ms
[Nest] 9  - 09/23/2023, 8:40:52 AM     LOG [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.79.1] [PRODUCTION]
```

### The OS that Immich Server is running on

Synology 7.1

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    image: altran1502/immich-server:release
    command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/homes:/volume1/homes:ro
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started
      typesense:
        condition: service_started

  immich-microservices:
    image: altran1502/immich-server:release
    command: ["start-microservices.sh"]
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
      - /volume1/homes:/volume1/homes:ro
    restart: on-failure:5
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started
      typesense:
        condition: service_started
```

### Your .env content

```Shell
...
```

### Reproduction steps

```bash
1.Mount Docker Volumes and restart
2.Set External Path
3.Edit Import Paths and Save
4.Refresh and Click on Scan Library Files
...
```

**Comment by Cebrain** [comment]
Did you also add the path to the User and Set an External Path?

![image](https://github.com/immich-app/immich/assets/78339531/76e64f46-4143-4b2a-908f-d5e93fa5cce2)

**Comment by eeezae** [comment]
> Did you also add the path to the User and Set an External Path?
> 
> ![image](https://user-images.githubusercontent.com/78339531/270093727-76e64f46-4143-4b2a-908f-d5e93fa5cce2.png)

Yes, I have added the path to the User directory and set an external path.

<img width="495" alt="image" src="https://github.com/immich-app/immich/assets/34007837/3dfd0dd4-3f4c-4414-86fe-b034d17c4d66">

**Comment by mckayc** [comment]
I have basically the exact same issue.

Here is my docker compose:

```
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/Media/Photos:/mnt/media/photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /srv/dev-disk-by-uuid-c86d7d16-7af6-4a4d-bc27-0aace5fb8074/Media/Photos:/mnt/media/photos:ro
```

And here is my library path:
![image](https://github.com/immich-app/immich/assets/3774563/0806572d-1734-46e6-8f35-17558567dcc5)

When I scan the library nothing at all appears to happen. I am not sure where to check logs.

(P.S. I am BEYOND thrilled that you guys added this feature. Super excited to use it. Keep up the great work!)
