### ISSUE TITLE
[BUG] Creation Time of Fujifilm JPG file is parsed incorrectly from EXIF

### ISSUE THREAD

**Issue by bbieberle** [immich-app/immich#4189]
### The bug

Hello all,

photos i Upload from my Fujifilm camera are always ordered incorrectly in my timeline. I investigated a little and i seems that the EXIF date is somehow parsed incorrectly for those files. 
The timezone is somehow UTC+9:17 (??) on thw web. On mobile the timezone is not displayed but the time is off.

Thanks in advance, love your work <3

### Web
![Image](https://i.imgur.com/RIXN6Ta.png)

### Mobile
![Image](https://i.imgur.com/k5UIciN.jpeg)

### EXIF dump of the file in question
```text
ExifTool Version Number         : 12.55
File Name                       : DSCF4107.JPG
Directory                       : F:/DCIM/104_FUJI
File Size                       : 17 MB
File Modification Date/Time     : 2023:09:23 10:09:20+02:00
File Access Date/Time           : 2023:09:23 10:09:20+02:00
File Creation Date/Time         : 2023:09:23 10:09:20+02:00
File Permissions                : -rw-rw-rw-
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : FUJIFILM
Camera Model Name               : X100V
Orientation                     : Horizontal (normal)
X Resolution                    : 72
Y Resolution                    : 72
Resolution Unit                 : inches
Software                        : Digital Camera X100V Ver2.13
Modify Date                     : 2023:09:23 10:09:17
Artist                          : B. BIEBERLE
Y Cb Cr Positioning             : Co-sited
Copyright                       : B. BIEBERLE
Exposure Time                   : 1/20
F Number                        : 2.0
Exposure Program                : Aperture-priority AE
ISO                             : 6400
Sensitivity Type                : Standard Output Sensitivity
Exif Version                    : 0230
Date/Time Original              : 2023:09:23 10:09:17
Create Date                     : 2023:09:23 10:09:17
Components Configuration        : Y, Cb, Cr, -
Compressed Bits Per Pixel       : 4.8
Shutter Speed Value             : 1/21
Aperture Value                  : 2.0
Brightness Value                : 0.74
Exposure Compensation           : +1.67
Max Aperture Value              : 2.0
Metering Mode                   : Multi-segment
Light Source                    : Daylight Fluorescent
Flash                           : No Flash
Focal Length                    : 23.0 mm
Version                         : 0130
Quality                         : FINE
White Balance                   : Daylight Fluorescent
Saturation                      : +2 (high)
White Balance Fine Tune         : Red -40, Blue +80
Noise Reduction                 : -4 (weakest)
Clarity                         : -4
Fuji Flash Mode                 : Not Attached
Flash Exposure Comp             : 0
Focus Mode                      : Auto
AF Mode                         : No
Focus Pixel                     : 2249 1645
AF-S Priority                   : Release
AF-C Priority                   : Release
Focus Mode 2                    : AF-S
Pre AF                          : Off
AF Area Mode                    : Wide/Tracking
AF Area Point Size              : n/a
AF Area Zone Size               : n/a
AF-C Setting                    : Set 1 (multi-purpose)
AF-C Tracking Sensitivity       : 2
AF-C Speed Tracking Sensitivity : 0
AF-C Zone Area Switching        : Auto
Slow Sync                       : Off
Picture Mode                    : Aperture-priority AE
Exposure Count                  : 1
Shadow Tone                     : 0 (normal)
Highlight Tone                  : -2 (soft)
Digital Zoom                    : 0
Lens Modulation Optimizer       : On
Grain Effect Roughness          : Strong
Color Chrome Effect             : Strong
Grain Effect Size               : Small
Crop Mode                       : n/a
Color Chrome FX Blue            : Weak
Shutter Type                    : Mechanical
Auto Bracketing                 : Off
Sequence Number                 : 0
Drive Mode                      : Single
Drive Speed                     : n/a
Blur Warning                    : Blur Warning
Focus Warning                   : Good
Exposure Warning                : Good
Dynamic Range                   : Standard
Film Mode                       : F1b/Studio Portrait Smooth Skin Tone (Astia)
Dynamic Range Setting           : Manual
Development Dynamic Range       : 400
Image Generation                : Original Image
Image Count                     : 4245
Flicker Reduction               : On (0x3130)
Fuji Model                      : X100V_0200
Fuji Model 2                    : X100V_0200
Faces Detected                  : 1
Face Positions                  : 229 359 530 661
Num Face Elements               : 1
Face Element Types              : Face
Face Element Positions          : 229 359 530 661
User Comment                    : 
Flashpix Version                : 0100
Color Space                     : sRGB
Exif Image Width                : 6240
Exif Image Height               : 4160
Interoperability Index          : R98 - DCF basic file (sRGB)
Interoperability Version        : 0100
Focal Plane X Resolution        : 2660
Focal Plane Y Resolution        : 2660
Focal Plane Resolution Unit     : cm
Sensing Method                  : One-chip color area
File Source                     : Digital Camera
Scene Type                      : Directly photographed
Custom Rendered                 : Normal
Exposure Mode                   : Auto
Scene Capture Type              : Standard
Sharpness                       : Soft
Subject Distance Range          : Unknown
Serial Number                   : 31M50196
PrintIM Version                 : 0250
Compression                     : JPEG (old-style)
Thumbnail Offset                : 3792
Thumbnail Length                : 8669
Rating                          : 0
Preview Image Width             : 640
Preview Image Height            : 480
Preview Image                   : (Binary data 42690 bytes, use -b option to extract)
Image Width                     : 6240
Image Height                    : 4160
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:2 (2 1)
Aperture                        : 2.0
Image Size                      : 6240x4160
Megapixels                      : 26.0
Preview Image Size              : 640x480
Scale Factor To 35 mm Equivalent: 1.5
Shutter Speed                   : 1/20
Thumbnail Image                 : (Binary data 8669 bytes, use -b option to extract)
Circle Of Confusion             : 0.020 mm
Field Of View                   : 54.0 deg
Focal Length                    : 23.0 mm (35 mm equivalent: 35.3 mm)
Hyperfocal Distance             : 13.51 m
Light Value                     : 0.3
```

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your Helmrelease

```YAML
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-release
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: immich
  releaseName: immich-release
  chart:
    spec:
      version: 0.1.1
      chart: immich 
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: immich-secret
      valuesKey: jwtSecret
      targetPath: common_env.JWT_SECRET
    - kind: Secret
      name: immich-secret
      valuesKey: dbPassword
      targetPath: common_env.DB_PASSWORD
    - kind: Secret
      name: immich-secret
      valuesKey: dbPassword
      targetPath: postgresql.global.postgresql.auth.password
  values:
    image:
      tag: v1.79.1
    common_env:
        REDIS_HOSTNAME: '{{ printf "%s-redis-master" (include "common.names.fullname" .) }}'
        DB_HOSTNAME: '{{ include "common.names.name" . }}-postgresql'
        DB_USERNAME: immich
        DB_DATABASE_NAME: immich
        DISABLE_REVERSE_GEOCODING: true
        ENABLE_MAPBOX: false
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            database: immich
      primary:
        resources:
          requests:
            cpu: 100m
    redis:
      enabled: true

    immich:
      persistence:
        library:
          existingClaim: immich-data
    
    typesense:
      enabled: true
      persistence:
        tsdata:
          enabled: true  
          storageClass: localnvme
          size: 5Gi
      image:
        tag: 0.24.1

    machine-learning:
      enabled: true
      persistence:
        cache: 
          enabled: true
          storageClass: localnvme

    proxy:
      ingress:
        main:
          enabled: true
          primary: enabled
          hosts:
            - host: example.com
              paths:
                - path: "/"
          tls:
            - hosts:
                - example.com
              secretName: tls-immich-ingress
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-issuer
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect@kubernetescrd, traefik-security-headers@kubernetescrd
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1. Take fuji photo
2. upload
3. wrong datetime on web and mobile
```
