### ISSUE TITLE
[BUG] Error when viewing map on web

### ISSUE THREAD

**Issue by dankozlowski1** [immich-app/immich#4195]
### The bug

When I click on the Map in the web, it shows 3 circles, containing about 3,000 photos total. However, I have about 70,000 photos in my library, most of which were taken on cell phones and therefore have latitude/longitude coordinates. Additionally, after a few moments, the map appears to become unresponsive and clicking any button or link has no affect.

To investigate, I opened the console in developer tools and found the following error.

index.8e9d6492.js:4 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'lat')
    at Object.project (index.8e9d6492.js:4:14552)
    at Object.latLngToPoint (index.8e9d6492.js:4:13160)
    at e.project (index.8e9d6492.js:4:38053)
    at e._addLayer (index.8e9d6492.js:4:165524)
    at e.<anonymous> (index.8e9d6492.js:4:155265)
    at e.addLayers (index.8e9d6492.js:4:155706)
    at As.k.$$.update (index.8e9d6492.js:4:187620)
    at It (boolean_attributes.1a147532.js:4:1732)
    at Gt (boolean_attributes.1a147532.js:4:1463)

![Immich Error](https://github.com/immich-app/immich/assets/144633666/2340c165-ad9d-45a3-b143-00b5bdecd5be)

### The OS that Immich Server is running on

Ubuntu 20.04.6 LTS

### Version of Immich Server

1.79.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/Documents/Pictures:/mnt/media/Pictures/External:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/media/Documents/Pictures:/mnt/media/Pictures/External:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d>
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/enviro>

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/media/Pictures/Backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Navigate to Immich.
2. Click on Map.
3. Error will immediately appear in the dev console.
```

### Additional information

This is a new instance of Immich that I recently spun up to use the External Libraries feature. All of these photos have been loaded using that tool.
