### ISSUE TITLE
[BUG] Unusable performance on Android with large photo libraries

### ISSUE THREAD

**Issue by Tom-GitLab** [immich-app/immich#4244]
### The bug

My wife and I both have the exact same phone (Android 13, Samsung Galaxy S20). However, our app experience with the photo library differs greatly. On my phone, it's working flawlessly. I have a photo library of about ~3000 photos. On my wife's phone, it's unusable. She has over 60,000 photos, and it seems whenever the app is launched, it has to load for at least 5 minutes before it becomes somewhat responsive. During this time, she will have the loading icon over the cloud in the upper-right corner for the entire 5 minutes.

While it's loading, the app experience is that it takes about 60 seconds for anything to respond, such as navigating to the Sharing Tab, tapping on an Album, or tapping on any photo, which would take minutes to complete.

I have attempted uninstalling/clearing app data and reinstalling the application. I suspect the difference in our user experience is that my wife has such a massive photo library that it is causing this behavior.

### The OS that Immich Server is running on

Debian 11 via Docker

### Version of Immich Server

1.79.1

### Version of Immich Mobile App

1.79.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file: stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file: stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /home/tom/docker_volumes/immich/model-cache:/cache
    env_file: stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file: stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - /home/tom/docker_volumes/immich/tsdata:/data
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /home/tom/docker_volumes/immich/pgdata:/var/lib/postgresql/data
    env_file: stack.env
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}

    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
```

### Your .env content

```Shell
DB_DATABASE_NAME=immich
DB_USERNAME=postgres
DB_PASSWORD=<secret>
DB_HOSTNAME=immich_postgres
UPLOAD_LOCATION=<secret>
TYPESENSE_API_KEY=<secret>
REDIS_HOSTNAME=immich_redis
IMMICH_VERSION=v1.79.1
```

### Reproduction steps

```bash
1. Open Mobile Application on Android with a photo library in excess of 60,000 photos.
2. Application is very slow to respond for the first several minutes.
```
