### ISSUE TITLE
[BUG] Problem by deploying Immich for the first time in Portainer

### ISSUE THREAD

**Issue by shahram7** [immich-app/immich#4259]
### The bug

Hi everyone, I've tried many different things at least right now i see that the immich server runs green

```
Request #1695823213211: Sleeping for 4s and then retrying request...
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [TypesenseRepository] Schema up to date: assets/assets-v8
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [TypesenseRepository] Schema up to date: albums/albums-v2
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [TypesenseRepository] Schema up to date: faces/faces-v1
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [TypesenseRepository] Alias mapping: [{"collection_name":"faces-v1","name":"faces"},{"collection_name":"albums-v2","name":"albums"},{"collection_name":"assets-v8","name":"assets"}]
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [TypesenseRepository] Collections needing migration: {"assets":false,"albums":false,"faces":false}
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [AppService] Feature Flags: {
  "clipEncode": true,
  "facialRecognition": true,
  "tagImage": true,
  "map": true,
  "sidecar": true,
  "search": true,
  "oauth": false,
  "oauthAutoLaunch": false,
  "passwordLogin": true,
  "configFile": false
}
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [NestApplication] Nest application successfully started +7ms
[Nest] 7  - 09/27/2023, 2:00:25 PM     LOG [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.79.1] [PRODUCTION] 
```

But I am still not able to run the immich
![image](https://github.com/immich-app/immich/assets/34509793/09b45013-5782-48e0-84b0-6aa461f966cc)

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.79.1

### Version of Immich Mobile App

1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
    #   Make sure these values get passed through from the env file
       - IMMICH_SERVER_URL
       - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/qnas/Immich
IMMICH_VERSION=v1.79.1
TYPESENSE_API_KEY=IAMNOTSUREIFTHISISGOINGTOWORK
DB_PASSWORD=removed
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
IMMICH_SERVER_URL=http://192.168.178.100:2283
IMMICH_WEB_URL=https://immich.mydomain.com
```

### Reproduction steps

```bash
trying to deploy the immich for the first time
```

### Additional information

I've tried with this changes in the service proxy service, but it didnt help

```
  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    environment:
    #   Make sure these values get passed through from the env file
       IMMICH_SERVER_URL: ${IMMICH_SERVER_URL}
       IMMICH_WEB_URL: ${IMMICH_WEB_URL}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```
