### ISSUE TITLE
[BUG] Incorrect storage display size for Mac

### ISSUE THREAD

**Issue by Rihcus** [immich-app/immich#4318]
### The bug

Storage counter in home ui broken.

<img width="245" alt="image" src="https://github.com/immich-app/immich/assets/30292597/1d384a10-afc2-4b57-ba23-e83b2489f7d4">

My host mac has 256gb ssd and 1tb hard drive (usb)

The external 1tb hardrive contains the immich library and is using Mac OS Extended (Journaled) file system

Admin panal storage count is correct however:

<img width="928" alt="image" src="https://github.com/immich-app/immich/assets/30292597/4aba031e-9ce6-47b3-9810-07a9a8457c33">

### The OS that Immich Server is running on

macOS 12.6.2 21G320 x86_64

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [x] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Volumes/MACHD/PhotoLibrary/Library/Photos/Oneplus8/OP8_Camera_Backup/Camera:/mnt/media/Camera:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /Volumes/MACHD/PhotoLibrary/Library/Photos/Oneplus8/OP8_Camera_Backup/Camera:/mnt/media/Camera:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/Volumes/MACHD/PhotoLibrary/immich-upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Set up docker compose on macOS 12.6.2 21G320 x86_64 
2. Plug in an external usb hard drive (make sure its formated in Mac OS Extended (Journaled) file system).
3. Mount some external libraries to docker-compose.yml
4. Install immich and update the web ui accordingly
5. Run a library scan
6. Check the storage counter in the home ui and compare it to admin panal
...
```

### Additional information

Possibly related issues:
- https://github.com/docker/for-mac/issues/2136
- https://github.com/goharbor/harbor/pull/5695/files#diff-863faac4a7e2eea4d78a34dc31ce004d72d6578aead1cf569176de4b6f017d87R60-R66
