### ISSUE TITLE
[BUG] {"statusCode":500,"message":"Internal server error"}

### ISSUE THREAD

**Issue by alexsalex** [immich-app/immich#4328]
### The bug

The server web page is working grate. But iOS application cant log in and show the message:
`{"statusCode":500,"message":"Internal server error"}`

Before works grate, until I restart the compose...

Will provide any log by request, I don't know where to look for it... sorry

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.79.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: Immich-Server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - ./Immich.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.4

  immich-microservices:
    container_name: Immich-Microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - ./Immich.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.5

  immich-machine-learning:
    container_name: Immich-Machine-Learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - ./Immich.env
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.6

  immich-web:
    container_name: Immich-Web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - ./Immich.env
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.7

  typesense:
    container_name: Immich-Typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      - GLOG_minloglevel=1
    volumes:
      - ./tsdata:/data
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.8

  redis:
    container_name: Immich-Redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.9

  database:
    container_name: Immich-Postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - ./Immich.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.10

  immich-proxy:
    container_name: Immich-Proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      ovm_default:
        ipv4_address: 10.2.1.11

volumes:
  model-cache:

networks:
  ovm_default:
    external: true
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich-redis

#################################################################################### 
# Alternative Service Addresses - Optional 
# 
# This is an advanced feature for users who may be running their immich services on different hosts. 
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers. 
# Note: immich-microservices is bound to 3002, but no references are made 
#################################################################################### 
 
IMMICH_WEB_URL=http://10.2.1.7:3000 
IMMICH_SERVER_URL=http://10.2.1.4:3001 
IMMICH_MACHINE_LEARNING_URL=http://10.2.1.6:3003
```

### Reproduction steps

```bash
1.
2.
3.
...
```
