### ISSUE TITLE
[BUG] /etc/timezone mount not found

### ISSUE THREAD

**Issue by markeeisner** [immich-app/immich#4333]
### The bug

The docker compose changes to pass through the host timezones in #4313 will fail to start on almost all non Debian/Ubuntu systems.

The linux standard is for /etc/localtime to symlink to the relevant timezone. /etc/timezone is only used by Debian and only certain older packages use it anyway. The standard docker compose should only use /etc/localtime which will work for all systems and not cause errors for systems without an /etc/timezone file.

See [Stackexchange discussion](https://unix.stackexchange.com/questions/451709/timedatectl-set-timezone-doesnt-update-etc-timezone/451714#451714) for a better explaination.

### The OS that Immich Server is running on

Almalinux 

### Version of Immich Server

v1.81.0

### Version of Immich Mobile App

v1.81.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
...
services:
  server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    volumes:
      - /xxx:/usr/src/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
...
  microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "microservices"]
    volumes:
      - /xxx:/usr/src/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Update docker-compose.yml to add both timezone volumes from #4313
2. Bring up stack
3. server and microservices fail with a bind mount not found error
```
