### ISSUE TITLE
[BUG] Merge faces from 3-dot menu does not propogate through Immich after merging

### ISSUE THREAD

**Issue by Linecutterx** [immich-app/immich#4334]
### The bug

Merging faces does not fully update/refresh the database/cache of faces after the operation is complete. This allows for an offer to merge faces that are already merged. Graphical walk through attached.

[ImmichFacesDemo.pdf](https://github.com/immich-app/immich/files/12800831/ImmichFacesDemo.pdf)

### The OS that Immich Server is running on

Docker, on Debian

### Version of Immich Server

1.8.0

### Version of Immich Mobile App

1.8.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      #- GLOG_minloglevel=1
    volumes:
      #- tsdata:/data
      - /<redacted>/typesense:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      #PG_DATA: /var/lib/postgresql/data
    volumes:
      #- pgdata:/var/lib/postgresql/data
      - /<redacted>/postgres:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  #pgdata:
  model-cache:
  #tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=<redacted>
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=<redacted>
REDIS_HOSTNAME=<redacted>
UPLOAD_LOCATION=/<redacted>
LOG_LEVEL=simple
JWT_SECRET=<redacted>
PUBLIC_LOGIN_PAGE_MESSAGE=Another way to share my photos
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TYPESENSE_API_KEY=<redacted>
PUBLIC_IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_API_URL_EXTERNAL=/api
```

### Reproduction steps

```bash
Select a face that needs merging.
Select merge option.
Select second face (to merge) - with the same name in my case (I'm unsure if this element is important)
Agree to the irreversible merging
This directs you to a page with the merged faces
Clicking on the name gives you a dropdown with both of the original face groups. The top, default one, allows editing of the name.
Clicking the other leads to a dialog asking whether to merge the faces.
Accepting the offer to merge then fails to find the face (which has already been merged)
```
