### ISSUE TITLE
[BUG] Shared file security bug 1.81.1

### ISSUE THREAD

**Issue by AlexanderIlyanok** [immich-app/immich#4382]
### The bug

I shared one MOV, selected not to show metadata. Instead of empty info, app show full path in my external library. See screenshot.
![image](https://github.com/immich-app/immich/assets/1693942/171a20cd-7fca-48ba-b243-814ed65cfb7c)

### The OS that Immich Server is running on

Windows 10

### Version of Immich Server

1.81.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
...
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - d:/Photo:/mnt/media/archive:ro 

...
immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - d:/Photo:/mnt/media/archive:ro
```

### Your .env content

```Shell
Default from release.
```

### Reproduction steps

```bash
1. Set external library for some folder
2. Select MOV (may be any?) file to share
3. Turn off Show Metadata
4. Copy shared link and open somewhere
5. You will see, that full path of file is shown in info panel: "Metadata not loaded for /mnt/media/archive/2023/07/..../IMG_1888.MOV"
```

### Additional information

Etnoy comfired bug. https://discord.com/channels/979116623879368755/1159963526945849455
