### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by entr0p1** [immich-app/immich#4400]
### The bug

When starting the immich-web container, it doesn't launch the web server. The below lines loop in the container logs:

```
SyntaxError: Unexpected end of input
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:273:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
Node.js v20.8.0
file:///usr/src/app/build/shims.js:12806
	      throw new Ty
```

Sometimes the server will start after a minute or two of these errors, others I just have to keep restarting it manually until it eventually goes. I've tried re-creating the container, destroying the entire stack and recreating it (including all data), re-pulling the images, nothing I can think of resolves the problem.

### The OS that Immich Server is running on

Oracle Linux 8.8 (within Docker-CE 24.0.6)

### Version of Immich Server

1.81.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    environment:
      - IMMICH_MEDIA_LOCATION=./library
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=<REDACTED>
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - TYPESENSE_API_KEY=<REDACTED>
    volumes:
      - /data/container-data/immich/library:/usr/src/app/library
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    environment:
      - TZ=<REDACTED>
      - IMMICH_MEDIA_LOCATION=./library
      - DB_HOSTNAME=immich_postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=<REDACTED>
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immich_redis
      - TYPESENSE_API_KEY=<REDACTED>
    volumes:
      - /data/container-data/immich/library:/usr/src/app/library
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /data/container-data/immich/mlcache:/cache
    restart: unless-stopped

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    restart: unless-stopped
    environment:
      - IMMICH_SERVER_URL=http://immich-server:3001

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=<REDACTED>
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /data/container-data/immich/tsdata:/data
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    environment:
      POSTGRES_PASSWORD: <REDACTED>
      POSTGRES_USER: immich
      POSTGRES_DB: immich
    volumes:
      - /data/container-data/immich/pgsqldata:/var/lib/postgresql/data
    restart: unless-stopped

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      - IMMICH_WEB_URL=http://immich-web:3000
      - IMMICH_SERVER_URL=http://immich-server:3001
    ports:
      - 40006:8080
    depends_on:
      - immich-server
      - immich-web
    restart: unless-stopped
```

### Your .env content

```Shell
N/A - all variables are manually entered into the docker-compose yml
```

### Reproduction steps

```bash
Start the container, the error shows up immeadiately
```
