### ISSUE TITLE
[BUG] iOS Portrait photos breaking, converted to jpg

### ISSUE THREAD

**Issue by N0Klu3** [immich-app/immich#4406]
### The bug

iOS 17 on my 15 Pro Max the portrait phots are being converted to .jpg away from .heic

On my photos app, the portrait photos are still in .heic format, but when the images get uploaded to the Immich app it gets converted to FullSizeRender.jpg instead of the original filename and extension.

This is breaking the zoom functionality of the app when clicking the zoom button I get a ? in a blue box for all my portrait photos. This ONLY happens on the .jpg portrait converted images. All the others work perfectly fine too.

Some photos have 3 versions with slightly different ISO settings - I have no filters or anything applied other than just a portrait photo
eg: 
FullSizeRender.jpg 12 MP 3024 x 4032 1.3 MiB
ƒ/2.8 1/411 15.66 mm ISO 50
FullSizeRender.jpg 12 MP 3024 x 4032 1.3 MiB
ƒ/2.8 1/365 15.66 mm ISO 50
FullSizeRender.jpg 12 MP 3024 x 4032 1.2 MiB
ƒ/2.8 1/373 15.66 mm ISO 50

Sometimes its 2x 12 MP and 1x 24 MP

### The OS that Immich Server is running on

unRAID

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

v1.80.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/images

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take a Portrait photo - confirm its .heic format
2. Upload via mobile app
3. Check the web or app for the uploaded photo, and confirm its renamed to FullSizeRender.jpg
4. Try to use the Zoom functionality via the Web App
5. Some photos have 3 versions of the same photo with slightly different iso
```
