### ISSUE TITLE
[BUG] WEBMs get stuck in upload folder

### ISSUE THREAD

**Issue by quinnv903** [immich-app/immich#4416]
### The bug

I can't seem to properly upload .webm files anymore, they seem to upload fine, but i noticed they always end up in the upload/upload/[userId] directory, rather than upload/library/[userId] where everything else normally ends up. only have that issue with .webm, no other file type, it happens from mobile app and PC alike. 

I have immich running behind a reverse proxy, specifically nginx proxy manager. The file size is not the issue, since I am able to upload files larger than that, as long as they are a different file type.

Any idea what could be causing this? This started happening 1-2 weeks ago.

### The OS that Immich Server is running on

Unraid 6.11.5

### Version of Immich Server

v1.80.0

### Version of Immich Mobile App

v1.80.0 build .104

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:

    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${VAULT_DIR}/immich/upload:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - immich

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${VAULT_DIR}/immich/upload:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - immich

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - immich

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data

    volumes:
      - ${DOCKER_DIR}/immich/tsdata:/data
    restart: unless-stopped
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: unless-stopped
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${DOCKER_DIR}/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL

    depends_on:
      - immich-server
    restart: unless-stopped
    networks:
      - immich
      - proxy

networks:
  proxy:
    external: true
    name: proxy_net
  immich:
    name: immich_net
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TYPESENSE_API_KEY=[redacted]
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=false
DOCKER_DIR=/mnt/user/appdata/docker
VAULT_DIR=/mnt/user/vault
```

### Reproduction steps

```bash
1. upload a .webm file to immich
2. image appears without thumbnail (for a while only, after a couple hours the thumbnail does appear)
3. check directory and the upload folder contains the file you tried to upload in step 1, it doesn't show up in the library folder
```

### Additional information

I use portainer, which is why i use stack.env in my docker-compose.yml
