### ISSUE TITLE
[BUG] Mobile app backup issues

### ISSUE THREAD

**Issue by Digital39999** [immich-app/immich#4420]
### Mobile app backup issues and button state

I've been experiencing weird stuff while backing up my phone, firstly it got stuck at uploading **videos**, and on server side it started causing exponential file growth in /library/uploads folder, as shown here:
![uwUB9eRYM](https://github.com/immich-app/immich/assets/65065580/5d41c230-a3b5-4ba1-b552-1c15b9d06cd3)
![6AxKZ2SHM](https://github.com/immich-app/immich/assets/65065580/4a507edb-e938-4955-8964-7bdfd5d80da9)
(this one is few min before or later, sizes changed already)

It successfully backed up all my photos, but kept failing on videos, and also to note, all files in /uploads are videos generated by immich too:
![tnotAk9Iz](https://github.com/immich-app/immich/assets/65065580/a4f4ff19-8969-4b7f-b113-99e966b199b4)

It has random cpu spikes, but every time it happened i checked jobs and none was running, and i have few disabled too. Logs don't show any bugs or errors, all seems pretty normal.

And another bug is that when having backup page opened, and swiping on notifications, button state and upload progress resets for some reason:
https://github.com/immich-app/immich/assets/65065580/69d01a52-5a67-4306-aed7-8e4326813126

Related Discord threads is here: https://discord.com/channels/979116623879368755/1161292114513121381

### The OS that Immich Server is running on

Debian 12, Docker

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

v1.81.0 build.104

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
TYPESENSE_API_KEY=something_yes_i_changes_this
DB_PASSWORD=something_yes_i_changes_this_too
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Video and storage bug:
1. Turn background backup on(?)
2. Make it somehow upload videos, which are like few hundred megabytes.

Button and progress bug:
1. Scroll down to the end of backup page on mobile.
2. Turn background backup, and have backup ongoing.
3. Swipe down on notifications and observe "Start Upload" button.
```

### Additional information

Android Version: 13
One UI Version: 5.1
