### ISSUE TITLE
[BUG] Immich FPS higher than screen refresh rate

### ISSUE THREAD

**Issue by Superpiffer** [immich-app/immich#4468]
### The bug

I have an old phone (Xiaomi Mi 9T Pro) with an AOSP rom. The screen has 60Hz but for some reason the app tries to draw 70-80 fps, causing flickering and unwanted touch inputs (in the search form, every letter is pressed 2-3 times). I installed an app to check fps in realtime in an overlay window and Immich is the only app on my phone with this behaviour. 

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

v1.81.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    depends_on:
      - redis
      - database
      - typesense
    environment:
      - DB_HOSTNAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE_NAME
      - REDIS_HOSTNAME
      - TYPESENSE_API_KEY
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - photos_volume:/mnt/photos:ro
    networks:
      - default
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    depends_on:
      - redis
      - database
      - typesense
    environment:
      - DB_HOSTNAME
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE_NAME
      - REDIS_HOSTNAME
      - TYPESENSE_API_KEY
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - photos_volume:/mnt/photos:ro
    networks:
      - default
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    networks:
      - default
    restart: unless-stopped

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    networks:
      - default
    restart: unless-stopped

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1
    logging:
      driver: none
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: "/data"
    volumes:
      - ./tsdata:/data
    networks:
      - default
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6-alpine
    networks:
      - default
    volumes:
      - ./redis:/data
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped

  immich:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    depends_on:
      - immich-server
      - immich-web
    environment:
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    networks:
      - default
      - proxy
    labels:
      traefik.enable: "true"
      traefik.http.services.immich.loadbalancer.server.port: 8080
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  photos_volume:
    name: photos_volume
    driver_opts:
      type: nfs4
      o: addr=192.168.1.30,rw
      device: :/Multimedia/Personal/Photos
  upload_volume:
    name: upload_volume
    driver_opts:
      type: nfs4
      o: addr=192.168.1.30,rw
      device: :/Multimedia/Personal/Immich_upload
```

### Your .env content

```Shell
IMMICH_VERSION=v1.81.1
TZ=Europe/Rome

UPLOAD_LOCATION=upload_volume

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

TYPESENSE_API_KEY=abcdefghijklmnopqrstuvwxyz
```

### Reproduction steps

```bash
1. Open mobile app.
2. Click on something or write in the search bar.
```
