### ISSUE TITLE
[BUG] Presence of complex duration metadata in video causes extraction to fail

### ISSUE THREAD

**Issue by dfb** [immich-app/immich#4480]
### The bug

I have some video files that show up in the wrong location in the timeline (the problem happens both with uploading them into Immich as well as importing them via an external library). Interestingly, when I select one of the videos in Immich and then click the information icon, it shows the proper timestamp. For example, this file I added via an external library yesterday (Oct 13, 2023) and it shows up in the timeline as June 29, 2023, but the metadata shows the correct date:
![image](https://github.com/immich-app/immich/assets/739849/eb2554cf-d321-4833-8448-3490e4882e35)
Jun 29, 2023 is the lastmod on the file, so it looks like some part of Immich was able to read the date from the metadata, but the part that assigns it to a location in the timeline used the file lastmod instead.

When I told Immich to refresh the metadata, I noticed that immich_microservices was throwing an unhandled exception:
```
ERROR [JobService] Unable to run job handler (metadataExtraction/metadata-extraction): Error:
ERROR [JobService] Error: Invalid unit value [object Object]
    at asNumber (/usr/src/app/node_modules/luxon/build/node/luxon.js:1530:87)
    at normalizeObject (/usr/src/app/node_modules/luxon/build/node/luxon.js:1539:35)
    at Duration.fromObject (/usr/src/app/node_modules/luxon/build/node/luxon.js:2590:15)
    at MetadataService.getDuration (/usr/src/app/dist/domain/metadata/metadata.service.js:338:33)
    at MetadataService.handleMetadataExtraction (/usr/src/app/dist/domain/metadata/metadata.service.js:152:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/domain/job/job.service.js:109:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:346:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:531:24)
```

I added a log statement inside `getDuration` and it shows:
```
  LOG [MetadataService] {"Scale":0.0000111111111111111,"Value":6061440}
```

Using exiftool, I dumped any duration-related metadata tags:
```
Duration                        : 0:01:07
Preview Duration                : 0 s
Selection Duration              : 0 s
Track Duration                  : 0:01:07
Media Duration                  : 0:01:07
Track Duration                  : 0:01:07
Media Duration                  : 0:01:07
Duration Scale                  : 1.11111111111111e-005
Duration Value                  : 6061440
```

I was able to work around the problem by removing those tags:
```
./exiftool -XMP:DurationScale= -XMP:DurationValue= 20180118_223020.mp4
```
and then asking Immich to refresh the metadata.

### The OS that Immich Server is running on

Ubuntu 23.04

### Version of Immich Server

v1.81.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /ssd1/backed/GooglePhotos:/mnt/davejennie/GooglePhotos:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /ssd1/backed/GooglePhotos:/mnt/davejennie/GooglePhotos:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/ssd1/backed/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=****
DB_PASSWORD=****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Refresh metadata on files that have `XMP:DurationScale` and `XMP:DurationValue` metadata.
```

### Additional information

FWIW, all of the files that have this problem were originally very old AVI files that were then converted to MP4s using ffmpeg.
