### ISSUE TITLE
[BUG] Repair page not accessible

### ISSUE THREAD

**Issue by TheZoker** [immich-app/immich#4510]
### The bug

When I try to access the /admin/repair endpoint, I get this error:

![image](https://github.com/immich-app/immich/assets/1368405/67c2409f-1c81-4cf5-a33c-e6701e9137b3)

In the logs it looks like this:
```
2023/10/17 09:18:54 [error] 45#45: *708 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.3.102, server: , request: "GET /admin/repair/__data.json?x-sveltekit-invalidated=01 HTTP/1.1", upstream: "http://172.18.0.3:3000/admin/repair/__data.json?x-sveltekit-invalidated=01", host: "<removed>", referrer: "https://<removed>/admin/jobs-status"
2023/10/17 09:18:58 [error] 46#46: *723 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.3.102, server: , request: "GET /admin/repair HTTP/1.1", upstream: "http://172.18.0.3:3000/admin/repair", host: "photos.zkr.io", referrer: "https://<removed>/admin/jobs-status"
```

### The OS that Immich Server is running on

Proxmox Alpine Based LXC with docker

### Version of Immich Server

v1.82.0

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_server
    restart: always
    command: [ "start.sh", "immich" ]
    volumes:
      - /shared/nas/immich:/usr/src/app/upload
      - /shared/nas/photos:/mnt/media/nas:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich_microservices
    restart: always
    command: [ "start.sh", "microservices" ]
    volumes:
      - /shared/nas/immich:/usr/src/app/upload
      - /shared/nas/photos:/mnt/media/nas:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    environment:
#      - LOG_LEVEL=verbose
      - TZ=Europe/Berlin

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich_machine_learning
    restart: always
    volumes:
      - model-cache:/cache
    env_file:
      - .env

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    restart: always
    env_file:
      - .env

  typesense:
    image: typesense/typesense:0.24.1
    container_name: immich_typesense
    restart: always
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    image: postgres:14-alpine
    container_name: immich_postgres
    restart: always
    volumes:
      - ~/files/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}

  immich-proxy:
    image: ghcr.io/immich-app/immich-proxy:release
    container_name: immich_proxy
    restart: always
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 80:8080
    depends_on:
      - immich-server
      - immich-web

volumes:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<removed>
DB_PASSWORD=<removed>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Update to v1.82.0
2. Go to repair page
```
