### ISSUE TITLE
[BUG] different content shown between mobile app and webview

### ISSUE THREAD

**Issue by Igor01-Tech** [immich-app/immich#4526]
### The bug

Immich is running since a month now.

But today I recognized this all of a sudden: when I open up the mobile app, I only see one image (taken yesterday - maybe shortly after I updated server/app?).
But when I open up the webclient over my computer I see all of my thousands of images.

All images seem to be there - I can filter faces, places etc. But in the Mainview there is only one image and no time-line-scrollbar on the right side of the view..

### The OS that Immich Server is running on

OMV  6.9.1-1 (Shaitan) with Linux 6.1.0-0.deb11.11-amd64

### Version of Immich Server

v1.82.0

### Version of Immich Mobile App

v1.82.0 built.106

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_LOCATION}:/mnt/media/external_library:ro
      - ${EXTERNAL_LOCATION_SINA}:/mnt/media/external_library_sina:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_LOCATION}:/mnt/media/external_library:ro
      - ${EXTERNAL_LOCATION_SINA}:/mnt/media/external_library_sina:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION="/srv/dev-disk-by-uuid-779c2882-ebd5-419b-b9f2-b561d74d0a9d/immich_uploaddir"
IMMICH_VERSION=release
TYPESENSE_API_KEY=ksudhfiuehkfuhksjnuhoquhqoalaijoiajyoijoiajoigjgjdtzuhnbmv
DB_PASSWORD=lsdihfp983il23f89
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres34531
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
EXTERNAL_LOCATION="/srv/dev-disk-by-uuid-7abe35c3-116e-44af-80ff-634b63f5c119/privatefiles/lars/Fotos"
EXTERNAL_LOCATION_SINA="/srv/dev-disk-by-uuid-779c2882-ebd5-419b-b9f2-b561d74d0a9d/privatefiles_sina/Fotos"
```

### Reproduction steps

```bash
1. open the app
```
