### ISSUE TITLE
[BUG] Downloading from External Library results in corrupt files

### ISSUE THREAD

**Issue by tspirtle** [immich-app/immich#4547]
### The bug

When downloading an asset from an External Library, the resulting file is corrupt. The downloaded file size is identical to the original, but it is missing metadata and won't display in any photo viewers. The Download function results in a corrupt file on both the web and mobile app.

The assets are online, and they display properly in Immich. Right Click > Save As works fine, but that doesn't download the original file (and isn't an option in the mobile app).

Assets in the default library (uploaded with the Immich app natively) do not have this issue. 

I can only find 2 relevant log entries that coincide with the downloads:

immich_proxy log
```
2023/10/17 22:40:52 [warn] 47#47: *3112 upstream sent more data than specified in "Content-Length" header while reading upstream, client: 10.0.3.109, server: , request: "POST /api/asset/download/8aea94d6-3f76-4bfa-87f2-b971ee34e1a9 HTTP/1.1", upstream: "http://172.30.0.7:3001/asset/download/8aea94d6-3f76-4bfa-87f2-b971ee34e1a9", host: "redacted.com:2283", referrer: "http://redacted.com:2283/photos"
```

immich_server log
```
[Nest] 7  - 10/17/2023, 10:40:52 PM   ERROR [ExpressAdapter] Premature close
Error [ERR_STREAM_PREMATURE_CLOSE]: Premature close
    at new NodeError (node:internal/errors:406:5)
    at ServerResponse.onclose (node:internal/streams/end-of-stream:159:30)
    at ServerResponse.emit (node:events:526:35)
    at emitCloseNT (node:_http_server:1023:10)
    at Socket.onServerResponseClose (node:_http_server:278:5)
    at Socket.emit (node:events:526:35)
    at TCP.<anonymous> (node:net:337:12)
```

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/docs-mystuff/Photos:/mnt/docs-mystuff/Photos:ro
      - /mnt/docs-mystuff/Videos:/mnt/docs-mystuff/Videos:ro
      - /mnt/docs-partnerstuff/Photos:/mnt/docs-partnerstuff/Photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/docs-mystuff/Photos:/mnt/docs-mystuff/Photos:ro
      - /mnt/docs-mystuff/Videos:/mnt/docs-mystuff/Videos:ro
      - /mnt/docs-partnerstuff/Photos:/mnt/docs-partnerstuff/Photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload #removed in v1.62.0
      - /usr/src/docker/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /usr/src/docker/immich/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /usr/src/docker/immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
    restart: always
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=redacted
DB_PASSWORD=redacted
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/data/docker/immich
TYPESENSE_API_KEY=redacted
PUBLIC_LOGIN_PAGE_MESSAGE=redacted
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Add external library
2. Scan library
3. Attempt to download any photo or video from external library
```
