### ISSUE TITLE
[BUG] Database is full / Out of memory - Android

### ISSUE THREAD

**Issue by Allram** [immich-app/immich#4558]
### The bug

Getting alof of but the log is full of "Out of memory", "Database is full", "Catch all error: Null check operator used on a null value - Null check operator used on a null value" errors when i try to share a video from the Android app.

Used on:
Nothing Phone 2 (12GB ram, 6.5GB used while getting the errors)
Android 14

### The OS that Immich Server is running on

UnRaid 6.12.4 Docker compose

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0 build 106

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /tmp/Postgresql/postgresql/:/var/run/postgresql
      - /tmp/Redis/Redis/:/var/run/redis
      - /mnt/user/Drone/:/mnt/media/Vegard/drone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - typesense
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.17
    labels:
    - TZ=Europe/Oslo
    - "traefik.enable=true"
    - "traefik.http.routers.immich-api.entryPoints=https"
    - "traefik.http.services.immich-api.loadbalancer.server.port=3001"
    - "traefik.http.routers.immich-api.rule=Host(*REDACTED*) && Pathprefix(`/api`)"
    - "traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes=/api"
    - "traefik.http.routers.immich-api.middlewares=middlewares-secure-headers@file,service-immich-api-strip"
    #environment:
      #- TZ=Europe/Oslo
        

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: /mnt/apps/appdata/Immich/microservices/hwaccel.yml
      service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /tmp/Postgresql/postgresql/:/var/run/postgresql
      - /tmp/Redis/Redis/:/var/run/redis
      - /mnt/user/Drone/:/mnt/media/Vegard/drone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - typesense
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.18
   #environment:
      #- TZ=Europe/Oslo

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/apps/appdata/Immich/machine-learning:/cache
    env_file:
      - .env
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.30
    #environment:
      #- TZ=Europe/Oslo

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.16
    labels:
    - "TZ=Europe/Oslo"
    - "traefik.enable=true"
    - "traefik.http.routers.immich-web.entryPoints=https"
    - "traefik.http.services.immich-web.loadbalancer.server.port=3000"
    - "traefik.http.routers.immich-web.rule=Host(*REDACTED*)"
    - "traefik.http.routers.immich-web.middlewares=middlewares-secure-headers@file"
    #environment:
      #- TZ=Europe/Oslo

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      #- TZ=Europe/Oslo
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /mnt/apps/appdata/Immich/typesense:/data
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.10
        
  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      #- TZ=Europe/Oslo
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:2283
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      immich:
        ipv4_address: 192.168.30.23



networks:
  immich:
    name: br0.30
    external: true
```

### Your .env content

```Shell
# Database
DB_HOSTNAME=/var/run/postgresql
DB_USERNAME=immich
DB_PASSWORD=*REDACTED*
DB_DATABASE_NAME=immich
DB_PORT=0

# Typesense
# TYPESENSE
TYPESENSE_API_KEY=tedsadasdhg

# Redis
REDIS_HOSTNAME=localhost
REDIS_PORT=0
REDIS_DBINDEX=2
REDIS_PASSWORD=*REDACTED*
REDIS_SOCKET=/var/run/redis/redis.sock

# Upload File Config
LIBRARY_LOCATION=/mnt/user/Immich/
THUMBS_LOCATION=/mnt/apps/Immich-Cache/thumbs/
UPLOAD_LOCATION=/mnt/apps/Immich-Cache/upload/
PROFILE_LOCATION=/mnt/apps/Immich-Cache/profile/
VIDEO_LOCATION=/mnt/apps/Immich-Cache/encoded-video/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Public login message
PUBLIC_LOGIN_PAGE_MESSAGE="@Fladby Bildehosting"
```

### Reproduction steps

```bash
1. Try to share a video from the Android App
2. The app will load for a while (maybe download the asset? Even tho the asset exist on the phone)
3. Then you can share it, but the log is full of "Out of memory", "Database is full", "Catch all error: Null check operator used on a null value - Null check operator used on a null value" errors.
...
```
