### ISSUE TITLE
[BUG] Upload photos not shown

### ISSUE THREAD

**Issue by Glareascum** [immich-app/immich#457]
**Describe the bug**
I've started immich through podman. I've a centralized  database so  i configured  immich to point to my postgres host. 
Plus, I removed the container immich_machinelearning from docker-compose file since I don't need it. 

All start, I registered a user and accessed the main console. But then, when I upload a photo nothing happens, I don't see it from  immich, but I can see it on my disk. Am I missing something or  why this configuration has some problemm?

I have no error in container logs.

**Task List**

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my `docker-compose` file.
- [X] I have included my redacted `.env` file.
- [X] I have included information on my machine, and environment.

**To Reproduce**
1 . Open Immich
2. Upload a photo

**Expected behavior**
See the photo  in the web console

**Docker-compose file**
```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks: immich

  immich-microservices:
    container_name: immich_microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    user: 1000:984
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always
    networks: immich

  immich-web:
    container_name: immich_web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    environment:
      - PUID=1000
      - PGID=984
    env_file:
      - .env
    restart: always
    networks: immich

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 7900:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
    networks: immich

networks:
  immich:
    name: immich-network
```

**.env file**
```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=postgres
DB_USERNAME=immichuser
DB_PASSWORD=mypassword
DB_DATABASE_NAME=immich

# Optional Database settings:
DB_PORT=5432




###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=redis

# Optional Redis settings:
REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=





###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/mnt/immich




###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=mysupersecretstringthatnoonecanguess




###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=


####################################################################################
# WEB - Optional
####################################################################################

# Custom message on the login page, should be written in HTML form.
# For example VITE_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

VITE_LOGIN_PAGE_MESSAGE=
```

**System**
- Server Version: `1.21.1`
