### ISSUE TITLE
[BUG] Generating thumbs

### ISSUE THREAD

**Issue by piciuok** [immich-app/immich#4573]
### The bug

My library has 67840 photos and 4420 videos. App trying process all media but for now it showing me: 
![image](https://github.com/immich-app/immich/assets/26445888/64d91018-165a-490a-a656-e99f1e6df7ba)

So it's much more then my 77260 total media files. 

Process of generating thumbs run over 24h and count grow every few seconds. 
Could someone tell me that's ok? How generting works and how many files are generated? 
I using before Immich, Photoprism, and processing all thumb take less then 12 hours (each media file had up to 12 thumb files). 

btw. All videos converted by myself to mp4 h264 for web.

btw2. At end of writing that ticket immich show:
![image](https://github.com/immich-app/immich/assets/26445888/c4301904-2b2b-49a8-ad7b-cff69a95639b)

Total thumbs in upload/thumbs is 89844

### The OS that Immich Server is running on

Linux / QNAP

### Version of Immich Server

v.1.82.1

### Version of Immich Mobile App

v.1.82.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/CACHEDEV2_DATA/Fotografie:/mnt/media/Mateusz/Fotografie:ro
      - /share/CACHEDEV2_DATA/Wideo/NagraniaFonem:/mnt/media/Mateusz/Wideo:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /share/CACHEDEV2_DATA/Fotografie:/mnt/media/Mateusz/Fotografie:ro
      - /share/CACHEDEV2_DATA/Wideo/NagraniaFonem:/mnt/media/Mateusz/Wideo:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    environment:
      - NODE_OPTIONS=--max-old-space-size=10240
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /share/CACHEDEV3_DATA/DockerData/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always


  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /share/CACHEDEV3_DATA/DockerData/immich/typesense:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /share/CACHEDEV3_DATA/DockerData/immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    
networks:
  default:
    name: npm_private_net
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/CACHEDEV3_DATA/DockerData/immich/upload
IMMICH_VERSION=release
TYPESENSE_API_KEY=dummy
DB_PASSWORD=dummy
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Run whole stack and wait
2.
3.
...
```
