### ISSUE TITLE
[BUG] 500 error when logging in from mobile; no issues on other platforms

### ISSUE THREAD

**Issue by emteedubs** [immich-app/immich#4580]
### The bug

Everything was working fine until a recent upgrade of Immich stack to 1.82.1. Then all of a sudden my photos stopped showing up and I tried to log out and relogin the app. After logging out and trying to login (via email and not OAuth), I get an error message that says: "StatusCode:500; "Internal Server Error"

The corresponding error in my server log:

```
[Nest] 7  - 10/21/2023, 4:03:33 PM   ERROR [ExceptionsHandler] Unexpected token '<', "<!DOCTYPE "... is not valid JSON
10/21/2023
12:03:33 PM
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
10/21/2023
12:03:33 PM
    at JSON.parse (<anonymous>)
10/21/2023
12:03:33 PM
    at IncomingMessage.get (/usr/src/app/node_modules/openid-client/lib/helpers/request.js:153:30)
10/21/2023
12:03:33 PM
    at processResponse (/usr/src/app/node_modules/openid-client/lib/helpers/process_response.js:55:25)
10/21/2023
12:03:33 PM
    at Issuer.discover (/usr/src/app/node_modules/openid-client/lib/issuer.js:179:18)
10/21/2023
12:03:33 PM
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10/21/2023
12:03:33 PM
    at async AuthService.getOAuthClient (/usr/src/app/dist/domain/auth/auth.service.js:240:24)
10/21/2023
12:03:33 PM
    at async AuthService.generateConfig (/usr/src/app/dist/domain/auth/auth.service.js:141:22)
10/21/2023
12:03:33 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:28
10/21/2023
12:03:33 PM
    at async /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

My server is running behind Traefik. But none of those configs were changed and was working prior to the recent update. Not sure what's causing this error. I have no trouble logging in and out on desktop.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

v.1.82.1

### Version of Immich Mobile App

v1.82.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
### Immich -  is a high performance self-hosted photo and video backup solution
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
    environment:
      DB_HOSTNAME: immich_db
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
      TYPESENSE_HOST: immich_typesense
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
      SERVER_PORT: ${SERVER_PORT}
    depends_on:
      - immich_redis
      - immich_db
      - immich_typesense
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - ${DOCKERDIR}/appdata/immich/micro:/usr/src/app/.reverse-geocoding-dump
    environment:
      TZ: ${TZ}
      DB_HOSTNAME: immich_db
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LOG_LEVEL: ${LOG_LEVEL}
      TYPESENSE_HOST: ${TYPESENSE_HOST}
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_PORT: ${TYPESENSE_PORT}
      MICROSERVICES_PORT: ${MICROSERVICES_PORT}
    depends_on:
      - immich_redis
      - immich_db
      - immich_typesense
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${DOCKERDIR}/appdata/immich/cache:/cache
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${ENCODED_VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
    environment:
      MACHINE_LEARNING_PORT: ${MACHINE_LEARNING_PORT}
    depends_on:
      - immich_db
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-web:
    container_name: immich-web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    environment:
      PUBLIC_LOGIN_PAGE_MESSAGE: ${PUBLIC_LOGIN_PAGE_MESSAGE}
      PORT: ${PORT}
    depends_on:
      - immich-server
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich-proxy:
    container_name: immich-proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      # Make sure these values get passed through from the env file
      IMMICH_SERVER_URL: ${IMMICH_SERVER_URL}
      IMMICH_WEB_URL: ${IMMICH_WEB_URL}
      IMMICH_MACHINE_LEARNING_URL: ${IMMICH_MACHINE_LEARNING_URL}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      com.centurylinklabs.watchtower.monitor-only: "true"

  immich_typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1
    environment:
      TYPESENSE_API_KEY: ${TYPESENSE_API_KEY}
      TYPESENSE_DATA_DIR: /data
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DOCKERDIR}/appdata/immich/typesense:/data
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  immich_redis:
    container_name: immich_redis
    image: redis:6.2
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
    volumes:
      - ${DOCKERDIR}/appdata/immich/redis:/data
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  immich_db:
    container_name: immich_db
    image: postgres:14
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "immich", "-U", "immich"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      POSTGRES_PASSWORD_FILE: /run/secrets/immich_postgres_password
      POSTGRES_USER_FILE: /run/secrets/immich_postgres_user
      POSTGRES_DB_FILE: /run/secrets/immich_postgres_db
    secrets:
      - immich_postgres_password
      - immich_postgres_user
      - immich_postgres_db
    volumes:
      - ${DOCKERDIR}/appdata/immich/db:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_bridge
    labels:
      com.centurylinklabs.watchtower.enable: "false"
```

### Your .env content

```Shell
PUID=<<REDACTED>>
PGID=<<REDACTED>>
TZ=<<REDACTED>>

##### DIRECTORIES

DOCKERDIR=<<REDACTED>>

##### DOMAIN

DOMAIN=<<REDACTED>>

###################################################################################
#
# IMMICH ENV
#
###################################################################################

###################################################################################
# Upload Directory File Locations
#
# This is the location where uploaded files are stored.
# Used for:
# - immich-machine-learning
# - immich-microservices
# - immich-server
###################################################################################

# UPLOAD_LOCATION=absolute_location_on_your_machine_where_you_want_to_store_the_backup  ### DEFAULT saves to one directory, but below splits the library and data


LIBRARY_LOCATION=/<<REDACTED>>/shared/pictures/photos/
THUMBS_LOCATION=/<<REDACTED>>/docker/appdata/immich/upload/thumbs/
UPLOAD_LOCATION=/<<REDACTED>>/docker/appdata/immich/upload/upload/
PROFILE_LOCATION=/<<REDACTED>>/docker/appdata/immich/upload/profile/
ENCODED_VIDEO_LOCATION=/<<REDACTED>>/docker/appdata/immich/upload/encoded-video/

###################################################################################
# POSTGRS Database
###################################################################################
# NOTE: The following four database variables support Docker secrets by adding a *_FILE suffix to the variable name
# See the docker-compose documentation on secrets for additional details: https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets

DB_USERNAME=<<REDACTED>>
DB_DATABASE_NAME=<<REDACTED>>
DB_PASSWORD=<<REDACTED>>

###################################################################################
# Ports
###################################################################################
PORT=3000
# DB_PORT=5432
SERVER_PORT=3001
MICROSERVICES_PORT=3002
MACHINE_LEARNING_PORT=3003
TYPESENSE_PORT=8108

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=


###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=<<REDACTED>>
# TYPESENSE_ENABLED=false
TYPESENSE_HOST=immich_typesense



###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################


PUBLIC_LOGIN_PAGE_MESSAGE=

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

IMMICH_VERSION=release


####### Other environment Variables ##################################
####### Default=log; verbose, debug, log, warn, error
LOG_LEVEL=debug
```

### Reproduction steps

```bash
1.Enter my external domain address that is directed to Immich on mobile app
2.Click next on the app
3.
...
```
