### ISSUE TITLE
[BUG] Thumbnail and exif data missing

### ISSUE THREAD

**Issue by alexkiddddd** [immich-app/immich#4626]
### The bug

I am uploading my phone camera photos with the android app and sometimes the video is uploaded but on the web interface the video has no thumbnail and no exif info
![immich](https://github.com/immich-app/immich/assets/148880908/cc9a025b-af77-4c00-8605-fe5b7ac7875f)

### The OS that Immich Server is running on

QTS Container Station

### Version of Immich Server

v1.82.1

### Version of Immich Mobile App

v1.82.0 build.106

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

networks:
  default:
    driver: bridge
  npm_proxy:
    name: npm_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.89.0/24
        
services:
  immich-server:
    container_name: immich_server
    networks:
    - npm_proxy
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    user: 1003:1001
    
  immich-microservices:
    container_name: immich_microservices
    networks:
    - npm_proxy
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - geocoding-dump:/usr/src/app/.reverse-geocoding-dump
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    user: 1003:1001
    
  immich-machine-learning:
    container_name: immich_machine_learning
    networks:
    - npm_proxy
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    networks:
    - npm_proxy
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    networks:
    - npm_proxy
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - UID=1003
      - GID=1001
      - UMASK=002
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    networks:
    - npm_proxy
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    networks:
    - npm_proxy
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    networks:
    - npm_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:

      # Make sure these values get passed through from the env file
      IMMICH_SERVER_URL: 
      IMMICH_WEB_URL: 
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
  geocoding-dump:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/data/fotos
IMMICH_VERSION=v1.82.1
TYPESENSE_API_KEY=redacted
DB_PASSWORD=redacted
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Europe/Lisbon
```

### Reproduction steps

```bash
1. Upload the photo or video trough the android app
2. Check the web interface
This does not occur with every photo or video, it seems random...
```
