### ISSUE TITLE
[BUG] Immich does not sync libraries nor does it update the default library if items are deleted

### ISSUE THREAD

**Issue by vanimox** [immich-app/immich#4648]
### The bug

Here's the first half of my docker-compose file that contains the mounting instructions for the library: 

```
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/12Bay/Pictures/Allen:/mnt/12Bay/Pictures/Allen:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/12Bay/Pictures/Allen:/mnt/12Bay/Pictures/Allen:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
```

Here's the .env file:
```
UPLOAD_LOCATION=/mnt/12Bay/Pictures/MobileUploads

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


PUBLIC_LOGIN_PAGE_MESSAGE="Family Photos aand Videos Backup Server"

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001`
```

I can also confirm that the file is properly mounted within the Immich Server here:
<img width="374" alt="image" src="https://github.com/immich-app/immich/assets/25700693/637a7b84-fae1-454b-a24d-58ece6f45138">

But when I go into the web GUI>Account Settings>Libraries and enter the mount path under new Library, it doesn't show anything even when doing a force rescan. 

<img width="601" alt="image" src="https://github.com/immich-app/immich/assets/25700693/2c9cc61d-014b-482c-94ed-6b3dd393dd02">

Additionally, I deleted the MobileUpload path at: /mnt/12Bay/Pictures/MobileUploads so there is nothing currently in that directory; however, I continue to see that Immich believes there are still files there and doing a library refresh doesn't resolve the issue. 

### The OS that Immich Server is running on

Ubuntu 20.04.5 LTS

### Version of Immich Server

1.82.1

### Version of Immich Mobile App

1.82.0 build.121

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/12Bay/Pictures/Allen:/mnt/12Bay/Pictures/Allen:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/12Bay/Pictures/Allen:/mnt/12Bay/Pictures/Allen:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/12Bay/Pictures/MobileUploads

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


PUBLIC_LOGIN_PAGE_MESSAGE="Family Photos aand Videos Backup Server"

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
```

### Reproduction steps

```bash
1. Fresh Ubuntu Installation
2. Installed Immich using the config and .env listed above.
3. Attempted to add mounted library to no avail. 
4. Noticed Mobile uploads were not going to /mnt/12Bay/Pictures but rather going to /mnt/12bay/Pictures (case difference in 12Bay).
5. Deleted /mnt/12bay and corrected the path to the NFS mounted drive at /mnt/12Bay/Pictures
6. Confirmed backups work without issue, but noticed that the Default Library was still showing the old photos that were since deleted from the filesystem. 
7. Attempted a forced library refresh and neither did the Mounted Library update (still shows as zero) nor the Default Library (items should have gone down as there is only 1 picture in the actual filesystem).
...
```
