### ISSUE TITLE
[BUG] Ordering Albums by Most Recent Photos does not work and is not persistent

### ISSUE THREAD

**Issue by nicokaiser** [immich-app/immich#4680]
### The bug

Ordering Albums by their Most Recent Photo seems not to work correctly. EXIF dates are correct, and the album pages display the date ranges correctly, but the albums are not ordered by the newest photos. I did not figure out how they are ordered however.

Also, when setting the search order and reloading the page, the search order is displayed as "Album title" again, although `{"sortBy":"Most recent photo"}` is correctly (?) saved to localStorage.

Maybe there is just some minor mapping inconsistency?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.83.0

### Version of Immich Mobile App

web

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./external:/mnt/media/external:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - immich

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./external:/mnt/media/external:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - immich

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - immich

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - immich

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - ./tsdata:/data
    restart: unless-stopped
    networks:
      - immich

  redis:
    container_name: immich_redis
    image: redis:6-alpine
    restart: unless-stopped
    networks:
      - immich
    volumes:
      - ./redis:/data
    command: redis-server --loglevel warning

  database:
    container_name: immich_postgres
    image: postgres:15.4-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    depends_on:
      - immich-server
      - immich-web
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.rule: Host(`immich.example.com`)
      traefik.http.services.immich.loadbalancer.server.port: "8080"
    networks:
      - immich
      - traefik

networks:
  immich:
  traefik:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
TYPESENSE_API_KEY=...
DB_PASSWORD=...
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Europe/Berlin
LOG_LEVEL=warn
```

### Reproduction steps

```bash
1. Open the Albums page
2. Select the sort order menu, select "Most recent photo"
3. Reload the page
```
