### ISSUE TITLE
[BUG] shown in Android App: "No hsot specified in URI ..." and almost no images shown

### ISSUE THREAD

**Issue by GFNiko** [immich-app/immich#4693]
### The bug

Server and App updated today.
 I get this error mesage in the logs
![signal-2023-10-29-134628_002](https://github.com/immich-app/immich/assets/114079308/b44a0ef7-bbef-41d3-b042-7011d0c64588)
and there are almost no images shown in the app. They are all there when I log in via browser on the server. Happens on 2 different Android devices.
Strangely, this worked until a few weeks ago. Hoped for the next version to for the bug to vanish, but alas, it's still here

### The OS that Immich Server is running on

Fedora 37

### Version of Immich Server

1.83.0 build.107

### Version of Immich Mobile App

1.83.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/l ocaltime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresqyl/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/ntfs/Pictures
IMMICH_MACHINE_LEARNING_ENABLED=false
TYPESENSE_ENABLED=false
IMMICH_VERSION=release
```

### Reproduction steps

```bash
1. open the android app
2. miss most of the images
3. take a gander into the logs
```

### Additional information

Android:
LineageOS 20 or
/e/ OS 1.16

Hosted via Caddyserver v2 Reverse-Proxy (works like a charm):
```
foto.{$DOMAIN} {
	reverse_proxy 192.168.0.28:2283
	encode zstd gzip
	header {
		Strict-Transport-Security max-age=31536000;
		Referrer-Policy no-referrer-when-downgrade
		X-Content-Type-Options nosniff
		X-Frame-Options DENY
	}
}
```

And Homepage Dashboard API access works as well:
![image](https://github.com/immich-app/immich/assets/114079308/8365e2b8-0695-444e-b3fe-e65bc7c32546)
