### ISSUE TITLE
[BUG] Repair page error - Operation timed out

### ISSUE THREAD

**Issue by bestrocker221** [immich-app/immich#4776]
### The bug

After indexing the library, there are few thousands metadata and thumbnail generation failed but when I browse to the Repair page it throws an error.

![image](https://github.com/immich-app/immich/assets/11471776/6a628e7a-a417-4a97-bb76-284148beaa42)

The only log visible by the server is the following
```
immich_proxy             | 2023/11/01 15:24:35 [error] 51#51: *38181 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.48.1, server: , 
request: "GET /admin/repair/__data.json?x-sveltekit-invalidated=01 HTTP/1.0", upstream: "http://192.168.48.3:3000/admin/repair/__data.json?x-sveltekit-invalidated=01", host: "127.0.0.1:2283", 
referrer: "https://XXX/admin/user-management"
```

### The OS that Immich Server is running on

debian 11

### Version of Immich Server

v1.83.0

### Version of Immich Mobile App

v1.83.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"                                                                                                                                               
                                                                                                                                                             
services:                                                                                                                                                    
  immich-server:                                                                                                                                             
    container_name: immich_server                                                                                                                            
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]                                                                                                                          
    #user: "1000:1000"                                                                                                                                       
    volumes:                                                                                                                                                 
      - ${LIBRARY_UPLOAD_LOCATION}:/usr/src/app/upload/library                                                                                               
      - ${ENCODED_VID_LOCATION}:/usr/src/app/upload/encoded-video                                                                                            
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs                                                                                                        
      - ${MYLIB_LOCATION}:/usr/src/app/mylibrary:ro                                                                                                          
      - /etc/localtime:/etc/localtime:ro                                                                                                                     
    env_file:                                                                                                                                                
      - .env                                                                                                                                                 
    depends_on:                                                                                                                                              
      - redis                                                                                                                                                
      - database                                                                                                                                             
      - typesense                                                                                                                                            
    restart: always                                                                                                                                          
                                                                                                                                                             
  immich-microservices:                                                                                                                                      
    container_name: immich_microservices                                                                                                                     
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}                                                                                       
    extends:                                                                                                                                                 
       file: hwaccel.yml                                                                                                                                     
       service: hwaccel                                                                                                                                      
    command: ["start.sh", "microservices"]                                                                                                                   
    #user: "1000:1000"                                                                                                                                       
    volumes:                                                                                                                                                 
      #- ${UPLOAD_LOCATION}:/usr/src/app/upload                                                                                                              
      - ${LIBRARY_UPLOAD_LOCATION}:/usr/src/app/upload/library                                                                                               
      - ${ENCODED_VID_LOCATION}:/usr/src/app/upload/encoded-video                                                                                            
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs                                                                                                        
      - ${MYLIB_LOCATION}:/usr/src/app/mylibrary:ro                                                                                                          
      - /etc/localtime:/etc/localtime:ro                                                                                                                     
    env_file:                                                                                                                                                
      - .env                                                                                                                                                 
    depends_on:                                                                                                                                              
      - redis                                                                                                                                                
      - database                                                                                                                                             
      - typesense                                                                                                                                            
    restart: always 
  immich-machine-learning:                                                                                                                                   
    container_name: immich_machine_learning                                                                                                                  
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}                                                                             
    #user: "1000:1000"                                                                                                                                       
    volumes:                                                                                                                                                 
      - ./model-cache:/cache                                                                                                                                 
    env_file:                                                                                                                                                
      - .env                                                                                                                                                 
    restart: always                                                                                                                                          
                                                                                                                                                             
  immich-web:                                                                                                                                                
    container_name: immich_web                                                                                                                               
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}                                                                                          
    env_file:                                                                                                                                                
      - .env                                                                                                                                                 
    restart: always                                                                                                                                          
    user: "1000:1000"                                                                                                                                        
                                                                                                                                                             
  typesense:                                                                                                                                                 
    container_name: immich_typesense                                                                                                                         
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd                                                
    environment:                                                                                                                                             
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}                                                                                                               
      - TYPESENSE_DATA_DIR=/data                                                                                                                             
      # remove this to get debug messages                                                                                                                    
      - GLOG_minloglevel=1                                                                                                                                   
    user: "1000:1000"             
    volumes:                                                                  
      - ./tsdata:/data                                                        
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    #user: "1000:1000"

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    #user: "1000:1000"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
```


### Your .env content

```Shell
MYLIB_LOCATION=XXX
LIBRARY_UPLOAD_LOCATION=XXXX
ENCODED_VID_LOCATION=XXXX
THUMBS_LOCATION=XXX

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# added by me
NODE_OPTIONS="--max-old-space-size=8192"
TYPESENSE_API_KEY=blah-bliggedy-blah

PUBLIC_LOGIN_PAGE_MESSAGE="Your own private photo library."
###

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```


### Reproduction steps

```bash
1.Index external library (few thousands errors in thumbnails and other metadata gen)
2.Browse to Repair
3.
...
```


### Additional information

_No response_
