### ISSUE TITLE
[BUG] UNTRACKS FILES after deleting external library

### ISSUE THREAD

**Issue by techn0pia** [immich-app/immich#4863]
### The bug

Current state:
- if I remove an external library, Thumbnails are remaining as "UNTRACKS FILES" in the /usr/src/app/upload/thumbs folder

Desired state:
- if I remove an external library, Thumbnails should be cleaned automatically or via "Repair" button

<img width="671" alt="image" src="https://github.com/immich-app/immich/assets/119968680/120253e3-9790-4c4c-9cc3-2c03db25bb01">

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.84.0

### Version of Immich Mobile App

no app used

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - /usb/immich/upload:/usr/src/app/upload
      - /usb/nextcloud/data/sebastian/files/Photos:/mnt/media/Photos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
     immich-backbone: 
     immich-proxy:       
    extra_hosts:
     - "download.geonames.org:172.23.0.101"      
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - /usb/immich/upload:/usr/src/app/upload
      - /usb/nextcloud/data/user/files/Photos:/mnt/media/Photos:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
     immich-backbone: 
     immich-proxy:
    extra_hosts:
     - "download.geonames.org:172.23.0.101" 
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /data/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
     immich-backbone: 
     immich-proxy:
    extra_hosts:
     - "download.geonames.org:172.23.0.101"           
  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always
    networks:
     immich-backbone:
     immich-proxy:     
    extra_hosts:
     - "download.geonames.org:172.23.0.101" 
  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /data/immich/tsdata:/data    
    restart: always
    networks:
     immich-backbone: 
     
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
     immich-backbone: 
     
  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /data/immich/postgresql:/var/lib/postgresql/data
    restart: always
    networks:
     immich-backbone: 

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
     immich-backbone: 
     immich-proxy:
    
networks:
  immich-backbone:
   external: true
  immich-proxy:
   name: immich-proxy
   external: true
```

### Your .env content

```Shell
IMMICH_VERSION=release
```

### Reproduction steps

```bash
- setting up external library for a user, e.g. /mnt/media/Photos
- deleting external library via GUI
- Thumbnails generated for the external library are now "UNTRACKS FILES" and cannot be repaired via GUI
```
