### ISSUE TITLE
[BUG] After the face recognition task is completely re-run, every face is a single photo?

### ISSUE THREAD

**Issue by davidpan** [immich-app/immich#4929]
### The bug

It looks like there is no merging of similar/same person faces and the face recognition parameters are using default values.

There are about 20,000 photos and a few hundred videos on the immich.

Is there any way to fix this?

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

v1.85.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/1T/PhotoPrism:/mnt/media/PhotoPrism:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/1T/PhotoPrism:/mnt/media/PhotoPrism:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    dns:
      - 1.1.1.1

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.25.1
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      #- GLOG_minloglevel=1
    volumes:
      - tsdata1:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata1:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=*
DB_PASSWORD=*

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. rebuild all hosts, delete tsdata volume
2. re-run the face recognition task completely
3. check the photos in the PEOPLE interface after the task is complete
...
```

### Additional information

immich_typesense logs:
```
I20231109 11:16:35.191955   167 batched_indexer.cpp:285] Running GC for aborted requests, req map size: 0
I20231109 11:16:39.852726   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:16:39.852813   210 raft_server.h:60] Peer refresh succeeded!
I20231109 11:16:49.853705   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:16:49.853812   204 raft_server.h:60] Peer refresh succeeded!
I20231109 11:16:59.854790   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:16:59.854955   210 raft_server.h:60] Peer refresh succeeded!
I20231109 11:17:09.855840   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:17:09.855958   204 raft_server.h:60] Peer refresh succeeded!
I20231109 11:17:19.856822   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:17:19.856940   210 raft_server.h:60] Peer refresh succeeded!
I20231109 11:17:29.857842   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:17:29.857949   204 raft_server.h:60] Peer refresh succeeded!
I20231109 11:17:36.197216   167 batched_indexer.cpp:285] Running GC for aborted requests, req map size: 0
I20231109 11:17:39.859115   166 raft_server.cpp:564] Term: 2, last_index index: 1510, committed_index: 1510, known_applied_index: 1510, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 2939
I20231109 11:17:39.859218   210 raft_server.h:60] Peer refresh succeeded!
```
