### ISSUE TITLE
Android app confuses fresh pictures/videos for old non-local pictures/videos

### ISSUE THREAD

**Issue by aphymi** [immich-app/immich#4939]
### The bug

This is a weird one, but bear with me.

Since I re-installed the app after a factory-reset about a week ago, whenever a new photo (or video, but I'll just say photos here for brevity) is taken (added to the Camera album, or any other backup albums), the Immich app mistakes that photo for some other photo on the timeline (which does not exist on the phone), seemingly believing that it now has a copy of that old photo on the local device, and that that copy is this new photo file.

The photo does not get uploaded to the server or added to its proper place in the timeline. The new photo takes the old photo's place on the app's timeline. If the new photo replaces a video, the preview shows correctly, but with the old video's length preview on it, and expanding the 'video' results in an infinite loading wheel.

I don't know by what process it's deciding which old photo to mistake the new one for, but they've all been from the last year so far, and photos taken close together seem to replace photos on the timeline that were taken close together.

---

That description may be unclear, so here's an example. Say I take a photo of a candle on my desk with the default camera app:
<img src="https://github.com/immich-app/immich/assets/5588944/94553217-8372-4b95-bf91-72157632e387" height="600px"/>

Finding it through my phone's file browser, the name of the photo file is PXL_20231109_224242285.MP.jpg
<img src="https://github.com/immich-app/immich/assets/5588944/ba45200f-22d3-4a7c-b1ee-c647df5cb2dd" height="600px"/>

Loading the Immich app and finding the photo through the camera album, it's apparently mistaken the photo for a video (trying and failing to play it), and the file name it believes it has is PXL_20221120_182501591.mp4
<img src="https://github.com/immich-app/immich/assets/5588944/10aea84f-a5f3-4cf6-8923-def7193db25e" height="600px"/>
<img src="https://github.com/immich-app/immich/assets/5588944/fffe2c98-4401-4cf4-bd81-71793bfd327a" height="600px"/>

Loading up immich through the browser and looking at that date, there is indeed a completely separate video with that filename, which the candle photo has replaced in the app's timeline.
![image](https://github.com/immich-app/immich/assets/5588944/7c222f16-e18c-4eb4-9c44-fc8831f14931)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.85.0

### Version of Immich Mobile App

1.85.0 build.109

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2001:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_DATABASE_NAME=<redacted>

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=<redacted>/immich/

TYPESENSE_API_KEY=<redacted>

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=false
IMMICH_MACHINE_LEARNING_ENABLED=false
```

### Reproduction steps

```bash
As described above.
```

### Additional information

This issue persists even without access to the internet, so it's probably contained to the mobile app.

This issue persists through an uninstall/reinstall from the play store, and cache clear.

Loading up a completely separate instance of the app from source (37ab37b) through USB debugging with Flutter and VSCode, this issue does not occur on the debug instance. All local photos that have been affected by this issue on the main instance get recognised and uploaded as they originally should have been. Closing down the debug instance, the issue persists on the main instance with new photos.

The app log has nothing notable. Just variations on:
```
2023-11-09 17:43:20.248175,LogLevel.INFO,"AlbumService","Syncing completed. Changes: false",""
2023-11-09 17:43:20.246320,LogLevel.INFO,"AlbumService","'Recents' is not selected, keeping only selected albums",""
2023-11-09 17:43:20.246156,LogLevel.INFO,"AlbumService","Found 8 device albums",""
```
