### ISSUE TITLE
[BUG] Large video files are not uploaded and get stuck on upload on Android mobile.

### ISSUE THREAD

**Issue by thierrybla** [immich-app/immich#4948]
### The bug

Large video files are not uploaded and get stuck on upload on Android mobile.

I am trying to upload a video of 4.29GB but it keeps getting stuck on 31%
Not sure if this is normal or just happens with this file.
I also tried to upload it via web but it also is giving me errors.

### The OS that Immich Server is running on

TrueNAS-SCALE-23.10.0.1

### Version of Immich Server

v1.85.0

### Version of Immich Mobile App

v1.85.0 Build.109

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.1.x
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.x
      - DB_PORT=5432
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - path_to_appdata:/config
      - path_to_photos:/photos
      - path_to_machine-learning:/config/machine-learning #optional
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Have a big video files ~5 GB in your library
2. Open the app.
3. Wait for it to get stuck on the upload.
```
