### ISSUE TITLE
[BUG] 502 Bad Gateway - Multiple Immich In the Same Machine

### ISSUE THREAD

**Issue by tangsteve** [immich-app/immich#4996]
### The bug

I have deployed another stack with the 2283 port. 
The previous one works fine. 
I am attempting to build another set to test the scanning functions to enhance the performance.

After change the HOSTNAME for the DB, TYPESENSE, REDIS, seem everything works fine.
Immich-server has no error logs. 
immich-proxy has shown the following error:

```
2023/11/13 04:12:09 [error] 41#41: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.24.0.3:3000/", host: "192.168.9.116:2284"
2023/11/13 04:12:09 [error] 41#41: *40 connect() failed (111: Connection refused) while connecting to upstream, client: 172.24.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.24.0.3:3000/favicon.ico", host: "192.168.9.116:2284", referrer: "http://192.168.9.116:2284/"
```

![image](https://github.com/immich-app/immich/assets/14835462/cfc0a933-dd92-44ab-9824-8fa58f3213a4)

### The OS that Immich Server is running on

Synology

### Version of Immich Server

release

### Version of Immich Mobile App

release

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server${SUFFIX}
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    environment:
      - REDIS_HOSTNAME=immich_redis${SUFFIX}
      - TYPESENSE_HOST=immich_typesense${SUFFIX}
      - DB_HOSTNAME=immich_postgres${SUFFIX}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/photo:/import
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices${SUFFIX}
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    environment:
      - REDIS_HOSTNAME=immich_redis${SUFFIX}
      - TYPESENSE_HOST=immich_typesense${SUFFIX}
      - DB_HOSTNAME=immich_postgres${SUFFIX}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/photo:/import
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    dns:
      - 8.8.8.8

  immich-machine-learning:
    container_name: immich_machine_learning${SUFFIX}
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web${SUFFIX}
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense${SUFFIX}
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis${SUFFIX}
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
database:
    container_name: immich_postgres${SUFFIX}
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy${SUFFIX}
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - ${PORT}:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/docker/immich-test-exceptSynoPhoto
SUFFIX =_testscanning

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY= JUSTRANDOM
DB_PASSWORD=postgres

# Configure the Port
PORT=2284

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

PUBLIC_LOGIN_PAGE_MESSAGE="This server is to test the scanning function"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
```

### Reproduction steps

```bash
1. Go to http://server:2284
2. See Error
```
