### ISSUE TITLE
[BUG] duplicate key value violates unique constraint "UQ_assets_owner_library_checksum"

### ISSUE THREAD

**Issue by bobotu** [immich-app/immich#5067]
### The bug

I was trying to sync my iPhone photo library to immich for the first time. I noticed that some photos would get stuck at 100% upload progress. I checked the DB log and found this error. I want to know how to fix this problem.

```
2023-11-15 16:07:33.335 UTC [2295] ERROR:  duplicate key value violates unique constraint "UQ_assets_owner_library_checksum"
2023-11-15 16:07:33.335 UTC [2295] DETAIL:  Key ("ownerId", "libraryId", checksum)=(fad7c823-c114-4d62-9212-f1e41b2ae58e, 9d136cd3-5c62-4625-85c5-f6569e794cde, \xfd38f18c36f42908a2a8a14f287b4a39ec3f647e) already exists.
```

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

v1.86.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - TYPESENSE_HOST=${TYPESENSE_HOSTNAME}
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - default
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.hostname == node1
      labels:
        traefik.enable: "true"
        ## HTTP Routers
        traefik.http.routers.immich-api.entrypoints: websecure
        traefik.http.routers.immich-api.rule: "Host(`${PUBLIC_HOSTNAME}`) && Pathprefix(`/api`)"
        traefik.http.routers.immich-api.middlewares: service-immich-api-strip
        ## Middlewares
        traefik.http.middlewares.service-immich-api-strip.stripprefix.prefixes: "/api"
        ## HTTP Services
        traefik.http.routers.immich-api.service: immich-api
        traefik.http.services.immich-api.loadbalancer.server.port: "3001"

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=production
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - TYPESENSE_HOST=${TYPESENSE_HOSTNAME}
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - database
      - typesense
    deploy:
      placement:
        constraints:
          - node.labels.capability == compute
      resources:
        limits:
          cpus: "8"
          memory: 4G

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    environment:
      - NODE_ENV=production
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - MACHINE_LEARNING_REQUEST_THREADS=${ML_WORKERS}
    deploy:
      placement:
        constraints:                  
          - node.labels.capability == compute
      resources:
        limits:
          cpus: ${ML_WORKERS}
          memory: 4G

  immich-web:
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    environment:
      - NODE_ENV=production
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        traefik.enable: "true"
        ## HTTP Routers
        traefik.http.routers.immich-web.entrypoints: websecure
        traefik.http.routers.immich-web.rule: Host(`${PUBLIC_HOSTNAME}`)
        ## HTTP Services
        traefik.http.routers.immich-web.service: immich-web
        traefik.http.services.immich-web.loadbalancer.server.port: 3000

  typesense:
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    command: ["--peering-subnet","10.0.4.0/24"]
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    deploy:
      placement:
        constraints:
          - node.hostname == node2

  redis:
    image: redis:6.2-alpine@sha256:3995fe6ea6a619313e31046bd3c8643f9e70f8f2b294ff82659d409b47d06abb

  database:
    image: postgres:14-alpine@sha256:874f566dd512d79cf74f59754833e869ae76ece96716d153b0fa3e64aec88d92
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.hostname == node2

volumes:
  pgdata:
  model-cache:
  tsdata:

networks:
  default:
    name: immich_internal
    external: true
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true
```

### Your .env content

```Shell
No .env file due to limitation of portainer with Docker Swarm. I put all of them in the compose file.
```

### Reproduction steps

```bash
Just sync my photos.
```

**Comment by alextran1502** [comment]
Can you try accessing over local IP and uploading? Your reverse proxy might have limitation on the max body size that hasn't been set up correctly yet

**Comment by bobotu** [comment]
Okay, I can have a try later. But I have uploaded a 1GB+ video successfully and the failed items are just HEIC image.

**Comment by alextran1502** [comment]
Can you grab the mobile log?

**Comment by DX37** [comment]
Oh, I have this bug as well, but related to #1517 after firmware change (or device change, since app thinks that way).

**Comment by bobotu** [comment]
Okay, I can upload all the photos now. I think this might be transient issue on the server side. The duplicated key error seems not to be related to the upload issue. Maybe something wrong on the data or just there are duplicated photos?

**Comment by jflattery** [comment]
Having the same issue. Adding the below lines to my immich `docker-compose` in the  labels section seemed to help get a few images uploaded that were previously stuck, but still stuck on 1 particular image leaving the app stuck at 529 remaining.

```yaml
    labels:
      traefik.enable: "true"
      traefik.docker.network: "proxy"
      traefik.http.routers.immich.rule: "Host(`${FQDN}`)"
      traefik.http.services.immich-api.loadbalancer.server.port: "3001"
      
      # Sets the maximum request body to 10GB
      traefik.http.routers.immich.middlewares: limit@docker
      traefik.http.middlewares.limit.buffering.maxRequestBodyBytes: 10737418240
      traefik.http.middlewares.limit.buffering.memRequestBodyBytes: 200000000
      traefik.http.middlewares.limit.buffering.maxResponseBodyBytes: 10737418240
      traefik.http.middlewares.limit.buffering.memResponseBodyBytes: 200000000
```
