### ISSUE TITLE
[BUG] typesense crash after editing people names

### ISSUE THREAD

**Issue by deiop** [immich-app/immich#5079]
### The bug

Clean start of stack
After editing multiple people names and merging faces, typsense crashes with segmenation fault

immich_microservices     | [Nest] 7  - 11/16/2023, 9:02:05 AM   ERROR [TypesenseRepository] Unable to index documents
immich_typesense         | W20231116 09:02:05.731760   358 controller.cpp:1454] SIGINT was installed with 1
immich_typesense         | W20231116 09:02:05.731803   358 node.cpp:811] [default_group:172.21.0.4:8107:8108 ] Refusing concurrent configuration changing
immich_typesense         | E20231116 09:02:05.731869   375 raft_server.h:62] Peer refresh failed, error: Doing another configuration change
immich_typesense         | W20231116 09:02:06.574638   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_typesense         | W20231116 09:02:20.248103   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_typesense         | W20231116 09:02:20.271138   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_typesense         | W20231116 09:02:22.256361   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_microservices     | Request #1700125281084: Request to Node 0 failed due to "ECONNRESET read ECONNRESET"
immich_microservices     | Request #1700125281084: Sleeping for 4s and then retrying request...
immich_typesense         | W20231116 09:02:28.649591   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_typesense         | W20231116 09:02:29.061244   432 index.cpp:5406] Error while removing field `embedding` from document, message: Label not found
immich_microservices     | Request #1700125271087: Request to Node 0 failed due to "ECONNRESET read ECONNRESET"
immich_microservices     | Request #1700125271087: Sleeping for 4s and then retrying request...
immich_microservices     | Request #1700125266111: Request to Node 0 failed due to "ECONNRESET read ECONNRESET"
immich_microservices     | Request #1700125266111: Sleeping for 4s and then retrying request...
immich_typesense         | E20231116 09:02:42.886212    27 backward.hpp:4199] Stack trace (most recent call last) in thread 27:
immich_typesense         | E20231116 09:02:42.886250    27 backward.hpp:4199] #11   Object "", at 0xffffffffffffffff, in
immich_typesense         | E20231116 09:02:42.886253    27 backward.hpp:4199] #10   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb715a8abb3, in __clone
immich_typesense         | E20231116 09:02:42.886256    27 backward.hpp:4199] #9    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb7159f9b42, in
immich_typesense         | E20231116 09:02:42.886261    27 backward.hpp:4199] #8    Source "../../../../../libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x15126cf]
immich_typesense         | E20231116 09:02:42.886265    27 backward.hpp:4199] #7  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 215, in operator()
immich_typesense         | E20231116 09:02:42.886268    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 271, in _M_invoke<0>
immich_typesense         | E20231116 09:02:42.886271    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/thread", line 264, in __invoke<ThreadPool::ThreadPool(size_t)::<lambda()> >
immich_typesense         | E20231116 09:02:42.886274    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, ThreadPool::ThreadPool(size_t)::<lambda()> >
immich_typesense         | E20231116 09:02:42.886277    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()
immich_typesense         | E20231116 09:02:42.886281    27 backward.hpp:4199]     | Source "/typesense/include/threadpool.h", line 57, in operator()
immich_typesense         | E20231116 09:02:42.886284    27 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1560, in _M_run [0x520cc4]
immich_typesense         | E20231116 09:02:42.886287    27 backward.hpp:4199] #6  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1427, in _M_set_result
immich_typesense         | E20231116 09:02:42.886291    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 404, in call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()>*, bool*>
immich_typesense         | E20231116 09:02:42.886294    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/mutex", line 729, in __gthread_once
immich_typesense         | E20231116 09:02:42.886297    27 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/x86_64-linux-gnu/bits/gthr-default.h", line 700, in _M_run [0x60e089]
immich_typesense         | E20231116 09:02:42.886301    27 backward.hpp:4199] #5    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb7159fef67, in
immich_typesense         | E20231116 09:02:42.886303    27 backward.hpp:4199] #4  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 564, in operator()
immich_typesense         | E20231116 09:02:42.886307    27 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 622, in _M_do_set [0x51e63a]
immich_typesense         | E20231116 09:02:42.886322    27 backward.hpp:4199] #3  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/std_function.h", line 292, in __invoke_r<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
immich_typesense         | E20231116 09:02:42.886327    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 113, in __invoke_impl<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<_Fn, _Alloc, _Res(_Args ...)>::_M_run<std::_Bind<Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>()>, std::allocator<int>, void, {}>::<lambda()>, void>&>
immich_typesense         | E20231116 09:02:42.886330    27 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in _M_invoke [0x630242]
immich_typesense         | E20231116 09:02:42.886338    27 backward.hpp:4199] #2  | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1365, in operator()
immich_typesense         | E20231116 09:02:42.886341    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/future", line 1424, in __invoke_r<void, std::_Bind<Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>()>&>
immich_typesense         | E20231116 09:02:42.886344    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 110, in __invoke_impl<void, std::_Bind<Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>()>&>
immich_typesense         | E20231116 09:02:42.886348    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator()<>
immich_typesense         | E20231116 09:02:42.886351    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 499, in __call<void>
immich_typesense         | E20231116 09:02:42.886355    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/functional", line 416, in __invoke<Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>&>
immich_typesense         | E20231116 09:02:42.886363    27 backward.hpp:4199]     | Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 95, in __invoke_impl<void, Index::index_field_in_memory(const field&, std::vector<index_record>&)::<lambda()>&>
immich_typesense         | E20231116 09:02:42.886366    27 backward.hpp:4199]       Source "/usr/local/gcc-10.1.0/include/c++/10.1.0/bits/invoke.h", line 60, in operator() [0x6301fc]
immich_typesense         | E20231116 09:02:42.886369    27 backward.hpp:4199] #1    Source "/typesense/src/index.cpp", line 1014, in operator() [0x6300a9]
immich_typesense         | E20231116 09:02:42.886373    27 backward.hpp:4199] #0    Source "/typesense/external-Linux/hnswlib-21de18ffabea1a9d1e8b16b49afc6045d7707e4c/hnswlib/hnswalg.h", line 848, in insertPoint [0x6241fb]
immich_typesense         | Segmentation fault (Address not mapped to object [0x8])
immich_typesense         | E20231116 09:02:43.508272    27 typesense_server.cpp:102] Typesense 0.24.1 is terminating abruptly.

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

1.86

### Version of Immich Mobile App

1.86

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-caddy:
    container_name: caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    environment:
      ACME_AGREE: 'true'
      DOMAIN: 'pics.deiop.de'
      EMAIL: 'tobi@deiop.de'

  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:X
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:X
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:X
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./data

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=X
DB_PASSWORD=X

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.docker compose up -d
2.Wait for starting
3.Open Webfrontend
4.Edit multiple faces / persons' names
5.Merge several faces
6.Typesense crashes
...
```
