### ISSUE TITLE
[BUG] Partner sharing assets don't show previews and images don't show at all

### ISSUE THREAD

**Issue by FrankelJb** [immich-app/immich#5081]
### The bug

After updating to [v1.86.0](https://github.com/immich-app/immich/releases), newly added Partner Sharing assets stopped showing previews. My partner and I share in both directions and now neither of our newly uploaded assets show previews. When accessing videos, they play but photos do not display. The error shows the picture icon with a line through it. Assets don't show up on mobile or web.

### The OS that Immich Server is running on

K3s

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

1.86.0 build.126

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.2.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-web
              tag: v1.86.0@sha256:817235ae94af3abdba10d900d14f06650fd47c502b67f898575ce26c81fba7f9
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 10m
                memory: 100Mi
    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: ${ROOT_DOMAIN}
          external-dns.home.arpa/enabled: 'true'
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nginx.ingress.kubernetes.io/proxy-body-size: '0'
          nignx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          whitelist-source-range.home.arpa/disabled: 'true'
        className: nginx
        enabled: true
        hosts:
          - host: &host immich.${ROOT_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
    service:
      main:
        ports:
          http:
            port: 3000
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.2.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            args:
              - start-server.sh
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.86.0@sha256:0fe2508c706a580871564115c7e5e58ecf8972d415b1bf90537fd7c83e47e227
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        globalMounts:
          - path: /usr/src/app/upload
    service:
      main:
        ports:
          http:
            port: 3001
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.2.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            args:
              - start-microservices.sh
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.86.0@sha256:0fe2508c706a580871564115c7e5e58ecf8972d415b1bf90537fd7c83e47e227
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
    persistence:
      library:
        enabled: true
        existingClaim: immich-pvc
        mountPath: /usr/src/app/upload
    service:
      main:
        enabled: false
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-machine-learning
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.2.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.86.0@sha256:09f8c46395051b0f3e72fe1e53674ddb6a00ed90a3eb2e3087be7bced18bf336
            resources:
              limits:
                memory: 5000Mi
              requests:
                cpu: 100m
                memory: 800Mi
    persistence:
      cache:
        enabled: true
        path: ${LOCAL_PATH}/immich-machine-learning-pvc
        server: ${NFS_HOST}
        type: nfs
      library:
        enabled: true
        existingClaim: immich-pvc
        mountPath: /usr/src/app/upload
    service:
      main:
        ports:
          http:
            port: 3003
```
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-typesense
  namespace: cloud
spec:
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.2.0
  install:
    createNamespace: true
    remediation:
      retries: 3
  interval: 15m
  maxHistory: 3
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controller:
      type: statefulset
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            envFrom:
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            image:
              repository: docker.io/typesense/typesense
              tag: 0.25.1@sha256:035ccfbc3fd8fb9085ea205fdcb62de63eaefdbebd710e88e57f978a30f2090d
            probes:
              liveness: &probes
                custom: true
                enabled: true
                spec:
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8108
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
    persistence:
      config:
        enabled: true
        existingClaim: immich-typesense-pvc
    service:
      main:
        ports:
          http:
            port: 8108
```
```


### Your .env content

```Shell
apiVersion: v1
data:
  DISABLE_REVERSE_GEOCODING: "true"
  LOG_LEVEL: "verbose"
  NODE_ENV: "production"
  REDIS_HOSTNAME: redis-master.default.svc.cluster.local
  IMMICH_SERVER_URL: http://immich-server.cloud.svc.cluster.local:3001
  IMMICH_WEB_URL: http://immich-web.cloud.svc.cluster.local:3000
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.cloud.svc.cluster.local:3003
  TYPESENSE_HOST: immich-typesense.cloud.svc.cluster.local
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  TYPESENSE_DATA_DIR: /config
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: immich-configmap
  namespace: cloud
```

### Reproduction steps

```bash
1. Upgrade immich-machine-learning to v1.86.0, immich-server to v1.86.0 and immich-web to v1.86.0
2. Upload photos to timeline, works correctly
3. Open Sharing -> Partner -> Friend's photos
4. All assets upload after update show broken image icon
...
```

### Additional information

Server logs show errors with the previews:

```	
[Nest] 8  - 11/16/2023, 1:12:49 PM   ERROR [AssetService] Cannot create read stream for asset 58e9835f-e88a-4a85-ad9d-43ab2693bbd1
	
2023-11-16 21:12:49.540	
[Nest] 8  - 11/16/2023, 1:12:49 PM    WARN [AssetService] WebP thumbnail requested but not found for asset 58e9835f-e88a-4a85-ad9d-43ab2693bbd1, falling back to JPEG
```

I tried to rerun the GENERATE THUMBNAILS job for missing but nothing runs and the error persists.

Web console error when loading the video is just `Invalid URI. Load of media resource  failed.`
