### ISSUE TITLE
[BUG] Videos incorrectly placed in timeline

### ISSUE THREAD

**Issue by fredmorais** [immich-app/immich#5109]
### The bug

I have uploaded a video through the web client into Immich. The video's date is July 27th 2023 as you can see in the screenshot below:

<img width="347" alt="Screenshot 2023-11-17 at 21 12 50" src="https://github.com/immich-app/immich/assets/40044095/8899fa5d-f06d-48f1-bfbe-449401ccbe66">

However, in the timeline it is not showing on the pictures/videos of that day, it is instead being shown on the day it was uploaded. This is NOT happening in iOS. 

<img width="722" alt="Screenshot 2023-11-17 at 21 10 08" src="https://github.com/immich-app/immich/assets/40044095/589ea47f-7fac-4589-95f5-2b541c39c454">

### The OS that Immich Server is running on

Ubuntu 22.04.3

### Version of Immich Server

v1.86.0

### Version of Immich Mobile App

v1.86.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"


volumes:
  pgdata:
  model-cache:
  tsdata:
  immich_photos:
    REDACTED


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - proxy

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    networks:
      - proxy
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    networks:
      - proxy
    env_file:
      - .env
    restart: always

  immich-web:
    container_name: immich_frontend
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    networks:
      - proxy
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    networks:
      - proxy
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    networks:
      - proxy
    restart: always

  database:
    container_name: immich_db
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - proxy

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    #environment:
    #  # Make sure these values get passed through from the env file
    #  - IMMICH_SERVER_URL
    #  - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.immich.rule=Host(`immich.MYDOMAIN.COM`)"
      - "traefik.http.routers.immich.entrypoints=https"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.services.immich.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=immich_photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=REDACTED
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_db
DB_USERNAME=REDACTED
DB_DATABASE_NAME=REDACTED

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Upload video through web client.
2. Video's date in timeline is the updated date, not date of capture.
```
