### ISSUE TITLE
[BUG] immich_typesense Container on Raspberry PI 5 - unsupported system page size

### ISSUE THREAD

**Issue by RummsMurmel** [immich-app/immich#5122]
### The bug
Hello,

I wanted to move my self-hosted immich instance from my pi4 (8GB - raspberry pi os bases on debian11) to a new pi5 (8GB -raspberry pi os bases on debian12). 

The docker-compose files are identical.

On the Pi 5 there is an error of the Typesense container at startup:

```
...
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | terminate called without an active exception
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | terminate called without an active exception
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | <jemalloc>: Unsupported system page size
immich_typesense | terminate called without an active exception
immich_typesense exited with code 133
```

According to research, the kernel for the Pi4 is compiled with a page size of 4K, the one for the Pi5 with 16K.

Can I solve the problem here by changing the configuration or do I have to wait for newer releases until the Pi5 is supported?

Kind regards
Adrian

### The OS that Immich Server is running on

Raspberry Pi Os (Debian 12)

### Version of Immich Server

v1.87.0

### Version of Immich Mobile App

v1.87.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich_network

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    networks:
      - immich_network

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /path/to/my/local_storage/ml_model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich_network

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: always
    networks:
      - immich_network

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - /path/to/my/local_storage/tsdata:/data
    restart: always
    networks:
      - immich_network

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always
    networks:
      - immich_network

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /path/to/my/local_storage/postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_network

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.rule=Host(`<my_immich_domain>)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.service=immich"
      - "traefik.http.services.immich.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_default"
    networks:
      - immich_network
      - traefik_default

networks:
  traefik_default:
    external: true
  immich_network:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/path/to/my/local_storage/immich/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<censored>
DB_PASSWORD=<censored>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Run my docker-compose.yml on a pi4 - everything is fine
2. Run the same compose-file on a pi5 - typesense will fail
```
