### ISSUE TITLE
[BUG] 1.88.0+ are missing immich-web and immich-proxy containers

### ISSUE THREAD

**Issue by Scrumplex** [immich-app/immich#5215]
### The bug

1.88.0 and 1.88.1 didn't publish new tags for `immich-web` and `immich-proxy` causing my Helm chart deployment to fail.

### The OS that Immich Server is running on

K3s on NixOS

### Version of Immich Server

v1.88.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
values:
  global:
    storageClass: "openebs-hostpath"
  image:
    # registry and repository are only declared for renovate
    registry: ghcr.io
    repository: immich-app/immich-server
    tag: v1.88.1
  immich:
    persistence:
      library:
        existingClaim: photo-library
  postgresql:
    enabled: true
  redis:
    enabled: true
  typesense:
    enabled: true
    persistence:
      tsdata:
        enabled: true
        storageClass: "openebs-hostpath"
  machine-learning:
    probes:
      liveness:
        spec:
          initialDelaySeconds: 60
  proxy:
    ingress:
      main:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        enabled: true
        hosts:
          - host: immich.foobar
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: "traefik"
```

### Your .env content

```Shell
(empty)
```

### Reproduction steps

```bash
1. Try to pull `ghcr.io/immich-app/immich-web:v1.88.1`
```
