### ISSUE TITLE
[BUG] almost all mp4-videos are marked as duplicate, even if they aren't

### ISSUE THREAD

**Issue by hjjg** [immich-app/immich#5216]
### The bug

Hi there!

I installed a fresh copy of immich with docker-compose (Portainer), yesterday, and began to import my data through the mobile app, as well es immich-go. I quickly noticed that dozens of videos are rejected with the message that they are duplicates, so after some time I started to search for them. Turns out that they haven't been imported and the videos cannot be found by either a timestamp nor the filename. The mechanism to check for duplicates seems to be buggy or maybe it is just my data.

Not sure, but it does not happen with .mov-files. There are some mp4 files in my immich library, so I think it stopped working at some point.

Could you please give me some advice on how to investigate this issue?

### The OS that Immich Server is running on

Debian with Docker, docker-compose and Portainer

### Version of Immich Server

1.87.0

### Version of Immich Mobile App

1.87.0 build.111

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    env_file:
      - stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:3995fe6ea6a619313e31046bd3c8643f9e70f8f2b294ff82659d409b47d06abb
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/data/immich-uploads

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.87.0

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Install the app and sync the files on your phone
2. Use immich-go to import multiple files in folders from old libraries
3. almost all mp4-videos get rejected with a duplicate file message
4. search for the video via webinterface, it is not there
5. try to upload it manually -> same duplicate message.
```
