### ISSUE TITLE
[BUG] CLI error when uploading a folder with 8k images

### ISSUE THREAD

**Issue by SitramSoft** [immich-app/immich#5218]
### The bug

When I tried to upload a folder with over 8k images and videos using the new CLI, I got the following error. I think the node process ran out of memory then was killed by the OS. My laptop runs Arch and has 16 GB of RAM memory. The process consumed according to the Resource Monitor, a bit over 12 GB RAM before I got the error.

![image](https://github.com/immich-app/immich/assets/8177290/13f36fbd-780b-4739-91c9-3ef2436f2409)

Uploading a folder that contained around 1.3k images and videos using the new CLI worked.

Below is a snippet from the content of the folder and the file count:
![image](https://github.com/immich-app/immich/assets/8177290/53b1cf6f-a90f-40fe-9b78-e3eb4d73411b)

### The OS that Immich Server is running on

Ubuntu 22.04.2 LTS

### Version of Immich Server

v1.88.1

### Version of Immich Mobile App

v1.88.0 build.112

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"

services:
#Immich - self hosted photos and videos management application - https://immich.app/
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    cpus: 6
    restart: always


volumes:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
COMPOSE_PROJECT_NAME=serenity_immich

# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/sitram/data/photos_immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
# Typesense
TYPESENSE_ENABLED=true
TYPESENSE_API_KEY=xxx
DB_PASSWORD=xxx

# Timezone
TZ=Europe/Bucharest

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=192.168.0.101
DB_USERNAME=xxx
DB_DATABASE_NAME=xxx

REDIS_HOSTNAME=192.168.0.101
```

### Reproduction steps

```bash
1. immich login-key http://192.168.0.101:2283/api xxx
2. immich upload --dry-run  --recursive --album '2020 - Sabrina' /home/sitram/mounts/data/photos/Sabrina/2020
```

### Additional information

Redis and database container are hosted in a common docker container for my entire homlab, that's why they are not part of the docker-compose.yml content
