### ISSUE TITLE
[BUG] Application soft-crash (greyed in the main screen) after a few seconds

### ISSUE THREAD

**Issue by kai23** [immich-app/immich#528]
**Describe the bug**
Launching the application after killing it, the main header and the body of the turns grey after a few seconds

https://streamable.com/hfurpc

**Task List**

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my `docker-compose` file.

```yaml
immich-server:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-server:release
  entrypoint: ["/bin/sh", "./start-server.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - redis
    - database

immich-microservices:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-server:release
  entrypoint: ["/bin/sh", "./start-microservices.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - redis
    - database
  restart: always

immich-machine-learning:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-machine-learning:release
  entrypoint: ["/bin/sh", "./entrypoint.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - database

immich-web:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-web:release
  entrypoint: ["/bin/sh", "./entrypoint.sh"]
  env_file:
    - .env

redis:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_redis
  image: redis:6.2

database:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_postgres
  image: postgres:14
  env_file:
    - .env
  environment:
    POSTGRES_PASSWORD: ${DB_IMMICH_PASSWORD}
    POSTGRES_USER: ${DB_IMMICH_USERNAME}
    POSTGRES_DB: ${DB_IMMICH_DATABASE_NAME}
    PG_DATA: /var/lib/postgresql/data
  volumes:
    - pgdata:/var/lib/postgresql/data

immich-proxy:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_proxy
  image: altran1502/immich-proxy:release
  # ports:
  #   - 2283:80
  logging:
    driver: none
  depends_on:
    - immich-server
```

- [X] I have included my redacted `.env` file.

```env
###################################################################################
# IMMICH
###################################################################################

DB_IMMICH_HOSTNAME=immich_postgres
DB_IMMICH_USERNAME=XXX # <- obfuscated
DB_IMMICH_PASSWORD=XXX # <- obfuscated
DB_IMMICH_DATABASE_NAME=immich

REDIS_IMMICH_HOSTNAME=immich_redis

UPLOAD_LOCATION=XXX # <- obfuscated

JWT_SECRET=XXX # <- obfuscated

ENABLE_MAPBOX=false
MAPBOX_KEY=

VITE_LOGIN_PAGE_MESSAGE=
```

- [X] I have included information on my machine, and environment.

```
Linux 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

```

**To Reproduce**
See current streamable : 

https://streamable.com/hfurpc

- Kill the app
- Launch the app
- Wait a few seconds

**Expected behavior**
I expect to get the main app

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://streamable.com/hfurpc)

**System**
- Phone OS [Android]: `12 (OneUI 4.1)`
- Server Version: ``
- Mobile App Version: `1.25.0`

**Additional context**

Here is the stacktrace of the app :

```
08-24 12:03:25.899  9789  9828 I flutter : FormatException: Invalid date format
08-24 12:03:25.899  9789  9828 I flutter : 507-09-15
08-24 12:03:25.900  9789  9828 I flutter : #0      DateTime.parse (dart:core/date_time.dart:347)
08-24 12:03:25.900  9789  9828 I flutter : #1      HomePage.build._buildBody.<anonymous closure> (package:immich_mobile/modules/home/views/home_page.dart:68)
08-24 12:03:25.900  9789  9828 I flutter : #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614)
08-24 12:03:25.900  9789  9828 I flutter : #3      HomePage.build._buildBody (package:immich_mobile/modules/home/views/home_page.dart:67)
08-24 12:03:25.900  9789  9828 I flutter : #4      HomePage.build (package:immich_mobile/modules/home/views/home_page.dart:150)
08-24 12:03:25.900  9789  9828 I flutter : #5      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:424)
08-24 12:03:25.900  9789  9828 I flutter : #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919)
08-24 12:03:25.900  9789  9828 I flutter : #7      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:485)
08-24 12:03:25.900  9789  9828 I flutter : #8      HookElement.build (package:flutter_hooks/src/framework.dart:416)
08-24 12:03:25.900  9789  9828 I flutter : #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806)
08-24 12:03:25.900  9789  9828 I flutter : #10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977)
```

I guess that at least one of my image has an incorrect date in the EXIF but to be honest, I don't know how to find it in my 40k+ photos uploaded :/
