### ISSUE TITLE
[BUG] Large videos are not uploaded to the server

### ISSUE THREAD

**Issue by kai23** [immich-app/immich#529]
**Describe the bug**
Some videos (3 in my collection) can't be uploaded

**Task List**

- [X] I have read thoroughly the README setup and installation instructions.
- [X] I have included my `docker-compose` file.

```yaml
immich-server:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-server:release
  entrypoint: ["/bin/sh", "./start-server.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - redis
    - database

immich-microservices:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-server:release
  entrypoint: ["/bin/sh", "./start-microservices.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - redis
    - database
  restart: always

immich-machine-learning:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-machine-learning:release
  entrypoint: ["/bin/sh", "./entrypoint.sh"]
  volumes:
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
  env_file:
    - .env
  environment:
    - NODE_ENV=production
    - DB_PASSWORD=${DB_IMMICH_PASSWORD}
    - DB_USERNAME=${DB_IMMICH_USERNAME}
    - DB_DATABASE_NAME=${DB_IMMICH_DATABASE_NAME}
  depends_on:
    - database

immich-web:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  image: altran1502/immich-web:release
  entrypoint: ["/bin/sh", "./entrypoint.sh"]
  env_file:
    - .env

redis:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_redis
  image: redis:6.2

database:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_postgres
  image: postgres:14
  env_file:
    - .env
  environment:
    POSTGRES_PASSWORD: ${DB_IMMICH_PASSWORD}
    POSTGRES_USER: ${DB_IMMICH_USERNAME}
    POSTGRES_DB: ${DB_IMMICH_DATABASE_NAME}
    PG_DATA: /var/lib/postgresql/data
  volumes:
    - pgdata:/var/lib/postgresql/data

immich-proxy:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: immich_proxy
  image: altran1502/immich-proxy:release
  # ports:
  #   - 2283:80
  logging:
    driver: none
  depends_on:
    - immich-server
```

- [X] I have included my redacted `.env` file.

```env
###################################################################################
# IMMICH
###################################################################################

DB_IMMICH_HOSTNAME=immich_postgres
DB_IMMICH_USERNAME=XXX # <- obfuscated
DB_IMMICH_PASSWORD=XXX # <- obfuscated
DB_IMMICH_DATABASE_NAME=immich

REDIS_IMMICH_HOSTNAME=immich_redis

UPLOAD_LOCATION=XXX # <- obfuscated

JWT_SECRET=XXX # <- obfuscated

ENABLE_MAPBOX=false
MAPBOX_KEY=

VITE_LOGIN_PAGE_MESSAGE=
```

- [X] I have included information on my machine, and environment.

```
Linux 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

```

**To Reproduce**

I don't really know why these three videos in particular  to be honest. Maybe because of the extension ?

**Expected behavior**
I expect to have the videos uploaded

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://streamable.com/hfurpc)

**System**
- Phone OS [Android]: `12 (OneUI 4.1)`
- Server Version: `v1.25.0`
- Mobile App Version: `1.25.0`

**Additional context**

Here is the stacktrace of the app :
```
08-24 12:07:38.492 10732 10764 I flutter : ERROR backupAsset: SocketException: Write failed (OS Error: Connection reset by peer, errno = 104), address = photos.milo.ovh, port = 41506
```

And in the microservice app : 
```logs
today at 01:00:02[Nest] 6  - 08/24/2022, 1:00:02 AM     LOG [mp4Conversion] Start Converting Video
today at 01:00:02[Nest] 6  - 08/24/2022, 1:00:02 AM   ERROR [mp4Conversion] Cannot Convert Video Error: ffmpeg exited with code 1: upload/961f1e40-7dc7-45d9-b568-b4f3b0bff525/original/fb493a08-1700-535e-94a9-c55d8a50d789/6c601d5b-62b6-4aa3-bad9-7e3034c9261e.mov: Invalid data found when processing input
```
