### ISSUE TITLE
[BUG] Immich CLI - Unexpected ping reply

### ISSUE THREAD

**Issue by klausmark** [immich-app/immich#5332]
### The bug

New install of the immich cli throws "Unexpected ping reply" Error, when issuing server-info or upload sub-commands. login-key succeeds.
```sh
root@server:~# immich server-info
/usr/local/lib/node_modules/@immich/cli/dist/src/services/session.service.js:70
            throw new Error('Unexpected ping reply');
                  ^

Error: Unexpected ping reply
    at SessionService.ping (/usr/local/lib/node_modules/@immich/cli/dist/src/services/session.service.js:70:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionService.connect (/usr/local/lib/node_modules/@immich/cli/dist/src/services/session.service.js:37:9)
    at async ServerInfo.connect (/usr/local/lib/node_modules/@immich/cli/dist/src/cli/base-command.js:27:30)
    at async ServerInfo.run (/usr/local/lib/node_modules/@immich/cli/dist/src/commands/server-info.js:6:9)
    at async Command.<anonymous> (/usr/local/lib/node_modules/@immich/cli/dist/src/index.js:37:5)

Node.js v20.10.0
```

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.88.2

### Version of Immich Mobile App

na

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 8000:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/disk1/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=wavjwfqf,23r.3g3f
DB_PASSWORD=wer,wer.g34qfqfq3

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. immich login-key http://127.0.0.1:8000 npKTjKZXx7lGXcbRV4aJW7S9ncIePLcuTLxfVBay8
2. immich server-info
```

### Additional information

Immach and nodejs are new to me, so maybe i'm overseeing something. If that's the case, then please point me in the right direction.
