### ISSUE TITLE
[BUG] 502 every other day

### ISSUE THREAD

**Issue by gthb96** [immich-app/immich#5358]
### The bug

Hello,
I am not sure if this is really a bug but I am not sure how to proceed on my own.

I am running Immich for a few months on bare metal Ubuntu 22.04 server (nothing else installed, just Immich) behind a caddy reverse proxy without a problem.

Maybe 2 months ago the following behaviour started.

It happens almost everyday for Immich to be unavailable for 1-2 minutes with status "Request failed with status code 502".
Today it happend twice within 5 minutes.
I am using UptimeKuma for monitoring my services, that's why I even know about that.

Other services behind the same caddy proxy are not having issues.

I checked docker logs of Immich containers but can't find anything obvious happing at the time of 502.

Maybe someone has an idea what could be happening or how to analyze it?

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.88.2

### Version of Immich Mobile App

1.88.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/xxxxx/immich-app/images

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxxxxxxxxxxxxxxxxxxx
DB_PASSWORD=xxxxxxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxx
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
The server is running and sometimes giving 502
I guess it's not reproducible and probably not a general thing but I can't find the cause.
```
