### ISSUE TITLE
[BUG] Immich iOS app cannot upload, stuck

### ISSUE THREAD

**Issue by handonam** [immich-app/immich#5445]
### The bug

I took a bit of a break since around November 5th through November 17th, in which I didn't have immich running. So, I started immich again on Nov 17th, updating to 1.87.0. I forgot what I was on when it was November 5th and prior.  

But, fact is, iOS hasn't been uploading images since 1.87.0.  And checking the app, the server storage says "0 of 0 used"
![IMG_5214](https://github.com/immich-app/immich/assets/455463/d25b7e00-d540-4845-b91a-c466476253b4)

In the backup screen, none of the numbers in "Backup" and "Remainder" have moved:
![IMG_5215](https://github.com/immich-app/immich/assets/455463/208fe958-3065-400d-bf7c-d0bb05b3b818)

Most notably, this "Uploading file info" section does not move at all. Even if you click "Cancel" followed by "Start Backup"
![IMG_5216](https://github.com/immich-app/immich/assets/455463/60085f71-4616-451e-9e53-49ae2f4960ce)

Singularly uploading images do not change anything as well.

Attempted to check iOS app for any logs (including Troubleshooting mode on with finest log settings), but nothing came up. Logs are fairly blind to this issue.

### The OS that Immich Server is running on

docker-compose via Unraid

### Version of Immich Server

1.89.0 and 1.88.2

### Version of Immich Mobile App

1.89.0 build.129

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  portainer_agent:
    ports:
      - '9001:9001'
    container_name: portainer_agent
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    image: 'portainer/agent:2.19.1'
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml # this is in /boot/config/plugins/compose.manager/projects/immich/hwaccel.yml
      service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    ports:
      - 3003:3003
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

      
volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Documents/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=<REDACTED>
DB_PASSWORD=<REDACTED>


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
See screenshots.
```
