### ISSUE TITLE
[BUG] Merging pictures resets name

### ISSUE THREAD

**Issue by modem7** [immich-app/immich#5463]
### The bug

When merging a picture, the name gets reset. 

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.89.0

### Version of Immich Mobile App

na

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
##########
 ##Immich##
 ##########

  immich-server:
    container_name: Immich_Server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/docker_data/immich/uploads:/usr/src/app/upload
      - /mnt/oldhd/Pictures:/photos
    environment:
      - TZ=$TZ
      - LOG_LEVEL=log
      - IMMICH_MEDIA_LOCATION=./upload
      - DB_HOSTNAME=immichdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=$IMMICH_DB_PWD
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immichredis
      - TYPESENSE_HOST=immichtypesense
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
    networks:
      pihole:
        ipv4_address: '172.22.0.147'
      isolated:
      isonet:
    ports:
      - 2283:3001
    labels:
      # - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.immich-rtr.entrypoints=https"
      - "traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)"
      - "traefik.http.routers.immich-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.immich-rtr.middlewares=chain-no-auth@file"
      # - "traefik.http.routers.immich-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.immich-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.immich-rtr.service=immich-svc"
      - "traefik.http.services.immich-svc.loadbalancer.server.port=3001"
      ## Homepage
      - homepage.name=Immich
      - homepage.group=Other
      - homepage.icon=immich
      - homepage.href=https://immich.$DOMAINNAME
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      - immichredis
      - immichdb
      - immichtypesense
    restart: always

  immich-microservices:
    container_name: Immich_Microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - /mnt/docker_data/immich/uploads:/usr/src/app/upload
      - /mnt/oldhd/Pictures:/photos
    environment:
      - TZ=$TZ
      - LOG_LEVEL=log
      - IMMICH_MEDIA_LOCATION=./upload
      - REVERSE_GEOCODING_DUMP_DIRECTORY=./.reverse-geocoding-dump/
      - DB_HOSTNAME=immichdb
      - DB_USERNAME=postgres
      - DB_PASSWORD=$IMMICH_DB_PWD
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=immichredis
      - TYPESENSE_HOST=immichtypesense
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
      - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
    networks:
      pihole:
        ipv4_address: '172.22.0.148'
      isolated:
      isonet:
    depends_on:
      - immichredis
      - immichdb
      - immichtypesense
    devices:
      - /dev/dri:/dev/dri
    runtime: nvidia
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immich-machine-learning:
    container_name: Immich_Machine_Learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    networks:
      isonet:
    environment:
      - MACHINE_LEARNING_WORKERS=4
    volumes:
      - /mnt/docker_data/immich/cache:/cache
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichtypesense:
    container_name: Immich_Typesense
    image: typesense/typesense:0.24.1
    environment:
      - TYPESENSE_API_KEY=$IMMICH_TYPESENSE_API_KEY
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    networks:
      isonet:
    volumes:
      - /mnt/docker_data/immich/typesense:/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichredis:
    container_name: Immich_Redis
    image: redis:6.2-alpine
    networks:
      isolated:
    volumes:
      - $USERDIR/Immich/redis:/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always

  immichdb:
    container_name: ImmichDB
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=$IMMICH_DB_PWD
      - POSTGRES_DB=immich
    volumes:
      - $USERDIR/Immich/DB:/var/lib/postgresql/data
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    networks:
      isolated:
    restart: always
```

### Your .env content

```Shell
# Immich
IMMICH_DB_PWD="xxxx"
IMMICH_TYPESENSE_API_KEY="xxxx"
```

### Reproduction steps

```bash
1. Find image to merge
2. Click merge
3. Name gets reset
```
![image](https://github.com/immich-app/immich/assets/4349962/8499922c-b03a-4454-abb4-bcfa2c870a64)
![image](https://github.com/immich-app/immich/assets/4349962/e4075c32-d4fc-4485-b9c8-33bcbfd036fe)
![image](https://github.com/immich-app/immich/assets/4349962/c1ccb2b5-a892-454e-85c6-99e56a275cd0)
