### ISSUE TITLE
[BUG] iOS live photos which have been rotateed or an effect are shown as separate images and videos in immich

### ISSUE THREAD

**Issue by philw07** [immich-app/immich#5473]
### The bug

When uploading a live photo from iOS which has either been rotated or an effect (bounce, loop, etc.), it will be displayed as separate photo and video in immich.
In case of rotated photos, the video has the original orientation.
I would expect it to show as a regular live photo in immich (without any effect, but ideally rotated correctly).

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

v1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped
    networks:
      - default
      - web
    labels:
      <traefik labels>

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


networks:
  web:
    external: true


volumes:
  pgdata:
  model-cache:
  tsdata:
  photos:
    <nfs share options>
```

### Your .env content

```Shell
IMMICH_VERSION=release

TYPESENSE_API_KEY=<pw>
DB_PASSWORD=<pw>

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take a live photo on iOS device
2. Rotate it or add an effect (bounce, lopp, etc.)
3. Upload the photo to immich
4. Immich will show a separate photo and video
```
