### ISSUE TITLE
immich_server issue after removing typsense api key env - Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"

### ISSUE THREAD

**Issue by psilantropy** [immich-app/immich#5575]
### The bug

After following the new typesense removal instructions, I redeployed, removed typesense container and everything looked good.

In the interest of making things slightly tidier I noticed the "TYPESENSE_API_KEY" was still present. I removed this and deployed again.

immich-server would not run correctly as the TYPESENSE_API_KEY was required.
I added it back and now get this error;

```
Request #1702075713167: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1702075713167: Sleeping for 4s and then retrying request...
```

If I add TYPESENSE_ENABLED=false the error is resolved.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    runtime: nvidia
    privileged: true
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=xxx
IMMICH_VERSION=release
DB_PASSWORD=xxxxx
DB_HOSTNAME=immich_postgres
DB_USERNAME=xxxxx
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=xxxxxxx
NVIDIA_DRIVER_CAPABILITIES=all
NVIDIA_VISIBLE_DEVICES=xxx
TYPESENSE_API_KEY=xxx
TYPESENSE_ENABLED=false
```

### Reproduction steps

```bash
1. Follow new deployment instructions - good
2. Remove TYPESENSE_API_KEY  variable - fail
3. Add TYPESENSE_ENABLED=false - success :)
```
