### ISSUE TITLE
[BUG] insert or update on table "person" violates foreign key constraint

### ISSUE THREAD

**Issue by maltokyo** [immich-app/immich#5580]
### The bug

After upgrading to v1.90.2, I can no longer start the container, even after waiting 15-20 minutes for potential migrations etc.
Detailed log file attached below, but not sure what to do to resolve this.  The only thing I did was run `docker compose pull ` 

### The OS that Immich Server is running on

Debian 12 latest updates applied

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

#   immich-web:
#     container_name: immich_web
#     image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
#     env_file:
#       - .env
#     restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/sWes1000/z_immich_msi_metadata

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=REDACTED
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres

DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose
```

### Reproduction steps

```bash
1. docker compose pull to latest version v1.90.2
2. docker compose up -d

...
```

### Additional information

Logs from `docker compose logs` - this just repeats over and over endlessly:

```
immich_server            | [Nest] 7  - 12/09/2023, 9:58:06 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich_server            | QueryFailedError: insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async EditFaceAssetForeignKey1699727044012.up (/usr/src/app/dist/infra/migrations/1699727044012-EditFaceAssetForeignKey.js:11:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
immich_server            |     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
immich_postgres          | 2023-12-09 09:58:10.844 UTC [76] ERROR:  insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_postgres          | 2023-12-09 09:58:10.844 UTC [76] DETAIL:  Key (faceAssetId)=(1b3b7403-a52f-494c-a0aa-60ced5623285) is not present in table "asset_faces".
immich_postgres          | 2023-12-09 09:58:10.844 UTC [76] STATEMENT:  ALTER TABLE "person" ADD CONSTRAINT "FK_2bbabe31656b6778c6b87b61023" FOREIGN KEY ("faceAssetId") REFERENCES "asset_faces"("id") ON DELETE SET NULL ON UPDATE NO ACTION
immich_microservices     | [Nest] 6  - 12/09/2023, 9:58:10 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
immich_microservices     | QueryFailedError: insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_microservices     |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async EditFaceAssetForeignKey1699727044012.up (/usr/src/app/dist/infra/migrations/1699727044012-EditFaceAssetForeignKey.js:11:9)
immich_microservices     |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_microservices     |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
immich_microservices     |     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
immich_postgres          | 2023-12-09 09:58:14.495 UTC [77] ERROR:  insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_postgres          | 2023-12-09 09:58:14.495 UTC [77] DETAIL:  Key (faceAssetId)=(1b3b7403-a52f-494c-a0aa-60ced5623285) is not present in table "asset_faces".
immich_postgres          | 2023-12-09 09:58:14.495 UTC [77] STATEMENT:  ALTER TABLE "person" ADD CONSTRAINT "FK_2bbabe31656b6778c6b87b61023" FOREIGN KEY ("faceAssetId") REFERENCES "asset_faces"("id") ON DELETE SET NULL ON UPDATE NO ACTION
immich_server            | [Nest] 7  - 12/09/2023, 9:58:14 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
immich_server            | QueryFailedError: insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async EditFaceAssetForeignKey1699727044012.up (/usr/src/app/dist/infra/migrations/1699727044012-EditFaceAssetForeignKey.js:11:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
immich_server            |     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
immich_typesense         | W20231209 09:58:15.255029   214 controller.cpp:1454] SIGINT was installed with 1
immich_typesense         | W20231209 09:58:15.255084   214 raft_server.cpp:570] Single-node with no leader. Resetting peers.
immich_typesense         | W20231209 09:58:15.255098   214 node.cpp:894] node default_group:172.19.0.5:8107:8108 set_peer from 172.19.0.7:8107:8108 to 172.19.0.5:8107:8108
immich_postgres          | 2023-12-09 09:58:17.889 UTC [78] ERROR:  insert or update on table "person" violates foreign key constraint "FK_2bbabe31656b6778c6b87b61023"
immich_postgres          | 2023-12-09 09:58:17.889 UTC [78] DETAIL:  Key (faceAssetId)=(1b3b7403-a52f-494c-a0aa-60ced5623285) is not present in table "asset_faces".
immich_postgres          | 2023-12-09 09:58:17.889 UTC [78] STATEMENT:  ALTER TABLE "person" ADD CONSTRAINT "FK_2bbabe31656b6778c6b87b61023" FOREIGN KEY ("faceAssetId") REFERENCES "asset_faces"("id") ON DELETE SET NULL ON UPDATE NO ACTION
```
