### ISSUE TITLE
[BUG] TYPENSENSE_API_KEY still required in 1.90.0+

### ISSUE THREAD

**Issue by milouk** [immich-app/immich#5583]
### The bug

Although I have upgrade to version 1.90.2 and have remove `TYPESENSE_API_KEY` from my env file I get the following error:

```
/usr/src/app/node_modules/@nestjs/config/dist/config.module.js:78
                throw new Error(`Config validation error: ${error.message}`);
                ^

Error: Config validation error: "TYPESENSE_API_KEY" is required
    at ConfigModule.forRoot (/usr/src/app/node_modules/@nestjs/config/dist/config.module.js:78:23)
    at Object.<anonymous> (/usr/src/app/dist/infra/infra.module.js:50:27)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/src/app/dist/infra/index.js:19:14)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

Node.js v20.10.0
```

### The OS that Immich Server is running on

Debian Bookworm

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    <<: *common-keys-core
    container_name: immich_server
    image: altran1502/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /mnt/media:/usr/src/app/upload
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
      - redis
      - database
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.22
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.services.immich-server.loadbalancer.server.port=3001
      - traefik.http.routers.immich-server-https.entrypoints=https
      - traefik.http.routers.immich-server-https.rule=Host(`${IMMICH_HOST}`)
      - traefik.http.routers.immich-server-https.tls=true
      - traefik.http.routers.immich-server-https.middlewares=chain-middlewares-no-auth@file


  immich-microservices:
    <<: *common-keys-core
    container_name: immich_microservices
    image: altran1502/immich-server:release
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    volumes:
      - /mnt/media:/usr/src/app/upload
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
      - redis
      - database
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.23
    labels:
      - com.centurylinklabs.watchtower.enable=true


  immich-machine-learning:
    <<: *common-keys-core
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - /data/immich/model-cache:/cache
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.24
    labels:
      - com.centurylinklabs.watchtower.enable=true


  redis:
    <<: *common-keys-core
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      private-network:
        ipv4_address: 10.1.0.26
    labels:
      - com.centurylinklabs.watchtower.enable=true
  

  database:
    <<: *common-keys-core
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - ./immich/immich.env
    volumes:
      - /data/immich/pgdata:/var/lib/postgresql/data
    networks:
      private-network:
        ipv4_address: 10.1.0.27
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
TZ=Europe/Athens
```

### Reproduction steps

```bash
1. Use docker-compose up
```
