### ISSUE TITLE
[Updating Issue] Immich stopped working after updating server from 1.8x to 1.9x

### ISSUE THREAD

**Issue by thrhgh** [immich-app/immich#5589]
### The bug

Hi guys.

First of all, thank you very much for this great piece of software!

Today, I updated my server from 1.8x to 1.9x. I followed the release guide and adapted the docker-compose.yml. 
Now everything stopped working and I cannot even access the web ui anymore. If i run docker logs immich_server:
`Request #1702150844124: Request to Node 0 failed due to "ENOTFOUND getaddrinfo ENOTFOUND typesense"
Request #1702150844124: Sleeping for 4s and then retrying request...
`

the database seems to work. If I run docker logs immich_postgres:
`2023-12-09 19:38:26.415 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-12-09 19:38:26.452 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-12-09 19:38:26.452 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-12-09 19:38:26.466 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-12-09 19:38:26.500 UTC [27] LOG:  database system was shut down at 2023-12-09 19:38:04 UTC
2023-12-09 19:38:26.518 UTC [1] LOG:  database system is ready to accept connections
`

Anyone has an idea what went wrong during the update?

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.9.02

### Version of Immich Mobile App

1.9.02

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - adguardhome
      - redis
      - database
    restart: always

... unrelevant stuff removed

database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=xxx

IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxxxxx
DB_PASSWORD=xxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Update 1.8x to 1.9x
```
