### ISSUE TITLE
[BUG] Changing external library "import path" does not update the path of the pre-existing content of the library

### ISSUE THREAD

**Issue by maltokyo** [immich-app/immich#5629]
### The bug

Changing external library "import path" does not update the path of the pre-existing content of the library.

Lets say for the Library `MyPhotos` the import path until yesterday was:

`/mnt/SmallHarddrive01/MyPhotos`

and today you upgraded storage on the machine and moved the entire directory of photos to another path, eg they are now here:

`/mnt/BigHarddrive02/MyPhotos`

Then rerun all of the jobs to rescan the library etc, nothing gets updated for photos that were already in the Library in the old path, even though they are all now in a new path.

### The OS that Immich Server is running on

Debian 12 latest updates applied

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro

    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

#   immich-web:
#     container_name: immich_web
#     image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
#     env_file:
#       - .env
#     restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/sWes1000/z_immich_msi_metadata

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=REDACTED
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres

DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose
```

### Reproduction steps

```bash
1. Run immich normally and create a library with import path: `/mnt/SmallHarddrive01/MyPhotos` and where external path for user to `/mnt/SmallHarddrive01`
2. Change external path for user to `/mnt/BigHarddrive02`
3. Change the library import path to: `/mnt/BigHarddrive02/MyPhotos` (including in the docker-compose mounts (redacted above) 
4. Run `rescan all library files` in library section of the user and run all background jobs for "missing" info.

Even after doing all of this, the path for the files in that library remains as `/mnt/SmallHarddrive01/MyPhotos` in the database, and as a result, all files in the library get marked as "offline" and cannot be downloaded.
```
