### ISSUE TITLE
[BUG] download ios live photos error from a android phone

### ISSUE THREAD

**Issue by yueziii** [immich-app/immich#5631]
### The bug

uploaded live photo from my iphone with heic format, then download it from android phone, shows error. here is the log: 

```bash
01:17.3	LogLevel.SEVERE	ImageViewerService	Error saving file OS Error: Darwin Editor should only be use on iOS or macOS.	"#0      Editor.darwin (package:photo_manager/src/internal/editor.dart:30)
#1      ImageViewerService.downloadAssetToDevice (package:immich_mobile/modules/asset_viewer/services/image_viewer.service.dart:51)
<asynchronous suspension>
#2      ImageViewerStateNotifier.downloadAsset (package:immich_mobile/modules/asset_viewer/providers/image_viewer_page_state.provider.dart:32)
<asynchronous suspension>
"
00:58.3	LogLevel.SEVERE	ImmichErrorLogger	"Catch all error:  - Cancelled - image resource service - null - #0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"	"#0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"
00:58.2	LogLevel.SEVERE	ImmichErrorLogger	"Catch all error:  - Cancelled - image resource service - null - #0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"	"#0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"
00:58.1	LogLevel.SEVERE	ImmichErrorLogger	"Catch all error:  - Cancelled - image resource service - null - #0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"	"#0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"
00:58.0	LogLevel.SEVERE	ImmichErrorLogger	"Catch all error:  - Cancelled - image resource service - null - #0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"	"#0      _IsolateExecutor.submit (package:executor_lib/src/isolate_executor.dart:69)
#1      PoolExecutor.submit (package:executor_lib/src/pool_executor.dart:38)
#2      VectorTileLoadingCache._loadTile (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:100)
<asynchronous suspension>
#3      VectorTileLoadingCache.retrieve (package:vector_map_tiles/src/cache/vector_tile_loading_cache.dart:41)
<asynchronous suspension>
#4      CachesTileProvider._retrieve (package:vector_map_tiles/src/stream/caches_tile_provider.dart:64)
<asynchronous suspension>
#5      CachesTileProvider._provide (package:vector_map_tiles/src/stream/caches_tile_provider.dart:34)
<asynchronous suspension>
#6      TileLoader._renderTile (package:vector_map_tiles/src/raster/tile_loader.dart:76)
<asynchronous suspension>
"
```

### The OS that Immich Server is running on

Ubuntu 22.04 WSL

### Version of Immich Server

v1.89.0

### Version of Immich Mobile App

v.1.89.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:
  tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.89.0

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=**************************
DB_PASSWORD=**************************

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. use iphone take a live photo with `heic` format
2. use iphone immich app upload the live photo. 
3. use android immich app view that live photo, and click download button at top
4. a `Download Error` message popup
```
