### ISSUE TITLE
[BUG] <Thumbnails waiting kept on increasing even though I dont have this much pictures>

### ISSUE THREAD

**Issue by TajAFK** [immich-app/immich#5660]
### The bug

I had uploaded my library with the help of immich cli. It is successfully finished but thumbnail generation kept going. Currently its 43000 waiting and number is increasing. I dont know whats the issue
![Screenshot 2023-11-21 224751](https://github.com/immich-app/immich/assets/76711189/e86cc58d-973c-4927-9fbe-468852c0c5b8)
![Screenshot 2023-11-21 224751](https://github.com/immich-app/immich/assets/76711189/1ffe8b47-f160-42d4-8183-e1d00c64a88f)

### The OS that Immich Server is running on

Qnap TS251D

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

1.90

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich
services:
  # Main Immich Server service configuration
  immich-server:
    container_name: immich-server # Name of the running container
    image: ghcr.io/immich-app/immich-server:release # Image to be used
    command:
      - start.sh
      - immich
      # Command to be executed upon container start
    ports:
      # Mapping ports from the host OS to the container
      - 2283:3001
    volumes:
      # Mounting directories for persistent data storage
      - /share/homes/taj/immich-app/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Setting environment variables
      TYPESENSE_API_KEY: fGHrdQQ68v4VtBGyABeTUSNkGoX67omBSjiaWH3pwzJWKSd6GV
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: kSsk457L9ACLaG
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
      IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003
    depends_on:
      # Dependencies to ensure the order of service startup
      - redis
      - database
      - typesense
    restart: always # Policy to always restart the container if it stops
  # Configuration for the Immich Microservices
  immich-microservices:
    container_name: immich-microservices # Name of the running container
    image: ghcr.io/immich-app/immich-server:release # Image to be used
    # extends:  # Feature to use configuration from another service (currently commented out)
    #   file: hwaccel.yml
    #   service: hwaccel
    command:
      - start.sh
      - microservices
      # Command to be executed upon container start
    volumes:
      # Mounting directories for persistent data storage
      - /share/homes/taj/immich-app/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Setting environment variables
      TYPESENSE_API_KEY: fGHrdQQ68v4VtBGyABeTUSNkGoX67omBSjiaWH3pwzJWKSd6GV
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: kSsk457L9ACLaG
      DB_DATABASE_NAME: immich
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    depends_on:
      # Dependencies to ensure the order of service startup
      - redis
      - database
      - typesense
    restart: always # Policy to always restart the container if it stops
  # Configuration for Immich Machine Learning service
  immich-machine-learning:
    container_name: immich-machine-learning # Name of the running container
    image: ghcr.io/immich-app/immich-machine-learning:release # Image to be used
    volumes:
      # Mounting directories for persistent data storage model-cache
      - /share/Container/immich-app/model-cache:/cache
    environment:
      # Setting environment variables
      DB_HOSTNAME: immich-postgres
      DB_USERNAME: casaos
      DB_PASSWORD: kSsk457L9ACLaG
      DB_DATABASE_NAME: casaos
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    restart: always # Policy to always restart the container if it stops
  # Configuration for Typesense service
  typesense:
    container_name: immich-typesense # Name of the running container
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd # Image to be used
    environment:
      # Setting environment variables
      - TYPESENSE_API_KEY=fGHrdQQ68v4VtBGyABeTUSNkGoX67omBSjiaWH3pwzJWKSd6GV
      - TYPESENSE_DATA_DIR=/data
      - GLOG_minloglevel=1
    volumes:
      # Mounting directories for persistent data storage tsdata
      - /share/Container/immich-app/tsdata:/data
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: always # Policy to always restart the container if it stops
  # Configuration for Redis service    
  redis:
    container_name: immich-redis # Name of the running container
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46 # Image to be used
    labels:
      - com.centurylinklabs.watchtower.enable=false
    restart: always # Policy to always restart the container if it stops
  # Configuration for Database service
  database:
    container_name: immich-postgres # Name of the running container
    image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07 # Image to be used
    environment:
      # Setting environment variables
      POSTGRES_PASSWORD: kSsk457L9ACLaG
      POSTGRES_USER: casaos
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      # Mounting directories for persistent data storage
      - /share/Container/immich-app/pgdata:/var/lib/postgresql/data
    restart: always # Policy to always restart the container if it stops
networks: {}
```

### Your .env content

```Shell
Not using env...
```

### Reproduction steps

```bash
1.Fresh install of immich
2.Upload the libraries through cli
3.Thumbnail generation kept going
...
```

### Additional information

Can someone please suggest when thumbnail gen will stop if it at all ever stops
