### ISSUE TITLE
[BUG] Can not update feature photo of peoples

### ISSUE THREAD

**Issue by akoyaxd** [immich-app/immich#5674]
### The bug

When I try to update the feature photo of persons, the Web UI tells me the image was updated correctly, but it does not change afterwards.

### The OS that Immich Server is running on

Debian 12 with docker with traefik reverse proxy and Portainer

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`photos.domain.x`)"
      - "traefik.http.services.immich.loadbalancer.server.port=3001"
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always
    ports:
      - 2283:3001
    networks:
      - default
      - traefik-web

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
#    extends:
#      file: hwaccel.yml
#      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../stack.env
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /opt/immich/immich-ml/cache:/cache
    env_file:
      - ../stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
    volumes:
      - /opt/immich/immich-typesense:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    env_file:
      - ../stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/immich/immich-postgres:/var/lib/postgresql/data
    restart: always

networks:
  traefik-web:
    name: traefik-web
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=XXX
DB_DATABASE_NAME=immichdb
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/data/immich/upload
TYPESENSE_API_KEY=XXX
PUBLIC_LOGIN_PAGE_MESSAGE="Some text"
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_VERSION=v1.90.2
```

### Reproduction steps

```bash
1. Upload photos to immich
2. Open photos of a person
3. Select new feature photo
4. Reload Page
5. Feature photo is not updated
```

### Additional information

Logs when I try to update feature photo:
```
}
  "id": "f720bab2-a21b-4032-8da1-cc40751cd152"
	
	
{
	
	
[Nest] 7  - 12/13/2023, 12:34:58 PM   ERROR [JobService] Object:
	
	
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:574:24)
	
	
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:387:28)
	
	
    at async /usr/src/app/dist/domain/job/job.service.js:112:37
	
	
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	
	
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/domain/person/person.service.js:328:58)
	
	
    at MediaRepository.crop (/usr/src/app/dist/infra/repositories/media.repository.js:22:14)
	
	
    at Sharp.extract (/usr/src/app/node_modules/sharp/lib/resize.js:470:38)
	
	
    at Array.forEach (<anonymous>)
	
	
    at Sharp.<anonymous> (/usr/src/app/node_modules/sharp/lib/resize.js:475:16)
	
	
    at Object.invalidParameterError (/usr/src/app/node_modules/sharp/lib/is.js:135:10)
	
	
[Nest] 7  - 12/13/2023, 12:34:58 PM   ERROR [JobService] Error: Expected integer for width but received -2 of type number
	
	
[Nest] 7  - 12/13/2023, 12:34:58 PM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Expected integer for width but received -2 of type number

[Nest] 7  - 12/13/2023, 12:34:56 PM   ERROR [ErrorInterceptor] Error: Request aborted
	
	
[Nest] 7  - 12/13/2023, 12:34:56 PM   ERROR [ErrorInterceptor] Failed to serve file
	
	
I20231213 12:34:53.612052   593 raft_server.h:60] Peer refresh succeeded!
	
	
I20231213 12:34:53.611974   454 raft_server.cpp:546] Term: 141, last_index index: 25294, committed_index: 25294, known_applied_index: 25294, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 618841
	
	
[Nest] 7  - 12/13/2023, 12:34:50 PM   ERROR [ErrorInterceptor] Error: Request aborted
	
	
[Nest] 7  - 12/13/2023, 12:34:50 PM   ERROR [ErrorInterceptor] Failed to serve file
	
	
I20231213 12:34:43.611174   589 raft_server.h:60] Peer refresh succeeded!
	
	
I20231213 12:34:43.611090   454 raft_server.cpp:546] Term: 141, last_index index: 25294, committed_index: 25294, known_applied_index: 25294, applying_index: 0, queued_writes: 0, pending_queue_size: 0, local_sequence: 618841
	
	
[Nest] 7  - 12/13/2023, 12:34:38 PM     LOG [CommunicationRepository] Websocket Connect:    4X2XDk8TrgyIPOBAAAAJ
	
	
[Nest] 7  - 12/13/2023, 12:34:37 PM     LOG [CommunicationRepository] Websocket Disconnect: QKqggC03tstCP6ITAAAD

```
