### ISSUE TITLE
[BUG] Back navigation loop from search results

### ISSUE THREAD

**Issue by rvelasq** [immich-app/immich#5713]
### The bug

This happens on the viewing immich from a browser.
When opening a person from a photo after a search, clicking the back arrow will keep going back and forth between the person view and the search results.

Tested on these browsers

* (MacOS Sonoma 14.2) MS Edge Version 120.0.2210.61
* (MacOS Sonoma 14.2) Safari 17.2
* (iOS 17.2) Mobile Safari

### The OS that Immich Server is running on

Debian 6.1.66-1

### Version of Immich Server

v1.90.2

### Version of Immich Mobile App

v1.90.0 build.130

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
      - immich-machine-learning
      - immich-microservices
    restart: always
    ports:
      - 2283:3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_LOCATION}:/usr/src/app/upload

    env_file:
      - .env
    depends_on:
      - redis
      - database
      - typesense
      - immich-machine-learning
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always
    ports:
      - 3003:3003

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      - GLOG_minloglevel=1
    volumes:
      - ./tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
TZ=Redacted
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/v1/photos/immich-library
TYPESENSE_API_KEY=some-random-characters
TYPESENSE_HOST=typesense
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Type in a search term on the search box.
2. Click on a photo that has a person on it. If there are none, do another search.
3. Click the (i) icon to reveal the photo's metadata.
4. Click on the person's thumbnail.
5. Click the back button on the page (not the browser's back button). This will take you back to the search results.
6. Click the back button again. This will bring you back to the person's page.

Steps 5 and 6 will just repeat if you keep clicking the back button.
```
