### ISSUE TITLE
[BUG] machine-learning container exits errorcode 132

### ISSUE THREAD

**Issue by mrestivill** [immich-app/immich#5715]
### The bug

The container machine-learning keeps restarting exiting with errorcode 132. Seams (searching on internet)  something related to tensorflow and some x86_64 instruction set that is not found on some processors.
```
 Worker (pid:11) was sent code 132!
```

This is the cpuinfo of my system
```
processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 6
model name      : AMD Turion(tm) II Neo N54L Dual-Core Processor
stepping        : 3
microcode       : 0x10000c8
cpu MHz         : 2200.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs            : tlb_mmatch apic_c1e fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips        : 4393.06
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

### The OS that Immich Server is running on

Ubuntu 22.04.3

### Version of Immich Server

v1.90.02

### Version of Immich Mobile App

v1.90.02

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - internal
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
```

### Your .env content

```Shell
.
```

### Reproduction steps

```bash
1. docker-compose up -d
2. docker logs -f immich-machine-learning
3.   Worker (pid:11) was sent code 132!
...
```
