### ISSUE TITLE
[BUG] 1.9.1 deployment failed

### ISSUE THREAD

**Issue by 9k001** [immich-app/immich#5727]
### The bug

The container logs on the microservices side of server show that they are not connected to the database.
It seems that previous environment variables have no effect, such as:
DB_HOSTNAME.
DB_PORT.
DB_USERNAME.
DB_PASSWORD.
DB_DATABASE_NAME.
My PostgreSQL is deployed independently.
I use ansible for standardized deployment.
Confirm that the table has been created: immich.
Confirm that cube,earthdistance,vectors is installed.
Confirm that the container environment has loaded the aforementioned environment variables.
Confirm that there is no problem with v1.89.0 installation and operation.

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.91.0

### Version of Immich Mobile App

v1.91.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.5'
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:{{ IMMICH_VERSION }}
    container_name: immich-server
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/immich-server/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ SERVER_PORT }}:3001"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/server.env
    command: [ "start.sh", "immich" ]
    environment:
      - TZ=Asia/Shanghai

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:{{ IMMICH_VERSION }}
    container_name: immich-microservices
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/immich-server/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ MICROSERVICES_PORT }}:3002"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/microservices.env
    command: [ "start.sh", "microservices" ]
    environment:
      - TZ=Asia/Shanghai

  immich-machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:{{ IMMICH_VERSION }}
    container_name: immich-machine_learning
    restart: always
    volumes:
      - ${APP_DATA_HOME}/project/immich/machine_learning/cache:/cache
    ports:
      - "{{ MACHINE_LEARNING_PORT }}:3003"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/immich/env/machine_learning.env
    environment:
      - TZ=Asia/Shanghai

networks:
  default:
    name: ${MODE_ENV}
    external: true
```

### Your .env content

```Shell
# 数据库 地址
DB_HOSTNAME={{ SERVICE_DB_HOSTNAME }}

# 数据库 端口
DB_PORT={{ SERVICE_DB_PORT }}

# 数据库 账号
DB_USERNAME={{ SERVICE_DB_USERNAME }}

# 数据库 密码
DB_PASSWORD={{ SERVICE_DB_PASSWORD }}

# 数据库 表名
DB_DATABASE_NAME={{ DB_TABLES }}

# Redis 地址
REDIS_HOSTNAME={{ SERVICE_REDIS_HOSTNAME }}

# Redis 端口
REDIS_PORT={{ SERVICE_REDIS_PORT }}
```

### Reproduction steps

```bash
1. Deploy
2. Run
3. Error
```

### Additional information
![image](https://github.com/immich-app/immich/assets/63529476/9e64a9a9-c37e-4dfa-8d15-afd9ceb1a8b9)
![image](https://github.com/immich-app/immich/assets/63529476/d1c297c6-1e4b-4338-8cdd-899e0a61bf1e)

**Comment by bo0tzz** [comment]
Can you post some detail about your postgres installation? It's complaining that it can't find the pgvecto.rs extension.

**Comment by 9k001** [comment]
> Can you post some detail about your postgres installation? It's complaining that it can't find the pgvecto.rs extension.
My postgres is deployed using docker-compose.
```
version: '3.5'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: db-postgres
    restart: always
    tty: true
    volumes:
      - ${APP_DATA_HOME}/project/db/postgres:/var/lib/postgresql/data
    ports:
      - "{{ DB_POSTGRES_PORT }}:5432"
    env_file:
      - ${WORKSPACE_HOME}/{{ DeployRepo }}/db/env/postgres.env
    environment:
      - TZ=Asia/Shanghai

networks:
  default:
    name: ${MODE_ENV}
    external: true
```
