### ISSUE TITLE
[BUG] DST ignored when backing up from mobile

### ISSUE THREAD

**Issue by pig-cop** [immich-app/immich#5741]
### The bug

In my country we set the time one hour back due to DST some weeks ago.
Since then the mobile app continued to apply the time without considering this, so every photo is uploaded one hour in the future.
If I check the metadata from the Immich mobile app before it gets uploaded on the server the time is correct (DST applied) but as soon as it is backed up the time goes one hour ahead.
The result is the photos are uploaded normally and appear in the Recents section or Search but they will not show up in the gallery homepage (Today section) until the time catches up, so one hour later in my case.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.91.0

### Version of Immich Mobile App

v1.91.0 build.115

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${TAG}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${TAG}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
---
```

### Reproduction steps

```bash
1. Take a photo in a country with DST
2. Check the metadata > it has the correct time
3. Photo gets uploaded > DST is ignored and wrong time is applied
```
