### ISSUE TITLE
[BUG] After upgrading to 1.91.0, deadlock in immich_postgresql

### ISSUE THREAD

**Issue by tnys** [immich-app/immich#5759]
### The bug

immich_postgresql container log...

```
2023-12-16 18:57:42.065 UTC [41] FATAL:  the database system is starting up
2023-12-16 18:57:42.099 UTC [1] LOG:  database system is ready to accept connections
2023-12-16 18:57:46.435 UTC [49] ERROR:  deadlock detected
2023-12-16 18:57:46.435 UTC [49] DETAIL:  Process 49 waits for ShareLock on transaction 3012936; blocked by process 48.
	Process 48 waits for AccessExclusiveLock on relation 16911 of database 16384; blocked by process 49.
	Process 49: CREATE EXTENSION IF NOT EXISTS vectors
	Process 48: 
	        ALTER TABLE asset_faces 
	        ALTER COLUMN embedding SET NOT NULL,
	        ALTER COLUMN embedding TYPE vector(512)
2023-12-16 18:57:46.435 UTC [49] HINT:  See server log for query details.
2023-12-16 18:57:46.435 UTC [49] CONTEXT:  while inserting index tuple (0,11) in relation "pg_extension_name_index"
2023-12-16 18:57:46.435 UTC [49] STATEMENT:  CREATE EXTENSION IF NOT EXISTS vectors
```

### The OS that Immich Server is running on

Ubuntu 22.0

### Version of Immich Server

v1.91.0

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/photos-usb:/media/photos-usb:ro
    ports:
      - 2283:3001
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/photos-usb:/media/photos-usb:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /media/photos-usb/immich-model-cache:/cache
      - /media/photos-usb/immich-machine-learning-tmp:/tmp
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /media/photos-usb/immich-pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/photos-usb/immich-library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Upgrade from 1.90.x to 1.91.0
```
