### ISSUE TITLE
Is TAG OBJECTS job supposed to be Disabled [!] state on raspberry pi 5? -- noticed after upgrade to v1.91.1

### ISSUE THREAD

**Issue by SteveDevOps** [immich-app/immich#5765]
### The bug

After upgrading v1.90.1 to v1.91.1 I noticed in jobs that the  TAG OBJECTS job is disabled.. or maybe it was before and I didn't notice? Is this correct state for raspberry pi 5?

### The OS that Immich Server is running on

Rasberry Pi 5 / Raspbian -- Linux rpi5.local 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### Version of Immich Server

v1.91.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/usb/immich/upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxxxxxxxxx
DB_PASSWORD=xxxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. followed breaking changes notes from release notes / altered docker_compose.yml to match -- pulling out typesense
2. ran upgrade command docker compose pull && docker compose up -d
3. reloaded site in browser and went to administration - > job
```

### Additional information

Initially I ran a docker compose up -d after making yml changes from release notes (to pull out typsense) forgetting to do a pull also... then I subsequently ran the correct full command that included the pull (step 2 above).

immich_machine_learning log:

```
[12/16/23 20:14:25] INFO     Starting gunicorn 21.2.0                           
[12/16/23 20:14:25] INFO     Listening at: http://0.0.0.0:3003 (9)              
[12/16/23 20:14:25] INFO     Using worker: app.config.CustomUvicornWorker       
[12/16/23 20:14:25] INFO     Booting worker with pid: 13                        
[12/16/23 20:14:43] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[12/16/23 20:14:43] INFO     Initialized request thread pool with 4 threads.    
[12/16/23 20:19:25] INFO     Loading facial recognition model 'buffalo_l'
```
