### ISSUE TITLE
[BUG] Archive not working after open a photo

### ISSUE THREAD

**Issue by Smiehoo** [immich-app/immich#5780]
### The bug

After open a photo and clicked Archive we get back to photos time line. Archive only working after mark one or more photos.

This bug is not related to 1.91 update ( I encounter from version 1.90 or even before)

### The OS that Immich Server is running on

Google Pixel 6 (Android 14)

### Version of Immich Server

1.91.2

### Version of Immich Mobile App

1.91.0.115

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: Immich-SRV
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: Immich-MCS
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel 
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: Immich-MLR
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/user/docker_files/immich-model:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: Immich-RDS
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: Immich-DB
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/user/docker_files/immich-pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  immich-pgdata:
  immich-model:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/user/docker_files/immich-photos

IMMICH_VERSION=release

DB_PASSWORD=************
DB_HOSTNAME=Immich-DB
DB_USERNAME=***********
DB_DATABASE_NAME=*********

REDIS_HOSTNAME=Immich-RDS

PUBLIC_LOGIN_PAGE_MESSAGE=*******
```

### Reproduction steps

```bash
1. Open Photos on mobile app
2. Click Archive
```
