### ISSUE TITLE
[BUG] Only some map spots open when you click on them

### ISSUE THREAD

**Issue by abstrakct** [immich-app/immich#5784]
### The bug

I'm new to immich, started on v1.89, upgraded to 1.90.2 -> 1.91.0 -> 1.91.2. Noticed this now after upgrading to 1.91.2, not sure if it was like this before, because I hadn't used the map much.

Basically, most spots on the map don't open any images when I click on them. However, some work, but I can't find any obvious pattern, except spots with > 10 images almost never work - except I found one with 12 pics that works... If a spot has < 10, then maybe it works, maybe not.

Some examples:

![2023-12-17-10-48-29](https://github.com/immich-app/immich/assets/182898/2cd6d8ee-3312-47e5-8efe-b95804239f21)
One of these spots open the 2 images there, the other doesn't. Nothing happens when I click. Nothing in the browser console, nothing happens in the devtools network tab.

![2023-12-17-10-52-35](https://github.com/immich-app/immich/assets/182898/6b728335-984f-4480-9ea7-4db0acc1f106)
The spot with 6 pictures opens and I can scroll through them. The spot with 7 does nothing when I click. The spot with just one pic works. All these 14 pictures were taken with the same camera/phone, on the same day.

### The OS that Immich Server is running on

Docker v24.0.7, on Arch Linux

### Version of Immich Server

v1.91.2

### Version of Immich Mobile App

I don't use it yet

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /opt/appdata/immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /opt/appdata/immich-db:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/appdata/immich/library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.91.2

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=redacted
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open map, optionally zoom in
2. Click on any spot with x pictures
3. Either the pictures in that spot open, and you can view them, or nothing happens.
```

### Additional information

In case it matters, yesterday I imported my google takeout using immich-go (about 70GB). 

Before that (a week ago) I had imported many images (around 30GB) I had on my computer.

Location metadata therefore comes either from EXIF data, or google takeout. For some older pictures without location metadata I added location manually. 

But this bug affects all pictures, no matter where the metadata comes from.

My browser is Firefox. Haven't tried any other.

I also tried disabling uBlock origin, even though it doesn't block anything in Immich, with no change.

Same behavior if I use a private window.
