### ISSUE TITLE
[BUG] Some photo metadata doesn't show up when photo is accessed through a `m:<Location>` search

### ISSUE THREAD

**Issue by pedropombeiro** [immich-app/immich#5805]
### The bug

| File retrieved through `m:Feira` | File retrieved by scrolling through Photos |
| ---------------- | ------------- |
| <img width="1350" alt="image" src="https://github.com/immich-app/immich/assets/138074/ba25edf6-d601-42ae-a247-fc7804b74014"> | <img width="1347" alt="image" src="https://github.com/immich-app/immich/assets/138074/b14f1c41-c411-456a-a19c-c0b8a0ef2950"> |

### The OS that Immich Server is running on

QNAP QTS 5.1.4 (Docker)

### Version of Immich Server

v1.91.3

### Version of Immich Mobile App

v1.91.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

networks:
  default:

  database_postgresql:
    external: true
  database_redis:
    external: true
  prometheus_network:
    external: true
  traefik_proxy:
    external: true

secrets:
  db_password:
    file: ../../secrets/immich_db_password
  immich_api_key:
    file: ../../secrets/immich_api_key

x-media-volumes: &media-volumes
  volumes:
    # - ../../config/immich/immich-config.json:${IMMICH_CONFIG_FILE}
    - ${UPLOAD_LOCATION}:/usr/src/app/upload
    - /share/Multimedia/Pictures/Mobile Photos/:/mnt/media/mobilephotos:ro
    - /share/Multimedia/Pictures/Exported/:/mnt/media/photos:ro
    - /share/Multimedia/Video/Home Video/:/mnt/media/homevideo:ro

services:
  immich-server:
    <<: *media-volumes
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: ../common-services.yml
      service: baseapp_in_user_bridge
    command: ["start.sh", "immich"]
    ports:
      - 2283:3001
    env_file:
      - .env
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    networks:
      - default
      - database_postgresql
      - database_redis
      - traefik_proxy
    restart: always

  immich-microservices:
    <<: *media-volumes
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    extends:
      file: ../common-services.yml
      service: baseapp_in_user_bridge
    command: ["start.sh", "microservices"]
    devices:
      - /dev/dri:/dev/dri
    env_file:
      - .env
    environment:
      - DB_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    networks:
      - default
      - database_postgresql
      - database_redis
    depends_on:
      - immich-server
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - default
    volumes:
      - ../../data/immich/machine-learning/cache:/cache
    env_file:
      - .env
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false

  immich-exporter:
    image: ghcr.io/martabal/immich-exporter
    extends:
      file: ../common-services.yml
      service: baseapp_in_user_bridge
    container_name: immich_exporter
    environment:
      - IMMICH_BASE_URL=http://immich-server:3001
      - IMMICH_API_KEY_FILE=/run/secrets/immich_api_key
    secrets:
      - immich_api_key
    expose:
      - 8090:8090
    command: ["/wait-for-it.sh", "immich-server:3001", "/go/bin/immich-exporter"]
    volumes:
      - ./exporter/wait-for-it.sh:/wait-for-it.sh:ro
    networks:
      - default
      - prometheus_network
    depends_on:
      - immich-server
    labels:
      - "org.label-schema.group=monitoring"
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    mem_limit: 128m

  library-helper:
    container_name: immich_library_helper
    image: alpine
    environment:
      - IMMICH_API_KEY_FILE=/run/secrets/immich_api_key
    secrets:
      - immich_api_key
    networks:
      - default
    command: ["/bin/sh", "/monitor-libraries.sh"]
    volumes:
      - ./library-helper/monitor-libraries.sh:/monitor-libraries.sh:ro
      - /share/Multimedia/Pictures/Mobile Photos/:/mnt/media/mobilephotos:ro
      - /share/Multimedia/Pictures/Exported/:/mnt/media/photos:ro
      - /share/Multimedia/Video/Home Video/:/mnt/media/homevideo:ro
    depends_on:
      - immich-server
    restart: unless-stopped
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/share/Multimedia/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# IMMICH_CONFIG_FILE=/config/immich-config.yml

PUID=502
PGID=101

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=postgres
DB_USERNAME=immich
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=redis
```

### Reproduction steps

```bash
1. Enter a search in the Search box containing the `m:` prefix and a known location
2. Click on a resulting photo
3. Open the Info panel from the `i` button
4. Notice that the info panel does not contain the timestamp, file path, or location info.
```
