### ISSUE TITLE
[BUG] (Web) Search Page is throwing an error

### ISSUE THREAD

**Issue by MohamedFBoussaid** [immich-app/immich#5833]
### (Web) Search Page is throwing an error

1. Connect to the Web page using a mobile
2. Click on the search button 

**Result:** 
- An Error page is displayed

**Expected:** 
- The search page should be displayed (Please check screenshoot on the Additional information)

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.91.3

### Version of Immich Mobile App

1.91.3

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

#  immich-machine-learning:
#    container_name: immich_machine_learning
#    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
#    labels:
#      - "com.centurylinklabs.watchtower.enable=false"
#    volumes:
#      - model-cache:/cache
#    env_file:
#      - .env
#    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_backup
    image: prodrigestivill/postgres-backup-local
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 5
      BACKUP_DIR: /db_backup
    volumes:
      - ${DB_BACKUP_LOCATION}:/db_backup
    depends_on:
      - database
    user: 33:1002
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/PI-2048-ST/immich/library
# The location where your daily db backup is stored
DB_BACKUP_LOCATION=/media/PI-2048-ST/immich/db_backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Connect to the Web page using a mobile
2. Click on the search button 

Result: 
- An Error page is displayed

Expected: 
- The search page should be displayed (Please check screenshoot on the Additional information)
```

### Additional information

- If I try to open the search page : `immich-host:2283/search` I am getting the same error
- If I open the web page on mobile on landscape mode, no error is shown as the search box is displayed instead of redirecting to `immich-host:2283/search` 
![IMG_2801](https://github.com/immich-app/immich/assets/52571029/6e662f38-d561-4881-88a2-b41908899954)
