### ISSUE TITLE
[BUG] Buggy metadata search with v1.91.4

### ISSUE THREAD

**Issue by thariq-shanavas** [immich-app/immich#5883]
### The bug

I can now search for location and make/model of the camera using the m: keyword in v1.91.4 after https://github.com/immich-app/immich/pull/5800 has been merged.

However, searching for people or words in the photo description still gives no results.
There is nothing notable in the server or microservices log (with verbose logging level)
Is there any other info I can provide to make debugging easier?

Strangely, "m:300mm" gives results for pictures that were taken with a 70-300mm lens through the whole focal length range, and searching for 50mm or 24mm yields no results (even though there are plenty of pictures taken with all 3 lenses). Very curiously, "m:70mm" produces no results either.

Following search terms give no results: "m:300 mm", "m:50mm", "m:50 mm", "m:24mm", "m:24 mm"

I'll attach example results from "m:300mm" search: https://drive.google.com/drive/folders/1wcQlec88kVet03qwXp6NdrkCixF1QpFK?usp=sharing

Granted, searching by lens/focal length is a niche feature which I never expected to be implemented, I am just documenting possibly buggy behavior.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  redis:
    container_name: immich_redis
    command: redis-server --loglevel warning
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "false"

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
All default values, except DB password and upload location
```

### Reproduction steps

```bash
1. Use the search functionality in the web app with the m: keyword
```
