### ISSUE TITLE
[BUG] Config validation error: "DB_USERNAME" is required. "DB_PASSWORD" is required. "DB_DATABASE_NAME" is required

### ISSUE THREAD

**Issue by zeitchef** [immich-app/immich#5915]
### The bug

The `immich_server` and `immich_microservices` services are restarting in a loop due to an apparent configuration validation error (see attached logs).

### The OS that Immich Server is running on

Debian 12 (OMV6)

### Version of Immich Server

latest

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=<redacted>
IMMICH_VERSION=release
DB_USERNAME=<redacted>
DB_PASSWORD=<redacted>
DB_HOSTNAME=immich_postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
NOTE: I'm installing in OpenMediaVault 6 using the built-in `omv-compose` plugin:

1. Add contents of `docker-compose.yml` and `env` into plugin configs for immich;
2. Adjust `docker-compose.yml` (see above) - excluding references to the `env` file (the plugin manages this itself;
3. Adjust environment variables accordingly in the plugin configuration;
4. Run `up` command.
```

### Additional information

immich_server logs:

```
immich_server  | /usr/src/app/node_modules/@nestjs/config/dist/config.module.js:78
immich_server  |                 throw new Error(`Config validation error: ${error.message}`);
immich_server  |                 ^
immich_server  | 
immich_server  | Error: Config validation error: "DB_USERNAME" is required. "DB_PASSWORD" is required. "DB_DATABASE_NAME" is required
immich_server  |     at ConfigModule.forRoot (/usr/src/app/node_modules/@nestjs/config/dist/config.module.js:78:23)
immich_server  |     at Object.<anonymous> (/usr/src/app/dist/infra/infra.module.js:49:27)
immich_server  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
immich_server  |     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
immich_server  |     at Module.load (node:internal/modules/cjs/loader:1207:32)
immich_server  |     at Module._load (node:internal/modules/cjs/loader:1023:12)
immich_server  |     at Module.require (node:internal/modules/cjs/loader:1235:19)
immich_server  |     at require (node:internal/modules/helpers:176:18)
immich_server  |     at Object.<anonymous> (/usr/src/app/dist/infra/index.js:20:14)
immich_server  |     at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Comment by hoopyfrood** [comment]
Sounds like while you have an `.env` file you are not supplying to your `docker-compose.yml` file. Try adding:

```
    container_name: ...
    env_file: ./.env <-- add this
    image: ...
```

**Comment by zeitchef** [comment]
Thanks @hoopyfrood your comment got me on the right track. Apparently, I can be this stupid :) The problem is I can't reference `env_file` using the plugin in OMV, but I CAN add them to the `environment` table like this:

```
container_name: ...
environment:
  KEY: $VALUE
image: ...
```

**Comment by rivarob** [comment]
> Thanks @hoopyfrood your comment got me on the right track. Apparently, I can be this stupid :) The problem is I can't reference `env_file` using the plugin in OMV, but I CAN add them to the `environment` table like this:
> 
> ```
> container_name: ...
> environment:
>   KEY: $VALUE
> image: ...
> ```

@zeitchef I am brand new to OMV, Immich, and Docker. I am stuck on the same issue as you. Can you walk me through what you did to fix it? apologies if this is not the correct forum for such advice.

**Comment by zeitchef** [comment]
@rivarob I'm going to assume you're using OMV 6 and using the Compose plugin. Basically, to solve my issue I needed to pass the environment variables directly to the services. To do this. I added an `environment:` list and passed each variable under this list as key/value pairs. Here's my working `docker-compose.yml`:

```
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOSTNAME: $DB_HOSTNAME
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    environment:
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      DB_DATABASE_NAME: $DB_DATABASE_NAME
      DB_HOSTNAME: $DB_HOSTNAME
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    environment:
      REDIS_HOSTNAME: $REDIS_HOSTNAME
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_DB: $DB_DATABASE_NAME
    volumes:
      - ${COMPOSE_DATA}/immich/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

A couple of points to remember:
1. Comment out the `extends` list under `immich-microservices` - we're adding variables here directly; and 
2. Make sure to add `$DB_PASSWORD`, `$DB_USERNAME`, and `$DB_DATABASE_NAME` in the `Environment` section of the Compose plugin (you can name them whatever you want).

**Comment by rivarob** [comment]
Thanks so much @zeitchef !!

I spent many hours trying to figure out why `immich-microservices` and `immich-server` were on a reboot loop.

Thanks for posting your solution. I was about to try your solution but then I found  an alternative solution elsewhere, where I had to rename the .env file in the OMV compose plugin to the same name as specified in the compose file and now it works!

The key is renaming this part of the dockercompose.yml downloaded from github 
```
    env_file:
      - .env
```

to 
```
    env_file:
      - immich.env
```

I've posted my compose and .env files below for reference, they are minimally changed from the ones available on the immich github

**compose**
```
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

**immich.env**
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=_redacted_

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=redacted
DB_USERNAME=redacted
DB_DATABASE_NAME=redacted

REDIS_HOSTNAME=redacted
```
