### ISSUE TITLE
[BUG] Some videos won't start to play on iOS (1.91.4)

### ISSUE THREAD

**Issue by markussiebert** [immich-app/immich#5941]
### The bug

I have videos in my gallery that won't play on iOS but do fine in web

### The OS that Immich Server is running on

K8s

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
values:
  # https://github.com/immich-app/immich-charts/blob/main/charts/immich/values.yaml
    image:
      tag: v1.91.4
    immich:
      persistence:
        # Main data store for all photos shared between different components.
        library:
          # Automatically creating the library volume is not supported by this chart
          # You have to specify an existing PVC to use
          existingClaim: immich-data-dir
    postgresql:
      enabled: true
      image:
        repository: tensorchord/pgvecto-rs
        tag: pg14-v0.1.11
      global:
        storageClass: proxmox-data-xfs
        postgresql:
          auth:
            username: immich
            database: immich
            password: immich
      primary:
        initdb:
          scripts:
            create-extensions.sql: |
              CREATE EXTENSION cube;
              CREATE EXTENSION earthdistance;
              CREATE EXTENSION vectors;
    redis:
      enabled: true
      global:
        storageClass: proxmox-data-xfs
      architecture: standalone
      auth:
        enabled: false
    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
      ingress:
        main:
          enabled: true
          hosts:
            - host: immich.stage....
              paths:
                - path: "/"
          tls: []
    microservices:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        pullPolicy: IfNotPresent
    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        pullPolicy: IfNotPresent
      env:
        TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          enabled: true
          size: 8Gi
          # Optional: Set this to pvc to avoid downloading the ML models every start.
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: proxmox-data-xfs
```

### Your .env content

```Shell
??? k8s - above is full config
```

### Reproduction steps

```bash
1. Upload this file (https://www.swisstransfer.com/d/0b84b754-fb99-4747-b1e9-df029de7ff0f)
2. View it on web -> Works
3. View it in iOS App -> Thumbnail is presented, but playback won't start
I find the following in the logs


Catch all error:  - Exception: Invalid image data - image resource service - resolving an image codec - #0      _futurize (dart:ui/painting.dart:6950)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6764)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307)
#3      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2251)
#4      ImageLoader.loadBufferAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:68)
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:121)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:25)
<asynchronous suspension>

...

#0      _futurize (dart:ui/painting.dart:6950)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:6764)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2307)
#3      instantiateImageCodecFromBuffer (dart:ui/painting.dart:2251)
#4      ImageLoader.loadBufferAsync.<anonymous closure> (package:cached_network_image/src/image_provider/_image_loader.dart:68)
<asynchronous suspension>
#5      ImageLoader._load (package:cached_network_image/src/image_provider/_image_loader.dart:121)
<asynchronous suspension>
#6      new MultiImageStreamCompleter.<anonymous closure> (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:25)
<asynchronous suspension>
```
```


### Additional information

_No response_
