### ISSUE TITLE
[BUG] fails to start after postgres db change (1.89->1.91.4), Unknown CLIP model

### ISSUE THREAD

**Issue by Flamewires** [immich-app/immich#5957]
### The bug

No UI shows up, see this in a ```docker logs -f``` on the immich container. Worked fine on 1.89 before update.
```
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)
[Nest] 7  - 12/24/2023, 6:22:36 AM   ERROR [ExceptionHandler] Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
Error: Unknown CLIP model: ViT-H-14::laion2b_s32b_b79k
    at getCLIPModelInfo (/usr/src/app/dist/domain/smart-info/smart-info.constant.js:119:15)
    at UsePgVectors1700713871511.up (/usr/src/app/dist/infra/migrations/1700713871511-UsePgVectors.js:19:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
    at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:260:35)
    at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:148:17)


```

### The OS that Immich Server is running on

docker in arch

### Version of Immich Server

latest

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
ersion: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
#UPLOAD_LOCATION=./library
UPLOAD_LOCATION=/ssd/immich/backup

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=<REDACTED>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.docker-compose pull && docker-compose up -d
2.docker logs -f <immich server container>
...
```

### Additional information

Db appears to be up, docker logs -f on it shows:
```

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-12-24 06:07:01.934 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-12-24 06:07:01.934 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-12-24 06:07:01.934 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-12-24 06:07:01.936 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-12-24 06:07:01.938 UTC [27] LOG:  database system was shut down at 2023-12-24 06:06:54 UTC
2023-12-24 06:07:01.942 UTC [1] LOG:  database system is ready to accept connections

```
