### ISSUE TITLE
Smart search shows irrelevant results

### ISSUE THREAD

**Issue by Chuckame** [immich-app/immich#5996]
### The bug

Searching with any word or sentence always returns all the photos, both in webapp or android app. Expecting some filters or no result. 

Screenshots:
![Screenshot_20231227-014712](https://github.com/immich-app/immich/assets/16419143/5d145cc9-6698-43ac-a737-834f0fb4cf6f)
![Screenshot_20231227-014618](https://github.com/immich-app/immich/assets/16419143/f7a5bf8f-35ae-4901-9661-63898d123663)
![Screenshot_20231227-014553](https://github.com/immich-app/immich/assets/16419143/cc95fb56-054b-466f-b93c-398f8f2b131d)

I only put 4 photos on the immich instance for reproduction, but it's the same with my personal photos. 

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - internal
      - caddy
    labels:
      caddy: media.home.chuckame.fr
      caddy.reverse_proxy: '{{upstreams http 3001}}'

  microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - internal

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal

  redis:
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped
    networks:
      - internal

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  pgdata:
  model-cache:

networks:
  caddy:
    external: true
  internal:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/user/Photos/immich

IMMICH_VERSION=v1.91.4

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=redis
```

### Reproduction steps

```bash
1. Upload photos
2. Search with any word/sentence
3. Results always showing all the photos
```

### Additional information

- all machine learning stuff enabled 
- jobs appeared (tagging, face reco,...) well on the jobs screen
- no error/abnormal log in any of the services
