### ISSUE TITLE
[BUG] Missing Details & Stuck Info Screen on Landscape (iOS)

### ISSUE THREAD

**Issue by Swamp2k9** [immich-app/immich#6025]
### The bug

I've encountered the following bugs in Immich when viewing image information in landscape mode:

1. Missing Image Details: The details of some images are not visible in landscape mode, though they appear normally in portrait mode. This seems to occur specifically with images that lack geolocation information in their metadata.

2. Info Screen Closure Issue: I am unable to close the image information screen in landscape mode. Attempting to drag down the screen inadvertently brings up the Apple Notification Center.

These issues significantly affect the usability of the application in landscape mode and seem to be related to how the app handles images without geolocation data.

### The OS that Immich Server is running on

Debian 12.0

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build.132

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Autoupdate feature.

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Autoupdate feature.

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Autoupdate feature.

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Autoupdate feature.

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true" # Autoupdate feature.

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.  Select an Image Without Detailed Metadata: Browse through your image library and open an image that is known to lack detailed metadata, particularly geolocation information.

2.  Access Image Information: In the image viewer, locate and click/tap the "Info" button. This action should open a panel displaying the image's metadata and details.

3.  Observe the Results in Landscape Mode: Rotate your device to switch to landscape mode (if not already in this mode).

4.  Attempt to Close the Info Screen: Try closing the information screen by dragging down.
```
