### ISSUE TITLE
[BUG] Motion photos are very low fps

### ISSUE THREAD

**Issue by Inrego** [immich-app/immich#6059]
### The bug

When playing back motion photos from either web interface or Android app (so anywhere, really), they seem to be very low FPS. Something like 2 fps.
In Google Photos, it's a smooth video.
Photos are taken with a Pixel phone.

### The OS that Immich Server is running on

Docker on Ubuntu

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build.116

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    hostname: immich
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - /raid/photos/immich:/usr/src/app/upload
      - /raid/photos:/raid/photos
    env_file:
      - /docker-volumes/compose/secrets/immich.env
    depends_on:
      - redis
      - database
    networks:
      - web
      - immich
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    volumes:
      - /raid/photos/immich:/usr/src/app/upload
      - /raid/photos:/raid/photos
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - /docker-volumes/compose/secrets/immich.env
    depends_on:
      - redis
      - database
    networks:
      - web
      - immich
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - /docker-volumes/immich/ml-cache:/cache
    env_file:
      - /docker-volumes/compose/secrets/immich.env
    networks:
      - immich
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always
    networks:
      - immich  
  
  database:
    container_name: immich_postgres
    hostname: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - /docker-volumes/compose/secrets/immich.env
    volumes:
      - /docker-volumes/immich/db:/var/lib/postgresql/data
    networks:
      - web
    restart: always


networks:
  web:
    name: web
    external: true
  immich:
```

### Your .env content

```Shell
mostly just passwords, so not pasting here
```

### Reproduction steps

```bash
1. Take motion photo
2. Upload with app
3. Play back photo
```
