### ISSUE TITLE
[BUG] database connection reset

### ISSUE THREAD

**Issue by useib** [immich-app/immich#6060]
### The bug

During upload of assets some jobs (generate thumbnails, extract metadata, smart search, recognize faces, transcode videos, storage template migration) fail. Database log shows unexpected eof and connection reset by peer.
[_immich_postgres_logs.txt](https://github.com/immich-app/immich/files/13797821/_immich_postgres_logs.txt)
[_immich_microservices_logs.txt](https://github.com/immich-app/immich/files/13797833/_immich_microservices_logs.txt)

### The OS that Immich Server is running on

Docker in a Debian 12 VM on Proxmox 8.1.3

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 (iOS)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Photo/Lightroom:/mnt/media/Lightroom:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Photo/Lightroom:/mnt/media/Lightroom:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped
    volumes:
      - redisdata:/data  

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  model-cache:
  redisdata:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/Photo/Immich
IMMICH_VERSION=release
DB_PASSWORD=#redacted#
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. docker compose up -d
2. Create admin user
3. Connect mobile app to server
4. Backup photos from mobile app
```

### Additional information

started the database container manually for initialization "docker compose up database -d" before deploying the compete stack "docker compose down database and docker compose up -d".
