### ISSUE TITLE
[BUG] Unable to access after updating from v1.19.0 to v1.19.4

### ISSUE THREAD

**Issue by s3cst4rs** [immich-app/immich#6072]
### The bug

~/immich$ docker-compose up
Creating network "immich_default" with the default driver
Creating immich_postgres         ... done
Creating immich_machine_learning ... done
Creating immich_redis            ... done
Creating immich_server           ... done
Creating immich_microservices    ... done
Attaching to immich_machine_learning, immich_redis, immich_postgres, immich_server, immich_microservices
immich_machine_learning    | [12/31/23 03:38:51] INFO     Starting gunicorn 21.2.0
immich_machine_learning    | [12/31/23 03:38:51] INFO     Listening at: http://0.0.0.0:3003 (9)
immich_machine_learning    | [12/31/23 03:38:51] INFO     Using worker: app.config.CustomUvicornWorker
immich_machine_learning    | [12/31/23 03:38:51] INFO     Booting worker with pid: 13
immich_postgres            |
immich_postgres            | PostgreSQL Database directory appears to contain a database; Skipping initialization
immich_postgres            |
immich_postgres            | 2023-12-31 03:38:51.414 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich_postgres            | 2023-12-31 03:38:51.415 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich_postgres            | 2023-12-31 03:38:51.415 UTC [1] LOG:  listening on IPv6 address "::", port 5432
redis_1                    | 1:C 31 Dec 2023 03:38:51.210 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1                    | 1:C 31 Dec 2023 03:38:51.210 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1                    | 1:C 31 Dec 2023 03:38:51.210 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1                    | 1:M 31 Dec 2023 03:38:51.210 * monotonic clock: POSIX clock_gettime
redis_1                    | 1:M 31 Dec 2023 03:38:51.211 * Running mode=standalone, port=6379.
redis_1                    | 1:M 31 Dec 2023 03:38:51.211 # Server initialized
redis_1                    | 1:M 31 Dec 2023 03:38:51.211 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1                    | 1:M 31 Dec 2023 03:38:51.211 * Ready to accept connections
immich_postgres            | 2023-12-31 03:38:51.438 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich_postgres            | 2023-12-31 03:38:51.487 UTC [27] LOG:  database system was shut down at 2023-12-31 03:38:46 UTC
immich_postgres            | [2023-12-31T03:38:51Z INFO  vectors::utils::clean] Find directory "pg_vectors/indexes/17302".
immich_postgres            | [2023-12-31T03:38:51Z INFO  vectors::utils::clean] Find directory "pg_vectors/indexes/17301".
immich_postgres            | [2023-12-31T03:38:51Z INFO  vectors::utils::clean] Find directory "pg_vectors/indexes/17302/segments/d46bb749-ea36-4103-a410-39d6b6beb3f2".
immich_postgres            | [2023-12-31T03:38:51Z INFO  vectors::utils::clean] Find directory "pg_vectors/indexes/17301/segments/95a97d8c-d580-429c-b11e-541dc562e676".
immich_postgres            | 2023-12-31 03:38:51.566 UTC [1] LOG:  database system is ready to accept connections
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [SystemConfigService] LogLevel=log (set via system config)
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [MetadataRepository] Initializing metadata repository
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [MetadataService] Initialized local reverse geocoder
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [NestFactory] Starting Nest application...
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] ConfigModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] InfraModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] DomainModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [NestApplication] Nest application successfully started
immich_microservices       | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [ImmichMicroservice] Immich Microservices is listening on http://[::1]:3002 [v1.91.4] [PRODUCTION]
immich_server              | [Nest] 7  - 12/31/2023, 3:38:53 AM     LOG [SystemConfigService] LogLevel=log (set via system config)
immich_machine_learning    | [12/31/23 03:38:56] INFO     Created in-memory cache with unloading after 300s
immich_machine_learning    |                              of inactivity.
immich_machine_learning    | [12/31/23 03:38:56] INFO     Initialized request thread pool with 4 threads.
redis_1                    | 1:M 31 Dec 2023 03:43:52.013 * 100 changes in 300 seconds. Saving...
redis_1                    | 1:M 31 Dec 2023 03:43:52.013 * Background saving started by pid 22
redis_1                    | 22:C 31 Dec 2023 03:43:52.027 * DB saved on disk
redis_1                    | 22:C 31 Dec 2023 03:43:52.027 * RDB: 0 MB of memory used by copy-on-write
redis_1                    | 1:M 31 Dec 2023 03:43:52.114 * Background saving terminated with success

Unable to access
![image](https://github.com/immich-app/immich/assets/117639542/67cb4886-05ce-4aa0-b627-7b1b5a64fda5)

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.19.4

### Version of Immich Mobile App

v1.19.4

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 30041:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  upload:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.xxx.xx,nfsvers=4"
      device: ":/mnt/MyPool/Immich/Upload"
  pgdata:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.xxx.xx,nfsvers=4"
      device: ":/mnt/MyPool/Immich/Pgdata"
  cache:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.xxx.xx,nfsvers=4"
      device: ":/mnt/MyPool/Immich/Cache"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.docker-compose pull && docker-compose up -d
```
