### ISSUE TITLE
[BUG] Unsupported file type IMG_0707.largeThumbnail

### ISSUE THREAD

**Issue by benatard9** [immich-app/immich#6084]
### The bug

When backing up iPhone 12 Pro album via Immich iOS app (1.91.4 build.132), certain photos raise an error in AssetService - e.g. "Unsupported file type IMG_0707.largeThumbnail". The photos themselves are unable to be shared from the iPhone via the Photos app. When I attempt to share these files, iOS rejects it and shows error message "Unable to share. There was an error while preparing to share." So this seems like an iOS problem, but this iOS problem halts the entire backup. It would be very helpful if the errors were logged and the backup still continued with the remainder of the files.

immich server logs attached.
[immich_server_logs.txt](https://github.com/immich-app/immich/files/13802245/immich_server_logs.txt)

### The OS that Immich Server is running on

RHEL8.9

### Version of Immich Server

1.91.4

### Version of Immich Mobile App

1.91.4 build.132

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION="/srv/raid/immicher/upload"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.91.4"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=redacted

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.On Immich App upper right corner, click Backup button
2.Select "Recents (All)" Album
3.Click "Start Backup"
4.Wait until backup fails (first occurrence) or hangs indefinitely (subsequent attempts to load after first failure).
```
