### ISSUE TITLE
[BUG] duplicate file name(different directory) cause upload failure

### ISSUE THREAD

**Issue by kkyeer** [immich-app/immich#6085]
### The bug

I've got an iPhone on which I installed immich(Great app),but failed to upload 8 videos as described below.Did some digging,seems relative to duplicate file names.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build.132

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    ports:
      - 65532:3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:3995fe6ea6a619313e31046bd3c8643f9e70f8f2b294ff82659d409b47d06abb
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11 
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/nnas/picture

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.91.4

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=asdffghhhhh
DB_PASSWORD=7ygfdcvb

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Place two video into mobile device(mine is iPhone 12 mini,the file is imported by iTunes backup from a previous iPhone)
2. Start backup
3. The first photo upload successfully into the library,can be seen in web console/file system,and marked synced on mobile
4. The second photo upload showes success,but can not be seen in web console/file system,and doesn't marked synced on mobile,stayes unsync and will try to sync every time.
```

### Additional information

1. There is no error log in both mobile and docker logs(server&micro-service)
2. The two videos were shot in diffrent year, so I assume should be in diffrent directory on server side
3. The two videos are both shown in "Recent Items" Album (Mine is different language,translated like this)
4. More information is been digging,I sure hope I can solve this by myself,learning TypeScript,need time
