### ISSUE TITLE
Issues with machine learning since 1.91.0

### ISSUE THREAD

**Issue by GlenSatchwell** [immich-app/immich#6089]
### The bug

Hey! Absolutely loving Immich so far!

Upgrading to 1.91.0 and also the minor versions (1.91.4) everything started back up fine. I made sure my docker-compose was using the correct changes for "tensorchord/pgvecto-rs:pg14-v0.1.11".

Everything was fine until I noticed that faces were no longer showing newer photos and only existing matched photos.

There's also some weird search bugs happening. I know that the switch from typesense has caused some features to need rebuilding but when searching without metadata the search on both web/mobile it loads forever and eventually causes a 500.

The main bug is relating to the People/Faces, when logging the immich_postgres container, I can see an error below:

`ERROR:  column faces.embedding does not exist at character 370
`

Hoping someone can assist with what could have caused this?

Thanks! ❤️

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 Build 116

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always
  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
    volumes: [HIDDEN FOR PRIVACY]
    depends_on:
      - database
    restart: always
volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
# The location where your uploaded files are stored
UPLOAD_LOCATION=[HIDDEN FOR PRIVACY]
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=
# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Login to web.
2. Visit Adminstration -> Job Status.
3. Rerun all Recognise Faces.

This will wipe all existing faces which I didn't mind since I can recreate them after. Since rerunning this, no faces are detected and the above error is shown in postgres logs.
```
