### ISSUE TITLE
[BUG] swipe forward, swipe backward and back buttons stop working on shared albums (and shared grouped pictures) after zooming in on one picture during swiping

### ISSUE THREAD

**Issue by arpanghosh8453** [immich-app/immich#6109]
### The bug

The title says it all.

Just to clarify, it works fine on the interface itself when logged in as a user/owner. The bug exists when visiting the shared album/grouped photo page. It works fine there too until you pinch or scroll to zoom on one specific picture during swiping. Then neither the swipe buttons nor the back buttons work anymore. you will need to reload the whole webpage to go back. 

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

V1.91.4 (Latest)

### Version of Immich Mobile App

Latest

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/archive-read-only:/mnt/media/Pictures:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    #ports:
    #  - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      proxy-network:

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/archaive-read-only:/mnt/media/Pictures:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      proxy-network:

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      proxy-network:

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:60e49e22fa5706cd8df7d5e0bc50ee9bab7c608039fa653c4d961014237cca46
    restart: unless-stopped
    networks:
      proxy-network:

  database:
    container_name: immich_postgres
    #image: postgres:14-alpine@sha256:6a0e35296341e676fe6bd8d236c72afffe2dfe3d7eb9c2405c0f3fc04500cd07
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      proxy-network:

volumes:
  pgdata:
  model-cache:

networks:
  proxy-network:
    external: true
    name: proxy-network
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/immich-sync

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.91.4
TZ=America/Toronto
LOG_LEVEL=log
# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=[REDACTED]
DB_PASSWORD=[REDACTED]

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create a sharable public link for an album
2. go to the link, open an image, and try the back and swipe buttons ( they work just fine )
3. Now, while swiping, scroll to zoom or pinch to zoom on one image ( the zooming will work fine )
4. The back and swipe buttons will not work anymore.
```
