### ISSUE TITLE
[BUG] New photos in external libraries not shown after automatic library scan

### ISSUE THREAD

**Issue by dekiesel** [immich-app/immich#6122]
### The bug

I have library scanning set up (under an administrator account) like this
![image](https://github.com/immich-app/immich/assets/17333827/a8efeb41-6f7c-4b20-aa0f-b1111a038f67)

But new pictures aren't shown after the run. I have to "Rescan new library files" as the user that added the external library: 

"Account Settings"->Libraries->three dot menu next to the library->"Scan New Library Files".

### The OS that Immich Server is running on

Alpine 3.18

### Version of Immich Server

1.94

### Version of Immich Mobile App

1.94

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICHUPLOADDIR}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/samba/sambaserver/storaged:/mnt/users/d/samba/sambaserver/storaged:ro
      - /mnt/samba/sambaserver/storagej:/mnt/users/j/samba/sambaserver/storagej:ro
      - /mnt/htpc:/mnt/users/d/htpc:ro
    env_file:
      - .env
    ports:
      - 80:3001
    depends_on:
      - redis
      - database
    restart: always
    logging:
      driver: "syslog"
      options:
        tag: "immich-server"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${IMMICHUPLOADDIR}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/samba/sambaserver/storaged:/mnt/users/d/samba/sambaserver/storaged:ro
      - /mnt/samba/sambaserver/storagej:/mnt/users/j/samba/sambaserver/storagej:ro
      - /mnt/htpc:/mnt/users/d/htpc:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MLMODELCACHE}:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${MYPGDATA}:/var/lib/postgresql/data
    restart: always

immich:~/app#
```

### Your .env content

```Shell
# Custom
IMMICHUPLOADDIR=/root/app/persistant-data/immich/uploads
MLMODELCACHE=/root/app/persistant-data/ml/model-cache
MYPGDATA=/root/app/persistant-data/postgres/data
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION="v1.91.4"

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<mysecretpw>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Set up an external library as a user
2. set up library scanning as an administrator
3. wait for the next scan
4. see no new images as the user
...
```
