### ISSUE TITLE
[BUG] Syncing completed. (But not really?)

### ISSUE THREAD

**Issue by illnesse** [immich-app/immich#6170]
### The bug

If i click "Start Backup" it uploads 

Syncing completed. Changes: true
From AlbumService

but has still 83 items remaining

![immich2](https://github.com/immich-app/immich/assets/40355982/e401b855-5208-4e36-b3d1-27cfeba0e881)

Maybe due to the fact that some of these items have already been uploaded to the external library via the nextcloud app?

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/crypt1/:/media/crypt1/:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
     #extends:
       #file: hwaccel.yml
       #service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /media/crypt1/:/media/crypt1/:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/crypt1/Immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=[redacted]
DB_PASSWORD=[redacted]
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=[redacted]
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. upload files via app
2. wait till finish
3. observe that they never actually get marked as uploaded
```
