### ISSUE TITLE
[BUG] some local images are missing (/ ignored / not recognized) in immich app

### ISSUE THREAD

**Issue by Hyffer** [immich-app/immich#6196]
### The bug

I am using the official android app to back up my photos. The app works great and It detect all picture folders, except that some of images are missing in immich app. (The missing images is visible in my phone's native gallery app. And other images in the same directory as the missing ones are showing up correctly in immich.)

I suppose the metadata of image is to be blame. Although I am not familiar with exif kind of things, another gallery app (Les Pas, shows the image, but) says the image size is 0w*0h, which is definitely incorrect. The image is posted below.
![-990f2baad6699c6](https://github.com/immich-app/immich/assets/58105986/0980339b-774a-403c-9477-4c3f4dc1a6b3)

(to avoid picture got compressed and metadata got lost, I also make it a zip pack)
[-990f2baad6699c6.jpg.zip](https://github.com/immich-app/immich/files/13843655/-990f2baad6699c6.jpg.zip)

Now I guess that the immich app actually do read in this image, but due to some metadata related errors, it skips this one. (But I don't see anything related in logs)

BTW in most cases it should not be a problem, photos we take will have correct metadata. My situation is this "broken" image is saved from a chat app (QQ, which is commonly used in China), and lots of images saved from it have the same issue (like the size 0w*0h I mentioned).

### The OS that Immich Server is running on

ubuntu 22.04

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
(This problem should has nothing to do with server.)

version: "3.8"
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./immich-library
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. On Android(I don't know if iOS has the same thing), download the picture I posted and copy it to image folder
2. You can see it does not show up in immich app
```
