### ISSUE TITLE
[BUG] Live photos correctly display in Chrome but display as individual photos and videos in iOS Client

### ISSUE THREAD

**Issue by AngelPone** [immich-app/immich#6251]
### The bug

The Live Photos in my library are correctly identified and displayed in Chrome, but display as individual photos and videos in iOS Client.  

### The OS that Immich Server is running on

Ubuntu 22.10

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4 build.132

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2451:3001
    depends_on:
      - redis
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=192.168.50.100
DB_USERNAME=immich
DB_PASSWORD=immich
DB_DATABASE_NAME=immich

# Optional Database settings:
DB_PORT=5432
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/path/to/location
PORT=3000
SERVER_PORT=3001
MICROSERVICES_PORT=3002
MACHINE_LEARNING_HOST=0.0.0.0
MACHINE_LEARNING_PORT=3003
IMMICH_VERSION=release
```

### Reproduction steps

```bash
1. I disabled the access to photo library of immich app. Thus, the app only displays Photos uploaded in the cloud.
2. The live photos are uploaded into the library through immich cli.
2. All Live photos are correctly displayed in Chrome, but are shown as individual photos and videos in iOS app.
```
