### ISSUE TITLE
[BUG] Failed login attempt after upgrading to 1.92.0

### ISSUE THREAD

**Issue by tomsik-radek** [immich-app/immich#6255]
### The bug

After upgrading to 1.92.0 any new login attempts into Immich will fail. Mobile app on my phone can still connect and access files (I don't want to risk logging out now).

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.92.0

### Version of Immich Mobile App

v1.92.0 build.117

### Platform with the issue

- [X] Server
- [X] Web
- [x] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    ports:
      - 2283:3001
    networks:
      - reverse_proxy

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - reverse_proxy

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    networks:
      - reverse_proxy

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    networks:
      - reverse_proxy

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee

    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - reverse_proxy

volumes:
  pgdata:
  model-cache:

networks:
  reverse_proxy:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=[redacted]
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/media/nas1/apps/immich/upload
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_VERSION=v1.92.0
TZ=Europe/Prague
```

### Reproduction steps

```bash
1. Upgrade to 1.92.0
2. Log out of web app
3. Can't log back in on any user
```

### Additional information

Using Portainer.
Immich is behind NGINX Proxy Manager - issue happens with or without it (ie accessing server:port directly)

Docker log from Portainer

```[Nest] 6  - 01/08/2024, 1:32:33 PM     LOG [NestApplication] Nest application successfully started

[Nest] 6  - 01/08/2024, 1:32:33 PM     LOG [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.92.0] [PRODUCTION] 

[Nest] 6  - 01/08/2024, 1:32:43 PM    WARN [AuthService] Failed login attempt for user [user1] from ip address 10.0.2.77

[Nest] 6  - 01/08/2024, 1:33:04 PM     LOG [CommunicationRepository] Websocket Connect:    oqhqnHch9a3TOmwTAAAB **this is where mobile app still logs in**

[Nest] 6  - 01/08/2024, 1:33:28 PM    WARN [AuthService] Failed login attempt for user [user1] from ip address 10.0.2.77

[Nest] 6  - 01/08/2024, 1:33:42 PM     LOG [CommunicationRepository] Websocket Disconnect: oqhqnHch9a3TOmwTAAAB

[Nest] 6  - 01/08/2024, 1:35:43 PM     LOG [CommunicationRepository] Websocket Connect:    M7NWAGA2oc1UQZnhAAAD

[Nest] 6  - 01/08/2024, 1:35:58 PM     LOG [CommunicationRepository] Websocket Disconnect: M7NWAGA2oc1UQZnhAAAD

[Nest] 6  - 01/08/2024, 1:37:03 PM    WARN [AuthService] Failed login attempt for user [user2] from ip address ::ffff:10.0.2.77

[Nest] 6  - 01/08/2024, 1:37:10 PM    WARN [AuthService] Failed login attempt for user [user1] from ip address ::ffff:10.0.2.77```
