### ISSUE TITLE
Always copy the shared link URL

### ISSUE THREAD

**Issue by maxheadroom** [immich-app/immich#6280]
### The bug

I've created a public share link for an album and set a password for the album. At the bottom of the "create a link to share"  dialog will be the generated link displayed and a large "Copy" button. The link itself can't be selected as it's truncated. The "Copy" button puts a string in the clipboard which looks like this:

```
Link: https://immich.mydomain.net/share/2Ij8M1f323hgAFeZro6J5-PKstr9-UWCQX_K3NOD1SJ681s_Y3Da-9Gzr4BPL-31LuE
Password: immichpassword

```

Pasted in a browsers address bar, this strong wont work anyway. 

I think the correct behaviour should be to just copy the URL, nothing else. The password shouldn't be copied to the clipboard. 

### The OS that Immich Server is running on

docker-compose from official images

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

none

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
networks:
    web:
        name: web
        external: true
    internal:
        name: internal
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
      - web
    env_file:
      - .env
    ports:
      - 2283:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich.rule=Host(`immich.mydomain.net`)"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=letsencrypt"
      - "traefik.http.services.immich.loadBalancer.server.port=3001"
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - internal

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - internal

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=fslkdfjlsdfjk

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create Album
2. Create Public Share Link with Password protection
3. Copy the generated Link
```
