### ISSUE TITLE
[BUG] iOS Background Upload Not Running

### ISSUE THREAD

**Issue by uninvitedguest** [immich-app/immich#6281]
### The bug

I am finding that the background sync on my partner's iPhone is not working/triggering at all, despite foreground sync working flawlessly.

### The OS that Immich Server is running on

Proxmox 8.0.4 -> Turnkey Core 17.1 / Debian 11

### Version of Immich Server

1.9.3

### Version of Immich Mobile App

1.9.3

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - immich-internal

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    environment:
      - TZ=TZ
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - immich-internal

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - immich-internal

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped
    networks:
      - immich-internal
    labels:
      com.centurylinklabs.watchtower.enable: "false"

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      #PG_DATA: /var/lib/postgresql/data
    volumes:
      - /database:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich-internal
    labels:
      com.centurylinklabs.watchtower.enable: "false"

volumes:
  pgdata:
  model-cache:

networks:
  immich-internal:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=hostname
DB_USERNAME=username
DB_PASSWORD=password
DB_DATABASE_NAME=database
REDIS_HOSTNAME=redis
UPLOAD_LOCATION=upload
TZ=TZ
IMMICH_VERSION=release
```

### Reproduction steps

```bash
1. Configure iOS application to enable foreground and background uploads (no charging restriction)
2. While open, Immich app uploads without issue in the foreground
3. While closed, Immich app does not upload images in the background (e.g. last uploaded images were from Dec 7th while keeping the app open for a foreground upload).
4. 2 Background processes are listed as queued. Dec 8th, 12:37 is the last time the application was opened. As of 16:15 pm logs do not indicate anything uploaded
```

### Additional information

1. iPhone 13
2. iOS 17.1.2
3. iCloud optimized images is turned on.
4. In iOS general settings, every background refresh service is disabled except Immich.
