### ISSUE TITLE
[BUG] Photo's on iCloud which are downloaded for Immich Upload have weird Duplicate Behaviour

### ISSUE THREAD

**Issue by ChristopherFunk** [immich-app/immich#6295]
### The bug

I have photo's uploaded on iCloud and removed from my device via Optimize iPhone Storage. When immich goes to upload these photo's it first downloads them, and then uploads them. However, once they are uploaded, there are duplicates of many photo's, and other photo's are missing.

This does not happen with new photo's taken, only appears to be after they are optimized by iCloud via the Optimize iPhone Storage setting in iCloud Photo's

- iOS Photo's App:
![iOS Library View](https://github.com/immich-app/immich/assets/8630493/ddb70274-2d9f-4ff9-82a8-e4b541a0df2d)

- immich app view:
![immich ios app library view](https://github.com/immich-app/immich/assets/8630493/8fe08d3c-c162-4dce-a943-d553dd90c35f)
- note the long cat in the bottom left, with the photo liked with the heart

- immich web view:
![immich web view](https://github.com/immich-app/immich/assets/8630493/aebec5da-0b35-47e6-b845-4a603b48de41)

- note here, there are many duplicates, when I delete these duplicates from the web view, the ios app shows the photo's need to be re-uploaded but it uploads the duplicates, note the missing long cat, and other photo's
- this happens a lot in my library from what I can tell
- when I download the photo's from the web view, they are the duplicate photo's that they appear to be

### The OS that Immich Server is running on

Ubuntu Server 22.04

### Version of Immich Server

v1.91.4

### Version of Immich Mobile App

v1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /mnt/config/configs/immich/model-cache:/cache
    env_file:
      - stack.env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /mnt/config/configs/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/md0/immich
IMMICH_VERSION=release
TYPESENSE_API_KEY=Ehz_RKw9__BLZ3b9u!yBTQJE!aVzfH_G
DB_PASSWORD=EJC*qyx2xnb3rvq2qek
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
REVERSE_GEOCODING_PRECISION=3
```

### Reproduction steps

```bash
1. Set iPhone Photo's to Optimize iPhone Storage
2. Have Older Photo's in your iPhone Photo's App
3. Let Immich Upload these, where it downloads from iCloud and uploads to immich
4. View on Web and Mobile App, notice discrepancy
```

### Additional information

- my docker-compose is running on portainer, that's why the `env_file` is set as `- stack.env`
