### ISSUE TITLE
[BUG] External library doesn't follow relative symlinks

### ISSUE THREAD

**Issue by forerunnert** [immich-app/immich#6311]
### The bug

I have a large collection of photo's a part of which I added to Immich using an external library.

The collection is a folder on the server (a zfs volume mounted from NAS) with both sub-folders with actual files and relative symbolic-links to other locations on the same volume:

/folderA/folderB/collection/2020
/folderA/folderB/collection/2021
/folderA/folderB/collection/2022 -> ../../other_location/2022
/folderA/folderB/collection/2023 -> ../../other_location/2023

After adding the collection folder as /mnt/media/collection to immich files found in /2020 and /2021 are found and processed but /2022 and /2023 (the relative symlinks) are not.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.92.1 and v1.92.0

### Version of Immich Mobile App

v1.92.0 build 117

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /folderA/folderB/collection:/mnt/media/collection:ro

    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /folderA/folderB/collection:/mnt/media/collection:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/folderA/folderB/Immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<passwd>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. create a collection folder containing folders with files:
     /folderA/folderB/collection/2020
2. add a relative symlink to the collection pointing to a sub-level of collection:
    /folderA/folderB/collection/2022 -> ../../other_location/2022
3. Scan new library files: /2020 files are found, 2022 are not
```
