### ISSUE TITLE
[BUG] Files missing after CLI upload

### ISSUE THREAD

**Issue by fritut08** [immich-app/immich#6380]
### The bug

I am experiencing the same problem as described in issue #2698: After uploading files through the immich cli, they can be found in the filesystem but do not show up in immich. All jobs in the administration section were run multiple times without an issue since. Unfortunately, unlike the author of #2698, the pictures were not simply organized into a date he did not expect.

What I did was uploading folders with the cli using the `--album`option. For at least 5 folders, the resulting album did not consist of the same number of files as the original folder. For example, one folder had 8 pictures and one video taken on 2023-03-18. All of these were successfully transferred into the folder on immich's filesystem that I expected (since the storage template I picked had the date in it). However, only 5 pictures and the video appear in the web or mobile app of immich. This was a few days ago and I do not recall any errors from the cli.

What I tried since (to no avail):

- restart the system
- triggering all jobs in the administration section
- reuploading through the cli

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm) LXC within Proxmox

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.0 build.117 (seems irrelevant to me)

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/hdd

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=MYRANDOMPASSWORD

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.  On the system containing the pictures, I executed `immich upload --ignore **/*.arw --album --recursive 2023-03-18\ Skifahren\ Montafon/`
2.  On the system running immich, I went to the folder where I expected the files: `cd /mnt/hdd/library/.../2023-03-18
3.  There are all 9 files that I was expecting to see.
4.  Using the web or mobile app, I cannot find 3 of the pictures anywhere. The newly created album "Skifahren Montafon" only contains 6 files.
```
