### ISSUE TITLE
[BUG] immich_machine_learning fails to start with permission denied on onnxruntime_pybind11_state.cpython-311-x86_64-linux-gnu.so

### ISSUE THREAD

**Issue by mkre** [immich-app/immich#6404]
### The bug

Hi,

I am using the latest `docker-compose.yml` and the startup fails with 
```
immich_machine_learning  | [01/15/24 18:56:01] ERROR    Exception in worker process
immich_machine_learning  |                              Traceback (most recent call last):
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/ar
immich_machine_learning  |                              biter.py", line 609, in spawn_worker
immich_machine_learning  |                                  worker.init_process()
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/uvicorn/wor
immich_machine_learning  |                              kers.py", line 66, in init_process
immich_machine_learning  |                                  super(UvicornWorker, self).init_process()
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/wo
immich_machine_learning  |                              rkers/base.py", line 134, in init_process
immich_machine_learning  |                                  self.load_wsgi()
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/wo
immich_machine_learning  |                              rkers/base.py", line 146, in load_wsgi
immich_machine_learning  |                                  self.wsgi = self.app.wsgi()
immich_machine_learning  |                                              ^^^^^^^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
immich_machine_learning  |                              p/base.py", line 67, in wsgi
immich_machine_learning  |                                  self.callable = self.load()
immich_machine_learning  |                                                  ^^^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
immich_machine_learning  |                              p/wsgiapp.py", line 58, in load
immich_machine_learning  |                                  return self.load_wsgiapp()
immich_machine_learning  |                                         ^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/ap
immich_machine_learning  |                              p/wsgiapp.py", line 48, in load_wsgiapp
immich_machine_learning  |                                  return util.import_app(self.app_uri)
immich_machine_learning  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/gunicorn/ut
immich_machine_learning  |                              il.py", line 371, in import_app
immich_machine_learning  |                                  mod = importlib.import_module(module)
immich_machine_learning  |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/usr/local/lib/python3.11/importlib/__init__.py",
immich_machine_learning  |                              line 126, in import_module
immich_machine_learning  |                                  return _bootstrap._gcd_import(name[level:],
immich_machine_learning  |                              package, level)
immich_machine_learning  |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                              ^^^^^^^^^^^^
immich_machine_learning  |                                File "<frozen importlib._bootstrap>", line 1204,
immich_machine_learning  |                              in _gcd_import
immich_machine_learning  |                                File "<frozen importlib._bootstrap>", line 1176,
immich_machine_learning  |                              in _find_and_load
immich_machine_learning  |                                File "<frozen importlib._bootstrap>", line 1147,
immich_machine_learning  |                              in _find_and_load_unlocked
immich_machine_learning  |                                File "<frozen importlib._bootstrap>", line 690,
immich_machine_learning  |                              in _load_unlocked
immich_machine_learning  |                                File "<frozen importlib._bootstrap_external>",
immich_machine_learning  |                              line 940, in exec_module
immich_machine_learning  |                                File "<frozen importlib._bootstrap>", line 241,
immich_machine_learning  |                              in _call_with_frames_removed
immich_machine_learning  |                                File "/usr/src/app/main.py", line 15, in <module>
immich_machine_learning  |                                  from
immich_machine_learning  |                              onnxruntime.capi.onnxruntime_pybind11_state import
immich_machine_learning  |                              InvalidProtobuf, NoSuchFile
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/onnxruntime
immich_machine_learning  |                              /__init__.py", line 56, in <module>
immich_machine_learning  |                                  raise import_capi_exception
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/onnxruntime
immich_machine_learning  |                              /__init__.py", line 23, in <module>
immich_machine_learning  |                                  from onnxruntime.capi._pybind_state import
immich_machine_learning  |                              ExecutionMode  # noqa: F401
immich_machine_learning  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                              ^^^^^^^^^
immich_machine_learning  |                                File
immich_machine_learning  |                              "/opt/venv/lib/python3.11/site-packages/onnxruntime
immich_machine_learning  |                              /capi/_pybind_state.py", line 32, in <module>
immich_machine_learning  |                                  from .onnxruntime_pybind11_state import *  #
immich_machine_learning  |                              noqa
immich_machine_learning  |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
immich_machine_learning  |                              ImportError:
immich_machine_learning  |                              /opt/venv/lib/python3.11/site-packages/onnxruntime/
immich_machine_learning  |                              capi/onnxruntime_pybind11_state.cpython-311-x86_64-
immich_machine_learning  |                              linux-gnu.so: cannot enable executable stack as
immich_machine_learning  |                              shared object requires: Permission denied
immich_machine_learning  | [01/15/24 18:56:01] INFO     Worker exiting (pid: 13)
immich_machine_learning  | [01/15/24 18:56:01] ERROR    Worker (pid:13) exited with code 3
immich_machine_learning  | [01/15/24 18:56:01] ERROR    Shutting down: Master
immich_machine_learning  | [01/15/24 18:56:01] ERROR    Reason: Worker failed to boot.
```

The SELinux logs are showing the following which might be related:
```
time->Mon Jan 15 20:00:34 2024
type=AVC msg=audit(1705345234.188:1999): avc:  denied  { execstack } for  pid=21908 comm="gunicorn" scontext=system_u:system_r:spc_t:s0 tcontext=system_u:system_r:spc_t:s0 tclass=process permissive=0
```

This could be the same issue as observed by @nkay08 [here](https://github.com/immich-app/immich/issues/2481#issuecomment-1870295671).

### The OS that Immich Server is running on

OpenSUSE MicroOS

### Version of Immich Server

1.92.1

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    user: 1000:1000

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    user: 1000:1000

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

PORT=3010

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/photos/upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Invoke `docker-compose up`
2. Observe failure
```
