### ISSUE TITLE
[BUG] <Facial recognition issues>

### ISSUE THREAD

**Issue by LIHAQI** [immich-app/immich#6414]
### The bug

Install the latest version 1.92.1, but facial recognition and intelligent search are not working properly

[01/15/24 12:37:10] INFO     Starting gunicorn 21.2.0                           
[01/15/24 12:37:10] INFO     Listening at: http://0.0.0.0:3003 (8)              
[01/15/24 12:37:10] INFO     Using worker: app.config.CustomUvicornWorker       
[01/15/24 12:37:10] INFO     Booting worker with pid: 10                        
[01/15/24 12:37:24] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[01/15/24 12:37:24] INFO     Initialized request thread pool with 2 threads.    
[01/16/24 01:07:37] INFO     Downloading facial recognition model 'buffalo_l'.  
                             This may take a while.                             
[01/16/24 01:09:47] WARNING  Failed to load facial-recognition model            
                             'buffalo_l'.Clearing cache and retrying.           
[01/16/24 01:09:47] INFO     Downloading clip model 'ViT-B-32__openai'. This may
                             take a while.                                      
[01/16/24 01:09:47] WARNING  Attempted to clear cache for model 'buffalo_l', but
                             cache directory does not exist                     
[01/16/24 01:11:58] INFO     Downloading clip model 'ViT-B-32__openai'. This may
                             take a while.                                      
[01/16/24 01:11:58] WARNING  Failed to load clip model                          
                             'ViT-B-32__openai'.Clearing cache and retrying.    
[01/16/24 01:11:58] WARNING  Attempted to clear cache for model                 
                             'ViT-B-32__openai', but cache directory does not   
                             exist 

### The OS that Immich Server is running on

Ubuntu 20.04.1 LTS

### Version of Immich Server

1.92.1

### Version of Immich Mobile App

1.92.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.
2.
3.
...
```
