### ISSUE TITLE
[BUG] Thumbnail is created and visible on Mobile App but not visible on the Web page

### ISSUE THREAD

**Issue by usikpavel** [immich-app/immich#6437]
### The bug

New photo made by Android is uploaded by not visible in Web. Visible only in mobile App.

1. On Android, make a photo
2. Immich mobile App immediately uploads asset and shows "cloud uploaded" icon on the photo
3. immich_microservices container creates thumbnails JPEG and WEBP (I see generated files and logs)
5. But there is no any new photos in Web :(
6. (optionally) To see the new photos on the Web the only way is "Admin panel" -> "Generate ALL Thumbnails".

### Asset related logs

**immich_microservices**
_[Nest] 7  - 01/17/2024, 12:19:08 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0
[Nest] 7  - 01/17/2024, 12:19:08 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0_

**immich_server**
_[Nest] 7  - 01/17/2024, 12:19:08 AM    WARN [AssetService] WebP thumbnail requested but not found for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0, falling back to JPEG_

### The OS that Immich Server is running on

Ubuntu 23.10 (Xubuntu)

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.0 build.117

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. On Android, make a photo
2. Immich mobile App immediately uploads asset and shows "cloud uploaded" icon on the photo
3. immich_microservices container creates thumbnails JPEG and WEBP (I see generated files and logs)
5. But there is no any new photos in Web :(
6. (optionally) To see the new photos on the Web the only way is "Admin panel" -> "Generate ALL Thumbnails".
```

### Asset related logs

**immich_microservices**
_[Nest] 7  - 01/17/2024, 12:19:08 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0
[Nest] 7  - 01/17/2024, 12:19:08 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0_

**immich_server**
_[Nest] 7  - 01/17/2024, 12:19:08 AM    WARN [AssetService] WebP thumbnail requested but not found for asset 62239742-a8e3-44ae-a39c-3ecb1ad1d9d0, falling back to JPEG_
