### ISSUE TITLE
Same amount of assets number each time I try to do upload via CLI

### ISSUE THREAD

**Issue by troyane** [immich-app/immich#6496]
### The bug

I've done a batch upload of assets via CLI. I tried to run the same command and got the message, "A total of 38 assets will be uploaded to the server". Every time I try to run the same command, I get the same message. Is it a bug or a feature? Also, I don't know what the mentioned assets were to check if they are already uploaded. 

<img width="1244" alt="Screenshot 2024-01-19 at 16 51 15" src="https://github.com/immich-app/immich/assets/477468/e423f4d2-0d40-43c9-9ea4-4e0940f35183">

### The OS that Immich Server is running on

Synology NAS

### Version of Immich Server

v.1.93

### Version of Immich Mobile App

v.193

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/docker/immich/upload
IMMICH_VERSION=release
TYPESENSE_API_KEY=[REDACTED]
DB_PASSWORD=[REDACTED]
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. On macOS 14 Sonoma, immich cli 0.41.0. 
2. Run `immich upload --key [KEY] --server http://[SERVER]:2283/api --recursive /[PATH]`. 
3. Upload done without errors/warnings. Expect everything uploaded.
4. Run the same command again: got 38 assets to upload more. Agree to upload.
5. On every next run, there are always 38 assets to upload.
```
