### ISSUE TITLE
People "No people" despite images having People assigned

### ISSUE THREAD

**Issue by othyn** [immich-app/immich#6523]
### The bug

So this is a really weird one.

I've just imported around ~13k photos using the CLI tool within the Docker container, just mounting the old Nextcloud path and importing via localhost, not really important but just fyi. I noticed that the Face Detection/Grouping cut off around 2018, not relevant to this, but may as well be said.

The main problem was;
- I was going through People and adding names/birthdays, all seemed to be going well.
- I wanted to change the featured photo of each person to something else, so I went through and did so. There was a success toast confirming the change on each user. Despite that, none of the images changed after a cache refresh.
- Searching for information about this problem online, [this thread](https://github.com/immich-app/immich/discussions/3357) came up under this repo's discussions board. They suggested to re-run the 'all' face detection.
- I was a bit annoyed as it will reset all the names/birthday's I'd added, but followed the instructions anyway and started an 'All' job via the Admin Jobs GUI for Face Detection, then Facial Recognition.
- It went through all the images/videos in the library and finished, then did all the grouping and it finished. Both successfully. However, heading over to the People tab, it just says 'No people', despite the container logs for the ML container saying that its detected and created loads of People.
- Going into an individual image with a face in it however, it shows People attached but with broken image URL's (the little browser icon for a broken image is shown):

<img width="343" alt="Screenshot 2024-01-20 at 04 07 34" src="https://github.com/immich-app/immich/assets/7256684/1b94845f-23ba-4e58-bed4-a587462be424">

... and clicking on those broken People goes through to the asset page for that Person, with a broken image URL and no name:

<img width="407" alt="Screenshot 2024-01-20 at 03 45 44" src="https://github.com/immich-app/immich/assets/7256684/b304cbf5-ed19-4029-9828-cb57d361e265">

- Setting a name does not fix the issue, they still don't appear under the 'People' tab. There are also no people or anything under the 'hidden' option, as I double checked.
- However, setting a new featured image for the Person makes them appear under the 'People' tab, and appears to be the only way I can make them appear under the Person tab

I've tried rebooting the container instances, didn't make any difference.

Is there a way I can reset all this and start again for the Facial Recognition/Grouping / People in general? It seems something has got borked somewhere.

This is my first foray into Immich debugging, so please point me in the right direction for providing the relevant logs. Stupidly, as above, I rebooted the instance so have lost the logs from that session.

### The OS that Immich Server is running on

Alpine (Official Docker Container)

### Version of Immich Server

1.93.2

### Version of Immich Mobile App

1.93.0 build.134

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

networks:
  oxnet:
    external: true

volumes:
  model-cache:

services:
  photos:
    container_name: photos
    image: ghcr.io/immich-app/immich-server:v1.93.2
    command: ["start.sh", "immich"]
    restart: unless-stopped
    depends_on:
      - photos-redis
    volumes:
      - /mnt/user/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      oxnet:
        ipv4_address: 172.18.111.1
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env
    labels:
      traefik.enable: true
      traefik.docker.network: oxnet
      traefik.http.routers.photos.service: photos
      traefik.http.routers.photos.entrypoints: https
      traefik.http.services.photos.loadbalancer.server.port: 3001

  photos-microservices:
    container_name: photos-microservices
    image: ghcr.io/immich-app/immich-server:v1.93.2
    command: ["start.sh", "microservices"]
    restart: unless-stopped
    depends_on:
      - photos-redis
    volumes:
      - /mnt/user/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      oxnet:
        ipv4_address: 172.18.111.2
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env

  photos-machine-learning:
    container_name: photos-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    restart: unless-stopped
    volumes:
      - model-cache:/cache
    networks:
      oxnet:
        ipv4_address: 172.18.111.3
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env

  photos-redis:
    container_name: photos-redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: unless-stopped
    networks:
      oxnet:
        ipv4_address: 172.18.111.4
    dns:
      - 172.18.3.141

  photos-postgresdb:
    container_name: photos-postgresdb
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/photos-postgresdb:/var/lib/postgresql/data:rw
    networks:
      oxnet:
        ipv4_address: 172.18.111.5
    dns:
      - 172.18.3.141
    ports:
      - "5433:5432"
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env
```

### Your .env content

```Shell
HOST_CONTAINERNAME=photos

REDIS_HOSTNAME=photos-redis

DB_HOSTNAME=photos-postgresdb
DB_DATABASE_NAME=immich
DB_USERNAME=<user>
DB_PASSWORD=<pass>

POSTGRES_DB=immich
POSTGRES_USER=<user>
POSTGRES_PASSWORD=<pass>
```

### Reproduction steps

```bash
1. I was going through People and adding names/birthdays, all seemed to be going well.
2. I wanted to change the featured photo of each person to something else, so I went through and did so. There was a success toast confirming the change on each user. Despite that, none of the images changed, even after a cache refresh.
3. Searching for information about this problem online, [this thread](https://github.com/immich-app/immich/discussions/3357) came up under this repo's discussions board. They suggested to re-run the 'all' face detection.
4. I was a bit annoyed as it will reset all the names/birthday's I'd added, but followed the instructions anyway and started an 'All' job via the Admin Jobs GUI for Face Detection, then Facial Recognition.
5. It went through all the images/videos in the library and finished successfully on both jobs. However, heading over to the People tab, it just says 'No people', despite the container logs for the ML container saying that its detected and created loads of People successfully.
6. Tried cache refreshes and redeployed the containers just as sometimes things can get stuck, no dice.
7. Going into QA mode and thinking of other entrypoints, going into an individual image with a face in it however, it shows the relevant and correct People attached - but all with broken image icons in place of the Person's face/name, and clicking on those broken People icons goes through to the asset page for that Person, with a broken image URL (the browsers little broken image URL icon) and no name.
8. Continuing with the debugging mentality, setting a name does not fix the issue, they still don't appear under the 'People' tab. There are also no people or anything under the 'hidden' option, as I double checked.
9. However, continuing along that path, setting a new featured image for the Person makes them appear under the 'People' tab with that new featured image (instantly), and appears to be the only way I can make them appear under the Person tab. No other method will get them to appear on the Person tab.
```

### Additional information

The machine learning URL is configured correctly:

```json
{
  "machineLearning": {
    "url": "http://photos-machine-learning:3003",
  }
}
```

All other features work flawlessly, this is the only one. And it was working perfectly fine, until I did the second 'All' run.
