### ISSUE TITLE
immich_microservices error after update to 1.93.2

### ISSUE THREAD

**Issue by davidrwilliamson** [immich-app/immich#6531]
### The bug

I updated from v.1.92.1 to v1.93.2 using `docker-compose down` followed by `docked-compose pull && docker-compose up -d`. The pull completed successfully, but I received the following errors on up:

```
ERROR: for immich-microservices  Cannot start service immich-microservices: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

1.93.3 was released while I was typing this issue, but updating to that version did not solve the issue.

### The OS that Immich Server is running on

Ubuntu 22.

### Version of Immich Server

v1.93.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/6TB_Media/Photos:/mnt/6TB_Media/Photos:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: 
       file: hwaccel.yml
       service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /mnt/6TB_Media/Photos:/mnt/6TB_Media/Photos:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/6TB_Media/Photos/immich-upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Custom settings
LOG_LEVEL=verbose
# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=xxxx
DB_PASSWORD=xxxx

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Navigate to immich-app folder
2. docker-compose down
3. docker-compose pull && docker-compose up -d
```

**Comment by danieldietzler** [comment]
Can you try commenting out the hardware acceleration section in the compose file?

**Comment by martabal** [comment]
Sounds like an issue with docker https://github.com/NVIDIA/nvidia-docker/issues/1648

**Comment by davidrwilliamson** [comment]
> Can you try commenting out the hardware acceleration section in the compose file?

Yes, if I change the relevant section like this
> ```yaml
>  #   extends: 
>  #      file: hwaccel.yml
>  #      service: hwaccel
> ```
The services come up with no error.

**Comment by davidrwilliamson** [comment]
The contents of hwaccel.yml in case they are helpful:

```
version: "3.8"

# Hardware acceleration for transcoding - Optional
# This is only needed if you want to use hardware acceleration for transcoding.
# Depending on your hardware, you should uncomment the relevant lines below.

services:
  hwaccel:
    # devices:
    #   - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    # volumes:
    #   - /usr/lib/wsl:/usr/lib/wsl # If using VAAPI in WSL2
     environment:
       - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
    #   - LD_LIBRARY_PATH=/usr/lib/wsl/lib # If using VAAPI in WSL2
    #   - LIBVA_DRIVER_NAME=d3d12 # If using VAAPI in WSL2
     deploy: # Uncomment this section if using NVIDIA GPU
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: 1
               capabilities: [gpu,video]

```

I'm running an NVIDIA RTX 3060 Ti.
