### ISSUE TITLE
[CLI] Error 401 when using API key non-admin user 

### ISSUE THREAD

**Issue by klaasch** [immich-app/immich#6536]
### The bug

When trying to upload the photos of my wife via CLI, using the API key generated by her non-admin profile, I get error 401 "Request failed". Its seems like an authentication issue. Everything works fine if I use the API key from the admin profile.

```
# immich login-key http://192.168.1.16:2283/api REDACTED
Executing API key auth flow...
/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:44
            throw new login_error_1.LoginError(`Failed to connect to server ${instanceUrl}: ${error.message}`);
                  ^

LoginError: Failed to connect to server http://192.168.1.16:2283/api: Request failed with status code 401
    at /usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:44:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionService.keyLogin (/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:43:36)
    at async LoginKey.run (/usr/src/app/node_modules/@immich/cli/dist/src/commands/login/key.js:7:9)
    at async Command.<anonymous> (/usr/src/app/node_modules/@immich/cli/dist/src/index.js:57:5)

Node.js v20.11.0
```

### The OS that Immich Server is running on

Debian 12 (Bookworm) on Raspberry Pi5

### Version of Immich Server

2.0.6 (immich -V) / opencontiners.image.version = v1.91.4

### Version of Immich Mobile App

1.92.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich>

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Login to docker container: docker exec -it immich_server sh
2. Go to Android App and enable API key of non-admin user, copy this key.
3. Go back to your docker container, and paste:
immich login-key http://192.168.1.16:2283/api APIKEY_HERE

Result = request failed with status code 401.
```

### Additional information

- This command also fails for non-admin users: immich login-key http://127.0.0.1:3001/api APIKEY_HERE
-  The non-admin API key is 1 character longer then the admin API key (42 vs 41 chars)
