### ISSUE TITLE
postgres constantly writing

### ISSUE THREAD

**Issue by gccollect** [immich-app/immich#6549]
### The bug

Thank you for developing this amazing app. I am experiencing an odd behaviour running Immich: every few seconds, I can see in iotop that postgres is writing to disk even though Immich is idle, and no files are being added to the library. All I can see in pgAdmin is the select query below being executed, which shouldn't cause anything to be written to the DB. However, I can see that files in /var/lib/postgresql/data/pg_wal are being written into every few seconds. Is there a way to stop or at least increase the interval of this "polling" behaviour as this is causing excessive constant disk activity?

`/*pga4dash*/
SELECT
    pid,
    datname,
    usename,
    application_name,
    client_addr,
    pg_catalog.to_char(backend_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS backend_start,
    state,
    wait_event_type || ': ' || wait_event AS wait_event,
    array_to_string(pg_catalog.pg_blocking_pids(pid), ', ') AS blocking_pids,
    query,
    pg_catalog.to_char(state_change, 'YYYY-MM-DD HH24:MI:SS TZ') AS state_change,
    pg_catalog.to_char(query_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS query_start,
    pg_catalog.to_char(xact_start, 'YYYY-MM-DD HH24:MI:SS TZ') AS xact_start,
    backend_type,
    CASE WHEN state = 'active' THEN ROUND((extract(epoch from now() - query_start) / 60)::numeric, 2) ELSE 0 END AS active_since
FROM
    pg_catalog.pg_stat_activity
WHERE
    datname = (SELECT datname FROM pg_catalog.pg_database WHERE oid = 16384)ORDER BY pid`

### The OS that Immich Server is running on

DSM 7.2.1-69057 Update 3

### Version of Immich Server

v1.93.2

### Version of Immich Mobile App

v1.93.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"
services:
  immich-redis:
    healthcheck:
      disable: true
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    environment:
      - TZ=Europe/London
    volumes:
      - /volume1/docker/immich/redis:/data
    restart: on-failure:5

  immich-db:
    image: tensorchord/pgvecto-rs:pg16-v0.1.11
    container_name: Immich-DB
    hostname: immich-db
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    environment:
      - TZ=Europe/London
      - POSTGRES_DB=immich
      - POSTGRES_USER=immichuser
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 2665:5432
    restart: on-failure:5

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 8212:3001
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
    restart: on-failure:5
    depends_on:
      - immich-redis
      - immich-db

  immich-microservices:
    healthcheck:
      disable: true
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
    restart: on-failure:5
    depends_on:
      - immich-redis
      - immich-db

  immich-machine-learning:
    healthcheck:
      disable: true
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    volumes:
      - /volume1/docker/immich/upload:/usr/src/app/upload
      - /volume1/docker/immich/cache:/cache
    restart: on-failure:5
    depends_on:
      - immich-db
```

### Your .env content

```Shell
NODE_ENV=production
TZ=Europe/London
TYPESENSE_API_KEY=*****
DB_HOSTNAME=immich-db
DB_USERNAME=immichuser
DB_PASSWORD=*****
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
JWT_SECRET=*****
DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3
PUBLIC_LOGIN_PAGE_MESSAGE=
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Start Immich using the docker-compose.yml and .env files and wait for it to settle down
2. Launch iotop and observe postgres writing to disk every few seconds
3. In pgAdmin observe database activity
4. Run ls -lrt /var/lib/postgresql/data/pg_wal and observe the latest file being modified every few seconds
```
