### ISSUE TITLE
(android) backup dialog not working

### ISSUE THREAD

**Issue by gardiol** [immich-app/immich#6573]
### The bug

Installed android app from Play Store.
Connected to local immich server.
Waited until timeline is visible. 
Disabled battery optimization for immich app (A13).

The two issues described below are, i think, strictly correlated somehow.

### The OS that Immich Server is running on

Gentoo Linux 

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.3.2 build 119

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}/Willy:/usr/src/app/external/Willy
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}/Willy:/usr/src/app/external/Willy
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/Photos/Uploads
EXTERNAL_PATH=/data/Photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. open immich app
2. tap backup icon (top right)
3. select folders to include in backup
4. exit from dialog
5. start upload ("start upload" -> change in "cancel")
6. switch to another app OR lock screen
7. switch back to immich app OR unlock screen
8. backup is stopped: "start backup" button is back ("cancel" is gone)
9. need to start backup again
...

Similar correlated issue:
1. open immich app
2. tap backup icon (top right)
3. select folders to include in backup
4. exit from dialog
5. close immich app
6. reopen immich app
7. there are no folder in backup selection.
8. go back to backup dialog, select folders
9. now, without any selection, all previously selected folders are selected.
10. You can backup again
```

### Additional information

Also seems that automatic backups do not work. This is probably also a consequence of losing backup folders after app is closed.
Again, battery optimization is disabled (LineageOS 20.0, based on A13)
