### ISSUE TITLE
GPS Coordinates Are Not Correct If Coordinate Direction Is In Separate Field when using external XMP file

### ISSUE THREAD

**Issue by BigCheeZ** [immich-app/immich#6580]
### The bug

This is the same issue as reported in issue [3540](https://github.com/immich-app/immich/issues/3540) except that I'm reporting it for when external XMP files are used with media (eg: image0.jpg and image0.jpg.xmp) using External Libraries. The linked ticket is fixed, but it seems it was only fixed for when the data is embedded in the media file.

I've attached a zip file with a JPG and XMP file that show the issue. The JPG actually has the accurate EXIF data inside the file. The XMP files does too, but when it is parsed by Immich it results in the location being shown as Nepal (see below) instead of Orlando, FL USA because GPSLongitudeRef is not being handled appropriately.

Birendranagar
Surkhet, Karnali Pradesh
Nepal

[immich-xmp-test.zip](https://github.com/immich-app/immich/files/14002230/immich-xmp-test.zip)

I understand that if I did not use the external XMP file then the location would be properly extracted from the JPG. I have other data in the XMP file from previous applications I've used that I do not want to lose.

I have tried:

* Syncing Sidecar Metadata in Jobs tab
* Extract Metadata (All) in Jobs tab
* Force re-scan all Library files from Settings >> Libraries

### The OS that Immich Server is running on

Docker on NixOS 23.05

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.0 build.134

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${IMMICH_ROOT}/uploads:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - <my_external_library_mount>:/mnt/media/icloud:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - luna-compose_caddynet
      - immich-net
    labels:
      caddy: "photos.${MY_DOMAIN}"
      caddy.reverse_proxy: "{{upstreams 3001}}"
      caddy.tls.dns: "cloudflare ${CLOUDFLARE_API_TOKEN}"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${IMMICH_ROOT}/uploads:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - <my_external_library_mount>:/mnt/media/icloud:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - immich-net

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${IMMICH_ROOT}/model-cache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - immich-net

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    env_file:
      - .env
    restart: always
    networks:
      - immich-net

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${IMMICH_ROOT}/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - immich-net

networks:
  luna-compose_caddynet:
    external: true
  immich-net:
    attachable: true
    driver: bridge
```

### Your .env content

```Shell
IMMICH_VERSION=v1.93.3
```

### Reproduction steps

```bash
1. Create an External Library using the JPG and associated XMP in the zip file linked in the ticket
2. After image is added to Immich open it in web view and see that GPS is incorrect
```
