### ISSUE TITLE
File download fails and hangs after exactly 512 MB for large file (Android only / no issue on web client)

### ISSUE THREAD

**Issue by tnoms** [immich-app/immich#6583]
### The bug

While trying to download a 980 MB video file using the Immich app on Android, the download consistently fails and hangs. In two consecutive tests, a partial video file exactly 512 MB in size was written to disk. In the third test, 100k error logs were generated about running out of memory. This issue does not appear in the web client.

Error logs show: _"PlatformDispacter - Catch all error: Out of Memory"_

Assumptions:
- Immich Android is loading the full file into RAM before writing to disk
- my OS is enforcing a limit of 512 MB of RAM usage for the download

While brainstorming with a friend, we discovered the following [Stack Overflow post](https://stackoverflow.com/questions/73262584/how-do-you-go-over-512mb-of-memory-in-an-android-app) noting that manufacturers can enforce heap limits on apps to prevent excessive memory usage. This could be related.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.92.1

### Version of Immich Mobile App

v1.92.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

...

# Immich block 1 start #
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /docker/Immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /docker/Immich/pgdata:/var/lib/postgresql/data
    restart: always
# Immich block 1 end #

  ...

# Immich block 2 start
volumes:
  pgdata:
  model-cache:
# Immich block 2 end
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/Storage/.Immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

**Initial tests performed:**

1. Android App Download - client hung, waited for a long time, killed the app, saw exactly 512 MB of the file on my phone
2. Android App Download - client hung, waited for a long time, killed the app, saw exactly 512 MB of the file on my phone

**Next test performed:**

1. Web Client Download - downloaded same video fully and quickly with no issues

**Final test performed:**
1. Android App Download - client hung, waited for a long time, checked memory settings and noted elevated but not maxed out, Immich error log had generated ~100,000 out of memory logs, killed the app, file was never written to disk

### Additional information

App was downloaded from F-Droid, not Google Play
