### ISSUE TITLE
docker immich_server can't run after upgrade v1.93.3 from v1.91.4

### ISSUE THREAD

**Issue by chuoke** [immich-app/immich#6596]
### The bug

see the log
```log
2024-01-23 17:46:08 node:fs:2352
2024-01-23 17:46:08     return binding.writeFileUtf8(
2024-01-23 17:46:08                    ^
2024-01-23 17:46:08 
2024-01-23 17:46:08 Error: ENOENT: no such file or directory, open '/usr/src/open-api/immich-openapi-specs.json'
2024-01-23 17:46:08     at writeFileSync (node:fs:2352:20)
2024-01-23 17:46:08     at useSwagger (/usr/src/app/dist/immich/app.utils.js:165:32)
2024-01-23 17:46:08     at bootstrap (/usr/src/app/dist/immich/main.js:29:32)
2024-01-23 17:46:08     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-01-23 17:46:08   errno: -2,
2024-01-23 17:46:08   code: 'ENOENT',
2024-01-23 17:46:08   syscall: 'open',
2024-01-23 17:46:08   path: '/usr/src/open-api/immich-openapi-specs.json'
2024-01-23 17:46:08 }
```

### The OS that Immich Server is running on

Windows 11 WSL Ubuntu 22

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

not use

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

networks:
  traefik:
    name: traefik_default
    external: true
  redis:
    name: redis_default
    external: true
  postgresql:
    name: postgresql_default
    external: true

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    # ports:
    #   - 2283:3001
    expose:
      - 3001
    # depends_on:
    #   - redis
    #   - database
    restart: unless-stopped
    networks:
      - default
      - redis
      - postgresql
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-router.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-router.entrypoints=web"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}-service.loadbalancer.server.port=3001"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    # depends_on:
    #   - redis
    #   - database
    restart: unless-stopped
    networks:
      - default
      - redis
      - postgresql
    expose:
      - 3002

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - 3003

  # redis:
  #   container_name: immich_redis
  #   image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
  #   restart: unless-stopped

  # database:
  #   container_name: immich_postgres
  #   image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   restart: unless-stopped

volumes:
  # pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

COMPOSE_PROJECT_NAME=immich

APP_HOSTNAME=immich.test

# The location where your uploaded files are stored
UPLOAD_LOCATION="F:\\backup\\immich"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.93.3

NODE_ENV=development

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=postgresql
DB_USERNAME=postgres
DB_PORT=5432
DB_PASSWORD=123456
DB_DATABASE_NAME=immich

# REDIS_HOSTNAME=immich_redis
REDIS_HOSTNAME=redis
```

### Reproduction steps

```bash
I only changed `IMMICH_VERSION=v1.91.4` to `IMMICH_VERSION=v1.93.3`, and ran `docker-compose up -d`.
and see the server is not running successfully.
```
