### ISSUE TITLE
can't move from the Trash to the Archive

### ISSUE THREAD

**Issue by zcr268** [immich-app/immich#6601]
### The bug

can't move from the Trash to the Archive

### The OS that Immich Server is running on

docker

### Version of Immich Server

1.93.3

### Version of Immich Mobile App

1.93.3

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich-server
    image: $PROXY/immich-app/immich-server:${IMMICH_VERSION:-release}
    command:
      #- start.sh
      - pre_start.sh
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${EXTERNAL_PATH}:${IMAGE_EXTERNAL_PATH}
      - ${CONFIG_FILE}:${USED_IMMICH_CONFIG_FILE}
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
  immich-microservices:
    container_name: immich-microservices
    image: $PROXY/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command:
      #- start.sh
      - pre_start.sh
      - microservices
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${EXTERNAL_PATH}:${IMAGE_EXTERNAL_PATH}
      - ${CONFIG_FILE}:${USED_IMMICH_CONFIG_FILE}
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
  immich-machine-learning:
    container_name: immich-machine-learning
    image: $PROXY/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped
  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./data
UPLOAD_LOCATION_LIBRARY=/volume1/photo/immich
EXTERNAL_PATH=/volume1/photo/photo
IMAGE_EXTERNAL_PATH=/usr/src/app/external
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=XXXX
DB_USERNAME=XXXX
DB_DATABASE_NAME=XXXX

REDIS_HOSTNAME=immich-redis

CONFIG_FILE=./data/immich-config.json
USED_IMMICH_CONFIG_FILE=/config/immich-config.json
#IMMICH_CONFIG_FILE=/config/immich-config.json

PROXY=ghcr.dockerproxy.com
#PROXY=ghcr.io
```

### Reproduction steps

```bash
1.
2.
3.
...
```
