### ISSUE TITLE
upload failed. stuck in 100%

### ISSUE THREAD

**Issue by sky-stroller** [immich-app/immich#6615]
### The bug

I uploaded a video (https://drive.google.com/file/d/1jF9NjMoQl4eOlVV4mdbBa83RXjXoOW3o/view?usp=sharing) to server by web and phone (iPhone 13 Pro). It stucked in 100% for a long time and then failed.

### The OS that Immich Server is running on

Linux 6.1.64-Unraid x86_64

### Version of Immich Server

v1.93.3 

### Version of Immich Mobile App

v1.93.2

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_DIR}:/usr/src/app/upload/library
      - ${UPLOADS_DIR}:/usr/src/app/upload/upload
      - ${THUMBS_DIR}:/usr/src/app/upload/thumbs
      - ${PROFILE_DIR}:/usr/src/app/upload/profile
      - ${VIDEO_DIR}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '50900:3001'
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${LIBRARY_DIR}:/usr/src/app/upload/library
      - ${UPLOADS_DIR}:/usr/src/app/upload/upload
      - ${THUMBS_DIR}:/usr/src/app/upload/thumbs
      - ${PROFILE_DIR}:/usr/src/app/upload/profile
      - ${VIDEO_DIR}:/usr/src/app/upload/encoded-video
      - /etc/localtime:/etc/localtime:ro
      - /usr/lib/wsl:/usr/lib/wsl # If using VAAPI in WSL2
    env_file:
      - .env
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    # volumes:
    #   - /usr/lib/wsl:/usr/lib/wsl # If using VAAPI in WSL2
    # environment:
    #   - NVIDIA_DRIVER_CAPABILITIES=all # If using NVIDIA GPU
      # - LD_LIBRARY_PATH=/usr/lib/wsl/lib # If using VAAPI in WSL2
      # - LIBVA_DRIVER_NAME=d3d12 # If using VAAPI in WSL2
    # deploy: # Uncomment this section if using NVIDIA GPU
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu,video]
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:7.0.11
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg15-latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=immich
DB_PASSWORD=***
DB_DATABASE_NAME=immich
PG_DATA_DIR=/mnt/user/app_persistents/immich/db

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################

UPLOAD_LOCATION=/mnt/user/appdata/immich/data
LIBRARY_DIR=/mnt/user/app_persistents/immich/data/library
UPLOADS_DIR=/mnt/user/app_persistents/immich/data/uploads
THUMBS_DIR=/mnt/user/appdata/immich/data/thumbs
PROFILE_DIR=/mnt/user/appdata/immich/data/profile
VIDEO_DIR=/mnt/user/appdata/immich/data/video

###################################################################################
# Reverse Geocoding
#
# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM
####################################################################################

# DISABLE_REVERSE_GEOCODING=false
# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
#
# Custom message on the login page, should be written in HTML form.
# For example:
# PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"
####################################################################################

PUBLIC_LOGIN_PAGE_MESSAGE="Memory"

####################################################################################
# Alternative Service Addresses - Optional
#
# This is an advanced feature for users who may be running their immich services on different hosts.
# It will not change which address or port that services bind to within their containers, but it will change where other services look for their peers.
# Note: immich-microservices is bound to 3002, but no references are made
####################################################################################

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001

####################################################################################
# Alternative API's External Address - Optional
#
# This is an advanced feature used to control the public server endpoint returned to clients during Well-known discovery.
# You should only use this if you want mobile apps to access the immich API over a custom URL. Do not include trailing slash.
# NOTE: At this time, the web app will not be affected by this setting and will continue to use the relative path: /api
# Examples: http://localhost:3001, http://immich-api.example.com, etc
####################################################################################

#IMMICH_API_URL_EXTERNAL=http://localhost:3001

###################################################################################
# Immich Version - Optional
#
# This allows all immich docker images to be pinned to a specific version. By default,
# the version is "release" but could be a specific version, like "v1.59.0".
###################################################################################

#IMMICH_VERSION=
```

### Reproduction steps

```bash
1.upload video(https://drive.google.com/file/d/1jF9NjMoQl4eOlVV4mdbBa83RXjXoOW3o/view?usp=sharing)(use web or mobile app)
2.
3.
...
```
