### ISSUE TITLE
FACE DETECTION and FACIAL RECOGNITION fail after updating to v1.93.3

### ISSUE THREAD

**Issue by Liujun3712** [immich-app/immich#6629]
### The bug

At the version of v1.92 the Facial Recognition works fine. But after updating, even when all the asserts are re-recognized, the facial recognition function still failed.
<img width="1254" alt="截屏2024-01-24 23 42 26" src="https://github.com/immich-app/immich/assets/29953246/532974c2-4fb7-4239-b21d-46abaee20981">

### The OS that Immich Server is running on

Debian Docker

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - type: volume
        source: Immich
        target: /usr/src/app/upload
        volume:
          nocopy: false
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - type: volume
        source: Immich
        target: /usr/src/app/upload
        volume:
          nocopy: false
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  Immich:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=XXXXXXXX,nolock,soft,rw"
      device: ":/mnt/SafetyData/Immich"
```

### Your .env content

```Shell
IMMICH_VERSION=release
DB_PASSWORD=XXX
DB_HOSTNAME=XXX
DB_USERNAME=XXX
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.update to the v1.93.3
2.re-face detection and facial recognition
3.the error occur
...
```

### Additional information

After looking to the logs, I found that may relate to the database.

### The immich_microservices log shows:

> {
>   "id": "bc15ff28-e608-42a6-832b-bcc0e5c680b7"
> }
> [Nest] 7  - 01/24/2024, 3:32:24 PM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): QueryFailedError: column "embedding" of relation "asset_faces" does not exist
> [Nest] 7  - 01/24/2024, 3:32:24 PM   ERROR [JobService] QueryFailedError: column "embedding" of relation "asset_faces" does not exist
>     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
>     at async PersonRepository.createFace (/usr/src/app/dist/infra/repositories/person.repository.js:176:9)
>     at async PersonService.handleDetectFaces (/usr/src/app/dist/domain/person/person.service.js:259:13)
>     at async /usr/src/app/dist/domain/job/job.service.js:116:37
>     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
>     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

### The immich_postgres log shows:

> 2024-01-24 15:34:26.936 UTC [361] ERROR:  column "embedding" of relation "asset_faces" does not exist at character 56
> 2024-01-24 15:34:26.936 UTC [361] STATEMENT:  INSERT INTO "asset_faces"("id", "assetId", "personId", "embedding", "imageWidth", "imageHeight", "boundingBoxX1", "boundingBoxY1", "boundingBoxX2", "boundingBoxY2") VALUES (DEFAULT, $1, DEFAULT, '[-0.7424001,-0.42208022,-1.8435683,0.83982444,0.4872973,-0.9877277,1.1967025,0.0075268,-0.56281,0.1425616,0.13260415,0.040306497,0.258518,1.5720917,-1.0343225,0.82617056,0.92539656,-1.0639395,-0.06630112,-1.495015,-0.12719509,0.41763884,0.35532612,1.0206045,0.6070815,0.7273457,1.073182,0.5910805,0.17229962,-0.74731183,-0.49089187,0.6665522,-0.6936395,0.9764599,0.87043786,-0.030807301,0.026926354,1.3338076,0.45865,-0.5164295,1.7155681,-0.82816404,0.24153921,0.73972875,1.1519246,0.65031683,0.6082416,-0.710093,0.3995945,0.82789886,-0.07144949,1.0860404,0.36345652,0.2387717,-0.20819281,0.2881877,0.9737544,-0.7417954,0.91268265,0.5955002,0.75910944,0.17715698,1.625598,0.056858346,0.080493286,0.23609014,-0.43822697,-0.45683885,0.22399919,0.6116898,-0.05215206,-0.3153174,1.5308459,-0.48676756,-1.5864677,0.72398186,-1.0309834,-0.63434505,0.5851306,0.97637844,-1.5941994,-1.2273904,-1.345386,-1.1071099,0.30060634,1.6085287,-0.027708113,2.2154176,0.21998996,0.8079996,-0.50645304,-0.50154746,0.28555095,-0.023362264,-0.5218893,-0.19233902,0.59252334,1.8466932,-0.9297592,1.7408588,0.28692892,0.20883122,0.39597762,-0.59887266,-1.0381262,-0.5155381,-0.03605924,0.7433221,0.0773559,0.16146985,0.45083514,-0.5699533,0.25864962,-0.07110295,-0.75887805,-0.08622718,0.70483243,0.5856836,1.2679112,-0.98124856,1.5406377,0.77687293,-1.4706017,1.0926538,-1.12035,-1.478551,-0.99819165,-0.6087491,0.8818676,0.054217376,0.32108843,0.9643998,-0.4096936,0.39381334,-0.4680571,0.3952665,0.3932123,1.4267879,0.8811756,1.0777339,-0.504463,0.19053695,1.1482867,-1.7256982,0.46407196,0.09157331,-1.0769236,-0.4651315,-0.39141282,-1.6518191,-1.6519941,-1.5408244,0.123083495,-0.40097788,-0.19852145,0.09495583,-0.3038926,0.034847043,0.20233765,0.47393313,0.5756495,0.29461107,1.0710603,-0.29954353,-0.8618345,-0.8075003,-0.3558377,-0.2153137,-1.0193747,-0.55647016,0.82955605,-1.478339,-0.39241946,-0.35757205,1.5590005,-2.058132,0.67979217,0.9032491,-0.6875338,-1.5343049,-0.51678014,-0.8236072,0.25702038,0.28568643,0.75811875,-1.0381085,0.06020387,1.2008059,1.4389824,-0.97763807,-0.9589922,0.6434085,-0.055626526,2.1132188,0.9121899,1.5336756,0.29892766,1.7588134,1.0280849,1.5863827,1.6217183,2.036937,-0.919892,-0.40120876,2.5796611,0.9456003,-2.1824906,0.33234763,-0.45007175,-0.9518731,1.5239037,0.61063564,-0.005931452,-0.8666646,0.72562575,0.44598407,-2.02603,-0.72955555,-1.1368771,-0.765478,-0.032041818,-1.0366032,1.5872455,0.96442795,0.4310509,0.5213331,0.10562007,2.4462469,-0.63915676,-0.52658,-0.24670215,-0.42881566,-1.9355857,-0.36138043,1.2928029,-0.16068295,-1.0156343,-0.28154272,0.044314638,0.45585185,-0.95085365,0.51925075,1.2162143,-1.5391213,0.67466164,-0.196733,-1.3156184,-1.0682688,-0.12823072,-0.22874615,-0.15341878,-0.9136096,0.27417028,0.29160628,-2.0343869,0.120585695,1.1604726,0.19403557,0.83383775,0.8011533,-0.098723195,0.8493291,0.7637416,-0.6962723,0.22037685,1.1383579,-1.5631553,-0.69091916,-1.3118908,0.346263,0.774654,-0.116294175,0.6284864,1.8805425,0.4147508,0.75828665,-0.088762686,0.6435436,-1.134871,-0.49736056,-1.1537982,-0.31269673,0.6706904,1.2013316,0.33395472,-0.6550602,-1.79304,-1.2331586,0.101958334,0.6724515,0.684784,0.043696843,0.46431035,-0.68612915,-0.25399742,1.0089508,-2.7993522,0.7812951,1.5159984,-0.3474455,-0.027629714,0.27178705,0.7522866,1.2664682,-1.1977142,0.35020027,-0.7200499,-0.01606246,-1.1716897,0.17437759,-1.8774627,0.1368933,0.8001249,0.16025943,0.6462701,-1.2203393,0.1198819,1.2142124,0.027096331,0.33595285,-1.7982485,0.7555244,-0.73007846,0.14091386,1.1839813,0.41314274,1.3334522,-0.72115076,-0.6564759,-1.3039109,-1.0820287,0.2190699,-0.7145514,-0.6768246,0.3898358,-0.46021006,0.49782404,0.43722183,-1.4006827,-0.06534314,-0.40677893,-0.8858886,-0.6731924,-1.2895705,-1.47955,-1.0921812,-0.54543257,-1.3217196,-0.4892244,-0.8012757,0.30771995,-0.29570112,-0.07953824,1.3693042,-0.74149317,0.26478747,0.0753396,0.3226,0.05715604,1.3014666,-1.8569577,-0.23649171,1.7132461,0.91709757,0.8403977,0.8244532,0.62080353,-0.5739614,-0.83278537,-0.7324853,0.08985271,0.13080184,0.23965845,0.0060792863,0.32683104,0.3226116,1.1924841,1.3302063,-0.90564847,1.3056654,-0.12853014,-1.1743417,0.6017321,0.30937615,-0.31467953,-0.8339632,-0.28350958,-0.38786855,-0.96146005,-0.02112548,-1.0041012,-0.14032705,0.51734924,0.20875916,0.77235365,1.0374444,-0.54158336,0.7376085,0.3290025,0.7915242,0.3602291,-0.6216965,1.0587138,-0.021647602,-0.20307896,-1.604147,0.42095113,-0.15063536,-0.6594051,1.3143781,1.2385598,1.2274222,-0.5495391,-0.10082728,0.55703825,0.0017161965,0.48333806,-1.1539295,-1.4947661,0.5448791,0.9302496,1.3581963,0.8021865,-0.550217,-0.40336192,-0.48995256,-0.44903,-0.0012803432,-0.036812704,-1.0534439,-0.88056964,-0.51295644,-0.267586,0.14287391,-0.45675063,0.6950189,-0.57468104,0.7301471,-1.0838315,-0.6952431,-1.2097789,-0.35227287,0.38733122,0.3434527,-1.5223575,-0.5524875,0.64593077,-0.49979913,0.43210962,-0.20439874,-1.4567263,0.05232978,-0.14596832,-0.421709,-1.1355374,-1.0288655,0.61615723,0.39952305,0.13449526,-0.7319524,0.07471472,-0.60095245,0.19445117,0.45858857,0.011413693,-0.6940017,-0.45964804,-1.0543087,-1.1271472,0.7358477,-0.14486694,-1.1853883,0.022383466,-1.1815248,-0.5177913,-0.45546207,0.05002457,0.2700746,0.6822462,0.76590264,-0.8246526,-0.10726058,-0.5225926,-1.3933387,0.778679,0.16960749,1.4227767,0.35841393,1.1530067,-0.4344993,0.028580606,-1.2063606,0.58531165,0.70083743,0.08355595,-0.55936277,-1.1504847,-0.14590606,1.218176,-1.1636767,-1.1928881,-0.41149378,-0.43955046,0.88195807,0.04958547,-1.2925434,0.974025,1.223699,-2.2502654,0.017510138,-0.74005616,1.66462]', $2, $3, $4, $5, $6, $7) RETURNING "id", "imageWidth", "imageHeight", "boundingBoxX1", "boundingBoxY1", "boundingBoxX2", "boundingBoxY2"

### The immich_machine_learning shows:

> [01/24/24 15:21:16] INFO     Listening at: http://0.0.0.0:3003 (9)              
> [01/24/24 15:21:16] INFO     Using worker: app.config.CustomUvicornWorker       
> [01/24/24 15:21:16] INFO     Booting worker with pid: 49                        
> [01/24/24 15:21:22] INFO     Created in-memory cache with unloading after 300s  
>                              of inactivity.                                     
> [01/24/24 15:21:22] INFO     Initialized request thread pool with 40 threads.   
> [01/24/24 15:21:23] INFO     Loading facial recognition model 'buffalo_l' to    
>                              memory                                             

I am not familiar with the database.
It seems that the database should add the 'asset_faces' when it found missing.
But, when the second time of re-face detection, the database just showed the same log as the first time.
And I also find SMART SEARCH unavailable after migration to the new database。
