### ISSUE TITLE
Android app crash and exit to login page

### ISSUE THREAD

**Issue by Lugic1993** [immich-app/immich#6638]
### The bug

I hope this message finds you well. I am reaching out to report a bug I've encountered while using your Android application. I'm experiencing a consistent issue where the app crashes when I attempt to browse through photos from a few years back.

Bug Description:

Device Information: [Android 13]
Issue Details: Whenever I navigate to the section of the app that displays photos and scroll back to view images from several years ago, the app abruptly crashes and returns me to the login screen where I'm prompted to re-enter the app's URL and my login credentials.
Frequency: The crash occurs every time I try to view these older photos.

I have tried basic troubleshooting - such as restarting the app, clearing the cache, and even reinstalling the app, but the issue persists. It would be much appreciated if you could investigate this issue and, potentially, provide a fix in a future update.

### The OS that Immich Server is running on

Synology docker

### Version of Immich Server

1.93.3

### Version of Immich Mobile App

1.93.3 build 2119

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 4283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/immich-data/upload
GEOCODING_DATA=/volume1/immich-data/geo
# CACHE LOCATION
CACHE_DATA=/volume1/immich-data/cache

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres
TYPESENSE_API_KEY=i^SImfyi65ZF23&9

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Open the app and log in with the stored credentials.
Navigate to the photo browsing section.
Scroll to access photos from a few years prior.
Observe the app crashing and being redirected to the login page.
After this crash, it also seems that all previously stored settings in the app are lost.
```

### Additional information

[server log files.zip](https://github.com/immich-app/immich/files/14052542/server.log.files.zip)
The app logs files
[90f503c4a4549b280afb31f544e28261.csv](https://github.com/immich-app/immich/files/14052532/90f503c4a4549b280afb31f544e28261.csv)
