### ISSUE TITLE
iOS: "x years since" images/memories are low quality

### ISSUE THREAD

**Issue by Teonyr** [immich-app/immich#6640]
### The bug

Using the mobile app for iOS, all memories / "x years since" are using low quality images instead of the high quality versions.

You can see here, how it  looks on my mobile phone:
![Bildschirmfoto 2024-01-25 um 15 27 17 jpeg](https://github.com/immich-app/immich/assets/75175693/47c90a9a-8fe9-47fb-9d76-122128110bd9)

Compared to how it looks on my desktop, using the website:
![grafik](https://github.com/immich-app/immich/assets/75175693/84530b20-432e-47df-8c31-75ce192d1c7f)

If you need more info, just ask, I'm happily sharing everything you need to fix it. :)

Thx & keep up the great work!

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

v1.93.2 build.135

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #entrypoint: ["/bin/sh", "./start-server.sh"]
    entrypoint:
      - ./start.sh
      - immich
    volumes:
      - /media/raid/storage/immich:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    labels:
      traefik.enable: true
      #removed traefik labels for privacy reasons
    restart: unless-stopped
    networks:
      - backend
  immich-microservices:
    container_name: immich-microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    entrypoint:
      - ./start.sh
      - microservices
    volumes:
      - /media/raid/storage/immich:/usr/src/app/upload
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /media/raid/storage/immich:/usr/src/app/upload
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=postgres-16
DB_USERNAME=immich
DB_PASSWORD= #REMOVED FOR PRIVACY REASONS
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=redis
JWT_SECRET= #REMOVED FOR PRIVACY REASONS
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
NODE_ENV=production
REDIS_PASSWORD= #REMOVED FOR PRIVACY REASONS
TYPESENSE_API_KEY= #REMOVED FOR PRIVACY REASONS
TYPESENSE_DATA_DIR=/data
IMMICH_API_URL_EXTERNAL= #REMOVED FOR PRIVACY REASONS
```

### Reproduction steps

```bash
1. Wait until a memory / x years since appears in your mobile app
2. Open it
```
