### ISSUE TITLE
Unable to use immich CLI in docker

### ISSUE THREAD

**Issue by Emanuel-Bjurhager** [immich-app/immich#6731]
### The bug

I followed the official docker compose install guide and everything went well. I now want to use the cli to bulk import images into immich. I am not sure if I am doing something wrong, or if this is a bug.

Open a shell into the docker container and run:

```
immich upload -r -n .
No auth file exist. Please login first

immich login-key 127.0.0.1:3001 Ix.....JhA # 3001 is the internal port used by immich


Executing API key auth flow...
/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:44
            throw new login_error_1.LoginError(`Failed to connect to server ${instanceUrl}: ${error.message}`);
                  ^

LoginError: Failed to connect to server 127.0.0.1:3001: connect ECONNREFUSED 127.0.0.1:80
    at /usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:44:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionService.keyLogin (/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:43:36)
    at async LoginKey.run (/usr/src/app/node_modules/@immich/cli/dist/src/commands/login/key.js:7:9)
    at async Command.<anonymous> (/usr/src/app/node_modules/@immich/cli/dist/src/index.js:57:5)


immich login-key http://127.0.0.1:3001 Ixb.....JhA
Executing API key auth flow...
Logged in as undefined
Wrote auth info to /root/.config/immich/auth.yml

# That kind of worked, but my name is admin, and I have logged in multiple times with the web UI. Not sure why I am called undefined here

# I then try to dry run the upload command on everything in the current dir. I am currently in a bind mounted dir full of pictures

immich upload -r -n .
/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:68
            throw new Error(`Could not parse response. Is Immich listening on ${this.api.apiConfiguration.instanceUrl}?`);
                  ^

Error: Could not parse response. Is Immich listening on http://127.0.0.1:3001?
    at SessionService.ping (/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:68:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SessionService.connect (/usr/src/app/node_modules/@immich/cli/dist/src/services/session.service.js:38:9)
    at async Upload.connect (/usr/src/app/node_modules/@immich/cli/dist/src/cli/base-command.js:16:30)
    at async Upload.run (/usr/src/app/node_modules/@immich/cli/dist/src/commands/upload.js:16:9)
    at async Command.<anonymous> (/usr/src/app/node_modules/@immich/cli/dist/src/index.js:43:5)

Node.js v20.11.0
```

### The OS that Immich Server is running on

Official immich docker container (Debian GNU/Linux 12)

### Version of Immich Server

v1.93.3

### Version of Immich Mobile App

Not used

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/immich_temp_pics:/immich_temp_pics:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/immich_temp_pics:/immich_temp_pics:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=secret

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Run docker image according to instructions in docs
2. Shell into container
3. Run `immich login-key http://127.0.0.1:3001 <API key>`
4. Run `immich upload -r -n .` in a folder containing pictures
...
```
