### ISSUE TITLE
[Feature]: Using External Postgres/Redis

### ISSUE THREAD

**Issue by ajay-actuary** [immich-app/immich#675]
### Feature detail

I have a common postgres/redis server running for nextcloud, home assistant, lychee etc (not installed as a docker but as a system repo app). Is it possible for immich to use an external postgres/redis server rather than as a part of it's docker container? I tried removing the depends on in the docker & modifying the postgres/redis host but I'm not successful. Any help will be appreciated. Thanks! 

### Platform

Server

**Comment by bo0tzz** [comment]
You need to edit the .env file to use the external services.

**Comment by ajay-actuary** [comment]
Below is my docker-compose. I keep getting 

Error code 500
Request failed with status code 502

Verbose
Request failed with status code 502,AxiosError,ERR_BAD_RESPONSE,[object Object],[object XMLHttpRequest],[object Object]

-----------------------------------------------------
```

version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - /absolutepath/:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=immich
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_HOST=postgres_host
      - REDIS_HOST=redis_host
      - REDIS_HOST_PORT=redis_port
      - REDIS_HOST_PASSWORD=redis_pass
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - /absolutepath/:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=immich
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_HOST=postgres_host
      - REDIS_HOST=redis_host
      - REDIS_HOST_PORT=redis_port
      - REDIS_HOST_PASSWORD=redis_pass
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - /absolutepath/:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - POSTGRES_DB=immich
      - POSTGRES_USER=immich
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_HOST=postgres_host
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

```

**Comment by bo0tzz** [comment]
Can you post your redacted .env file as well?
Looking at the env vars you have set in the docker-compose.yml, `- POSTGRES_HOST=postgres_host` does not seem correct. Is that the actual address of your postgres instance?

**Comment by ajay-actuary** [comment]
> Can you post your redacted .env file as well? Looking at the env vars you have set in the docker-compose.yml, `- POSTGRES_HOST=postgres_host` does not seem correct. Is that the actual address of your postgres instance?

Below is my env file:
```

###################################################################################
# Database
###################################################################################

DB_HOSTNAME=192.168.x.x
DB_USERNAME=immich
DB_PASSWORD=postgres_pass
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432




###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=192.168.x.x

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
REDIS_PASSWORD=redis_pass
# REDIS_SOCKET=





###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/home/xx/Apps/Immich/config




###################################################################################
# JWT SECRET
###################################################################################

JWT_SECRET=NzdXsF53bk9uh5xohDqoi2h1c1in1pi3n2pi3SNh7UE6X9SB3F7u6do7t




###################################################################################
# MAPBOX
####################################################################################

# ENABLE_MAPBOX is either true of false -> if true, you have to provide MAPBOX_KEY
ENABLE_MAPBOX=false
MAPBOX_KEY=


####################################################################################
# WEB - Optional
####################################################################################

# Custom message on the login page, should be written in HTML form.
# For example PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

PUBLIC_LOGIN_PAGE_MESSAGE="Welcome to Home Server Immich"
```

**Comment by bo0tzz** [comment]
The environment variables you're setting in the `environment:` section of the docker-compose are overriding the ones from the .env file. Please remove them, then it should work.

**Comment by ajay-actuary** [comment]
Thanks. I get the same error:
```
immich-immich-server-1            | [Nest] 7  - 09/11/2022, 12:01:16 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
immich-immich-server-1            | QueryFailedError: function uuid_generate_v4() does not exist
immich-immich-server-1            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
immich-immich-server-1            |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
immich-immich-server-1            |     at async CreateUserTable1645130759468.up (/usr/src/app/dist/apps/immich/libs/database/src/migrations/1645130759468-CreateUserTable.js:6:9)
immich-immich-server-1            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:178:17)
immich-immich-server-1            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:248:35)
immich-immich-server-1            |     at async DataSource.initialize (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:137:17)
immich-immich-server-1            | Migration "CreateUserTable1645130759468" failed, error: function uuid_generate_v4() does not exist

```

```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always


  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:80
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

```
