### ISSUE TITLE
Uploads no longer working on Android

### ISSUE THREAD

**Issue by alternativesurfer** [immich-app/immich#6806]
### The bug

Uploads no longer work on Android.

Screenshot is of a manual upload.
Starts and stalls at 18% or 20% (tested on 2 phones)
![signal-2024-01-31-085648](https://github.com/immich-app/immich/assets/10135929/13d5604f-d52a-4662-99c3-c19289ef653c)

Logs from mobile app
[Immich_log.csv](https://github.com/immich-app/immich/files/14114963/Immich_log.csv)

### The OS that Immich Server is running on

Ubuntu 22.04.3 LTS

### Version of Immich Server

1.93.3

### Version of Immich Mobile App

1.93.3

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

	# The location where your uploaded files are stored
	UPLOAD_LOCATION=/mnt/media/immich

	# The Immich version to use. You can pin this to a specific version like "v1.71.0"
	IMMICH_VERSION=release

	# Connection secret for postgres. You should change it to a random password
	DB_PASSWORD=PASSWORDENTEREDHERE

	# The values below this line do not need to be changed
	###################################################################################
	DB_HOSTNAME=immich_postgres
	DB_USERNAME=postgres
	DB_DATABASE_NAME=immich

	REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Upload from Web works.
Upload from mobile fails
I've tested this on 2 phones.
Pixel 7 Pro, Android 14 with Jan 5 security update.
Pixel 8, GrapheneOS Android 14 with the Jan 5 security update.


1. Open app
2. Select folder for upload
3. Click manual upload button
4. Upload does not occur.
```
