### ISSUE TITLE
Cant persist docker volume for Immich unless this line is being modified

### ISSUE THREAD

**Issue by jslearn81** [immich-app/immich#6836]
### The bug

In https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

Originally:
- ${UPLOAD_LOCATION}:/usr/src/app/upload
Fixed:
- ${UPLOAD_LOCATION}:/usr/src/app/upload/upload

This was also noticed in the following reddit post.
https://www.reddit.com/r/immich/comments/18h5trn/immich_is_not_moving_files_from_upload_to_library/

### The OS that Immich Server is running on

Windows

### Version of Immich Server

latest/docker

### Version of Immich Mobile App

V1.0.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
# Nas example: https://www.reddit.com/r/immich/comments/18h5trn/immich_is_not_moving_files_from_upload_to_library/

name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
```

### Your .env content

```Shell
NA
```

### Reproduction steps

```bash
NA
```
