### ISSUE TITLE
Error when trying to change a person's "feature photo"

### ISSUE THREAD

**Issue by pluja** [immich-app/immich#6848]
### The bug

When I go to the people page, and try to change a person's feature photo, the UI says "Feature photo updated", but then this change is not reflected at all.

Going through the logs, and provoking the error, I see the following `immich-microservices` error:

```
immich_microservices     | [Nest] 7  - 02/02/2024, 7:07:06 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Expected integer for width but received -2 of type number
immich_microservices     | [Nest] 7  - 02/02/2024, 7:07:06 AM   ERROR [JobService] Error: Expected integer for width but received -2 of type number
immich_microservices     |     at Object.invalidParameterError (/usr/src/app/node_modules/sharp/lib/is.js:135:10)
immich_microservices     |     at Sharp.<anonymous> (/usr/src/app/node_modules/sharp/lib/resize.js:478:16)
immich_microservices     |     at Array.forEach (<anonymous>)
immich_microservices     |     at Sharp.extract (/usr/src/app/node_modules/sharp/lib/resize.js:473:38)
immich_microservices     |     at MediaRepository.crop (/usr/src/app/dist/infra/repositories/media.repository.js:23:14)
immich_microservices     |     at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/domain/person/person.service.js:382:58)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async /usr/src/app/dist/domain/job/job.service.js:116:37
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 02/02/2024, 7:07:06 AM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "897cdc0c-9d95-4bd7-9091-fc174071441c"
immich_microservices     | }
immich_microservices     | 
immich_microservices     |
```

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/whoami/STORAGE/PHOTOS

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Go to Explore page
2. Select "View all" on the people section
3. Select a person and click the three upper-right dots
4. Change the feature photo
5. Select a different photo and confirm
6. See a success error
7. Check nothing changed.
```
