### ISSUE TITLE
Heif thumbnail generate failed with bad image dimensions on decode

### ISSUE THREAD

**Issue by CatTail** [immich-app/immich#6849]
### The bug

After add external library I saw lots of HEIF image thumbnails are not properly generated, after I try to refresh the thumbnail, I was able to see the error logs from immich mircoservices

<img width="1473" alt="image" src="https://github.com/immich-app/immich/assets/1606069/dcc54403-5c6d-490a-a6fa-55a0e15fe14a">

```
immich_microservices     | [Nest] 7  - 02/02/2024, 6:49:15 AM     LOG [PersonService] Creating new person for face 388648e7-ff80-4333-93eb-b24302b6d414
immich_microservices     | [Nest] 7  - 02/02/2024, 6:49:16 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-jpeg-thumbnail): Error: /mnt/media/dsc07956.heif: bad seek to 5510386
immich_microservices     | heifload: bad image dimensions on decode
immich_microservices     | [Nest] 7  - 02/02/2024, 6:49:16 AM   ERROR [JobService] Error: /mnt/media/dsc07956.heif: bad seek to 5510386
immich_microservices     | heifload: bad image dimensions on decode
immich_microservices     |     at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
immich_microservices     |     at MediaRepository.resize (/usr/src/app/dist/infra/repositories/media.repository.js:41:14)
immich_microservices     |     at MediaService.generateThumbnail (/usr/src/app/dist/domain/media/media.service.js:121:44)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async MediaService.handleGenerateJpegThumbnail (/usr/src/app/dist/domain/media/media.service.js:108:28)
immich_microservices     |     at async /usr/src/app/dist/domain/job/job.service.js:116:37
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

Below is the image produce the error [test.heif.zip](https://github.com/immich-app/immich/files/14136906/test.heif.zip)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.1

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${ORIGINAL_LOCATION}:/mnt/media/original:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${ORIGINAL_LOCATION}:/mnt/media/original:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: /media/immich/pgdata
      o: bind
  model-cache:
    driver: local
    driver_opts:
      type: none
      device: /media/immich/model-cache
      o: bind
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/photos/upload
ORIGINAL_LOCATION=/media/photos/migration

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
```

### Reproduction steps

```bash
I write a minimal script to reproduce the issue


const sharp = require('sharp');

sharp('test.heif')
.pipelineColorspace('rgb16')
  .toBuffer()
```
