### ISSUE TITLE
Immich Web Reports Server "offline" and "version" unknown. 

### ISSUE THREAD

**Issue by hiddenpcmaster** [immich-app/immich#6859]
### The bug

Not a new install, been running for many months. Immich has been very stable for me. After v1.94.1 upgrade the Web Interface shows:

![Capture](https://github.com/immich-app/immich/assets/19600811/f7a75f98-5294-4f3b-bd16-90d53b7a90fe)

However, Immich seems to be fully operational. I can run jobs and view server stats. 

The mobile application connects fine and states "Client and Server are up-to-date".

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

1.94.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
    - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

#  immich-web:
#    container_name: immich_web
#    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
#    env_file:
#      - .env
#    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

 # immich-proxy:
 #   container_name: immich_proxy
 #   image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
 #   environment:
 #     # Make sure these values get passed through from the env file
 #     - IMMICH_SERVER_URL
 #     - IMMICH_WEB_URL
 #   ports:
 #     - 2283:8080
 #   depends_on:
 #     - immich-server
 #     - immich-web
 #   restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/disk1/immich-app

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.1. Login to Immich web interface
2. Look at bottom left side of screen for server information
```

### Additional information

I'm exposing this through NGINX proxy manager using my own domain if this helps.
