### ISSUE TITLE
Immich CLI changed the hash of images when uploading

### ISSUE THREAD

**Issue by Emanuel-Bjurhager** [immich-app/immich#6913]
### The bug

I used Immich CLI to upload about 100,000 images to Immich. After the upload was completed, I was unsure if I had uploaded some of the folders, and therefore uploaded them again. Since immich uses hashes to prevent the same photo from being uploaded twice, I though that it would not matter if I let the Immich upload cli go through some folders again.
I then noticed that I had duplicate photos in my library. The duplicates was named <filename>+1.jpg. I though this was weird, so I wrote a script that compared the md5 hash of all 100,000 images. Hash1 from my original library on disk, and hash2 being the same file in the Immich library. I then noticed that around 3000 images had its md5 hash changed after upload through the cli. That is why some of the photos became duplicated, since immich did not think these images where already in the library.
These photos with an incorrect md5 hash looks identical to the "real" photo, and the metadata is okay. I do not know why or how this happened. 
I will probably investigate this more later on, but I wanted to have this issue documented for now in case anyone else experiences something similar.

### The OS that Immich Server is running on

Ubuntu 20

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

-

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/immich_temp_pics:/immich_temp_pics:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /media/immich_temp_pics:/immich_temp_pics:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=secret

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Upload a lot of photos using Immich CLI
2.Compare md5 hash of all photos from original library and immich library
3.Some photos will have its md5 changed after upload. Most photos will not have its hash changed.
...
```

### Additional information

```
~ cmp Orignal.JPG upload1.JPG
Orignal.JPG upload1.JPG differ: byte 5, line 1
~ cmp -l Orignal.JPG upload1.JPG | wc -l
cmp: EOF on Orignal.JPG after byte 4620124
4595287
```
There are a lot of differences between these files that look identical to me.
Weirdly enough, all of the "corrupted"/changed images all come from 2 different cameras (8 different cameras in total) and on camera 1 were all taken within a few days of each other. Camera 2 has its photos more spread out over more dates. These 2 cameras are also the oldest cameras and only have around 8000 photos out of 100,000. If this issue was completely random, I would expect to see this over a wider range of dates and cameras, but only older photos with these 2 cameras. Is immich doing some kind of correction on upload if it detects issues with the image? 
I am thinking that maybe these images have experienced some minor bit-rot over the years and immich, or some library that immich is using is trying to correct this?
