### ISSUE TITLE
Images load in low quality if deleting assets in the asset view

### ISSUE THREAD

**Issue by lukaszwawrzyk** [immich-app/immich#6924]
### The bug

The scenario is that I want to clean my photos, so I open a photo and browse from there with a swipe gesture. Then I delete some using the trash button, and I am keep swiping to browse. Yet, sometimes the pictures that I am browsing display in the low resolution and do not upgrade. I use 250p for small thumbnails and 1140p for big. I think that I see this 250p thumbnail and it never upgrades. It is hard to tell if I want to delete this particular photo if it is blurred. Also zoom in gesture doesn't work then (which I guess is expected for small thumbnail).

It seems to happen more often on ios than android, yet it is observed on both. It is not fully deterministic, but on iphone it happens almost every time.

I tried closing the asset view (go back to timeline) and delete from there using select, but it doesn't fix the issue. When zooming in to the asset, the low res thumbnail issue still happens.

It can be fixed by restarting the app.

If photos are not deleted, the issue doesn't seem to occur, browsing images is seamless.

Another workaround for the issue is to lock the phone, wait for some time, and after unlock, the image loads in better quality.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /data/apps/immich:/data/apps/immich
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /data/apps/immich:/data/apps/immich
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    ports:
      - 5432:5432
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/data/personal/photos/immich
IMMICH_VERSION=release
DB_PASSWORD=password
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. delete some photos
2. open some photos
3. some will load in low quality and never upgrade
```

### Additional information

I enabled finest logging and debugging in the app, though logs do not look too verbose for me. These are logs from starting the app, deleting some asset and observing asset not loading in better quality. There is nothing relevant there.
Perhaps there is a way to get more logs?
[Immich_log_2024-02-05T15_17_55.996384.csv](https://github.com/immich-app/immich/files/14172175/Immich_log_2024-02-05T15_17_55.996384.csv)

This is a very important issue for me to fix. I could work on it myself, but I am not sure where/how to start. But maybe someone will know how is it caused.

## Bonus issues
I observe some other problems with managing my photos regularly. I can open tickets for them too, but maybe they are known already, but I couldn't find anything
1. If I am swiping fast, one swipe is enough to change photo, but if I stop and want to browse photos slower, I need to swipe twice for photo to change.
2. Deleting photo takes to the next in the asset view, but I can still swipe back and see what was already deleted, I need to reopen asset view to make it right.
3. I cannot delete photos from the computer (which would make life easier, as I wouldn't suffer that much from issues on mobile). I imagined this workflow like I trash assets on the web interface, I open trash on mobile and empty it. I'd hope it would remove local assets from the phone too, but instead they are reuploaded.
