### ISSUE TITLE
Database not working with new tensorchord/pgvecto-rs:pg14-v0.2.0

### ISSUE THREAD

**Issue by crazytil** [immich-app/immich#6997]
### The bug

New docker compose image from database causes errors and broken links to images.

docker-compose.yaml was changed from tensorchord/pgvecto-rs:pg14-v0.1.11 to 
tensorchord/pgvecto-rs:pg14-v0.2.0

2024-02-09 15:34:08.314 UTC [47] ERROR:  could not find function "vectors_amhandler_wrapper" in file "/usr/lib/postgresql/14/lib/vectors.so"

version 0.2.0 has had some breaking changes that may affect immich

### The OS that Immich Server is running on

Ubuntu 23.10

### Version of Immich Server

release (1.94.1)

### Version of Immich Mobile App

release (1.94.1 build.137)

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11
    #image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  caddy:
    image: technoguyfication/caddy-cloudflare:latest
    restart: unless-stopped
    environment:
    - ACME_EMAIL=****redacted****
    - CLOUDFLARE_API_TOKEN=****redacted****
    - ACME_AGREE=true
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - caddy_data:/data
    - caddy_config:/config
    - $PWD/Caddyfile:/etc/caddy/Caddyfile

volumes:
  pgdata:
  model-cache:
  caddy_data:
  caddy_config:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/tilian/Media/Immich/Library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
change 
image: tensorchord/pgvecto-rs:pg14-v0.1.11
to
image: tensorchord/pgvecto-rs:pg14-v0.2.0
```
