### ISSUE TITLE
Sharing broken in latest version 

### ISSUE THREAD

**Issue by dsavicIre** [immich-app/immich#7077]
### The bug

After picking pics for sharing, the generated link does not work.
The following message shows:

Not found: /immich/share/WJw-9RN0GsjAu698ZQHrqCZWeVhyu8Z5_tJTPrq94gVHjbQaQ3lvgMjIdmvg2tTQ8ok - 500
Error: Not found: /immich/share/WJw-9RN0GsjAu698ZQHrqCZWeVhyu8Z5_tJTPrq94gVHjbQaQ3lvgMjIdmvg2tTQ8ok
    at B (https://savichome.ddns.net:8443/_app/immutable/chunks/entry.iqgqkJV7.js:1:17343)
    at We (https://savichome.ddns.net:8443/_app/immutable/chunks/entry.iqgqkJV7.js:1:10059)
    at zt (https://savichome.ddns.net:8443/_app/immutable/chunks/entry.iqgqkJV7.js:1:20117)
    at Module.en (https://savichome.ddns.net:8443/_app/immutable/chunks/entry.iqgqkJV7.js:1:9679)
    at https://savichome.ddns.net:8443/immich/share/WJw-9RN0GsjAu698ZQHrqCZWeVhyu8Z5_tJTPrq94gVHjbQaQ3lvgMjIdmvg2tTQ8ok:77:11

### The OS that Immich Server is running on

Raspbian 

### Version of Immich Server

1.9.4.1

### Version of Immich Mobile App

1.9.4.10b 121

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
ersion: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose>
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/XXXXXXXXX/mnt/media:rw
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
 #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /home/XXXXXXX:/mnt/media:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-releas>
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e3>
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f>
    env_file:
      - .env
environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://im>

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.7>
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxxxxx

# The values below this line do not need to be changed
##############################################################################>
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Select few pictures in web client
2.Select sharing (not relevant is there is any option selected for sharing)
3.generate URL
4. Paste url in the browser
5. Error is shown.
...
```
