### ISSUE TITLE
Cannot regenerate transcoded videos of Android MP.JPG files

### ISSUE THREAD

**Issue by slackspace-io** [immich-app/immich#7085]
### The bug

I recently had to rebuild my stack due to a disagreement with etcd.

As part I attempted to backup from PVs immich's database and photos.  Specifically I rsync'd to the new volume the folders library, upload, and profile. 

I am using a storage template. 

Per the documentation, I did not keep encoded-videos folder as I thought one could regenerate. (Perhaps MPs are an exception ? :D)

I did successfully restore immich, including database and at first glance all my assets. 

I however noticed some untracked files, and offline paths. 

While investigating these, I noticed none of my motion photos were working.  When attempting to play them on a client, you see file not found in the immich-server container. When running transcoding job, you see errors in micro-services about ffprobe. 

I deleted the folder again, and now my most recent photos (today) have the same issue. Which makes me suspect this is reproducable. 

(I have not found a good way to resolve this. I manually moved one photo out the sync folder for immich on my phone, then deleted/trash/empty in immich, then moved it back. This fixed that single photo.)

### The OS that Immich Server is running on

ghcr container image, ontop an RKE2 cluster with ubuntu 22.04 as base image.

### Version of Immich Server

v1.94.1

### Version of Immich Mobile App

v1.94.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
I am running kubernetes, I exploded from helm onetime fileset and maintain them now. 

Here is deployment for server;
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-server
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: server
    app.kubernetes.io/version: v1.91.4
    helm.sh/chart: immich-0.3.1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: server
        app.kubernetes.io/instance: immich
    spec:

      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: immich-server
          image: ghcr.io/immich-app/immich-server:v1.94.1
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:

            - ./start-server.sh
          env:
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_HOSTNAME
              value: postgres-service
            - name: DB_PASSWORD
              value: supersecureipromise
            - name: DB_USERNAME
              value: immich
            #- name: IMMICH_MACHINE_LEARNING_URL
            #  value: http://immich-machine-learning:3003
            - name: REDIS_HOSTNAME
              value: redis-service
            - name: IMMICH_CONFIG_FILE
              value: /usr/src/app/immich-config.json
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          volumeMounts:
            - name: immich-config
              mountPath: /usr/src/app/immich-config.json
              subPath: immich-config.json
            - name: library
              mountPath: /usr/src/app/upload
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /server-info/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /server-info/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
      nodeSelector:
        immich: server
      volumes:
        - name: immich-config
          configMap:
            name: immich-config
        - name: library
          persistentVolumeClaim:
            claimName: immich-pvc

here is microservice
---
# Source: immich/templates/microservices.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-microservices
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: microservices
    app.kubernetes.io/version: v1.91.4
    helm.sh/chart: immich-0.3.1
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices
      app.kubernetes.io/instance: immich
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices
        app.kubernetes.io/instance: immich
    spec:

      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: immich-microservices
          image: ghcr.io/immich-app/immich-server:v1.94.1
          imagePullPolicy: IfNotPresent
          command:
            - "/bin/sh"
          args:

            - ./start-microservices.sh
          env:
            - name: DB_DATABASE_NAME
              value: immich
            - name: DB_HOSTNAME
              value: postgres-service
            - name: DB_PASSWORD
              value: totallysecurepasswordfromearlier
            - name: DB_USERNAME
              value: immich
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning:3003
            - name: REDIS_HOSTNAME
              value: redis-service
            - name: IMMICH_CONFIG_FILE
              value: /usr/src/app/immich-config.json
          volumeMounts:
            - name: immich-config
              mountPath: /usr/src/app/immich-config.json
              subPath: immich-config.json
            - name: library
              mountPath: /usr/src/app/upload

      nodeSelector:
        immich: server
      volumes:
        - name: library
          persistentVolumeClaim:
            claimName: immich-pvc
        - name: immich-config
          configMap:
            name: immich-config


If you want the ML or PVCs let me know.. guessing it's not relevant tho :)
```

### Your .env content

```Shell
{
  "ffmpeg": {
    "crf": 23,
    "threads": 2,
    "preset": "ultrafast",
    "targetVideoCodec": "h264",
    "acceptedVideoCodecs": [
      "h264"
    ],
    "targetAudioCodec": "aac",
    "acceptedAudioCodecs": [
      "aac"
    ],
    "targetResolution": "720",
    "maxBitrate": "0",
    "bframes": -1,
    "refs": 0,
    "gopSize": 0,
    "npl": 0,
    "temporalAQ": false,
    "cqMode": "auto",
    "twoPass": false,
    "preferredHwDevice": "auto",
    "transcode": "required",
    "tonemap": "hable",
    "accel": "disabled"
  },
  "job": {
    "backgroundTask": {
      "concurrency": 5
    },
    "smartSearch": {
      "concurrency": 6
    },
    "metadataExtraction": {
      "concurrency": 5
    },
    "faceDetection": {
      "concurrency": 6
    },
    "search": {
      "concurrency": 5
    },
    "sidecar": {
      "concurrency": 5
    },
    "library": {
      "concurrency": 5
    },
    "migration": {
      "concurrency": 5
    },
    "thumbnailGeneration": {
      "concurrency": 5
    },
    "videoConversion": {
      "concurrency": 1
    }
  },
  "logging": {
    "enabled": true,
    "level": "log"
  },
  "machineLearning": {
    "enabled": true,
    "url": "http://immich-machine-learning:3003",
    "clip": {
      "enabled": true,
      "modelName": "ViT-B-32__openai"
    },
    "facialRecognition": {
      "enabled": true,
      "modelName": "buffalo_l",
      "minScore": 0.6,
      "maxDistance": 0.5,
      "minFaces": 3
    }
  },
  "map": {
    "enabled": true,
    "lightStyle": "",
    "darkStyle": ""
  },
  "reverseGeocoding": {
    "enabled": true
  },
  "oauth": {
 #stuff
  },
  "passwordLogin": {
    "enabled": true
  },
  "storageTemplate": {
    "enabled": true,
    "hashVerificationEnabled": true,
    "template": "{{y}}/{{y}}-{{MM}}-{{dd}}/{{filename}}"
  },
  "thumbnail": {
    "webpSize": 250,
    "jpegSize": 1440,
    "quality": 80,
    "colorspace": "p3"
  },
  "newVersionCheck": {
    "enabled": true
  },
  "trash": {
    "enabled": true,
    "days": 30
  },
  "theme": {
    "customCss": ""
  },
  "library": {
    "scan": {
      "enabled": true,
      "cronExpression": "0 0 * * *"
    },
    "watch": {
      "enabled": false,
      "usePolling": false,
      "interval": 10000
    }
  },
  "server": {
    "externalDomain": "",
    "loginPageMessage": ""
  }
}
```

### Reproduction steps

```bash
I believe to reproduce:

- Take a MP photo, allow sync to occur.
- Confirm playback in a client.
- Delete encoded-video directory (or that specific asset)
- Rerun transcoding job

Confirm playback no longer functions on client.-
Observe in micro-services log errors from ffprobe.
Observe in browser the playback does not function - with errors in immich-server logs
```
