### ISSUE TITLE
[BUG] Missing thumbnails after viewing images

### ISSUE THREAD

**Issue by ExcelsiorEyer** [immich-app/immich#711]
**Describe the bug**
Some of the thumbnail images fail to load after viewing images

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x ] I have read thoroughly the README setup and installation instructions.
- [x ] I have included my `docker-compose` file.
- [x ] I have included my redacted `.env` file.
- [x ] I have included information on my machine, and environment.

**To Reproduce**
1. Open app
2. Click on any image to view
3. Swipe around to view few more images
4. Press the back button
5. Some of the thumbnails do not show anymore

**Expected behavior**
All thumbnails that were showing before need to show

**Screenshots**

**System**
- Phone OS [iOS, Android]: iOS 16.0.1
- Server Version: 1.29
- Mobile App Version: 1.29

docker-compose (I have the entire set of env variables repeated in my setup instead of an env file  because portainer doesn’t play nice in swarm)

```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    #env_file: stack.env
    environment:
      See below
    volumes:
      - nfs:/usr/src/app/upload
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM

  microsvc:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - nfs:/usr/src/app/upload
    #env_file: stack.env
    environment:
      See below
    restart: unless-stopped
    depends_on:
      - redis
      - db
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
          
  ml:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - nfs:/usr/src/app/upload
    #env_file: ../stack.env
    environment:
      See below
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
          
  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    #env_file: stack.env
    environment:
      See below
    restart: unless-stopped
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
          
  proxy:
    image: altran1502/immich-proxy:release
   #env_file: stack.env
    environment:
      See below
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: unless-stopped
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
          
  redis:
    image: redis:6.2
    #env_file: stack.env
    environment:
      See below
    restart: unless-stopped
    network_mode: "service:db"
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
          
  db:
    image: postgres:14
    #env_file: stack.env
    environment:
      See below
    volumes:
      - db_nfs:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - immich_nw
    deploy:
      placement:
        constraints:
          #- node.role == worker
          - node.hostname == DebianVM
     
volumes:
  db_nfs:
    driver: local
    driver_opts:
      type: "nfs4"
      o: addr=10.20.11.5,rw,nolock
      device: ":/volume1/Docker-Data/postgres"
  nfs:
    driver: local
    driver_opts:
      type: "nfs4"
      o: addr=10.20.11.5,rw,nolock
      device: ":/volume1/Docker-Data/immich"
      
networks:
  immich_nw:
```

environment variables:
```
      NODE_ENV: production
      DB_HOSTNAME: immich_db
      DB_USERNAME: uid
      DB_PASSWORD: pwd
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: immich_redis
      UPLOAD_LOCATION: nfs
      JWT_SECRET: FKvRg
      ENABLE_MAPBOX: "false"
      VITE_SERVER_ENDPOINT: http://immich.home.arpa:2283/api
      MAPBOX_KEY: pk
```
