### ISSUE TITLE
[BUG] Immich doesnt start after upgrading to 1.94.1

### ISSUE THREAD

**Issue by MergenStudios** [immich-app/immich#7213]
### The bug

I was running an old immich instance, and decided to upgrade to the newest version. I downloaded the updated docker-compose.yml and populated the .env file with values. For UPLOAD_LOCATION I just put in the upload location I had been using before. When it threw an error I checked the error, which relevealed it was having trouble with using the already existing datbase in the immich_pgdata volume. I proceeded to delete all remaining volumes related to immich, pruned all images and containers and ran `docker compose up --force-recreate`. It gave me the following error:

immich_postgres          | The files belonging to this database system will be owned by user "postgres".
immich_postgres          | This user must also own the server process.
immich_postgres          | 
immich_postgres          | The database cluster will be initialized with locale "en_US.utf8".
immich_postgres          | The default database encoding has accordingly been set to "UTF8".
immich_postgres          | The default text search configuration will be set to "english".
immich_postgres          | 
immich_postgres          | Data page checksums are disabled.
immich_postgres          | 
immich_postgres          | fixing permissions on existing directory /var/lib/postgresql/data ... ok
immich_postgres          | creating subdirectories ... ok
immich_postgres          | selecting dynamic shared memory implementation ... posix
immich_postgres          | selecting default max_connections ... 100
immich_postgres          | selecting default shared_buffers ... 128MB
immich_postgres          | selecting default time zone ... Etc/UTC
immich_postgres          | creating configuration files ... ok
immich_postgres          | running bootstrap script ... ok
immich_postgres          | performing post-bootstrap initialization ... ok
immich_postgres          | syncing data to disk ... ok
immich_postgres          | 
immich_postgres          | 
immich_postgres          | Success. You can now start the database server using:
immich_postgres          | 
immich_postgres          |     pg_ctl -D /var/lib/postgresql/data -l logfile start
immich_postgres          | 
immich_postgres          | initdb: warning: enabling "trust" authentication for local connections
immich_postgres          | You can change this by editing pg_hba.conf or using the option -A, or
immich_postgres          | --auth-local and --auth-host, the next time you run initdb.
immich_postgres          | waiting for server to start....2024-02-19 21:09:17.197 UTC [48] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich_postgres          | 2024-02-19 21:09:17.206 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich_postgres          | 2024-02-19 21:09:17.227 UTC [49] LOG:  database system was shut down at 2024-02-19 21:09:16 UTC
immich_postgres          | 2024-02-19 21:09:17.237 UTC [48] LOG:  database system is ready to accept connections
immich_postgres          |  done
immich_postgres          | server started
immich_machine_learning  | [02/19/24 21:09:17] INFO     Starting gunicorn 21.2.0                           
immich_machine_learning  | [02/19/24 21:09:17] INFO     Listening at: http://0.0.0.0:3003 (9)              
immich_machine_learning  | [02/19/24 21:09:17] INFO     Using worker: app.config.CustomUvicornWorker       
immich_machine_learning  | [02/19/24 21:09:17] INFO     Booting worker with pid: 17                        
immich_postgres          | CREATE DATABASE
immich_postgres          | 
immich_postgres          | 
immich_postgres          | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
immich_postgres          | 
immich_postgres          | waiting for server to shut down...2024-02-19 21:09:17.499 UTC [48] LOG:  received fast shutdown request
immich_postgres          | .2024-02-19 21:09:17.505 UTC [48] LOG:  aborting any active transactions
immich_postgres          | 2024-02-19 21:09:17.508 UTC [48] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
immich_postgres          | 2024-02-19 21:09:17.509 UTC [51] LOG:  shutting down
immich_postgres          | 2024-02-19 21:09:17.550 UTC [48] LOG:  database system is shut down
immich_postgres          |  done
immich_postgres          | server stopped
immich_postgres          | 
immich_postgres          | PostgreSQL init process complete; ready for start up.
immich_postgres          | 
immich_postgres          | 2024-02-19 21:09:17.641 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich_postgres          | 2024-02-19 21:09:17.641 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich_postgres          | 2024-02-19 21:09:17.641 UTC [1] LOG:  listening on IPv6 address "::", port 5432
immich_postgres          | 2024-02-19 21:09:17.652 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich_postgres          | 2024-02-19 21:09:17.665 UTC [66] LOG:  database system was shut down at 2024-02-19 21:09:17 UTC
immich_postgres          | 2024-02-19 21:09:17.675 UTC [1] LOG:  database system is ready to accept connections
immich_postgres          | 2024-02-19 21:09:20.065 UTC [81] ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
immich_postgres          | 2024-02-19 21:09:20.065 UTC [81] DETAIL:  Key (typname, typnamespace)=(users, 2200) already exists.
immich_postgres          | 2024-02-19 21:09:20.065 UTC [81] STATEMENT:  
immich_postgres          |              create table if not exists users
immich_postgres          |              (
immich_postgres          |                  id          uuid      default uuid_generate_v4() not null
immich_postgres          |                      constraint "PK_a3ffb1c0c8416b9fc6f907b7433"
immich_postgres          |                          primary key,
immich_postgres          |                  email       varchar                              not null,
immich_postgres          |                  password    varchar                              not null,
immich_postgres          |                  salt        varchar                              not null,
immich_postgres          |                  "createdAt" timestamp default now()              not null
immich_postgres          |              );
immich_postgres          |            
immich_server            | Migration "CreateUserTable1645130759468" failed, error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
immich_server            | /usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
immich_server            |             throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
immich_server            |                   ^
immich_server            | 
immich_server            | QueryFailedError: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
immich_server            |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_server            |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |     at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
immich_server            |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:263:35)
immich_server            |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/infra/repositories/database.repository.js:42:9)
immich_server            |     at async DatabaseService.init (/usr/src/app/dist/domain/database/database.service.js:33:9)
immich_server            |     at async AppService.init (/usr/src/app/dist/immich/app.service.js:56:9)
immich_server            |     at async AppModule.onModuleInit (/usr/src/app/dist/immich/app.module.js:32:9)
immich_server            |     at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9) {
immich_server            |   query: '\n' +
immich_server            |     '        create table if not exists users\n' +
immich_server            |     '        (\n' +
immich_server            |     '            id          uuid      default uuid_generate_v4() not null\n' +
immich_server            |     '                constraint "PK_a3ffb1c0c8416b9fc6f907b7433"\n' +
immich_server            |     '                    primary key,\n' +
immich_server            |     '            email       varchar                              not null,\n' +
immich_server            |     '            password    varchar                              not null,\n' +
immich_server            |     '            salt        varchar                              not null,\n' +
immich_server            |     '            "createdAt" timestamp default now()              not null\n' +
immich_server            |     '        );\n' +
immich_server            |     '      ',
immich_server            |   parameters: undefined,
immich_server            |   driverError: error: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
immich_server            |       at /usr/src/app/node_modules/pg/lib/client.js:526:17
immich_server            |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_server            |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_server            |       at async CreateUserTable1645130759468.up (/usr/src/app/dist/infra/migrations/1645130759468-CreateUserTable.js:6:9)
immich_server            |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_server            |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:263:35)
immich_server            |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/infra/repositories/database.repository.js:42:9)
immich_server            |       at async DatabaseService.init (/usr/src/app/dist/domain/database/database.service.js:33:9)
immich_server            |       at async AppService.init (/usr/src/app/dist/immich/app.service.js:56:9)
immich_server            |       at async AppModule.onModuleInit (/usr/src/app/dist/immich/app.module.js:32:9) {
immich_server            |     length: 245,
immich_server            |     severity: 'ERROR',
immich_server            |     code: '23505',
immich_server            |     detail: 'Key (typname, typnamespace)=(users, 2200) already exists.',
immich_server            |     hint: undefined,
immich_server            |     position: undefined,
immich_server            |     internalPosition: undefined,
immich_server            |     internalQuery: undefined,
immich_server            |     where: undefined,
immich_server            |     schema: 'pg_catalog',
immich_server            |     table: 'pg_type',
immich_server            |     column: undefined,
immich_server            |     dataType: undefined,
immich_server            |     constraint: 'pg_type_typname_nsp_index',
immich_server            |     file: 'nbtinsert.c',
immich_server            |     line: '663',
immich_server            |     routine: '_bt_check_unique'
immich_server            |   },
immich_server            |   length: 245,
immich_server            |   severity: 'ERROR',
immich_server            |   code: '23505',
immich_server            |   detail: 'Key (typname, typnamespace)=(users, 2200) already exists.',
immich_server            |   hint: undefined,
immich_server            |   position: undefined,
immich_server            |   internalPosition: undefined,
immich_server            |   internalQuery: undefined,
immich_server            |   where: undefined,
immich_server            |   schema: 'pg_catalog',
immich_server            |   table: 'pg_type',
immich_server            |   column: undefined,
immich_server            |   dataType: undefined,
immich_server            |   constraint: 'pg_type_typname_nsp_index',
immich_server            |   file: 'nbtinsert.c',
immich_server            |   line: '663',
immich_server            |   routine: '_bt_check_unique'
immich_server            | }
immich_server            | 
immich_server            | Node.js v20.11.0

### The OS that Immich Server is running on

Debian GNU/Linux 11 (bullseye) x86_64

### Version of Immich Server

1.94.1

### Version of Immich Mobile App

latest

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/nas/raid1_volume/docker_volumes/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
as stated above
```

### Additional information

no adiitional information
