### ISSUE TITLE
After update 1.9.5 image server was broken

### ISSUE THREAD

**Issue by ydrob** [immich-app/immich#7261]
### The bug

After update 1.9.5 image server was broken, microserver and server containers stop after running. Logs are attached.
[server.xlsx](https://github.com/immich-app/immich/files/14350969/server.xlsx)
[microservices.xlsx](https://github.com/immich-app/immich/files/14350970/microservices.xlsx)

![Screenshot_1](https://github.com/immich-app/immich/assets/77321248/d413cb38-9144-42a2-9f81-ec0b533b2756)

### The OS that Immich Server is running on

synology dsm 7.2.1 u4

### Version of Immich Server

v1.9.5

### Version of Immich Mobile App

v1.95.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: test_immich

services:
  immich-server:
    container_name: test_immich_server
    image: ghcr.io/immich-app/immich-server:v1.95.0
    environment:
      DB_HOSTNAME: test_immich_postgres
      REDIS_HOSTNAME: test_immich_redis
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    command: [ "start.sh", "immich" ]
    volumes:
      - /volume1/docker/test_immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 1283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: test_immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.95.0
    environment:
      DB_HOSTNAME: test_immich_postgres
      REDIS_HOSTNAME: test_immich_redis
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - /volume1/docker/test_immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: test_immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.95.0
    environment:
      DB_HOSTNAME: test_immich_postgres
      REDIS_HOSTNAME: test_immich_redis
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: test_immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped

  database:
    container_name: test_immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    environment:
      DB_HOSTNAME: test_immich_postgres
      REDIS_HOSTNAME: test_immich_redis
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/docker/test_immich/upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.95.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=nh68MzprxILz3

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Update yaml to use version 1.9.5
2.Run project
3.
...
```
