### ISSUE TITLE
Since 1.95.0 both microservices and Immich containers do not start (ERR: start.sh: 4: Bad substitution)

### ISSUE THREAD

**Issue by progecon** [immich-app/immich#7298]
### The bug

Title. Updating their versions to 1.95.1 did not help. I do not have any other entries in both container's logs.

![image](https://github.com/immich-app/immich/assets/109902876/c89b1306-b474-4e3c-ac2a-49638aedbbb3)

### The OS that Immich Server is running on

Docker on Ubuntu 22.04

### Version of Immich Server

v.1.95.1

### Version of Immich Mobile App

not important for this

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
(cosmos-compose for cosmos server)

{
  "services": {
    "Immich": {
      "container_name": "Immich",
      "image": "ghcr.io/immich-app/immich-server:v1.95.1",
      "environment": [
        "UPLOAD_LOCATION=/usr/src/app/upload",
        "TYPESENSE_API_KEY=${API}",
        "DB_PASSWORD=${Password}",
        "DB_HOSTNAME=Immich-database",
        "DB_USERNAME=postgres",
        "DB_DATABASE_NAME=immich",
        "REDIS_HOSTNAME=Immich-redis",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/bin",
        "NODE_VERSION=20.10.0",
        "YARN_VERSION=1.22.19",
        "NODE_ENV=production",
        "NVIDIA_DRIVER_CAPABILITIES=all",
        "NVIDIA_VISIBLE_DEVICES=all"
      ],
      "labels": {
        "cosmos-auto-update": "true",
        "cosmos-force-network-secured": "true",
        "cosmos-icon": "https://azukaar.github.io/cosmos-servapps-official/servapps/Immich/icon.png",
        "cosmos-network-name": "Immich",
        "cosmos-persistent-env": "UPLOAD_LOCATION, TYPESENSE_API_KEY, DB_PASSWORD, DB_DATABASE_NAME",
        "cosmos-stack": "Immich",
        "cosmos-stack-main": "Immich",
        "org.opencontainers.image.created": "2023-12-19T04:41:50.737Z",
        "org.opencontainers.image.description": "Self-hosted photo and video backup solution directly from your mobile phone.",
        "org.opencontainers.image.licenses": "MIT",
        "org.opencontainers.image.revision": "b40859551b2e792afafdfe4057de6ef1276ad47c",
        "org.opencontainers.image.source": "https://github.com/immich-app/immich",
        "org.opencontainers.image.title": "immich",
        "org.opencontainers.image.url": "https://github.com/immich-app/immich",
        "org.opencontainers.image.version": "v1.91.4"
      },
      "ports": [],
      "volumes": [
        {
          "Type": "bind",
          "Source": "/home/${USER}/mnt/XXX/Fotos",
          "Target": "/photos/import"
        },
        {
          "Type": "bind",
          "Source": "/home/${USER}/photos",
          "Target": "/usr/src/app/upload"
        },
        {
          "Type": "bind",
          "Source": "/etc/localtime",
          "Target": "/etc/localtime"
        }
      ],
      "networks": {
        "Immich": {},
        "bridge": {}
      },
      "routes": null,
      "restart": "always",
      "devices": null,
      "expose": [],
      "depends_on": [],
      "command": "start.sh immich",
      "entrypoint": "tini -- /bin/sh",
      "working_dir": "/usr/src/app",
      "hostname": "Immich",
      "network_mode": "default",
      "healthcheck": {
        "test": null,
        "interval": 0,
        "timeout": 0,
        "retries": 0,
        "start_period": 0
      }
    }
  }
}
```

### Your .env content

```Shell
"UPLOAD_LOCATION=/usr/src/app/upload",
        "TYPESENSE_API_KEY=${API}",
        "DB_PASSWORD=${Password}",
        "DB_HOSTNAME=Immich-database",
        "DB_USERNAME=postgres",
        "DB_DATABASE_NAME=immich",
        "REDIS_HOSTNAME=Immich-redis",
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/bin",
        "NODE_VERSION=20.10.0",
        "YARN_VERSION=1.22.19",
        "NODE_ENV=production",
        "NVIDIA_DRIVER_CAPABILITIES=all",
        "NVIDIA_VISIBLE_DEVICES=all"
```

### Reproduction steps

```bash
1.Be an idiot and auto-update
2.wake up to see the error in the image in both containers.
```
