### ISSUE TITLE
Search in 1.95.1 only returns a single result

### ISSUE THREAD

**Issue by installlooc** [immich-app/immich#7313]
### The bug

When attempting to search for any details, either using the simple search box or the advanced search box, only a single result is returned.

This appears to be a regression from 1.95.0, which was working fine before I updated to 1.95.1

### The OS that Immich Server is running on

Ubuntu 22.04.3 (Portainer)

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    networks:
      - proxy
    container_name: immich_server
    labels:
      - "traefik.http.routers.immich.rule=Host(`redacted`)"
      - "traefik.http.routers.immich.tls=true"
      - "traefik.http.routers.immich.tls.certresolver=cfresolver"
      - "traefik.http.routers.immich.entrypoints=websecure"
      - traefik.enable=true
    image: ghcr.io/immich-app/immich-server:v1.95.1
    ports:
      - 2283:3001
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.95.1
    networks:
      - proxy
    group_add:
      - "109" # Intel Quick Sync
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    networks:
      - proxy
    image: ghcr.io/immich-app/immich-machine-learning:v1.95.1
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    
  redis:
    container_name: immich_redis
    networks:
      - proxy
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    networks:
      - proxy
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
  model-cache:

networks:
  proxy:
    name: proxy
```

### Your .env content

```Shell
UPLOAD_LOCATION=redacted
DB_PASSWORD=redacted
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Begin a search using the advanced search button
2. Fill in only the context field
3. Get only a single result when filled in.
4. Repeat this with any combination of fields, as long as context is filled in.
```
