### ISSUE TITLE
Searching for metadata no longer works 1.95.1

### ISSUE THREAD

**Issue by Philshappy** [immich-app/immich#7314]
### The bug

When searching for a specific value in the metadata the search results is inaccurate.

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

V1.95.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/NAS6602/Photos:/mnt/media/Photos:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001  
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/NAS6602/Photos:/mnt/media/Photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri:/dev/dri
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /home/phil/Immich/database:/var/lib/postgresql/data
    restart: always


volumes:
  model-cache:
```

### Your .env content

```Shell
x
```

### Reproduction steps

```bash
1.type in the search bar m:xxx
2.
3.
...
```
