### ISSUE TITLE
Immich 1.95.1 Upgrade - Postgresql Errors

### ISSUE THREAD

**Issue by l4rm4nd** [immich-app/immich#7327]
### The bug

I've followed the release instructions to upgrade immich from v1.94.1 to 1.95.1.

What have I done:

1. Change the Docker image tags from v1.94.1 to 1.95.1 (except for postgresql of course).
2. Change the Docker image tag for postgresql from 0.1.11 to 0.2.0
3. Restarted the stack and/or postgresql container mutliple times as outlined by immich's release comments

This did not work though and the stack did not come up healthy.

````
immich-database       | 2024-02-22 01:06:36.636 UTC [1] LOG:  starting PostgreSQL 14.10 (Debian 14.10-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
immich-database       | 2024-02-22 01:06:36.636 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
immich-database       | 2024-02-22 01:06:36.637 UTC [1] LOG:  listening on IPv6 address "::", port 5432
immich-database       | 2024-02-22 01:06:36.646 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
immich-database       | 2024-02-22 01:06:36.662 UTC [28] LOG:  database system was shut down at 2024-02-22 01:06:32 UTC
immich-database       | [2024-02-22T01:06:36Z ERROR vectors::bgworker] Panickied. Info: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a sequences/file_atomic.rs", line: 51, col: 52 }, can_unwind: true, force_no_backtrace: false }. Backtrace: disabled backtrace.
immich-database       | 2024-02-22 01:06:36.687 UTC [1] LOG:  database system is ready to accept connections

....

immich-database       | 2024-02-22 01:06:57.346 UTC [40] ERROR:  pgvecto.rs: IPC connection is closed unexpected.
immich-database       |         ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
immich-database       | 2024-02-22 01:06:57.346 UTC [40] STATEMENT:
immich-database       |                   SELECT idx_status
immich-database       |                   FROM pg_vector_index_stat
immich-database       |                   WHERE indexname = $1
immich-microservices  | [Nest] 7  - 02/22/2024, 1:06:57 AM    WARN [DatabaseService] Could not run vector reindexing checks. If the extension was updated, please restart the Postgres instance.
immich-microservices  | /usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
immich-microservices  |             throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
immich-microservices  |                   ^
immich-microservices  |
immich-microservices  | QueryFailedError: pgvecto.rs: IPC connection is closed unexpected.
immich-microservices  | ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
immich-microservices  |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich-microservices  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich-microservices  |     at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
immich-microservices  |     at async DatabaseRepository.shouldReindex (/usr/src/app/dist/infra/repositories/database.repository.js:127:25)
immich-microservices  |     at async /usr/src/app/dist/domain/database/database.service.js:41:21
immich-microservices  |     at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
immich-microservices  |   query: '\n' +
immich-microservices  |     '          SELECT idx_status\n' +
immich-microservices  |     '          FROM pg_vector_index_stat\n' +
immich-microservices  |     '          WHERE indexname = $1',
immich-microservices  |   parameters: [ 'clip_index' ],
immich-microservices  |   driverError: error: pgvecto.rs: IPC connection is closed unexpected.
immich-microservices  |   ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
immich-microservices  |       at /usr/src/app/node_modules/pg/lib/client.js:526:17
immich-microservices  |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich-microservices  |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich-microservices  |       at async DataSource.query (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:350:20)
immich-microservices  |       at async DatabaseRepository.shouldReindex (/usr/src/app/dist/infra/repositories/database.repository.js:127:25)
immich-microservices  |       at async /usr/src/app/dist/domain/database/database.service.js:41:21
immich-microservices  |       at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
immich-microservices  |     length: 272,
immich-microservices  |     severity: 'ERROR',
immich-microservices  |     code: 'XX000',
````
I've then proceeded with the manual psql command instructions from the immich's release section. As I am using a different database name for my immich stack, I had to slightly adjust one command to hold my custom database name.

What I did:

````
docker compose down
docker compose up -d immich-database

# exec into psql container
docker exec -it immich-database bash

# inside the psql container
psql -U postgres -d immich-psgdb

# inside the psql db cli shell
BEGIN;
CREATE SCHEMA IF NOT EXISTS vectors;
ALTER DATABASE "immich-psgdb" SET search_path TO "$user", public, vectors;
SET search_path TO "$user", public, vectors;
UPDATE pg_catalog.pg_extension SET extversion = '0.1.11' WHERE extname = 'vectors';
UPDATE pg_catalog.pg_extension SET extrelocatable = true WHERE extname = 'vectors';
ALTER EXTENSION vectors SET SCHEMA vectors;
UPDATE pg_catalog.pg_extension SET extrelocatable = false WHERE extname = 'vectors';
ALTER EXTENSION vectors UPDATE TO '0.2.0';
SELECT pgvectors_upgrade();
COMMIT;
````
The commands went mostly through. The last command `SELECT pgvectors_upgrade();` fails though:

````
immich-psgdb=# SELECT pgvectors_upgrade();

ERROR:  pgvecto.rs: IPC connection is closed unexpected.
ADVICE: The error is raisen by background worker errors. Please check the full PostgreSQL log to get more information. Please read `https://docs.pgvecto.rs/admin/configuration.html`.
````

I've recovered from backup and running v1.94.1 again flawlessly.

Any hints how to fix the issue? 

Might be a bug in pgvecto.rs due to null values (see https://github.com/tensorchord/pgvecto.rs/issues/376#issuecomment-1960701731)

### The OS that Immich Server is running on

Ubuntu 22.04 LTS x86

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:v1.95.1
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    expose:
      - 3001
    depends_on:
      - immich-redis
      - immich-database
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`photos.mydomain.com`)
      - traefik.http.services.immich.loadbalancer.server.port=3001
      - traefik.docker.network=immich_default
      #- traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=5000000000 # optional, only necessary for file uploads; allow 5000MB
      #- traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=5000000000 # optional, only necessary for file uploads; allow 5000MB
      #- traefik.http.middlewares.limit.buffering.memRequestBodyBytes=5000000000 # optional, only necessary for file uploads; allow 5000MB
      #- traefik.http.middlewares.limit.buffering.memResponseBodyBytes=5000000000 # optional, only necessary for file uploads; allow 5000MB
      # Part for local lan services only
      - traefik.http.routers.immich.middlewares=local-ipwhitelist@file
      - com.centurylinklabs.watchtower.enable=true

  immich-microservices:
    container_name: immich-microservices
    image: altran1502/immich-server:v1.95.1
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-redis
      - immich-database
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  immich-machine-learning:
    image: altran1502/immich-machine-learning:v1.95.1
    container_name: immich-ml
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  immich-redis:
    container_name: immich-redis
    image: redis:6.2-alpine
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  immich-database:
    container_name: immich-database
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ${DB_DATABASE_LOCATION}:/var/lib/postgresql/data
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  model-cache:
```

### Your .env content

```Shell
# Database
DB_HOSTNAME=immich-database
DB_USERNAME=postgres
DB_PASSWORD=<masked-for-github>
DB_DATABASE_NAME=immich-psgdb
DB_DATABASE_LOCATION=/mnt/docker-volumes/immich/database

# Redis
REDIS_HOSTNAME=immich-redis

# Upload File Config
UPLOAD_LOCATION=/mnt/another-nfs-datastore/immich/uploads

# JWT SECRET
JWT_SECRET=<masked-for-github>
```

### Reproduction steps

```bash
1. Adjust compose to hold the new image versions
5. docker compose down && docker compose pull
6. docker compose up
7. PSQL throws errors
8. docker compose down
9. docker compose up -d immich-database
10. docker exec -it immich-database bash
11. Inside container connect to database via `psql -U postgres -d immich-psgdb` and run the commands from the release instructions to manually upgrade pgvecto-rs from 0.1.11 to 0.2.0.
12. Perceive error when executing `SELECT pgvectors_upgrade();`

```
