### ISSUE TITLE
Archived pictures appear as "untracked files" in v1.95.1 

### ISSUE THREAD

**Issue by Sangeppato** [immich-app/immich#7333]
### The bug

After upgrading to v1.95.1 from v1.94.1, all the archived pictures and the corresponding thumbnails appear as "untracked files" in the "repair" section. This holds for both previously and newly archived items.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    user: ${PUID}:${PGID}
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - default
      - npm

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    user: ${PUID}:${PGID}
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    user: ${PUID}:${PGID}
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    command: ["redis-server", "--save", ""]
    user: ${PUID}:${PGID}
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    user: ${PUID}:${PGID}
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:

networks:
  npm:
    external: true
    name: npm_default
```

### Your .env content

```Shell
IMMICH_VERSION=v1.95.1
TYPESENSE_API_KEY=key
DB_PASSWORD=passwd
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
PUID=1000
PGID=1000
UPLOAD_LOCATION=/storage/apps/immich/upload
PG_DATA=/data/apps/immich/pgdata
```

### Reproduction steps

```bash
1. Upgrade to v1.95.1
2. Archive some pictures
3. Go to Administration/Repair in the web UI and look at the untracked files
```
