### ISSUE TITLE
New search function - data is not transferred correctly

### ISSUE THREAD

**Issue by DeltaTango69** [immich-app/immich#7350]
### The bug

Enter in new search function from date to date - dates in search are changed:

Example:

![image](https://github.com/immich-app/immich/assets/82575543/5d41c6e2-f674-4451-bfe3-0f2a3b60b329)

Result:

![image](https://github.com/immich-app/immich/assets/82575543/2fb5be55-a551-4fb3-b14f-de6c9e7cdef8)

Only media from 03 April are showed.

Then suddenly this happens and I have no chance to get out:

![image](https://github.com/immich-app/immich/assets/82575543/9874b8a8-2437-4bf5-bbec-9adbe37cbaf8)

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

V1.95.1

### Version of Immich Mobile App

1.95.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "bilder2:/mnt/media/bilder_all:ro"
      - "mobil:/mnt/media/mobil:ro"
      - "insta:/mnt/media/insta:ro"
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - "bilder2:/mnt/media/bilder_all:ro"
      - "mobil:/mnt/media/mobil:ro"
      - "insta:/mnt/media/insta:ro"
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  bilder2:
    driver_opts:
      type: cifs
      o: "username=xxxxxx,password=xxxxxxxxxx,rw"
      device: "//192.168.178.4/Bilder_ok"
  insta:
    driver_opts:
      type: cifs
      o: "username=xxxxxx,password=xxxxxxxxxx,rw"
      device: "//192.168.178.4/insta"
  mobil:
    driver_opts:
      type: cifs
      o: "username=xxxxxx,password=xxxxxxxxxx,rw"
      device: "//192.168.178.4/mobil_bilder"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
 TZ=Europe/Berlin

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
see above
```
