### ISSUE TITLE
Update to 1.95.1: Error: Failed to fetch GitHub release

### ISSUE THREAD

**Issue by maxhofi1694** [immich-app/immich#7366]
### The bug

I followed the update procedure provided with v1.95.0 from v.1.93.3 and everything went fine. With the final docker compose up following error appear in immich_server:
`[Nest] 8  - 02/23/2024, 11:41:44 AM    WARN [Error: Failed to fetch GitHub release: TypeError: fetch failed
    at ServerInfoRepository.getGitHubRelease (/usr/src/app/dist/infra/repositories/server-info.repository.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ServerInfoService.handleVersionCheck (/usr/src/app/dist/domain/server-info/server-info.service.js:133:35)
    at async ServerInfoService.init (/usr/src/app/dist/domain/server-info/server-info.service.js:47:9)
    at async AppService.init (/usr/src/app/dist/immich/app.service.js:68:9)
    at async AppModule.onModuleInit (/usr/src/app/dist/immich/app.module.js:33:9)
    at async callModuleInitHook (/usr/src/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
    at async NestApplication.callInitHook (/usr/src/app/node_modules/@nestjs/core/nest-application-context.js:223:13)
    at async NestApplication.init (/usr/src/app/node_modules/@nestjs/core/nest-application.js:100:9)
    at async NestApplication.listen (/usr/src/app/node_modules/@nestjs/core/nest-application.js:169:33)] Unable to run version check: Error: Failed to fetch GitHub release: TypeError: fetch failed
`

nevertheless the service continues to run. I can access Immich fine on mobile and web, but in the administration view the server seems to be offline and the version is unkown:
![image](https://github.com/immich-app/immich/assets/77584664/ab85bb43-15c9-41a6-8a7b-a03395a6f6f4)

### The OS that Immich Server is running on

Debian 12/RaspberyPiOS

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95.0 build.122

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. update according release notes from 1.93.3
2. docker compose up
3. check docker logs immich_server
```
