### ISSUE TITLE
STORAGE TEMPLATE - {{album}} is always empty

### ISSUE THREAD

**Issue by bedeutsch** [immich-app/immich#7393]
### The bug

Hello, 

I am trying to use the {{album}} variable in the file name from the Storage Template when backing up files from a mobile device.

<img width="960" alt="Screenshot 2024-02-24 at 13 57 08" src="https://github.com/immich-app/immich/assets/50231215/fa69e1b6-a202-4d6c-8c23-0821315e1d0a">

However, when the file is uploaded, the file name is proceeded by a '.' and the {{album}} is blank:
<img width="461" alt="Screenshot 2024-02-24 at 14 07 52" src="https://github.com/immich-app/immich/assets/50231215/d97df349-3c20-415e-aab8-bd542de66c1e">

From the mobile device:

![Screenshot_20240224-141442](https://github.com/immich-app/immich/assets/50231215/5e9e6430-f163-4073-bc29-c8805b87017a)

I've tried running the Storage Migration Job (as written in the instructions) both before and after the file upload, but the {{album}} variable is never populated.

### The OS that Immich Server is running on

MacOS Sonoma 14.3

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

1.95.0 build.122

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/Users/MAINU/Pictures/IMMICH TEST

# Defining External Path
EXTERNAL_PATH=/Users/MAINU/Pictures/IMMICH TEST

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=immrich_dummy1

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create a new album on the mobile device using the native app (Gallery)
2. Select the album to be backed up in the settings
3. Run the Storage Migration Job on the server
4. Move an asset into the newly created album in the native app
5. Upload the asset from the Immich mobile app
6. Run the Storage Migration Job on the server (as a 2nd check)
...
```
