### ISSUE TITLE
Mobile app Photos & Library tab seemingly spin forever

### ISSUE THREAD

**Issue by rcrisanti** [immich-app/immich#7498]
### The bug

The "Photos" & "Library" tabs on the iOS mobile app tab bar seemingly spin forever, even after the backup icon at the top is done spinning. I'm not clear on what those spinners indicate, but it seems like it's just stuck. The "Search" & "Sharing" tabs do not have the spinner. All my photos seem to be there, so this is just a minor visual bug I think.
![immich-tabbar](https://github.com/immich-app/immich/assets/27363609/1b5cda7a-e65b-4d5f-a78b-84ed7869129f)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.95.1

### Version of Immich Mobile App

v1.95.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    secrets:
      - DB_PASSWORD_FILE
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    secrets:
      - DB_PASSWORD_FILE
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/DB_PASSWORD_FILE
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    secrets:
      - DB_PASSWORD_FILE
    restart: always

secrets:
  DB_PASSWORD_FILE:
    file: /etc/immich/POSTGRES_PASSWORD

volumes:
  pgdata:
  model-cache:

networks:
  default:
    name: caddy_net
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/homeserver/immich
IMMICH_VERSION=v1.95.1
DB_PASSWORD_FILE="/run/secrets/DB_PASSWORD_FILE"
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. It seems to happen for me every time I open the mobile app
```
