### ISSUE TITLE
Need to add port 3003 for machine learning or microservices fails to connect

### ISSUE THREAD

**Issue by spusuf** [immich-app/immich#7518]
### The bug

Default compose.yml does not expose port 3003 on machine learning server for microservices to connect to. If you look at the logs there are a bunch of errors about failing to connect to machine learning server. Needed to add the following to get my instance to work:
```
immich-machine-learning:
  ports:
    - 3003:3003
```

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

1.97.0

### Version of Immich Mobile App

1.96.0.build.125

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    ports:
      - 3003:3003

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/POOL/photos/immich/library
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
Run docker compose with latest compose.yml
Start the Face Detection job
Observe logs in microservices container
Errors appear
```

**Comment by alextran1502** [comment]
The port is used internally since the containers use docker's network and DNS to communicate, it has been working for the last 1.5 years. I don't see anything abnormal from your configuration. This is strange. From my prod instance, I don't need to expose to port to get it to work

**Comment by spusuf** [comment]
```
[Nest] 7  - 02/29/2024, 5:08:47 AM   ERROR [JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request to "http://192.168.1.2:3003" failed with Error: connect ECONNREFUSED 192.168.1.2:3003

[Nest] 7  - 02/29/2024, 5:08:47 AM   ERROR [JobService] Error: Machine learning request to "http://192.168.1.2:3003" failed with Error: connect ECONNREFUSED 192.168.1.2:3003

    at /usr/src/app/dist/infra/repositories/machine-learning.repository.js:18:19

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async MachineLearningRepository.predict (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:17:21)

    at async PersonService.handleDetectFaces (/usr/src/app/dist/domain/person/person.service.js:246:23)

    at async /usr/src/app/dist/domain/job/job.service.js:137:37

    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)

    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)

[Nest] 7  - 02/29/2024, 5:08:47 AM   ERROR [JobService] Object:

{

  "id": "651f26e2-e4f6-4c8e-ac1b-4d90c2e6a67d"

}
```

**Comment by spusuf** [comment]
To add, machine learning did not work without manually inputting the IP (even though it is the same stack on the same machine), and adding the port opening in the compose file

**Comment by bo0tzz** [comment]
> request to "http://192.168.1.2:3003"

You entered your host machine's address for ML, so of course the port will need to be open to connect. The default should work just fine internally, no need to change it.

**Comment by spusuf** [comment]
The machine learning IP is listed as required, if it is expected to be blank do not make it a required field

**Comment by jrasm91** [comment]
It is required, but there is a default value which works just fine.

**Comment by s0nerik** [comment]
Here's the error messages I get:

```
immich_microservices     | [Nest] 7  - 05/17/2024, 2:56:46 PM   ERROR [ImmichMicroservices] [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "7b4028b6-ee6e-44a8-b60b-f06c051dcafa"
immich_microservices     | }
immich_microservices     |
immich_microservices     | [Nest] 7  - 05/17/2024, 2:56:46 PM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     | [Nest] 7  - 05/17/2024, 2:56:46 PM   ERROR [ImmichMicroservices] [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with SocketError: other side closed
immich_microservices     |     at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
immich_microservices     |     at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
immich_microservices     |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:86:31)
immich_microservices     |     at async /usr/src/app/dist/services/job.service.js:145:36
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 05/17/2024, 2:56:46 PM   ERROR [ImmichMicroservices] [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "62d1439e-b340-45e3-aba4-f59b961c6b39"
immich_microservices     | }
immich_microservices     |
immich_microservices     | [Nest] 7  - 05/17/2024, 5:53:16 PM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (faceDetection/face-detection): Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
immich_microservices     | [Nest] 7  - 05/17/2024, 5:53:16 PM   ERROR [ImmichMicroservices] [JobService] Error: Machine learning request for facial recognition failed with status 500: Internal Server Error
immich_microservices     |     at MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:23:19)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async PersonService.handleDetectFaces (/usr/src/app/dist/services/person.service.js:270:23)
immich_microservices     |     at async /usr/src/app/dist/services/job.service.js:145:36
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 05/17/2024, 5:53:16 PM   ERROR [ImmichMicroservices] [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "ac338d50-212d-4b24-a5aa-ea8030c3b72f"
immich_microservices     | }
immich_microservices     |
```

It used to work just fine ten or so versions ago on the same hardware. BTW, it's on Intel N100 built-in GPU with OpenVINO.

**Comment by s0nerik** [comment]
Specifying a port didn't help in my case.

**Comment by Lipown** [comment]
I am facing same error.

**Comment by alextran1502** [comment]
@s0nerik @Lipown please post your docker-compose and env file

**Comment by s0nerik** [comment]
@alextran1502 Here's mine:

docker-compose.yml:
```yaml
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./old-library-as-external:/mnt/media/old-library-as-external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ./old-library-as-external:/mnt/media/old-library-as-external:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

volumes:
  model-cache:

```

.env:
```
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

hwaccel.ml.yml:
```yaml
version: "3.8"

# Configurations for hardware-accelerated machine learning

# If using Unraid or another platform that doesn't allow multiple Compose files,
# you can inline the config for a backend by copying its contents 
# into the immich-machine-learning service in the docker-compose.yml file.

# See https://immich.app/docs/features/ml-hardware-acceleration for info on usage.

services:
  armnn:
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
      - /usr/lib/libmali.so:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)

  cpu: {}

  cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

  openvino:
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb

  openvino-wsl:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /usr/lib/wsl:/usr/lib/wsl

```
