### ISSUE TITLE
Failed to finish oauth - callback 500 (Internal Server Error)

### ISSUE THREAD

**Issue by volcvn8** [immich-app/immich#7614]
### The bug

Hello. We encountered a problem through OAuth Authentication. Following this instructions https://immich.app/docs/administration/oauth/ we configure immich and oauth service.
After successfully authentication on oauth service, the authorization code successfully redirect from to immich endpoint /auth/login
then we have following error on login page:

Failed to finish oauth.

on browser log we have error:
![Screenshot_16](https://github.com/immich-app/immich/assets/162098915/89de7382-5922-41ae-876c-b846d20e8257)

entry.DJzkMQyl.js:1 
          
POST http://10.38.46.176:2283/api/oauth/callback 500 (Internal Server Error)
window.fetch @ entry.DJzkMQyl.js:1
c @ fetch-client.IOYw_s6m.js:1
n @ fetch-client.IOYw_s6m.js:1
o @ fetch-client.IOYw_s6m.js:1
ut @ fetch-client.IOYw_s6m.js:1
login @ utils.tSb-PrBI.js:1
(anonymous) @ 40.APKiO6AH.js:1
K @ scheduler.a1YLkTt0.js:1
(anonymous) @ index.agc2DCvO.js:4
ft @ scheduler.a1YLkTt0.js:1
Promise.then (async)
at @ scheduler.a1YLkTt0.js:1
ht @ index.agc2DCvO.js:4
(anonymous) @ index.agc2DCvO.js:4
(anonymous) @ 40.APKiO6AH.js:1
u @ index.cSPuM9g9.js:1
l @ index.cSPuM9g9.js:1
u @ server-config.store.UxMdsTT1.js:1
await in u (async)
(anonymous) @ 0.LfHbdwc2.js:14
K @ scheduler.a1YLkTt0.js:1
(anonymous) @ index.agc2DCvO.js:4
ft @ scheduler.a1YLkTt0.js:1
jt @ index.agc2DCvO.js:4
ht @ app.T591kbWd.js:1
Zt @ entry.DJzkMQyl.js:1
K @ entry.DJzkMQyl.js:1
await in K (async)
Xt @ entry.DJzkMQyl.js:1
Ye @ entry.DJzkMQyl.js:1
en @ entry.DJzkMQyl.js:1
(anonymous) @ login?code=FBEBC4E9C59A6E26A1BBEB18E55182B1D10B44E63A8033EDD3F9D7523A5CF595&scope=openid%20profile%20email&state=UtT87ezwXk2majflcSQjsBTxNRoTFSgx4DJ76JYUwZg&session_state=qqcKK_AQEKYnSa93xRZwG08m_uKf5h6ZKBOI3oTzdVI.EDC5EE01CC9BA3F5515A563F7EE999C3:79
Promise.then (async)
(anonymous) @ login?code=FBEBC4E9C59A6E26A1BBEB18E55182B1D10B44E63A8033EDD3F9D7523A5CF595&scope=openid%20profile%20email&state=UtT87ezwXk2majflcSQjsBTxNRoTFSgx4DJ76JYUwZg&session_state=qqcKK_AQEKYnSa93xRZwG08m_uKf5h6ZKBOI3oTzdVI.EDC5EE01CC9BA3F5515A563F7EE999C3:78
40.APKiO6AH.js:1 Error [login-form] [oauth.callback] Error: Error: 500
    at Object.ce [as ok] (fetch-client.IOYw_s6m.js:1:2829)
    at async 40.APKiO6AH.js:1:8631

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

-

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. configure oauth service (add new client, add users)
2. configure immich (enable oauth, set fields by step 1: client id, client secret, etc)
3. press oauth bгtton on immich login form (redirect to oauth login form)
4. input login:password on oauth service, press ok button
5. redirect with authentication code to immich endpoint /auth/login
```
