### ISSUE TITLE
h.264 transcoded livePhotoVideo not playing in the iPhone Immich app

### ISSUE THREAD

**Issue by ndewijer** [immich-app/immich#7617]
### The bug

This weekend, I transcoded all video's via the admin console.
Settings:
crf: 23
preset: medium
codec: h264
Target Res: 1080p
bitrate: 0
threads: 0

since then, videos connected to livePhotos no longer play. 
Normal, stand alone video's play just fine.

The livePhotoMovies work just fine via browser as well.

### The OS that Immich Server is running on

unRaid 6.12.6

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

1.97.0 build.141

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: always
    networks:
      - dockerlan
    command: [ "start.sh", "immich" ]
    ports:
      - 2283:3001
    env_file:
      - .env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    depends_on:
      - redis
      - database

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    deploy:  
      resources:
        limits:
          cpus: '3.00'
          memory: 5G
    networks:
      - dockerlan
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    networks:
      - dockerlan
    volumes:
      - ${DOCKERPATH}/immich/model:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    networks:
      - dockerlan
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: always
    networks:
      - dockerlan
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DOCKERPATH}/immich/postgresql:/var/lib/postgresql/data
    labels:
      - "postgresql-backup"   

networks:
  dockerlan:
    external: true
```

### Your .env content

```Shell
DOCKERPATH=/mnt/user/appdata
CACHEPATH=/mnt/cache/appdata
TZ=Europe/Amsterdam
UPLOAD_LOCATION=/mnt/user/immich
IMMICH_VERSION=release
DB_PASSWORD=xxx
DB_HOSTNAME=immich_postgres
DB_USERNAME=xxx
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Sync livephoto via app to Immich
2. Have Immich transcode the file
3. Try to play back the video via the image "play" button inside the app.
```
