### ISSUE TITLE
[BUG] Cannot access Immich behind HTTPS reverse proxy from Android app on Caddy with self-signed CA

### ISSUE THREAD

**Issue by FileGo** [immich-app/immich#765]
**Describe the bug**
I run my own CA, and have root certificate installed in trusted store of all of my devices. Reverse proxy (Caddy) obtains certificate from the CA for every subdomain, and this works great for all services on all of my devices.

I can access Immich via HTTPS from my phone's browser without any security warnings, but when I try to access it via app, I get the "Error logging you in, check server url, email and password" error message.

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Have an HTTPS reverse proxy with trusted root certificate installed on the Android device, which points to Immich instance.
2. Enter email and password.
3. Set Server Endpoint URL as "https://immich.domain.tld/api".
4. Click Login.

**Expected behavior**
The app should be able to login normally to Immich server, just as it does when accessing the instance directly (without reverse proxy).

**Screenshots**

**System**
- Android 12
- Server Version: `v1.30.0`
- Mobile App Version: `1.30.0 build.46`

**Additional context**

docker-compose.yaml:
```
version: "3.7"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always
```

.env:
```
DB_HOSTNAME=db.domain.tld
DB_USERNAME=immich
DB_PASSWORD=pass...
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=redis.domain.tld

UPLOAD_LOCATION=/data/immich

LOG_LEVEL=simple

JWT_SECRET=hU3...

PUBLIC_LOGIN_PAGE_MESSAGE=

ENABLE_MAPBOX=false
```

**Comment by alextran1502** [comment]
I also use Caddy as a reverse proxy but with its own auto managed certificated and I am able to access the site just fine. 

Besides checking your email/password and the server URL, I don't have any suggestion at the moment since this is very specific to your setup 🤔.

**Comment by bertmelis** [comment]
Did you add the CA certificate to your trusted certificates or just marked the site safe in your browser?

**Comment by FileGo** [comment]
That's because Caddy by default obtains a certificate from Let's Encrypt, whose root CA is trusted by pretty much every modern device connected to the internet.

I think this might be connected to this issue: https://github.com/flutter/flutter/issues/41781

**Comment by JaxTheWolf** [comment]
I'm experiencing the exact same issue; I let Caddy handle my internal network SSL certs with my own root cert.
Perhaps could a switch be added to the login screen, explicitly telling the HTTP/S library in use in the mobile apps to ignore any certificate validation issues? Just shooting ideas here, as I have no idea how it's actually implemented.

**Comment by sirdeniel** [comment]
> I also use Caddy as a reverse proxy but with its own auto managed certificated and I am able to access the site just fine.
> 
> Besides checking your email/password and the server URL, I don't have any suggestion at the moment since this is very specific to your setup 🤔.

Hi, would you mind to share your compose.yaml and .env to reproduce? I'm having trouble setting mine with the default Caddy. I think I got the proxy part working but the web server response is:
```
Error code 500
Internal Error
Verbose

{"message":"Internal Error"}
```
Many thanks for considering my request.
Deniel

**Comment by alextran1502** [comment]
> > I also use Caddy as a reverse proxy but with its own auto managed certificated and I am able to access the site just fine.
> > Besides checking your email/password and the server URL, I don't have any suggestion at the moment since this is very specific to your setup 🤔.
> 
> Hi, would you mind sharing your compose.yaml and .env to reproduce? I'm having trouble setting mine with the default Caddy. I think I got the proxy part working but the web server response is:
> 
> ```
> Error code 500
> Internal Error
> Verbose
> 
> {"message":"Internal Error"}
> ```
> 
> Many thanks for considering my request. Deniel

@sirdeniel Can you share your Caddy setting. I used Caddy myself, here is the config

```bash
immich.mydomain.com {

  handle {
    reverse_proxy immich-internal-ip:2283
  }

}
```

**Comment by sirdeniel** [comment]
> @sirdeniel Can you share your Caddy setting...

@alextran1502 My Caddyfile has this:
```
immich.mydomain.com {
    reverse_proxy immich-web:3000
}
```
I'm on Caddy v2, prior to 2.6
My compose.yml, with commented default proxy part:
<details>
  <summary>immich-compose.yml</summary>
      ```
    version: "3.8"
    networks:
      default:
        name: internal
        
    services:
      immich-server:
        image: altran1502/immich-server:release
        container_name: immich-server
        entrypoint: ["/bin/sh", "./start-server.sh"]
        volumes:
          - ${UPLOAD_LOCATION}:/usr/src/app/upload
        env_file:
          - stack.env
        environment:
          - NODE_ENV=production
        depends_on:
          - redis
          - database
        restart: always
    
      immich-microservices:
        image: altran1502/immich-server:release
        container_name: immich-microservices
        entrypoint: ["/bin/sh", "./start-microservices.sh"]
        volumes:
          - ${UPLOAD_LOCATION}:/usr/src/app/upload
        env_file:
          - stack.env
        environment:
          - NODE_ENV=production
        depends_on:
          - redis
          - database
        restart: always
    
      immich-machine-learning:
        image: altran1502/immich-machine-learning:release
        container_name: immich-machine-learning
        entrypoint: ["/bin/sh", "./entrypoint.sh"]
        volumes:
          - ${UPLOAD_LOCATION}:/usr/src/app/upload
        env_file:
          - stack.env
        environment:
          - NODE_ENV=production
        depends_on:
          - database
        restart: always
    
      immich-web:
        image: altran1502/immich-web:release
        container_name: immich-web
        entrypoint: ["/bin/sh", "./entrypoint.sh"]
        env_file:
          - stack.env
        environment:
          # Rename these values for svelte public interface
          - PUBLIC_IMMICH_SERVER_URL=${IMMICH_SERVER_URL}
        restart: always
    
      redis:
        container_name: immich_redis
        image: redis:6.2
        restart: always
    
      database:
        container_name: immich_postgres
        image: postgres:14
        env_file:
          - stack.env
        environment:
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_USER: ${DB_USERNAME}
          POSTGRES_DB: ${DB_DATABASE_NAME}
          PG_DATA: /var/lib/postgresql/data
        volumes:
          - pgdata:/var/lib/postgresql/data
        restart: always
    
    #  immich-proxy:
    #    container_name: immich_proxy
    #    image: altran1502/immich-proxy:release
    #    environment:
    #      # Make sure these values get passed through from the env file
    #      - IMMICH_SERVER_URL
    #      - IMMICH_WEB_URL
    #    ports:
    #      - 2283:8080
    #    logging:
    #      driver: none
    #    depends_on:
    #      - immich-server
    #    restart: always
    
    volumes:
      pgdata:
    
    ```
</details>

I manually set the `container_name` to match with Caddy `immich-web`.

My .env file:

```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/home/ubuntu/zcontainers/immich
LOG_LEVEL=simple
JWT_SECRET=185...
PUBLIC_LOGIN_PAGE_MESSAGE="Hosted by Deniel!"
```
