### ISSUE TITLE
[Bug] Search panel glitches when being used

### ISSUE THREAD

**Issue by othyn** [immich-app/immich#7707]
### The bug

Whenever I use the search panel, on a wide desktop display (so it has plenty of space on the left/right of the panel), when clicking a dropdown the page glitches out.

I can get it not to do it by hitting search once and then searching on the loaded search page instead.

https://github.com/immich-app/immich/assets/7256684/590fbdd4-b61b-47ae-abbe-0e899b874617

### The OS that Immich Server is running on

Unraid 6.12.6

### Version of Immich Server

v1.97.0

### Version of Immich Mobile App

v1.97.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
version: "3.8"

networks:
  oxnet:
    external: true

volumes:
  model-cache:

services:
  photos:
    container_name: photos
    image: ghcr.io/immich-app/immich-server:v1.97.0
    command: ["start.sh", "immich"]
    restart: unless-stopped
    depends_on:
      - photos-redis
      - photos-postgresdb
    volumes:
      - /mnt/user/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      oxnet:
        ipv4_address: 172.18.111.1
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env
    labels:
      traefik.enable: true
      traefik.docker.network: oxnet
      traefik.http.routers.photos.service: photos
      traefik.http.routers.photos.entrypoints: https
      traefik.http.services.photos.loadbalancer.server.port: 3001

  photos-microservices:
    container_name: photos-microservices
    image: ghcr.io/immich-app/immich-server:v1.97.0
    command: ["start.sh", "microservices"]
    restart: unless-stopped
    depends_on:
      - photos-redis
      - photos-postgresdb
    volumes:
      - /mnt/user/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      oxnet:
        ipv4_address: 172.18.111.2
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env

  photos-machine-learning:
    container_name: photos-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.97.0
    restart: unless-stopped
    volumes:
      - model-cache:/cache
    networks:
      oxnet:
        ipv4_address: 172.18.111.3
    dns:
      - 172.18.3.141
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env

  photos-redis:
    container_name: photos-redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped
    networks:
      oxnet:
        ipv4_address: 172.18.111.4
    dns:
      - 172.18.3.141

  photos-postgresdb:
    container_name: photos-postgresdb
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/photos-postgresdb:/var/lib/postgresql/data:rw
    networks:
      oxnet:
        ipv4_address: 172.18.111.5
    dns:
      - 172.18.3.141
    ports:
      - "5433:5432"
    env_file:
      - /mnt/user/appdata/_env/all.env
      - /mnt/user/appdata/_env/photos.env
```

### Your .env content

```Shell
<database secrets>
```

### Reproduction steps

```bash
1. Refresh/open Immich from a fresh start, especially after just uploading new content.
2. Open the search pane and attempt to use one of the dropdown boxes.
3. Issue occurs, see video in 'The bug' section.
```

### Additional information

Arc Version 1.32.0 (46908)
Chromium Engine Version 122.0.6261.94
