### ISSUE TITLE
Images in "add image to album" loads very slow

### ISSUE THREAD

**Issue by arellak** [immich-app/immich#7756]
### The bug

I created a new album and wanted to add images. The first 50 images or so are fine but when I scroll down a bit, it gets very very slow. It's just black and takes a few seconds before it loads the new images. Sometimes the page is completely unresponsive.

![image](https://github.com/immich-app/immich/assets/27505801/0299388d-ef87-48a2-8625-c1e5c18d759d)

### The OS that Immich Server is running on

Debian 12 (bookworm) x86_64

### Version of Immich Server

v1.98.0

### Version of Immich Mobile App

v1.98.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 127.0.0.1:2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=REDACTED
DB_USERNAME=REDACTED
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=REDACTED
```

### Reproduction steps

```bash
1. Create a new album.
2. Try to add images to the album.
3. Scroll down a bit.
```

### Additional information

My server usese 64gb of RAM, 8core, SSDs...
My desktop pc uses 32gb of RAM and a 6 core. So I don't think it's an hardware issue.
In the android app everything works perfectly fine.
I currently have about 11.5k images and 2k videos in Immich.
