### ISSUE TITLE
Exif data is lost in iOS when shared to option is used

### ISSUE THREAD

**Issue by srinidhi** [immich-app/immich#7810]
### The bug

Hi,
I am using Immich with all my photos in Nextcloud . Since I use external library for photos I am unable to edit photos.

I use Immich to back up photos and then move shortlisted photos to Nextcloud.
I am able to do that with share to option in Immich iOS app.
When I do that , I noticed exif data is getting stripped out. Is there a way in Immich app to save / share photos with exif data ?

### The OS that Immich Server is running on

Docker on Ubuntu 22.04

### Version of Immich Server

v1.98.1

### Version of Immich Mobile App

v1.98.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
command: [ "start.sh", "immich" ]
    volumes:
- ${UPLOAD_LOCATION}:/usr/src/app/upload
- ${NEXTCLOUD_PHOTOS}:/usr/src/app/external/public:ro
- /etc/localtime:/etc/localtime:ro
    env_file:
- .env
    ports:
      - 3001:3001
    depends_on:
      - redis
      - database
    restart: always
immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
command: [ "start.sh", "microservices" ]
    volumes:
- ${UPLOAD_LOCATION}:/usr/src/app/upload
- ${NEXTCLOUD_PHOTOS}:/usr/src/app/external/public:ro
- /etc/localtime:/etc/localtime:ro
    env_file:
- .env
depends_on:
- redis
- database
restart: always

immich-machine-learning:
  container_name: immich_machine_learning
 # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
 # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
 # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
 #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
volumes:
- model-cache:/cache
env_file:
- .env
    restart: always

redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
restart: always

database:
container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
 #image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
- .env
environment:
POSTGRES_PASSWORD: ${DB_PASSWORD}
POSTGRES_USER: ${DB_USERNAME}
POSTGRES_DB: ${DB_DATABASE_NAME}
volumes:
- pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/immich/upload
CONFIG=/mnt/immich/config
NEXTCLOUD_PHOTOS=/mnt/ncdata/Photos
POSTGRES_DATA_LOCATION=/mnt/immich/postgres_data

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=secret

#IMMICH_MACHINE_LEARNING_URL=false
#TYPESENSE_ENABLED=false

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Save a photo to iOS Photos which doesn’t have EXIF data
2. In Photos app, adjust date and location 
3. Open Immich mobile app for back up to begin. Photos are now uploaded
4. Use share to option and save photos to Nextcloud folder which is same as path to the external library.
5. Rescan external library for modified or new files in admin settings
6. Photos appear in Immich app without updated exif data.

Expected result : If adjusted date is March 1 2024 and uploaded to Nextcloud date is March 9. Photos should be shown on Mar 1 in timeline.

Actual Result : photos appear on Mar 9 in timeline 

...
```
