### ISSUE TITLE
no errors in UI, when deleting read only file

### ISSUE THREAD

**Issue by SlavikCA** [immich-app/immich#7832]
### The bug

I run Immich on Synology via Docker.
I mounted external folder with my photos in read only mode.

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    mem_limit: 1G
    command: [ "start.sh", "immich" ]
    volumes:
      - ./library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /volume1/pix/Photos_Personal:/volume1/pix/Photos_Personal:ro
    env_file:
...
```

I was looking at photos in the Web UI and wanted to delete one. I forgot, that I mounted them in read-only mode.
I clicked DELETE.
**Web U**I: `Moved to trash.` The photo got removed from the timeline.
**Server log**: no errors
**HTTP request**:
```
https://HOST/api/asset
Request Method: DELETE
Status Code: 204 No Content
```

Then I refreshed Web UI (F5), and I see that photo hasn't been deleted.

### The OS that Immich Server is running on

Docker on Synology

### Version of Immich Server

v1.98.1

### Platform with the issue

- [X] Server
- [X] Web

### Additional information

That may be edge case, 
But I would expect error message in UI.
