### ISSUE TITLE
Huge amount of photos discovered (1M instead of 30k)

### ISSUE THREAD

**Issue by Chuckame** [immich-app/immich#7864]
### The bug

When upgrading from 1.91.4 to 1.98.0, following the 2 breaking changes procedures (1.93 & 1.95), I came from 25k assets to 650k+ assets, and keeps increasing when the thumbnail job is processing.
<img width="874" alt="image" src="https://github.com/immich-app/immich/assets/16419143/980438d6-dbc8-49e3-91bc-aa53601fdd24">

I just updated to 1.98.2, still the same. When the job is resumed, the waiting assets keeps increasing.

I suspect the discovering process taking into account the thumbs.

I also set the external library for each user to a dot `.` (was in the immich doc, but feels not really clear), so to be sure I explicited the path for 2 users (me and my wife) and now I have 1M assets:
<img width="876" alt="image" src="https://github.com/immich-app/immich/assets/16419143/d8db8175-578b-4375-8efc-2a65a6091282">

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/Photos/<EXT>:/usr/src/app/external/<EXT>:ro
      - /mnt/user/Photos/<EXT>:/usr/src/app/external/<EXT>:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - internal
      - caddy
    labels:
      caddy: media.home.chuckame.fr
      caddy.reverse_proxy: '{{upstreams http 3001}}'

  microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/Photos/<EXT>:/usr/src/app/external/<EXT>:ro
      - /mnt/user/Photos/<EXT>:/usr/src/app/external/<EXT>:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    networks:
      - internal

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release} #-openvino
    extends:
      file: hwaccel.ml.yml
      service: cpu #openvino
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - internal

  machine-learning-lb:
    image: caddy
    volumes:
      - ./machine-learning-lb.Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    ports:
      - 3003:3003
    networks:
      - internal

  redis:
    image: redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped
    networks:
      - internal

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

volumes:
  pgdata:
  model-cache:

networks:
  caddy:
    external: true
  internal:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
PUID=33
PGID=33

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/user/Photos/immich

IMMICH_VERSION=v1.98.0

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=redis

#LOG_LEVEL=debug
```

### Reproduction steps

```bash
not sure:

1. start server with 1.91.4
2. migrate to 1.98.0
```
