### ISSUE TITLE
Upgrade to latest version this morning leaves immich_server container in restart loop

### ISSUE THREAD

**Issue by subtlesanitynet** [immich-app/immich#7900]
### The bug

Followed the recommended steps from the wiki for upgrading. Pulled the latest container images and redeployed. The Immich_server container now constantly restarts with the error message below.

I did follow the instructions in the error log and successfully executed `ALTER EXTENSION UPDATE vectors` in the database container but it didn't fix things. 

Docker log for immich_server container

`[Nest] 7  - 03/12/2024, 4:35:33 PM     LOG [CommunicationRepository] Initialized websocket server
/usr/src/app/dist/domain/database/database.service.js:140
            throw new Error(`
                  ^
Error: 
        The pgvecto.rs extension version is 0.1.11, but Immich only supports 0.2.0 and later minor releases.
        If the Postgres instance already has a compatible version installed, Immich may not have the necessary permissions to activate it.
        In this case, please run 'ALTER EXTENSION UPDATE vectors' manually as a superuser.
        See https://immich.app/docs/guides/database-queries for how to query the database.
        Otherwise, please update the version of pgvecto.rs in the Postgres instance to a compatible version.
    at DatabaseService.assertVectorExtension (/usr/src/app/dist/domain/database/database.service.js:140:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/domain/database/database.service.js:39:13
    at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23
Node.js v20.11.1`

### The OS that Immich Server is running on

Docker

### Version of Immich Server

latest release

### Version of Immich Mobile App

latest iOS release

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - /home/ghost/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - /home/ghost/immich/upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.1.11@sha256:0335a1a22f8c5dd1b697f14f079934f5152eaaa216c09b61e293be285491f8ee
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: Bunkhouse-Trout-Shrine-Distract-Royal-Machine-Rounding-Hardy-Vocalist0-Supernova
      POSTGRES_USER: immich
      POSTGRES_DB: immich
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=`REDACTED`/immich/upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=`REDACTED`

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=`REDACTED`
DB_USERNAME=`REDACTED`
DB_DATABASE_NAME=`REDACTED`

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.`docker compose pull`
2.`docker compose down`
3.`docker compose up -d`
...
```
