### ISSUE TITLE
node inside microservices sometimes throws segfault 

### ISSUE THREAD

**Issue by marcin-github** [immich-app/immich#7971]
### The bug

I noticed that from time to time I got coredumps from node working on microservices. As for now I don't know how to trigger it. In docker logs from this container I'm seeing only this (time of coredump):
```
immich_microservices       | [Nest] 7  - 03/15/2024, 8:35:53 AM     LOG [MediaService] Successfully generated JPEG image thumbnail for asset aa1f9555-dc75-4a56-8231-c454d222e934
immich_microservices       | [Nest] 7  - 03/15/2024, 8:35:53 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset af620089-5a9d-42ff-9997-850054bd292e
immich_microservices       | [Nest] 7  - 03/15/2024, 8:36:11 AM     LOG [CommunicationRepository] Initialized websocket server
immich_microservices       | [Nest] 7  - 03/15/2024, 8:36:11 AM     LOG [SystemConfigService] LogLevel=log (set via system config)
immich_microservices       | [Nest] 7  - 03/15/2024, 8:36:11 AM     LOG [LibraryService] Starting to watch library c95a9339-590b-47b2-83a4-1f9de674744c with import path(s) /mnt/media/reszta
immich_microservices       | [Nest] 7  - 03/15/2024, 8:36:12 AM     LOG [LibraryService] Starting to watch library c7a97acb-5f03-45fb-aaf6-2b5bcc586bab with import path(s) /mnt/media/xxx
immich_microservices       | [Nest] 7  - 03/15/2024, 8:36:21 AM     LOG [LibraryService] Starting to watch library 1cc889e2-9374-4242-b698-cb57449a54de with import path(s) /mnt/media/yyy
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [MetadataRepository] Initializing metadata repository
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [MetadataService] Initialized local reverse geocoder
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [NestFactory] Starting Nest application...
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] ConfigModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] BullModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] InfraModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] DomainModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [InstanceLoader] MicroservicesModule dependencies initialized
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [NestApplication] Nest application successfully started
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [ImmichMicroservice] Immich Microservices is listening on http://[::1]:3002 [v1.98.2] [PRODUCTION]
immich_microservices       | [Nest] 7  - 03/15/2024, 8:37:12 AM     LOG [MediaService] Successfully generated WEBP image thumbnail for asset 5711548b-5b37-4a7a-8991-f69b21eda04e
```

This is backtrace from gdb

```c++
# echo bt | gdb -q /usr/local/bin/node core-1710488153-0-11-\!usr\!local\!bin\!node-7
Reading symbols from /usr/local/bin/node...

warning: Can't open file /root/orcexec.JANkwe (deleted) during file-backed mapping note processing
[New LWP 18]
[New LWP 9]
[New LWP 10]
[New LWP 7]
[New LWP 14]
[New LWP 11]
[New LWP 16]
[New LWP 13]
[New LWP 3743]
[New LWP 3718]
[New LWP 12]
[New LWP 3747]
[New LWP 3744]
[New LWP 3737]
[New LWP 3746]
[New LWP 3749]
[New LWP 15]
[New LWP 3750]
[New LWP 17]
[New LWP 3748]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `immich_microservices                     '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1c0fa30b9d in mi_malloc () from /usr/lib/x86_64-linux-gnu/libmimalloc.so.2
[Current thread is 1 (Thread 0x7f1be4ad36c0 (LWP 18))]
(gdb) #0  0x00007f1c0fa30b9d in mi_malloc () at /usr/lib/x86_64-linux-gnu/libmimalloc.so.2
#1  0x00007f1bec5f5679 in g_malloc () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1bec8d995e in vips.argument_get_instance () at /usr/local/lib/libvips.so.42
#3  0x00007f1bec8da673 in vips_object_set_property () at /usr/local/lib/libvips.so.42
#4  0x00007f1bec55753d in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f1bec55a5ac in g_object_set_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f1bec55b11c in g_object_set () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f1bec8df74a in vips_image_new () at /usr/local/lib/libvips.so.42
#8  0x00007f1bec850ef9 in vips_conversion_build () at /usr/local/lib/libvips.so.42
#9  0x00007f1bec862926 in vips_copy_build () at /usr/local/lib/libvips.so.42
#10 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#11 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#12 0x00007f1bec8ec349 in vips_call_required_optional () at /usr/local/lib/libvips.so.42
#13 0x00007f1bec8ecdef in vips_call_split () at /usr/local/lib/libvips.so.42
#14 0x00007f1bec862c79 in vips_copy () at /usr/local/lib/libvips.so.42
#15 0x00007f1bec8e081d in vips_image_decode () at /usr/local/lib/libvips.so.42
#16 0x00007f1bec804c70 in vips_reduceh_build(_VipsObject*) () at /usr/local/lib/libvips.so.42
#17 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#18 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#19 0x00007f1bec8ec349 in vips_call_required_optional () at /usr/local/lib/libvips.so.42
#20 0x00007f1bec8ecdef in vips_call_split () at /usr/local/lib/libvips.so.42
#21 0x00007f1bec805027 in vips_reduceh () at /usr/local/lib/libvips.so.42
#22 0x00007f1bec7fd171 in vips_resize_build () at /usr/local/lib/libvips.so.42
#23 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#24 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#25 0x00007f1becbef813 in vips::VImage::call_option_string(char const*, char const*, vips::VOption*) () at /usr/local/lib/libvips-cpp.so.42
#26 0x00007f1becc02f00 in vips::VImage::resize(double, vips::VOption*) const () at /usr/local/lib/libvips-cpp.so.42
#27 0x00007f1becc4e5fb in PipelineWorker::Execute() () at /usr/src/app/node_modules/@img/sharp-linux-x64/lib/sharp-linux-x64.node
#28 0x00007f1becc3bbd1 in Napi::AsyncWorker::OnExecute(Napi::Env) () at /usr/src/app/node_modules/@img/sharp-linux-x64/lib/sharp-linux-x64.node
#29 0x0000000000c67dc9 in node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*)#1}::_FUN(uv_work_s*) ()
#30 0x0000000001886e10 in worker (arg=0x0) at ../deps/uv/src/threadpool.c:122
#31 0x00007f1c0f59c134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#32 0x00007f1c0f61ba40 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

and bt full

```c++
# echo "bt full" | gdb -q /usr/local/bin/node core-1710488153-0-11-\!usr\!local\!bin\!node-7 ode-7
Reading symbols from /usr/local/bin/node...

warning: Can't open file /root/orcexec.JANkwe (deleted) during file-backed mapping note processing
[New LWP 18]
[New LWP 9]
[New LWP 10]
[New LWP 7]
[New LWP 14]
[New LWP 11]
[New LWP 16]
[New LWP 13]
[New LWP 3743]
[New LWP 3718]
[New LWP 12]
[New LWP 3747]
[New LWP 3744]
[New LWP 3737]
[New LWP 3746]
[New LWP 3749]
[New LWP 15]
[New LWP 3750]
[New LWP 17]
[New LWP 3748]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `immich_microservices                     '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1c0fa30b9d in mi_malloc () from /usr/lib/x86_64-linux-gnu/libmimalloc.so.2
[Current thread is 1 (Thread 0x7f1be4ad36c0 (LWP 18))]
(gdb) #0  0x00007f1c0fa30b9d in mi_malloc () at /usr/lib/x86_64-linux-gnu/libmimalloc.so.2
#1  0x00007f1bec5f5679 in g_malloc () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1bec8d995e in vips.argument_get_instance () at /usr/local/lib/libvips.so.42
#3  0x00007f1bec8da673 in vips_object_set_property () at /usr/local/lib/libvips.so.42
#4  0x00007f1bec55753d in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f1bec55a5ac in g_object_set_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f1bec55b11c in g_object_set () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f1bec8df74a in vips_image_new () at /usr/local/lib/libvips.so.42
#8  0x00007f1bec850ef9 in vips_conversion_build () at /usr/local/lib/libvips.so.42
#9  0x00007f1bec862926 in vips_copy_build () at /usr/local/lib/libvips.so.42
#10 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#11 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#12 0x00007f1bec8ec349 in vips_call_required_optional () at /usr/local/lib/libvips.so.42
#13 0x00007f1bec8ecdef in vips_call_split () at /usr/local/lib/libvips.so.42
#14 0x00007f1bec862c79 in vips_copy () at /usr/local/lib/libvips.so.42
#15 0x00007f1bec8e081d in vips_image_decode () at /usr/local/lib/libvips.so.42
#16 0x00007f1bec804c70 in vips_reduceh_build(_VipsObject*) () at /usr/local/lib/libvips.so.42
#17 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#18 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#19 0x00007f1bec8ec349 in vips_call_required_optional () at /usr/local/lib/libvips.so.42
#20 0x00007f1bec8ecdef in vips_call_split () at /usr/local/lib/libvips.so.42
#21 0x00007f1bec805027 in vips_reduceh () at /usr/local/lib/libvips.so.42
#22 0x00007f1bec7fd171 in vips_resize_build () at /usr/local/lib/libvips.so.42
#23 0x00007f1bec8d9b89 in vips_object_build () at /usr/local/lib/libvips.so.42
#24 0x00007f1bec8e5442 in vips_cache_operation_buildp () at /usr/local/lib/libvips.so.42
#25 0x00007f1becbef813 in vips::VImage::call_option_string(char const*, char const*, vips::VOption*) () at /usr/local/lib/libvips-cpp.so.42
#26 0x00007f1becc02f00 in vips::VImage::resize(double, vips::VOption*) const () at /usr/local/lib/libvips-cpp.so.42
#27 0x00007f1becc4e5fb in PipelineWorker::Execute() () at /usr/src/app/node_modules/@img/sharp-linux-x64/lib/sharp-linux-x64.node
#28 0x00007f1becc3bbd1 in Napi::AsyncWorker::OnExecute(Napi::Env) () at /usr/src/app/node_modules/@img/sharp-linux-x64/lib/sharp-linux-x64.node
#29 0x0000000000c67dc9 in node::ThreadPoolWork::ScheduleWork()::{lambda(uv_work_s*)#1}::_FUN(uv_work_s*) ()
#30 0x0000000001886e10 in worker (arg=0x0) at ../deps/uv/src/threadpool.c:122
        w = 0x352021a2f90
        q = 0x352021a2fa8
        is_slow_work = 0
#31 0x00007f1c0f59c134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139757777401536, -8324149622998704423, -368, 2, 140726968429760, 139757769011200, 8236352952251834073, 8233337364946607833},
mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#32 0x00007f1c0f61ba40 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```

### The OS that Immich Server is running on

docker container

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

---

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
---

version: '3.8'

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/logi/yyy:/mnt/media/yyy:ro
      - /home/logi/xxx:/mnt/media/xxx:ro
      - /home/bb/Pictures:/mnt/media/reszta:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/logi/yyy:/mnt/media/yyy:ro
      - /home/logi/xxx:/mnt/media/xxx:ro
      - /home/bb/Pictures:/mnt/media/reszta:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - /home/logi/immich/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    volumes:
      - /home/logi/immich/redis:/data
    command: --save 601 1 --set-proc-title yes --rdbcompression yes --activedefrag yes --rdbcompression yes --list-compress-depth 2
    environment:
      TZ: "Europe/Warsaw"
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      TZ: "Europe/Warsaw"
    volumes:
      - /home/logi/immich/pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/logi/immich/immich
IMMICH_VERSION=release

DB_PASSWORD=zzzz

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

TZ=Europe/Warsaw
```

### Reproduction steps

```bash
1. I don't now yet how to trigger coredump
```
