### ISSUE TITLE
External library thumbnails are indexed into new photos

### ISSUE THREAD

**Issue by PDSCi996** [immich-app/immich#7980]
### The bug

I found that after the external library in the latest 1.98.2 version is imported into the system, the thumbnails will appear in the timeline photos at the same time as the original photos.

### The OS that Immich Server is running on

Synology 6.2.3 Docker

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
imagegenius AIO image (alpine)

---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - DB_HOSTNAME=192.168.1.234
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.1.234
      - DB_PORT=25432
      - REDIS_PORT=26379
      - REDIS_PASSWORD= 
      - MACHINE_LEARNING_GPU_ACCELERATION= 
      - MACHINE_LEARNING_WORKERS=1 
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 
    volumes:
      - /volume1/docker/immich/config:/config
      - /volume1/docker/immich/photo:/photos
      - /volume1/photo:/import:ro 
    ports:
      - 53030:8080
    restart: unless-stopped
# This container requires an external application to be run separately to be run separately.
# By default, ports for the databases are opened, be careful when deploying it
# Redis:
  redis:
    image: redis
    ports:
      - 26379:6379
    container_name: redis
# PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 25432:5432
    container_name: postgres14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: immich
    volumes:
      - /volume1/docker/immich/data:/var/lib/postgresql/data
```

### Your .env content

```Shell
not relevant
```

### Reproduction steps

```bash
1. Use Synology docker-compose to deploy immich and log in to immich.
2. Click "administration"-"External Libraries"-"Create Library"-"create"-"..."-"Edit Import Paths"-"Add Path", then enter the external library path in the Path column, and then click "Add"-"Save"-"Scan All Libraries", and then you can see the results I mentioned after the scan is completed.
```
