### ISSUE TITLE
Upgrading from 1.90.2 to 1.98.2 gives error

### ISSUE THREAD

**Issue by Lars-** [immich-app/immich#7998]
### The bug

I tried updating from 1.90.2 to 1.98.2. I changed the docker-compose.yml file and did the `docker compose pull`, `docker compose down` and `docker compose up`.
But now I get this error over and over again and I can't get Immich to boot:
```
immich_postgres          | 2024-03-16 07:41:48.492 UTC [149] ERROR:  pgvecto.rs: The extension is upgraded so all index files are outdated.
immich_postgres          |      ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich_postgres          | 2024-03-16 07:41:48.492 UTC [149] STATEMENT:  
immich_postgres          |            CREATE INDEX IF NOT EXISTS clip_index ON smart_search
immich_postgres          |            USING hnsw (embedding vector_cosine_ops)
immich_postgres          |            WITH (ef_construction = 300, m = 16)
immich_microservices     | Migration "AddCLIPEmbeddingIndex1700713994428" failed, error: pgvecto.rs: The extension is upgraded so all index files are outdated.
immich_microservices     | ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich_microservices     | /usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219
immich_microservices     |             throw new QueryFailedError_1.QueryFailedError(query, parameters, err);
immich_microservices     |                   ^
immich_microservices     | 
immich_microservices     | QueryFailedError: pgvecto.rs: The extension is upgraded so all index files are outdated.
immich_microservices     | ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich_microservices     |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
immich_microservices     |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |     at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
immich_microservices     |     at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_microservices     |     at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_microservices     |     at async DatabaseRepository.runMigrations (/usr/src/app/dist/infra/repositories/database.repository.js:177:9)
immich_microservices     |     at async /usr/src/app/dist/domain/database/database.service.js:52:13
immich_microservices     |     at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
immich_microservices     |   query: '\n' +
immich_microservices     |     '      CREATE INDEX IF NOT EXISTS clip_index ON smart_search\n' +
immich_microservices     |     '      USING hnsw (embedding vector_cosine_ops)\n' +
immich_microservices     |     '      WITH (ef_construction = 300, m = 16)',
immich_microservices     |   parameters: undefined,
immich_microservices     |   driverError: error: pgvecto.rs: The extension is upgraded so all index files are outdated.
immich_microservices     |   ADVICE: Delete all index files. Please read `https://docs.pgvecto.rs/admin/upgrading.html`.
immich_microservices     |       at /usr/src/app/node_modules/pg/lib/client.js:526:17
immich_microservices     |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
immich_microservices     |       at async PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:184:25)
immich_microservices     |       at async AddCLIPEmbeddingIndex1700713994428.up (/usr/src/app/dist/infra/migrations/1700713994428-AddCLIPEmbeddingIndex.js:13:9)
immich_microservices     |       at async MigrationExecutor.executePendingMigrations (/usr/src/app/node_modules/typeorm/migration/MigrationExecutor.js:225:17)
immich_microservices     |       at async DataSource.runMigrations (/usr/src/app/node_modules/typeorm/data-source/DataSource.js:265:35)
immich_microservices     |       at async DatabaseRepository.runMigrations (/usr/src/app/dist/infra/repositories/database.repository.js:177:9)
immich_microservices     |       at async /usr/src/app/dist/domain/database/database.service.js:52:13
immich_microservices     |       at async /usr/src/app/dist/infra/repositories/database.repository.js:185:23 {
immich_microservices     |     length: 203,
immich_microservices     |     severity: 'ERROR',
immich_microservices     |     code: 'XX000',
immich_microservices     |     detail: undefined,
immich_microservices     |     hint: undefined,
immich_microservices     |     position: undefined,
immich_microservices     |     internalPosition: undefined,
immich_microservices     |     internalQuery: undefined,
immich_microservices     |     where: undefined,
immich_microservices     |     schema: undefined,
immich_microservices     |     table: undefined,
immich_microservices     |     column: undefined,
immich_microservices     |     dataType: undefined,
immich_microservices     |     constraint: undefined,
immich_microservices     |     file: 'error.rs',
immich_microservices     |     line: '7',
immich_microservices     |     routine: undefined
immich_microservices     |   },
immich_microservices     |   length: 203,
immich_microservices     |   severity: 'ERROR',
immich_microservices     |   code: 'XX000',
immich_microservices     |   detail: undefined,
immich_microservices     |   hint: undefined,
immich_microservices     |   position: undefined,
immich_microservices     |   internalPosition: undefined,
immich_microservices     |   internalQuery: undefined,
immich_microservices     |   where: undefined,
immich_microservices     |   schema: undefined,
immich_microservices     |   table: undefined,
immich_microservices     |   column: undefined,
immich_microservices     |   dataType: undefined,
immich_microservices     |   constraint: undefined,
immich_microservices     |   file: 'error.rs',
immich_microservices     |   line: '7',
immich_microservices     |   routine: undefined
immich_microservices     | }
immich_microservices     | 
immich_microservices     | Node.js v20.11.1
immich_microservices exited with code 1
```

What to do?

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/raid/immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=[redacted]
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. I started with a working 1.90.2
2. I changed the docker-compose.yml to the latest release
3. I did `docker compose pull`, `docker compose down` and `docker compose up`
```
