### ISSUE TITLE
Constant empty commits to postgres database

### ISSUE THREAD

**Issue by riedel** [immich-app/immich#8000]
### The bug

immich is constantly committing to the data base even if there is no activity.

See pg_waldump:
```
rmgr: Standby     len (rec/tot):     50/    50, tx:          0, lsn: 0/64035EF8, prev 0/64035EC8, desc: RUNNING_XACTS nextXid 434203 latestCompletedXid 434202 oldestRunningXid 434203
rmgr: Transaction len (rec/tot):     46/    46, tx:     434203, lsn: 0/64035F30, prev 0/64035EF8, desc: COMMIT 2024-03-16 10:49:23.211143 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434204, lsn: 0/64035F60, prev 0/64035F30, desc: COMMIT 2024-03-16 10:49:24.554579 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434205, lsn: 0/64035F90, prev 0/64035F60, desc: COMMIT 2024-03-16 10:49:28.213329 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434206, lsn: 0/64035FC0, prev 0/64035F90, desc: COMMIT 2024-03-16 10:49:29.558266 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434207, lsn: 0/64035FF0, prev 0/64035FC0, desc: COMMIT 2024-03-16 10:49:33.214325 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434208, lsn: 0/64036038, prev 0/64035FF0, desc: COMMIT 2024-03-16 10:49:34.560701 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434209, lsn: 0/64036068, prev 0/64036038, desc: COMMIT 2024-03-16 10:49:38.215395 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434210, lsn: 0/64036098, prev 0/64036068, desc: COMMIT 2024-03-16 10:49:39.564074 UTC
rmgr: Transaction len (rec/tot):     46/    46, tx:     434211, lsn: 0/640360C8, prev 0/64036098, desc: COMMIT 2024-03-16 10:49:43.216769 UTC
```

### The OS that Immich Server is running on

QNAP

### Version of Immich Server

v1.98.1

### Version of Immich Mobile App

v1.98.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '4.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${IMAGE_LIBRARY_LOCATION}:/mnt/media/image:ro
      - ${VIDEO_LIBRARY_LOCATION}:/mnt/media/video:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
    networks:
      - proxy
      - default

    depends_on:
      - redis
      - database
    restart: always
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.immich.rule=Host(`immich.dach.myhome-server.de`)"
       - "traefik.http.routers.immich.entrypoints=websecure"
       - "traefik.docker.network=proxy"
       

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${IMAGE_LIBRARY_LOCATION}:/mnt/media/image:ro
      - ${VIDEO_LIBRARY_LOCATION}:/mnt/media/video:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      REDIS_HOSTNAME: immich_redis
      DB_HOSTNAME: immich_postgres
    depends_on:
      - redis
      - database
    restart: always
    cpu_percent: 25

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine
    restart: always
    command: redis-server --save 1800 1

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.1
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", "search_path=\"$$user\", public, vectors", "-c", "logging_collector=off", "-c", "autovacuum=off", "-c", "wal_level=logical"]

volumes:
  pgdata:
  model-cache:

networks:
  proxy:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/share/CACHEDEV4_DATA/Fotos/Immich/
IMAGE_LIBRARY_LOCATION=/share/CACHEDEV4_DATA/Fotos/DCIM/
VIDEO_LIBRARY_LOCATION=/share/CACHEDEV4_DATA/Fotos/MP_ROOT/
IMMICH_VERSION=release
DB_PASSWORD=dAEns2bMsEcdZFPo
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. make sure wal_level is logical `docker compose exec database bash`
2. `pg_waldump -f /var/lib/postgresql/data/pg_wal/000000010000000000000064` (use latest wal)
3. `pg_recvlogical -U postgres -d immich --slot=test --create-slot`
4. `pg_recvlogical -U postgres -d immich --slot=test --start -f -`
```

### Additional information

What you will likely see is constant COMMITs.
However, there seems to be no logical part to those COMMITs.

I would actually like the hard drive to spin down, but constant writes makes this pretty much impossible.
