### ISSUE TITLE
Adding photos to a new album resets the timeline position

### ISSUE THREAD

**Issue by TwoD** [immich-app/immich#8010]
### The bug

Adding photos to an album resets the timeline scroll position, making it time consuming to add lots of new albums.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

1.98.2

### Version of Immich Mobile App

1.91.4

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
name: "immich"
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${HENRIK_BILDER}:/mnt/media/henrik_bilder:ro
      - ${MARIA_BILDER}:/mnt/media/maria_foton:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
      # file: hwaccel.yml
      # service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${HENRIK_BILDER}:/mnt/media/henrik_bilder:ro
      - ${MARIA_BILDER}:/mnt/media/maria_foton:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/doc/install/environment-variables
HENRIK_BILDER=#####
MARIA_BILDER=#####

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=#######


# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=#########
DB_DATABASE_NAME=immich
UPLOAD_LOCATION=./data


PUBLIC_IMMICH_SERVER_URL=https://#######

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Scroll a bit down the timeline
2. Select one or more photos.
3. Click to add them to an album.
4. Type in a name of an album which does not exist, and then click to add it.
5. The new album opens up.
6. Press the back arrow to get back to the timeline.
6. Timeline has lost its position.
```

### Additional information

This does not happen when adding photos to an existing album.
