### ISSUE TITLE
Removal of users externalPath restriction for external libraries causes immich to scan the entire server

### ISSUE THREAD

**Issue by dorianim** [immich-app/immich#8020]
> **EDIT** the issue was caused by Immich scanning the entire server for assets, because an external library pointing to root (`/`) existed and after the `externalPath` restriction was removed in v1.98.0, there was noting stopping the indexing of the whole server. See https://github.com/immich-app/immich/issues/8020#issuecomment-2010975608

### The bug

After upgrading from v1.98.0 to v1.98.2, I am seeing a very high CPU utilization from immich related tasks and the webinterface is extremely slow and largely unusable:
![image](https://github.com/immich-app/immich/assets/30153207/6cbbd06c-7835-41b0-9751-444c840fc945)

Before the upgrade, everything was working fine. I didn't change any configuration nor triggered any jobs. Just did a `docker compose pull && docker compose up -d`.

Did I miss something obvious? What can I do to resolve this? I have left the server running for several days in a row and also tried restarting it, but that didn't change anything.
What can I do to troubleshoot the issue further?

### The OS that Immich Server is running on

Ubuntu 20.04 LTS

### Version of Immich Server

v1.98.2

### Version of Immich Mobile App

v1.98.2

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.immich.rule: "Host(`photos.dorian.im`) || Host(`photos.itsblue.de`)"
      traefik.http.routers.immich.entrypoints: webs
    
  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
IMMICH_VERSION=release

###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=xxx
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################
    
REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Config
###################################################################################
UPLOAD_LOCATION=/mnt/data/immich
    
###################################################################################
# Typesense
###################################################################################
TYPESENSE_API_KEY=xxx

###################################################################################
# JWT SECRET
###################################################################################
JWT_SECRET=xxx
```

### Reproduction steps

```bash
1. start immich
```

### Additional information

I have started using immmich very early on and upgraded version by version ever since.
