### ISSUE TITLE
Does unsupported video encoding format affect the normal operation of machine learning?

### ISSUE THREAD

**Issue by Gloryandel** [immich-app/immich#8160]
### The bug

When selecting the HEVC encoding format for transcoding videos in Intel i3 8100T, an error message appears as follows. When the encoding format is changed to AVC, machine learning runs normally!

*Firstly, it appears that the i3 8100T does not support HEVC encoding, but it is unclear whether the coupling between video encoding and machine learning is normal, and there is no error reported by the video transcoding component in the logs.*

Without changing other settings, only modify the transcoding format from HEVC to AVC, and then machine learning proceeds normally.

```
# Model Log
Fetching 11 files:  82%|████████▏ | 9/11 [09:08<02:01, 60.90s/it]
immich_machine_learning  | [03/21/24 14:54:20] INFO     Loading facial recognition model 'buffalo_l' to
immich_machine_learning  |                              memory
immich_machine_learning  | [03/21/24 14:54:20] WARNING  Failed to load clip model
immich_machine_learning  |                              'ViT-B-32__openai'.Clearing cache and retrying.
immich_machine_learning  | [03/21/24 14:54:20] INFO     Cleared cache directory for model
immich_machine_learning  |                              'ViT-B-32__openai'.
immich_machine_learning  | [03/21/24 14:54:21] INFO     Downloading clip model 'ViT-B-32__openai'. This may
immich_machine_learning  |                              take a while.
immich_server            | [Nest] 7  - 03/21/2024, 2:54:21 PM     LOG [CommunicationRepository] Websocket Disconnect: mt0kPx_eJsppCpuOAAAL
immich_server            | [Nest] 7  - 03/21/2024, 2:54:22 PM     LOG [CommunicationRepository] Websocket Connect:    trwRy6Nm6_mkOxxJAAAN
Fetching 11 files:  27%|██▋       | 3/11 [00:03<00:08,  1.07s/it]
immich_server            | [Nest] 7  - 03/21/2024, 2:54:34 PM   ERROR [Error: write EPIPE
immich_server            |     at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)] Failed to serve file

# I3 8100T HEVC QSV, machine learning error logs, intel_gpu_top backend occupied, slow video transcoding, GPU 100MHz
immich_microservices     | [Nest] 7  - 03/21/2024, 3:01:41 PM   ERROR [JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with HeadersTimeoutError: Headers Timeout Error
immich_microservices     | [Nest] 7  - 03/21/2024, 3:01:41 PM   ERROR [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with HeadersTimeoutError: Headers Timeout Error
immich_microservices     |     at /usr/src/app/dist/infra/repositories/machine-learning.repository.js:19:19
immich_microservices     |     at async MachineLearningRepository.predict (/usr/src/app/dist/infra/repositories/machine-learning.repository.js:18:21)
immich_microservices     |     at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/domain/smart-info/smart-info.service.js:76:31)
immich_microservices     |     at async /usr/src/app/dist/domain/job/job.service.js:137:36
immich_microservices     |     at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
immich_microservices     |     at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
immich_microservices     | [Nest] 7  - 03/21/2024, 3:01:41 PM   ERROR [JobService] Object:
immich_microservices     | {
immich_microservices     |   "id": "143de102-e6f9-4928-a7d4-408c3a6e4dec",
immich_microservices     |   "source": "upload"
immich_microservices     | }

# Video Transcoding Settings -> VIDEO CODEC -> HEVC to AVC，Machine learning runs normally after modification，GPU 180Mhz
immich_machine_learning  | [03/21/24 15:02:54] INFO     Loading clip model 'ViT-B-32__openai' to memory
immich_machine_learning  | [03/21/24 15:02:55] INFO     Loading clip model 'ViT-B-32__openai' to memory
immich_machine_learning  | [03/21/24 15:02:56] INFO     Loading clip model 'ViT-B-32__openai' to memory
immich_machine_learning  | [03/21/24 15:02:57] INFO     Loading clip model 'ViT-B-32__openai' to memory
immich_machine_learning  | [03/21/24 15:02:58] INFO     Loading facial recognition model 'buffalo_l' to
immich_machine_learning  |                              memory
immich_machine_learning  | [03/21/24 15:02:59] INFO     Loading clip model 'ViT-B-32__openai' to memory
immich_machine_learning  | [03/21/24 15:03:00] INFO     Loading facial recognition model 'buffalo_l' to
immich_machine_learning  |                              memory
```

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.99

### Version of Immich Mobile App

v1.95

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
As mentioned above.
```

### Additional information

Test Video Meta info: 4K VP9 HDR 10 10bit OPUS
