### ISSUE TITLE
UPLOAD Error - CORS

### ISSUE THREAD

**Issue by 19krikma** [immich-app/immich#8178]
### The bug

I am running NPM (Nginx Proxy Manager), I have no issues connecting to it or managing the server though web or the app. I am having issues with the upload of .mp4 files, some upload without issues some other don't upload. I am posting it here because I hoping someone can help me. I read documentation and tried everything that other people did nut nothing worked or just break and give me this error  "Bad SSL handshake" or "Bad gateway".

I am running immich.app in docker container.
APP - Upload never happens, it starts and looks like it's working but it resets around 30% - 40% completion.
Web - Upload just sits for a minute then just fails with an error.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.99.0

### Version of Immich Mobile App

1.99.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<password>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Upload 
2.Wait 1 min
3.Recieve [object ProgressEvent]
...
```

### Additional information

This is the error I was able to capture.
![Screenshot 2024-03-17 222106](https://github.com/immich-app/immich/assets/31541643/a24db9eb-d341-4779-8f96-ca0cd38acf1b)

This is my NPM configuration. 
![Screenshot 2024-03-21 204331](https://github.com/immich-app/immich/assets/31541643/5d4b42a8-acee-4924-9fcd-03ecd180f114)
![Screenshot 2024-03-21 204454](https://github.com/immich-app/immich/assets/31541643/1f05d03b-f64d-455d-9039-a57659a54540)
![Screenshot 2024-03-21 204526](https://github.com/immich-app/immich/assets/31541643/9eb5a658-4e6d-4da4-9f30-625c73d032c5)
