### ISSUE TITLE
Edit description doesn't get saved - Returns 'Asset description has been updated' then blanks out.

### ISSUE THREAD

**Issue by snowgumrd** [immich-app/immich#8188]
### The bug

All my photos are on an external library. When I try adding information on the description in a photo or video, I can type into the field, but then I click away and it says 'Asset description has been updated' and the information I've typed blanks out.

I couldn't find anything in the docs (or issues in github) that says anything about whether assets on external libraries can have descriptions (would love this to work).

### The OS that Immich Server is running on

Debian

### Version of Immich Server

1.99.0

### Version of Immich Mobile App

1.99.0 build.129

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - data_immich:/usr/src/app/upload
      - q_Photos:/mnt/media/photos:ro
      - q_Videos:/mnt/media/videos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
#      - typesense
    restart: always
    ports:
      - 2283:3001
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1.8'

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - data_immich:/usr/src/app/upload
      - q_Photos:/mnt/media/photos:ro
      - q_Videos:/mnt/media/videos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
#      - typesense
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1.8'
    

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.8'
          memory: 4G    

#  immich-web:
#    container_name: immich_web
#    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
#    env_file:
#      - stack.env
#    restart: always

#  typesense:
#    container_name: immich_typesense
#    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
#    environment:
#      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
#      - TYPESENSE_DATA_DIR=/data
#    volumes:
#      - tsdata:/data
#    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
#    image: postgres:14-alpine@sha256:28407a9961e76f2d285dc6991e8e48893503cc3836a4755bbc2d40bcc272a441
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '1.8'

#  immich-proxy:
#    container_name: immich_proxy
#    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
#    environment:
#      # Make sure these values get passed through from the env file
#      - IMMICH_SERVER_URL
#      - IMMICH_WEB_URL
#    ports:
#      - 2283:8080
#    depends_on:
#      - immich-server
#      - immich-web
#    restart: always

volumes:
  pgdata:
  model-cache:
#  tsdata:
  q_Photos:
    external: yes
  q_Videos:
    external: yes
  data_immich:
    external: yes
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_VERSION=release
TYPESENSE_API_KEY=***ZAPPED***
DB_PASSWORD=***ZAPPED***
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Australia/Melbourne
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1.Open an asset
2.Type something in description
3.Click on another part of the screen
4.Watch sadly as your descriptive words vanish :(
...
```
