### ISSUE TITLE
docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by Batwam** [immich-app/immich#8256]
### The bug

I don't believe that this has been reported yet. I'm getting this warning lately:
> /home/user/.local/share/applications/immich-app/docker-compose.yml: `version` is obsolete

I'm using the standard template from https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml which has `version: '3.8'` defined at the top.

Based on [this discussion](https://github.com/mailcow/mailcow-dockerized/issues/5797#issuecomment-2010649543), it looks like this line is now obsolete. I'm using Docker Compose version v2.25.0 and Docker Engine 26.0.0.

### The OS that Immich Server is running on

Ubuntu 23.10

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
as per https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /home/anthony/Pictures:/mnt/media/Pictures:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
...
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
start docker container using `sudo docker compose up`
```
