### ISSUE TITLE
Unable to search for a person appearing exclusively in archived photos

### ISSUE THREAD

**Issue by SteveDinn** [immich-app/immich#8265]
### The bug

We need to have a way to display people that appear exclusively in archived photos. Not being able to see "archived" people leads to the following issues:
- When correcting facial recognition, It is possible to accidentally add multiple "People" entries for the same person since they don't show up in the "People" page to be found and selected
- If you have multiple "People" entries representing the same person, it is not possible to merge them because you can't find and select a person that only appears in archived photos.
- It's not possible to change an archived person's feature photo because no photos show up for them (0 assets).

I found this closed issue (https://github.com/immich-app/immich/issues/3443), but it doesn't really address these particular problems.

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

v1.99.0

### Version of Immich Mobile App

n/a

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.3"
services:
  server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ./photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file: env
    ports:
      - 8053:3001
    depends_on:
      - redis
      - database
    restart: "no"

  microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    volumes:
      - ./photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file: env
    depends_on:
      - redis
      - database
  machine-learning:
    container_name: immich_machine_learning
    hostname: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ./model-cache:/cache
    env_file: env
    restart: "no"

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:3fcb624d83a9c478357f16dc173c58ded325ccc5fd2a4375f3916c04cc579f70
    restart: "no"

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: "[REDACTED]"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "immich"
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: "no"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/opt/immich/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

DB_PASSWORD=[REDACTED]
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Archive all photos of a particular person
2. See that the person can no longer be found with browsing or with search
3. See that this hampers much of the features surrounding updating featured photos for that person, merging with another person, etc.
```

### Additional information

Potential workarounds are to temporarily un-archive the photos involved, but it would be nicer to be able to have the option to display people in archived photos.
