### ISSUE TITLE
Map View is broken (showing photos in wrong country)

### ISSUE THREAD

**Issue by brandonkal** [immich-app/immich#8312]
### The bug

I have no photos in this library outside of the North America.
![image](https://github.com/immich-app/immich/assets/4714862/293b1355-b477-4c81-8f35-e772a62feace)
If I click the bubble near Nigeria, it takes me to a photo correctly identified as being from the Grand Canyon

![image](https://github.com/immich-app/immich/assets/4714862/5ab3bf16-0004-414f-b06d-ddf9d9351b1d)

### The OS that Immich Server is running on

Synology

### Version of Immich Server

v1.99

### Version of Immich Mobile App

v1.99

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.9"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume2/homes/brandon/Photos:/data/external/brandon:ro
      - /volume2/photo:/data/external/photo:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3001:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    user: 1026:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /volume2/homes/brandon/Photos:/data/external/brandon:ro
      - /volume2/photo:/data/external/photo:ro
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/immich/micro:/usr/src/app/.reverse-geocoding-dump
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}

    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5

    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    security_opt:
      - no-new-privileges:true
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - 54320:5432
    volumes:
      - /volume1/docker/immich/db:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/docker/immich/upload
IMMICH_VERSION=v1.99.0
DB_PASSWORD=REDACTED
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
PUID=REDACTED
PGID=REDACTED
```

### Reproduction steps

```bash
1. Look at the map in the browser
2. Observe places are incorrect
```
