### ISSUE TITLE
handleGeneratePersonThumbnail incorrectly crops if thumbnail is regenerated with a different size

### ISSUE THREAD

**Issue by raymondnumbergenerator** [immich-app/immich#8317]
### The bug

I reduced large thumbnail sizes and noticed that after thumbnails were regenerated the faces detected off the original image no longer generate thumbnails correctly.

Looking at the values for those faces still showed that the `imageHeight` and `imageWidth` are still the size of the original thumbnail and the bounding boxes are still relative to that, which makes sense, the face detection was ran against the original thumbnail, but face cropping still tries to happen on a differently sized thumbnail against those parameters.

The border that's drawn on the face when you hover over it in the photo viewer does correctly account for that though by adjusting for the height/width of the image. https://github.com/immich-app/immich/blob/main/web/src/lib/utils/people-utils.ts#L44

Something similar is never done in [handleGeneratePersonThumbnail](https://github.com/immich-app/immich/blob/9b705e445076db9206bc7ee4b0a878372819de60/server/src/services/person.service.ts#L472) as far as I can tell.

Some of them outright fail, I assume from trying to crop out of bounds.
```
[Nest] 7  - 03/28/2024, 12:49:39 AM VERBOSE [PersonService] Cropping face for person: 7f3a3e7c-fbcf-427e-8aeb-88373c83a2e9
[Nest] 7  - 03/28/2024, 12:49:39 AM   ERROR [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: extract_area: bad extract area
[Nest] 7  - 03/28/2024, 12:49:39 AM   ERROR [JobService] Error: extract_area: bad extract area
    at Sharp.toBuffer (/usr/src/app/node_modules/sharp/lib/output.js:161:17)
    at MediaRepository.crop (/usr/src/app/dist/infra/repositories/media.repository.js:36:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/domain/person/person.service.js:389:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/domain/job/job.service.js:137:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```

Happy to get a development setup up and put in a fix if people think the right approach here is to just normalize against the size of the asset it's actually cropping.

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.99

### Version of Immich Mobile App

v1.99

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${DIR_PRIVATE}/rng/Photos/Immich:/usr/src/app/upload
      - ${DIR_PRIVATE}/rng/Photos/Lightroom/Catalog:/mnt/media/lightroom:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ${DOCKER_CONFIG}/compose/immich/immich.env
    environment:
      - TZ=${TZ}
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    user: ${PUID}:${PGID}
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${DIR_PRIVATE}/rng/Photos/Immich:/usr/src/app/upload
      - ${DIR_PRIVATE}/rng/Photos/Lightroom/Catalog:/mnt/media/lightroom:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ${DOCKER_CONFIG}/compose/immich/immich.env
    environment:
      - TZ=${TZ}
    depends_on:
      - redis
      - database
    user: ${PUID}:${PGID}
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - ${DOCKER_CONFIG}/immich/model-cache:/cache
    env_file:
      - ${DOCKER_CONFIG}/compose/immich/immich.env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG}/immich/pgdata:/var/lib/postgresql/data
    restart: unless-stopped
```

### Your .env content

```Shell
IMMICH_VERSION=release

DB_PASSWORD=*****
DB_HOSTNAME=immich_postgres
DB_USERNAME=*****
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Generate thumbnails for an image
2. Run face detection
3. Change large thumbnail resolution
4. Regenerate thumbnail
5. Change feature photo for person in image
```
