### ISSUE TITLE
Mouse stays invisble after album slideshow ends

### ISSUE THREAD

**Issue by emil314** [immich-app/immich#8351]
### The bug

When a slideshow ends because the last picture was reached and the mouse pointer was invisible before (as introduced in v1.100.0), the mouse pointer stays invisible outside of the slideshow. It also stays partly (it depends on what you're hovering above) invisble in other immich views such as the normal timeline. It turns back to normal when you refresh the page.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.99.0

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#


services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #extends:
    #  file: hwaccel.yml
    #  service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    dns:
      - 0.0.0.0 //changed IP for bug request
      - 8.8.8.8

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    ports:
      - 3003:3003

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/foo/bar/ //deleted for bug request
EXTERNAL_PATH=/foo/bar/ //deleted for bug request
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

IMMICH_MACHINE_LEARNING_URL=http://0.0.0.0:3003 //changed IP for bug request


# added to avoid high mem+cpu consumption:
# cf.  https://github.com/immich-app/immich/issues/4530
DISABLE_REVERSE_GEOCODING=true
```

### Reproduction steps

```bash
1. Open an Album you own
2. Open a Picture
3. Start slideshow with the menu (I tested it with diffrent view times and the progress bar enabled and disabled, it occures every time)
4. Wait for the menu and mouse pointer to fade out
5. Wait for the last picture
6. When the slideshow terminates, the pointer stays invisible.
```
