### ISSUE TITLE
Search not working when using OpenVINO

### ISSUE THREAD

**Issue by fwmone** [immich-app/immich#8353]
### The bug

When enabling the immich-machine-learning openvino image, search is not working anymore but throws an HTTP 500 error. The immich-machine-learning log throws:

`[03/29/24 09:48:06] INFO     Loading clip model 'ViT-B-32__openai' to memory    

2024-03-29 09:48:09.988640928 [E:onnxruntime:, inference_session.cc:1985 Initialize] Encountered unknown exception in Initialize()

[03/29/24 09:48:09] ERROR    Exception in ASGI application                      

                                                                                

                             ╭─────── Traceback (most recent call last) ───────╮

                             │ /usr/src/app/main.py:116 in predict             │

                             │                                                 │

                             │   113 │   except orjson.JSONDecodeError:        │

                             │   114 │   │   raise HTTPException(400, f"Invali │

                             │   115 │                                         │

                             │ ❱ 116 │   model = await load(await model_cache. │

                             │       ttl=settings.model_ttl, **kwargs))        │

                             │   117 │   model.configure(**kwargs)             │

                             │   118 │   outputs = await run(model.predict, in │

                             │   119 │   return ORJSONResponse(outputs)        │

                             │                                                 │

                             │ /usr/src/app/main.py:137 in load                │

                             │                                                 │

                             │   134 │   │   │   model.load()                  │

                             │   135 │                                         │

                             │   136 │   try:                                  │

                             │ ❱ 137 │   │   await run(_load, model)           │

                             │   138 │   │   return model                      │

                             │   139 │   except (OSError, InvalidProtobuf, Bad │

                             │   140 │   │   log.warning(                      │

                             │                                                 │

                             │ /usr/src/app/main.py:125 in run                 │

                             │                                                 │

                             │   122 async def run(func: Callable[..., Any], i │

                             │   123 │   if thread_pool is None:               │

                             │   124 │   │   return func(inputs)               │

                             │ ❱ 125 │   return await asyncio.get_running_loop │

                             │   126                                           │

                             │   127                                           │

                             │   128 async def load(model: InferenceModel) ->  │

                             │                                                 │

                             │ /usr/lib/python3.10/concurrent/futures/thread.p │

                             │ y:58 in run                                     │

                             │                                                 │

                             │ /usr/src/app/main.py:134 in _load               │

                             │                                                 │

                             │   131 │                                         │

                             │   132 │   def _load(model: InferenceModel) -> N │

                             │   133 │   │   with lock:                        │

                             │ ❱ 134 │   │   │   model.load()                  │

                             │   135 │                                         │

                             │   136 │   try:                                  │

                             │   137 │   │   await run(_load, model)           │

                             │                                                 │

                             │ /usr/src/app/models/base.py:52 in load          │

                             │                                                 │

                             │    49 │   │   │   return                        │

                             │    50 │   │   self.download()                   │

                             │    51 │   │   log.info(f"Loading {self.model_ty │

                             │       to memory")                               │

                             │ ❱  52 │   │   self._load()                      │

                             │    53 │   │   self.loaded = True                │

                             │    54 │                                         │

                             │    55 │   def predict(self, inputs: Any, **mode │

                             │                                                 │

                             │ /usr/src/app/models/clip.py:146 in _load        │

                             │                                                 │

                             │   143 │   │   super().__init__(clean_name(model │

                             │   144 │                                         │

                             │   145 │   def _load(self) -> None:              │

                             │ ❱ 146 │   │   super()._load()                   │

                             │   147 │   │   self._load_tokenizer()            │

                             │   148 │   │                                     │

                             │   149 │   │   size: list[int] | int = self.prep │

                             │                                                 │

                             │ /usr/src/app/models/clip.py:36 in _load         │

                             │                                                 │

                             │    33 │   def _load(self) -> None:              │

                             │    34 │   │   if self.mode == "text" or self.mo │

                             │    35 │   │   │   log.debug(f"Loading clip text │

                             │ ❱  36 │   │   │   self.text_model = self._make_ │

                             │    37 │   │   │   log.debug(f"Loaded clip text  │

                             │    38 │   │                                     │

                             │    39 │   │   if self.mode == "vision" or self. │

                             │                                                 │

                             │ /usr/src/app/models/base.py:117 in              │

                             │ _make_session                                   │

                             │                                                 │

                             │   114 │   │   │   case ".armnn":                │

                             │   115 │   │   │   │   session = AnnSession(mode │

                             │   116 │   │   │   case ".onnx":                 │

                             │ ❱ 117 │   │   │   │   session = ort.InferenceSe │

                             │   118 │   │   │   │   │   model_path.as_posix() │

                             │   119 │   │   │   │   │   sess_options=self.ses │

                             │   120 │   │   │   │   │   providers=self.provid │

                             │                                                 │

                             │ /opt/venv/lib/python3.10/site-packages/onnxrunt │

                             │ ime/capi/onnxruntime_inference_collection.py:41 │

                             │ 9 in __init__                                   │

                             │                                                 │

                             │    416 │   │   disabled_optimizers = kwargs["di │

                             │        kwargs else None                         │

                             │    417 │   │                                    │

                             │    418 │   │   try:                             │

                             │ ❱  419 │   │   │   self._create_inference_sessi │

                             │        disabled_optimizers)                     │

                             │    420 │   │   except (ValueError, RuntimeError │

                             │    421 │   │   │   if self._enable_fallback:    │

                             │    422 │   │   │   │   try:                     │

                             │                                                 │

                             │ /opt/venv/lib/python3.10/site-packages/onnxrunt │

                             │ ime/capi/onnxruntime_inference_collection.py:48 │

                             │ 3 in _create_inference_session                  │

                             │                                                 │

                             │    480 │   │   │   disabled_optimizers = set(di │

                             │    481 │   │                                    │

                             │    482 │   │   # initialize the C++ InferenceSe │

                             │ ❱  483 │   │   sess.initialize_session(provider │

                             │    484 │   │                                    │

                             │    485 │   │   self._sess = sess                │

                             │    486 │   │   self._sess_options = self._sess. │

                             ╰─────────────────────────────────────────────────╯

                             RuntimeException: [ONNXRuntimeError] : 6 :         

                             RUNTIME_EXCEPTION : Encountered unknown exception  

                             in Initialize()                                    `

Search works well without openvino enabled.

My hwaccel.ml.yml:

`version: "3.8"

# Configurations for hardware-accelerated machine learning

# If using Unraid or another platform that doesn't allow multiple Compose files,
# you can inline the config for a backend by copying its contents
# into the immich-machine-learning service in the docker-compose.yml file.

# See https://immich.app/docs/features/ml-hardware-acceleration for info on usage.

services:
  armnn:
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
      - /usr/lib/libmali.so:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)

  cpu:

  cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video

  openvino:
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb

  openvino-wsl:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /usr/lib/wsl:/usr/lib/wsl
`

I run an Asustor AS6702T NAS with an Intel Celeron N5105 CPU. This problem started with v1.99.0. 

### The OS that Immich Server is running on

ADM 4.2.6RPI1 (Asustor NAS)

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

(not used)

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_LIBRARY}://mnt/media/external_library:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.yml
      service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_LIBRARY}://mnt/media/external_library:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    # image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/volume1/Docker/immich/upload_location

EXTERNAL_LIBRARY=/volume2/...

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Enable the openvino machine learning image / container
2. Try to search something using the web interface
```
