### ISSUE TITLE
Places gives error in v1.100.0 - no error in v1.99.0

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [immich-app/immich#8360]
### The bug

Places gives error in v1.100.0 - no error in v1.99.0 in web interface. Mobile app does not show the error and places are displayed correctly.

Error is:
Failed to get assets by city - 500
Error: Error: 500
    at Object.ie [as ok] (https://photos.xxx.com/_app/immutable/chunks/fetch-client.DbGu7UYN.js:1:2832)
    at async re (https://photos.xxx.com/_app/immutable/nodes/23.D1oj9X-m.js:1:789)
    at async Ie (https://photos.xxx.com/_app/immutable/chunks/entry.CqyUGNmt.js:1:13443)

If I go back to v1.99.0 places works as it did in the past.

### The OS that Immich Server is running on

PI OS

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.99.0 build.129

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${EXTERNAL_PATH}:/usr/src/app/external
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PGDATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/xxx
EXTERNAL_PATH=/yyy
PGDATA_LOCATION=/zzz
IMMICH_VERSION=v1.100.0
DB_PASSWORD=password
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.upgrade to v1.100.0
2.Error is present
3.
...
```
