### ISSUE TITLE
Place; View All; Error 'Failed to get assets by city (500)'

### ISSUE THREAD

**Issue by Philshappy** [immich-app/immich#8367]
### The bug

When selecting 'View All' in the explore tab places, immich reports 'Failed to get assets by city (500)'.  This did not occur in the previous release.

![Screenshot 2024-03-29 091501](https://github.com/immich-app/immich/assets/149206994/7f833427-f7e7-4133-8380-0bdcf48a9a0a)

### The OS that Immich Server is running on

Ubuntu

### Version of Immich Server

V1.100.0

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/NAS6602/Photos:/mnt/media/Photos:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001  
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/NAS6602/Photos:/mnt/media/Photos:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri:/dev/dri
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always


  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /home/phil/Immich/database:/var/lib/postgresql/data
    restart: always


volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/home/phil/Immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
# IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=ABCDEFGGFECBAASCDEFGABCDEFG
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
```

### Reproduction steps

```bash
1.Select Explore
2.Select View All
3.
...
```
