### ISSUE TITLE
Image upload from Android app gives Error uploading file Error: EPERM: operation not permitted, utime

### ISSUE THREAD

**Issue by qbicus** [immich-app/immich#8371]
### The bug

After the 1.99 upgrade any images/videos that the android app tries to upload have missing thumbnails/image. Upon investigating I saw that each upload gives the following error:
[Nest] 248  - 03/29/2024, 6:39:42 PM   ERROR [Error: EPERM: operation not permitted, utime '/photos/upload/c0ec343e-cbe3-4fe1-8402-f957e419a04c/8a/0f/8a0f3517-947c-4295-b81d-3aa774e0de7e.jpg'] Error uploading file Error: EPERM: operation not permitted, utime '/photos/upload/c0ec343e-cbe3-4fe1-8402-f957e419a04c/8a/0f/8a0f3517-947c-4295-b81d-3aa774e0de7e.jpg'
[Nest] 248  - 03/29/2024, 6:39:42 PM   ERROR [Error: EPERM: operation not permitted, utime '/photos/upload/c0ec343e-cbe3-4fe1-8402-f957e419a04c/8a/0f/8a0f3517-947c-4295-b81d-3aa774e0de7e.jpg'] Failed to upload file
[Nest] 248  - 03/29/2024, 6:39:42 PM   ERROR [Error: EPERM: operation not permitted, utime '/photos/upload/c0ec343e-cbe3-4fe1-8402-f957e419a04c/8a/0f/8a0f3517-947c-4295-b81d-3aa774e0de7e.jpg'] Error: EPERM: operation not permitted, utime '/photos/upload/c0ec343e-cbe3-4fe1-8402-f957e419a04c/8a/0f/8a0f3517-947c-4295-b81d-3aa774e0de7e.jpg'

### The OS that Immich Server is running on

Docker on Debian

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0 build 130

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich-app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DB_HOSTNAME=192.168.0.55
      - DB_USERNAME=postgres
      - DB_PASSWORD=-------
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=192.168.0.164
      - DISABLE_MACHINE_LEARNING=false #optional
      - DISABLE_TYPESENSE=false #optional
      - DB_PORT=5434 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD=------- #optional
      
    volumes:
      - /mnt/nas-share/docker/volumes/Immich_Application/config:/config
      - /mnt/nas-share/photos/:/photos
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Your .env content

```Shell
empty
```

### Reproduction steps

```bash
1. Take a new photo with the phone
2. In Android app select to upload the photo
3. Error appears in log
...
```
