### ISSUE TITLE
immich_machine_learning failed to start after 1.98.2

### ISSUE THREAD

**Issue by majorcheng** [immich-app/immich#8381]
### The bug

immich_machine_learning failed to start after upgrade to 1.99 or 1.100 , it's ok in 1.98.2
docker logs shows like
[03/30/24 19:04:34] ERROR    Can't connect to ('::', 3003)
[03/30/24 19:04:36] INFO     Starting gunicorn 21.2.0
[03/30/24 19:04:36] ERROR    Retrying in 1 second.
[03/30/24 19:04:37] ERROR    Retrying in 1 second.
[03/30/24 19:04:38] ERROR    Retrying in 1 second.
[03/30/24 19:04:39] ERROR    Retrying in 1 second.
[03/30/24 19:04:40] ERROR    Retrying in 1 second.

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.99/v.1.100

### Version of Immich Mobile App

v1.99/v.1.100

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      #- /backup/data/immich-app/service/cache:/cache
      - model-cache:/cache
    env_file:
      - .env
    restart: always
```

### Your .env content

```Shell
LOG_LEVEL=debug
TZ="Asia/Shanghai"

# The location where your uploaded files are stored
UPLOAD_LOCATION=/backup/data/immich-app/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_VERSION="v1.98.2"

# Connection secrets for postgres and typesense. You should change these to random passwords

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
docker compose pull && docker compose up -d
```
