### ISSUE TITLE
After 1.100.0 Version Update, ML Workers get killed

### ISSUE THREAD

**Issue by Adriankor** [immich-app/immich#8395]
### The bug

ML Worker Repeatedly killed no ML Container Function at all for the immich server (Face Recognition etc.)

> [03/30/24 21:16:11] INFO     Booting worker with pid: 151                       
[03/30/24 21:16:32] INFO     Started server process [151]                       
[03/30/24 21:16:32] INFO     Waiting for application startup.                   
[03/30/24 21:16:32] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[03/30/24 21:16:32] INFO     Initialized request thread pool with 8 threads.    
[03/30/24 21:16:32] INFO     Application startup complete.                      
[03/30/24 21:16:32] INFO     Setting 'buffalo_l' execution providers to         
                             ['OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'], in descending order of    
                             preference                                         
[03/30/24 21:16:32] INFO     Setting 'ViT-B-32__openai' execution providers to  
                             ['OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'], in descending order of    
                             preference                                         
[03/30/24 21:16:32] INFO     Loading facial recognition model 'buffalo_l' to    
                             memory                                             
[03/30/24 21:16:42] INFO     Loading clip model 'ViT-B-32__openai' to memory    
[03/30/24 21:18:14] INFO     Starting gunicorn 21.2.0                           
[03/30/24 21:18:14] INFO     Listening at: http://[::]:3003 (9)                 
[03/30/24 21:18:14] INFO     Using worker: app.config.CustomUvicornWorker       
[03/30/24 21:18:14] INFO     Booting worker with pid: 17                        
[03/30/24 21:18:37] INFO     Started server process [17]                        
[03/30/24 21:18:37] INFO     Waiting for application startup.                   
[03/30/24 21:18:37] INFO     Created in-memory cache with unloading after 300s  
                             of inactivity.                                     
[03/30/24 21:18:37] INFO     Initialized request thread pool with 8 threads.    
[03/30/24 21:18:37] INFO     Application startup complete.                      
[03/30/24 21:18:37] INFO     Setting 'ViT-B-32__openai' execution providers to  
                             ['OpenVINOExecutionProvider',                      
                             'CPUExecutionProvider'], in descending order of    
                             preference                                         
[03/30/24 21:18:37] INFO     Loading clip model 'ViT-B-32__openai' to memory    
[03/30/24 21:20:37] CRITICAL WORKER TIMEOUT (pid:17)                            
[03/30/24 21:20:38] ERROR    Worker (pid:17) was sent SIGKILL! Perhaps out of   
                             memory?

### The OS that Immich Server is running on

Ubuntu 22.4.04

### Version of Immich Server

1.100.0

### Version of Immich Mobile App

1.100.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: '3.8'

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding

    #hardware accel short for intel cpu 
    devices:
      - /dev/dri:/dev/dri
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      #openvino cpu hardware accel
      - /dev/bus/usb:/dev/bus/usb
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/home/adrian/docker/appdata/immich
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Repeatly redeployed the stack with portainer
2. Deleted the Volumes of the Containers
3. Deployed again
4. Started Backup from iOS App again.
```

### Additional information

I changed some bios settings for CPU C-State and ASPM Support for reducing Power consumption. But nothing else on the server is affected, except Immich.
Also, I activated GNA Device in the Bios.
