### ISSUE TITLE
Feature request: Mobile - Allow users to expand file upload list and prioritize uploads

### ISSUE THREAD

**Issue by ajbogh** [immich-app/immich#8404]
### The bug

The user would like to see which files are being uploaded and what their individual progress is. They may also like to pause uploads that will take more time (like videos) to prioritize other files that are smaller (like pictures).

Feature:

- Allow user to tap file upload area
- The list of Remainder files is displayed with the in-progress files shown with progress bars
- Files that are in progress can be paused and will continue when all other unpaused files are complete (pausing will not cancel a file upload, only delay it until the end)
- Allow concurrent file uploads so that multiple images and videos can be uploaded at the same time

Ideally videos should not block images from uploading, so please prioritize images over videos.

### The OS that Immich Server is running on

Ubuntu 23.10

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    # image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    # image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    # image: tensorchord/pgvecto-rs:pg14-v0.1.11
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pktriot:
    container_name: pktriot
    image: packetriot/pktriot:latest
    volumes:
      - ./pktriot-data:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: bridge
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=OMITTED
DB_PASSWORD=OMITTED
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/UUID/immich-data
TYPESENSE_API_KEY=some-random-text
IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
```

### Reproduction steps

```bash
1. Select backup cloud icon while it's processing images
2. Try clicking on the Uploading file info section
...
```
