### ISSUE TITLE
Upload fails on some images

### ISSUE THREAD

**Issue by monotok** [immich-app/immich#8420]
### The bug

Hi,

I seem to be having an issue uploading some images from the mobile app. These images seem to be perfectly valid images (they are HIEC) and I have uploaded them to my NAS via SMB separately. I am not sure when this started but it has been a few releases, it might have been since I had to swap databases due to the pg-vector requirement.

The mobile app will more or less instantly fail with a notification informing me it has failed. The image will then show as uploaded in the timeline view (cloud with a tick). The image on the web is shown with a broken thumbnail and if I try to download it then it will fail (no error) and is roughly 50B.

In the immich server logs I see this.

```
[Nest] 8  - 03/31/2024, 3:26:21 PM     LOG [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.100.0] [PRODUCTION] 
[Nest] 8  - 03/31/2024, 3:26:21 PM     LOG [EventRepository] Websocket Connect:    6is_4X0LzZRoOldFAAAB
[Nest] 8  - 03/31/2024, 3:26:50 PM     LOG [EventRepository] Websocket Disconnect: 6is_4X0LzZRoOldFAAAB
[Nest] 8  - 03/31/2024, 3:26:51 PM     LOG [EventRepository] Websocket Connect:    LwPUajOw77aCzRNGAAAD
[Nest] 8  - 03/31/2024, 3:26:55 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
[Nest] 8  - 03/31/2024, 3:27:18 PM     LOG [EventRepository] Websocket Connect:    lo_Vzjpmwc0fZN77AAAF
[Nest] 8  - 03/31/2024, 3:27:22 PM   ERROR [AssetServiceV1] Error uploading file QueryFailedError: could not read block 1289 in file "base/16385/151490": read only 0 of 8192 bytes
QueryFailedError: could not read block 1289 in file "base/16385/151490": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:50:9)
    at async AssetServiceV1.create (/usr/src/app/dist/services/asset-v1.service.js:260:9)
    at async AssetServiceV1.uploadFile (/usr/src/app/dist/services/asset-v1.service.js:69:27)
    at async AssetControllerV1.uploadFile (/usr/src/app/dist/controllers/asset-v1.controller.js:43:29)
[Nest] 8  - 03/31/2024, 3:27:22 PM   ERROR [QueryFailedError: could not read block 1289 in file "base/16385/151490": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:50:9)
    at async AssetServiceV1.create (/usr/src/app/dist/services/asset-v1.service.js:260:9)
    at async AssetServiceV1.uploadFile (/usr/src/app/dist/services/asset-v1.service.js:69:27)
    at async AssetControllerV1.uploadFile (/usr/src/app/dist/controllers/asset-v1.controller.js:43:29)] Failed to upload file
[Nest] 8  - 03/31/2024, 3:27:22 PM   ERROR [QueryFailedError: could not read block 1289 in file "base/16385/151490": read only 0 of 8192 bytes
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async InsertQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
    at async AssetRepository.upsertExif (/usr/src/app/dist/repositories/asset.repository.js:50:9)
    at async AssetServiceV1.create (/usr/src/app/dist/services/asset-v1.service.js:260:9)
    at async AssetServiceV1.uploadFile (/usr/src/app/dist/services/asset-v1.service.js:69:27)
    at async AssetControllerV1.uploadFile (/usr/src/app/dist/controllers/asset-v1.controller.js:43:29)] QueryFailedError: could not read block 1289 in file "base/16385/151490": read only 0 of 8192 bytes
[Nest] 8  - 03/31/2024, 3:27:28 PM     LOG [EventRepository] Websocket Disconnect: lo_Vzjpmwc0fZN77AAAF
```

I am not sure if this is a error from the mobile side or the server.

### The OS that Immich Server is running on

Kubernetes

### Version of Immich Server

1.100.0

### Version of Immich Mobile App

1.100.0 build.146

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: v1
data:
  key: XXXX
kind: Secret
metadata:
  name: immich-jwt-key
  namespace: default
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-server
    app: immich
    storage.type: iscsi
  name: immich-server
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-server
    spec:
      nodeName: "kubey01"
      containers:
        - args:
            - start-server.sh
          env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-server:latest
          name: immich-server
          resources: {}
          ports:
            - containerPort: 3001
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-server-claim0
            - mountPath: /usr/src/app/upload/thumbs
              name: immich-thumbs
            - mountPath: /mnt/media/photos-processed
              subPath: Photos-Processed
              name: photos-vol
      restartPolicy: Always
      volumes:
        - name: immich-server-claim0
          persistentVolumeClaim:
            claimName: immich-claim0
        - name: immich-thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs-ext-pvc
        - name: photos-vol
          nfs:
            path: /mnt/CS1_Stripe/Photos
            server: <IP>
            readOnly: true
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-machine-learning
    app: immich
    storage.type: iscsi
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-machine-learning
    spec:
      containers:
        - env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-machine-learning:latest
          name: immich-machine-learning
          resources:
            limits:
              cpu: "4"
          volumeMounts:
            - mountPath: /cache
              name: immich-machine-learning-cache
      restartPolicy: Always
      volumes:
        - name: immich-machine-learning-cache
          persistentVolumeClaim:
            claimName: immich-ml-cache-pvc
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application.name: immich-microservices
    app: immich
    storage.type: iscsi
  name: immich-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      application.name: immich-microservices
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application.name: immich-microservices
    spec:
      nodeName: "kubey01"
      containers:
        - args:
            - start-microservices.sh
          env:
            - name: DB_HOSTNAME
              value: cluster-immich-rw
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cluster-immich-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cluster-immich-user
            - name: DB_DATABASE_NAME
              value: immich-db
            - name: IMMICH_MACHINE_LEARNING_URL
              value: http://immich-machine-learning-service.default.svc:3003
            - name: IMMICH_SERVER_URL
              value: http://immich-server-service.default.svc:3001
            - name: IMMICH_WEB_URL
              value: http://immich-web-service.default.svc:3000
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: key
                  name: immich-jwt-key
            - name: NODE_ENV
              value: production
            - name: PUBLIC_LOGIN_PAGE_MESSAGE
            - name: REDIS_HOSTNAME
              value: immich-redis-master.default.svc
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: immich-redis
            - name: REDIS_DBINDEX
              value: "0"
            - name: REDIS_PORT
              value: "6379"
          image: ghcr.io/immich-app/immich-server:latest
          name: immich-microservices
          resources: {}
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: immich-microservices-claim0
            - mountPath: /usr/src/app/upload/thumbs
              name: immich-thumbs
            - mountPath: /mnt/media/photos-processed
              subPath: Photos-Processed
              name: photos-vol
      restartPolicy: Always
      volumes:
        - name: immich-microservices-claim0
          persistentVolumeClaim:
            claimName: immich-claim0
        - name: immich-thumbs
          persistentVolumeClaim:
            claimName: immich-thumbs-ext-pvc
        - name: photos-vol
          nfs:
            path: /mnt/CS1_Stripe/Photos
            server: <IP>
            readOnly: true
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "50000M"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "64 4k"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-snippet: |-
      gzip on;
      gzip_comp_level 2;
      gzip_min_length 1000;
      gzip_proxied any;
      gzip_types
         application/javascript
         application/json
         font/truetype
         image/svg+xml
         text/css
         text/html;
      gzip_vary on;
      gunzip on;

spec:
  tls:
  - hosts:
    - photo.example./com
    secretName: immich-tls-cert
  rules:
    - host: photo.example./com
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: immich-server-service
               port:
                 number: 3001
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1.Restart the services
2.Open mobile app and try to upload missing image - it fails
3.Delete broken image from web
4.Empty trash
5.Repeat
```

### Additional information

I am using the DB from here: https://github.com/tensorchord/cloudnative-pgvecto.rs/pkgs/container/cloudnative-pgvecto.rs/174587306?tag=16.1-v0.2.0

```
Instances status
Name              Database Size  Current LSN  Replication role  Status  QoS         Manager Version  Node
----              -------------  -----------  ----------------  ------  ---         ---------------  ----
cluster-immich-2  447 MB         57/3F000BF8  Primary           OK      BestEffort  1.22.0           kubey03
cluster-immich-5  447 MB         57/3F000C60  Standby (async)   OK      BestEffort  1.22.0           kubey02
cluster-immich-4  447 MB         57/3F000C30  Standby (async)   OK      BestEffort  1.22.0           kubey02

```
