### ISSUE TITLE
My logo has become like this

### ISSUE THREAD

**Issue by zcr268** [immich-app/immich#8429]
### The bug

My logo has become like this
![image](https://github.com/immich-app/immich/assets/9443858/5c2d5c4e-e0f7-4d00-b66e-d31becea63f1)

### The OS that Immich Server is running on

docker

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#
# format: {{y}}-{{MM}}/{{y}}-{{MM}}-{{dd}}_{{HH}}-{{mm}}-{{ss}}_{{filename}}
# doc: https://immich.app/docs/overview/introduction/
# https://github.com/immich-app/immich/releases
name: immich
services:
  immich-server:
    container_name: immich-server
    image: $PROXY/immich-app/immich-server:${IMMICH_VERSION:-release}
    command:
      #- start.sh
      - pre_start.sh
      - immich
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${EXTERNAL_PATH}:${IMAGE_EXTERNAL_PATH}
      - ${CONFIG_FILE}:${USED_IMMICH_CONFIG_FILE}
      - /etc/localtime:/etc/localtime:ro
      - ./data/custom_script/storage-template.service.js:${TEMPLATE_JS}:ro
      - ./data/custom_script/metadata.service.js:${META_JS}:ro
      - ./data/pre_start.sh:/usr/src/app/pre_start.sh:ro
      #- ./data/package.json:/usr/src/app/package.json:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped
  immich-microservices:
    container_name: immich-microservices
    image: $PROXY/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command:
      #- start.sh
      - pre_start.sh
      - microservices
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${UPLOAD_LOCATION_LIBRARY}:/usr/src/app/upload/library
      - ${EXTERNAL_PATH}:${IMAGE_EXTERNAL_PATH}
      - ${CONFIG_FILE}:${USED_IMMICH_CONFIG_FILE}
      - /etc/localtime:/etc/localtime:ro
      - ./data/custom_script/storage-template.service.js:${TEMPLATE_JS}:ro
      - ./data/custom_script/metadata.service.js:${META_JS}:ro
      - ./data/pre_start.sh:/usr/src/app/pre_start.sh:ro
      #- ./data/package.json:/usr/src/app/package.json:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped
  immich-machine-learning:
    container_name: immich-machine-learning
    image: $PROXY/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./model-cache:/cache
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    restart: always
  redis:
    container_name: immich-redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: unless-stopped
  database:
    container_name: immich-postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./data
UPLOAD_LOCATION_LIBRARY=/volume1/photo/immich
EXTERNAL_PATH=/volume1/photo/photo
IMAGE_EXTERNAL_PATH=/usr/src/app/external
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release
#IMMICH_VERSION=v1.99.0
# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=XXXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=XXX
DB_USERNAME=XXX
DB_DATABASE_NAME=XXX

REDIS_HOSTNAME=immich-redis

CONFIG_FILE=./data/immich-config.json
USED_IMMICH_CONFIG_FILE=/config/immich-config.json
#IMMICH_CONFIG_FILE=/config/immich-config.json

PROXY=ghcr.dockerproxy.com
#PROXY=ghcr.io
```

### Reproduction steps

```bash
1.
2.
3.
...
```
