### ISSUE TITLE
Explore places gives error

### ISSUE THREAD

**Issue by sendev1** [immich-app/immich#8454]
### The bug

Failed to get assets by city - 500
Error: Error: 500
    at Object.ie [as ok] (https://photo.sencloud.duckdns.org/_app/immutable/chunks/fetch-client.DbGu7UYN.js:1:2832)
    at async re (https://photo.sencloud.duckdns.org/_app/immutable/nodes/23.5x258rAJ.js:1:789)
    at async Ie (https://photo.sencloud.duckdns.org/_app/immutable/chunks/entry.CFJS3zKx.js:1:13445)

### The OS that Immich Server is running on

Raspberry Pi OS

### Version of Immich Server

v100.0

### Version of Immich Mobile App

v100.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
---
version: "2.1"
services:
  immich:
    image: ghcr.io/imagegenius/immich:latest
    container_name: immich
    mem_limit: 2500m
    environment:
      - PUID=1003
      - PGID=100
      - TZ=America/Chicago
      - DB_HOSTNAME=*************
      - DB_USERNAME=**************
      - DB_PASSWORD=*************
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=**********
      - DB_PORT=5432 #optional
      - REDIS_PORT=6379 #optional
      - REDIS_PASSWORD= #optional
      - MACHINE_LEARNING_GPU_ACCELERATION= #optional
      - MACHINE_LEARNING_WORKERS=1 #optional
      - MACHINE_LEARNING_WORKER_TIMEOUT=120 #optional
    volumes:
      - ./config:/config
      - ./Photo_Library:/photos
    ports:
      - 8088:8080
    restart: unless-stopped
    network_mode: bridge
  # This container requires an external application to be run separately to be run separately.
  # By default, ports for the databases are opened, be careful when deploying it
  # Redis:
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
    restart: unless-stopped
    network_mode: bridge
  # PostgreSQL 14:
  postgres14:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      POSTGRES_USER: ****
      POSTGRES_PASSWORD: ****
      POSTGRES_DB: ****
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

```bash
Just clicked on Explore > places in web app and got that error. In mobile Search > Places not showing any places
```
