### ISSUE TITLE
[Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Failed to get server info

### ISSUE THREAD

**Issue by luyzfernando08** [immich-app/immich#8485]
### The bug

I'm using a NAS to store photos and for some reason the storage information is no longer shown.

![image](https://github.com/immich-app/immich/assets/134880920/475dea28-dcf0-4fcc-a38b-41cabc8b5985)

Additionally, when trying to access the administrator area I receive the error below.

![image](https://github.com/immich-app/immich/assets/134880920/c492a308-eee8-4032-a2de-07a6693cd52b)

`Failed to get server info (500)

Stacktrace
Error: Error: 500
    at Object.ie [as ok] (http://fotos.local/_app/immutable/chunks/fetch-client.DbGu7UYN.js:1:2832)
    at async v (http://fotos.local/_app/immutable/chunks/auth.BSeebS59.js:1:636)
    at async ml (http://fotos.local/_app/immutable/nodes/39.DZd7bJfn.js:1:1738)
    at async Ie (http://fotos.local/_app/immutable/chunks/entry.gs5-sG3j.js:1:13443)`

`2024-04-03 07:35:52 [Nest] 6  - 04/03/2024, 10:35:52 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Failed to get server info`
`2024-04-03 07:35:52 [Nest] 6  - 04/03/2024, 10:35:52 AM   ERROR [Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'] Error: EAGAIN: resource temporarily unavailable, statfs 'upload/library'`

I'm not sure which version of Immich the problem started with

### The OS that Immich Server is running on

Windows 11

### Version of Immich Server

v1.100.0

### Version of Immich Mobile App

v1.100.0 build 130

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes: 
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - upload:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - "D:/Immich/pgdata:/var/lib/postgresql/data"
    restart: always

volumes:
  model-cache:
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.199/Immich/cache
      o: addr=192.168.0.199,vers=2.0,username=XXXXXX,password=XXXXX,file_mode=0777,dir_mode=0777
  upload: 
    driver: local
    driver_opts:
      type: cifs
      device: //192.168.0.199/Immich/upload
      o: addr=192.168.0.199,vers=2.0,username=XXXXX,password=XXXXX,file_mode=0777,dir_mode=0777
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=immich-upload

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.100.0

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=TYPESENSE_API_KEY
DB_PASSWORD=XXXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. open the web or mobile app
2. access the area to view "Server Storage"
```
