### ISSUE TITLE
[BUG] Unable to run after initial batch upload - High IOWait

### ISSUE THREAD

**Issue by joeShuff** [immich-app/immich#858]
**Describe the bug**
I am planning on migrating over from google photos so I got the container spun up prior to myself and my partner receiving our google takeout zips and it was all fine. Tested app backup, bulk backup via CLI and all was good.

Once I received our takeout zips I unpacked them, reorganized and got them ready to bulk upload via the CLI tool. It took a long time which I expected but that seemed to finish off great. 

After I uploaded everything the server started to become unresponsive. I managed to get a glimpse of netdata as it was struggling and I could see the IOWait graph was huge and not going down. Once I stopped the immich stack- it dropped back down to next to nothing. (which is usual levels)

During the time it was lagging I managed to find out a few things.

- The high IOWait was on my boot drive where the docker volumes would be, NOT the drive my media is stored on and mounted via the `UPLOAD_LOCATION` env variable.
- The likely task causing the issue was simply displayed as "Node" in the `iotop` command, and every time I saw it, it had a different task ID so maybe some recurring task?

docker-compose
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    deploy:
      resources:
        limits:
          cpus: 1.5
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    deploy:
      resources:
        limits:
          cpus: 1
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:

```
 
redacted .env

```
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
UPLOAD_LOCATION=/mnt/hdd/media/Photos
LOG_LEVEL=simple
JWT_SECRET=<secret>
```

**Task List**

- [ x ] I have read thoroughly the README setup and installation instructions.
- [ x ] I have included my `docker-compose` file.
- [ x ] I have included my redacted `.env` file.
- [ x ] I have included information on my machine, and environment.

**System**
- Phone OS [iOS, Android]: `Android 11`
- Server Version: Don't wanna start the container to find out but its latest as of now, so I'd guess `1.32.1`
- Mobile App Version: `1.32.0`
