### ISSUE TITLE
Some videos (but not all) stutter when viewing from the web

### ISSUE THREAD

**Issue by pingcheunglai** [immich-app/immich#8657]
### The bug

I'm running into an issue where some videos, but not all, stutter when viewing from the web. By stutter, I mean it looks like it freezes every half second for a moment and this lasts throughout the entire video, which makes for a very jerky watching experience. There's no indication the video is buffering, and the file size does not seem to matter (can happen with both large and small video files).

If a video is affected, the stutter happens whether I am hovering over the thumbnail or clicking into the video. The video file itself is fine - it plays back without issue when downloaded. Similarly, viewing the same video on the app does not have any stutter either.

Would appreciate any suggestions!

### The OS that Immich Server is running on

Ubuntu 22.04 LTS

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0 build.131

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# docker-compose.yml 
version: '3.8'

name: immich

networks:
  internal:
    driver: bridge

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - immichpgdata:/var/lib/postgresql/data
    restart: always

volumes:
  immichpgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=**********
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

UPLOAD_LOCATION=/mnt/photos/Immich
```

### Reproduction steps

```bash
1. Take video on cell phone
2. Let it autoupload to Immich
3. Sometimes the video stutters when viewing from the web (after it has completed processing). Not all videos are affected - appears to be random.
```

### Additional information

I'm running Immich on an Intel NUC with a Core i5-1135G7 and 32GB of RAM.
