### ISSUE TITLE
Partner Sharing not working on iOS

### ISSUE THREAD

**Issue by dannyvfilms** [immich-app/immich#8756]
### The bug

I configured partner sharing between my wife's account and mine. I am able to see my wife's photos on iOS and Web, but she is not able to see any of my shared content on iOS. I logged into the web on her account (which she does not use) and shared content is available. Attached are screen recordings of my app and my wife's. 

https://photos.dannyvfilms.com/share/HdYKjOuVAINqMFgfqTKFWzn7KsAoJ2I2sA9l7HJEv4TM5hUtuG9VzoiPGyL1W6b6RWQ

### The OS that Immich Server is running on

Unraid

### Version of Immich Server

1.101.0

### Version of Immich Mobile App

1.101.0 build.147

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database

    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database

    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always



volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/mnt/user/NachoSupreme/Backups/Offsite/Photos
IMMICH_VERSION=release
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open Immich on iOS
2. Select Sharing
3. Add a new Partner Share

Expected behavior is new partner photos are available. Resulting behavior is partner photos are not available.
```

### Additional information

Working device is iPhone 15 Pro. Issue device is iPhone 13. Both devices are running iOS 17.4.1
