### ISSUE TITLE
replay button not working on immich mobile app

### ISSUE THREAD

**Issue by Rihcus** [immich-app/immich#8761]
### The bug

Replay button is unresponsive:

https://github.com/immich-app/immich/assets/30292597/b9c6c14c-17bb-4e33-8b26-618c06e5d9c9

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS aarch64 

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0 build.131

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: 'TRUE'
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /db_dumps
    volumes:
      - /media/usb-hdd1/immich-backup/db_dumps:/db_dumps
    depends_on:
      - database

  caddy:
    image: caddy-desec:latest
    build: .
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./container-config:/etc/caddy
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - immich-server

  tailscale: 
    container_name: tailscale 
#    hostname: tailscale-immich 
    image: tailscale/tailscale:stable 
    volumes: 
      - ./tailscale:/var/lib # State data will be stored in this directory 
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work 
    cap_add: # Required for tailscale to work 
      - net_admin 
      - sys_module 
    command: tailscaled
    network_mode: container:caddy
    environment:
      - TS_ACCEPT_DNS=false
#      - TS_ROUTES=192.168.1.0/24
    privileged: false 
    restart: unless-stopped
    depends_on:
      - caddy

  ssh_portforward:
    image: davidlor/ssh-port-forward-client:dev
    container_name: ssh_portforward
    restart: unless-stopped
    network_mode: container:immich_server
    security_opt:
      - label:disable
    environment:
      - SSH_HOST=999.999.999.999 # ip obfuscated
      - SSH_USER=demo
#      - MAPPINGS=R3001:127.0.0.1:58737
      - MAPPINGS=R127.0.0.1:58737:127.0.0.1:3001
#      - MAPPINGS=R2283:127.0.0.1:58737
    volumes:
      - ./ssh_key/id_rsa:/ssh_key:ro
    depends_on:
      - immich-server

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/usb-hdd1/PhotoLibraryIM

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open a Video on immich mobile app
2. Let the video completly play
3. Try to click on the replay button 
...
```

### Additional information

One ui 6.1

I doubt this relates to the issue but regarding the three additional containers:

Tailscale docker:
https://tailscale.com/kb/1282/docker 
https://hub.docker.com/r/tailscale/tailscale

ssh_portforward:
https://github.com/David-Lor/Docker-SSH-Port-Forward-Client
https://hub.docker.com/r/davidlor/ssh-port-forward-client

caddy-desec:latest

Docker file:

```
FROM caddy:builder-alpine AS builder

RUN xcaddy build --with github.com/caddy-dns/desec

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
