### ISSUE TITLE
Immich breaks when there is a power outage

### ISSUE THREAD

**Issue by script-js** [immich-app/immich#8796]
### The bug

Recently, there was a power outage at my house. When the power came back on, I restarted my server to find that nothing shows up on the web UI, and the app cannot connect. Something like this has happened when my server crashed, and I had to completely reset the image and delete all of my pictures and settings. I really don't want to do this again, what should I do? I'm running a 2014 Mac Mini with 8 GB of ram, a Core i5, and a 512 GB HDD.

![image](https://github.com/immich-app/immich/assets/134544514/9d7f88b1-b214-4152-9922-13526bc78784)
![image](https://github.com/immich-app/immich/assets/134544514/f9c3252c-e84b-42b7-89f3-686aa0ab930a)

### The OS that Immich Server is running on

MacOS Monterey

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env

    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
Unknown
```

### Reproduction steps

```bash
1. Unplug server from power
2.
3.
...
```
