### ISSUE TITLE
Unknown keys found: "image"

### ISSUE THREAD

**Issue by 5ouma** [immich-app/immich#8807]
### The bug

I use my config with the "image" section. With this, Immich warns that there is no matched key, and this config is not reflected on the web.
Also, I couldn't edit image config from the web even if config is not existing.

### The OS that Immich Server is running on

OrbStack v1.5.1

### Version of Immich Server

v1.101.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v1.101.0@sha256:c1dbaec9766ba7a380833af2717c911a1490849e93060575414fb7f67378a03a
    command: ["start.sh", "immich"]
    env_file: [".env"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./config/immich.json:${IMMICH_CONFIG_FILE}:ro
    depends_on:
      - redis
      - database
      - tailscale
    network_mode: service:tailscale
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:v1.101.0@sha256:c1dbaec9766ba7a380833af2717c911a1490849e93060575414fb7f67378a03a
    command: ["start.sh", "microservices"]
    env_file: [".env"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ./config/immich.json:${IMMICH_CONFIG_FILE}:ro
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v1.101.0@sha256:067b76281cf7cb894e1a380aa0d388c6a04e0b192cdbaad3c5f82bdf71ff7821
    env_file: [".env"]
    volumes:
      - model-cache:/cache
    restart: always

  redis:
    container_name: immich_redis
    image: redis:7.2.4-alpine@sha256:7635b0bfdd7dd8552b4b31d6541fef07b734614045b45a52fd5cc27c9dada9e2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.1@sha256:ff2288833f32aa863ba46f4c6f5b5c143f526a2d27f4cca913c232f917a66602
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:16@sha256:c577b0d62673d4dce0471c75d21e3e08e4e9789903f5a3fd6613c410442e9670
    env_file: [".env"]
    environment:
      POSTGRES_HOST: database
      POSTGRES_CLUSTER: "TRUE"
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      POSTGRES_EXTRA_OPTS: "--clean --if-exists"
      BACKUP_DIR: /db_dumps
    volumes:
      - ./db_dumps:/db_dumps
    depends_on:
      - database
    restart: always

  tailscale:
    container_name: immich_tailscale
    hostname: immich
    image: tailscale/tailscale:v1.62.1@sha256:3b310f980cd9ff0e334e48c53eb95b21d77b72a596854c4369fd028f83b41b10
    env_file: [".env"]
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: /config/tailscale.json
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
      - ./config/tailscale.json:/config/tailscale.json:ro
    cap_add:
      - net_admin
      - sys_module
    restart: always

volumes:
  pgdata:
  model-cache:
  tailscale-state:
```

### Your .env content

```Shell
UPLOAD_LOCATION=./library
IMMICH_CONFIG_FILE=/config/immich.json
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD="<my db password>"
DB_DATABASE_NAME=immich
TS_AUTHKEY=""
```

### Reproduction steps

I use this config below and other than "image", there is no warnings.
```json
{
  "image": {
    "thumbnailSize": 1080,
    "thumbnailFormat": "webp",
    "previewSize": 2160,
    "previewFormat": "jpeg",
    "quality": 100,
    "colorspace": "p3"
  },
  "job": {
    "thumbnailGeneration": { "concurrency": 5 },
    "metadataExtraction": { "concurrency": 5 },
    "library": { "concurrency": 5 },
    "sidecar": { "concurrency": 5 },
    "search": { "concurrency": 5 },
    "smartSearch": { "concurrency": 2 },
    "faceDetection": { "concurrency": 2 },
    "videoConversion": { "concurrency": 1 },
    "migration": { "concurrency": 5 },
    "backgroundTask": { "concurrency": 5 }
  },
  "library": {
    "watch": { "enabled": false },
    "scan": { "enabled": true, "cronExpression": "0 0 * * *" }
  },
  "logging": { "enabled": true, "level": "log" },
  "machineLearning": {
    "enabled": true,
    "url": "http://immich-machine-learning:3003",
    "clip": { "enabled": true, "modelName": "ViT-B-32__openai" },
    "facialRecognition": {
      "enabled": true,
      "modelName": "buffalo_l",
      "minScore": 0.7,
      "maxDistance": 0.5,
      "minFaces": 3
    }
  },
  "map": {
    "enabled": true,
    "lightStyle": "",
    "darkStyle": ""
  },
  "reverseGeocoding": { "enabled": true },
  "oauth": {
    "autoLaunch": false,
    "autoRegister": true,
    "buttonText": "Login with OAuth",
    "clientId": "",
    "clientSecret": "",
    "defaultStorageQuota": 0,
    "enabled": false,
    "issuerUrl": "",
    "mobileOverrideEnabled": false,
    "mobileRedirectUri": "",
    "scope": "openid email profile",
    "signingAlgorithm": "RS256",
    "storageLabelClaim": "preferred_username",
    "storageQuotaClaim": "immich_quota"
  },
  "passwordLogin": { "enabled": true },
  "server": { "externalDomain": "", "loginPageMessage": "" },
  "storageTemplate": {
    "enabled": true,
    "hashVerificationEnabled": true,
    "template": "{{y}}/{{MM}}-{{dd}}/{{filename}}"
  },
  "theme": { "customCss": "" },
  "trash": { "enabled": true, "days": 30 },
  "user": { "deleteDelay": 7 },
  "newVersionCheck": { "enabled": true },
  "ffmpeg": {
    "crf": 23,
    "preset": "ultrafast",
    "targetAudioCodec": "aac",
    "acceptedAudioCodecs": ["aac", "mp3", "libopus"],
    "targetVideoCodec": "h264",
    "acceptedVideoCodecs": ["h264", "hevc", "vp9"],
    "targetResolution": "original",
    "maxBitrate": "0",
    "threads": 0,
    "transcode": "all",
    "tonemap": "hable",
    "twoPass": false,
    "accel": "disabled",
    "cqMode": "auto",
    "temporalAQ": false,
    "preferredHwDevice": "auto",
    "npl": 0,
    "bframes": -1,
    "refs": 0,
    "gopSize": 0
  }
}
```

### Relevant log output

```shell
immich_microservices     | [Nest] 6  - 04/15/2024, 10:24:27 AM    WARN [SystemConfigCore] Unknown keys found: {
immich_microservices     |   "image": {
immich_microservices     |     "thumbnailSize": 1080,
immich_microservices     |     "thumbnailFormat": "webp",
immich_microservices     |     "previewSize": 2160,
immich_microservices     |     "previewFormat": "jpeg",
immich_microservices     |     "quality": 100,
immich_microservices     |     "colorspace": "p3"
immich_microservices     |   }
immich_microservices     | }
```
