### ISSUE TITLE
IPV6 Connection issues since update to v1.102.0

### ISSUE THREAD

**Issue by Morethanevil** [immich-app/immich#8931]
### The bug

Since the latest update, the binding adress is 127.0.0.1:3001
I used the new env "HOST" to connect via IPV6 as always via my reverse proxy.

I tried `HOST="::1"` but I can not connect via my reverse proxy

`Log says: LOG [ImmichServer] Immich Server is listening on http://[::1]:3001/ [v1.102.0] [PRODUCTION]`

Then I tried `HOST="::" `<- all interfaces including IPV6 - works

Log says exactly the same, but it works now:

`LOG [ImmichServer] Immich Server is listening on http://[::1]:3001/ [v1.102.0] [PRODUCTION]`

I use the static IPV6 "fd00:112::2" for immich, the reverse proxy is installed on the host, so I need static adresses. I tried `HOST="fd00:112::2"` and it works too, as expected, the log then says correctly:

`LOG [ImmichServer] Immich Server is listening on http://[fd00:112::2]:3001/ [v1.102.0] [PRODUCTION]`

I tried `HOST="localhost" `too, it does not work either for IPV6.

Log exactly the same :) 

`LOG [ImmichServer] Immich Server is listening on http://[::1]:3001/ [v1.102.0] [PRODUCTION]`

### The OS that Immich Server is running on

Fedora 39 KDE

### Version of Immich Server

v1.102.0

### Version of Immich Mobile App

v1.102.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
#   ports:
#     - 2283:3001
    networks:
      innendienst:
        ipv4_address: 172.20.0.2
        ipv6_address: fd00:112::2
      default:

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    container_name: immich_microservices
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - default

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:release-cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
    volumes:
      - /docker/immich/modelcache:/cache
    env_file:
      - .env
    restart: always
    networks:
      - default

  redis:
    container_name: immich_redis
    image: redis:7.2-alpine
    restart: always
    networks:
      - default

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - /docker/immich/db:/var/lib/postgresql/data
    restart: always
    networks:
      - default

networks:
  innendienst:
    external: true
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

###################################################################################
# The Immich version to use. You can pin this to a specific version like "v1.71.0"
###################################################################################

#IMMICH_VERSION=release
HOST="::"

###################################################################################
# Database
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=posti
DB_PASSWORD=redacted
DB_DATABASE_NAME=immichdb
# Optional Database settings:
DB_PORT=5432
###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis
# Optional Redis settings:

# Note: these parameters are not automatically passed to the Redis Container
# to do so, please edit the docker-compose.yml file as well. Redis is not configured
# via environment variables, only redis.conf or the command line

# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_USERNAME=
# REDIS_PASSWORD=
# REDIS_SOCKET=


###################################################################################
# Upload File Location
#
# This is the location where uploaded files are stored.
###################################################################################
UPLOAD_LOCATION=/weiteres/immichpics
```

### Reproduction steps

```bash
Edit .env with HOST envs as explained above
```

### Relevant log output

```shell
[Nest] 7  - 04/19/2024, 9:41:50 PM     LOG [ImmichServer] Immich Server is listening on http://[::1]:3001 [v1.102.0] [PRODUCTION]
```
