### ISSUE TITLE
Table "asset_faces" seems corrupt

### ISSUE THREAD

**Issue by EricThunder** [immich-app/immich#8936]
### The bug

When trying to use make a database backup either with the docker image or the command ([documentation I used](https://immich.app/docs/administration/backup-and-restore/#database)) errors out, mentioning it fails at table "assets_faces" . The command partially completes the backup while the docker image completly aborts the process.

### The OS that Immich Server is running on

Ubuntu server 22.04

### Version of Immich Server

v1.102.0

### Version of Immich Mobile App

v1.101.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
     - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  immich-microservices:
      container_name: immich_microservices
      image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
      # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      #   file: hwaccel.transcoding.yml 
      #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
      command: [ "start.sh", "microservices" ]
      volumes:
        - ${UPLOAD_LOCATION}:/usr/src/app/upload
        - /etc/localtime:/etc/localtime:ro
      env_file:
        - .env
      depends_on:
        - redis
        - database
      restart: always
      labels:
        - "com.centurylinklabs.watchtower.enable=false"

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_DIR: /db_dumps
      BACKUP_KEEP_DAYS: 5
      TZ: America/Toronto
    volumes:
      - /LunaSMB/Backup/Immich-Database-Backup/db_dumps:/db_dumps
    depends_on:
      - database
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/LunaSMB/Immich

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=some-random-text
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Start the backup process
2. See the results
```

### Relevant log output

```shell
The docker image logs:
2024/04/19 20:20:22 15: Creating dump of immich database from database...
2024/04/19 20:20:23 15: pg_dump: error: Dumping the contents of table "asset_faces" failed: PQgetResult() failed.
pg_dump: detail: Error message from server: ERROR:  missing chunk number 0 for toast value 206398 in pg_toast_16911
pg_dump: detail: Command was: COPY public.asset_faces ("assetId", "personId", embedding, "imageWidth", "imageHeight", "boundingBoxX1", "boundingBoxY1", "boundingBoxX2", "boundingBoxY2", id) TO stdout;
2024/04/19 20:20:23 15 Exit Status: 1
```

### Additional information

The weird thing is that is *seems* like everything in the WebUI works as intented, including the people's section (despite it being the current trouble-maker).
