### ISSUE TITLE
CLI dry-run shows incorrect album count

### ISSUE THREAD

**Issue by rawcomposition** [immich-app/immich#8966]
### The bug

When running a upload dry run with `--album` and `--recursive` attributes, it says:

> Would have created 0 new albums

but when running the command without dry run, it correctly creates the albums.

> Successfully created 1 new album

See below:

```bash
adamjackson@bumblebee:~/Desktop/v2023$ immich upload --dry-run --recursive --album 2000/
Discovered API at http://localhost:2283/api
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 38s
Found 38 new files and 0 duplicates
Would have uploaded 38 assets (18.6 MB)
Would have created 0 new albums
Would have updated 0 assets

adamjackson@bumblebee:~/Desktop/v2023$ immich upload --recursive --album 2000/
Discovered API at http://localhost:2283/api
Crawling for assets...
Checking files | ████████████████████████████████████████ | 100% | ETA: 0s | 38s
Found 38 new files and 0 duplicates
Uploading assets | ████████████████████████████████████████ | 100% | ETA: 0s | B
Successfully uploaded 38 assets (18.6 MB)
Creating albums | ████████████████████████████████████████ | 100% | ETA: 0s | 1s
Successfully created 1 new album
Successfully updated 38 assets
Adding assets to albums | ████████████████████████████████████████ | 100% | ETAs
```

### The OS that Immich Server is running on

Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.102.2

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=v1.102.2

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xyz

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1.Run `immich upload --dry-run --recursive --album DIR_WITH_SUB_DIRS/` 
2. The response includes `Would have created 0 new albums`
3. Run `immich upload --recursive --album DIR_WITH_SUB_DIRS/`
4. The response includes `Successfully created 1 new album`
5. I expected the response in step 2 to include the same exact album count as shown in step 4.
```

### Additional information

This is a brand new Immich install from a few hours ago with no existing images in the library, and no customizations in the settings.
