### ISSUE TITLE
Regenerating thumbnails doesn't relink all of them inside the database

### ISSUE THREAD

**Issue by NyaomiDEV** [immich-app/immich#8981]
### The bug

After migrating to WebP from Jpeg I noticed that all of the Jpeg files were left over inside the thumbnails folder, so I just... `find . -type f -name "*.jpeg" -delete`'d them, thinking I'd be fine. To be honest, I am still fine, they are previews and my actual library resides somewhere else, however I found a bug.

The bug is, I think Live Previews do have a thumbnail of their own which means extra storage used. Why is that? Probably it's there by design - but anyway... the ACTUAL bug is, sure the job regenerated their thumbnails into WebP format, but it forgot to update the database, it seems, because in my `Offline Paths` section now I have 1048 missing assets and faces and from taking a look to some of them manually:
- they've all been reconverted to WebP
- of course I removed their Jpeg counterpart

Also, the thumbnails job doesn't seem to regenerate any of the people's faces previews, so they're now all missing from my library.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

Not applicable

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - immich
    volumes:
      - /data/immich/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    depends_on:
      - redis
      - postgres
    networks:
      - default
      - nginx_default
    restart: always
  immich_microservices:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - microservices
    volumes:
      - /data/immich/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    depends_on:
      - redis
      - postgres
    networks:
      - default
    restart: always
  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    networks:
      - default
    restart: always
  redis:
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    networks:
      - default
    restart: always
  postgres:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - /data/immich/db:/var/lib/postgresql/data
    networks:
      - default
    restart: always
volumes:
  model-cache: null
networks:
  default: null
  nginx_default:
    external: true
```

### Your .env content

```Shell
nothing here
```

### Reproduction steps

```bash
1. Have some photos with live previews
2. Migrate previews to WebP and run the thumbnail job for all assets
3. Delete all the Jpegs from the thumbnail cache
4. Observe issue
```

### Additional information

Probably I was stupid to use that option when it first dropped.
