### ISSUE TITLE
People's thumbnails don't get regenerated from the job that is supposed to regenerate them

### ISSUE THREAD

**Issue by NyaomiDEV** [immich-app/immich#8982]
### The bug

![image](https://github.com/immich-app/immich/assets/13177694/f0580987-6927-4bcd-a304-b6581e35856a)

This is a lie.

### The OS that Immich Server is running on

Arch

### Version of Immich Server

v1.102.3

### Version of Immich Mobile App

Not applicable

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich_server:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - immich
    volumes:
      - /data/immich/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    depends_on:
      - redis
      - postgres
    networks:
      - default
      - nginx_default
    restart: always
  immich_microservices:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - microservices
    volumes:
      - /data/immich/photos:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    depends_on:
      - redis
      - postgres
    networks:
      - default
    restart: always
  immich_machine_learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - model-cache:/cache
    environment:
      DB_HOSTNAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
    networks:
      - default
    restart: always
  redis:
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    networks:
      - default
    restart: always
  postgres:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
    volumes:
      - /data/immich/db:/var/lib/postgresql/data
    networks:
      - default
    restart: always
volumes:
  model-cache: null
networks:
  default: null
  nginx_default:
    external: true
```

### Your .env content

```Shell
nothing here
```

### Reproduction steps

```bash
1. Delete some faces from the thumbnail cache
2. Try to regenerate them
```
