### ISSUE TITLE
[BUG] Images & thumbnails are not loading

### ISSUE THREAD

**Issue by palitu** [immich-app/immich#903]
**Describe the bug**
After an update to the latest version (via docker-compose pull & docker-compose up), i can no longer view images or thumbnails.  

**Task List**

*Please complete the task list below. We need this information to help us reproduce the bug or point out problems in your setup. You are not providing enough info may delay our effort to help you.*

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**To Reproduce**
1. Load the WebUI, locations are reserved, but the thumbnails do not load.  Clicking on an thumbnail placeholder, opens the next screen, but no image is shown.
2. Load the Android, locations are reserved, but the thumbnails do not load (pre-cached thumbnails load as normal).  Clicking on an thumbnail placeholder, opens the next screen, but no image is shown.

**Some logs when accessing images/thumbnails**
```
immich-server              | [Nest] 6  - 10/31/2022, 1:59:19 AM     LOG [WebsocketConnectionEvent] Client PdubOeDWglYeYbfWAAAB disconnected from Websocket
immich-server              | [Nest] 6  - 10/31/2022, 2:00:25 AM   ERROR [serveFile[VIDEO]] Error serving VIDEO asset id 67790e76-19e7-40ed-a63a-d4a262db6da1
immich-server              | [Nest] 6  - 10/31/2022, 2:00:51 AM     LOG [WebsocketConnectionEvent] New websocket connection: O4VRLSjd2p1sl5VeAAAD
immich-server              | [Nest] 6  - 10/31/2022, 2:00:53 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset eec8c3b8-8e8e-4ee2-894b-aeaa094ceaed
immich-server              | [Nest] 6  - 10/31/2022, 2:00:53 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 9f153d0e-3f75-4397-a49a-4b14fa4d28aa
immich-server              | [Nest] 6  - 10/31/2022, 2:00:53 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 7b07af9e-5ee3-4b8d-9c5d-5abb663bb492
immich-server              | [Nest] 6  - 10/31/2022, 2:00:53 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset cdcddd96-6aef-4e38-860d-6199c5d51afd
immich-server              | [Nest] 6  - 10/31/2022, 2:00:53 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 5ef6ec6f-db96-4c58-af84-b73af9c94522
immich-server              | [Nest] 6  - 10/31/2022, 2:02:26 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 90bb47aa-6968-4d3f-ad3c-cb233a7dfb8f
immich-server              | [Nest] 6  - 10/31/2022, 2:02:26 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 4d35353a-a67d-4cc2-93c1-97f281768754
immich-server              | [Nest] 6  - 10/31/2022, 2:04:37 AM   ERROR [serveFile[IMAGE]] Cannot create read stream for asset 3457b425-11ca-4f82-8f94-3b1aa3618c7d {"errno":-2,"code":"ENOENT","syscall":"access","path":"upload/e4244f56-6d2d-4895-9a67-54593de506e9/original/30b5559cdd8e304f406a038704809fecd81fe5f15ffd143891e216b012d3c07c/20d6bc39-768b-485b-b16e-e0683341e115.jpg"}
immich-server              | [Nest] 6  - 10/31/2022, 2:04:37 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 3457b425-11ca-4f82-8f94-3b1aa3618c7d
immich-server              | [Nest] 6  - 10/31/2022, 2:04:38 AM   ERROR [getAssetThumbnail] Cannot create read stream for asset 3457b425-11ca-4f82-8f94-3b1aa3618c7d
immich-server              | [Nest] 6  - 10/31/2022, 2:04:38 AM   ERROR [serveFile[IMAGE]] Cannot create read stream for asset 3457b425-11ca-4f82-8f94-3b1aa3618c7d {"errno":-2,"code":"ENOENT","syscall":"access","path":"upload/e4244f56-6d2d-4895-9a67-54593de506e9/original/30b5559cdd8e304f406a038704809fecd81fe5f15ffd143891e216b012d3c07c/20d6bc39-768b-485b-b16e-e0683341e115.jpg"}
```

**Expected behavior**
I expect that the images will load.

**Screenshots**
![image](https://user-images.githubusercontent.com/6634784/198916520-77a4c662-49ad-4605-af43-5a67bc30bf6d.png)

**System**
- Phone OS [iOS, Android]: `<version>`
- Server Version: `v1.33.1` (Docker, Ubuntu 18.04)
- Mobile App Version: `1.33.0 b52`

**Additional context**
Has been working flawlessly until now.  no breaking changes since last update.

**compose**
```
  immich-server:
    container_name: immich-server
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - ./immich/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-microservices:
    container_name: immich-microservices
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - ./immich/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-web:
    container_name: immich-web
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - ./immich/.env
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-redis:
    container_name: immich-redis
    image: redis:6.2
    restart: always

  immich-postgres:
    container_name: immich-postgres
    image: postgres:14
    env_file:
      - ./immich/.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - ./immich/pgdata:/var/lib/postgresql/data
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  immich-proxy:
    container_name: immich-proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    container_name: immich-ML
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:nt:
      - ./immich/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - immich-postgres
    restart: always
```

**.env**
```
LOG_LEVEL=verbose
DB_HOSTNAME=immich-postgres
DB_USERNAME=postgres
DB_PASSWORD=xxxxxxxxxxx
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich-redis
UPLOAD_LOCATION=/home/xxxx/appdata/immich/uploads
JWT_SECRET=randomstringth
ENABLE_MAPBOX=false
MAPBOX_KEY=
VITE_SERVER_ENDPOINT=http://xx.xx.xx.xx:2283/api
VITE_LOGIN_PAGE_MESSAGE=
```
