### ISSUE TITLE
Unable to pull container: lchown /root/.npm: no data available

### ISSUE THREAD

**Issue by mmanjos** [immich-app/immich#9157]
### The bug

When running a `docker compose pull` in order to fetch v1.103.0, I get this error:

`failed to register layer: failed to Lchown "/root/.npm" for UID 0, GID 0: lchown /root/.npm: no data available`

### The OS that Immich Server is running on

Ubuntu 24.04 docker 24.0.7-0ubuntu4

### Version of Immich Server

v1.103.0

### Version of Immich Mobile App

v1.103.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

#name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=<redacted>

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./postgres

REDIS_HOSTNAME=immich_redis
TYPESENSE_API_KEY=<redacted>
```

### Reproduction steps

```bash
1. run `docker compose pull`
```

### Relevant log output

```shell
$ docker compose pull
[+] Pulling 27/28
 ✔ immich-server Skipped - Image is already being pulled by immich-microservices                            0.0s 
 ✔ immich-machine-learning Pulled                                                                           0.3s 
 ✔ redis Pulled                                                                                             0.1s 
 ✔ database Pulled                                                                                          0.2s 
 ⠹ immich-microservices 23 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulling                        29.2s 
   ✔ 8a1e25ce7c4f Already exists                                                                            0.0s 
   ✔ 503fbb4f74df Already exists                                                                            0.0s 
   ✔ e2fa1cdece32 Already exists                                                                            0.0s 
   ✔ 2049901257b8 Already exists                                                                            0.0s 
   ✔ 5b715564989c Already exists                                                                            0.0s 
   ✔ 311e00033755 Pull complete                                                                             0.2s 
   ✔ 0c8521ffe1e4 Pull complete                                                                             0.2s 
   ✔ c68d2c0d9e55 Pull complete                                                                             0.2s 
   ✔ 95d9257dff9a Pull complete                                                                             4.6s 
   ✔ ba1bd3dcf569 Pull complete                                                                             5.2s 
   ✔ 8b9d19fddc55 Pull complete                                                                             0.8s 
   ✔ 6a5f14ed0472 Pull complete                                                                             1.0s 
   ✔ 4f4fb700ef54 Pull complete                                                                             1.2s 
   ✔ ac401cec6bd4 Pull complete                                                                             4.4s 
   ✔ e222c3f4f79d Pull complete                                                                             4.6s 
   ✔ f54dbd4bc903 Pull complete                                                                             4.7s 
   ✔ c1e40a5bd4f7 Pull complete                                                                             5.0s 
   ✔ a8a18b5ae173 Pull complete                                                                             4.9s 
   ✔ 54e7a40835df Pull complete                                                                             5.2s 
   ✔ 0a5c46400896 Pull complete                                                                             5.2s 
   ✔ bafbf79a0a97 Download complete                                                                         5.5s 
   ✔ 33b732620422 Download complete                                                                         5.4s 
   ✔ 10651723fc0f Download complete                                                                         5.4s 
failed to register layer: failed to Lchown "/root/.npm" for UID 0, GID 0: lchown /root/.npm: no data available
```
