### ISSUE TITLE
Immich not accessible after update to v1.103.1 

### ISSUE THREAD

**Issue by toennema** [immich-app/immich#9171]
### The bug

Installed the latest version with `docker compose pull && docker compose up -d`. 
Before the update, the system was running v1.102.3 which worked well. The web page is inaccessible and the server logs show errors. I have already tried to restart all containers and also did a fresh install with the latest env and compose file, but Immich remains unavailable. Please help. Thank you.

### The OS that Immich Server is running on

Debian (Raspberry Pi OS)

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.102.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./upload
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Install latest Immich version by running ‘docker compose pull && docker compose up -d’
2. Try to access web page
3. Webpage is inaccessible
```

### Relevant log output

```shell
Immich_micro services log:
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: connect EHOSTUNREACH 172.26.0.4:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:29:21 AM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)


Immich_server log:
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [NestFactory] Starting Nest application...
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] BullModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] OpenTelemetryModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] OpenTelemetryCoreModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] ClsModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:45:17 AM     LOG [InstanceLoader] BullModule dependencies initialized +0ms
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
[Nest] 7  - 04/30/2024, 3:45:17 AM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND database
Error: getaddrinfo ENOTFOUND database
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
```
