### ISSUE TITLE
FATAL:  no pg_hba.conf entry for host

### ISSUE THREAD

**Issue by amgschnappi** [immich-app/immich#9175]
### The bug

1. Install docker desktop and wsl2
2. Docker desktop uses wls2
3. Download docker compose and .env file in C:\Users\username\Pictures\Immich folder
4. docker compose up on cli
5. Wait for 5 mins
6. Try to access http://localhost:2283/

Issue : Browser says "The connection was reset". Docker cli says "immich_postgres          | 2024-04-30 07:32:45.576 UTC [150] FATAL:  no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption"

### The OS that Immich Server is running on

Windows 10 with wsl2

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Install docker desktop and wsl2
2. Docker desktop uses wls2
3. Download docker compose and .env file in C:\Users\username\Pictures\Immich folder
4. docker compose up on cli
5. Wait for 5 mins
6. Try to access http://localhost:2283/

Issue : Browser says "The connection was reset". Docker cli says "immich_postgres          | 2024-04-30 07:32:45.576 UTC [150] FATAL:  no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption"
```

### Relevant log output

```shell
immich_server            | [Nest] 8  - 04/30/2024, 7:35:16 AM   ERROR [ExceptionHandler] no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption
immich_server            | error: no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption
immich_server            |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:283:98)
immich_server            |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:122:29)
immich_server            |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:35:38)
immich_server            |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
immich_server            |     at Socket.emit (node:events:518:28)
immich_server            |     at addChunk (node:internal/streams/readable:559:12)
immich_server            |     at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
immich_server            |     at Readable.push (node:internal/streams/readable:390:5)
immich_server            |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
immich_microservices exited with code 0
immich_server exited with code 0
immich_postgres          | 2024-04-30 07:35:35.485 UTC [217] FATAL:  no pg_hba.conf entry for host "172.20.0.5", user "postgres", database "immich", no encryption
immich_postgres          | 2024-04-30 07:35:36.419 UTC [218] FATAL:  no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption
immich_postgres          | 2024-04-30 07:35:38.536 UTC [219] FATAL:  no pg_hba.conf entry for host "172.20.0.5", user "postgres", database "immich", no encryption
immich_postgres          | 2024-04-30 07:35:39.483 UTC [220] FATAL:  no pg_hba.conf entry for host "172.20.0.6", user "postgres", database "immich", no encryption
```
