### ISSUE TITLE
IOS problem with upload

### ISSUE THREAD

**Issue by Smiehoo** [immich-app/immich#9216]
### The bug

On iOS (iPhone 15 Pro) photos are no uploaded on server when I open the app. The upload stuck. I must restart app and then the photos are on timeline but with wrong cloud indicator. Cloud icons show there are only on mobile but I have this photos on server (web). I have second phone with Android 13 and there everything works perfect.

### The OS that Immich Server is running on

Synology DSM

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

1.103.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich-srv
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich-mcs
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich-mlr
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume1/docker/immich-model:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich-rds
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich-db
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
```

### Your .env content

```Shell
x
```

### Reproduction steps

```bash
1. Take a photos.
2. Open app.
3. No new photos are show on timeline but backup icon show thats something is in progress.
4. Detail info about uploading file show no file uploading progress,
5. Restart app.
6. New photos is now on timeline but cloud icon show thats only on mobile (but in fact there is copy on server (visible on web).
7. Logs show error below.
```

### Relevant log output

```shell
PlatformDispatcher - Catch all
type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast
#0 _CastListBase.[] (dart:_internal/cast.dart:99)
#1 ListBase.toList (dart:collection/list.dart:225)
#2 AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54)
#3 ApiClient.fromJson (package:openapi/api_client.dart:262)
#4 ApiClient.deserialize (package:openapi/api_client.dart:158)

#5 AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74)

#6 AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:57)

#7 SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161)

#8 SyncService.syncRemoteAssetsToDb. (package:immich_mobile/shared/services/sync.service.dart:53)

#9 AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:45)

#10 AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
```
