### ISSUE TITLE
Machine learning service fails to start

### ISSUE THREAD

**Issue by lhjt** [immich-app/immich#9227]
### The bug

Trying to start the machine learning service results in the following error before termination:

```
 Error: Unable to configure handler 'console'
```

### The OS that Immich Server is running on

Containerised on Linux Ubuntu 22.04.4 LTS

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: immich-machine-learning
  name: immich-machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: immich-machine-learning
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: immich-machine-learning
    spec:
      containers:
        - image: ghcr.io/immich-app/immich-machine-learning:v1.103.1
          name: immich-machine-learning
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - mountPath: /cache
              name: model-cache
      restartPolicy: Always
      volumes:
        - name: model-cache
          hostPath:
            path: /volumes/immich/model-cache
```

### Your .env content

```Shell
N/A
```

### Reproduction steps

```bash
1. Apply the above kubernetes manifest
2. Observe that the container fails with the error
```

### Relevant log output

```shell
Error: Unable to configure handler 'console'
```
