### ISSUE TITLE
Immich Logo not scaled properly on web browser

### ISSUE THREAD

**Issue by jimeelicious** [immich-app/immich#9236]
### The bug

I appreciate the team's efforts in Immich which has played a tremendous role in getting me off the "App which must be named." I'd like to inform of a simple css bug noted on the web browser.

When generating a public share, a public share URL is generated. On this webpage, the immich logo appears on the top left.

On a web browser (Firefox and Chrome) whose window is wide, it appears normally.
![image](https://github.com/immich-app/immich/assets/18080637/02c88b98-5ac1-4828-8ffa-0ac461dfa960)

However, when scaling the window narrower, the Immich logo is reduced abnormally on Firefox (and Chrome)
![image](https://github.com/immich-app/immich/assets/18080637/9b1df28e-5d89-4104-bd6f-6a35359eec39)

Issue is also reproducible on a mobile web browser as well:
![438237661_960694472400981_7440643755898662996_n](https://github.com/immich-app/immich/assets/18080637/901c91fe-e556-4d8c-9752-9cce76204bc0)

### The OS that Immich Server is running on

Debian GNU/Linux 12 (bookworm)

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

1.103.1 build.137

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${FAMILY_PHOTOS}:/mnt/familyphotos:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends:
      file: hwaccel.transcoding.yml
      service: quicksync
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - ${FAMILY_PHOTOS}:/mnt/familyphotos:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applic>
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# Timezone
TZ=America/Los_Angeles

# Family photos that are mounted in the LXC, not Docker container
FAMILY_PHOTOS=/mnt/familyphotos/

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=[REDACTED]

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=[REDACTED]
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Select image > Share
2. Generate a public share (non-expiring, and uploadable) link
3. Copy the generated share link, paste in a web browser
4. Resize window to narrower width, OR open the generated link into a mobile web browser (not app)
```

### Relevant log output

```shell
No relevant logs. Issue is a simple CSS bug
```

### Additional information

Immich server is served behind an Apache reverse proxy running TLS
