### ISSUE TITLE
Issue with Machine Learning and Smart Search

### ISSUE THREAD

**Issue by Matt-UKTX** [immich-app/immich#9276]
### The bug

I am unable to use any of the machine learning features of Immich.  When I check the log for microservices, I see errors shown below.

I'm runnng a standaline Postgres DB (pg-vectors installed and working) and Redis.  Perhaps this is part of the issue?  Please forgive my ignorance as I am new to Docker/Self-Hosting.

### The OS that Immich Server is running on

Docker on Synology NAS

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
    immich-server:
        image: ghcr.io/immich-app/immich-server:release
        command: ["start.sh", "immich" ]
        container_name: immich-svr
        ports:
            - 4000:3001
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /volume1/docker/immich/upload:/usr/src/app/upload
        env_file:
            - stack.env
        network_mode: bridge
        restart: always
    
    immich-microservices:
        image: ghcr.io/immich-app/immich-server:release
        command: ["start.sh", "microservices"]
        container_name: immich-ms
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /volume1/docker/immich/upload:/usr/src/app/upload
        env_file:
            - stack.env
        security_opt:
            - no-new-privileges:true
        network_mode: bridge
        restart: always
    
    immich-machine-learning:
        image: ghcr.io/immich-app/immich-machine-learning:release
        container_name: immich-ml
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /volume1/docker/immich/upload:/usr/src/app/upload
            - /volume1/docker/immich/cache:/cache
        env_file:
            - stack.env
        security_opt:
            - no-new-privileges:true
        network_mode: bridge
        restart: always
```

### Your .env content

```Shell
TZ=America/Chicago
DB_URL=postgresql://user:userpwd@192.168.XX.XX:PORT/immich
REDIS_HOSTNAME=192.168.XX.XX
REDIS_PORT=6379
```

### Reproduction steps

```bash
1. Upload images to Immich
2. Search for "Dog" or "Car" get an error on Smart Search
3. Run machine learning job on assets to support Smart Search, see error in log shown below.
```

### Relevant log output

```shell
[Nest]` 7  - 05/05/2024, 10:17:56 PM   ERROR [JobService] Unable to run job handler (smartSearch/smart-search): Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning

[Nest] 7  - 05/05/2024, 10:17:56 PM   ERROR [JobService] Error: Machine learning request to "http://immich-machine-learning:3003" failed with Error: getaddrinfo ENOTFOUND immich-machine-learning
    at /usr/src/app/dist/repositories/machine-learning.repository.js:19:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MachineLearningRepository.predict (/usr/src/app/dist/repositories/machine-learning.repository.js:18:21)
    at async SmartInfoService.handleEncodeClip (/usr/src/app/dist/services/smart-info.service.js:85:31)
    at async /usr/src/app/dist/services/job.service.js:149:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
```
