### ISSUE TITLE
iOS asset upload state stays "not uploaded"

### ISSUE THREAD

**Issue by chr-ftw** [immich-app/immich#9327]
### The bug

on iOS mobile app upload state of pictures do not change.
Happens after some time, initially after login everything works as expected.
Icon state "not uploaded to cloud" while it actually is. Refreshing (swiping down) does not change.
It is not only the icon state, pictures are also not available to be added to an album in mobile app.
Mobile app also shows no detailed metadata information besides date/time and image size

In browser immich works as expected, all assets marked as "not uploaded" in iOS mobile are available. 

immich is running in docker on synology behind NGINX Reverse Proxy 

I can resolve by logging out and in, and waiting for timeline creation. Eventually the issue comes back.
This has been an issue since I started using immich some month ago with previous versions.

![IMG_2049](https://github.com/immich-app/immich/assets/121669848/015b60b3-4850-49ec-a3aa-c8ac40907918)
![IMG_2051](https://github.com/immich-app/immich/assets/121669848/b644b87c-722c-47d8-874d-68dcbd3c4d21)

### The OS that Immich Server is running on

Docker on Synology

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.0 build 155

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  
  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local
    env_file:
      - stack.env
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily" #"* * * * *" #"@hourly"
      BACKUP_DIR: /db_dumps
      POSTGRES_EXTRA_OPTS: "-Z1 --clean"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
    volumes:
      - ${DB_DUMP_LOCATION}:/db_dumps
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/volume1/docker/immich/library
IMMICH_VERSION=release
DB_PASSWORD=removed
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
DB_DUMP_LOCATION=/volume1/docker/immich/db_backup2
```

### Reproduction steps

```bash
1. create new asset on mobile
2. wait for upload, upload succeeds to server
3. iOS Mobile app state of assed (icon) stays "not uploaded".
4. this is not only a visualization issue, assets are also missing detailed information and are not available to be added to an album (only on mobile) while everything is fine in browser version
...
```
