### ISSUE TITLE
WARN [StorageRepository] File upload/thumbs/.../  does not exist

### ISSUE THREAD

**Issue by maltokyo** [immich-app/immich#9349]
### The bug

I use an external library, photos are curated in my own directory structure.  No auto uploads, only manually placed in that library folder, where I have 1000s of directories and hundreds of thousands of photos.  I have never touched any of the immich created database files or thumbnail directories manually, though recently in the logs, I start seeing endless lines of this error (see logs section below). I am not sure what is causing it, unclear from any other info in the logs.  Any advice on where I can look?  

### The OS that Immich Server is running on

Debian 12 latest updates applied

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.103.1

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/===REDACTED===path/to/my/photo/library:/mnt/path/to/my/photo/library:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - /mnt/===REDACTED===path/to/my/photo/library:/mnt/path/to/my/photo/library:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://immich_server:3001/api
      API_KEY: ===REDACTED===
      ROOT_PATH: /mnt/===REDACTED===path/to/my/photo/library
      CRON_EXPRESSION: "0 * * * *"
      TZ: Europe/Zurich
      ALBUM_LEVELS: 1

volumes:
  model-cache:

networks:
  default:
    external: true #needs to be created by other file
    name: mynetworkname
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./z_immich_metadata
DB_DATA_LOCATION=./z_immich_db

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
# TYPESENSE_API_KEY=REDACTED
DB_PASSWORD=REDACTED

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres

DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis


###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=verbose
```

### Reproduction steps

```bash
1. Run immich with included docker-compose.yml and env
2. Check logs
```

### Relevant log output

```shell
immich_microservices         | [Nest] 7  - 05/07/2024, 12:00:02 AM    WARN [StorageRepository] File upload/thumbs/13f0f8ca-8a14-48d2-96e3-2b2168456703/fb/bf/fbbfb458-0776-471c-a1f7-08504fe25311.jpeg does not exist.
immich_microservices         | [Nest] 7  - 05/07/2024, 12:00:02 AM    WARN [StorageRepository] File upload/thumbs/13f0f8ca-8a14-48d2-96e3-2b2168456703/fb/bf/fbbfd1cb-2832-4393-91d3-ad1d83eab39e.jpeg does not exist.
immich_microservices         | [Nest] 7  - 05/07/2024, 12:00:02 AM    WARN [StorageRepository] File upload/thumbs/13f0f8ca-8a14-48d2-96e3-2b2168456703/fb/c0/fbc0766f-5f2c-4b29-bbc3-64d817355bb9.jpeg does not exist.
```
```


### Additional information

_No response_
