### ISSUE TITLE
Mobile client not refreshing, after uploads not showing assets as cloud uploaded

### ISSUE THREAD

**Issue by freemjohn** [immich-app/immich#9389]
### The bug

1. Mobile client not refreshing even if manual
2. After uploading assets - assets not shown as uploaded to cloud
3. Relogin fixes refresh ONE time, then after some time issue reappears.

There is NOTHING in server side logs AT ALL,

### The OS that Immich Server is running on

Debian 12, Docker 26

### Version of Immich Server

v1.10.3.1

### Version of Immich Mobile App

v1.10.3.1 build 137

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always


  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
    restart: always


volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_USERNAME=postgres
DB_PASSWORD=xxxxxxxxxxxxxxxxxxx
DB_DATABASE_NAME=immich

DB_DATA_LOCATION=/data/immich/postgres
UPLOAD_LOCATION=/data/immich/data

IMMICH_VERSION=release
```

### Reproduction steps

```bash
Normal use.
After one of last updates that's happened.
3 phones - Android 13,12, all the same. Some rarely used phones just not refreshing at all, photo from cloud for month or something like this not shown, therefore old ones loaded fully and exported on try correctly.

There is NO ERROR in immich log files at all, nor in web app.
Mobile app shown errors included below
```

### Relevant log output

```shell
There are errors in MOBILE APP LOGS. Plenty of. Mostly one repeating

PlatformDispatcher - Catch all

type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast

#0      _CastListBase.[] (dart:_internal/cast.dart:99)
#1      ListBase.toList (dart:collection/list.dart:225)
#2      AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54)
#3      ApiClient.fromJson (package:openapi/api_client.dart:262)
#4      ApiClient.deserialize (package:openapi/api_client.dart:158)
<asynchronous suspension>
#5      AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74)
<asynchronous suspension>
#6      AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:57)
<asynchronous suspension>
#7      SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161)
<asynchronous suspension>
#8      SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53)
<asynchronous suspension>
#9      AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:45)
<asynchronous suspension>
#10     AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52)
<asynchronous suspension>
#11     HomePage.build.refreshAssets (package:immich_mobile/modules/home/views/home_page.dart:87)
<asynchronous suspension>
#12     MultiselectGrid.build.wrapLongRunningFun.<anonymous closure> (package:immich_mobile/shared/ui/asset_grid/multiselect_grid.dart:415)
<asynchronous suspension>
#13     RefreshIndicatorState._show.<anonymous closure>.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:508)
<asynchronous suspension>


```
