### ISSUE TITLE
iOS App no longer refreshing photos after removing offline files

### ISSUE THREAD

**Issue by pjft** [immich-app/immich#9412]
### The bug

I open the iOS app but it no longer refreshes photos since this afternoon. The only thing that happened today was that I was curating some of my photos, deleting some from my external library and then deleted offline files. Also rotated a few and refreshed thumbnails and metadata.

The error messages are the following, on the iOS front:

```
PlatformDispatcher - Catch all

type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast

From 
ImmichErrorLogger

Stack trace

#0 _CastListBase.[] (dart:_internal/cast.dart:99) 
#1 ListBase.toList (dart:collection/list.dart:225) 
#2 AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54) 
#3 ApiClient.fromJson (package:openapi/api_client.dart:262) 
#4 ApiClient.deserialize (package:openapi/api_client.dart:158) <asynchronous suspension> 
#5 AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74) <asynchronous suspension> 
#6 AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:57) <asynchronous suspension> 
#7 SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161) <asynchronous suspension> 
#8 SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53) <asynchronous suspension> 
#9 AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:45) <asynchronous suspension> 
#10 AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52) <asynchronous suspension> 
#11 HomePage.build.refreshAssets (package:immich_mobile/modules/home/views/home_page.dart:87) <asynchronous suspension> 
#12 MultiselectGrid.build.wrapLongRunningFun.<anonymous closure> (package:immich_mobile/shared/ui/asset_grid/multiselect_grid.dart:415) <asynchronous suspension> 
#13 RefreshIndicatorState._show.<anonymous closure>.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:508) <asynchronous suspension>
```

The current workaround is to sign out and sign back in again to regenerate the library.

### The OS that Immich Server is running on

Raspberry Pi OS

### Version of Immich Server

1.103.1

### Version of Immich Mobile App

1.103.0 build.155

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      - ${EXTERNAL_PATH}:/usr/src/app/external
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/srv/dev-disk-by-label-HDD/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/srv/dev-disk-by-label-HDD/immich/postgres

EXTERNAL_PATH=/srv/dev-disk-by-label-HDD/root/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=xxxxxxx

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=xxxxxxx
DB_DATABASE_NAME=xxxxx
```

### Reproduction steps

```bash
(I'm assuming the cause is what I describe in step 1).

1. Open a library-initialized iOS app after deleting external files and removing offline files from the server.
2. The library won't refresh.
```

### Relevant log output

```shell
PlatformDispatcher - Catch all

type '_Map<String, dynamic>' is not a subtype of type 'String' in type cast

From 
ImmichErrorLogger

Stack trace

#0 _CastListBase.[] (dart:_internal/cast.dart:99) 
#1 ListBase.toList (dart:collection/list.dart:225) 
#2 AuditDeletesResponseDto.fromJson (package:openapi/model/audit_deletes_response_dto.dart:54) 
#3 ApiClient.fromJson (package:openapi/api_client.dart:262) 
#4 ApiClient.deserialize (package:openapi/api_client.dart:158) <asynchronous suspension> 
#5 AuditApi.getAuditDeletes (package:openapi/api/audit_api.dart:74) <asynchronous suspension> 
#6 AssetService._getRemoteAssetChanges (package:immich_mobile/shared/services/asset.service.dart:57) <asynchronous suspension> 
#7 SyncService._syncRemoteAssetChanges (package:immich_mobile/shared/services/sync.service.dart:161) <asynchronous suspension> 
#8 SyncService.syncRemoteAssetsToDb.<anonymous closure> (package:immich_mobile/shared/services/sync.service.dart:53) <asynchronous suspension> 
#9 AssetService.refreshRemoteAssets (package:immich_mobile/shared/services/asset.service.dart:45) <asynchronous suspension> 
#10 AssetNotifier.getAllAsset (package:immich_mobile/shared/providers/asset.provider.dart:52) <asynchronous suspension> 
#11 HomePage.build.refreshAssets (package:immich_mobile/modules/home/views/home_page.dart:87) <asynchronous suspension> 
#12 MultiselectGrid.build.wrapLongRunningFun.<anonymous closure> (package:immich_mobile/shared/ui/asset_grid/multiselect_grid.dart:415) <asynchronous suspension> 
#13 RefreshIndicatorState._show.<anonymous closure>.<anonymous closure> (package:flutter/src/material/refresh_indicator.dart:508) <asynchronous suspension>
```

### Additional information

I open the iOS app but it no longer refreshes photos since this afternoon. The only thing that happened today was that I was curating some of my photos, deleting some from my external library and then deleted offline files. Also rotated a few and refreshed thumbnails and metadata.

The current workaround is to sign out and sign back in again to regenerate the library.
