### ISSUE TITLE
Fujifilm color space from RAW (RAF file) is incorrect (preview images and thumbnail)

### ISSUE THREAD

**Issue by gerwim** [immich-app/immich#9473]
### The bug

When viewing the JPEG which is generated from the RAW files, the color space is incorrect.

Attachment 1: JPEG from Immich
![immich](https://github.com/immich-app/immich/assets/1841721/50140d30-4013-4ada-bec4-184bb5eec868)

Attachment 2: JPEG from Capture One (export from RAW), no adjustments
![DSCF4808 1](https://github.com/immich-app/immich/assets/1841721/45819e75-9189-4eb3-bcea-2e3c6085fde7)

Original file (required to reproduce, can't upload on GitHub, max size is 25 MB):
https://drive.google.com/file/d/1SUz2oRpGMTyqGcMK0QiXJycJ4oNeM6eU/view?usp=drive_link

### The OS that Immich Server is running on

Rocky Linux 9

### Version of Immich Server

v1.104.0

### Version of Immich Mobile App

not relevant

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    #extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #  file: hwaccel.transcoding.yml
    #  service: quicksync # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/photos
# The location where your database files are stored
DB_DATA_LOCATION=./postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. Download the ![original file](https://drive.google.com/file/d/1SUz2oRpGMTyqGcMK0QiXJycJ4oNeM6eU/view?usp=drive_link) (see link above) 
2. Upload this file to Immich using the web interface
3. View the generated thumbnail and preview
4. This image should have the same colors as ![attachment 2](https://github.com/immich-app/immich/assets/1841721/45819e75-9189-4eb3-bcea-2e3c6085fde7)
```

### Additional information

Google Drive shows the same (wrong colors) as immich. The issue is probably related to imagemagick (or other library).
