### ISSUE TITLE
Ignore Certificate Error issue on registering a new account

### ISSUE THREAD

**Issue by Oneloutre** [immich-app/immich#9493]
### The bug

Hi, 

I just updated my immich install and I was really happy to see the new update about the mail thing.
But when I configured it, I think a little mistake has been made while coding the UI :

When you activate the "Ignore TLS certificate validation errors (not recommended)", it doesn't make the verification. But de-activating this option enable the verification.

Here are the screens, 1 image is worth a thousand words : 

Here, it should not try to verify : 

![Capture d’écran 2024-05-14 à 22 11 41](https://github.com/immich-app/immich/assets/54822802/d8fe5e07-b343-4da7-a75e-2fb6d212a36f)

but disabled, it doesn't verify : 

![Capture d’écran 2024-05-14 à 22 12 27](https://github.com/immich-app/immich/assets/54822802/97c1dffb-6599-4ebb-a72c-8254e2fd8afb)

I hope it will help, thanks for your hard work.

### The OS that Immich Server is running on

Docker • Debian 5.10.209-2 (2024-01-31) x86_64

### Version of Immich Server

v1.105.0

### Version of Immich Mobile App

not used but the last one

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:c5a607fb6e1bb15d32bbcf14db22787d19e428d59e31a5da67511b49bb0f1ccc
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/media/photos

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
DB_PASSWORD=MySecretDbPassword

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. try to add an email account for sending mails
2. check "Ignore TLS certificate validation errors (not recommended)"
3. see
```
