### ISSUE TITLE
WebSocket Connect Error, version status offline

### ISSUE THREAD

**Issue by Jamminroot** [immich-app/immich#9511]
### The bug

Hey!
Thanks for the amazing service & app.

WebSocket connection seem to fail, and server status displays as offline. DevConsole shows that websocket connection fails.

I've tried several suggestions from reddit or other issues here, but that didn't seem to help.

Some details:
Immich is running as docker container on machine on local network (proxmox container, but that should not really matter), at 192.168.1.101
I use Nginx for reverse proxying.

```yaml
server {
    listen 443 ssl;
    server_name <edited, public link like immich.server.com>;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_certificate /etc/pve/nodes/pxhome/pveproxy-ssl.pem;
    ssl_certificate_key /etc/pve/nodes/pxhome/pveproxy-ssl.key;


    # allow large file uploads
    client_max_body_size 50000M;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;


    proxy_set_header   Upgrade    $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_redirect     off;
    proxy_http_version 1.1;

    # set timeout
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    send_timeout       600s;



    location / {
        proxy_pass http://192.168.1.101:2283;
    }
}
```

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    #image: tensorchord/pgvecto-rs:pg14-v0.1.11
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=./library

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=Edited_Pwd1
DB_PASSWORD=Edited_Pwd2

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Open web ui
```

### Relevant log output

```shell
assets.store.DdsYK4Jv.js:1  WebSocket connection to 'wss://<EDITED>/api/socket.io/?EIO=4&transport=websocket' failed: 
doOpen @ assets.store.DdsYK4Jv.js:1
open @ assets.store.DdsYK4Jv.js:1
open @ assets.store.DdsYK4Jv.js:1
T @ assets.store.DdsYK4Jv.js:1
open @ assets.store.DdsYK4Jv.js:1
(anonymous) @ assets.store.DdsYK4Jv.js:1
assets.store.DdsYK4Jv.js:1 Websocket Connect Error Error: websocket error
    at ws.onError (assets.store.DdsYK4Jv.js:1:15251)
    at ws.onerror (assets.store.DdsYK4Jv.js:1:21833)
```
