### ISSUE TITLE
Failed upload - Large movie files (>1GB) on Android

### ISSUE THREAD

**Issue by gboudreau** [immich-app/immich#9515]
### The bug

Yesterday, I took 4 videos on my Android (Pixel 7) phone. One of them was uploaded without issues by background backup, but the other 3 couldn't. Notifications indicated failed upload, retrying.

You can see the 3 problematic files in the first two rows:
<img width="539" alt="image" src="https://github.com/immich-app/immich/assets/370329/e113e57c-722d-42ec-b246-ca74ad42d071">

The video file that could be uploaded is 781 MB in size. The smallest file that fails to upload is 1.04 GB.

So I tried to disable background and foreground backup, and manually upload the video, to ensure the problem was not with those. It still doesn't work.

I see the upload progress in my notifications drawer, and in the app:
<img width="524" alt="image" src="https://github.com/immich-app/immich/assets/370329/35831537-ca95-4dc3-98d4-c0e05724e2cc">
<img width="537" alt="image" src="https://github.com/immich-app/immich/assets/370329/18efeba5-4077-4ca3-a98f-39341c3005b6">

But once the progress reaches 100%, it simply indicates the upload failed:
<img width="538" alt="image" src="https://github.com/immich-app/immich/assets/370329/54c73322-7a7b-4213-a9b0-3a4472b6b3ea">

There are no errors in the logs, on the server or in the mobile app (except the upload log on mobile, which simply indicates 0 success, 1 failed - see screenshot below).

### The OS that Immich Server is running on

Debian

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [X] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /mnt/samba/Photos:/mnt/samba/Photos
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

    deploy:
      resources:
        limits:
          cpus: "2"

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: ['start.sh', 'microservices']
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${LIBRARY_LOCATION}:/usr/src/app/upload/library
      - ${UPLOAD_LOCATION}:/usr/src/app/upload/upload
      - ${THUMBS_LOCATION}:/usr/src/app/upload/thumbs
      - ${PROFILE_LOCATION}:/usr/src/app/upload/profile
      - ${VIDEO_LOCATION}:/usr/src/app/upload/encoded-video
      - /mnt/samba/Photos:/mnt/samba/Photos
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ${MODEL_CACHE_LOCATION}:/cache
    env_file:
      - .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
LIBRARY_LOCATION=./_vol/library/
THUMBS_LOCATION=./_vol/thumbs/
UPLOAD_LOCATION=./_vol/upload/
PROFILE_LOCATION=./_vol/profile/
VIDEO_LOCATION=./_vol/encoded-video/
MODEL_CACHE_LOCATION=./_vol/model-cache/
DB_DATA_LOCATION=./_vol/pgdata/

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=...

TZ=America/Montreal

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take a video of more than 1GB on your Android phone.
2. Try to upload it to Immich.
```

### Additional information

Nothing (no errors) gets logged, except the confirmation that the upload failed.
I checked the mobile and server logs.

<img width="536" alt="image" src="https://github.com/immich-app/immich/assets/370329/67cc8879-dcbe-4dba-98ed-f8fe425aa29a">
