### ISSUE TITLE
Issue with "cinematic" videos created by android phone

### ISSUE THREAD

**Issue by MelanieTanaka** [immich-app/immich#9581]
### The bug

I have issues with videos created by an android phone: Pixel 4, official google camera app shipped with the phone.

video settings: on video mode I select "cinematic pan" under "video stabilization".

My immich mobile app auto-uploads to the server. 

Regular videos that do not have this option selected play fine on the web browser immich app. 
Videos with "cinematic pan" seem to not upload correctly via the mobile app (on web browser they have a red cicrle with ! in the top right corner in gallery view, clicking the video thumbnail results in infinite loading animation).

 **If I transfer the video file to my PC via USB cable then drag & drop into the immich web app for manual upload, video playback is fine and this issue does not occur.**

### The OS that Immich Server is running on

debian 12.5 + docker

### Version of Immich Server

v1.103.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [ ] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always


  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
       file: hwaccel.ml.yml
       service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    restart: always

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/data/photos
# The location where your database files are stored
DB_DATA_LOCATION=/data/photosdb

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=*********************

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1. have immich app configured to auto upload to server
2. use android phone to create video with "cinematic pan" selected for video stabilization
3. allow video to upload
4. attempt to view video in web browser version of immich
5. create a "normal" video and some photos, allow them to upload to make sure everything else is fine
```

### Relevant log output

```shell
Only 2 lines of logs generate when the video is uploaded (docker compose logs -f):


immich_microservices     | [Nest] 7  - 05/18/2024, 2:12:12 PM     LOG [MediaService] Successfully generated JPEG video preview for asset b03b1111-3b19-4956-bd43-bf151d06186a
immich_microservices     | [Nest] 7  - 05/18/2024, 2:12:12 PM     LOG [MediaService] Successfully generated WEBP video thumbnail for asset b03b1111-3b19-4956-bd43-bf151d06186a


When hovering over the video thumbnail with mouse cursor:

immich_server            | [Nest] 7  - 05/18/2024, 2:14:00 PM    WARN [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
```
