### ISSUE TITLE
Android Asset Viewer UI Bug When Playing Video

### ISSUE THREAD

**Issue by Anguszzzzzzz** [immich-app/immich#9618]
### The bug

While "video looping" is enabled, playing any video on the mobile app results in incorrect UI:
- A "play" button is shown when the video is playing instead of a "pause" button
- Unable to pause video using the aforementioned button
- Progress bar doesn't correctly show video progress
- It's still possible to jump using the progress bar

https://github.com/immich-app/immich/assets/76796753/3d82f3d7-d64d-4050-a9be-2dfb944cc9d9

### The OS that Immich Server is running on

Windows 10 with Docker

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1 build.2140

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
      # - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: vaapi-wsl # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # - I:/Gallery/Camera:/mnt/media/old-media:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
      # - typesense
    privileged: true
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./config/model-cache:/cache
    env_file:
      - .env
    restart: always

  # typesense:
  #   container_name: immich_typesense
  #   image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
  #   environment:
  #     - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
  #     - TYPESENSE_DATA_DIR=/data
  #     # remove this to get debug messages
  #     - GLOG_minloglevel=1
  #   volumes:
  #     - tsdata:/data
  #   restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:80cc8518800438c684a53ed829c621c94afd1087aaeb59b0d4343ed3e7bcf6c5
    restart: always

  database:
    container_name: immich_postgres
    # image: postgres:14-alpine@sha256:50d9be76e9a90da4c781554955e0ffc79d9d5c4226838e64b36aacc97cbc35ad
    # image: tensorchord/pgvecto-rs:pg14-v0.1.11
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./config/pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
  # tsdata:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION="****"

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secrets for postgres and typesense. You should change these to random passwords
TYPESENSE_API_KEY=****
DB_PASSWORD=****

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

PUBLIC_LOGIN_PAGE_MESSAGE="****"
```

### Reproduction steps

```bash
1.Turn on "Looping" under Settings -> Asset Viewer -> Videos
2.Play a video
```
