### ISSUE TITLE
Unable to play GIF on mobile

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#9628]
### The bug

When viewing a GIF on Android, it's just a single frame and it doesn't play.

### The OS that Immich Server is running on

DSM 7.2

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

networks:
  # caddy:
  #   external: true
  #   name: caddy_default
  traefik:
    external: true
    name: traefik_proxy

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    networks:
      - traefik
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## HTTP Routers
      - traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)
      - traefik.http.routers.immich-rtr.entrypoints=https
      - traefik.http.routers.immich-rtr.tls=true
      - traefik.http.routers.immich-rtr.priority=10
      - traefik.http.routers.immich-rtr.service=immich-svc
      - traefik.http.routers.immich-rtr.middlewares=chain-basic@file
      - traefik.http.services.immich-svc.loadbalancer.server.port=3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    build:
      context: $DOCKERDIR/immich/immich-ml
      dockerfile: Dockerfile
    container_name: immich_machine_learning
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - default
    command: redis-server /etc/redis.conf
    volumes:
      - sockets:/sockets
      - $DOCKERDIR/immich/redis.conf:/etc/redis.conf
      - /etc/TZ:/etc/timezone:ro
      - $DOCKERDIR/immich/redisdb:/db

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    user: 1026:100
    command: postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      PGPORT: ${DB_PORT}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
      - sockets:/sockets
    restart: always

volumes:
  sockets:
    external: true
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=/sockets
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_PORT=5433
REDIS_PASSWORD="password"
REDIS_SOCKET=/sockets/immich_redis.sock
UPLOAD_LOCATION=$DOCKERDIR/immich/Gallerij
JWT_SECRET=secret
TYPESENSE_API_KEY=apikey
```

### Reproduction steps

```bash
1. Upload GIF
2. View GIF on mobile
3. See error
```
