### ISSUE TITLE
Unable to play (some) videos (again)

### ISSUE THREAD

**Issue by JVT038** [immich-app/immich#9666]
### The bug

When I try to play a video, I get a gray screen instead of the actual video.

I don't know if the cause of this issue is the same as #6897 (which I opened a couple of months ago), so if this is caused by the same thing, then I'll close this one and re-open the older one.

### The OS that Immich Server is running on

DSM 7.2

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1 build.2140

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

name: immich

networks:
  # caddy:
  #   external: true
  #   name: caddy_default
  traefik:
    external: true
    name: traefik_proxy

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "immich" ]
    networks:
      - traefik
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## HTTP Routers
      - traefik.http.routers.immich-rtr.rule=Host(`immich.$DOMAINNAME`)
      - traefik.http.routers.immich-rtr.entrypoints=https
      - traefik.http.routers.immich-rtr.tls=true
      - traefik.http.routers.immich-rtr.priority=10
      - traefik.http.routers.immich-rtr.service=immich-svc
      - traefik.http.routers.immich-rtr.middlewares=chain-basic@file
      - traefik.http.services.immich-svc.loadbalancer.server.port=3001

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    command: [ "start.sh", "microservices" ]
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - sockets:/sockets
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always
    devices:
      - /dev/dri:/dev/dri

  immich-machine-learning:
    build:
      context: $DOCKERDIR/immich/immich-ml
      dockerfile: Dockerfile
    container_name: immich_machine_learning
    networks:
      - default
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - model-cache:/cache
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always
    networks:
      - default
    command: redis-server /etc/redis.conf
    volumes:
      - sockets:/sockets
      - $DOCKERDIR/immich/redis.conf:/etc/redis.conf
      - /etc/TZ:/etc/timezone:ro
      - $DOCKERDIR/immich/redisdb:/db

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    user: 1026:100
    command: postgres -c unix_socket_directories='/var/run/postgresql/,/sockets/'
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
      PGPORT: ${DB_PORT}
    volumes:
      - $DOCKERDIR/immich/pgdata:/var/lib/postgresql/data
      - sockets:/sockets
    restart: always

volumes:
  sockets:
    external: true
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=/sockets
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_PORT=5433
REDIS_PASSWORD="password"
REDIS_SOCKET=/sockets/immich_redis.sock
UPLOAD_LOCATION=$DOCKERDIR/immich/Gallerij
JWT_SECRET=secret
TYPESENSE_API_KEY=apikey
```

### Reproduction steps

```bash
1. Upload video
2. Play video on Android
3. See error
```

### Relevant log output

```shell
05-22 18:31:04.473 11215 23641 D SurfaceUtils: connecting to surface 0xb400007dde92dc70, reason connectToSurface(reconnect)
05-22 18:31:04.476 11215 23642 E ACodec  : [OMX.qcom.video.decoder.avc] configureCodec returning error -12
05-22 18:31:04.476 11215 23642 E ACodec  : signalError(omxError 0x80001001, internalError -12)
05-22 18:31:04.478 11215 23641 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 3/CONFIGURING
05-22 18:31:04.478 11215 23641 D MediaCodec: flushMediametrics
05-22 18:31:04.478 11215 23641 D SurfaceUtils: disconnecting from surface 0xb400007dde92dc70, reason disconnectFromSurface
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.avc
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:   android.media.MediaCodec$CodecException: Error 0xfffffff4
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.media.MediaCodec.native_configure(Native Method)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.b.v(Unknown Source:14)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.b.p(Unknown Source:0)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.b$b.d(Unknown Source:68)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.k.a(Unknown Source:58)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.J0(Unknown Source:75)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.P0(Unknown Source:111)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.O0(Unknown Source:142)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.T0(Unknown Source:37)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at w4.h.T0(Unknown Source:0)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.c1(Unknown Source:21)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at p3.s.v(Unknown Source:28)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at y2.k1.p(Unknown Source:96)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at y2.k1.handleMessage(Unknown Source:220)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:288)
05-22 18:31:04.485 11215 23621 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer: Video codec error
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:   p3.s$b: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640032, -1, null, [1080, 1920, 59.95926], [-1, -1])
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.P0(Unknown Source:146)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.O0(Unknown Source:142)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.T0(Unknown Source:37)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at w4.h.T0(Unknown Source:0)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.c1(Unknown Source:21)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.v(Unknown Source:28)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at y2.k1.p(Unknown Source:96)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at y2.k1.handleMessage(Unknown Source:220)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:288)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_configure(Native Method)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.b.v(Unknown Source:14)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.b.p(Unknown Source:0)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.b$b.d(Unknown Source:68)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.k.a(Unknown Source:58)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.J0(Unknown Source:75)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       at p3.s.P0(Unknown Source:111)
05-22 18:31:04.486 11215 23621 E MediaCodecVideoRenderer:       ... 11 more
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal: Playback error
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:   y2.r: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640032, -1, null, [1080, 1920, 59.95926], [-1, -1]), format_supported=YES
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at y2.k1.handleMessage(Unknown Source:344)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:   Caused by: p3.s$b: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, avc1.640032, -1, null, [1080, 1920, 59.95926], [-1, -1])
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.P0(Unknown Source:146)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.O0(Unknown Source:142)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.T0(Unknown Source:37)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at w4.h.T0(Unknown Source:0)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.c1(Unknown Source:21)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.v(Unknown Source:28)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at y2.k1.p(Unknown Source:96)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at y2.k1.handleMessage(Unknown Source:220)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       ... 4 more
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:   Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_configure(Native Method)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2176)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2092)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.b.v(Unknown Source:14)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.b.p(Unknown Source:0)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.b$b.d(Unknown Source:68)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.k.a(Unknown Source:58)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.J0(Unknown Source:75)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       at p3.s.P0(Unknown Source:111)
05-22 18:31:04.488 11215 23621 E ExoPlayerImplInternal:       ... 11 more
05-22 18:31:04.488 11215 23641 D MediaCodec: flushMediametrics
05-22 18:31:04.490 11215 23641 D MediaCodec: flushMediametrics
05-22 18:31:04.493 11215 11242 I flutter : Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
05-22 18:31:04.493 11215 11242 I flutter : [SEVERE] [2024-05-22 18:31:04.493957] FlutterError - Catch all
```

### Additional information

Screenshot of error:

![image](https://github.com/immich-app/immich/assets/47184046/6d0cddc8-2181-40c1-9465-0843f6669d9d)
