### ISSUE TITLE
Manually Setting Location Occasionally Displays Wrong City/State

### ISSUE THREAD

**Issue by bitbytenybble110** [immich-app/immich#9674]
### The bug

On certain images with no geolocation data, manually setting the location on the map results in the wrong city/state being displayed.

This wrong location is shown on both mobile and web.

Two screenshots are included demonstrating this behavior.

The first is selecting the precise location of the image.  New York City, NY  
![image](https://github.com/immich-app/immich/assets/12929123/def65f67-6f07-4f3f-b242-b5a359f1b7d4)

The second shows that the map resolves this location as Hoboken, NJ.  This is wrong.  
![image](https://github.com/immich-app/immich/assets/12929123/dd0f0580-86d7-4def-86ea-e040bf682fbb)

### The OS that Immich Server is running on

Ubuntu 22.04 - Docker

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0 build.157

### Platform with the issue

- [X] Server
- [X] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8088:3001
    depends_on:
      - redis
      - database
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
    deploy:
      placement:
        constraints: [node.labels.zwave.hardware != true]

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - redis
      - database
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
    deploy:
      placement:
        constraints: [node.labels.zwave.hardware != true]

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    restart: always
    deploy:
      placement:
        constraints: [node.labels.zwave.hardware != true]

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: always
    deploy:
      placement:
        constraints: [node.labels.zwave.hardware != true]

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
    restart: always
    deploy:
      placement:
        constraints: [node.labels.zwave.hardware != true]

volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/opt/immich//library
IMMICH_VERSION=release
DB_PASSWORD=[redacted]
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
PG_DATA=/opt/immich/db
```

### Reproduction steps

```bash
1.  Upload an image with no geolocation data.
2.  Set the location of this image manually on Manhattans west side.
3.  The reported location appears as Hoboken.
```
