### ISSUE TITLE
Metrics generation error for microservice

### ISSUE THREAD

**Issue by zigarn** [immich-app/immich#9759]
### The bug

When calling the metrics endpoint on microservices, instead of metrics we get
```
# failed to export metrics: Error: MetricReader is not bound to a MetricProducer
```

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

N/A

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
# Immich provided one + this compose.override.yml

services:
  immich-server:
    volumes:
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
    ports: !override
      - 127.0.0.1:2283:3001
      - 127.0.0.1:2284:8081

  immich-microservices:
    volumes:
      - ${EXTERNAL_PATH}:/usr/src/app/external:ro
    ports:
      - 127.0.0.1:2285:8081

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:0db8::/112
```

### Your .env content

```Shell
# Immich provided one +

# Custom
###################################################################################
# External library path
EXTERNAL_PATH=/home/user/Images/Photos

# Connection secret for postgres
DB_PASSWORD='...'

# Monitoring
IMMICH_METRICS=true
```

### Reproduction steps

```bash
1. `curl http://localhost:2285/metrics`
2. Get no metrics but error message
```

### Relevant log output

```shell
Nothing about metrics in the logs
```

### Additional information

Metrics endpoint for server is OK.
