### ISSUE TITLE
Videos are unplayable

### ISSUE THREAD

**Issue by milouk** [immich-app/immich#9766]
### The bug

Video are unplayable. In console i get the following:

<img width="627" alt="Screenshot 2024-05-26 at 12 28 05" src="https://github.com/immich-app/immich/assets/22796276/e6034ac2-3065-4276-8ee2-6b5cb8aea15b">

and when i hover over a video i get this red exclamation mark

<img width="147" alt="Screenshot 2024-05-26 at 12 31 37" src="https://github.com/immich-app/immich/assets/22796276/e3f46434-2f2a-4393-b9a7-75a16517ff37">

** It used to work just fine sometime ago

### The OS that Immich Server is running on

Debian Bookworm

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0 build.139

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
immich-server:
    <<: *common-keys-core
    container_name: immich_server
    image: altran1502/immich-server:release
    command: [ "start.sh", "immich" ]
    ports:
      - 8081:8081
    volumes:
      - /mnt/media:/usr/src/app/upload
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
      - redis
      - database
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.22
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.services.immich-server.loadbalancer.server.port=3001
      - traefik.http.routers.immich-server-https.entrypoints=https
      - traefik.http.routers.immich-server-https.rule=Host(`${IMMICH_HOST}`)
      - traefik.http.routers.immich-server-https.tls=true
      - traefik.http.routers.immich-server-https.middlewares=chain-middlewares-no-auth@file


  immich-microservices:
    <<: *common-keys-core
    container_name: immich_microservices
    image: altran1502/immich-server:release
    command: [ "start.sh", "microservices" ]
    devices:
      - /dev/dri:/dev/dri  # If using Intel QuickSync or VAAPI
    volumes:
      - /mnt/media:/usr/src/app/upload
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
      - redis
      - database
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.23
    labels:
      - com.centurylinklabs.watchtower.enable=true


  immich-machine-learning:
    <<: *common-keys-core
    container_name: immich_machine_learning
    image: altran1502/immich-machine-learning:release
    volumes:
      - /data/immich/model-cache:/cache
    env_file:
      - ./immich/immich.env
    depends_on:
      - pihole
    dns:
      - 10.1.0.6
    networks:
      private-network:
        ipv4_address: 10.1.0.24
    labels:
      - com.centurylinklabs.watchtower.enable=true


  redis:
    <<: *common-keys-core
    container_name: immich_redis
    image: redis:6.2-alpine
    networks:
      private-network:
        ipv4_address: 10.1.0.26
    labels:
      - com.centurylinklabs.watchtower.enable=true
  

  database:
    <<: *common-keys-core
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    env_file:
      - ./immich/immich.env
    volumes:
      - /data/immich/pgdata:/var/lib/postgresql/data
    networks:
      private-network:
        ipv4_address: 10.1.0.27
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

### Your .env content

```Shell
IMMICH_VERSION=release
IMMICH_METRICS=true
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
UPLOAD_LOCATION=./library
DB_PASSWORD=postgres
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=Europe/Athens
```

### Reproduction steps

```bash
1. Open web library
2. Try to play a video
```

### Additional information

In mobile it works just fine
