### ISSUE TITLE
No photos displayed after naming a person in Photo view

### ISSUE THREAD

**Issue by jtruland** [immich-app/immich#9774]
### The bug

After naming a person in a photo detail view, clicking the back arrow to return to the All Photos view results in a blank library display.  Refresh of the page resolves the issue, but does not return to the previous location in the library, unlike clicking the back arrow when not adding a name.

![Screenshot 2024-05-26 160646](https://github.com/immich-app/immich/assets/37846824/308051e8-6525-417c-b932-179bd9dd3fc9)

### The OS that Immich Server is running on

Debian 11

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

NA

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    ports:
      - 2283:3001
    networks:
      - rp_network
      - default
    depends_on:
      - redis
      - database

    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - model-cache:/cache
    env_file:
      - stack.env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:b6124ab2e45cc332e16398022a411d7e37181f21ff7874835e0180f56a09e82a
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - stack.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always


  backup:
    container_name: immich_db_dumper
    image: prodrigestivill/postgres-backup-local:14
    env_file:
      - stack.env
    volumes:
      - /opt/immich_photos/db_backup:/backups
    environment:
      POSTGRES_HOST: database
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_NUM_KEEP: 7
      POSTGRES_EXTRA_OPTS: '--clean --if-exists'
      BACKUP_DIR: /backups
    depends_on:
      - database

volumes:
  pgdata:
  model-cache:
  db_backup:
  pgbackups_data:

networks:
  rp_network:
    external: true
```

### Your .env content

```Shell
UPLOAD_LOCATION=/opt/immich_photos/library
IMMICH_VERSION=release
TYPESENSE_API_KEY=
DB_PASSWORD=
DB_HOSTNAME=
DB_USERNAME=
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
TZ=America/New_York
```

### Reproduction steps

```bash
1. Click on photo with unnamed person
2. Edit person's name
3. Click back button to return to photo
4. Click back button to return to library view
```
