### ISSUE TITLE
Some photos do not appear in Immich on iOS

### ISSUE THREAD

**Issue by YannikBe** [immich-app/immich#9792]
### The bug

„Normal“ photos are not visible in immich. All videos, portrait photos, live photos and so on appear once the appropriate directory has been selected in the backup settings. There is no directory for non-special pictures, though. Those images can only be seen in the "Recents" category which would also include e.g. screenshots, though. I initially noticed this happening with photos taken on a DSLR which were airdropped to me. But upon further inspection I found that simply disabling live photos in the camera app and then clicking a normal picture would also do the trick. 

![IMG_1183](https://github.com/immich-app/immich/assets/57064400/dd912d26-f102-4e89-9f24-b4603b3b87f1)
![IMG_1184](https://github.com/immich-app/immich/assets/57064400/4c1b2332-d8d8-4266-b6f0-dfe94597d4e3)
![IMG_1185](https://github.com/immich-app/immich/assets/57064400/94de037b-d5de-4a14-a77c-6216b61c7c97)

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.105.0 build.157

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
# I don’t have access to a computer for a few weeks and had to format on my phone. I apologize for formatting errors!

version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION: -release} 
  command: [ "start.sh", "immich" ]
  volumes:
    - ${UPLOAD_LOCATION}: /usr/src/app/upload
    ﻿﻿-/etc/localtime:/etc/localtime:ro 
  env_file:
    - ﻿﻿.env 
  ports:
﻿﻿    - 2283:3001
  depends_on:
﻿﻿    - redis
    - ﻿﻿database
  restart: always

  immich-microservices:
    container_name: immich_microservices     
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION: -release}
    command: [ "start.sh", "microservices" ]     
    volumes:
      - ${UPLOAD_LOCATION}: /usr/src/app/upload
      - /etc/localtime: /etc/localtime:ro
    env_file：
      - .env
    depends_on:
﻿﻿      - redis
﻿﻿      - database
    restart: always

immich-machine-learning:
  container_name: immich_machine_learning 
  image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release} 
  volumes:
    - ﻿﻿model-cache: /cache 
  env_file:
﻿﻿    - .env
restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/media/immich-app/immich-data
IMMICH_VERSION=release
TYPESENSE_API_KEY=redacted
DB_PASSWORD=redacted
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Take one photo with Live Photo disabled on iPhone
2. Photo not available on immich unless recent photos have been selected
```
