### ISSUE TITLE
[BUG] Cannot login to Immich

### ISSUE THREAD

**Issue by PrzemekSkw** [immich-app/immich#980]
**Describe the bug**
Today I cannot login to my account and my other users account.

**Task List**

- [x] I have read thoroughly the README setup and installation instructions.
- [x] I have included my `docker-compose` file.
- [x] I have included my redacted `.env` file.
- [x] I have included information on my machine, and environment.

**Expected behavior**
Login to app.

**System**
- Phone OS: Android 12
- Server Version: docker-last
- Mobile App Version: `1.35.0`

**Additional context**
Cannot login on web browser too. Yesterday I install checkmk on my server.

docker-comopse:
```
version: "3.8"

services:
  immich-server:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  immich-web:
    image: altran1502/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: altran1502/immich-proxy:release
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

volumes:
  pgdata:
```
.env
```
###################################################################################
# Database
###################################################################################

DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

# Optional Database settings:
# DB_PORT=5432

###################################################################################
# Redis
###################################################################################

REDIS_HOSTNAME=immich_redis

# Optional Redis settings:
# REDIS_PORT=6379
# REDIS_DBINDEX=0
# REDIS_PASSWORD=
# REDIS_SOCKET=

###################################################################################
# Upload File Config
###################################################################################

UPLOAD_LOCATION=/mnt/samba/Immich/

###################################################################################
# Log message level - [simple|verbose]
###################################################################################

LOG_LEVEL=simple

###################################################################################
# JWT SECRET
###################################################################################

# This JWT_SECRET is used to sign the authentication keys for user login
# You should set it to a long randomly generated value
# You can use this command to generate one: openssl rand -base64 128
JWT_SECRET=xxxxxxxxxxx

###################################################################################
# Reverse Geocoding
####################################################################################

# DISABLE_REVERSE_GEOCODING=false

# Reverse geocoding is done locally which has a small impact on memory usage
# This memory usage can be altered by changing the REVERSE_GEOCODING_PRECISION variable
# This ranges from 0-3 with 3 being the most precise
# 3 - Cities > 500 population: ~200MB RAM
# 2 - Cities > 1000 population: ~150MB RAM
# 1 - Cities > 5000 population: ~80MB RAM
# 0 - Cities > 15000 population: ~40MB RAM

# REVERSE_GEOCODING_PRECISION=3

####################################################################################
# WEB - Optional
####################################################################################

# Custom message on the login page, should be written in HTML form.
# For example PUBLIC_LOGIN_PAGE_MESSAGE="This is a demo instance of Immich.<br><br>Email: <i>demo@demo.de</i><br>Password: <i>demo</i>"

PUBLIC_LOGIN_PAGE_MESSAGE="Nasze Rodzinne Zdjęcia"
```
Part of docker-comopse logs:
```
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [RoutesResolver] JobController {/jobs}: +1ms
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [RouterExplorer] Mapped {/jobs, GET} route +1ms
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [RouterExplorer] Mapped {/jobs/:jobId, GET} route +1ms
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [RouterExplorer] Mapped {/jobs/:jobId, PUT} route +1ms
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [NestApplication] Nest application successfully started +63ms
immich-server_1            | [Nest] 7  - 11/16/2022, 3:00:49 AM     LOG [ImmichServer] Running Immich Server in PRODUCTION environment - version 1.35.0
immich-server_1            | node:events:505
immich-server_1            |       throw er; // Unhandled 'error' event
immich-server_1            |       ^
immich-server_1            |
immich-server_1            | Error: getaddrinfo ENOTFOUND immich_redis
immich-server_1            |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
immich-server_1            | Emitted 'error' event on RedisAdapter instance at:
immich-server_1            |     at RedisClient.onError (/usr/src/app/node_modules/socket.io-redis/dist/index.js:65:22)
immich-server_1            |     at RedisClient.emit (node:events:527:28)
immich-server_1            |     at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:342:14)
immich-server_1            |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:223:14)
immich-server_1            |     at Socket.emit (node:events:527:28)
immich-server_1            |     at emitErrorNT (node:internal/streams/destroy:157:8)
immich-server_1            |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
immich-server_1            |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
immich-server_1            |   errno: -3008,
immich-server_1            |   code: 'ENOTFOUND',
immich-server_1            |   syscall: 'getaddrinfo',
immich-server_1            |   hostname: 'immich_redis'
immich-server_1            | }
immich-server_1            | [Nest] 7  - 11/16/2022, 6:35:09 AM     LOG [NestFactory] Starting Nest application...
immich-server_1            | [Nest] 7  - 11/16/2022, 6:35:09 AM     LOG [InstanceLoader] DatabaseModule dependencies initialized +156ms
immich-server_1            | [Nest] 7  - 11/16/2022, 6:35:09 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
immich-server_1            | [Nest] 7  - 11/16/2022, 6:35:09 AM     LOG [InstanceLoader] BullModule
```
When I redirect from Nginx Proxy Manager I don't see login screen but error page:

![Screenshot_2022-11-16-08-28-39-60_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/25219988/202115106-5bc7f7b6-63db-4a4c-a4f3-b5f50d8fa764.jpg)
on address `https://my site.org`
When it is  `https://my site.org/auth/login` I see normal login screen but cannot login.
Regards
