### ISSUE TITLE
[JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format

### ISSUE THREAD

**Issue by weiyideai520** [immich-app/immich#9839]
### The bug

I want to know what these errors mean.

Or rather, what do I need to do to eliminate these exceptions?
These exceptions occur every day.

### The OS that Immich Server is running on

Docker

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: 172.20.0.1

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      net:
        ipv4_address: 172.20.0.5
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    devices:
      - /dev/dri/:/dev/dri/
    command: ['start.sh', 'microservices']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      net:
        ipv4_address: 172.20.0.6
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - /volume1/Docker/immich/machine/model-cache:/cache
    env_file:
      - .env
    networks:
      net:
        ipv4_address: 172.20.0.3
    restart: always

  redis:
    container_name: immich_redis
    image: library/redis:6.2-alpine@sha256:84882e87b54734154586e5f8abd4dce69fe7311315e2fc6d67c29614c8de2672
    networks:
      net:
        ipv4_address: 172.20.0.2
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    networks:
      net:
        ipv4_address: 172.20.0.4
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/share/Docker/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/share/Docker/immich/postgres

# General
TZ=Asia/Shanghai
HF_ENDPOINT=https://hf-mirror.com

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=postgres

# Machine Learning
MACHINE_LEARNING_WORKER_TIMEOUT=1800

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
Handle it in the background
```

### Relevant log output

```shell
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "ef9aa408-c24a-4335-8018-bbdb8c99aac5"
}
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "871b03f7-f94f-4cc3-8be3-686dbb8e82d3"
“id”： “871b03f7-f94f-4cc3-8be3-686dbb8e82d3”
}
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "626abe5a-1620-4eef-898d-c3698da75d26"
}
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "9f767b24-15c3-4170-af5a-fc7b98e122da"
}
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "25994e31-13f3-4f0a-aaee-fee1e9490fbb"
}
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Unable to run job handler (thumbnailGeneration/generate-person-thumbnail): Error: Input file contains unsupported image format
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Error: Input file contains unsupported image format
    at Sharp.toFile (/usr/src/app/node_modules/sharp/lib/output.js:89:19)
    at MediaRepository.generateThumbnail (/usr/src/app/dist/repositories/media.repository.js:69:14)
    at PersonService.handleGeneratePersonThumbnail (/usr/src/app/dist/services/person.service.js:427:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/src/app/dist/services/job.service.js:145:36
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 6  - 05/29/2024, 12:00:10 AM   ERROR [ImmichMicroservices] [JobService] Object:
{
  "id": "caba0193-3b12-4a14-8bfa-90936a7001e5"
“id”： “CABA0193-3B12-4A14-8BFA-90936A7001E5”
}
[Nest] 6  - 05/29/2024, 12:00:47 AM    WARN [ImmichMicroservices] [PersonService] Face cee76ec4-6b7b-48eb-9a17-0ec550b73305 not found
[Nest] 6  - 05/29/2024, 12:00:47 AM    WARN [ImmichMicroservices] [PersonService] Face 005f43af-7cbf-481f-bd55-e00ec6dbc1ad not found
[Nest] 6  - 05/29/2024, 12:00:51 AM    WARN [ImmichMicroservices] [PersonService] Face b0ba2213-1a4c-47ca-b4b5-da9a37f3873c not found
[Nest] 6  - 05/29/2024, 12:00:51 AM    WARN [ImmichMicroservices] [PersonService] Face 87358a4e-3b95-4163-97f7-32e764dd1e2a not found
[Nest] 6  - 05/29/2024, 12:00:51 AM    WARN [ImmichMicroservices] [PersonService] Face ad9eb302-820a-4e51-b2c5-19b1a7a39135 not found
[Nest] 6  - 05/29/2024, 12:00:51 AM    WARN [ImmichMicroservices] [PersonService] Face 1cb8d004-a561-45ec-a5e4-28d135506691 not found
[Nest] 6  - 05/29/2024, 12:00:51 AM    WARN [ImmichMicroservices] [PersonService] Face 992d019a-b06a-4643-9515-67c56bd7af7d not found
[Nest] 6  - 05/29/2024, 12:01:15 AM    WARN [ImmichMicroservices] [PersonService] Face 72677fcb-d6dd-4fa3-afd5-eccd0c373ceb not found
[Nest] 6  - 05/29/2024, 12:01:16 AM    WARN [ImmichMicroservices] [PersonService] Face 7fec4696-5095-4a09-93ba-c3c5d95c0268 not found
[Nest] 6  - 05/29/2024, 12:01:16 AM    WARN [ImmichMicroservices] [PersonService] Face b1ef7c74-af64-4a0a-9720-4c7435d99952 not found
```
