### ISSUE TITLE
ML container in Docker Desktop throws errors and warnings

### ISSUE THREAD

**Issue by lockheed** [immich-app/immich#9911]
### The bug

I successfully started immich-machine-learning container on Windows 10 with Docker Desktop and connected it to an immich server on Linux, but when I add some photos the ML container start spewing out warnings and errors:
https://pastebin.com/raw/D20dxPf2

I don't know if related, but there's this bug report here: https://github.com/NVIDIA/nvidia-container-toolkit/issues/520
I doubt it's related because my Nvidia drivers are 522.xx.

### The OS that Immich Server is running on

 Windows 10, Nvidia drivers 552.44

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105

### Platform with the issue

- [X] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    # extends:
    #   file: hwaccel.ml.yml
    #   service: # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - c:\Docker\Immich\Cache:/cache
    restart: always
    ports:
      - 3003:3003
```

### Your .env content

```Shell
-
```

### Reproduction steps

```bash
1.
2.
3.
...
```

**Comment by schuhbacca** [comment]
According to the docs the driver version must be 535 or greater: https://immich.app/docs/features/ml-hardware-acceleration/#cuda

Please update and retry.

**Comment by lockheed** [comment]
My drivers are 552.44. 552.44 > 535.

**Comment by schuhbacca** [comment]
Can you also post your hwaccel file? Why is your hwaccel commented out in the compose you posted above?

**Comment by lockheed** [comment]
```
services:
  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-cuda
    extends:
       file: hwaccel.ml.yml
       service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - c:\Docker\immich-machine-learning\model-cache:/cache
    restart: always
    ports:
      - 3003:3003
```

```
version: "3.8"

# Configurations for hardware-accelerated machine learning

# If using Unraid or another platform that doesn't allow multiple Compose files,
# you can inline the config for a backend by copying its contents 
# into the immich-machine-learning service in the docker-compose.yml file.

# See https://immich.app/docs/features/ml-hardware-acceleration for info on usage.

services:
  armnn:
    devices:
      - /dev/mali0:/dev/mali0
    volumes:
      - /lib/firmware/mali_csffw.bin:/lib/firmware/mali_csffw.bin:ro # Mali firmware for your chipset (not always required depending on the driver)
      - /usr/lib/libmali.so:/usr/lib/libmali.so:ro # Mali driver for your chipset (always required)

  cpu: {}

  cuda:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  openvino:
    device_cgroup_rules:
      - "c 189:* rmw"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /dev/bus/usb:/dev/bus/usb

  openvino-wsl:
    devices:
      - /dev/dri:/dev/dri
      - /dev/dxg:/dev/dxg
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /usr/lib/wsl:/usr/lib/wsl
```
