### ISSUE TITLE
android app doesn't display local libraries

### ISSUE THREAD

**Issue by brettowe** [immich-app/immich#9913]
### The bug

I recently setup immich to try and see if I could have it replace google photos app.
I got setup and found that unless the local libraries are selected for backup does the images in those libraries show in the app.
having the libraries selected NOT for backup also doesn't display them.

my work flow is one of wanting to see all the items and then moving them to the correct album if they are worth sync'ing
I use the camera often for 'taking notes' so the pictures lifespan is typically less than a day

### The OS that Immich Server is running on

opensuse

### Version of Immich Server

1.105.1

### Version of Immich Mobile App

1.10.5 build 139

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
networks:
  im-backend:
    external: false
  pod-bridge:
    external: true

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'immich']
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      im-backend:
      pod-bridge:
        ipv4_address: 172.18.1.15
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ['start.sh', 'microservices']
    networks:
      im-backend:
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine
    restart: always
    networks:
      im-backend:

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
    networks:
      im-backend:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
```

### Your .env content

```Shell
# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/bulk/immich/library
# The location where your database files are stored
DB_DATA_LOCATION=/mnt/bulk/immich/postgres

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=yeap

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
DB_HOSTNAME=immich_postgres

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. install app
2. connect to server
3. nothing displayed unless select libraries to backup
```
