### ISSUE TITLE
Docker compose seems broken

### ISSUE THREAD

**Issue by felixschndr** [immich-app/immich#9922]
### The bug

When copying the example docker compose (https://github.com/immich-app/immich/blob/main/docker/docker-compose.yml) there are several problems:

1. The `name` and `start_interval` seem to be invalid
   ```
   ┌─[13:28:03]-[:)]-[felix@grievous]-[/home/felix/server/Immich/ (main)]
   └──> docker-compose up
   ERROR: The Compose file './docker-compose.yml' is invalid because:
   'name' does not match any of the regexes: '^x-'

   You might be seeing this error because you're using the wrong Compose file version. Either specify a 
   supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or 
   omit the `version` key and place your service definitions at the root of the file to use version 1.
   For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
   services.database.healthcheck value 'start_interval' does not match any of the regexes: '^x-'
   ```
2. After removing these parameters the `immich-server` does not start up
   ```
   ┌─[13:30:12]-[:(]-[felix@grievous]-[/home/felix/server/Immich/ (main)]
   └──> docker-compose up
   Creating network "immich_default" with the default driver
   Creating volume "immich_model-cache" with default driver
   Creating immich_machine_learning ... done
   Creating immich_redis            ... done
   Creating immich_postgres         ... done
   Creating immich_server           ... done
   Attaching to immich_redis, immich_machine_learning, immich_postgres, immich_server
   immich_postgres            |
   immich_postgres            | PostgreSQL Database directory appears to contain a database; Skipping    initialization
   immich_postgres            |
   immich_postgres            | 2024-06-01 11:30:14.674 UTC [1] LOG:  redirecting log output to logging    collector process
   immich_postgres            | 2024-06-01 11:30:14.674 UTC [1] HINT:  Future log output will appear in directory "log".
   redis_1                    | 1:C 01 Jun 2024 11:30:14.374 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
   redis_1                    | 1:C 01 Jun 2024 11:30:14.374 # Redis version=6.2.14, bits=64, commit=00000000, modified=0, pid=1, just started
   redis_1                    | 1:C 01 Jun 2024 11:30:14.374 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
   redis_1                    | 1:M 01 Jun 2024 11:30:14.376 * monotonic clock: POSIX clock_gettime
   redis_1                    | 1:M 01 Jun 2024 11:30:14.376 * Running mode=standalone, port=6379.
   redis_1                    | 1:M 01 Jun 2024 11:30:14.376 # Server initialized
   redis_1                    | 1:M 01 Jun 2024 11:30:14.377 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
   redis_1                    | 1:M 01 Jun 2024 11:30:14.377 * Ready to accept connections
   immich_server exited with code 0
   immich_machine_learning    | [06/01/24 11:30:17] INFO     Starting gunicorn 22.0.0
   immich_machine_learning    | [06/01/24 11:30:17] INFO     Listening at: http://[::]:3003 (9)
   immich_machine_learning    | [06/01/24 11:30:17] INFO     Using worker: app.config.CustomUvicornWorker
   immich_machine_learning    | [06/01/24 11:30:17] INFO     Booting worker with pid: 13
   immich_server exited with code 0
   immich_server exited with code 0
   immich_server exited with code 0
   immich_server exited with code 0
   immich_server exited with code 0
   ```
   I was not able to get any output of the `immich-server` container by setting the loglevel. It just finishes with code `0` and thats it.

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

Release (v.1.105.1)

### Version of Immich Mobile App

None

### Platform with the issue

- [x] Server
- [ ] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

# name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e31ca60b18f7e9b78b573d156702471d4eda038803c0b8e6f01559f350031e93
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      # start_interval: 30s
      # start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]
    restart: always

volumes:
  model-cache:
```

### Your .env content

```Shell
IMMICH_VERSION=release

DB_USERNAME=postgres
DB_PASSWORD=mysuperpassword
DB_DATABASE_NAME=immich

UPLOAD_LOCATION=./library

DB_DATA_LOCATION=./data/postgres
```

### Reproduction steps

```bash
Copy & paste the docker compose and env from the immich repo, run `docker-compose up`
```

### Relevant log output

```shell
None sadly
```
