### ISSUE TITLE
old people thumbnails broken after swiching to webp

### ISSUE THREAD

**Issue by heikomat** [immich-app/immich#9944]
### The bug

When [1.102.0](https://github.com/immich-app/immich/releases/tag/v1.102.) released, which introduced webp support for thumbnails and previews, i switched to webp.
I had issues with thumbnails and read https://github.com/immich-app/immich/issues/8981.
I deleted all jpeg files and reran about every job immich provides.

Most things work fine, but the thumbnails for people are not showing.
Logs show, that immich tries to load `.jpeg` files like this.
```
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [LoggerRepository] Unable to send file: Error
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/e5/24/e524e25a-fda9-4636-a5af-3e40d3f6ed40.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
```

If i look into that folder, a file with than name exists, but it has the (correct) `.webp` ending.

Interestingly enough, thumbnails of new people from photos from two weeks ago and yesterday do show up correctly.
When i look at the person-table, there is no entry with `.webp`-path (althouth there are thousands with `.jpeg`-path)
```sql
SELECT * FROM person WHERE "thumbnailPath" ilike '%.webp';

 id | createdAt | updatedAt | ownerId | name | thumbnailPath | isHidden | birthDate | faceAssetId
----+-----------+-----------+---------+------+---------------+----------+-----------+-------------
(0 rows)
```

In the code, i found a [`handlePersonMigration`](https://github.com/immich-app/immich/blob/d1135db8cf33901aee6449a6029480198099afa3/server/src/services/person.service.ts#L475-L484), which calls [`movePersonFile`](https://github.com/immich-app/immich/blob/d1135db8cf33901aee6449a6029480198099afa3/server/src/cores/storage.core.ts#L151-L163) which in turn uses [`getPersonThumbnailPath`](https://github.com/immich-app/immich/blob/d1135db8cf33901aee6449a6029480198099afa3/server/src/cores/storage.core.ts#L98-L100) as target-path.

getPersonThumbnailPath has the `.jpeg`-ending hardcoded. Could that be an issue?

How do i tell immich to update the paths of the thumbnails for the persons to webp?

### The OS that Immich Server is running on

Ubuntu 22.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"

services:
  server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
      # upload libraries
      - /quick-vault/main-storage/Bilder/smartphone-camera-roll:/usr/src/app/upload/library/heiko
      - /quick-vault/main-storage/Backups/<redacted>/smartphone/camera-roll:/usr/src/app/upload/library/<redacted>
      # external libraries
      - /quick-vault/main-storage/Bilder/Oer-Erkenschwicker\ bis\ 2018:/mnt/media/heiko/old-pics-til-2018:ro
      - /quick-vault/main-storage/Bilder/seit_2017:/mnt/media/heiko/albums-since-2017:ro
      - /fat-vault/Media/Backups/<redacted>/backup_hdd_<redacted>:/mnt/media/<redacted>/old-hdd:ro

    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`<redacted>`)

  microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      # upload libraries
      - /quick-vault/main-storage/Bilder/smartphone-camera-roll:/usr/src/app/upload/library/heiko
      - /quick-vault/main-storage/Backups/<redacted>/smartphone/camera-roll:/usr/src/app/upload/library/<redacted>
      # external libraries
      - /quick-vault/main-storage/Bilder/<redacted>\ bis\ 2018:/mnt/media/heiko/old-pics-til-2018:ro
      - /quick-vault/main-storage/Bilder/seit_2017:/mnt/media/heiko/albums-since-2017:ro
      - /fat-vault/Media/Backups/<redacted>/backup_hdd_<redacted>:/mnt/media/<redacted>/old-hdd:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    volumes:
      - ./immich-data/model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    image: redis:6.2-alpine
    volumes:
      - ./immich-data/redis:/data
    restart: always

  database:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always

networks:
  traefik:
    external: true
```

### Your .env content

```Shell
DB_HOSTNAME=database
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich
DB_DATA_LOCATION=./immich-data/pgdata

REDIS_HOSTNAME=redis

UPLOAD_LOCATION=/docker/immich/immich-data


TYPESENSE_API_KEY=some-random-text

PUBLIC_LOGIN_PAGE_MESSAGE=

IMMICH_WEB_URL=http://web:3000
IMMICH_SERVER_URL=http://server:3001
IMMICH_MACHINE_LEARNING_URL=http://machine-learning:3003

IMMICH_API_URL_EXTERNAL=https://<redacted>, http://192.168.178.20:2283, http://proxy:8080
```

### Reproduction steps

```bash
1. be on a version below 1.102.0
2. have people detected in the explore-page
3. upgrade to 1.102.0
4. switch thumbnails and previews from jpeg to webp
5. run necessary jobs to migrate thumbnails
--- optional
6. kill all jpegs as described in https://github.com/immich-app/immich/issues/8981
7. rerun more jobs
```

### Relevant log output

```shell
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [ExceptionsHandler] ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/5a/d2/5ad28af5-450b-42ec-83ec-5bec363d8b58.jpeg'
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/5a/d2/5ad28af5-450b-42ec-83ec-5bec363d8b58.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [LoggerRepository] Unable to send file: Error
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/e5/24/e524e25a-fda9-4636-a5af-3e40d3f6ed40.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [ExceptionsHandler] ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/e5/24/e524e25a-fda9-4636-a5af-3e40d3f6ed40.jpeg'
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/e5/24/e524e25a-fda9-4636-a5af-3e40d3f6ed40.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [LoggerRepository] Unable to send file: Error
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/d9/5f/d95f9dca-7310-4eee-9fa7-de8766b0c871.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM   ERROR [ImmichServer] [ExceptionsHandler] ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/d9/5f/d95f9dca-7310-4eee-9fa7-de8766b0c871.jpeg'
server-1                             | Error: ENOENT: no such file or directory, access 'upload/thumbs/cb765e07-ebd7-4903-a0c7-41598e43d1cf/d9/5f/d95f9dca-7310-4eee-9fa7-de8766b0c871.jpeg'
server-1                             |     at async access (node:internal/fs/promises:603:10)
server-1                             |     at async sendFile (/usr/src/app/dist/utils/file.js:51:9)
server-1                             |     at async PersonController.getPersonThumbnail (/usr/src/app/dist/controllers/person.controller.js:52:9)
server-1                             | [Nest] 7  - 06/02/2024, 12:48:30 PM    WARN [ImmichServer] [ExpressAdapter] Content-Type doesn't match Reply body, you might need a custom ExceptionFilter for non-JSON responses
```

### Additional information

- faces of people, that appeared first after the migration do show up
- could this hardcoded `.jpeg` in [`getPersonThumbnailPath`](https://github.com/immich-app/immich/blob/d1135db8cf33901aee6449a6029480198099afa3/server/src/cores/storage.core.ts#L98-L100) be the cause?
