### ISSUE TITLE
Removal of Microservices Container latest update

### ISSUE THREAD

**Issue by dwhitnall** [immich-app/immich#9957]
### The bug

No thumbnails and cant view new pics after update to 1.105.1 from 1.104.0

### The OS that Immich Server is running on

Ubuntu 24.04

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [X] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
name: immich

networks:
  web:
    external: true
  immich:
    external: true

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [cpu, nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
#    ports:
#      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always
    networks:
      web:
      immich:
    labels:
      traefik.enable: true
      traefik.docker.network: web
      traefik.http.routers.immich.rule: Host(`immich.***REDACTED***`)
      traefik.http.routers.immich.entrypoints: websecure
      traefik.http.routers.immich.middlewares: chain-no-auth-no-crowdsec@file
      traefik.http.routers.immich.tls.certresolver: letsencrypt
      traefik.http.services.immich.loadbalancer.server.port: 3001
      com.centurylinklabs.watchtower.monitor-only: true

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
      file: hwaccel.transcoding.yml
      service: vaapi # set to one of [cpu, nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    depends_on:
      - redis
      - database
    restart: always
    networks:
      immich:

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}-openvino
    extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
      file: hwaccel.ml.yml
      service: openvino # set to one of [cpu, armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    volumes:
      - model-cache:/cache
    env_file:
      - immich.env
    restart: always
    networks:
      immich:

  redis:
    container_name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:e31ca60b18f7e9b78b573d156702471d4eda038803c0b8e6f01559f350031e93
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    networks:
      immich:

  database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /home/docker/immich/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --dbname='${DB_DATABASE_NAME}' || exit 1; Chksum="$$(psql --dbname='${DB_DATABASE_NAME}' --username='${DB_USERNAME}' --tuples-only --no-align -->
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size>
    env_file:
      - immich.env
    restart: always
    labels:
      com.centurylinklabs.watchtower.monitor-only: true
    networks:
      immich:

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis

REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJyZWRpcy1zZW50aW5lbDEiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtc2VudGluZWwyIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6Im15bWFzd>

UPLOAD_LOCATION=/media/Pool/immich

DISABLE_REVERSE_GEOCODING=false
REVERSE_GEOCODING_PRECISION=3

PUBLIC_LOGIN_PAGE_MESSAGE=

IMMICH_WEB_URL=http://immich-web:3000
IMMICH_SERVER_URL=http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003
IMMICH_API_URL_EXTERNAL=http://localhost:3001
IMMICH_METRICS=true
IMMICH_VERSION=release
```

### Reproduction steps

```bash
1.Updated from v1.104.0 to v1.105.1 remove the microservices container
2.synced new photos from phone
3.no thumbnails or pics in the web app only grey boxes, click on the boxes and no pic comes up
4.Started microservices container and full functionality returned
```

### Additional information

I've recently updated from v1.104.0 to 1.105.1, I followed the new docker compose file and removed the microservices container and removed the command: [ "start.sh", "immich" ] line from my compose file.
The rest of the file is inline with the current version on here.  However when I spin up the containers the immich-server container dosen't seem to start so I put the command line back in and that fixed that issue.  But it fails to generate the thumbnails of any new pics, it accutally won't display any of the new pics even with clicked on, this is through the web app.
When I go into jobs and try to generate the thumbnails it never starts.
But when I put the microservices container back in the compose file and spin the containers all back up, it all works as expected.
I did have a quick read and aparently the microservices container was moved into the server container, is there anything else that need to be changed for it to work as expected.
