### ISSUE TITLE
APP login error

### ISSUE THREAD

**Issue by syge** [immich-app/immich#9958]
### The bug

![微信截图_20240603151444](https://github.com/immich-app/immich/assets/26926873/e1508977-147b-4a82-adc7-bb0636a7684a)
![微信图片_20240603151309](https://github.com/immich-app/immich/assets/26926873/0f0f5208-ea4f-4a10-b1b1-be3b22687cfa)
![微信图片_20240603151309](https://github.com/immich-app/immich/assets/26926873/7ea0cb12-3ce5-44e6-a689-f1cb917e1eca)

### The OS that Immich Server is running on

debian12

### Version of Immich Server

v1.105.0

### Version of Immich Mobile App

v1.105.0

### Platform with the issue

- [ ] Server
- [ ] Web
- [X] Mobile

### Your docker-compose.yml content

```YAML
version: "3.8"
services:
  immich-server:
    image: altran1502/immich-server:v1.105.0
    entrypoint: ["/bin/sh", "./start-server.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    ports:
      - 2283:3001
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    image: altran1502/immich-server:v1.105.0
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    image: altran1502/immich-machine-learning:v1.105.0
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
    depends_on:
      - database
    restart: always

  # immich-web:
  #   image: altran1502/immich-web:release
  #   entrypoint: ["/bin/sh", "./entrypoint.sh"]
  #   env_file:
  #     - stack.env
  #   restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    ports:
      - 15432:5432
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    restart: always
    command: ["postgres", "-c" ,"shared_preload_libraries=vectors.so", "-c", 'search_path="$$user", public, vectors', "-c", "logging_collector=on", "-c", "max_wal_size=2GB", "-c", "shared_buffers=512MB", "-c", "wal_compression=on"]

  # immich-proxy:
  #   container_name: immich_proxy
  #   image: altran1502/immich-proxy:release
  #   ports:
  #     - 2283:8080
  #   logging:
  #     driver: none
  #   depends_on:
  #     - immich-server
  #   restart: always
volumes:
  model-cache:
```

### Your .env content

```Shell
UPLOAD_LOCATION=/opt/immich_data/upload_location
DB_DATA_LOCATION=/opt/immich_data/db_data_location
IMMICH_VERSION=release
DB_PASSWORD=postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich
```

### Reproduction steps

```bash
1.
2.
3.
...
```
