### ISSUE TITLE
Slideshow has problems loading images after running for a while

### ISSUE THREAD

**Issue by midiwidi** [immich-app/immich#9991]
### The bug

The issue described below was previously posted as discussion #9340. As I have more data and evidence for it now I'm opening an issue so that it can be tracked an maybe fixed.

**The Problem**
I made an album containing all my images and videos (>5000). On my tablet I run a slideshow of this album (shuffled order) in the Fully Kiosk Browser to mimic a photo frame.
This works well but after running for many hours the images don't load anymore. I only get a black screen with a spinner indicating that the image is loading. Interestingly the videos still work. Every now and then when the slideshow gets to a video it is played but after that it goes back to a black screen with a spinner trying to load the next image.

Since I first encountered the issue I have changed from the Fully Kiosk Browser to Chrome and to the Kiwi Browser which is based on Chrome. Both show the identical behaviour to what I have experienced with the Fully Kiosk Browser. After the Immich slideshow is running for a while (sometimes it only takes some hours but at other times it takes over a day) it stops showing images and I get just a black screen with a spinner. Interestingly, if the current content is a video then it is shown but not the images. I connected the tablet via USB and was able to remotely debug Chrome / Kiwi from my PC.
Here is a screenshot
![335881781-c54e61ec-88f3-49f0-a8c6-c8cb79fc2935](https://github.com/immich-app/immich/assets/54610151/19f79566-1f48-4865-a643-6905f93932d2)
The network traffic tab shows the attempts to pull images every 10s. The long bar in the waterfall window is from when a video was shown instead of images.
I have saved the traffic from the network tab as a *.har file which you can investigate using Chrome.
[immich_slideshow_kiwi_errorstate.zip](https://github.com/user-attachments/files/15526030/immich_slideshow_kiwi_errorstate.zip)
I also saved the error messages from the console window
[immich_slideshow_kiwi_errorstate_console.log](https://github.com/user-attachments/files/15526047/immich_slideshow_kiwi_errorstate_console.log)
I hope this helps to identify what the problem is. Please let me know if you need more information.

### The OS that Immich Server is running on

Debian 12

### Version of Immich Server

v1.105.1

### Version of Immich Mobile App

v1.105.1

### Platform with the issue

- [ ] Server
- [X] Web
- [ ] Mobile

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine@sha256:afb290a0a0d0b2bd7537b62ebff1eb84d045c757c1c31ca2ca48c79536c0de82
    restart: always

  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
  model-cache:
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables

# The location where your uploaded files are stored
UPLOAD_LOCATION=/mnt/ssd_verbatim/immich_data

# The Immich version to use. You can pin this to a specific version like "v1.71.0"
IMMICH_VERSION=release

# Connection secret for postgres. You should change it to a random password
DB_PASSWORD=...

# The values below this line do not need to be changed
###################################################################################
DB_HOSTNAME=immich_postgres
DB_USERNAME=postgres
DB_DATABASE_NAME=immich

REDIS_HOSTNAME=immich_redis
```

### Reproduction steps

```bash
1. Create an album and add a big amount of images and videos (I don't know if the number of images matters)
2. Go to the album and start a slideshow
3. Wait for a long period of time
```
